### ISSUE TITLE
Add "joist" to bad text in multiple common code repos

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#1004]
From discussion around https://github.com/phetsims/tambo/issues/126#issuecomment-765658077.

This will likely have to wait on a fair number of issues to complete that decouples things first:

https://github.com/phetsims/tambo/issues/126#issuecomment-765658077
https://github.com/phetsims/joist/issues/685
https://github.com/phetsims/joist/issues/686
(insert issues about passing phet.joist.display to TAMBO/DisplayedProperty)

on-hold until then.

**Comment by zepumph** [comment]
I finally got around to this today. It looks like there were about 5 places that could have failed if run outside of phetsims, and I was able to clean up other usages, exchanging `hasIn` with `get`.

The best part of this for me is the new lint config called `phet-library_eslintrc.js`, this is a spot that we can use to create failure points when common libraries don't adhere to the open-source conventions we decide on. @samreid will you please review, especially in ReadOnlyProperty and AnimatedPanZoomListener.

**Comment by samreid** [comment]
I reviewed the commits and this is a good improvement, thanks! It made me wonder if we want to move these joistlike model attributes like `localeProperty` and `isSettingPhetioStateProperty` to a library that exists for common code. Perhaps in axon or maybe `isSettingPhetioStateProperty` would be in Tandem?  What do you think?

**Comment by zepumph** [comment]
I could see that as a reasonable path forward, though I do not think that it is worth it for the i18n stuff. In part I like code that guards around this gracefully, because that helps in understanding that this part of a common code element is actually a phet-sim-specific implementation, and most likely not important to the component itself for more general use. I created https://github.com/phetsims/tandem/issues/294, any other thoughts?

**Comment by samreid** [comment]
That sounds reasonable to me, ready to close?
