### ISSUE TITLE
phet-io overrides are set on `preloads`

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#1008]
I found a bug in how the default overrides file is generated in chipper. It still points to `phet.phetio.phetioElementsOverrides` even though it is now `phet.preloads.phetio.phetioElementsOverrides`. There are a couple usages I will remove.

Discovered while working on https://github.com/phetsims/ratio-and-proportion/issues/351

**Comment by zepumph** [comment]
@samreid please review.

**Comment by samreid** [comment]
Looks good, thanks!  I didn't see any other occurrences that need to change.  Closing.
