### ISSUE TITLE
Move new-cap to general rules from formatting ones

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#1010]
See https://github.com/phetsims/phet-info/issues/150, where formatting rules were created. This rule seems like it belongs in the general rules though, since it is hard to auto-fix.

**Comment by zepumph** [comment]
@samreid does this seem reasonable to you?

**Comment by samreid** [comment]
This issue is so reasonable, it inspired this comment: https://github.com/phetsims/phet-info/issues/150#issuecomment-785322855

I confirmed that new-cap correctly flags problems in the IDE, and that `grunt lint-everything --disable-eslint-cache` didn't show any problems on active-repos.  Closing.
