### ISSUE TITLE
'grunt build' is failing for newly-created sim

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#1011]
This was reported in the Google Group in [this thread](https://groups.google.com/accounts/SetOSID?authuser=0&continue=https%3A%2F%2Fgroups.google.com%2Fd%2Ftopic%2Fdeveloping-interactive-simulations-in-html5%2FcS8WqHpBcBs%3Fpli%3D1%26authuser%3D0&osidt=ALWU2cs1AXPT-Eparnn0HIQwCU8uWTdJpfVzGAob2A_NMGvUgFij0m8mZ2OXBv0S6kKevr7ellx7owGhR8TrV8Zr3hhhg9wRdnf4Sqk0s-zivDaca7AJd2aDOX6H7D1pezNiOS95wZO79n0XvonPYnyAICRcQ5Rxdy-fhhr9qq39bcQ0Nz-GFbFPlaxNYcnPw63wD3erDnH9jBy8zQJ7NKE7NNHuZg-YxA), and I have verified.

```
% pull-all.sh
% cd perennial
% npm prune
% npm update
% cd chipper
% npm prune
% npm update
% cd perennial
% grunt create-sim accelerator-lab --author=CM --title="Acceleration Lab"
// confirmed that the created sim runs unbuilt, then...
% cd create-sim accelerator-lab
% grunt build --brands=phet
Running "build" task
Building runnable repository (acceleration-lab, brands: phet)
Building brand: phet
>> Webpack build complete: 1688ms
Fatal error: Perennial task failed:
Error: git rev-parse HEAD in ../acceleration-lab failed with exit code 128 and stdout:

  at ChildProcess.<anonymous> (/Users/cmalley/PhET/GitHub/chipper/js/grunt/execute.js:77:17)
  at ChildProcess.emit (events.js:315:20)
  at maybeClose (internal/child_process.js:1048:16)
  at Socket.<anonymous> (internal/child_process.js:439:11)
  at Socket.emit (events.js:315:20)
  at Pipe.<anonymous> (net.js:673:12)

Full Error details:
Error: git rev-parse HEAD in ../acceleration-lab failed with exit code 128 and stdout:
```

When this is fixed, please reply to the Google Group thread linked above.

**Comment by jonathanolson** [comment]
It looks like we're expecting it to be a git repository! Looking into it.

**Comment by jonathanolson** [comment]
I've internally null-ed out non-git repo sha/branches, which would be put in dependencies.json. This should be compatible with what we're doing. Closing (I'll reply to the google group).
