### ISSUE TITLE
prefer "readonly" to false for globals

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#1017]
From https://github.com/NickCrews/chipper/commit/f69e8fd7097e811a302f71e98b226d4e11adca21. It would be nice to be consistent in any non chipper use of globals too.

**Comment by zepumph** [comment]
Thanks for the tip @NickCrews!

**Comment by NickCrews** [comment]
Oh awesome, I was about to go through all the repos and fix this, nice job getting to it!
