### ISSUE TITLE
Speed up macro API generation

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1019]
From https://github.com/phetsims/phet-io/issues/1733#issuecomment-790034059

> try to improve the efficiency. This could be done by (a) A better pattern for parallelism, that doesn't require all elements of a batch to finish

Right now, we are using `Promise.all` with with lodash chunking, which has the disadvantage that each chunk must completely finish before it goes to the next chunk.  This process took around 1m8.336s on my machine.

* @zepumph indicated the https://caolan.github.io/async/ library may be useful.
* There is also a puppeteer cluster which may help: https://github.com/thomasdondorf/puppeteer-cluster
* We could also try other "outside the box" strategies such as getting our sims to "run" in node (at least enough to compute phet-io metadata), but this sounds sketchy
* We could also focus on speeding up sim launching in general
* We could also focus on speeding up sim launching when generating phet-io metadata (for instance, maybe we can skip some rendering work).

My current opinion is that 1m8s is acceptable and does not warrant much more investigation.  @zepumph how long is this process taking on your machine?  I got my results by running:

```
cd chipper
time node js/phet-io/output-macro-api.js --simList=../perennial/data/phet-io
```

**Comment by zepumph** [comment]
```
real    2m17.060s
```

**Comment by samreid** [comment]
If I run with a chunkSize of 1, it takes `1m37.121s` on my machine.  Assuming we have 4 cores available, no overhead, and perfect scheduling, we could potentially reduce this to 97/4 = 25s or so (on my machine).  The other question to consider in how much time to spend optimizing this, in how often it will be run.  Keep in mind https://github.com/phetsims/phet-io/issues/1741 where it was proposed that this could also run on CT as part of every column.  If all team members are encouraged to run this many times a day, then faster will be better.  But if we are choosing between 1 vs 2 minutes, that may not be a big deal.

**Comment by samreid** [comment]
> If all team members are encouraged to run this many times a day, then faster will be better

Or (for a while), we could run it on a subset of sims (say, the 4 most recent phet-io sims), then we can run it all in one chunk.  This may be fast enough for a precommit hook?

**Comment by samreid** [comment]
I tested and there is almost no overhead on starting a server (3ms) vs around 3000ms to start up a puppeteer.

**Comment by zepumph** [comment]
Today we again discussed and decided that this is not needed right now (especially with the creation of the subset list: phet-io-api-stable), but one day, when there are many more sims, we may decide to optimize this.

**Comment by samreid** [comment]
Maybe when we investigate this again, puppeteer will have native support for clustering.  Unassigning for now.

**Comment by zepumph** [comment]
I recommend that we close this issue and open a new one when the speed of API generation is prohibitively expensive. A year later, this is still a reasonable number.
