### ISSUE TITLE
Move the ES6 lint rules into the primary file

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1020]
During https://github.com/phetsims/chipper/issues/814 I found that many important lint rules are in chipper/eslint/sim_es6_eslintrc.js which are being ignored in many of our repos.  This means for instance, there are many places in our code that are using var where they should be using let/const.

I recommend moving as many of those rules to the primary file as possible.  Pinging @zepumph so he's aware of this, since he helped write the first version of sim_es6_eslintrc.js.

**Comment by zepumph** [comment]
Yes I agree, we no longer need these to be separate rules.

**Comment by samreid** [comment]
Once this is changed, developers will need to point their IDE at the new file:

![image](https://user-images.githubusercontent.com/679486/110886652-3b89ca00-82a6-11eb-90d0-c8a3e0c6dce8.png)

**Comment by zepumph** [comment]
Since changing eslint to use the tree stucture, which involved adding eslintConfig to every package.json, it is best to do an automatic search, like so:

![image](https://user-images.githubusercontent.com/6856943/110887173-4ccada80-8296-11eb-961d-3ca3c5abb19a.png)

**Comment by samreid** [comment]
Thanks, that is very helpful!

**Comment by samreid** [comment]
This change was more invasive than I expected, particularly because there were so many `var` declarations in our code.  I opened https://github.com/phetsims/chipper/issues/1021 to help with that.  Everything is passing local aqua so far.  Developers will need to make sure their IDE is set up like https://github.com/phetsims/chipper/issues/1020#issuecomment-797206498 (maybe most developers already had that set, but I did not).

@zepumph can you spot check this when you have time?

**Comment by samreid** [comment]
I messaged CT:

> As part of lint upgrades, I moved the “sim es6 lint” rules into our main lint file.  Things are passing local aqua, but this was an invasive change and I would expect CT to catch something I missed.  Please see https://github.com/phetsims/chipper/issues/1020 for context.  You may also need to update your IDE as described in https://github.com/phetsims/chipper/issues/1020#issuecomment-797206498 if you haven’t done so previously.

Also, perhaps this should block publication until at least a spot check and a round of CT have completed.

**Comment by zepumph** [comment]
This is awesome. Good work.

**Comment by samreid** [comment]
Thanks, closing.
