### ISSUE TITLE
Remove as many // eslint-disable-line no-var as possible

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1021]
From https://github.com/phetsims/chipper/issues/1020, I found many occurrences where `var` hoisting was leveraged.  I marked nontrivial ones with `// eslint-disable-line no-var` so I could turn the rule on everywhere else, but it seems we should change some/most/all of these.

There were 2 main categories:
1. `var` used in switch/case statements (see balancing-act/js/game/view/BalanceGameView.js for an example)
2. `var` used for hoisting (see vegas/js/FiniteStatusBar.js for an example)

The switch/case vars didn't bother me too much (though I typically don't use switch/case myself), but the hoisting ones mostly seemed awkward/confusing/tricky.

There are around 80 cases total at the moment.

**Comment by zepumph** [comment]
From dev meeting today, we decided that both the above cases of `var` usage is less clear than using `let`/`const`. Let's get rid of all these usages. You can find them by searching for `// eslint-disable-line no-var`.



- [ ] area-builder (1) @jbphet
- [ ] balancing-act (1) @jbphet 
- [ ] build-a-molecule (1)  @jonathanolson 
- [ ] dot (5) @jonathanolson 
- [ ] equality-explorer (10) @pixelzoom 
- [ ] expression-exchange (2) @jbphet 
- [ ] gene-expression-essentials (1) @jbphet
- [ ] isotopes-and-atomic-mass (1) @jbphet 
- [ ] joist (1) @zepumph  
- [ ] kite (14) @jonathanolson 
- [ ] masses-and-springs (1) @chrisklus 
- [ ] neuron (3) @jbphet 
- [ ] phet-io-wrapper-classroom-activity (1) @zepumph 
- [ ] phet-io-wrapper-lab-book (1) @zepumph 
- [ ] projectile-motion (21) @zepumph 
- [ ] scenery-phet (1) @pixelzoom 
- [ ] scenery (3) @jonathanolson 
- [ ] shred (1) @zepumph 
- [ ] states-of-matter (5) @jbphet 
- [ ] trig-tour (1) @jessegreenberg 
- [ ] vegas (4) @jbphet

**Comment by zepumph** [comment]
Completed my sims.

**Comment by jbphet** [comment]
I've replaced all usages of `var` in sims for which I'm the responsible dev, as listed in the checklist above.  I'm unassigning myself.

**Comment by jbphet** [comment]
I fixed the ones that were in my repos, listed in https://github.com/phetsims/chipper/issues/1021#issuecomment-830069352.  Two were cases that had been fixed but the comment wasn't removed, the other had just been missed I guess.

@samreid - I think we're done here, but thought I'd run it by you to double check.  Are we good to close?

**Comment by samreid** [comment]
Looks great, thanks everyone! Closing.
