### ISSUE TITLE
How to deal with API changes during incremental development

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#1023]
The error below is showing up in CT for graphing-quadratics, reported in https://github.com/phetsims/graphing-quadratics/issues/150. I'm guessing it's related to phetioCompareAPIs.js.  graphing-quadratics is in the process of being revised, and it is known (and desired) that the API is changing.  So this is not helpful, it's annoying.

What is the process for dealing with this during incremental development, or when there's a known/desired API change?  Please describe here, and document in the appropriate PhET-iO doc.

```
graphing-quadratics : phet-io-api-compatibility : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/graphing-quadratics/graphing-quadratics_en.html?continuousTest=%7B%22test%22%3A%5B%22graphing-quadratics%22%2C%22phet-io-api-compatibility%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1616082139562%22%2C%22timestamp%22%3A1616083270647%7D&ea&brand=phet-io&phetioStandalone&phetioCreateArchetypes&phetioCompareAPI
Query: ea&brand=phet-io&phetioStandalone&phetioCreateArchetypes&phetioCompareAPI
Uncaught Error: Assertion failed: Breaking API changes detected, please roll them back or revise the reference API:

graphingQuadratics.focusAndDirectrixScreen.view.focusManipulator.visibleProperty.phetioTypeName changed from PropertyIO<BooleanIO> to DerivedPropertyIO<BooleanIO>
graphingQuadratics.focusAndDirectrixScreen.view.vertexManipulator.visibleProperty.phetioTypeName changed from PropertyIO<BooleanIO> to DerivedPropertyIO<BooleanIO>
graphingQuadratics.standardFormScreen.view.noRealRootsNode.visibleProperty.phetioTypeName changed from PropertyIO<BooleanIO> to DerivedPropertyIO<BooleanIO>
graphingQuadratics.standardFormScreen.view.rootsNode.visibleProperty.phetioTypeName changed from PropertyIO<BooleanIO> to DerivedPropertyIO<BooleanIO>
graphingQuadratics.standardFormScreen.view.vertexNode.visibleProperty.phetioTypeName changed from PropertyIO<BooleanIO> to DerivedPropertyIO<BooleanIO>
graphingQuadratics.vertexFormScreen.view.vertexManipulator.visibleProperty.phetioTypeName changed from PropertyIO<BooleanIO> to DerivedPropertyIO<BooleanIO>
Error: Assertion failed: Breaking API changes detected, please roll them back or revise the reference API:

graphingQuadratics.focusAndDirectrixScreen.view.focusManipulator.visibleProperty.phetioTypeName changed from PropertyIO<BooleanIO> to DerivedPropertyIO<BooleanIO>
graphingQuadratics.focusAndDirectrixScreen.view.vertexManipulator.visibleProperty.phetioTypeName changed from PropertyIO<BooleanIO> to DerivedPropertyIO<BooleanIO>
graphingQuadratics.standardFormScreen.view.noRealRootsNode.visibleProperty.phetioTypeName changed from PropertyIO<BooleanIO> to DerivedPropertyIO<BooleanIO>
graphingQuadratics.standardFormScreen.view.rootsNode.visibleProperty.phetioTypeName changed from PropertyIO<BooleanIO> to DerivedPropertyIO<BooleanIO>
graphingQuadratics.standardFormScreen.view.vertexNode.visibleProperty.phetioTypeName changed from PropertyIO<BooleanIO> to DerivedPropertyIO<BooleanIO>
graphingQuadratics.vertexFormScreen.view.vertexManipulator.visibleProperty.phetioTypeName changed from PropertyIO<BooleanIO> to DerivedPropertyIO<BooleanIO>
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/assert/js/assert.js:25:13)
at XMLHttpRequest.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616082139562/phet-io/js/phetioEngine.js:264:23)
id: Bayes Chrome
Snapshot from 3/18/2021, 9:42:19 AM
```

**Comment by samreid** [comment]
You can update the reference api via:

```
cd graphing-quadratics
grunt generate-phet-io-api
```

Then review and commit the file.

You can opt out of this testing by removing the sim from perennial/data/phet-io-api-stable

**Comment by pixelzoom** [comment]
> WebStorm tells me I have no changes.

API files are apparently created in phet-io repo.

**Comment by pixelzoom** [comment]
@samreid pointed me to https://github.com/phetsims/phet-io/issues/1733#issuecomment-800643313 for a list of possible workflows.  I would probably end up using "Use case 6", which presumably means run it in Studio or Standalone via phetmarks.  The other use cases are not at all friendly, I'll never remember them.  If we need a command line "compare APIs", then a grunt task like `grunt phet-io-compare-apis` would be preferrable. Otherwise I'll end up writing my own shell script.

**Comment by zepumph** [comment]
>Otherwise I'll end up writing my own shell script.

We don't want that! We are still working on usability in general, and are using https://github.com/phetsims/phet-io/issues/1733#issuecomment-800643313 to first organize before optimizing on the use cases that are most important, and frequent. This is in part why we have not briefed the team on this process yet, and why you ran into this CT error without any prior knowledge or backup from us.

**Comment by samreid** [comment]
I opened https://github.com/phetsims/chipper/issues/1025 for adding a grunt command.  Anything else for this issue?

**Comment by pixelzoom** [comment]
👍🏻 closing.
