### ISSUE TITLE
Add a simplified grunt command for API comparison

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1025]
From https://github.com/phetsims/phet-io/issues/1733 and subsequently https://github.com/phetsims/chipper/issues/1023, I would like to add a grunt command that does the following:

outputs the phet-io api for >=1 repos to the temporary location and runs a comparison between the temporary version and the reference version.  This will replace the commands:

```
node js/phet-io/output-apis.js --simList=../perennial/data/phet-io-api-stable --temporary
node js/phet-io/compare-apis.js --simList=../perennial/data/phet-io-api-stable
```

It should also have a `--delta` option that lets you show all changes rather than breaking changes.

**Comment by samreid** [comment]
Committed and ready for review, this could be part of our work/discussion for Wednesday.

**Comment by zepumph** [comment]
Review:

- [ ] getSimList() doesn't feel like it belongs in `phet-io/`, but I understand if we want to create a new directory outside of `grunt/` to start building up our command line arg tools.

**Comment by zepumph** [comment]
Review complete.

**Comment by zepumph** [comment]
- [ ] @samreid and I liked thinking of the checked in api in `phet-io/api/` as the `referenceAPI`, and the one comparing to it as the `proposedAPI`, perhaps we could rename in these scripts to adopt that language.

**Comment by zepumph** [comment]
- [ ] Should we delete compare-apis.js? @samreid and I think probably not, but we should optimize the grunt task to be the main usage of comparison. Perhaps the compare-apis is just for iterating on the same, generated API script (from temporary/) without needing to regenerate into memory each time.

**Comment by samreid** [comment]
> Can we add an 'output-phet-io-api` script as well?

There is already `grunt generate-phet-io-api` which I think should be sufficient for now.

**Comment by samreid** [comment]
A bad commit message sneaked in by manual error, so I referenced it above.

**Comment by zepumph** [comment]
> There is already `grunt generate-phet-io-api` which I think should be sufficient for now.
> 


Right! I totally forgot about how that functionality changed to output into `phet-io/api`.

**Comment by zepumph** [comment]
Looks great. Closing; please reopen if there is anything more here.
