### ISSUE TITLE
Enable prefer-template lint rule?

### ISSUE THREAD

**Issue by chrisklus** [phetsims/chipper#1027]
Discussion continued from https://github.com/phetsims/chipper/issues/814#issuecomment-802949806.

Taken from that comment:

>We, as a team are very ambivalent about this one, @pixelzoom comments in https://github.com/phetsims/chipper/issues/814#issuecomment-797688106. Pretty much people prefer templates most of the time, but also don't love being pigeon-holed by this. We will pick up discussion next time.
  SR: I don't feel strongly one way or the other about this rule, but my experience has been that I am trained reflexively to use concatenation even when it's sub-optimal.  I was also encouraged that this can be fixed either with `grunt lint --fix` or with the IDE with 2 keystrokes:

![image](https://user-images.githubusercontent.com/679486/111806494-aa16eb00-8897-11eb-8082-7b7eeabe6313.png)

>Do we use concatenation rarely enough that intentional uses can opt out of the rule with `// eslint-disable-line prefer-template`?  I wonder if we will get better at just learning to use templates in the first place.

We wanted to continue discussing with @pixelzoom present - labeling for dev meeting

**Comment by pixelzoom** [comment]
> SR: I don't feel strongly one way or the other about this rule, but my experience has been that I am trained reflexively to use concatenation even when it's sub-optimal. 

Enter a "new" language feature, which does some things better than an "old" language feature.  Choose the option that will make you a better programmer: 

(a) Keep both the old and new features in your toolbox, and learn how to choose the best one for the task.
(b) Ban the old feature, allow only the new feature, even when it's suboptimal.

**Comment by pixelzoom** [comment]
4/22/21 dev meeting:

Vote was 4 to remove rule, 2 to keep, 2 abstained.

@samreid will remove it.

**Comment by samreid** [comment]
I disabled the prefer-template rule and removed the now-redundant override in yotta.  Closing.
