### ISSUE TITLE
Enable require-await lint rule?

### ISSUE THREAD

**Issue by chrisklus** [phetsims/chipper#1028]
Discussion from https://github.com/phetsims/chipper/issues/814#issuecomment-802949806.

@jonathanolson votes no, because async functions that don't use await would fail, and he showed examples of this being a convenient case to allow.

@zepumph's recommendation was to check the usages that exist and figure out the percentage that are wrong and should be fixed vs ones like what @jonathanolson described above. If a large percentage are incorrect, maybe this would be worth having.

**Comment by zepumph** [comment]
I poked through again, and found that I am in agreement with @jonathanolson. We definitely have a pattern that doesn't rely on await, and I don't think we need to change this. I.E:

https://github.com/phetsims/chipper/blob/b4f9348651551c65dbb38900cc59e7e2ecbac5a0/js/grunt/Gruntfile.js#L115-L121

Closing
