### ISSUE TITLE
Enable the array-callback-return lint rule

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1030]
From https://github.com/phetsims/chipper/issues/814, we would like to enable the array-callback-return rule.  It seems like many occurrences need to convert `map` to `forEach`, but I'll request a spot check from @zepumph and @jonathanolson where many of the occurrences appear.

Please unassign yourself if everything seems OK.  If there are no more assignees, please close.

**Comment by jonathanolson** [comment]
Looks great, thanks! (No more assignees)
