### ISSUE TITLE
aria-valuetext in the a11y-view does not get hidden correctly

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/chipper#1036]
While working on description in GHE, we noticed that the paragraph displaying `aria-valuetext` is always shown even when the Node with the attribute is hidden. Likely related to #660.

**Comment by jessegreenberg** [comment]
Fixed in https://github.com/phetsims/chipper/commit/bc7d41e3a579913b1e321260e27ef6347726f8c8 just by checking for `!element.hidden` before displaying inline attributes. Following commits regenerate a11y views for interactive-description list. @zepumph can you verify this is OK?

**Comment by zepumph** [comment]
Looks great. Thanks for taking care of this.
