### ISSUE TITLE
create convenience Voicing query parameters parameters

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#1042]
After discussing with @jessegreenberg, it may help to have the following things for developing voicing features:

- [x] `?voicingInitiallyEnabled`, default to false, as the design specifies.
- [ ] ~`?debugVoicing`, which pulls out some of the hidden preferences controls into a spot that is easier and faster to access. One thought is a floating Node on top of the screenView, another is adding it into the voicing toolbar.~

**Comment by zepumph** [comment]
Add voicingInitiallyEnabled above.

**Comment by jessegreenberg** [comment]
Sorry I haven't gotten to this yet. But I reverted this for the moment because phet.chipper.queryParameters can't be used in scenery (where webSpeaker lives) and its causing an error on CT for some scenery docs/tests. I don't have time at the moment to investigate where it should go in scenery.

**Comment by zepumph** [comment]
@jessegreenberg had a good idea to just look at this parameter in Sim.js, and toggle webSpeaker as needed there. I'll do that.

**Comment by zepumph** [comment]
Does that seem better to you?

**Comment by zepumph** [comment]
And I added to phetmarks.

**Comment by zepumph** [comment]
voicingInitiallyEnabled has been working nicely. While working on friction I have realized how nice it would be to consistently load with the following preferences enabled (for debugging and generally development).

```diff
Index: js/accessibility/voicing/responseCollector.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/accessibility/voicing/responseCollector.js b/js/accessibility/voicing/responseCollector.js
--- a/js/accessibility/voicing/responseCollector.js	(revision 8890492fad8d496dee006a4cf692bec5653201f8)
+++ b/js/accessibility/voicing/responseCollector.js	(date 1626729429380)
@@ -21,13 +21,13 @@
     this.nameResponsesEnabledProperty = new BooleanProperty( true );
 
     // @public {BooleanProperty} - whether or not "Object Responses" are read as interactive components change
-    this.objectResponsesEnabledProperty = new BooleanProperty( false );
+    this.objectResponsesEnabledProperty = new BooleanProperty( true );
 
     // @public {BooleanProperty} - whether or not "Context Responses" are read as inputs receive interaction
-    this.contextResponsesEnabledProperty = new BooleanProperty( false );
+    this.contextResponsesEnabledProperty = new BooleanProperty( true );
 
     // @public {BooleanProperty} - whether or not "Hints" are read to the user in response to certain input
-    this.hintResponsesEnabledProperty = new BooleanProperty( false );
+    this.hintResponsesEnabledProperty = new BooleanProperty( true );
   }
 
   /**
Index: js/accessibility/voicing/voicingManager.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/accessibility/voicing/voicingManager.js b/js/accessibility/voicing/voicingManager.js
--- a/js/accessibility/voicing/voicingManager.js	(revision 8890492fad8d496dee006a4cf692bec5653201f8)
+++ b/js/accessibility/voicing/voicingManager.js	(date 1626729770322)
@@ -39,7 +39,7 @@
     this.voiceProperty = new Property( null );
 
     // @public {NumberProperty} - controls the speaking rate of Web Speech
-    this.voiceRateProperty = new NumberProperty( 1.0, { range: new Range( 0.75, 2 ) } );
+    this.voiceRateProperty = new NumberProperty( 2.0, { range: new Range( 0.75, 2 ) } );
 
     // {NumberProperty} - controls the pitch of the synth
     this.voicePitchProperty = new NumberProperty( 1.0, { range: new Range( 0.5, 2 ) } );

``` 
1. The quick and dirty, create a query parameter called `?debugVoicing` that toggles these settings, similar to my idea in the first checkbox, except right now I don't care about changing them as much as having them on startup, so maybe we wouldn't need to add UI to the toolbar or anything.
2. Create preferences that persist, such that when you use them, they save config to localStorage. I remember hearing from @jessegreenberg that this feature was discussed during general design of preferences but decided against for a variety of reasons. I wonder if we could hide this behind a query parameter like `?persistentPreferences`. When you supply that, it loads from local storage, and every time you change a perference, it autosaves it to localstorage for the next time you reload with that query parameter.
@jessegreenberg, what do you think?

**Comment by zepumph** [comment]
- [ ] Another idea I was thinking was a mode where voicing text would appear in a box on the screen. This would be helpful to me while developing (a) so that I wouldn't always have to have sound on to work, and (b) to ensure proper punctuation and formatting.  Maybe that would be called `?voicingOnScreen`, `?voicingDialog`, or `?voicingDisplayText`.

**Comment by zepumph** [comment]
- [ ] Increase the max voice rate also

**Comment by zepumph** [comment]
- [ ] Create preferencesStorage that can register any property to support localStorage preferences. (new issue)

**Comment by zepumph** [comment]
Everything has been moved to separate issues for implementation. Thanks @jessegreenberg!
