### ISSUE TITLE
Update to Webpack 5

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1044]
https://github.com/phetsims/tasks/issues/987 revealed that we are using Webpack 4, which was released in 2018.  Webpack 5 came out in October 2020, and it would be good to stay current on this.  There is a migration guide here:
https://webpack.js.org/migrate/5/.  I'll take a look.  If it goes well, I could publish a new version for testing in https://github.com/phetsims/QA/issues/654

**Comment by samreid** [comment]
This patch is working well, but I don't want to commit it until I can verify it on Windows:

<details>

```diff
Index: js/grunt/webpackBuild.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/grunt/webpackBuild.js b/js/grunt/webpackBuild.js
--- a/js/grunt/webpackBuild.js	(revision c92f51c1a9628142145435f7056ae9691586cce9)
+++ b/js/grunt/webpackBuild.js	(date 1622780877907)
@@ -35,14 +35,13 @@
  * @returns {Array.<string>}
  */
 const getRelativeModules = modules => {
-  for ( let i = 0; i < modules[ 0 ].length; i++ ) {
-    for ( const usedModule of modules ) {
-      if ( usedModule[ i ] !== modules[ 0 ][ i ] ) {
-        return modules.map( module => module.slice( i ) );
-      }
-    }
-  }
-  throw new Error( 'modules are all the same?' );
+  const root = path.resolve( __dirname, '../../../' );
+  const out = modules
+    .filter( m => fs.lstatSync( m ).isFile() )
+    .map( m => path.relative( root, m ) )
+    .filter( m => m !== '../package.json' );
+  // console.log( out.join( '\n' ) );
+  return out;
 };
 
 /**
@@ -76,6 +75,7 @@
     } );
 
     const compiler = webpack( {
+
       // We uglify as a step after this, with many custom rules. So we do NOT optimize or uglify in this step.
       optimization: {
         minimize: false
Index: package.json
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/package.json b/package.json
--- a/package.json	(revision c92f51c1a9628142145435f7056ae9691586cce9)
+++ b/package.json	(date 1622778608746)
@@ -29,9 +29,9 @@
     "request-promise-native": "^1.0.7",
     "taffydb": "^2.7.3",
     "terser": "~4.6.4",
-    "webpack": "^4.41.4",
-    "webpack-cli": "^3.3.10",
-    "webpack-dev-server": "^3.10.1",
+    "webpack": "^5.38.1",
+    "webpack-cli": "^4.7.0",
+    "webpack-dev-server": "^3.11.2",
     "html-webpack-plugin": "4.0.0-beta.11",
     "memfs": "^3.0.3"
   },

```

</details>

**Comment by samreid** [comment]
I tested the patch on Windows 10, from git bash and from the Webstorm built-in terminal, and it worked well in both places.  I uncommented the console.log in the path generation and it looked as expected (with back slashes, as in the previous version).  There may be other ways Windows users use the terminal, but for now, this seems safe to commit.

**Comment by samreid** [comment]
Committed.  Erring on the side of caution, it would be nice to do the following steps before closing:

- [ ] quick code review 
- [ ] windows developer do a test build

**Comment by samreid** [comment]
I also saw this warning on a fresh npm install:

```
npm WARN html-webpack-plugin@4.0.0-beta.11 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
```

**Comment by jonathanolson** [comment]
Reviewed the migration guide, the patch, and tested on Windows. It looks like we're handling everything (and well).

**Comment by samreid** [comment]
Thanks, I made one more change and notified slack:

> For https://github.com/phetsims/chipper/issues/1044, I also added another version change to package.json.  At your convenience, please pull chipper and run `npm update`.  (But note that it probably doesn’t affect you unless you use `grunt webpack-dev-server` )

Closing.

**Comment by jonathanolson** [comment]
Reopening, likely I'll need to maintenance patch this in.

**Comment by jonathanolson** [comment]
Maintenance complete, closing.
