### ISSUE TITLE
Migrate to Typescript

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1046]
In https://github.com/phetsims/tasks/issues/987 we investigated TypeScript and determined it will significantly improve our project. This is an epic "quarterly-goal" issue which we can use for planning migration. This migration will be reminiscent of when we migrated from requirejs to es6 modules--similar scope, impact on build tools, learning curve, etc. Here are the main checkpoints:

Q3 (July 1 - Sept 30)
* Tooling https://github.com/phetsims/chipper/issues/1047
* Dev team training/education https://github.com/phetsims/chipper/issues/1048
* Identification of patterns/conventions https://github.com/phetsims/chipper/issues/1049
* New code in TypeScript (mixed JS/TS)
* Migration of select existing code

Q4+
* Migration of sim stack

2022 Q2
* Typescript conventions (priority)
* Typescript common code conversion ongoing 
* ~4 hours/week for the quarter

Future
* Migration of node/preloads, etc. as appropriate

**Comment by samreid** [comment]
Notes from today's discussion:

JB: Some hesitation about--how long will the migration take?

> We can decide what level to go. We don't necessarily need to upgrade all of our pre-existing sims.  We could add TS whe

MK: TS has interfaces.  We have spent a lot of time dealing with that and working around it.  We can get good fixes to many annoying problems with interfaces.  That's just one thing.  I'm really excited.

CK: I'm very excited.  I think it will be a big time saver, and will reduce bug searching time dramatically.

JG: I'm excited but somewhat hesitant, I feel behind on existing projects so it is scary and I don't know where it would fit for timing.  I know TS will solve problems for us, but it brings in something heavier.  Lately using C++ and had trouble with basic abstractions, like adding a listener.  Will we have the same problem with typescript?

JO: I'm really looking forward to this, it's going to help a lot of things that have been problems.  IDE support will be better, it seems like a long term benefit to the project.  There will be cost to get up to speed and cost of conversion, but it seems worth it to me.

CM: I agree with JO.  Looking forward to having some better features in a JS-like language.  From a higher level, I don't know what the timing is or when to do it.  But I also agree with what Jesse said, I feel behind on everything, and if we start with this right now, I'm not sure how it will impact my productivity.  Technically, you may also have a smaller hiring pool, if there are fewer TS developers than JS developers.  Or if you hire a JS programmer, it is not a huge task, but learning TS would just be one more thing.  But that is outweighted by the long term productivity increase we could get.

MP: It sounds like a good direction.  Maybe using it in the build server would be a later step, though.

**Comment by samreid** [comment]
Notes from discussion about moving forward:

CM: I don't think I would go back and convert old sims to typescript.

MK: Should we split into 2 processes where old sims skip compilation, and only sims that have TS dependency use the new process?

CM: We should use the uniform process for doing this.

KP: People are excited about it, and can take it up at different times.  So we can ready the tooling for production, add the compile step to everything.  Then we can toe-dip as appropriate.

KP: So we will have a reviewer review this build steps, then move to master.

CM: I have 0 time to be involved in that review.  Not sure about timelines.

KP: Maybe after density is published, JO can review?

JO: I can review it then.

SR: After review, we can move it to master and leave it up to developers to decide when to convert files.

CM: Before converting common code, let's check in with the dev team and make sure everyone is ready for that step.  We could avoid stress by making sure we are all on the same page at that point.

KP: At least have a dev discussion before moving common code to typescript.  Then we can see how toe-dipping is going, make sure people have had time for that.  

CM: OK for this phase, everybody would be free to toe-dip, in sim-specific code.  That will help work out the build tools issues. Then we can see when it is ready for common code.  Or if a developer thinks it is ready for common code, we can discuss again and go for it.

**Comment by samreid** [comment]
I posted notes in the status meeting agenda that pertain to this issue:

Thanks to collaboration with Jonathan and Michael, TypeScript is now ready for usage in simulation code.

### For developers:
* The quick start guide is at https://github.com/phetsims/chipper/blob/master/doc/typescript-quick-start.md
* We can learn together by pair programming, discussion on #typescript, discussion at dev meetings or setting up mini-meetings like we did with our "patterns" meetings.
* I reserved time in developer meeting today to work on porting blast to TypeScript

### For the team:
* Please readjust timelines so that developers may use TypeScript for their next project if desired
* For the ES6 module conversion, we had an "all hands on deck" period where everybody pulled together for several weeks. Since we are using a more opt-in approach with TypeScript, it can be more asynchronous, letting developers opt-in at their own time, but please allow devs flexibility in their timelines in learning this new technology.
* This new technology is under evaluation. Let's do what we can to give it a fair trial.
* This is an evolving project in the early phases. Yes, it has reached a critical mass that makes it ready for usage.  But there will be growing pains. Discover problems, look for solutions! We are focusing on long-term investment.

**Comment by marlitas** [comment]
``` js
 
┌─────────────────┬───────┬───────┬────────────┬──────────────┐
│     (index)     │  JS   │  TS   │ % Complete │ "@ts-ignore" │
├─────────────────┼───────┼───────┼────────────┼──────────────┤
│      axon       │ 2837  │ 5106  │     64     │      51      │
│      brand      │  57   │   0   │     0      │      0       │
│     chipper     │ 10877 │   0   │     0      │      0       │
│       dot       │ 13828 │ 5775  │     29     │      4       │
│      joist      │ 6197  │ 7724  │     55     │      17      │
│      kite       │ 9474  │ 6795  │     41     │      10      │
│     mobius      │   0   │ 1764  │    100     │      3       │
│    perennial    │ 11426 │   0   │     0      │      0       │
│    phet-core    │ 2679  │ 1998  │     42     │      6       │
│     phet-io     │ 2963  │   0   │     0      │      0       │
│   phetcommon    │ 1926  │  273  │     12     │      0       │
│    phetmarks    │ 1048  │   0   │     0      │      0       │
│     scenery     │ 38772 │ 47993 │     55     │     132      │
│  scenery-phet   │ 7903  │ 19529 │     71     │      15      │
│      shred      │ 17413 │  274  │     1      │      0       │
│       sun       │  223  │ 15575 │     98     │      15      │
│      tambo      │  55   │ 6445  │     99     │      4       │
│     tandem      │ 2594  │ 3099  │     54     │      35      │
│      twixt      │ 2344  │  20   │     0      │      0       │
│ utterance-queue │  815  │ 2763  │     77     │      6       │
│      vegas      │   0   │ 2549  │    100     │      0       │
```

**Comment by samreid** [comment]
We have embraced TypeScript and are using it where appropriate, I think this issue can be closed.

**Comment by pixelzoom** [comment]
Reopening.

Having this issue open reminds us that there's still work to be done.  Current ts-status (below) shows "60% complete" for common code.  And as I'm converting sims to TypeScript, I'm (too frequently) encountering common code that I need that have not been converted.  twixt is 0% converted. axon is only 65% converted. 

So before closing this issue, I suggest that we should evaluate as a team, decide on next steps, and then decide whether this issue can be closed.

```
ts-status

 --------- SUMMARY ----------
 Total "@ts-ignore": 326
 Total JS: 102513
 Total TS: 154569
 % Complete: 60%
 
┌─────────────────┬───────┬───────┬────────────┬──────────────┐
│     (index)     │  JS   │  TS   │ % Complete │ "@ts-ignore" │
├─────────────────┼───────┼───────┼────────────┼──────────────┤
│      axon       │ 2988  │ 5700  │     65     │      44      │
│      brand      │   0   │  72   │    100     │      0       │
│     chipper     │ 12778 │  477  │     3      │      0       │
│       dot       │ 13644 │ 6103  │     30     │      6       │
│      joist      │  207  │ 14690 │     98     │      15      │
│      kite       │ 9502  │ 6764  │     41     │      10      │
│     mobius      │   0   │ 1767  │    100     │      3       │
│  nitroglycerin  │   0   │ 1941  │    100     │      0       │
│    perennial    │ 11471 │  41   │     0      │      0       │
│    phet-core    │ 2653  │ 2110  │     44     │      6       │
│     phet-io     │  270  │ 2809  │     91     │      4       │
│   phetcommon    │ 1931  │  273  │     12     │      0       │
│    phetmarks    │ 1075  │   0   │     0      │      0       │
│     scenery     │ 37231 │ 49544 │     57     │     137      │
│  scenery-phet   │ 4927  │ 23171 │     82     │      14      │
│     studio      │   2   │ 3729  │     99     │      13      │
│       sun       │  222  │ 15947 │     98     │      17      │
│      tambo      │  55   │ 6452  │     99     │      4       │
│     tandem      │  262  │ 5194  │     95     │      40      │
│      tappi      │  964  │  939  │     49     │      2       │
│      twixt      │ 2331  │  22   │     0      │      0       │
│ utterance-queue │   0   │ 3653  │    100     │      11      │
│      vegas      │   0   │ 3171  │    100     │      0       │
└─────────────────┴───────┴───────┴────────────┴──────────────┘
```

**Comment by pixelzoom** [comment]
> We have embraced TypeScript and are using it where appropriate

Reopening.  I agree that we've made progress, but we're certainly not done migrating common code.  There are many more places where Typescript is appropriate that are still JavaScript.

Having this issue open reminds us that there's still work to be done.  Current ts-status (below) shows "60% complete" for common code.  And as I'm converting sims to TypeScript, I'm (too frequently) encountering common code that has not been converted.  axon is only 65% converted. dot 30%. twixt is 0%.

So before closing this issue, I suggest that we should evaluate as a team, decide on next steps, and then decide whether this issue can be closed.  @kathy-phet FYI.

```
ts-status

 --------- SUMMARY ----------
 Total "@ts-ignore": 326
 Total JS: 102513
 Total TS: 154569
 % Complete: 60%
 
┌─────────────────┬───────┬───────┬────────────┬──────────────┐
│     (index)     │  JS   │  TS   │ % Complete │ "@ts-ignore" │
├─────────────────┼───────┼───────┼────────────┼──────────────┤
│      axon       │ 2988  │ 5700  │     65     │      44      │
│      brand      │   0   │  72   │    100     │      0       │
│     chipper     │ 12778 │  477  │     3      │      0       │
│       dot       │ 13644 │ 6103  │     30     │      6       │
│      joist      │  207  │ 14690 │     98     │      15      │
│      kite       │ 9502  │ 6764  │     41     │      10      │
│     mobius      │   0   │ 1767  │    100     │      3       │
│  nitroglycerin  │   0   │ 1941  │    100     │      0       │
│    perennial    │ 11471 │  41   │     0      │      0       │
│    phet-core    │ 2653  │ 2110  │     44     │      6       │
│     phet-io     │  270  │ 2809  │     91     │      4       │
│   phetcommon    │ 1931  │  273  │     12     │      0       │
│    phetmarks    │ 1075  │   0   │     0      │      0       │
│     scenery     │ 37231 │ 49544 │     57     │     137      │
│  scenery-phet   │ 4927  │ 23171 │     82     │      14      │
│     studio      │   2   │ 3729  │     99     │      13      │
│       sun       │  222  │ 15947 │     98     │      17      │
│      tambo      │  55   │ 6452  │     99     │      4       │
│     tandem      │  262  │ 5194  │     95     │      40      │
│      tappi      │  964  │  939  │     49     │      2       │
│      twixt      │ 2331  │  22   │     0      │      0       │
│ utterance-queue │   0   │ 3653  │    100     │      11      │
│      vegas      │   0   │ 3171  │    100     │      0       │
└─────────────────┴───────┴───────┴────────────┴──────────────┘
```

**Comment by matthew-blackman** [comment]
A subteam will go through the remaining files and decide on which ones to prioritize for TS conversion. Will be done during Oct 20-27 sprint (Common Code Week).

**Comment by marlitas** [comment]
It looks like a subgroup was never assigned for this issue during the Oct. 20-27 sprint. Moving back to `to be discussed` to put this back on the radar. 

In the meantime here is a new ts-status:
``` 
--------- SUMMARY ----------
 Total "@ts-expect-error": 281
 Total JS: 99798
 Total TS: 161975
 % Complete: 61%
 
┌─────────────────┬───────┬───────┬────────────┬────────────────────┐
│     (index)     │  JS   │  TS   │ % Complete │ "@ts-expect-error" │
├─────────────────┼───────┼───────┼────────────┼────────────────────┤
│      axon       │  438  │ 8552  │     95     │         57         │
│      brand      │   0   │  73   │    100     │         0          │
│     chipper     │ 13065 │  505  │     3      │         0          │
│       dot       │ 13642 │ 6448  │     32     │         6          │
│      joist      │  207  │ 15125 │     98     │         10         │
│      kite       │ 9676  │ 6731  │     41     │         7          │
│     mobius      │   0   │ 1779  │    100     │         3          │
│  nitroglycerin  │   0   │ 1991  │    100     │         0          │
│    perennial    │ 12177 │  41   │     0      │         0          │
│    phet-core    │ 2399  │ 2311  │     49     │         4          │
│     phet-io     │  270  │ 2806  │     91     │         4          │
│   phetcommon    │ 1536  │  633  │     29     │         0          │
│    phetmarks    │ 1075  │   0   │     0      │         0          │
│     scenery     │ 36528 │ 51476 │     58     │        137         │
│  scenery-phet   │ 4949  │ 24046 │     82     │         0          │
│     studio      │   2   │ 3700  │     99     │         13         │
│       sun       │  222  │ 15911 │     98     │         7          │
│      tambo      │  55   │ 6587  │     99     │         2          │
│     tandem      │  262  │ 5303  │     95     │         21         │
│      tappi      │  964  │  955  │     49     │         2          │
│      twixt      │ 2331  │  32   │     1      │         0          │
│ utterance-queue │   0   │ 3734  │    100     │         8          │
│      vegas      │   0   │ 3236  │    100     │         0          │
```

**Comment by marlitas** [comment]
JB: It seems like it would be difficult for a few devs to determine what are priorities in every repo. Perhaps we should do this as a team?
KP: This doesn't seem like a top priority right now and we can find another time to prioritize the rest of the conversion.

**Comment by zepumph** [comment]
Current Status:

```
 --------- SUMMARY ----------
 Total "@ts-expect-error": 322
 Total JS: 92423
 Total TS: 174667
 % Complete: 65%

┌─────────────────┬───────┬───────┬────────────┬────────────────────┐
│     (index)     │  JS   │  TS   │ % Complete │ "@ts-expect-error" │
├─────────────────┼───────┼───────┼────────────┼────────────────────┤
│      axon       │  159  │ 9061  │     98     │         63         │
│      brand      │   0   │  73   │    100     │         0          │
│     chipper     │ 13146 │  552  │     4      │         0          │
│       dot       │ 13444 │ 6775  │     33     │         5          │
│      joist      │  207  │ 14937 │     98     │         11         │
│     tandem      │  271  │ 5689  │     95     │         20         │
│      tappi      │  966  │  959  │     49     │         2          │
│      twixt      │  576  │ 1742  │     75     │         11         │
│ utterance-queue │   0   │ 3968  │    100     │         5          │
│      vegas      │   0   │ 3248  │    100     │         1          │
└─────────────────┴───────┴───────┴────────────┴────────────────────┘


```

As far as I know, this issue could be closed. It will never be worth converting the entire code base, and I believe we as a team are now quite trained as to the bar to convert an old sim or common code file. 

Good work team! 

What more do we want from this issue? Perhaps a short dev meeting discussion to see if anyone keeps running into sim-side code that remains in javascript and needs prioritization.

**Comment by pixelzoom** [comment]
FYI, here's the status of sims that I'm responsible for: https://github.com/phetsims/phet-info/blob/master/sim-info/pixelzoom-sims.md.   With the exception of function-builder and unit-rates, all other sims are 100% TypeScript, with stricter rules in package.json.

**Comment by pixelzoom** [comment]
I see a much longer list than what @zepumph reported in https://github.com/phetsims/chipper/issues/1046#issuecomment-1595413292.  I'd love to see more conversion of dot and kite.

```
 --------- SUMMARY ----------
 Total "@ts-expect-error": 322
 Total JS: 92423
 Total TS: 174667
 % Complete: 65%
 
┌─────────────────┬───────┬───────┬────────────┬────────────────────┐
│     (index)     │  JS   │  TS   │ % Complete │ "@ts-expect-error" │
├─────────────────┼───────┼───────┼────────────┼────────────────────┤
│      axon       │  159  │ 9061  │     98     │         63         │
│      brand      │   0   │  73   │    100     │         0          │
│     chipper     │ 13146 │  552  │     4      │         0          │
│       dot       │ 13444 │ 6775  │     33     │         5          │
│      joist      │  207  │ 14937 │     98     │         11         │
│      kite       │ 6709  │ 9453  │     58     │         10         │
│     mobius      │   0   │ 1786  │    100     │         3          │
│  nitroglycerin  │   0   │ 1992  │    100     │         0          │
│    perennial    │ 13640 │  41   │     0      │         0          │
│    phet-core    │ 2407  │ 2387  │     49     │         4          │
│     phet-io     │  280  │ 3051  │     91     │         3          │
│   phetcommon    │ 1057  │ 1130  │     51     │         0          │
│    phetmarks    │ 1091  │   0   │     0      │         0          │
│     scenery     │ 33419 │ 56481 │     62     │        165         │
│  scenery-phet   │ 4772  │ 24510 │     83     │         0          │
│     studio      │   2   │ 3827  │     99     │         12         │
│       sun       │  222  │ 16273 │     98     │         7          │
│      tambo      │  55   │ 6732  │     99     │         0          │
│     tandem      │  271  │ 5689  │     95     │         20         │
│      tappi      │  966  │  959  │     49     │         2          │
│      twixt      │  576  │ 1742  │     75     │         11         │
│ utterance-queue │   0   │ 3968  │    100     │         5          │
│      vegas      │   0   │ 3248  │    100     │         1          │
└─────────────────┴───────┴───────┴────────────┴────────────────────┘
```

**Comment by pixelzoom** [comment]
FYI, here's the status of sims that I'm responsible for: https://github.com/phetsims/phet-info/blob/master/sim-info/pixelzoom-sims.md.   With the exception of function-builder and unit-rates, all other sims are 100% TypeScript, with stricter rules in package.json.

**Comment by pixelzoom** [comment]
Rainy day project... I converted more of twixt (75% => 98%).  The remaining file is AnimationTest.js, which consists of QUnit tests that I've typically been unsuccessful in converting.

**Comment by pixelzoom** [comment]
Here's the current ts-status, for discuss at 6/21 dev meeting ...

```
 --------- SUMMARY ----------
 Total "@ts-expect-error": 322
 Total JS: 91898
 Total TS: 175280
 % Complete: 65%
 
┌─────────────────┬───────┬───────┬────────────┬────────────────────┐
│     (index)     │  JS   │  TS   │ % Complete │ "@ts-expect-error" │
├─────────────────┼───────┼───────┼────────────┼────────────────────┤
│      axon       │  159  │ 9044  │     98     │         63         │
│      brand      │   0   │  73   │    100     │         0          │
│     chipper     │ 13147 │  552  │     4      │         0          │
│       dot       │ 13444 │ 6775  │     33     │         5          │
│      joist      │  207  │ 14937 │     98     │         11         │
│      kite       │ 6709  │ 9453  │     58     │         10         │
│     mobius      │   0   │ 1786  │    100     │         3          │
│  nitroglycerin  │   0   │ 1992  │    100     │         0          │
│    perennial    │ 13640 │  41   │     0      │         0          │
│    phet-core    │ 2407  │ 2387  │     49     │         4          │
│     phet-io     │  280  │ 3103  │     91     │         3          │
│   phetcommon    │ 1057  │ 1130  │     51     │         0          │
│    phetmarks    │ 1102  │   0   │     0      │         0          │
│     scenery     │ 33419 │ 56492 │     62     │        165         │
│  scenery-phet   │ 4772  │ 24517 │     83     │         0          │
│     studio      │   2   │ 3827  │     99     │         12         │
│       sun       │  222  │ 16291 │     98     │         7          │
│      tambo      │  55   │ 6732  │     99     │         0          │
│     tandem      │  271  │ 5673  │     95     │         20         │
│      tappi      │  966  │  959  │     49     │         2          │
│      twixt      │  39   │ 2300  │     98     │         11         │
│ utterance-queue │   0   │ 3968  │    100     │         5          │
│      vegas      │   0   │ 3248  │    100     │         1          │
└─────────────────┴───────┴───────┴────────────┴────────────────────┘
```

**Comment by marlitas** [comment]
CM: Would like to see more TS conversion in dot because of the high Utils usage.
MK: Have been converting dot on an as needed basis. Does not feel like this is a priority and that we should perhaps close this issue and handle any other conversions individually.
CM: Most of the javascript code in Kite is rarely used. Everything that is heavily used in sim code is already converted.
SR: TS is able to parse JSDoc and providing type safety through that.
SR: I convert on an as needed basis as well. However, I haven't converted anything in a while.
MS: Is this an indication of priority/time or that we have already hit most of the important files.
SR: I just haven't run into it.
CM: I'm converting so that I don't have to talk about it again.
JG: I'm fine with closing.
CK: I'm also good with closing.

We are closing.
