### ISSUE TITLE
verification of required package.json files is missing

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#105]
Grunt file requires the presence of various properties (some specific to PhET) in package.json. It reads package.json and confirms the existence of properties here:
```js
  // Read package.json, verify that it contains required properties
  assert( fs.existsSync( 'package.json' ), 'repository must have a package.json' );
  var pkg = grunt.file.readJSON( 'package.json' );
  assert( pkg.name, 'name missing from package.json' );
  assert( pkg.version, 'version missing from package.json' );
  assert( pkg.phetLibs, 'phetLibs missing from package.json' );
  assert( pkg.license, 'license missing from package.json' );
```

But this is incomplete. It also requires `preload` and `simTitleStringKey`.  Adding `simTitleStringKey` to the above is problematic; it's used in a sim-specific task, is not defined in package.json for common-code repos, and would cause grunt to bail for common-code tasks (e.g. `grunt lint`).  So I will probably add the assertion for `simTitleStringKey` near its use, rather than in the chunk above.

**Comment by pixelzoom** [comment]
`preload` is also absent from (all?) non-sim package.json.

**Comment by jonathanolson** [comment]
> preload is also absent from (all?) non-sim package.json.

That is expected, we don't build common repositories like we build sims.

If we want to use the same Gruntfile for handling lots of common-repo tasks, we'll probably need to separate sim-repo-specific code under a check/flag.

**Comment by pixelzoom** [comment]
Yes, I realize its supposed to be missing.  But in fact, it's not. There are many common-code repos that have preload in package.json. https://github.com/phetsims/chipper/issues/106

**Comment by pixelzoom** [comment]
All required package.json properties are now verified. Those that are sim-specific are verified only in sim-specific tasks. Closing.
