### ISSUE TITLE
List of places to convert to TypeScript

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#1050]
From https://github.com/phetsims/tasks/issues/987, if we end up going with TypeScript, @samreid and I though that it may be nice to have a list of places on the project that could be improved upon. 

* UtteranceQueue's constructor parameter should implement an `Announcer` interface.
* `Property` and `Emitter` should be an interface. (for example instead of instanceof checks like https://github.com/phetsims/axon/blob/d848101bd6e9f29d49173b5f41e8a5c7baa70516/js/NumberProperty.js#L82
* `Property` should have a parametric, generic implementation.  Axon has a typescript branch with `Property<T>` in https://github.com/phetsims/axon/issues/360
* Re-evaluate the large number of features packed in Node.js (a single file), and see if they can be split up like done in ParallelDOM.js (see https://github.com/phetsims/scenery/issues/1159). For example named options.

**Comment by samreid** [comment]
@zepumph do you still see value in this issue?

**Comment by zepumph** [comment]
Nah, though it served its purpose.
