### ISSUE TITLE
Grunt update is fighting with daily-grunt-work

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1051]
Running `grunt update` gives copyright timestamps (single year) that are incompatible with daily-grunt-work (date range).  Running `grunt update` and `daily-grunt-work` whenever there is a change would yield an infinite loop.  Detected during https://github.com/phetsims/chipper/issues/1047

**Comment by samreid** [comment]
@jonathanolson can you please review the chipper commit at your convenience?

**Comment by samreid** [comment]
I slacked @jessegreenberg 

> I’m wondering if I broke daily-grunt-work with https://github.com/phetsims/chipper/issues/1051.  Is there a way to check if it is running correctly or needs to be restarted?

**Comment by samreid** [comment]
@jessegreenberg and I checked and saw that daily-grunt-work seems reasonable, and @jonathanolson checked that CT is acting reasonable.

**Comment by jonathanolson** [comment]
Changes look good (after the await fix).

**Comment by samreid** [comment]
Thanks, closing.
