### ISSUE TITLE
Webpack usedModules is reporting package.json as a dependency

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1056]
Discovered in https://github.com/phetsims/studio/issues/234, for unknown reasons I have been getting this error:

```
Fatal error: Perennial task failed:
AssertionError [ERR_ASSERTION]: repo package.jso missing from package.json's phetLibs for package.json
    at /Users/samreid/apache-document-root/main/chipper/js/grunt/buildRunnable.js:131:5
    at Array.forEach (<anonymous>)
    at module.exports (/Users/samreid/apache-document-root/main/chipper/js/grunt/buildRunnable.js:129:29)
    at async /Users/samreid/apache-document-root/main/chipper/js/grunt/Gruntfile.js:255:11
    at async wrap (/Users/samreid/apache-document-root/main/chipper/js/grunt/Gruntfile.js:74:7)
Full Error details:
AssertionError [ERR_ASSERTION]: repo package.jso missing from package.json's phetLibs for package.json
```

The problem is caused by this code:

```js
  webpackResult.usedModules.forEach( moduleDependency => {
    const moduleRepo = moduleDependency.slice( 0, moduleDependency.indexOf( path.sep ) );
    assert( Object.keys( dependencies ).includes( moduleRepo ), `repo ${moduleRepo} missing from package.json's phetLibs for ${moduleDependency}` );
  } );
```

For some reason, some of my webpacks have been reporting "package.json" as a dependency (with no directory).  I tried many things in order to unify my webpacks, including:
* getting rid of package-lock.json
* rm -rf node_modules
* getting rid of `~` and `^` in package.json
* npm prune and npm install
* reverting my prototypes that get rid of grunt dependency in sim repos.

Nothing seems to fix this, so I'm going to add support for directory-less entries in the usedModules.

**Comment by samreid** [comment]
I added support for directory-less usedModule entries.  I tested and it seems OK.  But I only tested from running `grunt` in the sim repos.  Is there a way to do builds from another directory, like perennial forwarding?  How does the build server build?  @jonathanolson can you help with that part?

**Comment by jonathanolson** [comment]
> I added support for directory-less usedModule entries. I tested and it seems OK. But I only tested from running grunt in the sim repos. Is there a way to do builds from another directory, like perennial forwarding? How does the build server build? @jonathanolson can you help with that part?

We currently ONLY run builds from the repo's directory, so that seems safe for now. This includes perennial/build-server/etc. Thoughts on whether this is good for now?

**Comment by samreid** [comment]
Thanks, this seems ready to close.

**Comment by samreid** [comment]
I have to cherry-pick this into gravity and orbits so I can do a build.  May also need to do that for natural selection too.
