### ISSUE TITLE
Centralize the color HTML file

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1061]
From https://github.com/phetsims/scenery-phet/issues/515, we would like to centralize the color HTML editor file, so it doesn't need to be copy/pasted to every simulation.  It seems it does not currently exist in built versions, so perhaps we don't need to support that.  I bounced this idea of @pixelzoom at a meeting earlier today and he said it sounded reasonable.  Also, we would eventually like all our sims to support the color editor, so it no longer makes sense to track which sims have color profiles and which do not.

**Comment by samreid** [comment]
Summary of changes:

* Removed colorProfile: true from package.json
* All runnables now show "color editor" in phetmarks
* `grunt update` no longer creates a color.html file
* phetmarks links to a central file and launches it with ?sim=...

@pixelzoom can you please review or recommend a reviewer?  Please focus on the changes in chipper and phetmarks.  A question for the reviewer, I wasn't sure where to move chipper/templates/sim-development-colors.html, but it is now serving as a runnable HTML file and not as a template.

**Comment by pixelzoom** [comment]
The behavior looks nice.

> Please focus on the changes in chipper and phetmarks.

Those would be https://github.com/phetsims/phetmarks/commit/22d23c75a7f43bb83bed372605f8648703df2d38 and https://github.com/phetsims/chipper/commit/377fb43ef3ac5295f96827893fa274efddb63eb4.   I don't see anything out of place here, but I wasn't very familiar with how ColorProfile was handled here previously.

> I wasn't sure where to move chipper/templates/sim-development-colors.html,

How about somewhere in phetmarks? Does it need to be runnable from phettest?

**Comment by samreid** [comment]
A note to myself or whoever resumes work on this issue, we should attempt to move file history via perennial/bin/copy-history-to-different-repo.sh

**Comment by samreid** [comment]
I moved the file from chipper/templates/sim-development-colors.html to phetmarks/color-editor.html.  It is working nicely locally.  @pixelzoom want to spot check or test anything?  Can this issue be closed?

**Comment by pixelzoom** [comment]
👍🏻 Closing.
