### ISSUE TITLE
Typescript convention: omit "public" modifier, and generally cluster attributes by public, then private

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1065]
The default visibility for typescript fields is public, and when asking WebStorm to convert a private to public member, it does so by removing the "private" modifier, not by switching to public. Still, things look a little less columnar if some things are marked with visibility and some are not.  Here is an example from GravityAndOrbitsModel:

```js 

// no public
class GravityAndOrbitsModel {
  private showGravityForceProperty: BooleanProperty;
  private showVelocityProperty: BooleanProperty;
  private showPathProperty: BooleanProperty;
  private showGridProperty: BooleanProperty;
  private showMassProperty: BooleanProperty;
  private showMeasuringTapeProperty: BooleanProperty;
  isPlayingProperty: BooleanProperty;
  timeSpeedProperty: EnumerationProperty;
  gravityEnabledProperty: BooleanProperty;
  steppingProperty: BooleanProperty;
  rewindingProperty: BooleanProperty;
  private showMassCheckbox: boolean;
  private showMeasuringTape: boolean;
  private sceneList: SceneFactory;
  private sceneProperty: Property;
``` 

```js
class GravityAndOrbitsModel {
  private showGravityForceProperty: BooleanProperty;
  private showVelocityProperty: BooleanProperty;
  private showPathProperty: BooleanProperty;
  private showGridProperty: BooleanProperty;
  private showMassProperty: BooleanProperty;
  private showMeasuringTapeProperty: BooleanProperty;
  public isPlayingProperty: BooleanProperty;
  public timeSpeedProperty: EnumerationProperty;
  public gravityEnabledProperty: BooleanProperty;
  public steppingProperty: BooleanProperty;
  public rewindingProperty: BooleanProperty;
  private showMassCheckbox: boolean;
  private showMeasuringTape: boolean;
  private sceneList: SceneFactory;
  private sceneProperty: Property;
  public static G: number;
```

I'm not sure which I like more, so I'd like to discuss it.  I don't think we should say "developer preference" though--seems good to have a convention that we enforce through lint or code review.  Labeling for https://github.com/phetsims/chipper/issues/1049

**Comment by samreid** [comment]
Organizing by private vs public also seems reasonable, then the public modifier is less important.  This also has the advantage of making the public-facing API clear:

```js
class GravityAndOrbitsModel {
  isPlayingProperty: BooleanProperty;
  timeSpeedProperty: EnumerationProperty;
  gravityEnabledProperty: BooleanProperty;
  steppingProperty: BooleanProperty;
  rewindingProperty: BooleanProperty;
  
  private showGravityForceProperty: BooleanProperty;
  private showVelocityProperty: BooleanProperty;
  private showPathProperty: BooleanProperty;
  private showGridProperty: BooleanProperty;
  private showMassProperty: BooleanProperty;
  private showMeasuringTapeProperty: BooleanProperty;
  private showMassCheckbox: boolean;
  private showMeasuringTape: boolean;
  private sceneList: SceneFactory;
  private sceneProperty: Property;
}
```

**Comment by pixelzoom** [comment]
At 11/4/21 dev meeting, we decided that using the `public` modifier was up to developer discretion.

And I may be hallucinating, but I've seen WebStorm reorganize my declarations so that they are in the order public, protected, private.   I'm not sure what I did to make this happen.

**Comment by pixelzoom** [comment]
If you choose "Reformat Code" and check "Rearrange entries", then WebStorm will order your declarations by visibility.

**Comment by samreid** [comment]
I've documented the "developer preference to use `public` modifier` convention in https://github.com/phetsims/phet-info/blob/master/doc/typescript-conventions.md#visibility-annotations.

Now that I am getting better at reading these class attributes in TypeScript, I feel less strongly that we should require a convention that clusters by visibility.  Can we also leave this as developer discretion?

**Comment by samreid** [comment]
We enabled a rule that requires visibility annotations.  It is developer preference how to organize the properties.  Closing.
