### ISSUE TITLE
Should colorProfile query parameter be public?

### ISSUE THREAD

**Issue by arouinfar** [phetsims/chipper#1066]
During discussion of https://github.com/phetsims/joist/issues/734, I noticed that `colorProfile` is not listed as public in [initialize-globals.js](https://github.com/phetsims/chipper/blob/master/js/initialize-globals.js). However, this query parameter has been disseminated to the public in Teacher Tips and PhET-iO client guides. It appears to be working fine in published sims, for example: https://phet.colorado.edu/sims/html/gas-properties/latest/gas-properties_en.html?colorProfile=projector

It seems like `colorProfile` should be a public query parameter, though I don't know the ramifications of making such a change.

Assigning to the responsible-dev for chipper, @jonathanolson and co-assiging @samreid since he's recently worked on color profiles.

**Comment by samreid** [comment]
It seems straightforward to mark it as public, still I will mark this for dev meeting to touch base and confirm that plan.

**Comment by chrisklus** [comment]
We confirmed that this would be straightforward (it is type `string`, and uses `validValues`, so it is definitely validatable.

Whoever marks it as public should remember to update the query parameter spreadsheet.

@pixelzoom recommends omitting the spreadsheet of public query parameters and using tooling to dump the public ones used in the phet codebase.

**Comment by pixelzoom** [comment]
> @pixelzoom recommends omitting the spreadsheet of public query parameters and using tooling to dump the public ones used in the phet codebase.

Tracking in https://github.com/phetsims/query-string-machine/issues/46.  In the meantime, please DO add `colorProfile` to the spreadsheet.

**Comment by samreid** [comment]
I marked `colorProfile` as public and updated the documentation.  I added an entry to the spreadsheet https://docs.google.com/spreadsheets/d/1TddeTtD8zAayJzs02g0fL7dR1iWYczs1CMFdYd3SBNc/edit#gid=0.

@zepumph or @pixelzoom can you please review?

**Comment by zepumph** [comment]
Looks good to me!

**Comment by samreid** [comment]
Thanks, closing.
