### ISSUE TITLE
tsc --build can pass even when there is a problem introduced by a dependency

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1067]
Follow these steps:

(1) in GravityAndOrbitsScene.ts, add a line like:

```js
this.tandem.runSomething();
```

(2) run tsc -b in gravity-and-orbits, it should fail
(3) Then in PhetioObject.js, comment out `this.tandem=DEFAULTS.tandem`
(4) run tsc -b in gravity and orbits, it should succeed since tandem now has `any` type.
(5) restore PhetioObject.js
(6) run tsc -b in gravity and orbits, it should fail like it did in step (2) since all of the code is exactly the same, but it succeeds for unknown reasons.  Inspecting chipper/dist/PhetioObject.d.ts, it does have the correct type.  So it seems that GravityAndOrbitsScene is not getting triggered to recompile.  Also, surprisingly, `tsc` succeeds even as `tsc -b` fails.

```
~/apache-document-root/main/gravity-and-orbits$ tsc
js/common/GravityAndOrbitsScene.ts:119:17 - error TS2339: Property 'runSomething' does not exist on type 'Tandem'.

119     this.tandem.runSomething();
                    ~~~~~~~~~~~~


Found 1 error.

~/apache-document-root/main/gravity-and-orbits$ tsc -b
~/apache-document-root/main/gravity-and-orbits$ 
```

Running `tsc -b --clean && tsc -b` for each of the 3 compiles correctly shows the missing method.  Therefore, it seems there is stale/bad intermediate data from the incremental or project build.

**Comment by samreid** [comment]
For now, perhaps we should use `--clean` for builds, since it is important to catch all the errors.  The code output is the same, but it can be important to error out if there is a type error.  But maybe we would catch it in the IDE in advance, but it seems flaky for the builds to not catch this.  Also, if we run `--clean` all the time, it will significantly hamper our workflow.

**Comment by samreid** [comment]
I wonder if this overlaps with the caveat in https://www.typescriptlang.org/docs/handbook/project-references.html#caveats.  Do we need to make sure noEmitOnError is truly enabled?

**Comment by samreid** [comment]
@jonathanolson and I discussed briefly.  The next steps for this issue are:

* Reproduce the problem above
* Create a self-contained reproducible case and see if it also has the problem
* Try more likely scenarios, such as introducing a type error in scenery or another dependency, and make sure it is picked up in the build
* Based on the above, search online to see if others had similar experience.  If not (but we do have a small reproducible example), then report a bug to TypeScript.

**Comment by samreid** [comment]
Surprisingly, the self-contained example does not exhibit this problem.  (Note that it is easier to switch between the tandem being a string vs any).  I'm not sure if I have the tsconfigs matching our style exactly, or where the essential difference might be.  Multiple layers to get to the dependency?

<details>

```diff

Index: test/typescript/test-dependencies/gravity-and-orbits/tsconfig.json
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/test/typescript/test-dependencies/gravity-and-orbits/tsconfig.json b/test/typescript/test-dependencies/gravity-and-orbits/tsconfig.json
new file mode 100644
--- /dev/null	(date 1631312913052)
+++ b/test/typescript/test-dependencies/gravity-and-orbits/tsconfig.json	(date 1631312913052)
@@ -0,0 +1,22 @@
+{
+  "references": [
+    {
+      "path": "../tandem"
+    }
+  ],
+  "compilerOptions": {
+    "module": "commonjs",
+    "target": "es5",
+    "sourceMap": true,
+    "composite": true,
+    "outDir": "./dist/",
+    "incremental": true,
+    "allowJs": true
+  },
+  "include": [
+    "GravityAndOrbitsScene.ts"
+  ],
+  "exclude": [
+    "node_modules"
+  ]
+}
\ No newline at end of file
Index: test/typescript/test-dependencies/gravity-and-orbits/GravityAndOrbitsScene.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/test/typescript/test-dependencies/gravity-and-orbits/GravityAndOrbitsScene.ts b/test/typescript/test-dependencies/gravity-and-orbits/GravityAndOrbitsScene.ts
new file mode 100644
--- /dev/null	(date 1631313092547)
+++ b/test/typescript/test-dependencies/gravity-and-orbits/GravityAndOrbitsScene.ts	(date 1631313092547)
@@ -0,0 +1,9 @@
+// Copyright 2021, University of Colorado Boulder
+import PhetioObject from '../tandem/PhetioObject';
+
+class GravityAndOrbitsScene extends PhetioObject {
+  constructor() {
+    super( {} );
+    this.tandem.runSomething();
+  }
+}
\ No newline at end of file
Index: test/typescript/test-dependencies/tandem/tsconfig.json
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/test/typescript/test-dependencies/tandem/tsconfig.json b/test/typescript/test-dependencies/tandem/tsconfig.json
new file mode 100644
--- /dev/null	(date 1631312555500)
+++ b/test/typescript/test-dependencies/tandem/tsconfig.json	(date 1631312555500)
@@ -0,0 +1,15 @@
+{
+  "compilerOptions": {
+    "module": "commonjs",
+    "target": "es5",
+    "sourceMap": true,
+    "composite": true,
+    "allowJs": true,
+    "outDir": "./dist/",
+    "incremental": true
+  },
+  "include": ["PhetioObject.js"],
+  "exclude": [
+    "node_modules"
+  ]
+}
\ No newline at end of file
Index: test/typescript/test-dependencies/tandem/PhetioObject.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/test/typescript/test-dependencies/tandem/PhetioObject.js b/test/typescript/test-dependencies/tandem/PhetioObject.js
new file mode 100644
--- /dev/null	(date 1631313103943)
+++ b/test/typescript/test-dependencies/tandem/PhetioObject.js	(date 1631313103943)
@@ -0,0 +1,16 @@
+// Copyright 2021, University of Colorado Boulder
+const DEFAULTS = {
+
+  tandem: 'optional'
+};
+
+class PhetioObject {
+  constructor( options ) {
+    this.tandem = 'its a tandem';
+
+    // other code
+    // this.tandem = options.tandem;
+  }
+}
+
+export default PhetioObject;
\ No newline at end of file

```

</details>

**Comment by samreid** [comment]
> Multiple layers to get to the dependency?

That did the trick.  I introduced an intermediate transitive dependency and now can reproduce the problem in an isolated case.  I'll commit this failing example to chipper/tests, then we can rename it to something sensible for sharing in a TypeScript issue.

**Comment by samreid** [comment]
Draft write up before creating a TypeScript issue:

# tsc -b incorrectly succeeds when there is a problem introduced by a transitive dependency

My team observed that `tsc -b` can incorrectly succeed when a problem is introduced by a transitive dependency.  In fact, `tsc -b` can give two different results for the same codebase: a build success or a build failure.  We created a self-contained reproducible example to demonstrate the problem.  This creates 3 projects using project references, where project A depends on project B and that, in turn, depends on project C.  There is one TypeScript file in project A, none in B and one in C.

## Step 1: Create the following 5 files, distributed into directories `projectA/`, `projectB/` and `projectC/`.

```ts
// projectA/A.ts
import C from '../projectC/C';

class A extends C {
  constructor() {
    super( {} );
    this.name.arbitraryFakeMethod();
  }
}
```

```json
// projectA/tsconfig.json
{
  "references": [
    {
      "path": "../projectB"
    }
  ],
  "compilerOptions": {
    "module": "commonjs",
    "target": "es5",
    "composite": true,
    "outDir": "./dist/",
    "incremental": true,
    "allowJs": true
  },
  "include": [
    "A.ts"
  ]
}
```

```json
// projectB/tsconfig.json
{
  "references": [
    {
      "path": "../projectC"
    }
  ],
  "compilerOptions": {
    "module": "commonjs",
    "target": "es5",
    "composite": true,
    "allowJs": true,
    "outDir": "./dist/",
    "incremental": true
  }
}
```

```ts
// projectC/C.ts
class C {
  name: string;
  constructor( options ) {
  }
}

export default C;
```

```json
// projectC/tsconfig.json
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es5",
    "composite": true,
    "allowJs": true,
    "outDir": "./dist/",
    "incremental": true
  },
  "include": [
    "C.ts"
  ]
}
```

## Step 2: clean and build project A

The clean step is not necessary on your first run, but we include it here in case you want to run through the steps again.
```
cd projectA
tsc -b --clean
tsc -b
```

In this case, the expected result is the same as the actual result, which is a build failure with this message:
```
A.ts:7:15 - error TS2339: Property 'arbitraryFakeMethod' does not exist on type 'string'.

7     this.name.arbitraryFakeMethod();
                ~~~~~~~~~~~~~~~~~~~


Found 1 error.
```

## Step 3: Fix the error by updating C.ts.

In C.ts, change `name: string;` to `name: any;`

### Step 4: build project A

```
tsc -b
```

Again, the expected result matches the actual result.  `tsc` succeeds with no output.

### Step 5. Reintroduce the problem in C.ts

In C.ts, change `name: any;` back to `name: string;`

### Step 6. Build Project A

```
tsc -b
```

Expected result: 

```
A.ts:7:15 - error TS2339: Property 'arbitraryFakeMethod' does not exist on type 'string'.

7     this.name.arbitraryFakeMethod();
                ~~~~~~~~~~~~~~~~~~~


Found 1 error.
```

Actual result: there is no output because `tsc -b` succeeds.

Discussion: Step 6 is building the same code as in Step 2.  However, in Step 2, the type error is correctly identified, but in Step 6 the type error is missed.  Note that changing project A to depend on C directly (not through B) correctly identifies the problem when running `tsc -b` in project A.

Is this behavior expected?  Is it a known problem?  Can it be corrected?

**Comment by samreid** [comment]
@jonathanolson and/or @zepumph can one of you please volunteer to review the prior comment, which is a draft issue to report to TypeScript?  You should follow the steps, see if you get the same result.  Are the instructions clear?  Do you have any ideas about the problem, or can you find any paper trail on it in https://github.com/microsoft/TypeScript/issues ?

**Comment by samreid** [comment]
The bug report template recommended testing against the nightly build.  I ran `npm install typescript@next` which gave `Version 4.5.0-dev.20210928`.  Since I did not install it globally, I used `node node_modules/typescript/bin/tsc` instead of just `tsc`. But for this `Version 4.5.0-dev.20210928`, following the steps above correctly identifies the problem in Step 6.  So presumably this problem has been fixed.  If we want to learn more about it, or are worried about it recurring, we could track down the version it changed it, and see if there is an associated issue.

I'll try some other versions:

Version 4.5.0-dev.20210922: fixed
Version 4.5.0-dev.20210822: fixed
Version 4.5.0-dev.20210810: fixed
Version 4.5.0-dev.20210807: fixed.  And that is the oldest day for this series.

**Comment by jonathanolson** [comment]
Verified https://github.com/phetsims/chipper/issues/1067#issuecomment-929802925, reproduced the buggy case, directions were quite clear!

**Comment by samreid** [comment]
I opened the issue in the TypeScript repo, linked above.  On hold while we await a response.

**Comment by samreid** [comment]
In the TypeScript issue, the behavior was identified as a bug, and it was labeled for investigation in TypeScript 4.6.  Self-unassigning until then.

**Comment by samreid** [comment]
We no longer use project references or `--build`, closing.
