### ISSUE TITLE
preload and phetLibs are parsed multiple times

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#107]
This appears 3 times in Gruntfile:
> pkg.preload.split( ' ' )

This appears 4 times in Gruntfile:
> pkg.phetLibs.split( ' ' )

Why not create these arrays once?

**Comment by jonathanolson** [comment]
Sounds great to just have them once.

**Comment by pixelzoom** [comment]
If we have them just once, we'll need to be careful that we don't modify them (which some use sites are currently doing.)

**Comment by pixelzoom** [comment]
On second thought... If we want to move long grunt task to .js files, it might be better to leave this alone, so we don't have to have global arrays.

**Comment by pixelzoom** [comment]
Since phetLibs and preload were converted to string arrays, this is no longer an issue. Closing.
