### ISSUE TITLE
Alternate brands should not require phet-io repos to be checked out

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1076]
As discussed on the Google Group, and in the slack #dev channel.  Alternate brands should not require phet-io repos to be checked out.  I'll push a fix for review shortly.

**Comment by samreid** [comment]
Fixed, and ready for review.  @jonathanolson can you please take a look?

**Comment by samreid** [comment]
@jessegreenberg can you please review this? It is is the name neighborhood as https://github.com/phetsims/chipper/issues/1077

**Comment by jessegreenberg** [comment]
Change looks good and builds with custom brands are working well.

**Comment by samreid** [comment]
Thanks, closing.
