### ISSUE TITLE
Rename "js" directories to "src"

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1078]
From https://github.com/phetsims/chipper/issues/1047, we would like to rename "js/" directories to "src/" so it is clearer they support multiple languages.

**Comment by samreid** [comment]
I'd like this to be discussed and approved in dev meeting before moving forward with it.  Also, it doesn't seem like a very high priority (risky, destabilizing for not much gain).

**Comment by samreid** [comment]
@zepumph said we should leave it as it is for a while, we are used to it and it is not worth the effort to change in the near future.  @jbphet said it would be confusing for newcomers to see *.ts code in a js/ folder.  We should look up what the convention is and follow it.  We saw a few projects using a "scripts" directory, but not sure if that is the convention.

**Comment by jonathanolson** [comment]
Decided 9/16/2021 closing as wont-fix until it becomes a problem that is costing time.
