### ISSUE TITLE
require-statement-match rule is broken

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#1079]
Discussed during discussion in https://github.com/phetsims/chipper/issues/1060.

**Comment by zepumph** [comment]
I had good luck finding the small bug that was causing that weird error in the package. I created a pull request for the fix. Given that, I think we should go all in on this package. I'm going to add this dependency, and add it to the eslintrc file turned off (since there will be many, many errors). I'll report back soon.

**Comment by zepumph** [comment]
I ran grunt lint-everything, and found 1272 errors, they looked something like this. I'm very pleased! I'll go ahead and commit this rule turned off.

```
C:\Users\path\git\wave-interference\js\diffraction\model\WavingGirlScene.js
  11:8  error  Default import name does not match filename "waving_girl_aperture_png.js"  consistent-default-export-name/default-import-match-filename

C:\Users\path\git\wave-interference\js\diffraction\view\DiffractionScreenView.js
  29:8  error  Default import name does not match filename "waving_girl_icon_png.js"  consistent-default-export-name/default-import-match-filename

C:\Users\path\git\wave-interference\js\interference\InterferenceScreen.js
  13:8  error  Default import name does not match filename "interference_screen_icon_png.js"  consistent-default-export-name/default-import-match-filename

C:\Users\path\git\wave-interference\js\slits\SlitsScreen.js
  13:8  error  Default import name does not match filename "slits_screen_icon_png.js"  consistent-default-export-name/default-import-match-filename

C:\Users\path\git\wave-interference\js\slits\view\PlaneWaveGeneratorNode.js
  15:8  error  Default import name does not match filename "plane_wave_source_png.js"  consistent-default-export-name/default-import-match-filename

C:\Users\path\git\wave-interference\js\waves\WavesScreen.js
  11:8  error  Default import name does not match filename "waves_screen_icon_png.js"  consistent-default-export-name/default-import-match-filename

C:\Users\path\git\wave-interference\js\waves\view\WavesScreenSoundView.js
  15:8  error  Default import name does not match filename "light-beam-loop-v5-eq-out-bass_mp3.js"  consistent-default-export-name/default-import-match-filename
  16:8  error  Default import name does not match filename "speaker-pulse-v4_mp3.js"                consistent-default-export-name/default-import-match-filename
  17:8  error  Default import name does not match filename "water-drop-v5-001_mp3.js"               consistent-default-export-name/default-import-match-filename
  18:8  error  Default import name does not match filename "water-drop-v5-002_mp3.js"               consistent-default-export-name/default-import-match-filename
  19:8  error  Default import name does not match filename "water-drop-v5-003_mp3.js"               consistent-default-export-name/default-import-match-filename
  20:8  error  Default import name does not match filename "water-drop-v5_mp3.js"                   consistent-default-export-name/default-import-match-filename

C:\Users\path\git\wave-interference\js\waves\view\WavesScreenView.js
  34:8  error  Default import name does not match filename "grab_mp3.js"     consistent-default-export-name/default-import-match-filename
  35:8  error  Default import name does not match filename "release_mp3.js"  consistent-default-export-name/default-import-match-filename

C:\Users\path\git\wave-on-a-string\js\wave-on-a-string\view\EndNode.js
  12:8  error  Default import name does not match filename "clamp_png.js"        consistent-default-export-name/default-import-match-filename
  13:8  error  Default import name does not match filename "ring_back_png.js"    consistent-default-export-name/default-import-match-filename
  14:8  error  Default import name does not match filename "ring_front_png.js"   consistent-default-export-name/default-import-match-filename
  15:8  error  Default import name does not match filename "window-back_png.js"  consistent-default-export-name/default-import-match-filename

C:\Users\path\git\wave-on-a-string\js\wave-on-a-string\view\StartNode.js
  26:8  error  Default import name does not match filename "wrench_png.js"  consistent-default-export-name/default-import-match-filename

C:\Users\path\git\wave-on-a-string\js\wave-on-a-string\view\WOASScreenView.js
  27:8  error  Default import name does not match filename "window-front_png.js"  consistent-default-export-name/default-import-match-filename

C:\Users\path\git\waves-intro\js\waves-intro-main.js
  16:8  error  Default import name does not match filename "light_screen_icon_png.js"  consistent-default-export-name/default-import-match-filename
  17:8  error  Default import name does not match filename "sound_screen_icon_png.js"  consistent-default-export-name/default-import-match-filename
  18:8  error  Default import name does not match filename "water_screen_icon_png.js"  consistent-default-export-name/default-import-match-filename

✖ 1272 problems (1272 errors, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.

Warning: 1272 errors and 0 warnings Use --force to continue.

```

Here are the repos that this effects:


- [ ] acid-base-solutions
- [ ] area-builder
- [ ] area-model-common
- [ ] arithmetic
- [ ] axon
- [ ] balancing-act
- [ ] balloons-and-static-electricity
- [ ] bamboo
- [ ] bending-light
- [ ] brand
- [ ] build-a-molecule
- [ ] build-a-nucleus
- [ ] build-an-atom
- [ ] capacitor-lab-basics
- [ ] charges-and-fields
- [ ] chipper
- [ ] circuit-construction-kit-ac
- [ ] circuit-construction-kit-black-box-study
- [ ] circuit-construction-kit-common
- [ ] circuit-construction-kit-dc
- [ ] color-vision
- [ ] coulombs-law
- [ ] counting-common
- [ ] density-buoyancy-common
- [ ] density
- [ ] dot
- [ ] energy-forms-and-changes
- [ ] energy-skate-park-basics
- [ ] energy-skate-park
- [ ] estimation
- [ ] expression-exchange
- [ ] faradays-law
- [ ] fluid-pressure-and-flow
- [ ] forces-and-motion-basics
- [ ] fourier-making-waves
- [ ] fractions-common
- [ ] friction
- [ ] gene-expression-essentials
- [ ] geometric-optics
- [ ] graphing-lines
- [ ] graphing-quadratics
- [ ] gravity-and-orbits
- [ ] gravity-force-lab-basics
- [ ] gravity-force-lab
- [ ] greenhouse-effect
- [ ] interaction-dashboard
- [ ] inverse-square-law-common
- [ ] isotopes-and-atomic-mass
- [ ] john-travoltage
- [ ] joist
- [ ] kite
- [ ] make-a-ten
- [ ] masses-and-springs-basics
- [ ] masses-and-springs
- [ ] molarity
- [ ] molecule-shapes
- [ ] neuron
- [ ] number-line-common
- [ ] number-line-distance
- [ ] number-line-integers
- [ ] number-line-operations
- [ ] number-play
- [ ] ohms-law
- [ ] pendulum-lab
- [ ] perennial-alias
- [ ] perennial
- [ ] phet-core
- [ ] phet-io-test-sim
- [ ] phetcommon
- [ ] plinko-probability
- [ ] projectile-motion
- [ ] proportion-playground
- [ ] quadrilateral
- [ ] ratio-and-proportion
- [ ] resistance-in-a-wire
- [ ] rutherford-scattering
- [ ] scenery-phet
- [ ] scenery
- [ ] simula-rasa
- [ ] states-of-matter
- [ ] tambo
- [ ] trig-tour
- [ ] utterance-queue
- [ ] vegas
- [ ] vibe
- [ ] wave-interference
- [ ] wave-on-a-string
- [ ] waves-intro

I'm not really sure how hard it would be to come up with a `--fix` hack on top of their rule for a one time use. Perhaps that is the way to go instead of manually doing it. That said, likely it is best to rename media files too.

**Comment by zepumph** [comment]
Ok, commented out above.

**Comment by zepumph** [comment]
I think it is time to check in with @jessegreenberg. Please let me know what you would like to do in combination with  https://github.com/phetsims/chipper/issues/1060

**Comment by samreid** [comment]
I'm seeing this error in sim code, even though I have `npm install` in chipper:

![image](https://user-images.githubusercontent.com/679486/131607992-60610e93-a558-4565-89d8-fc68b0c1bfc3.png)

**Comment by zepumph** [comment]
Ok. @jessegreenberg, please review our own implementation of `default-import-match-filename`. 

Using this patch + `grunt lint-everything`, you can see all the errors. Most likely these will need to be fixed manually.

```diff

Index: eslint/.eslintrc.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/eslint/.eslintrc.js b/eslint/.eslintrc.js
--- a/eslint/.eslintrc.js	(revision ceb0be752cff3809647289ea1b6dfe90decd8657)
+++ b/eslint/.eslintrc.js	(date 1630522948197)
@@ -943,10 +943,10 @@
     'no-spaced-func': 'error',
 
     // import variables for sounds and images must have the conventional suffix
-    'import-resource-variable-suffix': 'error'
+    'import-resource-variable-suffix': 'error',
 
     // TODO: comment back in when >1200 errors are fixed, see https://github.com/phetsims/chipper/issues/1079
-    // 'default-import-match-filename': 'error'
+    'default-import-match-filename': 'error'
     ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
   },
   env: {

```
What are you feeling about this?

**Comment by jessegreenberg** [comment]
This lint rule is working well, thanks @zepumph. I just removed a console.log, but I tested it and it is working well.

**Comment by jessegreenberg** [comment]
Should `default-import-match-filename` be a total replacement of `require-statement-match`? It is not catching this currently:
```
const _ = require( 'lodash' );
```

**Comment by jessegreenberg** [comment]
Nevermind, I see now that `default-import-match-filename` is for `imports` and `require-statement-match` is for require statements.
