### ISSUE TITLE
move long grunt tasks to .js files

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#108]
Gruntfile is getting a little large. It would be nice to move the larger grunt tasks to .js files, as was done for checkoutShas.js, et. al.  This would also discourage passing information between tasks via closures (see #102).

**Comment by pixelzoom** [comment]
This is done. All tasks are now in separate .js files, and any sharing is done via global.phet. Gruntfile.js consists of configuration initialization and registration of tasks.

I tested with a few sims, including one that uses mipmap (molecules-and-light).

Anyone want to do a quick review?

**Comment by pixelzoom** [comment]
No one time to review, so I'll close this. If any problems occur, please create a new issue.

**Comment by samreid** [comment]
The new Gruntfile.js looks great, nice work @pixelzoom

**Comment by pixelzoom** [comment]
Thanks @samreid.
