### ISSUE TITLE
The presence of chipper/dist will fail maintenance releases

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1080]
When running a maintenance release of Balancing Act for https://github.com/phetsims/balancing-act/issues/131, the build failed in the RC branch because chipper/dist failed lint.  

Notes from #1059 (duplicate):

Chipper has an eslint ignore directive for chipper/dist in master.  However, when doing an RC build, if chipper/dist exists, it will be linted.  This means we may need to do something like:

* rm -rf chipper/dist before doing a legacy build
* patch eslint ignore chipper/dist into legacy branches
* find another place to put the output

@jonathanolson can you please advise how we should proceed here?  Should we perform a maintenance release to add chipper/dist to eslint ignore?

**Comment by jonathanolson** [comment]
> Should we perform a maintenance release to add chipper/dist to eslint ignore?

That sounds good to me. Seems safe to do the maintenance process without deploying production versions. Should we collaborate on that?

**Comment by samreid** [comment]
Yes, let's maintenance release without deployments.  Can you please take the lead on that or schedule with me for collaboration?  I'll ping you on slack for potential collaboration.

**Comment by samreid** [comment]
Acid base solutions 1.2 did not have a problem.  Balancing act 1.2 could not be fixed with .eslintignore, but could be fixed with this patch:

<details>

```diff

Index: js/grunt/lint.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/grunt/lint.js b/js/grunt/lint.js
--- a/js/grunt/lint.js	(revision 0bb968a6b4758741404d97b9d0bc45743689b5b2)
+++ b/js/grunt/lint.js	(date 1630690288503)
@@ -28,7 +28,8 @@
   'phet-ios-app',
   'sherpa',
   'smithers',
-  'tasks'
+  'tasks',
+  'chipper'
 ];
 
 /**

```

</details>

**Comment by jonathanolson** [comment]
Affected release branch list:

```
skipping acid-base-solutions 1.2
  skipping area-builder 1.1
Added needed patch chipper to area-model-algebra 1.2
Added needed patch chipper to area-model-decimals 1.2
Added needed patch chipper to area-model-introduction 1.2
Added needed patch chipper to area-model-multiplication 1.2
  skipping arithmetic 1.0
Added needed patch chipper to atomic-interactions 1.2
  skipping balancing-act 1.1
Added needed patch chipper to balancing-act 1.2
Added needed patch chipper to balancing-chemical-equations 1.2
  skipping balloons-and-static-electricity 1.3-phetio
  skipping balloons-and-static-electricity 1.4
  skipping beers-law-lab 1.4
  skipping beers-law-lab 1.6-phetio
  skipping bending-light 1.1
Added needed patch chipper to blackbody-spectrum 1.0
Added needed patch chipper to build-a-fraction 1.0
Added needed patch chipper to build-a-molecule 1.0
  skipping build-an-atom 1.5-phetio
  skipping build-an-atom 1.6
Added needed patch chipper to build-an-atom 1.7
  skipping capacitor-lab-basics 1.6
  skipping charges-and-fields 1.0
  skipping charges-and-fields 1.0-phetio
  skipping circuit-construction-kit-black-box-study 1.1-phetio
Added needed patch chipper to circuit-construction-kit-dc 1.2
Added needed patch chipper to circuit-construction-kit-dc-virtual-lab 1.2
Added needed patch chipper to collision-lab 1.1
  skipping color-vision 1.1
  skipping color-vision 1.2-phetio
  skipping concentration 1.3
  skipping concentration 1.5-phetio
Added needed patch chipper to coulombs-law 1.0
Added needed patch chipper to curve-fitting 1.0
Added needed patch chipper to diffusion 1.0
Added needed patch chipper to energy-forms-and-changes 1.4
Added needed patch chipper to energy-skate-park 1.1
  skipping energy-skate-park-basics 1.1
  skipping energy-skate-park-basics 1.3-phetio
  skipping energy-skate-park-basics 1.4
  skipping equality-explorer 1.0
  skipping equality-explorer-basics 1.0
  skipping equality-explorer-two-variables 1.0
  skipping expression-exchange 1.1
  skipping faradays-law 1.3-phetio
Added needed patch chipper to faradays-law 1.4
  skipping forces-and-motion-basics 2.1-phetio
  skipping forces-and-motion-basics 2.3
Added needed patch chipper to fraction-matcher 1.2
Added needed patch chipper to fractions-equality 1.1
Added needed patch chipper to fractions-intro 1.0
Added needed patch chipper to fractions-mixed-numbers 1.0
Added needed patch chipper to friction 1.5
  skipping function-builder 1.0
  skipping function-builder-basics 1.0
Added needed patch chipper to gas-properties 1.0
Added needed patch chipper to gases-intro 1.0
  skipping gene-expression-essentials 1.0
Added needed patch chipper to graphing-lines 1.3
Added needed patch chipper to graphing-quadratics 1.1
  skipping graphing-quadratics 1.2
Added needed patch chipper to graphing-slope-intercept 1.1
Added needed patch chipper to gravity-and-orbits 1.4
  skipping gravity-and-orbits 1.5
Added needed patch chipper to gravity-force-lab 2.2
Added needed patch chipper to gravity-force-lab-basics 1.0
  skipping gravity-force-lab-basics 1.1
  skipping hookes-law 1.0
Added needed patch chipper to isotopes-and-atomic-mass 1.1
  skipping john-travoltage 1.4-phetio
  skipping john-travoltage 1.6
  skipping least-squares-regression 1.1
  skipping make-a-ten 1.0
  skipping masses-and-springs 1.0
Added needed patch chipper to masses-and-springs-basics 1.0
  skipping molarity 1.4
Added needed patch chipper to molarity 1.5
  skipping molecule-polarity 1.2
Added needed patch chipper to molecule-shapes 1.2
Added needed patch chipper to molecule-shapes 1.3
Added needed patch chipper to molecule-shapes-basics 1.2
  skipping molecules-and-light 1.3-phetio
Added needed patch chipper to molecules-and-light 1.5
Added needed patch chipper to natural-selection 1.2
Added needed patch chipper to natural-selection 1.3
  skipping natural-selection 1.4
  skipping neuron 1.1
  skipping number-line-distance 1.0
Added needed patch chipper to number-line-integers 1.1
Added needed patch chipper to number-line-operations 1.0
Added needed patch chipper to ohms-law 1.4
  skipping pendulum-lab 1.0
  skipping ph-scale 1.5
  skipping ph-scale-basics 1.5
  skipping plinko-probability 1.1
  skipping projectile-motion 1.0
  skipping proportion-playground 1.0
Added needed patch chipper to ratio-and-proportion 1.0
Added needed patch chipper to ratio-and-proportion 1.1
  skipping reactants-products-and-leftovers 1.2
  skipping resistance-in-a-wire 1.3-phetio
Added needed patch chipper to resistance-in-a-wire 1.6
Added needed patch chipper to rutherford-scattering 1.1
Added needed patch chipper to states-of-matter 1.2
Added needed patch chipper to states-of-matter-basics 1.2
  skipping trig-tour 1.0
  skipping under-pressure 1.1
  skipping unit-rates 1.0
Added needed patch chipper to vector-addition 1.0
Added needed patch chipper to vector-addition-equations 1.0
Added needed patch chipper to wave-interference 2.0
  skipping wave-on-a-string 1.1
Added needed patch chipper to waves-intro 1.1
```

**Comment by jonathanolson** [comment]
Also, we'll want to add it to the `.gitignore`, so we don't run into git issues.

**Comment by samreid** [comment]
Great idea!

**Comment by jonathanolson** [comment]
I've patched up the branches.

I was about to suggest not doing RCs (and leaving that for the next maintenance release), however... this actually seems like we'll potentially need to do production releases. If we build a typescript sim on build-server, it will add chipper/dist, then a future translation deployment of production sims without this patch would fail.

@samreid thoughts on this? @kathy-phet how much of a downside is it to do a production maintenance release (shouldn't take much testing time). Could we redeploy the apps with the freshly built versions?

**Comment by samreid** [comment]
I’m not sure about the maintenance releases--not sure how the translation process relates to the maintenance release process.  But we do need translations not to fail!  I have not yet tried a build on the build server, though bayes has done some TypeScript builds for CT and phettest.

**Comment by jonathanolson** [comment]
To clarify, say:

1. A user submits a translation on a sim with our typescript support. `chipper/dist` is created on the build-server.
2. A user submits a translation on a sim without our patch being production deployed (it uses the SHAs of the production version). It will then fail because of the existence of `chipper/dist`.

So we'd want to production-deploy to avoid this (or figure out another workaround). And we could consider turning off release-branch linting to avoid this in the future.

**Comment by samreid** [comment]
@jonathanolson and I discussed whether it would be useful to have a "latest release critical for the app" or a flag that lets us make maintenance releases without forcing downloads in the app.

I mentioned that we could always create another directory, like typescript/dist, but @jonathanolson said we do need to support being able to add directories in the future and chipper/dist sounds better for long-term.

@jonathanolson also pointed out a recent locale-related issue that may require maintenance releases anyways.

Until this is maintenance released, we have to be careful about doing TypeScript builds on the build server.

I mentioned we could add a workaround, like clearing chipper/dist after each build, but @jonathanolson pointed out that won't work well in other build cases, like bayes or even locally.  So getting a direct solution would be better than a workaround.

**Comment by samreid** [comment]
I slacked @kathy-phet and @jonathanolson 

> Hi Kathy, @jonathanolson and I recommend a production maintenance release to support an output folder in chipper.  The issue is https://github.com/phetsims/chipper/issues/1080#issuecomment-915499784. This would create a new maintenance release of many affected sims.  @jonathanolson also identified a locale problem in https://github.com/phetsims/chipper/issues/1093 which will require maintenance releases.  We wanted to get your approval before starting this, since with our current processes (based on our understanding), this will trigger updates from within the app.  Is there a way to deploy production releases without triggering updates from within the app?  Should we create an issue for that for future cases like this?

**Comment by kathy-phet** [comment]
@samreid @jonathanolson Yes, I believe this will definitely lead to an update of all sims within the apps. We would want to rebuild and redeploy the apps not long after this release is completed I think. Let's discuss tomorrow with @mattpen. Oliver is the lead on the iOS app, so he will understand the rebuild and deploy schedule of that version.

**Comment by samreid** [comment]
@jonathanolson said the next step for this is to make the RC deployments.  We will need to inform devs not to work in maintenance branches while that is happening.  We can do brief testing on the RCs.  But we need to do the production deploys before we can run the TypeScript build on the build server.

**Comment by mattpen** [comment]
As soon as the RC deployments are complete, we'll want to repackage the sims in the ios and android apps and republish.  The android app is in a stable state, and I can complete that at any time.  I'm not sure what the status of the ios app is, @oliver-phet has been coordinating with Kelly Bond on some improvements, I don't know if those have been published and if the app is in a stable state.

@samreid @jonathanolson - Do we have a deadline for completing these RC's? Can it wait until ON returns or should I investigate publishing an update?

**Comment by samreid** [comment]
The main time concern is that: when we run build with a sim that has `typescript:true` in package.json, the build server will create a directory chipper/dist which is not deleted at the end of the build (it is designed to be persistent across builds), and leaves output files that do not pass lint.  Older release branches have a rule that lints all of chipper, so they would fail building if chipper/dist is still there.  This is one of the last issues before we can enable TypeScript development for simulations, so would be good to do it soon.  I think it could wait another week though if necessary.  @jonathanolson is taking the lead in this maintenance release and should advise us on his projected timeline.  Do we need to coordinate the production releases with the rebuilds of the app (so they happen at about the same time)?.  Also, if we have a way to production release these sims without triggering app updates, we could proceed right away, but I don't know if we have that feature yet.

**Comment by mattpen** [comment]
> Do we need to coordinate the production releases with the rebuilds of the app (so they happen at about the same time)?

This would be ideal.  There will already be a delay since our current tooling doesn't allow us to package the MR in the app until after it is released to the public.  The delay arises from the time it takes to build and upload the package to the app stores, then submit it and wait for approval from Apple/Google.

We can tolerate some delay, but the longer we wait the more end users essentially will have to download the update twice (once using the PhET's sim update system, and once downloading the app update from the App/Play store).  Unfortunately, the best person to estimate volume/impact is ON (he is the most familiar with tracking stats in the stores).

> Also, if we have a way to production release these sims without triggering app updates, we could proceed right away, but I don't know if we have that feature yet.

No, we don't have this.  This feature was never considered in the designs for either app.

**Comment by jonathanolson** [comment]
Looks like there's going to be phet-io MR stuff later this week, will be pending on that.

**Comment by samreid** [comment]
From Sept 16, 2021. @jonathanolson confirmed that we need to publish the new sims before going ahead with TypeScript because of translations.  There is a QA issue above.  Once that clears, we are OK to move forward.

**Comment by jonathanolson** [comment]
@samreid this should be handled now!

**Comment by samreid** [comment]
@jonathanolson are the production versions published, and can we run a trial rc or production version of a typescript project?  Perhaps converting chains to typescript for this purpose?

**Comment by samreid** [comment]
On slack, @jonathanolson reported the publications were also completed and this is ready for testing.  Thanks @jonathanolson, I'll test this in https://github.com/phetsims/chipper/issues/1103.  Closing.

**Comment by zepumph** [comment]
Looks like a build failure just came in for diffusion, and it doesn't seem like this got picked up:

https://github.com/phetsims/chipper/blob/0dcc680922df28076301ea187742bc738bc4cdd4/.gitignore#L11-L10

Here is the email:

```
Build failure: Error: Build aborted, Error: grunt --allHTML --debugHTML --brands=phet --locales=yo in ../diffusion failed with exit code 1
stdout:
Running "lint-all" task

/data/share/phet/phet-repos/chipper/dist/axon/js/Action.js
  9:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/data/share/phet/phet-repos/chipper/dist/axon/js/animationFrameTimer.js
  2:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/data/share/phet/phet-repos/chipper/dist/axon/js/axon-phet-io-overrides.js
  1:1  error  Use the function form of 'use strict'  strict
  1:1  error  Strings must use singlequote           quotes

/data/share/phet/phet-repos/chipper/dist/axon/js/axon.js
  2:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/data/share/phet/phet-repos/chipper/dist/axon/js/BooleanProperty.js
  8:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/data/share/phet/phet-repos/chipper/dist/axon/js/CallbackTimer.js
  8:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/data/share/phet/phet-repos/chipper/dist/axon/js/createObservableArray.js
  8:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/data/share/phet/phet-repos/chipper/dist/axon/js/DerivedProperty.js
  9:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/data/share/phet/phet-repos/chipper/dist/axon/js/DynamicProperty.js
  97:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/data/share/phet/phet-repos/chipper/dist/axon/js/Emitter.js
  10:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

/data/share/phet/phet-repos/chipper/dist/axon/js/EnabledComponent.js
  10:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

. . . .

✖ 6433 problems (6433 errors, 0 warnings)
  1309 errors and 0 warnings potentially fixable with the `--fix` option.
Fatal error: 6433 Lint Errors

stderr:
(node:26581) Warning: Accessing non-existent property 'VERSION' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:26581) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
. Sim = diffusion Version = 1.0.5 Brands = phet Locales = yo Shas = {"comment":"# diffusion 1.0.5 Wed Sep 01 2021 08:38:06 GMT-0600 (Mountain Daylight Time)","assert":{"sha":"201c50a840e082354b013f4ab9e9d45006f98cfe","branch":"HEAD"},"axon":{"sha":"3f0943a68952c903024c190a43e4f3b9033e8c4e","branch":"HEAD"},"brand":{"sha":"40dd405ec950d10e15e957cbda3d97362e925bef","branch":"HEAD"},"chipper":{"sha":"0dcc680922df28076301ea187742bc738bc4cdd4","branch":"HEAD"},"diffusion":{"sha":"a5f9a58784f75964b8d57720c7aa9a4e1301912c","branch":"HEAD"},"dot":{"sha":"29e6b8aa840d467420c601c918556117dbaf9df2","branch":"HEAD"},"gas-properties":{"sha":"265b2874cd01603844a4d19839341a3fdfd44a68","branch":"HEAD"},"joist":{"sha":"3eea5f3f99c0e84eb517dddc5f46c04dc8d2bc5f","branch":"HEAD"},"kite":{"sha":"34e7bdb4379b8faab55c728fdd462d4477f77fe7","branch":"HEAD"},"phet-core":{"sha":"a4b79b885b6548940fe6a72dcd6a67693e6fb7e4","branch":"HEAD"},"phet-io":{"sha":"34b581c4106625082369457881195b6aa3028592","branch":"HEAD"},"phet-io-wrappers":{"sha":"4c05b62ef1fcbc8f09536d95abd9308ccaebb84b","branch":"HEAD"},"phetcommon":{"sha":"b82ae2142fe0874561941895a4b36ce6f91428b9","branch":"HEAD"},"phetmarks":{"sha":"8ff479ad6c1eeb1ee4667139d3173ba2ea4647ac","branch":"HEAD"},"query-string-machine":{"sha":"c4c6d494b474aeb14d700a8142da81776f62a2ba","branch":"HEAD"},"scenery":{"sha":"aba683b7a31dae1e355e1c23ad8fbee8602a34ee","branch":"HEAD"},"scenery-phet":{"sha":"0a029394e4d44182b730f63b54175f274157601b","branch":"HEAD"},"sherpa":{"sha":"4877464e8013ff1459091c854a8c2234c3d0e7d6","branch":"HEAD"},"sun":{"sha":"2956714d4645a2cffb6f87d2c6dbd545599d2843","branch":"HEAD"},"tambo":{"sha":"12fdefbf8ad194dc2cd6f05379e2345a68a4a866","branch":"HEAD"},"tandem":{"sha":"4fc21af570be99ba9ffbe6b13f5b5e85679df316","branch":"HEAD"},"twixt":{"sha":"ade8b222df3906d5a3298c4e3f12c72c54bda855","branch":"HEAD"}}
```

**Comment by jonathanolson** [comment]
Looks like somehow diffusion was skipped by the deployment process. Its release branch status works nicely, but it was never RC'ed or production'ed.

I'll be checking for other repos like this.

**Comment by samreid** [comment]
Please note https://github.com/phetsims/perennial/issues/253 was opened when translations failed for diffusion.

**Comment by samreid** [comment]
> I'll be checking for other repos like this.

Diffusion was reported in https://github.com/phetsims/chipper/issues/1080#issuecomment-973572810 and https://github.com/phetsims/perennial/issues/253, and as far as I know no others have been reported.

**Comment by zepumph** [comment]
Can we just patch the release branch's .gitignore? Or is the main hold up here that we don't know if there are other sims that were missed.

**Comment by zepumph** [comment]
>Can we just patch the release branch's .gitignore

Oh, I see, it is already patched, it just needs a release. I'll kick off an rc for diffusion right now.

**Comment by zepumph** [comment]
But even if it wasn't rc'd or production deployed, why is it failing, because when rebuilt, it is going to get the shas from diffusion's 1.0 branch, which has the chipper patch in it, right? So the next translation deploy would include `dist/` in its .gitignore. Or perhaps for translations it just checks out the exact same shas as the production version. . . . Hmmm.

**Comment by zepumph** [comment]
Published the RC here: 

https://phet-dev.colorado.edu/html/diffusion/1.0.6-rc.1/phet/diffusion_all_phet.html

I ran it and played with it for 30 seconds. I don't know how much more QA does for a spot check, but I also don't know all the pieces of the MR to test. Over to @jonathanolson to review the above comments, and then potentially just run the sim a bit, and then do a production deploy.

**Comment by jonathanolson** [comment]
Looks good! Production deployed.

This looks like the only case where this happened.
