### ISSUE TITLE
Use native "crypto" library instead of md5 package

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#1086]
From https://github.com/phetsims/chipper/issues/1084, why not use the build-in crypto library for our lint cache hashing?

**Comment by zepumph** [comment]
The example from https://nodejs.org/docs/latest-v8.x/api/crypto.html#crypto_crypto is working really nicely.

**Comment by zepumph** [comment]
@samreid can you give me a spotcheck please?

**Comment by samreid** [comment]
I tested the implementation and it seems to have the correct operational behavior. 
However, after reading https://stackoverflow.com/questions/5878682/node-js-hash-string, I'm wondering if we would prefer something like:

```js
crypto.createHash( 'md5' )
    .update( patterns.join( ',' ) )
    .digest( 'hex' )
```
