### ISSUE TITLE
How to generate/maintain tsconfig files compared to package.json?

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1087]
After #1070 there is duplication of project structure.  The dependencies are listed in package.json and also in tsconfig.json.  The tsconfig.jsons were generated from the dependencies in package.json, but then many had to be adjusted manually to get paths correct.  The goal is for there to be a 1:1 correspondence between these files, or at a minimum, a check that they have the same dependencies.

**Comment by samreid** [comment]
There are two "breadcrumbs" that may help with this issue.  One is generate.js which was used to batch generate all the tsconfig from the package.json.  The other is generateTSConfig, which is agnostic of the dependencies.

**Comment by zepumph** [comment]
I also wanted to note that at some point in the future, we will be able to move tsconfig.json structure into package.json (see https://github.com/microsoft/TypeScript/issues/32830).

**Comment by samreid** [comment]
`grunt update` now generates tsconfig.json, but there are some differences for some repos, such as brand.

**Comment by samreid** [comment]
See changes in https://github.com/phetsims/phet-io-sim-specific/issues/4 where we also needed a custom tsconfig for another repo.

**Comment by samreid** [comment]
We no longer need to generate tsconfig files, so I removed that part.  It is ok for different repos to have different structures. We can note that in tsconfig.  Closing.
