### ISSUE TITLE
Automate the maintenance patching steps

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1091]
From https://github.com/phetsims/phet-io/issues/1815 @pixelzoom said:

> Patching a dependency repo is more manual steps, and more opportunity for error, than patching the sim repo.

**Comment by samreid** [comment]
@zepumph said:

> The main problem that we are outlining here is that it is a time-consuming and error-prone process to adopt non-sim (dependency) changes into release branches. I have done exactly what @pixelzoom did multiple times (where I forget to push a dependency sha to github before kicking on the next `rc`), and each time it is an irksome gotcha. Instead of again trying to move proprietary PhET-iO IP into public repos, why don't we try to fix the actual problem head on. We don't say "it sure is annoying to patch scenery in the scenery repo, let's move that code to the sim." 
> 
> Let's develop tools and tasks that make changing dependencies for release branches much easier. We did it for pretty much everything else during chipper 2.0.
> 
> To start the discussion:
```
cd graphing-quadratics
grunt patch-dependency --repo=phet-io-client-guides --patchFileOrCherryPickSHA=4308758409789gf0ewvgfidhr
> checking out dependency
> applying sha in dependency
> pushing in dependency
> updating dependencies.json in sim repo
> pushing sim repo
> Done.
```

**Comment by jbphet** [comment]
In today's developer meeting we agreed that yes, it would be useful to have this supported by the maintenance release tools.  @jonathanolson has agreed to add it (thanks!).

**Comment by samreid** [comment]
@zepumph and @jonathanolson showed that this is already elegantly supported by the maintenance release tools. Can this issue be closed?

**Comment by pixelzoom** [comment]
> @pixelzoom does this seem like a good patch ...

A patch to what?  I'm not familiar with `grunt maintenance` or any of the `M.` function calls shown in https://github.com/phetsims/chipper/issues/1091#issuecomment-1520373444

**Comment by pixelzoom** [comment]
> ... Perhaps the best path forward would be to note that (generally), and the next time there are cherry picks to be made in dependency repos for a release, we should try out the MR process. How does that sound?

That sounds OK in theory, but not in practice.  Speaking for myself... When faced with the immediate need of patching a dependency repo, I'm unlikely to spend time (or have time to spend) on a new process. I will almost certainly use the existing manual process because I know that it works.  So I suspect that this issue will go nowhere until the tools and documentation are actually in place -- and that requires an upfront investment.

**Comment by zepumph** [comment]
>So I suspect that this issue will go nowhere until the tools and documentation are actually in place

Do you mean implemented and working on master? They definitely are, and are also being maintained and updated as problems arise. 

>and that requires an upfront investment.

Sounds good to me. Let's close this issue and we can let @pixelzoom learn the new process and documentation over in https://github.com/phetsims/perennial/blob/master/doc/automated-maintenance-process.md as time permits and space is made for it. Let me know if you ever want to pair on a process to get up to speed or try it out.
