### ISSUE TITLE
Why is docdash in sherpa but its dependency taffydb is in node_modules?

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1092]
From https://github.com/phetsims/phet-io-wrappers/issues/265 and recently discovered in https://github.com/phetsims/chipper/issues/1084#issuecomment-912046835.  If they cannot both be in sherpa, can they both be in node_modules?

**Comment by zepumph** [comment]
I could not find a way to get taffydb to be known from sherpa, so both are now added in package.json.

Ready to close?

**Comment by samreid** [comment]
This looks great, thanks!  I did a test build of gravity and orbits in phet-io and confirmed the JSDoc looked reasonable.  Closing.
