### ISSUE TITLE
Some released sims are not handling locale fallback gracefully

### ISSUE THREAD

**Issue by mattpen** [phetsims/chipper#1093]
Some sims are crashing when the _all file tries to load with an untranslated locale. e.g. https://phet.colorado.edu/sims/html/equality-explorer/1.0.13/equality-explorer_all.html?locale=ar_SA

Error:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'EQUALITY_EXPLORER/leftSideFull')
    at Object.window.phet.chipper.strings.get (equality-explorer_all.html?locale=wa:1227)
    at equality-explorer_all.html?locale=wa:1230
    at u (equality-explorer_all.html?locale=wa:1230)
    at l (equality-explorer_all.html?locale=wa:1230)
    at u (equality-explorer_all.html?locale=wa:1230)
    at l (equality-explorer_all.html?locale=wa:1230)
    at u (equality-explorer_all.html?locale=wa:1230)
    at l (equality-explorer_all.html?locale=wa:1230)
    at u (equality-explorer_all.html?locale=wa:1230)
    at l (equality-explorer_all.html?locale=wa:1230)
```

@jonathanolson found that this isn't happening in master.   @chrisklus found that some sims (like NLD and JT) do not have this bug in the released version.

This is affecting the virtual workshop, which relies on the locale fallback. This page has EE in an iframe that fails to load: https://phet.colorado.edu/ar_SA/teaching-resources/virtual-workshop/math?section=progressive-formalization

**Comment by jonathanolson** [comment]
List of release branches that look broken:

```
    acid-base-solutions 1.2 phet
    area-builder 1.1 phet
    arithmetic 1.0 phet
    balancing-act 1.1 phet
    balloons-and-static-electricity 1.3-phetio phet-io
    balloons-and-static-electricity 1.4 phet
    beers-law-lab 1.4 phet
    beers-law-lab 1.6-phetio phet-io
    bending-light 1.1 phet
    build-an-atom 1.5-phetio phet-io
    build-an-atom 1.6 phet
    capacitor-lab-basics 1.6 phet,phet-io
    charges-and-fields 1.0 phet
    charges-and-fields 1.0-phetio phet-io
    circuit-construction-kit-black-box-study 1.1-phetio phet-io
    color-vision 1.1 phet
    color-vision 1.2-phetio phet-io
    concentration 1.3 phet
    concentration 1.5-phetio phet-io
    energy-skate-park-basics 1.1 phet
    energy-skate-park-basics 1.3-phetio phet-io
    energy-skate-park-basics 1.4 phet
    equality-explorer 1.0 phet
    equality-explorer-basics 1.0 phet
    equality-explorer-two-variables 1.0 phet
    expression-exchange 1.1 phet
    faradays-law 1.3-phetio phet-io
    forces-and-motion-basics 2.1-phetio phet-io
    forces-and-motion-basics 2.3 phet
    function-builder 1.0 phet
    function-builder-basics 1.0 phet
    gene-expression-essentials 1.0 phet
    hookes-law 1.0 phet
    john-travoltage 1.4-phetio phet-io
    least-squares-regression 1.1 phet
    make-a-ten 1.0 phet
    masses-and-springs 1.0 phet
    molecules-and-light 1.3-phetio phet-io
    neuron 1.1 phet
    pendulum-lab 1.0 phet
    plinko-probability 1.1 phet
    projectile-motion 1.0 phet
    proportion-playground 1.0 phet
    resistance-in-a-wire 1.3-phetio phet-io
    trig-tour 1.0 phet
    under-pressure 1.1 phet
    unit-rates 1.0 phet
    wave-on-a-string 1.1 phet
```

**Comment by jonathanolson** [comment]
@samreid can you review the commit https://github.com/phetsims/chipper/commit/ef354141ba6396b1605f5b8ffda5c72fb17440fc (all of the sims had either this change in sim.html or chipper-strings.js).

I've applied it to all sims, I'll verify that things are working nicely (running verification, leaving myself assigned).

**Comment by jonathanolson** [comment]
Auditing the current sims:

```js
const checkoutMaster = require( './js/common/checkoutMaster.js' );
const puppeteerLoad = require( './js/common/puppeteerLoad.js' );
const build = require( './js/common/build.js' );
( async () => {
  const releaseBranches = await ReleaseBranch.getMaintenanceBranches();
  for ( let releaseBranch of releaseBranches ) {
    console.log( releaseBranch.toString() );

    const usesChipper2 = await releaseBranch.usesChipper2();
    const phetFolder = usesChipper2 ? '/phet' : '';
    const phetSuffix = usesChipper2 ? '_phet' : '';
    const url = `http://localhost/${releaseBranch.repo}/build${phetFolder}/${releaseBranch.repo}_en${phetSuffix}.html?debugger&locale=wa`;

    await releaseBranch.checkout( true );
    try {
      await build( releaseBranch.repo );
    }
    catch ( e ) {
      console.log( '  FAIL BUILD' );
    }
    console.log( ( await puppeteerLoad( url ) ) === null ? '  PASS' : '  FAILED' );
    await checkoutMaster( releaseBranch.repo, false );
  }
} )();
```

**Comment by jonathanolson** [comment]
Passed for all sims.

**Comment by samreid** [comment]
I reviewed the commit as requested in https://github.com/phetsims/chipper/issues/1093#issuecomment-916284027 and most everything looks great.  I checked out acid-base-solutions 1.2 and its shas, and built it, and put a debugger at the code in question and inspection seemed OK.  I did not know how to test with a different locale, since there is no "all" html at this level.  So when I tried ?locale=pt_XY it did not correctly fall back to locale=pt, but this is probably because I didn't know how to build the HTML file with all locales (if that exists in these 2015 SHAs).  @jonathanolson can you comment on that?  If this aspect been tested/verified, then I think my review is complete.

**Comment by jonathanolson** [comment]
> I did not know how to test with a different locale, since there is no "all" html at this level.

Add `--allHTML` to the grunt build.

**Comment by jonathanolson** [comment]
> If this aspect been tested/verified, then I think my review is complete.

I checked that, but it might be good to verify.

**Comment by samreid** [comment]
@jonathanolson and I tested the 1.2 branch with `--allHTML`, everything looks great and behaves as expected.

**Comment by jonathanolson** [comment]
@mattpen this should be patched now!

**Comment by samreid** [comment]
It seems this was addressed more than a year ago, closing.
