### ISSUE TITLE
tsconfig should set strict:true by default

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1097]
In slack #typescript, @zepumph said:

> I read the first chapter today, and wanted to especially note the section about which compiler options to use. We should discuss this in person likely, but to me it seems like we should eagerly turn on strictNullChecks, to make sure that our typing is supporting null/undefined cases explicitly. This feels important to do eagerly, even before noImplicitAny is set to true (while we are converting our codebase). It also isn't clear if our goal is eventually to convert every single file in our codebase to ts, because if not, it may limit our ability to eventually turn on strict compiler mode. Right?

**Comment by samreid** [comment]
I replied:

We probably won’t convert all simulations to ts.  And different repos can have different compiler options as necessary. For instance, gravity-and-orbits is getting close to full “strict:true” while we probably can’t turn that on in tsconfig-core.json for a while.  Turning on strictNullChecks may be difficult before we allow TS in common code, for instance, since we will need types from merge like in https://github.com/phetsims/chipper/issues/1094

But we will have to decide what is better: having strictNullChecks and things like that to help us where they can, knowing we will have to // @ts-ignore for a while, or leaving those off until we don’t have to ignore so many.

Another mid-ground would be to turn on “strict:true” or strictNullChecks temporarily while converting code, addressing as many cases as possible, then committing good code (but leaving the strict checks off in master).

How about we just go with strict: true as the default value in tsconfig-core.json, and if sims need to temporarily go with nonstrict, or ts-ignore, that is OK?

**Comment by samreid** [comment]
@zepumph replied:

> I think we should not do that right off the bat, though I will have a more informed opinion after using TS for a bit. My guess is that it will be nice to have strict off in general, and to just recommend turning it on in a specific sim repo to experiment and understand things better. Or perhaps that is ill conceived, because that would require Node or Property to be well typed out.

**Comment by samreid** [comment]
I personally found it useful to use `strict: false` as I was porting gravity-and-orbits and learning TypeScript.  As I got more familiar, I was able to turn on `strict:true`, and get better coverage.  Our proposed paradigm is that new simulation code will be in TypeScript and we won't try to convert all legacy projects to TypeScript.  For new projects, it makes sense to start with `strict: true` to develop well-typed code from the start.  The Vanderkam book says we will eventually want to end up with `strict: true` and it is recommended by TypeScript, so I think we should target that by default.  If repos need to opt-out, or we need to temporarily opt-out as we mature that will be OK, but I'll mark it as `strict:true` for now.  I should note that Gravity and Orbits was updated to support strict:true (with the help of a few any and type assertions).

**Comment by samreid** [comment]
I marked strict: true for now, but I'm aware this will warrant discussion.  Leaving open until it's time to discuss at developer meeting.

**Comment by samreid** [comment]
We discussed this at dev meeting today, and I revised the quick start guide based on a recommendation by @pixelzoom.

**Comment by samreid** [comment]
I moved it to "subgroups" in case @zepumph and I can make progress on it without the full dev team.  @zepumph let me know your thoughts.

**Comment by zepumph** [comment]
I'm going to just assign @samreid so that a subgroup discussion can happen. It would be best if I had been able to take things for a test drive before this conversation.

**Comment by samreid** [comment]
@zepumph can we move this issue forward asynchronously?  Or please reach out to me on slack if you'd like to schedule discussion.

**Comment by zepumph** [comment]
I think https://github.com/phetsims/chipper/commit/9b4a93508054d4c63c3f230c86cfd16facb43516 is best for now. Thanks for the ping. Ready to close?

**Comment by samreid** [comment]
Sounds good, thanks!  Closing.
