### ISSUE TITLE
Update supporting resources with TypeScript info

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#1098]
There are many places that will need to be updated on the project that are supplemental to actually writing TS code and building sims. I'll like a few here, and anyone feel free to add to it:

* How to setup IDE to support TypeScript (https://github.com/phetsims/phet-info/blob/5d80bb79f98f6ca9480888c094012a07d3dd8c15/ide/idea/setup.md)
  * To start I went to webstorm settings and then Languages & Frameworks -> TypeScript -> check TypeScript language services.
  * Codestyle updates?
  * Code coloring changes?
  * update live templates, perhaps we include a set of phet ones once they are converted to typescript.
* Getting started documentation.
* README files?

@samreid, I didn't see another issue with this sort of content, so I thought I'd add it, but please merge or move this where ever you would like. And add to it!

**Comment by samreid** [comment]
I've been writing a Quick Start Guide in https://github.com/phetsims/chipper/blob/master/doc/typescript-quick-start.md also in issue #1090.  I added a note to update the code style, which got better TypeScript support in April 2021.  I think live templates will be added later once we see what is needed.  I haven't investigated using WebStorm for compilation yet, maybe that will be a separate issue?  Anything else for this issue?
