### ISSUE TITLE
output-js should report how many errors there are

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#1099]
I'm thinking about how nice that is to have with linting.

**Comment by zepumph** [comment]
@samreid, how does that sound?

**Comment by samreid** [comment]
I was surprised to see that the number of lines in the stdout is the same as the number of errors, but it seems to match up at the moment.  I improved the formatting and think it's ready to close.  But I also won't be surprised if one day the tsc output is no longer "one error per line".
