### ISSUE TITLE
(Sims) Upgrade analytics.js to gtag.js (done via Tag Manager snippet)

### ISSUE THREAD

**Issue by mattpen** [phetsims/chipper#1102]
It looks like analytics.js is now outdated and we should switch to using gtag.js.  There is a guide here: https://developers.google.com/analytics/devguides/collection/upgrade/analyticsjs

**Comment by chrisklus** [comment]
Discussed during 9/23/21 dev meeting:

We are trying to understand how extensive these changes are.

MP/JO: Don't think this is a rush, analytics.js will likely be supported for a couple years.
SR: JO do you want someone else to learn and take the lead on this?
JO: If someone would like to pair and learn that would be great, but in general doesn't seem like a huge priority with what all is going on right now.
MK: Is there an EOL calendar for analytics.js?
MP: I couldn't find one (doesn't seem like there is yet), it just seems like the newest features from here on will be through gtag instead.
JO: okay, let's not worry about this until there is an EOL in sight or a bunch of console warnings or something.

We decided to make a calendar reminder to check in on this for at least a year out and revisit this then.

MP: Maybe we should switch to gtag the next time we need to add a new feature for analytics?

**Comment by chrisklus** [comment]
I made a calendar reminder to check on this issue in one year. If this upgrade happens before then (like the next time a feature is added), please notify me to cancel the reminder. Marking as on-hold and unmarking for dev meeting.

**Comment by oliver-phet** [comment]
Related to this, it sounds like we need to make a migration from Universal Analytics to Google Analytics 4 by July 1, 2023.

> [Google Analytics 4](https://notifications.google.com/g/p/AD-FnEyZ7Plcn_HfrXpKoQ6SymZ60Z3lFwfjXE0pbpgohcUKlhOsH7EtzMVzlFOJ9CFeafWuQOWUHtCTh_Cw-iWpmujq4DZo3C_E7sAj37-LGAhmZJifJBp53GRvlhu3f0nxsWXMAgXb2IRrMNJC4kKMzMPj1xgPz165LftyHJsrPm65Wkn1UgeN8zMe1HIuDCszU8CyHzRFPnqiejH7MMuabS-C35-rYh-HE-nO-t_ZnGZYzaM2_j0-dHGR3IBPzxRs3J9GPN3EuqWAemo-cGPrBRbCxk27ng) is our next-generation measurement solution, and is replacing Universal Analytics. On July 1, 2023, Universal Analytics properties will stop processing new hits. If you still rely on Universal Analytics, we recommend that you complete your move to Google Analytics 4.

I'm not exactly sure how the update to gtag.js is related to Google Analytics 4. 
https://support.google.com/analytics/answer/9964640?hl=en&ref_topic=11192706#zippy=%2Cin-this-article
https://support.google.com/analytics/answer/9310895?hl=en#zippy=%2Cin-this-article

**Comment by oliver-phet** [comment]
Internal tag manager integration will be tracked in: https://github.com/phetsims/phetcommon/issues/60
