### ISSUE TITLE
mipmap plugin

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#111]
From 2/24/15 dev meeting:

Create a mipmap plugin, with option to specify how many levels to generate. What it returns should work with scenery.Image.

Some possible syntaxes (we should look at other "standards" for plugin syntax):

```js
var mipmap = require(‘mipmap!MY_SIM/skater.png’);
var mipmap = require(‘mipmap!5!MY_SIM/skater.png’);
var mipmap = require(‘mipmap!MY_SIM/skater.png?levels=4’);
```

**Comment by jonathanolson** [comment]
There seem to be two require.js plugins embedding extra options in the require statements (most accept global options via the config file, which is probably unsuitable):
https://github.com/millermedeiros/requirejs-plugins uses requires like:
goog!visualization,1,packages:[corechart,geochart]
https://github.com/gamtiq/amd-proc-plugin uses requires like:
proc!json!some/folder/data.json!value^path.to.value

How is 'mipmap!MOLECULE_SHAPES/some-image.png,level=5' ?

**Comment by pixelzoom** [comment]
+1

**Comment by samreid** [comment]
Looks good @jonathanolson

**Comment by jonathanolson** [comment]
Chrome desktop for Balancing Act require.js: 2 seconds. With all mipmapped: 2.5 seconds. With buildCompatible mipmaps: 7 seconds.

Firefox desktop for Balancing Act require.js: 4 seconds. With all mipmapped: 4 seconds. WIth buildCompatible mipmaps: 5 seconds.

Basically, Firefox is much faster at manipulating pixel data, but slower at other things.

Will have data on built versions soon.

**Comment by jonathanolson** [comment]
Implementation and documentation complete. @samreid or @pixelzoom, let me know if you would like to review.

**Comment by pixelzoom** [comment]
Self assigned, I'll take a peek sometime next week.

**Comment by samreid** [comment]
Thank you @pixelzoom

**Comment by jonathanolson** [comment]
Balancing Act, loaded from what is presumably a cached version with the iPad 3:
No mipmaps: ~5 seconds, 1,498,473 bytes
All mipmaps, default levels (0-4): ~5.5 seconds, 2,039,949 bytes
No images (won't run): 1,014,433 bytes

**Comment by jonathanolson** [comment]
Above comment was typed in 3 days ago, and I forgot to hit "Comment".

**Comment by pixelzoom** [comment]
Looks good. Very nice documentation. Closing.
