### ISSUE TITLE
TypeScript Convention: Should we repeat type information in the JSDoc?

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1110]
For code using TypeScript, the types are described in the code.  In Effective TypeScript, Item 30 is "Don't Repeat Type Information in Documentation". Vanderkam recommends there being one source of truth for the types, and for types that are annotated in the code, they should not have types duplicated in the JSDoc.

I have been reluctant to strip out the JSDoc `@param` types in Gravity and Orbits and Bending Light, because it would be difficult to restore if we decide to want it back.  Let's discuss at an upcoming developer meeting once devs are up to speed on TypeScript and make sure we are on the same page about this.

**Comment by pixelzoom** [comment]
@samreid I'm almost positive that we decided not to repeat type information in JSdoc.  Can this be closed?
