### ISSUE TITLE
TypeScript mixins

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1127]
Related to https://github.com/phetsims/chipper/issues/1049, I set up a model of mixins following the new approach we have been using, which matches the recommended style in TypeScript https://www.typescriptlang.org/docs/handbook/mixins.html

Here's a patch that demonstrates this pattern using Node, PhetioObject and a ParallelDOM mixin, and a Node subtype of Panel:

<details>

```diff
Index: js/testts/MyNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/testts/MyNode.ts b/js/testts/MyNode.ts
new file mode 100644
--- /dev/null	(date 1634915520676)
+++ b/js/testts/MyNode.ts	(date 1634915520676)
@@ -0,0 +1,10 @@
+// Copyright 2021, University of Colorado Boulder
+
+import MyParallelDOM from './MyParallelDOM.js';
+import MyPhetioObject from './MyPhetioObject.js';
+
+class MyNode extends MyParallelDOM( MyPhetioObject ) {
+
+}
+
+export default MyNode;
\ No newline at end of file
Index: js/testts/MyPanel.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/testts/MyPanel.ts b/js/testts/MyPanel.ts
new file mode 100644
--- /dev/null	(date 1634916399665)
+++ b/js/testts/MyPanel.ts	(date 1634916399665)
@@ -0,0 +1,16 @@
+// Copyright 2021, University of Colorado Boulder
+
+import MyNode from './MyNode.js';
+
+class MyPanel extends MyNode {
+  constructor() {
+    super();
+
+    console.log( this.tandem );
+    console.log( this.divName );
+    // console.log( this.fakeAttribute );
+    this.focus();
+  }
+}
+
+export default MyPanel;
\ No newline at end of file
Index: js/testts/MyParallelDOM.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/testts/MyParallelDOM.ts b/js/testts/MyParallelDOM.ts
new file mode 100644
--- /dev/null	(date 1634916237068)
+++ b/js/testts/MyParallelDOM.ts	(date 1634916237068)
@@ -0,0 +1,21 @@
+// Copyright 2021, University of Colorado Boulder
+
+type Constructor = new ( ...args: any[] ) => {};
+
+function MyParallelDOM<TBase extends Constructor>( Base: TBase ) {
+  return class extends Base {
+    divName: string;
+
+    constructor( ...args: any[] ) {
+      super();
+      this.divName = 'my div';
+    }
+
+    // @public
+    focus() {
+      console.log( 'focus' );
+    }
+  };
+}
+
+export default MyParallelDOM;
\ No newline at end of file
Index: js/testts/MyPhetioObject.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/testts/MyPhetioObject.ts b/js/testts/MyPhetioObject.ts
new file mode 100644
--- /dev/null	(date 1634916307026)
+++ b/js/testts/MyPhetioObject.ts	(date 1634916307026)
@@ -0,0 +1,11 @@
+// Copyright 2021, University of Colorado Boulder
+
+class MyPhetioObject {
+  tandem: string;
+
+  constructor() {
+    this.tandem = 'hello!';
+  }
+}
+
+export default MyPhetioObject;
\ No newline at end of file

```

</details>

The usage site looks like this:

```ts
// Copyright 2021, University of Colorado Boulder

import MyNode from './MyNode.js';

class MyPanel extends MyNode {
  constructor() {
    super();

    console.log( this.tandem );  // Declared in the parent type
    console.log( this.divName ); // Declared in the mixin
    this.focus();                // Declared in the mixin
    // console.log( this.fakeAttribute ); // Not declared anywhere.  Fails type check
  }
}

export default MyPanel;
```
and has correct type checking and navigation in the IDE and correct type checking from `tsc`.  So this seems like a good pattern we can continue using.

The mixin declaration looks like this:

```ts
// Copyright 2021, University of Colorado Boulder

type Constructor = new ( ...args: any[] ) => {};

function MyParallelDOM<TBase extends Constructor>( Base: TBase ) {
  return class extends Base {
    divName: string;

    constructor( ...args: any[] ) {
      super();
      this.divName = 'my div';
    }

    // @public
    focus() {
      console.log( 'focus' );
    }
  };
}

export default MyParallelDOM;
```

If writing these files in *.js, they are inferred as `any` and while it passes the type checking, it also doesn't help.  So we would need to use *.ts for those, or investigate JSDoc to get it to not infer as `any` if that is possible.

**Comment by pixelzoom** [comment]
Has the pattern recommended in _Programming Typescript_ (p. 101) been evaluated?  The book claims that its “easy” to implement mixins/traits in TS, then has an extended example. There’s no mention of problems with `private` and `protected`.  I’m not very familiar with how/where/why PhET is using mixins/traits (my preference is to avoid them), so I don’t know how well the book’s approach matches PhET’s needs.

**Comment by samreid** [comment]
@jonathanolson can you please review the following 3rd party libraries and evaluate whether they would be a good match for our project?

https://github.com/tannerntannern/ts-mixer
https://github.com/fasttime/Polytype
https://github.com/bcherny/typed-trait/blob/master/src/index.ts

**Comment by samreid** [comment]
@jonathanolson and I discussed this today and feel like steps like these would be good:
* We aren't excited about ts-mixer since it doesn't correctly do `instanceof` checks
* Polytype has a low community support and looks like it is based on Proxy.  It may therefore have performance concerns.
* We don't remember why we avoided the legacy "alternative" mixin pattern in the handbook:  https://www.typescriptlang.org/docs/handbook/mixins.html. Maybe it is worth re-investigating.

The main problems with the approach in wilder at the moment are:
* It doesn't know the type in the mixin constructor: `( this as unknown as Node ).addChild( node );`
* Doesn't support private or protected attributes in the mixin.  Or we could try `#` to make these private, but there are downsides to that.  Maybe underscore is preferable and we would keep it private by convention.

We could always start with the wilder pattern then switch to another pattern if we find a better one.  We can't apply it in common code until common code is using TypeScript. Until then, we have the `d.ts` workaround and this new `Image` overrides workaround.

* We discussed that mixins aren't always the best solution, sometimes other approaches are better.  Mixins are not appropriate if you just want to have code in a different file and mix into a single core type.  But we do need to support mixins for some things like Imageable.
* We discussed using composition instead of mixins, but this has a maintainability burden and performance overhead--changing one thing in the mixin requires visiting all of the mixed sites.

**Comment by samreid** [comment]
I tested changing Imageable like so:

```ts
type Constructor = new ( ...args: any[] ) => {};
/**
 * @param {constructor} type
 */
const Imageable = <Base extends Constructor>( type: Base ) => {
  return class extends type {
```

Then I was able to create an Image, and access elements from Node, Image and Imageable, and `bodyNode instanceof Node` evaluated to `true`.  This pattern seems like it is working really well, and we should just get used to the constraints about private members and/or this-casting in the constructor.

**Comment by pixelzoom** [comment]
Can the same pattern that was used for `Imageable` also be used for `ParallelDOM` mixin?  Geometric Optics accesses fields and methods that Node gets from ParallelDOM, and I'm currently resorting to `@ts-ignore`.

**Comment by samreid** [comment]
It seems appropriate to use ts-ignore until we enable TypeScript in common code.  Self-unassigning for now.

**Comment by zepumph** [comment]
Hello mixin issue! We have not updated this in quite some time, but lots of progress has been made. @zepumph took the lead on https://github.com/phetsims/scenery/issues/1340, and @jonathanolson has converted Imageable, Paintable, and Poolable to typescript in the last quarter. We have established a pattern of how we want Typescript mixins to look (when possible) in our project, and documented it in https://github.com/phetsims/phet-info/blob/master/doc/phet-software-design-patterns.md#mixin-and-trait.

Tagging @jessegreenberg and @jonathanolson in case they have anything else to provide here. I'm going to close, but feel free to reopen if there are open questions or concerns that have not been addressed.
