### ISSUE TITLE
Update Studio build process to support Typescript

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#1129]
We don't yet have typescript in common code, but I wanted to note that we use webpack to compile the Studio wrapper, @jonathanolson @samreid what might need to be done to that process. It currently runs on `buildStandalone`. Is anything special needed to support this? Has a buildStandalone-supported repo been converted yet, even for testing?

**Comment by samreid** [comment]
After the above changes, studio using TypeScript common code can be supported by the following steps:

* Mark "typescript": true in studio/package.json
* run `grunt update`
* make sure index.html points to `<script type="module" src="../chipper/dist/studio/js/studio-main.js"></script>`

I tested this by converting StringProperty.js to StringProperty.ts and temporarily putting "typescript":true in studio/package.json and it seemed to work OK in built and unbuild modes.

**Comment by zepumph** [comment]
Thanks, this is awesome work. It seems like we are on hold until we support common code typescript.
