### ISSUE TITLE
Run tsc before running qunit tests

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1130]
In the precommit hooks, we should compile the TS code before running the qunit tests.  Otherwise tests could be running stale code.  Discovered in #1127

**Comment by samreid** [comment]
In investigating this, I found everything was running in parallel, because there were multiple `async` blocks.  I had to put them all in one `async` to get them to run sequentially.  Then it was straightforward to make sure the `tsc` step went before the qunit step.  I tested in circuit-construction-kit-common, because it is a TypeScript sim with unit tests.  @zepumph can you please spot check or review?

**Comment by zepumph** [comment]
Looks reasonable to me. If you can just confirm that you want linting to happen before ts compiling, then feel free to close.

**Comment by samreid** [comment]
Yes, linting first still sounds reasonable to me, thanks!  Closing.
