### ISSUE TITLE
Typescript Migration Team Learning

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/chipper#1132]
@jonathanolson: (investigate patterns in common code, in conjunction with layout work and go deeper with scenery, server side code if relevant)
@zepumph: (Port ratio and proportion sim - 60 hours)
@jessegreenberg: (Use in quadralateral/typscript)
@pixelzoom: (Geometric Optics)
@chrisklus: (Number Play)
@jbphet: (Learn language - 20 hours in October; probably Greenhouse Effect)
@mattpen: MP (if we adopt convert React and Build Server ... convert Build Server after we decide to or not on sim side)
@samreid: I've already ported Gravity and Orbits and Bending Light, and will probably port CCK as part of phetsims/circuit-construction-kit-common#749. I'll provide code reviews and pairing support, and help with patterns, tooling, etc.

**Comment by pixelzoom** [comment]
@zepumph's link in the previous comment no longer works. And a `dev:typescript` label has been added to all repos.  So the list of typescript issues for all repos is: https://github.com/issues?q=is%3Aopen+is%3Aissue+user%3Aphetsims+label%3Adev%3Atypescript+

**Comment by samreid** [comment]
Everyone is learning TypeScript as we go, and has been approved time for porting code, learning TypeScript and discussing conventions.  I think this issue can be closed.
