### ISSUE TITLE
Some common code repo unit tests are not in any tsconfig

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1134]
Discovered in https://github.com/phetsims/dot/issues/112, some unit tests such as dot are not covered in any tsconfig.  For instance, try changing LinearFunctionTests.js and see that it doesn't recompile.

**Comment by samreid** [comment]
In the commit, I demonstrated a way to add the unit test layer into a common code repo.  This defines a new tsconfig file in the sim repo that adds the unit tests.  The primary "tsconfig.json" file is the one which should be used as a standard dependency (for client usage).  I'm inclined to discuss this proposal with @zepumph before I apply it throughout the common code repos.  We should also consider that some repos may have a "demo" main that has downstream dependencies, without having tests.  So I'm not sure what the 2nd layer of tsconfig should be called (if we have a general term for it).

**Comment by zepumph** [comment]
Honestly, I think that making things as explicit as possible to start sounds best. One tsconfig for the library, another for the tests, and another for the demo (which likely includes joist). 

In that case, it seems like it would be easiest to potentially create tsconfig files automatically, because a default demo and tests config file will likely be quite straight forward.


Do you have an opinion on the matter?

**Comment by samreid** [comment]
The 2 prior commits demonstrate how to fix this for scenery-phet.

**Comment by samreid** [comment]
I said on slack:

> Some common code repos are showing on CT as e.g., ModuleNotFoundError: Module not found: Error: Can't resolve '../chipper/dist/scenery-phet/js/scenery-phet-main.js' .  This problem is being tracked in https://github.com/phetsims/chipper/issues/1134 and I demonstrated how to solve it for scenery-phet.  I have to leave for an appointment this morning and probably won’t be able to solve these before I go.  This is also a problem because commits on common code repos will probably fail due to the unit tests not working.  I’ll work on it as soon as I can but if you need to push common repos before it’s fixed, please (a) disable commit hooks or (b) follow the pattern in #1134 for scenery-phet.

**Comment by samreid** [comment]
Also, I'm thinking of inverting this so that, say, sun/tsconfig.json has everything.  And sun/tsconfig-core has only core files needed by dependencies.  This would make it easier to `cd sun` and `tsc -b` or `tsc`

**Comment by zepumph** [comment]
This seems reasonable to me, I'm curious though if the `-all.json` should reference its main file? I see you did do this in vegas:

https://github.com/phetsims/vegas/blob/ed76e36b8aec43ff7f4b7e2e6ea30484f9c8ad42/tsconfig-all.json#L7-L9

But not in twixt. Is that purposful?

**Comment by samreid** [comment]
I ran into cases where there were problems separating the tests and demos, so I started combining them.  @zepumph does https://github.com/phetsims/chipper/issues/1134#issuecomment-974111738 seem OK to you?  Each common code repo would have "tsconfig-core.json" that would be for dependencies, and "tsconfig.json" that has everything, including unit tests.

**Comment by zepumph** [comment]
Yes very good, thanks.

**Comment by samreid** [comment]
New columns are showing the same problem on CT.  Oh, it is because CT isn’t doing compile all.  So it will be corrected by the proposal in https://github.com/phetsims/chipper/issues/1134#issuecomment-974263087.  Or it could be safer to just compile everything if anythnig changed.   I think we did that for phettest on pull-all.

**Comment by samreid** [comment]
@zepumph said 

> Yes agreed, and that should definitely happen for CT per snapshot pull.

**Comment by samreid** [comment]
I decided to name as "tsconfig-module.json" so it wouldn't conflict with "core" file everything extends.

**Comment by samreid** [comment]
After the commits, all central (scenery,sun,joist,phetocommon, etc) common code repos have a tsconfig that includes all demos and tests.  This allows us to run `tsc` from those directories to build the tests, demos and everything, so that integrates with our tooling nicely.  There is a separate tsconfig-module.json that includes only the core dependencies that a user would need (no demos or tests).  I'll open a separate issue for addressing this for downstream common repos, such as "circuit-construction-kit-common" "area-builder-common" etc.

**Comment by samreid** [comment]
I also cleaned up axon and tandem, so they each have reasonable tsconfigs.  Remaining work to be done in https://github.com/phetsims/chipper/issues/1154, closing.

**Comment by samreid** [comment]
CT is showing a lot of red for these commits around https://github.com/phetsims/axon/commit/e68e11143568aba14a6fe945cd941af54d7d083e

**Comment by samreid** [comment]
It looks like it was caused by case sensitivity problems, where "*test*" on my Mac ignored "*Test*", it did not on the linux machine.  Since mac and linux are case insensitive for this search, it would probably not have affected developers.  But it is nice to clear this up on CT.  I wonder if there is a way to specify case-insensitive patterns in tsconfig globs.  We will have to wait and see if the next column on CT is clear.

**Comment by samreid** [comment]
OK that seems fixed.  The main problem I've had with this organization is that you cannot run `tsc -b` combined with `--project`.  So there is no easy way to build, say, dot as a module.  One alternative would be to move `dot/tsconfig-module.json` to `dot/tsconfig/module/tsconfig.json` or maybe `dot/module/tsconfig.json`, but maybe we will wait until we have more of a need for this.  Or we could add things in chipper/tsconfig to point to these as needed.  Maybe I'll create a side issue about this.
