### ISSUE TITLE
Prototype sims have "published" README.md files.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#1136]
I deployed a prototype version of Geometric Optics using the steps in [Production deployments](https://github.com/phetsims/phet-info/blob/master/deployment-info/chipper-2.0.md#prototype-deployments).

Some time later, I noticed that https://github.com/phetsims/geometric-optics/blob/master/README.md was updated to a published README.md, indicating that the sim has been published and (more importantly) its webpage is visibile (and a link is included in the README.md). 

I looked at the README.md for all prototype at https://phet.colorado.edu/en/simulations/prototypes.  Here's what I discovered about their README.md files:

| sim | README.md type | responsible dev |
| --- | --- | --- |
density | unpublished | @jonathanolson |
cck-ac | unpublished | @samreid |
geometric-optics | published | @pixelzoom |
greenhouse-effect | published | @jbphet |

Questions:

(1) Is this a problem? It seems like it to me.

(2) Why is there a difference here?  Were density and cck-ac published using a different process?

(3) Should geometric-optics  and greenhouse-effect  README.md be regenerated using `grunt unpublished-README` ?

(4) Should [Production deployments](https://github.com/phetsims/phet-info/blob/master/deployment-info/chipper-2.0.md#prototype-deployments) be updated to include information about this problem?

(5) Should we great a `grunt prototype` task, which handles this discrepancy?  It might be easier than relying on documentation, which currently says "do `grunt production`, then deal with these differences".

**Comment by pixelzoom** [comment]
I fixed the README.md for geometric-optics using `grunt unpublished-README`.

Assigning to @jbphet to decide if he wants to do the same for greenhouse-effect.

**Comment by pixelzoom** [comment]
> (5) Should we great a `grunt prototype task`, which handles this discrepancy? It might be easier than relying on documentation, which currently says "do `grunt production`, then deal with these differences".

Since PhET seems to be on a path where publishing prototypes will occur more often, I’d really like to have a `grunt prototype` task for deploying them.  If that’s `grunt production` internally, that’s fine.  But `grunt prototype` should handle the differences between “production” and “prototype”.  We currently need to document those difference, and handle them manually.

**Comment by jbphet** [comment]
I regenerated the unpublished version for Greenhouse, since I'm uncomfortable with there being an incorrect link in it.  I'll unassign this, and we can discuss next steps in the developer meeting.

**Comment by pixelzoom** [comment]
I was bitten by this again, when I published normal-modes prototype on 11/15.  Reverted in the above commit.

**Comment by pixelzoom** [comment]
All prototypes now have an unpublished README.md.

I've reorganized and fleshed out the [Prototype deployment documentation](https://github.com/phetsims/phet-info/blob/master/deployment-info/chipper-2.0.md#prototype-deployments), and added a step to run `grunt unpublished-README`.  So I think our dev-meeting time would be better spent discussing phetsims/chipper#1136.

Closing.

**Comment by pixelzoom** [comment]
Reopening.  It looks like @samreid ran `grunt update` and undid the fixes to geometric-optics and greenhouse-effect.  @samreid please revert.

**Comment by samreid** [comment]
Thanks, I reverted those repos.  Can you please spot check?  Anything else to do here?

**Comment by pixelzoom** [comment]
👍🏻 closing
