### ISSUE TITLE
What needs to be done to convert gravityAndOrbits.js et. al. to TS?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#1138]
Each sim has a Namespace file, e.g. gravityAndOrbits.js, circuitConstructionKitAc.js.  I asked why those files had not been converted to .ts.  According to @samreid, `grunt update` regenertes the .js file. 

I find it odd that `grunt update` gets involved with to the Namespace file. It is created from simula-rasa, and contains nothing that seems to be of interest to grunt update.  I wonder it’s regenerated because @jonathanolson has puts additional stuff in the Namespace file.

In any case, we should determine what needs to be done to convert this file to TS.

**Comment by samreid** [comment]
It looks like the namespace file is being created by `modulify.js`, which has this code:

```js
  // Create the namespace file, if it did not already exist
  const packageObject = grunt.file.readJSON( `../${repo}/package.json` );
  if ( fs.existsSync( `../${repo}/${repo}-strings_en.json` ) && packageObject.phet && packageObject.phet.requirejsNamespace ) {
    await createStringModule( repo );

    const namespace = _.camelCase( repo );
    const namespaceFile = `../${repo}/js/${namespace}.js`;
    if ( !fs.existsSync( namespaceFile ) ) {
      await createNamespaceModule( repo );
    }
  }
```

If we eliminate that part of modulify, then individual sims can convert to *.ts as desired.  @pixelzoom does this sound like a good plan to you?

**Comment by pixelzoom** [comment]
It sounds OK to me. But I'm not clear on why this would have been needed in the first place. When would a namespace file be missing?  Git history indicates that @jonathanolson was invovled with that code, so you might want to check with him.

**Comment by samreid** [comment]
It seems it was introduced for the modulify ES6 conversion steps.  I'll wait to hear from @jonathanolson if it's safe to remove that step from modulify.

**Comment by zepumph** [comment]
I  implemented the above before I found this issue/discussion. Basically we can create a default js if we don't already have a js OR a ts file for both string module and namespace file. Does that seem like an improvement? My main thought was just to get `grunt update` (a command I run quite often) from creating junk I have to revert each time.

**Comment by jonathanolson** [comment]
It seems safe to remove.

**Comment by samreid** [comment]
The guard added by @zepumph seems reasonable to me.  @pixelzoom does that seem good to you, or should we just eliminate that altogether?

**Comment by pixelzoom** [comment]
I have no idea what "the guard" is, and I'm having a difficult time interpretting https://github.com/phetsims/chipper/issues/1138#issuecomment-965816612.  

My recommendation is to remove namespace.js generation from `grunt update`. I've heard no reason why it needs to exist.

**Comment by samreid** [comment]
To clarify, @zepumph added a guard that the namespace.js file is only generated if it does not already exist (in typescript or javascript).  I'll remove it altogether.

**Comment by samreid** [comment]
Removed, @pixelzoom would you like to review?

**Comment by pixelzoom** [comment]
I'm not at all familiar with modulify.js.  That said, I insepected the commits, ran `grunt modulify`, and I didn't experience any problems.  So closing.
