### ISSUE TITLE
Evaluate integration and usage of typescript-eslint

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1146]
@pixelzoom pointed out that we don't have any enforceable convention about semicolons appearing after a type declaration statement like:

```ts
9  const FocalLengthControlValues = [ 'direct', 'indirect' ] as const;
10 type FocalLengthControlEnum = ( typeof FocalLengthControlValues )[number]
```

He said:

> Line 10 is missing a semicolon. WebStorm doesn’t complain, grunt lint doesn’t complain, and pre-commit hooks allow me to commit it.  If I remove the semicolon at the end of line 9, it is identified as a lint error.  Any idea what’s going on here? Are type definitions not being linted?

**Comment by samreid** [comment]
I replied:

I’m seeing some examples in the TypeScript handbook where type declarations have ; and some do not.  Perhaps there is no lint rule for it as part of our eslint setup.

It looks like ts-lint adds a rule for that: https://palantir.github.io/tslint/rules/semicolon/

I’m not surprised that our ESLint rules don’t know what to do about it.

**Comment by pixelzoom** [comment]
https://palantir.github.io/tslint/ says:

> :warning: TSLint has been deprecated as of 2019. Please see this issue for more details: [Roadmap: TSLint → ESLint](https://github.com/palantir/tslint/issues/4534). [typescript-eslint](https://typescript-eslint.io/) is now your best option for linting TypeScript.

**Comment by pixelzoom** [comment]
The typescript-eslint rule for semicolons is https://typescript-eslint.io/rules/semi.

And there are a lot of other rules that look interesting, https://typescript-eslint.io/rules/.

**Comment by samreid** [comment]
We are adding support for TypeScript ESLint in other issues, closing.
