### ISSUE TITLE
Enable TypeScript for every repo so it can be used in common code

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1148]
At today's dev meeting, we agreed to enable typescript for every repo so it can be used in common code.

In slack, I said:

> grunt update is set to create a *.ts string file for repos that have typescript enabled.  Can I output the *.ts strings for all repos?  Or do we want that to remain *.js in the majority of repos?
> 
> It seems best to keep things consistent, and I’m seeing the *.ts file can be used nicely in *.js files.  So I’ll plan to go forward with *.ts string files unless/until I hear otherwise.

@jonathanolson replied:

> Sounds good to me

Here are some steps:
- [x] Remove isRepoTypeScript
- [x] grunt update sims
- [ ] Add phet-types.d.ts to tsconfigs
- [x] Message the google group.
- [x] Message the slack channel.

**Comment by samreid** [comment]
> Add phet-types.d.ts to tsconfigs

I'm not sure that step is necessary, and not sure how to test.

@zepumph or @jonathanolson can you please review the chipper and perennial commits, and spot check 1-2 sim repo commits?

**Comment by jonathanolson** [comment]
Commits look good based on my understanding. getStringMap whitespace dependency sounds tricky, if we change how the code is formatted under chipper/dist (but looks correct for behavior right now).

**Comment by samreid** [comment]
Thanks, closing.
