### ISSUE TITLE
WARNING: You are currently running a version of TypeScript which is not officially supported

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#1149]
`grunt` is complaining about TypeScript version, see below.   I was using TypeScript 4.4.4, and now my development machines have updated to 4.5.2 in chipper/node_modules/typescript/bin/tsc.  I did not explicity update or run `npm update`, so I'm guessing that this was done by some build task. 

```
% type tsc
tsc is aliased to `node /Users/cmalley/PhET/GitHub/chipper/node_modules/typescript/bin/tsc'
%  tsc --version
Version 4.5.2
% cd geometric-optics
% grunt
Running "lint-all" task
=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.5.0

YOUR TYPESCRIPT VERSION: 4.5.2

Please only submit bug reports when using the officially supported version.

=============

Running "report-media" task
...
```

**Comment by samreid** [comment]
This problem was introduced because typescript `npm updated` to a version incompatible with `@typescript-eslint/parser`.  I recommend fixing this problem by:
(a) updating to a version of `@typescript-eslint/parser` that is compatible with latest typescript
(b) updating to latest typescript
(c) removing the carets and tildes from both so they won't update unexpectedly

**Comment by samreid** [comment]
I did (a)-(c) above.  I'll mention it to slack.

**Comment by samreid** [comment]
I said:

> In https://github.com/phetsims/chipper/issues/1149 we identified an incompatibility between typescript and the typescript-eslint-parser.  I updated both versions and set them to not auto-update any more.  Please npm install in chipper at your convenience.

@zepumph or @pixelzoom would you like to review and comment?

**Comment by pixelzoom** [comment]
> Please npm install in chipper at your convenience.

There are warnings (repeated multiple times) that seem to be relevant, see below.  I also tried removing node_modules, then doing a fresh `npm install`, with the same result.  Are we going to see these warnings everytime we do npm in chipper?

```
% cd chipper
% npm install
npm WARN notsup Unsupported engine for @typescript-eslint/parser@5.4.0: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"14.16.1","npm":"6.14.12"})
npm WARN notsup Not compatible with your version of node/npm: @typescript-eslint/parser@5.4.0
...
```

**Comment by samreid** [comment]
I reproduced the warnings above.  Two ways forward could be:

(a) downgrade `@typescript-eslint/parser` and `typescript` accordingly
(b) ask developers to update to node `^14.17.0`

To me (b) sounds preferable and forward-looking.

In either case, I still think we should remove carets and tildes from the package.json reference to typescript and its dependencies.

**Comment by pixelzoom** [comment]
I don't know the implications of (a). I'd be OK with (b).

**Comment by samreid** [comment]
I updated to:

```
node v14.18.1
npm v6.14.15
```

And when running npm install in chipper, I got these messages:

```
~/apache-document-root/main/chipper$ npm install
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.

> puppeteer@10.4.0 install /Users/samreid/apache-document-root/main/chipper/node_modules/puppeteer
> node install.js

Downloading Chromium r901912 - 116.3 Mb [====================] 100% 0.0s 
npm WARN acorn-import-assertions@1.8.0 requires a peer of acorn@^8 but none is installed. You must install peer dependencies yourself.

added 841 packages from 526 contributors and audited 842 packages in 56.955s

103 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

So perhaps we should open a side issue about `babel-eslint is now @babel/eslint-parser.`, recommend developers to upgrade to node v14.18.1 & npm v6.14.15, and close this issue.  Sound good @pixelzoom?

**Comment by pixelzoom** [comment]
> ... So perhaps we should open a side issue about babel-eslint is now @babel/eslint-parser., recommend developers to upgrade to node v14.18.1 & npm v6.14.15, and close this issue.  

I have not changed my node, npm, or tsc versions, still:

```
% node --version
v14.16.1
% npm --version
6.14.12
% tsc --version
Version 4.5.2
```

After doing a pull-all.sh, `cd chipper; npm install` reports no problems.   

I'm confused. Why do we need to upgrade node/npm. Why did the warnings go away?  And why don't I see the new warnings that @samreid sees?

**Comment by samreid** [comment]
I ran those commands (without clearing node_modules) and got this result:

```
~/apache-document-root/main$ node --version
v14.18.1
~/apache-document-root/main$ npm --version
6.14.15
~/apache-document-root/main$ tsc --version
Version 4.5.2
~/apache-document-root/main$ cd chipper/
~/apache-document-root/main/chipper$ npm install
npm WARN acorn-import-assertions@1.8.0 requires a peer of acorn@^8 but none is installed. You must install peer dependencies yourself.

audited 842 packages in 2.231s

101 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities



   ╭───────────────────────────────────────────────────────────────╮
   │                                                               │
   │      New major version of npm available! 6.14.15 → 8.3.0      │
   │   Changelog: https://github.com/npm/cli/releases/tag/v8.3.0   │
   │               Run npm install -g npm to update!               │
   │                                                               │
   ╰───────────────────────────────────────────────────────────────╯


```

**Comment by samreid** [comment]
After updating acorn in https://github.com/phetsims/chipper/issues/1171, I cleared node_modules and ran `npm install`.  It was the cleanest output I've seen in a long time:

```
~/apache-document-root/main/chipper$ npm install

> puppeteer@10.4.0 install /Users/samreid/apache-document-root/main/chipper/node_modules/puppeteer
> node install.js

Downloading Chromium r901912 - 116.3 Mb [====================] 99% 0.0s 
added 842 packages from 526 contributors and audited 843 packages in 15.224s

101 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

I'm not sure how else to investigate here, unless we want to try various versions of node or npm.  @pixelzoom can this issue be closed?

**Comment by pixelzoom** [comment]
> ... But there was no upgrade warning when running `npm install`. It seems very mysterious.

Still mysterious to me too.  But I don't think it's worth continuing to investigate, so closing.
