### ISSUE TITLE
Clean up and document async callbacks and processes in Gruntfile

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#115]
It's quite messy.

**Comment by pixelzoom** [comment]
Related issues:
https://github.com/phetsims/chipper/issues/108
https://github.com/phetsims/chipper/issues/107
https://github.com/phetsims/chipper/issues/102

**Comment by pixelzoom** [comment]
After tasks were broken out into .js files, this doesn't feel like it's an issue. Closing.
