### ISSUE TITLE
tsc -b --watch must be restarted after pulling changes to tsconfig files?

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#1150]
While I was confirming fixes in https://github.com/phetsims/chipper/issues/1134#issuecomment-974111738 and commits below, I did the following:

`cd chipper/tsconfig/all`
` tsc -b --watch`
`cd ../ && ./perennial/js/scripts/pull-all.sh'

tsc gave me the following errors:

error TS5083: Cannot read file 'C:/Users/Michael/PHET/git/twixt/tsconfig-all.json'.

For vegas and one other too (can't remember).

Then if I closed the tsc process and restarted it, it worked like a charm.

@samreid is this something you were aware of? I feel like it was worth noting, even if there are no actionables here.

**Comment by samreid** [comment]
Perhaps the watch was triggered when chipper was pulled but twixt was not yet pulled?  I have seen tsconfig updates reflected nicely in watch processes, though I can imagine there are corner cases that break it.

**Comment by zepumph** [comment]
Ahh, so perhaps if some other change triggered a rebuild, then it would have picked things up? I don't know if that's true because I was editing those files (the vegas/twixt tsconfig-all.json files), but if those weren't registered in the watch anyways, then perhaps that wouldn't trigger it. 

Anywho, nothing else from me here, I'm going to close.
