### ISSUE TITLE
Remove updateCopyrightForGeneratedFile

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1152]
After https://github.com/phetsims/chipper/issues/1138, chipper/js/grunt/updateCopyrightForGeneratedFile.js is no longer used. Can it be deleted, or do we think it will be used again soon?

**Comment by samreid** [comment]
It seems `getCopyrightLine` will handle the majority of cases we need.  I think this should be removed.  This issue will help in visibility if we need to resurrect it one day.

**Comment by samreid** [comment]
OK I removed the file.  @pixelzoom can you please review, perhaps as part of the review for #1138?

**Comment by pixelzoom** [comment]
Since it's unused, and was simply delete, there's really nothing to test or review here.  Deleting does seem like the right thing to do.  So closing.
