### ISSUE TITLE
Speed up TypeScript compilation for iteration

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1156]
@jessegreenberg reported in slack:

> So far I have been using tsc -b --watch in chipper/tsconfig/all, but compilation time there has gone up to about 30 seconds.  I will start a watch process just in the sim I am testing in from now on.

We discussed that changes to Property.ts compile quickly, but changes to Sim.js constructor take 30-60 seconds for @jessegreenberg.  We would like to find a faster way.

To investigate:
* Running babel as a WebStorm file watcher
* Running a babel watch process
* Running swc
* Writing our own script that layers into a watch process

TypeScript describes babel integration here: https://www.typescriptlang.org/docs/handbook/babel-with-typescript.html.  However, we currently have constraints about how and where the files are output (chipper dist with correct relative paths and *.js suffixes, and *.js files should be output too), so not everything is expected to work right out of the box.

I'm already seeing that babel doesn't copy *.js files by default, and does not change suffix if using --out-file in a file watcher.

Also, to support paralllel file outputs, we will likely need to export type definitions separately, which can be checked and enforced via `"isolatedModules": true`.  We can also discuss whether we will allow `tsc` to output files or just type check.

Given the constraints above, I'm considering that we will need our own script that takes a file and transpiles it into the right spot using babel.  We can then combine that with WebStorm file watcher or chokidar.  I also haven't looked into swc yet--it may work right out of the box.

**Comment by samreid** [comment]
@jonathanolson and I reviewed the proposal on my working copy and agreed it seems a good direction to go in, so I committed the current version.

Next steps:
- [ ] Follow https://www.typescriptlang.org/docs/handbook/babel-with-typescript.html and add:
```js
"compilerOptions": {
  // Ensure that .d.ts files are created by tsc, but not .js files
  "declaration": true,
  "emitDeclarationOnly": true,
  // Ensure that Babel can safely transpile files in the TypeScript project
  "isolatedModules": true
}
```

This will require updating the imports on every sim and I'll wait until @jonathanolson has pushed changes for the large scenery refactor to do so, since it will modify imports for many repos.

- [ ] Add the new process to the build steps
- [ ] Add the new process to CT
- [ ] Add the new process to phet-server
- [ ] When/where to run `tsc` for type checking?
- [ ] Code review for the new process
- [ ] Test the new process on windows
- [ ] Inform the team how to use the new process

**Comment by samreid** [comment]
I tried watching active-repos to update the watch paths, but if I add in js, images and sounds, then watching active-repos fails.  I'm probably hitting some limit, but it doesn't give me confidence in chokidar.

<details>

```diff
Index: transpile/transpile-all.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/transpile/transpile-all.js b/transpile/transpile-all.js
--- a/transpile/transpile-all.js	(revision 08fe7a06aae894b59e824856b6a1a999943b82ac)
+++ b/transpile/transpile-all.js	(date 1637975934584)
@@ -9,8 +9,6 @@
  *
  * OPTIONS:
  * --watch                continue watching all directories and transpile on detected changes
- * --ignoreInitial false  (default) transpile all files on startup
- * --ignoreInitial true   skip initial transpile on startup
  * --clean                dispose of the cache that tracks file status on startup, can be combined with other commands
  *                        you would need to run --clean if the transpiled file status ever gets out of sync with the
  *                        cache file status, for example if you deleted/modified a transpiled file
@@ -48,40 +46,56 @@
   fs.writeFileSync( statusPath, JSON.stringify( status, null, 2 ) );
 }
 
-let ignoreInitial = false;
-const index = args.indexOf( '--ignoreInitial' );
-if ( index >= 0 ) {
-  if ( args[ index + 1 ] === 'true' ) { ignoreInitial = true;}
-  else if ( args[ index + 1 ] === 'false' ) { ignoreInitial = false;}
-  else {throw new Error( 'illegal value for ignoreInitial' );}
-}
-
-const activeRepos = fs.readFileSync( '../perennial/data/active-repos', 'utf-8' ).trim().split( '\n' );
+const ACTIVE_REPOS_PATH = '../perennial/data/active-repos';
+const activeRepos = fs.readFileSync( ACTIVE_REPOS_PATH, 'utf-8' ).trim().split( '\n' );
+const watchedRepos = [ ...activeRepos ];
 const paths = [];
+paths.push( '../perennial/data/active-repos' );
 activeRepos.forEach( repo => {
   paths.push( `../${repo}/js` );
-  paths.push( `../${repo}/images` );
   paths.push( `../${repo}/sounds` );
+  // paths.push( `../${repo}/images` );
 } );
 
+let count = 0;
+let ready = false;
 chokidar.watch( paths, {
-  ignoreInitial: ignoreInitial,
-  ignored: [ '**/chipper/dist/**/' ]
+  ignoreInitial: true,
+  // ignored: [ '**/node_modules/**', '**/chipper/dist/**', '**/.git/**' ]
+  // ignored: path => path.includes( 'node_modules' )
 } ).on( 'all', ( event, path ) => {
-  if ( path.endsWith( '.js' ) || path.endsWith( '.ts' ) ) {
-    const changeDetectedTime = Date.now();
-    const text = fs.readFileSync( path, 'utf-8' );
-    const hash = crypto.createHash( 'md5' ).update( text ).digest( 'hex' );
-
-    if ( !status[ path ] || status[ path ].md5 !== hash ) {
-      status[ path ] = { md5: hash };
-      transpileFunction( path, text );
-      fs.writeFileSync( statusPath, JSON.stringify( status, null, 2 ) );
-      const elapsed = Date.now() - changeDetectedTime;
-      console.log( elapsed + 'ms: ' + path );
-    }
+  count++;
+  // console.log( path );
+  if ( count % 1000 === 0 ) {
+    console.log( count );
+  }
+  // console.log( path );
+  // if ( path.endsWith( '.js' ) || path.endsWith( '.ts' ) ) {
+  //   const changeDetectedTime = Date.now();
+  //   const text = fs.readFileSync( path, 'utf-8' );
+  //   const hash = crypto.createHash( 'md5' ).update( text ).digest( 'hex' );
+  //
+  //   if ( !status[ path ] || status[ path ].md5 !== hash ) {
+  //     status[ path ] = { md5: hash };
+  //     transpileFunction( path, text );
+  //     fs.writeFileSync( statusPath, JSON.stringify( status, null, 2 ) );
+  //     const elapsed = Date.now() - changeDetectedTime;
+  //     console.log( elapsed + 'ms: ' + path );
+  //   }
+  // }
+  // else if ( path === ACTIVE_REPOS_PATH ) {
+  //   console.log( path, ACTIVE_REPOS_PATH );
+  //   const newRepos = fs.readFileSync( ACTIVE_REPOS_PATH, 'utf-8' ).trim().split( '\n' );
+  //   const toRemove = watchedRepos.filter( repo => !newRepos.includes( repo ) );
+  //   const toAdd = newRepos.filter( repo => !watchedRepos.includes( repo ) );
+  //   console.log( 'removing: ' + toRemove.join( ', ' ) + ', adding: ' + toAdd.join( ', ' ) );
+  // }
+
+  if ( ready ) {
+    console.log( path );
   }
 } ).on( 'ready', () => {
+  ready = true;
   if ( !args.includes( '--watch' ) ) {
     console.log( 'Finished transpilation in ' + ( Date.now() - start ) + 'ms' );
     process.exit( 0 );

```

<details>

**Comment by samreid** [comment]
I messaged slack:

> As part of https://github.com/phetsims/chipper/issues/1156, we are investigating a new process for transpiling typescript.  It’s working well on my machine and I’m ready to test it on CT/phettest and windows.  So I’ll commit a change that disables transpilation from tsc.  Instead, we will use node js/scripts/transpile.js from chipper.  This script also supports a watch process via node js/scripts/transpile.js --watch

**Comment by samreid** [comment]
There are 2 known problems, and I've reverted until we can fix those:

(1) `grunt` for a sim says it can't find the babel files.  Adding 

```json
    "@babel/preset-typescript": "7.16.0",
    "@babel/core": "^7.15.0"
```
to the package.json and npm install works around the problem, but I don't know if we want to add that to all sim repos.

(2) Something is wrong with paths and it is giving this error:

```
~/apache-document-root/main/gravity-and-orbits$ grunt --brands=phet
Running "lint-all" task

Running "report-media" task

Running "clean" task

Running "build" task
185ms: ../chipper/js/common/Transpiler.js
27ms: ../chipper/js/getStringModule.js
>> TypeScript compilation complete: 7532ms
Building runnable repository (gravity-and-orbits, brands: phet)
Building brand: phet
Webpack build errors: [
  ModuleNotFoundError: Module not found: Error: Can't resolve '../../mipmaps/model_icon_png.js' in '/Users/samreid/apache-document-root/main/chipper/dist/gravity-and-orbits/js/model'
    at /Users/samreid/apache-document-root/main/chipper/node_modules/webpack/lib/Compilation.js:2011:28
    at /Users/samreid/apache-document-root/main/chipper/node_modules/webpack/lib/NormalModuleFactory.js:795:13
    at eval (<anonymous>:10:1)
    at /Users/samreid/apache-document-root/main/chipper/node_modules/webpack/lib/NormalModuleFactory.js:275:22
    at eval (<anonymous>:9:1)
    at /Users/samreid/apache-document-root/main/chipper/node_modules/webpack/lib/NormalModuleFactory.js:431:22
    at /Users/samreid/apache-document-root/main/chipper/node_modules/webpack/lib/NormalModuleFactory.js:124:11
    at /Users/samreid/apache-document-root/main/chipper/node_modules/webpack/lib/NormalModuleFactory.js:667:25
    at /Users/samreid/apache-document-root/main/chipper/node_modules/webpack/lib/NormalModuleFactory.js:852:8
    at /Users/samreid/apache-document-root/main/chipper/node_modules/webpack/lib/NormalModuleFactory.js:972:5
    at /Users/samreid/apache-document-root/main/chipper/node_modules/neo-async/async.js:6883:13
    at Array.<anonymous> (/Users/samreid/apache-document-root/main/chipper/node_modules/webpack/lib/NormalModuleFactory.js:947:14)
    at arrayEachFunc (/Users/samreid/apache-document-root/main/chipper/node_modules/neo-async/async.js:2517:19)
    at Object.parallel (/Users/samreid/apache-document-root/main/chipper/node_modules/neo-async/async.js:6858:9)
    at NormalModuleFactory._resolveResourceErrorHints (/Users/samreid/apache-document-root/main/chipper/node_modules/webpack/lib/NormalModuleFactory.js:870:12)
    at /Users/samreid/apache-document-root/main/chipper/node_modules/webpack/lib/NormalModuleFactory.js:831:18
    at finishWithoutResolve (/Users/samreid/apache-document-root/main/chipper/node_modules/enhanced-resolve/lib/Resolver.js:296:11)

```

**Comment by samreid** [comment]
I'm seeing this problem after these changes:

```
~/apache-document-root/main/circuit-construction-kit-ac$ node ../perennial/js/scripts/hook-pre-commit.js
{
  code: 2,
  stdout: "js/circuit-construction-kit-ac-main.ts(10,38): error TS6305: Output file '/Users/samreid/apache-document-root/main/chipper/dist/circuit-construction-kit-common/js/view/CCKCOptionsDialogContent.d.ts' has not been built from source file '/Users/samreid/apache-document-root/main/circuit-construction-kit-common/js/view/CCKCOptionsDialogContent.ts'.\n",
  stderr: '',
  cwd: '../circuit-construction-kit-ac',
  time: 2162
}
```

**Comment by samreid** [comment]
OK almost everything seems like it is working.  Working things include:

* CT
* phettest
* precommit hooks
* fast watch process
* fast transpile process
* builds (phet and phet-io)
* works great on windows

The only thing I'm aware of that is not working as expected is the sourcemaps.

I also decided it would be best to have this reviewed by another developer before enabling it, so I've commented it out for now.

**Comment by pixelzoom** [comment]
Before enabling this, can you also please summarize what the new workflow will be?

**Comment by samreid** [comment]
The new workflow is described in https://github.com/phetsims/chipper/issues/1156#issuecomment-981117127.  Summarizing the proposal:

Instead of using `tsc` to transpile our code, we will use a new script which can be invoked like so:

```
cd chipper
node transpile/transpile-all.js --watch
```

Or you can run it without `--watch` if you just want to run it once.  Options and behavior for that script are documented in https://github.com/phetsims/chipper/blob/master/js/scripts/transpile.js. That runs the transpilation step.  We would still use `tsc -b` to run the type checker.

**Comment by pixelzoom** [comment]
I still didn't understand what's being proposed, or the implications, so I discussed with @samreid. 

Notes: 
* The terms "transpile" and "compile" are now being used interchangeably wrt TypeScript.  Yes, tsc is techincally a transpiler - thank you Microsoft for naming it incorrectly.  But switching between "compile" and "transpile" in TS discussions is confusing. Maybe we should stick with "transpile" for the build process output, and "compile" for tsc output?  I'm going to use "compile" in the remainder of this comment.
* Compilation was taking an unacceptably long time for some common-code files. So another approach was needed, and @samreid found that babel offered a faster method, see https://www.typescriptlang.org/docs/handbook/babel-with-typescript.html.
* Compilation now requires Node, because babel is now a part of built and unbuilt workflows. 
* `tsc` will no longer generate output files (.js, .js.map). You can only use tsc for type checking.
* The watch process now involves running `node transpile/transpile-all.js --watch` from chipper. Now that compilation is faster, watching all files shouldn't be a problem.
* WebStorm "Recompile on changes" is likely not useful. Like tsc, it will do type checking, but not generate output files.

**Comment by samreid** [comment]
In discussion with @jonathanolson we agreed we want to:

- [ ]  Separate out the transpilation from the type checking.  Currently both are in tsc, but we want to visit call sites and let call sites decide whether they want transpilation or type checking or both.

**Comment by samreid** [comment]
I added a script that can be used with WebStorm's File Watcher.  I set up my configuration like so:

![image](https://user-images.githubusercontent.com/679486/143961970-9d1bcc5a-251f-4ebb-acb4-63c2dd5c808c.png)

And I observed that it quickly transpiles a single file when saved.  It seems to be working nicely and could be a good solution for those who don't want to run a watch process.  You can also see an indicator in the bottom bar of WebStorm that shows when compilation starts and ends.  It's pretty speedy. 

My main concern about using File Watcher is my uncertainty about what's best for "Scope"--when I tried "all files" changes to Sim.js seemed to trigger on sim mains as well (even when unchanged).  Could setting scope to "all changed files" sometimes do more or less than it should?

**Comment by zepumph** [comment]
Hey! I really like the transpile script. Thank you so much for making it happen. It is speedy quick and excellent for iterating. 

I kept hitting a failure case where it seems like watching could potentially have a null filename. I'm not sure if this is the best long term, but it worked for me, so I thought I'd commit and see what @samreid thinks.

```
 Michael ~/PhET/git/chipper (master)
 $ node js/scripts/transpile --watch
Finished initial transpilation in 7700ms
Watching...
2815ms: ../scenery\js\nodes\Node.ts
515ms: ../scenery\js\accessibility\pdom\ParallelDOM.ts
400ms: ../scenery\js\nodes\Node.ts
C:\Users\Michael\PhET\git\chipper\js\common\Transpiler.js:168
      if ( filename.includes( '/node_modules/' ) ||
                    ^

TypeError: Cannot read property 'includes' of null
    at FSWatcher.<anonymous> (C:\Users\Michael\PhET\git\chipper\js\common\Transpiler.js:168:21)
    at FSWatcher.emit (events.js:315:20)
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:186:12)


```

**Comment by zepumph** [comment]
- [ ] One other thought I had about transpile, perhaps you can ignore sherpa by default, and then with a flag include it, because it believe the font awesome files to be ~10-20% of the initial run of transpile.

**Comment by samreid** [comment]
I reviewed the current status with @zepumph today, and he said it is a good direction and recommended committing to master.  @jonathanolson also recommended to separate out the transpiled js (from the transpiler) and the declarations (from the type checker).  I'll do this as well, but it will require changing all simulation mains to refer to `chipper/dist/js`.

**Comment by samreid** [comment]
phettest and CT have been restarted and are behaving as expected.  I think this issue will be ready for review by @jonathanolson.  Here are my last messages from slack:

OK I pushed 154+ repos.  I’ll check phettest and monitor CT.  I’ll also check slack first thing in the morning, please report if something is in your way of working.
For developers, the new transpilation step is:
cd chipper
node js/scripts/transpile.js
You can run it with --watch to keep it alive and watching the filesystem.  If the watch process fails out, please report it to me and @mjkauzmann
For WebStorm integration, you can trigger it via a File Watcher as described in https://github.com/phetsims/chipper/issues/1156#issuecomment-982147893 though the node process has been more thoroughly vetted.






Sam Reid:house_with_garden:  9:42 PM
phettest has been updated and restarted, and appears to be working properly

Sam Reid:house_with_garden:  9:53 PM
Please ignore the upcoming CT column.  I haven’t restarted CT yet so it is expected to be problematic.
9:57
OK I restarted CT.  Not sure if it will be picked up in the next column or not.  I’ll check back in half an hour or so.

Sam Reid:house_with_garden:  10:43 PM
New column has all the SHAs and it seems to be working OK. Please write in if there are problems, I’ll check back early tomorrow.

**Comment by jonathanolson** [comment]
```js
this.activeRepos = fs.readFileSync( '../perennial/data/active-repos', 'utf-8' ).trim().split( /\r?\n/ );
```
in Transpiler.js could presumably be `this.activeRepos = getActiveRepos()` (from perennial-alias).

**Comment by jonathanolson** [comment]
I'm vaguely curious if parallelization could help, it looks like we're transpiling synchronously (could have a faster startup for transpiling everything). Not important.

**Comment by jonathanolson** [comment]
What is special about game-up-camera?

```js
this.visitFile( path.join( '..', repo, 'lib', 'game-up-camera-1.0.0.js' ) );
```

**Comment by jonathanolson** [comment]
In the build:
```js
new Transpiler().transpileAll();
```

I don't like the transpiler touching ALL active repos. This seems easy to break in the future (for maintenance builds, remember most repos are going to look very different)

**Comment by jonathanolson** [comment]
It seems like we changed to `grunt output-js-all`? So looks like we likely broke maintenance support for any maintenance releases that rely on `grunt output-js`.

`chipperSupportsOutputJSGruntTasks` seems to indicate `grunt output-js` would work.

Are we planning on maintenance releasing everything to be compatible with this new style?

**Comment by jonathanolson** [comment]
Overall looks good, but I'd want the maintenance-related issues above addressed/discussed with high priority.

**Comment by samreid** [comment]
From slack:


Sam Reid  10:57 AM
For https://github.com/phetsims/chipper/issues/1156#issuecomment-984851030, yes it was changed to output-js-all.  Should I rename it to “output-js” but still have the same implementation (doing all) so it is backward compatible?  Or what other options do we have?






Jonathan Olson  10:59 AM
First of all, generating JS outside of the repos we've checked out sounds dangerous
11:00
Second of all, we'll need to adjust perennial code so we can detect what grunt commands we need to run to generate the JS for the sim

Sam Reid  11:00 AM
 generating JS outside of the repos we’ve checked out sounds dangerous
Because of potential parallel usage and collisions?

Jonathan Olson  11:00 AM
Generating outside JS seems like a performance/reliability concern
11:01
The patterns and structures in our future repos could change significantly. What happens if old maintenance versions try to build 1GB of JS (transpilation) for every build?
11:01
Why would we want to slow down maintenance processes by redoing ALL the files?

Sam Reid  11:02 AM
So for this part, should we traverse dependencies through tsconfig or package.json?  Should we resurrect both output-js and output-js-project?

Jonathan Olson  11:06 AM
We should consider output-js and output-js-project, for backward compatibility and performance. Presumably the sim should determine its own dependencies and only output JS for those

Sam Reid  11:09 AM
OK I’ll resurrect those.  It would be nice if there is a TypeScript facility to get the files defined in the scope of a tsconfig file. Or should we just go repo-by-repo?

Jonathan Olson  11:09 AM
repo-by-repo is fine
11:10
chipper getDependencies() should contain repo info
11:10
or... getPhetLibs()

Sam Reid  11:11 AM
ok I can use that.  I need CCK SHAs for RC soon.  Is it critical to fix this first?
11:13
I’ll mark it as blocks-publication for now

Jonathan Olson  11:15 AM
Yes, it should block publication

**Comment by samreid** [comment]
I restored `output-js` and `output-js-project`.  

> I'm vaguely curious if parallelization could help, it looks like we're transpiling synchronously (could have a faster startup for transpiling everything). Not important.

It seems most of the time is disk read/write rather than babel core transpilation CPU, in that case parallelization may not help much.

I addressed the code review issues.  I thought I would have to revert perennial/js/common/outputJSAll.js back to perennial/js/common/outputJS.js, but it was only used by CT and phettest processes which want to transpile everything anyways.  Can you please re-review?  If there is more-to-do and the issue cannot be closed, please indicate whether it still blocks publication.

**Comment by samreid** [comment]
I created the CCK AC (and virtual lab) SHAs, so if there are fixes to this issue they will need to be cherry-picked into those release branches.

**Comment by jonathanolson** [comment]
This looks good to me, should be compatible with maintenance tools now. Thank you!

**Comment by samreid** [comment]
Thanks

**Comment by pixelzoom** [comment]
Reopening.
 
These tasks have not been completed:

>  - [ ] Update READMEs
>  - [ ] Update the Development Overview

And typescript-quick-start.md has not been updated.

**Comment by pixelzoom** [comment]
I would also be nice if the WebStorm file watcher info were incorporated into documentation, rather than having to search for it in this issue.

**Comment by samreid** [comment]
READMEs will be updated in https://github.com/phetsims/chipper/issues/1157
Development Overview will be updated in https://github.com/phetsims/phet-info/issues/172

**Comment by samreid** [comment]
I updated the other documentation in the commit, @pixelzoom can you please review?

**Comment by pixelzoom** [comment]
typescript-quick-start.md errors and questions:

> 6. Turn on TypeScript support in WebStorm: Preferences > Languages & Frameworks > TypeScript. Sublime also has an officially-supported plugin.

My understanding is that this is no longer an option, much less a required "Getting Started" step.

> 1. Compile the source and its dependencies via `grunt output-js-project`. This compiles the sim and its dependencies to chipper/dist/. It uses "Project References" (`tsc --build`) to trace the dependencies.  
...
> 4. Compile via `grunt output-js-project` and run it in the browser. Did it print 7?

Does this really use `tsc --build`.  It looks like it's using `transpiler.js`.

Why not just replace occurrences of `grunt output-js-project` with `cd chipper; node node js/scripts/transpile.js`?

> 1. TypeScript sims need to be compiled using `grunt output-js-project` before generating their PhET-iO API using `grunt generate-phet-io-api`.

This is error prone. Should `grunt generate-phet-io-api` be responsible for running `grunt output-js-project`?

> 2. Please do not convert common code to TypeScript until that phase is approved by the team. Some common code repos have a "typescript" branch for investigation in the meantime.

My understanding is TS in common code is OK; we're past this "gate".

> 8. Gravity and Orbits, Bending Light, and Circuit Construction Kit Common have been written in TypeScript,

The set of TS sims is larger now.

Back to @samreid.

**Comment by samreid** [comment]
Thanks, I updated the quick start guide more thoroughly.

> My understanding is that this is no longer an option, much less a required "Getting Started" step.

I revised that part to show how to turn on the language service, but turn off the compilation.

> This is error prone. Should grunt generate-phet-io-api be responsible for running grunt output-js-project?

It has been changed to autorun the transpiler.

> The set of TS sims is larger now.

I removed the list altogether. Users can search for *.ts filenames if desired.

Ready for re-review.

**Comment by pixelzoom** [comment]
> Turn on TypeScript support in WebStorm: Preferences > Languages & Frameworks > TypeScript. Make sure you are using your system's absolute path for chipper/node_modules/typescript, turn on "TypeScript language service" and turn on "Recompile on Changes". Turn off "Recompile on changes".

??

**Comment by samreid** [comment]
Oops, was a typo, should read:

Turn on "TypeScript language service", turn on "Show project errors", and turn off "Recompile on changes".
