### ISSUE TITLE
Google Group: announce breaking changes related to TypeScript. 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#1158]
Now that TS is used in common-code, there are breaking changes that will impact 3rd-party developers.  Sims will not run without a compile step,  all scenery imports must be changed to use imports.js, etc.   It would be courteous to announce these breaking changed (as they occur) in the Google Group.  The [TypeScript](https://groups.google.com/g/developing-interactive-simulations-in-html5/c/VCAUC6nhI6Q) thread is probably the approriate place to do this.

**Comment by samreid** [comment]
I added another message to the TypeScript thread.  Not sure what else to do here.

**Comment by pixelzoom** [comment]
An announcement about the breaking change to scenery imports seems relevant.

**Comment by samreid** [comment]
Thanks, I added an announcement about that.

**Comment by pixelzoom** [comment]
👍🏻
