### ISSUE TITLE
string utilities needed

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#116]
There are several similar implementations of string replacement in chipper:

```
createSim.js: var replaceOneString = function( str, substring, replacement )
createSim.js: var replaceAllString = function( str, substring, replacement )
generalREADME: var replaceAll = function( str, find, replace )
afterRequirejsBuild: var stringReplace = function( str, substring, replacement )
```

And there is also string replacement in other repos, for example:

```
SimIFrameAPI: var replaceAll = function( str, find, replace )
```

So it seems like we need to extract out of an API for common string-replacement functions.

**Comment by pixelzoom** [comment]
afterRequirejsBuild has a couple of other general string utilities: trimWhitespace, padString

**Comment by pixelzoom** [comment]
reportUnusedImagesAndAudio.js now has "endsWith" string function.

Renaming this issue to "string utilities needed".

**Comment by pixelzoom** [comment]
I'm going to take a stab at this.

**Comment by pixelzoom** [comment]
This is interesting in createSim.js:

```js
  // Replace a single occurrence in a string (if any) with another.
  var replaceOneString = function( str, substring, replacement ) {
    var idx = str.indexOf( substring );
    if ( str.indexOf( substring ) !== -1 ) {
      return str.slice( 0, idx ) + replacement + str.slice( idx + substring.length );
    }
    else {
      return str;
    }
  };
```

This is equivalent to `str.replace( substring, replacement )`, the default behavior of `replace`.

**Comment by samreid** [comment]
My bad, wasn't familiar with String.prototype.replace.  From the doc:

> The replace() method returns a new string with some or all matches of a pattern replaced by a replacement.

So I think we could use this for both `replaceAllString` and `replaceOneString`.

**Comment by pixelzoom** [comment]
I think it's worth having replaceAll:

```js   
replaceAll: function( str, find, replaceWith ) {
  return str.replace( new RegExp( find.replace( /[-\/\\^$*+?.()|[\]{}]/g, '\\$&' ), 'g' ), replaceWith );
},
```

**Comment by pixelzoom** [comment]
Done. @samreid please review.

**Comment by samreid** [comment]
ChipperStringUtils.js looks great, thanks for creating it.  I created 5 related issues that I noticed during my review.  This issue is good to close.
