### ISSUE TITLE
chipper/dist accumulates garbage

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1168]
Both the transpilation process and the declaration emit process (from tsc), can lead to the accumulation of garbage in chipper/dist.  Here is the slack conversation where @pixelzoom originally described the problem:

> 
> Chris Malley  12:45 PM
> As I’m working on geometric-optics, refactoring and renaming, I’ve discovered that I’m ending up with a lot of vestigial .js files in chipper/dist/js/geometric-optics/.  That seems undesirable. Thoughts on how to address it?  Or is the solution to delete chipper/dist/ periodically? (edited) 
> 
> Sam Reid  12:46 PM
> We could have the transpiler watch process look for file deletion, then delete the corresponding chipper/dist file?
> 
> Chris Malley  12:47 PM
> That sounds good. Something needs to be cleaning things up, and it would be nice if it weren’t the developer’s responsibility to handle it manually. (edited) 
> 
> Sam Reid  12:48 PM
> Should it also run an initial scan of everything in chipper/dist to make sure the corresdponding source file exists?
> 12:49
> Also, can you help me quantify the importance and priority of this?  Other than hunting around in chipper/dist or list disk space I’m not sure what use cases may be impacted.
> 
> Chris Malley  12:51 PM
> I rename a .ts file and change the .js imports.  I forget to change the .js import in some file, and now it points to a vestigial .js file.
> 
> Sam Reid  12:51 PM
> So I want to make sure it’s worth the complexity or additional CPU time.
> 12:52
> I see, thanks!  But that would be caught by tsc ,right?
> 
> Chris Malley  12:52 PM
> Would tsc catch it if the .js file still exists in chipper/dist/?
> 
> Sam Reid  1:09 PM
> tsc only checks the source files
> 1:10
> (Well, it caches d.ts files in chipper/dist for incremental and project references builds, but it doesn’t output to chipper/dist/js where the transpiler outputs).
> 
> Michael Kauzmann:spiral_calendar_pad:  1:14 PM
> Can we change chipper/dist/ so that it has two folders, one called js/ and the other where tsc outputs? It feels confusing that there is a top level output, and a sub-directory for transpiled output.
> 
> Chris Malley  1:15 PM
> I thought tsc was configured to no longer output files? … and only do type checking. (edited) 
> 
> Sam Reid  1:15 PM
> That was already completed based on @jonathanolson recommendation.  The transpiler outputs to chipper/dist/js and tsc outputs to chipper/dist/declarations.
> 1:15
> tsc no longer outputs transpiled JavaScript files. But it outputs declaration files for incremental project reference type checks. (edited) 
> 
> Chris Malley  1:16 PM
> Good to know.
> 1:17
> chipper/dist/declarations/ is also littered with vestigial .d.ts files.
> 1:18
> I guess I’ll get in the habit of blasting chipper/dist/ at least once a day.
> 
> Sam Reid  1:18 PM
> Won’t that make your builds and type checks take much longer?
> 
> Chris Malley  1:19 PM
> It will require an initial build of everything. But at least I won’t have an accumulation of garbage.
> 
> Sam Reid  1:20 PM
> Sounds good, I’ll try to be on the alert for problems that I run into from not taking out the garbage.
> 1:21
> I’ll also open a chipper issue for visibility
> 
> Chris Malley  1:21 PM
> thanks
> 1:21
> At the very least, devs should be aware that nothing is cleaning up the artifacts associated with vestigial .ts files.
> New
> 
> Jonathan Olson  1:22 PM
> I'll check to see if I ever run into a problem from it, but I don't anticipate it

**Comment by pixelzoom** [comment]
Adding to Developer Meeting for a PSA, so that developers are aware that garbage can build up in chipper/dist/.

**Comment by samreid** [comment]
We discussed this at today's dev meeting.  You can clean using `tsc -b --clean` and `node js/scripts/transpiler.js --clean`.  It isn't clear there will be problems from the accumulated garbage, but we will keep our eyes peeled.  It is up to developers to decide how often to clean.

**Comment by samreid** [comment]
This bit me during https://github.com/phetsims/tasks/issues/1090.  I changed an image filename, transpiled the new file, and neglected to change the import.  Lint passed and the code still ran.  The first step toward a remedy may be: the watch process could observe file deletion and delete the corresponding dist file.

**Comment by pixelzoom** [comment]
> This bit me during ...

That's exactly the scenario kind of scenario that I feared was possible.

**Comment by samreid** [comment]
@jonathanolson observed this problem today since molecule-shapes-basics imports:

```ts
import IE11StencilWarningNode from '../../molecule-shapes/js/common/view/IE11StencilWarningNode.js';
```
But this file has not existed for a long time.

@jonathanolson and I observed that the watch process checks for deletes, but the batch mode (on startup) does not, and left this error.  Alternatively, we could clean every time.  But we don't want all our tooling slowed down.  But we also don't want false positives or false negatives.  

Next step will be for me to investigate how long it would add to startup time to scan for deletes on startup.  If that is fast, we could go with that.

**Comment by samreid** [comment]
Also, perhaps a lint rule should tell us that file doesn't exist?

**Comment by samreid** [comment]
In the commits, chipper/dist/js is pruned on startup and intermittently during watch.  I was OK with that since it is only taking about 200ms on my system.  But I think the watch process has been detecting file deletes correctly, so the intermittent part is probably unnecessary.  I'll remove it and the code reviewer or dev team can decide if we want it?

**Comment by samreid** [comment]
I messaged slack:

> `@channel` The chipper transpiler now prunes orphaned files on startup.  This will happen next time you pull and restart the transpilation process.

This is ready for review.  @pixelzoom and @zepumph have been involved in this issue, would one of you like to volunteer to review/test?  If you don't have time, please label for dev meeting and someone else can review.

**Comment by pixelzoom** [comment]
While I've experienced the problem, I have no familiarity with the implementation.  So I'm not going to review.

**Comment by zepumph** [comment]
This is really great! Thanks so much for taking the lead on it. I have noticed these "deleted" logs in the past few days.

My only question is if it is helpful note Nodejs's path library? Instead of `forwardSlashify`, should be use `path.sep` somehow?


Feel free to close.

**Comment by samreid** [comment]
It simplified use cases to know that there are forward slashes, like:

```ts
  ignorePath( filePath ) {
    const withForwardSlashes = Transpiler.forwardSlashify( filePath );
    return withForwardSlashes.includes( '/node_modules/' ) ||
           withForwardSlashes.includes( '.git/' ) ||
           withForwardSlashes.includes( 'chipper/dist/' ) ||
           withForwardSlashes.includes( 'transpile/cache/status.json' ) ||

           // Temporary files sometimes saved by the IDE
           withForwardSlashes.endsWith( '~' );
  }
```

Closing.
