### ISSUE TITLE
Add custom locale: Karakalpak

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/chipper#1169]
Perhaps this custom locale could be added alongside the work to add Kurmanji https://github.com/phetsims/chipper/issues/1111

> I am writing to propose the idea of adding Karakalpak language to the simulators on your website. I am a teacher at the General Education University of the Republic of Karakalpakstan, where teachers strengthen their knowledge, exchange, and share experiences with students and other teachers. I share a variety of resources and ways for informative delivering lessons using information and communication technologies during my lessons, my seminars. 
>
>Additionally, I give information about your simulators to the teachers of STEM subjects. I believe that if teachers of secondary schools and universities used the opportunities of your website, in their lessons, to explain topics, they could achieve good results. Even in the absence of real laboratories, they can use virtual laboratories. Teachers like the simulators on your site, but there is one issue, the lack of simulators in the Karakalpak language. 
>
>It would be great if simulators on your website were also in this language because there are a lot of people and teachers who teach in the Karakalpak language. They would also like to conduct their lessons using PhET simulators. And I want to be a part of the translators' team and contribute to the translation of such simulators into the Karakalpak language. 

[Karakalpak Wiki page](https://en.wikipedia.org/wiki/Karakalpak_language)

I've written back to the user to inform them that adding a custom locale is not trivial and it may be a while until we are able to fulfill this request.

Assigning to @mattpen since he is familiar with #1111.

**Comment by mattpen** [comment]
Assigning the locale subgroup.  This would definitely be ideal to work on with #1111.

**Comment by jbphet** [comment]
For reference, the ISO 693-3 language code for this language is `kaa`, and in the reference page at https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Languages/List_of_ISO_639-3_language_codes_(2019) the language is listed as Kara-kalpak.

**Comment by jbphet** [comment]
In 639-1, Karakalpak is not listed, and the `ka` locale is already in use by Kartvelian, also known as Georgian.  `kk` and `kr` are also used.  The code `kp` does _not_ appear to be used, so perhaps we could use that one.

**Comment by jbphet** [comment]
@oliver-phet and @RVieyra - This issue was discussed with @kathy-phet at today's development planning meeting, and @kathy-phet recommended that we assign it to you to do a bit of investigation and make sure that people would really use this custom locale if we create it.  We've done some of these before, such as in https://github.com/phetsims/rosetta/issues/158, where no one ended up using it, so we want to make sure it's worth the effort.

**Comment by jbphet** [comment]
@oliver-phet - Once this is vetted, please assign it back to me.

**Comment by RVieyra** [comment]
PhET Global doesn't have any specific initiatives in this language's region, so it would not be as high on Global's priority list as say, some African languages with similar numbers of speakers.

The real question about utility comes down to if this person is seriously willing to do the translations and intends to integrate them into their teacher ed programs--something that is clearly more systemically impactful than doing it for a single classroom. I'm happy to get in touch with this person if you provide the e-mail contact so I can learn more about their level of commitment.

**Comment by oliver-phet** [comment]
I sent a follow up email to the user, will update when we receive a response.

**Comment by oliver-phet** [comment]
I haven't heard back from the requesting user in over 2 weeks. I think we should close this issue and wait on supporting any new custom locales until we have another serious request.
