### ISSUE TITLE
preload and phetLibs should be multiple entries rather than a space delimited string

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#117]
Preload and phetLibs lines are too long to manage as a single space delimited string.  For instance, here is a current preload line (weighing in at 300+ columns):

```js
"preload": "../assert/js/assert.js ../sherpa/jquery-2.1.0.js ../sherpa/lodash-2.4.1.js ../sherpa/has.js ../sherpa/FileSaver.js ../chipper/js/initialize-globals.js ../sherpa/jsondiffpatch-0.1.31.js ../together/js/initializeTogether.js ../together/js/SimIFrameAPI.js ../arch/js/arch.js ../phetcommon/js/analytics/google-analytics.js",
```

Having these entries be so far off the page with no option that I am aware of for line breaks within json, (see http://stackoverflow.com/questions/2392766/multiline-strings-in-json ) makes it difficult to read and understand what libraries are in place.  Instead preload and phetLibs should use arrays [] or object properties {} to nest and format properly.

This will be an invasive change, affecting all simulations + build tools.  I'll discuss with other PhET developers before we make any systemwide changes.

**Comment by jonathanolson** [comment]
Sounds good to me.

**Comment by pixelzoom** [comment]
Questions:

What doe you mean by "multiple entries"? Do you mean duplicate "phetLibs" and "preload" keys?

Rather than multiple keys, why not change these values to string arrays, so that they can be split across multiple lines? That would also eliminate the need to be doing ` pkg.preload.split( ' ' )` over and over. And would be a much easier change to make across build tools.

**Comment by samreid** [comment]
> What doe you mean by "multiple entries"? Do you mean duplicate "phetLibs" and "preload" keys?

No.  The entries are the individual path or library elements in each of the phetLibs and preload strings.  For instance, in the "preload" example 2 comments above, there are 11 preload entries. 

> Rather than multiple keys, why not change these values to string arrays,

Yes, that was the first option I suggested when I said "Instead preload and phetLibs should use arrays ..."

**Comment by pixelzoom** [comment]
+1 for arrays of {string}.

**Comment by pixelzoom** [comment]
@samreid you said:
> This will be an invasive change, affecting all simulations + build tools. 

I'm familiar with the build tools usages. Where are phetLibs and preload used in sims?  Just trying to get a feel for whether I want to volunteer to do this :)

**Comment by samreid** [comment]
> affecting all simulations

This only means changing the package.json files.

**Comment by pixelzoom** [comment]
Everyone OK with arrays of {string} for phetLibs and preloads? If so, I'll take care of this.

**Comment by samreid** [comment]
Before diving in to do all of them, can you prepare an example from a single simulation's package.json so we can take a look, test it in our IDE formatter, etc and make sure we are happy with everything?

**Comment by pixelzoom** [comment]
Example:

```js
{
  "name": "acid-base-solutions",
  "version": "1.2.0-dev.1",
  "phetLibs": [ 
    "acid-base-solutions", 
    "assert", 
    "axon", 
    "brand", 
    "chipper", 
    "dot", 
    "joist", 
    "kite", 
    "phet-core", 
    "phetcommon", 
    "scenery", 
    "scenery-phet", 
    "sherpa", 
    "sun" 
  ],
  "preload": [ 
    "../assert/js/assert.js", 
    "../sherpa/jquery-2.1.0.js", 
    "../sherpa/lodash-2.4.1.js", 
    "../sherpa/has.js", 
    "../sherpa/FileSaver.js", 
    "../chipper/js/initialize-globals.js", 
    "../phetcommon/js/analytics/google-analytics.js" 
  ],
  "license": "GPLv3",
  "repository": {
    "type": "git",
    "url": "https://github.com/phetsims/acid-base-solutions.git"
  },
  "devDependencies": {
    "grunt": "~0.4.1",
    "grunt-requirejs": "~0.4.0",
    "grunt-contrib-jshint": "~0.6.4",
    "uglify-js": "~2.4.0",
    "requirejs": "~2.1.8"
  },
  "simTitleStringKey": "ACID_BASE_SOLUTIONS/acid-base-solutions.name"
}
```

**Comment by pixelzoom** [comment]
I may also move simTitleStringKey and license closer to the top of package.json, perhaps immediate after version.

**Comment by samreid** [comment]
This looks great and my formatter loves it.

+1 for moving `simTitleStringKey` and `license` closer to the top of package.json

Let's get +1 from other developers before moving forward.

**Comment by pixelzoom** [comment]
@jonathanolson @jbphet @aaronsamuel137 please cast your vote.

**Comment by aaronsamuel137** [comment]
+1 for arrays of {string}
+1 for moving ```simTitleStringKey``` and ```license``` closer to the top.

**Comment by samreid** [comment]
Perhaps before & after making this kind of change, we should post to https://groups.google.com/forum/#!forum/developing-interactive-simulations-in-html5 since all people developing with PhET will have to update their chipper when they update their sim code.

**Comment by jbphet** [comment]
+1 for both (using arrays of strings, moving license and simTitleStringKey towards the top).

**Comment by pixelzoom** [comment]
Changes completed, build-server run to check for breakage, notification posted to Google Group.  Closing.

**Comment by samreid** [comment]
Did this break jshint:allFiles?  I observed:

```
> cd reactants-products-and-leftovers/
> grunt 
Running "generateLicenseInfo" task
created license info for 6 dependencies

Running "jshint:allFiles" (jshint) task
>> 0 files linted. Please check your ignored files.
```

**Comment by aaronsamuel137** [comment]
jshint:allFiles seems to be working as expected for me.

**Comment by pixelzoom** [comment]
I'll have a look.

**Comment by pixelzoom** [comment]
Seems to be working fine for me. @samreid are you on master? Your output indicates `created license info for 6 dependencies`, mine shows `10 dependencies`.
 
```
> cd reactants-products-and-leftovers/
> grunt
Running "generateLicenseInfo" task
created license info for 10 dependencies

Running "jshint:allFiles" (jshint) task
>> 472 files lint free.

Running "clean" task
Cleaning build directory

Running "generateLicenseInfo" task
created license info for 10 dependencies

Running "simBeforeRequirejs" task
Building simulation: reactants-products-and-leftovers 1.1.0-dev.1

Running "requirejs:build" (requirejs) task
>> RequireJS optimizer finished

(etc...)
```

**Comment by samreid** [comment]
It is working for me again, not sure what went wrong before.

```
> grunt 
Running "generateLicenseInfo" task
created license info for 13 dependencies

Running "jshint:allFiles" (jshint) task
>> 397 files lint free.
```
