### ISSUE TITLE
npm WARN acorn-import-assertions@1.8.0 requires a peer of acorn@^8 but none is installed. 

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1171]
From https://github.com/phetsims/chipper/issues/1149, I'm seeing

```
~/apache-document-root/main/chipper$ npm install
npm WARN acorn-import-assertions@1.8.0 requires a peer of acorn@^8 but none is installed. You must install peer dependencies yourself.
```

According to https://stackoverflow.com/questions/46053414/npm-warn-requires-a-peer-of-but-none-is-installed-you-must-install-peer we are supposed to manually add the acorn ourselves.  Which dependency is requiring acorn?  I searched node_modules and it may be one or more of these (each of which mentions acorn.)

* babel
* jimp
* es-module-lexer
* eslint
* espree
* html-minifier-terser
* pixelmatch
* terser
* terser-webpack-plugin
* webpack

**Comment by samreid** [comment]
My prior acorn was at 7.6 or so.  I tried `npm install acorn@^8 --save-dev` and ran `npm install` afterwards and it didn't report the warning.  But now I have to test all of the chipper functionality to see if acorn 7.6 => 8.6 may have broken anything.

**Comment by samreid** [comment]
Perhaps I'll add this acorn dependency and keep my eyes peeled for any unusual behavior during chipper tasks.

**Comment by samreid** [comment]
I deployed CCK RC.3 with this change and it seems OK so far.

**Comment by samreid** [comment]
@markgammon can you please recommend a reviewer for this minor change?  @jonathanolson would be ideal, but I know he has been busy.  @zepumph @jbphet or @jessegreenberg would also be good reviewers for this area.

**Comment by markgammon** [comment]
@jbphet will do a review.

**Comment by jbphet** [comment]
A couple of notes for future reference:
- acorn is "A tiny, fast JavaScript parser written in JavaScript.", according to [its npm page](https://www.npmjs.com/package/acorn).
- I ran the command `find ./node_modules/ -name package.json | xargs grep acorn`, and from the results I think that webpack has the dependency on acorn, and possibly some other packages that we don't explicitly specify.

In general, manually updating acorn seems like a reasonable thing to do, and the update to chipper's `package.json` file seems like the right way to do it.  Builds appear to be succeeding and, as @samreid said, he was able to deploy a sim that included TS with this in place.  Other than that, I don't think there's much more to review.  Change approved, closing.

**Comment by samreid** [comment]
Let's reopen until we figure out https://github.com/phetsims/perennial/issues/256

**Comment by samreid** [comment]
I decided to revert acorn for now.  After reverting it, I did a trial deploy of CCK DC phet brand, and it seemed to work OK.

**Comment by jbphet** [comment]
@samreid - I'm unmarking this is "read for review" since the original change was undone.  We can decide at the next meeting what the next steps should be and who should do them.

**Comment by samreid** [comment]
At today's meeting, we agreed to continue with the revert.  I'll run the maintenance tools to see what branches are impacted.

**Comment by samreid** [comment]
From running the maintenance tools:

```
maintenance> Maintenance.applyPatches()
Checked out chipper SHA for center-and-variability 1.0
Could not cherry-pick 3f52c81b253b46e90a4bcd2d047eef9f22cd864d
Checked out chipper SHA for density 1.0
Cherry-pick success for 3f52c81b253b46e90a4bcd2d047eef9f22cd864d, result is ebae72a59cb2623e8e81c6a236cc12b25a084a28
Checked out chipper SHA for geometric-optics 1.1
Could not cherry-pick 3f52c81b253b46e90a4bcd2d047eef9f22cd864d
1 patches applied
```

**Comment by samreid** [comment]
@jessegreenberg and I used the maintenance tools to redeploy density with the fix commits above, however the build logs said:

> Apr 05 08:45:59 phet-server2.int.colorado.edu build-server[1463982]: Error: Cannot find module 'acorn'

**Comment by samreid** [comment]
In https://github.com/phetsims/perennial/issues/256#issuecomment-1009401294 @mattpen said:

> Maybe a simple solution could be to use `rm -rf node_modules && npm install` instead of `npm prune && npm update` where acorn is needed. This would definitely result in longer build times.

@jessegreenberg and I discussed that a slow + correct build process is preferable to a fast + buggy build process.  Therefore, we want to ask for help from @mattpen and/or @jonathanolson for next steps.

**Comment by jonathanolson** [comment]
https://stackoverflow.com/questions/35207380/how-to-install-npm-peer-dependencies-automatically noted that the peer dependency (acorn) isn't installed with npm versions between 3-6. npm 7+ seems to solve this.

**Comment by samreid** [comment]
@jonathanolson do we need to redeploy a maintenance release of density after the node/npm versions have been updated on the server?  If not, is there anything else to do for this issue?

**Comment by jonathanolson** [comment]
> If not, is there anything else to do for this issue?

I'm not sure, did the Density production deploy succeed?

**Comment by samreid** [comment]
It doesn't appear the density production deploy succeeded.  The comment in https://github.com/phetsims/chipper/issues/1171#issuecomment-1088816728 sounds like it errored out.  And looking at the timestamps in https://phet.colorado.edu/sims/html/density/latest/ seems like last publication was Jan 31.  But I'm a little foggy on this issue--won't updating node/npm on the server address the problem by itself?  Or do we also need to maintenance release the sim?

**Comment by samreid** [comment]
From my discussion with @marlitas, @jonathanolson recently did maintenance releases.  We don't recall density having acorn problems during that process.  Also, density is scheduled for upcoming release as part of phet-io efforts.  So we believe this issue can be closed.
