### ISSUE TITLE
Report a bug to JetBrains that imports are not added on autocomplete

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1172]
From https://github.com/phetsims/chipper/issues/1126

@jbphet @jessegreenberg and I confirmed that autocomplete no longer auto-imports even if you have that selected in the options.  We decided to try to reproduce this in a simple case, and, if it is reproducible, report it to JetBrains.  Also, does this affect js too or just ts?

**Comment by samreid** [comment]
This may be related to the monorepo package.json problem described in https://github.com/phetsims/chipper/issues/1166

**Comment by jessegreenberg** [comment]
I am pretty sure this is the same issue and would be fixed by https://github.com/phetsims/chipper/issues/1166, a report to jetbrains was submitted there.

**Comment by samreid** [comment]
This week WebStorm got even worse importing *.ts from *.ts.  I'm at version WebStorm 2022.2.1.  Still, this bug has been reported and our team is aware of the problem so I think this issue can be closed.
