### ISSUE TITLE
Can we optimize the precommit hook by asking it to check in with the watch process?

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1174]
Similar to #1173, I also considered wiring up the precommit hook to the watcher process so the precommit hook just asks the watch process if it is good to go.

I also realized that if you change code in e.g., sun you need to run the type checker not just on sun and its dependencies, but on things that use sun (things that have sun as a dependency) so you can make sure they didn’t break.

**Comment by samreid** [comment]
At today's meeting, CM and CK mentioned this may not be too useful given their current workflows.

**Comment by samreid** [comment]
We haven't been using the watch process much for type checking, and have made improvements in speedup of running the full type checker.  But I recall @zepumph was interested in this feature.  @zepumph should we close this, or leave open and unassigned, or increase priority?

**Comment by zepumph** [comment]
>We haven't been using the watch process much for type checking

FYI This is the only way that I am type checking at this time. 

I think we should close this issue.
