### ISSUE TITLE
README.md: WARNING404: Skipping potentially non-public dependency

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#1176]
@samreid while you're working on updating README.md files for https://github.com/phetsims/chipper/issues/1157, here's an additional wart related to PhET-iO.

README.md for all sims says:

> (2) Build the sim: `grunt --brands=adapted-from-phet`

That results in a number of warnings:

```
% cd example-sim
% grunt --brands=adapted-from-phet
Building brand: adapted-from-phet
>> Webpack build complete: 3197ms
>> WARNING404: Skipping potentially non-public dependency phet-io
>> WARNING404: Skipping potentially non-public dependency phet-io-client-guides
>> WARNING404: Skipping potentially non-public dependency phet-io-wrappers
>> WARNING404: Skipping potentially non-public dependency studio
>> Production minification complete: 15802ms (1584600 bytes)
>> Debug minification complete: 0ms (17701996 bytes)

Done.
```

Should README.md indicate that it's safe to ignore these warnings?

**Comment by samreid** [comment]
I added a message to the template and it can be published when https://github.com/phetsims/chipper/issues/1157 proceeds.  Closing.
