### ISSUE TITLE
Rename media files and imports

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1177]
For https://github.com/phetsims/chipper/issues/1060.  @jessegreenberg volunteered to fill in details.

JG EDIT: Here is the list of repos with lint failures from `default-import-match-filename`. In order to test in your repo, uncomment this line in chipper's .eslintrc file and run `lint`.

```
    // 'default-import-match-filename': 'error'
```

If you need to disable the lint rule, you can use 
```js
// eslint-disable-line default-import-match-filename
```

- [x] acid-base-solutions (@pixelzoom)
- [x] area-builder (@jbphet)
- [x] area-model-common (@jonathanolson)
- [x] arithmetic (@jbphet)
- [x] balancing-act (@jbphet)
- [x] balloons-and-static-electricity (@jessegreenberg)
- [x] brand (@zepumph)
- [x] build-a-molecule (@jonathanolson)
- [x] build-a-nucleus (@chrisklus)
- [x] build-an-atom (@jbphet)
- [x] capacitor-lab-basics (@jonathanolson)
- [x] charges-and-fields (@jonathanolson)
- [x] circuit-construction-kit-black-box-study (@samreid)
- [x] color-vision (@chrisklus)
- [x] coulombs-law (@zepumph)
- [x] counting-common (@chrisklus)
- [x] density-buoyancy-common (@jonathanolson)
- [x] dot (@jonathanolson)
- [x] energy-forms-and-changes (@chrisklus)
- [x] energy-skate-park-basics (@jessegreenberg)
- [x] energy-skate-park (@jessegreenberg)
- [x] estimation (@jbphet)
- [x] expression-exchange (@jbphet)
- [x] faradays-law (@jbphet)
- [x] fluid-pressure-and-flow (@zepumph)
- [x] forces-and-motion-basics (@jessegreenberg)
- [x] fractions-common (@jonathanolson)
- [x] friction (@zepumph)
- [x] gene-expression-essentials (@jbphet)
- [x] geometric-optics (@pixelzoom)
- [x] gravity-force-lab (@zepumph)
- [x] greenhouse-effect (@jbphet/@jessegreenberg)
- [x] interaction-dashboard (@zepumph)
- [x] inverse-square-law-common (@zepumph)
- [x] isotopes-and-atomic-mass (@jbphet)
- [x] john-travoltage (@jessegreenberg)
- [x] joist (@zepumph)
- [x] kite (@jonathanolson)
- [x] make-a-ten (@jonathanolson)
- [x] masses-and-springs-basics (@chrisklus)
- [x] masses-and-springs (@chrisklus)
- [x] molarity (@zepumph)
- [x] molecule-shapes (@jonathanolson)
- [x] neuron (@jbphet)
- [x] number-line-common (@jbphet)
- [x] number-line-distance (@jbphet)
- [x] number-line-integers (@jbphet)
- [x] number-line-operations (@jbphet)
- [x] number-play (@chrisklus)
- [x] ohms-law (@jbphet)
- [x] pendulum-lab (@jonathanolson)
- [x] phet-io-test-sim (@chrisklus)
- [x] plinko-probability (@chrisklus)
- [x] projectile-motion (@jbphet)
- [x] proportion-playground (@jonathanolson)
- [x] quadrilateral (@jessegreenberg)
- [x] ratio-and-proportion (@zepumph)
- [x] resistance-in-a-wire (@jbphet)
- [x] rutherford-scattering (@jessegreenberg)
- [x] scenery-phet (@pixelzoom)
- [x] scenery (@jonathanolson)
- [x] states-of-matter (@jbphet)
- [x] tambo (@jbphet)
- [x] trig-tour (@jessegreenberg)
- [x] utterance-queue (@zepumph/@jessegreenberg)
- [x] vegas (@jbphet)
- [x] vibe (@jbphet)
- [x] wave-on-a-string (@jonathanolson)

**Comment by jessegreenberg** [comment]
Repos currently failing `default-import-match-filename` have been added in the checklist above with responsible devs noted. Chipping can commence!

**Comment by pixelzoom** [comment]
My repos are done. I'm looking forward to when we can enable `default-import-match-filename`, because this is the second time I've done this, and new errors had snuck in.

**Comment by pixelzoom** [comment]
I noticed that someone else was assigned to scenery-phet, and I'm the responsible dev. So I took care of scenery-phet too.

**Comment by zepumph** [comment]
I have 3 more repos still to get to that I haven't yet, but along the way, I'm finding that some of my repo's errors are from common code sounds or images. In my opinion this is the job of the person fixing that common code, and not something to do eagerly in my sim. Furthermore I think it would be easiest if everyone did their sims first before working on common code, but that isn't likely a universal opinion. I'll pick this up next time!

**Comment by zepumph** [comment]
I though I'd post a pretty helpful script I've used in 2 repos for ~200 files thus far. I hope others find it useful!

```js
const fs = require( 'fs' );

const path = '../ratio-and-proportion/assets/staccato/';
const files = fs.readdirSync( path );
console.log( files );

files.forEach( file => {

  const newFileName = file.replace( /-./g, function( match ) {
    return match.replace( '-', '' ).toUpperCase();
  } );
  console.log( newFileName );
  if ( file !== newFileName ) {
    fs.renameSync( path + file, path + newFileName );
  }
} );
```

**Comment by zepumph** [comment]
Ok. I have a new path forward on usages of common-code repo media used in my sim but that hasn't been converted yet. I found it best to rename the variable to what the resource WILL be, even though the common code `.js` file still has hyphens. This will greatly decrease the burden of some of the giant repos (I'm looking at you tambo). If everyone did that I think it would be really nice.

**Comment by zepumph** [comment]
I finished with my sims. and common code. In regards to eagerly changing variable names to camel case even when the common code resources haven't been changed yet (see https://github.com/phetsims/chipper/issues/1177#issuecomment-997065783), I actually found a bug that is working in my favor for that. https://github.com/phetsims/chipper/issues/1060#issuecomment-997071841. When I convert things like that 
(https://github.com/phetsims/molarity/blob/488c56e8289760a07c636f2df4c3895f51296718/js/molarity/view/SoluteSelectionSoundGenerator.js#L10-L18), the lint rule is fine with the discrepancy. Just noting here, but we will work on it in the other issue.

**Comment by chrisklus** [comment]
I finished my sims. Thanks @zepumph for the helpful script from https://github.com/phetsims/chipper/issues/1177#issuecomment-997063327!

**Comment by samreid** [comment]
From slack:


Michael Kauzmann  8:54 AM
Good job team, we are down to 638 lint errors for the media import matching. Almost halfway!
8:55
My experience, and what I have heard from a few I've talked to is that it is slow, annoying, and quite manual. My recommendation is to push on this as much as possible so that we can turn the lint rule on in master before more of these errors pop up.
8:55
(of course that's my biased opinion since I'm already done with my sims)






Sam Reid  9:15 AM
Have you been using a semi-automated process?  Should we divide up the remaining to other devs?

Michael Kauzmann  9:22 AM
My "semi-automated" was only used twice, when I found 125 pictures in inverse-square-law-common, and ~20 sounds in ratio and proportion. My automated process was documented in https://github.com/phetsims/chipper/issues/1177#issuecomment-997063327 and https://phetsims.slack.com/archives/C6HPE0J91/p1639700730389300?thread_ts=1639698381.384400&cid=C6HPE0J91. I feel like the process is really procedural, and I wouldn't have any problem with others fixing my sims. I'd be happy to take on a few more sims.
Michael Kauzmann
const fs = require( 'fs' );

const path = '../inverse-square-law-common/images/';
const files = fs.readdirSync( path );
console.log( files );
Show more
From a thread in #dev-public | Dec 16th | View reply

Sam Reid  9:24 AM
So git picks up on those renames even if you don’t use git mv?

Chris Klusendorf:spiral_calendar_pad:  9:26 AM
yes, everything was marked as a rename when i used that
9:26
i’m happy to take on some more today too

Sam Reid  9:26 AM
That’s great!

Michael Kauzmann  9:27 AM
hmmm, it seems like I blew away the histories with the process I did. Except it sorta looks like I only did sometimes?  Not sure
9:27
This shows no history: https://github.com/phetsims/inverse-square-law-common/commits/master/images/figurePull_3.png
9:28
But this does seem to show the history:
image.png 
image.png



Chris Klusendorf:spiral_calendar_pad:  9:28 AM
oh weird, mine too. the commit is listed as a rename in WebStorm and GitHub, but there is no git history on the file

Michael Kauzmann  9:29 AM
Anyways, I felt fine about blowing it away because these resources have such a limited history, and I don't foresee myself caring about them often.
9:29
If I do need the history, I can just look at the history for the whole directory, which will have few enough commits that it is easy to track: https://github.com/phetsims/inverse-square-law-common/commits/master/images
9:29
I hope that helps.

Sam Reid  9:29 AM
Ratio and proportion history seemed tracked

Michael Kauzmann  9:30 AM
Yes, I was seeing it was by github.
9:30
I made sure that my commits in webstorm looks like "X renamed from Y" instead of deleted + new file creations.
:+1::skin-tone-2:
1

9:30
If anyone is worried though, just rewrite my script using git mv.

**Comment by chrisklus** [comment]
From 1/27/21 dev meeting: we checked in on this, and we're getting close!

**Comment by jonathanolson** [comment]
Handled my repos.

**Comment by zepumph** [comment]
Just 85 errors left!

**Comment by jbphet** [comment]
Mine are done.  Whew.  I tried turning on the rule and running `grunt lint-everything`, and there were a few failures.  I'm going to assign this to the developers who own those repos.  The last one to fix their stuff can turn on the lint rule.

- [ ] chipper @jonathanolson
- [ ] density @jonathanolson
- [ ] inverse-square-law-common @zepumph 
- [ ] quadrilateral @jessegreenberg 
- [ ] simula-rasa @pixelzoom
- [ ] wave-interference @samreid

**Comment by zepumph** [comment]
There seem to be less than 15 left. I'll take it from here.

**Comment by zepumph** [comment]
Thanks @jbphet for crunching on this for the past few weeks. I turning it on in the above commit, with no errors. Closing!
