### ISSUE TITLE
clean up generation of dependencies.json

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#118]
Entries in dependencies.json are currently in reverse order of phetLibs in package.json, because of this line in function `nextDependency` of Gruntfile:

> 571 var dependency = dependencies.pop();

**Comment by pixelzoom** [comment]
@jonathanolson a question...

This bit of code below is from chipper/js/grunt/Gruntfile.js (line 477). It deals with adding the "comment" field to dependencies.json (the final field added) and writing the file.  It seems out of place in function `postMipmapLoad`.  Is there any reason why it can't live with the rest of the code that generates dependencies.json, in function `nextDependency`? 

```js
      var comment = '# ' + pkg.name + ' ' + pkg.version + ' ' + (new Date().toString());

      // protect against repos or other attributions named 'comment'
      assert( !dependencyInfo.comment, 'there was already a "comment" dependency!' );
      dependencyInfo.comment = comment;

      grunt.file.write( 'build/dependencies.json', JSON.stringify( dependencyInfo, null, 2 ) + '\n' );
```

**Comment by jonathanolson** [comment]
No reason, committed the change to put the dependency logic back in a better order.

**Comment by pixelzoom** [comment]
Thanks @jonathanolson.

**Comment by pixelzoom** [comment]
dependencies.json is now more human readable. The "comment" is at the top of the file, and the fields are in the same order as phetLib. I also added a check to prevent duplicate field (including "comment").

Closing, feel free to review if anyone is so inclined.
