### ISSUE TITLE
Text of A11y View Tool Updated - need to rebuild

### ISSUE THREAD

**Issue by terracoda** [phetsims/chipper#1183]
@zepumph, I have updated the text in the following file using a few live commits:
https://github.com/phetsims/chipper/blob/master/templates/sim-a11y-view.html

Please update the A11y Views that use this common code.

Actually, it would be nice to what sims are using this common code. If easy, please put a list here in this issue.

**Comment by zepumph** [comment]
Yes thanks, sorry I lost track of this issue. Pushing now, they should come through

>Actually, it would be nice to what sims are using this common code. If easy, please put a list here in this issue.


This is the list of sims that have an a11y view: https://github.com/phetsims/perennial/blob/master/data/interactive-description. Feel free to book mark that if you'd like.
