### ISSUE TITLE
Transpiler improvements

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#1188]
While trying to get https://github.com/phetsims/a11y-research/issues/170 to work. I made three changes within the Transpiler to help support this:

1. I want to ignore the same paths on file visiting as we do for watch. (This is to support `a11y-research/js/phrase-builder/node_modules` which is a weird structure to support linting).
2. For windows, we needed to factor out forward slash path conversion 
3. I found that a keyboard interrupt had a change of destroying out cache, so I set it up to write our status when you interrupt.

**Comment by zepumph** [comment]
@samreid, please review this commit.

**Comment by samreid** [comment]
> I found that a keyboard interrupt had a change of destroying out cache, so I set it up to write our status when you interrupt.

Since the cache file is written each time a change is observed, I suspect the only way interrupt was breaking the cache was if the cache file was being written at the time of ctrl+c and hence not fully written.  The proposal seems reasonable, especially if it avoids the problem on windows.

**Comment by zepumph** [comment]
Ready to close?

**Comment by samreid** [comment]
Sounds good, thanks!
