### ISSUE TITLE
npm update failing

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#1189]
Console output:

```
macbook-pro:~/phet/git/chipper # npm update

> jsdoc@3.6.8 preinstall /Users/jon/phet/git/chipper/node_modules/jsdoc
> npx npm-force-resolutions

npx: installed 6 in 4.368s
Error: ENOENT: no such file or directory, open './package-lock.json'
    at Object.openSync (fs.js:461:3)
    at Object.fs [as readFileSync] (fs.js:364:35)
    at npm_force_resolutions$core$node_slurp (/Users/jon/.npm/_npx/4932/lib/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.cljs:15:20)
    at npm_force_resolutions$core$read_json (/Users/jon/.npm/_npx/4932/lib/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.cljs:22:23)
    at switch__2144__auto__ (/Users/jon/.npm/_npx/4932/lib/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.cljs:151:3)
    at /Users/jon/.npm/_npx/4932/lib/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.cljs:151:3
    at npm_force_resolutions$core$update_package_lock_$_state_machine__2145__auto____1 (/Users/jon/.npm/_npx/4932/lib/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.js:648:4)
    at cljs.core.async.impl.ioc-helpers/FN-IDX (/Users/jon/.npm/_npx/4932/lib/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.js:664:88)
    at cljs.core.async.impl.ioc-helpers/run-state-machine (/Users/jon/.npm/_npx/4932/lib/node_modules/npm-force-resolutions/out/cljs/core/async/impl/ioc_helpers.cljs:35:23)
    at cljs$core$async$impl$ioc_helpers$run_state_machine_wrapped (/Users/jon/.npm/_npx/4932/lib/node_modules/npm-force-resolutions/out/cljs/core/async/impl/ioc_helpers.cljs:39:6)
npm WARN notsup Unsupported engine for klaw@4.0.1: wanted: {"node":">=14.14.0"} (current: {"node":"14.4.0","npm":"6.14.5"})
npm WARN notsup Not compatible with your version of node/npm: klaw@4.0.1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jsdoc@3.6.8 preinstall: `npx npm-force-resolutions`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jsdoc@3.6.8 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jon/.npm/_logs/2022-01-22T22_08_41_899Z-debug.log
```

Looks related to https://github.com/jsdoc/jsdoc/issues/1970. Specifying the exact version of 3.6.7 works to get master working again. If this isn't fixed soon, I'll need to maintenance-release this for all sims that specify jsdoc as a dependency (probably everything).

**Comment by samreid** [comment]
I saw a build error email today which also seemed related to jsdoc, but this error ended with 

```
> jsdoc@3.6.9 preinstall /data/share/phet/phet-repos/chipper/node_modules/jsdoc
> npx force-resolutions


stderr:
Cannot find module 'find-up'
```

<details>

```


Build failure: Error: Build aborted, Error: npm update in ../chipper failed with exit code 1
stdout:

> jsdoc@3.6.9 preinstall /data/share/phet/phet-repos/chipper/node_modules/jsdoc
> npx force-resolutions


stderr:
Cannot find module 'find-up'
Require stack:
- /usr/local/lib/node_modules/npm/node_modules/yargs/yargs.js
- /usr/local/lib/node_modules/npm/node_modules/yargs/index.js
- /usr/local/lib/node_modules/npm/node_modules/libnpx/y.js
- /usr/local/lib/node_modules/npm/node_modules/libnpx/index.js
- /usr/local/lib/node_modules/npm/bin/npx-cli.js
npm WARN notsup Unsupported engine for @typescript-eslint/parser@5.4.0: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"14.15.0","npm":"6.14.8"})
npm WARN notsup Not compatible with your version of node/npm: @typescript-eslint/parser@5.4.0
npm WARN notsup Unsupported engine for @typescript-eslint/scope-manager@5.4.0: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"14.15.0","npm":"6.14.8"})
npm WARN notsup Not compatible with your version of node/npm: @typescript-eslint/scope-manager@5.4.0
npm WARN notsup Unsupported engine for @typescript-eslint/types@5.4.0: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"14.15.0","npm":"6.14.8"})
npm WARN notsup Not compatible with your version of node/npm: @typescript-eslint/types@5.4.0
npm WARN notsup Unsupported engine for @typescript-eslint/typescript-estree@5.4.0: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"14.15.0","npm":"6.14.8"})
npm WARN notsup Not compatible with your version of node/npm: @typescript-eslint/typescript-estree@5.4.0
npm WARN notsup Unsupported engine for @typescript-eslint/visitor-keys@5.4.0: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"14.15.0","npm":"6.14.8"})
npm WARN notsup Not compatible with your version of node/npm: @typescript-eslint/visitor-keys@5.4.0
npm WARN notsup Unsupported engine for eslint-visitor-keys@3.2.0: wanted: {"node":"^12.22.0 || ^14.17.0 || >=16.0.0"} (current: {"node":"14.15.0","npm":"6.14.8"})
npm WARN notsup Not compatible with your version of node/npm: eslint-visitor-keys@3.2.0
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jsdoc@3.6.9 preinstall: `npx force-resolutions`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jsdoc@3.6.9 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/phet-admin/.npm/_logs/2022-01-23T15_20_58_696Z-debug.log
. Sim = density Version = 1.0.0 Brands = phet Locales = de Shas = {"comment":"# density 1.0.0 Fri Jan 21 2022 01:19:57 GMT-0700 (Mountain Standard Time)","assert":{"sha":"767b2f345518ceca5144a152ecf40cd4f9206136","branch":"HEAD"},"axon":{"sha":"aa2c970c5779fc1720a460f78487bd0a7e924404","branch":"HEAD"},"brand":{"sha":"abb2576ef6eb66541c6ff4524ab510e82e90303d","branch":"HEAD"},"chipper":{"sha":"50745bb81febca9928d065a597b78f6e3c23328c","branch":"HEAD"},"density":{"sha":"9d5622e57ab8d7a177302e3767a513393fdaf5e6","branch":"HEAD"},"density-buoyancy-common":{"sha":"e546736f2130e53fcff47a1e1349aa742be598da","branch":"HEAD"},"dot":{"sha":"67d17a901ca09970b8a74bcb611e48ba56404342","branch":"HEAD"},"joist":{"sha":"0d2bc615e4af7359ce56f9f7dd026f0b20b450e6","branch":"HEAD"},"kite":{"sha":"94e901a5ad9dfeac064fbff98fa9c3f8c3af070e","branch":"HEAD"},"mobius":{"sha":"d8749a3214a61d6d024bf75925b92b81b772e4fd","branch":"HEAD"},"perennial-alias":{"sha":"c8decf5124f0e2cc4385aabb7d859968c6ac8c5e","branch":"HEAD"},"phet-core":{"sha":"ff5e2d807780372c93817762b5d4871caf339f68","branch":"HEAD"},"phet-io":{"sha":"b5eb55a8177bb90b4e3582665422baebd5f4da11","branch":"HEAD"},"phet-io-client-guides":{"sha":"5581f49ac259d26d54c894a124a6f78c6692374f","branch":"HEAD"},"phet-io-wrappers":{"sha":"f928c2ff2ad0213d3e4cfcc51660f4c876995d26","branch":"HEAD"},"phetcommon":{"sha":"0dd5378b39009e61ec33e7285e6744b681adc8d4","branch":"HEAD"},"phetmarks":{"sha":"64b01a476a9b51471d8080dc8962df6cc0ed5e29","branch":"HEAD"},"query-string-machine":{"sha":"b34079414b982587bd382a81a254e9f362e8772c","branch":"HEAD"},"scenery":{"sha":"acfc20214421a4046a50317e5d82a20f23a39f71","branch":"HEAD"},"scenery-phet":{"sha":"81161107c34fa974f3cb2793dc047e8ab785010d","branch":"HEAD"},"sherpa":{"sha":"d5332473697c551771c9bae4a4817029f4ed9ced","branch":"HEAD"},"studio":{"sha":"fd30dce1c9d1ce4922fd0e530f1d5b02a51361f8","branch":"HEAD"},"sun":{"sha":"a7e59583e25b55e42999fc4b0ec9ad28c3ec9196","branch":"HEAD"},"tambo":{"sha":"2e713a4dd6b1028df098b56fbf1f7c7168ef77ca","branch":"HEAD"},"tandem":{"sha":"6ca834eec5e7830f193dd4bee374379a78bdb9e1","branch":"HEAD"},"twixt":{"sha":"bcdd52a5630885b865ddd99bc6927e5203b03897","branch":"HEAD"},"utterance-queue":{"sha":"228711ef351cf188ba1c8fa6b656eb75c874742f","branch":"HEAD"}}



```

</details>

**Comment by jonathanolson** [comment]
Deployed verions:

atomic-interactions 1.2 ()

- [ ] [atomic-interactions 1.2.4](https://phet.colorado.edu/sims/html/atomic-interactions/1.2.4/atomic-interactions_en.html)

balancing-act 1.2 ()

- [ ] [balancing-act 1.2.9 phet-io](https://phet-io.colorado.edu/sims/balancing-act/1.2.9/balancing-act_all_phet-io.html?phetioStandalone)
- [ ] [balancing-act 1.2.9 phet-io Studio](https://phet-io.colorado.edu/sims/balancing-act/1.2.9/wrappers/studio)

build-a-molecule 1.0 ()

- [ ] [build-a-molecule 1.0.6](https://phet.colorado.edu/sims/html/build-a-molecule/1.0.6/build-a-molecule_en.html)

circuit-construction-kit-ac 1.0 ()

- [ ] [circuit-construction-kit-ac 1.0.1](https://phet.colorado.edu/sims/html/circuit-construction-kit-ac/1.0.1/circuit-construction-kit-ac_en.html)

circuit-construction-kit-ac-virtual-lab 1.0 ()

- [ ] [circuit-construction-kit-ac-virtual-lab 1.0.1](https://phet.colorado.edu/sims/html/circuit-construction-kit-ac-virtual-lab/1.0.1/circuit-construction-kit-ac-virtual-lab_en.html)

circuit-construction-kit-dc 1.2 ()

- [ ] [circuit-construction-kit-dc 1.2.7](https://phet.colorado.edu/sims/html/circuit-construction-kit-dc/1.2.7/circuit-construction-kit-dc_en.html)

circuit-construction-kit-dc-virtual-lab 1.2 ()

- [ ] [circuit-construction-kit-dc-virtual-lab 1.2.7](https://phet.colorado.edu/sims/html/circuit-construction-kit-dc-virtual-lab/1.2.7/circuit-construction-kit-dc-virtual-lab_en.html)

collision-lab 1.1 ()

- [ ] [collision-lab 1.1.5](https://phet.colorado.edu/sims/html/collision-lab/1.1.5/collision-lab_en.html)

density 1.0 ()

- [ ] [density 1.0.1](https://phet.colorado.edu/sims/html/density/1.0.1/density_en.html)
- [ ] [density 1.0.1 phet-io](https://phet-io.colorado.edu/sims/density/1.0.1/density_all_phet-io.html?phetioStandalone)
- [ ] [density 1.0.1 phet-io Studio](https://phet-io.colorado.edu/sims/density/1.0.1/wrappers/studio)

energy-forms-and-changes 1.4 ()

- [ ] [energy-forms-and-changes 1.4.4](https://phet.colorado.edu/sims/html/energy-forms-and-changes/1.4.4/energy-forms-and-changes_en.html)
- [ ] [energy-forms-and-changes 1.4.4 phet-io](https://phet-io.colorado.edu/sims/energy-forms-and-changes/1.4.4/energy-forms-and-changes_all_phet-io.html?phetioStandalone)
- [ ] [energy-forms-and-changes 1.4.4 phet-io Studio](https://phet-io.colorado.edu/sims/energy-forms-and-changes/1.4.4/wrappers/studio)

energy-skate-park 1.1 ()

- [ ] [energy-skate-park 1.1.5](https://phet.colorado.edu/sims/html/energy-skate-park/1.1.5/energy-skate-park_en.html)

equality-explorer 1.1 ()

- [ ] [equality-explorer 1.1.1](https://phet.colorado.edu/sims/html/equality-explorer/1.1.1/equality-explorer_en.html)

faradays-law 1.4 ()

- [ ] [faradays-law 1.4.6](https://phet.colorado.edu/sims/html/faradays-law/1.4.6/faradays-law_en.html)

graphing-quadratics 1.1 ()

- [ ] [graphing-quadratics 1.1.8 phet-io](https://phet-io.colorado.edu/sims/graphing-quadratics/1.1.8/graphing-quadratics_all_phet-io.html?phetioStandalone)
- [ ] [graphing-quadratics 1.1.8 phet-io Studio](https://phet-io.colorado.edu/sims/graphing-quadratics/1.1.8/wrappers/studio)

graphing-quadratics 1.2 ()

- [ ] [graphing-quadratics 1.2.3](https://phet.colorado.edu/sims/html/graphing-quadratics/1.2.3/graphing-quadratics_en.html)
- [ ] [graphing-quadratics 1.2.3 phet-io](https://phet-io.colorado.edu/sims/graphing-quadratics/1.2.3/graphing-quadratics_all_phet-io.html?phetioStandalone)
- [ ] [graphing-quadratics 1.2.3 phet-io Studio](https://phet-io.colorado.edu/sims/graphing-quadratics/1.2.3/wrappers/studio)

gravity-and-orbits 1.4 ()

- [ ] [gravity-and-orbits 1.4.4 phet-io](https://phet-io.colorado.edu/sims/gravity-and-orbits/1.4.4/gravity-and-orbits_all_phet-io.html?phetioStandalone)
- [ ] [gravity-and-orbits 1.4.4 phet-io Studio](https://phet-io.colorado.edu/sims/gravity-and-orbits/1.4.4/wrappers/studio)

gravity-and-orbits 1.5 ()

- [ ] [gravity-and-orbits 1.5.3](https://phet.colorado.edu/sims/html/gravity-and-orbits/1.5.3/gravity-and-orbits_en.html)
- [ ] [gravity-and-orbits 1.5.3 phet-io](https://phet-io.colorado.edu/sims/gravity-and-orbits/1.5.3/gravity-and-orbits_all_phet-io.html?phetioStandalone)
- [ ] [gravity-and-orbits 1.5.3 phet-io Studio](https://phet-io.colorado.edu/sims/gravity-and-orbits/1.5.3/wrappers/studio)

gravity-force-lab 2.2 ()

- [ ] [gravity-force-lab 2.2.6](https://phet.colorado.edu/sims/html/gravity-force-lab/2.2.6/gravity-force-lab_en.html)
- [ ] [gravity-force-lab 2.2.6 phet-io](https://phet-io.colorado.edu/sims/gravity-force-lab/2.2.6/gravity-force-lab_all_phet-io.html?phetioStandalone)
- [ ] [gravity-force-lab 2.2.6 phet-io Studio](https://phet-io.colorado.edu/sims/gravity-force-lab/2.2.6/wrappers/studio)

gravity-force-lab-basics 1.1 ()

- [ ] [gravity-force-lab-basics 1.1.2](https://phet.colorado.edu/sims/html/gravity-force-lab-basics/1.1.2/gravity-force-lab-basics_en.html)

john-travoltage 1.6 ()

- [ ] [john-travoltage 1.6.3](https://phet.colorado.edu/sims/html/john-travoltage/1.6.3/john-travoltage_en.html)

molarity 1.4 ()

- [ ] [molarity 1.4.16 phet-io](https://phet-io.colorado.edu/sims/molarity/1.4.16/molarity_all_phet-io.html?phetioStandalone)
- [ ] [molarity 1.4.16 phet-io Studio](https://phet-io.colorado.edu/sims/molarity/1.4.16/wrappers/studio/studio.html?sim=molarity&relativeSimPath)

molarity 1.5 ()

- [ ] [molarity 1.5.6](https://phet.colorado.edu/sims/html/molarity/1.5.6/molarity_en.html)

molecule-polarity 1.2 ()

- [ ] [molecule-polarity 1.2.3](https://phet.colorado.edu/sims/html/molecule-polarity/1.2.3/molecule-polarity_en.html)
- [ ] [molecule-polarity 1.2.3 phet-io](https://phet-io.colorado.edu/sims/molecule-polarity/1.2.3/molecule-polarity_all_phet-io.html?phetioStandalone)
- [ ] [molecule-polarity 1.2.3 phet-io Studio](https://phet-io.colorado.edu/sims/molecule-polarity/1.2.3/wrappers/studio)

molecules-and-light 1.5 ()

- [ ] [molecules-and-light 1.5.13](https://phet.colorado.edu/sims/html/molecules-and-light/1.5.13/molecules-and-light_en.html)

natural-selection 1.2 ()

- [ ] [natural-selection 1.2.4 phet-io](https://phet-io.colorado.edu/sims/natural-selection/1.2.4/natural-selection_all_phet-io.html?phetioStandalone)
- [ ] [natural-selection 1.2.4 phet-io Studio](https://phet-io.colorado.edu/sims/natural-selection/1.2.4/wrappers/studio)

natural-selection 1.3 ()

- [ ] [natural-selection 1.3.4 phet-io](https://phet-io.colorado.edu/sims/natural-selection/1.3.4/natural-selection_all_phet-io.html?phetioStandalone)
- [ ] [natural-selection 1.3.4 phet-io Studio](https://phet-io.colorado.edu/sims/natural-selection/1.3.4/wrappers/studio)

natural-selection 1.4 ()

- [ ] [natural-selection 1.4.3](https://phet.colorado.edu/sims/html/natural-selection/1.4.3/natural-selection_en.html)
- [ ] [natural-selection 1.4.3 phet-io](https://phet-io.colorado.edu/sims/natural-selection/1.4.3/natural-selection_all_phet-io.html?phetioStandalone)
- [ ] [natural-selection 1.4.3 phet-io Studio](https://phet-io.colorado.edu/sims/natural-selection/1.4.3/wrappers/studio)

number-line-distance 1.0 ()

- [ ] [number-line-distance 1.0.2](https://phet.colorado.edu/sims/html/number-line-distance/1.0.2/number-line-distance_en.html)

number-line-integers 1.1 ()

- [ ] [number-line-integers 1.1.4](https://phet.colorado.edu/sims/html/number-line-integers/1.1.4/number-line-integers_en.html)

number-line-operations 1.0 ()

- [ ] [number-line-operations 1.0.5](https://phet.colorado.edu/sims/html/number-line-operations/1.0.5/number-line-operations_en.html)

ph-scale 1.5 ()

- [ ] [ph-scale 1.5.3](https://phet.colorado.edu/sims/html/ph-scale/1.5.3/ph-scale_en.html)
- [ ] [ph-scale 1.5.3 phet-io](https://phet-io.colorado.edu/sims/ph-scale/1.5.3/ph-scale_all_phet-io.html?phetioStandalone)
- [ ] [ph-scale 1.5.3 phet-io Studio](https://phet-io.colorado.edu/sims/ph-scale/1.5.3/wrappers/studio)

ph-scale-basics 1.5 ()

- [ ] [ph-scale-basics 1.5.3](https://phet.colorado.edu/sims/html/ph-scale-basics/1.5.3/ph-scale-basics_en.html)
- [ ] [ph-scale-basics 1.5.3 phet-io](https://phet-io.colorado.edu/sims/ph-scale-basics/1.5.3/ph-scale-basics_all_phet-io.html?phetioStandalone)
- [ ] [ph-scale-basics 1.5.3 phet-io Studio](https://phet-io.colorado.edu/sims/ph-scale-basics/1.5.3/wrappers/studio)

ratio-and-proportion 1.0 ()

- [ ] [ratio-and-proportion 1.0.5](https://phet.colorado.edu/sims/html/ratio-and-proportion/1.0.5/ratio-and-proportion_en.html)

states-of-matter 1.2 ()

- [ ] [states-of-matter 1.2.5](https://phet.colorado.edu/sims/html/states-of-matter/1.2.5/states-of-matter_en.html)
- [ ] [states-of-matter 1.2.5 phet-io](https://phet-io.colorado.edu/sims/states-of-matter/1.2.5/states-of-matter_all_phet-io.html?phetioStandalone)
- [ ] [states-of-matter 1.2.5 phet-io Studio](https://phet-io.colorado.edu/sims/states-of-matter/1.2.5/wrappers/studio)

states-of-matter-basics 1.2 ()

- [ ] [states-of-matter-basics 1.2.4](https://phet.colorado.edu/sims/html/states-of-matter-basics/1.2.4/states-of-matter-basics_en.html)
- [ ] [states-of-matter-basics 1.2.4 phet-io](https://phet-io.colorado.edu/sims/states-of-matter-basics/1.2.4/states-of-matter-basics_all_phet-io.html?phetioStandalone)
- [ ] [states-of-matter-basics 1.2.4 phet-io Studio](https://phet-io.colorado.edu/sims/states-of-matter-basics/1.2.4/wrappers/studio)

vector-addition 1.0 ()

- [ ] [vector-addition 1.0.3](https://phet.colorado.edu/sims/html/vector-addition/1.0.3/vector-addition_en.html)

vector-addition-equations 1.0 ()

- [ ] [vector-addition-equations 1.0.3](https://phet.colorado.edu/sims/html/vector-addition-equations/1.0.3/vector-addition-equations_en.html)

waves-intro 1.1 ()

- [ ] [waves-intro 1.1.6](https://phet.colorado.edu/sims/html/waves-intro/1.1.6/waves-intro_en.html)

**Comment by jonathanolson** [comment]
Scanned through, looks like production deploys worked for all of this. Closing!
