### ISSUE TITLE
Transpiler bug

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#1190]
Not sure if it is work fixing, but I thought I would note a case where the transpiler can get outdated and need restarting.

Steps to reproduce:
1. Have working copy changes in a file that cause a transpile ERROR (for example, an incomplete statement).
2. Start the transpiler, it will begin its initial transpilation phase.
3. Fix the error before the initial transpilation phase is done
4. Once the transpiler is watching, no changes will be made to the file, so it won't trigger a recompile.

Thus, you need to restart the transpiler before the changes of that file are picked up in dist.

@samreid, could this be solved by starting the watch process and then starting the initial transpilation? Since the initial transpile doesn't write to our main dirs, it shouldn't cause problems, right?

**Comment by zepumph** [comment]
I think that this solution isn't going to fix things because javascript is single threaded. 

For example, it is the same reason why SIGINT doesn't work during a clean transpile. https://stackoverflow.com/a/49458139/3408502

I bet we can just close this issue.

**Comment by samreid** [comment]
The proposal sounds reasonable and seems to be working well, so I committed it.  Ready for test/spot check.

**Comment by zepumph** [comment]
Excellent!
