### ISSUE TITLE
Can we add a composite options type to keep us organized and reduce the need for manually enforced conventions and boilerplate?

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1192]
While working on https://github.com/phetsims/chipper/issues/1128, it was clear that there is a lot of boilerplate and unenforced (or code review enforced) convention around the options pattern.  For instance, I have had to write a pattern like this many times:

```ts
type ResistorSelfOptions = {
  isMetallic: boolean;
  resistorType: any;
};
type ResistorOptions = ResistorSelfOptions & FixedCircuitElementOptions;
// ...
const options = optionize<ResistorOptions, ResistorSelfOptions, FixedCircuitElementOptions>( {
```

I have to manually keep track of 3 types and make sure they all end up in the right places.  I'm wondering and brainstorming if we can create a utility type that will help manage these parts for us and provide a convenient syntax for specifying the options, perhaps something like:

```ts
type ExtendOptions<Self, Parent, Combined = Self & Parent> = {
  selfOptions: Self;
  parentOptions: Parent;
  provided: Combined;
}
```

Then it would track each of the parts separately, then to combine options it would look like this:

```ts
type VoltageSourceOptions = ExtendOptions<{
  initialOrientation?: string, // TODO: enum
  voltage?: number,
  voltagePropertyOptions?: {
    range?: Range;
    tandem?: Tandem
  }
}, FixedCircuitElementOptions>;
```

Then optionize can just take the composite, like so:

```ts
const options = optionize<VoltageSourceOptions>( {
```

Would constructor signatures look like this, and is it a dealbreaker?

```ts
  constructor( startVertex: Vertex, providedOptions?: VoltageSourceOptions['provided'] ) {
```

Or if it is more palatable, write it like:

```ts
  constructor( startVertex: Vertex, providedOptions?: Provided<VoltageSourceOptions> ) {
```

I feel like there is a tension between flexibility and succinctness--it seems like this issue is looking for a succinctness that may reduce flexibility.  But maybe there is a way to have both (like in `ExtendOptions` having a 3rd option which the user can create however they want).  But beyond that, is this proposal boxing us in too much?

@zepumph what do you think?

**Comment by zepumph** [comment]
I could potentially see this being an improvement, but I want to think through this fully in terms of type space and value space.

The only thing we want to export is the public api for options (the providedOptions), so would it be something like this at the end of the file?

`export type { VoltageSourceOptions.providedOptions as VoltageSourceOptions }`

**Comment by zepumph** [comment]
@samreid and I met today and tried to get something like this working. The pattern of having a single composite type that holds all our needs for a Class's options was really appealing. We were calling it `ExtendedOptions`. The issue we ran into was in preventing type regressions when trying to pass it as a single argument to optionize. We could not get our type features with that single type parameter/argument. We will still work on it.

**Comment by zepumph** [comment]
@samreid and I brought this to dev meeting today, and most felt like the boilerplate of the current pattern was less than ideal, though most also felt like they could get used to it. We should continue on this pattern and see how far we can get.

**Comment by zepumph** [comment]
@samreid, let me know how you would like my assistance in moving forward on this issue.

**Comment by samreid** [comment]
I feel the existing solution is going ok, it is nice to sometimes be able to omit, require, etc.  So I think we need that flexibility in creating the provided options.  We also benefitted from EmptySelfOptions which streamlines the pattern a bit.  Combining all the types at the top into one thing doesn't seem a whole lot different than specifying them at the optionize call site.  I'm ok to self-assign from this issue for now, not quite confident enough to close it.

**Comment by zepumph** [comment]
>not quite confident enough to close it.

Your post made me confident enough. I don't see this pattern ever really taking off given our current options pattern and codebase. Please reopen though if you'd prefer
