### ISSUE TITLE
transpile.js needs to support 3rd-party sims 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#1195]
In https://github.com/phetsims/simula-rasa/issues/21, I discovered that a new sim created by following the [Create a New Sim](https://github.com/phetsims/phet-info/blob/master/doc/phet-development-overview.md#creating-a-new-sim) instructions cannot be run.  transpile.js will not know about it until you put it in perennial-alias/data/active-repos.

This workaround may be OK for PhET developers, but clearly doesn't work for 3rd parties.  We don't want 3rd parties modifying active-repos, and they shouldn't have to continually make a "temporary" entry in active-repos in order to do their development.

So what needs to be done here is:
- [x] Come up with a solution for 3rd parties sims
- [x] Document the solution in [Create a New Sim](https://github.com/phetsims/phet-info/blob/master/doc/phet-development-overview.md#creating-a-new-sim)

**Comment by samreid** [comment]
How about adding an option to `node js/scripts/transpile.js` that specifies additional watch directories?  Like: 

```
node js/scripts/transpile.js --watch --repos=../my-new-sim,../my-other-sim
```

I'd like feedback before working on this.  @pixelzoom and @zepumph does this sound like the right path?

**Comment by zepumph** [comment]
Yes. I think a `--repos` option makes sense, but instead of using paths, let's have it just be repos.

`node js/scripts/transpile.js --watch --repos=my-new-sim,my-other-sim`

**Comment by samreid** [comment]
Implemented and tested on a fake repo.  It seemed to work as expected on startup and during watch.  Ready for review.

**Comment by zepumph** [comment]
* see https://github.com/phetsims/chipper/commit/02a981a9b9d9e2183831dcaf639b5c2468afabfc#r80748337

For a second. I thought that it would be better and simpler to combine the activeRepos and provided-additional repos into a single list, but then I realized that activeRepos is reloaded from time to time during the watch. If that is an accurate assessment. Please feel free to close.

**Comment by zepumph** [comment]
Oh! One more thing. do we ever want to exclude intersection between activeRepos and repos, just to avoid extra work and potential confusion?

**Comment by samreid** [comment]
I considered the following ideas:

* Use _.uniq before processing transpileAll
* asserting that activeRepos don't overlap with --repos
* Creating a new list that combined activeRepos with repos, and updating it when activeRepos updated.

None of these seemed worth it to me, feel free to disagree, I'm happy to implement whichever is best.

**Comment by zepumph** [comment]
No need. Thanks for doing this. @pixelzoom anything else?

**Comment by pixelzoom** [comment]
Looks good. Nice doc in transpile.js and https://github.com/phetsims/phet-info/blob/master/doc/phet-development-overview.md#creating-a-new-sim.

Closing.
