### ISSUE TITLE
create-sim task generates erroneous README.md

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#120]
createSim.js currently generating an erroneous README.md, for example:

```
my-sim
===========

My Sim by Some Guy, using libraries from PhET Interactive Simulations at the University 
of Colorado Boulder (please see http://bit.ly/phet-development-overview for more). 
Readme file automatically created by https://github.com/phetsims/chipper

```

We should either cease generating the README.md in this taks, or run the `generate-unpublished-README` task.

**Comment by pixelzoom** [comment]
No way to easily generate the correct README.md, since you have to do so in the new repo directory. So for now 'create-sim' prints a reminder:

> Please generate README.md for your new repository using "grunt generate-unpublished-repo"

**Comment by aaronsamuel137** [comment]
Shouldn't this say "grunt generate-unpublished-README"?

**Comment by pixelzoom** [comment]
@aaronsamuel137 good catch, I'll fix it.

**Comment by pixelzoom** [comment]
Typo corrected.  

I'm going to leave it like this for now. That is, after running create-sim, you have to run generate-unpublished-README.  If someone else wants to automatically generate the README as part of the create-sim task, please open a new issue and go for it.
