### ISSUE TITLE
Confirm IE 11 error page is working as expected

### ISSUE THREAD

**Issue by chrisklus** [phetsims/chipper#1200]
From https://github.com/phetsims/chipper/issues/963#issuecomment-771308893.

@KatieWoe would you mind confirming that an IE 11 error page shows up when launching, say, a current RC sim in IE 11? 

I'm assuming it hasn't been tested since it's initial development in the summer of 2020, but would like to confirm with you. I don't think it's worth making this a regular step in testing but I think is worth a spot check right now.

**Comment by KatieWoe** [comment]
An error page that reads "Platform Error Internet Explorer is not supported. Please use a different browser to run this simulation." occurs when opening Density 1.0.0-rc.3 in IE.

**Comment by chrisklus** [comment]
Perfect, thanks for checking on this @KatieWoe! Closing.
