### ISSUE TITLE
Discuss instantiating in type declarations

### ISSUE THREAD

**Issue by chrisklus** [phetsims/chipper#1202]
From 2/28 supplemental TypeScript dev meeting, we mentioned it would be nice to revisit this.

@samreid mentioned that a new version of TS will allow this for subtypes as well, which makes this feature much more usable.

**Comment by jessegreenberg** [comment]
Some discussion today:

JO/CM: It distributes things. Some get instantiated at constructor other at definition. Can we allow this to be developer description?
JB: Does instantiating at declaration require `super` to be called first?
MK: Lets investigate that.
All: We like this being up to developer discretion but encourage devs to use consistency when possible.

@pixelzoom volunteered to update the documentation.
@zepumph is going to make a new issue to investigate whether super() must be called first, maybe we need to upgrade our TypeScript version.

Assigning to @pixelzoom to close when the documentation has been updated.

**Comment by pixelzoom** [comment]
Done, closing.
