### ISSUE TITLE
Clean up and maintain phet-types.d.ts entries in .eslintrc

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#1205]
chipper/eslint/.eslintrc has this section:

```
    //  FROM phet-types.d.ts
    ObservableArray: 'readonly',
    Assert: 'readonly',
    PhetioObjectOptions: 'readonly',
    NodeOptions: 'readonly',
    CanvasNodeOptions: 'readonly',
    ThermometerNodeOptions: 'readonly',
    ExpandCollapseButtonOptions: 'readonly',
    PanelOptions: 'readonly',
    LayoutBoxOptions: 'readonly',
    RectangleOptions: 'readonly',
    RoundPushButtonOptions: 'readonly',
    RoundButtonOptions: 'readonly',
    SoundClipOptions: 'readonly',
    SoundGeneratorOptions: 'readonly',
    PathOptions: 'readonly',
    ColorDef: 'readonly',
    ScreenViewOptions: 'readonly',
    AlerterOptions: 'readonly',
    PaintDef: 'readonly'
```

Many (most) of these types are no longer in phet-types.d.ts.  And some types that are in phet-types.d.ts are not listed here.  So developers have clearly not been maintaining this list as TypeScript conversion has been progressing -- probably because most of them (like me) didn't know about this.

Starting by assign to @samreid who added most of these.  How do we clean this up? Do we need a PSA about how to maintain this?

**Comment by samreid** [comment]
I removed unused types.  My recommendation for the other types is to delete them all, and encourage developers to port the common code where possible.  The types exported from phet-types.d.ts are:

```
ThermometerNodeOptions
RoundButtonOptions
RoundPushButtonOptions
ExpandCollapseButtonOptions
SoundClipOptions
QSMType
AlerterOptions
```

Eventually phet-types.d.ts would be exclusively for preloads like assert/query string machine.  Or we could have micro-d.ts files for each of those.  Let's chat at dev meeting.

**Comment by jonathanolson** [comment]
Decision: For the non-preload options, we'll get rid of them over the next week or so. For preloads, we'll discuss next week what to do.

**Comment by zepumph** [comment]
Done in https://github.com/phetsims/scenery-phet/issues/727. Unassigning.

**Comment by pixelzoom** [comment]
The "FROM phet-types.d.ts" section is now totally gone.  So closing this issue.
