### ISSUE TITLE
Migrate the build stack to Deno

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1206]
Deno https://deno.land/ describes itself as: Deno is a simple, modern and secure runtime for JavaScript and TypeScript that uses V8 and is built in Rust.

It has built-in support for TypeScript, and looks to have a superior package manager system to node.  We have numerous other issues with the existing package management system, and will one day want to be able to use TypeScript in our build side.  Deno looks like a good place to investigate.  A few hours of investigation may help us rule this out, but if we can go forward, this would be an epic-level issue, so I'll label it as such and add it to the project board.

**Comment by liam-mulhall** [comment]
It seems like more JS runtimes are cropping up: https://bun.sh/. Deno might not be the winner despite being worked on by Ryan Dahl. It would probably be a good idea to keep an eye on the various Node alternatives before we pick one.

**Comment by samreid** [comment]
Duplicate of https://github.com/phetsims/chipper/issues/1272, I'll close this one since the other one is already described in the project board.
