### ISSUE TITLE
Remove ObservableArray from phet-types.d.ts

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#1207]
... because ObservableArray is defined in createObservableArray.ts.

I took a stab at this, but there are ambient uses in CCK, and that's a diversion I don't have time for.  So assigning to @samreid.

**Comment by pixelzoom** [comment]
`cd chipper/tsconfig/all; tsc -b -w` show 79 errors when I remove ObservableArray from phet-types.d.ts.   So it's probably more than CCK that's expecting an ambinent declaration.

**Comment by samreid** [comment]
I removed ObservableArray from phet-types.d.ts and the type checker seems to be working OK with the version in axon.

**Comment by pixelzoom** [comment]
Reopening.  I still see this in chipper/eslint/.eslintrc.json.  Should it be removed?

```js
    //  FROM phet-types.d.ts
    ObservableArray: 'readonly',
    Assert: 'readonly'
```

**Comment by samreid** [comment]
Fixed in the commit, and the type checker is passing.  Closing but anyone feel free to reopen for any reason.
