### ISSUE TITLE
pattern for processing input events

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#121]
EnergyLine appears to be attempting to do something with the mouse:

```js
var mouse = require( 'SCENERY/input/Mouse' );
//...
while(mouse.over(width, this)){
```

You'll want to investigate adding an InputListener to your Node, via addInputListener. Examples are in the Scenery documentation, or search for addInputListener in other sim code.  You'll also be dealing with the more general "pointer", which works for desktop and mobile devices, and supports multitouch. "Mouse" is a desktop-only thing.

**Comment by samreid** [comment]
Is this in the right repo @pixelzoom ?

**Comment by pixelzoom** [comment]
Whoops, wrong repo. Moved to https://github.com/alecmartin/quantum-bound-states/issues/32.
