### ISSUE TITLE
Add TypeScript lint rule: "member-delimiter-style"

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#1210]
Tagging https://github.com/phetsims/chipper/issues/1114 and https://github.com/phetsims/ratio-and-proportion/issues/405.

This seems like an obvious and easy one to add (we have talked about it before in a dev meeting too). The 630+ errors can be auto fixed. Commits coming soon.

**Comment by pixelzoom** [comment]
We had concensus on this in a dev meeeting, and it looks like this has been enabled for 3+ weeks. @zepumph can this be closed?

**Comment by zepumph** [comment]
Yes please. Thanks
