### ISSUE TITLE
Use `override` modifier and turn on compiler option `noImplicitOverride`

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#1211]
Requiring `override` modifier for overridden methods would be really nice. See https://www.typescriptlang.org/tsconfig#noImplicitOverride.

**Comment by samreid** [comment]
@zepumph said:

>  I just looked through https://typescript-eslint.io/rules/ and didn’t see anything obvious for override keyword enforcement

This would be done through the noImplicitOverride rule in tsconfig.  It seems like a good idea, so I'm working through these.  I have changes in 218 files so far.  Any reason we wouldn't want this enabled?

**Comment by samreid** [comment]
Based on the docs and the recommendation from @pixelzoom, this seems like a good idea.  I'll push `override` keywords, then enable the tsconfig option.

**Comment by pixelzoom** [comment]
> This would be done through the noImplicitOverride rule in tsconfig.

I believe `noImplicitOverride` is actually a compiler option, not a rule. See https://www.typescriptlang.org/tsconfig#noImplicitOverride.

**Comment by samreid** [comment]
I messaged on slack:

> I pushed changes to many repos to enable a new compiler option: noImplicitOverride , see https://github.com/phetsims/chipper/issues/1211.  Local type checking and linting is passing. I’ll check CT in a column or two just in case.
Please pull at your convenience and report any errors.  Please be advised you will need to use the override modifier when overriding something.

**Comment by samreid** [comment]
Leaving open for dev meeting PSA.

**Comment by pixelzoom** [comment]
After a pull-all and `tsc -b --clean`, I'm seeing some related TS errors:

```
../../../sun/js/Panel.ts:162:10 - error TS4114: This member must have an 'override' modifier because it overrides a member in the base class '{ preferredWidthProperty: TinyProperty<number | null>; minimumWidthProperty: TinyProperty<number | null>; preferredWidth: number | null; minimumWidth: number | null; readonly widthSizable: boolean; } & { ...; } & Node'.

162   static DEFAULT_OPTIONS = DEFAULT_OPTIONS;
             ~~~~~~~~~~~~~~~

../../../sun/js/buttons/RectangularRadioButton.ts:198:10 - error TS4114: This member must have an 'override' modifier because it overrides a member in the base class 'RectangularButton'.

198   static FlatAppearanceStrategy: TButtonAppearanceStrategy = class FlatAppearanceStrategy {
```

**Comment by pixelzoom** [comment]
Both of these look problematic. Do we really want to override static fields in the superclass?

**Comment by samreid** [comment]
Can you please check that you pulled https://github.com/phetsims/sun/commit/fdc04728b8f93ea3ddb4b47bd93c9d886ffc1ce7 ?

**Comment by pixelzoom** [comment]
Hmmm...  I did pull-all after your announcement to Slack dev-public, and didn't get https://github.com/phetsims/sun/commit/fdc04728b8f93ea3ddb4b47bd93c9d886ffc1ce7. Another pull-all and I'm now showing zero TS errors.

**Comment by pixelzoom** [comment]
Were these `override`s reviewed for potential problems, or did you just add them whereever an error was reported?  In at least one place (see https://github.com/phetsims/geometric-optics/issues/422) you've added an `override` that now masks a programming error.  So please review the commits that you made for possible programming errors.

**Comment by pixelzoom** [comment]
Here are several others that look suspicious:

```js
// CCK Wire.ts
  override readonly lengthProperty: NumberProperty;

// WilderEnumerationPattern.js
static override enumeration = new Enumeration( SpecialTreeType, {

// kite Arc.ts
static override deserialize( obj: SerializedArc ): Arc {
static override intersect( a: Arc, b: Arc ): SegmentIntersection[] {

// SubitizeObjectType.ts
static override enumeration = new Enumeration( SubitizeObjectType, {

// Panel.ts
static override DEFAULT_OPTIONS = DEFAULT_OPTIONS;

// RectangularRadioButton.ts
static override FlatAppearanceStrategy: TButtonAppearanceStrategy = class FlatAppearanceStrategy {
```

**Comment by samreid** [comment]
Thanks, I would add to that:

```
// Greenhouse LandscapeObservationWindow.ts
public static override SIZE = SIZE;
```

I spot checked each site during this commit, but I recommend having each responsible dev review the commit on their repo.  Should we make it a chip-away with checkboxes?

**Comment by zepumph** [comment]
> // WilderEnumerationPattern.js: static override enumeration = new Enumeration( SpecialTreeType, {


This is a correct and expected override call.

**Comment by jessegreenberg** [comment]
Discussed today:

The overrides listed in https://github.com/phetsims/chipper/issues/1211#issuecomment-1090296131 and https://github.com/phetsims/chipper/issues/1211#issuecomment-1090324028 may be issues. @samreid reviewed them and thought they look OK but we should have responsible devs review each one. Lets try to do this this week.

- [ ] @jbphet/ @jessegreenberg for the greenhouse case
- [ ] @samreid for CCK
- [ ] @zepumph for Wilder
- [ ] @chrisklus for the SubitizeObjectType
- [ ] @jonathanolson for Kite and Panel
- [ ] @jbphet for RectangularRadioButton.ts

@pixelzoom reviewed other overrides in the project and identified this list.

**Comment by jessegreenberg** [comment]
The one from greenhouse-effect in https://github.com/phetsims/chipper/issues/1211#issuecomment-1090324028 was done in (https://github.com/phetsims/greenhouse-effect/commit/ed35e9159b5d9f724a5f433a06fb156f66923690)

**Comment by zepumph** [comment]
>@chrisklus for the SubitizeObjectType

This is the same case as for Wilder, where extending an Enumeration requires redefining the enumeration. I'm going to check this off.

**Comment by chrisklus** [comment]
Thanks @zepumph!

**Comment by jbphet** [comment]
I've reviewed the changes for greenhouse-effect and `RectangularRadioButton`, and they look good.

**Comment by samreid** [comment]
Everything seems good, closing.  Also tagging for https://github.com/phetsims/tasks/issues/1111
