### ISSUE TITLE
Anti-patterns for creating types related to options

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#1217]
I'm seeing three anti-patterns related to `type` definitions for options:

(1) Duplication of field definitions, instead of picking fields from other options types.
(2) Composing a `type` using options from an ancestor class other than the superclass.
(3) Going to the trouble of creating a `type` definition, then using `merge` instead of `optionize`.

Example: CAVModel.ts. This exhibits problem (1). The definition of `tandem` is being duplicated. It should be picked from PhetioObjectOptions.

```js
// current incorrect
type SelfOptions = {
  tandem: Tandem;
  includeCards: boolean;
  instrumentMeanPredictionProperty: boolean;
};

// correct
type SelfOptions = {
  includeCards: boolean;
  instrumentMeanPredictionProperty: boolean;
} & PickRequired<PhetioObjectOptions, 'tandem'>;
```

Example: bending-light LaserNode.ts.  This exhibits problems (1) and (2). `tandem` is presumably duplicated here to make it required, but this is not the way to do that. And LaserNode extends Node, but composes PhetioObjectOptions.

```js
// current incorrect
type LaserNodeOptions = {
  tandem: Tandem;
} & PhetioObjectOptions;

// correct
type LaserNodeOptions = NodeOptions & PickRequired(< NodeOptions, 'tandem'>);
```

Example: bending-light IntroScreen.ts.  This has problem (3). It defines and specifies `IntroScreenViewOptions`, then uses `merge` which provides no type-checking.

Note that problem (1) is not exclusive to `tandem`.  But searching the PhET codebase, I see at least 24 instances of `tandem: Tandem;` and 16 instances of `tandem?: Tandem` that are likely incorrect.

**Comment by zepumph** [comment]
Noting as part of https://github.com/phetsims/chipper/issues/1128

**Comment by pixelzoom** [comment]
5/5/2022 dev meeting: I'll add this to TypeScript Conventions doc.

**Comment by pixelzoom** [comment]
Tracking this in https://github.com/phetsims/phet-info/issues/191.
