### ISSUE TITLE
Improve linting and type checking in phet-types.d.ts

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1219]
Discovered in https://github.com/phetsims/chipper/issues/1207, we could Improve linting and type checking in phet-types.d.ts

**Comment by samreid** [comment]
Fixed.  @zepumph should we factor out those lint changes to an eslint file, or isolated in the file, or is this good as it is?

**Comment by zepumph** [comment]
Is this file going to stick around long term? What is your thought about types for the phet global, assert, QSM, and some other globals?

If you think that phet-types is the way forward, then perhaps we can just exclude checking from the whole file at the top like

`/* eslint-disable no-unused-vars, no-var */`


These are not helpful lint rules for the file anyways.

**Comment by samreid** [comment]
> Is this file going to stick around long term? What is your thought about types for the phet global, assert, QSM, and some other globals?

Better long term solutions would be:

* Making assert an es5 module instead of preload
* Putting the type definitions closer to the preloads.  Like `assert-type.d.ts` and one for query string machine.

However, I don't think we should plan on these now, and phet-types.d.ts seems reasonable for now.

**Comment by samreid** [comment]
I updated the lint directives, closing.
