### ISSUE TITLE
Check the sourcemaps in compiled TS sims

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1220]
From https://github.com/phetsims/chipper/issues/1140#issuecomment-1085013488

> Today at our quarterly goals meeting, we discussed that it isn't important to get the built sourcemaps working on CT. We should see if built sourcemaps are working (from the webpack/babel phase), but no need to make changes for how they are reported on CT.

**Comment by samreid** [comment]
I checked https://phet.colorado.edu/sims/html/geometric-optics/latest/geometric-optics_en.html?debugger and saw that the source was minified and there was no sourcemap, which I believe is the intended behavior.  Closing.

**Comment by samreid** [comment]
As discovered in https://github.com/phetsims/chipper/issues/946, there are TODOs in the code referring to this issue.  Reopening.

**Comment by samreid** [comment]
I'm promoting the TODO to a comment here:

> // TODO https://github.com/phetsims/chipper/issues/1220: How does this behave for built sim stacks?  Should it be skipped for those?
        // MK: perhaps it is a moot point, but maybe the sourcemap can help us in that case too, have you looked at
        // MK: what it does when testing a built stack? Do we have a sourcemap included in the built version? Perhaps we should?

I'm wondering if our "debug" version should be fully minified, but with assertions and correct sourcemaps?  @zepumph what do you recommend and when should we work on it?

**Comment by zepumph** [comment]
I feel like we purposefully test the built version as seen in production. It wouldn't be enough of a benefit to test the debug version just to see good stack traces. I recommend closing without changes. You?
