### ISSUE TITLE
Upgrade TypeScript to fix error: "super call must be first statement"

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#1222]
From #1202, we would like to investigate if upgrading to a new typescript 

We get this error when trying to declare defaults in type declarations, and also when marking properties with # to make them private.

**Comment by samreid** [comment]
I confirmed that TypeScript 4.6.3 fixes the "super call must be first statement" in a sample occurrence I introduced in `class SoccerModel extends CAVModel`.

**Comment by zepumph** [comment]
Wow! Can we upgrade then, that would be excellent! Were there any other type errors or breaking changes we need to manage?

**Comment by samreid** [comment]
Type checker is passing with --clean and full type check.

**Comment by jessegreenberg** [comment]
Consensus: This would be nice to have! @samreid checked with eslint and there was something to investigate. But everyone agreed that we should proceed with this.

**Comment by samreid** [comment]
I found the warning was masked by the caching, I had to use `--disable-eslint-cache` to resurface the error.  Updating the eslint versions seems to correct that problem.

**Comment by samreid** [comment]
I updated TypeScript to 4.6.3 and corresponding typescript-eslint packages.  Things are testing well here.  I considered updating the babel typescript package version, but didn't see anything relevant in the change logs.  I'll notify slack.

**Comment by pixelzoom** [comment]
tsc and typescript-eslint upgrades look good to me.

Test:

```
% cd chipper
% npm update
% ./node_modules/typescript/bin/tsc -v
Version 4.6.3
% cd chippr/tsconfig/all/
tsc -b
% cd chipper
% grunt lint-everything
Running "lint-everything" task
(Forwarding task to perennial)
Running "lint-everything" task
Done.
%
```
