### ISSUE TITLE
`bad-typescript-text` custom lint rule

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#1224]
We would like `@public`, `@private`, and `@protected` to be forbidden in typescript files. I think a bad text rule just in the ts overrides section will work here.

**Comment by zepumph** [comment]
There were 1000 lint errors when I turned this rule on. Let's chip away at this!

**Comment by jessegreenberg** [comment]
What do we do for mixin/trait with this? 
```
/* eslint-disable bad-typescript-text */
```
at the top of the file?

**Comment by zepumph** [comment]
I think just a line directive at every comment where we have those texts.

**Comment by pixelzoom** [comment]
Should `@returns` be added to this rule?

**Comment by pixelzoom** [comment]
Should `@returns` be added to this rule?

EDIT: The answer is no, because we want to be able to optionally document the return type, like in CarouselButton.ts:

```js
/**
...
 * @returns the pointer area, null if no dilation is necessary, i.e. x === 0 && y === 0
 */
function computePointerArea( button: CarouselButton, arrowDirection: ArrowDirection, x: number, y: number ): Bounds2 | null {
```

EDIT: How about making `@returns` by itself (no additional doc) an error?

**Comment by zepumph** [comment]
Yes good plan. Commit coming soon.

**Comment by zepumph** [comment]
Alright. I liked this regex best to allow for extra doc:

`/(@returns \{)|(@returns$)/`

There were something like 250 lint errors. So it isn't on right now.

**Comment by zepumph** [comment]
You can now opt out of rules like `// eslint-disable-line bad-typescript-text` as needed. @pixelzoom mentioned multiple good reasons to allow checking instanceof or typeof assertions in TypeScript files, so we can disable that line accordingly.

**Comment by samreid** [comment]
> You can now opt out of rules like // eslint-disable-line bad-typescript-text as needed.

Excellent, nice work @zepumph !

**Comment by pixelzoom** [comment]
geometric-optics and vegas are passing all bad-typescript-text.  sun and scenery-phet are close, not a problem in code that I've converted.  Self unassigning.

**Comment by pixelzoom** [comment]
I've fixed most of the `@private` problems, with these exceptions:

* axon.PhetioObject.ts is a mess.  Should all of the fields prefixed with '_' be `private`? `readonly`?
* wilder.Mixable - I don't know how to address @private in mixins
* axon.createObservableArray - I don't know how to address @private in mixins

@zepumph volunteered to handle these. Then `@private` can be turned on in bad-typescript-text.js.

**Comment by pixelzoom** [comment]
`@private` has been enabled in bad-typescript-text.js, so it's no longer relevant for ts-status.  Tracking removal of `@private` from ts-status in https://github.com/phetsims/chipper/issues/1259.

**Comment by zepumph** [comment]
There are 141 usages of @returns with no extra doc afterwards, we can work on this next.

**Comment by zepumph** [comment]
I also was able to add `@param {` as bad text, since we shouldn't be providing type info via jsdoc. There are still two commented out rules:


* `options = merge`
* assert related type checking. I'm not sure if we still want this one. There are 658 errors currently. I'll ask at next dev meeting.

**Comment by zepumph** [comment]
Today we decided that we want to turn on the useless assert instanceof/typeof check for all repos but scenery. Here is the current chip-away for it. Basically 2/3rds are in scenery, and javascript files will use this code for long enough that it isn't worth removing these assertions. 


 - [ ] axon: @samreid 14 errors in 8 files.
 - [ ] bamboo: @samreid 9 errors in 3 files.
 - [ ] circuit-construction-kit-common: @samreid 16 errors in 12 files.
 - [ ] density-buoyancy-common: @jonathanolson 11 errors in 3 files.
 - [ ] dot: @jonathanolson 17 errors in 4 files.
 - [ ] joist: @zepumph 1 errors in 1 files.
 - [ ] kite: @jonathanolson 101 errors in 11 files.
 - [ ] mobius: @jonathanolson 2 errors in 1 files.
 - [ ] models-of-the-hydrogen-atom: @pixelzoom 1 errors in 1 files.
 - [ ] phet-core: @jonathanolson 3 errors in 3 files.
 - [ ] scenery-phet: @pixelzoom 1 errors in 1 files.
 - [ ] ~scenery: @jonathanolson 445 errors in 62 files.~
 - [ ] sun: @jbphet 19 errors in 9 files.
 - [ ] tambo: @jbphet 2 errors in 1 files.
 - [ ] tandem: @zepumph 22 errors in 7 files.
 - [ ] utterance-queue: @jessegreenberg 2 errors in 2 files.
 - [ ] wilder: @jonathanolson 1 errors in 1 files.

**Comment by zepumph** [comment]
I felt the same way about kite and dot as I did for scenery, I also made the regex more specific, only testing an exact, single type check. Commit coming soon.

**Comment by zepumph** [comment]
Alright, no-simple-type-checking-assertions is now on, and a separate rule in which kite, dot, and scenery opt out. I ended up putting ~10 eslint-disable-lines in place because they seemed good and important.

**Comment by zepumph** [comment]
All that is left for this issue is to get `merge` out of our options in typescript. 

We are down to less than 70 merge issues:

✖ 69 problems (69 errors, 0 warnings)

 - [ ] axon: @samreid 3 errors in 2 files.
 - [ ] bamboo: @samreid 1 errors in 1 files.
 - [ ] bending-light: @samreid 3 errors in 3 files.
 - [ ] center-and-variability: @samreid, @chrisklus 1 errors in 1 files.
 - [ ] circuit-construction-kit-common: @samreid 14 errors in 14 files.
 - [ ] counting-common: @chrisklus 1 errors in 1 files.
 - [ ] density-buoyancy-common: @jonathanolson 1 errors in 1 files.
 - [ ] gravity-and-orbits: @samreid 11 errors in 10 files.
 - [ ] greenhouse-effect: @jbphet 15 errors in 14 files.
 - [ ] joist: @zepumph 1 errors in 1 files.
 - [ ] mobius: @jonathanolson 1 errors in 1 files.
 - [ ] phet-core: @jonathanolson 1 errors in 1 files.
 - [ ] quadrilateral: @jessegreenberg 1 errors in 1 files.
 - [ ] scenery-phet: @pixelzoom 1 errors in 1 files.
 - [ ] sun: @jbphet 3 errors in 3 files.
 - [ ] tandem: @zepumph 8 errors in 5 files.
 - [ ] tappi: @jessegreenberg 2 errors in 1 files.
 - [ ] wilder: @jonathanolson 1 errors in 1 files.
Warning: 69 errors and 0 warnings Use --force to continue.

**Comment by zepumph** [comment]
I updated the comment above, just 54 conversions left.

**Comment by zepumph** [comment]
I assigned the remaining repos to responsible devs

**Comment by pixelzoom** [comment]
In the above commits, I replaced so more occurrences of `merge` in sun.  The remaining cases are more involved.

**Comment by samreid** [comment]
Here's a chip-away report of the remaining parts:

 - [ ] axon: @samreid 3 errors in 2 files.
 - [ ] bending-light: @samreid 3 errors in 3 files.
 - [ ] center-and-variability: @samreid, @chrisklus 1 errors in 1 files.
 - [ ] circuit-construction-kit-common: @samreid 14 errors in 14 files.
 - [ ] density-buoyancy-common: @jonathanolson 1 errors in 1 files.
 - [ ] gravity-and-orbits: @samreid 11 errors in 10 files.
 - [ ] greenhouse-effect: @jbphet 14 errors in 13 files.
 - [ ] sun: @jbphet 1 errors in 1 files.

**Comment by jonathanolson** [comment]
Handled all merges in density-buoyancy-common.

**Comment by samreid** [comment]
Updated chip-away result:

Results from chipAway: 
 - [ ] joist: @zepumph 1 errors in 1 files. ===> @samreid is working in this area
 - [ ] scenery: @jonathanolson 1 errors in 1 files.  Use `combineOptions`

**Comment by zepumph** [comment]
@pixelzoom or @jbphet, I went for the ButtonModel usages, can you please review my commit https://github.com/phetsims/sun/commit/0d543c76d7256e1cfc3694ff45c1be3fe9716f93

**Comment by pixelzoom** [comment]
https://github.com/phetsims/sun/commit/0d543c76d7256e1cfc3694ff45c1be3fe9716f93 looks good to me.

**Comment by zepumph** [comment]
All that is left is usages of merge in greenhouse.

**Comment by jbphet** [comment]
The greenhouse-effect usages have now all been addressed, and I've turned the rule on.  I think we can close this!
