### ISSUE TITLE
Should all methods/function have a return type, including `void`?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#1225]
From https://github.com/phetsims/scenery/issues/1406#issuecomment-1099634315:

* Is it OK to omit `void` return type, or should all methods and functions have a return type? If we omit `void`, does that complicate being able to confirm that there's a return type?

And from https://github.com/phetsims/scenery/issues/1406#issuecomment-1099642273:

Verifying that methods and functions have a return type is done by compiler option `noImplicitReturns`.  It's a boolean, so does not appear to support the option to omit `void`.   So unless there's another way, I recommend enabling `noImplicitReturns` in tsconfig-core.json, then adding `void` return types where needed.

**Comment by jessegreenberg** [comment]
This was discussed in dev meeting today and it was decided that all methods have a return type, including `void`.

We are working on this in https://github.com/phetsims/chipper/issues/1215. `noImplicitReturns` simply ensures that every code path in a function will return a value matching the specified return type. But it doesn't enforce that you declare a return type. So we are going to try an eslint solution. Closing this as a duplicate.
