### ISSUE TITLE
Keep or delete `assert` statements that are handled by type checking?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#1227]
From https://github.com/phetsims/scenery/issues/1406#issuecomment-1099634315:

* Should assertions that are now handled by the type-checker be kept or deleted? If we keep them, is there a WebStorm setting to keep them from being flagged (highlighted)?

For example in Imageable.ts:

<img width="916" alt="screenshot_1655" src="https://user-images.githubusercontent.com/3046552/163480869-2cccf53f-9b59-4c88-802e-6eb494286f3a.png">

WebStorm highlighting is a little distracting, could make it more likely to miss real problems.

**Comment by samreid** [comment]
Decision from today's dev meeting:

> They should be removed.  We added this to the typescript-conventions document.  There is an acknowledged risk here that JS code that is interacting with TS code could send bad types across the API, but feel like this is a reasonable risk to take since the JS code is currently stable and unlikely to undergo significant revisions without being converted to TS.

**Comment by samreid** [comment]
Bringing back to Dev meeting to make sure everyone is aware of the decision above, and to see what remains for this issue.  Should it be a chip-away?

**Comment by zepumph** [comment]
In https://github.com/phetsims/chipper/issues/1224 we turned on the a line rule that uses a regex to achieve this called no-simple-type-checking-assertions

The regex is: `assert && assert\((( \w+ instanceof \w+ )|( typeof \w+ === '\w+' ))\)`

This purposefully doesn't cover any assertions that might have a simple one `&&` or `||` 'ed with something else. @samreid would you like to revise anything here?

**Comment by samreid** [comment]
This seems just right for now.  If it has false positives/negatives in the future we could consider a formal lint rule that checks the parse tree.
