### ISSUE TITLE
Where to put `static` fields?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#1228]
From https://github.com/phetsims/scenery/issues/1406#issuecomment-1099634315:

* Where should static field definitions appear? Above constructor? End of class definition, after all methods? Don't care? My preference is for "above constructor", so that all fields are in one place, making it easier to see the API at a glance.

I've been putting `static` field with the non-static fields, at the top of the constructor.

@jonathanolson's style seems to be to put them at the bottom of the class definition, after all methods.

I haven't investigated what WebStorm does when it organizes fields.

**Comment by pixelzoom** [comment]
While reviewing TypeScript/dev meeting notes from 4/21 (I was out), I discovered these related notes:

> Where should static field definitions appear? Above constructor? End of class definition, after all methods? Don't care? My preference is for "above constructor", so that all fields are in one place, making it easier to see the API at a glance. (Tracking in [Where to put static fields? chipper#1228](https://github.com/phetsims/chipper/issues/1228).)
> * SR: Does this look OK? https://github.com/phetsims/center-and-variability/blob/0478e3446730bfeaec0441529a48dcae9575f614/js/common/view/MedianBarNode.ts#L31-L38
> * JB: I prefer the constructor to be the first thing in the class.
> * JO: second that
> * Several devs said they preferred to have statics, and particularly static methods, at the bottom of the class definition.
> * Consensus: Developer choice.  MK will update doc with some notes about clustering such definitions together.

I'm OK with "developer choice".  But I'm confused about @jbphet's comment "I prefer the constructor to be the first thing in the class."   We're not doing that now -- we decided (rightly) to put non-static field declarations before the constructor. Why not do the same for static fields, so it's easy to see _all_ fields?  I was not suggesting putting static methods before the constructor, they can go wherever after the constructor.

**Comment by jbphet** [comment]
> @jbphet can you please clarify?

I'm not sure I can defend that comment very well, and I think it was written down by someone else and I eventually retracted it, but it didn't get removed.  I suspect I was thinking of JavaScript classes and had momentarily forgotten about the declarations at the top of a TypeScript class.  At any rate, I retract the comment because it doesn't make sense, and am also OK with "developer choice".

**Comment by samreid** [comment]
Let's double check this at an upcoming dev meeting.  If we decide a convention or "developer preference", we can document that in the conventions guide.

**Comment by pixelzoom** [comment]
I think it's already documented in the conventions guide, https://github.com/phetsims/phet-info/blob/master/doc/typescript-conventions.md#statics:

> **Statics**
> One line static properties and fields will likely be better and clearer when grouped with the prototype fields declared at the top of a class. That said, it is developer preference whether to group them or put them at the bottom of the file:

**Comment by pixelzoom** [comment]
And since it's developer preference... What I typcially do (and have done in programming languages as far back as I can recall) is to put static constants after non-static field declarations, and static methods after non-static method definitions. 

For example:

```typescript
class MyClass {

  public readonly someField: number;
  // ... followed by all other non-static fields

  public static readonly someConstant = 5;
  // ... followed by all other static fields

  constructor( ... ) {
    ...
  }

  public someMethod(...): void {
    ...
  }
  // ... followed by all other non-static methods

  public static someStaticMethod(...): void {
   ...
  }
  // ... followed by all other static methods

}
```

**Comment by pixelzoom** [comment]
Yes, closing.
