### ISSUE TITLE
`no-inferrable-types` typescript-eslint rule

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#1229]
Related to https://github.com/phetsims/chipper/issues/1114, I temporarily enabled this rule in [chipper/eslint/.eslintrc.js](https://github.com/phetsims/chipper/blob/master/eslint/.eslintrc.js):

> '@typescript-eslint/no-inferrable-types': 'error', // 62 errors

Repos:

- [x] bending-light @samreid 
- [x] counting-common @chrisklus 
- [x] density-buoyancy-common @jonathanolson 
- [x] dot @jonathanolson 
- [x] geometric-optics @pixelzoom 
- [x] greenhouse-effect @jbphet 
- [x] joist @zepumph 
- [x] kit @jonathanolson 
- [x] mobius @jonathanolson 
- [x] number-play @chrisklus 
- [x] quadrilateral @jessegreenberg 
- [x] scenery @jonathanolson 
- [x] scenery-phet @pixelzoom 
- [x] tambo @jbphet 
- [x] utterance-queue @jessegreenberg 

Probably best to have the responsible devs chip away at these.

**Comment by pixelzoom** [comment]
I did a few of the repos that had a single error (joist, tambo, utterance-queue).

**Comment by pixelzoom** [comment]
After making a few changes like this one in VisibileColor.ts:

```diff
-  colorToWavelength: function( color: IColorSubset, reduceIntensityAtExtrema: boolean = true ): number {
+  colorToWavelength: function( color: IColorSubset, reduceIntensityAtExtrema = true ): number {
```

.... something bothered me about this change.  I don't like this inconsistency:

```js
// error
someMethod( someParam: number = 1 )

// no error
someMethod( someParam: number | boolean = 1 )
```

And having type declarations for all parameters seems more in line with requiring inferrable return types.

This rule has additonal options, see https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-inferrable-types.md.   And I think that this is a better fit for PhET:

```
'@typescript-eslint/no-inferrable-types': [ 'error', {
  ignoreParameters: true,
  ignoreProperties: true
} ],
```

So I've enabled the above, and fixed the 3 errors that were remaining. 

Ready for discussion at dev meeting.

**Comment by samreid** [comment]
@pixelzoom and @zepumph and I discussed this, and in light of:

* Vanderkam Item 19's recommendation
* The recommended default settings for the rule (which is a recommended rule), we would like to switch to:
```
'@typescript-eslint/no-inferrable-types': [ 'error' ],
```

This rule can be autofixed with `--fix`, so we can catch the 50+ cases pretty easily.

**Comment by samreid** [comment]
This issue is complete, I'm wondering if we should still leave it open as an ultra-quick public service announcement?

**Comment by pixelzoom** [comment]
If this does end up needing more discussion.... I'm OK with whatever the team decides.

**Comment by chrisklus** [comment]
From 5/9 typescript dev meeting, PSA delivered, and no further discussion happened. Closing.
