### ISSUE TITLE
Some test harnesses such as dot/playground, are not using the correct paths from chipper/dist

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1232]
From https://github.com/phetsims/chipper/issues/1140, @jonathanolson and I discovered that some test harnesses such as dot/playground, are not using the correct paths from chipper/dist.

@jonathanolson surmised that our test harness is broken, and hence that hasn't been catching that this is a problem.

This means a class of tests aren't running/completing at all, at the moment.

**Comment by jonathanolson** [comment]
These are working now.
