### ISSUE TITLE
Fatal error: ENOENT: no such file or directory, unlink `. . . /chipper/build/studio.js'

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#1234]
This happens occasionally on CT. My best guess without any research is a race condition where multiple builds are using the same spots in chipper to build things. In this case, we build studio into chipper/ and then copy it into the necessary spot in the build dir.

@jonathanolson, are builds parallel on CT for a given snapshot? If so we should talk.

**Comment by zepumph** [comment]
```
projectile-motion : build
Build failed with status code 3:
Running "report-media" task

Running "clean" task

Running "build" task
>> TypeScript compilation complete: 8252ms
Building runnable repository (projectile-motion, brands: phet, phet-io)
Building brand: phet
>> Webpack build complete: 7591ms
>> Production minification complete: 43563ms (2426663 bytes)
>> Debug minification complete: 1ms (21330495 bytes)
Building brand: phet-io
>> Webpack build complete: 6669ms
>> Production minification complete: 38709ms (2460830 bytes)
>> Debug minification complete: 38574ms (2776085 bytes)
>> No client guides found at ../phet-io-client-guides/projectile-motion/, no guides being built.
>> TypeScript compilation complete: 972ms
Fatal error: ENOENT: no such file or directory, unlink '/data/share/phet/continuous-testing/ct-snapshots/1650425801505/chipper/build/studio.js'
Snapshot from 4/19/2022, 9:36:41 PM

```

**Comment by jonathanolson** [comment]
> are builds parallel on CT for a given snapshot? If so we should talk.

Absolutely, typically 8 will run at a time.

**Comment by zepumph** [comment]
@jonathanolson and I spoke about this. We are a very strong assumption that we are only building one of a repo (per snapshot/checkout) at a time. Studio being build per phet-io build broke this assumption, but it seems to be the only place where this is happening. We can add an option for webpackBuild and buildStandalone to allow the phet-io build to pass through a custom temp dir to put the studio file, but in general we are still totally tied to a single build per repo at a time (can still concurrently build different repos at the same time).

**Comment by zepumph** [comment]
Note that we are now building phet-io-wrappers as part of the phet-io build too, so we may start to see this issue with phet-io-wrappers too.

**Comment by zepumph** [comment]
Alrighty. I finally got to this. Along with this change making studio and phet-io-wrappers more safe, I'm putting the associated built file also under a repo-specific directory. 

At this time we are leaking those empty directories. This is because we don't know when we are done with all files in that dir. I don't mind this at all, but it is a "regression" of sorts. If anything, it will make this problem less likely to occur for the next case of concurrency. Ready to close?

**Comment by jonathanolson** [comment]
Sounds reasonable. Thanks!
