### ISSUE TITLE
ESLint missing semicolon (semi)

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1235]
@marlitas and I observed this lint error in WebStorm:

<img width="912" alt="image" src="https://user-images.githubusercontent.com/679486/164271716-db7ba8a6-1c5e-467c-adcb-b12a9e202a6d.png">

However, this rule is not caught by `grunt lint-everything` or the precommit hooks.  It is different than the rule that enforces semicolons at the end of type member declarations, which is a typescript-eslint rule.

How does WebStorm have a different rule than our command line linting?

@zepumph any ideas what is happening here?

**Comment by zepumph** [comment]
With this patch I tried to reproduce the error:

```diff
Index: js/leveling-out/model/PipeModel.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/leveling-out/model/PipeModel.ts b/js/leveling-out/model/PipeModel.ts
--- a/js/leveling-out/model/PipeModel.ts	(revision 869ec2245fcb39d223d98f8c8491c7f44a141d13)
+++ b/js/leveling-out/model/PipeModel.ts	(date 1650488232232)
@@ -12,7 +12,7 @@
 class PipeModel {
 
   readonly isOpenProperty: BooleanProperty;
-  readonly xProperty: NumberProperty;
+  readonly xProperty: NumberProperty
   readonly y: number;
 
   constructor( xProperty: NumberProperty, y: number ) {

```

I found no error in Webstorm and also from the command line. Can you recommend next steps? It seems buggy. Does this have to do with our recent upgrade to Webstorm 2022.1? Or is it some sort of typescript estlint plugin problem? I don' see the semi rule in the https://github.com/phetsims/chipper/blob/79ed381e0cb7cbb498c30c2c32acedabe4597f28/eslint/.eslintrc.js#L70-L77

**Comment by samreid** [comment]
I tried the same patch and saw WebStorm report an error, and lint reported this error:

```
mean-share-and-balance: 
/Users/samreid/apache-document-root/main/mean-share-and-balance/js/intro/model/Pipe.ts
  47:36  error  Missing semicolon  @typescript-eslint/semi

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.
```

So I think this issue can be closed, please reopen if there is more to do.
