### ISSUE TITLE
@protected is bad typescript text

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#1237]
https://github.com/phetsims/chipper/issues/1224, but a place to put my commits.

**Comment by zepumph** [comment]
For mixins it looks like I can't do:

      // @protected eslint-disable-line bad-typescript-text


Because of how getBadTextTester works. I'll make a new rule just for protected so I can disable it in the whole file.

**Comment by zepumph** [comment]
Actually there were two cases that were a bit hard, @samreid can you search for this issue, `https://github.com/phetsims/chipper/issues/1237` in the project to find these in Bending Light and Gravity and Orbits?

**Comment by samreid** [comment]
Thanks, I fixed those cases.  Want to move `@protected` back to bad-text?

**Comment by zepumph** [comment]
>Want to move @protected back to bad-typescript-text?

It will need to stay as its own file to more easily support our mixin files, which we want to disable this rule for. It is the only visibility annotation like that since `@private` will be noted with prefixes in the var name. I updated doc.

**Comment by samreid** [comment]
Sounds good and I added a 👍 .  The other alternative I considered is whether we should manually add `// eslint-disable-line` support for our home-grown bad-text rules.  But maybe it would be too much work.

**Comment by zepumph** [comment]
That is where I started, but The rule is set up to be per file (not ideal, but how it was implemented), so you can only turn it off on the first line of the file, anyways, and I didn't want to turn off all bad text rules for the whole file.
