### ISSUE TITLE
Make git hooks run faster on windows

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/chipper#1239]
For some Windows users git hooks can take from 1-10 minutes to run. We think that tsc is probably causing this. Some have git hooks disabled because it is causing too much of a slowdown. Is there a way we can get this to run faster on Windows?

**Comment by samreid** [comment]
Some performance improvements for `tsconfig/all tsc -b` noted in https://github.com/phetsims/chipper/issues/1241

**Comment by samreid** [comment]
We are now using the monolithic approach, with some windows timing noted in https://github.com/phetsims/chipper/issues/1241#issuecomment-1109945148.  @jessegreenberg can you please comment if the precommit hook times have gotten faster for you after pulling the monolithic tsconfig in https://github.com/phetsims/chipper/issues/1245 ?

**Comment by jessegreenberg** [comment]
I pulled all and tried running `tsconfig/all tsc -b`, here are some timing results:

- First run after pull-all: 24 seconds
- Five more runs with no changes: ~7.5 seconds each
- Add a misc change to ScreenView.ts: 36 seconds
- 2 more runs with no changes: ~12 seconds each
- Add a function to ScreenView.ts and use in a sim: 15 seconds
- After `git stash apply` for a large change set in a sim: 15 seconds.

Overall it is seeming quite a bit faster! I have not seen it run for more longer than 36 seconds, while previously it was common to take more than 2 minutes.

**Comment by samreid** [comment]
Based on the comment above, it seems this issue is at a good point to close.  Anyone feel free to reopen, or create a side issue as appropriate. Closing.
