### ISSUE TITLE
List all transitive dependencies for each tsconfig

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1245]
As described in https://github.com/microsoft/TypeScript/issues/46153, project references are designed so that if a project imports from another project, it should be listed in the direct references (not transitively).  According to the issue, that could address the false positives and false negatives we have been seeing.

This would be an alternative to the monolithic (one file/no project references) strategy or having to clean each time as described in https://github.com/phetsims/chipper/issues/1243#issuecomment-1116475546.

**Comment by samreid** [comment]
I did not see an existing lint rule that could help enforce this new requirement.  I checked the rules at https://www.npmjs.com/package/eslint-plugin-import.  I don't see an easy way to automatically update the tsconfig files from existing imports.  Maybe we would write our own lint rule that checks that any import has a direct listing in `references`?  But we would want to make sure that works for tsconfig.json and tsconfig-module.json.  If we write our own lint rule, it would flag as an error at the import site, but really it would probably indicate that a project reference needs to be added to `references`.  

It seems it would be much simpler to adopt the monolithic tsconfigs as described in https://github.com/phetsims/chipper/issues/1243#issuecomment-1116475546.  As far as I understand, those have the following disadvanatges:

* Up front cost to specify the monolithic tsconfig files
* Monolithic seems slower at detecting "there are no changes", taking 5 sec instead of 1 sec, see https://github.com/phetsims/chipper/issues/1241
* The proposed monolithic scheme specifies sim mains as entry points and would skip files that are never imported. (workaround is to import those files or add them as entry points).

Project references are indicated for modularity and speed, but are causing more complications.

Maybe it would be good to touch base at dev meeting before spending more time on this.

**Comment by samreid** [comment]
In today's discussion, we agreed we would like to explore the monolithic tsconfig approach, but having `**/*` to capture every entry point.  These will replace the project-references versions.  Not sure if we should keep those around in case we go back to them in the future.

@zepumph wants to time `**/*` and see how it goes before changing everything.

**Comment by samreid** [comment]
On my macbook air, the timing is like:

| Case | Initial (sec) | Incremental/no changes (sec) |
| ------------- | ------------- | ------------- |
| Geometric Optics  | 4.987  | 1.570  |
| tsconfig/all  | 13.983  | 5.403  |
| tsconfig/all (no images/mipmaps/sounds) | 11.106  | 3.100  |

**Comment by samreid** [comment]
From review with @zepumph:

* Seems promising and much simpler, easier to maintain.  Will likely solve the "false positives and false negatives" issues.
* Add a comment to the sim/common repo tsconfigs that say "this was autogenerated", and autogenerate with `grunt update`.  Maybe even other repos without `grunt update`, like aqua.
* Use "excludes node_modules" and build/ instead of "includes js, images, mipmaps, etc."
* Maybe add all repos, but use "include" pattern "*.ts"?

**Comment by samreid** [comment]
I updated a few things in https://github.com/phetsims/chipper/issues/1245#issuecomment-1126547026 and asked some questions.  @zepumph can you please review?  I didn't feel strongly about the uncompleted parts--happy to work on them more if recommended.  This issue is getting long--for anything nontrivial can you please promote it to a new issue?

**Comment by zepumph** [comment]
Please let me know if it wasn't ok to remove the commented out directories. I think it is more than acceptable to just type check imported images/sounds/etc, since they are generated js files anyways. 

tsconfig/all does not seem to have a good coverage across non sim-related repos. For example `aqua` not has ts code. How do you want to manage these sorts of side-repos as they gain coverage. Also what about PhET-iO repos?

**Comment by samreid** [comment]
I added more repos to the tsconfig.json, and I added `@ts-nocheck` in the files that seem they are not yet ready for type checking.

**Comment by zepumph** [comment]
Looks great. Do you think there is anything else here?

**Comment by samreid** [comment]
That seems good for now, closing.

**Comment by zepumph** [comment]
I see comments pointing to this issue that say `// This file was automatically generated by grunt update`. I don't see that occurring  though. @samreid can you help me understand this? Should we remove these comments?

**Comment by samreid** [comment]
I removed the stale code comment, closing.
