### ISSUE TITLE
Upgrade grunt

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#1246]
We are getting an error from dependabot

>Grunt prior to version 1.5.2 is vulnerable to path traversal.

- [x] Sims (chipper)
- [x] Quake
- [x] Weddell

Most package.json files are showing `~1.4`. After some regression testing I can just upgrade everything.

**Comment by zepumph** [comment]
I will try to get to this today.

**Comment by zepumph** [comment]
looks like 1.5.3 just came out. I tested it by running grunt in a sim, doing a dev version, and running grunt lint-everything in perennial


I used this regex to make sure all usages are on 1.5.3: `"grunt": "(?!~1.5.3)`

**Comment by zepumph** [comment]
Updates are above. @jbphet would you mind spot checking this, since I couldn't test weddell or quake because I didn't have all the setup needed (config files, dependencies, etc). I failed a grunt task quickly from a lack of setup and decided that it would just be easiest for you to do a quick command or two to spot check.

**Comment by jbphet** [comment]
I tested for quake, and it's fine.

@liam-mulhall - Can you please run a build (with no deploy) and verify that it works with this update to grunt?  If so, this issue can be closed.

**Comment by liam-mulhall** [comment]
I've successfully built the desktop app since Grunt was updated, so I'm going to close.
