### ISSUE TITLE
Chipper 1.0 tools still deploy to spot

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/chipper#1248]
Discovered during https://github.com/phetsims/forces-and-motion-basics/issues/291.

forces-and-motion-basics 2.3 uses a very old chipper SHA. I tried to deploy the phet and phet-io brands of forces-and-motion-basics with the following command
```
grunt production --brands=phet,phet-io
```

But got the following error:
```
info: npm update on perennial-alias
Fatal error: Perennial task failed:
AssertionError [ERR_ASSERTION]: chipper 0.0.0 cannot build multiple brands at a time
    at module.exports (C:\Users\Jesse\Documents\Development\phetsims\perennial\js\common\build.js:44:5)
```

So I went to deploy with chipper 1.0 since I thought that chipper 2.0 tools were unavailable. I went through the steps then ran 
```grunt deploy-production``` in the sim repo. But it produced 
```
Fatal error: Directory [spot.colorado.edu](http://spot.colorado.edu/):/htdocs/physics/phet/dev/html/forces-and-motion-basics/2.3.19 already exists.  If you intend to replace the content then remove the directory manually from [spot.colorado.edu](http://spot.colorado.edu/).
```
The directory 2.3.19 does not exist. I tried to deploy a dev version and got the same error.

We think that the issue is that the chipper 1.0 tools are still pointing to spot which has been decommissioned. I was able to proceed with my maintenance release by using the chipper 2.0 tools but deploying the brands separately. I will add documentation in both the chipper 1.0 and 2.0 documents to try this instead of using chipper 1.0.

**Comment by jessegreenberg** [comment]
I added notes about this in the chipper-1.0.md and chipper-2.0.md documentation. But wanted to see if @jonathanolson thought anything else should be done here. Sims with very old chipper SHAs might not be deployable with chipper 1.0 steps, but I don't know if that is very important. If not, feel free to close if the documentation changes are sufficient.

**Comment by jonathanolson** [comment]
The documentation looks good, it sounds good to avoid trying the chipper 1.0 tools.
