### ISSUE TITLE
use one approach for logging in grunt tasks

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#125]
Some of the grunt tasks use `grunt.log.writeln`, some use `console.log`, and some use both (!).  We should probably standardize on `grunt.log.writeln`.

**Comment by jonathanolson** [comment]
So presumably if code can also run in the browser, it shouldn't have console.log. I'm fine with the ```grunt.log.writeln```.

**Comment by pixelzoom** [comment]
`grunt.log.writeln` is now used for all logging in grunt tasks.  Closing.
