### ISSUE TITLE
`adjacent-overload-signatures` typescript-eslint rule

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/chipper#1250]
From to https://github.com/phetsims/chipper/issues/1114, see https://typescript-eslint.io/rules/adjacent-overload-signatures/.
 Currently 258 errors in the project. Should we chip-away and enable or ignore this rule? To be discussed during dev meeting.

**Comment by jessegreenberg** [comment]
It requires getters and setters to be next to each other. Like this
```js
  getHintResponse(): ResolvedResponse {
    return ResponsePacket.getResponseText( this._hintResponse );
  }

  get hintResponse(): ResolvedResponse { return this.getHintResponse(); }

  setHintResponse( hintResponse: VoicingResponse ): void {
    this._hintResponse = hintResponse;
  }

  set hintResponse( hintResponse: VoicingResponse ) { this.setHintResponse( hintResponse ); }
```

The `get hintResponse` and `set hintResponse` must be together.

The reason this may be useful is because it could prevent accidental overloading since overloaded functions must be grouped.

SR volunteered to to give it a try, if it doesn't take too long to fix existing errors it is worth having this rule enabled.

**Comment by samreid** [comment]
We reviewed the cases and decided to divide and conquer.  I'll do cases in scenery.  @marlitas will do the other cases.

**Comment by samreid** [comment]
OK I finished in scenery.  When the rest of the cases are complete, @marlitas can you please enable the rule in chipper/eslint/.eslintrc.js and commit/push?  Self-unassigning.

**Comment by marlitas** [comment]
lint rule enabled runs clean. Closing.
