### ISSUE TITLE
`ban-types` typescript-eslint rule

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/chipper#1252]
From https://github.com/phetsims/chipper/issues/1114, see https://typescript-eslint.io/rules/ban-types/.
Currently 251 errors in the project. Should we chip-away and enable or ignore this rule? To be discussed during dev meeting.

**Comment by pixelzoom** [comment]
Over in https://github.com/phetsims/geometric-optics/issues/437#issuecomment-1132161965, I noted why I did not enable `ban-types` for geometric-optics:

* `ban-types`:  This flags all occurrences of `{}` with:
> Don't use `{}` as a type. `{}` actually means "any non-nullish value".

... and `{}` is ubiquitous with `type SelfOptions = {}`.

**Comment by pixelzoom** [comment]
The `ban-type` documentation refers to this issue comment for workarounds to `{}`:  https://github.com/typescript-eslint/typescript-eslint/issues/2063#issuecomment-675156492

**Comment by jessegreenberg** [comment]
5/26/22 - 

We want this rule, and we think it could be used to automatically ban `Omit` in https://github.com/phetsims/phet-core/issues/119 with a custom message.

There was an example of allowing `{}` in the documentation in https://typescript-eslint.io/rules/ban-types/.

@zepumph and @AgustinVallejo will work on this one, thanks!

**Comment by pixelzoom** [comment]
As I mentioned above... There are also examples (and explanation) of how to deal with `{}` in https://github.com/typescript-eslint/typescript-eslint/issues/2063#issuecomment-675156492.

**Comment by zepumph** [comment]
@AgustinVallejo and I got to a commit point excluding `{}` as part of the rule, but we had to leave before we could commit on AV's side. Either tonight or tomorrow morning we will push commits to 18 files, turning on the rule.

**Comment by pixelzoom** [comment]
https://github.com/typescript-eslint/typescript-eslint/issues/2063#issuecomment-675156492 suggests that excluding `{}` from the rule is a bad idea.   It suggests defining an `EmptyObject` type.  Have you investigated that approach?

**Comment by zepumph** [comment]
That makes a lot of sense! With that part disabled, there were just 27 lint errors. This was a nice and bite sized portion to handle first, and @AgustinVallejo and I were quite happy with the fix from each (all problems were obvious improvements). 

I will note that we needed to do a bit of hackary in NumberPlay, and created a type called `TODO_Function` with a todo next to it to make sure that it was handled upon next typescript update.

From here we should investigate converting usages of the empty object to other types.

**Comment by zepumph** [comment]
Omit was added as a banned type in https://github.com/phetsims/phet-core/issues/119

**Comment by zepumph** [comment]
With this patch. . . 

```diff
Index: eslint/.eslintrc.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/eslint/.eslintrc.js b/eslint/.eslintrc.js
--- a/eslint/.eslintrc.js	(revision 40555e0ab59e66ff83793caf67b64ce500269716)
+++ b/eslint/.eslintrc.js	(date 1654096478849)
@@ -58,10 +58,7 @@
               Omit: {
                 message: 'Prefer StrictOmit for type safety',
                 fixWith: 'StrictOmit'
-              },
-
-              // un-ban a type that's banned by default
-              '{}': false
+              }
             },
             extendDefaults: true
           }

```

. . . there are 232 lint failures. Marking for dev meeting to discuss how/if/when we make this conversion to forbidding the type: `{}` from our project.

**Comment by zepumph** [comment]
Discussed at dev meeting today. We asked and everyone is using `{}` as an "Empty Object" and not as a structural type that is a superset of object with any keys allowed. We tried `Record<string, never>` but it didn't work as SelfOptions when passed to optionize. @AgustinVallejo and I will investigate.

**Comment by zepumph** [comment]
All usages updated and `{}` is now banned. We did find that all usages actually didn't want an empty object, but instead an object that accepted any keys. I wonder if we should rename EmptyObjectType to "FlexibleRecord" or something and have it be `Record<string,any>`. I think we should investigate this a bit more.

**Comment by zepumph** [comment]
But if we changed all usages, then I think that options would lose type safety because intersection with an object that can have any value is useless. I am also looking at the end of https://github.com/typescript-eslint/typescript-eslint/issues/2063#issuecomment-675156492:

>As an aside - it's worth noting that `{}` is a very weird anomaly in TypeScript, because there is just one case where it actually does mean something akin to "empty object"; in an intersection type.

This is just how we use `SelfOptions = {}` as a placeholder. I recommend that we close this issue, and note that in the future, EmptyObjectType only be used when actually needed. Most of the time `Record` will be the right type. I'll add to dev meeting for PSA next week (I'm out of town tomorrow).

**Comment by chrisklus** [comment]
From 6/16/22 dev meeting:

@AgustinVallejo delivered a PSA for devs to use EmptyObjectType for now, and then we will discuss further next week when @zepumph is back for additional possibilities.

**Comment by zepumph** [comment]
I'm back this week, but @samreid and @pixelzoom are out, let's hold off on discussing this.

**Comment by jessegreenberg** [comment]
Visited 6/30/22, but we need more devs here for the PSA. We will return in a future meeting.

**Comment by zepumph** [comment]
@pixelzoom, @samreid, @AgustinVallejo, @jonathanolson, and I met today and decided to get rid of as many usages `{}` as possible. We were able to convert many of them to `object`, which seemed to mean the same thing (like in phet-core/types/). And we made a new and special `EmptySelfOptions` to be used specifically for `type SelfOptions = EmptySelfOptions` (or in the optionize call directly). 

@AgustinVallejo would you mind spot checking these commits, mostly in optionize. Anything else here?

**Comment by zepumph** [comment]
Also, a PSA at dev meeting to explain the changes seems nice.

**Comment by AgustinVallejo** [comment]
Changed the last `EmptyObjectTypes` in optionize.ts for just `object`
