### ISSUE TITLE
`no-explicit-any` typescript-eslint rule

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/chipper#1253]
From to https://github.com/phetsims/chipper/issues/1114, see https://typescript-eslint.io/rules/no-explicit-any/.
Currently 515 errors in the project. Should we chip-away and enable or ignore this rule? To be discussed during dev meeting.

**Comment by jessegreenberg** [comment]
5/26/22 developer meeting: This is the last eslint rule to discuss from #1114, and will start on this topic next week (hence the high priority).

**Comment by samreid** [comment]
At today's meeting, we agreed we want to enable this rule.  To get there, we should chip away at it.  Developers can enable it on a repo-by-repo basis

@samreid will make a list of repos that have problems for this.

**Comment by marlitas** [comment]
Assignments for `no-explicit-any` chip away. 

 - [ ] axon: @samreid - 118 errors in 11 files.
 - [ ] bamboo: @samreid - 31 errors in 24 files.
 - [ ] bending-light: @samreid - 2 errors in 2 files.
 - [ ] center-and-variability: @samreid, @chrisklus - 5 errors in 4 files.
 - [ ] chipper: @jonathanolson - 10 errors in 2 files.
 - [ ] circuit-construction-kit-common: @samreid - 78 errors in 43 files.
 - [ ] counting-common: @chrisklus - 10 errors in 4 files.
 - [ ] density-buoyancy-common: @jonathanolson - 11 errors in 7 files.
 - [ ] dot: @jonathanolson - 2 errors in 1 files.
 - [ ] gravity-and-orbits: @samreid - 17 errors in 7 files.
 - [ ] greenhouse-effect: @jbphet - 26 errors in 7 files.
 - [ ] joist: @zepumph - 26 errors in 7 files.
 - [ ] kite: @jonathanolson - 1 errors in 1 files.
 - [ ] mean-share-and-balance: @marlitas, @samreid - 2 errors in 2 files.
 - [ ] mobius: @jonathanolson - 3 errors in 2 files.
 - [ ] my-solar-system: @jonathanolson - 1 errors in 1 files.
 - [ ] number-play: @chrisklus - 1 errors in 1 files.
 - [ ] perennial: @mattpen, @jonathanolson - 1 errors in 1 files.
 - [ ] phet-core: @jonathanolson - 22 errors in 9 files.
 - [ ] phet-io-sim-specific: @samreid - 12 errors in 2 files.
 - [ ] quadrilateral: @jessegreenberg - 5 errors in 3 files.
 - [ ] ratio-and-proportion: @zepumph - 2 errors in 1 files.
 - [ ] scenery-phet: @pixelzoom - 3 errors in 1 files.
 - [ ] scenery: @jonathanolson - 65 errors in 24 files.
 - [ ] sun: @jbphet - 13 errors in 9 files.
 - [ ] tandem: @zepumph - 48 errors in 8 files.
 - [ ] tangible: @zepumph - 2 errors in 2 files.
 - [ ] vegas: @jbphet - 9 errors in 6 files.
 - [ ] wilder: @jonathanolson - 10 errors in 2 files.

**Comment by pixelzoom** [comment]
The only problems in scenery-phet are in NumberControl, converted by @jonathanolson, and tracked in https://github.com/phetsims/scenery-phet/issues/742.  So I'm going to reassign scenery-phet to him in the above checklist.

**Comment by zepumph** [comment]
I think it is a false positive. I don't see any typescript files in perennial.

**Comment by jessegreenberg** [comment]
I gave this a try in https://github.com/phetsims/chipper/issues/1258#issuecomment-116469868. In that issue I added on override to 28 repos that we will still have to remove later. The result seems largely the same because new code in those repos won't be able to leverage the rule either. I don't think the gain is large enough to do it again here.

**Comment by jessegreenberg** [comment]
wilder done in the above commit, a couple of `IntentionalAny`s were required for Mixable.ts that I wasn't sure about but I checked them with @jonathanolson.

**Comment by zepumph** [comment]
I'm down to 8 hard ones in tandem. I'll keep cranking.

**Comment by samreid** [comment]
Updated chip-away:

 - [ ] chipper: @jonathanolson 14 errors in 1 files.
 - [ ] density-buoyancy-common: @jonathanolson 8 errors in 4 files.
 - [ ] dot: @jonathanolson 2 errors in 1 files.
 - [ ] greenhouse-effect: @jbphet 26 errors in 7 files.
 - [ ] joist: @zepumph 1 errors in 1 files.
 - [ ] kite: @jonathanolson 1 errors in 1 files.
 - [ ] mobius: @jonathanolson 3 errors in 2 files.
 - [ ] my-solar-system: @jonathanolson 1 errors in 1 files.
 - [ ] phet-core: @jonathanolson 23 errors in 9 files.
 - [ ] phet-io-wrappers: @zepumph 37 errors in 7 files.
 - [ ] ratio-and-proportion: @zepumph 3 errors in 1 files.
 - [ ] scenery: @jonathanolson 61 errors in 20 files.
 - [ ] sun: @jbphet 15 errors in 10 files.
 - [ ] tandem: @zepumph 6 errors in 2 files.
 - [ ] tappi: @jessegreenberg 1 errors in 1 files.

**Comment by samreid** [comment]
Updated chip away report:

 - [ ] chipper: @jonathanolson 14 errors in 1 files.
 - [ ] greenhouse-effect: @jbphet 26 errors in 7 files.
 - [ ] mobius: @jonathanolson 3 errors in 2 files.
 - [ ] my-solar-system: @jonathanolson 1 errors in 1 files.
 - [ ] phet-core: @jonathanolson 23 errors in 9 files.
 - [ ] phet-io-wrappers: @zepumph 37 errors in 7 files.
 - [ ] ratio-and-proportion: @zepumph 3 errors in 1 files.
 - [ ] sun: @jbphet 15 errors in 10 files.
 - [ ] tandem: @zepumph 6 errors in 2 files.
 - [ ] tappi: @jessegreenberg 1 errors in 1 files.

**Comment by zepumph** [comment]
I also don't see it in my local copy!

**Comment by samreid** [comment]
Updated chip-away results:

- [ ] greenhouse-effect: @jbphet 26 errors in 7 files.
- [ ] phet-io: @zepumph 2 errors in 2 files.
- [ ] sun: @jbphet 5 errors in 4 files.
- [ ] tandem: @zepumph 7 errors in 3 files.

**Comment by jbphet** [comment]
I've addressed all the `any` usages in greenhouse-effect and sun.

**Comment by pixelzoom** [comment]
FYI... There were some new `any` usages added to scenery-phet `KeyboadHelpSection` for https://github.com/phetsims/scenery-phet/issues/762, to be addressed by @jessegreenberg.

**Comment by zepumph** [comment]
Results from chipAway: 
 - [ ] phet-io: @zepumph 2 errors in 2 files.
 - [ ] scenery-phet: @pixelzoom 11 errors in 2 files.
 - [ ] tandem: @zepumph 5 errors in 2 files.

**Comment by zepumph** [comment]
All that is left is KeyboardHelpSection classes, see https://github.com/phetsims/scenery-phet/issues/762. These have been individually disabled and marked with TODOs in that issue. To be handled soon. I turned the rule on and all are passing. Closing.

**Comment by samreid** [comment]
Fixed a lint error in preceding commits, @jonathanolson FYI

**Comment by zepumph** [comment]
Today we found a couple more redundant usages of the error rule for `no-explicit-any`

**Comment by zepumph** [comment]
Alright fixed, and I updated the CRC from today's dev meeting to check in on package.json to make sure that we haven't turned off anything important during development.
