### ISSUE TITLE
`explicit-member-accessibility` typescript-eslint rule

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#1258]
Here's an example of why I'd like to revisit the decision to make `public` optional (at developer discretion). 

In bending-light GridCanvasNode.ts:

```typescript
class GridCanvasNode extends CanvasNode {
  modelViewTransformProperty: Property<ModelViewTransform2>;
  strokeDash: number[];
  gridLines: ObservableArray<{ x1: number; y1: number; x2: number; y2: number; lineDashOffset: number }>;
...
  constructor( gridLines: ObservableArray<{ x1: number; y1: number; x2: number; y2: number; lineDashOffset: number }>,
               modelViewTransformProperty: Property<ModelViewTransform2>, strokeDash: number[], providedOptions?: NodeOptions ) {

    super( providedOptions );
    this.gridLines = gridLines; // @private
    this.modelViewTransformProperty = modelViewTransformProperty; // @private
    this.strokeDash = strokeDash; // @private
  }
```

The fields here were probably auto-created using WebStorm, with default public visibility.  And then they were never given the proper visibility, which should be `private` (as noted in the comments).

And this is not an isolated case. While working on https://github.com/phetsims/chipper/issues/1224 to remove redundant `@private` annotations, I'm finding this problem throughout the fields and methods of bending-light.  And I've seen it elsewhere.

My feeling is that requiring developers to explicilty add an annotation is more likely to result in a correct annotation.  And (so far) some developers have abused default visibility.

**Comment by pixelzoom** [comment]
And again in SeriesCanvasNode.ts:

```typescript
class SeriesCanvasNode extends CanvasNode {
  seriesProperty: Property<DataPoint[]>;
  modelViewTransformProperty: Property<ModelViewTransform2>;
  color: string;
...
  constructor( seriesProperty: Property<DataPoint[]>, modelViewTransformProperty: Property<ModelViewTransform2>,
               color: string, providedOptions?: NodeOptions ) {

    super( providedOptions );
    this.seriesProperty = seriesProperty; // @private
    this.modelViewTransformProperty = modelViewTransformProperty; // @private
    this.color = color; // @private
  }
```

**Comment by samreid** [comment]
We discussed this at today's dev meeting.  @zepumph recommend we separate this into 3 problems:

* public modifier
* readonly modifier
* Lint rule that requires readonly for private members where possible: https://typescript-eslint.io/rules/prefer-readonly/

**Comment by samreid** [comment]
Have you been mindful of public/private?
AV - Forgot it existed, using the default
CM
CK - yes, and i opted to use public explicitly in NP
JB - I generally try to specify public explicitly
JG - 
JO - Don’t mind either way, yes mindful of that
KP
LM
LV - yes, I try to use public explicitly
MK- I’m sorry I haven’t been a good participant.
MP
MS: I’m being mindful.
SR: I’m being mindful of public vs private during new code development.  Making things private where possible

Recommendation for going forward, for voting for requiring public annotation: https://github.com/phetsims/chipper/issues/1258
AV - Sounds like explicit is better
CM - explicit, enforced in package.json 
CK - prefer explicit
JB - yes for explicit use of the “public” specifier
JG - Prefer explicit (especially for methods).
JO
KP - Yes, explicit
LM
LV
MK - Require some sort of this rule, turning it on for properties (public too) sounds really great.
MP
MS: Generally leaning towards dev choice, but am open either way.
SR: Can we try turning on this rule for a week and see how annoying it is?
Vote tally:
Explicit: 7
Dev Choice or Don’t feel strongly: 2

**Comment by samreid** [comment]
Several team members recommended that we should be consistent, even requiring `public|private|protected` on constructors, methods, getters, etc.

**Comment by samreid** [comment]
I added a (horribly inefficient) script that adds accessibility modifiers.

**Comment by samreid** [comment]
I used the script in axon to make all missing modifiers private, then I used the type checker to visit each site and make them public where appropriate.

**Comment by pixelzoom** [comment]
I'd be interested in a script like this for general use.  For some collection of .ts files, the script would change all fields to `private readonly` and methods to `private` (which should be the default, if a language is really serious about creating a good API) regardless of how you had set them.  Then let `tsc` tell you where it needs to be changed.   Not sure how much effort this would be, but it would certainly catch incorrect accessibility modifiers.

**Comment by samreid** [comment]
Here is the result of `grunt lint-everything --chip-away` for this rule:

 - [ ] bamboo: @samreid 113 errors in 25 files.
 - [ ] bending-light: @samreid 374 errors in 62 files.
 - [ ] build-a-nucleus: @Luisav1, @chrisklus 37 errors in 15 files.
 - [ ] buoyancy: @jonathanolson 4 errors in 4 files.
 - [ ] center-and-variability: @samreid, @chrisklus 155 errors in 42 files.
 - [ ] circuit-construction-kit-common: @samreid 612 errors in 111 files.
 - [ ] counting-common: @chrisklus 14 errors in 8 files.
 - [ ] density-buoyancy-common: @jonathanolson 662 errors in 70 files.
 - [ ] density: @jonathanolson 3 errors in 3 files.
 - [ ] dot: @jonathanolson 517 errors in 13 files.
 - [ ] gravity-and-orbits: @samreid 240 errors in 39 files.
 - [ ] greenhouse-effect: @jbphet 94 errors in 19 files.
 - [ ] joist: @zepumph 163 errors in 28 files.
 - [ ] kite: @jonathanolson 438 errors in 14 files.
 - [ ] mobius: @jonathanolson 65 errors in 10 files.
 - [ ] my-solar-system: @jonathanolson 101 errors in 34 files.
 - [ ] number-play: @chrisklus 59 errors in 42 files.
 - [ ] phet-core: @jonathanolson 78 errors in 10 files.
 - [ ] phet-io-wrappers: @zepumph 20 errors in 5 files.
 - [ ] quadrilateral: @jessegreenberg 93 errors in 33 files.
 - [ ] ratio-and-proportion: @zepumph 240 errors in 48 files.
 - [ ] scenery-phet: @pixelzoom 164 errors in 103 files.
 - [ ] scenery: @jonathanolson 2596 errors in 110 files.
 - [ ] shred: @jbphet 1 errors in 1 files.
 - [ ] simula-rasa: @pixelzoom 3 errors in 3 files.
 - [ ] sun: @jbphet 194 errors in 76 files.
 - [ ] tambo: @jbphet 64 errors in 39 files.
 - [ ] tandem: @zepumph 109 errors in 7 files.
 - [ ] tangible: @zepumph 3 errors in 1 files.
 - [ ] tappi: @jessegreenberg 1 errors in 1 files.
 - [ ] utterance-queue: @jessegreenberg 165 errors in 11 files.
 - [ ] vegas: @jbphet 18 errors in 18 files.
 - [ ] wilder: @jonathanolson 69 errors in 7 files.

**Comment by pixelzoom** [comment]
vegas, sun, and scenery-phet are all checking `explicit-member-accessibility` via their package.json.

**Comment by pixelzoom** [comment]
Title of this issue changed to reflect that we decided to require accessibility modifiers, and enforce that via the `explicit-member-accessibility` typescript-eslint rule

**Comment by pixelzoom** [comment]
In Slack#typescript on 6/10/2022, @zepumph said:
> I'm 24 hours into seeing public next to every member in Ratio and Proportion, and so far I'm completely sold. It has forced me to ask each time I make a new method, and I'm finding my default to be private much more often! Thanks team for a good rule.

... and this comment received 5 positive reactions.

**Comment by chrisklus** [comment]
From 6/16/22 dev meeting:

We checked in on this and @pixelzoom noted that this has been turned on in some common repos, as described in https://github.com/phetsims/chipper/issues/1258#issuecomment-1151600091

**Comment by zepumph** [comment]
This seems like a great candidate for turning it on for the project, and having individual repos opt out until they are passing. @jessegreenberg will make it happen!

**Comment by jessegreenberg** [comment]
I got a few more of the repos that only had a few more left. Commits following this comment will be to turn the rule on by default, remove the opt-in overrides in package.json's, and add opt-out overrides in repos where it is still failing.

**Comment by pixelzoom** [comment]
I took care of bamboo in the above commits. 

It was confusing to me that there are 13 occurrences of `"@typescript-eslint/explicit-member-accessibility": "off"` in package.json files.   I realize that this may have been an experiment in turning the rule on globally, then disabling it locally.  But I'd like to see that reverted.

**Comment by samreid** [comment]
I ran an updated chip-away report for this rule:

 - [ ] build-a-nucleus: @Luisav1, @chrisklus 37 errors in 15 files.
 - [ ] center-and-variability: @samreid, @chrisklus 153 errors in 42 files.
 - [ ] circuit-construction-kit-common: @samreid 612 errors in 111 files.
 - [ ] density-buoyancy-common: @jonathanolson 665 errors in 70 files.
 - [ ] density: @jonathanolson 3 errors in 3 files.
 - [ ] dot: @jonathanolson 517 errors in 13 files.
 - [ ] gravity-and-orbits: @samreid 239 errors in 39 files.
 - [ ] kite: @jonathanolson 438 errors in 14 files.
 - [ ] mobius: @jonathanolson 65 errors in 10 files.
 - [ ] my-solar-system: @jonathanolson 80 errors in 32 files.
 - [ ] number-play: @chrisklus 65 errors in 48 files.
 - [ ] phet-core: @jonathanolson 79 errors in 10 files.
 - [ ] scenery: @jonathanolson 2097 errors in 95 files.

**Comment by pixelzoom** [comment]
> However, I could not think of a straightforward way to re-enable the rule in all the repos that are respecting it. Is that important? Or should I just commit the patch?

Yes, that's important. Commits above by @jessegreenberg (like https://github.com/phetsims/geometric-optics/commit/c56f9c8d) removed the opt-in. Those should be resorted.

**Comment by zepumph** [comment]
>It was confusing to me that there are 13 occurrences of "@typescript-eslint/explicit-member-accessibility": "off" in package.json files. I realize that this may have been an experiment in turning the rule on globally, then disabling it locally. But I'd like to see that reverted.

I thought we decided to keep this experiement for this rule only, but we won't use this pattern in the future. Instead of toggling this in 30+ repos, let's just work on solving the lint errors!

**Comment by pixelzoom** [comment]
> ... Instead of toggling this in 30+ repos, let's just work on solving the lint errors!

I agree, because `explicit-member-accessibility` is relatively easy to fix.  Let's prioritize getting this cleaned up during next week's sprint.

**Comment by pixelzoom** [comment]
Unassigning myself because I have nothing left in the chip-away list, https://github.com/phetsims/chipper/issues/1258#issuecomment-1177942387.

**Comment by pixelzoom** [comment]
Oops, noticed that I'm also assigned to density-buoyancy-common.

**Comment by pixelzoom** [comment]
I spent 1.5 hours fixing up density-buoyancy-common. When I went to push, I hit loads of manual merge conflicts that I could not resolve.  It looks like multiple people were making changes to this repo while I was working.  I pushed my changes to a branch for @jonathanolson to sort out - see https://github.com/phetsims/density-buoyancy-common/issues/75.

**Comment by pixelzoom** [comment]
Here's what remains to be addressed, all @jonathanolson:

- [ ] density-buoyancy-common
- [ ] dot
- [ ] kite
- [ ] phet-core
- [ ] scenery

**Comment by samreid** [comment]
At today's check-in, @jonathanolson reported progress on these.  @zepumph volunteered for phet-core, thanks!

**Comment by pixelzoom** [comment]
This rule makes most of the [Access Modifiers](https://github.com/phetsims/phet-info/blob/master/doc/typescript-conventions.md#access-modifiers irrelevant) irrelevant in PhET's _TypeScript Conventions_ doc.  Should we remove the entire section? Keep part of it?

**Comment by zepumph** [comment]
I would remove it! It is out of date anyways

**Comment by zepumph** [comment]
After that, feel free to close, I cleaned up all package.jsons that were using this.

**Comment by pixelzoom** [comment]
@samreid do you have any feeling about blowing away the entire [Access Modifiers](https://github.com/phetsims/phet-info/blob/master/doc/typescript-conventions.md#access-modifiers) section?  I think that you may have been the author of the final 2 paragraphs.

**Comment by samreid** [comment]
Looks good to be deleted, thanks!

**Comment by samreid** [comment]
In today's meeting, we agreed this issue can be closed when:

* The section mentioned above is deleted

**Comment by pixelzoom** [comment]
**Access Modifiers** section deleted in the above commit. Closing.
