### ISSUE TITLE
Remove `@private` from ts-status

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#1259]
In https://github.com/phetsims/chipper/issues/1224, occurrences of `@private` were removed, and `@private` is not banned via bad-typescript-text.js.   So `@private` is now irrelevant for ts-status, because it is (and will always be) zero.  

@marlitas would you like to remove `@private` from ts-status, or would you like me to handle it?

<img width="919" alt="screenshot_1691" src="https://user-images.githubusercontent.com/3046552/171699921-b5957646-3a8e-4b88-9f9a-9b78ea902ec3.png">

**Comment by marlitas** [comment]
@pixelzoom I can remove it. Thanks!

**Comment by marlitas** [comment]
`@private` removed from ts-status script. Closing.
