### ISSUE TITLE
branch: arch

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#126]
chipper has an `arch` branch.  Can it be deleted? Or is it serving some purpose?

**Comment by samreid** [comment]
@jbphet created the only commit in that branch, so I will let him comment.

**Comment by pixelzoom** [comment]
@jbphet Can this branch be deleted?

**Comment by samreid** [comment]
The sh file was for deploying arch builds to simian.  Simian and arch are no longer used for our together projects, so I deleted the branch.  If needed for anything, it can be easily resurrected from 4c670e710fcbc79e878a7377c1a5677e8cf6329d .  Leaving assigned to @jbphet to make sure we did not need that script.

**Comment by jbphet** [comment]
Script not needed, no problem with deletion of branch.  Closing.
