### ISSUE TITLE
Maintenance Release: lint hits sherpa/node_modules

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#1261]
@samreid, @zepumph, and @jonathanolson, have discovered that lint only started ignoing all node_modules dirs in https://github.com/phetsims/chipper/commit/c627f0540e00b15d2dcdb28b484e79ae4d0c602e. So in the CCK AC circa 11/21, we were running an error because I recently added node_modules to sherpa in 4/26/21.

The build server will never npm install in sherpa, but to run MR's successfully locally, we would need an MR to ignore this. We could put a bandaid on this by removing sherpa/node_modules when going into old shas, but that isn't full proof, and may cause more issues upon the next time. 

I'll mark for dev meeting as a quick PSA, and get to a MR as I can.

**Comment by marlitas** [comment]
Pinging @zepumph to check in on this issue. Should this be part of the upcoming MR or is there further work to be done? Please advise on the status of this issue.

**Comment by zepumph** [comment]
@jonathanolson were you linting in your recent MR? Did you run into a sim that tried to lint our sherpa/node_modules? If so likely you added code like https://github.com/phetsims/chipper/commit/c627f0540e00b15d2dcdb28b484e79ae4d0c602e to be able to move forward. Can you speak to this?

**Comment by jonathanolson** [comment]
> @jonathanolson were you linting in your recent MR? Did you run into a sim that tried to lint our sherpa/node_modules? If so likely you added code like https://github.com/phetsims/chipper/commit/c627f0540e00b15d2dcdb28b484e79ae4d0c602e to be able to move forward. Can you speak to this?

Hmm, lets discuss if there is something else to do here? I have been doing linting in all MRs and haven't run into this.

**Comment by zepumph** [comment]
I agree. I'm surprised we haven't hit something in the area, but I'm also not complaining! I'm ready to close, because really the only trouble would be a lint failure during old shas.
