### ISSUE TITLE
Violations of SelfOptions naming conventions

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#1263]
Awhile back, we decided to standardize on the name `SelfOptions` for an unexported type that describes options that are specific to the class being defined ("self").     For nested classes, where `SelfOptions` is already used, the self-options for the nested class should be `{{ClassName}}SelfOptions`.

Using the regular expression `type .+SelfOptions =`, these violations are identified:

- [x] UnitConversionPropertySelfOptions @jonathanolson 
- [x] HalfLifeNumberLineNodeSelfOptions @chrisklus @Luisav1 
- [x] CheckboxPanelSelfOptions
- [x] AtmosphericPhotonsSoundGeneratorSelfOptions @jbphet 
- [x] ThermometerAndReadoutSelfOptions @jbphet 
- [x] IrAbsorbanceSoundPlayerSelfOptions @jbphet 
- [x] SurfaceAlbedoSoundPlayerSelfOptions @jbphet 
- [x] WaveLandscapeObservationWindowSelfOptions @jbphet 
- [x] ScreenSelfOptions @samreid 
- [x] ScreenViewSelfOptions @samreid 
- [x] ThreeIsometricNodeSelfOptions @jonathanolson 
- [x] ThreeNodeSelfOptions @jonathanolson 
- [x] ArrowsCheckboxNodeSelfOptions @AgustinVallejo 
- [x] CountingAccordionBoxSelfOptions @chrisklus 
- [x] TenFrameAccordionBoxSelfOptions @chrisklus 
- [x] WordAccordionBoxSelfOptions @chrisklus 
- [x] QuadrilateralPitchedPopGeneratorSelfOptions @jessegreenberg 
- [x] QuadrilateralNodeSelfOptions @jessegreenberg 
- [x] QuadrilateralVisibilityControlsSelfOptions @jessegreenberg 
- [x] SideLengthAreaNodeSelfOptions @jessegreenberg 
- [x] AccessibleNumberSpinnerSelfOptions @zepumph 
- [x] AccessibleSliderSelfOptions @zepumph
- [x] AccessibleValueHandlerSelfOptions @zepumph
- [x] AriaLiveAnnouncerAnnounceSelfOptions @zepumph

I'll clean these up, then alert the responsible devs.

Then the question is .... Should we have a lint rule for this?

**Comment by pixelzoom** [comment]
Violations fixed in the above commits. 

Questions related to a lint rule:
* Can we support this via bad-typescript-text.js?
* Can we detect when `{{ClassName}}SelfOptions` occurs for an inner class, or do we need `/* eslint-disable */`?  There are a handful of these so far, e.g. `HandleDragListenerSelfOptions` in BicyclePumpNode.ts.
* Should we do something to avoid needing `/* eslint-disable */` in cases where we're intentionally doing `export type {{ClassName}}SelfOptions = ...` for a non-nested class?
* Should we prevent exporting `SelfOptions`?

**Comment by zepumph** [comment]
>Should we prevent exporting SelfOptions?

I added bad text as `export type SelfOptions`, but that doesn't cover the main issue of having the primary class call its options `XSelfOptions`. Perhaps now that you have changed this, plus a PSA, it won't be an issue anymore? (wishful thinking much?)

**Comment by pixelzoom** [comment]
> I added bad text as `export type SelfOptions` ...

Not everyone appears to be using the "export where defined" pattern.  And this is not caught by bad-typescript-text.js:

```
type SelfOptions
...
export type SelfOptions;
```

**Comment by chrisklus** [comment]
From 6/16/22 dev meeting:

We think that cases that needed cleaning up were left behind from before we established this convention. Going forward, we would like to try just addressing any further violations in code review, as a lint rule seems complicated to accurately work. If we see this happening a lot still, we can revisit trying to get a lint rule working. We are ready to close, thanks @pixelzoom!
