### ISSUE TITLE
Build process with new sim pages

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/chipper#128]
Currently, in order to download html5 sims, we are relying on a .htaccess file in the sim directory on the server:

```
RewriteEngine On
RewriteCond %{QUERY_STRING} =download
RewriteRule ([^/]*)$ - [L,E=download:$1]
Header onsuccess set Content-disposition "attachment; filename=%{download}e" env=download
```

This file looks for a ?download query parameter and forces the browser to download the file instead of opening it. It is only needed in the case of browsers that don't support the new html5 "download" attribute.

Right now, there is a bit of a manual process when deploying html5 sims to make sure that this file is present. Should we make a grunt task that automatically generates this file and puts it into the build directory? Any other thoughts on this issue?

**Comment by pixelzoom** [comment]
The entire "production deploy" process is currently manual.  We've been deferring work on this until we address deploying translations.

**Comment by aaronsamuel137** [comment]
This was added in build-server. Closing
