### ISSUE TITLE
Investigate @typescript-eslint/consistent-type-definitions and @typescript-eslint/no-type-alias rules-

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#1280]
Related to our subteam meeting about https://github.com/phetsims/chipper/issues/1277 ...

We discussed 2 rules that deal with interfaces vs type aliases:

* https://typescript-eslint.io/rules/consistent-type-definitions
* https://typescript-eslint.io/rules/no-type-alias

Interfaces are described at https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#interfaces.

Type aliases are described at https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#type-aliases.

TODO:
- [ ] Understand the differences between interfaces and type aliases.
- [ ] Decide when PhET should prefer interfaces vs type aliases.
- [ ] Decide whether PhET should be making more use of interfaces.
- [ ] Decide whether either of these rules should be enabled.
- [ ] Understand what https://typescript-eslint.io/rules/no-type-alias means by "Debug your code" in this reason for preferring interfaces:

> * Debug your code: interfaces create a new name, so is easy to identify the base type of an object while debugging the application.

Additional notes:

@zepumph wondered if things like `optionize` would provide more useful information in WebStorm/tsc if interaces were used.

@pixelzoom showed this example, a case where he had not previously considered using an interface. Is interface better or worse here, and why? 

```typescript
// interface
interface IVector {
  x: number;
  y: number;
}

function printIVector( v: IVector ): void {
  console.log( `x=${v.x} y=${v.y}` );
}

// type alias
type TVector = {
  x: number;
  y: number;
};

function printTVector( v: TVector ): void {
  console.log( `x=${v.x} y=${v.y}` );
}
```

**Comment by pixelzoom** [comment]
Self assigning because this interests me, not because I want to own it.  So others should feel free to investigate.

**Comment by pixelzoom** [comment]
> - [ ] Understand the differences between interfaces and type aliases.

See https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#differences-between-type-aliases-and-interfaces

**Comment by pixelzoom** [comment]
> - [ ]  Decide when PhET should prefer interfaces vs type aliases.
> - [ ] Decide whether PhET should be making more use of interfaces.

From https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#differences-between-type-aliases-and-interfaces:
> For the most part, you can choose based on personal preference, and TypeScript will tell you if it needs something to be the other kind of declaration. If you would like a heuristic, use `interface` until you need to use features from `type`.

PhET is definitely not preferring `interface` to `type`.

So PhET should probably be making more use of `interface`.

**Comment by samreid** [comment]
Effective TypeScript by Vanderkam has a good section on the topic of types vs interfaces.  Page 52 item 13: "Know the differences between type and interface".  My takeaways from that section about the differences:

* types can represent a union, but interfaces cannot, like `type X = Y | Z`
* types are more capable than interfaces--interfaces have limitations and cannot extend certain types.
* types are a more natural match for tuples
* interfaces support declaration merging, but types do not.

Regarding declaration merging, that seems designed to support projects that need progressive enhancements over a type declaration API, which we do not need or want.  As Vanderkam says, "for a type that's used internally in your project, declaration merging is likely to be a mistake".

**Comment by samreid** [comment]
@marlitas agreed to investigate these concepts, thanks!

**Comment by pixelzoom** [comment]
> Based on these considerations, my recommendation would be to enable the lint rules that forbid our team from using `interface`, and `eslint-disable-line` for the one case we need. In the future, if we face a case where we need interfaces, we can re-evaluate.

Please no. I'm using `interface`.    And I agree with @marlitas' assessment:

> Overall, I see no benefit in limiting ourselves either way.

**Comment by pixelzoom** [comment]
I decided to try replacing `interface` with `type` in geometric-optics, to see what problems I might encounter.  I was surprised to find that `type` supports the `readonly` modifier. And that a class can use the `implements` keyword with a type.

So I feel less strongly about @samreid's proposal to ban `interface`.

**Comment by samreid** [comment]
I also tried using `type` instead of `interface` in files where I am one of the authors.  It seems to be working well.  I did notice one difference that you can `export default interface` but you cannot `export default type = ...`.

**Comment by pixelzoom** [comment]
I've concluded my investigation.  I'll be preferring `type`.  It's sad that TypeScript managed to make a mess of a basic OOP concept like `interface`.  Unassigning.

**Comment by marlitas** [comment]
The consistent-type-definitions rule has been turned on, and set to prefer 'type'. Fixes have been applied. Closing.
