### ISSUE TITLE
Notes on bringing TS code up to the current standards

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#1281]
As part of the TS sprint...

@kathy-phet would like me to take a making notes (a prioritized list of things to consider?) when bringing TS code up to the current standards.

**Comment by pixelzoom** [comment]
7/19/2022 TS meeting:

We had a discussion about the 4th bullet in https://github.com/phetsims/chipper/issues/1281#issuecomment-1185933099. Summary:

*  Regarding parameter types, I do agree with the advice in https://github.com/phetsims/chipper/issues/1281#issuecomment-1188149802.  Parameter types are informed by the needs of the method/function.  If your method needs the features of `Node`, don't use define your param at `Image`.  Prefer the most general type. 

* Regarding return types, I don't agree with the advice in https://github.com/phetsims/chipper/issues/1281#issuecomment-1188149802. Blindly returning the type of your implementation is a bad idea. Return types should be informed by the needs of the API, and you should use the most general type that meets the needs. 

* @kathy-phet asked me to add more comments to the examples in bullet 4, and that has been done.

**Comment by pixelzoom** [comment]
In Slack, @AgustinVallejo asked me about parameters.
> Does it mean that, for all my methods, if a parameter doesn't use the features of its main type, should it be typed as the most general type it belongs to?

Parameters should be typed based on the needs of the implementation, not based on the type of the arguments that happened to be used when the method was first implemented. Here's an example for `sumProperties`, a method that sums a set of Properties whose values are numbers.

```
// I have several Properties for the number of various types of particles.
// I plan to add more Properties like this in the future.
const numberOfElectronsProperty = new NumberProperty( 0, ... );
const numberOfProtonsProperty = new NumberProperty( 0, ... );
const numberOfNeutronsProperty = new NumberProperty( 0, ... );
const numberOfPhotonsProperty = new NumberProperty( 0, ... );

// I want to derive the total number of particles. This is where I discovered my need
// for a sumProperties methods.
const properties = [  numberOfElectronsProperty, numberOfProtonsProperty, numberOfNeutronsProperty, numberOfPhotonsProperty ];
const totalNumberOfParticlesProperty = new DerivedProperty( properties,
  () => sumProperties( properties ) );

// Here's my first implementation of sumProperties. Because I had NumberProperty instances
// above, I used NumberProperty[] as the type of my parameter.  This might be OK for a 
// single-use in a sim.  But as a general API this implementation is unnecessarily restrictive.
// It requires the caller to use NumberProperty, but doesn't use any of the features of 
// NumberProperty, or even features of IProperty (like set) in the implementation.  Callers 
// will not be able to use instances  Property, TinyProperty,  DerivedProperty, etc.
public sumProperties( properties: NumberProperty[] ): number {
  let sum = 0;
  properties.forEach( property => { sum += property.value; };
  return sum;
}

// This implementation is more flexible and general. The only feature used by the implementation
// is the abililty to get the value, so we type the parameter to meet that need.  In addition to 
// NumberProperty, this also allows the caller to provide arguments like Property<number>, 
// TinyProperty<number>, DerivedProperty, etc.
publiv addProperties( properties: IReadOnlyProperty<number>[]: number {
  let sum = 0;
  properties.forEach( property => { sum += property.value; };
  return sum;
}
```

Questions?

**Comment by pixelzoom** [comment]
At 7/21/2022 dev meeting, @kathy-phet said she'd like to keep this issue open, so that information herein can be rolled into other documentation as appropriate (conventions, onboarding, etc.). Assigned to @AgustinVallejo to lead that effort.

**Comment by jbphet** [comment]
I've assigned myself to this, and will work with @AgustinVallejo to make sure that we have captured the information above in our TypeScript standards doc(s).

**Comment by marlitas** [comment]
@jbphet and @AgustinVallejo, looks like we added this to the onboarding documentation. Can this be wrapped up and closed now?
