### ISSUE TITLE
Choose an appropriate prefix for naming type aliases.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#1287]
There is a curious convention I'm seeing in common-code, using an "I" prefix for type aliases.  I see IEmitter, IModel, and IBrand created recently, and there may be others.

Let's please not do this.  The "I" prefix is a questionable/controverisal convention that's applied to interfaces. Applying it to type aliases is confusing at best.  And if something started out as an `interface` and was converted to a `type`, let's please rename the type alias.

I hope we don't need to add this to the TypeScript Conventions doc, but perhaps we do.

**Comment by pixelzoom** [comment]
If we want a prefix, how about using "T" prefix in these cases?

**Comment by pixelzoom** [comment]
Since I suspect this will require dev meeting discussion, I'll jost down some notes...

The "I" prefix has its roots in Hungarian Notation, a convention of naming variables so that you can tell something about them by their names.  If this is new to you, see https://en.wikipedia.org/wiki/Hungarian_notation

The "I" prefix has historically been applied to `interface` in various programming languages at support interfaces (C++, Java,...)  It dates back to at least the late 1980's.  And note that this convention is applied to `interface` -- not "an interface", because everything has an interface.

The "I" prefix (and Hungarian notation) has also been controversial. See [IInterface Considered Harmful](https://developer.okta.com/blog/2019/06/25/iinterface-considered-harmful) for an example of the typical arguments against the "I" prefix.  

But this issue isn't about whether to use prefixes.  It's about abusing the "I" convention by applying it to something that is not an `interface`.   Reasons why this is a bad idea:

(1) The 'I' prefix is a decades-only convention that spans programming languages. When it is used, it's applied to an `interface`.  

(2) Violating conventions that span programming languages is a disservice to newer developers who are learning about conventions, and confusing for experienced developers that join the team. 

(3) Applying "I" to type aliases misses the entire point of Hungarian Notation and naming conventions. Your giving something a name that identifies it as an `interface`, and it is not an `interface`. You'd never name a class with an "I" prefix. Why would you do that for a type alias? 

(4) TypeScript type aliases and interfaces have many similarities, but they also have differences. Why would you name a type alias in a way that makes it look like an interface?

(5) PhET is discussing whether to ban `interface`, see https://github.com/phetsims/chipper/issues/1280#issuecomment-1188420551.  Regardless of the outcome there, how does that make it appropriate to use "I" for type aliases? And what happens if we change our minds (or need exceptions to the ban)? 

(6) Using the same prefix for type aliases and interfaces results in errors like the example shown below.  And it develops bad habits.  IModel and IControl both have names that tell me `interface`.  Composing types using IModel (a `type`) becomes a bad habit, causing me to get in trouble by trying to do the same with IControl (and `interface`).

```
type IModel = {...}
interface IControl {...}

type MyOptions = SelfOptions & IModel; // no error, types can be composed
type MyOptions = SelfOptions & IControl; // error, interface cannot be composed with type
```

(7) It's entirely unnecessary to use the "I" prefix for type aliases.  If you like having a "prefix", or if it helps resolve naming problems, choose a different prefix for type aliases.  Use it consistently and be prepared to explain when the convention should be used.

**Comment by pixelzoom** [comment]
At 7/20/2022 TS meeting, @kathy-phet suggested changing to prefix 'A'.   That's also problematic, because:

* 'A' is a lesser-used prefix that is typically applied to abstract class names. 
* Names like "AModel" and "AProperty" don't read very well.  "A" reads like an indefinite article.

**Comment by kathy-phet** [comment]
Note, suggestion based on A=alias. But sounds like good reasons to not use "A".

**Comment by samreid** [comment]
After reading this article https://stackoverflow.com/questions/31876947/confused-about-the-interface-and-class-coding-guidelines-for-typescript I'm more inclined to name the interface for its behavior, like `type Emitter = {...}` and then to give more specific names to the subtypes.  We already have `TinyEmitter` which is good.  For AXON/Emitter, @jonathanolson suggested `FullEmitter`.  Brainstorming alternatives in case we pursue this direction:

* FullEmitter
* AxonEmitter (awkward since TinyEmitter is also defined in axon)
* PhetioEmitter (since it adds phetio functionality. Awkward since it doesn't emit phetios)
* InstrumentedEmitter (this sounds promising, since it is how we often refer to in in discussion).  But beside instrumention Emitter also adds Validator.  But in many cases that is now unnecessary, such as `Emitter<[number]>({valueType: 'number'})`

Scanning through occurrences of `new Emitter`, I see 334 cases.  But I'm also seeing that many (maybe half?) aren't instrumented at all. Those cases could (should?) use TinyEmitter.  We could guard against this case by making `tandem` required in `Emitter`.  In doing that, I see 38 errors where TinyEmitter looks preferable.

**Comment by pixelzoom** [comment]
While I agree with https://github.com/phetsims/chipper/issues/1287#issuecomment-1191562287, I think a better frist step would be to use a different prefix for type aliases.  Then (as time permits) take on the large task of eliminiating the need for a prefix. 

Looking through the list in https://github.com/phetsims/chipper/issues/1287#issuecomment-1190501197, the prefixes that will be most difficult to eliminate are probably IColor, IPaint, and IProperty.

**Comment by pixelzoom** [comment]
So... I propose that we use a 'T' prefix for type aliases _where necessary_, strive to avoid using such a prefix in new code, and (longterm) eliminate the need for a prefix where possible by improving/refactoring names.

**Comment by zepumph** [comment]
I totally agree, so I'll just re-iterate in a slightly different way. To proceed:
* Rename all "I" prefixes to "T"
* Create an issue to rename the Emitter hierarchy or use https://github.com/phetsims/axon/issues/402.
* Continue to seek out interfaces that could be better renamed
* Try hard to never create a new type that starts with `T`, instead naming it to be the best, prefixless name possible.

Any opposition or addendum?

**Comment by jonathanolson** [comment]
Additionally, this should be put into the TypeScript conventions document (e.g. prefer a good name, otherwise prefer T...)

**Comment by marlitas** [comment]
@AgustinVallejo and I also found:
- [ ] IOverlay
- [ ] IInputListener

**Comment by marlitas** [comment]
changed the prefix for all instances I could find. @AgustinVallejo can you double check that there are no remaining I types that need to be changed to T? If we're all good I think we can close!

**Comment by samreid** [comment]
@AgustinVallejo can this issue be closed?

**Comment by AgustinVallejo** [comment]
It can!
