### ISSUE TITLE
Require return type for `function`?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#1288]
A .ts file often contains private functions, like this one in Dialog.ts:

```ts
function applyDoubleMargin( dimension: number, margin: number ) {
  return ( dimension > margin * 2 ) ? ( dimension - margin * 2 ) : dimension;
}
```

Note that there's no return type specified.  And when I glanced quickly at this and saw `dimension`, I guessed that this returned `Dimension2` -- which is not the case.   

Should we require a return type for functions? I think so.  

I'm still OK with arrow functions being up to developer discretion.

**Comment by zepumph** [comment]
```
const applyDoubleMargin = ( dimension: number, margin: number ): number => {
  return ( dimension > margin * 2 ) ? ( dimension - margin * 2 ) : dimension;
}
```

**Comment by zepumph** [comment]
Tagging the last time we talked about explicit-function-return-type:

https://github.com/phetsims/chipper/issues/1215

**Comment by jessegreenberg** [comment]
Discussed today - We would like to have return types for functions and methods but we do not want explicit return types for anonymous functions. Last time we tested https://typescript-eslint.io/rules/explicit-function-return-type/ we identified that the rule could not distinguish between functions and anonymous functions. But I will try briefly try options.

If the built-in rule doesn't work out Ill investigate modifying our custom `explicit-method-return-type` rule to also catch functions.

**Comment by jessegreenberg** [comment]
Option `allowExpressions: true` catches declared functions but allows anonymous functions.

<details>

![image](https://user-images.githubusercontent.com/6396244/184170058-66a54ff4-0b71-45db-a7f2-e49ad2939d82.png)

</details>

`explicit-function-return-type` with `allowExpressions: true` has 754 errors on master but the rule does not support auto-fix.

Maybe it would be quick enough to implement an auto fix with our custom rule, and then switch to the built-in rule once there are no more errors.

**Comment by jessegreenberg** [comment]
I was mistaken in https://github.com/phetsims/chipper/issues/1288#issuecomment-1198536600, we want to allow return type inference for anonymous functions AND functions of a variable declaration. The built-in rule `explicit-function-return-type` does not support this. But it should be easy to catch function declarations with our custom `explicit-method-return-type` rule and probably even use the auto fix.

**Comment by jessegreenberg** [comment]
`explicit-function-return-type` now has support for requiring return types on function declarations with an auto fix. Commits following this comment apply the auto fixes. Ill skim through them to make sure they seem right.

**Comment by jessegreenberg** [comment]
Function declarations now require return types. There was still a question about whether function defined in variable declarations also need to have return types annotations:


> Jesse Greenberg
> Im back to https://github.com/phetsims/chipper/issues/1288. Should a variable declaration like this require return type annotations?
> 
>     const allLengthsEqualListener = ( allLengthsEqual: boolean ) => {
>       allLengthsEqual && this.allLengthsEqualSoundClip.play();
>     };
>     shapeModel.allLengthsEqualProperty.lazyLink( allLengthsEqualListener );
> 
> 
> Sam Reid
> I think we agreed localized cases like that do not need to declare the return type, OK to infer
> 
> Jesse Greenberg
> Thank you. I think that rules out the built-in rule, but simplifies an auto fix with our own rule. I had thought we only wanted to let anonymous functions skip the annotation.
> 
> Michael Kauzmann
> Hmmm. I thought we agreed that anything declared with an equals sign needed one, if it is a function(){} or a ()=>{}, and that we didn't need it for anonymous items like doSomething( ()=> {then()})
> 
> 
> Jesse Greenberg
> That matches my notes but it seemed unnecessary for many cases. Im almost done with function declarations, we can come back and confirm we want it for variable declarations too.
> 
> Sam Reid
> I thought the rule was if it formed part of a public API it needed a type annotation.  Local “implementation details” do not
> 

Searching for these functions with explicit-function-return-type. Most examples look like
https://github.com/phetsims/tambo/blob/9db69bcaefbecf0e347eca6d9a6bf66ae8720005/js/soundManager.ts#L242-L248
https://github.com/phetsims/geometric-optics/blob/bc112e89d4cfec8a35d7f53cbf30125eb0a941b2/js/common/view/tools/GORulerNode.ts#L141-L143
https://github.com/phetsims/scenery-phet/blob/437ccabc8e8c23bd5c4638197f1f5099b145be95/js/NumberDisplay.ts#L205-L213

Putting back on dev meeting to decide if we should do more with lint.

**Comment by zepumph** [comment]
>I thought the rule was if it formed part of a public API it needed a type annotation. Local “implementation details” do not

@samreid, that was the decision we made in https://github.com/phetsims/chipper/issues/1215. Then we reopened the discussion to add more potential cases in this issue, with private "helper" functions that aren't used in the public API. The example in the initial issue comment here is a great example that we decided at dev meeting was worth adding to the lint rule. Do you feel differently?

**Comment by zepumph** [comment]
>Putting back on dev meeting to decide if we should do more with lint.


@jessegreenberg, can we start with just `function(){}` annotation?

**Comment by jessegreenberg** [comment]
Functions like the one in the initial issue comment require a return type after https://github.com/phetsims/chipper/issues/1288#issuecomment-1213387205.  But the remaining question was whether we also want to require a return type for functions assigned to a variable declaration like the examples at the bottom of https://github.com/phetsims/chipper/issues/1288#issuecomment-1213492354. These are not anonymous but most are local and probably would be anonymous if disposal was not a requirement.

**Comment by samreid** [comment]
Today we discussed https://github.com/phetsims/chipper/issues/1288#issuecomment-1198524562 and asked if it would be ok if the `:number` return type was missing?

@pixelzoom and @zepumph agreed that would be OK.  This seems to be the team consensus.

@pixelzoom argues that this issue is at a good point, and we don't need to add more requirements.  We are at the point of diminishing returns.

@zepumph clarifies: would the lint rule would be harder to create than the benefit we would attain?

**Comment by jessegreenberg** [comment]
To summarize the above from dev meeting today we agreed that examples mentioned in https://github.com/phetsims/chipper/issues/1288#issuecomment-1213492354 do not need a return type. That syntax is most often used in local declarations and not in public APIs so a return type does not need to be explicit. This is ready to close.
