### ISSUE TITLE
Webstorm-only bug: `Attempt to assign to const or readonly variable`

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#1291]
When using IProperty, I found that my Webstorm was unable to parse where the `value` setter comes from. When I press "go to declaration" (ctrl + b), it gives me a list of IProperty and IReadOnlyProperty, as if it could be possible that `set value` is in IReadOnlyProperty`. Then it gives the error "Attempt to assign to const or readonly variable". TSC and lint passes though.

This patch does not solve it:
```diff
Index: js/IProperty.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/IProperty.ts b/js/IProperty.ts
--- a/js/IProperty.ts	(revision a526a60590f3e5b0cd6677beab18813cc83065e7)
+++ b/js/IProperty.ts	(date 1658867019716)
@@ -13,5 +13,6 @@
 type IProperty<T> = IReadOnlyProperty<T> & {
   set( value: T ): void;
   set value( value: T );
+  get value(): T;
 };
 export default IProperty;
\ No newline at end of file
```

But I found this patch does. I'm going to commit it and see if we should keep it forever:

```diff
Index: js/IProperty.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/IProperty.ts b/js/IProperty.ts
--- a/js/IProperty.ts	(revision a526a60590f3e5b0cd6677beab18813cc83065e7)
+++ b/js/IProperty.ts	(date 1658867127960)
@@ -1,5 +1,6 @@
 // Copyright 2021-2022, University of Colorado Boulder
 
+import StrictOmit from '../../phet-core/js/types/StrictOmit.js';
 import IReadOnlyProperty from './IReadOnlyProperty.js';
 
 /**
@@ -10,8 +11,9 @@
  */
 
 // See comments in Property.ts / TinyProperty.ts
-type IProperty<T> = IReadOnlyProperty<T> & {
+type IProperty<T> = StrictOmit<IReadOnlyProperty<T>, 'value'> & {
   set( value: T ): void;
   set value( value: T );
+  get value(): T;
 };
 export default IProperty;
\ No newline at end of file
```

Tagging @chrisklus since he was experiencing this, and also wanted to be part of our meeting but was busy.

**Comment by zepumph** [comment]
@samreid will you please review this. I'm unsure if you had been able to reproduce this on your copy of webstorm. I'll note that @jessegreenberg was unable to, but I could. He was able to reproduce the part though where ctrl + B showed both the IReadOnlyProperty declaration of `value` (getter only) as well as the setter in `IProperty`.

**Comment by zepumph** [comment]
I experienced this on 2022.1 but am currently on 2022.2. @jessegreenberg was on 2022.1 for our call but just updated to 2022.2 and still doesn't see the problem (before pulling my change above).

**Comment by chrisklus** [comment]
Patch is working for me, thank you very much!

**Comment by zepumph** [comment]
Tagging @Luisav1 because I believe she had this exact issue that she brought to dev meeting last week. It should be fixed!

**Comment by Luisav1** [comment]
Thanks @zepumph! This is the issue I had but the patch fixed it now too.

**Comment by samreid** [comment]
I temporarily reverted the fix commit, and navigated to several sites that specified `.value = ...` in *.ts code.  They all seemed to navigate correctly on my system.  Still, the proposed commit seems a good way to pair the getters and setters, so it seems good to me.  Anything else to discuss here?
