### ISSUE TITLE
Update documentation about precommit hooks, precommit-hook-changed-repos and commit workflow

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1293]
Today, @kathy-phet asked me to update documentation about precommit-hook-changed-repos and that commit process.

* SR/MK: PSA: New caching strategy for super speed pre commit hooks. Thanks SR!
* Caching is super fast, and automatically set up in all linting and pre commit hooks.
* We also have two new scripts for your use:
* absolute-tsc uses the cache layer for type checking
* precommit-hook-changed-repos will run the pre-commit hooks on all repos with working copy changes. These results are cached so that the actual git hooks upon commit and super speedy.
* SR to update documentation for devs / new devs, and MS to review. 
* To be clear, we are no longer pursuing pre-push hooks (this solves that).

**Comment by samreid** [comment]
I updated the docs, @marlitas can you please review?

**Comment by marlitas** [comment]
@samreid the new language looks good. 

I saw you removed the bullet point `- Check lint and tsc separately by running "grunt lint" or "tsc" in a sim repo.`, but it doesn't seem like the new info you provided addresses that bullet point. Should we add info referring to `grunt lint` and `tsc` or should that stay out of this document?

**Comment by samreid** [comment]
I removed those details since the precommit hooks include lint and tsc, so I thought it would be simplest to just have one entry point.  Particularly since this section is about precommit hooks.  But I'm not opposed to mentioning `grunt lint` or `tsc` (or more appropriately absolute-tsc?) here or elsewhere.

**Comment by marlitas** [comment]
Tsc documentation updated in on-boarding doc based on developer feedback from 8/4/22.
Closing.
