### ISSUE TITLE
absolute-tsc not providing links in Windows/IntelliJ

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1294]
@marlitas indicated that @jbphet reported absolute-tsc not providing links in Windows/IntelliJ.  

We were wondering if you did this step?

```
IMPORTANT!!! This makes the files paths clickable in Webstorm:
output filters: $FILE_PATH$\($LINE$\,$COLUMN$\)
```

If so, please reassign to me for further evaluation.

**Comment by jbphet** [comment]
Ah, thanks, I definitely missed that step.  I just added it, and the links are now clickable.  Thanks @samreid!  Closing.
