### ISSUE TITLE
Increase size of Activity Log in a11y view

### ISSUE THREAD

**Issue by arouinfar** [phetsims/chipper#1296]
The Activity log of Responsive Descriptions only displays the five most recent alerts. 
<img width="468" alt="image" src="https://user-images.githubusercontent.com/8419308/182715087-ce0fa0f5-1071-4bb4-8c99-15fb6c860e66.png">

This is a relatively low number and makes things difficult when reviewing the descriptions in the a11y view. Would it be possible to increase the maximum number of displayed responsive descriptions? Maybe even double it?

This has been an ongoing frustration while working on Greenhouse Effect, and I often resort to pausing the simulation so I can review the responsive descriptions before they fall off the Activity Log. Not all simulations have a pause button, so this workaround won't always be viable.

Assigning @jessegreenberg since I brought this up in a Greenhouse meeting,  but feel free to re-assign as appropriate.

**Comment by jessegreenberg** [comment]
OK, changed with the above commits and regenerated all a11y views. To summarize the changes:
- Doubled the number of alerts in the log.
- Increased the min height of the activity log
- Added a "Clear Log" button that will clear all alerts in the log when you press it.

@arouinfar can you please review how this looks?

**Comment by arouinfar** [comment]
@jessegreenberg this is amazing! It really improves the experience of reviewing responsive descriptions in Greenhouse Effect, and likely in other sims too.

**Comment by jessegreenberg** [comment]
Excellent, thanks @arouinfar! @zepumph would you like to review this? You did a significant amount of the layout work for the a11y view so I thought it would be good for you to at least be aware of this change. Important commits are
https://github.com/phetsims/chipper/commit/d61f4879814cf0e69e6ead9427f8396bcf3dd0cc
https://github.com/phetsims/chipper/commit/c6f3db661af558eebecdb90a889b349e94f9265b
https://github.com/phetsims/chipper/commit/466b649e1f05d50e7280272a7b62d0dff9b00eba

https://github.com/phetsims/chipper/issues/1296#issuecomment-1204572366 describes changes.

**Comment by zepumph** [comment]
I love it! While I was reviewing, I found a lot of margin around the edges, and thought it would be nice to clean up some CSS. Feel free to close on my account.

**Comment by jessegreenberg** [comment]
It looks nice, thanks! Closing.
