### ISSUE TITLE
lint --fix option isn't working

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/chipper#1297]
@marlitas noticed this and announced on slack:

> What is the recommended lint command to run with the --fix option? All I have used is grunt lint-everything from chipper and that does not seem to like --fix. (edited) 

The error from running grunt lint on @marlitas machine was
>Fatal error: perennial grunt "--repo=chipper" "lint-everything" "--fix" failed with code 1

We tried to get more info about the error with
> await ESLint.outputFixes( allResults ).then( ( event => { console.log( 'success' ); }, event => { console.log( 'failure' ); } ) );

And saw that "failure" is printed. The `event` here is undefined. We tried this with a few different lint rules that were documented as fixable and none of them would fix.

**Comment by marlitas** [comment]
Did a little more investigation on this today:

- I tried running eslint directly from chipper's `node_modules` while referencing the path of a specific file to fix:
`./node_modules/.bin/eslint  --fix /Users/marlitas/my_code/PhET/phetsims/scenery/js/overlays/IOverlay.ts`

- At first this gave me the error:
`ESLint couldn't find the plugin "@typescript-eslint/eslint-plugin".`

- So I ran an `npm install` for `@typescript-eslint/eslint-plugin@latest` from my phetsims root.
- Running the eslint directly again from `node_modules` did apply the auto-fix to `IOverlay.ts`
- Running `grunt lint --fix` still errors out as does `grunt lint-everything --fix`

**Comment by zepumph** [comment]
Thanks for the report @marlitas. 

@marlitas and I took a look together, and after I drove us down deep and dark spaces, we realized that it was a simple bug fix in lint.js where we weren't passing the fix option through.

Closing
