### ISSUE TITLE
Add a grunt task to build a together.js sim

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#130]
Documentation for how to do so manually currently resides in:
https://github.com/phetsims/together/blob/master/doc/publishing-a-sim.md

**Comment by samreid** [comment]
Step 1 is:
> Make sure you're on the together branch or are using a repo that only produces together-enhanced sims, such as beaker.

Instead, we should automatically append the package.json preload entries with the required files.

**Comment by jbphet** [comment]
implemented, assigning to @samreid to review

**Comment by pixelzoom** [comment]
This documentation was added in `grunt.registerTask( 'build',...)`:

> '--together',

This is insufficient, it doesn't describe what it does. See the other examples directly above it.

**Comment by pixelzoom** [comment]
The assertions below were added to js/grunt/Gruntfile.js. These don't belong in Gruntfile.js.  They belong in the grunt task (.js file) that requires them. 

```js
  if ( grunt.option( 'together' ) ) {
    console.log( 'Adding additional preload files for together' );
    // add the additional preload files needed to support data exchange using together.js
    pkg.preload.push( '../together/js/together.js' );
    pkg.preload.push( '../together/js/SimIFrameAPI.js' );
    pkg.preload.push( '../together/js/arch.js' );
    pkg.preload.push( '../together/js/datamite.js' );
    pkg.preload.push( '../together/js/api/Common.js' );
    pkg.preload.push( '../together/js/api/' + pkg.name + '-api.js' );
  }
```

**Comment by pixelzoom** [comment]
This block of code was added to js/grunt/Gruntfile.js. It doesn't belong in Gruntfile.js.  It belongs in the grunt task (.js file) that handles the 'together' option.

```js
  if ( grunt.option( 'together' ) ) {
    console.log( 'Adding additional preload files for together' );
    // add the additional preload files needed to support data exchange using together.js
    pkg.preload.push( '../together/js/together.js' );
    pkg.preload.push( '../together/js/SimIFrameAPI.js' );
    pkg.preload.push( '../together/js/arch.js' );
    pkg.preload.push( '../together/js/datamite.js' );
    pkg.preload.push( '../together/js/api/Common.js' );
    pkg.preload.push( '../together/js/api/' + pkg.name + '-api.js' );
  }
```

**Comment by pixelzoom** [comment]
This block of code was added to js/grunt/Gruntfile.js. It doesn't belong in Gruntfile.js.  It belongs in afterRequirejsBuild.js, which is where the preloads are injected into the HTML file.

```js
  if ( grunt.option( 'together' ) ) {
    console.log( 'Adding additional preload files for together' );
    // add the additional preload files needed to support data exchange using together.js
    pkg.preload.push( '../together/js/together.js' );
    pkg.preload.push( '../together/js/SimIFrameAPI.js' );
    pkg.preload.push( '../together/js/arch.js' );
    pkg.preload.push( '../together/js/datamite.js' );
    pkg.preload.push( '../together/js/api/Common.js' );
    pkg.preload.push( '../together/js/api/' + pkg.name + '-api.js' );
  }
```

**Comment by samreid** [comment]
Well, some of the additional packages have 3rd party license info that needs to get added, so I think this list should be augmented before that step.

**Comment by pixelzoom** [comment]
To be clear... Gruntfile.js is supposed to be a lightweight container for registering tasks, and I spent a huge amount of time making it so.  It is not supposed to do the lifting.  'together' is irrelevant to many of the other tasks registered, and should be handled in the grunt task (.js) where it is relevant.  If 3rd party licenses need to be augmented, then do so in the appropriate grunt task (.js), not in Gruntfile.js.

**Comment by pixelzoom** [comment]
License text is assembled in generateLicenseText.js.  It would be appropriate to check grunt.option( 'together' ) there, then augment the license text as needed.

**Comment by samreid** [comment]
Sounds good, thanks!

**Comment by pixelzoom** [comment]
Or create a new grunt task (set-preload?) that augments pkg.preload and add it as an addition step here:

```js
grunt.registerTask( 'build-no-lint',
    'identical to "build", but does not run "lint-all"',
    [ 'clean', 'set-preload', 'generate-license-text', 'before-requirejs-build', 'requirejs:build', 'after-requirejs-build' ] );
```

**Comment by pixelzoom** [comment]
Or if you think there will be more things required for together, call the new task something with 'together' in the name.

**Comment by samreid** [comment]
Yes, it will be a suite of several files, so I don't recommend set-preload.

**Comment by jbphet** [comment]
I've added the brief description of the --together option and fixed a problem with its operation.  I'm a bit reluctant to do the rest of the refactoring until I can work with @pixelzoom on it, lest we go through another round of this.  I'll work with him when he's available to get this into an acceptable state.  Assigning to myself.

**Comment by samreid** [comment]
Today @pixelzoom volunteered to factor out preload files (common and together).

**Comment by pixelzoom** [comment]
Consensus at 4/23/15 developer meeting:

• Remove common preloads out of package.json for all sim.
• Specify only sim-specific preloads in package.json for sims.
• Create something like getPreload.js that gets the list of preloads.  It adds common preloads first, then sim-specific preloads (as specified in package.json), then (if --together option is specified) adds together preloads.
• Call getPreload.js wherever preloads are needed.

**Comment by pixelzoom** [comment]
Looks like the common preloads are:

```
    "../assert/js/assert.js",
    "../sherpa/jquery-2.1.0.js",
    "../sherpa/lodash-2.4.1.js",
    "../sherpa/has.js",
    "../sherpa/FileSaver.js",
    "../chipper/js/initialize-globals.js",
    "../phetcommon/js/analytics/google-analytics.js"
```

Is everyone OK with all sims having to use the same versions for the common preloads?

**Comment by pixelzoom** [comment]
The development html files for sims have a different order of preloads than package.json.  For example:

```
  // acid-base-solutions_en.html
  <!-- jquery must be loaded here -->
  <script type="text/javascript" src="../sherpa/jquery-2.1.0.js"></script>
  <script type="text/javascript" src="../sherpa/lodash-2.4.1.js"></script>
  <script type="text/javascript" src="../sherpa/has.js"></script>
  <script type="text/javascript" src="../sherpa/FileSaver.js"></script>
  <!-- PhET common code that must be loaded pre-RequireJS -->
  <script type="text/javascript" src="../assert/js/assert.js"></script>
  <script type="text/javascript" src="../chipper/js/initialize-globals.js"></script>

    // acid-base-solutions/package.json
    "../assert/js/assert.js",
    "../sherpa/jquery-2.1.0.js",
    "../sherpa/lodash-2.4.1.js",
    "../sherpa/has.js",
    "../sherpa/FileSaver.js",
    "../chipper/js/initialize-globals.js",
    "../phetcommon/js/analytics/google-analytics.js"
```

I'm going to change the order of the common preloads, so that all sherpa stuff is loaded first. That is:

```
    "../sherpa/jquery-2.1.0.js",
    "../sherpa/lodash-2.4.1.js",
    "../sherpa/has.js",
    "../sherpa/FileSaver.js",
    "../assert/js/assert.js",
    "../chipper/js/initialize-globals.js",
    "../phetcommon/js/analytics/google-analytics.js"
```

**Comment by pixelzoom** [comment]
Work completed. 

The new task is `set-preload`, implemented in setPreload.js. It modifies pkg.preload, and encapsulates common- and together-specific preloads.  The preload field in package.json is now used to specify only sim-specific preloads.   When the preloads are assembled, they are assemble in this order: common, sim-specific, together.  

Common preloads were removed from all package.json files, and the order of sim-specific preloads was preserved. 

I used `grunt-all.sh` and 'grunt-all.sh build-no-lint` to test that all sims build.  But 11 sims failed to build for other reasons (issues were created).  I spot checked a few of the builds to make sure they run; a few with only common preloads, a few with sim-specific preloads. 

The most common sim-specific preload is Tween-r12.js, followed by seedrandom-2.2.js.

**Comment by pixelzoom** [comment]
Assigning to @jbphet to review, since he did the initial work on adding together preloads.

**Comment by pixelzoom** [comment]
This seems to be working OK, and people are too busy to review. So closing.

**Comment by samreid** [comment]
Thanks for working on this.  I haven't taken it for a test drive yet but am looking forward to doing so.  I also wanted to point out that the chipper together builder may have to change if/when we move forward with https://github.com/phetsims/together/issues/108 (using requirejs instead of preload for loading critical parts of together).

**Comment by samreid** [comment]
@jbphet does the documentation at together/doc/publishing-a-sim.md need to be updated to reflect the changes here?  I'm just wondering how to publish a together sim based on the changes you and @pixelzoom made here.

**Comment by jbphet** [comment]
We're doing another round of mods to this based on a discussion from last week's developer meeting.  We've decide to build both -dev and -together versions when the --together flag is specified.  @pixelzoom has volunteered to do the initial round of implementation for this.  Once that's in place, then yes, the docs should be updated.

**Comment by jbphet** [comment]
The work done here was for a 'phase 1' sort of thing, and I believe this issue is now supplanted by https://github.com/phetsims/chipper/issues/440.  I don't see together/doc/publishing-a-sim.md in the repo anymore, so I'm thinking it is no longer needed.  I think it's safe to close this, assigning to @samreid to confirm.

**Comment by samreid** [comment]
Indeed #440 is going nicely and this issue can be closed.
