### ISSUE TITLE
Is there a faster way to check the working copy status of all repos?

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#1301]
In precommit-hook-multi.js we run these two git commands on every repo:

`git update-index --refresh`
`git diff-index --quiet HEAD --`

The commands themselves are really really fast, when we Promise.all on each `execute` call, it only takes 20 ms to resolve. The issue is in spinning up 2n child processes. I found that each command (of 2) takes between 1.1 and 1.2 seconds to execute:

```

    const updateIndexPromises = repos.map( repo => execute( 'git', 'update-index --refresh'.split( ' ' ), `${repo}`, {

      // resolve errors so Promise.all doesn't fail on first repo that cannot pull/rebase
      errors: 'resolve'
    } ) );
    await Promise.all( updateIndexPromises );

    const diffIndexPromises = repos.map( repo => execute( 'git', 'diff-index --quiet HEAD --'.split( ' ' ), `${repo}`, {

      // resolve errors so Promise.all doesn't fail on first repo that cannot pull/rebase
      errors: 'resolve'
    } ) );
    const results = await Promise.all( diffIndexPromises );

```

@samreid mentioned yesterday that those commands take only a fraction of a second on a mac (or his mac at least). I'll investigate to see if we can make some cross-platform performance improvements.

**Comment by zepumph** [comment]
I looked at https://stackoverflow.com/questions/35004492/node-child-process-spawn-multiple-commands and saw that by passing in "shell:true" to execute, you can use `&&`, so that is just a single command per repo. This line takes between 1700 and 2000ms. An improvement, but not too much (I guess it takes more to run a command from a new shell).

```
    const updateIndexAndDiffPromises = repos.map( repo => execute( 'git', 'update-index --refresh && git diff-index --quiet HEAD --'.split( ' ' ), `${repo}`)

```

**Comment by zepumph** [comment]
Here was a commit that uses child_process.exec instead of spawn (from execute), trying to see if it is something from execute that we are doing. It isn't. I still was getting ~1600 and greater spin up time. Sometimes it was even 3seconds or so (perhaps a weird way git caches these?)

```diff
Index: js/scripts/precommit-hook-multi.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/scripts/precommit-hook-multi.js b/js/scripts/precommit-hook-multi.js
--- a/js/scripts/precommit-hook-multi.js	(revision 140eb3cced3a69d72a6d1efaaa0c8ad3ebd8bb19)
+++ b/js/scripts/precommit-hook-multi.js	(date 1660146419785)
@@ -4,6 +4,7 @@
 const execute = require( '../../../perennial-alias/js/common/execute' );
 const _ = require( 'lodash' ); // eslint-disable-line
 const fs = require( 'fs' );
+const child_process = require( 'child_process' );
 
 // constants
 // Don't use getActiveRepos() since it cannot be run from the root
@@ -33,24 +34,23 @@
 
   if ( !all ) {
 
-    // Detect uncommitted changes in each repo:
-    // https://stackoverflow.com/questions/3878624/how-do-i-programmatically-determine-if-there-are-uncommitted-changes
-    // git update-index --refresh
-    // git diff-index --quiet HEAD --
-
-    const updateIndexPromises = repos.map( repo => execute( 'git', 'update-index --refresh'.split( ' ' ), `${repo}`, {
+    const execOnRepo = repo => {
+      return new Promise( resolve => {
+
+        // Detect uncommitted changes in each repo:
+        // https://stackoverflow.com/questions/3878624/how-do-i-programmatically-determine-if-there-are-uncommitted-changes
+        // git update-index --refresh
+        // git diff-index --quiet HEAD --
+        // This will error if the diff-index shows any changes in the repo, otherwise error is null.
+        child_process.exec( 'git update-index --refresh && git diff-index --quiet HEAD --', { cwd: repo },
+          error => resolve( error ) );
+      } );
+    };
 
-      // resolve errors so Promise.all doesn't fail on first repo that cannot pull/rebase
-      errors: 'resolve'
-    } ) );
-    await Promise.all( updateIndexPromises );
-
-    const diffIndexPromises = repos.map( repo => execute( 'git', 'diff-index --quiet HEAD --'.split( ' ' ), `${repo}`, {
-
-      // resolve errors so Promise.all doesn't fail on first repo that cannot pull/rebase
-      errors: 'resolve'
-    } ) );
-    const results = await Promise.all( diffIndexPromises );
+    const start = Date.now();
+    const updateIndexAndDiffPromises = repos.map( execOnRepo );
+    console.log( Date.now() - start );
+    const results = await Promise.all( updateIndexAndDiffPromises );
 
     // Find out which repos have uncommitted changes
     const changedRepos = [];
@@ -58,7 +58,7 @@
       const repo = repos[ i ];
       const result = results[ i ];
 
-      if ( result.code === 0 ) {
+      if ( result === null ) {
 
         // was up-to-date
       }
```

**Comment by zepumph** [comment]
Ok. What I really found was that the overhead is in running these two git commands. I was able to pull some minor savings (my best guess is between 300-500ms by combing two child processes into a single command (which requires exec instead of spawn), but it was no where near the amount of speed increase as this patch below. I really wanted to convince myself that we didn't need to reindex each time, enough so that I committed, but then I "rolled back" a change in a repo in webstorm, and the script still thought there were working copy changes in that repo. 

Here are some great time savings for me (~50%)!

```diff
Index: js/scripts/precommit-hook-multi.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/scripts/precommit-hook-multi.js b/js/scripts/precommit-hook-multi.js
--- a/js/scripts/precommit-hook-multi.js	(revision 5867bf012ab9dd66cda0a4c5f780293ab95e5497)
+++ b/js/scripts/precommit-hook-multi.js	(date 1660147787826)
@@ -42,7 +42,7 @@
         // git update-index --refresh
         // git diff-index --quiet HEAD --
         // This will error if the diff-index shows any changes in the repo, otherwise error is null.
-        child_process.exec( 'git update-index --refresh && git diff-index --quiet HEAD --', { cwd: repo },
+        child_process.exec( 'git diff-index --quiet HEAD --', { cwd: repo },
           error => resolve( error ) );
       } );
     };
```


@samreid will you take a look. I'm not sure it is worth much more effort on my side. I guess git commands just take longer on windows git bash. I am fine with it being ~2-5 seconds to do this calculation given the last hour.

**Comment by samreid** [comment]
It seems reasonable to have intermittent false positives if they are all in the direction of testing too much instead of too little.  We could also add another script/utility that does the update-index when a false positive is observed.  I'll commit the change above and let's go from there.

**Comment by zepumph** [comment]
I was worried for a second with the following thought: If it can have a false positive when rolling back, couldn't it also have a false negative when applying a patch?

To test this, I reproduced the false positive, and added a few more steps to find that it did in fact detect the changes from the patch when applying them:

* delete a line of code from a file
* Run the script and see that the script detects that change.
* Create a patch from those changes and rollback the code
* Run the script and see that the script still sees changes in the repo (even though there aren't any).
* run `git stash` -> "no local changes to save" 
* Run script again and see that indexing occurred under the hood, and now it doesn't detect it as a changed repo.
* Apply patch and run the script again and see it finds the changes in the repo. Ready to close until we find a case that is prohibitively destructive.

**Comment by samreid** [comment]
Sounds good, thanks!  Closing.

**Comment by samreid** [comment]
I'm always getting false positives, so I made it always update the index.  But should we only update the index for repos that detect changes, to identify false positives?

**Comment by samreid** [comment]
I switched to a 2-phase process, where only the repos with changes detected are scanned for false positives.  This speeds things up. I left in console logging to help us understand when this guards us, since it is difficult to trigger this problem reliably.  I tried the instructions above but for some reason it wasn't triggering the false positive.

**Comment by zepumph** [comment]
Ok. I believe that what you are saying is a more nuanced definition of "false positive" in which we look at all stale, un-updated diff-index results, and then update-index on them to ensure they are still correct. 

Isn't this only half of the issue though? Couldn't we also be getting false negatives with this approach, in which diff-index returns no changes, and thus it isn't in the list to update indices, but if it was, it would yield working copy changes?


I understand I removed all indexing, so I'm not trying to call your solution bad/incomplete (as mine was the most incomplete possible). Do I understand things correctly? Do you have reason to believe that my "false negative" definition doesn't actually happen, and we are mostly/only worried about false positives?

**Comment by samreid** [comment]
You are right, I had been focusing on the false positives since they waste time.  False negatives take no time at all so weren't worrying me, but they should be worrisome because they would allow you to commit code without passing tests.  So I removed the guard and just refresh the index every time.  It was fast enough now that we know it is necessary. Please review and close if all is well.

**Comment by zepumph** [comment]
Perfect thanks
