### ISSUE TITLE
Allow sim/phet-io originated creation of internationalizable strings that do not appear in rosetta

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1307]
From https://github.com/phetsims/chipper/issues/1302, @kathy-phet said:

> @samreid @arouinfar Related to the textProperty work that JO is doing, we have a corner case that I think will be important to have a plan for ...
* Situations in which we have a special text field for PhET-iO that isn't in the PhET-brand sim and thus doesn't have a translatable string.
* Example is the Element or Vertex label in CCK
* Proposal would be to have a parallel sort of approach where each of these labels has a dynamicProperty PhET-iO Element name, and then that has some sort of default as well as locale specific values, so if they want the value to be "A" for all locales, they don't have to specify each separately.
* It seems like this would work similarly, to the textProperty discussions we have already been having, but would likely be kept in a special place like: phetioStrings. ...   so they don't get put into the big list of translator generated strings?
* Anyways, Sam, perhaps you can think about this corner case and make sure we have a plan that is consistent and will work when we need it.

**Comment by samreid** [comment]
Also a heads up to @jonathanolson and @zepumph about this request.

**Comment by kathy-phet** [comment]
One thought is that these text properties are added - like the a11y properties are now - to the internationalizable strings, so they have the exact same interface as regular translator strings, but they are flagged in a way that they do not show up in babble - like the a11y strings don't show up there now.

**Comment by zepumph** [comment]
>Example is the Element or Vertex label in CCK

I think it would be helpful to understand this more. Can you point me this in code and or studio?

**Comment by samreid** [comment]
For instance, drag out a resistor, then look for `circuitConstructionKitDc.introScreen.model.circuit.vertexGroup.vertex_0.labelTextProperty` in the studio tree.

**Comment by kathy-phet** [comment]
Yep - its in a phet-io group ... 
![image](https://user-images.githubusercontent.com/5096804/184988817-2d2cece9-27c3-40bf-83f7-5b54cf156e26.png)

**Comment by samreid** [comment]
This patch creates new properties beneath the labelTextProperty:

<details>

```diff

Index: js/model/Vertex.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/model/Vertex.ts b/js/model/Vertex.ts
--- a/js/model/Vertex.ts	(revision 6b3f91c788335d3527a90fb30b05e39f46dd0354)
+++ b/js/model/Vertex.ts	(date 1660691211133)
@@ -11,7 +11,6 @@
 import TEmitter from '../../../axon/js/TEmitter.js';
 import NumberProperty from '../../../axon/js/NumberProperty.js';
 import Property from '../../../axon/js/Property.js';
-import StringProperty from '../../../axon/js/StringProperty.js';
 import Vector2 from '../../../dot/js/Vector2.js';
 import Vector2Property from '../../../dot/js/Vector2Property.js';
 import optionize from '../../../phet-core/js/optionize.js';
@@ -19,6 +18,10 @@
 import Tandem from '../../../tandem/js/Tandem.js';
 import IOType from '../../../tandem/js/types/IOType.js';
 import circuitConstructionKitCommon from '../circuitConstructionKitCommon.js';
+import DynamicProperty from '../../../axon/js/DynamicProperty.js';
+import localeProperty from '../../../joist/js/localeProperty.js';
+import StringIO from '../../../tandem/js/types/StringIO.js';
+import TReadOnlyProperty from '../../../axon/js/TReadOnlyProperty.js';
 
 // Index counter for debugging
 let counter = 0;
@@ -82,7 +85,7 @@
   // for black box study
   public outerWireStub: boolean;
   public isCuttableProperty: BooleanProperty;
-  public labelTextProperty: StringProperty;
+  public labelTextProperty: TReadOnlyProperty<string>;
 
   public static VertexIO: IOType;
 
@@ -147,8 +150,23 @@
       tandem: options.tandem.createTandem( 'isCuttableProperty' )
     } );
 
-    this.labelTextProperty = new StringProperty( '', {
-      tandem: options.tandem.createTandem( 'labelTextProperty' )
+    const labelTextPropertyTandem = options.tandem.createTandem( 'labelTextProperty' );
+    const localePropertiesMap: Record<string, Property<string>> = {};
+
+    Object.keys( phet.chipper.strings ).sort().forEach( locale => {
+      localePropertiesMap[ locale ] = new Property<string>( '', {
+        tandem: labelTextPropertyTandem.createTandem( 'locales' ).createTandem( _.camelCase( locale ) + 'Property' ),
+        phetioValueType: StringIO
+      } );
+    } );
+
+    this.labelTextProperty = new DynamicProperty( localeProperty, {
+      derive: ( locale: string ) => localePropertiesMap[ locale ],
+      bidirectional: true,
+      phetioReadOnly: false,
+      phetioValueType: StringIO,
+      phetioState: false,
+      tandem: labelTextPropertyTandem
     } );
   }
 

```

</details>

It looks like this:

<img width="756" alt="image" src="https://user-images.githubusercontent.com/679486/185001092-4cef91c1-862c-4686-81f6-0ccda9f4c684.png">

This works well in state--customized per-language strings appear correctly in "Preview"
However:

* I had to populate all locales since it appears in an archetype
* This has each string appearing in state--doesn't reuse the state engine in getStringModule
* This does not have a "fallback" other than the empty string.  It does not have a way to say strings fall back to English

I'd like to experiment with backing this in the actual strings, but then would we have linked elements to get there?  This UI works reasonably well.

**Comment by samreid** [comment]
> to the internationalizable strings, so they have the exact same interface as regular translator strings, but they are flagged in a way that they do not show up in babble - like the a11y strings don't show up there now.

What if the english translation was the empty string `''`?  Would translators know that they should translate it as `''`?  Or could we have a heuristic that empty strings do not appear in rosetta?

**Comment by kathy-phet** [comment]
I think we can do what we need on the rosetta side - that seems like a solvable issue since we already solved it for a11y strings. The question I was wondering was does a dynamic property approach (one string - and then lightweight translation strings) work with phet-io group?

**Comment by zepumph** [comment]
OVer in https://github.com/phetsims/chipper/issues/1302, @jonathanolson will prototype changes to our general dynamic strings pattern that should support this nicely. TBD on exact implementation/api to be used here in Vertex, but it will be available soon!

**Comment by zepumph** [comment]
Removing hold. ready for review. I'll assign.

**Comment by zepumph** [comment]
"Most of the work is over in https://github.com/phetsims/chipper/issues/1302"

- A great man named Sam.

**Comment by zepumph** [comment]
Review done in https://github.com/phetsims/chipper/issues/1302#issuecomment-1238718059. Closing
