### ISSUE TITLE
Remove stringModule.get()

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#1309]
Over in #1302 @samreid and I were surprised to find 0 usages of the `get()` function is added to the output of getStringModule. 

It looks like when needed, we are just using array bracket accessor notation (`ratioAndProportionStrings.something['0MyKey']).

**Comment by zepumph** [comment]
Implemented above and all sims were run and passed. @jonathanolson does this seem reasonable to you? @samreid and I like the change and simplification.

**Comment by jonathanolson** [comment]
Added a commit above that removed a `.get(` part of getStringMap related to this.

**Comment by jonathanolson** [comment]
Commit above looks good to me, thanks!
