### ISSUE TITLE
modify Java build tools to generate new format of HTML string files

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#131]
... as reported in https://github.com/phetsims/babel/issues/3#issuecomment-95499258. Assigning to @jonathanolson since reported the invalidness and is therefore familiar with how it was invalid.

**Comment by pixelzoom** [comment]
XMLToProperties likely has the same problem.

Both of these files are in chipper/java/.

**Comment by jonathanolson** [comment]
There were tab chars (0x09) in strings (probably automated, should be fixed how we encode), extra last comma (probably manually caused, just one sim) and missing comma (probably manually caused).

If we're using it for more, I'd make sure that it warns or strips non-space whitespace in string values.

**Comment by pixelzoom** [comment]
Actually... We need to modify PropertiesToJSON and XMLToJSON to generate the new JSON format for our HTML5 string files.   So changing the title of this issue.

**Comment by pixelzoom** [comment]
@samreid suggested that we run the current PropertiesToJSON and XMLToJSON *now* on all Java and Flash sims, and process the output with the script that @jonathanolson wrote.

**Comment by jonathanolson** [comment]
Gists of files to be changed/added, since SVN on my side corrupted itself after Unfuddle failed on PROPFIND requests:
PhetLocales.java: https://gist.github.com/jonathanolson/826e7643db328fe59e59
ExportPhetcommonLocales.java: https://gist.github.com/jonathanolson/e2d2101dfe3fc3dafee9
JavaScriptUtils.java: https://gist.github.com/jonathanolson/ebb7612575534ffc86cd
PropertiesToRequireJSI18n.java: https://gist.github.com/jonathanolson/5d4392b0b23873224c41

Only enough changes to PropertiesToRequireJSI18n.java so it works.

Hopefully I'll get SVN back up soon, and will get these committed.

**Comment by pixelzoom** [comment]
@jonathanolson wrote:
> Hopefully I'll get SVN back up soon, and will get these committed.

Why do they need to be committed to SVN? I thought that all relevant Java tools had been moved to chipper/java/.

**Comment by jonathanolson** [comment]
I was unaware of that, particularly since they are still checked into SVN.

**Comment by jonathanolson** [comment]
(Still assigned to me, I'll fix when I handle something similar in chipper again).

**Comment by pixelzoom** [comment]
I don't know of any reason why they shouldn't be deleted from SVN.  You might ask @samreid if there's any reason why he didn't delete them from SVN after he migrated them to GitHub.

**Comment by jonathanolson** [comment]
Not moving through strings from Java, closing.

**Comment by pixelzoom** [comment]
Reopening, see https://github.com/phetsims/chipper/issues/132#issuecomment-157450388. We are porting Java strings, but stripping out any with HTML markup.

**Comment by pixelzoom** [comment]
Since we're stripping out, not reformatting, HTML strings, I'll move that requirement to #132.  Then this issue is ok to close.

**Comment by pixelzoom** [comment]
Ah, perhaps I misunderstood the intent of this issue. Looks like there are some HTML *encoding* issues. Reopening to understand this better.

**Comment by samreid** [comment]
Since I'm working on #132 perhaps I should look at this issue as well.

**Comment by pixelzoom** [comment]
This issue should probably be merged into #132.

**Comment by samreid** [comment]
It would be good to discuss the @jonathanolson gists above and make sure there are no corner cases that aren't handled in #132.  I'll tag for developer-meeting in case we don't discuss it beforehand.

**Comment by samreid** [comment]
In #132 we decided to port all strings as a batch.  I don't want to proceed until discussing @jonathanolson's gists above.  I can see what all of the files are doing, but I cannot figure out why they are doing it or if it is important for our batch conversion.  Reassigning to @jonathanolson for discussion.

**Comment by samreid** [comment]
After discussion with @jonathanolson:

1. Check in the gists to subversion
2. Determine where to place the output
3. That should allow us to run conversions on each svn simulation/common code directory
4. Test that the output is compatible

**Comment by samreid** [comment]
I committed the gists above in SVN 74479

**Comment by samreid** [comment]
Using the Java utility to convert strings, I'm seeing things like extra whitespace:

![image](https://cloud.githubusercontent.com/assets/679486/12214026/bf4eb23c-b642-11e5-8fb0-495a49960520.png)

**Comment by samreid** [comment]
I'm wondering if this would be simpler if we loaded strings in Node and used JSON.stringify()..

**Comment by samreid** [comment]
Maybe we should do both and compare results?

**Comment by samreid** [comment]
Do the strings in babel have to have a history array?

**Comment by samreid** [comment]
According to commitQueue.js:

```js
        if ( history ) {
          history.push( newHistoryEntry );
        }
        else {
          history = [ newHistoryEntry ];
        }
        repos[ repo ][ key ] = {
          value: stringValue,
          history: history
        };
```

So it seems undefined history is OK.

**Comment by samreid** [comment]
After 1st pass of converting files from Java (using Java), I'm seeing 11.3MB for for 3,258 items.  Will babel be OK with this?  Anyone with babel knowledge please chime in.  @jbphet @pixelzoom or @jonathanolson is that you?

**Comment by samreid** [comment]
Should I keep translation.credits?  I'm thinking not but it would be difficult to add back in if I toss it out now.

**Comment by samreid** [comment]
Comparing my results with acid-base-solutions pre-existing string seems like things are matching up nicely so far.  There was one removed string, the mismatch between acid-base-solutions.title and acid-base-solutions.name and the credits.

**Comment by samreid** [comment]
My plan is to port all strings, then we can delete ones that already exist (if desired).

**Comment by samreid** [comment]
I'm using the "check for a less than sign" rule for detecting html fragments that @pixelzoom suggested:

```js
                // skip anything that seems like it might have HTML
                if ( !p.get(k).toString().contains( "<" ) ) {
                    reducedKeySet.add( k );
                }
```

**Comment by samreid** [comment]
To test whether the ported structure would load properly, I copied the autoported acid-base-solution "bs" locale to the acid-base-solution folder.  I'm using this sim for testing since its keys seem pretty similar to the Java version.  Then I launched with ?locale=bs.  The sim launched nicely and I could see the translated strings.

I can't think of any other good tests to do before committing, so I'll commit shortly.

**Comment by samreid** [comment]
I strolled through the files for another manual spot check and didn't see anything suspicious, so here comes a big commit.

**Comment by samreid** [comment]
Also, hopefully the presence of an "autoport" directory in babel won't mess anything up.  Will it look like there is an "autoport" sim in the rosetta gui?  I am really unfamiliar with rosetta.

**Comment by samreid** [comment]
According to the docs, rosetta "sends a request to get the active-sims list from chipper", so perhaps it is OK to have an extra directory in there?  Let's look closer.

**Comment by samreid** [comment]
Apparently the sim selector draws data from this file:
rosetta/data/simInfoArray.json

So having an extra directory should be fine (unless somehow rosetta checks babel directories to try to populate that file, but it seems unlikely.  It looks like rosetta only reads this file).

**Comment by samreid** [comment]
Committed above.  @pixelzoom @jonathanolson @jessegreenberg @jbphet @mattpen @ariel-phet please keep your eyes peeled for any babel problems that may result from this.  Next I'll look at XML.

**Comment by samreid** [comment]
Also, to finish up here, we should remove the grunt "port strings" task and its dependencies.

**Comment by samreid** [comment]
I converted the XML strings using the pre-existing Java code and iterating over simulations-flash and simulations-flex.  I inspected the strings and didn't see any problems.  I tried running the Arabic strings for wave-on-a-string since the keys were a close match and it looked like it loaded and rendered properly.  I'll commit shortly.

**Comment by samreid** [comment]
Since I did the Java strings there have been 2 submissions to babel, so it seems like things aren't broken:

![image](https://cloud.githubusercontent.com/assets/679486/12214512/ccc20944-b653-11e5-9eed-e2f11ae69aef.png)

Committed flash/flex strings above.

**Comment by samreid** [comment]
Removed grunt task "port-java-strings" above.

**Comment by samreid** [comment]
It looks like the process missed simulations-flash/common/data/localization, looking into it....

**Comment by samreid** [comment]
I'm no longer sure it is safe to commit to babel, so I should probably wait to hear about https://github.com/phetsims/babel/issues/7 before proceeding.  Marking for developer-meeting (as babel#7 is marked).

**Comment by samreid** [comment]
Also @jonathanolson pointed out that if the flash/flex common strings are the only ones missing then we may not need to port them since we have a different strategy in HTML5.  However, I still want to find out why this directory was missed in case others are missing as well.

**Comment by samreid** [comment]
> I'm no longer sure it is safe to commit to babel

Two thoughts from this:
1. We will need to be able to make commits on babel when we port strings into the correct directories
2. We could put the automatically "batch" ported strings in a separate repo if necessary (though they are already in babel/autoport).

**Comment by jbphet** [comment]
During the 1/12/2016 dev meeting we decide to go ahead and get rid of the scripts, since all porting is done.  The worst case consequence (that we can think of) is that translators would just start from scratch, which would be no big deal.  @samreid will do this, in both SVN and Git.

**Comment by samreid** [comment]
@jbphet also volunteered to take some 5+ minutes and review the ported strings.

**Comment by jbphet** [comment]
I just looked at the ported strings and didn't see any obvious problems.  I spot checked several files, and the structure looks correct.  I only spent a few minutes on it but from what I can tell they look fine.

**Comment by samreid** [comment]
I added logs to the process and verified that sims were being visited properly even though common xml wasn't.  I think we aren't porting the common strings, since the common stings for joist are very different anyways, so I think everything's done here.
