### ISSUE TITLE
String Property suffix convention

### ISSUE THREAD

**Issue by marlitas** [phetsims/chipper#1310]
While investigating https://github.com/phetsims/mean-share-and-balance/issues/99, @samreid and I noticed that `meanShareAndBalanceStrings.numberOfCupsProperty` was a bit confusing. 

At first glance `numberOfCupsProperty` appears to be a number property, but is actually a string property. We are not sure if calling it from `meanShareAndBalanceStrings` is clear enough while glancing through code that it is in fact a string property. 

- Should the suffix convention for string properties be: `numberOfCupsStringProperty`? 

In addition we noticed that `getStringModule` adds a "StringProperty" suffix for PhET-iO studio. 
```currentTandemName = `${tandemName}${j === 1 ? '' : j}StringProperty`;```

It seems like a consistent convention would be to follow this practice with string properties in code as well.

**Comment by zepumph** [comment]
Totally fine with me! Let's do it.

**Comment by samreid** [comment]
Do we want to go one step further and change the strings to have a `String` suffix?  So instead of:

`gravityAndOrbitsStrings.age` it would be `gravityAndOrbitsStrings.ageString`?  But to me that feels unnecessary.  So now I'm wondering why we would suffix `Property<string>` but not `string`?  Maybe more important for `Property<string>` because:

```ts
const ageProperty = gravityAndOrbitsStrings.ageProperty;

// many lines later...
// feels like it should be a {number}, but it's a {string}.  But that's why we have TypeScript, right?
// But ageStringProperty sounds pretty nice.
ageProperty.value 
```

**Comment by samreid** [comment]
At today's dev meeting:

@jonathanolson says we are already getting it from a strings object, so it doesn't need the `String` suffix.
@samreid: But it's difficult to search for the actual `numberOfCupsProperty` where it is really the number.
@pixelzoom: If it was a parameter, I would name it `numberOfCupsStringProperty`.
@jonathanolson: But do we need the verbosity?
@pixelzoom: We do not need to rename the string ones.  Very little value in doing that.  I'm OK either way with the Property ones.
@chrisklus I'm leaning toward the `StringProperty`.
@kathy-phet: Me too, I prefer `StringProperty`.
@liammulh: I recommend leaning towards more verbose.

So our consensus is to add `StringProperty` suffix for the strings.

@AgustinVallejo volunteered to work on this. The sims are:

- [ ] gravity and orbits
- [ ] molecule shapes
- [ ] friction
- [ ] my solar system
- [ ] density
- [ ] buoyancy
- [ ] mean-share-and-balance
- [ ] molecule-shapes-basics
- [ ] There may be common code repos like joist, sun, scenery-phet, etc.
- [ ] Search for the regex like `Strings.*Property`
- [ ] `grunt update` will change the strings types file. (it runs grunt modulify automatically). @jonathanolson will show how to for-each all sims.
- [ ] the code in `getStringModule` and `getStringMap` will be the part that changes it.

Thanks @AgustinVallejo!
