### ISSUE TITLE
'Y' in general.strings.joist.a11Y looks like a typo

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#1311]
While looking through Studio tree and inspecting API changes created by `grunt generate-phet-io-api`, I noticed phetioIDs that contain `general.strings.joist.a11Y`.   Note the capital 'Y' in `a11Y'.  That sure looks like a typo.  But's it's likely the result of this line in getStringModule.ts

> 157     let tandemName = _.camelCase( keyParts[ i ] );

While `a11Y` is argueably correct camel casing, is it OK?

**Comment by pixelzoom** [comment]
Slack:

[Michael Kauzmann](https://app.slack.com/team/U6DFWDG1Z)
:house_with_garden:  [1 minute ago](https://phetsims.slack.com/archives/C6HPE0J91/p1661531695771779?thread_ts=1661530725.024389&cid=C6HPE0J91)
My first preference would be to leave it. Otherwise can we just hard code lowercase a11y as an exception to lodash camelcase?





[Chris Malley](https://app.slack.com/team/U6EMFARV2)
  [< 1 minute ago](https://phetsims.slack.com/archives/C6HPE0J91/p1661531764691189?thread_ts=1661530725.024389&cid=C6HPE0J91)
Might be a question for PhET-iO designers, since it’s public-facing.

**Comment by zepumph** [comment]
@samreid and I decided that it was OK after discussion last week in #1302. It is camel case, technically. 

Let's just change it.

**Comment by zepumph** [comment]
Hows that?

**Comment by kathy-phet** [comment]
Thank you for fixing it. :)

**Comment by pixelzoom** [comment]
👍🏻 closing
