### ISSUE TITLE
Make `// eslint-disable-line` bad text when no rule is provided

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#1313]
@samreid and I just found 2 cases where an `//eslint-disable-line` was hiding a real problem in the code. Can we prevent this from creating more technical debt?

Problems:

Should have a return type but was being hidden:
https://github.com/phetsims/axon/blob/56a3d733eb7cd1dbba328f7d6e8796d3b4623e2f/js/TinyProperty.ts#L171

Should not return any:
https://github.com/phetsims/axon/blob/6ad1413c68e5b46de464144952ce4ae3571980e4/js/TReadOnlyProperty.ts#L22

**Comment by samreid** [comment]
I fixed the easy part.

**Comment by samreid** [comment]
I'll be deleting `unlinkAttribute` next.

**Comment by samreid** [comment]
Fixed, closing.

**Comment by zepumph** [comment]
This issue was meant to be a place to discuss a general rule that we shouldn't be able to have `// eslint-disable-line` allowed, and that instead we should have to specify the exact rules that are disabled. There are currently 300 usages of `eslint-disable-line$` and 0 usages of `eslint-disable-next-line$`. I would recommend removing or adding the specific lint rule to all of them, and I bet that we will find a fair number of places where we were hiding failures accidentally.

**Comment by jonathanolson** [comment]
Dev meeting: this sounds valuable, initial work should proceed to see if it needs to be a chip-away issue.

**Comment by samreid** [comment]
For a process, I would recommend using a regex to detect all `// eslint-disable-line` that ends there (maybe it is a `$`), query-replace them all with the empty string.  Run lint-everything in WebStorm popup window so you can tap on links to visit each case, then add-back the line with the specific rule that is failing there.

**Comment by marlitas** [comment]
Patch for unicorn plugin that will provide the functionality to flag `// eslint-disable-line` with no rule specified.

<details>

```diff
Index: package.json
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/package.json b/package.json
--- a/package.json	(revision 423da391da1a60017069f8e28e6e6c67ab55d017)
+++ b/package.json	(date 1663691765275)
@@ -31,6 +31,7 @@
     "@babel/eslint-parser": "7.18.2",
     "docdash": "^1.2.0",
     "eslint": "8.19.0",
+    "eslint-plugin-unicorn": "43.0.2",
     "eslint-plugin-react": "7.30.1",
     "grunt": "~1.5.3",
     "html-webpack-plugin": "^5.3.2",
Index: eslint/.eslintrc.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/eslint/.eslintrc.js b/eslint/.eslintrc.js
--- a/eslint/.eslintrc.js	(revision 423da391da1a60017069f8e28e6e6c67ab55d017)
+++ b/eslint/.eslintrc.js	(date 1663692109425)
@@ -534,6 +534,11 @@
       }
     }
   ],
+  plugins: [
+    'unicorn'
+  ],
+
+  reportUnusedDisableDirectives: true,
 
   // The rules are organized like they are in the list at https://eslint.org/docs/rules/
   // First by type, then alphabetically within type
@@ -1415,6 +1420,14 @@
     // Require or disallow spacing around the `*` in `yield*` expressions
     'yield-star-spacing': 'error',
 
+    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
+    // Unicorn Rules
+    //
+
+    'unicorn/no-abusive-eslint-disable': 'error',
+
+    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
+
     ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
     // Custom Rules
     //
```
</details>

**Comment by marlitas** [comment]
I attempted to implement this unicorn no-abusive-eslint-disable rule, but unfortunately it applies to  `eslint-disable` for a full file on top of `eslint-disable-line` and `eslint-disable-next-line`. This implicated many sound and mip-map files where providing specific lint rule comments begins to get out of hand (over 1,000 errors reported). I think the next step is to look at making this a bad text rule as originally suggested.

**Comment by samreid** [comment]
Adding a bad-text entry sounds great, bad-text supports regular expressions and we have a working regex for that.  And we can avoid bringing in a package.json dependency.

**Comment by samreid** [comment]
I have a hypothesis that explains all of the bad-text.js problems we saw today.  We tried to catch lines that have // eslint-disable-line without an explanation, but the problem was that linting was disabled for those lines. That’s also why our rule caught `// eslint-disableline` with one hyphen, because lint wasn’t disabled.

**Comment by samreid** [comment]
OK I added a new option `lineNumberDelta` so the error can be reported on a different line.  That prevents the ignore from ignoring the bad-text.  It seems to be working OK, and I added text to the remaining eslist-disable-lines.  I think this issue can be closed, but perhaps a spot check from @marlitas would be good.

**Comment by marlitas** [comment]
@samreid I'm not sure what the `???` in [eslint/rules/require-statement-match.js](https://github.com/phetsims/chipper/commit/0392937fe2e0129ef0a9d5921cdc38e1e7122228#diff-58eb2baf9ab123b9e849f28924bb0c9ba98af12f1eff562fc30e1e54f580911f) means. Can that be deleted since it's all commented out?

I'm added a rule for `eslint-disable-next-line` as well.

**Comment by samreid** [comment]
I removed that extra eslint-disable-line in the comment, and reviewed the behavior of `eslint-disable-next-line`. Everything seems good. So I think this issue can be closed. Please reopen if there's more to do.
