### ISSUE TITLE
`naturalSelectionStrings.*Property.value` is a build error

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#1314]
In https://github.com/phetsims/natural-selection/issues/319, I had to undo a whole bunch of work in Natural Selection, because calling `naturalSelectionStrings.addMutationsProperty.value` (for example) is a build error. All Properties in *Strings.ts are of type `TReadOnlyProperty<string>`, which includes get and get value() in its API.  Why this is an error? Why is it not flagged until build?!?  Aren't we trying to eliminate `string` instances from *Strings.ts eventually?

Also note that getting the value of a StringProperty indirectly, like in this example, is NOT a build error:

```typescript
class Foo {
 constructor( stringProperty: TReadOnlyProperty<string> ) {
   console.log( stringProperty.value );
 }
}
new Foo( naturalSelectionStrings.addMutationsProperty );
```

The build error is:

> Fatal error: Perennial task failed:
Error: no value for string: addMutations.value
    at Object.getStringFromMap (/Users/cmalley/PhET/GitHub/chipper/js/common/ChipperStringUtils.js:148:15)

.. and occurs in getStringMap.js. Assigning to the author @jonathanolson.

High priority because for https://github.com/phetsims/natural-selection/issues/319.

**Comment by samreid** [comment]
It thinks “value” is a nested string key.  The workaround is to put `const m = naturalSelectionString.addMutationsProperty` on a separate line, then you can link to `m`.  Someone at dev meeting proposed a long term fix, I think it’s assigned to 
@jonathanolson.

**Comment by pixelzoom** [comment]
Thanks. I’ll wait for the longterm fix.

**Comment by samreid** [comment]
The general problem is described in https://github.com/phetsims/mean-share-and-balance/issues/99, assigned to @jonathanolson

**Comment by pixelzoom** [comment]
My workaround in natural-selection ProportionsBarNode.js:

```js
//TODO https://github.com/phetsims/chipper/issues/1314 using these Properties inline causes a build error
const greaterThanValuePercentProperty = naturalSelectionStrings.greaterThanValuePercentStringProperty;
const lessThanValuePercentProperty = naturalSelectionStrings.lessThanValuePercentStringProperty;
const valuePercentProperty = naturalSelectionStrings.valuePercentStringProperty;
```

**Comment by jonathanolson** [comment]
Should be fixed above for common usages. @pixelzoom can you verify?

Also, I'd like to note that there are some degenerate examples that the current method will fail on, notably:

```js
        // - joistStrings.someStringProperty[ 0 ]
        // - joistStrings.something[ 0 ]
        // - joistStrings.something[ 'length' ]
```

We'd need to remove our "error on something that looks like a string but isn't found" since there's no good way to filter these out (without looking for array indices, any method/property that can be on a string, etc.)

Tagging for dev meeting to see if this is acceptable (with a PSA).

**Comment by pixelzoom** [comment]
👍🏻 Confirmed by doing a build of natural-selection with things like `naturalSelectionStrings.valuePercentStringProperty.value` in the code. Closing.
