### ISSUE TITLE
Make it easier to switch locales during development or QA testing

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1316]
During https://github.com/phetsims/circuit-construction-kit-dc/issues/199 and related to https://github.com/phetsims/natural-selection/issues/319#issuecomment-1226082140 and https://github.com/phetsims/chipper/issues/1302, during development we would like a better way to switch languages to test.  It is difficult to show the preferences dialog to switch, or to run with studio to find the localeProperty in the tree.  

Instead, let's add a query parameter that adds a keyboard shortcut to cycle through languages.  I have a nice prototype I'll commit momentarily.

Notifying @pixelzoom and @zepumph and @jonathanolson since they have been working in this area.

**Comment by samreid** [comment]
Implemented in the commits.  The docs for `?stringTest` say:

```
keyboardShortcutLocaleSwitcher: adds keyboard shortcuts. ctrl+i (forward) or ctrl+u (backward). Also,
  same physical keys on the dvorak keyboard (c=forward and g=backwards)
```

@pixelzoom can you please review?
* Please test the functionality
* Review the commits
* Do you think this should be under `?stringTest` query parameters, or a separate key?

**Comment by pixelzoom** [comment]
> * Please test the functionality

This is very nice.  I especially like that I can run with a couple of locale, like `?stringTest= keyboardShortcutLocaleSwitcher&locales=en,ar,de`, and cycle through them.

> * Review the commits

I don't see any problems.

> * Do you think this should be under ?stringTest query parameters, or a separate key?
> * If we stick with ?stringTest, do you think keyboardShortcutLocaleSwitcher is the appropriate value?

I think I'd rather have a flag that's separate from `stringTest`, and certainly a shorter name.  Maybe `?localeSwitcher` ?

**Comment by samreid** [comment]
> I think I'd rather have a flag that's separate from `stringTest`, and certainly a shorter name.  Maybe `?localeSwitcher` ?

I moved it out of `?stringTest`, but after prototyping with `?localeSwitcher` I changed it to `?localeKeyboardSwitcher` in case we want `localeSwitcher` to mean something else (like automatic locale switching?) in the future.

Back to @pixelzoom, please close if all is well.

**Comment by pixelzoom** [comment]
Looking good.

Yes, ...

- [ ] PSA to dev team
- [ ] add `localeKeyboardSwitcher` to phetmarks

I also keep forgetting to run with `locales=*` or some subset of locales. I guess I'll get used to adding that, and when I see "en" printed to the console repeatedly it reminds me :)

**Comment by samreid** [comment]
I added it to phetmarks and it looks like so:

<img width="465" alt="image" src="https://user-images.githubusercontent.com/679486/187353832-a972cce0-c6f0-454e-b6be-008420c439c0.png">

I'll label for Status meeting PSA, since it seems good for QA and other team members to be aware of as well.

**Comment by pixelzoom** [comment]
How about also adding this to phetmarks for 'studio' mode? I'm doing most of my work in Studio these days, and it would be nice not to have to manually add the query parameters, or resort to changing `localeProperty` in Studio.

**Comment by samreid** [comment]
In the commits, we renamed the query string and pass it through to all phet-io wrappers.

However, not all phet-io wrappers forward their key events to sims (including studio), so this doesn't work at the moment.  I tried:

```diff
Index: js/studio-main.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/studio-main.ts b/js/studio-main.ts
--- a/js/studio-main.ts	(revision 4bcb311e0d032d6be28a6b3ba30e6b49a3918c4c)
+++ b/js/studio-main.ts	(date 1661878825971)
@@ -89,6 +89,7 @@
    */
   phetioClient.launchSim( {
     passThroughQueryParameters: true,
+    forwardZoomKeyboardEventsToSim: true,
     queryString: 'phetioEmitAPIBaseline&phetioCreateArchetypes&phetioEmitHighFrequencyEvents=false&phetioEmitStates=true&phetioEmitStatesInterval=60',
 
     onPhetioInitialized: function( phetioEngineElements: PhetioElementCreatedData[] ) {
```

But then you cannot use ctrl +/- to zoom in and out on the studio frame.  @zepumph and/or @jessegreenberg can you please advise?

**Comment by samreid** [comment]
@zepumph said we can forward the key commands if the query parameter is on.  See keyboardEventForwarding.

**Comment by zepumph** [comment]
For the exact same code snippet decontextualized, see https://stackoverflow.com/questions/45457271/forward-a-keydown-event-from-the-parent-window-to-an-iframe-that-contains-reveal

**Comment by zepumph** [comment]
Assigning to myself because I see some trouble in global event listeners.

**Comment by zepumph** [comment]
Ok. Committed above. In general I think it is nicer to have a single place where all global keyboard listeners are added (globalKeyStateTracker). This feels a bit more prudent to me.

**Comment by samreid** [comment]
Thanks, it seems like it is working well.  I also added an adapter that initializes it in phet-io wrappers when you have `keyboardLocaleSwitcher` set.  It works in studio and screenshot wrapper, but not the state wrapper because it doesn't use launchSim.  @zepumph can you please review?

**Comment by zepumph** [comment]
I believe I got everything set. It works in the state wrapper now, and could work in multi, or the unsupported mirror inputs and input-record-and-playback if we just added that function. Doesn't matter too much to me. Please review and fee free to close.

**Comment by zepumph** [comment]
ctrl + shift + i is a very important shortcut for me (to open the dev tools) in chrome. So I made sure that we didn't have any other modifier keys presetn in addition to having ctrl.

**Comment by samreid** [comment]
The changes look great, thanks!  Closing.
