### ISSUE TITLE
main.js vs {{repo}}-main.js

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#1321]
Noted while fixing a bug in axon's main.js.

The PhET naming convention is {{repo}}-main.js.  Why do axon, dot, kit, phetcommon, and scenery all have files named main.js? 

Assigning to the creators of the main.js files.

**Comment by jonathanolson** [comment]
Because they're used to include files in standalone builds, or for the things like the playgrounds.

e.g. because scenery/js/filters/GaussianBlur is mentioned from its main file, it will show up in the `grunt` build of scenery.

**Comment by samreid** [comment]
The main files such as axon/main.js seem well-documented

```ts
/**
 * Module that includes all axon dependencies, so that requiring this module will return an object
 * that consists of the entire exported 'axon' namespace API.
 *
 * @author Jonathan Olson <jonathan.olson@colorado.edu>
 */
```

I do not feel it has to follow the same policy of the main nomenclature for a runnable repo, since it is a different kid of entry point. (Not a runnable sim).

**Comment by pixelzoom** [comment]
👍🏻 closing
