### ISSUE TITLE
ESLint cache not invalidated when tsconfig or plugins change

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1326]
We saw this on CTQ

```
lint: /data/share/phet/continuous-quick-server/beers-law-lab/js/concentration/model/Precipitate.ts  0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
lint: /data/share/phet/continuous-quick-server/beers-law-lab/js/concentration/model/Precipitate.tsThe file does not match your project config: ../beers-law-lab/js/concentration/model/Precipitate.ts.
```

@zepumph and I traced the problem to the fact that tsconfig changes not invalidating the eslint built-in cache.  That is, after tsconfig changes, ESLint doesn't know so it recalls its last error list instead of re-running linting.

@zepumph and I agreed to include the tsconfig into the cache name, so that changes to the tsconfig will invalidate the cache.  I'm also throwing in the contents of package.json so that plugin changes will also invalidate caches, since that was described on https://eslint.org/docs/latest/developer-guide/nodejs-api

This introduces a memory leak--the cache directory has no self-cleaning capability so will continue growing (slowly) over time.

**Comment by samreid** [comment]
Fixed in the commit, @zepumph would you like to review?

**Comment by zepumph** [comment]
It is excellent! Thanks for doing this.
