### ISSUE TITLE
Adding reportUnusedDisableDirectives to eslint

### ISSUE THREAD

**Issue by marlitas** [phetsims/chipper#1331]
@samreid and I would like to add `reportUnusedDisableDirectives` to chipper eslint. This has an auto-fix and will implement changes across all repos that have a `// eslint-disable-line` that is not needed. The auto-fix will delete all usages. 

The documentation can be found here: https://eslint.org/docs/latest/user-guide/configuring/rules#report-unused-eslint-disable-comments

@samreid came across this configuration while researching https://github.com/phetsims/chipper/issues/1313

We think this would be a very useful directive to implement, with little overhead

**Comment by marlitas** [comment]
I attempted to apply this directive by using `grunt lint-everything --fix --disable-cache`. This did indeed remove many instances of `// eslint-disable-line`, but not all of them were unused. 

For example, in the below code snippet it reports `// eslint-disable-line bad-sim-text` as unused, however when that disable is removed eslint flags the line for `bad-sim-text`

```ts
 setTimeout( () => { // eslint-disable-line bad-sim-text

        // Run in the next frame after the object finished getting constructed
        const stateObject = phetioType.toStateObject( instance );
        assert.equal( stateObject.value, propertyValue, 'toStateObject should match' );
        assert.deepEqual( stateObject.validValues, validValues, 'toStateObject should match' );
        done();
      }, 0 );
```

I am holding off on further changes and implementation until this can be researched and discussed further.

**Comment by samreid** [comment]
> --disable-cache

For reference, the disable cache option is `--disable-eslint-cache`.  But that may not have affected the results here.  I'll take a closer look.

**Comment by samreid** [comment]
This seems like a good issue for collaboration.

**Comment by marlitas** [comment]
This is what is causing the interference: https://github.com/phetsims/chipper/issues/1224#issuecomment-1121456413

**Comment by marlitas** [comment]
Patch:
<details>

```diff
Index: eslint/rules/getBadTextTester.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/eslint/rules/getBadTextTester.js b/eslint/rules/getBadTextTester.js
--- a/eslint/rules/getBadTextTester.js	(revision 6f702873386080f7177c3d4f2bd5840f1730f15f)
+++ b/eslint/rules/getBadTextTester.js	(date 1666108602627)
@@ -27,7 +27,7 @@
     const codeLines = sourceCode.lines;
     const text = sourceCode.text;
 
-    const lineDisabledDirectiveRegex = new RegExp( `eslint-disable-line *${ruleName}` );
+    // const lineDisabledDirectiveRegex = new RegExp( `eslint-disable-line *${ruleName}` );
 
     /**
      * @param {number} lineNumber
@@ -69,9 +69,9 @@
             const lineString = codeLines[ i ];
 
             // Opt out of lines that have something like "eslint-disable-line bad-text"
-            if ( lineDisabledDirectiveRegex.test( lineString ) ) {
-              continue;
-            }
+            // if ( lineDisabledDirectiveRegex.test( lineString ) ) {
+            //   continue;
+            // }
 
             // lines are 1 based, codeLines array is 0 based
             const badLineNumber = i + 1;
@@ -79,7 +79,8 @@
             // only test regex if provided
             if ( forbiddenText.regex ) {
               if ( forbiddenText.regex.test( lineString ) ) {
-                reportBadText( badLineNumber, 0, forbiddenText.id );
+                // TODO: Let's double check this
+                reportBadText( badLineNumber, 0, lineString );
               }
             }
             else if ( forbiddenText.predicate ) {
Index: eslint/.eslintrc.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/eslint/.eslintrc.js b/eslint/.eslintrc.js
--- a/eslint/.eslintrc.js	(revision 6f702873386080f7177c3d4f2bd5840f1730f15f)
+++ b/eslint/.eslintrc.js	(date 1666106429334)
@@ -538,6 +538,8 @@
     }
   ],
 
+  reportUnusedDisableDirectives: true,
+
   // The rules are organized like they are in the list at https://eslint.org/docs/rules/
   // First by type, then alphabetically within type
   // Explicitly list all rules so it is easy to see what's here and to keep organized
```

</details>

**Comment by marlitas** [comment]
Completed in the above commits. @samreid would you like to review and close if all looks good?

**Comment by pixelzoom** [comment]
After reading the reference, I’m not clear on what `reportUnusedDisableDirectives` does. After reading this chipper issue, I’m not clear on the motivation for enabling it, or why/when it is valuable to PhET.  Can you please clarify?

**Comment by pixelzoom** [comment]
In Slack#dev-public, @samreid replied:

> It tells you if you have an eslint disable directive that is unnecessary.  For example, in https://github.com/phetsims/scenery-phet/commit/523d872ba90a883b4de5a3cf8b825d8314564acd we corrected an `// eslint-disable-line` that was doing nothing.  It’s important to remove those since they could mask future problems.  Like if the line changed to `new Display( rootNode, time.toFixed() )` .

**Comment by pixelzoom** [comment]
In Slack#dev-public, I was confused about why `no-simple-type-checking-assertions` was removed in some cases, like https://github.com/phetsims/scenery-phet/commit/523d872ba90a883b4de5a3cf8b825d8314564acd, but still necessary in other cases, like equality-explorer ConstantTermCreator.ts.  @samreid replied:

> I tracked this to a bug in this regular expression that we should correct: https://github.com/phetsims/chipper/blob/4af2cc828aff6451483bbdad72b167458502f081/eslint/rules/no-simple-type-checking-assertions.js#L24

... and:
> After we fix that regex, we will need to resurrect some of the disable directives that were removed (like the one you identified).

**Comment by samreid** [comment]
Let's deal with the regex problem in the side issue https://github.com/phetsims/chipper/issues/1344

**Comment by samreid** [comment]
#1344 was fixed, @marlitas and I spot checked the functionality.  Closing.  @pixelzoom please reopen or create a side issue if there are more questions or problems.
