### ISSUE TITLE
Build Error: unsupported locale: zh_HK 

### ISSUE THREAD

**Issue by mattpen** [phetsims/chipper#1337]
Some sims will need to be patched to add the zh_HK locale as it is currently missing.  This is affecting translations for all locales, as the _all.html file cannot be created.  Known sims that are affected include arithmetic, color-vision, and acid-base-solutions.

<details>

<summary>Error Details</summary>

```
Build failure: Error: Build aborted, Error: grunt build-for-server --brand=phet --locales=zh_HK --allHTML in ../color-vision failed with exit code 3
stdout:
 [4mRunning "eslint:allFiles" (eslint) task [24m


 [4mRunning "clean" task [24m

 [4mRunning "requirejs:build" (requirejs) task [24m
 [32m>>  [39mRequireJS optimizer finished

 [4m/data/share/phet/build-server/color-vision/build/color-vision.min.js [24m
Uncompressed size:  [32m2207793 [39m bytes.
Compressed size:  [32m651575 [39m bytes gzipped. ( [32m1369632 [39m bytes minified)

 [4mRunning "after-requirejs-build" task [24m
 [31mFatal error: unsupported locale: zh_HK  [39m

stderr:
(node:1688665) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
. Sim = color-vision Version = 1.1.26 Brands = phet Locales = zh_HK Shas = {"comment":"# color-vision 1.1.26 Wed Sep 21 2022 11:34:53 GMT-0600 (Mountain Daylight Time)","assert":{"sha":"7d27130a4d27da15aa7f8a21bbfb9245288c1b44","branch":"HEAD"},"axon":{"sha":"60213ff7028991c5be284cf5f1d436739fe87f97","branch":"HEAD"},"brand":{"sha":"312f1245ba26c6835f86f3af0119acab4d2c6573","branch":"HEAD"},"chipper":{"sha":"7d1f51c35439be708ce63a0c5c9024879c619798","branch":"HEAD"},"color-vision":{"sha":"e77647ddd9cadbc0327c673d1ce4aeff51d8c4a4","branch":"HEAD"},"dot":{"sha":"da78031b6f080d20bc8346beaa1d37148188371e","branch":"HEAD"},"joist":{"sha":"24215085639831eafa5fd641760a097010bf333c","branch":"HEAD"},"kite":{"sha":"10ca8bf2b2712307ff528352de8451c0c8afe093","branch":"HEAD"},"phet-core":{"sha":"8cbb9e42c086bee93fd4e9e0f727455f920dc64f","branch":"HEAD"},"phetcommon":{"sha":"72e873e159c952f6114fe7f4c71e386c8a3e6870","branch":"HEAD"},"phetmarks":{"sha":"3fdfece0fe0262594bb06856833b8b16be25deb8","branch":"HEAD"},"scenery":{"sha":"7f82d8f1c65f6f852c8dcc2e1b75b378e09f7d7e","branch":"HEAD"},"scenery-phet":{"sha":"71937eb4ba428f1a5529b1757caa248fafd93213","branch":"HEAD"},"sherpa":{"sha":"f5043f7d9adaad7b1c2e620a096a8e5bc09a4ef8","branch":"HEAD"},"sun":{"sha":"2f236352156037a4eec24680a709a4f6b50ea18e","branch":"HEAD"},"tandem":{"sha":"d0be78ddaf3bbbba746ecd7a4bf891fef99fc7ee","branch":"HEAD"}}
```

**Comment by samreid** [comment]
@mattpen and I are collaborating.  So far we have:

```
Maintenance.reset()
Maintenance.createPatch( 'chipper', 'https://github.com/phetsims/chipper/issues/1337', 'add-zh_HK' )
Maintenance.addNeededPatchesBefore('add-zh_HK','6b35401792319dde05c4eb785f4ae9acba9daeca')
```

Here are the branches identified here:

```
acid-base-solutions 1.2
arithmetic 1.0
color-vision 1.1
hookes-law 1.0
trig-tour 1.0
```

**Comment by samreid** [comment]
Release Candidate links


acid-base-solutions 1.2 (https://github.com/phetsims/chipper/issues/1337)

- [ ] [acid-base-solutions 1.2.27-rc.1](https://phet-dev.colorado.edu/html/acid-base-solutions/1.2.27-rc.1/acid-base-solutions_en.html)

arithmetic 1.0 (https://github.com/phetsims/chipper/issues/1337)

- [ ] [arithmetic 1.0.27-rc.1](https://phet-dev.colorado.edu/html/arithmetic/1.0.27-rc.1/arithmetic_en.html)

color-vision 1.1 (https://github.com/phetsims/chipper/issues/1337)

- [ ] [color-vision 1.1.27-rc.1](https://phet-dev.colorado.edu/html/color-vision/1.1.27-rc.1/color-vision_en.html)

hookes-law 1.0 (https://github.com/phetsims/chipper/issues/1337)

- [ ] [hookes-law 1.0.26-rc.1](https://phet-dev.colorado.edu/html/hookes-law/1.0.26-rc.1/hookes-law_en.html)

trig-tour 1.0 (https://github.com/phetsims/chipper/issues/1337)

- [ ] [trig-tour 1.0.25-rc.1](https://phet-dev.colorado.edu/html/trig-tour/1.0.25-rc.1/trig-tour_en.html)

**Comment by samreid** [comment]
@mattpen and I realized too late that we had not completed the `Maintenance.checkBranchStatus()` step.  But we didn't see any problems in the RCs above and we are hoping for the best.

**Comment by samreid** [comment]
@mattpen and I finished the production release, and opened 2 side issues for other problems we discovered.  We also updated documentation.

**Comment by samreid** [comment]
We spot checked the production versions, and everything seems good. Nice work @mattpen, thanks.  Closing.
