### ISSUE TITLE
Chip away for TS ESLint rule `@typescript-eslint/no-base-to-string`

### ISSUE THREAD

**Issue by liammulh** [phetsims/chipper#1338]
From https://github.com/phetsims/chipper/issues/1277.  Results from chipAway: 
 - [x] equality-explorer: @pixelzoom 12 errors in 5 files.
 - [x] joist: @zepumph 1 errors in 1 files.
 - [x] scenery-phet: @pixelzoom 5 errors in 3 files
 - [ ] scenery: @jonathanolson 12 errors in 3 files.
 - [x] studio: @chrisklus 3 errors in 2 files.
 - [x] sun: @jbphet 1 errors in 1 files.
 - [x] tandem: @zepumph 1 errors in 1 files.
 - [ ] https://github.com/phetsims/scenery-phet/issues/772 @jessegreenberg

**Comment by liammulh** [comment]
Assigning responsible devs, but this can probably be done without sim-specific knowledge.

**Comment by pixelzoom** [comment]
For the benefit of other assignees who were not a the dev meeting where this was apparently discussed...

This rule is documented at https://typescript-eslint.io/rules/no-base-to-string/.  It says:
> Require `.toString()` to only be called on objects which provide useful information when stringified.

I'm not sure how lint determines if the info is "useful", but I guess I'll see what cases need to be addressed for my sims.

This rule is currently "off" in chipper/eslint/rules/.eslintrc.  You'll need to enable it to "chip away".

**Comment by pixelzoom** [comment]
This rule was a royal pain for abstract classes in equality-explorer. See above commits.

**Comment by pixelzoom** [comment]
This rule was a royal pain for abstract classes in equality-explorer. See above commits.

**Comment by pixelzoom** [comment]
I took care of scenery-phet.  But there's a voicing bug that was exposed by this rule, and @jessegreenberg will need to address it: https://github.com/phetsims/scenery-phet/issues/772

**Comment by pixelzoom** [comment]
@jbphet I took care of sun.

**Comment by zepumph** [comment]
I took care of the last ones I found, and turned on the rule. Closing
