### ISSUE TITLE
Inconsistent specification of sim-specific features in package.json

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#1339]
I'm seeing this pattern in package.json files:

```
    "simFeatures": {
      "supportsSound": true,
      "supportsInteractiveDescription": true
    },
    "supportsOutputJS": true,
    "supportsDynamicLocale": true
```

I'm not sure about  "supportsOutputJS", but the other 3 properties are definitely sim-specific features. Why are some under "simFeatures", while others (like "supportsDynamicLocale") are not? 

I stumbled across this problem while trying to add `"supportsDynamicLocale": true` to a package.json.  I added it to "simFeatures", it didn't work, and I spent time figuring out why.

@jonathanolson you recently added "supportsDynamicLocale". Should it be under "simFeatures"?

**Comment by pixelzoom** [comment]
It looks like @zepumph renamed “features” to “simFeatures”, but I can’t tell who originally added it. I’m guessing it was someone on the a11y team, since it seems to be mostly (all?) a11y features. There are other properties, like “colorProfiles”, that are clearly sim-specific features and not under “simFeatures”.   Adding to the Dev Meeting project board.

**Comment by pixelzoom** [comment]
I'm not 100% certain, but it looks like @zepumph added "simFeatures" (originally named "features") to package.json for https://github.com/phetsims/chipper/issues/1031.

@zepumph what was the purpose of adding the "simFeatures" property? Should other properties be relocated to be consistent?  Or should features under "simFeatures" be moved up a level, and "simFeatures" deleted?

**Comment by zepumph** [comment]
My opinion would be to have the runtime-specific features of the simulation itself be housed in simFeatures. There are an ever growing number, and it has simplified the package files in my opinion. @jonathanolson can we move supportsDynamicLocale into simFeatures?

supportsOutputJS has nothing to do with the features of the runtime, but instead about the source code. It is not a good candidate for nesting in simFeatures.

**Comment by pixelzoom** [comment]
What other features should be moved into simFeatures? colorProfiles? Anything else?

**Comment by jonathanolson** [comment]
> can we move supportsDynamicLocale into simFeatures?

Yes definitely! I was unaware of simFeatures. colorProfiles seems like it works also.

**Comment by samreid** [comment]
This commit had at least one problem, seen in https://github.com/phetsims/density/commit/07a3118d4fdbed1c59ad2d6a56d5a9fa91f96a9f?diff=split

The JSON came out like:

```json
      "phet": {
        "requirejsNamespace": "DENSITY",
        "phetLibs": [
          "density-buoyancy-common",
          "mobius"
        ],
          "../sherpa/lib/poly-decomp-0.3.0.js",
        "preload": [
          "../sherpa/lib/p2-0.7.1.js",
          "../sherpa/lib/three-r104.js"
        ],
```
and the unbuilt sim fails with: 

> Uncaught SyntaxError: Unexpected string (at density_en.html?brand=phet&ea&debugger:40:11)

I'm not sure if other sims are affected.

**Comment by samreid** [comment]
I ran `grunt update` for density, and it seemed to help.

**Comment by zepumph** [comment]
voicing colorProfile and dynamicLocale have been moved into simFeatures.  I think we are ready to close. @pixelzoom do things look good to you?

**Comment by pixelzoom** [comment]
Confirmed by inspecting geometric-options/package.json.  Closing.
