### ISSUE TITLE
make shell scripts runnable from anywhere

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#134]
print-missing-repos.sh has an example of how to determine where the working directory is.

```
CHIPPER_BIN=`dirname "${BASH_SOURCE[0]}"`
WORKING_DIR=${CHIPPER_BIN}/../..
cd ${WORKING_DIR}
```

**Comment by pixelzoom** [comment]
Done. I'm assuming that this approach didn't break anything, since (presumably) print-missing-repos.sh was working after @jonathanolson's changes above. 

@ariel-phet It would be good to have you test whichever scripts you use, to make sure this didn't break anything.

**Comment by pixelzoom** [comment]
Scripts that were not appropriate to change:

checkout-branch.sh
deploy-dev.sh
working-snapshot.sh

**Comment by ariel-phet** [comment]
@pixelzoom - the scripts I use seem to be working fine if from my main directory I use something like

chipper/bin/script-name.sh

**Comment by pixelzoom** [comment]
@ariel-phet The point of this issue is that they should be runnable from any directory. Is that working for you?

**Comment by pixelzoom** [comment]
You'll need to have chipper/bin/ in your shell's PATH variable.

**Comment by ariel-phet** [comment]
Created the .bashrc file with the PATH modification you gave. All works nicely now!
