### ISSUE TITLE
Lint Everything should report errors as it goes

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#1341]
Without a cache + type checking rules, linting all repos can take minutes, it would be nice, and easy to report errors per repo as it goes. I discovered this over the course of the last few months, but really felt it just not working on https://github.com/phetsims/chipper/issues/1335. I also mentioned it to @samreid and he potentially agreed (I kinda can't remember).

**Comment by samreid** [comment]
I tested the code and observed it worked well.  I confirmed `--chip-away` still worked well.  I confirmed the precedence order in `options.inProgressErrorLogging && totalWarnings + totalErrors > 0`. I think this issue can be closed. Nice work.
