### ISSUE TITLE
no-simple-type-checking-assertions doesn't allow assertion messages

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1344]
Discovered in https://github.com/phetsims/chipper/issues/1331, some disable directives were removed because the lint rule no-simple-type-checking-assertions doesn't correctly flag assertions with a message string.

**Comment by samreid** [comment]
@marlitas volunteered to take the next steps.

**Comment by marlitas** [comment]
@samreid and @jonathanolson I left a couple of TODO's regarding assertion situations I or @chrisklus were unsure how to handle. 

@samreid your TODO's can be found in DOM.ts & Input.ts
@jonathanolson  your TODO can be found in Node.ts

I also referenced the wrong issue when pushing these changes. The commits can be found here: https://github.com/phetsims/mean-share-and-balance/issues/102 Sorry about that confusion.

**Comment by samreid** [comment]
I believe all 4 of those assertions should remain.  They are testing corner cases that are difficult to guarantee with the type system.

**Comment by marlitas** [comment]
Great. I will remove the Todos and mark ready for review.

**Comment by marlitas** [comment]
TODOs removed. @samreid this is ready for your review. Feel free to close if all looks good.

**Comment by samreid** [comment]
Looks good, thanks!  Closing.
