### ISSUE TITLE
`@typescript-eslint/member-delimiter-style` is not catching all missing semicolons.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#1348]
Re this lint rule in chipper/eslint/rules/.eslintrc.js:

```
        // Require a specific member delimiter style for interfaces and type literals  🔧
        '@typescript-eslint/member-delimiter-style': 'error', // semi colons in type declarations.
```

I'm wondering if there is a problem with it.  For example:

In Vector2.ts, this definition of `Vector2StateObject` is missing a semicolon after the last field (`y`), but this specific formatting of the code was not triggering the lint rule:

```typescript
export type Vector2StateObject = { x: NumberStateObject; y: NumberStateObject };
```

Without changing the definition, this formatting of `Vector2StateObject` does trigger the lint rule:

```typescript
export type Vector2StateObject = { 
  x: NumberStateObject;
  y: NumberStateObject
};
```

... and required adding a semicolon in https://github.com/phetsims/dot/commit/ea3b37e1b852a3abae18e19f0b634e2e36f81464

I think that GitHub history shows that @samreid enabled this rule, so I'll start by assigning to him.

**Comment by samreid** [comment]
According to https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/member-delimiter-style.md, the default options are:

```ts
{
  "multiline": {
    "delimiter": "semi",
    "requireLast": true
  },
  "singleline": {
    "delimiter": "semi",
    "requireLast": false
  },
  "multilineDetection": "brackets"
}
```

Would you like to change singleline.requrieLast to `true`?

**Comment by pixelzoom** [comment]
I guess I don't feel too strongly about it.  Changing to this:

```
        '@typescript-eslint/member-delimiter-style': [ 'error', {
          singleline: {
            requireLast: true
          }
        } ],
```

... results in 116 errors for `grunt lint-everything`, which appear to be fixable with `--fix`.

I've put this on the dev meeting board, to see how other devs feel about it.

**Comment by pixelzoom** [comment]
On second thought, I don't think this is worth discussing. Leave it as is. Closing.
