### ISSUE TITLE
`readonly` modifier is often missing.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#1349]
Somewhat related to https://github.com/phetsims/tandem/issues/278 ...

There is a disturbing number of places where the `readonly` modifier is missing for static constants. For example in Tandem.ts, all of these should be `readonly`:

```typescript
  public static ROOT: RootTandem;
  public static ROOT_TEST: Tandem;
  public static GENERAL_MODEL: Tandem;
  public static GENERAL_VIEW: Tandem;
  public static GENERAL_CONTROLLER: Tandem;
  public static GLOBAL_MODEL: Tandem;
  public static GLOBAL_VIEW: Tandem;
  public static COLORS: Tandem;
  public static OPTIONAL: Tandem;
  public static OPT_OUT: Tandem;
  public static REQUIRED: Tandem;
  public static PREFERENCES: Tandem;
```

I've also been encountering this problem frequently for non-static properties. 

Two things for discussion developer meeting:

(1) PSA about the importance of the `readonly` modifier. If you don't use it, TypeScript can help you.

(2) Can we create a rule to enforce use of the `readonly` modifier?

**Comment by samreid** [comment]
I searched ESLint and could not find a pre-existing rule that enforces static attributes be readonly.

**Comment by chrisklus** [comment]
From 12/8/22 dev meeting:

PSA delivered. We also talked about the meaning of `static`. 

JG: It might be easy to make a lint rule for this.
CM: It's not just `public static` that relates to needing `readonly`.

We still think it is worth it to make a rule for this case. @zepumph and @AgustinVallejo volunteered to make it, thanks!

**Comment by jessegreenberg** [comment]
In https://github.com/phetsims/tandem/issues/278 I found an AST Node that may be helpful for the champions working on a lint rule: https://typescript-eslint.io/play/#ts=4.8.4&sourceType=module&showAST=es&code=MYGwhgzhAECyCeBhcVoG8CwAoa0AOArgEYgCWw0EALmFedAE4CmYAJgPYB2I80AKgFEAynwD6fABIBJAHIBxaAF5oAckEiVAbmwBfIA

**Comment by zepumph** [comment]
@AgustinVallejo and I will discuss this bad boy next Tuesday

**Comment by zepumph** [comment]
@AgustinVallejo and I had good success with this today! We got the rule working and are through about half of the errors. For now we are committing the rule in the 'off' setting.

Our current rule is just for class fields that are in upper case, but in the future we could expand this if we feel even better.

**Comment by zepumph** [comment]
@AgustinVallejo will take the lead on the rest, and let me know if he runs into trouble and/or is ready for review.

**Comment by zepumph** [comment]
This is looking really great!

* I added doc and cleaned up the rule a bit
* We had talked about the best name for the rule but never got back to it. I think it made more sense the way you suggested with "uppercase" as part of the name. 

Thanks for all the hard work!
