### ISSUE TITLE
include dependencies.json in built html file

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#135]
... and display in Troubleshooting dialog?

**Comment by pixelzoom** [comment]
At 4/30/14 dev meeting, it looks like @jonathanolson has been working on this. So assigning to him.

**Comment by pixelzoom** [comment]
@jonathanolson is this done? I see what looks like dependencies.json in the built HTML file.

**Comment by jonathanolson** [comment]
Yes, it's done. Closing.
