### ISSUE TITLE
Precommit hooks print duplicate error message.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#1359]
Reported in https://github.com/phetsims/chipper/issues/1350#issuecomment-1310608107 12 days ago. It's partially fixed but still some problems. 

Slack#developer:

@pixelzoom:
I noticed that there were some changes to git hooks today. When I encounter errors, I’m now seeing duplicate errors in WebStorm console, for example see below.  Is it possible that something is being run twice?

> 0 errors in 16559ms
/Users/cmalley/PhET/GitHub/natural-selection/js/common/view/NaturalSelectionTimeControlNode.ts
  14:8  error  'merge' is defined but never used        @typescript-eslint/no-unused-vars
  17:8  error  'AssertUtils' is defined but never used  @typescript-eslint/no-unused-vars
  21:8  error  'Tandem' is defined but never used       @typescript-eslint/no-unused-vars
✖ 3 problems (3 errors, 0 warnings)
Task failed: lint, 
/Users/cmalley/PhET/GitHub/natural-selection/js/common/view/NaturalSelectionTimeControlNode.ts
  14:8  error  'merge' is defined but never used        @typescript-eslint/no-unused-vars
  17:8  error  'AssertUtils' is defined but never used  @typescript-eslint/no-unused-vars
  21:8  error  'Tandem' is defined but never used       @typescript-eslint/no-unused-vars
✖ 3 problems (3 errors, 0 warnings)

@zepumph:
Most likely it's just duplicate logging. "lint" is in a child process now, so there are probably two spots where we report logging from the subtask. I'd just note it in https://github.com/phetsims/chipper/issues/1350

**Comment by kathy-phet** [comment]
@pixelzoom - It looks like @samreid posted a commit to address this issue, but maybe it is not working for you? 


> @samreid
> [Only output error messages once, see](https://github.com/phetsims/chipper/commit/d6255e4df747e4e9c7dcd6f83ac9fc3dffb7d189) https://github.com/phetsims/chipper/issues/1350
> [d6255e4](https://github.com/phetsims/chipper/commit/d6255e4df747e4e9c7dcd6f83ac9fc3dffb7d189)

**Comment by pixelzoom** [comment]
Compare to what I see when running tsc directly.  1 error, 1 message.

```
% cd gas-properties
% node ../chipper/node_modules/typescript/bin/tsc
js/common/model/BaseContainer.ts:99:5 - error TS2322: Type 'number' is not assignable to type 'Bounds2'.

99     this.maxBounds = 1;
       ~~~~~~~~~~~~~~


Found 1 error in js/common/model/BaseContainer.ts:99
```

**Comment by kathy-phet** [comment]
OK - I fixed the summary above saying partially fixed. @samreid and @zepumph can take another look next week, after the holiday.

**Comment by samreid** [comment]
I saw this as well--it seems tsc has a self-printing phase, so the prior fix only fixed other tasks.  I'll take a look at tsc now.

**Comment by samreid** [comment]
OK I pushed a fix and it seems better in my testing, @pixelzoom can you please verify?  Please close if all is well.

**Comment by pixelzoom** [comment]
Fix tested, much nicer output.  For the example above, I now see:

```
/Users/cmalley/PhET/GitHub/gas-properties/js/common/model/BaseContainer.ts(99,5): error TS2322: Type 'number' is not assignable to type 'Bounds2'.
1 error in 12833ms
```

Thanks. Closing.
