### ISSUE TITLE
Use @ts-expect-error instead of @ts-ignore

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1363]
From https://github.com/phetsims/chipper/issues/1360 @zepumph said:

> @samreid what I am finding here is that this was a regression, and it could have been solved if there was an assert.throws style unit test for type checking. Is it possible to formulate code that is expected to have a type error in it, and test that it does? I am not aware of anything, but I think it could greatly assist in helping us move WilderOptionsPatterns in to some sort of unit testable, regression proof system.

We can probably add a new source root or pattern that can be:
* excluded by the IDE
* excluded by our primary tsconfig coverage
* have a separate tsconfig
* add process entry points (scripts or mains)
* also check during a grunt build probably
* add coverage on CT

We could have used this several times before, but also it seems like a lot of new complexity.  How can we decide whether this is worth it?

**Comment by zepumph** [comment]
That sounds like quite a nuisance. In my  mind it could be something that would work in our qunit system, or it wouldn't be worth it. Perhaps worth some investigation though. I'm glad to be assigned.

**Comment by zepumph** [comment]
Oh. My. Goodness. They already thought of this. 

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-9.html#-ts-expect-error-comments

Used above. Would you like us to PSA about this in dev meeting?

**Comment by samreid** [comment]
Yes, a PSA sounds appropriate for this.

**Comment by zepumph** [comment]
From a slack conversation today, we actually want to use `@ts-expect-error` everywhere we are @ts-ignoring right now.

**Comment by zepumph** [comment]
And `@ts-ignore` should be bad-text

**Comment by zepumph** [comment]
I'm going to rename this issue, and I'm going to assign @pixelzoom because he is doing some initial work and reporting on slack.

**Comment by pixelzoom** [comment]
And ts-status should be modified to count ts-expect-error instead of ts-ignore.

**Comment by pixelzoom** [comment]
I'm done changing my sims from ts-ignore to ts-expect-error.  

On Slack, @samreid graciously volunteered:
> I’m also happy to help on that issue.  Want me to query replace ts-ignore => ts-expect-error across the project and remove any unnecessary ones?

**Comment by zepumph** [comment]
when you add this as a lint rule, I recommend in `bad-typescript-text`

**Comment by samreid** [comment]
Before I started, @zepumph reported this table in slack:

<img width="315" alt="image" src="https://user-images.githubusercontent.com/679486/206324526-9a13ac75-f599-45f5-ac1a-f7d28b50f8e9.png">


I did the following:

* converted ts-ignore to ts-expect-error
* remove ts-expect-errors that don't have an associated error (131 of them)
* update lint rules so we have to use ts-expect-error instead of ts-ignore going forward
* update the table to report on ts-expect-error.

Here is the resultant table:

```
┌─────────────────┬───────┬───────┬────────────┬────────────────────┐
│     (index)     │  JS   │  TS   │ % Complete │ "@ts-expect-error" │
├─────────────────┼───────┼───────┼────────────┼────────────────────┤
│      axon       │  723  │ 8244  │     91     │         57         │
│      brand      │   0   │  72   │    100     │         0          │
│     chipper     │ 13064 │  502  │     3      │         0          │
│       dot       │ 13642 │ 6452  │     32     │         6          │
│      joist      │  207  │ 15008 │     98     │         13         │
│      kite       │ 9676  │ 6731  │     41     │         7          │
│     mobius      │   0   │ 1779  │    100     │         3          │
│  nitroglycerin  │   0   │ 1985  │    100     │         0          │
│    perennial    │ 12139 │  41   │     0      │         0          │
│    phet-core    │ 2399  │ 2324  │     49     │         4          │
│     phet-io     │  270  │ 2807  │     91     │         4          │
│   phetcommon    │ 1514  │  633  │     29     │         0          │
│    phetmarks    │ 1075  │   0   │     0      │         0          │
│     scenery     │ 36528 │ 51482 │     58     │        137         │
│  scenery-phet   │ 4930  │ 24039 │     82     │         1          │
│     studio      │   2   │ 3700  │     99     │         13         │
│       sun       │  222  │ 15875 │     98     │         7          │
│      tambo      │  55   │ 6587  │     99     │         4          │
│     tandem      │  262  │ 5312  │     95     │         29         │
│      tappi      │  964  │  955  │     49     │         2          │
│      twixt      │ 2331  │  32   │     1      │         0          │
│ utterance-queue │   0   │ 3735  │    100     │         9          │
│      vegas      │   0   │ 3236  │    100     │         0          │
└─────────────────┴───────┴───────┴────────────┴────────────────────┘
```

@zepumph @pixelzoom or @marlitas want to review?

**Comment by zepumph** [comment]
Amazing. Thanks so much. I looked at the lint rule, searched for `ts-ignore`, `tsignore` and `ts ignore` case insensitive and found only good things. I feel like we are ready to close, but it seems good for a PSA now.

**Comment by pixelzoom** [comment]
Before we close this issue... Across all repos, we went from 595 `@ts-ignore` to 458 `@ts-expect-error`.  While that's certainly an improvement, having that many is concerning - especially in common-code repos like axon (91) and scenery (137).  In my experience, most `@ts-expect-error` are easily resolved, and it's beneficial to eliminate them. So I think we should discuss why we have so many `@ts-expect-error`, what (if anything) we’re going to do about it, etc.  We can either do that as part of this issue, or maybe another issues is needed.

**Comment by chrisklus** [comment]
From 12/8/22 dev meeting:

PSA delivered! This is great news. Also, as noted above, 458 `@ts-expect-error`s is still to many - let's work on this!

KP: Should we create a chip away for the number in each repo?
CM: We should also have issue links or code comments for the ones we can't get rid of so we aren't double investigating cases in common code.
CM: I agree with SR that we don't need to handle all of these, but the current number is too high and there are likely lots of cases that were rushed during conversion etc that should be revisited.

@marlitas will create a chip away issue, thanks!

We are all set here, closing.

**Comment by marlitas** [comment]
I created the issue https://github.com/phetsims/chipper/issues/1366, so am now closing!

**Comment by pixelzoom** [comment]
Reopening.

From https://github.com/phetsims/chipper/issues/1363#issuecomment-1341705273:
> And `@ts-ignore` should be bad-text

I don't see `@ts-ignore` in bad-typescript-text.js.

**Comment by marlitas** [comment]
It is not in bad-typescript-text. This is supported through a rule in typescript-eslint. This is the relevant commit: https://github.com/phetsims/chipper/commit/15258550c3ffc9e4e81c0bac5e5305f16885f8de

@pixelzoom please close if that feels adequate.

**Comment by pixelzoom** [comment]
@marlitas Thanks for clarifying. Re-closing.
