### ISSUE TITLE
Upgrade to TypeScript 4.9

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1364]
TypeScript 4.9 was recently released and it would be good to upgrade to use it.

**Comment by samreid** [comment]
@marlitas and I observed new type errors caught by 4.9.3.  One was introduced in 331833d8ce02ee5db30cfafc537362887ad53288 when the RewardDialog star node options were moved to be nested, but RewardDialog defaults weren't updated at the same time.

We'll push a correction.

**Comment by samreid** [comment]
We messaged slack dev-public:

> In https://github.com/phetsims/chipper/issues/1364 @marlitas and I updated to TypeScript 4.9.3 and it helped catch some type errors.  Please pull-all and npm update in chipper at your convenience.

Closing.

**Comment by pixelzoom** [comment]
I’ve run npm prune; npm update in chipper. I’m now seeing this warning every time that I run grunt lint:

```
% grunt lint
Running “lint” task
=============
WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.
You may find that it works just fine, or you may not.
SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.9.0
YOUR TYPESCRIPT VERSION: 4.9.3
Please only submit bug reports when using the officially supported version.
=============
```

**Comment by pixelzoom** [comment]
I re-ran `npm prune; npm update` in chipper, perennial, and perennial-alias, and now `grunt lint` is running without warnings.

**Comment by samreid** [comment]
I updated to the current version of eslint.  Testing seems to work OK and get rid of the error, so I committed it.  @pixelzoom can you please pull chipper, npm install and test?

**Comment by pixelzoom** [comment]
I verified that the `grunt lint` warning is gone.

I announced on Slack#dev-public:
> PSA: In https://github.com/phetsims/chipper/issues/1364, @samreid  fixed the grunt lint warning by upgrading ESlint. Please pull chipper, then npm prune; npm update.

Closing.
