### ISSUE TITLE
It's still possible to use static strings in a sim that has `supportsDynamicLocale: true`

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#1370]
After adding support for dynamic locale to a sim, we've been adding `supportsDynamicLocale: true` to package.json, then running `grunt modulify` to remove the static strings from Strings.ts.   This supposedly ensures that we're not accidentally using any static strings, or won't add usages of static strings in the future.

But I’ve discovered that I can still access those static strings when the sim is running.  For example, GeometricOpticsStrings.ts has an entry for `radiusOfCurvaturePositiveStringProperty`, and no entry for `radiusOfCurvaturePositive`. But I can still use `GeometricOpticsStrings.radiusOfCurvaturePositive` in code and it returns the value of the StringProperty. 

Questions:

(1) How is this happening? Is there an ES5 getter with the same name as the StringProperty? Does it have something to do with `babel/_generated_development_strings_`?

(2) Is this desirable behavior? I don't think so. It seems to defeat the purpose of removing static strings from Strings.ts, which was to verify that we’re using only using StringProperties, and not static strings.

(3) If it is desirable, why do we need the static strings in Strings.ts? If having the StringProperty allows you to also access the static string, then the static strings in Strings.ts are redundant.

**Comment by samreid** [comment]
I do not know how strings are populated for built or unbuilt sims, but this problem is not related to generated_development_strings.  I confirmed this by commenting out loading of the generated_development_strings and checking radiusOfCurvature strings in Geometric Optics like so:

<details>

```diff

Subject: [PATCH] Use dynamic strings
---
Index: main/geometric-optics/js/common/view/RadiusOfCurvatureControl.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/main/geometric-optics/js/common/view/RadiusOfCurvatureControl.ts b/main/geometric-optics/js/common/view/RadiusOfCurvatureControl.ts
--- a/main/geometric-optics/js/common/view/RadiusOfCurvatureControl.ts	(revision 1a6b74f62b1a126c0c50f8ebd8ad737d8aed9a9a)
+++ b/main/geometric-optics/js/common/view/RadiusOfCurvatureControl.ts	(date 1673438992357)
@@ -36,6 +36,10 @@
 
     const range = radiusOfCurvatureMagnitudeProperty.range;
 
+    // @ts-expect-error
+    console.log( GeometricOpticsStrings.radiusOfCurvaturePositive );
+    console.log( GeometricOpticsStrings.radiusOfCurvaturePositiveStringProperty.value );
+
     const titleStringProperty = new DerivedProperty( [
       radiusOfCurvatureProperty,
       GeometricOpticsStrings.radiusOfCurvaturePositiveStringProperty,
Index: main/chipper/js/load-unbuilt-strings.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/main/chipper/js/load-unbuilt-strings.js b/main/chipper/js/load-unbuilt-strings.js
--- a/main/chipper/js/load-unbuilt-strings.js	(revision 464b10b1fd9c38afd13f94bb5686faf803d4f530)
+++ b/main/chipper/js/load-unbuilt-strings.js	(date 1673438949986)
@@ -232,17 +232,17 @@
   if ( localesQueryParam === '*' ) {
 
     // Load the conglomerate files
-    requestJSONFile( `../babel/_generated_development_strings/${ourRepo}_all.json`, json => {
-      processConglomerateStringFile( json, ourRequirejsNamespace );
-      phet.chipper.stringRepos.forEach( stringRepoData => {
-        const repo = stringRepoData.repo;
-        if ( repo !== ourRepo ) {
-          requestJSONFile( `../babel/_generated_development_strings/${repo}_all.json`, json => {
-            processConglomerateStringFile( json, stringRepoData.requirejsNamespace );
-          } );
-        }
-      } );
-    } );
+    // requestJSONFile( `../babel/_generated_development_strings/${ourRepo}_all.json`, json => {
+    //   processConglomerateStringFile( json, ourRequirejsNamespace );
+    //   phet.chipper.stringRepos.forEach( stringRepoData => {
+    //     const repo = stringRepoData.repo;
+    //     if ( repo !== ourRepo ) {
+    //       requestJSONFile( `../babel/_generated_development_strings/${repo}_all.json`, json => {
+    //         processConglomerateStringFile( json, stringRepoData.requirejsNamespace );
+    //       } );
+    //     }
+    //   } );
+    // } );
 
     // Even though the English strings are included in the conglomerate file, load the english file directly so that
     // you can change _en strings without having to run 'grunt generate-unbuilt-strings' before seeing changes.

```

</details>

This outputted "Radius of Curvature" 4 times, so this shows those strings are available at runtime even without the generated development strings file.

> (1) How is this happening? Is there an ES5 getter with the same name as the StringProperty? Does it have something to do with babel/_generated_development_strings_?

I do not know how the string engine populates strings in built or unbuilt mode, but it is not caused by babel/_generated_development_strings_.

> (2) Is this desirable behavior? I don't think so. It seems to defeat the purpose of removing static strings from Strings.ts, which was to verify that we’re using only using StringProperties, and not static strings.

It seems like it would cause errors during development of JavaScript code, but not TypeScript code.  Since new development is done in TypeScript, this is not a significant problem, or one that we should expend effort on.

> (3) If it is desirable, why do we need the static strings in Strings.ts? If having the StringProperty allows you to also access the static string, then the static strings in Strings.ts are redundant.

Listing the strings in the Strings.ts file allows us to support the TypeScript sims that are not yet using dynamic strings.  Once all TypeScript sims are using dynamic strings, we could delete the non-Property strings from those Strings.ts files.

**Comment by pixelzoom** [comment]
> Listing the strings in the Strings.ts file allows us to support the TypeScript sims that are not yet using dynamic strings. Once all TypeScript sims are using dynamic strings, we could delete the non-Property strings from those Strings.ts files. 

Yes -- and I'm reporting that deleting the static strings is not effective.  They can still be accessed at runtime, and their use is not flagged as an error in .js code.

If you don't think this is something that should be investigated/addressed, feel free to close as "won't fix".  Otherwise please assign to someone who is qualified to investigate.

**Comment by samreid** [comment]
I was surprised to see a JavaScript sim going through QA dev testing this week.  Some of the bugs caught by QA would have been caught by TypeScript. But perhaps our team isn't at a point where we can say development is done in TypeScript.  Perhaps @jonathanolson or @liammulh or @zepumph know more about how the strings are populated?  It was unclear to me after looking around in loadUnbuiltStrings for a while.  Also, I think the static (non-dynamic) string were also accessible during a build.

**Comment by liammulh** [comment]
> Perhaps @jonathanolson or @liammulh or @zepumph know more about how the strings are populated?

@samreid, @pixelzoom, I'm fuzzy on this issue. What is meant by "how strings are populated for built or unbuilt sims"?

I was involved in the issue where we made `babel/_generated_development_strings_`, but outside of that, I know very little about how sim code handles strings (which is unfortunate because it would almost certainly be helpful in developing Rosetta, but alas).

**Comment by zepumph** [comment]
It seems like the `supportsDynamicLocale` flag is just used for the TypeScript type in modulify. There is nothing in getStringModule about actually creating the object. The work here is to read package.supportsDynamicLocale in getStringModule and respect it when determining if it should populate the return object: https://github.com/phetsims/chipper/blob/28f8a34cd1d34cecce8d0fee0304f2c4442adcd7/js/getStringModule.ts#L207

It may be as simple as wrapping that line, but there is likely more to do, for example don't do this link either. 
https://github.com/phetsims/chipper/blob/28f8a34cd1d34cecce8d0fee0304f2c4442adcd7/js/getStringModule.ts#L222-L224

I didn't spend enough here, but wanted to point someone else in the right direction if this was high enough priority to make its way onto someone else's list.

**Comment by samreid** [comment]
After hearing this, it does not feel high priority enough to me to warrant much effort.  If a JavaScript sim uses a static string, that will easily be discovered by one of the string tests.  Also, let's use more TypeScript and less JavaScript.  I will take the option mentioned in https://github.com/phetsims/chipper/issues/1370#issuecomment-1380885299 and close as will not fix. Others feel free to disagree or reopen if you wish.
