### ISSUE TITLE
Locale info is still a "ROUGH DRAFT". Make it production ready.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#1375]
While working on https://github.com/phetsims/chipper/issues/1374, I was examining commits for localeInfoModule.js, the primary source for PhET locale information that is displayed in Preferences and elsewhere.  

There is a single comment by @jonathanolson about this file in https://github.com/phetsims/chipper/issues/1302#issuecomment-1213644765:
> Added a VERY rough-draft locale switcher in the navbar for demo-ing, see https://bayes.colorado.edu/dev/olsonjb/locale-test.html

This is a single commit by @jonathanolson in GitHub for this file, with this message:
 > Adding ROUGH DRAFT locale switcher for development purposes, see https://github.com/phetsims/chipper/issues/1302

In both cases the use of cap ("VERY rough-draft" and "ROUGH DRAFT") seems significant. And there's even an acknowledge that this isn't ready for production ("for development purposes") - which I can vouch for given issues like https://github.com/phetsims/chipper/issues/1374.

So given that a huge amount of work has been done since August to support dynamic locale, and that this is the foundation that's now "included in all sims"...  Do you think we should move this from the "ROUGH DRAFT" stage to production-ready?  

@jonathanolson for comment. @kathy-phet for prioritization.

**Comment by jonathanolson** [comment]
The "rough draft" parts referred to the temporary locale switcher, which has been phased out and removed. Is there something that should be done about locale info? I'm not aware of any "rough" bits right now.
