### ISSUE TITLE
Dynamic locale switching should only be available in the _all html file for builds

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/chipper#1378]
Over slack I noticed

> Dynamic locale switching is now in all non-english sims from the website. Is that expected? I didn't realize that is how it was supposed to work. For example, see the preferences localization tab at https://phet.colorado.edu/sims/html/friction/latest/friction_fi.html. (It might be fine, just checking...)

@kathy-phet responded
>  My expectation was only in the _all file (at least at the moment). The discussion about how to leverage this capability on the PhET basic sim is a complex one and involves the website functionality and the apps.  I don't think we need to maintenance release the few specific sims that have this in their locale, but let's fix master.

**Comment by pixelzoom** [comment]
Reopening.  In https://github.com/phetsims/beers-law-lab/issues/329#issuecomment-1431892375, I noted that `all_phet_debug.html` does not have a Localization tab in Preferences.  And that seems like a bug. 

@jessegreenber commented in Slack#dev-public
> I think that is wrong. I can't find how the debug file is created but it is probably missing a `window.phet.chipper.allowLocaleSwitching = true;`

@jonathanolson commented in Slack#dev-public:
> I’ll need to check buildRunnables to see if we’re passing the flag to the all-debug variety

**Comment by pixelzoom** [comment]
This is now blocking the next RC for beers-law-lab and concentration, see https://github.com/phetsims/beers-law-lab/issues/329.  So top priority.

**Comment by jonathanolson** [comment]
Fixed above, and patched those two branches. @samreid can you verify my fix looks good?

**Comment by samreid** [comment]
Should we also add this for the XHTML build?

**Comment by pixelzoom** [comment]
It's definitely not working as expected for the XML build.  For example xml/beers-law-lab_all.xhtml has no Localization tab.

**Comment by jonathanolson** [comment]
I'll add that too.

**Comment by pixelzoom** [comment]
I did a phet-io build, and it looks like the "all" resources are behaving as expected; they include a Localization tab:

* beers-law-lab_all_phet-io.html
* beers-law-lab_all_phet-io_debug.html
* xhtml/beers-law-lab_all_phet-io.xhtml

I'm not sure about beers-law-lab_all_phet-io.html.gz, or what it's used for.

@samreid is there anything else for PhET-iO that needs to be check here?

**Comment by samreid** [comment]
Yes, ungzip that file and make sure the sim HTML in it has the localization dialog, I think.

**Comment by pixelzoom** [comment]
@samreid beers-law-lab_all_phet-io.html.gz unzip to 1 file: beers-law-lab_all_phet-io.html.  That is a file that is already in the phet-io build directory.  Why is the same file provided in both zipped and unzipped format?

**Comment by pixelzoom** [comment]
Re beers-law-lab_all_phet-io.html.gz ... @samreid discovered that .gz files are created for evrery "all" file (regardless of brand) to improve performance of the iOS app.

Re beers-law-lab-phet-io-1.7.0-dev.8.zip... It's intended to be a download artifact, not to be unzipped in the build directory.  So overwriting other files in the build directory is not a concern (although it does make testing/inspecting inconvenient.)

**Comment by jonathanolson** [comment]
Applied patches to beers-law-lab/concentration.

**Comment by jonathanolson** [comment]
> Why is the same file provided in both zipped and unzipped format?

In-code comment has more info:

> Add a compressed file to improve performance in the iOS app, see https://github.com/phetsims/chipper/issues/746

**Comment by pixelzoom** [comment]
@jonathanolson said:
> > Why is the same file provided in both zipped and unzipped format?
> 
> In-code comment has more info:
> 
> > Add a compressed file to improve performance in the iOS app, see https://github.com/phetsims/chipper/issues/746

Indeed - After digging through commit history, @samreid and I added that comment yesterday because it wasn't documented.

**Comment by pixelzoom** [comment]
Verifying in https://github.com/phetsims/beers-law-lab/issues/329.  I'll close this and reopen if there are any futher problems.
