### ISSUE TITLE
In dynamic locale dialog, some parens in RTL lang are in wrong direction

### ISSUE THREAD

**Issue by liammulh** [phetsims/chipper#1379]
<b>Test Device</b>

MacBook Air

<b>Operating System</b>

macOS 12.4

<b>Browser</b>

Safari 15.5

<b>Problem Description</b>

Discovered during https://github.com/phetsims/qa/issues/900. In the dynamic locale dialog, the parentheses in one of the Arabic language locales — I think it's `ar_MA` or Arabic (Morocco) — are in the wrong direction. I believe the parenthesis circled in red below should be an open parenthesis, not a close parenthesis.

I am not sure if this is a rendering issue or a text data issue. Feel free to move this issue.

<b>Steps to Reproduce</b>

1. Open [this link](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.3.0-dev.20/phet-io/circuit-construction-kit-dc_all_phet-io.html?postMessageOnError&phetioStandalone)
2. Open the preferences dialog
3. Open the localization tab

<b>Visuals</b>

<img width="600" alt="parens2" src="https://user-images.githubusercontent.com/60749003/219804789-92d15865-b087-4b97-afb9-65331aa383d7.png">

**Comment by samreid** [comment]
In slack, @kathy-phet said: 
> BLL published in PhET-iO has it right, so I'm not sure why it has it wrong here:
![image](https://user-images.githubusercontent.com/679486/219861389-827d48ea-81d4-4bd3-a79c-7f9f7bcee165.png)

@Nancy-Salpepi replied:

> I had opened an issue related to ar_MA in BLL.
https://github.com/phetsims/beers-law-lab/issues/326. Maybe that is why?

**Comment by samreid** [comment]
There is evidence this is a browser-specific bug. I tested https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.3.0-dev.20/phet-io/circuit-construction-kit-dc_all_phet-io.html?postMessageOnError&phetioStandalone in Chrome and Safari, and saw that Chrome is correct and Safari is incorrect.  Here's the screenshot (Chrome on left, Safari on right):

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/679486/219863788-3c44dcd2-92c6-45ae-b87c-214fdcc80e85.png">

**Comment by samreid** [comment]
Would it help to call wrapRTL like https://github.com/phetsims/build-a-molecule/commit/8b6bc0c2c7697a83373841cac9613fc7a0175114 ?

**Comment by Nancy-Salpepi** [comment]
Actually it is incorrect in published BBL as well with safari. The issue I had opened was for the formulas. 
Sorry I didn't catch this.

**Comment by matthew-blackman** [comment]
@samreid @zepumph @arouinfar and I discussed this, and note that this is not a sim-specific issue.

We would like to reach out to @jonathanolson and @jbphet to provide insight into how this could be solved.

**Comment by jonathanolson** [comment]
Looking into it. I don't see directional marks in the string for some reason.

**Comment by kathy-phet** [comment]
It still works fine on Windows, Chrome.

**Comment by jbphet** [comment]
@jonathanolson and I are going to experiment a bit with isolates (see https://github.com/phetsims/chipper/issues/1355) and see if it makes any different.

**Comment by jonathanolson** [comment]
Patched above. Browsers were making different guesses for directionality when we didn't have embedding marks in.

**Comment by jonathanolson** [comment]
@kathy-phet should this be maintenance-patched? I'll patch joist/phetcommon if so.

**Comment by Nancy-Salpepi** [comment]
FYI @samreid: this is fixed in Circuit Construction Kit: DC 1.3.0-rc.1 with mac + safari.

**Comment by zepumph** [comment]
This is to @kathy-phet to note if an MR is needed for this.

**Comment by jonathanolson** [comment]
MR'ed, closing!
