### ISSUE TITLE
rename all-build.sh?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#138]
Comment in all-build.sh by @jonathanolson 

```
# (named all-build because I like build.sh to be tab-completed easily. lazy? yes)
```

I see no build.sh script.  Can we rename?

**Comment by jonathanolson** [comment]
Yes, that sounds fine with me. @jbphet @samreid or @aaronsamuel137, any objections?

**Comment by aaronsamuel137** [comment]
Fine with me.

**Comment by pixelzoom** [comment]
[4/27/15, 11:41:45 AM] Chris Malley: I see no build.sh. Can we rename?
[4/27/15, 12:16:10 PM] Jonathan Olson: Yes

**Comment by pixelzoom** [comment]
Renamed to build-all.sh.  Closing.

**Comment by pixelzoom** [comment]
It looks like build-all.sh was meant to be capable of running any grunt task for all sims. Here's the relevant source line:

`grunt $1  # run the build`

This is passing the first command-line arg to grunt.  A couple of problems:

1. It should be passing all command-line args to grunt (i.e., $*).

2. It should be named something like `grunt-all.sh` because it doesn't necessarily do a build. For example, it can be used to lint all sims by running `build-all.sh lint`.  

So I'm going to rename to grunt-all.sh, and make it pass through all command-line args.

**Comment by pixelzoom** [comment]
It's also silently ignoring sims that are in active-sim but missing from the current working copy. I'll make it print a warning.

**Comment by pixelzoom** [comment]
Done, closing.
