### ISSUE TITLE
Stricter tsconfig and lint for some TypeScript repos

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#1380]
I'm responsible for a growing number of sims and common-code repos that have been converted to TypeScript. Most of them are very clean and exceed the requirements of chipper/eslint/sim_eslintrc.js. and I'd like to keep it that way.  

TODO:

(1) Identify what to make stricter, and whether that should be done via tsconfig.json or package.json "eslintConfig".

(2) Identify the correct pattern to use in package.json "eslintConfig".  I see this being done in 2 different ways, and I'm not sure if they are correct/equivalent.  For example, I added this override to geometric-optics/package.json to prevent `// @ts-` comments:

```
"eslintConfig": {
    "extends": "../chipper/eslint/sim_eslintrc.js",
    "overrides": [
      {
        "files": [
          "**/*.ts"
        ],
        "rules": {
          "@typescript-eslint/ban-ts-comment": "error"
        }
      }
    ]
  }
```

But @zepumph recently added this override to a number of repos to opt-out of "todo-should-have-issue". It's less verbose, but is this also effectively an override? Why is it not in the "eslintConfig.overrides" section?

```
  "eslintConfig": {
    "extends": "../chipper/eslint/sim_eslintrc.js",
    "rules": {
      "todo-should-have-issue": "off"
    }
  }
```

**Comment by pixelzoom** [comment]
> ... I see this being done in 2 different ways, and I'm not sure if they are correct/equivalent. 

I tested and they are equivalent. So in the above commit, I've replaced "eslintConfig.override.rules" with the simpler "eslintConfig.rules" form.

**Comment by pixelzoom** [comment]
Looking through PhET's tsconfig-core.json, I see `"strict": true`.  So I don't feel the need to add anything to repo-specific tsconfig.json at this time.

For the repos that I'm responsible for that have been converted to TypeScript, I added add a ban on `any` and `// ts-` comments, via the package.json entry shown below.  In addition to sim repos, this includes example-sim, sceney-phet, simulation-rasa, and vegas (PSA was made to Slack#typescript).

```
  "eslintConfig": {
    "extends": "../chipper/eslint/sim_eslintrc.js",
    "rules": {
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/ban-ts-comment": "error"
    }
  }
```

This feels sufficient for now, and I'll enable additional rules as needed.

**Comment by zepumph** [comment]
When you remove this from the "overrides" section, then you are running these rules on js files as well. This means that you are at the mercy of the typescript-eslint rule writers as to the performance of said rule. I would recommend bringing it back the overrides section generally. 

For example, in no-explicit-any, the rule code only triggers on an ast hook called `TSAnyKeyword`, which only occurs in typescript files (so no trouble there), but in `ban-ts-comment`, the rule runs on the `Program` hook, which is the most general ast hook. Thus, this block is run on every javascript file in the repo as well (iterating through every comment).

```js
 return {
            Program() {
                const comments = sourceCode.getAllComments();
                comments.forEach(comment => {
                    const regExp = comment.type === utils_1.AST_TOKEN_TYPES.Line
                        ? commentDirectiveRegExSingleLine
                        : commentDirectiveRegExMultiLine;
                    const match = regExp.exec(comment.value);
                    if (!match) {
                        return;
                    }
                    const { directive, description } = match.groups;
                    const fullDirective = `ts-${directive}`;
                    const option = options[fullDirective];
                    if (option === true) {
                        context.report({
                            data: { directive },
                            node: comment,
                            messageId: 'tsDirectiveComment',
                        });
                    }
                    if (option === 'allow-with-description' ||
                        (typeof option === 'object' && option.descriptionFormat)) {
                        const { minimumDescriptionLength = exports.defaultMinimumDescriptionLength, } = options;
                        const format = descriptionFormats.get(fullDirective);
                        if (description.trim().length < minimumDescriptionLength) {
                            context.report({
                                data: { directive, minimumDescriptionLength },
                                node: comment,
                                messageId: 'tsDirectiveCommentRequiresDescription',
                            });
                        }
                        else if (format && !format.test(description)) {
                            context.report({
                                data: { directive, format: format.source },
                                node: comment,
                                messageId: 'tsDirectiveCommentDescriptionNotMatchPattern',
                            });
                        }
                    }
                });
            },
```

The above iterates through every comment.

Perhaps it currently isn't that important, but it kinda depends on the number of unconverted files and the type of rule you are adding for a clean typescript codebase.

It isn't too big of a deal, but with the number of times that linting occurs on the project on a daily basis, I am constantly trying to optimize things. I would recommend continuing to only run these rules on typescript files.

**Comment by pixelzoom** [comment]
@zepumph I had this very discussion with you on 1/20/23 in https://phetsims.slack.com/archives/D6E41BT17/p1674229377750839, and you recommended what I've done here.  So I'm not keen on undoing this.

**Comment by zepumph** [comment]
Yes I see that, thanks. I don't like my old response. Sorry about that. 

I said ". . . . and/or for a subset of files", so maybe I was explaining in a super confusing way, but it sounds like I was just wrong. Overrides seems best to opt out of typescript rules running on javascript code and it is adding fluff to our lint process. I also wonder if we would get to a case where a typescript rule would assume it had typescripting logic available but didn't because of it being javascript. 

This seems pretty small potatoes in general though. Either way is fine.

**Comment by pixelzoom** [comment]
@zepumph what do you recommend when we're overriding both TS and JS lint rules?

For example, suppose we have this in package.json. "todo-should-have-issue" is relevant for *.js and *.ts. "@typescript-eslint/no-explicit-any" is relevant only for *.ts.

```
  "eslintConfig": {
    "extends": "../chipper/eslint/sim_eslintrc.js",
    "rules": {
      "todo-should-have-issue": "off",
      "@typescript-eslint/no-explicit-any": "error"
    },
  }
```

Should it be change to this?

```
  "eslintConfig": {
    "extends": "../chipper/eslint/sim_eslintrc.js",
    "rules": {
      "todo-should-have-issue": "off",
    },
    "overrides": [
      {
        "files": [
          "**/*.ts"
        ],
        "rules": {
          "@typescript-eslint/no-explicit-any": "error"
        }
      }
    ]
  }
```

**Comment by pixelzoom** [comment]
Is this the general pattern that you're recommending as most performant? 

```
  "eslintConfig": {
    "extends": "../chipper/eslint/sim_eslintrc.js",
    "rules": {
      // Overrride TypeScript rules here
    },
    "overrides": [
      {
        "files": [
          "**/*.ts"
        ],
        "rules": {
          // Overrride TypeScript rules here
        }
      }
    ]
  }
```

**Comment by zepumph** [comment]
https://github.com/phetsims/chipper/issues/1380#issuecomment-1438873905 is ideal and what I recommend. Typescript rules should not apply to javascript files. Let me know if you run into trouble with that approach.

**Comment by pixelzoom** [comment]
In the above commits, I moved all TypeScript rules to eslintConfig.overrides.rules, as recommended by @zepumph.  I did this for all repos where it was relevant.

Closing.
