### ISSUE TITLE
Upgrade to TypeScript 5.0

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#1384]
@samreid mentioned it was released today. Fun! When should we pull that upgrade trigger ourselves?

I'm inclined to wait a week for the first couple of maintenance releases. No strong preference though.

**Comment by samreid** [comment]
I'm seeing a type error in 5.0:

```
~/apache-document-root/main/chipper/tsconfig/all$ tsc
../../../natural-selection/js/common/model/Bunny.ts:386:5 - error TS2322: Type '{ father: IOType<any, any>; mother: IOType<any, any>; generation: IOType<number, number>; isAlive: IOType<boolean, boolean>; age: IOType<number, number>; _private: { ...; }; }' is not assignable to type 'CompositeSchema'.
  Type '{ father: IOType<any, any>; mother: IOType<any, any>; generation: IOType<number, number>; isAlive: IOType<boolean, boolean>; age: IOType<number, number>; _private: { ...; }; }' is not assignable to type 'Record<string, IOType<any, any>>'.
    Property '_private' is incompatible with index signature.
      Type '{ restTime: IOType<number, number>; hopTime: IOType<number, number>; cumulativeRestTime: IOType<number, number>; cumulativeHopTime: IOType<number, number>; hopDelta: IOType<...>; hopStartPosition: IOType<...>; }' is missing the following properties from type 'IOType<any, any>': events, toStateObject, fromStateObject, stateObjectToCreateElementArguments, and 13 more.

386     return {
        ~~~~~~~~
387 
    
... 
406       }
    ~~~~~~~
407     };
    ~~~~~~

../../../natural-selection/js/common/model/Bunny.ts:399:9 - error TS2578: Unused '@ts-expect-error' directive.

399         // @ts-expect-error https://github.com/phetsims/tandem/issues/282 TypeScript support for _private
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 2 errors in the same file, starting at: ../../../natural-selection/js/common/model/Bunny.ts:386
```

This looks related to https://github.com/phetsims/tandem/issues/282

**Comment by marlitas** [comment]
From Slack:


> Chris Malley:
> I’d love to wait until after CG publication, so we don’t introduce additional risk.  Or if we must upgrade sooner, understand/discuss why it’s worth the additional risk.
> 
> 
> Kathy Perkins:
> After CG and NP and MSS sound good
> 
> 
> Chris Malley:
> So perhaps the goal for the next iteration should be to identify an appropriate time to upgrade — and not necessarily schedule the upgrade for the next iteration.

**Comment by samreid** [comment]
Since TypeScript is used exclusively for type checking and not for transpiling, upgrading seems like a low cost and low risk. That being said, I'm happy to wait until after CG, NP and MSS have release SHAs.

**Comment by samreid** [comment]
At today's dev meeting, we agreed it's a good time to upgrade to Typescript 5.0.  Keep in mind Microsoft does not use semantic versioning for this, so it's kind of like "4.10". Local tests seem good.  WebStorm seems good. Type-aware linting seems good.  I'll commit and notify the team.

**Comment by samreid** [comment]
I wrote in slack dev-public:

> TypeScript has been upgraded to 5.0.4, please see https://github.com/phetsims/chipper/issues/1384 for details.  Please pull chipper and npm install to get the new version.  After updating, you can run `cd chipper` then `node node_modules/typescript/bin/tsc --version` to see that your version updated correctly. Please report problems in the issue.

**Comment by samreid** [comment]
I added:

> I cleared my local caches in chipper:
rm -rf dist/declarations/
rm -rf dist/outDir/
Not sure if that is really necessary.
Keep in mind this just pertains to type checking, and that our transpiler remains unchanged.

@zepumph or @jessegreenberg can you please sanity check this change and close if all seems well?

**Comment by samreid** [comment]
Also, I saw that tsc 5.0.4 took `0m25.842s` to type check tsconfig/all (with no caches) compared to `0m30.229s` in 4.9.5 (also after clearing caches), so it is a bit faster.

**Comment by zepumph** [comment]
Un-cached on my machine, absolute-tsc took 112 seconds, cached took 6.7 seconds.

**Comment by zepumph** [comment]
Perhaps the speed increases you are seeing is explained in https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#speed-memory-and-package-size-optimizations.

I poked through that blob post and didn't see too much that I will automatically take to heart, but I do appreciate the upgrade. I have also been able to successfully type check a few times in the last few hours. @jessegreenberg feel free to close.

**Comment by jessegreenberg** [comment]
Looking good! I tried running the type checker and pre commit hooks. I also verified that Webstorm has the right version of after restarting and it is behaving well. Closing, if anything is amiss we can return.

**Comment by samreid** [comment]
I suspect that if someone used new TypeScript 5.0 features, they would type check but not transpile correctly (since we just updated tsc but not babel).  So I'll check if I need to update babel too. Also, do we need to upgrade eslint to work with TS 5.0?  I'll check.

**Comment by samreid** [comment]
@jonathanolson and I updated other tooling, and tested new TS5.0 features. We used this patch to test in CCK:

<details>

```diff

Subject: [PATCH] Update more TypeScript tooling, see https://github.com/phetsims/chipper/issues/1384
---
Index: js/main.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/main.ts b/js/main.ts
new file mode 100644
--- /dev/null	(date 1681488630872)
+++ b/js/main.ts	(date 1681488630872)
@@ -0,0 +1,12 @@
+// main.ts
+import { vehicles } from './models/index.js';// eslint-disable-line
+
+function takeASpaceship( s: vehicles.Spaceship ) {
+  // ✅ ok - `vehicles` only used in a type position
+}
+
+function makeASpaceship() {
+  return new vehicles.Spaceship();
+  //         ^^^^^^^^
+  // 'vehicles' cannot be used as a value because it was exported using 'export type'.
+}
\ No newline at end of file
Index: js/models/index.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/models/index.ts b/js/models/index.ts
new file mode 100644
--- /dev/null	(date 1681488490911)
+++ b/js/models/index.ts	(date 1681488490911)
@@ -0,0 +1,1 @@
+export type * as vehicles from "./vehicles";
\ No newline at end of file
Index: js/models/Spaceship.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/models/Spaceship.ts b/js/models/Spaceship.ts
new file mode 100644
--- /dev/null	(date 1681488450582)
+++ b/js/models/Spaceship.ts	(date 1681488450582)
@@ -0,0 +1,4 @@
+// models/vehicles.ts
+export class Spaceship {
+  // ...
+}
\ No newline at end of file
Index: js/circuit-construction-kit-dc-main.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/circuit-construction-kit-dc-main.ts b/js/circuit-construction-kit-dc-main.ts
--- a/js/circuit-construction-kit-dc-main.ts	(revision f6070e255c1cea7f05a02a39355d50b716d30564)
+++ b/js/circuit-construction-kit-dc-main.ts	(date 1681488336416)
@@ -19,12 +19,46 @@
 import LabScreen from './lab/LabScreen.js';
 import CodapScreen from './codap/CodapScreen.js';
 import CCKCQueryParameters from '../../circuit-construction-kit-common/js/CCKCQueryParameters.js';
+import IntentionalAny from '../../phet-core/js/types/IntentionalAny.js';
 
 // constants
 const tandem = Tandem.ROOT;
 
 const circuitConstructionKitDcTitleStringProperty = CircuitConstructionKitDcStrings[ 'circuit-construction-kit-dc' ].titleStringProperty;
 
+function loggedMethod( originalMethod: IntentionalAny, _context: IntentionalAny ): () => void {
+
+  function replacementMethod( this: IntentionalAny, ...args: IntentionalAny[] ): void {
+    console.log( 'LOG: Entering method.' );
+    const result = originalMethod.call( this, ...args );
+    console.log( 'LOG: Exiting method.' );
+    return result;
+  }
+
+  return replacementMethod;
+}
+
+class Person {
+  private name: string;
+
+  public constructor( name: string ) {
+    this.name = name;
+  }
+
+  @loggedMethod
+  public greet(): void {
+    console.log( `Hello, my name is ${this.name}.` );
+  }
+}
+
+const p = new Person( 'Ron' );
+p.greet();
+
+declare function fnGood<const T extends readonly string[]>( args: T ): void;
+
+// T is readonly ["a", "b", "c"]
+fnGood( [ 'a', 'b', 'c' ] );
+
 simLauncher.launch( () => {
 
   const showCodapScreen = CCKCQueryParameters.codap;


```

</details>

We got everything working except for `export type *`, which fails our lint rules anyways.  We can add that in the future if necessary.

**Comment by samreid** [comment]
OK we updated the rest and I'll notify the team to `npm update` again.
