### ISSUE TITLE
Exported class name should match filename

### ISSUE THREAD

**Issue by marlitas** [phetsims/chipper#1395]
From https://github.com/phetsims/center-and-variability/issues/241 @samreid and I thought a lint rule to double check that exported class names match their filenames would be incredibly helpful in catching typos or unintentional mis-naming. We created the lint rule: `default-class-match-filename`

We ran the new lint rule and found 4 errors:
Results from chipAway: 
 - [x] quadrilateral: @jessegreenberg 1 errors in 1 files.
 - [x] scenery-phet: @pixelzoom 1 errors in 1 files.
 - [x] sound: @samreid 1 errors in 1 files.
 - [x] vegas: @pixelzoom 1 errors in 1 files.

We will turn this rule on, and manually turn it off for the erroring repos until it can be addressed.

**Comment by pixelzoom** [comment]
In the commits above, I fixed the name of the export, and removed the opt-out from package.json.

Imo, this rule is misnamed. This rule has to do with the name of the default export, not the "default class".  And in 2 of the 4 cases that were erroring, it was a functon (not a class) that was exported. `default-export-match-filename` would be a more appropriate name.  Back to @marlitas to consider a rename.

**Comment by marlitas** [comment]
> Seems like it would have been easier to address the 4 files that are misnamed, rather than opting out of the rule in 4 package.json files

I did not feel comfortable assuming which of the options was the correct name in each repo. Thanks for addressing it so quickly @pixelzoom. 

The file and rule rename was handled in the commit above. Closing this issue as completed.
