### ISSUE TITLE
Do not use PhetioObject, 'tandem', you probably meant PhetioObjectOptions, 'tandem'

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1396]
Do not use PhetioObject, 'tandem', you probably meant PhetioObjectOptions, 'tandem'

**Comment by samreid** [comment]
Implemented, @marlitas or @matthew-blackman can you please review?

**Comment by matthew-blackman** [comment]
Reviewed this with @marlitas and @samreid and we feel good about this. @samreid noted that he had to turn this lint rule off in two places where the PhetioObject was being intentionally used here, but fixed all other typos found by this rule. Closing.
