### ISSUE TITLE
generateDevelopmentStrings Underscore edge case

### ISSUE THREAD

**Issue by marlitas** [phetsims/chipper#1397]
While working on Center and Variability I ran into a bug when I used `grunt modulify`. The `center-and-variability_all.json` file had strange key names generated...
![image](https://github.com/phetsims/chipper/assets/42476338/9b63aa42-bbbe-44b5-b15f-ffbe8d3680bb)

We discovered this is because my local repo structure has an underscore in it:
`/Users/marlitas/my_code/PhET/phetsims/babel/center-and-variability/center-and-variability-strings_om.json`

And the regex in generateDevelopmentStrings assumed that only one underscore would be in a user's local path. 
`const localeRegex = /(?<=_)(.*)(?=.json)/;`

This has been addressed now by grabbing a substring of the path following the last forward or back slash. We tested this on Mac, and is working as expected, but would like to test on windows as well to confirm.

Assigning to @jbphet since he both uses windows and is familiar with the translation utility.

**Comment by jbphet** [comment]
I tested this on my Windows 11 Dell Precision 7560 by creating a directory called `temp_my_code`, cloning the minimum repos needed to build center-and-variability, and running `grunt modulify`.  The resulting composite strings file looks fine.  Here's a snapshot of the start of the `bn` strings, which @marlitas shows in here screenshot above:

![image](https://github.com/phetsims/chipper/assets/3082831/4cade6ca-f296-474b-8398-37e10fe8e884)

Does this give you what you need @marlitas?

**Comment by marlitas** [comment]
That looks great. Thanks for testing @jbphet! Closing as completed.
