### ISSUE TITLE
Provide validation for simFeatures only being in simFeatures.

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#1410]
Over in https://github.com/phetsims/number-line-integers/issues/119 I saw an accidental `supportsDynamicLocale` at the top level of `phet` in package.json, instead of in `simFeatures`. I think an assertion about that will help catch future mistakes more easily.

**Comment by zepumph** [comment]
Committed above and confirmed that number-line-integers correctly failed out because `supportsDynamicLocale` was in the `phet` object. I didn't find any other issues, but I'm running locale testing to confirm all sims load.

@marlitas can you please review?

**Comment by marlitas** [comment]
Overall the commit looks good to me. This was the only part that was a bit strange for me, and felt like it might not scale the best, but I do understand the intention. 

```js
// At this time, all arrays are assumed to only support strings
            assert && assert( _.every( simFeatureValue, value => typeof value === 'string' ), `string entry expected for ${simFeatureName}` );
```

It's probably fine, but I imagine that there may be a point in the future when that will need to change.

**Comment by zepumph** [comment]
Right. I totally agree. I don't want to overoptimize on a case that we don't know the details of at this time. I think it is best to error loudly for the new case, and to have the comment help provide the guidance for the next simFeature case. Closing
