### ISSUE TITLE
`grunt modulify` should run reportMedia

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#1412]
Noted over in https://github.com/phetsims/chipper/issues/1411#issuecomment-1847533479 ...

> reportMedia.js checks the license files.  It looks like `grunt modulify` is not calling reportMedia, and that is instead deferred until `grunt build`.  That seems way too late -- missing licenses should be reported when the image is added, which is when `grunt modulify` is run. 

So... Should `grunt modulify` be running reportMedia?  Assigning to the authors of modulify.js.

**Comment by samreid** [comment]
Running reportMedia after grunt modulify sounds reasonable to me, but I want to also note `reportMedia` also runs in the precommit hooks which is closer to the "when the image is added" phase. So I don't feel too strongly.

**Comment by zepumph** [comment]
Ok. So when I went to actually work on this, I actually ended up not agreeing with @jonathanolson here. I was thinking about prototyping assets, and how it could be annoying to have to have the license correct BEFORE even being able to test the sim. I'm really happy to be outvoted here, but perhaps it is enough that there is an error when running the command.

@jonathanolson what do you think?

**Comment by zepumph** [comment]
Also, I wasn't clear if your recommendation was to integrate report media logic into Modulify so that only the assets with licenses are modulified. Personally I think that is suave but overkill and likely a fair bit of work. It's just as easy to all or nothing it. I think people want to do the right thing, they just need the reminder.

**Comment by jonathanolson** [comment]
What about having this run during pre-commit hooks then? If that is when we want to catch it?

**Comment by zepumph** [comment]
That is a great idea. Generally this task is speedy, and I think would make a nice addition to the pre-commit hooks without too much overhead.

**Comment by jonathanolson** [comment]
https://github.com/phetsims/chipper/blob/af908a163b8761fd154be7c7612aa5412f9976ad/js/scripts/hook-pre-commit-task.js#L67-L77 seems like this would cover it. I'm not too familiar with the pre-commit hook code. @samreid or @zepumph, does this seem like it is already happening in the above code? Can we just close this issue?

**Comment by zepumph** [comment]
Ahaa! Good catch. yes that is it. Thanks for finding it, I had totally forgot.
