### ISSUE TITLE
New Lint Rule: Each source file should list at least one author annotation

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1414]
From a TODO in https://github.com/phetsims/projectile-data-lab/issues/7, we would like to check that each file has at least one author annotation.

**Comment by samreid** [comment]
I added the lint rule and enabled it for projectile-data-lab.  I temporarily enabled the rule project-wide to generate a chip-away report like so:

> grunt lint-everything --disable-eslint-cache --chip-away

The result was:

Results from chipAway: 
 - [ ] alpenglow: @jonathanolson 7 errors in 6 files.
 - [ ] aqua: @zepumph 7 errors in 7 files.
 - [ ] area-builder: @jbphet 2 errors in 2 files.
 - [ ] area-model-algebra: @jonathanolson 1 errors in 1 files.
 - [ ] area-model-decimals: @jonathanolson 1 errors in 1 files.
 - [ ] area-model-introduction: @jonathanolson 1 errors in 1 files.
 - [ ] axon: @samreid 5 errors in 5 files.
 - [ ] balancing-act: @jbphet 34 errors in 34 files.
 - [ ] balancing-chemical-equations: @pixelzoom 1 errors in 1 files.
 - [ ] bamboo: @samreid 3 errors in 3 files.
 - [ ] bending-light: @samreid 2 errors in 2 files.
 - [ ] blackbody-spectrum: @AgustinVallejo, @jbphet 1 errors in 1 files.
 - [ ] brand: @zepumph 4 errors in 4 files.
 - [ ] build-a-molecule: @jonathanolson 2 errors in 2 files.
 - [ ] build-an-atom: @jbphet 5 errors in 5 files.
 - [ ] chains: @jbphet 1 errors in 1 files.
 - [ ] charges-and-fields: @jonathanolson 1 errors in 1 files.
 - [ ] chipper: @jonathanolson 11 errors in 11 files.
 - [ ] circuit-construction-kit-common: @samreid 10 errors in 10 files.
 - [ ] concentration: @pixelzoom 1 errors in 1 files.
 - [ ] coulombs-law: @zepumph 2 errors in 2 files.
 - [ ] density-buoyancy-common: @jonathanolson 1 errors in 1 files.
 - [ ] density: @jonathanolson 3 errors in 3 files.
 - [ ] diffusion: @pixelzoom 1 errors in 1 files.
 - [ ] dot: @jonathanolson 3 errors in 3 files.
 - [ ] energy-forms-and-changes: @jbphet 2 errors in 2 files.
 - [ ] estimation: @jbphet 20 errors in 20 files.
 - [ ] expression-exchange: @jbphet 8 errors in 8 files.
 - [ ] faradays-electromagnetic-lab: @pixelzoom 1 errors in 1 files.
 - [ ] faradays-law: @jbphet 3 errors in 3 files.
 - [ ] forces-and-motion-basics: @jessegreenberg 1 errors in 1 files.
 - [ ] fraction-comparison: @samreid 1 errors in 1 files.
 - [ ] fraction-matcher: @jonathanolson 1 errors in 1 files.
 - [ ] gene-expression-essentials: @jbphet 1 errors in 1 files.
 - [ ] gravity-and-orbits: @samreid 2 errors in 2 files.
 - [ ] gravity-force-lab: @zepumph 1 errors in 1 files.
 - [ ] greenhouse-effect: @jbphet 9 errors in 9 files.
 - [ ] griddle: @samreid 2 errors in 2 files.
 - [ ] interaction-dashboard: @zepumph 2 errors in 2 files.
 - [ ] isotopes-and-atomic-mass: @jbphet 2 errors in 2 files.
 - [ ] joist: @zepumph 4 errors in 4 files.
 - [ ] kite: @jonathanolson 1 errors in 1 files.
 - [ ] make-a-ten: @marlitas 2 errors in 2 files.
 - [ ] mobius: @jonathanolson 1 errors in 1 files.
 - [ ] molecule-polarity: @pixelzoom 2 errors in 2 files.
 - [ ] molecule-shapes-basics: @jonathanolson 1 errors in 1 files.
 - [ ] molecule-shapes: @jonathanolson 1 errors in 1 files.
 - [ ] neuron: @jbphet 5 errors in 5 files.
 - [ ] nitroglycerin: @pixelzoom 2 errors in 2 files.
 - [ ] number-line-integers: @jbphet 1 errors in 1 files.
 - [ ] pendulum-lab: @jonathanolson 1 errors in 1 files.
 - [ ] perennial: @mattpen, @jonathanolson 24 errors in 24 files.
 - [ ] ph-scale-basics: @pixelzoom 1 errors in 1 files.
 - [ ] ph-scale: @pixelzoom 1 errors in 1 files.
 - [ ] phet-core: @jonathanolson 3 errors in 3 files.
 - [ ] phet-info: @zepumph 2 errors in 2 files.
 - [ ] phet-io-sim-specific: @samreid 21 errors in 21 files.
 - [ ] phet-io-website: @chrisklus 5 errors in 5 files.
 - [ ] phet-io-wrapper-classroom-activity: @zepumph 6 errors in 6 files.
 - [ ] phet-io-wrapper-haptics: @jessegreenberg 1 errors in 1 files.
 - [ ] phet-io-wrapper-lab-book: @zepumph 3 errors in 3 files.
 - [ ] phet-io-wrappers: @zepumph 32 errors in 32 files.
 - [ ] phet-io: @zepumph 1 errors in 1 files.
 - [ ] phet-lib: @jonathanolson 2 errors in 2 files.
 - [ ] phetcommon: @zepumph 2 errors in 2 files.
 - [ ] phetmarks: @jonathanolson 1 errors in 1 files.
 - [ ] phettest: @zepumph 2 errors in 2 files.
 - [ ] plinko-probability: [See #214](https://github.com/phetsims/phet-info/issues/214) 2 errors in 2 files.
 - [ ] projectile-motion: @matthew-blackman 1 errors in 1 files.
 - [ ] quake: @jbphet 3 errors in 3 files.
 - [ ] ratio-and-proportion: @zepumph 2 errors in 2 files.
 - [ ] reactants-products-and-leftovers: @pixelzoom 1 errors in 1 files.
 - [ ] rosetta: @jbphet 11 errors in 11 files.
 - [ ] scenery-phet: @jessegreenberg 30 errors in 30 files.
 - [ ] scenery: @jonathanolson 8 errors in 8 files.
 - [ ] shred: @jbphet 5 errors in 5 files.
 - [ ] skiffle: @jbphet 1 errors in 1 files.
 - [ ] states-of-matter: @jbphet 6 errors in 6 files.
 - [ ] studio: @zepumph 2 errors in 2 files.
 - [ ] sun: @jbphet 17 errors in 17 files.
 - [ ] tambo: @jbphet 8 errors in 8 files.
 - [ ] tandem: @zepumph 2 errors in 2 files.
 - [ ] tappi: @jessegreenberg 2 errors in 2 files.
 - [ ] trig-tour: @jessegreenberg 1 errors in 1 files.
 - [ ] twixt: @jonathanolson 2 errors in 2 files.
 - [ ] under-pressure: @samreid 2 errors in 2 files.
 - [ ] unit-rates: @pixelzoom 1 errors in 1 files.
 - [ ] utterance-queue: @jessegreenberg 2 errors in 2 files.
 - [ ] vegas: @pixelzoom 5 errors in 5 files.
 - [ ] wave-on-a-string: @jonathanolson 3 errors in 3 files.
 - [ ] weddell: @jbphet 3 errors in 3 files.
Fatal error: Lint failed

I don't know whether we will want to chip away at this or not. Or maybe just enable on a repo-by-repo basis as desired.

**Comment by samreid** [comment]
I wrote on slack dev-public:

> For Projectile Data Lab, we wanted to make sure each file was annotated with at least one @author annotation. To make sure we didn’t miss anything, we added a new lint rule, described in https://github.com/phetsims/chipper/issues/1414.  I also ran the rule across our project to see how our @author coverage was across all our repos. The chip-away report is in https://github.com/phetsims/chipper/issues/1414#issuecomment-1878806624. Should we do anything about this, discuss it in dev meeting, or just enable repo-by-repo (opt in) as desired?

**Comment by pixelzoom** [comment]
For anyone else wanting to work on fixes... The rule is author-annotation.js, and can be enabled in chipper/eslint/rules/.eslintrc.js

```ts
    // Each source file should list at least one author
    'author-annotation': 'off'
```

**Comment by pixelzoom** [comment]
My repos were addressed in the above commits.

**Comment by samreid** [comment]
Currently at 174 problems remaining across 37 repos. I have done the ones labeled for @samreid, so will self-unassign and I'll add it to the agenda for dev meeting in case we want to discuss further.

**Comment by marlitas** [comment]
I addressed my repos, unassigning.

**Comment by pixelzoom** [comment]
At 1/18/24 dev meeting, it was noted that all of the remaining cases are @jonathanolson @jbphet @matthew-blackman , so assigning to them to chip away.

**Comment by pixelzoom** [comment]
I took care of many of @jbphet's repos, there are still some to do.

I discovered that @jonathanolson had apparently addressed most of his repos, but didn't tag this issue in commit, and didn't change those repos off in the list.  That was at least 15 minutes of unnecessary work.

**Comment by pixelzoom** [comment]
I addressed all remaining repos, did a pull-all, and saw no errors with `grunt lint-everything --disable-eslint-cache`.  So I'm going to turn the `author-annotation` on.

**Comment by pixelzoom** [comment]
Slack#developer:

> PSA: I addressed all remaining violations of the ‘author-annotation’ lint rule.  The rule is now enabled for all repos. Where `@author` was missing, I used the person who created the file, based on git history.


Slack#DM to @jonathanolson @jbphet @mattpen:

> FYI… In localeInfo.js:
```js
IMPORTANT - MUST READ!!!
You may modify this file with new locale information. After modifying the file you must take the following steps:
1. Run ./updateLocaleInfo.js, so that the automatically generated files are also update
2. Notify the responsible developers for rosetta, weddell, yotta, and the website that localeInfo was updated.
```
> For https://github.com/phetsims/chipper/issues/1414, all .js and .ts source files are required to have at least 1 `@author `annotation.  So in https://github.com/phetsims/chipper/commit/4065e2fe8de8377bd25544992c6ffa19573c1d73, I added an `@author` annotation to  the template in updateLocaleInfo.js, then ran node chipper/js/data/updateLocaleInfo.js which updated localeModuleInfo.js. The comment at the top of localeModuleInfo.js now looks like this:
```js
/**
  * This file is automatically generated by js/data/updateLocaleInfo.js. Do not modify it directly.
  *
  * @author automatically generated by updateLocaleInfo.js
  */
```

**Comment by jbphet** [comment]
Thanks @pixelzoom for handling to many of these!
