### ISSUE TITLE
webpackGlobalLibraries are not included in 3rd party licenses

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#1419]
Since this refactor over in https://github.com/phetsims/chipper/issues/1409, himalaya and peggy have not been included in our licenses. 

We need to make sure to add these into `getLicenseKeys`.

**Comment by zepumph** [comment]
Alright. This was fixed above. Looks like licensing for these have not been in every sim with chipper sha after 10/5/23.

https://github.com/phetsims/chipper/commit/e15949391f2a4b06629d375161a3739a0e2f49b0

I'm not sure if an MR is warranted. Here. @jonathanolson do you recommend an MR?

**Comment by jonathanolson** [comment]
In the comments, it says:

> at this time we do not have a way to conditionally add these based on where they were imported/used

but it seems like we do have that ability. Things are very split up, but getLicenseKeys only use is in getThirdPartyLibEntries, which is only used in getAllThirdPartyEntries, which is only used in one place in buildRunnable.

Here, we have `webpackResult.usedModules` in buildRunnable, where we can check what was imported. Presumably we can just add the "usedModules" to those function calls? (Perhaps there is utility in having those separated out to a chain of files, but I'm fine if it gets collapsed to one).

**Comment by jonathanolson** [comment]
> @jonathanolson do you recommend an MR?

Yes, we don't want to ship things with missing license entries (as it is violating those licenses).

**Comment by zepumph** [comment]
https://github.com/phetsims/chipper/commit/f7bf09b70ab1ae26a360ea54018a1cd345227ccd

**Comment by zepumph** [comment]
Ok. That may have been the easiest MR I've ever done. 

Here are the commands:
```
  Maintenance.reset();
  m.checkBranchStatus();

  // https://github.com/phetsims/chipper/issues/1419
  // Broken in https://github.com/phetsims/chipper/commit/f7bf09b70ab1ae26a360ea54018a1cd345227ccd
  // fixed in https://github.com/phetsims/chipper/commit/fe0684e7df226c4b7606a04aadb50993bd4e9337
  m.createPatch( 'chipper', 'https://github.com/phetsims/chipper/issues/1419' );
  m.addNeededPatchesAfter( 'chipper', 'f7bf09b70ab1ae26a360ea54018a1cd345227ccd' );
  m.addPatchSHA( 'chipper', 'fe0684e7df226c4b7606a04aadb50993bd4e9337' );
  m.applyPatches();
  m.updateDependencies();
  m.deployReleaseCandidates();
  m.deployProduction();
```

It found 6 release branches:

```
center-and-variability 1.1
energy-skate-park 1.3
my-solar-system 1.3
number-line-distance 1.1
number-line-integers 1.2
number-line-operations 1.1
```

And all of these had the fix from main apply successfully. I am deploying RCs right now.

**Comment by zepumph** [comment]
**center-and-variability 1.1** (https://github.com/phetsims/chipper/issues/1419)

- [ ] [center-and-variability 1.1.4-rc.1](https://phet-dev.colorado.edu/html/center-and-variability/1.1.4-rc.1/phet/center-and-variability_all_phet.html)
- [ ] [center-and-variability 1.1.4-rc.1 phet-io](https://phet-dev.colorado.edu/html/center-and-variability/1.1.4-rc.1/phet-io/center-and-variability_all_phet-io.html?phetioStandalone)
- [ ] [center-and-variability 1.1.4-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/center-and-variability/1.1.4-rc.1/phet-io/wrappers/studio)

**energy-skate-park 1.3** (https://github.com/phetsims/chipper/issues/1419)

- [ ] [energy-skate-park 1.3.1-rc.1](https://phet-dev.colorado.edu/html/energy-skate-park/1.3.1-rc.1/phet/energy-skate-park_all_phet.html)

**my-solar-system 1.3** (https://github.com/phetsims/chipper/issues/1419)

- [ ] [my-solar-system 1.3.1-rc.1](https://phet-dev.colorado.edu/html/my-solar-system/1.3.1-rc.1/phet/my-solar-system_all_phet.html)
- [ ] [my-solar-system 1.3.1-rc.1 phet-io](https://phet-dev.colorado.edu/html/my-solar-system/1.3.1-rc.1/phet-io/my-solar-system_all_phet-io.html?phetioStandalone)
- [ ] [my-solar-system 1.3.1-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/my-solar-system/1.3.1-rc.1/phet-io/wrappers/studio)

**number-line-distance 1.1** (https://github.com/phetsims/chipper/issues/1419)

- [ ] [number-line-distance 1.1.2-rc.1](https://phet-dev.colorado.edu/html/number-line-distance/1.1.2-rc.1/phet/number-line-distance_all_phet.html)

**number-line-integers 1.2** (https://github.com/phetsims/chipper/issues/1419)

- [ ] [number-line-integers 1.2.3-rc.1](https://phet-dev.colorado.edu/html/number-line-integers/1.2.3-rc.1/phet/number-line-integers_all_phet.html)

**number-line-operations 1.1** (https://github.com/phetsims/chipper/issues/1419)

- [ ] [number-line-operations 1.1.1-rc.1](https://phet-dev.colorado.edu/html/number-line-operations/1.1.1-rc.1/phet/number-line-operations_all_phet.html)

**Comment by zepumph** [comment]
I found that all sims run and all now have himalaya's license in the source code. Running `deployProduction` now

**Comment by zepumph** [comment]
Maintenance release completed, I double checked the source code to see the license entries including himalaya. Closing
