### ISSUE TITLE
move common phetLibs to build.json

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#142]
The package.json files for sims have a lot of duplication for the phetLibs field. Consider moving the common libs (required by every sim) to build.json, and specify only the sim-specific phetLibs in package.json.

**Comment by pixelzoom** [comment]
Looks like the common (required) set of phetLibs is:

```
  "phetLibs": [
      "assert",
      "axon",
      "babel",
      "brand",
      "chipper",
      "dot",
      "joist",
      "kite",
      "phet-core",
      "phetcommon",
      "scenery",
      "scenery-phet",
      "sherpa",
      "sun"
    ]
```

vegas, vibe, and nitroglycerin are optional.  And sims would specific themselves and any dependent repos.  For example, phet-scale-basics/package.json would have this entry for phetLibs:

```
  "phetLibs": [
    "ph-scale-basics",
    "ph-scale",
    "nitroglycerin"
  ],
```

**Comment by pixelzoom** [comment]
I like how this is looking. Much easier to see what is specific to the sim, and much easier to add a repository required by all sims.

**Comment by pixelzoom** [comment]
The one downside is that phetLibs in package.json no longer matches the set of paths in config.js. But that is supposed to be addressed in https://github.com/phetsims/chipper/issues/33.

**Comment by pixelzoom** [comment]
Common phetLibs have been moved to chipper/build.json.  phetLibs in package.json now specifies only sim-specific dependencies (similar to preload and licenseKeys fields).  All package.json files have been modified accordingly.

To verify, inspect the diff for these files:

chipper/build.json
chipper/js/Gruntfile.js
phet-scale-basics/package.json (as an example, similar changes for all sim package.json)

Assigning to @aaronsamuel137 to verify.

**Comment by aaronsamuel137** [comment]
Looks good to me. Closing

**Comment by pixelzoom** [comment]
This change was announced in the Google Group at https://groups.google.com/forum/?fromgroups#!topic/developing-interactive-simulations-in-html5/JZLARg5DblY
