### ISSUE TITLE
build server needs to pull master before checking out shas

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/chipper#143]
We need to make sure that the repositories cloned on the build server are up to date before running ```grunt checkout-shas```. The simplest way to do this is probably to write a function that calls

```js
exec( 'git pull', '../' + repoName ), function() {...}
```

for every repo in dependencies.json.

This work should be done in build-server.js in chipper.

Assigning to @zepumph. Let me know if you have questions.

**Comment by aaronsamuel137** [comment]
Seems to work well over all, but not very error resistant if repos contains any keys that are not actually directories. Might be good to have a check in here to make sure the directory exists. You could use fs.existsSync() .

The main issue here is the whole build will fail if this fails. In fact the server will get stuck because "finished()" won't be called enough times for the callback to be called. I'm not sure what the best solution is here, but we'll want some way to recover gracefully from errors here.

**Comment by zepumph** [comment]
@aaronsamuel137 What do you think?

**Comment by aaronsamuel137** [comment]
There is a bug here. Your code:

```js
    for (var repoName in repos){
        if( repos.hasOwnProperty(repoName) ) {
          fs.exists( '../' + repoName, function( exists ) {
          if ( exists ) {
            winston.log( 'info', 'pulling from ' + repoName );
            exec( 'git pull', '../' + repoName, finished );
          }
          else {
            winston.log( 'Alert', repoName + "  is not a repo." );
            callback();
          }

          } );
        }
    }
  };
```

Won't work because of some interesting characteristics about Javascript. Basically, the var repoName will always be the last item of the object when it is used in the anonymous function passed to exists(). I encourage you to read up about this here: http://robertnyman.com/2008/10/09/explaining-javascript-scope-and-closures/ 

For now I have fixed some of these issues since I was working on related issues last night.
