### ISSUE TITLE
custom eslintrc files don't work in sub directories

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#1430]
I found in aqua that having an `.eslintrc.js` file in a sub directory that extends over to a chipper one fails. This is because of relative paths AND because it expects that the HTMl plugin exists in the repo you are in, not over in chipper. This is at least the case with my webstorm. I think the answer is to put everything into the package.json with overrides with glob patterns. That isn't pretty, but perhaps it is best. 

![image](https://github.com/phetsims/chipper/assets/6856943/648dd966-77b8-416e-88ac-85bcc63b5a4c)

I'd like to discuss with @samreid a bit, because even when I fixed this, I still had Webstorm's TypeScript thinking that fuzz-lightyear was Node code (which I believe is coming from eslint config options, but I'm not sure).

**Comment by samreid** [comment]
There is an option to choose how to resolve plugins: https://eslint.org/docs/latest/use/command-line-interface#--resolve-plugins-relative-to

I also saw that eslint is moving to a better strategy for configuration files, called "flat" "new" files like eslint.config.js which are described in https://eslint.org/docs/latest/use/configure/configuration-files-new, and may have different discovery rules.

**Comment by zepumph** [comment]
@samreid and I met. We now understand the two problems here:

1. hard coding `--resolve-plugins-relative-to=../chipper/`, means that nested eslintrc files that serve as the root end up having the wrong relative path. This means that, for now, we don't support nested eslintrc files. Otherwise we need to tell everyone to make that option hard coded with an absolute path. It is totally fine to punt on this, since the above commits easily move nested config files into the top package.json with `overrides`. 
2. The TypeScript type checking error with setTimeout in fuzz-lightyear.ts
    - To reproduce, remove the `window.` from setTimeout, then it takes the setTimeout for Node's d.ts file and causes this error:
    
           Type 'Timeout' is not assignable to type 'number'.
    
    - This seems to be because of the auto-discovery settings for TypeScript, as described here: https://stackoverflow.com/a/70856713/3408502. It will be something to think about when we move to using TypeScript in our NodeJS code and build tools, over in https://github.com/phetsims/chipper/issues/1272.
    - For now, it is easy to keep window.setTimeout(), and we see that this behavior doesn't happen in a place like `joist/`, just in aqua where there is typescript code AND other js code close by that is NodeJS code.
