### ISSUE TITLE
write grunt deploy-production task

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/chipper#144]
We discussed this during translation meeting on 5/28/15.

This simplest option is to have a task ```grunt deploy-production``` that is run after ```grunt build```. The deploy production task would then look in build/dependencies.json to find the correct version and shas to send to the build server to build and deploy.

**Comment by pixelzoom** [comment]
@aaronsamuel137 is this done?

**Comment by aaronsamuel137** [comment]
Yep. It's been used by multiple people, so I think it is safe to close this issue.
