### ISSUE TITLE
Bug in paths in copySupplementalPhetioFiles

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1455]
During https://github.com/phetsims/chipper/issues/1437 I observed this code:

https://github.com/phetsims/chipper/blob/62f957f7f48183ccb132daaf61712634e52e6abd/js/grunt/copySupplementalPhetioFiles.js#L709-L712

Note that it ends up outputting to ../chipper/density/build/phet-io rather than ../density/build/phet-io, because it doesn't have enough '..'. This is what has been causing all the spurious folders like this in chipper:

<img width="435" alt="image" src="https://github.com/user-attachments/assets/ceee532a-6279-42bd-96a6-f2e8a816f9a8">

**Comment by samreid** [comment]
Fixed and tested via `grunt` then testing http://localhost/density/build/phet-io/wrappers/migration/ in density. @zepumph would you like to spot check review? Should be quick.

**Comment by zepumph** [comment]
Ahh! You found it!! This has been on my list for a year but I never made time for it. Thank you so much.
