### ISSUE TITLE
Use process.cwd() instead of __dirname

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1456]
In https://github.com/phetsims/chipper/issues/1437 some of the relative paths are incorrect when running from chipper/dist/chipper/js vs directly from chipper/js. It seems since programs are supposed to be run from one of the checked out repos, we can use `process.cwd()` instead.  Note that as I was investigating this, I found and fixed a relative __dirname problem in https://github.com/phetsims/chipper/issues/1455.

Local tests are working well here, I tested a build with __dirname and process.cwd and they were identical except for timestamps and string key ordering (which I guess is nondeterministic).

I'd like to push to main and see how it runs on CT and on my windows machine.

**Comment by samreid** [comment]
I wrote to slack dev-public:

> As part of https://github.com/phetsims/chipper/issues/1456, #faradonkey replaced __dirname with process.cwd() in about a dozen places. This should not change any behavior of any of the chipper or perennial tasks. After you pull, please notify us here or in #faradonkey if you spot any trouble. We pushed to main so it can be tested on CT now.

**Comment by zepumph** [comment]
It is annoying to need to tie the top level CWD to those scripts. I wonder if we can get around that at all in the same kind of way that we do for some shell scripts like this, similar to using __dirname:


https://github.com/phetsims/perennial/blob/e6837a4a2b637f3a39cdf1ab02ac857106592085/bin/for-each.sh#L36-L39.

I guess this is a general problem with a transpile step. That said. I wish that we didn't need to hard code one cwd for all build tool resources. Ideally in something more long term, like Deno we wouldn't need this constraint.

**Comment by zepumph** [comment]
I think for me I'd like to revert this if we don't end up going with a custom transpiler program. Let's have an opportunity to discuss the main direction before closing this.

**Comment by samreid** [comment]
Reverted since this change is not necessary for https://github.com/phetsims/chipper/issues/1459, closing.
