### ISSUE TITLE
checkNodeVersion should probably be unified and made consistent

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1458]
Discovered in https://github.com/phetsims/chipper/issues/1437, we have 2 copies of checkNodeVersion.js and they do not match requirements. What requirement is correct? Can we just use the perennial-alias copy?

**Comment by samreid** [comment]
We recently updated servers to Node 20.18. Can we encode that as the minimum requirement?

**Comment by samreid** [comment]
- [ ] Coalesce into the perennial-alias one (delete the chipper one)
- [ ] Update the required version to 20.18

**Comment by zepumph** [comment]
I found a previously installed version of node mine from this fall and then ran npm update in perennial. Here is the output in many eslint-related items:

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@stylistic/eslint-plugin@2.8.0',
npm WARN EBADENGINE   required: { node: '^18.18.0 || ^20.9.0 || >=21.1.0' },
npm WARN EBADENGINE   current: { node: 'v18.16.0', npm: '9.5.1' }
npm WARN EBADENGINE }
```

So I think 18.18 is the best bet. We could also just check either based on the major version of the running node. No strong preference, but I think 18.18 is probably easiest to set up so I'll start there.
