### ISSUE TITLE
build server should check if version directory exists and mkdir if not

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/chipper#146]
build-server.js currently fails if the version directory doesn't exist. We need to add another step before trying to copy the files to check if the version directory exists and if not, run mkdir.

See this part of the code to see where the files are trying to be copied to:

```js
 exec( 'cp build/* /data/web/htdocs/phetsims/sims/html/' + simName + '/' + version + '/', simDir, ...

```

Assigning to @zepumph

**Comment by aaronsamuel137** [comment]
Looks ok, but fails with the following message when running on the server:

```bash
info: running command: IF exist /data/web/htdocs/phetsims/sims/html/molecules-and-light/1.1.0-dev.2/ ( echo /data/web/htdocs/phetsims/sims/html/molecules-and-light/1.1.0-dev.2/ exists ) ELSE ( mkdir /data/web/htdocs/phetsims/sims/html/molecules-and-light/1.1.0-dev.2/ && echo /data/web/htdocs/phetsims/sims/html/molecules-and-light/1.1.0-dev.2/ created)

/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `IF exist /data/web/htdocs/phetsims/sims/html/molecules-and-light/1.1.0-dev.2/ ( echo /data/web/htdocs/phetsims/sims/html/molecules-and-light/1.1.0-dev.2/ exists ) ELSE ( mkdir /data/web/htdocs/phetsims/sims/html/molecules-and-light/1.1.0-dev.2/ && echo /data/web/htdocs/phetsims/sims/html/molecules-and-light/1.1.0-dev.2/ created)'

error: error running command: IF exist /data/web/htdocs/phetsims/sims/html/molecules-and-light/1.1.0-dev.2/ ( echo /data/web/htdocs/phetsims/sims/html/molecules-and-light/1.1.0-dev.2/ exists ) ELSE ( mkdir /data/web/htdocs/phetsims/sims/html/molecules-and-light/1.1.0-dev.2/ && echo /data/web/htdocs/phetsims/sims/html/molecules-and-light/1.1.0-dev.2/ created). build aborted.
```

I would recommend using a similar pattern as is already used in this file instead of executing bash commands directly:

```js
  fs.exists( buildDir, function( exists ) {
    if ( !exists ) {
      fs.mkdir( buildDir, function( err ) {
        if ( !err ) {
          writeDependenciesFile();
        }
      } );
    }
    else {
      writeDependenciesFile();
    }
  } );
```

You can also use fs.existsSync() for a version of exists() that runs synchronously.

If you do end up using the same pattern, it is a good idea to refactor the code into reusable method that can be used in both cases.

**Comment by zepumph** [comment]
@aaronsamuel137 What do you think?

**Comment by pixelzoom** [comment]
Out of curiosity... What does build server do if the directory already exists? Does it stop? If not, how do we know that we're not accidentally overwriting something because someone forgot to update the sim version number?

**Comment by aaronsamuel137** [comment]
At this point the build server will overwrite. I am imaging a code review process where we flesh out things like this before we run this on our production server.

**Comment by aaronsamuel137** [comment]
Looks pretty good for now. Closing
