### ISSUE TITLE
Webstorm: Add TypeScript -> "sort imports by module" to code style

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#1462]
From discussion today https://github.com/phetsims/chipper/issues/1461. If we add this to the code style and optimize all imports, then things will be much cleaner.

**Comment by zepumph** [comment]
Update to the code style in https://github.com/phetsims/phet-info/commit/b1b066a84dcc6ffc4452b49ecbf3f1d51b8fa078. Everything else is just auto formatting in `/js` dirs. @samreid can you give me a spot check?

**Comment by samreid** [comment]
I applied the new style, and saw that it correctly updated my settings like so:

<img width="1146" alt="image" src="https://github.com/user-attachments/assets/9895f389-c2af-4308-aefe-df20220f4215">

However, when navigating to bamboo, and pressing format code => optimize imports, I saw lots of shuffled imports. Let's check in with @zepumph

**Comment by zepumph** [comment]
I believe that perhaps this was incomplete in the commits above. I just saw that scenery/ wasn't committed to at all. My settings are the same as yours above. Can you please redo the review but only for files in scenery, and see if it is correct for you. If so, then I will just to another pass to be sure I was complete everywhere.

**Comment by samreid** [comment]
Still seeing changes in scenery when formatting scenery, let's check this synchronously.

**Comment by zepumph** [comment]
We chatted sync and are seeing the same behavior. The directory reformatter in webstorm keeps leaving out some files. I'll try again and attempt to get better coverage.

**Comment by samreid** [comment]
I swamped the issue with commits, please be aware there are comments that got hidden above.

**Comment by zepumph** [comment]
I'm not sure why my webstorm was not able to optimize all files, but @samreid was able to run it once from the main checkout dir. I checked on some of the repos and everything looks great. Closing
