### ISSUE TITLE
Convert repo to TypeScript

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#1465]
From https://github.com/phetsims/chipper/issues/1464, this issue is just to hold commits where we convert files to typescript.

**Comment by samreid** [comment]
All issues addressed or moved elsewhere, @zepumph want to spot check or work on anything else as part of this issue? If not, feel free to close.

**Comment by zepumph** [comment]
I looked through usages of ts-expect-error and IntentionalAny. The main work left is in side issues with the exception of using optionize. I add that over to #1523.
