### ISSUE TITLE
Lint Rule no-floating-promises takes a long time

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1466]
From #1356, we observed:

> TIMING=1 npx eslint --rulesdir ../chipper/eslint/rules/ --resolve-plugins-relative-to ../chipper --no-error-on-unmatched-pattern --ignore-path ../chipper/eslint/.eslintignore --format=json --ext .js,.jsx,.ts,.tsx,.mjs,.cjs,.html ../density/

Rule                                    | Time (ms) | Relative
:---------------------------------------|----------:|--------:
@typescript-eslint/no-floating-promises |    62.101 |    40.2%
require-property-suffix                 |    14.776 |     9.6%
no-redeclare                            |     4.109 |     2.7%
no-implicit-globals                     |     3.368 |     2.2%
no-unmodified-loop-condition            |     3.359 |     2.2%
@typescript-eslint/no-unused-vars       |     2.987 |     1.9%
@typescript-eslint/no-redeclare         |     2.866 |     1.9%
no-unused-vars                          |     2.510 |     1.6%
no-useless-return                       |     2.285 |     1.5%
bad-text                                |     1.988 |     1.3%

**Comment by samreid** [comment]
We can all afford 62ms, closing.

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.
