### ISSUE TITLE
Speed up lint-everything

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1468]
lint-everything slowed down in https://github.com/phetsims/chipper/issues/1356 since (a) project references per-repo adds overhead, and (b) couldn't fit all sims in memory at once.  Let's see if we can speed it up again. Parts like #1467 and #1466 may help too.

also:
- [ ] grunt lint-everything --disable-eslint-cache prints "cache file deleted" over and over. Instead, just delete the cache file once, then let everything run.

**Comment by samreid** [comment]
ESLint does not have good support for project references. I tried the proposal in `https://github.com/typescript-eslint/typescript-eslint/issues/2094` and `https://github.com/typescript-eslint/typescript-eslint/pull/6754` for adding 

```js
  parserOptions: {
    EXPERIMENTAL_useProjectService: true,
  },
```

but I could not get it to work. Running multiple repos with different parserOptions.projects overwhelms the memory and in https://github.com/phetsims/chipper/issues/1356 I split it up into worker threads, but it takes 5+ minutes even when little has changed.

At the moment, we could specify an eslint-specific tsconfig.json that allows multiple repos to fit in memory and use shared type information. The main problem with this is it would be redundant with our modular project references tsconfigs. Furthermore, when we start specifying different behavior (node vs browser), we would need a way to accommodate that in the eslint-specific tsconfig.

Running `grunt lint --disable-eslint-cache` in density with the specific tsconfig takes about 4 seconds. With the full one it is about 12 seconds.  A cached one with no changes is about the same for each. A project-references one may also be slow.  With the way our linting is set up, I don't see a practical way to say "when linting one repo, use the repo-specific tsconfig, when linting more than one repo in the same unit, use the combined config". We could likely make that happen if we used .eslintrc.js files which can dynamically check what's happening. But that is more complex. And we may want to do that after switching to the flat config.

I also experimented with coming up with a config file dynamically that would be for the lint-everything, but paths were messy and difficult to match the rules with the files.

So to speed up lint-everything and lint-all, and to restore prior behavior to lint-everything such as --chip-away and better behavior for disable-eslint-cache, the recommendation for this issue is:
* revert changes to perennial/Gruntfile/lint-everything
* restore the prior chipper/tsconfig/all/tsconfig.json as chipper/tsconfig/eslint/tsconfig.json and point to it from parserOptions.project.

Let's consult with @zepumph soon.

**Comment by samreid** [comment]
I implemented the recommendation here and in #1470 since I already had it in my working copy. But I left a placeholder in each package.json to make it easy to experiment or revert in the future.

**Comment by samreid** [comment]
We should look into https://typescript-eslint.io/packages/parser#projectservice

**Comment by samreid** [comment]
We used `projectService` and rewrote lint.ts so that a cached lint-everything takes around 8 seconds on my machine. However, with `--disable-eslint-cache` it is more like 7 minutes, but in that case we are fighting with a memory limit. I feel this issue is covered by TODOs in https://github.com/phetsims/chipper/issues/1451, so let's close and continue there.

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.

**Comment by samreid** [comment]
Fixed in the branch, will be merged with https://github.com/phetsims/chipper/issues/1484, closing.
