### ISSUE TITLE
For linting, switch from parserOptions.project to parserOptions.projectService

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1473]
According to ESLint, parserOptions.projectService is now recommended over parserOptions.project because it is simpler and more predictable. They also say:

> We now recommend using [projectService](https://typescript-eslint.io/packages/parser/#projectservice) instead of project for easier configuration and faster linting.

**Comment by samreid** [comment]
After changing my working copy to use solely projectService, I still get this error on lint-everything:

```
~/phet/root/buoyancy$ time grunt lint-everything --disable-eslint-cache
Running "lint-everything" task
(Forwarding task to perennial)
Running "lint-everything" task
Cache file '../chipper/eslint/cache/.eslintcache' deleted successfully
[........................................] 100.00%


/Users/samreid/phet/root/solar-system-common/js/SolarSystemCommonConstants.ts
  0:0  error  Parsing error: ESLint was configured to run on `/Users/samreid/phet/root/solar-system-common/js/SolarSystemCommonConstants.ts` using `parserOptions.project`:

That TSConfig uses project "references" and doesn't include `/Users/samreid/phet/root/solar-system-common/js/SolarSystemCommonConstants.ts` directly, which is not supported by `parserOptions.project`.
Either:
- Switch to `parserOptions.projectService`
- Use an ESLint-specific TSConfig
See the typescript-eslint docs for more info: https://typescript-eslint.io/troubleshooting/typed-linting#are-typescript-project-references-supported

```

I cannot explain it. Not sure what to try, but I see projectService related fixes in newer 8.x series eslint, so I'll try upgrading.

**Comment by zepumph** [comment]
I believe the above was fixed with eslint 9. @samreid I think this issue is ready to close. We are now using projectService:true in our linting. Is there anything else here?
