### ISSUE TITLE
generate-phet-io-api should transpile only what is needed

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#1477]
From working with swc a bit in https://github.com/phetsims/chipper/issues/1354, we don't want to have to transpile everything to generate APIs (like BASE when generating Density).

Also can we just tap into a running watch process to say that we don't need to re-transpile in certain cases.

**Comment by samreid** [comment]
> Also can we just tap into a running watch process to say that we don't need to re-transpile in certain cases.

Let's also check performance before optimizing. If swc on <15 repos is fast enough (200ms?) then we can just do it every time.
