### ISSUE TITLE
Lint rules and code patterns for typescript node code

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#1482]
Since adding typescript node JS code in https://github.com/phetsims/chipper/issues/1437, I think there may be good questions to answer about how our linting system or code style may want to differ. We started parsing this with some rule changes here:

https://github.com/phetsims/chipper/blob/93d830f215be91c9ed094f40ae785cccdfa4a48e/eslint/node.eslint.config.mjs#L13-L29

But there is still more to do, and I don't want these questions to block pattern making/propagation or converting files to TypeScript. Let's keep them here!

**Comment by zepumph** [comment]
- [ ] Auto imports in typescript files in node code always include the .js suffix. But with require statements we often omit the `.js` suffix. Should we be consistent, and always include .js like in sim code? Also sometimes I see it imports `.ts`, probably we never want that.

**Comment by zepumph** [comment]
14 usages of `@ts-expect-error` in chipper/

**Comment by zepumph** [comment]
- [ ] `phet/no-object-spread-on-non-literals` allowed in node code?

**Comment by samreid** [comment]
@zepumph and I reviewed chipper and agreed this issue is ready to close.
