### ISSUE TITLE
Update lint.js now that we are using ESLint 9

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1484]
From https://github.com/phetsims/chipper/issues/1451 there were many TODOs to upgrade the lint process. Most of this should be done before #1415.

**Comment by zepumph** [comment]
From https://github.com/phetsims/chipper/issues/1469 here are some checklist items:

- [ ] Should lint-all do multiple in one batch? Or separate? Do we still want progress bar?
- [ ] grunt lint-everything no longer works with --chip-away
- [ ] lint-all is taking longer

**Comment by samreid** [comment]
I'll run performance tests of using the API or processes on cached or --clean, on mac and windows. That will help us know for sure whether we need both implementations.

**Comment by samreid** [comment]
```
mac
cache is fresh - main algorithm => 9sec
cache is fresh - spawn only => 52sec
--clean - spawn only => 4m22s
--clean - API only => 54% then crash at 2m40s

windows
cache is fresh - main algorithm => 16sec
cache is fresh - spawn only => 63s
--clean - spawn only => 4m23s
--clean - API only => 54% then crash at 4m14s
```

**Comment by zepumph** [comment]
Design goals:
1. No crashing possible
2. Cleaner implementation than one file with two implementations

Next steps:
1. Let's go all in on the Node CLI (API), and use sub processes to keep heaps for overloading. Lets start with 50 repos per sub process.
2. We can run multiple sub processes at once (multi threading)
3. We can remove the npx implementation
4. Keep the CLI running a single repo at a time, with a cache file per repo.

**Comment by zepumph** [comment]
- [ ] I think we should keep the ability to have debug logging, maybe turned on via the `--verbose` flag?  What do you think?

```diff
Subject: [PATCH] add authors, https://github.com/phetsims/chipper/issues/1502
---
Index: js/grunt/lint.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/grunt/lint.ts b/js/grunt/lint.ts
--- a/js/grunt/lint.ts	(revision 9c6461e0c47a003490903950a5c25b4448071083)
+++ b/js/grunt/lint.ts	(date 1730747840002)
@@ -175,7 +175,8 @@
     cache: true,
     cacheLocation: path.resolve( getCacheLocation( repo ) ),
     fix: options.fix,
-    errorOnUnmatchedPattern: false
+    errorOnUnmatchedPattern: false,
+    flags: [ '--debug' ]
   };
 
   // Create ESLint instance

**Comment by samreid** [comment]
- [ ] delete chip away
- [ ] use number of processors to estimate batching

**Comment by samreid** [comment]
Ready for review in the chipper and perennial-alias branches `lint-batches-chipper-1484`. Note there is one remaining TODO that I could not figure out how to solve and need help on.

**Comment by zepumph** [comment]
- [ ] Even before this patch, I was feeling like js/eslint/ was getting a bit unweildy. I think we should make a subdir called `config/`, and keep linting module and running code that the top level.
- [ ] This morning I fixed the "reopen issues with TODOs" task and it will likely yield an annoying merge conflict, let's merge main into the branches together.
- I committed a change that removed cleanOnly and can just run a function. I'm unsure if cleaning tsc is needed from lint, but I like keeping it for now. 
- I ran `grunt lint --clean --all` and it took 2 minutes before this commit https://github.com/phetsims/perennial/commit/8bc2e5238d298ba007ec367f2596e1b98a67cae9

**Comment by zepumph** [comment]
```

 mjkauzmann ~/PHET/git/perennial-alias (lint-batches-chipper-1484)
 $ time grunt lint --all --clean
Running "lint" task
processes 4
Done.

real    2m18.486s
user    0m0.061s
sys     0m0.061s

 mjkauzmann ~/PHET/git/perennial-alias (lint-batches-chipper-1484)
 $ time grunt lint --all --clean
Running "lint" task
processes 15
Done.

real    1m56.170s
user    0m0.060s
sys     0m0.062s

```

**Comment by zepumph** [comment]
I added 6 TODOs as part of the review. @samreid and I merged to main, and the rest is in his court. Thanks SR!1

**Comment by samreid** [comment]
TODOs addressed, --processes added which sets the maximum number of allowable processes. We are merged to main. Feature branches deleted. Closing.

**Comment by samreid** [comment]
On second thought, I'm very confused about all the entry points that are allowed to pass through LintOptions. The default occurs in several places. Would be good for @zepumph to review and comment.

**Comment by zepumph** [comment]
@samreid and I agree it is awkward, and `getLintOptions` shouldn't always provide defaults that are duplicated with the module defaults. We will make a separate side issue.
