### ISSUE TITLE
Import json directly instead of `grunt.file.readJSON`

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#1491]
From https://github.com/phetsims/chipper/issues/1436, let's do something like this instead:

```ts
( async () => {
  console.log( 'loading' );
  try {
    const json = await import( './json.json');
    console.log( json.hi );
  }
  catch( e ) {
    console.log( 'e', e ); // Transform failed with 1 error:
  }
} )();
```

Following steps in here: https://stackoverflow.com/questions/48911030/import-json-in-typescript

Looks like we just need to add "resolveJsonModule": true to support it. Let's do that in tsconfig-node for now, since we don't have `esModuleInterop` turned on in sim code at the moment.

**Comment by zepumph** [comment]
Or we can just use the `loadJSON()` function in perennial.

**Comment by zepumph** [comment]
There are 30 usages or so of `grunt.file.readJSON`

**Comment by samreid** [comment]
Fixed, closing.
