### ISSUE TITLE
root.eslint.config should use all node options for Gruntfile and eslint configs

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#1493]
Promoting a TODO from https://github.com/phetsims/chipper/issues/1464.

Right now it just added node-based language options. It should do more than just this:

https://github.com/phetsims/chipper/blob/9d03567f930d0580e10f416671e6e09eed3edcb8/eslint/root.eslint.config.mjs#L47-L51

**Comment by zepumph** [comment]
This was done by moving getNodeConfiguration to a separate file. Does this seem reasonable to you @samreid?

**Comment by samreid** [comment]
Does this part belong here in the way getNodeConfiguration is being reused?

https://github.com/phetsims/chipper/blob/a433593afd4fcf15d99fee4c7265db99986d6f8b/eslint/getNodeConfiguration.mjs#L29-L39

**Comment by zepumph** [comment]
Completed above with collaboration from @samreid.
