### ISSUE TITLE
Move eslint rules blocks to separate files

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#1496]
While working on https://github.com/phetsims/chipper/issues/1492, @samreid and I felt like root.eslint.config would be much nicer if it didn't have thousands of lines of rules breaking it up. I smell a side issue!

**Comment by samreid** [comment]
Moved. @zepumph want to review or recommend better filenames? Feel free to close.

**Comment by zepumph** [comment]
This is amazing. Thanks!
