### ISSUE TITLE
licensing URL for HTML5 sims?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#150]
HTML deliverables have this comment header (for example), generated by afterRequirejsBuild.js, circa line 205.

```
<!--
hookes-law
Copyright 2002-2015, University of Colorado Boulder
PhET Interactive Simulations
Licensed under GPLv3
http://phet.colorado.edu/en/about/licensing
-->
```

Does the URL http://phet.colorado.edu/en/about/licensing pertain to HTML5 sims? For example, it has language like this:

> The executable versions of all PhET Interactive Simulations by PhET, University of Colorado (the *.jar files, the *.jnlp files, the *.swf files) are licensed under a Creative Commons Attribution 3.0 United States License,  ....

... which doesn't mention the HTML5 executables.

Is this URL correct? Does the webpage need to be updated? Is there a different URL for HTML5 sims?

**Comment by ariel-phet** [comment]
This should be the url:

http://phet.colorado.edu/en/html-terms-privacy-and-licensing

That is the url that is linked in published sims like Balancing Act

**Comment by ariel-phet** [comment]
BTW - the only way to get to that url obviously is currently from an HTML5 sim.

**Comment by pixelzoom** [comment]
Fixed, closing.
