### ISSUE TITLE
Move contents of `chipper/js/grunt/Gruntfile` into `gruntMain`

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#1502]
Don't forget about GruntfileTests too.

**Comment by samreid** [comment]
1. Delete gruntMain. 
2. mv Gruntfile to gruntMain.

Keep history

**Comment by samreid** [comment]
I moved as described above, not sure what to do about GruntfileTests. @zepumph can you please advise?

**Comment by zepumph** [comment]
Amazing! Thanks so much.

>I moved as described above, not sure what to do about GruntfileTest. This worked itself out and now we have `test-exec-sync`
