### ISSUE TITLE
Convert node to sage/tsx in bash scripts that have the word "node" in them (we can ignore yotta)

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1506]
From https://github.com/phetsims/chipper/issues/1481. Convert node to sage/tsx in bash scripts that have the word "node" in them (we can ignore yotta)

Start with daily-grunt-work.sh as a warm-up.

**Comment by zepumph** [comment]
sage run doesn't currently support node options, for example it errors on this patch:

```diff
Subject: [PATCH] Just pull all always, https://github.com/phetsims/phettest/issues/14
---
Index: bin/main-pull-status.sh
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/bin/main-pull-status.sh b/bin/main-pull-status.sh
--- a/bin/main-pull-status.sh	(revision 4892575778ce7afc8bbaf6058f5b37662767b398)
+++ b/bin/main-pull-status.sh	(date 1730762253961)
@@ -9,4 +9,4 @@
 #====================================================================================================
 
 cd perennial
-node --no-warnings js/scripts/main-pull-status.js
+./bin/sage run --no-warnings js/scripts/main-pull-status.js

**Comment by zepumph** [comment]
I'd like to touch base with @jonathanolson about the yotta half of these. Some of them look to use perennial dependencies, but I want to ask how he'd like the entry points to behave. I invited him to our standup this morning.

**Comment by zepumph** [comment]
@jonathanolson likes converting the `node` runnable in yotta scripts too. Let's do that. Yotta already has a dependency on perennial.

**Comment by zepumph** [comment]
two new issues:
1. yotta specific sage run conversion
2. yotta scripts to be run by phet-admin instead of olsonjb

**Comment by zepumph** [comment]
Alright. We are ready to close. Everything else is in side issues.
