### ISSUE TITLE
old releases re-create chipper/eslint/cache/

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#1508]
Lint on release branches (like with grunt rc), and then when you checkout main again, you still have a chipper/eslint/cache/ directory. Let's fix this.

**Comment by zepumph** [comment]
Current fix just deletes the chipper/eslint/ dir when running lint. This seems acceptable to me only because I also added back in chipper/eslint/ to the gitignore on main.

**Comment by zepumph** [comment]
@samreid, any thoughts from here? Feel free to close.

**Comment by samreid** [comment]
Looks good to me, thanks. Does it need to be cherry-picked into recent RC branches?
