### ISSUE TITLE
output-js-project broken on 1.3.0

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#1509]
I just found a bug on main that snuck into the most recent release of color vision. Transpiling will be project for any maintenance releases that it will get.

If you see here: https://github.com/phetsims/chipper/blob/0dbc5d719a7cb5c94ffc7f4f3c0f27fe74fc984c/js/grunt/tasks/output-js-project.ts

There was a copy paste error, and output-js-project should be transpiling all phet libs, but is only doing the single repo. 

I'll make an RC with the change patched in, and we can go from there.

**Comment by zepumph** [comment]
This is the commit with the copy paste error: 

https://github.com/phetsims/chipper/commit/901491de6f30e92001d6517a4bb02ab111f7c2ca

Here is what the code should be:

```js
      const getPhetLibs = require( './getPhetLibs' );
      transpiler.transpileRepos( getPhetLibs( getRepo() ) );
```

**Comment by zepumph** [comment]
There two lines confirmed that only color vision and unit rates were affected

```js
await m.createPatch( 'chipper', 'https://github.com/phetsims/chipper/issues/1509', 'outputJSProject' );
  await m.addNeededPatchesAfter('outputJSProject', '901491de6f30e92001d6517a4bb02ab111f7c2ca')
```

**Comment by zepumph** [comment]
MR changes are complete and RCs have been created:

https://phet-dev.colorado.edu/html/color-vision/1.3.1-rc.1/phet/color-vision_all_phet.html
https://phet-dev.colorado.edu/html/unit-rates/1.1.0-rc.3/phet/unit-rates_all_phet.html


For QA: Can you please spend 5-10 minutes spot checking color vision before I move to production. There should be absolutely no changes from the final publication from a week or two ago. My change was just to support future maintenance releases. Thanks!

**Comment by KatieWoe** [comment]
When testing color vision, I had an instance of the keyboard nav disappearing repeatedly while moving a slider. This was on the red light slider on the second screen. I didn't see this on published, but after coming back and refreshing the rc I haven't been able to reproduce it again.

**Comment by Nancy-Salpepi** [comment]
Using mac + safari I didn't see any issues while testing Color Vision or Unit Rates.

**Comment by zepumph** [comment]
Excellent. Thanks so much. Given my changes, I'm not worried at all about that @KatieWoe. Thanks for reporting. Proceeding with production release of color-vision.
