### ISSUE TITLE
format of dependencies.json vs 3rd-party license info in html deliverable

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#151]
Third-party dependencies appear as an HTML comment near the top of the html deliverable, for example:

```
<!--
Third-party licenses:
{
  "almond-0.2.9": {
    "text": [
      "almond 0.2.9",
      "Copyright (c) 2011-2014, The Dojo Foundation All Rights Reserved."
    ],
    "license": "The MIT License",
    "projectURL": "https://github.com/jrburke/almond",
    "notes": "Allows a RequireJS-based simulation to run in its compiled (smaller, faster) form"
  },
  ...
}
```

dependencies.json info appears in the html deliverable (and much later in the file) as a script that assigns to window.phet.chipper.dependencies, for example:

```js
<script type="text/javascript">
window.phet.chipper.dependencies = {
  "comment": "# hookes-law 1.0.0-dev.11 Tue Jun 09 2015 14:04:31 GMT-0600 (MDT)",
  "assert": {
    "sha": "903564a25a0f26acdbd334d3e104039864b405ef",
    "branch": "master"
  },
  "axon": {
    "sha": "7de4a27be4b322b71c5f5046df193a03ccf0f161",
    "branch": "master"
  },
  ...
}
</script>
```

Should be done the same way? 
Which way is preferred?
Should they be co-located in the file?
For @jonathanolson: Is there an envisioned use for the global window.phet.chipper.dependencies?

**Comment by pixelzoom** [comment]
If we assigned 3rd-party license to a global, then they could potentially be shown in the About dialog in the future.

**Comment by pixelzoom** [comment]
@samreid and I decided to go for it, and added 3rd-party licenses to window.phet.chipper.thirdPartyLicenses.

**Comment by pixelzoom** [comment]
This was a rathole.  We decided to move more of the structure of the script into sim.html, so it's easier to see what's going on.  Ie, the template now determines the ordering of the script, like this:

```
<script type="text/javascript">
  window.phet = {};
  window.phet.chipper = {};
  window.phet.chipper.project = 'PHET_PROJECT';
  window.phet.chipper.version = 'PHET_VERSION';
  window.phet.chipper.buildTimestamp = 'PHET_BUILD_TIMESTAMP';
  window.phet.chipper.locale = 'PHET_LOCALE';
  window.phet.chipper.thirdPartyLicenses = THIRD_PARTY_LICENSES;
  window.phet.chipper.dependencies = PHET_SHAS;
  window.phet.chipper.strings = PHET_STRINGS;
</script>
```

... and the uppercase tokens are replaced by afterRequirejsBuild.js. 

We also decided to put the things that are likely to be read by humans towards the top of the HTML file. This entire script is now before the splash image, we'll see if that causes any startup delay (doubt it).

Assigning to @jonathanolson to review.

**Comment by pixelzoom** [comment]
Btw... We considered a nested assignment, like this:

```
window.phet = {
  chipper: {
    project: 'PHET_PROJECT',
    ...
  }
}
```

... but decide that it was easier to search for the globals in the form checked into sim.html.

**Comment by jonathanolson** [comment]
> For @jonathanolson: Is there an envisioned use for the global window.phet.chipper.dependencies?
Yes, it's the basic "sim was built with these SHAs", since that can vary from translation to translation.

Changes look great, thanks!

**Comment by samreid** [comment]
I have a few questions--can you check the formatting of your answer above @jonathanolson since it looks like your response got bundled into the question?  Also, why did you want this to be accessible at runtime via a variable rather than just something that can be parsed out of the file.  Do you intend to read those values across the iframe API or something?

**Comment by jonathanolson** [comment]
It actually does read those runtime right now so it can report SHAs to the "Report a problem..." link.

**Comment by samreid** [comment]
Ah, understood, thanks. Closing.
