### ISSUE TITLE
Multi-grunt dispatch duplicates

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1519]
I ran `grunt lint check` to use grunt's built-in ability to dispatch multiple tasks in sequence. However, it ran each twice:

```
~/phet/root/wave-interference$ grunt check lint
Running "check" task
(Forwarding task to perennial-alias)
Running "check" task

Running "lint" task

Done.

Running "lint" task
(Forwarding task to perennial-alias)
Running "check" task

Running "lint" task

Done.

Done.
```

**Comment by zepumph** [comment]
This solution says that you can never have a grunt task that provides options to grunt that doesn't start with `--`. So far we have fully embraced this, but if you don't agree with the commit, please feel free to revert.

```
mjkauzmann ~/PHET/git/chipper (main)
 $ grunt lint check --repo=density
Running "lint" task
(Forwarding task to perennial-alias)
Running "lint" task

Done.

Running "check" task
(Forwarding task to perennial-alias)
Running "check" task

Done.

Done.
```

**Comment by samreid** [comment]
I like it, thanks. How should `grunt lint check --clean` behave?

**Comment by zepumph** [comment]
Clean should go to both in my opinion. You?

**Comment by samreid** [comment]
Sounds good, thanks. Everything seems good here, closing. Nice work.
