### ISSUE TITLE
revisions related to setLicenseText.js

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#152]
In light of https://github.com/phetsims/chipper/issues/151, setLicenseText is now creating an object literal. 
Rename:

setLicenseText.js -> setThirdPartyLicenses.js
global.phet.licenseText -> global.phet.thirdPartyLicenses

Handle JSON.stringify of global.phet.licenseText in afterRequirejsBuild, at the point where it needs to be turned into a string.

**Comment by pixelzoom** [comment]
Work completed. Assigning to @samreid to take a quick look, since he worked on the overhaul of 3rd-party license stuff with me.

**Comment by samreid** [comment]
Change set looks good, and like we discussed previously.  Nice work, closing.
