### ISSUE TITLE
Why does output-js-project have --silent by default?

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1522]
In https://github.com/phetsims/chipper/issues/1499 we made output-js-project silent by default. Let's remove the silent default or document why it is important here but not elsewhere.

```
// TODO: explain why output-js-project is silent by default but transpile is not. This can be used outside of the maintenance tooling.
```

**Comment by samreid** [comment]
I removed it while working on https://github.com/phetsims/chipper/issues/1520, and left a TODO to discuss

**Comment by zepumph** [comment]
Looks great. And I didn't realize I had already set `--silent` at the appropriate usage sites.
