### ISSUE TITLE
Convert phetioCompareAPIs to Typescript

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#1526]
https://github.com/phetsims/phet-io/issues/1951
https://github.com/phetsims/perennial/issues/410
https://github.com/phetsims/perennial/issues/403
https://github.com/phetsims/chipper/issues/1465

This typescript module can then be used in sim AND build-tools code.

**Comment by zepumph** [comment]
- [x] Convert to es6 module with `export default`
- [x] remove as preload
- [ ] Convert to TypeScript

**Comment by zepumph** [comment]
I got an error when building phet-io with this import:

`Error: Cannot find module '../../../chipper/js/phet-io/phetioCompareAPIs.js'`


https://stackoverflow.com/questions/45968302/webpack-module-not-found-error-cant-resolve-with-relative-path

**Comment by zepumph** [comment]
Converted and fixed in the above. The webpack build was ignoring files from `/phet-io/` in phet brand build (what phet-io-wrappers standalone was build in).

**Comment by zepumph** [comment]
@samreid can you please give a spotcheck. Mostly for the typescript in chipper/js/phet-io/

**Comment by samreid** [comment]
I read the recent commits and everything seems reasonable. I tested by renaming a tandem and running `grunt pre-commit --phet-io-api` and it correctly caught the change. Closing.

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.

**Comment by samreid** [comment]
I can address these TODO's, I forgot to search them during the code review. Leaving self-assigned.

**Comment by samreid** [comment]
@zepumph and I reviewed this issue, and we feel this is high priority to discriminate between browser-and-node code and make sure it is correctly typed via a tsconfig.json file. We need `browser-and-node/` in perennial-alias and chipper. For instance, these files should not know what `process.exit()` is. While this remains a high priority, it does not need to block publication for new RCs.

**Comment by zepumph** [comment]
Alright. All TODOs have been handled, and we will pick things up in https://github.com/phetsims/perennial/issues/418
