### ISSUE TITLE
empty script in html deliverable

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#153]
In the html deliverable, there is an empty script immediately after the splash img tag:

```
<script type="text/javascript"></script>
```

**Comment by pixelzoom** [comment]
Immediately after the splash in sim.html is the PRELOAD_INLINE_JAVASCRIPT token.  And here's how it's replaced in afterRequirejsBuild:

```
// workaround for Uglify2's unicode unescaping. see https://github.com/phetsims/chipper/issues/70
preloadBlocks = preloadBlocks.replace( '\x0B', '\\x0B' );
...
html = replaceFirst( html, 'PRELOAD_INLINE_JAVASCRIPT', preloadBlocks );
```

'\x0B' is the vertical tabulation (VT) character, and I don't see anything else added to preloadBlocks. So presumably this is responsible for the empty script.   Looks like this was added by @jonathanolson so assigning to him for comment.

**Comment by jonathanolson** [comment]
Which sim were you building? After the splash, that's not the next line, it's this:
```html
<script type="text/javascript">PHET_MIPMAPS</script>
```

So I presume you built a sim with no mipmaps, and I would expect an empty script block?

**Comment by pixelzoom** [comment]
Ah, indeed, it's the PHET_MIPMAPS block. If that's optional, then perhaps the script start/end tags shouldn't be in sim.html?

**Comment by jonathanolson** [comment]
I'm fine if it done the way you describe, so it's only added if it is needed.

**Comment by pixelzoom** [comment]
The PHET_MIPMAPS_JAVASCRIPT token had to be replaced with something. Could have replaced it with an empty string, but then someone would be wondering why there was a blank line in the html deliverable. So if there are no mipmaps, I replaced the token with `'<!-- no mipmaps -->'`. 

Assigning to @jonathanolson to review.

**Comment by jonathanolson** [comment]
Looks good, thanks!
