### ISSUE TITLE
Better type for Lodash in phetioCompareAPIs.ts

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1536]
phetioCompareAPIs.ts currently has:

```ts
// TODO: how to type this? https://github.com/phetsims/chipper/issues/1465
type Lodash = any;
```

@zepumph and I discussed that it would be preferable to get the types from lodash, but it must be done in typespace only so it is compatible with node, browser built and browser unbuilt.

**Comment by samreid** [comment]
I found that `import type { LoDashStatic } from 'lodash'` seems to work well, keeps everything in type space. I tested that this runs properly in density => phet-io standalone + phetioCompareAPIs.  If this seems reasonable to you, can you please spot check the type assertions I added to make this work?

**Comment by zepumph** [comment]
Yes I like it. I thought about exporting this from npm-dependencies/lodash.ts I lost type info again (as we saw when pairing). In another issue we already decided it was worth keeping lodash as a chipper devDependency so this seems totally great. Thanks!
