### ISSUE TITLE
inspect contents of html deliverable

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#154]
To make sure that there's no unexpected 3rd-party code in html deliverables, it might be worth taking some time to inspect the contents.  Load an html file into a beautifier such as http://jsbeautifier.org and scroll through it. (If you're on a Mac, just drag the html file from the Finder into the beautifier's window.)

**Comment by pixelzoom** [comment]
I inspected the content of the html deliverable, and didn't see anything obviously amiss.  But I should note that the token MAIN_INLINE_JAVASCRIPT is replaced with the output of the `requirejs:build` task. That is a huge amount of stuff, and looks like mostly PhET-specific code. But it's quite possible that I missed something that the `requirejs:build` task adds to that.

Does anyone else want to take a look?...

**Comment by samreid** [comment]
Some things I noticed that I didn't recognize:

> s.canvasPNGOutput = e("image/png"), s.canvasJPEGOutput = e("image/jpeg"), s.canvasGIFOutput = e("image/gif"), s.canvasICONOutput = e("image/x-icon"), i("canvasPNGInput", "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIW2NkYGD4DwABCQEBtxmN7wAAAABJRU5ErkJggg=="), i("canvasJPEGInput", "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD/wAARCAABAAEDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD8qqKKKAP/2Q=="), i("canvasSVGInput", "data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIj8+DQo8c3ZnIHZlcnNpb249IjEuMSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB2aWV3cG9ydD0iMCAwIDEgMSIgd2lkdGg9IjEiIGhlaWdodD0iMSIgPg0KICA8cmVjdCB4PSIwIiB5PSIwIiB3aWR0aD0iMSIgaGVpZ2h0PSIxIiByeD0iMCIgcnk9IjAiIHN0eWxlPSJmaWxsOiBibGFjazsgc3Ryb2tlOiBub25lOyI+PC9yZWN0Pg0KPC9zdmc+DQo="), i("canvasGIFInput", "data:image/gif;base64,R0lGODlhAQABAJEAAAAAAP///////wAAACH5BAEAAAIALAAAAAABAAEAAAICRAEAOw==")


```js
              function R() {
                var e, i, r, s, o;
                if (s = U, o = U, 65 === t.charCodeAt(U) ? (e = "A", U++) : (e = null, 0 === J && n('"A"')), null !== e) {
                  for (i = [], r = j(); null !== r;) i.push(r), r = j();
                  null !== i ? (r = x(), null !== r ? e = [e, i, r] : (e = null, U = o)) : (e = null, U = o)
                } else e = null, U = o;
                if (null !== e && (e = function(t, e) {
                      return e.map(function(t) {
                        return {
                          cmd: "ellipticalArcTo",
                          args: t
                        }
                      })
                    }(s, e[2])), null === e && (U = s), null === e) {
                  if (s = U, o = U, 97 === t.charCodeAt(U) ? (e = "a", U++) : (e = null, 0 === J && n('"a"')), null !== e) {
                    for (i = [], r = j(); null !== r;) i.push(r), r = j();
                    null !== i ? (r = x(), null !== r ? e = [e, i, r] : (e = null, U = o)) : (e = null, U = o)
                  } else e = null, U = o;
                  null !== e && (e = function(t, e) {
                    return e.map(function(t) {
                      return {
                        cmd: "ellipticalArcToRelative",
                        args: t
                      }
                    })
                  }(s, e[2])), null === e && (U = s)
                }
                return e
              }
```

StringUtils contained some things I didn't recognize:

```js
            function he(t) {
              return function(e, i, n) {
                var r = {};
                i = U.createCallback(i, n, 3), n = -1;
                var s = e ? e.length : 0;
                if ("number" == typeof s)
                  for (; ++n < s;) {
                    var o = e[n];
                    t(r, o, i(o, n, e), e)
                  } else f(e, function(e, n, s) {
                  t(r, e, i(e, n, s), s)
                });
                return r
              }
            }
```

I saw lots of language names in the _en file, why are these here and is it costing us much kb?
```js
            ab: {
              name: "Abkhazian",
              localizedName: "Abkhazian",
              direction: "ltr"
            },
            ae: {
              name: "Avestan",
              localizedName: "Avestan",
              direction: "ltr"
            },
            af: {
              name: "Afrikaans",
              localizedName: "Afrikaans",
              direction: "ltr"
            }
```

some accessibility stuff is still in the compiled output
```js
define("SCENERY/accessibility/FocusRectangle", ["require", "PHET_CORE/inherit", "SCENERY/nodes/Rectangle", "AXON/Property"], function(t) {
      "use strict";

      function e(t, e) {
        var i = this;
        n.call(this, 0, 0, 0, 0, 0, 0, {
          stroke: "rgb(178,35,154)",
          visible: !1,
          lineWidth: 3
        });
        var s = 2.5;
        t.link(function(t) {
          t && i.setRect(t.x - s, t.y - s, t.width + 2 * s, t.height + 2 * s, 6, 6)
        }), r.multilink([t, e], function(t, e) {
          var n = null !== t && "rectangle" === e;
          i.visible = n
        })
      }
      var i = t("PHET_CORE/inherit"),
          n = t("SCENERY/nodes/Rectangle"),
          r = t("AXON/Property");
      return i(n, e)
    })
```

**Comment by pixelzoom** [comment]
@jonathanolson comments on the above things that @samreid identified:

`s.canvasPNGOutput = ...` is from features.js

`function R() { ...` is part of svgPathParser

`function he(t) {...` is part of lodash

 language names in the _en file: This is chipper/js/data/localInfo.js.  Used in the string plug-in in requirejs mode. Don't need to be in built version, but gets included because there's a require() statement.  Might need this info in the future. 19KB uncompressed, so probably OK to leave for now.

accessibility stuff: There are scenery issues to expunge this stuff, since it's buried behind query parameters.

**Comment by pixelzoom** [comment]
6/18/15 meeting: Close this.
