### ISSUE TITLE
grunt.log.debug does not exist in @types

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#1540]
From https://github.com/phetsims/chipper/issues/1465. So we have 13 calls to grunt.log.debug, and each has a ts-expect-error.  We could try to add to DefinitelyTyped, or stop calling grunt.log.debug, or maybe do interface extension.

**Comment by samreid** [comment]
Since we would like to move away from grunt in #1436, let's just use `grunt.log.verbose.writeln` instead.

**Comment by samreid** [comment]
Fixed in the commits, @zepumph want to spot check?

**Comment by zepumph** [comment]
I love this. I made a private note for dev PSA. Thanks for doing this.
