### ISSUE TITLE
support different copyright/license headers in the html deliverable

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#156]
In https://github.com/phetsims/chipper/issues/148#issuecomment-112588453, @kathy-phet requested different headers for "Regular" vs "Interoperable" sims.  Here's what's involved:

• Resolve https://github.com/phetsims/chipper/issues/148 so that we know what the header text is supposed to be.
• In afterRequirejsBuild.js, modify the assignment to `var htmlHeader`, based on `grunt.option( 'together' )`. Something like this:

```js
var htmlHeader = null;
if ( grunt.option( 'together' ) ) {
   //... use the "Interoperable" sim header 
}
else {
  //... use the "Regular" sim header 
}
```

**Comment by samreid** [comment]
We are reworking the way branding is done, and "interoperable" is currently one of the brands.  Once the build tools are using the build-local.json to determine the brand, we could also use that flag to determine the text to show in the header.  I'm inclined to address the branding issues before proceeding on this.

**Comment by pixelzoom** [comment]
+1 for changing the grunt option name (if that's what you mean :). The current `--together` flag should be changed to `--brand=interoperable`.

**Comment by samreid** [comment]
I like the idea of being able to specify brand using query parameters for requirejs mode, and being able to use build-local.json *or* command line args to specify it for the build.

**Comment by pixelzoom** [comment]
... where command line overrides build-local.json for builds.

**Comment by samreid** [comment]
https://github.com/phetsims/brand/issues/11 is the issue that would be good to complete either before or in conjunction with this issue.  Also, this issue is not critical for production deploys, but will be necessary for interoperable deploys.

**Comment by samreid** [comment]
I'm not planning to work on this until I get to branding, so I'll unassign for now.

**Comment by samreid** [comment]
Fixed above, using the brand identified in global.phet.chipper.getBrandName() and the text from @kathy-phet in #148

This is what the top of an interoperable HTML file looks like now:

```html
<!DOCTYPE HTML>
<!-- saved from url=(0025)http://phet.colorado.edu/ -->
<html>
<head>
  <meta charset="utf-8"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
  <meta name="viewport" content="initial-scale=1,user-scalable=no,maximum-scale=1"/>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="phet-sim-level" content="production">
  <title>‪Bending Light‬ 1.0.0-dev.5</title>
</head>
<!--
‪Bending Light‬ 1.0.0-dev.5
Copyright 2002-2015, Regents of the University of Colorado
PhET Interactive Simulations, University of Colorado Boulder

This Interoperable PhET Simulation file requires a license.
USE WITHOUT A LICENSE AGREEMENT IS STRICTLY PROHIBITED.
Contact phethelp@colorado.edu regarding licensing.
http://phet.colorado.edu/en/licensing
-->
<body bgcolor="black">
<script type="text/javascript">
```

It would be good for @kathy-phet to review the text above and make sure it is accurate and for @pixelzoom to review the code changes.

**Comment by pixelzoom** [comment]
Implementation looks good. 

Is this TODO tracked elsewhere? 

afterRequirejsBuild.js, line 208:
`var englishSimTitle = stringMap.en[ titleKey ] + ' ' + pkg.version; //TODO: i18n order`

**Comment by samreid** [comment]
We will not be internationalizing the text for the HTML headers for the same reason we do not provide translations for our licensing pages.  I'll remove the TODO and close the issue.

**Comment by samreid** [comment]
Just to be clear: the englishSimTitle var mentioned above only appears in the HTML header text comment.

**Comment by samreid** [comment]
Fixed above and closing.
