### ISSUE TITLE
input to FontAwesomeToScenery has changed

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#157]
For some other issue, @samreid replaced `sherpa/lib/font-awesome.txt` with `fontawesome-webfont-3.0.2.svg`. Two problems:

(1) This documentation in `FontAwesomeToScenery` is now incorrect:

```js
/**
 * Reads a data file (sherpa/lib/font-awesome.txt) that contains lines like:
 * <glyph unicode="&#xf000;" horiz-adv-x="1792" d="M1699 ... -36.5z" />
 * and creates a scenery-compatible version.  See sun.FontAwesomeNode.
 * <p>
 * font-awesome.txt was created by taking src/assets/font-awesome/fonts/fontawesome-webfont.svg
 * from the Font-Awesome GitHub repository at https://github.com/FortAwesome/Font-Awesome,
 * and manually deleting everything except the "glyph" tags.
 *
 * @author Sam Reid
 */
```

(2) We can't run FontAwesomeToScenery because the input file format is now XML instead of what is described in the doc.

**Comment by samreid** [comment]
I updated the docs to indicate that the filename has changed and that a manual step is required for preprocessing before running FontAwesomeToScenery.  @pixelzoom can you review?

**Comment by samreid** [comment]
Note: the reason for the filename & contents change was to match what appears in the Font Awesome distribution.

**Comment by pixelzoom** [comment]
Doc is still incorrect:
>  Reads a data file (sherpa/lib/font-awesome.txt) (sherpa/lib/font-awesome.txt)

This file does not exist.

**Comment by samreid** [comment]
Updated docs above, please review.

**Comment by pixelzoom** [comment]
Reopening, I noticed something else. @samreid the default path is:
> "C:\\workingcopy\\phet\\svn-1.7\\trunk\\simulations-html\\build-tools\\data\\font-awesome.txt"

I realize that this is specific to your host, but that path no longer exists in Unfuddle SVN.  I'm fine with leaving this as is, but you'll have to either deal with it now or in the future.  And it may serve as a false clue to other developers about where the file might be found.

**Comment by samreid** [comment]
We should change this path to be a required path.  I don't have time to do so at the moment, so will unassign for now.

**Comment by pixelzoom** [comment]
I would do this, but it's a pain to run and test.  

Delete constant `SAM_PATH` and change:

`String filename = ( args.length > 0 ) ? args[0] : SAM_PATH;`

to:

```
if ( args.length != 1 ) {
  System.err.println( "usage: FontAwesomeToScenery font-awesome.txt" );
  exit( 1 );
}
String svg = FileUtils.loadFileAsString( new File( args[0] ) );
```

**Comment by samreid** [comment]
I think there's a fair chance we will never need to run this script again.  If we do, perhaps then would be the best time to address deficiencies in the script.

**Comment by samreid** [comment]
FontAwesomeToScenery.java was removed in c0effd5c3fd6bb55feeb6b99f5656d328e9c7fe6, closing.
