### ISSUE TITLE
Code review for deployDev.js

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/chipper#159]
Code review of port of deploy-dev.sh to grunt.

Also added the ability to mkdir and create the .htaccess file. The file is js/grunt/deplotDev.js.

We'll need to update the deploy procedure in phet-info once this has been tested and code reviewed.

**Comment by pixelzoom** [comment]
I committed to get to this sometime Monday, 6/29/15, sooner if possible.

**Comment by pixelzoom** [comment]
General problem with all error handling in this task...

(1) When an error occurs, there is no "error recovery" code, and the task is allowed to continue. All of the errors in this task are non-recoverable, so the task should exit immediate on error.

(2) Error messages should be logged either using grunt.log.error, or by using `throw Error`. The latter will stop the task.

**Comment by pixelzoom** [comment]
Credentials are currently expected to be in `chipper/credentials.json`.  This makes it likely that someone will accidentally check them in.  A better place is $HOME/.phet/credentials.json. Also not sure that credentials.json is the best name for this file.

The server name is split up between 2 files:

Gruntfile, line 184: `deployDev( grunt, grunt.option( 'serverName' ) || 'spot' );`
deployDev, line 62: `host: serverName + '.colorado.edu',`

It makes more sense to have the entire server name in one place. And for security reasons, it would be preferable to have the server name in a preferences file in $HOME/.phet.  Also recommended to put this in the same preferences file that is used to store credentials.

**Comment by pixelzoom** [comment]
The comment about server name also applies to the deploySimulation task.

**Comment by pixelzoom** [comment]
Also for security reasons, recommended to put this path in preferences files:

`var DEV_DIRECTORY = '/htdocs/physics/phet/dev/html/';`

**Comment by pixelzoom** [comment]
Assigning back to @aaronsamuel137 to discuss/address issues.

**Comment by pixelzoom** [comment]
Btw... There is precedence for using $HOME/.phet to store preferences.  For Java/Flash sims:

```
% ls -1 $HOME/.phet
build-local.properties
phet-build-gui.properties
preferences.properties
session-counts.properties
sim-sharing.properties
%
```

**Comment by jonathanolson** [comment]
> Also for security reasons, recommended to put this path in preferences files:

> var DEV_DIRECTORY = '/htdocs/physics/phet/dev/html/';

Just curious about how this is a security risk?

>  A better place is $HOME/.phet/credentials.json.

+1

**Comment by pixelzoom** [comment]
> Also for security reasons, recommended to put this path in preferences files:
> 
> var DEV_DIRECTORY = '/htdocs/physics/phet/dev/html/';

I guess it's not a security risk per se. But why would you want to make it easier for someone to know where the files are on the server?

**Comment by pixelzoom** [comment]
There should be something like this at the top of the task:

```js
var PREFERENCES_FILE = ...; // the file in $HOME/.phet
assert( fs.existsSync( PREFERENCES_FILE ) );
var preferences = grunt.file.readJSON( PREFERENCES_FILE );
assert( preferences.userName, 'username is missing from ' + PREFERENCES_FILE );
assert( preferences.userName, 'password is missing from ' + PREFERENCES_FILE );
assert( preferences.devDeployServer, 'devDeployServer is missing from ' + PREFERENCES_FILE );
assert( preferences.devDeployPath, 'devDeployPath is missing from ' + PREFERENCES_FILE );
//... verify that other required entries are present
```

**Comment by jonathanolson** [comment]
> I guess it's not a security risk per se. But why would you want to make it easier for someone to know where the files are on the server?

It's already pretty public information. Indexed by Google, this issue pointing out the path is indexed by Google, and I don't think anyone would likely need to review that code to identify where we deploy dev builds.

I'm fine with either approach, just was curious.

**Comment by pixelzoom** [comment]
Another reason to factor out the server path is generalization. If you're going to factor out the server name, then why would you hardcode the server path? Very unlikely that a different server would have the same deploy path.

**Comment by jonathanolson** [comment]
> Another reason to factor out the server path is generalization. If you're going to factor out the server name, then why would you hardcode the server path? Very unlikely that a different server would have the same deploy path.

It's likely we'd want everyone to switch to the new server if we switch. Then it's easier to make 1 change in chipper code, instead of making everyone update their private config files on every development computer.

**Comment by aaronsamuel137** [comment]
I've made these changes. I decided to give and option to put preferences.devDeployServer and preferences.devDeployPath, but default these to spot and the hardcoded path if they aren't in the preferences file.

Assigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
Looks great.  A few notes...

I fixed one general issue: constants were not being used consistently for file and directory names.  See commit above.

A new npm dependency has apparently been introduced. I had to run `npm install` in chipper. You might want to advertise that when this work is completed.

In build-local.json, I recommend changing `userName` and `userPassword` to `devUsername` and `devPassword` respectively.  Username is not typically camel cased. And we are likely to need other usernames and passwords, for example for the production server. (My credentials are not the same on spot and figaro.)

**Comment by aaronsamuel137** [comment]
Fixed the names. @pixelzoom, are you up for testing this with hookes-law next time you need to deploy dev?

**Comment by pixelzoom** [comment]
Yep, I'll try to remember to test for the next hookes-law dev version.  Assigning to me.

**Comment by pixelzoom** [comment]
I use `grunt deploy-dev` to deploy Hooke's Law 1.0.0-dev.23 and it worked great.

One request: deploy-dev.sh prints the URL for deployed sim, and that's super convenient for quickly navigating to the deployed sim, pasting the URL into emails, etc.  Could you add that to this grunt task? For example, deploy-dev.sh would have printed:

`deployed:" http://www.colorado.edu/physics/phet/dev/html/hookes-law/1.0.0-dev.23/hookes-law_en.html`

**Comment by aaronsamuel137** [comment]
I've added added this log message. Assigning to @pixelzoom for review. If it looks good to you I'll go ahead and update the deploy dev documentation in phet-info.

**Comment by pixelzoom** [comment]
Looks good. You can also delete deploy-dev.sh.

**Comment by aaronsamuel137** [comment]
Deleted deploy-dev in 3a4ef0e457b5ca250fa541b64b3d9500b24449b6 (forgot to reference this issue).

Updated https://github.com/phetsims/phet-info/blob/master/sim_deployment.md and sent an email to developers. Assigning to @pixelzoom for review. Feel free to close if it looks good to you.

**Comment by pixelzoom** [comment]
Visually inspected, looks good.  Nice job, closing.
