### ISSUE TITLE
Remove excess console output during grunt tasks

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#160]
During a normal grunt task, I see this:

```
samreid$ grunt
phetLibs = assert,axon,babel,bending-light,brand,chipper,dot,joist,kite,phet-core,phetcommon,scenery,scenery-phet,sherpa,sun

Running "jshint:allFiles" (jshint) task
>> 434 files lint free.

Running "clean" task
Cleaning build directory

Running "set-preload" task
Adding common preload files...
Adding sim-specific preload files...
pkg.preload = ../sherpa/lib/jquery-2.1.0.js,../sherpa/lib/lodash-2.4.1.js,../sherpa/lib/FileSaver-b8054a2.js,../assert/js/assert.js,../chipper/js/initialize-globals.js,../phetcommon/js/analytics/google-analytics.js,../sherpa/lib/Tween-r12.js

Running "set-third-party-licenses" task
Adding common licenses...
Adding preload licenses...
licenseKeys = almond-0.2.9,FileSaver-b8054a2,fontawesome-webfont-3.0.2,jama-1.0.2,jquery-2.1.0,lodash-2.4.1,pegjs-0.7.0,text-2.0.12,Tween-r12

Running "before-requirejs-build" task
Building simulation: bending-light 1.0.0-dev.4
Locales to build: en

Running "requirejs:build" (requirejs) task
>> RequireJS optimizer finished

/Users/samreid/github/bending-light/build/bending-light.min.js
Uncompressed size: 2182097 bytes.
Compressed size: 605845 bytes gzipped. (1379438 bytes minified)

Running "after-requirejs-build" task
Minifying preload scripts
Copying changes.txt
Scanning dependencies from:
assert,axon,babel,bending-light,brand,chipper,dot,joist,kite,phet-core,phetcommon,scenery,scenery-phet,sherpa,sun
assert              master 903564a25a0f26acdbd334d3e104039864b405ef
axon                master f4996f9d182deb1b9e799c9ec6282bf8dcfa43bc
babel               master 2431e7111ee0aa3d3eedef3727972abc78b6c1f1
bending-light       master 690d59587d09a30849ea030c7763db897f830da4
brand               master 4cb9a321bed065c983a5203f26fd5898bd775b7e
chipper             master fb7704bebace28d0acd6291c41e308d3dd6edfcd
dot                 master 65da3f573d6d13ae776d93aed25eed022079f33d
joist               master 9c8a4e7384235b5dc6ce7edfd4310df15b054e12
kite                master 9d2a34ddcb9258544a02afdc65f9632348fd7b73
phet-core           master 8e31808c67a23066b43fbbd2080784daa44433c2
phetcommon          master 48b8119d27954452d6d8e015ac7ed9c044261285
scenery             master 61011f28042e8960fd9ed43bf3d3f1e1c38826a1
scenery-phet        master ea0e0d835c72338dd5c88d52473759125eb95ee1
sherpa              master 1929c9a687c4e2164285c434742136051568a619
sun                 master cec7fc906bdb209ba0938760f2e60eb25a59912d
Writing dependencies.json
Constructing HTML from template
Writing HTML
Constructing HTML for iframe testing from template
Writing HTML for iframe testing
Writing string map to  build/bending-light_string-map.json
Cleaning temporary files
```

Can we get rid of:

> phetLibs = assert,axon,babel,bending-light,brand,chipper,dot,joist,kite,phet-core,phetcommon,scenery,scenery-phet,sherpa,sun

and

>pkg.preload = ../sherpa/lib/jquery-2.1.0.js,../sherpa/lib/lodash-2.4.1.js,../sherpa/lib/FileSaver-b8054a2.js,../assert/js/assert.js,../chipper/js/initialize-globals.js,../phetcommon/js/analytics/google-analytics.js,../sherpa/lib/Tween-r12.js

and

>licenseKeys = almond-0.2.9,FileSaver-b8054a2,fontawesome-webfont-3.0.2,jama-1.0.2,jquery-2.1.0,lodash-2.4.1,pegjs-0.7.0,text-2.0.12,Tween-r12

and

> Scanning dependencies from:
assert,axon,babel,bending-light,brand,chipper,dot,joist,kite,phet-core,phetcommon,scenery,scenery-phet,sherpa,sun

Why not go even further and remove everything except for the `Running _ task` markers?  Assigned to @pixelzoom for discussion.

**Comment by jonathanolson** [comment]
We could consider very concise console output, but then log most things to a logfile.

**Comment by pixelzoom** [comment]
Most of that output is useful primarily for debugging. How about if we add a `--debug` option to grunt tasks?

**Comment by pixelzoom** [comment]
Looks like --debug is already used grunt.  Eg:

```
% grunt
phetLibs = assert,axon,babel,brand,chipper,dot,hookes-law,joist,kite,phet-core,phetcommon,scenery,scenery-phet,sherpa,sun

Running "jshint:allFiles" (jshint) task
[D] Task source: /Users/cmalley/PhET/GitHub/hookes-law/node_modules/grunt-contrib-jshint/tasks/jshint.js
...
```

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/chipper/commit/b94125e8f8a7d18686ebfcc98ac569fa0c150d45, I changed `grunt.log.writeln` to `grunt.log.debug` for debugging output.  I did this only for grunt tasks that are related to the "build" task.

Here it is without `--debug`:

```
% grunt 
Running "jshint:allFiles" (jshint) task
>> 432 files lint free.

Running "clean" task
Cleaning build directory

Running "set-preload" task

Running "set-third-party-licenses" task

Running "before-requirejs-build" task

Running "requirejs:build" (requirejs) task
>> RequireJS optimizer finished

/Users/cmalley/PhET/GitHub/hookes-law/build/hookes-law.min.js
Uncompressed size: 1987119 bytes.
Compressed size: 298547 bytes gzipped. (918056 bytes minified)

Running "after-requirejs-build" task

Done, without errors.
%
```

**Comment by pixelzoom** [comment]
Here's the output with `--debug`.  The debug lines are automatically prefixed with `[D]`, and in my console they appear in purple.  Grunt adds very little of its own debug output.  This looks great to me. If we want to differentiate between verbose and non-verbose debug output, we could change some of this to use `grunt.log.verbose.debug`, which will only be printed when `--debug` and `--verbose` are both specified.  More on grunt.log at http://gruntjs.com/api/grunt.log.

```
% grunt --debug
phetLibs = assert,axon,babel,brand,chipper,dot,hookes-law,joist,kite,phet-core,phetcommon,scenery,scenery-phet,sherpa,sun

Running "jshint:allFiles" (jshint) task
[D] Task source: /Users/cmalley/PhET/GitHub/hookes-law/node_modules/grunt-contrib-jshint/tasks/jshint.js
^Ccmalley@semitone[55]: grunt --debug
[D] phetLibs = assert,axon,babel,brand,chipper,dot,hookes-law,joist,kite,phet-core,phetcommon,scenery,scenery-phet,sherpa,sun

Running "jshint:allFiles" (jshint) task
[D] Task source: /Users/cmalley/PhET/GitHub/hookes-law/node_modules/grunt-contrib-jshint/tasks/jshint.js
^Ccmalley@semitone[56]: 
cmalley@semitone[56]: grunt --debug
[D] phetLibs = assert,axon,babel,brand,chipper,dot,hookes-law,joist,kite,phet-core,phetcommon,scenery,scenery-phet,sherpa,sun

Running "jshint:allFiles" (jshint) task
[D] Task source: /Users/cmalley/PhET/GitHub/hookes-law/node_modules/grunt-contrib-jshint/tasks/jshint.js
>> 432 files lint free.

Running "clean" task
[D] Task source: /Users/cmalley/PhET/GitHub/hookes-law/Gruntfile.js
Cleaning build directory

Running "set-preload" task
[D] Task source: /Users/cmalley/PhET/GitHub/hookes-law/Gruntfile.js
[D] Adding common preload files...
[D] Adding sim-specific preload files...
[D] pkg.preload = ../sherpa/lib/jquery-2.1.0.js,../sherpa/lib/lodash-2.4.1.js,../sherpa/lib/FileSaver-b8054a2.js,../assert/js/assert.js,../chipper/js/initialize-globals.js,../phetcommon/js/analytics/google-analytics.js,../sherpa/lib/Tween-r12.js

Running "set-third-party-licenses" task
[D] Task source: /Users/cmalley/PhET/GitHub/hookes-law/Gruntfile.js
[D] Adding common licenses...
[D] Adding preload licenses...
[D] licenseKeys = almond-0.2.9,FileSaver-b8054a2,fontawesome-webfont-3.0.2,jama-1.0.2,jquery-2.1.0,lodash-2.4.1,pegjs-0.7.0,text-2.0.12,Tween-r12

Running "before-requirejs-build" task
[D] Task source: /Users/cmalley/PhET/GitHub/hookes-law/Gruntfile.js
[D] Building simulation: hookes-law 1.0.0-dev.18
[D] Locales to build: en

Running "requirejs:build" (requirejs) task
[D] Task source: /Users/cmalley/PhET/GitHub/hookes-law/node_modules/grunt-requirejs/tasks/require.js
>> RequireJS optimizer finished

/Users/cmalley/PhET/GitHub/hookes-law/build/hookes-law.min.js
Uncompressed size: 1987119 bytes.
Compressed size: 298547 bytes gzipped. (918056 bytes minified)

Running "after-requirejs-build" task
[D] Task source: /Users/cmalley/PhET/GitHub/hookes-law/Gruntfile.js
[D] Minifying preload scripts
[D] Copying changes.txt
[D] Scanning dependencies from:
assert,axon,babel,brand,chipper,dot,hookes-law,joist,kite,phet-core,phetcommon,scenery,scenery-phet,sherpa,sun
[D] assert              master 903564a25a0f26acdbd334d3e104039864b405ef
[D] axon                master f4996f9d182deb1b9e799c9ec6282bf8dcfa43bc
[D] babel               master 2431e7111ee0aa3d3eedef3727972abc78b6c1f1
[D] brand               master b3362651f1d7eddb7f8697d02400472f97f9d140
[D] chipper             master be476e554163c5f611bd8becdaf1ba5cfc0692d1
[D] dot                 master 65da3f573d6d13ae776d93aed25eed022079f33d
[D] hookes-law          master c6ec6b29f022218564afe38843416d691146cb59
[D] joist               master 9c8a4e7384235b5dc6ce7edfd4310df15b054e12
[D] kite                master 9d2a34ddcb9258544a02afdc65f9632348fd7b73
[D] phet-core           master 8e31808c67a23066b43fbbd2080784daa44433c2
[D] phetcommon          master 48b8119d27954452d6d8e015ac7ed9c044261285
[D] scenery             master 61011f28042e8960fd9ed43bf3d3f1e1c38826a1
[D] scenery-phet        master ea0e0d835c72338dd5c88d52473759125eb95ee1
[D] sherpa              master d6441e3e4d7ab3af844899243c7d5c0f55a12ae2
[D] sun                 master 3d9fe824652fffc958ad8993632c749b0b183582
[D] Writing dependencies.json
[D] Constructing HTML from template
[D] Writing HTML
[D] Constructing HTML for iframe testing from template
[D] Writing HTML for iframe testing
[D] Writing string map to  build/hookes-law_string-map.json
[D] Cleaning temporary files

Done, without errors.
%
```

**Comment by pixelzoom** [comment]
Back to @samreid for comment.

**Comment by pixelzoom** [comment]
I looked for a way to suppress the `Running "XXX" task` messages. Most people recommend this duck punch: `grunt.log.header = function() {}`.

**Comment by samreid** [comment]
> I looked for a way to suppress the Running "XXX" task messages. Most people recommend this duck punch: grunt.log.header = function() {}.

I feel like those are an acceptable level of granularity and am ok leaving them in.

**Comment by samreid** [comment]
This output is looking much better, I'm happy with the --debug and sans debug output.  Closing.

**Comment by samreid** [comment]
Every simulation just picked up this additional text to every build (this is the tail of a grunt):

/Users/samreid/github/hookes-law/build/hookes-law.min.js
Uncompressed size: 2047518 bytes.
Compressed size: 173482 bytes gzipped. (757533 bytes minified)

Running "after-requirejs-build" task
mipmapped /Users/samreid/github/brand/js/../images/logo.png to level 4 with quality: 98
level 0 (PNG 273x108) base64: 3226 bytes 
level 1 (PNG 137x54) base64: 1978 bytes 
level 2 (PNG 69x27) base64: 1122 bytes 
level 3 (PNG 35x14) base64: 706 bytes 
level 4 (PNG 18x7) base64: 406 bytes 
mipmapped /Users/samreid/github/brand/js/../images/logo-on-white.png to level 4 with quality: 98
level 0 (PNG 273x108) base64: 2778 bytes 
level 1 (PNG 137x54) base64: 1742 bytes 
level 2 (PNG 69x27) base64: 990 bytes 
level 3 (PNG 35x14) base64: 626 bytes 
level 4 (PNG 18x7) base64: 374 bytes 

Can we please move these mipmap notes to the --debug as well?

**Comment by jonathanolson** [comment]
grunt.log.debug didn't work out of the box (not defined in Node.js), and global.grunt was undefined. If I did require( 'grunt' ), grunt.log.debug output didn't show up.

I've had to resort to passing in the logging function (which seems pretty unclean for code in general). @samreid, can you see if there's a better way of doing this, and review?

**Comment by samreid** [comment]
I believe the convention for chipper code called from grunt is to pass the grunt instance.  For example afterRequirejsBuild.js starts like:

```js
/**
 * @param grunt the grunt instance
 * @param {Object} pkg package.json
 * @param {string} fallbackLocale
 */
module.exports = function( grunt, pkg, fallbackLocale ) {
```

Would that work for the mipmapper?

**Comment by pixelzoom** [comment]
I only see the mipmap output when running `grunt -d`.

**Comment by jonathanolson** [comment]
> I believe the convention for chipper code called from grunt is to pass the grunt instance.

Is there any advantage to doing that as opposed to passing just the log function (so that it isn't dependent on grunt itself?)

**Comment by samreid** [comment]
The main advantages of passing the grunt:

1) consistency with pre-exising code
2) it is obvious what grunt.log.debug is doing, less obvious what logFunction(...) would do
3) what if you need to add a grunt.log.error call (or any other grunt functionality)?  Then would you introduce a new parameter, or switch to passing the grunt?

Main advantages of passing a minimal log function instead of the grunt:
1) no opportunity to accidentally mutate or misuse the other grunt things
2) ability to run this code in a different (non-grunt) context and clear that no grunt functionality is required

For me, passing the grunt seems like the winner here (though not by a lot), but I'm open for discussion.

**Comment by jonathanolson** [comment]
It seems like if we ever want to be open to the possibility of mipmapping in a non-grunt context (e.g. server that can mipmap images on the fly), it's beneficial to have it not depend on grunt.

I however can't particularly think of a realistic scenario other than "we're not using grunt for builds anymore".

I'll leave it up to you, no strong preferences.

**Comment by samreid** [comment]
Let's see if @jbphet or @pixelzoom can cast a deciding vote (no rush).

**Comment by pixelzoom** [comment]
As I said in https://github.com/phetsims/chipper/issues/160#issuecomment-121667826:
> I only see the mipmap output when running `grunt -d`.

So I'm confused about why this is an issue.

**Comment by pixelzoom** [comment]
7/16/15 dev meeting consensus: Pass in `grunt`, to be consistent with other chipper code.
