### ISSUE TITLE
AquaRadioButtons in trig-lab have ceased functioning

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#161]
@dubson reported:

> My AquaRadioButtons in trig-lab have ceased functioning, following an update project.  Perhaps I accidentally inserted a death-comma somewhere, but viewProperties.graphProperty.link( function( graph ) is passing a value of graph which is behaving very strangely.  Anyone else have issues with their radio buttons?

Using bisection by date, I tracked down the troublesome commit to https://github.com/phetsims/chipper/commit/a282938be9077a980309b1330b9084e5e6c95e08

I'll take a look and see if I can figure out what is happening here.

**Comment by samreid** [comment]
The significant change is in the string plugin:

```js
       if ( isRTL ) {
                    for ( var stringKey in parsed ) {
                      parsed[ stringKey ].value = '\u202b' + parsed[ stringKey ].value + '\u202c';
                    }
                  }
```

became

```js
                for ( var stringKey in parsed ) {
                    parsed[ stringKey ].value = ( isRTL ? '\u202b' : '\u202a' ) + parsed[ stringKey ].value + '\u202c';
                  }
```

It looks like unicode start/end characters are being added now for LTR strings as well as for RTL strings.  So I suspect that logic code in trig lab is doing === comparisons on internationalized strings to determine whether to show the sin/cos/tan and degree/radian. This will be a problem since those strings will be different in every language.  I'll move this issue over to trig-lab since that seems like the most likely culprit at this point.

**Comment by samreid** [comment]
I moved this issue to trig-lab, linked above.  Closing this one.

**Comment by dubson** [comment]
Hi Sam,
Thanks!!
Yes, my code contains comparisons like graph === ‘cos’   but how can the String ‘cos’ get confused with my internationalized string for ‘cos’ which is

var cosStr = require( 'string!TRIG_LAB/cos' );

?

-mike

**Comment by samreid** [comment]
Let's discuss it over here: https://github.com/phetsims/trig-lab/issues/4
