### ISSUE TITLE
Generate sim-specific 3rd party licensing reports

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#162]
While @aaronsamuel137 & I were working on https://github.com/phetsims/sherpa/issues/22 we discussed a strategy for handling the licensing report as well as integrating the licensing information into each simulation.

1. Create a new grunt task that generates a simulation-specific licensing report.  This will look at the dependencies in package.json as well as the common dependencies to determine what is used.  Together with the metadata in third-party-licenses.json (which should probably also include the license texts), a simulation-specific report can be generated.  This will allow team members to know what encumberances each simulation has, and this report can be embedded in the HTML as a legal requirement for https://github.com/phetsims/sherpa/issues/33 and made available to the about dialog https://github.com/phetsims/joist/issues/252 (in the future).  This task should also throw assertion errors if anything essential is missing from one of the license metadatas.
2. Create a new grunt task that aggregates over the results above to generate a report of "what is used in every simulation".  This will help us easily filter out things that are used elsewhere, such as scenery documentation, but not deployed in our simulations.  In the future, this task could also be used to generate reports based on subsets of simulations, for instance if we need to know what 3rd party dependencies are used by all chemistry sims.
3. As discussed in https://github.com/phetsims/chipper/issues/158 we could use the above scripts to see if there are stale entries in third-party-licenses.json which are no longer used.

While we are working on this, we should consider that 3rd party contributions are not limited to sherpa/code, but also includes images & audio from each simulation.  This may be lower priority at the moment.  See https://github.com/phetsims/tasks/issues/274 for more details.

**Comment by ariel-phet** [comment]
I definitely would like to make sure that as we redeploy we address any images/audio, and just make sure they are owned by PhET. That just seems to be a much better long term solution, and avoids any future hassles with image/audio. So that can be taken care of on a sim by sim basis, and does not need to be part of the above plan and/or scripts.

Overall, what you are proposing seems reasonable to me, but I am sure the other developers have opinions about what sorts of technical hurdles this work could imply.

**Comment by jonathanolson** [comment]
Sounds good to me. I assumed there already was sim-specific licensing lists handled in chipper?

**Comment by samreid** [comment]
> So that can be taken care of on a sim by sim basis, and does not need to be part of the above plan and/or scripts.

If it is not too much effort, scripts to report on images & audio may still be useful to help us (a) understand what still needs to be re-created by PhET or (b) to handle any images/audio that PhET does not re-create.  @ariel-phet said we probably will stick with font-awesome artwork for the time being.

> I assumed there already was sim-specific licensing lists handled in chipper?

I am unfamiliar with recent work done in chipper/js/grunt/setThirdPartyLicenses.js, so not sure whether sim-specific licensing lists are handled or not.

**Comment by pixelzoom** [comment]
> I assumed there already was sim-specific licensing lists handled in chipper?

If you're asking if there is a way to include 3rd-party licenses that are sim-specific and not indicated in chipper/build.json... The answer is yes.  Use the "licenseKeys" field in package.json, format is identical to build.json.   Sim-speciific licenses are added on line 64 of setThirdPartyLicenses.js:

```js
  // Add sim-specific licenses, as specified in the (optional) licenseKeys field of package.json.
  if ( pkg.licenseKeys ) {
    grunt.log.debug( 'Adding sim-specific licenses...' );
    licenseKeys = licenseKeys.concat( pkg.licenseKeys );
  }
```

**Comment by pixelzoom** [comment]
Btw... A sim-specific library doesn't need to be noted in pkg.licenseKeys if it's already specified in pkg.preload.

**Comment by samreid** [comment]
> I definitely would like to make sure that as we redeploy we address any images/audio, and just make sure they are owned by PhET.

At a previous meeting, @kathy-phet pointed out that it is impractical to own all images/audio and that we will need a process for managing 3rd party images/audio.

**Comment by samreid** [comment]
The composite report should be pushed to the sherpa MD file.

**Comment by samreid** [comment]
I pushed a first draft of sim-specific reports and composite-reports in the above commit.  With TODOs as noted here:

* Make sure we hit all of the repos from active-sims (if one didn't build, it might not have a report file).
* Should we just use active-sims as the list to iterate over?
* Should there be a sim report as well as a non-sim report?
* Add other 3rd party things from sherpa that are used in non-requirejs projects.
* Should we parse the HTML and get the values from the HTML so that we can (a) run reports for published sims instead of just master, and won't have to generate additional report files after the build?

**Comment by samreid** [comment]
I've created the report aggregator, here is the documentation:

Creates a composite report of all of the 3rd party images, code, audio, fonts used by PhET Simulations and updates the online version by automatically adding and pushing the changes to GitHub.  The output can be seen at:
https://github.com/phetsims/sherpa/blob/master/third-party-licenses.md

Entries in sherpa/license.json are used for the code report, and this is augmented by information obtained by running mandatory simulation-specific reports using:

`grunt-all.sh build-no-lint --createSimSpecificThirdPartyReport`

indicating which third-party code resources are used by which simulations.

The task itself is run with

`grunt create-composite-third-party-report`

**Comment by samreid** [comment]
Finished, closing.
