### ISSUE TITLE
"grunt deploy-dev" fails

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#163]
I was testing out the new `grunt deploy-dev` from https://github.com/phetsims/chipper/issues/159 and am running into this error:

> Fatal error: handle is not a Buffer

Here is my full transcript:

```
example-sim samreid$ cd ../chipper/
chipper samreid$ npm install
npm WARN package.json pngjs@0.4.0 No repository field.
chipper samreid$ cd ../example-sim/
example-sim samreid$ grunt
Running "jshint:allFiles" (jshint) task
>> 383 files lint free.

Running "clean" task

Running "set-preload" task

Running "set-third-party-licenses" task

Running "before-requirejs-build" task

Running "requirejs:build" (requirejs) task
>> RequireJS optimizer finished

/Users/samreid/github/example-sim/build/example-sim.min.js
Uncompressed size: 1741128 bytes.
Compressed size: 168125 bytes gzipped. (655762 bytes minified)

Running "after-requirejs-build" task

Done, without errors.
example-sim samreid$ grunt deploy-dev
Running "deploy-dev" task
Copying files to spot.colorado.edu...
Fatal error: handle is not a Buffer
```

What do you think the problem may be?

**Comment by pixelzoom** [comment]
Did you run `npm install` in chipper?

**Comment by aaronsamuel137** [comment]
What OS are you using? There is an issue I just discovered with Windows where the path is set wrong, not sure if this is related or not.

**Comment by aaronsamuel137** [comment]
You can also try logging credentialsObject.path and let me know what the output is.

**Comment by samreid** [comment]
> Did you run `npm install` in chipper?

Yes, see my transcript above:
```
example-sim samreid$ cd ../chipper/
chipper samreid$ npm install
npm WARN package.json pngjs@0.4.0 No repository field.
```

I'm running OS X Yosemite 10.10.2 and my npm version is 1.4.28

```
samreid$ npm --version
1.4.28
```

**Comment by samreid** [comment]
Here is my credentialsObject:

```
{ host: 'spot.colorado.edu',
  username: 'REDACTED',
  password: 'REDACTED',
  path: '/htdocs/physics/phet/dev/html/example-sim/1.0.0-dev.6/' 
}
```

**Comment by samreid** [comment]
Perhaps I need to bump up the version number, since 1.0.0-dev.6 already exists?

**Comment by samreid** [comment]
I tried using grunt bump-version and it appears broken, see https://github.com/phetsims/chipper/issues/164, I'll do it manually instead.

**Comment by samreid** [comment]
After updating the version, this problem disappeared.  Can @aaronsamuel137 detect this error condition and provide a helpful console message, since it is likely to happen again?

**Comment by aaronsamuel137** [comment]
Looks like there is a pull request in scp2 already to address this issue: https://github.com/spmjs/node-scp2/pull/32. Perhaps I can add a try catch in our code as a workaround for now.

**Comment by aaronsamuel137** [comment]
deploy-dev has been redone with commandline scp, and seems to work. Closing. Feel free to reopen if it isn't working for you.
