### ISSUE TITLE
grunt bump-version is broken, perhaps it can be deleted

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#164]
grunt bump-version is broken.  And possibly it is no longer needed since we have consolidated the version info into a single file.  Perhaps we should delete it, can I get a +1 from somebody?

**Comment by pixelzoom** [comment]
+1

**Comment by samreid** [comment]
I'm on it.

**Comment by pixelzoom** [comment]
bump-verison has probably been broken since version.js went away.

**Comment by samreid** [comment]
I removed it above and ran a test grunt to see that things still worked properly.  Closing.
