### ISSUE TITLE
Together license keys not added

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#166]
While looking at setThirdPartyLicenses.js, I saw this code:

```js
  // Add sim-specific licenses, as specified in the (optional) licenseKeys field of package.json.
  if ( pkg.licenseKeys ) {
    grunt.log.debug( 'Adding sim-specific licenses...' );
    licenseKeys = licenseKeys.concat( pkg.licenseKeys );
  }

   // Add together (data collection) licenses, as specified in build.json
  if ( grunt.option( 'together' ) ) {
    grunt.log.debug( 'Adding together licenses...' );
    assert( buildInfo.together && buildInfo.together.licenseKeys, BUILD_INFO_FILENAME + ' is missing together.licenseKeys' );
    licenseKeys.concat( buildInfo.together.licenseKeys );
  }
```

The last line doesn't mutate the licenseKeys, for example see:

```
var x = [0,1]
> undefined
x.concat([3,4,5]);
> [0, 1, 3, 4, 5]
x
> [0, 1]
```

So this was broken for prior deploys and will need to be fixed.

**Comment by samreid** [comment]
Fixed above, reassigning to @jbphet to see if any deployed or delivered files need to be patched.

**Comment by pixelzoom** [comment]
This looks like it should be verified before deploying sims.  Assigned to @jbphet since 7/8.

**Comment by pixelzoom** [comment]
Ah... This is just together-specific licensing that was missing. So does not apply to S2015R.

**Comment by jbphet** [comment]
I checked, and all sims delivered to the two primary customers with whom I've been working were built after the fix made above, so it should be safe to close this.
