### ISSUE TITLE
Require projectURL for licenses

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#170]
https://github.com/phetsims/sherpa/issues/48 was being caused by a missing projectURL in stats.  We should add code to check for the existence of the projectURL and fail if it is missing.

**Comment by samreid** [comment]
I added a check above.  I tested removing projectURL temporarily and observing that hookes-law failed to build.  Adding the projectURL back in caused hookes-law to lint and build properly.   Anybody want to review this small change set? @jbphet @jonathanolson @aaronsamuel137 @pixelzoom ?

**Comment by samreid** [comment]
I decided notes should be required as well (committed above), and tested grunt + launch for hookes-law.

**Comment by pixelzoom** [comment]
Sounds ok to make projectURL and notes required fields.  Changes look good. Closing.
