### ISSUE TITLE
Report which images/audio for a simulation were *not* used

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#172]
After a requirejs build and all dependencies have been traversed, we should search for which images/audio have *not* been used and error/warn the developer so things can get cleaned up.

**Comment by samreid** [comment]
This list is not necessarily complete, but running `grunt licenseTXTReport` and comparing the output to the `grunt-all.sh build-no-lint` with plugin checks enabled shows the following problematic images that are not used in the sims:

NOT ANNOTATED IN FILE: /Users/samreid/github/capacitor-lab-basics/images/closeButton.png
NOT ANNOTATED IN FILE: /Users/samreid/github/capacitor-lab-basics/images/probe_3D_black_large.png
NOT ANNOTATED IN FILE: /Users/samreid/github/capacitor-lab-basics/images/probe_3D_black_large_cutout.png
NOT ANNOTATED IN FILE: /Users/samreid/github/capacitor-lab-basics/images/probe_3D_field_cutout.png
NOT ANNOTATED IN FILE: /Users/samreid/github/capacitor-lab-basics/images/probe_3D_field_large.png
NOT ANNOTATED IN FILE: /Users/samreid/github/capacitor-lab-basics/images/probe_3D_red_large.png
NOT ANNOTATED IN FILE: /Users/samreid/github/capacitor-lab-basics/images/probe_3D_red_large_cutout.png
NOT ANNOTATED IN FILE: /Users/samreid/github/capacitor-lab-basics/images/probe_3D_red_large_outline.png
NOT ANNOTATED IN FILE: /Users/samreid/github/color-vision/images/head.svg
NOT ANNOTATED IN FILE: /Users/samreid/github/gene-expression-basics/images/GEB-02.png
NOT ANNOTATED IN FILE: /Users/samreid/github/gene-expression-basics/images/GEB-03.png
NOT ANNOTATED IN FILE: /Users/samreid/github/gene-expression-basics/images/GEB-04.png
NOT ANNOTATED IN FILE: /Users/samreid/github/gene-expression-basics/images/GEB-05.png
NOT ANNOTATED IN FILE: /Users/samreid/github/gene-expression-basics/images/GEB-06.png
NOT ANNOTATED IN FILE: /Users/samreid/github/masses-and-springs/images/ruler.png
NOT ANNOTATED IN FILE: /Users/samreid/github/neuron/images/neuron-mockup.png
NOT ANNOTATED IN FILE: /Users/samreid/github/neuron/images/neuron-particles-test-texture.png
NOT ANNOTATED IN FILE: /Users/samreid/github/neuron/images/neuron-particles-texture-2.png
NOT ANNOTATED IN FILE: /Users/samreid/github/neuron/images/neuron-particles.png
NOT ANNOTATED IN FILE: /Users/samreid/github/plinko-probability/images/mockup01.png
NOT ANNOTATED IN FILE: /Users/samreid/github/plinko-probability/images/mockup02.png
NOT ANNOTATED IN FILE: /Users/samreid/github/rutherford-scattering/images/exampleGun.jpg
NOT ANNOTATED IN FILE: /Users/samreid/github/rutherford-scattering/images/gunOffButton.png
NOT ANNOTATED IN FILE: /Users/samreid/github/rutherford-scattering/images/gunOnButton.png
NOT ANNOTATED IN FILE: /Users/samreid/github/rutherford-scattering/images/plumPudding-Fireworks.png
NOT ANNOTATED IN FILE: /Users/samreid/github/rutherford-scattering/images/plumPudding.png
NOT ANNOTATED IN FILE: /Users/samreid/github/rutherford-scattering/images/ray-gun.png
NOT ANNOTATED IN FILE: /Users/samreid/github/rutherford-scattering/images/testImage.png
NOT ANNOTATED IN FILE: /Users/samreid/github/sugar-and-salt-solutions/images/battery.png
NOT ANNOTATED IN FILE: /Users/samreid/github/sugar-and-salt-solutions/images/lightBulbBase.png
NOT ANNOTATED IN FILE: /Users/samreid/github/sugar-and-salt-solutions/images/lightBulbGlass.png
NOT ANNOTATED IN FILE: /Users/samreid/github/sugar-and-salt-solutions/images/lightBulbGlassMask.png

So many unused images!  We should delete most of them, I presume.

**Comment by samreid** [comment]
@jbphet @jonathanolson @pixelzoom @aaronsamuel137 @jessegreenberg should we fail the build if there are unused image/audio files in the simulation directory?

**Comment by jonathanolson** [comment]
If it's phet-branded, sounds good to me (but allow --force).

**Comment by samreid** [comment]
Consensus from developer meeting: always print warnings.  This way we can check in all of the artwork when we receive it and still be able to build without --force.

**Comment by samreid** [comment]
I added the warnings above and am seeing unused images in balancing-act and balancing-chemical-equations.  We should create a separate issue to iterate over all repos and look for unused things.
