### ISSUE TITLE
Provide attribution for 3rd party images/audio in the compiled HTML file

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#175]
From #171: The build output should include a statement of 3rd party image/audio/mipmap files and their source & license.

For some 3rd parties such as NASA, this is important to be in concordance with their terms, but we should be doing it for every 3rd party resource.

**Comment by samreid** [comment]
I've got this working in my working copy.  Here's an example of the output for gravity-and-orbits:

```js
  window.phet.chipper.thirdPartyLicensesImagesAudio = [
  {
    "name": "GRAVITY_AND_ORBITS/earth.gif",
    "licenseInfo": "earth.gif source=NASA notes=see http://www.harmsy.freeuk.com/images/earth2.jpeg, http://cac-science8.wikispaces.com/ nasa copyright rules here http://www.nasa.gov/audience/formedia/features/MP_Photo_Guidelines.html"
  },
  {
    "name": "GRAVITY_AND_ORBITS/moon.png",
    "licenseInfo": "moon.png source=public domain notes=http://astro.unl.edu/misc/moonpics/moon08_th.jpg public domain license at http://astro.unl.edu/misc/moonpics"
  },
  {
    "name": "GRAVITY_AND_ORBITS/space-station.png",
    "licenseInfo": "space-station.png source=NASA notes=http://www.nasa.gov/images/content/323090main_s119e009793_hires.jpg linked from http://www.nasa.gov/mission_pages/station/multimedia/iss_sts119_images.html"
  }
]
```

I'm including the name since it should be unique (otherwise different images with the same name would have collisions).

I'm putting this output directly beneath the 3rd party code licenses.

Having trouble deciding what to name this.  It is currently for non-code assets, such as images and audio.  The current name is thirdPartyLicensesImagesAudio but that is a bit unwieldy.

**Comment by samreid** [comment]
I tested with grunt for hookes-law and didn't see any lint or build errors.  By the way, the output for a simulation without any 3rd party images or audio such as hookes-law looks like this:

```js
window.phet.chipper.thirdPartyLicensesImagesAudio = [];
```

Since lint+grunt are passing, I'll commit shortly.

**Comment by samreid** [comment]
I pushed the changes above.  We could take additional steps to beautify the output if we decide it is necessary but at least we are reporting on these licenses now.

**Comment by pixelzoom** [comment]
Reopening to ask a question.  I see that  we now have window.phet.chipper.thirdPartyLicensesImagesAudio. Why can't images and audio be added to window.phet.chipper.thirdPartyLicenses?

**Comment by pixelzoom** [comment]
Or perhaps a better questions is: Why is it necessary to have separate globals for libs vs audio/images? 

Also note a bug in createCompositeThirdPartyReport.js:

> 'their HTML files for the `window.phet.chipper.thirdPartyLicenses` and `window.phet.chipper.thirdPartyImagesAndAudio`

Is the global named thirdPartyLicenses or thirdPartyLicensesImagesAudio?

**Comment by samreid** [comment]
> Or perhaps a better questions is: Why is it necessary to have separate globals for libs vs audio/images?

This question is also touched on in https://github.com/phetsims/chipper/issues/194 .  For reports, etc I think it is valuable for us to distinguish the types of certain objects, so that a report can show "code" first, then "images" etc.  So that means either (a) keeping things in separate lists or (b) adding "type" metadata to each entry.

Note from #194 that things are basically "code + fonts" vs "images + audio" at the moment, from the way things are loaded.  Do you think we should take the additional step of creating 4 separate lists?  Adding "type" metadata, etc?

**Comment by pixelzoom** [comment]
> Do you think we should take the additional step of creating 4 separate lists? Adding "type" metadata, etc?

Yes.

Also recommended to move font-related stuff to sherpa/fonts/, with an associated license.json file.

**Comment by pixelzoom** [comment]
Btw... A "type" field in license.json may not be necessary. It can be inferred from where it lives, perhaps using the subdirectory name. Eg:

sherpa/lib/license.json ->  "lib"
sherpa/fonts/license.json -> "font"
my-sim/images/license.json -> "image"
my-sim/audio/license.json -> "audio"

Then consolidate to one global. Eg:

```js
window.phet.chipper.licenses = {
lib: { ... },
font: { ... },
image: { ... },
audio: { ... },
...
}
```

**Comment by pixelzoom** [comment]
Btw... A resource "type" field in license.json may not be necessary. The type can be inferred from where it lives. Eg:

(directory -> type)
sherpa/lib/license.json ->  "lib"
sherpa/fonts/license.json -> "font"
my-sim/images/license.json -> "image"
my-sim/audio/license.json -> "audio"

Then consolidate to one global. Eg:

```js
window.phet.chipper.licenses = {
lib: { ... },
fonts: { ... },
images: { ... },
audio: { ... },
...
}
```

**Comment by samreid** [comment]
Above, it was proposed that we call it `window.phet.chipper.licenses` but it excludes the license of the HTML file itself and only pertains to included 3rd party materials.  What do you think about calling it `window.phet.chipper.thirdPartyLicenses`?

**Comment by pixelzoom** [comment]
` window.phet.chipper.thirdPartyLicenses` sounds fine.

**Comment by pixelzoom** [comment]
For consistency, how about renaming TranslationCreditPanel.java to TranslationCreditsPanel.java?

**Comment by samreid** [comment]
I'll move forward with `window.phet.chipper.thirdPartyLicenses` but wanted to note that we decided our Font occurrences are actually more Lib-like, so we won't have a font category.

**Comment by samreid** [comment]
Note: we are already using `window.phet.chipper.thirdPartyLicenses` but now we will nest lib/images/audio within it.

**Comment by samreid** [comment]
I think I'll create a separate sub issue for the remainder of the work to make it clear what's happening.
