### ISSUE TITLE
Don't check license.json entries when building as non-phet brands

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#176]
@jonathanolson suggested in #171 that we should not require simulations to have license attributions in the license.txt files when building with a 3rd-party brand (such as a non-phet brand).

**Comment by samreid** [comment]
I'm going to unassign this until I get to work on the branding issues.

**Comment by pixelzoom** [comment]
Retitling issue, since license.txt is now license.json.

**Comment by samreid** [comment]
Fixed above and tested by building build-a-molecule (which has license issues) for default brand and phet brand.  phet brand failed and adapted-from-phet succeeded. Closing.
