### ISSUE TITLE
Check license.json entries during the require.js mode when brand==='phet'

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#177]
From #171:

> Bonus points if we can additionally get this to work in requirejs (dynamic) mode.

**Comment by samreid** [comment]
(unless it makes simulation launch take a lot longer)

**Comment by samreid** [comment]
This should also respect the branding, and have the same behavior as during a build.  Missing or incompatible license information during phet mode=>fail.  During adapted-from-phet mode => ok.

**Comment by samreid** [comment]
I'm going to unassign this for now and leave it for work during branding.

**Comment by samreid** [comment]
Branding time draws nigh.  Reassigning to @samreid.

**Comment by samreid** [comment]
Note: from #176 this should only get checked if brand==='phet'.

**Comment by samreid** [comment]
It actually seems like a lot of work to XHR load the license.json files to check this.  One of the troubles being how to find and download the right license.json file and then waiting for the results before proceeding (or I guess once results obtained, we could print an error then).  Can other developers (a) think of an easy way to do this or (b) ok if we only check this during builds?

**Comment by zepumph** [comment]
Consensus: 8/6 dev meeting. It is ok to have this at build time only.
