### ISSUE TITLE
Review of new licensing code

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#178]
After 

- [x] #162
- [x] #170
- [x] #171 
- [x] #172
- [x] #174
- [x] #175
- [x] #179 
- [x] #180 
- [x] #181 
- [x] #182 
- [x] #183
- [x] #185 
- [x] #186 
- [x] #188 
- [x] #189
- [x] #191
- [x] #193 

are completed, this entire suite of work should be reviewed.

Note that #184 and #187 and #194 are still under discussion.

**Comment by samreid** [comment]
I'm wondering if I should have used a milestone instead of label for these related issues.......

**Comment by samreid** [comment]
I've finished the licensing work above.  Quick summaries of what was done:

1. Simulations fail to build if they use images/audio with incomplete/incompatible licensing.  Build a molecule still suffers from this problem https://github.com/phetsims/build-a-molecule/issues/75
2. Added a new grunt task `create-license-json-report`
 * (project-wide) Report on license.json files throughout all working copies. Reports any images or audio that have any of the following problems:
    * missing-license.json
    * third-party
    * not-annotated           

3. Added a new grunt build option `--createSimSpecificThirdPartyReport` which creates a report for that simulation that includes the code/font/image/audio licensing details.  This runs the requirejs step to determine what images & audio are actually used by the simulation, and uses the 3rd party code dependencies & fonts as set by the package.json (and includes libraries used in every sim)
4. Added a new grunt task: `create-composite-third-party-report`
  * Given the simulation-specific reports created by createSimSpecificThirdPartyReport, aggregate them and provide a complete report, indicating which third-party resources are used by which simulations. 

The result of this final step can be seen here:
https://github.com/phetsims/sherpa/blob/master/third-party-licenses.md

I think this project is ready for (a) discussion of the outstanding issues noted in the issue description, (b) discussion of the other open licensing issues and (c) code review of the work described above and in the issues marked in the issue description.  Two of our development team members are currently away, perhaps it would be best to wait until they return before discussion or scheduling review.

**Comment by samreid** [comment]
Some pre-review notes:

* The new code passes jshint
* The new tasks run without errors (aside from https://github.com/phetsims/build-a-molecule/issues/75 )
* The new grunt tasks are documented
* The new grunt tasks have been tested from multiple simulation directories

Additional questions for the reviewer:

Discussion of #177, #184,  #187 and #194.

Does https://github.com/phetsims/chipper/blob/master/js/grunt/createCompositeThirdPartyReport.js contain enough code comments/documentation?  Does it require any refactoring/cleanup?

Should createSimSpecificThirdPartyReport be a grunt task rather than a build option?

Should the third-party-report.json be created during every build?

How to handle stale third-party-report.json files?

**Comment by samreid** [comment]
Some skype notes from @pixelzoom:

> [8/3/15, 1:22:07 PM] Chris Malley: createSimSpecificThirdPartyReport is not shown as an option to the build task in "grunt help".
[8/3/15, 1:23:10 PM] Chris Malley: create-license-json-report apparently doesn't include sherpa/lib/license.json?

**Comment by pixelzoom** [comment]
"grunt create-composite-third-party-report" fails, see #199.

**Comment by pixelzoom** [comment]
> Should createSimSpecificThirdPartyReport be a grunt task rather than a build option?

My first inclination is yes, for symmetry with create-composite-third-party-report. But I'm not at all clear on how these reports are intended to be used, when they need to be run, or whether its desirable to fail a build when the licensing is not in order.

**Comment by pixelzoom** [comment]
Why do we need `create-composite-third-party-report`? Why can't we just have a sim-specific report (e.g. license-report), and periodically run "grunt-all.sh license-report"?  Is aggregation by a build task really worth the effort?

**Comment by pixelzoom** [comment]
> How to handle stale third-party-report.json files?

Since "grunt create-composite-third-party-report" currently fails (see #199) I didn't realize that an output file was created.  Where is it created? (This should be indicated in the "grunt help" doc.) Is there an automatic git add/commit/push?

**Comment by pixelzoom** [comment]
I've created 8 new issues, so perhaps this is a good place to pause this review.  Back to @samreid.

**Comment by samreid** [comment]
> Is aggregation by a build task really worth the effort?

As explained above in https://github.com/phetsims/chipper/issues/178#issuecomment-125827443, this task is what generates the final (important) report here:

https://github.com/phetsims/sherpa/blob/master/third-party-licenses.md

**Comment by samreid** [comment]
Thanks for the review @pixelzoom.  I'll take it from here and let you know when I'm at a good point to discuss it again.

**Comment by samreid** [comment]
@pixelzoom I addressed several issues and raised questions in several issues.  The only open "licensing" issues assigned to me are the ones cross-listed with branding, and I'm saving those for a later step.  So I'm ready for your feedback on the chipper & licensing issues assigned to you.

**Comment by pixelzoom** [comment]
All issues commented on and a few new ones created. Back to @samreid.

**Comment by samreid** [comment]
Thanks, I'll take a look at everything and let you know when I'm ready for you again.

**Comment by samreid** [comment]
It seems like we are at a good point to review open issues on an issue-by-issue basis.  @pixelzoom can we close this one?

**Comment by pixelzoom** [comment]
Yep. Closing.
