### ISSUE TITLE
Create stricter rules for license.txt parsing

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#179]
Currently license parsing is just a string search.  For instance:

license=this used to be public domain but isn't anymore

would result in a classification of "public domain" because it contains that text.  We will either need a better system or to be very careful about the text in our license.txt files.

**Comment by samreid** [comment]
#181 would help with this quite a bit

**Comment by samreid** [comment]
Since this has been converted to JSON and all of the data normalized, this issue is resolved, closing.

**Comment by pixelzoom** [comment]
Retitled this issue, since license.txt is now license.json.
