### ISSUE TITLE
Unify image/audio and code treatment for 3rd party licensing

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#180]
Currently images/audio are treated completely differently than code for 3rd party licensing, from metadata for attribution to how it appears in the HTML file.  Can/should we unify them?  Ideally yes, but how much effort/complexity will it require?

**Comment by samreid** [comment]
We have started using the same file format and schema, and now the tools that work for 3rd party code also works for 3rd party images/audio for the most part.  Though images/audio are loaded through requirejs so the way the licenses are "gathered up" are a bit different.  Anyways, this may be as far as we can go.

**Comment by pixelzoom** [comment]
Reopening. Why not also unify them in the global that's created and added to the html file?

**Comment by samreid** [comment]
As I mentioned in https://github.com/phetsims/chipper/issues/175#issuecomment-127265301 we need to distinguish the types.  Do you recommend adding a "type" property to each entry?

**Comment by samreid** [comment]
Also, I think we should maintain control over the order that resource types get outputted in the HTML (whether using separate lists or type properties).

**Comment by pixelzoom** [comment]
See my responses in https://github.com/phetsims/chipper/issues/175#issuecomment-127297077 and https://github.com/phetsims/chipper/issues/175#issuecomment-127308210

**Comment by samreid** [comment]
It seems like @pixelzoom's suggestions in #175 are being tracked in #175.  Can we close this issue and continue in #175?

**Comment by pixelzoom** [comment]
Looks like #175 covers this, closing.
