### ISSUE TITLE
Make sure license.txt/license.json doesn't fail builds if --force is set

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#184]
Make sure license.txt/license.json doesn't fail builds if --force is set.  A suggestion from @jonathanolson

**Comment by samreid** [comment]
Apparently we can check if --force is set by doing: grunt.option( 'force' )

However, the grunt is not passed to the image/audio/mipmap plugins so I am not sure how to get this information.  Should we add global.grunt or global.gruntForce?  Not sure it is worth it for this.  @jonathanolson what do you recommend?

**Comment by jonathanolson** [comment]
I was under the impression that calling grunt.log.error (or indicating an error state to Grunt without throwing anything) would cause an abort if running without --force, but would allow the build process to go on if --force is passed.

Can you confirm/clarify, and/or describe why we would need to manually check if the --force option is passed in?

**Comment by samreid** [comment]
I just tried grunt.log.error and it printed out text in red, but reported `Done, without errors.` afterwards.  Perhaps we should use `grunt.fail.warn`? http://gruntjs.com/api/grunt.fail says 

> Display a warning and abort Grunt immediately. Grunt will continue processing tasks if the --force command-line option was specified.

However, in the image plugin, for example, we do not have access to the grunt instance as far as I know.  So how could we use this?

**Comment by pixelzoom** [comment]
I'm not clear... What is the motivation for wanting grunt to proceed when it encounters a problem?

**Comment by jonathanolson** [comment]
> I'm not clear... What is the motivation for wanting grunt to proceed when it encounters a problem?

Same motivation that we can use --force to bypass linting.

**Comment by pixelzoom** [comment]
Bypassing linting can be done via build-no-lint.  

I'm concerned that --force will become a lazy way of bypassing lint, possibly bypassing something more important.

**Comment by samreid** [comment]
I rarely (never?) use --force, though I do use build-no-lint in certain circumstances.  I'm okay to close this issue as "will not fix" but don't have a good sense of how strongly @jonathanolson feels about this or if there are cases where it would be more useful.

**Comment by jonathanolson** [comment]
I don't feel too strongly, but I do use grunt --force a lot (particularly for helping people who have linting issues). I'll be ok saying "I can't help with X until licensing is fixed".

**Comment by pixelzoom** [comment]
@jonathanolson Why can't you use build-no-lint in this situation?

**Comment by pixelzoom** [comment]
Ah, I see... You want something similar to build-no-lint for licensing.

**Comment by pixelzoom** [comment]
Perhaps we should get rid of build-no-lint and make --force work?

**Comment by jonathanolson** [comment]
"grunt --force" lints, but ignores any linting issues and continues the build. I'm not usually bugged by the extra time linting.

Others may have opinions on getting rid of no-lint.

**Comment by samreid** [comment]
I labeled this issue for next developer meeting.

**Comment by samreid** [comment]
I'd like to keep `build-no-lint'.

**Comment by zepumph** [comment]
Consensus 8/6 dev meeting: Try using exceptions for licenses. Each exception is printed as a warning. Also a warning if there are unused media file. 

These are only being checked in the phet brand, so if you build it with the adapted from phet brand, then you wont have these issues.
