### ISSUE TITLE
Put the simNameUppercase in the package.json?

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#187]
For licensing, I need to obtain the uppercased sim name, such as BALANCING_ACT.  I am currently obtaining this by looking at the prefix of the simTitleStringKey, but it may be better to factor out the upper case name into a separate field.  We could potentially even obviate the need for this simTitleStringKey if we can automatically construct it from the lower+upper case names.

**Comment by pixelzoom** [comment]
> I am currently obtaining this by looking at the prefix of the simTitleStringKey, 

There is no requirement that simTitleStringKey contain the repo name, it can be anything. The convention of (for example) `beaker.name` is a hold-over from Java sims and there's nothing that requires that for HTML5 sims.

**Comment by pixelzoom** [comment]
Several sims that don't follow the `repos.name` convention:

friction
ohms-law
resistance-in-a-wire
states-of-matter-basics
wave-on-a-string

**Comment by pixelzoom** [comment]
Also recommended to call this something other than "simNameUppercase".  It's not the sim's name. It's the symbolic constant for the path to the sim's repository.  And it's not exactly repo name in uppercase, hypens are also converted to underscores.

**Comment by pixelzoom** [comment]
Looks like it would be safe to convert the "name" field in package.json.  So now I'm questioning whether an additional field is needed.

**Comment by samreid** [comment]
Thanks for identifying the problem about repo.name.  Perhaps we don't need the SIM_NAME_UPPERCASE here, just a unique identifier for the sim.  Maybe we can use package.json's "name" property?

**Comment by pixelzoom** [comment]
Seems like this issue should be assigned and addressed promptly, since the implemented assumption of using simTitleStringKey will fail for some sims.

**Comment by pixelzoom** [comment]
Yes, recommend to use "name" field in package.json.

**Comment by pixelzoom** [comment]
Ah... I misunderstood this.  simTitleStringKey will indeed always contain the symbolic constant for the sim's repo path as the *prefix* to the string key.  For example: 

`"simTitleStringKey": "HOOKES_LAW/hookes-law.name",`

This will be the case unless a sim gets its title from some other sim's string file -- which should not be the case. But I have seen this done on more than one occasion, typically when one sim is a subset of another sim (e.g. Concentration and Beer's Law Lab).

**Comment by samreid** [comment]
Hmmm.. Simply using the package.json name field will not work here.  What is recorded during the build is the plugin invocation name, such as "BALANCING_ACT/rock.png".  If we want to check for its existence, it will have to be an exact string match.  @pixelzoom do you think it is safe to take package.json's name property, then uppercase it and convert hyphens to underscores to obtain the uppercase name which is required for matching?

**Comment by pixelzoom** [comment]
As mentioned in https://github.com/phetsims/chipper/issues/187#issuecomment-127418725, I think it's probably safe to use the prefix of the simTitleStringKey value.

**Comment by samreid** [comment]
Thanks for clarifying.  Since this is already how it is being done, do you recommend further work for this issue?

The relevant code that implements the "use the prefix" strategy is in afterRequirejsBuild.js:

```js
    // After all plugins completed, check which images & audio files are in the images/audio directories 
    // but not loaded by the plugins. The simNameUppercase such as BALANCING_ACT is required in order
    // to identify the namespaced resources. This reuses the pkg.simTitleStringKey to get the simNameUppercase
    var simNameUppercase = pkg.simTitleStringKey.substring( 0, pkg.simTitleStringKey.indexOf( '/' ) );
```

**Comment by pixelzoom** [comment]
I agree that this works and should continue to work. But grabbing the symbolic path name from from simTyleStringKey feels a little wrong.  Perhaps we should factor out the symbolic path for the sim?  

Here's what package.json (e.g. for balancing-act) might look like. I've used "requirePath" for the name because it's the sim's path as specified in the call to `require.config`.  Use something else if you'd like (symbolicPath, simPath, ...)

```js
{
   "requirePath": "BALANCING_ACT",
   "simTitleStringKey": "balancing-act.name",
   ...
}
```

Changes (with line numbers) requires if we did this:

In afterRequirejsBuild.js:

```js
+ assert( pkg.requirePath, 'requirePath missing from package.json' );
197 var simNameUppercase = pkg.requirePath;
206 var titleKey = pkg.requirePath + '/' + pkg.simTitleStringKey;
```

In build-server.js:

```js
+ assert( packageJSON. requirePath );
179 var simTitleKey = packageJSON. requirePath + '/' + packageJSON.simTitleStringKey;
```

In generateREADME.js:

```js
28 var titleKey = simTitleStringKey;
```

**Comment by pixelzoom** [comment]
Note in the above that I've also removed the path name from the value of "simTitleStringKey".

**Comment by pixelzoom** [comment]
Assigning to @samreid for feedback on the above proposal of factoring out the path name.

**Comment by samreid** [comment]
This is a rather large change and I'd like to get feedback from at least @jonathanolson.  I'll mark it for discussion at tomorrow's developer meeting.

**Comment by samreid** [comment]
Unassigning to remove it from my TODO list, even though it will probably go back on my TODO list tomorrow after the developer meeting.

**Comment by pixelzoom** [comment]
Yes, it is a lot of work. But I think this will fall into the "pay me now, or pay me later" category :)

**Comment by pixelzoom** [comment]
We used to have field "requirejsNamespace", but it was deleted because unused.

Consensus 8/6/15 dev meeting:
• use "requirejsNamespace"
• no change to simTitleStringKey, OK to duplicate
• @pixelzoom will self-assign

**Comment by pixelzoom** [comment]
requirejsNamespace has been added to all package.json files, and reportUnusedMedia.js has been modified to use it instead of stripping the prefix off of simTitleStringKey.

Assigning to @jonathanolson for review.

**Comment by jonathanolson** [comment]
Looks good, thanks.
