### ISSUE TITLE
Standardize images/README.txt

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#190]
About half of our repositories contain images/README.txt.  We should decide whether this belongs here or not and standardize the sims.  In my opinion, the small potential benefit to 3rd parties from the existence of these files does not outweigh the "copy-paste" nature of these files, so I'm planning to delete them.  Please feel free to disagree/discuss.

**Comment by samreid** [comment]
I've removed the images above and will soon create a simula-rasa issue for not propagating the README.txt file.  Closing.

**Comment by pixelzoom** [comment]
Reopening.

We're using README.md at the top level of repos.  And reason why images/README.txt shouldn't also be in .md format?

**Comment by samreid** [comment]
I removed projectile-motion/images/README.txt and renamed simula-rasa/images/README.txt => md, see the above commits.  @pixelzoom anything else to do here?
