### ISSUE TITLE
Give a more specific name to createXML

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#192]
The grunt task createXML has too general a name.  The name should indicate the intended usage and possibly also the contents of the XML.  Task names, filenames, etc should be renamed to match.

**Comment by pixelzoom** [comment]
The documentation for "grunt help" is also lacking. It currently says:

> Write XML file with specific translations for sim

Does "specific translations" means that you can specify which locales you want? 
If so, how does one do that?

**Comment by aaronsamuel137** [comment]
createXML ended up moving inside the build-server code, so it is no longer needed as an independent file or grunt task. I have deleted it.

Assigning to @samreid for review

**Comment by samreid** [comment]
I skimmed the change sets, the grunt --help output and tested a build and everything seemed good, thanks.  Closing.
