### ISSUE TITLE
Require statement names should match

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#195]
While I was reviewing Bending Light, I noticed that one of the PhET code style guidelines says:

> For modules, the var name should match the file name

I wrote a script that uses string parsing to check whether this is the case.  It is neither documented nor generalized but it confirm that Bending Light doesn't suffer from this problem at all.  However, I ran it for our other projects and found this list of mismatches:

var Checkbox = require( 'SUN/CheckBox' );
	/Users/samreid/github/area-builder/js/common/view/AreaBuilderControlPanel.js

var MediumTrashCan = require( 'BALANCING_ACT/common/model/masses/SmallRock' );
	/Users/samreid/github/balancing-act/js/game/model/BalanceGameChallengeFactory.js

var Spectrum = require( 'SCENERY_PHET/SpectrumNode' );
	/Users/samreid/github/blackbody-spectrum/js/blackbody-spectrum/view/GraphDrawingNode.js

var CapacitorLabBasicLightBulbsModel = require( 'CAPACITOR_LAB_BASICS/light-bulb/model/CapacitorLabBasicsLightBulbModel' );
	/Users/samreid/github/capacitor-lab-basics/js/light-bulb/CapacitorLabBasicsLightBulbScreen.js

var Util = require( 'DOT/Util');
	/Users/samreid/github/charges-and-fields/js/charges-and-fields/view/ElectricPotentialLinesNode.js

var uglify = require( '../../../' + pkg.name + '/node_modules/uglify-js' );
	/Users/samreid/github/chipper/js/grunt/afterRequirejsBuild.js

var _ = require( '../../../sherpa/lib/lodash-2.4.1.min' ); // allow _ to be redefined, contrary to jshintOptions.js
	/Users/samreid/github/chipper/js/grunt/createCompositeThirdPartyReport.js

var _ = require( '../../sherpa/lib/lodash-2.4.1.min' );
	/Users/samreid/github/chipper/js/requirejs-plugins/string.js

var text = require( 'text' );
	/Users/samreid/github/chipper/js/requirejs-plugins/string.js

var Rectangle2 = require( 'DOT/Rectangle' );
	/Users/samreid/github/energy-forms-and-changes/js/common/view/BeakerView.js

var EnergyChunkNode = require( 'ENERGY_FORMS_AND_CHANGES/common/view/energyChunkNode' );
	/Users/samreid/github/energy-forms-and-changes/js/intro/view/EnergyChunkContainerSliceNode.js

var DotRectangle = require( 'DOT/Rectangle' );
	/Users/samreid/github/energy-skate-park-basics/js/energy-skate-park-basics/view/EnergySkateParkBasicsScreenView.js

var FILL_TYPE = require( 'FRACTION_MATCHER/model/FillType' );
	/Users/samreid/github/fraction-matcher/js/model/Constants.js

var AttachmentState = require( 'GENE_EXPRESSION_BASICS/common/model/attachmentstatemachines/AttachmentStateMachine' );
	/Users/samreid/github/gene-expression-basics/js/common/model/attachmentstatemachines/MessengerRnaFragmentAttachmentStateMachine.js

var RAND = require( 'DOT/Random' );
	/Users/samreid/github/gene-expression-basics/js/common/model/motionstrategies/DriftThenTeleportMotionStrategy.js

var MovableAtom = require( 'ISOTOPES_AND_ATOMIC_MASS/mix-isotopes/model/MovableAtom');
	/Users/samreid/github/isotopes-and-atomic-mass/js/mix-isotopes/model/MonoIsotopeBucket.js

var Shape = require( 'KITE/shape' );
	/Users/samreid/github/isotopes-and-atomic-mass/js/mix-isotopes/view/AverageAtomicMassIndicator.js

var Rect = require( 'DOT/Rectangle' );
	/Users/samreid/github/john-travoltage/js/john-travoltage/view/ElectronNode.js

var Platform = require( 'PHET_CORE/platform' );
	/Users/samreid/github/joist/js/PhetMenu.js

var packageString = require( 'text!REPOSITORY/package.json' );
	/Users/samreid/github/joist/js/packageJSON.js

var DotUtil = require( 'DOT/Util' );
	/Users/samreid/github/kite/js/segments/Arc.js

var DotUtil = require( 'DOT/Util' );
	/Users/samreid/github/kite/js/segments/EllipticalArc.js

var DotUtil = require( 'DOT/Util' );
	/Users/samreid/github/kite/js/segments/Segment.js

var LSRConstants = require( 'LEAST_SQUARES_REGRESSION/least-squares-regression/LeastSquaresRegressionConstants' );
	/Users/samreid/github/least-squares-regression/js/least-squares-regression/LeastSquaresRegressionScreen.js

var LSRConstants = require( 'LEAST_SQUARES_REGRESSION/least-squares-regression/LeastSquaresRegressionConstants' );
	/Users/samreid/github/least-squares-regression/js/least-squares-regression/view/BestFitLineControlPanel.js

var LSRConstants = require( 'LEAST_SQUARES_REGRESSION/least-squares-regression/LeastSquaresRegressionConstants' );
	/Users/samreid/github/least-squares-regression/js/least-squares-regression/view/DataPointCreatorNode.js

var LSRConstants = require( 'LEAST_SQUARES_REGRESSION/least-squares-regression/LeastSquaresRegressionConstants' );
	/Users/samreid/github/least-squares-regression/js/least-squares-regression/view/DataSetComboBox.js

var LSRConstants = require( 'LEAST_SQUARES_REGRESSION/least-squares-regression/LeastSquaresRegressionConstants' );
	/Users/samreid/github/least-squares-regression/js/least-squares-regression/view/DynamicDataPointNode.js

var LSRConstants = require( 'LEAST_SQUARES_REGRESSION/least-squares-regression/LeastSquaresRegressionConstants' );
	/Users/samreid/github/least-squares-regression/js/least-squares-regression/view/EquationNode.js

var LSRConstants = require( 'LEAST_SQUARES_REGRESSION/least-squares-regression/LeastSquaresRegressionConstants' );
	/Users/samreid/github/least-squares-regression/js/least-squares-regression/view/GraphAxesNode.js

var LSRConstants = require( 'LEAST_SQUARES_REGRESSION/least-squares-regression/LeastSquaresRegressionConstants' );
	/Users/samreid/github/least-squares-regression/js/least-squares-regression/view/GraphNode.js

var LSRConstants = require( 'LEAST_SQUARES_REGRESSION/least-squares-regression/LeastSquaresRegressionConstants' );
	/Users/samreid/github/least-squares-regression/js/least-squares-regression/view/GridIcon.js

var LSRConstants = require( 'LEAST_SQUARES_REGRESSION/least-squares-regression/LeastSquaresRegressionConstants' );
	/Users/samreid/github/least-squares-regression/js/least-squares-regression/view/LeastSquaresRegressionScreenView.js

var LSRConstants = require( 'LEAST_SQUARES_REGRESSION/least-squares-regression/LeastSquaresRegressionConstants' );
	/Users/samreid/github/least-squares-regression/js/least-squares-regression/view/MyLineControlPanel.js

var LSRConstants = require( 'LEAST_SQUARES_REGRESSION/least-squares-regression/LeastSquaresRegressionConstants' );
	/Users/samreid/github/least-squares-regression/js/least-squares-regression/view/PearsonCorrelationCoefficientNode.js

var LSRConstants = require( 'LEAST_SQUARES_REGRESSION/least-squares-regression/LeastSquaresRegressionConstants' );
	/Users/samreid/github/least-squares-regression/js/least-squares-regression/view/ResidualLineAndSquareNode.js

var LSRConstants = require( 'LEAST_SQUARES_REGRESSION/least-squares-regression/LeastSquaresRegressionConstants' );
	/Users/samreid/github/least-squares-regression/js/least-squares-regression/view/SourceAndReferenceNode.js

var LSRConstants = require( 'LEAST_SQUARES_REGRESSION/least-squares-regression/LeastSquaresRegressionConstants' );
	/Users/samreid/github/least-squares-regression/js/least-squares-regression/view/StaticDataPointNode.js

var LSRConstants = require( 'LEAST_SQUARES_REGRESSION/least-squares-regression/LeastSquaresRegressionConstants' );
	/Users/samreid/github/least-squares-regression/js/least-squares-regression/view/SumOfSquaredResidualsChart.js

var Checkbox = require( 'SUN/CheckBox' );
	/Users/samreid/github/making-tens/js/making-tens/explore/view/MakingTensExploreScreenView.js

var DotUtil = require( 'DOT/Util' );
	/Users/samreid/github/molecule-shapes/js/common/model/AttractorModel.js

var NitroglycerinAtom = require( 'NITROGLYCERIN/Atom' );
	/Users/samreid/github/molecule-shapes/js/common/model/RealAtomLocation.js

var DotUtil = require( 'DOT/Util' );
	/Users/samreid/github/molecule-shapes/js/common/model/RealMoleculeShape.js

var DotUtil = require( 'DOT/Util' );
	/Users/samreid/github/neuron/js/neuron/model/PieSliceShapedCaptureZone.js

var ParticlesWebGLNode = require( 'NEURON/neuron/view/ParticlesWebGLNode4' );
	/Users/samreid/github/neuron/js/neuron/view/NeuronScreenView.js

var DOTUtil = require( 'DOT/Util' );
	/Users/samreid/github/neuron/js/neuron/view/ParticleTextureMap.js

var Stats = require( 'stats' );
	/Users/samreid/github/phetcommon/js/view/PerformanceMonitor.js

var ResistanceInAWireStage = require( 'RESISTANCE_IN_A_WIRE/resistance-in-a-wire/view/ResistanceInAWireStageContainer' );
	/Users/samreid/github/resistance-in-a-wire/js/resistance-in-a-wire/view/ResistanceInAWireView.js

var config = require( '../config.json' );
	/Users/samreid/github/rosetta/js/TranslationUtils.js

var dependencies = require( HTML_SIMS_DIRECTORY + simName + '/' + version + '/dependencies.json' );
	/Users/samreid/github/rosetta/js/routes.js

var Rectangle = require( 'SCENERY/nodes/Rectangle');
	/Users/samreid/github/rutherford-scattering/js/common/view/ZoomView.js

var colorVertexShaderSource = require( 'text!SCENERY/display/webgl/colorTriangle.vert' );
	/Users/samreid/github/scenery/js/display/webgl/ColorTriangleRenderer.js

var colorFragmentShaderSource = require( 'text!SCENERY/display/webgl/colorTriangle.frag' );
	/Users/samreid/github/scenery/js/display/webgl/ColorTriangleRenderer.js

var textureVertexShaderSource = require( 'text!SCENERY/display/webgl/texture.vert' );
	/Users/samreid/github/scenery/js/display/webgl/TextureRenderer.js

var textureFragmentShaderSource = require( 'text!SCENERY/display/webgl/texture.frag' );
	/Users/samreid/github/scenery/js/display/webgl/TextureRenderer.js

var KiteLine = require( 'KITE/segments/Line' );
	/Users/samreid/github/scenery/js/nodes/Line.js

var BooleanRectangularToggleButtonWithContent = require( 'SUN/buttons/BooleanRectangularToggleButton' );
	/Users/samreid/github/scenery-phet/js/buttons/SoundToggleButton.js

var ForcesControlNode = require( 'STATES_OF_MATTER/atomic-interactions/view/ForcesControlPanel' );
	/Users/samreid/github/states-of-matter/js/atomic-interactions/view/AtomicInteractionsScreenView.js

var rectangularButtonView = require( 'SUN/buttons/RectangularButtonView' );
	/Users/samreid/github/states-of-matter/js/atomic-interactions/view/ZoomableGridNode.js

var GridNode = require( 'STATES_OF_MATTER/atomic-interactions/view/ZoomableGridNode' );
	/Users/samreid/github/states-of-matter/js/common/view/InteractionPotentialDiagramNode.js

var SugarAndSalSolutionsConstants = require( 'SUGAR_AND_SALT_SOLUTIONS/common/SugarAndSaltConstants' );
	/Users/samreid/github/sugar-and-salt-solutions/js/micro/model/dynamics/CrystalGrowth.js

var BooleanRectangularToggleButtonWithContent = require( 'SUN/buttons/BooleanRectangularToggleButton' );
	/Users/samreid/github/sun/js/demo/ButtonsDemoView.js

var UtilTrig = require( 'TRIG_LAB/trig-lab/common/Util' );
	/Users/samreid/github/trig-lab/js/trig-lab/view/GraphView.js

var UtilTrig = require( 'TRIG_LAB/trig-lab/common/Util' );
	/Users/samreid/github/trig-lab/js/trig-lab/view/ReadoutNode.js

var UtilTrig = require( 'TRIG_LAB/trig-lab/common/Util' );
	/Users/samreid/github/trig-lab/js/trig-lab/view/UnitCircleView.js

Note: a few of these are somewhat false positives since there is the wrong whitespace character in the line (not matching PhetStyle.xml).

In my opinion, these issues like Checkbox/CheckBox and MediumTrashCan/SmallRock should be fixed.  In the former case, a case-sensitive search for 'new CheckBox' would fail and cause problems.  Some of these are legitimate renamings and should probably be kept.

Here's the grunt task I used:
```js
  grunt.registerTask( 'check-style', 'Additional Code Style checks', function() {
    /* jslint node: true */
    // allows "process" to pass lint instead of getting an undefined lint error
    var directory = process.cwd();

    // Start in the github checkout dir (above one of the sibling directories)
    var rootdir = directory + '/../';
    //var rootdir = directory;

    grunt.file.recurse( rootdir, function( abspath, rootdir, subdir, filename ) {
        if (
          filename.toLowerCase().indexOf( '.js' ) >= 0 &&
          abspath.toLowerCase().indexOf( '/js/' ) >= 0 &&
          subdir.indexOf( 'node_modules' ) === -1
        ) {
          //console.log( 'found js file', filename );

          var text = grunt.file.read( abspath );
          var lines = text.split( /\r?\n/ );
          for ( var i = 0; i < lines.length; i++ ) {
            var line = lines[ i ];
            if ( line.indexOf( ' = require( ' ) >= 0 ) {
              //console.log( 'require statement: ' + line );
              var tokens = line.split( /\s+/ );
              //console.log( tokens );
              if ( tokens[ 0 ] === '' && tokens[ 1 ] === 'var' ) {
                var className = tokens[ 2 ];
                var importText = tokens[ 5 ];
                var lastIndex = importText.lastIndexOf( '/' );
                var sub = importText.substring( lastIndex + 1 );
                sub = sub.substring( 0, sub.length - 1 );
                //console.log( 'sub', sub );
                if ( sub !== className &&
                     line.indexOf( 'string!' ) === -1 &&
                     line.indexOf( 'image!' ) === -1 &&
                     line.indexOf( 'mipmap!' ) === -1 &&
                     line.indexOf( 'audio!' ) === -1 &&
                     line.indexOf( ').' ) === -1
                ) {
                  //console.log( 'Mismatch, ' + className + '!=' + sub + ', in ' + abspath, '\n\t> ', line );
                  console.log( line.trim() + '\n\t' + abspath + '\n' );
                }
              }
            }
          }
        }
      }
    )
  } )
```

Note that this task ignores plugins, but we could extend it to catch those errors too, if desired.

I have placed this issue in chipper since it seems the appropriate place to check in additional style checks, if we need to.  And I thought it would be good to discuss how/who should solve these before breaking them out into separate issues (if at all).  I'll add it to an upcoming meeting agenda.

**Comment by pixelzoom** [comment]
I don't see this grunt task in chipper, and you haven't identified it by name.  Where do I find it?

**Comment by pixelzoom** [comment]
@samreid I don't see this grunt task in chipper, and you haven't identified it by name.  Where do I find it?

**Comment by samreid** [comment]
I did not commit the new task, it only appears in the issue description above.  I thought it would be best to discuss it before committing it to chipper.  And if committing to chipper it would have to be documented properly and moved to a separate JS file (and other hygiene as appropriate).

**Comment by zepumph** [comment]
Consensus 8/6 dev meeting: try to put this check into the lint phase, and if not make it a second check afterwards. Run it always during a build, like lint.

**Comment by samreid** [comment]
Also, ok to add this and other code-reviewish things to the standard build, as long as they don't slow down the build.

**Comment by samreid** [comment]
Apparently you cannot add your own logic and checks into jshint 2, but this may be coming in jshint 3: http://jshint.com/blog/jshint-3-plans/

It seems like an alternative that provides the "add your own logic" feature is eslint:
https://gist.github.com/jareware/7179093

It seems popular enough that it might be worth investigation:
https://github.com/eslint/eslint

I'll create a separate issue.

**Comment by samreid** [comment]
Notes in eslint suggest this may not be coming in jshint 3.

**Comment by samreid** [comment]
Even the simplest task of unifying the files tested by jshint and our own custom logic seems daunting.

**Comment by samreid** [comment]
I'm fixing the issues above manually.  I tested each fixed sim by launching the non-built version in the browser and looking for issues.  I couldn't get energy-forms-and-changes or gene-expression-basics to launch, so I'm omitting those changes, which ideally will be caught during code review anyways.  Neuron was in a debugger-ish sort of code, so I left it since it will probably be eliminated.  Rutherford had launch errors, so I skipped it.  States of matter had navbar icon size errors and wouldn't launch, so I bailed on those changes too.  Sugar and salt solutions won't launch, so I'm skipping it too.

By the way, several sims are missing from phetmarks, such as isotopes-and-atomic-mass and rutherford-scattering.

Commits coming.

**Comment by samreid** [comment]
In my opinion it would be awkward for us to add lint-ish rules completely separately from our lint checker.  I recommend investigating eslint in #235 and if that works, we can try adding a rule for "Require statement names should match".  Otherwise this may be best left for manual review or running a script like the above in controlled circumstances.

**Comment by samreid** [comment]
Not planning to work on this further, so unassigning.

**Comment by pixelzoom** [comment]
Since we've moved to ESLint and you wrote the require-statement-match.js rule, can this issue be closed?

**Comment by samreid** [comment]
Yes, we added our own rule for this in ESLint, closing.
