### ISSUE TITLE
createCompositeThirdPartyReport.js uses console.log

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#196]
In https://github.com/phetsims/chipper/issues/125, we decided to use grunt.log for all logging.  That seems to get violated whenever some adds or modifies a grunt task. The latest example is createCompositeThirdPartyReport.js, line 265: 

> console.log( OUTPUT_FILE + ' contents are the same.  No need to save/commit.' );

**Comment by samreid** [comment]
I fixed this occurrence above.  Should we add a lint-ish rule that checks for the existence of the text "console.log" in certain chipper subdirectories?

**Comment by samreid** [comment]
Sorry @patricialoeblein, assigned to you temporarily accidentally.  Over to you @pixelzoom.

**Comment by pixelzoom** [comment]
Looks good.  Issue of catching this automatically moved to https://github.com/phetsims/chipper/issues/197. Closing.
