### ISSUE TITLE
grunt create-license-json-report should iterate over active-repos and focus search on images & audio

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#198]
Previous version was looking recursively over everything.

**Comment by samreid** [comment]
Perhaps use active-runnables so we don't hit website repo, etc.

**Comment by pixelzoom** [comment]
By searching over all directories, it's potentially looking at things that it shouldn't be looking at. And it's potentially missing things that it should be looking at if all repos aren't checked out.

**Comment by samreid** [comment]
Well, we cannot use active-runnables since that would miss things like joist.

**Comment by samreid** [comment]
Fixed above.  @pixelzoom can you take a look and let me know if you recommend further work?

**Comment by pixelzoom** [comment]
Implementation is flawed.  If one of the active-repos is not checked out, this task should fail. As implemented it silently ignores the missing repo and produces an incomplete report.

**Comment by pixelzoom** [comment]
I added an assertion to verify that the repo exists. If you'd prefer to handle this differently, go for it. The important point is that the task should bail if a required repo is missing. 

Assigning to @samreid for review.

**Comment by pixelzoom** [comment]
Whoopise, stand by, what I checked in has a problem.

**Comment by pixelzoom** [comment]
OK, fixed.

**Comment by samreid** [comment]
I tried deleting one of the repos and confirmed that the report bails with an error.  Thanks, closing.
