### ISSUE TITLE
createSimSpecificThirdPartyReport option not reported by "grunt --help"

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#200]
#178 says:

> Added a new grunt build option --createSimSpecificThirdPartyReport which creates a report for that simulation that includes the code/font/image/audio licensing details.

This option to the build task is not reported by "grunt --help".  Eg:

**Comment by samreid** [comment]
In https://github.com/phetsims/chipper/issues/178 @pixelzoom said he was inclined to make this a grunt task rather than a build option.  Perhaps we should focus our efforts there instead of documenting this as a grunt option.

**Comment by samreid** [comment]
I created #207 to move this to a task instead of build option, which will obviate this task.  Closing.
