### ISSUE TITLE
create-license-json-report violates convention for name of associated .js file

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#201]
Noted during review in #178.

In chipper/js/Gruntfile.js:

```js
  // See licenseJSONReport.js
  grunt.registerTask( 'create-license-json-report', '(project-wide) Report on license.json files throughout all working copies. ' +
                                                    'Reports any images or audio that have any of the following problems:\n' +
                                                    '\n' +
                                                    'missing-license.json\n' +
                                                    'third-party\n' +
                                                    'not-annotated\n', function() {
    licenseJSONReport( grunt );
  } );
```

When tasks correspond to a single .js file, our convention is for task "some-task" to be implemented in someTask.js.  In this case task "create-license-json-report'" is implemented by licenseJSONReport.js.  

Why the break in convention?

**Comment by samreid** [comment]
Fixed above, and tested with grunt create-license-json-report in hookes-law with no problems noted.  Reassigning to @pixelzoom to see if there's anything else.
