### ISSUE TITLE
task create-license-json-report is poorly named

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#202]
Noted during review in #178.

In https://github.com/phetsims/sherpa/issues/54, sherpa/lib/third-party-license.json was renamed to license.json for uniformity.  So perhaps task `create-license-json-report` was appropriately named before that change. But it is now poorly named, since it reports only on license.json for images and audio.

**Comment by samreid** [comment]
Or perhaps create-license-json-report should report on lib and font as well?

**Comment by samreid** [comment]
Well, since simulations can add images and/or audio (and not lib or fonts) perhaps we should just rename this task accordingly.

**Comment by samreid** [comment]
Renamed above and tested by running `grunt create-image-and-audio-license-report` in hookes-law.  Seemed ok.  Reassigning to @pixelzoom for further discussion.

**Comment by samreid** [comment]
Well, keep in mind that grunt task names are subject to be shortened in https://github.com/phetsims/chipper/issues/209 anyways.

**Comment by pixelzoom** [comment]
Name is better. But imo putting "images and audio" in this and other names (e.g., reportUnsedImagesAndAudio.js) is short-sighted.

**Comment by pixelzoom** [comment]
To be more specific... Names like `createMediaLicenseReport` and `reportUnusedMedia.js` would (most importantly) allow us to more easily incorporate additional media resource types in the future. Secondarily they wouldn't have "JSON" in their names, and wouldn't be confused with the license.json file(s) in sherpa.

**Comment by samreid** [comment]
I think this will get solved in #212, closing.
