### ISSUE TITLE
when to check licensing correctness?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#203]
Noted during review in #178.

In afterRequirejsBuild.js, this happens at line 194:

```js
    // After all plugins completed, check which images & audio files are in the images/audio directories 
    // but not loaded by the plugins. The simNameUppercase such as BALANCING_ACT is required in order
    // to identify the namespaced resources. This reuses the pkg.simTitleStringKey toget the simNameUppercase
    var simNameUppercase = pkg.simTitleStringKey.substring( 0, pkg.simTitleStringKey.indexOf( '/' ) );
    reportUnusedImagesAndAudio( grunt, simNameUppercase );
```

Why is this done *after* all images and audio are processed? Shouldn't the correctness of licensing be checked *before* any significant work is done?

**Comment by samreid** [comment]
Running the require.js build step is the only way to determine which images & audio are actually used by a simulation.

**Comment by pixelzoom** [comment]
> Running the require.js build step is the only way to determine which images & audio are actually used by a simulation.

I'm not question that it needs to be done in the build step. I'm questioning when it's being done in the build step.

**Comment by samreid** [comment]
It is literally the first thing that happens after all plugins have been resolved.  I'm confused.

**Comment by pixelzoom** [comment]
OK, I re-read all of the source to figure out how this works, because I'm not getting what I need from the documentation. Doc in getLicenseInfo.js says "This file is used during string and audio plugin resolution in order to accomplish 2 goals". But this has nothing to do with plugin "resolution" (identification, determination... pick your favorite definition of resolution), it has to do with the loading of resources by the plugins. It also has to be done after loading mipmaps (not after requirejs) because of mipmaps can't be loaded synchronously during the require.js build step.

So... Plugins used to load media resources (audio, image, mipmap) call getLicenseInfo for each resource loaded. Each time a resource is loaded by a plugin, it's license info is added to global.imageAndAudioLicenseInfo. At the end of the requirejs step, all resources will have been loaded, and we'll have a list of the resources used by the sim.  We can then compare that list to what's in the filesystem, and identify resources that aren't used.  So now I understand why this needs to be done after loading mipmaps in the afterRequirejsBuild task.

**Comment by pixelzoom** [comment]
Since reportUnusedImagesAndAudio requires global.imageAndAudioLicenseInfo as a prerequisite, it should assert that it exists. This convention is used throughout other tasks/functions that share information via globals.  See for example afterRequirejsBuild.js:

```js
  // globals that should be defined by this point
  assert( global.phet, 'missing global.phet' );
  assert( global.phet.thirdPartyLicenses, 'missing global.phet.thirdPartyLicenses' );
  assert( global.phet.strings, 'missing global.phet.strings' );
  assert( global.phet.localesToBuild, 'missing global.phet.localesToBuild' );
  assert( global.phet.mipmapsToBuild, 'missing global.phet.mipmapsToBuild' );
```

**Comment by pixelzoom** [comment]
Assertion for global.imageAndAudioLicenseInfo added.  Assigning to @samreid for verification.  If it looks ok, feel free to close.

**Comment by pixelzoom** [comment]
I also added doc about global.imageAndAudioLicenseInfo to getLicenseInfo and reportUnusedImagesAndAudio.

**Comment by samreid** [comment]
Thanks, the change sets above look good and I verified grunt and looked at the HTML output for third party licenses and everything still looked ok.  Closing.
