### ISSUE TITLE
create-license-json-report task help is incomprehensible

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#205]
Noted during review #178.

The last 3 lines of the task help for create-license-json-report are incomprehensible.

```
% grunt --help
...
          create-license-json-report  (project-wide) Report on license.json    
                                      files throughout all working copies.     
                                      Reports any images or audio that have any
                                      of the following problems:               
                                                                               
                                      missing-license.json                     
                                      third-party                              
                                      not-annotated  
...
%
```

**Comment by pixelzoom** [comment]
I can guess that `missing-license.json` means that a license.json file is missing in some images/ or audio/ directory.  Perhaps `not-annotated` means that there's a license.json file, but the resource has no entry in it. No idea what `third-party` means.

**Comment by samreid** [comment]
It is documented in the createLicenseJSONReport:

 * missing-license.json: => The resource file has no associated license.json file
 * third-party =========>Known to be from an unapproved source outside of PhET
 * not-annotated ======> There is a license.json file but the asset is not in there

I tried putting that information in the grunt help previously but it didn't seem to fit well in the thin columns.  I'll leave this assigned to me to see if there's a way to move some of this information to the help.

**Comment by samreid** [comment]
Improved docs for create-license-json-report.  I tried adding verbose text again but it is very difficult to parse.  I eventually settled on this:

```
          create-license-json-report  (project-wide) Report on license.json    
                                      files throughout all working copies.     
                                      Reports any images or audio that have any
                                      of the following problems:               
                                                                               
                                      missing-license.json (no file)           
                                      third-party (incompatible license)       
                                      not-annotated (entry missing)  
```

Does that solve the problem?

**Comment by samreid** [comment]
Committed above and reassigned to @pixelzoom for feedback.

**Comment by pixelzoom** [comment]
By the time I reviewed this, it now looks like:

```
 create-image-and-audio-license-report  (project-wide) Report on license.json  
                                        files throughout all working copies.   
                                        Reports any images or audio that have  
                                        any of the following problems:         
                                        (1) missing-license.json (no           
                                        license.json for the resource)         
                                        (2) incompatible-license (resource     
                                        license not approved)                  
                                        (3) not-annotated (entry missing from  
                                        license.json)                          
                                        (4) missing-file (entry in the         
                                        license.json but not on the file       
                                        system)  
```

And that looks fine to me.

Closing.

**Comment by pixelzoom** [comment]
Reopening. 

Documentation in getLicenseInfo.js is now stale:

`* The classification is one of: missing-license.json, not-annotated, phet or third-party`

**Comment by pixelzoom** [comment]
Reopening.

Is the documentation in getLicenseInfo.js now incorrect? Or is "classification" something else?

* The classification is one of: missing-license.json, not-annotated, phet or third-party

**Comment by pixelzoom** [comment]
Reading the source, I guess it's something else. Changing "third-party" to "incompatible-license" in this issue was what confused me.  Re-closing.
