### ISSUE TITLE
odd/misleading use of JSLint option

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#206]
Noted in review #178.

In createCompositeThirdPartyReport, at line 38:

```
  /* jslint node: true */
  // allows "process" to pass lint instead of getting an undefined lint error
  var directory = process.cwd();
```

The comment here is misleading. This doesn't just allow "process" to pass lint.  It causes *all* object that can be accessed by node.js to pass lint.   If you wanted only "process" to pass lint, then you'd use `/*global process */`.

This is also a non-standard place to put this JSLint option. It's typically placed at the *top* of the source file. See https://coderwall.com/p/-h1h1w/how-to-use-jslint-in-node-js-projects-properly

**Comment by samreid** [comment]
This directive appears 8 times throughout chipper.

**Comment by samreid** [comment]
We have many things competing to be the "top" of the source file, including the copyright statement, the jsdoc, use strict and this jslint directive.  I'll move this jslint directive to be directly above the 'use strict' statement in all of our files (and add 'use strict') where I saw it missing.

Can our 'use strict's move underneath the jsdoc?  It might be a good place to standardize.

**Comment by samreid** [comment]
Will it create problems to move the 'use strict' out of the exports?

**Comment by aaronsamuel137** [comment]
Thanks for moving these @samreid.

I like the placement of this below the jsdoc. I don't think it will cause problems to have it out of the exports, and it is useful in files like routes.js (in rosetta) where there are multiple exports that would all require their own 'use strict' otherwise.

**Comment by samreid** [comment]
I'll reassign to me to work on as @aaronsamuel137 suggested.

**Comment by samreid** [comment]
Fixed as described in the commit message above.  @aaronsamuel137 when you have time can you double check and see if there is anything else to do here?

**Comment by aaronsamuel137** [comment]
Changes look good to me. Closing.
