### ISSUE TITLE
global.imageAndAudioLicenseInfo violates convention

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#211]
Noted during code review #178.

By convention, we have been adding all PhET-specific globals to global.phet.  You can verify this convention by searching chipper/js/ for "global." This convention is violated by global.imageAndAudioLicenseInfo.  Please relocate to global.phet.imageAndAudioLicenseInfo.

**Comment by pixelzoom** [comment]
I'd also like to see this renamed to global.phet.mediaLicenseInfo

**Comment by samreid** [comment]
I moved imageAndAudioLicenseInfo to global.phet in the above commit.  Renaming it to *media will happen in #212.  @pixelzoom anything else here?

**Comment by pixelzoom** [comment]
:+1: Closing.
