### ISSUE TITLE
refer to "media" instead of "images and audio" throughout

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#212]
Noted during code review #178.

As noted in https://github.com/phetsims/chipper/issues/202#issuecomment-127715640, using variations of "images and audio" (in doc, vars, files, functions,...) is short-sighted. There's no reason why the same approach (and likely implementation) can't be applied to additional media types in the future.  Also, searching for "imagesAndAudio" (plural) and "imageAndAudio" (singular) reveals that the naming is inconsistent.  So I propose that we used the more generic "media" instead of "images and audio". 

Here is a (complete?) list of files and tokens that would need to be renamed (as of chipper c7059ccc9ea679c62aae7929d75d407a8ee92096):

```
createImageAndAudioLicenseReport.js -> createMediaLicenseReport.js
create-image-and-audio-license-report -> create-media-license-report
reportUnusedImagesAndAudio.js -> reportUnusedMedia.js
global.imageAndAudioLicenseInfo -> global.phet.mediaLicenseInfo
imagesAndAudio -> media
compositeImagesAndAudio -> compositeMedia
json.imagesAndAudio -> json.media
imageAndAudioLicensesUsed -> mediaLicensesUnused
imageAndAudioKey -> mediaKey
imageAudioEntryLines -> mediaEntryLines
images or audio -> media files
images & audio files -> media files
images/audio directories -> media directories
'Unused resource: ' -> 'Unused media file: '
```

Assignign to @samreid for discussion.

**Comment by pixelzoom** [comment]
Indeed, it looks like it would be easy to add additional media types in createImagesAndAudioLicenseReport.js by changing this:

```js
for ( var i = 0; i < reposByLine.length; i++ ) {
    reportForDirectory( reposByLine[ i ], 'images' );
    reportForDirectory( reposByLine[ i ], 'audio' );
  }
```

... by simply adding additional calls to `reportForDirectory`, like this:

```js
for ( var i = 0; i < reposByLine.length; i++ ) {
    reportForDirectory( reposByLine[ i ], 'images' );
    reportForDirectory( reposByLine[ i ], 'audio' );
    reportForDirectory( reposByLine[ i ], 'video' );
    reportForDirectory( reposByLine[ i ], 'futuristicAnimationFormat' );
}
```

**Comment by samreid** [comment]
> Just trying to be forward-looking here and not box us into this being for images and audio only.

Thanks, I was looking for a good term here, but didn't have a good feeling about "resource".  "media" sounds great.

**Comment by samreid** [comment]
I think I got all of the occurrences above, but would appreciate a double-check.

**Comment by samreid** [comment]
More fixes appear above.

**Comment by samreid** [comment]
I went through the above list and I think I got everything that was mentioned there.  I also tested grunt on hookes-law and grunt report-media and grunt report-third-party:build and didn't see any issues.

**Comment by pixelzoom** [comment]
Did a cursor skim of files in chipper/grunt/js, looks good, thanks for doing this. Closing.
