### ISSUE TITLE
add assertions for package.json dependencies in build-server.js

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#213]
build-server.js depends on the existence of simTitleStringKey in package.json, but contains no check for whether package.json or the required field exists.  If either is missing, this will fail:

```js
   // grab the title from sim/package.json
   var packageJSON = JSON.parse( fs.readFileSync( '../' + sim + '/package.json', { encoding: 'utf-8' } ) );
    var simTitleKey = packageJSON.simTitleStringKey;
    simTitleKey = simTitleKey.split( '/' )[ 1 ];
```

It would be preferrable to catch this with an assertion and a nice message, as is done elsewhere in chipper for package.json dependencies.  Eg, change the above to:

```js
// grab the title from sim/package.json
var PACKAGE_JSON = '../' + sim + '/package.json';
assert( fs.existsSync( PACKAGE_JSON ), 'missing ' + PACKAGE_JSON );
var packageJSON = JSON.parse( fs.readFileSync( PACKAGE_JSON, { encoding: 'utf-8' } ) );
assert( packageJSON.simTitleStringKey, 'simTitleStringKey missing from package.json' );
var simTitleKey = packageJSON.simTitleStringKey;
simTitleKey = simTitleKey.split( '/' )[ 1 ];
```

**Comment by pixelzoom** [comment]
Note that the format of simTitleStringKey may change, which would affect how this issue is addressed. See https://github.com/phetsims/chipper/issues/187#issuecomment-127735690.

**Comment by pixelzoom** [comment]
Assigning to @aaronsamuel137 since he has the majority of commits on build-server.js.

**Comment by aaronsamuel137** [comment]
One potential issue with using assert here is that we don't really want the whole build server to die if simTitleStringKey isn't found. That's why there is a try-catch here instead. If simTitleStringKey isn't found, then the build will proceed without writing the XML file.

What do you think @pixelzoom?

**Comment by pixelzoom** [comment]
Bailing on just the problematic sim would be fine.

**Comment by aaronsamuel137** [comment]
OK to close this then, or is there still something you have in mind here?

**Comment by pixelzoom** [comment]
It current just fails.  It would be better to test, print a warning, and bail for the problematic sim.

**Comment by aaronsamuel137** [comment]
I've improved the error handling in build server based on your suggestions. Assigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
:+1: Closing.
