### ISSUE TITLE
investigate grunt-available-tasks

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#216]
From #209 @pixelzoom said:

This is kind of nice: https://www.npmjs.com/package/grunt-available-tasks

Install the package:

`npm install grunt-available-tasks --save-dev`

Add this to grunt.initConfig to get color-coded output:

```js
availabletasks: {
  tasks: {},
},
```

Add this to grunt.initConfig if you'd like the output to be in markdown format:

```js
availabletasks: {
  tasks: {},
  options: {
    reporter: 'markdown'
  }
},
```

Run the task:

`grunt availabletasks`

**Comment by samreid** [comment]
Seems like worth investigation, though I'm wondering (a) if this can this be done without disturbing others that haven't installed grunt-available-tasks and (b) how often I would remember to do grunt availabletasks instead of grunt --help.

**Comment by samreid** [comment]
I'm not planning to work on this in the near future but I do want to hear other developers thoughts about this in Thursday's meeting.  I'll mark for developer meeting and unassign.

**Comment by zepumph** [comment]
Consensus 8/6 dev meeting. Not a high priority!!

**Comment by pixelzoom** [comment]
:+1: Closing.
