### ISSUE TITLE
Can global.phet.chipper.getBrandName be changed to global.phet.chipper.brandName?

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#217]
I don't see any reason why global.phet.chipper.getBrandName needs to be a function.  Would it be better as a property?

**Comment by pixelzoom** [comment]
I don't see any obvious reason why it's a function, but I didn't create it.  Probably best to look at git history and consult with however added it.

**Comment by samreid** [comment]
According to git history @samreid created it.  I asked and he said "I don't see any reason why global.phet.chipper.getBrandName needs to be a function."  I'll switch it to a var.

**Comment by pixelzoom** [comment]
:-)

**Comment by samreid** [comment]
I’m wondering if you would prefer global.phet.chipper.brandName or global.phet.chipper.brand.

Part of me is wondering if in the future brand would become a strategy pattern (an instance of type Brand), this would mean using brandName for the string.  Or if we think we will always use `brand` as a string, it may be preferable to `brandName`

**Comment by samreid** [comment]
I'm going to go with `brand` for now.  We can change it later if necessary.

**Comment by pixelzoom** [comment]
Either is fine with me.

**Comment by samreid** [comment]
`brand` has a nice symmetry with --brand and ?brand, which are both strings, I'll continue with it.

**Comment by samreid** [comment]
Tested a grunt with hookes-law and --brand=phet, everything seems ok.  I'll commit shortly.  Brace yourselves for commits across all of our sim repos.

**Comment by samreid** [comment]
I also tested hookes-law requirejs mode with query parameters and didn't see anything amiss.  Closing.

**Comment by pixelzoom** [comment]
Reopening.  

This is a breaking change and should be announced to the Google Group.  Eg, quantum-bound-states (Emily Randall's project) is now broken.

**Comment by samreid** [comment]
OK I'll write in on that thread.

**Comment by samreid** [comment]
Thanks, I posted on this thread: https://groups.google.com/forum/#!topic/developing-interactive-simulations-in-html5/QIuJJLeLqEk

Closing.
