### ISSUE TITLE
Consolidate third party licenses to one global in the HTML

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#219]
See https://github.com/phetsims/chipper/issues/175

It should look like so:

```js
window.phet.chipper.thirdPartyLicenses = {
lib: { ... },
images: { ... },
audio: { ... },
...
}
```

**Comment by samreid** [comment]
Marking a S2015R since we need a stable API for this going forwards.

**Comment by samreid** [comment]
Fixed above and it looks as described in the issue description.  @pixelzoom can you please review at your convenience?

**Comment by pixelzoom** [comment]
Looks like the global name is actually `window.phet.chipper.thirdPartyLicenseEntries`.  Was the name change intentional?

**Comment by pixelzoom** [comment]
I built gravity-and-orbits, ran it in Chrome, and inspected the global in the console. Looks good.

The global name is actually window.phet.chipper.thirdPartyLicenseEntries. Was the name change intentional?

**Comment by samreid** [comment]
Yes, I chose "licenseEntries" rather than "licenses" because there is more each entry than just the license.
