### ISSUE TITLE
Add a "deployment" flag

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#22]
Notable benefits would be hard errors instead of warnings for lack of changes.txt, screenshots, etc., so that we won't miss anything.

**Comment by pixelzoom** [comment]
What is a "deployment" flag?  Do you mean "this is a public version"?  Why do we need a flag, why isn't the version number sufficient? (i.e., it has no dev number).

**Comment by pixelzoom** [comment]
@jonathanolson please clarify.

**Comment by jonathanolson** [comment]
It would be beneficial to have two modes:
1) development build (for testing built versions, dev versions, etc.). Does NOT fail on missing screenshots (not made yet), or other items.
2) production build (meant for website). Fails on anything that we wouldn't want deployed.

**Comment by pixelzoom** [comment]
Since we have deploy-dev and deploy-production tasks implemented, this issue feels old/stale.  @jonathanolson is there anything that needs to be done, or any request that isn't satisfied elsewhere?

**Comment by jonathanolson** [comment]
Yup, closing.
