### ISSUE TITLE
print a warning for media files that are annotated with "exception" field

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#222]
An "exception" field was added to license.json, as described in https://github.com/phetsims/john-travoltage/issues/82#issuecomment-127682789.   One bit that was not implemented and requires discussion:

> Might still want to output a warning, so that we're aware of how many of these we have.

There is currently no warning. My feeling is that there should be a warning, so that we're aware of the exceptions.

**Comment by pixelzoom** [comment]
Consensus at 8/6/15 dev meeting: print warning.

**Comment by pixelzoom** [comment]
Should this warning be printed when the file is loaded by the media plugin? Or only by `grunt report-media`?

**Comment by samreid** [comment]
I recommend (a) during a build and (b) during `grunt report-media`.  Not when loaded in dynamic requirejs non-built mode (to match other conventions).

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/chipper/issues/227#issuecomment-129524984, we decided to put the warning message in isAcceptableLicenseEntry.js.   The problem with that is that it's called from media plugins, doesn't have access to the grunt instance, so can't do `grunt.log.warn` during a build.  I've temporarily put in `console.log` until we decide what to do here.

**Comment by pixelzoom** [comment]
I don't know how to proceed with this. Unassigning and labeling as "developer-meeting".

**Comment by pixelzoom** [comment]
Options:

1. Use console.log

2. Assign grunt instance to global.phet.chipper.grunt, use it for logging if it exists.

**Comment by samreid** [comment]
@jonathanolson said assigning grunt to a global seems good.

@jbphet said assigning grunt to a global sounds good.

**Comment by pixelzoom** [comment]
+1 for global.

**Comment by pixelzoom** [comment]
`global.phet.chipper.grunt` has been added.  Initialization of `global` has also been moved to the very top of Gruntfile.js.

I noticed several other uses of console.log in media plugins, will discuss whether those should use grunt.log in https://github.com/phetsims/chipper/issues/249.

Assigning to @samreid for verification.

**Comment by samreid** [comment]
Shouldn't we use grunt.fail.warn instead of grunt.log.warn?  According to the grunt docs http://gruntjs.com/api/grunt.log that is the way to get a "fail with error unless --force is specified" sort of behavior.

**Comment by samreid** [comment]
Oh sorry, media annotated with exception shouldn't fail the build.

**Comment by samreid** [comment]
Now that we have access to a grunt, we could use a grunt.fail.warn instead of this line:
```js
onload.error( new Error( 'unacceptable license entry for ' + name ) );
```

which would fail the build early with a great error message, but the disadvantage would be that it doesn't aggregate all errors (just reports the first one and fails unless --force).

**Comment by samreid** [comment]
@pixelzoom's changes look good.  The last item to discuss in this issue is my previous comment.  @pixelzoom can you take a look and let me know your recommendation? I'm fine with it either way.

**Comment by pixelzoom** [comment]
I have no strong preference for `onload.error` vs `grunt.fail.warn`.

**Comment by pixelzoom** [comment]
The only thing I will note is that using `onload.error( Error )` provides nice symmetry with `onload(null)`.

**Comment by samreid** [comment]
Sounds good, let's leave it as-is.  Closing.
