### ISSUE TITLE
convert getLicenseInfo to getLicenseEntry

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#224]
The current pattern for getLicenseInfo is that it returns an object with the following fields:

```
{classification: <string>, isProblematic: <boolean>, entry: <object> }
```

And the entry has 
```
 * text - copyright statement or "Public Domain"
 * projectURL - the URL for the resource
 * license - the name of license, such as "Public Domain"
 * notes - additional helpful information about the resource, or ""
 * exception - [optional] description of why the file is being used despite the fact that it doesn't match PhET's licensing policy
```

Having separate data types for this is growing confusing.  We should just have the entries, and at the point where the `classification` or `isProblematic` are needed, they should be returned from a function call.

**Comment by samreid** [comment]
Calling getClassification() or isProblematic() twice won't be too performance-demanding, but if it is, we can cache the values privately.

**Comment by samreid** [comment]
On the other hand, having getLicenseInfo does centralize this logic nicely...

**Comment by samreid** [comment]
Another con if we make this change: it will be more difficult to know whether the license.json file is missing or if the file is present and the entry is missing.

**Comment by samreid** [comment]
Ah yes, I'm remembering another reason I did it this way (the getLicenseInfo way)--this code has to run at build time and requirejs time, and requires exports and define declarations.

**Comment by samreid** [comment]
Completed above and things are much simpler now.  Reassigning to @pixelzoom for review & discussion.

**Comment by pixelzoom** [comment]
I updated some doc and variable names.  The one significant issue I see is noted in #237 (getLicenseEntry returns null for 2 different cases).

In Skype, we discussed renaming this to getMediaLicenseEntry, since it's currently only applicable to media licenses.  But @samreid said:
> I’m just wondering if we would ever use that for code—keeping license info for code in sync with license info for media files seems like it has been working well and we should continue with it

**Comment by samreid** [comment]
@pixelzoom would it be OK to leave it as is?  Named as getLicenseEntry and able to load a license entry for any file (code/image/audio/etc), though currently only used for media.

**Comment by pixelzoom** [comment]
Fine with me. Anything else here?

**Comment by samreid** [comment]
Not that I am aware of. Closing.
