### ISSUE TITLE
Warning: missing preferences file undefined/.phet/build-local.json Use --force to continue.

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#225]
@phetsims/ashrafsharf reported the following error

```
Warning: missing preferences file undefined/.phet/build-local.json Use --force to continue.
```

**Comment by samreid** [comment]
Workaround is to set HOME and make sure you have the file HOME/.phet/build-local.json

**Comment by samreid** [comment]
I was able to reproduce the problem after doing `unset HOME` in bash.

**Comment by samreid** [comment]
I'm seeing 2 problems here:

1. The preferences file as well as having a HOME is mandatory?
2. `var PREFERENCES_FILE = process.env.HOME + '/.phet/build-local.json';` is duplicated in several files

**Comment by samreid** [comment]
--force doesn't work around the problem at hand

**Comment by AshrafSharf** [comment]
Ok. Setting the HOME env variable and having a empty ({}) build-local.json fixed this problem.

**Comment by samreid** [comment]
Thanks @AshrafSharf. I also pushed a change above so that neither a HOME directory or build-local.json is required for builds (not sure if other developers or build servers have those).

Reassigned to @pixelzoom. I recommend to:
(a) evaluate at the changes above
(b) factor out an abstraction for BuildLocalPreferences instead of duplicating these four lines in several files:

```js
  // read the preferences file
  var PREFERENCES_FILE = process.env.HOME + '/.phet/build-local.json';
  assert( fs.existsSync( PREFERENCES_FILE ), 'missing preferences file ' + PREFERENCES_FILE );
  var preferences = grunt.file.readJSON( PREFERENCES_FILE );
```
(c) the abstraction should not require a HOME or a build-local.json, similarly to my fix above.

**Comment by AshrafSharf** [comment]
@samreid Running "after-requirejs-build" task now results in 
Fatal error: Cannot read property 'projectURL' of null

**Comment by samreid** [comment]
@AshrafSharf that is a separate issue, I'll see you over in #226

**Comment by pixelzoom** [comment]
Thanks for taking care of this. I copied the build-local.json from deployDev.js, but didn't consider the fact that deployDev requires the file (for authentication) but brand specification should be optional.

**Comment by samreid** [comment]
I made 3 recommendations in https://github.com/phetsims/chipper/issues/225#issuecomment-128695450 that still need to be completed.  @pixelzoom If you would like I can put them on my TODO list.

**Comment by pixelzoom** [comment]
Recommendations sound good, broken out into https://github.com/phetsims/chipper/issues/232.  Currently assigned to me.

@samreid Anything else to do here?

**Comment by samreid** [comment]
#232 seems like a good place to continue.  Nothing else to see here, move along.
