### ISSUE TITLE
Running "after-requirejs-build" task now results in  Fatal error: Cannot read property 'projectURL' of null

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#226]
@phetsims/ashrafsharf reported

> Running "after-requirejs-build" task now results in 
> Fatal error: Cannot read property 'projectURL' of null

**Comment by samreid** [comment]
Since I do not see the problem, I presume you have changes in your working copy?

The issue seems to be related to the new requirement that each image/audio must have an entry in the associated license.json file.  Have you added any new image/audio files that don't have an entry in the license.json?  I'll look into making a better error message.

**Comment by samreid** [comment]
By removing a license.json entry for a used image, I was able to reproduce the error.

**Comment by samreid** [comment]
Above, I am only checking the license entries when using the phet or phet-io brands, and improved the error message.  I tested `grunt --brand=phet` and `grunt` with and without missing license.json entries and all seems well.  @phetsims/ashrafsharf can you test?

**Comment by AshrafSharf** [comment]
There are 27 images in the project and the licence.json now has all the entries for them. I am still getting this error. The project uses a audio file indirectly through GameAudioPlayer  component from Vibe( but  no direct audio file is imported in MakingTens itself)

**Comment by samreid** [comment]
Can you help me reproduce the problem?  Make sure you don't have any uncommitted files and let me know exactly what grunt command you are using?  And this is for making-tens, right?

**Comment by AshrafSharf** [comment]
@samreid - Took the latest chipper again, the grunt command finished without any errors. Thanks.

**Comment by samreid** [comment]
Hooray!  Thanks for checking, I'll close the issue.
