### ISSUE TITLE
Does LicenseEntryClassifier.js need a requirejs implementation?

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#227]
From #221

**Comment by samreid** [comment]
Fixed above, @pixelzoom can you make sure this makes sense?

**Comment by samreid** [comment]
It does need it for builds with brand==phet, as @jbphet discovered.  Fixed above.

**Comment by pixelzoom** [comment]
Questions:

1. Why does the name of this looks like a type? 
2. isAcceptable is not used outside of LicenseEntryClassifier. Does it need to be part of the public API?
3. The API is a pair of functions that return the inverse boolean of each other. Why can't this just a `isLicenseOK` function that returns true or false? Seems too complicated.
4. Does this apply only to media licenses? If so, the name and doc should indicate that.

**Comment by pixelzoom** [comment]
The current implementation of LicenseEntryClassifier also makes it difficult to print a warning for media files that have an "exception" annotation without having to check the "exception" field again. Eg, here's what we'd have to do in audio.js:

```js
if ( (phet.chipper.brand === 'phet' || phet.chipper.brand === 'phet-io') && LicenseEntryClassifier.isProblematic( licenseEntry ) ) {
  errorString += 'Error for ' + urlList[ i ].url;
}
else {
  global.phet.chipper.licenseEntries.audio = global.phet.chipper.licenseEntries.audio || {};
  global.phet.chipper.licenseEntries.audio[ name ] = licenseEntry;
  if ( licenseEntry.exception ) {
   // print warning message here
  }
}
```

**Comment by pixelzoom** [comment]
Other possible names for this... isCompatibleLicense, isValidLicense

**Comment by samreid** [comment]
> Why does the name of this looks like a type?

I thought it would have more public "static" style methods.  I think we can change it to a function now.

> isAcceptable is not used outside of LicenseEntryClassifier. Does it need to be part of the public API?

I don't think so.

> The API is a pair of functions that return the inverse boolean of each other. Why can't this just a isLicenseOK function that returns true or false? Seems too complicated.

Let's just use `isLicenseEntryAcceptable`

> Does this apply only to media licenses? If so, the name and doc should indicate that.

Currently only used by media, but I recommend to leave it general for unification of code/media in the future.

> The current implementation of LicenseEntryClassifier also makes it difficult to print a warning (see #222) for media files that have an "exception" annotation without having to check the "exception" field again. 

What is the difficulty of having to check the exception field again?  I didn't understand the problem.

**Comment by samreid** [comment]
> Let's just use `isLicenseEntryAcceptable`

To clarify, let's rename the file to isLicenseEntryAcceptable.js as well.

**Comment by pixelzoom** [comment]
> What is the difficulty of having to check the exception field again? I didn't understand the problem.

It seems like the thing deciding whether the license is acceptable should also be responsible for issuing the warning.  Ie, isLicenseEntryAcceptable should note "the license isn't really compatible, but there's an exception annotation, so we'll let it slide. but we will note that with a warning message".  Instead, you're requiring every client who calls isLicenseEntryAcceptable to also decide whether to test for "exception" and issue a warning message (probably resulting in duplicate code, inconsistent warning messages,...).

So what do you think about putting the warning inside isLicenseEntryAcceptable?

**Comment by samreid** [comment]
Inside isLicenseEntryAcceptable seems like a good place to put this warning.  Please proceed or reassign to me if I should take care of it.

**Comment by pixelzoom** [comment]
Do you want me to rename and reimplement LicenseEntryClassifier.js too?

**Comment by samreid** [comment]
No preference who does this, feel free to proceed or let me know if I should.

**Comment by pixelzoom** [comment]
I'll take it on.

**Comment by samreid** [comment]
Thanks, good luck!

**Comment by pixelzoom** [comment]
Original work of this issue was completed.  Moved additional refactoring to #240.  Closing.
