### ISSUE TITLE
Convert build-no-lint to build --lint=false

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#231]
It seems like things would be a bit simpler if --lint=false was moved to an option (instead of a task).  @pixelzoom @jbphet @jonathanolson @aaronsamuel137 @jessegreenberg is that OK with you?  If there is no quick consensus here, we can mark for developer-meeting.

**Comment by aaronsamuel137** [comment]
I'm fine with ```build --lint-false```. If we make this change, it will need to be changed in build-server too, since it currently uses ```grunt build-no-lint```

**Comment by pixelzoom** [comment]
Sounds like a nice change.

**Comment by samreid** [comment]
That is enough upvotes for me, let's go for it.  I'll assign it to @samreid to get it done, then over to @aaronsamuel137 to update and test the build server afterwards.

**Comment by samreid** [comment]
Fixed above.  Here's a log of my test which looks correct:

```
Sams-MacBook-Air:hookes-law samreid$ grunt
Running "jshint:allFiles" (jshint) task
^CSams-MacBook-Air:hookes-law samreid$ grunt --lint=true
Running "jshint:allFiles" (jshint) task
^CSams-MacBook-Air:hookes-law samreid$ grunt --lint=false
Running "clean" task
```

**Comment by samreid** [comment]
@aaronsamuel137 it looks like the change in build-server.js will be straightforward but I didn't know how to deploy the changes, whether I need to stop a process, or anything like that, so can you take care of it and let me know what you had to do, so I could do it next time if necessary?

**Comment by aaronsamuel137** [comment]
I've updated the call to grunt build-no-lint in build-server and restarted the server. I can go over how to restart the server with you at dev meeting sometime or on a call. It's not difficult, but you'll need to be sure you have the correct info in your build-local.json on figaro if it is going to be running under your username.

**Comment by samreid** [comment]
I think as long as n>=2 people on our team know how to do it, it is ok.  @pixelzoom do you want to review the implementation of --lint=false?

**Comment by pixelzoom** [comment]
`--lint` option is not described in the help for the `build` task.

**Comment by samreid** [comment]
Added above, anything else?

**Comment by pixelzoom** [comment]
Doc tweaked, "linting sub-task" to "lint sub-task", because there is no "linting" subtask.

Closing.
