### ISSUE TITLE
create an abstraction for build options

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#232]
... as recommended in https://github.com/phetsims/chipper/issues/225#issuecomment-128695450.

**Comment by pixelzoom** [comment]
The earliest I can get to this is Monday 8/10.

**Comment by pixelzoom** [comment]
Perhaps we should also have a BuildOptions abstraction, which handles reading both build-local.json and grunt.option.  This would handle default values, and would ensure that precedence is handled correctly, and in one place.  

Eg in beforeRequirejsBuild.js, this:

`global.phet.chipper.brand = grunt.option( 'brand' ) || preferences.brand || 'adapted-from-phet';`

would become:

`global.phet.chipper.brand = buildOptions.brand;`

**Comment by samreid** [comment]
Yes, that seems reasonable.

**Comment by pixelzoom** [comment]
Should we have both BuildLocal and BuildOptions (which uses BuildLocal), or handle it all in BuildOptions?

**Comment by pixelzoom** [comment]
Should we have both BuildLocal and BuildOptions (which uses BuildLocal), or handle it all in BuildOptions?  I'm leaning towards BuildOptions only, unless we need to check BuildLocal independently.

**Comment by pixelzoom** [comment]
Recommendations on how to structure this so that it's usable by the build process, build-server, etc?

**Comment by samreid** [comment]
I suspect a node module (module.exports=...) would do the trick.

**Comment by samreid** [comment]
I believe @aaronsamuel137 said the build server also uses build-local.json.

**Comment by pixelzoom** [comment]
> I believe @aaronsamuel137 said the build server also uses build-local.json.

Indeed it does, that's why I asked (in https://github.com/phetsims/chipper/issues/232#issuecomment-129599709) about how to structure this so that it works with the build process and build-server.

**Comment by samreid** [comment]
I suspect (but am not sure) that you are looking for a more specific answer than "use a node module".  If so, please ask a more specific question.

**Comment by aaronsamuel137** [comment]
Rosetta also uses build-local.json. I am available to collaborate on this if needed.

**Comment by pixelzoom** [comment]
Should BuildOptions also encapsulate package.json? I'm thinking yes.

So here's the (complete?) list of what BuildOptions would be responsible for reading, then providing an appropriate abstraction:

grunt.option
$HOME/.phet/build-local.json
chipper/build-local.json
package.json

Btw... Instead of hardcoding "adapted-from-phet" as the default brand, I think it would preferable to move it to chipper/build.json.

**Comment by pixelzoom** [comment]
Build options would be read in this order:

chipper/build-local.json
RESPOSITORY/package.json
$HOME/.phet/build-local.json
grunt.option

**Comment by pixelzoom** [comment]
BuildOptions should live in chipper/js/common/.

**Comment by pixelzoom** [comment]
Checking in first pass, discussed with @samreid, he suggested a function for each entry that requires some computation, to encapsulate and make dependencies clear via function parameters.

**Comment by pixelzoom** [comment]
Second pass at buildConfig, integrating @samreid's feedback.  @samreid can we discuss again after you've looked it over?  If you'd like to test, add this to Gruntfile.js:

```js
37 var initBuildConfig = require( '../../../chipper/js/grunt/initBuildConfig' );
50 var buildConfig = initBuildConfig( grunt );
```

Then run `grunt --debug --lint=false`, and the buildConfig will be printed out.

**Comment by samreid** [comment]
Sure, I'll take a look, hopefully before tomorrow evening.  Can I assign to me?

**Comment by pixelzoom** [comment]
Yep.

**Comment by pixelzoom** [comment]
I renamed initBuildConfig to getBuildConfig, since it is now returning a value instead of setting a global. Modified test code in Gruntfile.js is:

```js
37 var getBuildConfig = require( '../../../chipper/js/grunt/getBuildConfig' );
50 var buildConfig = getBuildConfig( grunt );
```

**Comment by pixelzoom** [comment]
@samreid I know that one of your concerns was that there is a lot of stuff in getBuildConfig.js. That's because (a) we have a lot of build options, and (b) they are currently spread out like this:
 
* Gruntfile.js : read package.json, compute `brand`, compute `phetLibs`, create jshint config, create grunt config
* setPreload.js: compute `preload`
* beforeRequire.js : call setPreload.js, compute `locales`
* getThirdPartyLibEntries: compute `licenseKeys`

... where each of these source files has to potentially deal with package.json, build.json, build-local.json and grunt.option, as well as how to properly determine which of these takes precedence.  And there are also order dependencies that are not obvious when the code is spread out.

**Comment by samreid** [comment]
Overall this is looking much better, and I made one minor change above.

One of the code review items from https://github.com/phetsims/phet-info/blob/master/code_review_checklist.md states:

> Is there any unnecessary coupling? (e.g., by passing large objects to constructors, or exposing unnecessary properties/functions)

are you intending to pass the entire buildConfig to every build function that needs any part of it, or just pass in the relevant bits?

**Comment by pixelzoom** [comment]
> are you intending to pass the entire buildConfig to every build function that needs any part of it, or just pass in the relevant bits?

I'm planning to address this in 2 phases. 

First phase: Make minimal changes to the existing code base by substituting either `buildConfig` or `buildConfig.someField` for existing things like `pkg` and `pkg.name`.  Most source files currently an interface that looks like `module.exports = function( grunt, pkg, ...)`, so they'll initially get passed the entire buildConfig.  Once that is all working...

Second phase: Revisit all APIs and reduce coupling where possible. And I suspect there are a lot of places where decoupling is possible.

**Comment by samreid** [comment]
Sounds great.  I'm not planning further review at the moment, but can take another look after 1st or 2nd phase as described above.

**Comment by pixelzoom** [comment]
@samreid Thanks for the feedback and review!

**Comment by pixelzoom** [comment]
I've integrated buildConfig into chipper/js/grunt/ code.  The media plugins are still relying on `global.phet.chipper.brand`, which is set in Gruntfile.js using buildConfig.brand.  Trying to get buildConfig into the plugins is similar to trying to get the grunt instance into the plugins, so maybe using a global is OK.

**Comment by pixelzoom** [comment]
We're down to this set of globals:

```js
global.phet.chipper.brand
global.phet.chipper.getCacheBusterArgs
global.phet.chipper.grunt
global.fs
global.phet.licenseEntries
global.phet.mipmapsToBuild
global.phet.strings
```

Everything else is passed around in buildConfig.

**Comment by pixelzoom** [comment]
> Trying to get buildConfig into the plugins is similar to trying to get the grunt instance into the plugins, so maybe using a global is OK.

No objections at dev meeting.

**Comment by pixelzoom** [comment]
All build and plugin code is now using information supplied by getBuildConfig.js.

build-server.js is still reading package.json and build-local.json directly. And perhaps it should continue to do so. It doesn't have access to grunt, which is required by getBuildConfig.js. And in the case of build-local.json, it has its own set of fields that it's interested in that are not related to the build process, and therefore not part of buildConfig.  @aaronsamuel137 what is you opinion?

**Comment by pixelzoom** [comment]
deployDev and deploySimulation are also reading build-local.json directly, for these fields:

devUsername
devDeployServer
devDeployPath
buildServerAuthorizationCode
productionServerName
productionServerURL

Options, from most to least work:

(1) Create a new abstraction, e.g. getDeployCong.js
(2) Add these field to getBuildConfig.js
(3) Leave as is

@aaronsamuel137 you opinion?

**Comment by aaronsamuel137** [comment]
I would agree that (1) is the best option, with (3) being my second choice. Feel free to assign to me if you'd like me to take care of this.

**Comment by pixelzoom** [comment]
Let's do (3), create getDeployConfig.js.  Broken out into https://github.com/phetsims/chipper/issues/309.

**Comment by pixelzoom** [comment]
All work is done here. 

Build configuration is encapsulated in getBuildConfig.js.
Grunt configuration is encapsulated in getGruntConfig.js.
Deploy configuration will be implemented in getDeployConfig.js (see #309).

@samreid Since you reviewed previous passes, would you mind taking a quick look?

**Comment by samreid** [comment]
I looked through the above 5 change sets, and the implementation & usage of getBuildConfig and getGruntConfig and all looks good.  I just committed one change for phet style (not sure if related to this issue) and added a missing `@param` annotation.  Closing.
