### ISSUE TITLE
Consolidate thumbnail tasks

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#233]
In #209 I noticed that we have 3 thumbnail tasks:

```
 generate-128-thumbnail  Generate 128x84 thumbnail                             
 generate-600-thumbnail  Generate 600x394 thumbnail
    generate-thumbnails  Generate thumbnails
```

Do we really need all 3 tasks?  Can we simplify things by just generating all of the thumbnails in one task?  Also, based on #209 can we rename the task from generate-thumbnails to simply `thumbnails`?  Or is this problematic because it creates a schism between the task name and the JS filename?

**Comment by aaronsamuel137** [comment]
I've consolidated this into one grunt task that generates both thumbnails. Assigning to @samreid for review.

**Comment by samreid** [comment]
I reviewed it but didn't run it.  Looks good.
