### ISSUE TITLE
add authorization to build server

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/chipper#234]
build-server.js needs some way of authorizing legitimate requests from phet. I discussed with @jonathanolson creating password in build-local.json and sending it vis HTTPS.

**Comment by aaronsamuel137** [comment]
This has been implemented and deployed. Assigning to @jonathanolson to review during his review of build-server.

**Comment by jonathanolson** [comment]
This was reviewed as part of https://github.com/phetsims/chipper/issues/141. Closing.
