### ISSUE TITLE
Missing or empty entries lead to blank lines in the report

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#236]
https://github.com/phetsims/sherpa/issues/57#issuecomment-129497776

@pixelzoom said:

> Looks generally awesome, nice job!

> I do have one suggestion about formatting, not sure if it belongs in this issue.  I see some entries that look like this:

```
BUILD_A_MOLECULE/green-left.png


License: Unknown
Notes:
```

> This would be easier to read without the blank lines, especially when there are contiguous entries like this.

**Comment by samreid** [comment]
When text or project url is null, it will be replaced with text like "no text" or  "no project url".  I'll commit shortly.

**Comment by samreid** [comment]
Fixed above, reassigning to @pixelzoom since he originally reported the issue.

**Comment by pixelzoom** [comment]
If you're going to default `text` to "(no text)" and `projectURL` to "(no project URL)",  then perhaps `notes` should be defaulted to "(no notes)".  They are all required fields, so they should be handled consistently.

**Comment by samreid** [comment]
Fixed above, see commit message.
