### ISSUE TITLE
getLicenseEntry returns null for 2 different cases

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#237]
getLicenseEntry return null if the license.json file isn't found, or if the media file doesn't have an entry in the file (see below).  Since `grunt report-media` has a `missing-license.json` problem type, I'm guessing that we need to differentiate between those 2 cases.  How is that done?

```js
    var file = null;
    // look in the license.json file to see if there is an entry for that file
    try {
      file = global.fs.readFileSync( licenseFilename, 'utf8' );
    }
    catch( err ) {
      // File not found
      return null;
    }
    var json = JSON.parse( file );

    var entry = json[ mediaFilename ];
    if ( !entry ) {
      // Not annotated in file
      return null;
    }
    return entry;
```

**Comment by samreid** [comment]
In getting rid of the license info type in #224 we have also removed the ability to distinguish between missing license.json and "license.json exists but the entry is missing".  I considered adding separate return values to distinguish between those issues (such as string literals) but decided the complexity of returning a variety of different types from getLicenseEntry wasn't worth it.   OK with you if I just change the docs to unify these two problems?

**Comment by pixelzoom** [comment]
Yes, please change docs in Gruntfile.js and reportMedia.js.  The return value in getLicenseEntry should also describe the cases where it returns null.

**Comment by samreid** [comment]
Fixed above, please review.

**Comment by pixelzoom** [comment]
Doc added another reference to "asset" that should be "media", I changed it. Feel free to review. 

Closing.
