### ISSUE TITLE
improve error messages for unacceptable license entries

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#239]
Testing recent changes to media licensing, I noticed that the error message for "unacceptable" licensing are not very friendly.

For example... I changed `projectURL` for the first entry in beers-law-lab/images/license.json to something incompatible with PhET, like this:

```js
"at-detector-probe.png": {
    "text": [
      "Copyright 2002-2015 University of Colorado Boulder"
    ],
    "projectURL": "BOGUS",
    "license": "contact phethelp@colorado.edu",
    "notes": "copied intensity_meter_probe.png from bending-light"
  },
```

Here's the messy/verbose error message that I get at build time:

```
% cd beers-law-lab
% grunt --brand=phet`
...
Running "requirejs:build" (requirejs) task
>> Error: Error: Loader plugin did not call the load callback in the build:
>> image:
>>   image!BEERS_LAW_LAB/at-detector-probe.png: Error: problematic license entry
>> Module loading did not complete for: beers-law-lab-main, BEERS_LAW_LAB/beerslaw/BeersLawScreen, BEERS_LAW_LAB/beerslaw/view/BeersLawView, BEERS_LAW_LAB/beerslaw/view/ATDetectorNode
>>     at Function.build.checkForErrors (/Users/cmalley/PhET/GitHub/beers-law-lab/node_modules/requirejs/bin/r.js:28424:19)
Warning: Task "requirejs:build" failed. Use --force to continue.

Aborted due to warnings.
%
```

The bit that's important is buried in there:

```
image!BEERS_LAW_LAB/at-detector-probe.png: Error: problematic license entry
```

The message should probably say "unacceptable license entry", since that's the terminology used in the source code, and since one has to resort to reading the source code to determine why it was unacceptable.

**Comment by pixelzoom** [comment]
Note that this problem existed before I start refactoring https://github.com/phetsims/chipper/issues/227.

**Comment by pixelzoom** [comment]
Not sure what to do about this. Unassigning and labeling as "developer-meeting".

**Comment by samreid** [comment]
I presumed (but wasn't sure) that this is the usual sort of error printout when an error occurred during r.js build.

**Comment by samreid** [comment]
@pixelzoom have you tried passing a string to onload.error()?

**Comment by samreid** [comment]
Well, the docs do say you must pass in an Error instance.

**Comment by pixelzoom** [comment]
onload is a requirejs function. For doc on onload.error, search http://requirejs.org/docs/plugins.html. Doesn't looks like there's any way to control what parts of the error are used by onload.error (probably does a toString).  

Consensus: OK as is.
