### ISSUE TITLE
Include dependencies.json info in single-file HTML

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#24]

**Comment by pixelzoom** [comment]
Are you suggesting that dependency.json should be embedded in the deliverable HTML file?

**Comment by samreid** [comment]
I think that is what @jonathanolson was suggesting--that way the dependencies.json cannot get "lost" or separated from the html file it describes.  We may also want to write a tool that can read the dependencies.json file out of an HTML file.

**Comment by pixelzoom** [comment]
Duplicate of #135, closing.
