### ISSUE TITLE
plugins don't identify the problem media file

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#242]
If an image file has an unacceptable license entry, image.js and mipmap.js don't identify the file in the error message. All we get is "unacceptable license entry".  For example, here's an example where I inserted an unacceptable entry into acid-base-solutions/images/license.json.  You have to look at ToolsControl to see what images it's loading, and if it's loading >1, you'll have to examine all of their license entries until you find the problem.

```
% grunt
...
Running "requirejs:build" (requirejs) task
>> Error: Error: unacceptable license entry
>> In module tree:
>>     acid-base-solutions-main
>>       ACID_BASE_SOLUTIONS/mysolution/MySolutionScreen
>>         ACID_BASE_SOLUTIONS/mysolution/view/MySolutionView
>>           common/view/AcidBaseSolutionsView
>>             ACID_BASE_SOLUTIONS/common/view/AcidBaseSolutionsControlPanel
>>               ACID_BASE_SOLUTIONS/common/view/ToolsControl
>>                 image
>> 
>>     at Object.load (eval at <anonymous> (/Users/cmalley/PhET/GitHub/acid-base-solutions/node_modules/requirejs/bin/r.js:25344:38), <anonymous>:37:25)
Warning: Task "requirejs:build" failed. Use --force to continue.

Aborted due to warnings
%
```

**Comment by samreid** [comment]
We could add the plugin name (includes repo name and relative path) to the error message.  Do you think this would be sufficient?

**Comment by pixelzoom** [comment]
https://github.com/phetsims/chipper/issues/239 covers improving the overall error messages. Identifying the media file in the error message would be a good first step. audio.js already seems to do that:

`errorString += 'unacceptable license entry for ' + urlList[ i ].url;`

... though I'm not clear on what urlList is, or why there's errorString is a concatenation of licenseEntries, instead of having 1 error per audio file (which is discussed in https://github.com/phetsims/chipper/issues/229).

**Comment by pixelzoom** [comment]
Might as well clean up audio.js too.  If there errorString is indeed needs to be a concatenation for some reason, there is currently no separator between error messages.  So you'll get (for example):

`unaccepable license entry for someURLunaccepable license entry for someURL`

**Comment by pixelzoom** [comment]
I took a stab at this. Not crazy about `'..'` in the paths (e.g. `/Users/cmalley/PhET/GitHub/scenery-phet/js/../images/faucet_track.png`), but it's better than having no idea which file caused the error.

**Comment by pixelzoom** [comment]
Sample error message for the same case as https://github.com/phetsims/chipper/issues/242#issue-100167786:

```
% grunt
...
Running "requirejs:build" (requirejs) task
>> Error: Error: unacceptable license entry for /Users/cmalley/PhET/GitHub/acid-base-solutions/js/../images/light-bulb-icon.png
>> In module tree:
>>     acid-base-solutions-main
>>       ACID_BASE_SOLUTIONS/mysolution/MySolutionScreen
>>         ACID_BASE_SOLUTIONS/mysolution/view/MySolutionView
>>           common/view/AcidBaseSolutionsView
>>             ACID_BASE_SOLUTIONS/common/view/AcidBaseSolutionsControlPanel
>>               ACID_BASE_SOLUTIONS/common/view/ToolsControl
>>                 image
>> 
>>     at Object.load (eval at <anonymous> (/Users/cmalley/PhET/GitHub/acid-base-solutions/node_modules/requirejs/bin/r.js:25344:38), <anonymous>:37:25)
Warning: Task "requirejs:build" failed. Use --force to continue.

Aborted due to warnings.
%
```

**Comment by samreid** [comment]
This has been factored out in checkAndRegisterLicenseEntry.js.  Also, in #229 I made it so that for audio, only the 1st error is reported (as commented).  In my opinion, this is sufficient to identify the issue to a developer.  @pixelzoom anything else to do here?

**Comment by pixelzoom** [comment]
Nothing else to do, closing.
