### ISSUE TITLE
expand doc for build-server

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#243]
The current overview of build-server.js is:

```js
/**
 * PhET build and deploy server
 *
 * @author Aaron Davis
 */
```

Recommend expanding this documentation, including:

• What does it build and deploy?
• How is it intended to be run?
• How is it started and stopped?
• (anything else we need to know?)

**Comment by aaronsamuel137** [comment]
Added documentation, assigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
Awesome. Closing.
