### ISSUE TITLE
global.phet.chipper.brand vs phet.chipper.brand?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#244]
In grunt/js/, I see `global.phet.chipper.brand` and `phet.chipper.brand` used interchangeably.  For example, beforeRequirejsBuild.js and afterRequirejsBuild.js use both.  Media plugins use  `phet.chipper.brand`, but use `global.phet.chipper` for other globals.

Should we use `global.phet.chipper.brand` throughout for consistency?

**Comment by pixelzoom** [comment]
string.js also uses `window.phet.chipper.getQueryParameter` and `phet.chipper.getQueryParameter` interchangeably.

**Comment by pixelzoom** [comment]
Note that `global.phet` and `window.phet` are 2 different global namespaces.

**Comment by samreid** [comment]
window.phet.chipper.brand is necessary in initialize-globals.js since it is the code that runs in the simulation.  Other cases are replaced with global.* in the following commit.

**Comment by samreid** [comment]
Fixed as described above, @pixelzoom can you review?

**Comment by pixelzoom** [comment]
:+1: Closing.
