### ISSUE TITLE
suspicious output from "grunt lint-all"

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#246]
This looks wrong. For chipper, `grunt lint` hits 31 files, while `grunt lint-all` only hits 3.

```js
% cd chipper
% grunt lint
Running "jshint:repoFiles" (jshint) task
>> 31 files lint free.

Done, without errors.
% grunt lint-all
Running "jshint:allFiles" (jshint) task
>> 3 files lint free.

Done, without errors.
%
```

Is the "all files" list forgetting to include the repo's files, and including only dependencies?  Is this happening for other repos?

Not sure if this is related to recent lint changes in https://github.com/phetsims/brand/issues/24 or https://github.com/phetsims/chipper/issues/231, but assigning to @samreid since he was recently making changes.

**Comment by pixelzoom** [comment]
The files to lint are configured in the main Gruntfile.js, variables `repoFilesToLint` (for `lint` task) a d and `allFilesToLint` (for `lint-all` task).  Printing those variables to the console:

```
allFilesToLint=../brand/*/js/**/*.js,!../kite/js/parser/svgPath.js
repoFilesToLint=js/**/*.js
```

So allFilesToLint is indeed missing the repo files.

**Comment by pixelzoom** [comment]
For `grunt lint` in hooks-law, things look OK, `../hookes-law/js/**/*.js` is included in allFilesToLint.

```
allFilesToLint=../assert/js/**/*.js,../axon/js/**/*.js,../babel/js/**/*.js,../brand/js/**/*.js,../chipper/js/**/*.js,../dot/js/**/*.js,../hookes-law/js/**/*.js,../joist/js/**/*.js,../kite/js/**/*.js,../phet-core/js/**/*.js,../phetcommon/js/**/*.js,../scenery/js/**/*.js,../scenery-phet/js/**/*.js,../sherpa/js/**/*.js,../sun/js/**/*.js,../brand/*/js/**/*.js,!../kite/js/parser/svgPath.js
repoFilesToLint=js/**/*.js
```

**Comment by pixelzoom** [comment]
This problem has been around for a long time, introduced in d08fbdc.  Here's how pkg.phetLibs is set in Gruntfile.js:

```js
 if ( pkg.phetLibs ) {
    assert( fs.existsSync( '../chipper/build.json' ), 'missing build.json' );
    var buildInfo = grunt.file.readJSON( '../chipper/build.json' );
    pkg.phetLibs = _.uniq( pkg.phetLibs.concat( buildInfo.common.phetLibs ).sort() );
    grunt.log.debug( 'phetLibs = ' + pkg.phetLibs );
  }
```

So if the repo doesn't define `phetLibs` (which is optional) in its own package.json, then it won't get the `phetLibs` that are defined in chipper/build-local.json and are supposed to be included for all sims.

**Comment by pixelzoom** [comment]
Fixed. Here's the lint output for chipper:

```
% cd chipper
% grunt lint
Running "jshint:repoFiles" (jshint) task
>> 31 files lint free.

Done, without errors.
% grunt lint-all
Running "jshint:allFiles" (jshint) task
>> 376 files lint free.

Done, without errors.
%
```

**Comment by pixelzoom** [comment]
Assigning to @samreid to verify, since he's the other developer who's been most recently working with lint.

**Comment by samreid** [comment]
The changes above look good and I confirmed the lint vs lint-all behavior at the command line and all seems good.

The changes above define pkg.phetLibs to be at least [] if it wasn't already defined.  Hence I think we should get rid of all the subsequent
```
assert( pkg.phetLibs, 'phetLibs missing from package.json' );
```

I'll remove them and commit shortly.

**Comment by samreid** [comment]
Committed above, @pixelzoom please comment and close if everything is good.

**Comment by pixelzoom** [comment]
:+1: Closing.
