### ISSUE TITLE
Several simulations are missing titles

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#247]
I am seeing these simulations without a `<title>` attribute in the html

> title not found for /Users/samreid/temp/blast_en.html
title not found for /Users/samreid/temp/litmus_en.html
title not found for /Users/samreid/temp/mikes-playground_en.html
title not found for /Users/samreid/temp/ph-scale-basics_en.html
title not found for /Users/samreid/temp/states-of-matter-basics_en.html

We should add them in and republish the report, see #220

**Comment by pixelzoom** [comment]
Assigning to myself to take a look at ph-scale-basics. Thought I fixed that yesterday.

**Comment by pixelzoom** [comment]
@samreid what html files are you testing with?

When I build ph-scale-basics, I see this `<title>` tag:

`<title><202a>pH Scale: Basics<202c> 1.2.0-dev.1</title>`

202a pushes LTR directional format, 202c pops the directional format.

**Comment by samreid** [comment]
ph-scale basics is now fixed.  I'll look into the others.

**Comment by samreid** [comment]
The directionality markers cannot be seen in Sublime, IDEA or GitHub rendered markdown.  It seems like it is safe to leave them.

**Comment by pixelzoom** [comment]
The escapes for directional formatting are added by string.js.

**Comment by pixelzoom** [comment]
The escapes for directional formatting are added by string.js, line 145:

`parsed[ stringKey ].value = ( isRTL ? '\u202b' : '\u202a' ) + parsed[ stringKey ].value + '\u202c';`

**Comment by samreid** [comment]
Note: the only text editor we have tried so far that showed the escapes is vi.

**Comment by samreid** [comment]
Apparently we must load the string through the string plugin in the sim for it to be loaded through the string loader.

**Comment by samreid** [comment]
The litmus title is loaded via:

```js
var simTitle = require( 'string!MOLECULE_POLARITY/molecule-polarity.name' );
```

I'll reassign thing to @pixelzoom to decide what to do here after I finish working on the other ones.

**Comment by samreid** [comment]
I think everything is fixed except for litmus.  I also added a grunt.fail.warn for missing title--this should cause litmus to fail build.  Reassigning to @pixelzoom to decide what to do with litmus.

**Comment by pixelzoom** [comment]
> I think everything is fixed except for litmus. I also added a grunt.fail.warn for missing title--this should cause litmus to fail build.

Why should litmus build fail? `MOLECULE_POLARITY/molecule-polarity.name` is a valid title string.

**Comment by pixelzoom** [comment]
> I think everything is fixed except for litmus. I also added a grunt.fail.warn for missing title--this should cause litmus to fail build.

Why should litmus build fail? `MOLECULE_POLARITY/molecule-polarity.name` is a valid title string. And there should be nothing in the build process that requires the title to come from LITMUS.

**Comment by samreid** [comment]
The package.json is looking for LITMUS/litmus.name but this string is never loaded through the string plugins and hence is unavailable to the build process internationalization.  One solution would be to change the package.json to refer to the same string that is used in litmus-main.js

**Comment by samreid** [comment]
It looks like you fixed this 27 minutes ago https://github.com/phetsims/litmus/commit/3087fe2fdbe0dbdcc15c25c0cdd5e8d1449ceaec

Closing.
