### ISSUE TITLE
move files to js/grunt/?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#248]
Should js/requirejs-plugins/loadFileAsDataURI.js move to js/grunt? It's used by the build process (afterRequirejsBuild.js) and plugins (audio.js, image.js).  Our convention elsewhere (e.g. getLicenseEntry) is to put things used by both in js/grunt/.

**Comment by pixelzoom** [comment]
Same question for createMipmap.js.  @jonathanolson please weigh in.

**Comment by samreid** [comment]
I suggest that if something is only used by the plugins, then it should be in the plugins directory.  Something used by both plugins and the grunt task should be in the grunt directory.  Reassigning to @jonathanolson to weigh in.

**Comment by jonathanolson** [comment]
It seems we'd want 'js/requirejs-plugins' to just contain the plugins themselves, 'js/grunt' to just contain code used in the build, and another directory to contain the rest?

**Comment by pixelzoom** [comment]
js/common/?  What a concept!  +1

**Comment by pixelzoom** [comment]
Another good reason to move stuff to js/common/ is that BuildOptions (coming in #232) will be used by build-server and grunt.

**Comment by samreid** [comment]
+1 for js/common.  I can take a 1st pass at this.

**Comment by samreid** [comment]
I'm working on this.  Some notes:

1. createMipmap is only used from grunt while mipmapDownscale is used by grunt and plugins
2. The following path needed some extra dots (I'm not sure why but it doesn't work without them)
```js
var mipmapDownscale = require( '../../../chipper/js/common/mipmapDownscale' );
```
3. Testing my working copy changes, I see `Uncaught TypeError: 1 is not a function`--I will need to work on this some more!

**Comment by samreid** [comment]
Hmmm I cannot replicate the TypeError above, perhaps a caching thing?

**Comment by samreid** [comment]
Moved things out of the plugins directory in https://github.com/phetsims/chipper/commit/5b0ffe75152444c6d438424fcd50bda76c1295ce.  Commit message is:

> Moved loadFileAsDataURI.js, mipmapDownscale.js to js/common and moved createMipmap.js to js/grunt

**Comment by samreid** [comment]
Tested by linting, building and launching hookes-law, which uses several of the plugins.  Also tested build + launch john travoltage, since it exercises the audio plugin.

**Comment by samreid** [comment]
Moved getLicenseEntry.js to js/common, tested by linting, building, launching hookes-law and `grunt report-media` since it uses getLicenseEntry as well.  No issues noted.  @pixelzoom or @jonathanolson anything else to do here?
