### ISSUE TITLE
should media plugins use grunt.log if it's available?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#249]
global.phet.chipper.grunt was added in https://github.com/phetsims/chipper/issues/222, to address warning message for media files that have an "exception" in their license entry. 

There are several other uses of console.log in the media plugins. Should they also use grunt.log, if it's available?

**Comment by samreid** [comment]
We are wondering if the console.log for these warnings are redundant.  @pixelzoom will investigate.

**Comment by pixelzoom** [comment]
The `console.log` calls are indeed redundant in the media plugins.  They're also inconsistent, since audio.js doesn't use them.

Here's an example with image.js and a bogus image file.

With `console.log` in requirejs mode:
```
GET http://localhost/~cmalley/GitHub/acid-base-solutions/images/solventX.png?bust=1439504711117 404 (Not Found)
image.js?bust=1439504711117:35 failed to load image: js/./../images/solventX.png
```

For `grunt build`, the console.log doesn't even show up:

```
Running "requirejs:build" (requirejs) task
>> Error: Error: ENOENT, no such file or directory '/Users/cmalley/PhET/GitHub/acid-base-solutions/js/../images/solventX.png'
>>     at Object.fs.openSync (fs.js:427:18)
Warning: Task "requirejs:build" failed. Use --force to continue.
```

After removing the `console.log`:

requirejs mode:

```
GET http://localhost/~cmalley/GitHub/acid-base-solutions/images/solventX.png?bust=1439504711117 404 (Not Found)
``

`grunt build` (unchanged):

```
Running "requirejs:build" (requirejs) task
>> Error: Error: ENOENT, no such file or directory '/Users/cmalley/PhET/GitHub/acid-base-solutions/js/../images/solventX.png'
>>     at Object.fs.openSync (fs.js:427:18)
Warning: Task "requirejs:build" failed. Use --force to continue.
```

So it's safe to remove `console.log` from image.js and mipmap.js.

**Comment by pixelzoom** [comment]
https://github.com/phetsims/chipper/issues/258 (missing string key is not detected) needs to be fixed before I can investigate the `console.log` statements in string.js.

**Comment by pixelzoom** [comment]
`console.log` statements were changed to `throw new Error` in #258.  Closing.
