### ISSUE TITLE
grunt-all.sh is difficult to stop

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#250]
grunt-all.sh is currently difficult to stop once you've started it.  Ctrl-C stops the current sim, then it starts the next sim, so you have to hit Ctrl-C a bunch of times.  I'd like to add this, which traps signals and exits:

`trap "exit 1" SIGINT`

I'm not sure how this will affect Windows users.

**Comment by pixelzoom** [comment]
@jbphet volunteered to test on Windows.

**Comment by jbphet** [comment]
Works fine on Windows, closing.
