### ISSUE TITLE
package.json preload is now mandatory?

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#252]
To verify #229 I tried building john-travoltage but received this error:

```
Sams-MacBook-Air:john-travoltage samreid$ grunt --lint=false
Running "clean" task

Running "before-requirejs-build" task
Warning: preload missing from package.json Use --force to continue.

Aborted due to warnings.
```

Did "preload" recently become mandatory?  Tagging @pixelzoom since I know he was in the build tools recently but leaving assigned to me for investigation.

**Comment by samreid** [comment]
Order dependency introduced in #133.  Fixing shortly.

**Comment by samreid** [comment]
Fixed above, closing.

**Comment by pixelzoom** [comment]
Looks like this got introduced when setPreload was moved into beforeRequirejsBuild.  And looks like you discovered and fixed.
