### ISSUE TITLE
check that media file exists before checking its license entry

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#256]
Perhaps the media plugins should confirm that the media file exists before bothering to check its license entry? 

I was testing something else (#45), and tried to load a bogus image in acid-base-solutions, MagnifierNode line 27:

`var solventImage = require( 'image!ACID_BASE_SOLUTIONS/solventX.png' );`

solventX.png doesn't exist. But the error message that I received at build time is:

```
Running "requirejs:build" (requirejs) task
>> Error: Error: unacceptable license entry for ACID_BASE_SOLUTIONS/solventX.png
>> In module tree:
>>     acid-base-solutions-main
>>       ACID_BASE_SOLUTIONS/mysolution/MySolutionScreen
>>         ACID_BASE_SOLUTIONS/mysolution/view/MySolutionView
>>           common/view/AcidBaseSolutionsView
>>             ACID_BASE_SOLUTIONS/common/view/MagnifierNode
>> 
>>     at registerLicenseEntry (eval at <anonymous> (/Users/cmalley/PhET/GitHub/acid-base-solutions/node_modules/requirejs/bin/r.js:25344:38), <anonymous>:79:21
```

Assigning to @samreid for discussion.

**Comment by samreid** [comment]
Well, since both the license entry and image file must exist, I'm not sure this is too much of a problem.  Are you thinking of using fs.fileExistsSynchronous or something like that in the config.isBuild phase of the plugin.load's function?

**Comment by pixelzoom** [comment]
When the license.json file is missing, this (the current case) is an inappropriate and misleading error message:

`Error: unacceptable license entry for ACID_BASE_SOLUTIONS/solventX.png`

Something like this is what's required:

`Error: missing ACID_BASE_SOLUTIONS/images/license.json`

**Comment by samreid** [comment]
Let's try to gracefully handle the following cases:

1. the image file exists but the license.json does not
2. the image file does not exist
3. the image file exists and the license.json exists but the entry within license.json does not (we may choose to handle this in the same way as (1) for technical reasons

For the first case, I deleted acid-base-solutions/license.json and ran grunt.  I received this error:

>> Error: TypeError: Cannot read property 'exception' of null
>> In module tree:
>>     acid-base-solutions-main
>>       ACID_BASE_SOLUTIONS/mysolution/MySolutionScreen
>>         ACID_BASE_SOLUTIONS/mysolution/view/MySolutionView
>>           common/view/AcidBaseSolutionsView
>>             ACID_BASE_SOLUTIONS/common/view/AcidBaseSolutionsControlPanel
>>               ACID_BASE_SOLUTIONS/common/view/ToolsControl
>>                 image
>> 
>>     at isAcceptableLicenseEntry (eval at <anonymous> (/Users/samreid/github/acid-base-solutions/node_modules/requirejs/bin/r.js:27418:38), <anonymous>:48:31)

**Comment by samreid** [comment]
Note: I am building with brand=adapted-from-phet

**Comment by samreid** [comment]
Fixed above.  Next case, missing license.json with brand=phet

The output is:

>> Error: Error: Loader plugin did not call the load callback in the build:
>> image:
>>   image!ACID_BASE_SOLUTIONS/light-bulb-icon.png: Error: unacceptable license entry for ACID_BASE_SOLUTIONS/light-bulb-icon.png
>>   image!ACID_BASE_SOLUTIONS/magnifier-icon.png: Error: unacceptable license entry for ACID_BASE_SOLUTIONS/magnifier-icon.png
>>   image!ACID_BASE_SOLUTIONS/solvent.png: Error: unacceptable license entry for ACID_BASE_SOLUTIONS/solvent.png
>> Module loading did not complete for: acid-base-solutions-main, ACID_BASE_SOLUTIONS/mysolution/MySolutionScreen, ACID_BASE_SOLUTIONS/mysolution/view/MySolutionView, common/view/AcidBaseSolutionsView, ACID_BASE_SOLUTIONS/common/view/AcidBaseSolutionsControlPanel, ACID_BASE_SOLUTIONS/common/view/ToolsControl, ACID_BASE_SOLUTIONS/common/view/ViewsControl, ACID_BASE_SOLUTIONS/common/view/MagnifierNode, ACID_BASE_SOLUTIONS/introduction/IntroductionScreen, ACID_BASE_SOLUTIONS/introduction/view/IntroductionView
>>     at Function.build.checkForErrors (/Users/samreid/github/acid-base-solutions/node_modules/requirejs/bin/r.js:29387:19)

In my opinion, this is acceptable since the license entry (null) is unacceptable.  If it is necessary to provide a different error message, then we would have to introduce another return type or value from getLicenseEntry, which currently returns null if the licenseEntry does not exist within license.json *or* license.json does not exist.  @pixelzoom let's discuss.

**Comment by pixelzoom** [comment]
Why would the build process continue to check images and output multiple error messages, e.g.:

```
image!ACID_BASE_SOLUTIONS/light-bulb-icon.png: Error: unacceptable license entry for ACID_BASE_SOLUTIONS/light-bulb-icon.png
image!ACID_BASE_SOLUTIONS/magnifier-icon.png: Error: unacceptable license entry for ACID_BASE_SOLUTIONS/magnifier-icon.png
image!ACID_BASE_SOLUTIONS/solvent.png: Error: unacceptable license entry for ACID_BASE_SOLUTIONS/solvent.png
```

When the real problem is:

`Error: missing ACID_BASE_SOLUTIONS/images/license.json`

**Comment by pixelzoom** [comment]
> In my opinion, this is acceptable since the license entry (null) is unacceptable

The license entry can be null for 2 different reasons: there is no license entry in license.json, or license.json is missing.

**Comment by pixelzoom** [comment]
> we would have to introduce another return type or value from getLicenseEntry

If there is not license.json, then getLicenseEntry should never be called.

**Comment by pixelzoom** [comment]
On review... I guess it's OK (but not ideal) to handle this in getLicenseEntry.

**Comment by pixelzoom** [comment]
I added the error message. Example:

```
% cd john-travoltage
% rm images/license.json
% grunt
Running "requirejs:build" (requirejs) task
>> Error: Error: missing license file: /Users/cmalley/PhET/GitHub/john-travoltage/js/../images/license.json
>> In module tree:
>>     john-travoltage-main
>>       JOHN_TRAVOLTAGE/john-travoltage/JohnTravoltageScreen
>>         JOHN_TRAVOLTAGE/john-travoltage/view/JohnTravoltageView
>>           JOHN_TRAVOLTAGE/john-travoltage/view/BackgroundElementsNode
>>             image
>> 
>>     at getLicenseEntry (eval at <anonymous> (/Users/cmalley/PhET/GitHub/john-travoltage/node_modules/requirejs/bin/r.js:23461:38), <anonymous>:40:13)
Warning: Task "requirejs:build" failed. Use --force to continue.

Aborted due to warnings.
%
`

This involved no new code path in getLicenseEntry.  It involved modifying what getLicenseEntry does when license.json is missing. Instead of returning null, it now throws an Error.

Assigning to @samreid to review.

**Comment by pixelzoom** [comment]
The change affect build mode only.

**Comment by samreid** [comment]
This is a very nice solution, I am glad you are on the case.  Can I suggest using `grunt.file.exists` rather than `global.fs.exists` in this case?  We probably have other cases that should be unified as well. http://gruntjs.com/api/grunt.file#grunt.file.exists

**Comment by pixelzoom** [comment]
(1) What are the advantages of using `grunt.file.exists` vs `global.fs.existsSync?

(2) Is `grunt.file.exists` synchronous? Documentation doesn't say.

(3) The grunt instance is not available in getLicenseEntry, and this code is structured so that the grunt instance is not required. `global.fs` is available because of this code in Gruntfile.js:

```js
/*
 * In Node, global is the global namespace object.
 * Register fs as a global so it can be accessed through the requirejs build system. Text.js plugin
 * may have a superior way to handle this but I (SR) couldn't get it working after a small amount of effort.
 */
global.fs = fs;
```

My inclination is to stick with `global.fs`. Back to @samreid.

**Comment by pixelzoom** [comment]
And to be consistent, we should probably be adding `fs` to `global.phet.chipper.fs`, as we are doing for the grunt instance (Gruntfile.js line 56):

`global.phet.chipper.grunt = grunt;`

**Comment by samreid** [comment]
(1) fs.existsSync() will be deprecated, see https://nodejs.org/api/fs.html#fs_fs_existssync_path
(2) since it has no callback, grunt.file.exists is synchronous
(3) the grunt instance is available via `global.phet.chipper.grunt`

**Comment by pixelzoom** [comment]
Hmmm... Since we have `global.phet.chipper.grunt`, perhaps we could get rid of `global.fs` and use `global.phet.chipper.grunt.file` (including in getLicenseEntry.js).

**Comment by pixelzoom** [comment]
Replacing `grunt.fs` moved to https://github.com/phetsims/chipper/issues/285.

@samreid Anything else to do here?

**Comment by samreid** [comment]
This seems good, closing.
