### ISSUE TITLE
reorder if-else in string.js

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#257]
The media plugins (audio.js, image.js, mipmap.js) are ordered like this:

```js
if ( config.isBuild ) {
  ... build mode
}
else {
  ... requirejs mode
}
```

string.js does the opposite, with expressing `!config.isBuild`:

```js
if ( !config.isBuild ) {
  ... requirejs mode
}
else {
  ... build mode
}
```

Recommend to reorder the if-else in string.js.

Can I get a +1?

**Comment by samreid** [comment]
+1, isBuild should be first in string.js

**Comment by pixelzoom** [comment]
I'll take care of this immediately after https://github.com/phetsims/chipper/issues/258 is resolved.
