### ISSUE TITLE
missing string key is not detected

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#258]
I believe that this problem was introduced when the structure of string.json was changed.  Each entry was changed (for example) from this:

`"hello": "Hello"`

to this:

```js
"hello": {
  "value": "Hello"
}
```

When a key doesn't have an entry in strings.json, it's not detected, it just fails. The error in requirejs mode is therefore fairly useless:

`Uncaught TypeError: Cannot read property 'value' of undefined`

The offending code (identified by the stack trace) is in string.js, line 138:

`var fallback = parsedFallbackStrings[ key ].value;`

To me, it looks like this entire chunk of code should be restructured, starting at line 141:

```js
               getWithCache( localeSpecificPath, function( parsed ) {
                  // Pad LTR/RTL language values with unicode embedding marks (see https://github.com/phetsims/joist/issues/152)
                  // Uses directional formatting characters: http://unicode.org/reports/tr9/#Directional_Formatting_Characters
                  for ( var stringKey in parsed ) {
                    parsed[ stringKey ].value = ( isRTL ? '\u202b' : '\u202a' ) + parsed[ stringKey ].value + '\u202c';
                  }

                  // Combine the primary and fallback strings into one object hash.
                  var parsedStrings = _.extend( parsedFallbackStrings, parsed );
                  if ( parsedStrings[ key ] !== undefined && parsedStrings[ key ].value.length > 0 ) {
                    onload( window.phet.chipper.mapString( parsedStrings[ key ].value, stringTest ) );
                  }
                  else {
                    console.log( 'string not found for key: ' + key );
                    onload( fallback );
                  }
                },
```

**Comment by pixelzoom** [comment]
The error message at build time is even more useless:

```
% grunt
...
Running "after-requirejs-build" task
Fatal error: Cannot read property 'value' of undefined
%
```

**Comment by pixelzoom** [comment]
`'string not found for key: '` is also an obsolete message. Keys map to {Object} entry, not {string}.

**Comment by pixelzoom** [comment]
This is blocking #249.

**Comment by pixelzoom** [comment]
Skype:
[8/13/15, 6:00:39 PM] Jonathan Olson: I rebuilt that part of the string plugin, and did not test to see what happened with missing strings. I can handle https://github.com/phetsims/chipper/issues/258 if you would like

Assigning to @jonathanolson.

**Comment by pixelzoom** [comment]
This would resolve the requirejs mode error. string.js line 133:

`var fallback = parsedFallbackStrings[ key ] && parsedFallbackStrings[ key ].value;`

**Comment by jonathanolson** [comment]
Added assertions to detect the missing string keys, let me know if anything else is needed.

**Comment by pixelzoom** [comment]
To test, I removed `acid-base-solutions.name` from acid-base-solutions-strings_en, and ran the sim in requirejs mode. 

The error message looks good for a build:

```
% grunt
...
Running "after-requirejs-build" task
Fatal error: Missing string: ACID_BASE_SOLUTIONS/acid-base-solutions.name in acid-base-solutions for fallback locale: en
%
```

But the error message for requirejs mode is not acceptable, it doesn't identify the missing key:

`string.js?bust=1439830358108:138 Uncaught TypeError: Cannot read property `

So this is not fixed. Reassigning to @jonathanolson to try again.

**Comment by pixelzoom** [comment]
So this is still failing as I identified in https://github.com/phetsims/chipper/issues/258#issuecomment-130903091.

**Comment by jonathanolson** [comment]
Added extra throws, so it will fail in require.js without assertions.

**Comment by samreid** [comment]
It looks like the above change is causing lint failures:

```
Linting ../chipper/js/requirejs-plugins/string.js ...ERROR
[L155:C21] W027: Unreachable 'onload' after 'throw'.
                    onload( fallback );
```

Reassigning to @jonathanolson to investigate.

**Comment by pixelzoom** [comment]
Apparently fixed by @jonathanolson in https://github.com/phetsims/chipper/commit/ee8272227818378e939d405f6c8cd2e7e39a5330, which didn't reference this issue.

Back to me for test.

**Comment by pixelzoom** [comment]
Back to @jonathanolson.   You added extra throws for the console.log statements that are unrelated to this issue.  You did not address https://github.com/phetsims/chipper/issues/258#issuecomment-131888795.  Can you please test thoroughly before assigning this back to me?

**Comment by jonathanolson** [comment]
> Can you please test thoroughly before assigning this back to me?

I remove the string from the translation file, and run in require.js mode:

![abs-strings](https://cloud.githubusercontent.com/assets/480878/9314772/426ac1c8-44e8-11e5-9c9b-823970b3ac91.PNG)

And running without assertions still results in the same error message:

Error: Assertion failed: Missing string: acid-base-solutions.name in js/./../acid-base-solutions-strings_en.json?bust=1439841393503

I've tried this on 4 different sims, and on common and sim-specific strings.

> You did not address #258 (comment).

I tested exactly as described, and the assertion you got above is now literally a throw in code (so I'm not sure how your testing would reproduce either something else or still trigger an assertion, besides running into cache issues).

Can you test in incognito mode after pulling, and provide screenshots/etc. of how it is failing differently?

**Comment by jonathanolson** [comment]
Reassigning to me, apparently by changing the URL to not include assertions and refreshing, Chrome switched back to assertions.

**Comment by pixelzoom** [comment]
I am on master for all repos, including chipper. When running without assertions enabled in requirejs mode, I am still experiencing the same problem described inhttps://github.com/phetsims/chipper/issues/258#issuecomment-131888795.  I see no commit related to changing the assertion to `throw Error`, and in chipper f2e621707d300593a046e57c1e6a943ff990c6b3 string.js line 164 looks like this:

```
              assert && assert( parsedFallbackStrings[ key ] !== undefined,
                'Missing string: ' + key + ' in ' + fallbackSpecficPath );
```

Do you perhaps have unpushed changes?

**Comment by jonathanolson** [comment]
Should be fixed now, see https://github.com/phetsims/chipper/issues/258#issuecomment-131967400.

**Comment by pixelzoom** [comment]
Fix verified, closing.
