### ISSUE TITLE
use onload.error in string.js?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#259]
In build mode, string.js does this:

```js
if ( requirePath.substring( requirePath.lastIndexOf( '/' ) ) !== '/js' ) {
  throw new Error( 'Assumes REPO/js location' );
}
...
// tell require.js we're done processing
onload( null );
```

Why is this calling `throw new Error(...)` instead of `onload.error( new Error(...) )`?

**Comment by samreid** [comment]
`onload.error(new Error())` seems better, let's do that instead.

**Comment by samreid** [comment]
Reassign to me if you'd like me to take care of this.

**Comment by pixelzoom** [comment]
Done, closing.
