### ISSUE TITLE
use "requirejsNamespace" consistently?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#260]
There are (at least) 3 names in the code for what we've been calling "requirejs namespace" (e.g. ACID_BASE_SOLUTIONS).  The 3 names are `requirejsNamespace`, `requirePrefix` and `prefix`.

package.json uses `requirejsNamespace`, e.g.:

`"requirejsNamespace": "ACID_BASE_SOLUTIONS",`

string.js uses `requirePrefix`:

```
95 var requirePrefix = name.substring( 0, name.indexOf( '/' ) ); // e.g. 'SOME_SIM'
... and several other places
```

afterRequirejsBuild.js reads `requirePrefix`, and gives it yet-another name, `prefix`:

`97 prefix: global.phet.strings[ stringKey ].requirePrefix`

... then uses `prefix` when building a map:

`139 fileMap[ repository.prefix + '/' + stringKeyMissingPrefix ] = fileContents[ stringKeyMissingPrefix ];`

afterRequirejsBuild.js is interesting because it uses all 3 names.

Should we consolidate these 3 names to "requirejsNamespace" for consistency?

**Comment by pixelzoom** [comment]
Another variation in reportUnusedMedia.js:

` @param {string} simNameUppercase - the upper-case string prefix such as BALANCING_ACT`

**Comment by pixelzoom** [comment]
I took the liberty of renaming simNameUppercase in reportUnusedMedia, since it's called like this:

`reportUnusedMedia( grunt, pkg.requirejsNamespace );`

**Comment by samreid** [comment]
Yes, let's use this consistently with `requirejsNamespace`.  Assign to me if you'd like me to take care of it.
