### ISSUE TITLE
what are the requirements for audio files?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#261]
A question about this workaround in reportUnusedMedia.js:

```js
      // TODO vibe#17 eliminate vibe-specific code in audio.js
      // if it is an audio file, strip off the suffix .mp3 or .ogg because audio is loaded without a suffix
      // The only exception is VIBE/empty.mp3 which doesn't require an ogg version (WHY?)
      if ( key !== 'VIBE/empty.mp3' ) {
        if ( endsWith( key, '.mp3' ) || endsWith( key, '.ogg' ) ) {
          key = key.substring( 0, key.length - 4 );
        }
      }
```

Does this imply that every audio file exists in both .mp3 and .ogg versions? If so, why?  Is this a requirement of the audio plugin, or just of this report? 

Assigning to @samreid since he was the initial author.

**Comment by pixelzoom** [comment]
While working on #262, I created a bogus audio file at john-travoltage/audio/bogus.mp3.  When I ran `grunt`, I got this warning:

`>> Unused audio: JOHN_TRAVOLTAGE/bogus

So I'm wondering why the VIBE workaround is needed?

**Comment by pixelzoom** [comment]
If I have 2 unused images (e.g. `bogus.mp3` and `bogus.ogg`), then I get this:

```
>> Unused audio: JOHN_TRAVOLTAGE/bogus
>> Unused audio: JOHN_TRAVOLTAGE/bogus
```

So there is a fundamental flaw in how this report is handling audio files.

**Comment by samreid** [comment]
> Does this imply that every audio file exists in both .mp3 and .ogg versions? If so, why? 

@jbphet did this work on vibe, but if I recall correctly, Firefox required ogg (cannot play *.mp3) and other platforms (iPad?) required *.mp3.  The EMPTY audio file is only needed on iPad, so it didn't need two encodings.

> So I'm wondering why the VIBE workaround is needed?

VIBE is the only site that loads the filename with a suffix, so the suffix should not be stripped from the report in that case.  All other cases should load the suffix-less version.

I'll look into suppressing one of the error messages for unused audio, or adding suffixes or something.

**Comment by pixelzoom** [comment]
+1 for adding suffixes to the warning messages, rather than suppressing one of the messages.

**Comment by samreid** [comment]
I revised the logic and improved the error messages.  Testing with a new mp3 in hookes law (which has no other audio), I see:

```
>> Unused audio: HOOKES_LAW/x.mp3
```

I think the previous version would have missed this because there was no audio--should be fixed.

Adding an unused audio file to John Travoltage, I see:

```
>> Unused audio: HOOKES_LAW/x.mp3
```

Adding the ogg unused audio file to John Travoltage, I see:
```
>> Unused audio: JOHN_TRAVOLTAGE/x.mp3
>> Unused audio: JOHN_TRAVOLTAGE/x.ogg
```

Grunt & lint on an unmodified hookes-law look good, so I'll commit shortly.

**Comment by samreid** [comment]
Fixed above, @pixelzoom can you take a look?

**Comment by pixelzoom** [comment]
```
% cd john-travoltage
% ls audio/shock.*
audio/shock.mp3  audio/shock.ogg
% touch audio/shock.wav
% grunt
```

This reports no warning for file `shock.wav`, which has no entry in `license.json`.

Back to @samreid.

**Comment by pixelzoom** [comment]
I examined audio license entries at the top of reportUnusedMedia.js:

`console.log( 'global.phet.chipper.licenseEntries=' + JSON.stringify( global.phet.chipper.licenseEntries.audio, null, 2 ) )`

Here's what I see:

```
```

**Comment by samreid** [comment]
I'm halfway through adding that support now.

**Comment by pixelzoom** [comment]
I examined audio license entries at the top of reportUnusedMedia.js:

`console.log( 'JSON.stringify( global.phet.chipper.licenseEntries.audio, null, 2 ) )`

Here's what I see:

```
{
  "VIBE/empty.mp3": {
    "text": [
      "Copyright 2002-2015 University of Colorado Boulder"
    ],
    "projectURL": "http://phet.colorado.edu",
    "license": "contact phethelp@colorado.edu",
    "notes": "required for iOS+Safari workaround, see Sound.js"
  },
  "JOHN_TRAVOLTAGE/shock-ouch": {
    "text": [
      "Copyright 2002-2015 University of Colorado Boulder"
    ],
    "projectURL": "http://phet.colorado.edu",
    "license": "contact phethelp@colorado.edu",
    "notes": "created by Sam Reid"
  },
  "JOHN_TRAVOLTAGE/shock": {
    "text": [
      "Copyright 2002-2015 University of Colorado Boulder"
    ],
    "projectURL": "http://phet.colorado.edu",
    "license": "contact phethelp@colorado.edu",
    "notes": "created by Sam Reid"
  }
}
```

shock-ouch and shock have multiple entries in license.json, but are coalesced to a single entry here. As far as I can tell, there's no check to make sure the entries in license.json are the same - there should be.  But I recommend *not* coalescing them - there should be a license entry for each *file*.  This would also simplify reportUnusedMedia.js, since we wouldn't need to do something special to handle audio file basenames.

**Comment by samreid** [comment]
Fixed above, discussed with @pixelzoom over skype.  Ran this test and results were OK https://github.com/phetsims/chipper/issues/261#issuecomment-131896772 and we also tested that 3rd party licenses appear in the HTML as non-coalesced entries.  My next step is to refactor image/audio handling in reportUnusedMedia since they are similar now.

**Comment by samreid** [comment]
I refactored image/audio handling together above and tested with unused audio files in John Travoltage.  I also added an unused image and it was reported properly.  @pixelzoom care to review?

**Comment by pixelzoom** [comment]
Looks good, except for https://github.com/phetsims/chipper/issues/268.

Closing.
