### ISSUE TITLE
iffy way to strip off a suffix

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#262]
In reportUnusedMedia.js:

```js
 if ( endsWith( key, '.mp3' ) || endsWith( key, '.ogg' ) ) {
  key = key.substring( 0, key.length - 4 );
 }
```

Hardcoding `-4` is an iffy way to strip off a suffix.  A robust solution would string off everything starting from the last occurrence of `'.'`.

**Comment by pixelzoom** [comment]
There's also this incorrect error message in reportUnusedMedia.js  when checking audio files:

`72 grunt.log.warn( 'Unused image: ' + key );`

It should read `'Unused audio: '.

**Comment by pixelzoom** [comment]
Assigned to @samreid to review.

**Comment by samreid** [comment]
Yes, this is very nice, thanks!
