### ISSUE TITLE
string.js fails with invalid locale

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#265]
If you request a bogus locale, e.g.:

`http://localhost/~cmalley/GitHub/acid-base-solutions/acid-base-solutions_en.html?locale=aar`

string.js fails with this error:

`Uncaught TypeError: Cannot read property 'direction' of undefined`

The culprit is string.js, line 114:

```js
        // Read the locale from a query parameter, if it is there, or use english
        locale = phet.chipper.getQueryParameter( 'locale' ) || config.phetLocale || 'en';
        var isRTL = localeInfo[ locale ].direction === 'rtl';
```

`locale` should be validated after it's read. Ie:

```js
if ( !localeInfo[ locale ] ) {
  // ... print error and exit
}

**Comment by pixelzoom** [comment]
Perhaps this?

```js
if ( !localeInfo[ locale ] ) {
  onload.error( new Error( 'unsupported locale: ' + locale ) );
}
```

**Comment by pixelzoom** [comment]
That does error out in requirejs mode, but it stops in the debugger.

**Comment by pixelzoom** [comment]
In build mode, string.js fails with a similar error.

```
% grunt --locales=foo
...
Running "after-requirejs-build" task
Fatal error: Cannot read property 'direction' of undefined
%
```

**Comment by pixelzoom** [comment]
Validation added for build and requirejs mode.  In both cases, the error message is (e.g. ):

`unsupported locale: foo`

Assigning to @jonathanolson to verify.

**Comment by jonathanolson** [comment]
Looks good to me.
