### ISSUE TITLE
PhET-specific metadata in package.json

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#266]
PhET has been adding custom (i.e. PhET-specific) metadata field to package.json, and that's bothered me a little for some time. Is it safe? Will it come back to bite us? 

According to this StackOverflow post, it seems to be a safe practice.
http://stackoverflow.com/questions/10065564/add-custom-metadata-or-config-to-package-json-is-it-valid

The recommendations are to choose a key name:
• not already defined
• not reserved for future use
• avoid prefixes _ and $
• and preferably use a single top-level key in which to nest your custom entries.

That last one seems like particularly good advice. Should we nest all PhET-specific metadata under a "phet" key? For example:

```js
{
  "name": "hookes-law",
  "version": "1.0.0-dev.27",
  "license": "GPLv3",
  "repository": {
    "type": "git",
    "url": "https://github.com/phetsims/hookes-law.git"
  },
  "devDependencies": {
    "grunt": "~0.4.1",
    "grunt-requirejs": "~0.4.0",
    "grunt-contrib-jshint": "~0.6.4",
    "uglify-js": "~2.4.0",
    "requirejs": "~2.1.8"
  },
  "phet": {
    "requirejsNamespace": "HOOKES_LAW",
    "simTitleStringKey": "HOOKES_LAW/hookes-law.name",
    "phetLibs": [ "hookes-law" ],
    "preload": [ "../sherpa/lib/Tween-r12.js" ],
  }
}
```

This might be something to keep in mind when creating the BuildOptions abstraction (see https://github.com/phetsims/chipper/issues/232), or perhaps do this after BuildOptions is in place, since it will encapsulate reading of package.json.

**Comment by pixelzoom** [comment]
The more I look at the example above, the more I like it. It makes it very clear what is specific to PhET.

**Comment by samreid** [comment]
Nesting phet things under `phet` seems brilliant.  Here, take this: +1

**Comment by pixelzoom** [comment]
If no one objects, I'll handle this.

**Comment by pixelzoom** [comment]
The set of PhET-specific fields in package.json is:

licenseKeys
phetLibs
preload
requirejsNamespace
simTitleStringKey

In chipper/js/grunt, search for `"pkg."`.

In chipper/js/build-server, search for `"packageJSON."`.

**Comment by pixelzoom** [comment]
Changes pushed.  

I attempted to use test-server to verify this before pushing. But test-server kept hanging after about 30 minutes, looked like perhaps an out-of-memory problem in Chrome.  So I bailed and used `grunt-all.sh` to verify that everything built.  Probably a safe test, since these changes involved building.  But apologies if I broke anything.

Google Group announcement coming soon, since this is a breaking change.

**Comment by pixelzoom** [comment]
Google Group post:
https://groups.google.com/forum/#!topic/developing-interactive-simulations-in-html5/NEEtIEIVD0w

**Comment by pixelzoom** [comment]
@samreid please review, thanks.

**Comment by samreid** [comment]
I'm having trouble spotting the changes in chipper that make this work.  I can't find it annotated in the commits.  I'll look in the source.

**Comment by samreid** [comment]
Looks like it was committed in e7cbd5ca567bb1909b3e6268b4aa85901af4af5b

**Comment by samreid** [comment]
This change looks good.  I'm seeing some related issues but I'll create separate issues for them.  Closing.
