### ISSUE TITLE
we need access to brand in setPreload

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#267]
To support https://github.com/phetsims/together/issues/154 we will need to know the brand in setPreload.  It is currently defined in beforeRequirejsBuild.

**Comment by samreid** [comment]
Fixed above and tested by building hookes-law with grunt and faradays-law with grunt --brand=phet-io.  @pixelzoom can you review?

**Comment by pixelzoom** [comment]
Change set looks reasonable. This will eventually move to BuildOptions (see https://github.com/phetsims/chipper/issues/232). Closing.
