### ISSUE TITLE
list of media types is duplicated

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#268]
The list of media types is now defined in 2 places, introduced by #261.

reportMedia.js line 104:

`var mediaTypes = [ 'images', 'audio' ];`

reportUnusedMedia line 33:

`[ 'images', 'audio' ].forEach( function( mediaType ) {`

**Comment by pixelzoom** [comment]
Perhaps we can investigate moving these to buildConfig after #232 is buttoned up.  Something like `{string[]} buildConfig.mediaTypes`.

**Comment by samreid** [comment]
Can I unassign this or reassign to @pixelzoom if this will be done in conjunction with #232?  Though actually I don't think this should be part of the buildConfig, this seems more like it should just be a constant (unless buildConfig has constants in it too?)

**Comment by pixelzoom** [comment]
I'll be happy to take care of this.

Re mediaTypes, @samreid said:
>  I don't think this should be part of the buildConfig, this seems more like it should just be a constant (unless buildConfig has constants in it too?)

All fields in the buildConfig API are constants: `@public (read-only)`.  If you mean, "not computed based on config files or options"... We have things like `fallbackLocale` that fall into that category, but are used throughout build code. It seems like `mediaTypes` falls into that category too.

**Comment by pixelzoom** [comment]
I see that there are some constants in ThirdPartyConstants.js.  As an alternative, how about if we combine all constants into buildConstants.js (or pick a better name).  To start, it would looks like this:

```js
/**
 * Constants used in the build process.
 */

// Locale to use when no locale is specified
module.exports.FALLBACK_LOCALE = 'en';

// Media types, also the directory names where the media files live
module.exports.MEDIA_TYPES = [ 'audio', 'images' ];

// @public, for replacement in the sim template by afterRequirejsBuild.js
module.exports.START_THIRD_PARTY_LICENSE_ENTRIES = '### START THIRD PARTY LICENSE ENTRIES ###';

// @public, for replacement in the sim template by afterRequirejsBuild.js
module.exports.END_THIRD_PARTY_LICENSE_ENTRIES = '### END THIRD PARTY LICENSE ENTRIES ###';
```

**Comment by pixelzoom** [comment]
Or perhaps the structor of this can be:

module.exports = function() {
   'use strict';
   return {
    FALLBACK_LOCALE: 'en',
    MEDIA_TYPES: [ 'audio', 'images' ],
    START_THIRD_PARTY_LICENSE_ENTRIES: '...',
    END_THIRD_PARTY_LICENSE_ENTRIES: '...'
   }
};

**Comment by pixelzoom** [comment]
Example of how this would be used in reportUnusedMedia.js:

```js
+ var buildConstants = require( '../../../chipper/js/grunt/buildConstants' );

33 buildConstants.mediaTypes.forEach( function( mediaType ) {
  ...
} );
```

**Comment by pixelzoom** [comment]
Assigning to @samreid for feedback on the above "constants file" proposal.  Feel free to assign back to me when done.

**Comment by samreid** [comment]
Constants as depicted in https://github.com/phetsims/chipper/issues/268#issuecomment-132687674 sounds great.  I think the rule would be to factor out constants (i.e. variables that do not depend on grunt options, variables, etc) that appear across >=2 files.  Constants that only are used within a single file should continue to be declared within that file for modularity.

**Comment by pixelzoom** [comment]
OK, I'm on it.

**Comment by pixelzoom** [comment]
Constants factored out into buildConstants.js.
MEDIA_TYPE used where identified above.
FALLBACK_LOCALE used in getBuildConfig.js (other places to be addressed in https://github.com/phetsims/chipper/issues/284)

@samreid please review.

**Comment by samreid** [comment]
I skimmed through usages of buildConstants.js and all looks good.  The only thing I wasn't sure about is why the name `buildConstants` is lowercased.

**Comment by pixelzoom** [comment]
Because I proposed "buildConstants.js (or pick a better name)" and I didn't hear any negative feedback on buildConstants :)

It's already pushed, but I can change it to BuildConstants (global string replace), if you'd prefer.

**Comment by pixelzoom** [comment]
I also just realized that BuildConstants.js should live in chipper/js/common/, so I can rename at the same time that I move it.

**Comment by pixelzoom** [comment]
Will move to `chipper/js/common/ChipperConstants.js`.

Skype discussion with @samreid.

[8/19/15, 3:44:58 PM] Chris Malley: BuildConstants.js ok with you?
[8/19/15, 3:45:31 PM] Sam Reid: I’m debating between that and ChipperConstants.js
[8/19/15, 3:45:35 PM] Sam Reid: thoughts?
[8/19/15, 3:45:48 PM] Chris Malley: It's moving to chipper/js/common.
[8/19/15, 3:46:06 PM] Chris Malley: Use in grunt/, requirejs-plugins/ and build-server/.
[8/19/15, 3:46:23 PM] Chris Malley: So ChipperConstants is ok with me.
[8/19/15, 3:46:38 PM] Sam Reid: It may be more general for the future, let’s roll with it.

**Comment by pixelzoom** [comment]
`chipper/js/common/ChipperConstants.js` is pushed. Closing.
