### ISSUE TITLE
grunt deploy-dev locks up on Windows 

### ISSUE THREAD

**Issue by jbphet** [phetsims/chipper#269]
The deployment itself seems to work as evidenced by the appearance of the simulation on the dev server, but on my machine (Win7 using GitBash) the grunt task freezes on the ```git push``` step and never recovers.

Screenshot:
![grunt-deploy-dev-issue](https://cloud.githubusercontent.com/assets/3082831/9314343/8ec3cb44-44e5-11e5-88e1-18f31296d426.png)

**Comment by jbphet** [comment]
I think @aaronsamuel137 was mostly working on this, so I'm assigning to him initially, and he can pass it off as necessary.

**Comment by aaronsamuel137** [comment]
Have you tried this again since last Thursday? I have made some minor changes since then that may help with this, but hard to know for sure since I am not sure why it is happening.

**Comment by jbphet** [comment]
Just tried it again to do a dev deploy, and the symptom still exists.

**Comment by aaronsamuel137** [comment]
I tested this with @jessegreenberg when testing grunt deploy-rc (which uses the same code to commit and push). It seemed to work for him just fine on Windows, so perhaps there is something specific to your configuration?

I can look at it with you after meetings on Thursday if you'd like. I'm not sure where to start if I can't reproduce it.

**Comment by jbphet** [comment]
I haven't updated node or my global grunt package for a while.  I'll try that and see if the issue goes away.

**Comment by pixelzoom** [comment]
What version of git are you running?

**Comment by jbphet** [comment]
After updating node, grunt, and git, the deploy-dev works without locking up the shell.  Closing.
