### ISSUE TITLE
use 'phet-io' instead of 'together' when naming dev versions?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#270]
In https://github.com/phetsims/together/issues/154, the 'together' entries in build.json were changed to 'phet-io'.  Perhaps we want to do the same for a adhoc naming of development versions?

afterRequirejsBuild.js line 344:

```js
// TODO: As a temporary means of keeping track of "together" versions, replace "-dev" with "-together" in the
// version string. This approach has a lot of problems and should be replaced as soon as we work out a more all
// encompassing way of tracking together-enhanced versions.  See https://github.com/phetsims/special-ops/issues/3
// for more info.
if ( global.phet.chipper.brand === 'phet-io' ) {
  var unalteredVersion = pkg.version.replace( '-together', '-dev' );
  localeHTML = replaceFirst( localeHTML, unalteredVersion, pkg.version );
}
```

Questions:
• Should we replace 'dev' with 'phet-io', instead of 'together'? Eg: `1.0.0-together.13` vs `1.0.0-phet-io.13`
• Will the hypen in 'phet-io' present any problems? It looks a big odd since hypen is a separator in the version identifier.

Assigning to @jbphet since I believe he implemented this adhoc naming convention.

See also https://github.com/phetsims/special-ops/issues/3

**Comment by pixelzoom** [comment]
@jbphet Note that this workaround is now modifying the `version` field in buildConfig, whose fields are all documented as being `@public (read-only)`.  See getBuildConfig.js.  So this workaround has been less desirable.

**Comment by pixelzoom** [comment]
I moved this workaround to getBuildConfig.js, so that it's not modifying a read-only field.

**Comment by pixelzoom** [comment]
Hmmm... I thought this workaround was isolated in one place, but apparently not. I see this in afterRequirejsBuild.js:

```js
    // TODO chipper#270 As a temporary means of keeping track of "together" versions, replace "-dev" with "-together" in the
      // version string. This approach has a lot of problems and should be replaced as soon as we work out a more all
      // encompassing way of tracking together-enhanced versions.  See https://github.com/phetsims/special-ops/issues/3
      // for more info.
      if ( buildConfig.brand === 'phet-io' ) {
        var unalteredVersion = buildConfig.version.replace( '-together', '-dev' );
        localeHTML = localeHTML.replace( unalteredVersion, buildConfig.version );
      }
```

@jbphet If the version was modified in buildConfig, why is it necessary to replace it here again?  This code is probably doing nothing, since buildConfig.version already contains '-together'.

**Comment by pixelzoom** [comment]
I removed the workaround from afterRequirejsBuild.js, then tested with:

`grunt --brand=phet-io`

The output filenames look correct:

```
% ls -1 build
concentration_en-iframe.html
concentration_en.html
concentration_string-map.json
dependencies.json
```

So this workaround is unnecessary in afterRequirejsBuild.js, and I've deleted it.

**Comment by jbphet** [comment]
In response to @pixelzoom's question above, I believe one location was for altering the name of the file produced, and the other was for altering the version information that appears in the about dialog and on the tab.

**Comment by jbphet** [comment]
The build process has evolved a ton since this renaming thing was initially created, so it is very possible that both are no longer needed, but we should verify that both the file name and the reported version information are correct after the code removal @pixelzoom mentions above.

**Comment by pixelzoom** [comment]
> The build process has evolved a ton since this renaming thing was initially created

I've done nothing to the original workaround, other than to relocate it to getBuildConfig.js.

**Comment by jbphet** [comment]
I just tested a phet-io build of the Concentration simulation, and the ```<title>``` tag does indeed end up being set to ```‪Concentration‬ 1.2.0-together.6``` (which is good), but the About dialog and the tab title show the version as 1.2.0-dev.6 (which is not so good).  When searching through the source code of the built version I am seeing the string 1.2.0-dev.6, so I think the part where @pixelzoom said, 
>I removed the workaround from afterRequirejsBuild.js, then tested...[s]o this workaround is unnecessary in afterRequirejsBuild.js, and I've deleted it
may have had some undesirable consequences.  I'll leave this assigned to me, and we can discuss what we really want to happen at the next dev meeting, and go from there.

**Comment by pixelzoom** [comment]
Ah, I see what's going on here. At runtime, the sim is reading package.json, which does not get updated when buildConfig.version is updated.  So after the html template is filled in, there's an additional search-and-replace occurring.  I'll restore the workaround in afterRequirejsBuild.js and note that there are 2 parts to the workaround.

**Comment by pixelzoom** [comment]
`<title>` tag in html file now contains 'together', as does the About dialog and browser tab/window title.

**Comment by pixelzoom** [comment]
Btw... This workaround never addressed the version identifier that's in the html file for testing iframes (e.g. concentration_en-iframe.html).

**Comment by jbphet** [comment]
I changed the workaround to use -phet-io instead of -together, so that version look like ```1.1.0-phet-io.6```.  I tested this and found that the title and the information in the about dialog appears as expected.

I'm not too concerned about the iframe issue that @pixelzoom raises in the previous comment, but if he feels it should be followed up on, it would be best to log a separate issue.

This is still very much a short term approach until we invent a general strategy for managing the different possible build products.

@pixelzoom - anything left to do on this issue, or should it be closed?

**Comment by pixelzoom** [comment]
:+1: Closing.

**Comment by pixelzoom** [comment]
Reopening. Recommended to remove this workaround now that html filenames end with "-phetio.html".

**Comment by samreid** [comment]
Workarounds removed above, tested by building with `grunt` and `grunt --brand=phet-io`, all seemed well in the filenames/version numbers. @pixelzoom would you like to take a look?

**Comment by pixelzoom** [comment]
Inspected commit, looks good, closing.
