### ISSUE TITLE
automatically add repo to phetLibs

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#271]
Noted while working on #266 (nest PhET-specific metadata under "phet").

PhET-specific metadata in package.json has this boilerplate form:

```js
{
  "name": "balloons-and-static-electricity",
  ...
  "phet": {
    "requirejsNamespace": "BALLOONS_AND_STATIC_ELECTRICITY",
    "simTitleStringKey": "BALLOONS_AND_STATIC_ELECTRICITY/balloons.name",
    "phetLibs": [
      "balloons-and-static-electricity"
    ]
  }
}
```

The phetLibs entry could be eliminated in most cases by automatically adding the value of the "name" field to phetLibs, at the same time that we add the phetLibs from build.json.  The above would then become:

```
{
  "name": "balloons-and-static-electricity",
  ...
  "phet": {
    "requirejsNamespace": "BALLOONS_AND_STATIC_ELECTRICITY",
    "simTitleStringKey": "BALLOONS_AND_STATIC_ELECTRICITY/balloons.name"
  }
}
```

This would be encapsulated in BuildOptions, see https://github.com/phetsims/chipper/issues/232.

**Comment by pixelzoom** [comment]
Can I get a +1 or -1 on this?

**Comment by samreid** [comment]
+1, duplicating the name in the "name" and "phetLib" is awkward and our build tools should know what to do simply from the "name" entry.

**Comment by pixelzoom** [comment]
Done. @samreid would you mind reviewing?  Keep in mind that the chunk of code at the top of Gruntfile.js that sets phetLibs will soon be moved to BuildOptions (see #232).

**Comment by pixelzoom** [comment]
... and I will mention this change in the Google Group post for #266.

**Comment by samreid** [comment]
Here's the code in chipper that makes this work:

```js
  function getPhetLibs( packageJSON, buildJSON, brand ) {

    // start with package.json
    var phetLibs = packageJSON.phet.phetLibs || [];

    // add the repo that's being built
    phetLibs.push( packageJSON.name );

    // add common and brand-specific entries from build.json
    [ 'common', brand ].forEach( function( id ) {
      if ( buildJSON[ id ] && buildJSON[ id ].phetLibs ) {
        phetLibs = phetLibs.concat( buildJSON[ id ].phetLibs );
      }
    } );

    // sort and remove duplicates
    return _.uniq( phetLibs.sort() );
  }
```

Looks great to me, and much cleaner for all our package.json.  Closing.
