### ISSUE TITLE
brand-specific phetLibs in build.json are ignored

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#272]
Noted while working on #271.

In chipper/build.json, it's possible to specify phetLibs for that are common to all sims, and that are required by specific brands.  There are currently no phetLibs specified for "together", and that's a good thing - because they'd currently be ignored. This needs to be handled in Gruntfile.js, immediately after the common.phetLibs is added:

`pkg.phet.phetLibs = pkg.phet.phetLibs.concat( buildInfo.common.phetLibs ); // add phetLibs from build.json

**Comment by pixelzoom** [comment]
Done, @samreid please review.

I tested like by adding `"phetLibs": [ "foo" ]` to build.json under "phet-io".  Then I ran:

```
% cd concentration
% grunt --brand=phet-io --debug
```

... and verified that "foo" appears in the debug output for preload:

`[D] pkg.phet.phetLibs = ../foobar,assert,axon,babel,beers-law-lab,brand,chipper,concentration,dot,joist,kite,nitroglycerin,phet-core,phetcommon,scenery,scenery-phet,sherpa,sun`

**Comment by samreid** [comment]
I ran the test as described in https://github.com/phetsims/chipper/issues/272#issuecomment-132057060 and saw the correct output.  The change set looks straightforward and this is good to close.
