### ISSUE TITLE
setPreload doesn't verify that phet-io API file exists

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#273]
setPreload.js adds the API file for "phet-io" like this, line 51:

`preload.push( '../together/js/api/' + pkg.name + '-api.js' );`

It doesn't both to check that the file actually exists.  So if you happen to do a build with `--brand=phet-io` for a sim that doesn't have an API file (which I did), you get a failure later in the game. It would be nice if that were handled here, with a useful error message.

**Comment by pixelzoom** [comment]
Done. @samreid please review. 

To test:

```
% cd concentration
% grunt --brand=phet-io
...
Done, without errors.
% cd ../hookes-law
% grunt --brand=phet-io
...
Warning: together API file does not exist: ../together/js/api/hookes-law-api.js Use --force to continue.

Aborted due to warnings.
```

**Comment by samreid** [comment]
Change set looks good, thanks.  Closing.
