### ISSUE TITLE
why does setPreload.js read sherpa/lib/license.json?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#274]
setPreload.js line 31:

```js
  // Read license info
  assert( fs.existsSync( LICENSE_INFO_FILENAME ), 'missing ' + LICENSE_INFO_FILENAME );
```

This appears to be vestigial, unused. @samreid can you confirm?

**Comment by pixelzoom** [comment]
Looks like this moved to getThirdPartyLicenseEntries.js:

`var THIRD_PARTY_LICENSES_FILENAME = '../sherpa/lib/license.json'; // contains third-party license info`

**Comment by pixelzoom** [comment]
Vestigial code deleted, @samreid please verify.

**Comment by samreid** [comment]
Thanks, that was vestigial.  Closing.
