### ISSUE TITLE
documentation reference for jshint configuration

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#276]
Encountered while working on #232.

Gruntfile.js line 171 creates the config object for jshint:

```js
   // configure the JSHint plugin
    jshint: {

      // source files that are specific to this repository
      repoFiles: repoFilesToLint,

      // All source files for this repository (repository-specific and dependencies).
      // Excludes kite/js/parser/svgPath.js, which is auto-generated.
      allFiles: allFilesToLint,

      // reference external JSHint options in jshintOptions.js
      options: require( './jshintOptions' )
    }
```

I've been unable to find documentation showing `repoFiles` and `allFiles`. I'd like to put a URL reference in the code.  Anyone know where I can find this?

**Comment by samreid** [comment]
`repoFiles` and `allFiles` are PhET inventions, used in tasks like:

```js
grunt.registerTask( 'lint', 'lint js files that are specific to this repository', [ 'jshint:repoFiles' ] );
```

The doc for grunt talking to jshint is here: https://github.com/gruntjs/grunt-contrib-jshint

**Comment by samreid** [comment]
@pixelzoom based on the above comment can we unmark `developer meeting` and assign to you?

**Comment by pixelzoom** [comment]
Added documentation, closing.
