### ISSUE TITLE
documentation references for requirejs configuration

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#277]
Noted while working on https://github.com/phetsims/chipper/issues/275 and #232.

Gruntfile.js line 138 defines the configuration object for requirejs:

```js
   // configure the RequireJS plugin
    requirejs: {

      // builds the minified script
      build: {
        options: {
          almond: true,
          mainConfigFile: 'js/<%= pkg.name %>-config.js',
          out: 'build/<%= pkg.name %>.min.js',
          name: '<%= pkg.name %>-config',

          // Minification strategy.  Put this to none if you want to debug a non-minified but compiled version
          optimize: 'uglify2',
          wrap: true,
//            generateSourceMaps: true, //#42 commented out this line until source maps are fixed
          preserveLicenseComments: false,
          uglify2: {
            output: {
              inline_script: true // escape </script
            },
            compress: {
              global_defs: globalDefs,
              dead_code: true
            }
          },

          //stub out the plugins so their source code won't be included in the minified file
          stubModules: [ 'string', 'audio', 'image' ]
        }
      }
    },
```

I'd like to document the various parts of this with URLs, but haven't been able to find them. Anyone?

**Comment by pixelzoom** [comment]
And why do we need to do this:

```js
          mainConfigFile: 'js/<%= pkg.name %>-config.js',
          out: 'build/<%= pkg.name %>.min.js',
          name: '<%= pkg.name %>-config',
```

instead of this?

```js
          mainConfigFile: pkg.name + '-config.js',
          out: 'build/' + pkg.name + '.min.js',
          name: pkg.name + '-config',
```

**Comment by samreid** [comment]
Are you looking for https://github.com/jrburke/r.js/blob/master/build/example.build.js ?

**Comment by pixelzoom** [comment]
I saw that reference.  Guess I must have stopped looking at it when the first option ("almond") was not described.  Looks like the others are there.  Any idea if the `almond: true,` entry is actually doing anything, or is bogus?

**Comment by samreid** [comment]
I thought we needed to include the almond https://github.com/jrburke/almond as the compiled replacement for require.js.  But looking into hookes-law_en.html (the built one), I see:

```js
define("almond",function(){})
```

So now I'm not really sure whether we need it.

**Comment by pixelzoom** [comment]
I recall something like that too. But I also recall a lot of confusion and trial-and-error surrounding almond. So this entry is highly suspect. Perhaps @jonathanolson has a clearer recollection?

**Comment by jonathanolson** [comment]
> Perhaps @jonathanolson has a clearer recollection?

I believe almond is the "stub" version of of the require()/define() function provided during runtime to the built version that hooks everything together (instead of shipping the full require.js lib).

I can test and see what happens if we remove it, and work at documenting the rest.

**Comment by jonathanolson** [comment]
Looks like almond is used so that we don't have to provide a full require.js. Running with "almond: false" gives:
```js
ReferenceError: define is not defined at http://localhost:8080/molarity/build/molarity_en.html:459:44 at http://localhost:8080/molarity/build/molarity_en.html:479:29619
```

Documented in place, let me know if there's anythign else to do.

**Comment by pixelzoom** [comment]
Reopening. 

@jonathanolson Any reason why you changed `almond:true` to `almond:false`?  This looks like a bug. It causes the built html file to fail with `Uncaught ReferenceError: define is not defined`.

**Comment by jonathanolson** [comment]
Yup, was my mistake. Sorry!
