### ISSUE TITLE
necessary method of setting requirejs build options?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#278]
In Gruntfile.js...

When specifying requirejs build options, why do we need to do this business with setting `pkg` and using template strings?

```js
    /*
     * Read in the project settings from the package.json file into the pkg property.
     * This allows us to refer to project settings from within this config file.
     */
   pkg: pkg,
   ...
          mainConfigFile: 'js/<%= pkg.name %>-config.js',
          out: 'build/<%= pkg.name %>.min.js',
          name: '<%= pkg.name %>-config',
```

Can't we just do this?

```js
          mainConfigFile: 'js/' + pkg.name + '-config.js',
          out: 'build/' + pkg.name + '.min.js',
          name: pkg.name + '-config',
```

**Comment by samreid** [comment]
Yes, I think we can just do that ourselves.  I think we were just unfamiliar with grunt and tried its default string interpolation to begin with.  I'd recommend to try the "can't we just do this" as you described and keep it if it works (I suspect it will).

**Comment by pixelzoom** [comment]
I made this change and built versions still work just fine.  Since I did exactly what is typed in https://github.com/phetsims/chipper/issues/278#issue-101751416, I'm not going to ask anyone to review it. Closing. If anyone encounters a problem, please reopen.
