### ISSUE TITLE
vestigial 'phetLocale' code?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#279]
While working on #232... I ran across this in beforeRequirejsBuild.js:

```js
// See if a specific language was specified like: grunt build --locale fr
var locale = grunt.option( 'locale' ) || fallbackLocale;

// Pass an option to requirejs through its config build options
grunt.config.set( 'requirejs.build.options.phetLocale', locale );
```

Is the `--locale` option vestigial? My understanding is that this was replaced by `--locales` and `--localesRepo` (which are also handled in beforeRequirejsBuild.js).

**Comment by pixelzoom** [comment]
Searching for "phetLocale" in all .js files... I see phetLocale in string.js, in the requirejs mode:

`143 locale = phet.chipper.getQueryParameter( 'locale' ) || config.phetLocale || 'en';`

I believe this is reading phetLocale from config.js (which should also probably be vestigial).  But the bit of code in beforeRequirejsBuild.js appears to be doing nothing.  Can someone confirm my understanding?

**Comment by pixelzoom** [comment]
To summarize:

(1) Can we remove `--locale` support from beforeRequirejsBuild.js? (affects build mode)

(2) Can we remove `phetLocale` support from config.js? (affects requirejs mode)

**Comment by pixelzoom** [comment]
Looks like this is something that should have been deleted in https://github.com/phetsims/chipper/issues/124 (clean up locale-related options to 'build' task). We went from this set of locale options:

```js
 * --all-locales true: to build all of the provided locales
 * --locales beers-law-lab: use locales from another sim's strings directory
 * --locale fr: to build just the French locale
 * [no options] to build just the fallback locale (typically English)
```

to this:

```js
* --locales=* : all locales from the sim's strings/ directory
* --locales=fr : French
* --locales=ar,fr,es : Arabic, French and Spanish (comma separated locales)
* --localesRepo=beers-law-lab: all locales from another repository's strings/ directory, ignored if --locales is present
```

`locales` replaced `locale` as a more general way to specify 1 or more locales to build.

So I'm going to remove the code identified as vestigial from beforeRequirejsBuild.js.

**Comment by pixelzoom** [comment]
Done. Assigned to @samreid to have a look, and see if my detective work makes sense.

**Comment by samreid** [comment]
Since I am out of the loop on the internationalization implementation, I think it would make more sense for @jbphet or @jonathanolson to review this part.

**Comment by pixelzoom** [comment]
Labeled 'high-priority' to get @jbphet's attention.

**Comment by jbphet** [comment]
I've looked through the code and I think @pixelzoom's detective work makes sense.  The commits look reasonable, and I searched the code and found no occurrences of phetLocale, and the usages of the work 'locale' seem reasonable.  I also did a build with ```es,en``` specified as locales and it succeeded.  Looks good, closing.
