### ISSUE TITLE
clean up 'en' fallback locale

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#284]
The fallback locale 'en' is currently hardcoded in 7 different places. If should be in either buildConfig or a constants file.

**Comment by pixelzoom** [comment]
Addressing this is dependent on https://github.com/phetsims/chipper/issues/268, where we decide to put constants like FALLBACK_LOCALE.

**Comment by pixelzoom** [comment]
Note that buildConfig.js was moved to chipper/js/common/ChipperConstants.js in #268.

**Comment by pixelzoom** [comment]
build-server has 3 occurrences of 'en'.

Options:

(1) Leave it as is, since we're unlikely to ever fallback to anything other than English. (But that argument could have been applied to other chipper code too.)

(2) Replace 'en' with ChipperConstants.FALLBACK_LOCALE.  Here's the change set: 

```js
+ var ChipperConstants = require( '../../../chipper/js/common/ChipperConstants' );
294 var englishStringsFile = simName + '-strings_' + ChipperConstants.FALLBACK_LOCALE + '.json';
295 var stringFiles = [ { name: englishStringsFile, locale: ChipperConstants.FALLBACK_LOCALE } ];
343 var languageJSON = ( stringFile.locale === ChipperConstants.FALLBACK_LOCALE ) ? englishStrings :
```
.. and 'english' in `var` names should be changed to 'fallback' (e.g. `englishStringsFile` -> `fallbackStringFile`).

If we choose (2), I'm not familiar enough with build-server to handle this, so I'd assign it to @aaronsamuel137.

Opinions on this from @aaronsamuel137 and @samreid?

**Comment by aaronsamuel137** [comment]
The use case in build-server is not so much of a fallback locale, as much as handling the case that english strings are in sim repos and other locales are in babel. Build server looks for the localized (or English) sim name in one of those places so it can tell the website the sim title in every locale.

I'm personally fine with option 1 as far as build server is concerned, but I am not familiar with the other chipper code.

**Comment by pixelzoom** [comment]
I'm ok with option (1) too. Let's discuss briefly at developer meeting.

**Comment by pixelzoom** [comment]
8/20/15 consensus is leave as is. Closing.
