### ISSUE TITLE
replace global.fs with global.phet.chipper.grunt.file

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#285]
See https://github.com/phetsims/chipper/issues/256#issuecomment-132775385:
> (1) fs.existsSync() will be deprecated, see https://nodejs.org/api/fs.html#fs_fs_existssync_path
(2) since it has no callback, grunt.file.exists is synchronous
(3) the grunt instance is available via global.phet.chipper.grunt

**Comment by pixelzoom** [comment]
I'd like a second opinion before embarking on this. @jonathanolson?

**Comment by jonathanolson** [comment]
An alternative is to do what the Node.js documentation recommends:

> In particular, checking if a file exists before opening it is an anti-pattern that leaves you vulnerable to race conditions: another process may remove the file between the calls to fs.exists() and fs.open(). Just open the file and handle the error when it's not there.

**Comment by samreid** [comment]
@jonathanolson's suggestion sounds like worth investigation.  But we should also discuss whether to use fs.read or grunt.file and whether to use the sync or async versions.

**Comment by pixelzoom** [comment]
8/20/15 dev meeting: I'll investigate moving to `grunt.file`.

**Comment by pixelzoom** [comment]
build-server uses global.fs because it doesn't have grunt.
common uses global.js because it needs to run in both requirejs and build modes.

Consensus at 8/20/15 dev meeting:  
• Convert to `grunt.file` where we have access to grunt.
• Use `global.fs` where we don't to grunt. 
• Remove antipattern identified in https://github.com/phetsims/chipper/issues/285#issuecomment-132839296 where possible (includes removing `global.fs.existsSync`).

**Comment by pixelzoom** [comment]
Evaluation of what needs to be done...

Places where 'fs' can be replaced with 'grunt.file':
• 19 occurrences in chipper/js/grunt

Places where `grunt.file.exists` needs to be replaced with `grunt.file` method of "open file and handle error":
• 12 occurrences in chipper/js/grunt

Places where 'fs.existsFileSync` needs to be replaced with 'fs' method of "open file and handle error":
• 18 occurrences chipper/js/build-server
• 1 occurrences in chipper/js/common

**Comment by pixelzoom** [comment]
Looking at the anti-pattern recommendation... I realize that *in general* there can be a race condition. But that's highly unlikely to be the case with any files that we're reading.

The pattern we're using now is:

```js
  var PACKAGE_FILENAME = 'package.json';
  assert( fs.existsSync( PACKAGE_FILENAME ), 'missing ' + PACKAGE_FILENAME );
  var packageJSON = grunt.file.readJSON( PACKAGE_FILENAME );
```

and `grunt` output looks like this:

```
% grunt
>> AssertionError: missing package.json
Aborted due to warnings.
%
```

Handling the read/open error would look like this:

```js
var PACKAGE_FILENAME = 'package.json';
var packageJSON;
try {
  packageJSON = grunt.file.readJSON( PACKAGE_FILENAME );
}
catch( error ) {
  throw error;
} 
```

and `grunt` output looks like this:

```
% grunt
>> Error: Unable to read "package.json" file (Error code: ENOENT).
Aborted due to warnings.
%
```

Interestingly, not handling the error (e.g. below) outputs the same error and stops the build immediately.

`var packageJSON = grunt.file.readJSON( PACKAGE_FILENAME );`

**Comment by pixelzoom** [comment]
So... I'm inclined to forgo the error checking since (a) the code is more compact and (b) the end result is the same.

I'd like feedback from @samreid and @jonathanolson before proceeding.

**Comment by pixelzoom** [comment]
Does the anti-pattern recommendation also apply for optional files?

Eg, should we read build-local.json like this:

```js
if ( grunt.file.exists( BUILD_LOCAL_JSON ) ) {
   buildLocalJSON = grunt.file.readJSON( BUILD_LOCAL_FILENAME );
}
```

Or like this?

```js
var buildLocalJSON;
try {
  buildLocalJSON = grunt.file.readJSON( BUILD_LOCAL_FILENAME );
}
catch( error ) {
  buildLocalJSON = {};
}
```

**Comment by pixelzoom** [comment]
Skype:

[8/21/15, 11:35:49 AM] Sam Reid: Your proposed approach sounds great for required files.
[8/21/15, 11:36:39 AM] Chris Malley: Many grunt.file.read are already using that pattern (e.g.  build/repo.min.js in afterRequirejsBuild.js line 197)
[8/21/15, 11:36:54 AM] Sam Reid: anything else I should comment on?
[8/21/15, 11:37:01 AM] Chris Malley: preference on pattern for optional files?
[8/21/15, 11:37:10 AM] Sam Reid: checking
[8/21/15, 11:37:22 AM] Chris Malley: test and open? or open, catch and fallback.
[8/21/15, 11:37:51 AM] Sam Reid: the docs from node were also advocating to use open, catch and fallback, which sounds good to me
[8/21/15, 11:38:00 AM] Chris Malley: ok

**Comment by pixelzoom** [comment]
Accidentally deleted changes to getBuildConfig.js in https://github.com/phetsims/chipper/commit/156bdafe4bbd2439cb7b2fe4013aee0befc795a2, will fix momentarily.

**Comment by pixelzoom** [comment]
Here's an interesting case, in the `clean` task. I tried this:

```js
try {
  grunt.file.delete( 'build' );
}
catch( error ) {
  // do nothing
}
grunt.file.mkdir( 'build' );
```

And this prints a warning:

```
% grunt clean
Running "clean" task
>> Cannot delete nonexistent file.

Done, without errors.
%
```

Personally, I don't want to see this warning.  So I'm going to do revert to this:

```js
      if ( grunt.file.exists( 'build' ) ) {
        grunt.file.delete( 'build' );
      }
      grunt.file.mkdir( 'build' );
```

**Comment by pixelzoom** [comment]
Work completed, remaining issues broken out into separate GitHub issues (see immediately above).

js/build-server/ still uses `fs` because it doesn't have access to grunt.

js/common/ still uses `fs` because it needs to run in both build and requirejs modes. It gets `fs` via `global.phet.chipper.fs`.

Remaining usages of `grunt.file.exists` in createSim.js, generateThumbnails.js, getBuildConfig.js and Gruntfile.js seem appropriate to me.

@aaronsamuel137 would you mind reviewing this?

**Comment by pixelzoom** [comment]
You can search for "fs." and "grunt.file.exists" to see remaining use sites.

**Comment by pixelzoom** [comment]
@aaronsamuel137 poke.

**Comment by aaronsamuel137** [comment]
Changes look good to me.

One question: Did we decide that we want to remove all cases of the deprecated method fs.existsSync()? There are still 5 uses in build-server and 1 use in getLicenseEntry. I can take care of these if that is the consensus.

**Comment by pixelzoom** [comment]
As mentioned in https://github.com/phetsims/chipper/issues/285#issuecomment-133541852 above... #306, #307 and #308 were broken out as separate issues to address cases where use of `fs` is questionable. The other uses of `fs` (as described in that comment) seem acceptable to me - and I don't know how you'd remove `fs` from build-server and chipper/common, because they don't have access to `grunt`.

@aaronsamuel137 if you agree, feel free to close this issue.

**Comment by aaronsamuel137** [comment]
All uses of fs seem acceptable to me, I was particularly wondering about the method existsSync(), since we had discussed removing this pattern and replacing it with the open, catch and fallback pattern https://github.com/phetsims/chipper/issues/285#issuecomment-133506741.

I couldn't quite decipher from the comments above if we had reached a definite consensus on this.

**Comment by pixelzoom** [comment]
Ah... Ok, now I understand what you're asking.  Yeah, probably worth getting rid of fs.existsSync, since it's deprecated.

`fs.readFileSync( 'foo' )` without a try/catch will fail with:

`>> Error: ENOENT, no such file or directory 'foo'`

So for required files (no fallback), I'd be OK with removing the `fs.existsSync` call, and just letting it fail with that error message.

For files where there is a fallback, the pattern would be:

```js
try {
   fs.readFileSync( ... );
}
catch ( error ) {
   // do whatever the fallback action is
}
```

In getLicenseEntry.js, there is no fallback. So just let `fs.readFileSync` fail.

In build-server.js, it looks like 2 of the 5 uses result in a call to `abortBuild`, so those could just fail too. The other 3 uses look like there may be a fallback.

**Comment by pixelzoom** [comment]
I handled getLicenseEntry.js, and moved the build-server.js work to https://github.com/phetsims/chipper/issues/337. 

Since @aaronsamuel137 said other changes looked good, I'll go ahead and close this issue.
