### ISSUE TITLE
directory name for "grunt deploy-dev --test"

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#286]
`grunt deploy-dev --test` copies to a test directory on spot.  Here's the relevant part of `grunt --help`:

`--test : set to true to disable commit and push, and  SCP to a test directory on spot`

The URL is printed to the console when the task completes, so it's OK that the directory name isn't noted in the help.  But the directory name is `www.colorado.edu/physics/phet/dev/html/ad-tests`. The "ad" in `ad-tests` is (presumable) @aaronsamuel137's initials. That's not appropriate for production code.  Recommend to change to something like `deploy-dev-tests`.

**Comment by aaronsamuel137** [comment]
Good call. I've updated the test directory name to deploy-dev-tests. Assigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
Shall we move the existing `ad-tests` on spot to `deploy-dev-tests`?

**Comment by aaronsamuel137** [comment]
That's fine with me. I can't move hookes-law because permission denied. Not sure who the owner is. I'm also fine with deleting, since these are just tests, so are not linked to from anywhere.

**Comment by aaronsamuel137** [comment]
Once hookes-law is moved or deleted, I will delete the directory, or someone else can feel free to.

**Comment by pixelzoom** [comment]
I was the owner of ad-tests/hookes-law/. I delete it and ad-tests/.

Closing.
