### ISSUE TITLE
is getCacheBusterArgs vestigial?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#288]
In beforeRequirejsBuild.js:

```js
  // polyfill to work around the cache buster arg in the *-config.js file that all sims have.
  global.phet.chipper.getCacheBusterArgs = global.phet.chipper.getCacheBusterArgs || function() { return ''; };
```
I don't see `global.phet.chipper.getCacheBusterArgs` uses anywhere in any repo. Is this vestigial?

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/chipper/commit/b4930f8af33cff088192fa92d252bf53d3040d0c, I moved this from Gruntfile.js to beforeRequirejsBuild.js (formerly simBeforeRequirejs.js).

**Comment by pixelzoom** [comment]
Assigning to @jonathanolson for comment.

**Comment by jonathanolson** [comment]
I'm updating repos after the build change (in progress), but unless something changed, it's used in 94 sim config files, so I wouldn't consider it vestigial.

**Comment by pixelzoom** [comment]
Hmmm. I must've been searching is something other than *.js, sorry about that.  Closing.

**Comment by pixelzoom** [comment]
Reopening. There are still some things I'm not clear about.

**Comment by pixelzoom** [comment]
Here's the code in beforeRequirejsBuild.js:

`global.phet.chipper.getCacheBusterArgs = global.phet.chipper.getCacheBusterArgs || function() { return ''; };`

When would `global.phet.chipper.getCacheBusterArgs` already be defined? Why isn't it simply this?:

`global.phet.chipper.getCacheBusterArgs = function() { return ''; };`

**Comment by pixelzoom** [comment]
Would it be OK to move this to the global initialization that takes place in Gruntfile.js? I.e.:

```js
global.phet = {

    chipper: {

      // for situations where we can't pass the grunt instance as a function argument
      grunt: grunt,

      // polyfill to work around the cache buster arg in the *-config.js file that all sims have.
      getCacheBusterArgs: function() { return ''; };
    }
  };

**Comment by jonathanolson** [comment]
> Would it be OK to move this to the global initialization that takes place in Gruntfile.js?

Probably. If in build-mode, it should presumably always return the empty string.

**Comment by pixelzoom** [comment]
Verified that `global.phet.chipper.getCacheBusterArgs` is `undefined` in beforeRequirejsBuild.js.  So I'm going to simplify it and move it to global initialization as described in #296.

**Comment by pixelzoom** [comment]
Moved to global initialization block in Gruntfile.js. @jonathanolson please review.

**Comment by jonathanolson** [comment]
Looks good.
