### ISSUE TITLE
move initialization of global.phet.mipmapsToBuild to mipmap?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#289]
After #232, beforeRequirejsBuild.js doesn't contain much.  So I'm looking at possibly making it go away.

Regarding this:

```
  // Since require.js plugins can't be asynchronous with isBuild=true (r.js mode), we need to catch all of the
  // mipmaps that we'll need to build and then handle them later asynchronously.
  global.phet.mipmapsToBuild = [];
```

Instead of initializing an empty array here, would it be acceptable for mipmap.js to handle the initialization?
`

**Comment by jonathanolson** [comment]
I'd be fine with mipmap.js handling the initialization if run in build-mode.
