### ISSUE TITLE
remove redundant initialization of global.phet.chipper.licenseEntries 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#290]
After #232, beforeRequirejsBuild.js doesn't contain much. So I'm looking at possibly making it go away.

Regarding this:

```js
  // These entries will be filled in as plugins are loaded.  
  // This will have elements: lib, audio, images, etc.
  global.phet.chipper.licenseEntries = {};
```

This initialization seems unnecessary, since registerLicenseEntry.js (called by the media plugins) does this:

`global.phet.chipper.licenseEntries[ mediaType ] = global.phet.chipper.licenseEntries[ mediaType ] || {};`

OK to remove the initialization in beforeRequirejsBuild.js?

**Comment by pixelzoom** [comment]
Whoops. registerLicenseEntry.js isn't initializing `global.phet.chipper.licenseEntries`. We'd need to add this:

`global.phet.chipper.licenseEntries = global.phet.chipper.licenseEntries || {};`

Is that OK?

**Comment by samreid** [comment]
Yes, I think it has generally been a good idea to move initialization of data structures to the plugins that use them.

**Comment by pixelzoom** [comment]
Reopening. I realized that I didn't test for the case where no media plugins are called, and therefore `global.phet.chipper.licenseEntries` is never initialized.  I don't believe this currently happens. But it would cause afterRequirejsBuild.js to fail an assertion.

**Comment by pixelzoom** [comment]
Case handled.  Closing again.
