### ISSUE TITLE
delete beforeRequirejsBuild.js? 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#291]
After #232, there are 3 lines of non-debug code remaining in beforeRequirejsBuild.js. Depending on the resolution of #288, #289 and #290, we may be able to simply delete this file and associated grunt task.

**Comment by samreid** [comment]
Getting rid of beforeRequirejsBuild.js would be very nice.  It is inconvenient to have to have internal methods show up as public tasks in grunt --help.

**Comment by pixelzoom** [comment]
As the result of the above-mentioned issues, beforeRequirejsBuild.js has been reduced to:

`grunt.log.debug( 'Building simulation: ' + name + ' ' + version );`

I think we can live without this, so I'm going to disappear beforeRequirejsBuild.js.
