### ISSUE TITLE
untangle afterRequirejsBuild.js

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#292]
afterRequirejsBuild.js is currently a complicated, long (445 lines) collection of unrelates responsibilities (strings, mipmaps, preloads, sim template,...) all rolled into one source file.  Maintenance would be simplified and readability improved if this were split up into functions - either defined in afterRequirejsBuild.js or in separate files.  As is, it's difficult to grok the subtasks and dependencies.

**Comment by pixelzoom** [comment]
Consensus at 8/20/15 dev meeting: Sounds like a good idea, I'll go for it.

**Comment by pixelzoom** [comment]
Looks like the big chunks of stuff are (in no particular order):

* build mipmaps
* create string map
* populate sim template 
* create html files (for 1 or more locales)
* create dependencies.json

**Comment by pixelzoom** [comment]
afterRequirejsBuild.js has been factored out into the following files:

```
createDependenciesJSON.js
createMipmapsJavaScript.js
createHTMLFile.js
```

Each of these is a well-encapsulated step in the 'after-requirejs-build' task, which is asynchronous.

From the doc in afterRequirejsBuild.js, here's how these steps fit together:

```js
 * Due to the asynchronous nature of determining shas and branch names for dependencies (via child_process.exec)
 * and creating scripts for mipmaps, the overall structure of this task is necessarily nested, relying on callbacks.
 * Here's the basic flow of this task:
 *
 * createDependenciesJSON() {
 *
 *   var dependenciesJSON = ... // create JSON that describes dependencies
 *   write dependencies.json file;
 *
 *   createMipmaps( dependenciesJSON ) {
 *
 *     var mipmapsJavascript = ... // create script for mipmaps
 *
 *     createHTMLFiles( dependenciesJSON, mipmapsJavascript ) {
 *       replace tokens in HTML template;
 *       write locale-specific HMTL files;
 *       done;
 *     }
 *   }
 * }
```

**Comment by pixelzoom** [comment]
One other "factored out" file that I forgot to mention is getStringMap.js. It creates the map that allows us to lookup a string by locale + key.  It is a synchronous function used in the createHTMLFiles.js step.

I tested a dozen sims in requirejs and build modes, and I didn't see any issues.

**Comment by samreid** [comment]
It is confusing for createDependenciesJSON.js to call createMipmapsJavaScript() and for createMipmapsJavaScript.js to call createHTMLFiles.  I understand this was an incremental refactor and a step in a good direction, but I would recommend to go even further and use a different pattern to simplify and modularize these tasks.  One possibility would be to use callback functions, like so:

Change: 
```js
// in createDependenciesJSON.js
      // Begin the next build step
      createMipmapsJavaScript( grunt, buildConfig, dependenciesJSON, done );
```

to:
```js
      // Begin the next build step
      callback( dependenciesJSON );
```

In the latter case, the grunt, buildConfig, and done can be passed from the parent (afterRequirejsBuild).

afterRequirejsBuild.js would look like this:

```js
  createDependenciesJSON( grunt, buildConfig, done, function( dependenciesJSON ) {
    createMipmapsJavaScript( grunt, buildConfig, dependenciesJSON, done );
  } );
```

and so forth through the call chain.

**Comment by samreid** [comment]
One edit: the createDependenciesJSON doesn't need to know anything about the `done`, so it would be like this:

```js
  createDependenciesJSON( grunt, buildConfig, function( dependenciesJSON ) {
    createMipmapsJavaScript( grunt, buildConfig, dependenciesJSON, done );
  } );
```

**Comment by pixelzoom** [comment]
> One edit: the createDependenciesJSON doesn't need to know anything about the done, so it would be like this:

According to the doc for `grunt.task.current.async` (http://gruntjs.com/api/inside-tasks#this.async), it tells grunt that the task is asynchronous, and instructs grunt to wait.  And when the task is completed, the handle returned by `grunt.task.current.async` needs to be called to tell grunt that the task has completed. So my understanding (and experience) is that `grunt.task.current.async` needs to be called at the beginning of the tasks, and the function handle needs to be passed to the last step in the task.

**Comment by pixelzoom** [comment]
Ah, I see what you're saying.

What you're describing is similar to the original structure that I implemented.  It looked nice in afterRequirejsBuild.js, like:

`createDependenciesJSON( grunt, buildConfig, createMipmapsJavaScript, done );`

And in createDependenciesJSON.js:

```
module.exports = function( grunt, buildConfig, nextStepCallback, done ) {
  ...
  nextStepCallback( grunt, buildConfig, dependenciesJSON, done );
}
```

But I encountered a couple of problems:

(1) createMipmapsJavaScript.js would need to know about createHTMLFiles.js, and it was impossible to specify the entire callback chain in afterRequirejsBuild.js
(2) nextStepCallback's identify and signature is non-obvious, while createMipmapsJavaScript's signature is easy to determine.

So I switched to the current implementation, where each step has a `require` statement for the next step, and the functions involved (and their signatures) are obvious.

**Comment by samreid** [comment]
Yes, you still have to call done when everything cascading from afterRequirejsBuild is complete, but createDependenciesJSON doesn't need to know anything about it.

**Comment by pixelzoom** [comment]
Oh wait... I get it. Yeah, let me try that. Thanks.

**Comment by pixelzoom** [comment]
Thanks for the suggestion @samreid. I like this much better, in afterRequirejsBuild.js:

```js
// The multi-step asynchronous task described above.
// For each step, a callback function invokes the next step.
createDependenciesJSON( grunt, buildConfig, function( grunt, buildConfig, dependenciesJSON ) {
  createMipmapsJavaScript( grunt, buildConfig, dependenciesJSON, function( grunt, buildConfig, dependenciesJSON, mipmapsJavaScript ) {
    createHTMLFiles( grunt, buildConfig, dependenciesJSON, mipmapsJavaScript, done );
  } );
} );
```

**Comment by samreid** [comment]
This is looking much better, thanks @pixelzoom.  One improvement you could make from here is to omit extraneous parameters (in this case grunt and buildconfig) from the callbacks:

```js
  createDependenciesJSON( grunt, buildConfig, function( dependenciesJSON ) {
    createMipmapsJavaScript( grunt, buildConfig, dependenciesJSON, function( dependenciesJSON, mipmapsJavaScript ) {
      createHTMLFiles( grunt, buildConfig, dependenciesJSON, mipmapsJavaScript, done );
    } );
  } );
```

**Comment by pixelzoom** [comment]
I'm not entirely convinced that it's an improvement, but done.

**Comment by pixelzoom** [comment]
I think I'm done with this. @samreid since you've looked around already, would you mind reviewing?

**Comment by samreid** [comment]
Sure, I'll review but it may be several days before I get to it.

**Comment by pixelzoom** [comment]
At your leisure.

**Comment by samreid** [comment]
Now that the actual implementation of the file is:

```js
  // The multi-step asynchronous task described above.
  // For each step, a callback function invokes the next step.
  createDependenciesJSON( grunt, buildConfig, function( dependenciesJSON ) {
    createMipmapsJavaScript( grunt, buildConfig, dependenciesJSON, function( dependenciesJSON, mipmapsJavaScript ) {
      createHTMLFiles( grunt, buildConfig, dependenciesJSON, mipmapsJavaScript, done );
    } );
  } );
```

can we remove the jsdoc that says:

```js
 /* Here's the basic flow of this task:
 *
 * createDependenciesJSON() {
 *
 *   var dependenciesJSON = ... // create JSON that describes dependencies
 *   write dependencies.json file;
 *
 *   createMipmaps( dependenciesJSON ) {
 *
 *     var mipmapsJavascript = ... // create script for mipmaps
 *
 *     createHTMLFiles( dependenciesJSON, mipmapsJavascript ) {
 *       replace tokens in HTML template;
 *       write locale-specific HMTL files;
 *       done;
 *     }
 *   }
 * }
 */
```

**Comment by samreid** [comment]
This line refers to a nonexistent file:

```
* @param {Object} buildConfig - see initBuildConfig.js
```

**Comment by samreid** [comment]
```js
createMipmapsJavaScript( grunt, buildConfig, dependenciesJSON, function( dependenciesJSON, mipmapsJavaScript ) {
```
should be changed to:

```js
createMipmapsJavaScript( grunt, buildConfig, dependenciesJSON, function( mipmapsJavaScript ) {
```

Shadowing variables with different variables that happen to have the same value is a code smell and it is simpler without the shadowing variables. The implementation of `createMipmapsJavaScript` will need to be updated accordingly.

**Comment by samreid** [comment]
Do you want to revise these comments?  Seems a bit obvious that the callback invokes the next step.  Why describe it above? etc.

```
  // The multi-step asynchronous task described above.
  // For each step, a callback function invokes the next step.
  createDependenciesJSON( grunt, buildConfig, function( dependenciesJSON ) {
    createMipmapsJavaScript( grunt, buildConfig, dependenciesJSON, function( dependenciesJSON, mipmapsJavaScript ) {
      createHTMLFiles( grunt, buildConfig, dependenciesJSON, mipmapsJavaScript, done );
    } );
  } );
```

If I were documenting it, I may have written something like:

>// Enumerate the dependencies (and their shas), then the mipmaps and use both to generate the final minified HTML file

**Comment by pixelzoom** [comment]
Internal doc revised for afterRequirejsBuild.js (both the file header and the `createDependenciesJSON` cal.

Doc for @param buildConfig also fixed.

**Comment by samreid** [comment]
I wasn't sure why the callbacks are named `nextStep`.  Each module shouldn't have to know whether or not there is a next step--it only needs to send out a notification when its work is complete.  I have seen others call these something like `callback` or (less frequently) `finished`.

**Comment by pixelzoom** [comment]
There's also a bug on line 63 of createMipmapJavaScript.js. 

`nextStep( dependencies, mipmapsJavaScript );`

should be:

`nextStep( grunt, buildConfig, dependencies, mipmapsJavaScript );`

**Comment by samreid** [comment]
Not necessarily something that must be changed, but I noticed that some of the JSDoc is formatted like:

```js
/**
 * Creates JavaScript for mipmaps used by the sim.
 * This will be embedded in the HTML files.
 *
 * This is one step in the 'after-requirejs-build' task.
 * See afterRequirejsBuild.js for documentation on how this step fits into that asynchronous task.
 *
 * @author Johnathan Olson <jonathan.olson@colorado.edu>
 * @author Chris Malley (PixelZoom, Inc.)
 */
```

instead of 
```js
/**
 * Creates JavaScript for mipmaps used by the sim. This will be embedded in the HTML files.
 *
 * This is one step in the 'after-requirejs-build' task. See afterRequirejsBuild.js for documentation on how this step 
 * fits into that asynchronous task.
 *
 * @author Johnathan Olson <jonathan.olson@colorado.edu>
 * @author Chris Malley (PixelZoom, Inc.)
 */
```
or even
```js
/**
 * Creates JavaScript for mipmaps used by the sim. This will be embedded in the HTML files.  This is one step in the 
 * 'after-requirejs-build' task. See afterRequirejsBuild.js for documentation on how this step fits into that 
 * asynchronous task.
 *
 * @author Johnathan Olson <jonathan.olson@colorado.edu>
 * @author Chris Malley (PixelZoom, Inc.)
 */
```

Is this just a style preference?  No big deal, I'm just curious.

**Comment by pixelzoom** [comment]
It was called `nextStep` when data was being (e.g. `dependencies`) propogated.  I'll change it when I've implemented your suggestion above of removing params related to propagation, and propagate via closure variables.

**Comment by pixelzoom** [comment]
This part:

```
This is one step in the 'after-requirejs-build' task.
 * See afterRequirejsBuild.js for documentation on how this step fits into that asynchronous task.
```

... was repeated in each step's .js file.  And my style is to break documentation into logical paragraphs, rather than have one run-on paragraph.

**Comment by samreid** [comment]
> There's also a bug on line 63 of createMipmapJavaScript.js.

I think we decided to get rid of the shadowing variables.  Together with my recommendation above in https://github.com/phetsims/chipper/issues/292#issuecomment-135165287, this should become:

```js
nextStep( mipmapsJavaScript );
```

**Comment by pixelzoom** [comment]
Right... This line is buggy:

`nextStep( grunt, buildConfig, '<!-- no mipmaps -->' )`

**Comment by pixelzoom** [comment]
All of the above suggestions (except https://github.com/phetsims/chipper/issues/292#issuecomment-135167392) have been pushed.  Tested with john-travoltage in build mode.

**Comment by samreid** [comment]
Looks great, nice work.
