### ISSUE TITLE
initialize and document all globals in one place?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#296]
We currently set some globals at the top of Gruntfile.js, like this:

```js
global.phet = {
    chipper: {
      grunt: grunt // for situations where we can't pass the grunt instance as a function argument
    }
  };
```

How about consolidating all initialization and documentation here? E.g.:

```js
  // Initialize and document all globals
  assert( !global.phet, 'global.phet already exists' );
  global.phet = {

    chipper: {

      // the grunt instance, for situations where we can't pass it as a function argument
      grunt: grunt,

      // polyfill to work around the cache buster arg in the *-config.js file that all sims have.
      getCacheBusterArgs: function() { return ''; },

      // media plugins populate this with license.json entries, see getLicenseEntry.js for format of entries
      licenseEntries: {},

      // use by media plugins, which don't have access to buildConfig
      brand: buildConfig.brand
    },

    // populated by mipmap.js
    mipmapsToLoad: [],

    // populated by string.js
    strings: {}
  };
```

**Comment by pixelzoom** [comment]
I went ahead and did this, didn't see any down side. @samreid please review.

**Comment by samreid** [comment]
The old version had:
```js
global.phet.chipper.getCacheBusterArgs = global.phet.chipper.getCacheBusterArgs || function() { return ''; };
```

The new version has:
```js
getCacheBusterArgs: function() { return ''; },
```

Was this intentional?  Will it have any negative ramifications?  I don't think so, but thought I should ask.  Everything else looks good.

**Comment by pixelzoom** [comment]
I verified that `global.phet.chipper.getCacheBusterArgs` was undefined at the point where the old version lived. See https://github.com/phetsims/chipper/issues/288#issuecomment-133043596.  So 

`global.phet.chipper.getCacheBusterArgs = undefined || function() { return ''; };`

was replaced with

`getCacheBusterArgs: function() { return ''; },`

**Comment by samreid** [comment]
This seems good, since chipper won't need anything for the cache buster args--it is for the browser requirejs non-built version.  Closing.
