### ISSUE TITLE
buggy call to deploySimulation

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#297]
I ran across this while working on #282.

In Gruntfile.js, I see 2 calls to `deploySimulation`:

```js
125 deploySimulation( grunt, grunt.option( 'devDeploy' ) );

136 deploySimulation( grunt, 'simian' );
```

The second call looks buggy. In deploySimulaton.js, the second parameter is documented as:

`@param {boolean} devDeploy deploy to development server instead of production if true`

**Comment by pixelzoom** [comment]
And in fact the 2nd arg is immediately converted to a boolean in deploySimulaton.js:

`41 devDeploy = !!devDeploy; // cast to boolean`

**Comment by aaronsamuel137** [comment]
Good catch @pixelzoom. This bug was a remnant from a past version where the server name was passed instead of a boolean.

Assigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
:+1: Closing.
