### ISSUE TITLE
missing --buildServer in help descriptions

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#299]
checkoutShas.js reads `grunt.option( 'buildServer' )`, but there is no indication of this in the help descriptions for tasks `checkout-shas` and `checkout-master`.

**Comment by pixelzoom** [comment]
For these tasks, `--buildServer` is reserved for use by build-server, and shouldn't be used by other clients. So I've documented it as such, and will not add `--buildServer` to the help for these tasks.

There's a semantic overloading problem here: `--buildServer` has 2 different meanings. For task deploy-dev, it mean "run the deploy on the build server". For tasks checkout-shas andcheckout-master, it means "this task was invoked by the build server".  Those are 2 very different things, and I recommend using separate options.

Assigning to @aaronsamuel137 to address.

**Comment by aaronsamuel137** [comment]
I've removed the build-server option from deploy-dev since it doesn't seem necessary. There is no reason why people would want to deploy dev from the build server instead of locally, and the build server already copies to spot on deploys anyway.

Assigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
:+1: Closing.
