### ISSUE TITLE
Licensing Info

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#30]
This ticket is to report on the status of licensing:

PhET HTML5 Simulations use several open source 3rd party libraries.  We have performed the following tasks to comply with the licensing terms:

1. In the published HTML or JavaScript file(s), license headers for each dependency are included.  This provides the following information:
    a. Which 3rd party libraries are included in the compiled simulation
    b. Copyright statement for each library
    c. Name of the license for each library
    d. Link to the project page for each library.
An example is provided here: http://phet.colorado.edu/sims/html/beers-law-lab/1.0.0/beers-law-lab.min.js

2. In our source code, most of the 3rd party dependencies have been moved to a single GitHub repository called sherpa: https://github.com/phetsims/sherpa . Libraries that must exist outside of sherpa (such as Font Awesome and almond) are annotated in sherpa.  Licenses for each 3rd party library are copied to the licenses directory.  Annotations as they appear in the compiled HTML or JavaScript file(s) appear in sherpa/info.js.

3. For simulation repositories, we have added a "Third Party Dependencies" section to the README.md file, which describes the list of dependencies and that the licenses can be found in the sherpa repository.  An example of this section is visible in PhET's Beer's Law Lab repository:
https://github.com/phetsims/beers-law-lab

4. When simulations are built using PhET's build system 'chipper' the license information will be automatically processed and added to the compiled HTML file.  Explicit 3rd party dependencies without license attribution will cause the build process to fail.  When new implicit dependencies (like Font Awesome) are added, annotations must be manually added to chipper's Gruntfile so that the licenses will be published as part of the build process.

**Comment by pixelzoom** [comment]
What work remains to be done on this issue? Or can this be closed?

**Comment by samreid** [comment]
I guess this was a "for your information" issue--looks safe to close.
