### ISSUE TITLE
global.fs in Gruntfile.js

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#300]
Address this in Gruntfile.js:

```js
/*
 * In Node, global is the global namespace object.
 * Register fs as a global so it can be accessed through the requirejs build system. Text.js plugin
 * may have a superior way to handle this but I (SR) couldn't get it working after a small amount of effort.
 */
global.fs = fs;
```

Either make it go away (unlikely, since code that needs it runs in requirejs mode), or move it to `global.phet.chipper.fs`.

**Comment by pixelzoom** [comment]
Related to https://github.com/phetsims/chipper/issues/285

**Comment by pixelzoom** [comment]
I moved global.js to global.phet.chipper.fs, and documented why it's necessary.  @samreid does this look acceptable? If so, please close.

**Comment by samreid** [comment]
Looks great, thanks.
