### ISSUE TITLE
factor getGruntConfig out of getBuildConfig

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#301]
Creating the grunt config is a large chunk of getBuildConfig. And it's only need in Gruntfile.js, to call `grunt.initConfig`.  So it makes sense to factor this out into a separate getGruntConfig.js file.

**Comment by pixelzoom** [comment]
Related to #232 (abstraction for build options).

**Comment by pixelzoom** [comment]
getBuildConfig was getting too big, and the grunt config seemed a bit out of place. I like this much better. Assigning to @samreid for review/comment. If it looks ok, please close.

**Comment by samreid** [comment]
Looks good, thanks.  Closing.
