### ISSUE TITLE
deployProduction.js method of determining repo name

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#303]
deployProduction.js gets the repository name like this:

```js
 // get the sim name from the current directory
  var directory = process.cwd();
  var directoryComponents = directory.split( ( /^win/.test( process.platform ) ) ? '\\' : '/' );
  var sim = directoryComponents[ directoryComponents.length - 1 ];
```

`package.json` is read elsewhere in this file. Whey not skip the platform-specific code and just use `pkg.name`?

**Comment by pixelzoom** [comment]
@aaronsamuel137 I did this, along with some change related to #285. Please review and see what you think.

**Comment by aaronsamuel137** [comment]
Looks good, thanks for doing this! Closing.

**Comment by pixelzoom** [comment]
Note that I did the same thing to deployDev.sh as part of #309.
