### ISSUE TITLE
verification of build directory in generateThumbnails.js

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#304]
In generateThumbnails.js:

```js
  if ( !grunt.file.exists( 'build' ) ) {
    grunt.file.mkdir( 'build' );
  }
```

This doesn't handle the case where 'build' exists, but is not a directory.  In that case, this should bail. See `grunt.file.isDir`.

**Comment by aaronsamuel137** [comment]
Assigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
:+1: Closing.
