### ISSUE TITLE
why are string files read with 'utf8' encoding?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#305]
Related to #285 (replacing fs with grunt.file)...

In afterRequirejsBuild.js, we had this:

`var fileContents = JSON.parse( fs.readFileSync( stringsFilename, 'utf8' ) );`

which I replaced with:

`var fileContents = grunt.file.readJSON( stringsFilename, { encoding: 'utf8' } );`

I'm not clear on why the strings files needs to be read with a specific encoding.  @jonathanolson can you clarify?

**Comment by jonathanolson** [comment]
In Node.js, it meant fs.readFileSync returned a string, not a Buffer (generally).

It looks like utf8 is the grunt.file default encoding, so we should be able to drop those sections.

**Comment by jonathanolson** [comment]
Assign back to me if I should do this, I don't have as much current testing experience to tell if it would break anything.

**Comment by pixelzoom** [comment]
OK, I'll investigate removing the 'utf' encoding from grunt.file.readJSON.

**Comment by pixelzoom** [comment]
`fs.readFile` and `fs.readFileSync` default to `encoding:null`, so we'll need to leave 'utf8' for those (I guess).

Inspecting all calls to `fs.readFile` and `fs.readFileSync`... I see that createMipmap.js calls `fs.readFile` without specifying 'utf8'.  That doesn't seem to be causing problems, just thought I'd note it.  @jonathanolson if that's OK, feel free to close this issue.

**Comment by jonathanolson** [comment]
> I see that createMipmap.js calls fs.readFile without specifying 'utf8'

Since it uses the Node.js Buffer object, not the string, from the documentation for fs.readFile:

> If no encoding is specified, then the raw buffer is returned.
