### ISSUE TITLE
remove grunt.file.exists from reportThirdParty.js

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#306]
Broken out from #285...

Where possible, remove grunt.file.exists from reportThirdParty.js.

I started to do this, but was unsure about what was going on in a few places.  For example:

```js
    // check for existence of the license file
    if ( !grunt.file.exists( LICENSES_DIRECTORY + library + '.txt' ) ) {
      grunt.log.error( 'license file not found for ' + library );
    }
```

I'm unclear why this check is necessary, because this file is never used.

**Comment by samreid** [comment]
We are no longer including the full license text in the reportThirdParty, so I think that line can be removed now.

**Comment by samreid** [comment]
I ran the report before and after removing the suspicious line and the contents of the resultant md file were identical.

**Comment by samreid** [comment]
Fixed above, closing.
