### ISSUE TITLE
encapsulate deploy-related config in getDeployConfig.js

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#309]
Broken out of #232.  This would be similar to getBuildConfig.js, but for deploy tasks.

**Comment by pixelzoom** [comment]
One difference from getBuildConfig.js is that getDeployCong.js doesn't have access to grunt. So it must use 'fs' to read config files, and it won't be reading `grunt.option`.

**Comment by pixelzoom** [comment]
getDeployCong.js will be used by:

build-server.js
deployDey.js
deployProduction.js

**Comment by pixelzoom** [comment]
Read from package.json:

```
name
version
phet.simTitleStringKey
```

Read from build-locale.json:

```
devUsername
devDeployServer
devDeployPath
buildServerAuthorizationCode
productionServerName
productionServerURL
```

**Comment by pixelzoom** [comment]
@aaronsamuel137 I made a good start on this, but (if you don't mind) I'm going to ask you to take it from here.  I wrote getDeployConfig.js, integrated it into deployDev.js and deployProductions.js, and tested `grunt deploy-dev --test`.  

Here's what remains to be done:

• Test `grunt deploy-production`. I didn't see a test mode for this, and wasn't sure if it was safe (or ready) to use.

• Integrate getDeployConfig.js into build-server.js.  You'll initialize it like this:
```js
var getDeployConfig = require( '../../../chipper/js/common/getDeployConfig' );
var deployConfig = getDeployConfig( fs );
```

Let me know if you have questions or run into any problems. Thanks.

**Comment by pixelzoom** [comment]
@aaronsamuel137 If you could also flesh out this documentation in the header comment, that would be great. Thanks.

```js
 * {string} devUsername
 * {string} devDeployServer
 * {string} devDeployPath
 * {string} productionServerName
 * {string} productionServerURL
```

**Comment by aaronsamuel137** [comment]
I've integrated this into the build server and added documentation. I also moved the optional email configuration fields to getDeployConfig.

Assigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
Question about `emailFrom`.  It's not clear from the doc why I'd want to use this. Is this similar to a "reply to" address? If so, maybe rename it `emailReplyTo`. Or document it better.

**Comment by aaronsamuel137** [comment]
Decided to remove emailFrom altogether since it is really not necessary. All emails are just sent from phethelp@colorado.edu now. It really makes no difference where they are sent from, since they are only going to be sent to phet developers and never replied to.

Assigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
> All emails are just sent from phethelp@colorado.edu now.

I'm still confused. If all emails are sent from phethelp@colorado.edu, what are `emailUsername` and `emailPassword` used for?  Some doc is probably in order.

A couple of typos:

> 32 smpt.colorado.edu
> 33 <person@exmaple.com>

**Comment by aaronsamuel137** [comment]
Updated the docs and fixed typos. Assigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
:+1: Closing.
