### ISSUE TITLE
reportThirdParty defines a new endsWith function

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#315]
While reviewing #116 I noticed reportThirdParty.js defines:

```js
  var endsWith = function( string, substring ) {
    return string.indexOf( substring ) === string.length - substring.length;
  };
```

I think this could just use string.prototype.endsWith function instead.

**Comment by pixelzoom** [comment]
If not `string.prototype.endsWith`, then this should be moved to ChipperStringUtils.js.

**Comment by samreid** [comment]
I tried running this in node:

```
console.log('hello'.endsWith('o'));
```

and it told me:
> Warning: Object hello has no method 'endsWith' Use --force to continue.

So let's move to ChipperStringUtils.js

**Comment by samreid** [comment]
Fixed above, closing.

**Comment by pixelzoom** [comment]
FYI... sting.endsWith is new in ES6, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/endsWith
