### ISSUE TITLE
is Rosetta using files created by build?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#318]
createHTMLFiles.js (factored out of afterRequirejsBuild.js) contains this chunk of code:

```js
// Write the string map, which may be used by translation utility for showing which strings are available for translation
var stringMapFilename = 'build/' + buildConfig.name + '_string-map.json';
grunt.log.debug( 'Writing string map to ', stringMapFilename );
grunt.file.write( stringMapFilename, JSON.stringify( stringMap[ fallbackLocale ], null, '\t' ) );
```

This creates a file like `john-travoltage_string-map.json`.

@jbphet or @aaronsamuel137, is Rosetta using this file?

**Comment by pixelzoom** [comment]
Also wondering about this bit in createHTMLFiles.js. Is repo_STRING_TEMPLATE.html used by Rosetta?

```js
  // Write the stringless template in case we want to use it with the translation addition process.
  // Skip it if only building one HTML.
  if ( buildConfig.locales.length > 1 ) {
    grunt.log.debug( 'Writing stringless HTML file' );
    grunt.file.write( 'build/' + buildConfig.name + '_STRING_TEMPLATE.html', html );
  }
```

**Comment by aaronsamuel137** [comment]
Neither of those files are currently being used by Rosetta

**Comment by jbphet** [comment]
Yes, what @aaronsamuel137 said.  Rosetta looks at the actual simulation to determine which strings need to be translated, not the string map file.  Does this fully answer your question @pixelzoom?

**Comment by pixelzoom** [comment]
Does anyone (@jbphet @aaronsamuel137 @jonathanolson @samreid) know who added the code that creates those files, and whether it's OK to delete that code?

**Comment by pixelzoom** [comment]
8/25/15 dev meeting: Vestigial code, delete it.
