### ISSUE TITLE
enforce convention for simTitleStringKey

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#319]
8/25/15 dev meeting consensus:

We're not sure how Rosetta and chipper will behave if a repository has no string file of its own.

We’ll make all sims follow the naming convention for simTitleStringKey (REPO/repo.name), no exceptions in package.json. All sims will therefore have a string file with at least one entry (REPO/repo.name).

These sims will need to be adjusted:

balloons-and-static-electricity
friction
ohms-law
resistance-in-a-wire
wave-on-a-string

**Comment by pixelzoom** [comment]
@jbphet Thanks for the offer to fix the babel files. But it was easier for me to just do it (global string replace) than to describe what to do.  That commit is https://github.com/phetsims/babel/commit/17afa02f1aa93979c435b99f1c588031d723d884.

If you don't mind, I will ask you to review.

**Comment by pixelzoom** [comment]
This change was announced to the Google Group at https://groups.google.com/d/msg/developing-interactive-simulations-in-html5/NEEtIEIVD0w/Ij4B1VpBBQAJ

**Comment by jbphet** [comment]
Thanks @pixelzoom for doing this.  It all looks good to me.  I also updated and verified that the Friction sim builds, which it does, and verified that the name appears correctly on the browser tab and in the about dialog, which it does.  Closing.
