### ISSUE TITLE
Determine which 3rd-party licenses should be included in the HTML deliverable

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#32]
Base64binary license annotation is added to all html files, even though base64binary is not used in all projects.  Can we automatically identify which sims use that, perhaps through requirejs dependency resolution?  Or add the file as a package.json preload dependency?

**Comment by pixelzoom** [comment]
It looks like this is begin done by the generateLicenseInfo task in chipper.Gruntfile. It appears to be reading dependencies from package.json.  If I've interpreted that correctly, please close this issue.

**Comment by samreid** [comment]
I'm seeing these lines in the chipper Gruntfile.js

```js
    /*
     * Add libraries that are not explicitly included by the sim.
     * Note: must have a . character for the parsing below TODO: Remove this restriction
     */
    sherpaDependencyPaths.push( 'almond-0.2.9.js' );
    sherpaDependencyPaths.push( 'pegjs.' );
    sherpaDependencyPaths.push( 'font-awesome.' );
    sherpaDependencyPaths.push( 'require-i18n.js' );
    sherpaDependencyPaths.push( 'text.js' );
    sherpaDependencyPaths.push( 'base64binary.js' );//TODO: Not all simulations use Vibe
```

So this still appears to be a problem.

**Comment by pixelzoom** [comment]
Lots of changes to chipper since this was last visited.  @samreid is this still an issue?

**Comment by samreid** [comment]
Yes, the lines 2 comments above still exist in modern chipper.  Couldn't those files be added to the new preload files @pixelzoom added recently?  Why are they handled separately?  Also, one issue here is that base64binary.js is being included in every sim, not just vibe sims.

**Comment by pixelzoom** [comment]
> Couldn't those files be added to the new preload files @pixelzoom added recently?

No, because these files are not being preloaded in the HTML deliverable. These are libraries that are not included in the deliverable.  But apparently their licensing info needs to be included. (I'm not totally clear on why that's the case.)

Perhaps we need something for licenses that is similar to preloads.  That is, a list of "common" licenses that need to be included in every sim, and a field in package.json that can be used to load sim-specific licenses (e.g. base64binary.js?)

**Comment by pixelzoom** [comment]
Discussed with @jonathanolson. These "dependencies" are all things that are used to build the HTML deliverable, they are not delivered.  If there's some requirement to include the license info for things used to build, then there should be many more of these (grunt, npm, jshint, uglify,...)  Unless including these is meeting some legal requirement, I recommend not including licenses for things that are not part of the deliverable.

Assigning to @ariel-phet to determine if there's a legal requirement to include licenses for tools use to build the HTML deliverable.

**Comment by samreid** [comment]
I see how https://github.com/phetsims/vibe/issues/15 could get us away from including base64binary, but I think all sims are using font awesome and hence require attribution provided by this line:

```js
sherpaDependencyPaths.push( 'font-awesome.' );
```

Also, doesn't some almond code get delivered?  Or is it all part of the build process and not in the deliverable?

**Comment by jonathanolson** [comment]
We set ```almond: true``` in the require.js grunt task, it includes its own version of it. Definitely doesn't use the one in sherpa.

If we're adding info for almond, we should be adding info for many other libraries and code that get included or partially included by the build.

**Comment by pixelzoom** [comment]
5/7/2015 developer meeting:
• I'll create something similar to set-preload for licenses. There will be a common licenses required by all sims. 
• @jbphet will investigate phetsims/vibe#15, whether base64binary.js is really needed

**Comment by pixelzoom** [comment]
base64binary.js was removed from vibe in https://github.com/phetsims/vibe/issues/15, and was also removed from generateLicenseText.js by @jbphet in https://github.com/phetsims/chipper/commit/792c4be95d723113c29066c709ac65fda1e0142e

**Comment by pixelzoom** [comment]
Changes complete.

Summary:

• generateLicenseText.js was renamed to setLicenseText.js, and the grunt task is now set-license-text. I renamed it because it sets global.phet.licenseText.

• As it did before, this task identifies 3rd-party libraries by looking at preload paths, and pulling out the ones that are coming from sherpa. 

• Licenses that are not preloads and are required by all sims are enumerated at line 30 of setLicenseText.js.  This set is currently very dubious. And I’d like to see it pulled out into JSON someday.

• Sims can specify additional licenses in package.json via the licenseKeys field. This is an array of strings, and the strings are keys in sherpa/info.js (which I’d also like to see as JSON someday.)

• If you build with —together, additional preloads are added to pkg.preload, and you’ll therefore get addition license info for those preloads.

Let me know if you see any issues. None of these changes affect the general public or PhET contractors, so I will not announce this change to the Google Group.

**Comment by pixelzoom** [comment]
So now that the build process aspect of this has been cleaned up, we can get back to the original topic of this issue - which 3rd-party licenses need to be included?  Clearly anything that is preloaded needs to be included, or anything sim-specific specific in package.json `licenseKeys` field. 

Here's the "common" set that's currently specified in setLicenseText.js:

```    
    'almond-0.2.9',
    'font-awesome',
    'pegjs',
    'require-i18n',
    'text-2.0.12'
```

What else?

**Comment by pixelzoom** [comment]
pegjs is a good example. It's a tool that was used to generate KITE.svgPath.js, not something we're delivering.  If we need to include it, then why don't we need to include licenses for everything in our toolchain?

**Comment by samreid** [comment]
KITE/parser/svgPath.js is delivered with our simulations (included by Shape.js), and svgPath.js contains code like:

```js
  function quote( s ) {
    /*
     * ECMA-262, 5th ed., 7.8.4: All characters may appear literally in a
     * string literal except for the closing quote character, backslash,
     * carriage return, line separator, paragraph separator, and line feed.
     * Any character may appear in the form of an escape sequence.
     *
     * For portability, we also escape escape all control and non-ASCII
     * characters. Note that "\0" and "\v" escape sequences are not used
     * because JSHint does not like the first and IE the second.
     */
    return '"' + s
        .replace( /\\/g, '\\\\' )  // backslash
        .replace( /"/g, '\\"' )    // closing quote character
        .replace( /\x08/g, '\\b' ) // backspace
        .replace( /\t/g, '\\t' )   // horizontal tab
        .replace( /\n/g, '\\n' )   // line feed
        .replace( /\f/g, '\\f' )   // form feed
        .replace( /\r/g, '\\r' )   // carriage return
        .replace( /[\x00-\x07\x0B\x0E-\x1F\x80-\uFFFF]/g, escape )
           + '"';
  }
```

pegjs/lib/compiler/passes/generate-javascript.js contains this code
```js
    /*
     * ECMA-262, 5th ed., 7.8.4: All characters may appear literally in a string
     * literal except for the closing quote character, backslash, carriage
     * return, line separator, paragraph separator, and line feed. Any character
     * may appear in the form of an escape sequence.
     *
     * For portability, we also escape all control and non-ASCII characters.
     * Note that "\0" and "\v" escape sequences are not used because JSHint does
     * not like the first and IE the second.
     */
    '          return s',
    '            .replace(/\\\\/g,   \'\\\\\\\\\')',   // backslash
    '            .replace(/"/g,    \'\\\\"\')',        // closing double quote
    '            .replace(/\\x08/g, \'\\\\b\')',       // backspace
    '            .replace(/\\t/g,   \'\\\\t\')',       // horizontal tab
    '            .replace(/\\n/g,   \'\\\\n\')',       // line feed
    '            .replace(/\\f/g,   \'\\\\f\')',       // form feed
    '            .replace(/\\r/g,   \'\\\\r\')',       // carriage return
    '            .replace(/[\\x00-\\x07\\x0B\\x0E\\x0F]/g, function(ch) { return \'\\\\x0\' + hex(ch); })',
    '            .replace(/[\\x10-\\x1F\\x80-\\xFF]/g,    function(ch) { return \'\\\\x\'  + hex(ch); })',
    '            .replace(/[\\u0100-\\u0FFF]/g,         function(ch) { return \'\\\\u0\' + hex(ch); })',
    '            .replace(/[\\u1000-\\uFFFF]/g,         function(ch) { return \'\\\\u\'  + hex(ch); });',
    '        }',
    '',
```

We are not redistributing all of pegjs in its entirety, but we are distributing code generated by pegjs and containing pegjs code (not necessarily restricted to the small function above).  I cannot find any license info on the pegjs site saying how the *generated code* is licensed, but it seems risky to assume that we don't need to provide attribution or track how this code is ending up in our deliverables.

For instance, let us imagine for the moment that pegjs was GPL.  In that case, could we relicense svgPath.js?  According to http://www.gnu.org/licenses/gpl-faq.html#WhatCaseIsOutputGPL svgPath.js would also have to be GPL because peg.js copied part of itself to the output.

I think it is our responsibility to keep track of what code we did not write that we are delivering or redistributing (through minified HTML files or on GitHub) and, where licensing is unclear, to check with @kathy-phet or our lawyers about how to handle it.  This will help protect us from becoming encumbered with troublesome/incompatible licensing issues.

**Comment by pixelzoom** [comment]
I can't do anything about this without some guidance from PhET management and/or legal.  In what cases does a 3rd-party license need to be embedded in the HTML deliverable for a PhET simulation? Assigning to @ariel-phet to get an answer.

**Comment by pixelzoom** [comment]
This issue should be resolved before PhET starts redeploying sims.

**Comment by pixelzoom** [comment]
See dev meeting notes at https://github.com/phetsims/sherpa/issues/22#issuecomment-106523323.

The decision by @kathy-phet is to include licenses only for libs whose code ends up in the html deliverable.

**Comment by pixelzoom** [comment]
The general question has been answered.  So now we need to make sure the proper entries are in sherpa/info.json, chipper/build.json and sim package.json.  I'm going to address that in phetsims/sherpa#22.  

Closing.
