### ISSUE TITLE
[build-server] Should the build-server be set up as a linux service?

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#320]
Right now, lots of things (like yotta's server and build-server) use nohup to run. When there are server restarts (happens occasionally), they need to be manually restarted.

Having OIT set these up with an init script would remove the need to remember to restart them.

Review for https://github.com/phetsims/chipper/issues/141

**Comment by aaronsamuel137** [comment]
Sent an email to OIT about this with a init script I want them to try. Waiting to hear back.

**Comment by aaronsamuel137** [comment]
I've worked with OIT to set this up. Closing.
