### ISSUE TITLE
[build-server] locales query parameter

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#321]
It's noted in the documentation that:
```
 * - locales - a list of locales to build [optional, defaults to all locales in babel]
```
and at first I wondered if it was comma-separated (like the grunt --locales option). Then saw:
```js
var locales = ( req.query[ LOCALES_KEY ] ) ? JSON.parse( decodeURIComponent( req.query[ LOCALES_KEY ] ) ) : '*';
```
and it looks like it's (probably) a JSON string array, e.g. [ 'en', 'es' ], but URLencoded. Is that correct, and could it be documented?

Review: https://github.com/phetsims/chipper/issues/141

**Comment by pixelzoom** [comment]
Should this use the same format as the chipper grunt option?  From getBuildConfig.js:

```
   * --locales=* : all locales from the repo's strings/ directory
   * --locales=fr : French
   * --locales=ar,fr,es : Arabic, French and Spanish (comma-separated locales)
```

**Comment by jonathanolson** [comment]
It looks like it uses ```'grunt build --brand=phet --lint=false --locales=' + locales.toString()```

**Comment by pixelzoom** [comment]
In general, it's not a good idea to rely on the behavior of `toString` for any non-integral type. In this case `toString` for an array just happens to put them in the desired (comma-separated) format. (And yes, I realize that some doc will say things like "The returned string will separate the elements in the array with commas.")

**Comment by aaronsamuel137** [comment]
Changed to a comma separated list. Also gave deploy-production a --locales option.

Assigning to @jonathanolson for review.

**Comment by jonathanolson** [comment]
Looks good, thanks.
