### ISSUE TITLE
bogus brand global?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#326]
We suspect that this is wrong/vestigial in initialize-globals.js:

`window.phet.chipper.brand = phet.chipper.getQueryParameter( 'brand' ) || 'adapted-from-phet';`

The brand is actually determined by Brand.id, and which Brand is loaded/included is specified via config.js.

This global needs to be correct for Google analytics.

**Comment by pixelzoom** [comment]
`window.phet.chipper.brand` is indeed bogus. I did a build with `grunt --brand=phet`.  Ran the built version, then here's what I see in the console:

```
> window.phet.chipper.brand
"adapted-from-phet"
```

**Comment by pixelzoom** [comment]
We also don't want to be able to run a version that was built for a specific brand to be run as another brand. The proper Brand.js file won't be bundled, etc.

**Comment by pixelzoom** [comment]
2 changes to fix this:

(1) Set `window.phet.chipper.brand` in the built html file.  This involved adding a new 'PHET_BRAND' token to sim.html.

(2) In initialize-globals.js, use `window.phet.chipper.brand` if it's already set. Ie:

 `window.phet.chipper.brand = window.phet.chipper.brand || phet.chipper.getQueryParameter( 'brand' ) || 'adapted-from-phet';`

If running a built version, `window.phet.chipper.brand` will already be set and can't be overridden with the query parameter.  If running in requirejs mode, the only way to set  `window.phet.chipper.brand` is via the query parameter.

@samreid would you mind reviewing?

**Comment by samreid** [comment]
The change sets above look great.  I tested the following configurations and saw the correct behavior noted below:
non-built + phet => phet
non-built + adapted-from-phet => adapted-from-phet
built --brand=phet + phet => phet
built --brand=phet + adapted-from-phet => phet

Closing.
