### ISSUE TITLE
HTML encode strings replaced in sim.html

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#327]
When replacing the SIM_TITLE token in sim.html, the title needs to be HTML encoded.

In sim.html:

`<title>SIM_TITLE</title>`

And in createHTMLFile.js:

```js
172 localeHTML = ChipperStringUtils.replaceFirst( localeHTML, 'SIM_TITLE',
      stringMap[ locale ][ buildConfig.simTitleStringKey ] + ' ' + buildConfig.version );

188 iframeTestHtml = ChipperStringUtils.replaceFirst( iframeTestHtml, 'SIM_TITLE',
      stringMap[ fallbackLocale ][ buildConfig.simTitleStringKey ] + ' ' + buildConfig.version + ' iframe test' );
```

And related, this is duplicated:

`stringMap[ locale ][ buildConfig.simTitleStringKey ] + ' ' + buildConfig.version`

**Comment by pixelzoom** [comment]
Hmmm... It's not just SIM_TITLE, there are other places where string should be HTML encoded before replacing token in sim.html.  Eg, HTML_HEADER.

**Comment by pixelzoom** [comment]
HTML_HEADER doesn't need to be escaped. Just SIM_TITLE and OG_TITLE.

**Comment by pixelzoom** [comment]
I added support for this using node-html-encoder (https://github.com/minchenkov/node-html-encoder). 

Encoded example from a build of john-travoltage_en.html:

```
<title>&#8234;John Travoltage&#8236; 1.2.0-dev.1</title>
```

@jonathanolson would you mind reviewing?

**Comment by pixelzoom** [comment]
@jonathanolson Raising priority of this for review. We don't want this to be wrong in sims that we're redeploying.

**Comment by jonathanolson** [comment]
Tested a few cases and reviewed the code. Looks good to me.
