### ISSUE TITLE
nb locale looks weird in LocaleInfo.js

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/chipper#329]
Noticed by @phet-steele when testing rosetta:

```js
nb: {
      name: 'Norwegian Bokmï¿½l',
      localizedName: 'Norwegian Bokmål',
      direction: 'ltr'
    },
```

I'm guessing the name should be something like "Norwegian Bokmal", but I'm not totally sure. As the file warns not to modify directly, I am going to assigning this to @jonathanolson.

**Comment by pixelzoom** [comment]
Looks identically weird in Rosetta's combo box.

**Comment by aaronsamuel137** [comment]
Yep, the combo box pulls directly from this file, that's how the issue was noticed.

**Comment by aaronsamuel137** [comment]
Another issue with this file: Avestan should be rtl not ltr.

@jonathanolson, why is there a warning not to modify this file? Is it okay to change these two things?

**Comment by jonathanolson** [comment]
There is a warning since it was generated from the Java version.

It may be best for the future to make changes directly to it, and never auto-generate it again.

**Comment by jonathanolson** [comment]
Added developer-meeting tag to discuss how this file should be handled.

**Comment by pixelzoom** [comment]
This pertains to localInfo.js, not LocalInfo.js.

@jonathanolson proposed:
> It may be best for the future to make changes directly to it, and never auto-generate it again.

Consensus was that this sounds good.  @aaronsamuel137 will remove the "auto-generated" doc, and rename LocalInfo.js to getLocalInfo.js.

**Comment by aaronsamuel137** [comment]
Updated localInfo.js in chipper.

Regarding changing the name of LocaleInfo.js in rosetta, this file currently exports 3 methods, it is not just a single method getLocalnfo. In that case, is it still advisable to change it?

**Comment by pixelzoom** [comment]
I'd like to hear from other developers (@jonathanolson?), because I'm not as familiar with the common patterns for node.  But my inclination would be add bundle everything in one object literal, then export that object literal (see for example ChipperConstants).

**Comment by pixelzoom** [comment]
... and in that case, LocalInfo.js would be an appropriate name.

**Comment by aaronsamuel137** [comment]
I did a little googling around about this, and didn't see a consistent best practice here. I decided for this file that putting all the exports in an object literal seems a little nicer.

Assigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
LocalInfo.js looks good. 'nb' locale now shows up as ""Norwegian Bokmal" in Rosetta combo box.

Closing.
