### ISSUE TITLE
Make sure all dependencies captured in dependencies.json

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#33]
dependencies.json is created based solely on the phetlibs in the package.json, which could be inaccurate (out of sync with the config.js file).  How can we make sure we capture all of the dependencies accurately without any (or while minimizing) false positives?

**Comment by pixelzoom** [comment]
At 2/24/15 dev meeting, @jonathanolson said:
> it would be good to automatically generate config.js from the package.json

**Comment by pixelzoom** [comment]
Thoughts on how we could generate config.js from the package.json? We need config.js when running in development mode, so it doesn't seem like something we can defer until build.

**Comment by jonathanolson** [comment]
We can have a node script that should be run after updating package.json, which creates/updates <sim>_en.html and js/<sim>-config.js.

**Comment by samreid** [comment]
Dependencies.json should contain the union of phet dependencies and phet-io dependencies (or generally for all brands).

**Comment by zepumph** [comment]
In https://github.com/phetsims/chipper/issues/567#issuecomment-346513337 I worked on summarizing that issue. There we will confirm the "one dependencies.json per branch" approach and then work here to discuss the details.

**Comment by jonathanolson** [comment]
This is implemented in the chipper 2.0 branch (has one dependencies.json per `build/${brand}` directory, they are all the same).

Slight "unclean" feeling in that it grabs the dependencies.json from the first brand (to copy to top-level and commit/push), but they really should be the same so the future risk is somewhat low.

**Comment by samreid** [comment]
> Slight "unclean" feeling in that it grabs the dependencies.json from the first brand (to copy to top-level and commit/push)

To clarify: the phet-io brand and adapted-from-phet brand now have the same dependencies?

**Comment by zepumph** [comment]
>To clarify: the phet-io brand and adapted-from-phet brand now have the same dependencies?

If so how would that work if you only built adapted-from-phet and didn't have phet-io checked out? I would assume that it would just be phet dependencies, with omitted phet-io repos.

This means that the adapted-from-phet/phet branded builds are different depending on if phet-io repos are checked out. This is alright with me, at least right now after thinking about it briefly, but I just wanted to make sure we all understand this.

**Comment by jonathanolson** [comment]
> To clarify: the phet-io brand and adapted-from-phet brand now have the same dependencies?

They create the same dependencies.json (assuming you have all the phet-io things checked out). If not checked out, you can't build phet-io (and warnings print out for anything you can build), and you can't deploy anything.

> If so how would that work if you only built adapted-from-phet and didn't have phet-io checked out? I would assume that it would just be phet dependencies, with omitted phet-io repos.

Yup.

**Comment by jonathanolson** [comment]
Confirmed that molecule-shapes (with the clone commands that are on its public README.md) will build with a standalone `grunt` (adapted-from-phet) with "reduced" dependencies, and also that a phet/phet-io build will outright fail with only those dependencies checked out (as it requires the private repos).

As that is as desired, I'm closing this issue.
