### ISSUE TITLE
duplication of direction formatting for strings

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#332]
The policy is to add directional format characters to all strings. That policy is duplicated in 2 places.  That is a maintenance issues, as demonstrated while working on #330.

In strings.js, called for requirejs mode:

```js
172 parsed[ stringKey ].value = ( isRTL ? '\u202b' : '\u202a' ) + parsed[ stringKey ].value + '\u202c'
```

In getStringMap.js, called in build mode:

```js
85 stringData.value = ( isRTL ? '\u202b' : '\u202a' ) + stringData.value + '\u202c';
```

Ideally this policy should be encapsulated in 1 source file.

**Comment by pixelzoom** [comment]
Related to #330, so I'll assign this to @aaronsamuel137 too.

**Comment by aaronsamuel137** [comment]
Moved to addDirectionalFormatting.js. Assigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
Perhaps better to add this to ChipperStringUtils, rather than creating another .js file?

**Comment by pixelzoom** [comment]
I think it would also be preferable to have `addDirectionalFormatting` return a modified string, rather than modifying its arguments.

**Comment by pixelzoom** [comment]
Also more general to take a {string}, rather than stringData as the first parameter.

Ie:

```js
var addDirectionalFormatting = function( str, isRTL ) {
    if ( str.length > 0 ) {
      return ( isRTL ? '\u202b' : '\u202a' ) + str + '\u202c';
    }
    else {
      return stringData.value
    }
  };
```

**Comment by aaronsamuel137** [comment]
I've made these changes, assigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
Inspected change set, looks good, closing.
