### ISSUE TITLE
Production deploy failure

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#335]
On OS X, on campus (no VPN needed), I'm getting the following error:
```
Running "deploy-production" task
Running command: scp -r build olsonjb@spot.colorado.edu:/htdocs/physics/phet/dev/html/molecule-shapes/1.1.1


Running command: git add dependencies.json


Running command: git commit --message "updated dependencies.json for 1.1.1 "
On branch 1.1
Your branch is up-to-date with 'origin/1.1'.

nothing to commit, working directory clean


Running command: git push

Everything up-to-date

deployed: http://www.colorado.edu/physics/phet/dev/html/molecule-shapes/1.1.1/molecule-shapes_en.html
error: deploy failed

Done, without errors.
```

**Comment by aaronsamuel137** [comment]
Looks like the reason for this failure was out of date repos on figaro. Needed to pull perennial (needed by newer versions of build-server) and chipper and npm install in both.

I went ahead and deployed MS 1.1.1 while debugging this. Take a look on the live site and make sure it all looks right.

I guess this raises the issue of how to keep the phet repos up to date on figaro in a more automated way.

**Comment by aaronsamuel137** [comment]
Should be fixed. Closing
