### ISSUE TITLE
applying 'stringTest' query parameter to patterns is problematic

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#336]
Noted while investigating an i18n layout issue in https://github.com/phetsims/hookes-law/issues/22, where this issue is cause false reports of layout issues, and possibly masking legitimate issues.

The `stringTest` query parameter is used to specify a string to use for i18n layout testing, or with `stringTest=double` it doubles the length of each string.

This is problematic when applied to MessageFormat patterns.  For example, consider '{0} m', used to display a value with units in meters.  

Current behavior: 
`stringTest=double` →  '{0} m : {0} m'
`stringTest=SomeExtremelyLongStringThatWouldLikelyBreakSomething` -> 'SomeExtremelyLongStringThatWouldLikelyBreakAnythingDidNot'

Better behavior:
`stringTest=double` →  '{0} m : m'
`stringTest=SomeExtremelyLongStringThatWouldLikelyBreakSomething` -> 
  '{0} SomeExtremelyLongStringThatWouldLikelyBreakAnythingDidNot'

Best behavior?...

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/hookes-law/issues/22#issuecomment-137892025, @samreid said:

> Perhaps stringTest=double is a better standard for testing?

**Comment by pixelzoom** [comment]
9/8/15 dev meeting:

• Use long-string test as a discovery tool to see if there are any obvious problems.
• Recommend that we don't require passing long-string test as part of regression testing.

@ariel-phet Does that seem like a reasonable approach?

**Comment by ariel-phet** [comment]
Seems reasonable to me

**Comment by pixelzoom** [comment]
Great. Closing.

**Comment by ariel-phet** [comment]
Reopening - Seems we should mention at developer meeting just to make sure everyone is on the same page.

**Comment by pixelzoom** [comment]
@ariel-phet We discussed it at Tuesday's developer meeting (see https://github.com/phetsims/chipper/issues/336#issuecomment-138624037), and it was still open mainly to make sure you were OK with the decision.  But if you want to discuss it again, that's fine.

**Comment by pixelzoom** [comment]
Reviewed at 9/10/15 dev meeting. Everyone's on the same page. Closing.
