### ISSUE TITLE
make test-server.js independent of where it's started

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#339]
test-server.js currently contains code like this:

```js
  var npmInstall = spawn( 'npm', [ 'install' ], {
    cwd: '../../' + simName
  } );
```
... which requires you to cd into chipper/test-server/ in order to run it.

It would be very easy (and convenient) to make this independent of where it's executed by using `__dirname`, which is the name of the directory that the currently-executing script resides in (see https://nodejs.org/docs/latest/api/globals.html#globals_dirname).

For example, for: 

% node /Users/cmalley/PhET/GitHub/chipper/test-server/test-server.js

`__dirname` is /Users/cmalley/PhET/GitHub/chipper/test-server/.

The above example from test-server.js would then be:

```js
  var npmInstall = spawn( 'npm', [ 'install' ], {
    cwd: __dirname + '/../../' + simName
  } );
```

Or better yet, factor out something like this:

```js
// root of your GitHub working copy
var rootDir = __dirname + '/../../';
```

**Comment by pixelzoom** [comment]
test-server is now independent of location, as described above.  At startup, it now prints both the port and root directory.

I tested running with an absolute path:

```
% node /Users/cmalley/PhET/GitHub/chipper/test-server/test-server.js
server running on port 45361 with root directory /Users/cmalley/PhET/GitHub/
...
```

With a relative path:

```
% cd /Users/cmalley/
% node PhET/GitHub/chipper/test-server/test-server.js
server running on port 45361 with root directory /Users/cmalley/PhET/GitHub/
...
% 
```

And from chipper/test-server/:

```
% cd /Users/cmalley/PhET/GitHub/chipper/test-server/
% node test-server.js
server running on port 45361 with root directory /Users/cmalley/PhET/GitHub/
...
% 
```

My active-runnables file contained 2 sims: acid-base-solutions, area-builder.  All tests completed successfully (3 green boxes) in all of the above scenarios.

I also reverted the README.md file, because it's no longer necessary to run from chipper/test-server/.

Assigning to @jbphet to verify.

**Comment by jbphet** [comment]
Commits look good, and I tested it from within chipper/test-server and from my git root dir and both worked on Windows.  Nicely done @pixelzoom - thanks.  Closing.
