### ISSUE TITLE
support subdirectories for media files

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#341]
In function-builder, I have a large number of image files, which I want to organize like this:

```
function-builder/images/
  functions/
  inputs/
```

I discovered that this is currently not supported by images.js and mipmap.js.  For example, this require statement:

`var disappearImage = require( 'mipmap!FUNCTION_BUILDER/functions/disappear.png' );`

results in this error:

```
Uncaught Error: Module name "image!FUNCTION_BUILDER/functions/disappear.png" has not been loaded yet for context: _
http://requirejs.org/docs/errors.html#notloaded
```

The offending code in images.js is at line 27:

```js
var imageName = name.substring( name.lastIndexOf( '/' ) );
var path = getProjectURL( name, parentRequire ) + 'images' + imageName;
```

The call to `name.lastIndexOf` should be `name.indexOf`.

There is a similar bug in mipmap.js, and audio.js.

We'll also need to check whether license reports support subdirectories.

**Comment by pixelzoom** [comment]
Fixed and tested audio.js, image.js and mipmap.js. 

Using function-builder... Tested the build process with a subdirectory in images/, and verified that it behaves as expected. Tested the resulting built html file to verify that it runs. 

Tested a few other sims with various media types in requirejs mode, no problems encountered.

@jonathanolson would you mind reviewing this? The commit above is pretty straightforward; changed `lastIndexOf` to `indexOf`, and renamed local var (e.g. `imageName`) to indicate that it's a path (e.g. `imagePath`).

**Comment by pixelzoom** [comment]
Looks like reportUnusedMedia.js needs fixing too. Back to me.

**Comment by pixelzoom** [comment]
reportUnusedMedia.js is fixed. There was support here for subdirectories, but it was apparently untested, because it was broken.

Back to @jonathanolson.

**Comment by jonathanolson** [comment]
Looks good to me.
