### ISSUE TITLE
[build-server] Assumptions about future chipper behavior/structure

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#342]
Right now it seems build-server and perennial are going to be run from the latest (stable) master. Once it checks out the SHAs needed for the build (which should be done from perennial, will have an issue for that soon), it will proceed to do the following actions:
1. grunt build ...
2. grunt generate-thumbnails

I'd prefer there to be one task that handles all of this, something like:
1. grunt build-for-server

So say in the future, we add a chipper task (grunt generate-X), and want it to be run after the build and generate-thumbnails tasks. The way the build-server calls chipper now, it would:
1. grunt build ...
2. grunt generate-thumbnails
3. Check to see if generate-X even in chipper by this point (but if so, run it).

It's worse if we don't WANT to run generate-thumbnails, etc. in the future. Basically, build-server is making assumptions about how future chipper wants to build sims. By having a single task meant for this purpose, current chipper's "build-for-server" can do "build" then "generate-thumbnails", and then in the future this could be changed without requiring any changes or complicated logic on the build server.

Thoughts?

**Comment by jonathanolson** [comment]
Review: https://github.com/phetsims/chipper/issues/141

**Comment by aaronsamuel137** [comment]
Seems like a good idea to me.

**Comment by aaronsamuel137** [comment]
This is actually an SR2015 issue, since it will require sims to have grunt build-for-server in chipper.

**Comment by aaronsamuel137** [comment]
It will require redeploying and maybe re-testing? Or we could just patch sims with the latest chipper?

Any opinions on whether or not we should do this?

**Comment by pixelzoom** [comment]
> This is actually an SR2015 issue, since it will require sims to have grunt build-for-server in chipper.

By "in chipper", do you mean in the snapshot of chipper indicated by dependencies.json?

**Comment by aaronsamuel137** [comment]
Yes, I do. build-server will fail trying to run ```grunt build-for-server``` if ```build-for-server``` doesn't exist as a grunt task in that snapshot of chipper.

**Comment by pixelzoom** [comment]
This is going to be a recurring problem as we add more responsibilities to the build tools. Currently, we are planning to use old build tools to maintain old versions of products. I sounds like that is a flawed plan.

**Comment by pixelzoom** [comment]
9/29/15 dev meeting:
• we've only redeployed 1 sim (Molecules Shapes, which requires redeploy anyway), so let's get this in now
• use new process only for sims that have been redeployed (S2015R)
• old process for maintenance release still works for English, if we need to patch an old sim

**Comment by aaronsamuel137** [comment]
I've finished the work on this issue. Assigning to @jonathanolson for review.

**Comment by aaronsamuel137** [comment]
Here's the commit for convenience (so you don't have to search above between the comments): https://github.com/phetsims/chipper/commit/f5c3986cea110068b27dd17a94de523cc6dcbc36

**Comment by jonathanolson** [comment]
Looks good, thanks!
