### ISSUE TITLE
[build-server] Alternative deployment support

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#343]
I'd either cut the commented out spot SCP code, or (preferably) implement https://github.com/phetsims/chipper/issues/145. We may long-term want build-server parameters that are able to note what should be done with the build simulation. Some options:
1. Do what it does now (create/update directory under htdocs with built simulation)
2. SCP to spot, skipping .htaccess/XML/notifying server/rosetta commits, etc.
3. Send it to an automated process to be tested (if we have continuous integration set up)

Thoughts?

**Comment by jonathanolson** [comment]
Review: https://github.com/phetsims/chipper/issues/141

**Comment by aaronsamuel137** [comment]
I've spent some time wrestling with this issue of spot deploys. It would be fairly easy to have build server deploy to spot at the same time as it does production deploys, but it comes with extra complications. We'll need to: make sure the permissions are right, make sure we're not overwriting files that we don't want to be, consider the case of translations, etc.

I guess I am fuzzy on what the spec we want to implement is here. Why do we need build-server to do spot deploys when we are already handling these locally?

Right now "grunt deploy-production" does a spot deploy first, then a call to build server. This seems cleaner to me than trying to do the spot deploy from build-server.

At one point, I had an option to do a spot deploy on build-server, but it seemed weird to have to ways of dev deploying, one way through a call to build-server and one way through grunt-deploy dev.

**Comment by jonathanolson** [comment]
> Why do we need build-server to do spot deploys when we are already handling these locally?

There was one point where building on Windows and building on OS X / Linux resulted in different behavior of the sim (one failed to have a CR LF, so had issues loading offline on IE). Having RCs go through the exact same build setup that production deployments do will ensure we will catch errors that would be seen from production deployments. Additionally if there is some configuration issue with build-server that causes it to build unusable sims, that wouldn't be caught by RCs.

I'm not concerned about pushing to spot on production deployments (the thing we care about is already live), or normal dev deployments (won't receive that level of testing), and I understand the addition in complexity.

Just thought I'd bring it up, in case we want to prevent "the RC was fine but the production deployment won't run" cases (I'd still lean towards it, but understand if we don't want to).

**Comment by aaronsamuel137** [comment]
If we give build-server an rc-deploy option, should we have it do a commit and push like grunt deploy-dev does? Or just the deployment to spot?

**Comment by jonathanolson** [comment]
That could potentially be left in client-side code? Probably easiest to keep the build-server checking out shas, not having to push to branches that are fully developer controlled.

**Comment by aaronsamuel137** [comment]
Great! I just added an build server parameter 'option', which can be set to 'rc' to do a spot deploy. We can change these names if you can think of better ones. I used 'option' instead of a boolean in case we want to add an another option later.

Do you think we should commit and push on the client side as part of grunt deploy-rc, or leave it up to the developer to do this?

**Comment by aaronsamuel137** [comment]
Added commitAndPush here. Assigning to @jonathanolson for review.

**Comment by jonathanolson** [comment]
Looks good, thanks.
