### ISSUE TITLE
[build-server] Top-level documentation updates

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#344]
Discrepancies I noted from the "What the Build Server Does" section:
- Note that perennial is pulled after chipper is pulled
- A note that perennial "grunt checkout-master-all" is done on failure would help
- Note about rosetta potential commit on new sims
- Note sim-only "git checkout sha" after the checkout-shas
- Update "grunt build" docs with ideally how it is used (it includes the brand option now)

Additionally, if the init script auto-start for the build-server is set up, updates will need to be done for that.

Besides those notes, the top-level documentation was awesome and very helpful. Thanks!

**Comment by jonathanolson** [comment]
Review: https://github.com/phetsims/chipper/issues/141

**Comment by aaronsamuel137** [comment]
Updated the docs, and will probably update once more after addressing #343.

**Comment by aaronsamuel137** [comment]
Finished docs. Assigning to @jonathanolson for review.

**Comment by jonathanolson** [comment]
Looks good, thanks!
