### ISSUE TITLE
[build-server] Consider separate location for build-server's chipper

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#345]
Correct me if I'm wrong, but I only see one location where chipper code is stored. It seems the build-server is run from /data/share/phet/phet-repos/chipper, and then it checks out older code SHAs to build older sims.

If there's an segfault or something in build-server while chipper is on an old SHA, presumably an OLD out-dated version of the build-server would be launched when it is started (!!!).

Also, it means that we always have to keep master stable for build-server, since the next time figaro/simian restart, it will probably use the latest master. Things could suddenly start erroring out.

If not done already, I'd recommend a separate checked out copy of repos where we can run build-server in peace (and where git pull only happens when we WANT to update the build-server that is running).

**Comment by jonathanolson** [comment]
Review: https://github.com/phetsims/chipper/issues/141

**Comment by jonathanolson** [comment]
Also as a potential consequence of this, should build-server be moved to a separate repo (since it's effectively handled somewhat independently?)

Adding developer-meeting tag to discuss (unfortunately after I filled the chipper issues page with review issues, sorry).

**Comment by aaronsamuel137** [comment]
I think it's a good idea to move it. Maybe to perennial? Or to it's own repository.

**Comment by jonathanolson** [comment]
> I think it's a good idea to move it. Maybe to perennial? Or to it's own repository.

I'm fine with either option. Would we ever want to have checked out SHAs be different for perennial and the build-server?

**Comment by aaronsamuel137** [comment]
>Would we ever want to have checked out SHAs be different for perennial and the build-server?

I don't think so. The idea of perennial is that it should always be on master, which I think should be true of build-server as well.

**Comment by pixelzoom** [comment]
9/29/15 dev meeting:
• new repo for build-server, or move it to perennial? consensus: move to perennial

**Comment by aaronsamuel137** [comment]
Moved to perennial. Assigning to @jonathanolson for review.

**Comment by jonathanolson** [comment]
Looks good, thanks!
