### ISSUE TITLE
[build-server] Recommend renaming cloneMissingRepos

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#346]
The pulling of chipper/perennial is also included, and threw me off a bit when reviewing.

Review: https://github.com/phetsims/chipper/issues/141

**Comment by aaronsamuel137** [comment]
Decided just to remove this method and put the steps in the build sequence. Assigning to @jonathanolson for review.

**Comment by jonathanolson** [comment]
Looks good, thanks!
