### ISSUE TITLE
[build-server] npm install for chipper/others

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#347]
I haven't seen a place where chipper has "npm install" (only the sim directory).

If dependencies are added (like the stuff for generating thumbnails), lack of "npm install" would cause a build failure, so I recommend it getting added.

**Comment by jonathanolson** [comment]
Review: https://github.com/phetsims/chipper/issues/141

**Comment by aaronsamuel137** [comment]
Added npm install for chipper and perennial. Assigning to @jonathanolson for review.

**Comment by jonathanolson** [comment]
Looks good, thanks.
