### ISSUE TITLE
[build-server] Ordering of npm install

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#348]
The current npm install on the sim directory is done after the previous task checked out master. This is a problem if the older SHA for chipper/the sim had different dependencies specified in the package.json.

I'd recommend only doing "npm install" after we are on the SHAs we want to build.

Review: https://github.com/phetsims/chipper/issues/141

**Comment by aaronsamuel137** [comment]
Moved npm install after checkout-shas. Assigning to @jonathanolson for review.

**Comment by jonathanolson** [comment]
Looks good, thanks!
