### ISSUE TITLE
[build-server] checkout-shas handling

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#349]
Right now build-server relies on "grunt checkout-shas" from master chipper, NOT perennial. I'd recommend switching this to use perennial (since it's also required to do so that we can check out the chipper SHA and THEN npm install for https://github.com/phetsims/chipper/issues/348).

Review: https://github.com/phetsims/chipper/issues/141

**Comment by aaronsamuel137** [comment]
Use perennial for check-out shas and tested on phet-dev. Assigning to @jonathanolson for review.

**Comment by jonathanolson** [comment]
Looks good, thanks!
