### ISSUE TITLE
[build-server] Why skip lint?

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#350]
I have a slight preference for not skipping the linting process in the build server, even though it will cause things to take a bit longer. It seems best to catch the grunt errors if they somehow crept through.

Thoughts?

Review: https://github.com/phetsims/chipper/issues/141

**Comment by pixelzoom** [comment]
+1 for not skipping lint.  Skipping lint should be done only if `--lint=false`.

**Comment by aaronsamuel137** [comment]
I'm fine to not skip lint. It will just a little longer and I was assuming it would've already been done if we got to this point. But I guess it would be an extra safe guard in case something has gone wrong with the build.

Regarding @pixelzoom's comment, I am not sure I follow. Currently, build server uses --lint=false.

**Comment by pixelzoom** [comment]
It was unclear whether this was issue was referring to linting the build-server code itself (during deploy of the build-server) or build-server skipping lint when building sims.   My comment about `--lint=false` was meant to indicate that anytime anything is built, it should also be linted, and lint should only be skipped if explicitly requested.

**Comment by aaronsamuel137** [comment]
Removed --lint=false.

Assigning to @jonathanolson for review.

**Comment by jonathanolson** [comment]
Looks good, thanks.
