### ISSUE TITLE
[build-server] Lodash version

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#351]
It looks like the build-server is requiring the specific sherpa version. Is there an advantage of that over doing:
```js
var _ = require( 'lodash-node' );
```

Review: https://github.com/phetsims/chipper/issues/141

**Comment by pixelzoom** [comment]
+1 for `require( 'lodash-node' )`.

**Comment by aaronsamuel137** [comment]
No advantage, just followed the pattern of using sherpa that I saw elsewhere in our code.

However it looks like lodash-node is depricated, so maybe we should use just lodash instead.

>The lodash-node package is deprecated in favor of lodash & lodash-compat ≥ v3.0.0.

https://www.npmjs.com/package/lodash-node

**Comment by jonathanolson** [comment]
> However it looks like lodash-node is depricated

If it's available now, 'lodash' or 'lodash-compat' would be preferred over 'lodash-node'.

**Comment by aaronsamuel137** [comment]
Using lodash package. Assigning to @jonathanolson for review.

**Comment by jonathanolson** [comment]
Looks good, thanks.
