### ISSUE TITLE
[build-server] 'server' var shadowed

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#353]
"var server" is used on the initialization for the email server, BUT THEN in the task queue is shadowed with another "var server" in the closure that deals with the server we are deploying to.

I'd recommend renaming so this shadowing of the outer "server" isn't present.

Review: https://github.com/phetsims/chipper/issues/141

**Comment by pixelzoom** [comment]
+1 for renaming.

**Comment by aaronsamuel137** [comment]
I renamed both of these vars so they have more descriptive names now too. Assigning to @jonathanolson for review.

**Comment by jonathanolson** [comment]
Looks good, thanks!
