### ISSUE TITLE
[build-server] Potentially send SHAs in failed build email?

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#354]
Sending SHAs in a failed build email might help debugging for developers who don't know where the build server log is (so they can reproduce on their own maybe?)

Also, where will the emails be set to send to (what is the emailTo value?)

Review: https://github.com/phetsims/chipper/issues/141

**Comment by aaronsamuel137** [comment]
I've made this change to the default fail email.

>Also, where will the emails be set to send to (what is the emailTo value?)

Right now this is configured in build-local.json. Currently, it just sends an email to me, but I can add others if they'd like.

Assigning to @jonathanolson for review.

**Comment by jonathanolson** [comment]
> Currently, it just sends an email to me, but I can add others if they'd like.

Feel free to add me if possible?

**Comment by aaronsamuel137** [comment]
Added you to the email list. Anyone else want to be added?

People can also add themselves by logging in to figaro as phet-admin and adding their email to ~/.phet/build-local.json. This raises the question of where should we store phet-admin credentials, etc.

I'll mark for developer meeting so we can discuss. Should be brief.
