### ISSUE TITLE
[build-server] Templates?

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#355]
I see express.js "template" code:
```js
app.set( 'views', __dirname + '/html/views' );
app.set( 'view engine', 'dot' );
app.engine( 'html', doT.__express );
```
but I don't see any /html/views folder or template usage. Is this vestigial?

Review: https://github.com/phetsims/chipper/issues/141

**Comment by aaronsamuel137** [comment]
Good catch. I've removed this and updated the comment. Assigning to @jonathanolson for review.

**Comment by jonathanolson** [comment]
Sounds good, thanks.
