### ISSUE TITLE
[build-server] Safety of query parameters

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#356]
First of all, it sounds safest to apply decodeURIComponent to all of the query parameters.

Second, there is query-parameter-derived information being passed as fragments to exec commands:
- simTitle, (in git commit message)
- repoName, (in git pull)
- repos[ simName ].sha (in git checkout)
- simName/version (in cp)

For this reason, I'd prefer some additional checking of the format of query parameters (or things we use, like the SHA) so that it can't contain arbitrary content. Otherwise, if someone obtains the authorization code, there's a good potential they could execute arbitrary shell commands.

For example, vetting simName/repoName (undercase letters and dashes), version (digits, dots, dashes, undercase letters), the SHA (hex digits) and using the simName instead of simTitle for the git commit message would make things a lot safer.

Review: https://github.com/phetsims/chipper/issues/141

**Comment by aaronsamuel137** [comment]
Added validation for query params. Assigning to @jonathanolson for review.

**Comment by aaronsamuel137** [comment]
Here's another commit where I added some return statements after abortBuild calls... might be a better way to do this. 34533224da7c32fd476ea5b22a18127e1b664a22

**Comment by jonathanolson** [comment]
Looks good, thanks!
