### ISSUE TITLE
[build-server] Version regex

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#357]
The version regular expression looks like it will fail for a few patterns that have more than single-digit numbers for all slots:
- "1.1.10" will be silently truncated to "1.1.1"
- "1.10.0" will fail to match at all
- "10.0.0" will be silently truncated to "0.0.0"

I'd recommend making the version regex handle multiple digits AND force it to start matching at the start of the string, AND force it to end (with an optional dash and content afterwards).

Review: https://github.com/phetsims/chipper/issues/141

**Comment by aaronsamuel137** [comment]
I've updated this regex. I had to move a few things around to get this to work, so that abortBuild can be called if the version is bad.

Assigning to @jonathanolson for review.

**Comment by jonathanolson** [comment]
Sweet, didn't learn about the non-capturing parenthesis "(?:" until now! Will need to rewrite a few things to use that in the future.

Looks good, thanks.
