### ISSUE TITLE
[build-server] Sim title key fallbacks

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#358]
It looks like simTitleStringKey is now required in package.json, so I would highly prefer if the fallbacks (simname.title and simname.name) be removed from the build-server.

Review: https://github.com/phetsims/chipper/issues/141

**Comment by pixelzoom** [comment]
`simTitleStringKey` is no longer specifiable in package.json, see https://github.com/phetsims/chipper/issues/340/.  All sims must conform to the repo.title convention, which is not a fallback.  The fallback is repo.name, which I understand will be removed once we've republished all sims that used that convention.

@jonathanolson ok to close?

**Comment by jonathanolson** [comment]
Ah sorry, saw the following and assumed (didn't realize that it was essentially removed, but still had a property of the same name):
```js
  var simTitle = stringMap[ ChipperConstants.FALLBACK_LOCALE ][ buildConfig.simTitleStringKey ];
  assert( simTitle, 'missing entry for sim title, key = ' + buildConfig.simTitleStringKey );
```

> simTitleStringKey is no longer specifiable in package.json, see #340.

So then build-server shouldn't try to access it.

> The fallback is repo.name, which I understand will be removed once we've republished all sims that used that convention.

Sounds best to make changes to the sims where this is the case, and remove it from build-server, right?

**Comment by pixelzoom** [comment]
> Sounds best to make changes to the sims where this is the case, and remove it from build-server, right?

I renamed in all sims in master. I'm not sure when why the fallback is needed. @aaronsamuel137 can you comment?

**Comment by aaronsamuel137** [comment]
Fallback no longer needed if we are doing maintenance releases of all sims published before the .title change.

Removed the fallback and the searching of package.json for the simTitleKey. 

Assigning to @jonathanolson for review.

**Comment by jonathanolson** [comment]
Looks good, thanks!
