### ISSUE TITLE
[build-server] simTitle intialization

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#359]
createTranslationsXML is currently creating simTitle, which is used later in addToRosetta. I'd prefer this would be more explicit, so that createTranslationsXML would call a callback including the simTitle e.g.:
```js
callback( simTitle )
```
then have the callback put it in a closure:
```js
createTranslationsXML( function( simTitle ) {
```
and pass it to the function that needs it:
```js
addToRosetta( simTitle function() {
```

That makes it very explicit that it's unsafe to reorder those two (I know it's specified in addToRosetta's docs, and I appreciate that), but also gets rid of the need for the global.

Thoughts?

Review: https://github.com/phetsims/chipper/issues/141

**Comment by aaronsamuel137** [comment]
Not sure if I followed exactly what you were suggesting, but I made an attempt at it. Assigning to @jonathanolson for review.

**Comment by jonathanolson** [comment]
Looks good, thanks!
