### ISSUE TITLE
[build-server] Locales included in XML

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#360]
It currently seems like a locale is not included in the XML file if it has no sim-specific babel's master OR if the HTML file isn't present in the versioned directory after copying.

It seems safe, since it prevents unpublished locales from being listed AND handles removal of translations from the website if the sim-specific translation file was removed from babel (while not removing the runnable file)

If we need to manually remove a translation (due to obscenity, etc.), it seems the procedure will require manually deleting it from the sim directories, and NOT relying on the build server to take care of this, correct?

Review: https://github.com/phetsims/chipper/issues/141

**Comment by aaronsamuel137** [comment]
That is correct. Perhaps we could think of a way of handling this from build-server? Not sure how though, unless we create an API for doing so. Any thoughts?

**Comment by jonathanolson** [comment]
> Any thoughts?

Up to you if you want to have a "remove-missing-locales" task, where it checks what is in babel and cleans the HTML sim directory.

I'd probably opt to not worry about it though.

**Comment by aaronsamuel137** [comment]
Not worrying about it for now sounds good. Closing
