### ISSUE TITLE
[build-server] Process for updating .htaccess files?

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#362]
Since the build-server overwrites .htaccess files, what is the process if we need to add things to the .htaccess files? Would probably require restarting the build-server after pulling changes, and THEN manually making the changes?

Review: https://github.com/phetsims/chipper/issues/141

**Comment by aaronsamuel137** [comment]
Yep, that's what it would require. Or you could restart build-server and rebuild sims, but that seems like it would take longer.

We could think about making an "updateHtaccess" API for build server if this need ever arises.

**Comment by jonathanolson** [comment]
Ok, can't think of a better way. Thanks.
