### ISSUE TITLE
[build-server] Download .htaccess files

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#363]
I don't see anything sim-specific or version-specific at all in them. Can the rewrite info be included in the main (other) .htaccess files, OR could we just have this in one .htaccess file at HTML_SIMS_DIRECTORY?

Review: https://github.com/phetsims/chipper/issues/141

**Comment by aaronsamuel137** [comment]
Good point. I've combined the .htaccess files. That way build-server takes care of it instead of having to manually create the file in HTML_SIMS_DIRECTORY. Did a little testing on phet-dev and seemed to work as expected combined.

Assigning to @jonathanolson for review.

**Comment by jonathanolson** [comment]
Looks good, thanks.
