### ISSUE TITLE
[build-server] addToRosetta with changed English sim title

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#364]
Not sure how much of an issue it would be, but if a published sim has a slight change to its English title, the build-server won't update rosetta's simInfoArray.json (since the entry for the sim already exists).

Is this worth a fix?

Review: https://github.com/phetsims/chipper/issues/141

**Comment by aaronsamuel137** [comment]
I think changes to the English title will actually create updates. Here is the code:

```js
        var newSim = true;
        for ( var i = 0; i < data.length; i++ ) {
          var simInfoObject = data[ i ];
          if ( simInfoObject.projectName && simInfoObject.projectName === simName ) {
            simInfoObject.simTitle = simTitle;
            simInfoObject.testUrl = testUrl;
            newSim = false;
          }
        }
        if ( newSim ) {
          data.push( {
            simTitle: simTitle,
            projectName: simName,
            testUrl: testUrl
          } );
        }
```

The title and url are updated every time if the sim already exists in the array. Does that seem right to you or is there something I am missing here?

**Comment by jonathanolson** [comment]
Sorry, I must have mis-read the code, sorry!
