### ISSUE TITLE
[build-server] Potentially verify checked out SHAs

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#366]
Any thoughts on whether it would be worth it to verify that the checked out SHAs match what we should be building? With writing out dependences.json from the SHAs passed in, it might be very difficult to track down bugs if somehow (unlikely) a sim is built with incorrect SHAs. It might be easy to check by creating another dependencies.json file and comparing (if the original written one from writeDependenciesFile isn't overwritten by the build process). Speaking of that, is it overwritten?

Review: https://github.com/phetsims/chipper/issues/141

**Comment by aaronsamuel137** [comment]
>Speaking of that, is it overwritten?

No it isn't, build-server writes it to it's own temporary build directory in writeDependenciesFile, and during the build it is written in the sim directory's build dir.

>Any thoughts on whether it would be worth it to verify that the checked out SHAs match what we should be building?

Not sure how this would happen unless grunt checkout-shas did the wrong thing. Are you suggesting this a test for grunt checkout-shas?

**Comment by jonathanolson** [comment]
> Not sure how this would happen unless grunt checkout-shas did the wrong thing. Are you suggesting this a test for grunt checkout-shas?

I guess I was thinking if checkout-shas managed to silently fail, but that seems unlikely. Have you tested to see what happens if checkout-shas has a git command fail, or if it runs into an error condition before that?

**Comment by aaronsamuel137** [comment]
If checkout-shas fails, the build will fail and abort as expected. I accidentally tested this today by creating an rc branch for chains locally and not pushing it. Build server tried to checkout the sha, but it didn't exist since it was never pushed to github. "git checkout [sha]" failed, and the build failed and sent an email.

I guess it could fail in another way? but not sure how. Anything else you want to do here?

**Comment by aaronsamuel137** [comment]
Assigning to @jonathanolson

**Comment by jonathanolson** [comment]
Nope, should be good. Thanks for the answers!
