### ISSUE TITLE
[build-server] pullMaster

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#367]
pullMaster uses an async pattern to execute the pulls in parallel, however if 2 or more of those pulls fail, the exec() calls from all of the failures will call parallel (or multiple) "grunt checkout-master-all" and WILL call taskCallback multiple times. Calling taskCallback multiple times seems bad, and hopefully doesn't skip ahead in the queue.

Maybe use execWithoutAbort (but have execWithoutAbort send back error conditions in the callback), and if ANY of the concurrent pulls failed out, call abortBuild once?

Review: https://github.com/phetsims/chipper/issues/141

**Comment by aaronsamuel137** [comment]
Implemented this. Assigning to @jonathanolson for review.

**Comment by jonathanolson** [comment]
```js
   var finished = _.after( Object.keys( reposCopy ).length + 1, function() {
     if ( _.any( errors ) ) {
       abortBuild( 'at least one repository failed to pull master' );
     }
     callback();
   } );
```

If there is an error, it calls abortBuild() and callback()? Would we only want to call abortBuild(), so we stop processing the failed task?

Otherwise, looks good to me.

**Comment by aaronsamuel137** [comment]
Good catch, that was supposed to have an else block. Assigning to @jonathanolson for review

**Comment by jonathanolson** [comment]
Looks good, thanks.
