### ISSUE TITLE
[build-server] Consolidate permissions bitmask constant

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#368]
436 (0664) is specified multiple times, and it would be nice to have it isolated into a global constant with documentation about it in just one place (presumably we always want just one permissions bitmask, and wouldn't vary them independently in the future).

Review: https://github.com/phetsims/chipper/issues/141

**Comment by pixelzoom** [comment]
If this is factored out, please refer to it as the `umask` (not bitmask) so that we know what it applied to by its name.

**Comment by aaronsamuel137** [comment]
Factored out as UMASK.

Assigning to @jonathanolson for review.

**Comment by jonathanolson** [comment]
Looks good, thanks.
