### ISSUE TITLE
[build-server] What to do if project synchronization fails

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#369]
Since the synchronization only happens if it's a local request (according to website code), should we send a failure email if the project synchronization fails? This might happen on 'deleted' translations, as noted in https://github.com/phetsims/chipper/issues/360.

Review: https://github.com/phetsims/chipper/issues/141

**Comment by aaronsamuel137** [comment]
Added email on synchronization failure. Assigning to @jonathanolson for review.

**Comment by jonathanolson** [comment]
Looks good, thanks!
