### ISSUE TITLE
[build-server] Does writeDependenciesFile failure stall the task queue?

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#371]
I noticed that if the writeFile for writeDependenciesFile fails, you return a winston.log( .. ). This prevents taskCallback from being called, which my intuition would say it stalls the task queue, preventing any further tasks from being processed.

Is that correct?

Review: https://github.com/phetsims/chipper/issues/141

**Comment by aaronsamuel137** [comment]
That's correct, good catch. I've fixed this. Assigning to @jonathanolson for review.

**Comment by jonathanolson** [comment]
Looks good, thanks.
