### ISSUE TITLE
factor out JSHint options

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#372]
At 10/1/15 developer meeting, @samreid demonstrated JSHint support in IntelliJ IDEA. He had to copy the contents of jshintOptions.js (JSHint config options) to a separate file in order to load it into IDEA.   Investigate factoring this out so that it can be used by both jshintOptions.js and IDEA.

Low priority.

**Comment by samreid** [comment]
I was going to dig into this, but converting to to JSON would mean leaving all of our nice comments behind (or using a clumsy way to turn the comments into JSON data).  @pixelzoom please advise.

**Comment by pixelzoom** [comment]
As noted in the first comment, "low priority". I don't have time (or interest) to work on this, and was merely the scribe for the dev meeting.

**Comment by pixelzoom** [comment]
Also wondering why you're working on this when we've also been discussing moving to ESLint?

**Comment by samreid** [comment]
Since it was your idea to move the file to json, I thought you might want to (a) be alerted to the issue about the comments and why it would not be straightforward to move to json and (b) maybe have a solution to that problem.  Indeed this issue remains at low priority and may be abandoned if we also abandon jshint.  Unassigning.

**Comment by pixelzoom** [comment]
My observation at the meeting was that it having the JSHint config duplicated in 2 places wasn't desirable. I seem to recall that a number of us proposed moving to JSON simultaneously. 

I agree that preserving the comments is desirable. If IDEA requires the options in JSON format, then I don't have another solution to propose. Perhaps one of the other developers has a proposal?

**Comment by samreid** [comment]
JSHint has been removed from our toolchain.  ESLint doesn't suffer from the problem--we can point directly to the .eslintrc file from IDEA.  Closing.
