### ISSUE TITLE
Kite, dot and scenery cannot run grunt eslint

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#373]
From #235 kite, dot, scenery have their own grunt files and hence cannot run `grunt eslint`.  We should fix this somehow.

**Comment by samreid** [comment]
I'm seeing this kind of config in the grunt files:

```js
    jshint: {
      all: [
        'Gruntfile.js', 'js/**/*.js', '../phet-core/js/**/*.js', '../assert/js/**/*.js'
      ],
      dot: [
        'js/**/*.js'
      ],
      // reference external JSHint options in jshintOptions.js
      options: require( '../chipper/js/grunt/jshintOptions' )
    }
```

Can @jonathanolson look into adding the desired grunt tasks to kite, dot, scenery?  If you don't have time let me know and I'll try to figure it out.

**Comment by samreid** [comment]
This also relates to the qunit tests--they will need to know how to run the new lint, I supposed. I noticed this for phet-core.

**Comment by samreid** [comment]
I'm seeing these files:
phet-core/tests/qunit/afterJSHintOptions.js
phet-core/tests/qunit/beforeJSHintOptions.js

That will probably need to be renamed after jshint is gone.

**Comment by samreid** [comment]
qunit has qhint for running jshint during qunit tests.  I don't know how we will do this with eslint.  @jonathanolson can we discuss it?

**Comment by samreid** [comment]
I'm going to leave qhint and jshint in sherpa/ until @jonathanolson & I figure out a plan for the tests.

**Comment by samreid** [comment]
axon is in the same boat here

**Comment by samreid** [comment]
and build a molecule

**Comment by jonathanolson** [comment]
As noted in the commits, I removed the browser-based linting from the unit tests. I'll plan on doing console lint tests AND browser unit tests for those repos.

I also updated them to point to eslint for their linting needs, and verified that the dot/kite/scenery builds are functional.

Anything else to do here?

**Comment by samreid** [comment]
I tested that qunit doesn't run lint tests and that grunt-lint works for kite.  Thanks, closing.
