### ISSUE TITLE
Next steps for ESLint

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#374]
From https://github.com/phetsims/chipper/issues/235#issuecomment-146011594

Next steps:
- [x] Integrate eslint into the main build process
- [x] Get rid of jshint
- [x] add .gitignore for the .eslint cache files
- [x] check through to see if there are other prebuilt rules we want/need
- [x] add documentation to the eslint files in chipper
- [x] generate a new 3rd party licenses document

**Comment by samreid** [comment]
I wrote this to our google group:

Moments ago I pushed a change to chipper so that it will use ESLint rather than JSHint for its linting process.  This has a good chance of identifying new lint issues, since our ESLint is catching issues that our JSHint let slide, such as using single quotes, LF vs CRFL, etc.

Please take it for a test drive and report any problems.

Best Regards,
Sam

**Comment by samreid** [comment]
I also realized that other groups using PhET software probably don't want to have to use the PhET copyright statement.  Not sure how to generalize this.

**Comment by samreid** [comment]
I removed as much jshint reference as possible, aside from the issue of scenery/dot/kite/axon and their gruntfiles and qhint tests.  So I'll check the checkbox above, and leave those repos to be done in #373

**Comment by samreid** [comment]
I would love to get the valid-jsdoc task running, but acid-base-solutions shows this many errors:

```
1368 problems (1368 errors, 0 warnings)
```

**Comment by pixelzoom** [comment]
Curious about what JSdoc errors are. Are the all the same type of error? Something specific to PhET's use of JSdoc?

**Comment by pixelzoom** [comment]
Curious about what the JSdoc errors are. Are they all the same type of error? Something specific to PhET's (mis)use of JSdoc?

**Comment by samreid** [comment]
Mostly
Missing JSDoc parameter description for ...

and
Missing JSDoc @returns for function

Some:
Expected JSDoc for 'x' but found 'callback' 

Some 
syntax error

**Comment by samreid** [comment]
You can add this line to your .eslintrc if you want to see all 1368 issues:
"valid-jsdoc": 2

**Comment by samreid** [comment]
See related issue https://github.com/phetsims/scenery-phet/issues/193

**Comment by pixelzoom** [comment]
I took this rule for a test drive, with acid-base-solutions.

The majority of the errors are in common code repos, not in acid-base-solutions. That's a little disconcerting. It indicates that common-code doc is not up to speed with PhET development guidelines.  I'd like to see JSdoc for *all* PhET common code brought up to standards. I realize that this will be time consuming - particularly for scenery/kite/dot. But I think it's important, especially for repositories where deep understanding of the code is limited to one team member.

Re specific types of errors... 

I don't think we should address errors of the forms `"missing parameter description"` and `"missing return description"`. I don't want to have to document the obvious, like: `@param {number} width - the width of the widget`.

I think we should address `"missing parameter type"`,  `"missing returns"`, `"expected X but found Y"` and syntax errors.

**Comment by jonathanolson** [comment]
The npm install'ed node_modules take up about another 2GB total after switching to ESLint, since it seems to have a lot of dependencies, and I've been having sporadic npm install failures.

Is it possible to set up eslint so the npm install for it is only needed in chipper?

**Comment by pixelzoom** [comment]
I also experienced some `npm install` failures. The problem cleared up after I did `rm -rf */node_modules` and ran `grunt-all.sh eslint`.  But it would be nice to investigate setting things up so that eslint (and other build-specific dependencies) are only needed in chipper.

**Comment by samreid** [comment]
I think everything in this issue is completed or moved elsewhere, closing.
