### ISSUE TITLE
Enforcing 120 max columns

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#376]
Our style guides says:

> Comments should not extend beyond 120 columns, and line breaks should be inserted for multi-line comments just before word that would extend beyond 120th column.  Code lines should also be broken up if they pass 120 columns.

However, when I run ESLint with:

```js
    "max-len": [
      2,
      // this many columns per line
      120,
      // tab counts for this many spaces
      4
    ]
```

We have 1543 line length problems reported for acid-base-solutions and its dependencies.  It would be great to have this rule enabled so that we can guarantee that all new code will be <=120 columns.  However, there would be a large up front price of fixing these pre-existing problems if we want to use this in our default rule set.  @pixelzoom @jbphet @jonathanolson @jessegreenberg @aaronsamuel137 what do you recommend?  I'm only flagging for 'developer-meeting' to keep this on our radar, hopefully we can decide how to proceed here in the comments.

**Comment by samreid** [comment]
By the way, I ran this on all-sims (which includes transitive dependencies) and the result was:

```
✖ 15904 problems (15904 errors, 0 warnings)
```

This doesn't include a few repos that aren't included, such as together.js.

**Comment by aaronsamuel137** [comment]
Looking at this in GAO, I noticed that some of the offending lines are require statements, for instance:

```js
  var SpaceObjectsPropertyCheckbox = require( 'GRAVITY_AND_ORBITS/gravity-and-orbits/view/right-control-panel/SpaceObjectsPropertyCheckbox' );
```

**Comment by aaronsamuel137** [comment]
Also, with regard to fixing lines such as this:

```js
    var sliderWithTicksNode = new VBox( { children: [ tickBox, slider ], spacing: -5, resize: false, top: smallLabel.bottom + 5 } );
```

Is there a convention for moving each option to its own line vs putting the whole string of options on the next line?

So this:

```js
    var sliderWithTicksNode = new VBox(
      { children: [ tickBox, slider ], spacing: -5, resize: false, top: smallLabel.bottom + 5 } );
```

vs:

```js
    var sliderWithTicksNode = new VBox( {
      children: [ tickBox, slider ],
      spacing: -5,
      resize: false,
      top: smallLabel.bottom + 5
    } );
```

**Comment by pixelzoom** [comment]
My 2¢: I'm not too concerned about strictly enforcing the 120-column guideline. When I run into the odd comment that's a little too long, I just reformat it and push. And if there's a chronic problem (like acid-base-solutions), it should be kicked back in code review.  That said... If it's the chronic offenders are few, then perhaps have ESLint auto-fix them.  If it's widespread, perhaps omit the ESLint rule.

**Comment by pixelzoom** [comment]
Re @aaronsamuel137 question about option...  My preference is:

```js
var sliderWithTicksNode = new VBox( {
      children: [ tickBox, slider ],
      spacing: -5,
      resize: false,
      top: smallLabel.bottom + 5
    } );
```

**Comment by pixelzoom** [comment]
Re `require` statements that exceed 120 columns... I would prefer not to line-break those.

**Comment by pixelzoom** [comment]
I took this for a test drive. `copyright.js` (the ESLint copyright rule) is failing, which is funny in a tragic sort of way.  So I guess maybe we should address this.

**Comment by samreid** [comment]
> And if there's a chronic problem (like acid-base-solutions), it should be kicked back in code review

The report of "We have 1543 line length problems reported for acid-base-solutions and its dependencies." includes scenery/dot/kite/joist/etc--it is not necessarily about acid-base solutions.

One option would be to turn on the max-len rule once during code review for new sims and address issues by hand.

**Comment by pixelzoom** [comment]
After inspecting a random selection of the errors (with my columns set correctly in IDEA :), I guess I'm not too concerned about this.  I'd be fine with using ESLint to check it during code review, and fixing errors on a case-by-case basis.  If there are cases where readability is improved by exceeding the line-limit by a char or two, then I'd be inclined to leave those alone.

**Comment by jonathanolson** [comment]
I'm not concerned about strict adherence to 120 chars.

**Comment by jbphet** [comment]
Me neither - I see it as a guideline to be followed in most cases, but one that can and should be broken if adhering to it makes the code less clear.

**Comment by pixelzoom** [comment]
I said:
>  I'd be fine with using ESLint to check it during code review, and fixing errors on a case-by-case basis.

But that doesn't address common code. And I don't want to have to address common-code errors of this type during code review of a sim.

**Comment by jbphet** [comment]
Consensus in 10/8/2015 dev meeting
+ won't be enforced by ESLint
+ for code review, we will turn this on and flag egregious violations, use ```grunt lint``` to avoid linting common code files
