### ISSUE TITLE
Ensure require statements match

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#377]
One custom rule we've needed is to check that the lhs and rhs of a require statement match.  I put together a quick rule in ESLint and saw offenders like these:

![image](https://cloud.githubusercontent.com/assets/679486/10331196/9b6bbd5c-6c90-11e5-9f8b-27dd51c38c63.png)

We should bring this rule to production and solve the issues it discovers.

**Comment by samreid** [comment]
I committed the rule and addressed issues it caught.  I also added a whitelist, but it may be even better to  just flag aberrant lines with // eslint-disable-line require-statement-match

**Comment by samreid** [comment]
I decided to bail on the whitelist and go with the comment above.

**Comment by pixelzoom** [comment]
Looks good to me. +1 for the "comment" approach.

**Comment by samreid** [comment]
This rule is integrated into our .eslintrc and used for development now, I don't know of any failures.  Closing.
