### ISSUE TITLE
build process identifies README.md as "unused images file"

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#384]
In function-builder, I added README.md files in the images subdirectories to describe how the image files were exported from the .ai asset file.  This causes reportUnusedMedia.js to complain that the README.md files are unused images.  For example:

```
% cd function-builder
% grunt
....
Running "after-requirejs-build" task
>> Unused images file: FUNCTION_BUILDER/functions/README.md
>> Unused images file: FUNCTION_BUILDER/inputs/README.md
```

This should be fixed. The easiest would be to change line 40 of reportUnusedMedia.js from this:

```if ( filename !== 'license.json' ) {```

to this:

```if ( filename !== 'license.json'  && filename !=== 'README.md' ) {```

@samreid Is that an acceptable fix?

**Comment by pixelzoom** [comment]
I implemented the above proposed fix.

**Comment by samreid** [comment]
Yes, I think this fix is good.
