### ISSUE TITLE
Shape.rect, Shape.ellipse should not be called with `new`

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#388]
During https://github.com/phetsims/bending-light/issues/251 code review for bending light, I turned on an eslint rule that helped me catch new calls to lowercase things, and it demonstrated that we are calling new Shape.rect(), new Shape,ellipse() in many places.  I ran a search for `new Shape.` across all our repos and saw 23 occurrences across sims such as area-builder, balancing-act, plinko-probability and even scenery-phet.  Here's a screenshot of the full list:

![image](https://cloud.githubusercontent.com/assets/679486/10493627/62da63b4-726f-11e5-9235-044b4301a06f.png)

I wasn't too keen on creating 13 separate issues for this problem, so I'm isolating it here in kite.  So to clarify, this is not a problem with kite but with the sims that are using Shape incorrectly.

**Comment by pixelzoom** [comment]
What is the eslint rule that you turned on?

**Comment by samreid** [comment]
I believe it is

```
    "new-cap": [
      2
    ],
```

which is commented out at the moment.

**Comment by pixelzoom** [comment]
> I wasn't too keen on creating 13 separate issues for this problem, so I'm isolating it here in kite.

This is chipper.

**Comment by samreid** [comment]
> This is chipper.

You are right, my apologies.  If others think query-replace "new Shape." with "Shape." will work sufficiently well, I can do that query replace, spot test and close the issue.

**Comment by pixelzoom** [comment]
Here's a screenshot showing which specific files this problem occurs in.  I recommend that each developer take care of fixing cases that they created.

![screenshot_79](https://cloud.githubusercontent.com/assets/3046552/10496583/c256c378-727e-11e5-8df7-87e12d5aaf63.png)

**Comment by pixelzoom** [comment]
... or as @samreid suggest, do a global replace of 'new Shape.' with 'Shape.'.

**Comment by pixelzoom** [comment]
+1 for global replace. But that's mainly because there's no code affected that's used by any of my sims :)

**Comment by samreid** [comment]
Reassigning to @samreid.  @samreid, do you have time to do the global replace that @pixelzoom suggested and spot test a few sims?

**Comment by samreid** [comment]
> do you have time to do the global replace that @pixelzoom suggested and spot test a few sims?

Sure, I'll take a look.

**Comment by pixelzoom** [comment]
> do you have time to do the global replace that @pixelzoom suggested

I'm afraid I can't take credit for this suggestion. It was @samreid's idea in https://github.com/phetsims/chipper/issues/388#issuecomment-148183842.

**Comment by samreid** [comment]
Just to clarify what should be done here before starting.

@samreid said:
> query-replace "new Shape." with "Shape."

@pixelzoom said:
> as @samreid suggested, do a global replace of 'new Shape.' with 'Shape.'.

It is unclear which is the preferred approach:
```js
Shape.rect(0,0,100,100); // method 1
new Shape().rect(0,0,100,100); // method 2
```

I also noticed some method don't have static adapters like that, for example arcPoint can be called on a shape instance but not on Shape.  @jonathanolson can you comment on what is preferable here?

**Comment by jonathanolson** [comment]
I'd recommend:
```js
Shape.rect( 0, 0, 100, 100 ); // method 1
```

Generally I'd only use the rect() instance method if one Shape is going to include multiple rectangles (which is possible).

**Comment by samreid** [comment]
Above I replaced `new Shape.` with `Shape.`.  I visually inspected each site and saw that the changes looked correct (and it wasn't using a broader Shape API), and I spot tested Balancing Act and Capacitor Lab and didn't see any issues.  I'll close, but if someone wants to reopen and review, please be my guest.
