### ISSUE TITLE
Pass query parameters through to the iframe

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#389]
@ariel-phet had an idea to pass the outer query parameters through to the iframe, to make it easy to use features like ?profiler, ?ea, ?stringTest, etc within the iframe version.

**Comment by samreid** [comment]
Fixed above, newly deployed versions should have the iframe query parameters pass through.  This won't compromise release-candidates in progress because the commit is isolated to the iframe-test.  This should be tested on a few more browsers before closing.

**Comment by samreid** [comment]
Seems good on os x firefox and os x safari as well as os x chrome. My only question was about whether I got the attributes right for scrolling.  I did it like so:

```js
  var frame = document.createElement( 'iframe' );

  var suffix = window.location.search || '';
  frame.setAttribute( 'src', 'PHET_SIM_URL' + suffix );
  frame.style.width = 600 + 'px';
  frame.style.height = 400 + 'px';
  frame.scrolling = 'no';
  frame.setAttribute( 'allowFullScreen', '' );

  document.body.appendChild( frame );
```

I'm fuzzy on what is an attribute vs setAttribute.  @jonathanolson can you make sure I got scrolling and allowFullScreen right?

**Comment by jonathanolson** [comment]
Seems preferable to create the iframe as before (in HTML), and just set the 'src' attribute in JS. But you should be able to set attributes (```frame.src = ```) or use setAttribute (```frame.setAttribute( 'src', ... )```).

**Comment by samreid** [comment]
That sounds much better @jonathanolson, I'll put it on my todo list.

**Comment by samreid** [comment]
Fixed as prescribed and tested that it still works well.  Closing.
