### ISSUE TITLE
Add build flag to skip mangling/uglify

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#393]
It should be possible to skip mangling names (but still run the sim through uglify), OR to skip uglify completely. Both are options I've needed to use for debugging in the last week (multiple times).

@samreid, @pixelzoom, @jbphet, @aaronsamuel137, @jessegreenberg, any objections or preferences on flag names?

I was thinking --no-mangle and --no-uglify.

**Comment by jonathanolson** [comment]
--no-mangle will also beautify the code for readability.

**Comment by jonathanolson** [comment]
@samreid, can you review/close?

**Comment by samreid** [comment]
The code review looks good, I still need to test each option on the command line.  The only thing I noticed during the code review is an inconsistency between how these options are named:
```
--lint=false : skip the lint sub-task
--no-mangle : skip the mangling portion of UglifyJS2, and beautify the output
--no-uglify : skip the UglifyJS2 step altogether
```

--lint=false was decided upon several months ago (with precedent from query parameters like ?webgl=false), --no-mangle & --no-uglify were decided upon recently.  We should choose a convention here and stick with it.  @jbphet @pixelzoom @jonathanolson @aaronsamuel137 @jessegreenberg @aaronsamuel137 may want to give input or be informed of the decision.

**Comment by samreid** [comment]
--no-mangle and --no-uglify outputs look great, so all that is left here is to decide on whether to change the names.  I'll flag for developer-meeting in case we cannot decide before then.

**Comment by jonathanolson** [comment]
I'm ok with --no-mangle or --mangle:false (same for uglify), I'll leave it up to others.

**Comment by pixelzoom** [comment]
+1 for `--mangle=false` and `--uglify=false`.

**Comment by samreid** [comment]
I like `--uglify=false` style because it matches the convention & style of other arguments passed to grunt.

**Comment by jbphet** [comment]
Another +1 for `--mangle=false` and `--uglify=false`.

**Comment by aaronsamuel137** [comment]
I like ```--mangle=false``` and ```--uglify=false``` too.

**Comment by jonathanolson** [comment]
Sounds like a consensus, removing developer-meeting tag and assigning to myself.

**Comment by jonathanolson** [comment]
Made the change, tested all 3 options. I presume it gets cast somehow to the boolean false value, as other usages tested for equality?

**Comment by samreid** [comment]
What do you think about simplifying 
```js
grunt.option( 'mangle' ) === false ? false : true
```
to read
```js
grunt.option( 'mangle' ) !== false
```

I wasn't sure if there is a simpler way to do this?

Same for beautify.

**Comment by jonathanolson** [comment]
Sounds good, was just in auto-replace mode.

**Comment by jonathanolson** [comment]
Done (and fixed ternaries where not needed).

**Comment by samreid** [comment]
Change set looks correct, closing.
