### ISSUE TITLE
what is the correct copyright rule for ESLint?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#394]
From chipper/eslint/rules/copyright.js, the PhET copyright rule for ESLint:

```js
if ( comments[ 0 ].value !== ' Copyright 2002-2015, University of Colorado Boulder' &&
    comments[ 0 ].value !== ' Copyright 2002-2014, University of Colorado Boulder' &&
    comments[ 0 ].value !== ' Copyright 2002-2013, University of Colorado Boulder' ) {
```

This code will need to be modified once a year. Can we use a regular expression here?

**Comment by pixelzoom** [comment]
@samreid Wondering why you hard-coded this. Did you investigate using a regular expression here and run into problems?

**Comment by samreid** [comment]
I'm unfamiliar with regex, this seemed fast/simple/clear/maintainable at the time.  If you recommend something else, go for it (or reassign to me and I will google for enough regex-kung-fu to solve this).

Also, if you go for a regex, let's use one that doesn't permit dates from the future.  When I turned this rule on I actually saw Copyright claims that extended beyond the year 20,000 AD.

**Comment by pixelzoom** [comment]
Here's the regular expression. It guarantees that the second year is >=2010, and won't require maintenance until 2100:

```js
 if ( ! /^ Copyright 2002-20[1-9]\d, University of Colorado Boulder$/.test( comments[ 0 ].value ) ) {
```

Assigning to @samreid for review.

**Comment by samreid** [comment]
The regex rule that was added permits dates from the future.  https://github.com/phetsims/chipper/issues/394#issuecomment-151637196 said:

> Also, if you go for a regex, let's use one that doesn't permit dates from the future. 

Are you recommending that we permit dates from the future?  Why not use `new Date().getFullYear()` or dates up until `new Date().getFullYear()`?

**Comment by pixelzoom** [comment]
> Why not use new Date().getFullYear() or dates up until new Date().getFullYear()?

Because it's nontrivial to write a regex verifying that the second year in the copyright is between `2002` and `new Date().getFullYear()`.  It's not as simple as `'[2002-2015]'`. I'm not going to spend time on that.  Let me know if you think editing copyright.js once a year is a better solution, and I'll revert.

**Comment by pixelzoom** [comment]
Btw... The years that I saw that were in the future were something like `20135`, which looked like someone tried to copy-paste-modify a comment line and blew it.

**Comment by pixelzoom** [comment]
Btw... The years that I saw that were in the future were something like `20135`, which looked like someone tried to copy-paste-modify a `2013` comment line and blew it.  And I think the more common problems are (1) copy-pasting older copyright comments without modifying them, and (2) not having a variable year in the IDEA copyright config. Testing for a date between 2002 and today won't catch either of these problems.

**Comment by samreid** [comment]
What about just checking that the copyright statement is an exact match for:

```js
' Copyright 2002-'+new Date().getFullYear()+', University of Colorado Boulder'
```

Won't that solve both of the problems (1) and (2) you described?  And it would only require a query-replace + commit once a year?

**Comment by pixelzoom** [comment]
I don't understand.  Are you proposing that all copyright statements must match the current year? That would require us to update all source files once a year.

I'm also wondering about why 2002 is the first year. The first date is supposed to be the date when the artifact came into existence.  None of the source code for HTML5 sims existed in 2002.  And I would expect source files to have various first years, depending on when they were created.

**Comment by pixelzoom** [comment]
Technically, the copyright configuration in IntelliJ IDEA should be:

`Copyright $today.year, University of Colorado Boulder`

eg:

`Copyright 2015, University of Colorado Boulder`

This is the copyright that is inserted for a new source file, and indicates the date that the file was created (i.e., first copyright).  When the file is modified, its copyright should be updated to a date range, where the first copyright year is maintained, and the second year is the date of most recent modification, e.g.:

`Copyright 2014-2015, University of Colorado Boulder`

**Comment by pixelzoom** [comment]
I've reverted changes to copyright.js.  After looking at this more closely, my opinion is that PhET's approach to copyright comments is generally incorrect (see above).  So I'm going to bow out of this.

**Comment by samreid** [comment]
In 2011, we were approved by our legal counsel to put 2002-NOW as the date range.  However, @pixelzoom and I are concerned that this may not be legally accurate.  Should we discuss with @kathy-phet?  It could take 2-4 hours to correctly check for the cases of single date vs date range and make sure the years are not too far in the past and not in the future, or we can continue with what we have now.

**Comment by pixelzoom** [comment]
In the email thread on legal counsel that @samreid forward to me, this link from UC Berkeley was cited as "an excellent summary of best practices for posting copyright notices in software": 

http://ipira.berkeley.edu/software-copyright-notice-and-disclaimer

It says:

The Berkley reference says:

> Copyright ©20xx [see Other Notes, below]. 
...
> Other Notes: Insert year software was first published as well as any subsequent years when a modified version is published. Publication is defined in the U.S. Copyright Act as the distribution or offer of distribution of a work to the public by sale or other transfer of ownership or by rental, lease, or lending. 

While I’m not a lawyer, I would interpret “first published” as “first pushed to GitHub”, since that’s when it is first made public. There is no software for PhET HTML5 sims that was “first published” in 2002.  And nowhere does it say that “first published” is equivalent to “year that the project started”. 

The Berkley reference also doesn’t recommend a date range.  But when a date range is used, all Google searches I’ve found indicate that (typically) the first year is the year of “first copyright”, and the second year is the year of most recent modification.

**Comment by pixelzoom** [comment]
In the email thread on legal counsel that @samreid forward to me, this link from UC Berkeley was cited as "an excellent summary of best practices for posting copyright notices in software": 

http://ipira.berkeley.edu/software-copyright-notice-and-disclaimer

It says:

The Berkley reference says:

> Copyright ©20xx [see Other Notes, below]. The Regents of the University of California (Regents).
...
> Other Notes: Insert year software was first published as well as any subsequent years when a modified version is published. Publication is defined in the U.S. Copyright Act as the distribution or offer of distribution of a work to the public by sale or other transfer of ownership or by rental, lease, or lending. 

While I’m not a lawyer, I would interpret “first published” as “first pushed to GitHub”, since that’s when it is first made public. There is no software for PhET HTML5 sims that was “first published” in 2002.  And nowhere does it say that “first published” is equivalent to “year that the project started”. 

When a date range is used, all Google searches I’ve found indicate that (typically) the first year is the year of “first copyright”, and the second year is the year of most recent modification.  This appears to be consistent with the UC Berkeley reference cited above.

**Comment by samreid** [comment]
Noted in conversation with @pixelzoom--creating and updating new files would be a much smaller task than dealing with the thousands of pre-existing files.

**Comment by samreid** [comment]
My recommendation: let's discuss/decide at a developer meeting what we prefer as a development team, then take our recommendation to @ariel-phet and @kathy-phet.

**Comment by pixelzoom** [comment]
Discussed at 10/29/15 dev meeting. Deferred for discussion with @kathy-phet at next status meeting.

**Comment by pixelzoom** [comment]
My recommendations:

(1) For new source files, follow the UC Berkeley recommendation for first-published year. Use this IntelliJ IDEA template when a source file is first created:

`Copyright $today.year, University of Colorado Boulder`

(2) For modified source files, follow the UC Berkeley recommendation. Manually modify the copyright comment to include a date range when the source file is modified. E.g.:

`// Copyright 2014-2015, University of Colorado Boulder`

(3) Don't bother to fix existing source files.

(4) For validating the copyright comment via ESLint, test for either of these 2 regular expressions, and punt on validating the years.

```js
/^ Copyright \d\d\d\d, University of Colorado Boulder$/
/^ Copyright \d\d\d\d-\d\d\d\d, University of Colorado Boulder$/
```

**Comment by pixelzoom** [comment]
My recommendations:

(1) For new source files, follow the UC Berkeley recommendation for first-published year. Use this IntelliJ IDEA template when a source file is first created:

`Copyright $today.year, University of Colorado Boulder`

E.g.:

`// Copyright 2015, University of Colorado Boulder`

(2) For modified source files, follow the UC Berkeley recommendation. Manually modify the copyright comment to include a date range when the source file is modified, and the year of modification differs from the year of first publication. E.g.:

`// Copyright 2014-2015, University of Colorado Boulder`

(3) For files ported from Java/Flash, maintain the existing year of first publication, and modify the year of most recent modification.  For example, if the Java source file copyright is:

`// Copyright 2004, University of Colorado Boulder`

and the file is ported to JavaScript in 2015, then the copyright in the .js file would be:

`// Copyright 2004-2015, University of Colorado Boulder`

(4) Don't bother to fix existing source files.

(5) For validating the copyright comment via ESLint (rule copyright.js), test for either of these 2 regular expressions, and punt on validating the years.

```js
/^ Copyright \d\d\d\d, University of Colorado Boulder$/
/^ Copyright \d\d\d\d-\d\d\d\d, University of Colorado Boulder$/
```

**Comment by samreid** [comment]
@pixelzoom recommendations above generally sound good.  Some minor modifications:

The Berkeley link says:

> Insert year software was first published as well as any subsequent years when a modified version is published.

I've seen this described as entering a year for each time a file is changed, and collapsing adjacent years with a dash, such as "2000, 2003, 2005-2006", see http://stackoverflow.com/questions/3487007/when-to-update-the-year-in-open-source-copyright-notice

It seems simple enough to update the regexes to test for `20/d/d` instead of `/d/d/d/d` as a basic sanity check.

I'm also not opposed to (perhaps somewhat in favor of?) basic date checks (nothing from before 2002 and nothing from the future), since it doesn't seem like too much effort and we know copy/paste errors and typos have occurred here in the past.

**Comment by pixelzoom** [comment]
> I've seen this described as entering a year for each time a file is changed, and collapsing adjacent years with a dash, such as "2000, 2003, 2005-2006

Not a fan of this format. I think it's less common and unnecessary. Is "collapsing adjacent years" something you made up? Hashing out the syntax (and getting it right in practice) seems like unnecessary work. Why is "2000, 2003, 2005-2006" preferable to "2000, 2003, 2005, 2006"? How do I know that "2000-2002" effectively means "2000, 2001, 2002"?   Frankly, I'll be amazed if we remember to update the last-modified year, never mind getting this more complicated form correct.

> I'm also not opposed to (perhaps somewhat in favor of?) basic date checks

As noted in https://github.com/phetsims/chipper/issues/394#issuecomment-151654178, previous copy-paste errors (that I've seen) have been of the form `20135` (a botched attempt to change `2013` to `2015`) which would be caught by the regex (too many digits). Imo the time to validate the dates is not time well spent. But if you feel it's important, go for it.

**Comment by samreid** [comment]
> Is "collapsing adjacent years" something you made up?

No, it's from the link I referenced.

> Imo the time to validate the dates is not time well spent.

If it can be completed in less than X minutes, it seems worthwhile.  My X is somewhere around 30 minutes.

**Comment by jbphet** [comment]
We need to discuss with Kathy at the 11/5/2015 dev meeting.  We'll start with the recommendation shown in comment https://github.com/phetsims/chipper/issues/394#issuecomment-152309608 above.

**Comment by samreid** [comment]
Here's the quote from Kathy Dessau:

**Comment by samreid** [comment]
After discussion today, @samreid is going to look into writing a script that automatically updates each file to put copyright START_DATE-END_DATE based on git history.  We can keep this script around and run it intermittently to make sure things are correct.

**Comment by samreid** [comment]
One question: is changing the copyright line a sufficiently substantive change that it warrants changing the copyright date?  If so, we can put END_DATE as 2015 for every file, which would be a nice simplification.

**Comment by pixelzoom** [comment]
Discussion with KP at status meeting:

• Use these, as appropriate:
`// Copyright <yearOfFrstPublication>-<yearOfLastModification>, University of Colorado Boulder`

• Ignore derivative "first publication" date from ported Java/Flash source files. 

• Write a script to (periodically) fix up copyright comments by getting years of creation and last modification from github.

**Comment by samreid** [comment]
At the meeting, we decided that a change to the copyright statement is not a substantive change, and we should use github dates for end date as well.

**Comment by samreid** [comment]
I'll go with this pair of regexes:

```js
var isDateRangeOK = /^ Copyright 20\d\d-20\d\d, University of Colorado Boulder$/.test( comments[ 0 ].value );
var isSingleDateOK = /^ Copyright 20\d\d, University of Colorado Boulder$/.test( comments[ 0 ].value );
```

If either is OK, then the rule will pass.  We will use a script to help us get the dates right.

**Comment by samreid** [comment]
I'll close this issue and create a separate issue for the "get the copyright dates right script".
