### ISSUE TITLE
Make .eslintcache files ignoreable

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#397]
Searching across multiple directories in IDEA is great, but we can't exclude the .eslintcache files from searches, and I often need to search across multiple file types (json + js and sometimes md or html or others)j  One possibility would be to write a filename pattern that hits what I need but skips .eslintcache files, but that could make it too easy to miss search results (if we forgot a suffix).  Another possibility would be to move all .eslintcache files somewhere else.  See also https://github.com/phetsims/chipper/issues/392

**Comment by samreid** [comment]
This may be solved by using cacheLocation as described in https://github.com/eslint/eslint/issues/4241

**Comment by samreid** [comment]
Oh it looks like that change in eslint was just made 2 days ago.  No idea when it will get released.  But it would be a good solution to our problem.

**Comment by samreid** [comment]
Looks it was just released today.  Things sure move fast around here:
http://eslint.org/blog/2015/10/eslint-v1.8.0-released/

**Comment by samreid** [comment]
Looks like grunt-eslint is still 2 weeks old at 17.3.1.  Do we need to wait for a new one of these in order to get the new eslint?

**Comment by samreid** [comment]
Above I made it so that all of the eslintcache files will be located under chipper/eslint/cache, which can be easily ignored.  @jbphet @jonathanolson @jessegreenberg @pixelzoom @aaronsamuel137 please feel free to remove any .eslintcache clutter files you have.  Note this uses an option that is deprecated in eslint 1.8 and will be removed in 2.0.  Hopefully by then a new grunt-eslint can save us.

**Comment by pixelzoom** [comment]
Reopening. Shouldn't .eslintcache also be removed from all .gitignore files?

**Comment by pixelzoom** [comment]
There seems to be a problem with this approach.  I did `grunt lint-all` for hookes-law, and I see `chipper/eslint/cache/hookes-law.eslintcache` was created, and it appears to contain the cache results for its dependencies. How are the cached results for common repos accessed when linting other repos?  With the previous approach, I only needed to lint (for example) scenery once.  This was a significant speedup when doing (for example) `grunt-all.sh build`.  Or perhaps I misunderstood how caching worked with the previous approach.

**Comment by pixelzoom** [comment]
I inspected my old .eslintcache files (e.g., hookes-law/.eslintcache) and they also contain results for dependencies.  So I guess I was mistaken about how caching worked, and common repos are being repeatedly linted.  Perhaps we should investigate how to make this repeated linting unnecessary?

**Comment by samreid** [comment]
> So I guess I was mistaken about how caching worked, and common repos were (and are) being repeatedly linted. Perhaps we should investigate how to make this repeated linting unnecessary?

Let's keep track of what gets linted in the following example, assuming starting with an empty cache
```
cd bending-light
grunt // lints every single file in sim code, common code, chipper, etc
grunt // nothing linted, hooray!
edit a single file in a common repo or sim repo
grunt // lints the single file that changed, hooray!

cd ../hookes-law
grunt // lints every single file in sim code, common code, chipper, etc
grunt // nothing linted, hooray!
edit a single file in a common repo
grunt // lints the single file that changed, hooray!

cd ../bending-light
grunt // lints the single file that changed in the common repo, a few lines above.  Hooray!
```

etc. In my opinion this addresses the common cases of repeated linting sufficiently well and it is not worth the effort and complexity to create a separate lint command and cache file for each dependency.

**Comment by pixelzoom** [comment]
@samreid 
> In my opinion this addresses the common cases of repeated linting sufficiently well and it is not worth the effort and complexity to create a separate lint command and cache file for each dependency.

OK. Just means that test-server will take a little longer because of repeatedly linting any common files that have changed.

**Comment by pixelzoom** [comment]
Back to @samreid to remove .eslintcache from .gitignore files, which is why this was reopened in https://github.com/phetsims/chipper/issues/397#issuecomment-152740697.

**Comment by aaronsamuel137** [comment]
In https://github.com/phetsims/molecules-and-light/issues/128 I discovered that an accidentally checked in .eslintcache file will cause build failures. Not sure if this warrants leaving it in the .gitignore files or not, but wanted to mention it as something we need to avoid.

**Comment by samreid** [comment]
I removed the .eslintcache entries from .gitignore in many repos above.

I think it may eventually be worthwhile to investigate caching each each repo independently--though it is at the moment unclear how to do so with the existing grunt task structure.  I'll create a separate issue for that, which can be prioritized separately.  @pixelzoom anything else to do for this issue?

**Comment by pixelzoom** [comment]
:-1: Closing.
