### ISSUE TITLE
Bad extension of options

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#399]
In https://github.com/phetsims/scenery-phet/issues/200 @pixelzoom pointed out this problem:

Here's the problem:

```js
    this.options = _.extend( {
    ...
    }, options );
```

Now if someone accidentally uses `options` instead of `this.options` in the constructor, they may get the wrong value.  The preferred approach (in general) is:

```js
    options = _.extend( {
    ...
    }, options );
    this.options = options; // @private
```

After reviewing https://github.com/phetsims/scenery-phet/issues/200 I identified 11 more occurrences across our codebases with the text `this.options = _.extend`.  Shall we fix these cases as well?

**Comment by pixelzoom** [comment]
+1 to fix.

**Comment by pixelzoom** [comment]
I see 23 occurrences of `this.options = _.extend`, see screenshot below.

![screenshot_90](https://cloud.githubusercontent.com/assets/3046552/10952980/ae01b7ea-8302-11e5-9c51-e7de394588e5.png)

**Comment by pixelzoom** [comment]
Ah, sorry, should ignore pesky `node_modules` in above search.

**Comment by pixelzoom** [comment]
I need something mindless to do this afternoon, so I'll knock a few of these off.

**Comment by pixelzoom** [comment]
I fixed all of these. Assigning to @jonathanolson to review the 3 scenery changes made in https://github.com/phetsims/chipper/issues/399.

**Comment by jonathanolson** [comment]
Looks good to me, thanks!
