### ISSUE TITLE
String keys should be camel case?

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#401]
String searchability would be a bit easier if the keys in the JSON files matched the var names in the file.  Since we have decided on a camel case rule for the var names in https://github.com/phetsims/chipper/issues/396 perhaps we should go one step further and make the key names in the JSON files have this same convention?  Opinions from @pixelzoom @jonathanolson @jbphet @aaronsamuel137 @jessegreenberg?

**Comment by pixelzoom** [comment]
Let's discuss at developer meeting. Changing keys has repercussions, especially if we do it after having deployed (and translated) sims.

**Comment by pixelzoom** [comment]
Examples in common code:

Similar problem in scenery-phet for these keys:

// joist
HomeButton.name
PhetButton.name

// scenery-phet
FaceWithPointsNode.pattern_0sign_1points
NumberControl.pattern_0value_1units
WavelengthSlider.pattern_0wavelength_1units
ResetAllButton.name
SoundToggleButton.name

**Comment by jbphet** [comment]
Consensus from 11/5/2015 design meeting: Leave these strings as they are, ESLint has been modified to tolerate this, and it is okay to use this pattern (TypeName.stringName) going forward for common code.
