### ISSUE TITLE
Create a script that will set the correct dates in copyright comments

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#403]
From #394:

Summary of discussion with KP at status meeting, her decision:

• Use this when a file is created:
`// Copyright <yearOfCreation>, University of Colorado Boulder`

• Use this when a file is modified, and the year of modification differs from the year that the file was created:
`// Copyright <yearOfCreation>-<yearOfLastModification>, University of Colorado Boulder`

• Ignore derivative "first publication" date from ported Java/Flash source files. 

• Write a script to (periodically) fix up copyright comments by getting years of creation and last modification from github.

**Comment by samreid** [comment]
I added the script above, ran it on Beer's Law Lab and manually spot checked.  Still to do:

1. Run the script for every active-repo and commit the results
2. Make sure the script works properly on windows
3. Determine if there are other directories or file types that should be processed here.  The script above is currently solving the biggest problem, all files under repo/js directories, but we could extend it to handle  other file types and source roots (such as test source roots) if needed.
4. Make sure files are actually *.js.  If a .DS_STORE or or *.txt something snuck in, then it would cause problems.

**Comment by samreid** [comment]
@jbphet tested this in his machine and all seems good.  We noticed one quirk of this script though.  Committing a change to the copyright statement appears in the git log as a commit, and hence has the potential to change the "last modified" date.  Ideally we would just want to look for substantive changes, ignoring changes to the copyright line itself.  However, this seems technically much more difficult so @jbphet & I decided to proceed with the script as it is, since this is a major improvement over the previous status quo.

**Comment by samreid** [comment]
This means I will run the script twice on every source file in js directories, and all end dates will be set to 2015, even if the last change before today was an earlier year.  But this issue won't occur in future years.

**Comment by samreid** [comment]
@pixelzoom is there a code freeze on Beer's Law Lab or can I proceed here?

**Comment by pixelzoom** [comment]
Proceed.

**Comment by samreid** [comment]
Thanks, will do.

**Comment by samreid** [comment]
To run this script, I'm going to change grunt-all.sh to point to active-repos and run `grunt-all.sh update-copyright-dates` three times.  The first time I expect to see changes in every JS file.  The second time I expect to see changes in all files that *haven't* been otherwise updated yet in 2015.  The third time I expect to see no changes since the rule should be idempotent after n=2.

I think I should spot check the results after each batch, and commit, using a different commit message for the 2nd batch in case we decide to try to handle files not otherwise modified in 2015 differently.

**Comment by samreid** [comment]
Brace yourself for commits to all of our repo/js/*.js files.

**Comment by samreid** [comment]
My script is failing in dot because it has a different gruntfile.

**Comment by samreid** [comment]
As the script is running, I'm realizing that we need to make sure each modified file begins with a line comment copyright.  If it is a block comment, for example, and the first line got replaced with a line comment, then the file would have syntax errors.

**Comment by samreid** [comment]
I'll have to address the comment above before committing, but for the record and comparison later, there are 2,682 files modified by this in the first pass.

**Comment by samreid** [comment]
I'm seeing `FIRST LINE WAS NOT COPYRIGHT` in masses-and-springs, optics-lab and one file in shred.  These will be skipped by the script and must be handled manually.

**Comment by samreid** [comment]
I ran the script 1st pass, skipping the problematic files identified in the above comment, spot checked several files, compared a few files to git history to make sure dates are correct and I haven't seen any issues.  So I'll commit the 1st pass.

**Comment by samreid** [comment]
166 files hit in the 2nd pass, distributed like this:

![image](https://cloud.githubusercontent.com/assets/679486/11013411/19c7ecf6-84ca-11e5-8290-6f04cd593718.png)

**Comment by samreid** [comment]
The majority of the work is committed above.  Remaining work:
1. Address dot/kite/scenery

In my opinion, the following can be deferred:
1. addressing optics-lab & masses-and-springs
2. addressing js code outside of js/ such as test code, can be done manually at lower priority

**Comment by samreid** [comment]
I updated scenery/kite/dot above by hacking the script to point to that directory and use cwd in childprocess.exec.  @jbphet do you recommend any further work here at the moment?

**Comment by jbphet** [comment]
@samreid - in the previous comment you said:
>I updated scenery/kite/dot above by hacking the script to point to that directory and use cwd in childprocess.exec.

Will this hack need to be done every time the copyright needs updating?

**Comment by samreid** [comment]
There are many options:

1. Extend chipper to be able to build scenery/kite/dot, then they will automatically gain this functionality
2. Copy paste this rule into scenery/kite/dot
3. Make a way for scenery/kite/dot builds to reference this rule in chipper
4. Ignore copyright statements in scenery/kite/dot or update them manually or through a hack

I am in favor of (1) but I do not know the time or complexity that will be required to do so.

**Comment by jbphet** [comment]
It seems to me that the final solution should not omit these three repos, so I would prefer to avoid (4).  Assigning to @jonathanolson for his input on how to bring scenery, dot, and kite into the fold.

**Comment by pixelzoom** [comment]
+1 for option 1, as described in https://github.com/phetsims/chipper/issues/403#issuecomment-155113719.  For this and other difference, scenery/dot/kite should conform to PhET conventions, unless there's a *really* good reason not to.

**Comment by jonathanolson** [comment]
I'm fine with option 1 (seems like a lot of work to make chipper that flexible though), but would prefer an option where we didn't have to have that gruntfile dependency to do this task (and would keep dot/kite/scenery build logic more separate from sim build logic). Using grunt seems fine, but requiring top-level gruntfiles seems weird to me.

Things also missing: yotta, perennial, phetmarks, brand, phet-metacog, installer-builder, chronicle, datamite, slater, etc. I'd like an approach that covers these repos too.

**Comment by samreid** [comment]
Grunt extensions or plugins sounds ideal here.  Perhaps (somehow?) scenery could use chipper by default, then add its own grunt tasks in dynamically somehow.

**Comment by jonathanolson** [comment]
Since chipper's gruntfile was built for sim-like things, it sounds like a lot of development to have special cases for non-sim-like things.

**Comment by pixelzoom** [comment]
@samreid can this be closed?  What remains to be done?

**Comment by samreid** [comment]
I'm going to run the script `grunt-all.sh update-copyright-dates` again and add a note in my calendar to run it every year.

I ran the script and spot checked the results and it seems legit, so I'll commit to many repos shortly.  I can see that kite/dot/scenery are still not updating, but we can create another issue for them.

**Comment by samreid** [comment]
I ran the script and committed/pushed changes for many repos.  I don't think we need to spend more time on this for kite/dot/scenery at the moment.  I put a note in my calendar to run this again next year.
