### ISSUE TITLE
"clean" option to "grunt create-sim" is broken

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#407]
The `--clean=true` option is supposed to give you the option to remove the directory. It currently aborts regardless of the value.

For example, when the repo already exists, all of these "Abort due to warnings":

```
% grunt create-sim --name="..." --author="..." --title="..."
% grunt create-sim -name="..." --author="..." --title="..." --clean=true
% grunt create-sim -name="..." --author="..." --title="..." --clean=false
```

This finishes with "Done with warnings", but doesn't create the files:

```
% grunt create-sim --name="..." --author="..." --title="..." --force
```

**Comment by pixelzoom** [comment]
Here's the relevant code in createSim.js:

```js
if ( grunt.file.exists( destinationPath ) ) {
    if ( clean ) {
      grunt.log.writeln( 'Cleaning ' + destinationPath );
      grunt.file.delete( destinationPath, { force: true } ); // delete won't operate outside of current working dir unless forced
    }
    else {
      throw new Error( destinationPath + ' already exists. Run with --clean if you want to do over.' );
    }
  }
```

Does anyone mind if I remove the `throw Error`? The use case is where I've already created the repo via GitHub, I check it out, and then populate it with `grunt create-sim`.

**Comment by pixelzoom** [comment]
Or perhaps `--clean` should be replaced with `--overwrite`, which defaults to `false`.

**Comment by pixelzoom** [comment]
Hmmm... Looks like both `--clean` and `--overwrite` are useful (both default to false).

**Comment by jbphet** [comment]
Consensus in 11/12/2015 design meeting - go for it!
