### ISSUE TITLE
use tokens for author and title in simula-rasa

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#409]
Some of simula-rasa isn't very template-like.  Here are the tokens I'm referring to, along with what I propose to change them to:

`Your Name (Your Affiliation)` -> `$AUTHOR$`

`Simula Rasa` -> `$TITLE$`

createSim.js will be modified accordingly.

**Comment by pixelzoom** [comment]
Assigning to @samreid in case he wants to take a quick peek.

**Comment by pixelzoom** [comment]
Note that "$TITLE$" will be displayed when running simula-rasa_en.hmtl. I'm assuming that's OK - the sim runs just fine, and it makes it clear where the title will be inserted. It appear in the browser title, the sim's title (navbar), and About dialog.

**Comment by samreid** [comment]
I noted some commits in this revision: 936411a40184dac3cd4adbefe920869482c8cfdf

I didn't see any problems, and it's OK with me if $TITLE$ appears in the browser, navbar, etc.

**Comment by samreid** [comment]
Close if nothing else to do here.

**Comment by pixelzoom** [comment]
> I noted some commits in this revision: 936411a40184dac3cd4adbefe920869482c8cfdf

I don't see a commit with that sha, and GitHub is not tagging it as a sha.  ??

**Comment by samreid** [comment]
Sorry, wrong repo: https://github.com/phetsims/simula-rasa/commit/936411a40184dac3cd4adbefe920869482c8cfdf

**Comment by pixelzoom** [comment]
Got it, thanks. Sorry I forgot to fully quality the commits.  Closing.
