### ISSUE TITLE
Discuss style for number of parameters

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#415]
In https://github.com/phetsims/bending-light/issues/315 @pixelzoom pointed out that the BendingLightView has too many required parameters (10 when the issue was created).  I asked the following follow-up questions:

1. How many required constructor/function parameters is too many?  Is it context-sensitive?
2. Should we formalize a rule for our style guide about limiting the number of parameters?
3. Should we formalize a lint rule for limiting the number of parameters?

It looks like eslint already has a max-params rule: http://eslint.org/docs/rules/max-params.html

Marking for developer meeting unless we can discuss/decide before then.

**Comment by pixelzoom** [comment]
I don't think that number of parameters should be a metric.  I think the recommendations should be:

• use constructor parameters for things that have no sensible default value
• use options for things that have a default value

**Comment by jbphet** [comment]
Discussed in 12/8/2015 developer meeting, consensus was to add it as an element in the code review checklist and to *not* add an ESLint rule for it at this time.

**Comment by pixelzoom** [comment]
Rather than put this in the code-review check list, it belongs in the code-style guidelines. I augmented the code-style guidelines in "PhET Development Overview" at http://bit.ly/phet-development-overview.  Search for "For constructors, use parameters".
