### ISSUE TITLE
ESLint isn't catching violations of naming conventions

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#416]
While working on https://github.com/phetsims/bending-light/issues/315, I noticed a parameter whose name began with an uppercase letter: `IndexOfRefractionDecimals`.  This was fixed in https://github.com/phetsims/bending-light/commit/37411610ff6f93c2412ded6ddaaaee775ea90708.  But before fixing it, I ran `grunt lint` and was surprised to find that it wasn't flagged.   

I also tried adding something like:

 ```js
var MyVar = 0;
MyVar++;
```

... and `MyVar` was not flagged.

This seems like a pretty basic naming convention, so I'm wondering... do we have something turned off in ESLint that is allowing this type of error to pass undetected? @samreid any thoughts?

**Comment by pixelzoom** [comment]
Also not detecting type names that start with lowercase.  Eg I renamed bending-light's `IntroView` to `introView`, and it passed lint.

**Comment by samreid** [comment]
It is difficult to know whether a variable is assigned to a constructor function or not.  For instance, the following example var *should* be uppercase:

```js
var MyVar = function(){/*some constructor function*/};
```

Here is another situation where an uppercase is appropriate:
```js
var MY_VAR = 0;
```

I noticed an ESLint rule "new-cap" that may be able to help us on a related problem:
http://eslint.org/docs/rules/new-cap.html

However, it doesn't detect problematic upper case var names for non-functions.

This rule seems like it is more about forbidding underscores within var names than starting them with a lowercase:
http://eslint.org/docs/rules/camelcase

@pixelzoom where do you want to go from here?

**Comment by pixelzoom** [comment]
So the conclusion seems to be that this is not possible with ESLint.  Closing.
