### ISSUE TITLE
Investigate GA compatability with Chrome webstore

### ISSUE THREAD

**Issue by mattpen** [phetsims/chipper#417]
The GA code we are using in offline sim packages is not compatible with Chrome Packaged Apps.  We need to investigate the [Chrome Platform Analytics](https://github.com/GoogleChrome/chrome-platform-analytics/wiki) library to determine feasibility.

Can we push information to our current GA setup?  Is it compatible with yotta?

**Comment by mattpen** [comment]
@samreid @jonathanolson I think I may have found a bug in the GA code in the downloaded packages. If I download an HTML5 sim from the website (I tested Hooke's Law and Arithmetic) and then run the sim from my local drive (Win7/Chrome47) with the GA debugger enabled, I get the following errors:

    Running command: ga("send", "pageview", {dimension1: "arithmetic", dimension2: "1.0.0", dimension3: "en", dimension4: "2015-12-19 15:13:35 UTC"})
    Unallowed document protocol. Aborting hit.
and 

    Running command: ga("send", "pageview", {dimension1: "arithmetic", dimension2: "1.0.0", dimension3: "en", dimension4: "2015-12-19 15:13:35 UTC"})
    Storage not available. Aborting hit.

I fixed it by adding this code before the send command 

    window.googleAnalytics("set", "checkProtocolTask", null);
    window.googleAnalytics("set", "checkStorageTask", null);
I appended "_mptest" to the simName dimension in order to verify in the GA console if its really working.  It hasn't showed up yet ,I'll check later today to see if it was successful.

**Comment by mattpen** [comment]
@samreid @jonathanolson When I test sims launched using the file:// protocol they don't seem to be sending pageviews to GA in either their original state or after the modifications I mentioned above.  Can either of you point out where in GA I would be able to find pageviews of sims launched locally?  (I'm tagging Sam as he is the author of [google-analytics.js](https://github.com/phetsims/phetcommon/blob/master/js/analytics/google-analytics.js))

**Comment by mattpen** [comment]
@oliver-phet @ariel-phet It looks like Chrome webstore apps will need to push GA hits to a Mobile App instead of a Website.  To test this out we need to add a property on the GA admin page for a mobile app, but when I am logged in as phethelp I don't have this permission.  Do you know who the admin is for GA for PhET?

**Comment by jonathanolson** [comment]
Just checked, and I see a new property (Phet Chrome Webstore), so I assume that part has been handled?

Good catch on the file:// protocol. Sounds like that is happening for the main property. Does that happen for the Hewlett property (I think they only want things from our domain, which can't be from the file protocol), or our others?

We may also want:
```js
window.googleAnalytics("io.set", "checkProtocolTask", null);
window.googleAnalytics("io.set", "checkStorageTask", null);
...
window.googleAnalytics("thirdParty.set", "checkProtocolTask", null);
window.googleAnalytics("thirdParty.set", "checkStorageTask", null);
```

**Comment by samreid** [comment]
@mattpen I'm unfamiliar with the Google Analytics code, my commits for that file are mostly from when I moved it from one place to another.  So I'll leave this up to you and @jonathanolson to handle (though let me know if I need to get up to speed to provide assistance).

**Comment by mattpen** [comment]
@jonathanolson - I haven't been able to confirm that the hits from the html sims are being sent to any of the trackers (phet-io and hewlett included) when launched from the file:// protocol.  The code I added did not fix it, although it is pretty well documented that it should so I might be missing something.

I did successfully send hits from the chrome-extension protocol using the chrome-platform-analytics API.  It looks like it is easy to track through the Mobile App property.  I've confirmed that we can also send Events to other properties as well.  For example, if you look at today in the 03 PhET - No Filter view and go to Top Events, you can see an example set of events in the testEvent Category.

**Comment by mattpen** [comment]
Tagging the developer-meeting to discuss how hits should be structured.

**Comment by pixelzoom** [comment]
At 12/29/15 dev meeting, deferred until 1/7/16, when @ariel-phet and @oliver-phet are present.

**Comment by mattpen** [comment]
Discussed at 1/7/2016 dev meeting.

Offline caching of hits is not a high priority requirement at the current time.
I'm going to proceed with adapting yotta scripts to analyze GA Events sent from chrome apps.

**Comment by mattpen** [comment]
Sims should be able to send their normal GA hits now through the improvements in https://github.com/phetsims/chipper/issues/50
