### ISSUE TITLE
Mipmaps should be deterministic

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#419]
Sometimes it is valuable to compare two minified HTML files to understand their exact differences.  For instance, I am deploying a release candidate and I want to verify that it differs from the dev version by only known changes (such as build date, version number, etc).  However, the mipmaps output in different orders, making the diffs `diff`icult to understand.  Over Skype a few days ago, @jonathanolson said this is because they are just keys in an object, and the traversal order is not deterinistic, but that it could be changed to be deterministic.  Since this is my second time running into this issue in a short period of time, I thought it would be a good change to make.

@jonathanolson do you have time for this?  If not, can you recommend someone else and point them in the right direction?

**Comment by jonathanolson** [comment]
Due to not thinking through my copy-paste-fu, the commit is https://github.com/phetsims/chipper/commit/598dca87189da3f9c955b61ac229ff8def5008a3.

**Comment by jonathanolson** [comment]
@samreid, mind reviewing?

**Comment by samreid** [comment]
I visually inspected the code and its output as well as doing a diff between two builds and everything looks good.
