### ISSUE TITLE
why is create-together-files being run by build task?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#421]
I tried to build a PhET-iO version of beers-law-lab by running `grunt --brand=phet-io`.  For some reason, this also ran the `create-together-files` task.  I now have a whole bunch of examples in beers-law-lab/build/phet-io that I don't want or need. 

Why is it necessary to run that task whenever building a sim for the phet-io brand?
Or is this a misplaced workaround for building the PhET-iO examples?

**Comment by samreid** [comment]
It seems like we can replace this with the table that has been developed for the phet-io docs.

@pixelzoom was thinking this still makes sense to do this on a sim-by-sim basis.

**Comment by pixelzoom** [comment]
Would be nice if create-together-files was an optional step of a dev build, so we can do dev builds without having to wait for this step.  

Recommended generating phet-io docs/examples per sim (rather than per "batch"), it will potentially result in duplicate files, but will simplify build and delivery processes.

**Comment by pixelzoom** [comment]
12/29/15 Leave as is.

**Comment by pixelzoom** [comment]
Reopening. This task is being run regardless of the `--brand` option.  It does nothing unless `--brand=phet-io`.  But it's confusing to see `Running "create-together-files" task` for every build.  Let's change that.

**Comment by samreid** [comment]
Fixed above and tested by building concentration with and without --brand=phet-io.  Review if you wish.

**Comment by pixelzoom** [comment]
Great, thanks for doing this. Closing.
