### ISSUE TITLE
Investigate standard issue labels via api and webhooks

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/chipper#425]
I made a feature request to github, and received this reply about standardizing labels

>Hi Ariel,

>Thanks for the very kind words, and for taking the time to submit feedback.

>Yeah, I agree it would be useful if there was a way to have organization-wide labels as you described. Adding that is on our feature request list, but it probably won't happen in the near future.

>For now, you could use the API to automatically create labels in repositories:

>https://developer.github.com/v3/

>Even better, if you pair that up with using organization-level webhooks, you could automatically create labels for any new repository created in your organization:

>https://developer.github.com/webhooks/

>Hope this helps and thanks again!

**Comment by ariel-phet** [comment]
@mattpen - when time allows could you investigate the above suggetions from github? Seems like knowing more about this topic would be great for us, as well as your personal "github mojo"

**Comment by ariel-phet** [comment]
Feel free to try a test case with creating a test repo like "label test" and perhaps summarize findings in this issue.

**Comment by jonathanolson** [comment]
Already had briefly looked into this, and it looked doable at the time. Also this issue is related to https://github.com/phetsims/tasks/issues/223 (duplicate?)

**Comment by ariel-phet** [comment]
Yes, duplicate. I will close that task issue now that we have some more info.

**Comment by pixelzoom** [comment]
Related to https://github.com/phetsims/tasks/issues/465

**Comment by mattpen** [comment]
I investigated this a bit tonight.  On first glance, it appears webhooks are probably overkill for our purposes.  It would require setting up a server that listens on a port for all activity from the phetsims organization then parses out which events are for a new repo.  It would be easier in terms of development time (and possibly in terms of resource usage on figaro or simian) to just set up a script that runs once a night (week? month?) and standardizes all labels in any new repo that has appeared.
If we want to do additional work with webhooks, such as automaticallly applying milestones or labels, it might be worth spending more time on.

I can write this script relatively quickly once the [hex codes](https://github.com/phetsims/phet-info/blob/e107784c98c62781bacb8905391f5f3eb17e6ce0/issue-info/labels.md) are finalized.

**Comment by ariel-phet** [comment]
We are moving forward with this project, but investigation sounds complete, closing
