### ISSUE TITLE
delete deploy-dev.sh ?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#426]
Can we delete deploy-dev.sh? It has been replaced by `grunt deploy-dev`.

**Comment by samreid** [comment]
I have been modifying deploy-dev.sh and using it for deploying dirs for phet-io.  I could come up with another way of doing this, but it has been very helpful as a reference and starting point.

**Comment by pixelzoom** [comment]
Why have you been modifying deploy-dev.sh instead of the grunt task that was supposed to replace it?

**Comment by samreid** [comment]
I'm more familiar with deploy-dev.sh, but I'll take deployDev.js for a test drive for next PhET-iO deploy.

**Comment by jbphet** [comment]
Discussed at 1/12/2016 meeting and decided that it could be deleted.  @pixelzoom will blow it away.
