### ISSUE TITLE
Google Analytics errors on file: protocol

### ISSUE THREAD

**Issue by mattpen** [phetsims/chipper#429]
I noticed this while investigating #417, but this is not related to the CWS so I'm opening a new issue.

Google Analytics hits when sent from a downloaded sim are currently not being sent successfully.  The problem appears to lie in compatibility issues with the "file:" protocol.  The work around I found is to set the protocol and storage checks to null and then manually set the location.  While testing pageviews, I was not able to find the hit in the Analytics console when using the default location: `file:///C:/Users/Matt/Downloads/bending-light_en%20(1).html`.  If I manually set it to something without the file:///, it worked successfully (`/fileprotocol/bending-light` for example.)

I think the hits will work if we add this code for each of the tracking ids:

    if (window.location.protocol === 'file:') {
      window.googleAnalytics("set", "checkProtocolTask", null),
      window.googleAnalytics("set", "checkStorageTask", null),
      window.googleAnalytics("set", "location", "/fileprotocol/"+i.dimension1),
    }

The hit shows up like this: 
![image](https://cloud.githubusercontent.com/assets/11747676/12254220/8f6cd6d0-b8a3-11e5-96c4-6c6d0b7ff034.png)

@jonathanolson does this fix look ok? Is it ok to branch chipper to test it out?

**Comment by jonathanolson** [comment]
Could we have it do something like "/offline/html/" + simName + "_" + locale?

Having it closer to the other entries style is helpful, and it's important to record the locale in the URL.

**Comment by mattpen** [comment]
Yes, that's possible, we can get the locale from `phet.chipper.locale`.

**Comment by jonathanolson** [comment]
@ariel-phet, we identified a fix for this.

Since it seems we haven't been getting analytics from downloaded HTML sims (seems important!), I think it's likely this deserves to be patched with a maintenance release (possibly with other changes like the phet-app query parameter included).

Thoughts?

**Comment by ariel-phet** [comment]
@jonathanolson yes I agree it would be important to patch, but I also agree it would be good to batch changes (like the ?phet-app) lets bring up at status meeting.

My instinct tells me that our "downloaded" html5 sim runs are low, though obviously without this fix we cannot tell, and I think it can wait until Thursday to make a decision.

**Comment by jonathanolson** [comment]
Maintenance releases will not wait for phet-app, will push out for translatable sims.

**Comment by jonathanolson** [comment]
Production deployments complete, will be completing documentation for toolchain soon in https://github.com/phetsims/perennial/issues/12.
