### ISSUE TITLE
clone-missing-repos.sh doesn't work on Windows

### ISSUE THREAD

**Issue by jbphet** [phetsims/chipper#430]
I'm setting up a new machine and tried to use clone-missing-repos.sh, but it failed.  I tracked the issue down to line endings.

**Comment by jbphet** [comment]
I added a pipe through the ```dos2unix``` utility in ```print-missing-repos.sh```, and this appears to have fixed the problem.  I believe that this is a no-op on unix derivatives, but it's probably best to check.  I'll assign to @pixelzoom to test on Mac and make sure it's not broken there.  Any other Mac or Linux users can go ahead and test this before @pixelzoom if they want to.

**Comment by jbphet** [comment]
On second thought, assigning to @jonathanolson to test.

**Comment by pixelzoom** [comment]
On Mac OS X 10.11.3, this is broken:

```
% bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
Copyright (C) 2007 Free Software Foundation, Inc.
% print-missing-repos.sh 
/Users/cmalley/PhET/GitHub/chipper/bin/print-missing-repos.sh: line 28: dos2unix: command not found
```

**Comment by jbphet** [comment]
Dang.  Okay, I'll revert it and try to figure out how to do this in a more platform independent way.

**Comment by pixelzoom** [comment]
Try `col -b`

**Comment by pixelzoom** [comment]
or `sed -e 's/\r$//' inputfile > outputfile`, if you're trying to remove carriage returns.

**Comment by jbphet** [comment]
I tried using ```tr -d '015'```, which was recommended here: http://stackoverflow.com/questions/2613800/how-to-convert-dos-windows-newline-crlf-to-unix-newline-n-in-bash-script.  This works on Windows.  Assigning to @jonathanolson to test on OSX.  @pixelzoom - feel free to test it if you have time and inclination.

**Comment by pixelzoom** [comment]
`print-missing-repos.sh` works for me on Mac OS X 10.11.3.

**Comment by pixelzoom** [comment]
I'm going to close this.  Works for me, I doubt that @jonathanolson's testing would prove otherwise.
