### ISSUE TITLE
togetherPreload is unnecessary

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#432]
In @5bdbb01347f5e79254a79a7b6f3a4373e4982b23, `packageJSON.phet.togetherPreload` was added to specify sim-specific preloads for PhET-iO.  This was added in order to load PhET-iO API files from other sims. See https://github.com/phetsims/together/issues/204.

The `concentration` repo is currently the only client, and it looks like this in `concentration/package.json`:

```js
{
  ...
  "phet": {
    ...
    "togetherPreload": [
      "../together/js/api/beers-law-lab-api.js"
    ]
  }
}
```

This should be handled like in `chipper/build.json`, i.e.:

```js
{
  ...
  "phet": {
    ...
  },
  "phet-io": {
    ...
    "preload": [
      "../together/js/api/beers-law-lab-api.js"
    ]
  }
}
```

**Comment by pixelzoom** [comment]
Tested with `?phet-io-standalone`.

Committed in https://github.com/phetsims/chipper/commit/519cfaa6aa1a457dd6225ea04d1cd5d1a7a4c119.

Assigning to @samreid for review.

**Comment by pixelzoom** [comment]
Whoopsie, back to me.  I just realized that packageJSON.phet is not the PhET brand, it's supposed to encapsulate *all* fields that are specific to PhET.  So the correct entry in package.json should have `"phet-io"` nested under `"phet"`, like this:

```js
{
  ...
  "phet": {
    ...
    "phet-io": {
      ...
      "preload": [
        "../together/js/api/beers-law-lab-api.js"
      ]
  }
  },
}
```

@samreid do you agree?

**Comment by samreid** [comment]
Ah, right `phet` is the root for all phet things, `phet-io` should be nested underneath. Nice catch!

**Comment by pixelzoom** [comment]
`phet-io` is now nested under `phet` in package.json. Back to @samreid for review.

**Comment by samreid** [comment]
This looks correct, thanks! Closing.
