### ISSUE TITLE
specify PhET-iO API file in package.json?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#433]
In getBuildConfig.js:

```js
    // add the together API file
    if ( brand === 'phet-io' ) {

      var TOGETHER_API_FILENAME = '../together/js/api/' + packageJSON.name + '-api.js';
      if ( !grunt.file.exists( TOGETHER_API_FILENAME ) ) {
        grunt.log.warn( 'together API file does not exist: ' + TOGETHER_API_FILENAME );
      }

      preload.push( TOGETHER_API_FILENAME );
      preload.push( '../together/js/finishedPreloads.js' );
    }
```

Why not add the API file to package.json? (`packageJSON[ 'phet-io' ].preload`, in getBuildConfig.js) 

For example, here's what concentration/package.json would look like:

```js
{
  ...
  "phet-io": {
    "preload": [
      "../together/js/api/beers-law-lab-api.js",
      "../together/js/api/concentration-api.js"
    ]
  }
}
```

Then the `if` statement in getBuildConfig.js becomes:

```js
    if ( brand === 'phet-io' ) {
      // add preload that must be last
      preload.push( '../together/js/finishedPreloads.js' );
    }
```

Pros: 
• Makes explicit what API files are preloaded
• We already have to specify dependency API files (eg,beers-law-lab-api.js), so this provides a more complete view of what API files are used. 
• Naming convention for the API file is no longer frozen in code

Cons:
• API file must be added to package.json for every sim that has been instrumented
• API file paths are visible in package.json

**Comment by pixelzoom** [comment]
I did a search for "-api.js" and don't see any other places where the naming convention for the API file is codified.  So I think this proposal is safe.

**Comment by pixelzoom** [comment]
Resolution of https://github.com/phetsims/chipper/issues/432

**Comment by pixelzoom** [comment]
Resolution of https://github.com/phetsims/chipper/issues/432 is a pre-requisite, so that we have the correct placement in package.json files.

**Comment by pixelzoom** [comment]
I made the changes proposed above in my working copy, and tested with a couple of sims by doing `grunt --brand=phet-io` and running with `?phet-io-standalone`.  No problems noted, and this seems much cleaner to me.  

Based on the contents of together/js/api/, there are 11 package.json files that will need to be edited.

@samreid Let me know if you want me to make and commit this change.

**Comment by samreid** [comment]
Yes, please proceed.

**Comment by pixelzoom** [comment]
@samreid wrote to phew-dev list:
> I'll need to deploy phet-io sims soon, and I suspect I'll need to use master to pick up recent phet-io changes.  What is the state of master?  Is there any known in-progress work that would need cleanup before deploys?

Do you want me to wait on this until after your this deploy?

**Comment by samreid** [comment]
Can we touch base on skype?

**Comment by pixelzoom** [comment]
We talked on Skype, and @samreid said that this would be useful to have pre-deploy.  So I've made the change to getBuildConfig.js and package.json for all sims that have an API file.  I built all of the sims and verified that they ran with `?phet-io-standalone`.

Back to @samreid.

**Comment by pixelzoom** [comment]
We talked on Skype, and @samreid said that this would be useful to have pre-deploy. So I've made the change to getBuildConfig.js and package.json for all sims that have an API file. I built all of the sims and verified that they ran with ?phet-io-standalone.

Back to @samreid.

**Comment by pixelzoom** [comment]
I missed on (color-vision) which I have now updated.  But it won't build, looks like I picked up buggy changes in https://github.com/phetsims/chipper/commit/8e01f759b86e1b8ac3fe9543acaeaeaf2810b053.  

```
% cd color-vision
% grunt --brand=phet-io
Running "eslint:allFiles" (eslint) task

/Volumes/b5 Data1/PhET/GitHub/chipper/js/grunt/toPhETiOSite.js
  67:7  error  "packageJSON" is defined but never used  no-unused-vars

✖ 1 problem (1 error, 0 warnings)

Warning: Task "eslint:allFiles" failed. Use --force to continue.

Aborted due to warnings.
```

**Comment by pixelzoom** [comment]
Builds of non-phetio brands are also failing:

```
% cd function-builder
% grunt
Running "eslint:allFiles" (eslint) task

/Volumes/b5 Data1/PhET/GitHub/chipper/js/grunt/toPhETiOSite.js
  67:7  error  "packageJSON" is defined but never used  no-unused-vars

✖ 1 problem (1 error, 0 warnings)

Warning: Task "eslint:allFiles" failed. Use --force to continue.

Aborted due to warnings.
```

**Comment by pixelzoom** [comment]
This is a lint error. As a temp fix, I've commented out the offending line and pushed, see https://github.com/phetsims/chipper/commit/3b42d966106e05d0f5460935caecbd3c31a32eaa.

**Comment by pixelzoom** [comment]
Removing the developer-meeting label.  @samreid anything else to do here, other than review?

**Comment by samreid** [comment]
Nope, the last step will be for me to review.

**Comment by samreid** [comment]
Changes look good, I have used them to take the next steps in the site deploy process and no problems noted.
