### ISSUE TITLE
Add a command that iterates over a given list of simulations

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#434]
Many of our scripts in chipper/bin are hard-coded to operate on a single list.  For instance, grunt-all.sh works on `active-runnables`.  In some cases, it would be nice to be able to select the list of simulations as a command line argument.  For instance, if I only want to run the grunt build on the `active-sims`, there could be a command like:

```
for-each.js active-sims grunt
```

I'm adding a list of `instrumented-sims` and it would be nice to perform commands that iterate over the instrumented sims.

**Comment by samreid** [comment]
I've implemented the proposed shell script above, and tested it like so:

```
~/github/concentration$ for-each.sh instrumented-sims pwd
beers-law-lab
/Users/samreid/github/beers-law-lab
color-vision
/Users/samreid/github/color-vision
concentration
/Users/samreid/github/concentration
faradays-law
/Users/samreid/github/faradays-law
molecules-and-light
/Users/samreid/github/molecules-and-light
```

I've also used it to create built simulations for the PhET-iO site.  @pixelzoom or @jonathanolson do you want to review?

**Comment by pixelzoom** [comment]
This script fails for me.

```
% cat sims
beers-law-lab
function-builder
% for-each.sh sims ls
cat: /Users/cmalley/PhET/GitHub/chipper/bin/../data/sims: No such file or directory
%
```

**Comment by pixelzoom** [comment]
Looks like the script is assuming that the file containing the list of sims is in `chipper/data/`.  It would be preferable to not have that limitation, and default to that as a convenience if the file isn't found at the path specified on the command line.

**Comment by samreid** [comment]
> This script fails for me.

As described in the docs:

```The lists are drawn from chipper/bin/data```

So you can choose from:
* active-repos
* active-runnables
* active-sims
* instrumented-sims

**Comment by samreid** [comment]
I like the idea of allowing any file list, and falling back to chipper/bin/data

**Comment by pixelzoom** [comment]
Perhaps we should reimplement `grunt-all.sh` in terms of this new script?
Eg, `grunt-all.sh lint` is equivalent to `for-each.sh active-repos grunt lint`.

**Comment by pixelzoom** [comment]
Sorry, I missed the doc.  Regardless, this script would be much more useful if it didn't require files to live in `chipper/data/`.  And I don't want to create temp files in `chipper/data/` that I may accidentally check in.

**Comment by pixelzoom** [comment]
Seeing a lot of junk (probably from `echo` and `cd`) when running this script with one of the supported input files.

Eg, I expected to see:

```
% ```
% for-each.sh instrumented-sims pwd
/Users/cmalley/PhET/GitHub/beers-law-lab
/Users/cmalley/PhET/GitHub/color-vision
/Users/cmalley/PhET/GitHub/concentration
/Users/cmalley/PhET/GitHub/faradays-law
/Users/cmalley/PhET/GitHub/molecules-and-light
%
```

But here's the (noisy) output:

```
% for-each.sh instrumented-sims pwd
beers-law-lab
/Users/cmalley/PhET/GitHub/beers-law-lab
/Users/cmalley/PhET/GitHub/beers-law-lab
color-vision
/Users/cmalley/PhET/GitHub/color-vision
/Users/cmalley/PhET/GitHub/color-vision
concentration
/Users/cmalley/PhET/GitHub/concentration
/Users/cmalley/PhET/GitHub/concentration
faradays-law
/Users/cmalley/PhET/GitHub/faradays-law
/Users/cmalley/PhET/GitHub/faradays-law
molecules-and-light
/Users/cmalley/PhET/GitHub/molecules-and-light
/Users/cmalley/PhET/GitHub/molecules-and-light
%
```

**Comment by pixelzoom** [comment]
I suppressed the `cd` output in the above commit.  I can see why the script is echoing the repository name, because something like `for-each.sh instrumented-sims grunt lint` will not identify the repository when a command is applied to it.  Eg, this is not very useful:

```
% for-each.sh instrumented-sims grunt lint
Running "eslint:repoFiles" (eslint) task

Done, without errors.
Running "eslint:repoFiles" (eslint) task

Done, without errors.
Running "eslint:repoFiles" (eslint) task

Done, without errors.
Running "eslint:repoFiles" (eslint) task

Done, without errors.
Running "eslint:repoFiles" (eslint) task

Done, without errors.
```

**Comment by pixelzoom** [comment]
The filename can now be either an absolute or relative path.  If it's a relative path and the file isn't found, then it directory defaults to `chipper/data/`.  Here are some tests:

```
% pwd
/Users/cmalley/Downloads

% foreach.sh
usage: for-each.sh filename command

% foreach.sh /bogusAbsoluteFile pwd
/bogusAbsoluteFile does not exist

% foreach.sh bogusRelativeFile pwd
for-each.sh bogusRelativeFile pwd
/Users/cmalley/PhET/GitHub/chipper/data/bogusRelativeFile does not exist

% cat repos
beers-law-lab
chipper

% for-each.sh repos pwd
beers-law-lab
/Users/cmalley/PhET/GitHub/beers-law-lab
chipper
/Users/cmalley/PhET/GitHub/chipper

% for-each.sh instrumented-sims pwd
... list of directories
%
```

**Comment by pixelzoom** [comment]
Back to @samreid for review.

**Comment by samreid** [comment]
I skimmed the changes and took it for a test drive.  All seems well, thanks!  The only outstanding issue is @pixelzoom comment:

> Perhaps we should reimplement grunt-all.sh in terms of this new script? Eg, grunt-all.sh lint is equivalent to for-each.sh active-repos grunt lint.

I think this is a good idea but don't have time t work on it now, I'll create a separate issue for it.

**Comment by samreid** [comment]
I created https://github.com/phetsims/chipper/issues/439 (currently unassigned), closing.
