### ISSUE TITLE
'grunt deploy-production' should fail if there are working copy changes OR if checked out dependencies don't match JSON file

### ISSUE THREAD

**Issue by jbphet** [phetsims/chipper#437]
Closely related to #435.  This was discussed in the developer meeting on 1/28/2016.  Right now, there is no warning or failure if the developer forgets to do a ```grunt checkout-shas``` before doing a production deployment, and this could case a production version to be deployed that has very different SHAs than were contained in the most recent release candidate.  We should add this check into the ```deploy-production``` task and fail if the SHAs don't appear to be checked out.

**Comment by jbphet** [comment]
Consider adding a check that the version number appears to be in the correct format for a production deployment.

**Comment by jbphet** [comment]
Should actually fail if dependencies don't match what's in the dependencies.json file, not just if the deps are on master.  This was decided at the Feb 18 2016 dev meeting.

**Comment by jbphet** [comment]
@jonathanolson and I discussed and decided to also add a ```dryRun``` flag that would check all preconditions but skip the actual build and deployment, as well as the commit of the dependencies.json.

**Comment by jbphet** [comment]
I reviewed most of the changes for this issue with @jonathanolson prior to committing them, but it would be good if he could review them in their final (for now) form and do some testing on OSX (I've only tested on Windows).  Assigning to him.

**Comment by jonathanolson** [comment]
Deployed with OS X (fine) and cursory review looks good.
