### ISSUE TITLE
Update to Grunt 1.0.0

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#445]
Grunt 1.0.0 rc1 was released on February 11, 2016 including fixes like the nopt fix (that parses command line arguments):

http://gruntjs.com/blog/2016-02-11-grunt-1.0.0-rc1-released

There are API changes so this may not be an easy upgrade, but it seems like it is worth our time.  I'll assign it to myself but may not have time to get to it in the near future.  @jonathanolson @pixelzoom @jbphet @jessegreenberg feel free if you want to take a look into it.

**Comment by pixelzoom** [comment]
I have no time to look at this.

**Comment by jbphet** [comment]
Two thoughts: 

1. If it's an rc1, shouldn't we wait for the full 1.0.0 release?

2. We could get started on this by showing @phet-steele how to update the package.json file, then test build and regression test on a handful of sims (and not check in the change) and see what if any error arise. If nothing breaks initially, we could do a quick script to update the package.json for all sims, and have him run the automated tests to verify builds and basic functionality.  Other QA team members could do in depth testing of at least some of the resulting builds.

**Comment by pixelzoom** [comment]
Do we really want to do this when we just decided to fix i18n and republish remaining sims as quickly as possible? (https://github.com/phetsims/tasks/issues/476#issuecomment-183029769)

**Comment by pixelzoom** [comment]
+1 to wait for 1.0.0 GA, we don't have time for an RC.

**Comment by jbphet** [comment]
Agreed - IMO we shouldn't do anything until the 1.0.0 version is available.  When it is, can can consider whether the timing works with the i18n deployments.

**Comment by samreid** [comment]
OK I've unassigned and marked as on-hold.  We can re-evaluate once 1.0 is live.

**Comment by samreid** [comment]
Grunt 1.0.0 has been out since April.

**Comment by samreid** [comment]
@jbphet can you please review the translation (locales) issue and see how it pertains?

**Comment by samreid** [comment]
Assigned to me to update grunt.

Assigned to @jbphet to see about the nopt bug and if there is a workaround we need to remove.

@samreid can create a test task issue after the update.

**Comment by jbphet** [comment]
I just spent some time looking at this, and I didn't find any workaround related to the locales and the options behavior.  The release notes page for Grunt 1.0.0 (http://gruntjs.com/blog/2016-04-04-grunt-1.0.0-released) says,
> Be aware previously ```--foo bar``` used to pass the value ```bar``` to the option ```foo```. It will now set the option foo to true and run the task bar.

I recall running into issues with this behavior previously when running commands like ```grunt --dryRun deploy-rc```.  With the version that we are currently using (v0.4.5), this ends up running the default grunt task and sets the value of ```dryRun``` to ```deploy-rc```, which is summarily ignored.  I've gotten into the habit of setting values explicitly, e.g. ```--dryRun=true```.  Updating will make such commands work as expected.

I also looked through the code in chipper for scripts that rely on the older behavior and didn't find anything.  I'm going to re-label this issue for developer meeting to see if anyone else has any recollection of workarounds for this behavior and, if not, we can proceed towards testing the upgrade.  As I mentioned in a previous comment, we may be able to use some of the QA team resources to verify that updating doesn't cause any problems before committing to it.

**Comment by pixelzoom** [comment]
@jbphet said:
>  I'm going to re-label this issue for developer meeting to see if anyone else has any recollection of workarounds for this behavior

I don't recall any workaround in code. What I recall is getting in the habit of providing a value for every option switch (line in @jbphet's `--dryRun=true` example).

**Comment by samreid** [comment]
I also recall we had to explicitly specify arguments like `--dryRun=true` which wouldn't be broken in Grunt 1.0.0.  It is more a question of whether we want to go back to using `--dryRun` now that it will be supported.  We may wish to stick with `--dryRun=true` because it is clearer.

**Comment by pixelzoom** [comment]
The bug that @jbphet mentioned in https://github.com/phetsims/chipper/issues/445#issuecomment-245771015 was apparently in 'nopt', a grunt dependency.  From the [grunt CHANGELOG](https://github.com/gruntjs/grunt/blob/master/CHANGELOG), in v1.0.0-rc.1:

>  - `nopt` is upgraded to `~3.0.6` which has fixed many issues, including passing
      multiple arguments and dealing with numbers as options. Be aware previously
      `--foo bar` used to pass the value `'bar'` to the option `foo`. It will now
      set the option `foo` to `true` and run the task `bar`.

**Comment by samreid** [comment]
> I don't recall any workaround in code. 

Perhaps this habit is codified in one or more places, I saw this code in build-server.js:

```js
exec( 'grunt checkout-shas --buildServer=true --repo=' + simName, PERENNIAL, function() {
```

I wonder if this used to read `--buildServer` and was running into the nopt bug.

**Comment by pixelzoom** [comment]
Looks like the output of `grunt --help` for PhET-specific tasks is sufficiently vague that we won't need to change anything if we want to do `--dryRun` instead of `--dryRun=true`.

**Comment by pixelzoom** [comment]
I take it back... one help line in chipper/js/grunt/Gruntfile.js:

```js
240    '--clean=true : (optional) deletes the repository directory if it exists',
```

**Comment by samreid** [comment]
Based on https://github.com/phetsims/chipper/issues/445#issuecomment-245771015 I'll hold off on update until we check in again.

**Comment by jbphet** [comment]
We discussed this at the 9/15/2016 developer meeting and decided to move forward with the upgrade.  @samreid will start on it and let us know if there are any unforeseen challenges.

**Comment by samreid** [comment]
When I updated grunt and did npm install, I received this warning:

```
npm WARN grunt-requirejs@0.4.2 requires a peer of grunt@~0.4.0 but none was installed.
```
Apparently grunt-requirejs has not been updated beyond 0.4.2.  grunt-contrib-requirejs looks like it is versioning with grunt, but I can't remember why we had to use grunt-requirejs instead.

**Comment by samreid** [comment]
Some possibilities:

1) the warning above is just a warning and everything will be just fine
2) We could get rid of grunt-require and just call r.js ourselves using the node or command line interface
3) we could stick with old grunt.

I'm leaning toward 2) but my enthusiasm for a speedy grunt update has wavered.

**Comment by samreid** [comment]
I have a hunch this is nearly all we need, but it will need to include almond as well:

```js
  grunt.registerTask( 'requirejs-build', 'Internal task for r.js step', function() {
    console.log( 'hello' );
    console.log( JSON.stringify( config.requirejs.build.options, null, 2 ) );
    requirejs.optimize( config.requirejs.build.options, function( buildResponse ) {

      //buildResponse is just a text output of the modules
      //included. Load the built file for the contents.
      //Use config.out to get the optimized file contents.
      console.log( 'loaded ' + buildResponse.length + ' modules' );
      var contents = fs.readFileSync( config.requirejs.build.options.out, 'utf8' );
      console.log( contents.length );
    }, function( err ) {
      console.log( 'error', err );
      //optimization err callback
    } );
  } );
```

**Comment by samreid** [comment]
This would take longer than the "quick update" we hoped for at last developer meeting, so I'll wait for feedback before spending more time.  My vote is to decouple our build process from grunt-requirejs, but it could take 2 hours or more.

**Comment by samreid** [comment]
@jonathanolson agrees that moving away from the plugin sounds good.

**Comment by samreid** [comment]
@ariel-phet approved 2+ hours in the next week or two to investigate this.

**Comment by samreid** [comment]
Apparently we cannot launch r.js from the command line because our config files are not pure JSON.  This is a step in the right direction though:

```js
var requirejs = require( 'requirejs' );

/**
 * @param grunt - the grunt instance
 */
module.exports = function( grunt ) {
  'use strict';
  var done = grunt.task.current.async();
  var config = {
    baseUrl: 'js/',
    name: 'almond.js',
    mainConfigFile: 'js/faradays-law-config.js',
    out: 'build/main-built.js'
  };

  console.log( 'starting requirejs' );
  requirejs.optimize( config, function( buildResponse ) {
    //buildResponse is just a text output of the modules
    //included. Load the built file for the contents.
    //Use config.out to get the optimized file contents.
    var contents = fs.readFileSync( config.out, 'utf8' );
    console.log( 'done requirejs2' );
    done();
  }, function( err ) {
    //optimization err callback
    console.log( 'done requirejs3' );
    console.log( err );
    done();
  } );

  console.log( 'done requirejs1' );
};
```

We still need to drop license comments, make sure asserts are stripped, etc.

**Comment by samreid** [comment]
I committed a custom requirejs task above.  With uglify=false, the only difference between the new build and the old build is that the new build doesn't include the config file:

![image](https://cloud.githubusercontent.com/assets/679486/18774979/8c8ae236-811b-11e6-9336-f4f4c5ae097b.png)

This is preventing the sim from running at all.

**Comment by samreid** [comment]
Is this now done with `insertRequire`? https://github.com/requirejs/almond

**Comment by samreid** [comment]
insertRequire did the trick.  It appears the remainder of the require.config is not necessary...?

**Comment by samreid** [comment]
We are also missing this output:

```
/Users/samreid/github/faradays-law/build/faradays-law.min.js
Uncompressed size: 2272944 bytes.
Compressed size: 170821 bytes gzipped. (733948 bytes minified)
```

**Comment by samreid** [comment]
Comparing the uglified files I'm seeing this kind of difference, perhaps it is to be expected:

![image](https://cloud.githubusercontent.com/assets/679486/18775657/708efbe4-8120-11e6-8cad-1f1544569641.png)

**Comment by samreid** [comment]
OK my work here is complete.  This is ready for review by another developer. To test, pull chipper, then navigate to Gruntfile.js line 103:

```js
  var additionalTasks = [
    'clean',
    // 'requirejs-build',
    'requirejs:build',
    'after-requirejs-build'
  ];
```

Comment out the old one `'requirejs:build',` and include the new one I just wrote `'requirejs-build',` so that you may test it.

The build output differences are noted above, in summary: The old version included other require.config things, but it seems like they aren't necessary.

The uglified versions are hard to compare because of (random?) noise.  You may wish to compare outputs with `grunt --uglify=false`

After review is approved, we will have to do the following step:
- [ ] Remove requirejs from getGruntConfig.js.  I'm leaving it there for now to facilitate testing in master.

@ariel-phet please assign a developer to review my code changes and test out the new build engine.

**Comment by ariel-phet** [comment]
@andrewadare you are the winner! :trophy:

**Comment by andrewadare** [comment]
@samreid going through requirejsBuild.js now. Just a reminder that you have [this TODO](3127161cbdb6df92a07eb2dfff8781c85780323b) that should be cleared once the review and testing have passed.

**Comment by samreid** [comment]
Thanks for the reminder, that is also the first checkbox in this list: https://github.com/phetsims/chipper/issues/445#issuecomment-249110133

**Comment by andrewadare** [comment]
requirejsBuild.js looks fine, everything is well commented and clear enough.

Console output from current build step (running `grunt --uglify=false` on Charges and Fields):
```

[charges-and-fields]$ grunt --uglify=false
Running "eslint:allFiles" (eslint) task


Running "clean" task

Running "requirejs:build" (requirejs) task
>> RequireJS optimizer finished

/Users/adare/phetsims/charges-and-fields/build/charges-and-fields.min.js
Uncompressed size: 2472672 bytes.
Compressed size: 542239 bytes gzipped.

Running "after-requirejs-build" task

Done, without errors.
```

And from new build process:
```

[charges-and-fields]$ grunt --uglify=false
Running "eslint:allFiles" (eslint) task


Running "clean" task

Running "requirejs-build" task

Running "after-requirejs-build" task

Done, without errors.
```
The new one doesn't seem to report the file sizes.

**Comment by samreid** [comment]
> The new one doesn't seem to report the file sizes.

Correct, I mentioned that in https://github.com/phetsims/chipper/issues/445#issuecomment-249107213

**Comment by andrewadare** [comment]
Just noting that it's still the case. Seeing the output sizes is useful, but of course not critical.

A diff of the old and new Charges and Fields build output HTML files is identical.

Everything looks good to me; I don't see any problems with the new code or with the build output.

**Comment by samreid** [comment]
It looks like that size reporting was done in https://github.com/asciidisco/grunt-requirejs/blob/master/lib/helper/sizeInfo.js, not in requirejs or uglify2.  If it is important, we could add our own variant, but I don't think it is that important.

**Comment by samreid** [comment]
> A diff of the old and new Charges and Fields build output HTML files is identical.

Except for the require.config call at the bottom, and the timestamps?

**Comment by andrewadare** [comment]
Yes, to be precise, the output is not identical. Here's an example from Charges and Fields:

```

[charges-and-fields]$ diff -w charges-and-fields_en_old.html charges-and-fields_en_new.html
--- charges-and-fields_en_old.html	2016-09-23 09:22:06.000000000 -0600
+++ charges-and-fields_en_new.html	2016-09-23 09:20:32.000000000 -0600
@@ -38,7 +38,7 @@
   window.phet.chipper = {};
   window.phet.chipper.project = 'charges-and-fields';
   window.phet.chipper.version = '1.0.0';
-  window.phet.chipper.buildTimestamp = '2016-09-23 15:22:06 UTC';
+  window.phet.chipper.buildTimestamp = '2016-09-23 15:20:32 UTC';
   window.phet.chipper.brand = 'phet';
   window.phet.chipper.locale = 'en';

@@ -508,7 +508,7 @@
 };
   // ### END THIRD PARTY LICENSE ENTRIES ###
   window.phet.chipper.dependencies = {
-  "comment": "# charges-and-fields 1.0.0 Fri Sep 23 2016 09:22:01 GMT-0600 (MDT)",
+  "comment": "# charges-and-fields 1.0.0 Fri Sep 23 2016 09:20:27 GMT-0600 (MDT)",
   "assert": {
     "sha": "7d27130a4d27da15aa7f8a21bbfb9245288c1b44",
     "branch": "master"
@@ -18957,7 +18957,6 @@
         jQuery: true
     };
 }());
-
 define("almond", function(){});

 // Copyright 2015, University of Colorado Boulder
@@ -85635,56 +85634,8 @@
 } );


-// Copyright 2014-2015, University of Colorado Boulder
-
-/**
- * RequireJS configuration file for the sim.
- *
- */
-require.config( {
-  // An array of dependencies to load. Useful when require is defined as a config object before require.js
-  // is loaded, and you want to specify dependencies to load as soon as require() is defined.
-  deps: [ 'charges-and-fields-main' ],
-
-  // baseUrl: don't bother trying to set it here, it is overridden by data-main in the top-level HTML file
-
-  // Path mappings for module names not found directly under baseUrl. The path settings are assumed to be
-  // relative to baseUrl unless the paths setting starts with a '/' or has a URL protocol.
-  paths: {
-
-    // third-party libs
-    text: '../../sherpa/lib/text-2.0.12',
-
-    // PhET plugins
-    image: '../../chipper/js/requirejs-plugins/image',
-    mipmap: '../../chipper/js/requirejs-plugins/mipmap',
-    string: '../../chipper/js/requirejs-plugins/string',
-    ifphetio: '../../chipper/js/requirejs-plugins/ifphetio',
-
-    // common directories, uppercase names to identify them in require imports
-    AXON: '../../axon/js',
-    BRAND: '../../brand/' + phet.chipper.brand + '/js',
-    DOT: '../../dot/js',
-    JOIST: '../../joist/js',
-    KITE: '../../kite/js',
-    PHET_CORE: '../../phet-core/js',
-    PHET_IO: '../../phet-io/js',
-    PHETCOMMON: '../../phetcommon/js',
-    REPOSITORY: '..',
-    SCENERY: '../../scenery/js',
-    SCENERY_PHET: '../../scenery-phet/js',
-    SUN: '../../sun/js',
-    TANDEM: '../../tandem/js',
-
-    // this sim
-    CHARGES_AND_FIELDS: '.'
-  },
-
-  // optional cache buster to make browser refresh load all included scripts, can be disabled with ?cacheBuster=false
-  urlArgs: phet.chipper.getCacheBusterArgs()
-} );
-define("charges-and-fields-config", function(){});

+require(["charges-and-fields-main"]);
 }());</script>
 </body>
 </html>
```

**Comment by samreid** [comment]
OK is the review complete and ready for me to convert from `'requirejs:build'` to `'requirejs-build'` in master and the other checklist items in https://github.com/phetsims/chipper/issues/445#issuecomment-249110133 ?  Please assign to me when ready.

**Comment by andrewadare** [comment]
@samreid The new code looks good and my spot-check with Charges and Fields reveals no problems. Signing off on the review and test.

**Comment by samreid** [comment]
In the above commit, we are now using the new requirejs-build task. @andrewadare @pixelzoom @jessegreenberg @jonathanolson @jbphet @aadish please pull chipper and report any build problems you observe.

**Comment by samreid** [comment]
In the above commit, grunt-requirejs was removed from chipper's package.json.

**Comment by samreid** [comment]
dot, kite and scenery have their own build systems, with different grunt tasks.

**Comment by jonathanolson** [comment]
> dot, kite and scenery have their own build systems, with different grunt tasks.

Do I need to look at upgrading those build systems?

**Comment by samreid** [comment]
Some possibilities:

(1) drop support for kite/scenery/dot builds
(2) leave them on old grunt
(3) someone on our team (could be me or @jonathanolson) upgrades them.
(4) add chipper support for kite/scenery/dot builds

Here is how I currently feel about each option:
(1) 75%
(2) 60%
(3) 40% 
(4) 50%

**Comment by samreid** [comment]
Spot tests with the new grunt seem good, I tested Function Builder and Friction with grunt 1.0.1 and all seems well.  I'll start committing things.

**Comment by samreid** [comment]
After above changes, developers have to rm -rf node_modules or build errors are reported.

**Comment by samreid** [comment]
The above commit moves all repos to grunt ~1.0.0.  Developers need to update chipper, `rm -rf node_modules` in every directory and `npm install` in every directory.

**Comment by samreid** [comment]
I emailed the team:

In https://github.com/phetsims/chipper/issues/445 I updated our repos to use Grunt 1.0.1, rewrote the grunt-requirejs dependency and updated all simulations package.json files.  You will need to rm -rf all of the node_modules and do fresh npm installs.

Other build systems will need to be updated, such as build-server, test-server, etc.  I do not know how to rm node_modules on those machines.

Scenery, Kite and Dot have their own build systems and I have not updated them.

Please report any problems you observe.

Best Regards,
Sam

**Comment by jonathanolson** [comment]
> Some possibilities:
> 
> (1) drop support for kite/scenery/dot builds
> (2) leave them on old grunt
> (3) someone on our team (could be me or @jonathanolson) upgrades them.
> (4) add chipper support for kite/scenery/dot builds
> 
> Here is how I currently feel about each option:
> (1) 75%
> (2) 60%
> (3) 40% 
> (4) 50%

(1) Would presumably mean removing or updating HTML documentation and examples, as they use the built versions, and would mean abandoning the original goal of allowing other projects to use Scenery/Kite/Dot. Due to PhET mostly using the in-code documentation (and I'm really not sure if anyone else is using them), it would probably not affect us too much. Still would prefer not to.
(2) @samreid, what are the downsides?
(3) I'd be willing to do this.
(4) @samreid, how much effort would this take?

**Comment by samreid** [comment]
I'm moving the scenery/kite/dot to a new issue, probably in scenery.

**Comment by samreid** [comment]
We discovered that we need to run `npm prune` when we move from a package.json with grunt-requirejs to a package.json without grunt-requirejs.  @mattpen is implementing this for the build-server.  @jonathanolson can you implement it for phettest.colorado.edu?

**Comment by jonathanolson** [comment]
> @jonathanolson can you implement it for phettest.colorado.edu?

I already removed node_modules and started the build process to test (going well). Are you saying we want this for the next time we bump package.json?

**Comment by samreid** [comment]
> I already removed node_modules and started the build process to test (going well). Are you saying we want this for the next time we bump package.json?

My apologies, I forgot test-server only goes forward.  If this happens again in the future (say we remove grunt-eslint from package.json), then we may need npm prune or rm -rf node_modules.

**Comment by samreid** [comment]
Summary: grunt has been updated to ~1.0.0, grunt-requirejs is gone, npm prune has been added to build-server, maintenance releases have checked out ok.  I'll close this issue, if subsequent problems arise, please open a new issue and reference this one.
