### ISSUE TITLE
deploy-rc and deploy-production tasks should include a build step

### ISSUE THREAD

**Issue by jbphet** [phetsims/chipper#447]
This was discussed in the 2/23/2016 developer meeting.  

Right now, developers have to remember to run `grunt` before running `grunt deploy-rc` or `grunt deploy-production`.  If they don't, an incorrect version can get deployed, since these two tasks use the `build/dependencies.json` file when composing the command that is sent to the build server.  The `deploy-rc` and `deploy-production` tasks should just include a build step so that this is not a risk.  The only cost is the somewhat longer time for the build-and-deploy process, and we could potentially just add a check of the dependencies files and skip the build step when unnecessary if anyone is concerned about the time.

**Comment by samreid** [comment]
When the build and deploy steps are automated in https://github.com/phetsims/chipper/issues/616 this problem will disappear.
