### ISSUE TITLE
incomprehensible build error when license.json in malformed

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#449]
Here's a real fun error that @phetsims/schmitzware was experiencing when trying to build rutherford-scattering:

```
% grunt
Running "eslint:allFiles" (eslint) task

Running "clean" task

Running "requirejs:build" (requirejs) task
>> Error: SyntaxError: Unexpected token }
>> In module tree:
>>     rutherford-scattering-main
>>       RUTHERFORD_SCATTERING/rutherfordatom/RutherfordAtomScreen
>>         image
>> 
>>     at Object.parse (native)
Warning: Task "requirejs:build" failed. Use --force to continue.

Aborted due to warnings.
```

Turns out there was an extra comma in images/license.json, and getLicenseEntry.js was bailing here, where it reads that file:

```js
39 var json = JSON.parse( global.phet.chipper.fs.readFileSync( licenseFilename, 'utf8' ) );
```

The error message handling here could be improved ;)

**Comment by pixelzoom** [comment]
Changed the above to:

```js
// read license.json
    var fileContents = global.phet.chipper.fs.readFileSync( licenseFilename, 'utf8' );
    try {
      var json = JSON.parse( fileContents );
    }
    catch( err ) {
      if ( err instanceof SyntaxError ) {
        err.message = 'syntax error in ' + licenseFilename;
      }
      throw err;
    }
```

The error message is now:

```
Running "requirejs:build" (requirejs) task
>> Error: SyntaxError: syntax error in /Volumes/b5 Data1/PhET/GitHub/rutherford-scattering/js/../images/license.json
>> In module tree:
>>     rutherford-scattering-main
>>       RUTHERFORD_SCATTERING/rutherfordatom/RutherfordAtomScreen
>>         image
>> 
>>     at Object.parse (native)
```

**Comment by pixelzoom** [comment]
There are 5 other places in chipper where JSON.parse is called. So I've noted this as a general problem in https://github.com/phetsims/chipper/issues/450.

@samreid could you take a quick look to verify that this solution is acceptable?

**Comment by samreid** [comment]
I've never used this strategy before:

```js
      if ( err instanceof SyntaxError ) {
        err.message = 'syntax error in ' + licenseFilename;
      }
```

Is it a standard approach to mutate error messages?

Also, I would move `var json=null` out of the try block for clarity (even though I know scoping works with it declared in the try block).

Also, throwing errors doesn't seem consistent with the rest of our error checking and handling.  Why not use assert in this case, to be consistent?

**Comment by pixelzoom** [comment]
> Is it a standard approach to mutate error messages?

I tried wrapping the caught Error in a new Error, but that resulted in a very long, irrelevant error message.  I don't know if mutating error messages is a standard approach. But in this case it seemed warranted, since the error message is useless.  

> Also, I would move var json=null out of the try block for clarity (even though I know scoping works with it declared in the try block).

Done.

> Also, throwing errors doesn't seem consistent with the rest of our error checking and handling. Why not use assert in this case, to be consistent?

I think that's because we're not very good about handling errors that could be thrown.  Assert is appropriate for verifying a return value or state; it's not appropriate for catching and handling an error.

**Comment by pixelzoom** [comment]
Rather than mutating the caught Error, I changed to throwing a new Error:

```js
 // read license.json
    var fileContents = global.phet.chipper.fs.readFileSync( licenseFilename, 'utf8' );
    var json = null;
    try {
      json = JSON.parse( fileContents );
    }
    catch( err ) {
      if ( err instanceof SyntaxError ) {
        throw new SyntaxError( 'syntax error in '+ licenseFilename );
      }
      else {
        throw err;
      }
    }
```

The resulting message now identifies the correct source file:

```
Running "requirejs:build" (requirejs) task
>> Error: SyntaxError: syntax error in /Volumes/b5 Data1/PhET/GitHub/rutherford-scattering/js/../images/license.json
>> In module tree:
>>     rutherford-scattering-main
>>       RUTHERFORD_SCATTERING/rutherfordatom/RutherfordAtomScreen
>>         image
>> 
>>     at getLicenseEntry (eval at <anonymous> (/Volumes/b5 Data1/PhET/GitHub/rutherford-scattering/node_modules/requirejs/bin/r.js:26191:38), <anonymous>:46:15)
Warning: Task "requirejs:build" failed. Use --force to continue.
```

@samreid Is this acceptable?

**Comment by samreid** [comment]
SyntaxError takes a "filename" argument, we should use it:

```
new SyntaxError([message[, fileName[, lineNumber]]])
```
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError

**Comment by pixelzoom** [comment]
Changing to 

`throw new SyntaxError( 'syntax error', licenseFilename );`

results in this message, which no longer identifies the filename.

```js
Running "requirejs:build" (requirejs) task
>> Error: SyntaxError: syntax error
>> In module tree:
>>     rutherford-scattering-main
>>       RUTHERFORD_SCATTERING/rutherfordatom/RutherfordAtomScreen
>>         image
>> 
>>     at getLicenseEntry (eval at <anonymous> (/Volumes/b5 Data1/PhET/GitHub/rutherford-scattering/node_modules/requirejs/bin/r.js:26191:38), <anonymous>:47:15)
Warning: Task "requirejs:build" failed. Use --force to continue.
```

Whatever is printing the error (grunt?) doesn't seems limited in what error information it prints. So I've changed to throwing a vanilla Error:

`throw new Error( 'syntax error in '+ licenseFilename );`

**Comment by pixelzoom** [comment]
Ah... Now the message is missing the description of the syntax error ("Unexpected token }").  I will revise to include that.

**Comment by pixelzoom** [comment]
`throw new Error( 'syntax error in ' + licenseFilename + ': ' + err.message );`

which (for rutherford-scattering) results in this message, which identifies the json file and specific syntax error. 

```
>> Error: Error: syntax error in /Volumes/b5 Data1/PhET/GitHub/rutherford-scattering/js/../images/license.json: Unexpected token }
>> In module tree:
>>     rutherford-scattering-main
>>       RUTHERFORD_SCATTERING/rutherfordatom/RutherfordAtomScreen
>>         image
>> 
>>     at getLicenseEntry (eval at <anonymous> (/Volumes/b5 Data1/PhET/GitHub/rutherford-scattering/node_modules/requirejs/bin/r.js:26191:38), <anonymous>:47:15)
```

Back to @samreid for review.

**Comment by samreid** [comment]
Code inspection looks good, error after introducing a syntax error looks good, error when file is non-existent looks good, closing.
