### ISSUE TITLE
grunt should automatically build the phet-io version for instrumented sims

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#451]
See https://github.com/phetsims/phet-io/issues/341

We could add an entry to package.json that indicates whether it is phet-io instrumented.  Then grunt should automatically build both.

**Comment by samreid** [comment]
Charges and Fields may be the first simulation that gets published with both brands.

**Comment by samreid** [comment]
When https://github.com/phetsims/phet-io/issues/370 and this issue are complete, all sims will build both brands.

**Comment by samreid** [comment]
I'm concerned about this because of the following:

* the phet-io build takes twice as long as the standard build
* the composite build makes it difficult to see errors from the individual builds
* it seems difficult (impossible?) to run both builds in the same process because of globals used for brands and possibly other state

Let's chat about this before proceeding.

**Comment by samreid** [comment]
If we can fix the "error propagation" issue, then perhaps we could make it so that phet-io instrumented sims automatically use it (maybe there is a way to opt out) and still use grunt forking without rewriting chipper.

This seems like it will become much more important when we are ramping up on the number of sims that are instrumented or deploying them much more frequently.

**Comment by samreid** [comment]
We decided it does not yet make sense to deploy phet-io ones every time, so let's leave these as separate for now.

**Comment by samreid** [comment]
@mattpen and I concluded that phet-io deploys and phet deploys should remain separate for the foreseeable future.  Closing.

**Comment by samreid** [comment]
On second thought, it is nice to use phet-io for testing the production sims, and perhaps we will get to a point where these can be developed and deployed together.

**Comment by pixelzoom** [comment]
Definitely related to #567 (Build PhET and PhET-iO brands together).

**Comment by samreid** [comment]
Meeting consensus: Versions will stay in step, we will build both together, but we don't necessarily need to test or deploy both together.

**Comment by samreid** [comment]
Closing this issue, we will tackle the automated builds in https://github.com/phetsims/chipper/issues/616
