### ISSUE TITLE
Add an eslint rule to check for uses of native constructors

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/chipper#454]
`image` and `text` are native to HTML5, and both have constructors that match Image and Text nodes of scenery.  Because of this, it is easy to forget to include Image and Text in modules, and the resulting error is difficult to recognize if one is not familiar with it.

@andrewadare suggested that we include a linting rule that can check for missing `Text` and `Image` modules.  In 3/24/16 dev meeting, we discussed and decided that this was something that could be worked on by @andrewadare and @jessegreenberg.

This tool would be helpful to those that are learning the PhET codebase.  Once one is familiar with this error, it is standard to look for missing `Image` and `Text` modules, so adding a low priority tag.

**Comment by jessegreenberg** [comment]
When forgetting to require a scenery Node for Text or Image one might see this error:
```
Picker.js?bust=1481581388148:443 Uncaught TypeError: Cannot read property 'selfPruned' of undefined(…)
```

The above lint rule will catch it like this:
```
C:\Users\Jesse\Documents\Development\phetsims\balloons-and-static-electricity\js\balloons-and-static-electricity\view\ControlPanel.js
  148:15  warning  using HTML Text instead of scenery Node  no-html-constructors
  153:15  warning  using HTML Text instead of scenery Node  no-html-constructors
  158:15  warning  using HTML Text instead of scenery Node  no-html-constructors
  261:7   warning  using HTML Text instead of scenery Node  no-html-constructors
  262:7   warning  using HTML Text instead of scenery Node  no-html-constructors

✖ 5 problems (0 errors, 5 warnings)


Done.
```

**Comment by jessegreenberg** [comment]
Added the rule to eslintrc.  It caught 1 legitimate use case in a sim wrapper, but I disabled the rule for that case. Closing.

**Comment by pixelzoom** [comment]
Reopening.  

The way that this was implemented makes it specific to scenery types. I.e.:

```js
58            message: 'using HTML ' + node.callee.name + ' instead of scenery Node'
``` 

And there are other types that this rule could (and should) be applied to. For example, I discovered this deficiency while attempting to add `DOT.Range`, because `Range` is also a native function.

**Comment by pixelzoom** [comment]
The current implementation is also hardcoded for `Image` and `Text`. I.e.:

```js
16  var calleeModulePathMap = {
17    Image: '\'SCENERY/nodes/Image\'',
18    Text: '\'SCENERY/nodes/Text\''
18  };
...
38      if ( node.callee && 
39           node.callee.name &&
40          node.callee.name === 'Image' ||
41           node.callee.name === 'Text' ) {
```

The `if` expression should contain a general test, e.g. `calleeModulePathMap.hasOwnProperty( node.callee.name )`.

**Comment by pixelzoom** [comment]
There's another flaw in the current implementation.  If a PHET type references itself inside of its .js file, then there will be no `requirejs` statement.  And this will be flagged as an error.  `DOT.Range` is an example.

**Comment by pixelzoom** [comment]
I disabled the lint rule for the case where Range is calling its own constructor, see commits above.  I'm not sure if this qualifies as a workaround or a permanent fix.

**Comment by pixelzoom** [comment]
Also, an efficiency question, concerning this `for` loop:

```js
        source.tokensAndComments.forEach( function( token ) {
          if ( token.value === modulePath ) {
            usingModule = true;
          }
        } );
```

Once we've set `usingModule = true`, this continues to examine tokens. Is that necessary, or can we stop as soon as we've found the module?

**Comment by jessegreenberg** [comment]
I read through http://eslint.org/docs/developer-guide/working-with-rules a bit more, there are two features of eslint rules that I was not aware of.

1 - In one eslint rule you can define behavior for multiple AST nodes.
2 - The AST is traversed twice, first down then up, and you can specify on which direction of traversal you want a function to be called.

So we should be able to check for the case mentioned in https://github.com/phetsims/chipper/issues/454#issuecomment-269885878 by searching for any AST node that could represent the declaration of a type that shares a name with a native JavaScript constructor.  And for https://github.com/phetsims/chipper/issues/454#issuecomment-269886968 we shouldn't need to search through tokens since eslint will come back up the AST a second time.

**Comment by jessegreenberg** [comment]
I changed the implementation to follow https://github.com/phetsims/chipper/issues/454#issuecomment-270252876.

The rule now works like this:
 - On the traversal down the AST, we search for function and variable declarations for types that have the same name as native JavaScript constructors like Image, Text, and Range, and store them.
 - On the traversal back up the AST, we search for instantiations of these types, and verify that its type was defined.

It doesn't matter where the type comes from.  It could be Scenery or Dot or a constructor in its own file (like ```DOT.Range```).  We are no longer looking through tokens so https://github.com/phetsims/chipper/issues/454#issuecomment-269886968 should be addressed.

@pixelzoom would you like to review?

**Comment by pixelzoom** [comment]
Work great. But this map:

```js
  var typeMap = {
    Image: 'Image',
    Range: 'Range',
    Text: 'Text'
  };
```

... is redundant.  A simple array is now sufficient:

```js
  var nativeConstructors = [ 'Image', 'Range', 'Text' ];
```

Changed and tested in the above commit. @jessegreenberg please review.

**Comment by jessegreenberg** [comment]
Yes, good point, thanks.  I tested it again, and verified it is still working.  I also like the improvement to the output message.  Closing.
