### ISSUE TITLE
grunt deploy-production should not copy locally built file to dev server

### ISSUE THREAD

**Issue by jbphet** [phetsims/chipper#455]
As of this writing, when `grunt deploy-production` is performed, the build server is used to build the production version, but the built version that results is not copied to the dev server (currently spot).  Instead, the version on the developer's local machine is copied.  For `grunt deploy-rc`, the version built by the build server **is** copied to the dev server.  Not sure why this is different, but `deploy-production` should be changed to act the same as `deploy-rc` in this regard.

I looked through the code, and I think the changes would be in Gruntfile.js for the deploy-production task.

This issue is closely related to https://github.com/phetsims/perennial/issues/17 and both issues will need to be addressed at the same time.

**Comment by jonathanolson** [comment]
I believe this is done. @mattpen can you confirm?

**Comment by mattpen** [comment]
Yes, in chipper 2.0 both deploys are completed by the build-server.
