### ISSUE TITLE
Add memory tests

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#456]
We could add tests that (a) run gc and (b) snapshot used heap size, to plot the memory used as a function of time for all our sims, to understand memory usage and visualize leaks across sims.

The tests could be integrated into the automated fuzz tester.

This could be useful when we are doing larger searches for memory leaks in sims.

Assigning to @ariel-phet to prioritize and reassign.

**Comment by ariel-phet** [comment]
@samreid does this seem necessary now that we seem to be publishing new sims without memory leaks, and testing for memory leaks is part of the code review (so in theory each new sim going out should remain "leak free")?

**Comment by ariel-phet** [comment]
If you no longer see a need, feel free to close.

**Comment by samreid** [comment]
The programmatic access to the GC has not been reliable, it tends to show max allocated not current allocated, so let's close this issue and rely on manual testing.
