### ISSUE TITLE
improve error handling for missing entry in sherpa/lib/license.json

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#458]
If you attempt to use a sherpa library that doesn't have an entry in sherpa/lib/license.json, then you get this incredibly useless error message from `grunt build`:

> Running "after-requirejs-build" task
Fatal error: Cannot read property 'dependencies' of undefined

**Comment by pixelzoom** [comment]
Fixed. 

I removed the entry for BigInteger from license.json.  Here's the new error message:

> Running "after-requirejs-build" task
Fatal error: sherpa/lib/license.json: no entry for key = BigInteger-cda5bcc.js

**Comment by pixelzoom** [comment]
Assigned to @samreid for review, since he's the other author of this source file.

**Comment by samreid** [comment]
I reviewed the diff and it seemed nice, closing.
