### ISSUE TITLE
there is a potentially redundant call to decodeURIComponent in chipper-strings-setup.js

### ISSUE THREAD

**Issue by jbphet** [phetsims/chipper#459]
An issue was recently found where alternate strings that were passed in to simulations through the query parameters were being run through ```decodeURIComponent``` twice, and this was causing problems for any strings that contained a per cent symbol, see https://github.com/phetsims/rosetta/issues/115.  I was discussing this issue with @pixelzoom, and he searched through the code and found a call in chipper-strings-setup.js that appeared to be doing the same thing, i.e. calling ```decodeURIComponent``` on strings that probably had already had it called on them.  The code looks like this:
```js
  var stringOverrides = JSON.parse( decodeURIComponent( phet.chipper.getQueryParameter( 'strings' ) || '{}' ) );
```
I did a little looking around to see what chipper-strings-setup is used for, and it appears to be involved in the process of creating locale-specific HTML files.  @jonathanolson created it originally, so rather than spending much more time on it myself, I'm assigning it to him to determine whether the call to ```decodeURIComponent``` in this file should also be removed.

**Comment by jonathanolson** [comment]
Fixed.
