### ISSUE TITLE
sherpa/lib/license.json is repeated 6 times

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#460]
Noted while working on #458.

sherpa/lib/license.json is repeated 6 times as a string literal, while constant THIRD_PARTY_LICENSES_FILENAME is for the loading the file.

**Comment by pixelzoom** [comment]
Assigned to @samreid for review, since he's the other author of this source file.

**Comment by samreid** [comment]
The diff seems reasonable, and the grunt task is undisturbed, closing.
