### ISSUE TITLE
Add ESLint rule to forbid property access in require statement

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#461]
From https://github.com/phetsims/scenery-phet/issues/233#issuecomment-210040056

> (3) var linear = require( 'DOT/Util' ).linear; We have discouraged this type of import.

We could add an ESLint rule for this.

**Comment by samreid** [comment]
I added this rule above, will flag for developer meeting to discuss whether we should enable the rule.

**Comment by samreid** [comment]
Consensus: let's add the rule.  @samreid will continue and report back if there are too many or too complex problems.

**Comment by pixelzoom** [comment]
The source file is named no-attributes-in-require-statement.js, the doc refers to "property access", and the error message refers to "Property" (which is confusable with axon.Property).  Let's standardized on terminology. Eg, no-property-in-require-statement.js and "property" in error message.

**Comment by samreid** [comment]
Sounds good, will do.

**Comment by samreid** [comment]
I fixed a number of cases above and am running the test server now.

**Comment by samreid** [comment]
Seems like most cases are passing nicely.  Acid base solutions had a hiccup which I cannot reproduce:

![image](https://cloud.githubusercontent.com/assets/679486/14828263/75a469d6-0ba3-11e6-8c12-f634a73853cf.png)

**Comment by pixelzoom** [comment]
Was there an error message associated with the above mentioned ABS hiccup?

**Comment by samreid** [comment]
![image](https://cloud.githubusercontent.com/assets/679486/14828386/03e0765e-0ba4-11e6-93e2-ab1cf8091d09.png)

**Comment by pixelzoom** [comment]
I can't reproduce either. This is what I would expect if you ran `grunt` twice. First grunt fails when second grunt runs clean and min.js file no longer exists.

**Comment by samreid** [comment]
Perhaps the build server was over-zealous 😼

**Comment by samreid** [comment]
Tests seems good so far.
![image](https://cloud.githubusercontent.com/assets/679486/14828890/20c90414-0ba6-11e6-993e-d9070533d634.png)

> for-each.sh active-repos grunt lint
reveals problems in rosetta and a few other sims that look like they have pre-existing lint issues (not going to tackle them now).

**Comment by samreid** [comment]
I'll leave this assigned to me to rename to "property" instead of "attribute" once tests finish.

**Comment by samreid** [comment]
I think my test server gave up, it shows two exited commands in a row.

**Comment by samreid** [comment]
Rule renamed above.  I'll close the issue.  @jonathanolson @jbphet @pixelzoom @andrewadare @mattpen @jessegreenberg please report any problems you discover as a new issue.
