### ISSUE TITLE
preloads are all on one long line in development html file

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#462]
This was noticed while debugging a dependency that was added to function-builder.

`grunt generate-development-html` generates html as one long line, reproduced here for your scrolling enjoyment:

```js
var preloads = ( brand === 'phet-io' ) ? [ '../sherpa/lib/jquery-2.1.0.js', '../sherpa/lib/lodash-2.4.1.js', '../sherpa/lib/FileSaver-b8054a2.js', '../assert/js/assert.js', '../chipper/js/initialize-globals.js', '../sherpa/lib/seedrandom-2.4.2.js', '../sherpa/lib/BigInteger-cda5bcc.js', '../sherpa/lib/BigRational-8f8c2fa.js', '../sherpa/lib/Tween-r12.js', '../sherpa/lib/jsondiffpatch-0.1.31.js', '../phet-io/js/phetio.js', '../phet-io/js/SimIFrameAPI.js', '../phet-io/js/phetioEvents.js', '../phet-io/js/datamite.js', '../phet-io/js/api/PhETIOCommon.js', '../phet-io/js/finishedPreloads.js' ] : [ '../sherpa/lib/jquery-2.1.0.js', '../sherpa/lib/lodash-2.4.1.js', '../sherpa/lib/FileSaver-b8054a2.js', '../assert/js/assert.js', '../chipper/js/initialize-globals.js', '../sherpa/lib/seedrandom-2.4.2.js', '../sherpa/lib/BigInteger-cda5bcc.js', '../sherpa/lib/BigRational-8f8c2fa.js', '../sherpa/lib/Tween-r12.js' ];
```

Problems with having this all on one long line:

(1) It's difficult to inspect.
(2) It's a conditional, and it's difficult to compare the `then` and `else` values.

BETTER: This would be better, `then` and `else` values on separate lines, scrolling still required:

```js
    var preloads = ( brand === 'phet-io' ) ?
      [ '../sherpa/lib/jquery-2.1.0.js', '../sherpa/lib/lodash-2.4.1.js', '../sherpa/lib/FileSaver-b8054a2.js', '../assert/js/assert.js', '../chipper/js/initialize-globals.js', '../sherpa/lib/seedrandom-2.4.2.js', '../sherpa/lib/BigInteger-cda5bcc.js', '../sherpa/lib/BigRational-8f8c2fa.js', '../sherpa/lib/Tween-r12.js', '../sherpa/lib/jsondiffpatch-0.1.31.js', '../phet-io/js/phetio.js', '../phet-io/js/SimIFrameAPI.js', '../phet-io/js/phetioEvents.js', '../phet-io/js/datamite.js', '../phet-io/js/api/PhETIOCommon.js', '../phet-io/js/finishedPreloads.js' ] :
      [ '../sherpa/lib/jquery-2.1.0.js', '../sherpa/lib/lodash-2.4.1.js', '../sherpa/lib/FileSaver-b8054a2.js', '../assert/js/assert.js', '../chipper/js/initialize-globals.js', '../sherpa/lib/seedrandom-2.4.2.js', '../sherpa/lib/BigInteger-cda5bcc.js', '../sherpa/lib/BigRational-8f8c2fa.js', '../sherpa/lib/Tween-r12.js' ];
```

BEST: Something like this would be best, human readable, no scrolling required:

```js
    var preloads = ( brand === 'phet-io' ) ? [ 
      '../sherpa/lib/jquery-2.1.0.js', 
      '../sherpa/lib/lodash-2.4.1.js', 
      '../sherpa/lib/FileSaver-b8054a2.js', 
      '../assert/js/assert.js', 
      '../chipper/js/initialize-globals.js', 
      '../sherpa/lib/seedrandom-2.4.2.js', 
      '../sherpa/lib/BigInteger-cda5bcc.js', 
      '../sherpa/lib/BigRational-8f8c2fa.js', 
      '../sherpa/lib/Tween-r12.js', 
      '../sherpa/lib/jsondiffpatch-0.1.31.js', 
      '../phet-io/js/phetio.js', 
      '../phet-io/js/SimIFrameAPI.js', 
      '../phet-io/js/phetioEvents.js', 
      '../phet-io/js/datamite.js', 
      '../phet-io/js/api/PhETIOCommon.js', 
      '../phet-io/js/finishedPreloads.js'
    ] : [ 
      '../sherpa/lib/jquery-2.1.0.js', 
      '../sherpa/lib/lodash-2.4.1.js', 
      '../sherpa/lib/FileSaver-b8054a2.js', 
      '../assert/js/assert.js', 
      '../chipper/js/initialize-globals.js', 
      '../sherpa/lib/seedrandom-2.4.2.js', 
      '../sherpa/lib/BigInteger-cda5bcc.js', 
      '../sherpa/lib/BigRational-8f8c2fa.js', 
      '../sherpa/lib/Tween-r12.js'
    ];
```

**Comment by pixelzoom** [comment]
For now, I went with the "BETTER" approach above, since it involved a trivial change to the sim-development.html template.  Implementing the "BEST" approach would require reworking `stringifyArray` in generateDevelopmentHTML.js.

**Comment by pixelzoom** [comment]
@samreid do you think it's worth the effort to implement the "BEST" approach above?

**Comment by samreid** [comment]
Yes, I'd prefer single line per preload.  I've had to inspect these manually in the past and it has been a hassle.

**Comment by pixelzoom** [comment]
"BEST" approach implemented. Required a bit of ugly fixed indentation in `stringifyArray`, but I documented it. 

@samreid can you please review and test drive?

**Comment by pixelzoom** [comment]
Example in https://github.com/phetsims/function-builder/commit/fc278b4a0d463a5dc1ce7f0e74818c492b738f26 (function-builder).

**Comment by samreid** [comment]
I ran `grunt generate-development-html` on circuit-construction-kit and manually inspected the diff.  It looks great.  I read through the code change in generateDevelopmentHTML.js and all seems well.  Should I run this command?
`for-each.sh active-runnable grunt generate-development-html`

**Comment by pixelzoom** [comment]
I'm ambivalent about whether to update all development html files.  Tagged for developer meeting discussion to see if anyone has a strong opinion.

**Comment by samreid** [comment]
> I'm ambivalent about whether to update all development html files.

I think we should update all of them, I can't think of any reason not to.  Let's get a 3rd opinion and proceed.

@jessegreenberg @jbphet @jonathanolson can one of you weigh in here?

**Comment by jonathanolson** [comment]
I think we should regenerate all of them.

**Comment by samreid** [comment]
thanks @jonathanolson, I'll proceed.

**Comment by samreid** [comment]
blackbody-spectrum was stale, gene-expression-basics was stale, litmus was very old (I skipped that one), same with optics-lab, sugar-and-salt-solutions.  I'll commit the rest.

**Comment by samreid** [comment]
Next I'll update the staler ones, and test more thoroughly.

**Comment by samreid** [comment]
I updated optics lab.  Skipped litmus test because I was missing dependencies.  @pixelzoom you may update litmus if you wish.

**Comment by pixelzoom** [comment]
litmus updated. 

Closing.
