### ISSUE TITLE
branch: phet-io-require

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#466]
See https://github.com/phetsims/phet-io/issues/436

This is a temporary branch until the work is completed and merged into master or we identify a reason this strategy cannot work and the branch is abandoned/deleted.

**Comment by pixelzoom** [comment]
Please add a short explanation of this branch to this issue. We now have branches named phet-io-require and phet-io-require-2, and the issues that describe them both point to phetsims/phet-io#436. Not a fan of having to read through that issue to figure out what these branches are for, how they differ, etc. Thanks.

**Comment by pixelzoom** [comment]
Or link to a comment in phetsims/phet-io#436 that clearly describes the branches, their differences, which repos have this branch, etc.

**Comment by samreid** [comment]
I wrote a description here: https://github.com/phetsims/phet-io/issues/439#issuecomment-219617170

**Comment by samreid** [comment]
Branch deleted, closing.
