### ISSUE TITLE
branch: phet-io-require-2

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#467]
See https://github.com/phetsims/phet-io/issues/436

**Comment by pixelzoom** [comment]
Please add a short explanation of this branch to this issue. We now have branches named phet-io-require and phet-io-require-2, and the issues that describe them both point to phetsims/phet-io#436. Not a fan of having to read through that issue to figure out what these branches are for, how they differ, etc. Thanks.

**Comment by samreid** [comment]
I wrote a description here: https://github.com/phetsims/phet-io/issues/439#issuecomment-219617170

**Comment by samreid** [comment]
Branch merged to master and deleted, closing.
