### ISSUE TITLE
What is our position on relative imports?

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#469]
It appears that relative imports work properly.  For instance, in Hooke's Law EnergyScreen.js, there is the following code:
```js
  var EnergyModel = require( 'HOOKES_LAW/energy/model/EnergyModel' );
  var EnergyView = require( 'HOOKES_LAW/energy/view/EnergyView' );
```

It appears to work equally well in require mode and built mode if you use a relative import (tested in Chrome on OS X):
```js
  var EnergyModel = require( './model/EnergyModel' );
  var EnergyView = require( './view/EnergyView' );
```

As far as I know, we have always been using absolute paths in require statements.  However, it seems to me there is some merit in using a relative path because it makes it clear when something is nested in a subpackage.  Are there disadvantages?  Should we permit both strategies?  Or recommend one over another?

Marking for discussion at next developer meeting.

**Comment by samreid** [comment]
> Are there disadvantages?

Copy-pasting code is less likely to work, if you copy a relative path to a different location.

**Comment by jonathanolson** [comment]
Interesting. It doesn't change the string keys?

**Comment by samreid** [comment]
At today's meeting we decided to stick with absolute paths in require statements, for clarity and ease of moving the code.
