### ISSUE TITLE
grunt deploy-dev incorrectly reports success

### ISSUE THREAD

**Issue by andrewadare** [phetsims/chipper#470]
I had a stale entry in ~/.ssh/known_hosts for spot.colorado.edu, which prevented me from logging in directly.

When running `grunt deploy-dev`, it said "Done, without errors" but the sim was not uploaded. Can we propagate the scp return code through grunt to the user (or whatever tool is used for the transfer)? I didn't look at the code for the task.

**Comment by samreid** [comment]
This issue is similar to https://github.com/phetsims/chipper/issues/468

**Comment by andrewadare** [comment]
If #468 can be closed, this should also be closed.
