### ISSUE TITLE
robustness issues with 'grunt deploy-dev'

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#473]
A couple of problems with `grunt deploy-dev`:

(1) It doesn't verify whether the destination directory already exists.

(2) If the destination directory does exist, the files are not overwritten. Instead, you end up with a `build/` directory inside the destination directory.

**Comment by samreid** [comment]
Is this fixed?  I tried dev deploying once this week without updating package.json and received an error telling me that version already existed.

**Comment by jessegreenberg** [comment]
@mattpen was this fixed?  Comments in #581 indicate that it might be.

**Comment by pixelzoom** [comment]
11/2/17 dev meeting: This has indeed already been fixed, closing.
