### ISSUE TITLE
all published sims should have the screenshot capability without requiring query parameter

### ISSUE THREAD

**Issue by jbphet** [phetsims/chipper#475]
At the ISTE conference, @phet-steele and @ariel-phet noticed that a number of simulations don't have the screenshot capability in the menu, at least not without having a ```screenshot``` query parameter.  They were surprised by this and thought all sims had the capability by default.  We should discuss at next developer meeting to understand if this somehow went away, or just wasn't published yet on a number of sims, and determine a plan of action.

**Comment by ariel-phet** [comment]
@phet-steele please identify which sims do not have the screenshot in the menu and put a checklist here in this issue

**Comment by ariel-phet** [comment]
Also please note, if there is not screenshot option, check if screenshot works with the query quarameter

**Comment by phet-steele** [comment]
All sims work with `?screenshot`
- [ ] Acid-Base Solutions
- [ ] Arithmetic
- [ ] Balancing Act
- [ ] Balancing Chemical Equations
- [ ] Balloons and Static Electricity
- [ ] Beer's Law Lab
- [ ] Bending Light
- [ ] Color Vision
- [ ] Concentration
- [ ] Faraday's Law
- [ ] Fraction Matcher
- [ ] Friction
- [ ] Graphing Lines
- [ ] Gravity Force Lab
- [ ] Hooke's Law
- [ ] John Travoltage
- [ ] Least-Squares Regression
- [ ] Molarity
- [ ] Molecules and Light
- [ ] Molecule Shapes
- [ ] Molecule Shapes: Basics
- [ ] Neuron
- [ ] Ohm's Law
- [ ] pH Scale
- [ ] pH Scale: Basics
- [ ] Reactants, Products and Leftovers
- [ ] Resistance in a Wire
- [ ] Trig Tour
- [ ] Wave on a String

**Comment by phet-steele** [comment]
Beer's Law Lab and Concentration recently re-published and now have the Screenshot feature.

**Comment by ariel-phet** [comment]
marking for next dev meeting to see when we can schedule a maintenance release

**Comment by ariel-phet** [comment]
Tentatively scheduled for week of July 25

**Comment by jbphet** [comment]
This was discussed in the 5/7/2016 developer meeting, and we **think** that the code should be changed so that the screenshot capability exists without the presence of the ```screenshot``` query parameter, but it should **not** be available in the presence of the ```phet-app``` query parameter.  However, there is some question about whether we actually **do** what the screenshot capability in the app.  So, @mattpen is going to test this in the app by temporarily removing the ```phet-app``` query parameter in the app and report back, then we'll decide for sure exactly what the patch for the maintenance release should be.  I'm adding @mattpen to the list of assignees and leaving this tagged for discussion in the next dev meeting.

**Comment by mattpen** [comment]
@jbphet - Taking a screenshot with the phet menu appears to fail silently on the phet app.  In the XCode console, the following error is thrown:

```2016-07-08 00:06:31.576 PhET Interactive Simulations[2379:4674981] -canOpenURL: failed for URL: "blob:https://phet.colorado.edu/77f3a0f4-27ff-4dbc-abf5-3358b63a7137" - error: "This app is not allowed to query for scheme blob"```

**Comment by mattpen** [comment]
I have whitelisted the "blob" scheme in the phetapp configuration, but it is still giving the same error.

I also tried the screenshot in mobile safari and chrome on the iPad Mini.  In Mobile safari, it opens the screenshot in a new tab.  In Chrome, it opens a new blank tab.

**Comment by ariel-phet** [comment]
We are going to assume no screenshot in the app, closing.

**Comment by jbphet** [comment]
@ariel-phet - did you really mean to close this issue?  As far as I know the maintenance release is still needed, we've just resolved the question of whether or not the screenshot capability should continue to be disabled in the app.

**Comment by ariel-phet** [comment]
@jbphet -oops, I think I was reading the last comment thinking this was a separte issue. Correct, maintenance release is still needed. Thanks for verifying!

**Comment by jbphet** [comment]
For reference, the commit where this feature was turned on permanently in Joist is https://github.com/phetsims/joist/commit/b32cec92eff9878f953ba0d7454b1dbc01f2952f, and later an additional clause was added to prevent the menu item from showing up in the app, see https://github.com/phetsims/joist/commit/ecd8d968e09ee1be00a444a261a01d1b391422e2.

**Comment by jbphet** [comment]
All sims have been re-released with screenshots turned on with the exception of Neuron, where I noticed an issue before publication and waved off.  Two other simulations - Bending Light and Friction - were found by @phet-steele to have issues with the screenshot feature after publishing.  Issues have been logged for each, they are:
+ https://github.com/phetsims/neuron/issues/125
+ https://github.com/phetsims/bending-light/issues/350
+ https://github.com/phetsims/friction/issues/35

@phet-steele is in the process of verifying all published sims and will update this issue when done.  If all but the three mentioned above look good, this issue can be closed.

**Comment by phet-steele** [comment]
> If all but the three mentioned above look good, this issue can be closed.

This is the case.
