### ISSUE TITLE
test-server: fix buggy behavior/doc for "loadOnly" query param

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#478]
Skype:
[8/25/16, 3:23:48 PM] Chris Malley: Anyone know how to run test-server in a mode that only tests that each sim launches?
[8/25/16, 3:25:07 PM] Jonathan Olson: chipper/test-server/test-sims.html?loadOnly
[8/25/16, 3:43:13 PM] Chris Malley: chipper/test-server/test-sims.html?loadOnly appears to be also building the sims. Bug?
[8/25/16, 3:43:33 PM] Jonathan Olson: will also test load-only on build sims
[8/25/16, 3:43:37 PM] Jonathan Olson: can turn off the server part of it
[8/25/16, 3:43:40 PM] Jonathan Olson: if you only want them to require.js
[8/25/16, 3:44:05 PM] Chris Malley: Doc for loadOnly query param says: "// verify that sims start in requirejs mode, skip other tests".
[8/25/16, 3:44:16 PM] Chris Malley: Says nothing about built mode.
[8/25/16, 3:45:40 PM] Jonathan Olson: Then it's bad documentation?

**Comment by jonathanolson** [comment]
loadOnly was definitely originally meant to also try loading the built versions, since it's caught build-specific bugs quickly before. I propose we update the documentation. Sorry if I documented it incorrectly.

**Comment by pixelzoom** [comment]
I attempted to run test-server without running "node chipper/test-server/test-server.js".  After printing an error to the console:

> test-sims.js:115 GET http://localhost:45361/acid-base-solutions net::ERR_CONNECTION_REFUSED

... it continues to run.  Seems like if `?loadOnly` is specified, then it shouldn't be trying to connect to the server, or build anything.

**Comment by jonathanolson** [comment]
> Seems like if ?loadOnly is specified, then it shouldn't be trying to connect to the server, or build anything. The meaning of "loadOnly" seems pretty clear - it should load only, not "load and build only".

"It should only load the simulations (in all modes), but not do any mouse fuzzing after it loads. Instead go to the next simulation".

Should a 'requirejsOnly' flag be added, or should the loadOnly flag be renamed to better indicate its purpose? I don't mind renaming/adding things.

**Comment by pixelzoom** [comment]
I don't know where you're looking for documentation, but in test-sims.js:

```js
7 // verify that sims start in requirejs mode, skip other tests
8 var loadOnly = !!phet.chipper.getQueryParameter( 'loadOnly' );
```

So the documentation clear indicates requirejs mode, *not* both modes.

For this issue, let's fix either the documentation or the behavior.  

In general, we need a way to specify which specific tests we want to run, and for which modes. Something like:

```.../test-sims.html?mode=requirejs&tests=load```

mode: which mode to run in, 'build' or 'requirejs', defaults to both
tests: which tests to run, 'load', 'fuzz',..., default to all tests

**Comment by jonathanolson** [comment]
> So the documentation clear indicates requirejs mode, not both modes.

Understood, proper documentation was definitely lacking (my fault). It looks like the incorrect documentation was added in later (https://github.com/phetsims/chipper/commit/a01a8e0f000fd53eaba1cb0d912ae16521b6c2af), and my naming definitely didn't make the behavior clear (was originally just a tool for myself).

> For this issue, let's fix either the documentation or the behavior.

> In general, we need a way to specify which specific tests we want to run, and for which modes. Something like:

>> .../test-sims.html?mode=requirejs&tests=load

> where...

> mode = which mode to run in, 'build' or 'requirejs', defaults to both
> tests = which tests to run, 'load', 'fuzz',..., default to all tests

Sounds good and much more clear. If we plan to extend it, I would imagine we could have touch fuzzing or other tests (but probably just one test at a time?). Additionally, you can't fuzz unless you're also loading it (fuzz implies load), so maybe tests would be 'fuzzMouse', or 'none', with whatever default?

Flagged for developer meeting for approval (or to notify about pending changes).

**Comment by pixelzoom** [comment]
9/15/16 dev meeting: Skipped because @jonathanolson not present. Would be nice to have a concrete proposal for approval.

**Comment by pixelzoom** [comment]
@jonathanolson Based on discussion at 9/15/16 developer meeting, I think the expectation is that you're going to propose something prior to some developer meeting, which we can review and then discuss at a developer meeting.

**Comment by jonathanolson** [comment]
Possibly query parameters:

- test = 'fuzz' or 'none', determines what test is done after loading the simulation. Default fuzz?
- build = 'true' or 'false', determines if it should attempt to build the sims and test the built versions. Default true?

**Comment by jonathanolson** [comment]
- sim = <sim-name>, will only test a specific simulation.

**Comment by samreid** [comment]
We decided to use `sims` and use a comma separated list. QueryStringMachine can parse it.

**Comment by samreid** [comment]
@jonathanolson said he will finalize a proposal (not sure for API or implementation) that passes through the entire query string from wrapper to sim iframe.  I'll review it when it is ready.

**Comment by jonathanolson** [comment]
Proposal:
1. All query strings passed to the test server will be passed through to the simulations themselves, in addition to 'postMessageOnLoad' and 'postMessageOnError' which are used for load/error detection.
2. testTask='fuzzMouse' or 'none', default 'none' (potentially fuzzTouch added in the future)
3. testRequirejs='true' or 'false', default 'true'
4. testBuilt='true' or 'false', default 'true'
5. testSims=(comma-separated list of sims), default to active-runnables
6. testDuration=(milliseconds after load to test, if there is a testTask), default 30000
7. testFuzzRate=(actions per frame), default 100, will apply to fuzzMouse and in the future, fuzzTouch

Thoughts @samreid and @pixelzoom?

**Comment by samreid** [comment]
Perhaps an option to loop, so it can be used for continuous integration?

**Comment by pixelzoom** [comment]
Looks good. But isn't the current default `testTask=fuzzMouse` (not `none`)?

**Comment by jonathanolson** [comment]
> Looks good. But isn't the current default testTask=fuzzMouse (not none)?

Yes, I'm proposing changing the default, as we'll already need to change most links to the test-server to add thinks like ?ea.

**Comment by jonathanolson** [comment]
> Perhaps an option to loop, so it can be used for continuous integration?
> Perhaps options to email errors to a list?

Sounds like nice features to add, should we create separate issues for those? Or is aqua going to be the thing for continuous integration?

**Comment by samreid** [comment]
> Or is aqua going to be the thing for continuous integration?

Aqua will just be one part, please see https://github.com/phetsims/aqua/issues/2

**Comment by samreid** [comment]
@jonathanolson the proposal sounds good.

**Comment by samreid** [comment]
One more note about how this work relates to aqua.  The test wrapper proposed in https://github.com/phetsims/chipper/issues/478#issuecomment-249282054 could be used by aqua as one of its browser test pages (or possibly its primary test page).

**Comment by jonathanolson** [comment]
@pixelzoom, any other recommendations (and is the new default ok), or should I proceed with implementing the changes?

**Comment by samreid** [comment]
Should we move these test pages to aqua (which is dedicated to testing), or leave them here in chipper?  Issue management may be simpler if we move away from chipper.

**Comment by jonathanolson** [comment]
Moving to aqua sounds nice to me.

**Comment by jonathanolson** [comment]
@pixelzoom, can you see if the documentation (at aqua/test-server/README.md) should be improved, and see if the changes look good?

I've updated phettest.colorado.edu to the latest version.

**Comment by pixelzoom** [comment]
I read through (looks great), but didn't test drive the instructions. One minor edit in https://github.com/phetsims/aqua/commit/f44cf7deb0cfda30dff5f0f4d8e7f912d25dd18a. 

Back to @jonathanolson. Feel free to close if there's nothing left to do.

**Comment by jonathanolson** [comment]
Thanks!
