### ISSUE TITLE
pattern for getting query parameter values

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#479]
I'm creating this issue in chipper, since `phet.chipper.getQueryParameter` is defined in initialize-globals.js.  

It seems like we need a better API for getting values from query parameters. Especially since phet-io is likely to need more such parameters (e.g. https://github.com/phetsims/phet-io/issues/568, with query parameter added in @34c0572417fc4abe4fe7973e315c80ed0eb828a3).

`getQueryParameter` current returns either `undefined` or a string value.

For query parameters that have no value (present or not present), you do this:

```js
var myBoolean = !!getQueryParameter( 'myQueryParam' );
```

But be careful, because `?myQueryParam=false` will result in `true`.

For numbers, I've been doing this:

```js
var myInteger = getQueryParameter( 'myQueryParam' ) && parseInt( getQueryParameter( 'myQueryParam' ), 10 );
```

And all of the above require boilerplate error checking, if you really want to verify that the value is a boolean, integer, float, etc.  (Do we need to make PhET-iO robust in this respect?)

Is there a better way? Do we need `getQueryParameterBoolean`, `getQueryParameterInteger`, `getQueryParameterFloat`?

**Comment by pixelzoom** [comment]
9/1/16 dev meeting consensus: Need something like this, I'll propose an API.  Would be nice to be able to specify default value.

**Comment by samreid** [comment]
We also discussed a query parameter schema that could look like this:

```js
  var queryParameters = QueryParameters.parse( {
    height: {
      type: 'number',
      defaultValue: 6
    },
    name: {
      type: 'string',
      defaultValue: 'Larry',
      validate: function( str ) {
        assert && assert( allowedNames.indexOf( str ) >= 0 );
      }
    },
    isWebGL:{
      type:'flag'  // If no equals sign, then presence indicates true
                   // If there is an equals sign, then parse string as boolean
    },
    translationStrings: {
      type: 'Object',
      defaultValue: {},
      validate: function() {}
    }
  } );
  
  queryParameters.height // it is already a number
```

**Comment by pixelzoom** [comment]
+1 for something like what @samreid described in https://github.com/phetsims/chipper/issues/479#issuecomment-244177283.

Reassigning to @ariel-phet because (a) I'm unlikely to get to this anytime soon and (b) query parameters are part of the PhET-iO "toolkit".

**Comment by ariel-phet** [comment]
Remarking for dev meeting, but tentatively assigning to @andrewadare 

Please take a look at @samreid suggestion

**Comment by samreid** [comment]
@ariel-phet I'm also interested in working on this, could do sometime in the next couple of weeks.

**Comment by samreid** [comment]
I assigned @ariel-phet to see if he wants to assign this to me.

**Comment by ariel-phet** [comment]
Well then, if you are interested, SOLD! Assigning to @samreid 

@samreid up to you if you want to leave marked for dev meeting or not, or if you want to chew on it for a bit before having others take a look.

**Comment by samreid** [comment]
I'll unassign developer-meeting for now, then get feedback when I have a draft ready for review.

**Comment by samreid** [comment]
We could also support arrays like ?value=x&value=y and also checking that keys appear only once for non-array.

**Comment by samreid** [comment]
If this is developed as a global instead of requirejs module, it will be very easy to reuse in phet-io and other non-sim JS.

**Comment by samreid** [comment]
https://github.com/sindresorhus/query-string looks like a step in the right direction but doesn't provide defaults or correct types.

**Comment by samreid** [comment]
This one upconverts to arrays: https://github.com/jgallen23/querystring

**Comment by samreid** [comment]
It looks like "query string" is the correct technical term, but there are 10x as many google hits for "query parameters".

**Comment by samreid** [comment]
I think I'll create a new repo for this and make it export a global.  This will facilitate reuse in other contexts such as PhET-iO.

https://github.com/phetsims/query-string-machine

**Comment by samreid** [comment]
@pixelzoom does QueryStringMachine address all of the trouble you identified in this issue?  Shall we create any sub-issues for outstanding work?  Perhaps an issue for deprecating phet.chipper.getQueryParameter and porting to QueryStringMachine?

**Comment by pixelzoom** [comment]
> does QueryStringMachine address all of the trouble you identified in this issue? 

Yes.

> Shall we create any sub-issues for outstanding work? 

Looks like that's proceeding naturally in query-string-machine repo.

> Perhaps an issue for deprecating phet.chipper.getQueryParameter and porting to QueryStringMachine?

That's the only issue I can think of: https://github.com/phetsims/chipper/issues/486

Closing.
