### ISSUE TITLE
lint rule for parseInt?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#480]
[Documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt) for `parseInt` says:

>  Different implementations produce different results when a radix is not specified, usually defaulting the value to 10.

So we should be including the radix argument.  I've forgotten to do this on a number of occasions, and others seem to be doing this too.  See:

https://github.com/phetsims/circuit-construction-kit-common/issues/214
https://github.com/phetsims/john-travoltage/issues/116
https://github.com/phetsims/neuron/issues/128

... and some others that I fixed without creating issues.

Do we need a rule to verify that the `radix` argument is provided to `parseInt`?

**Comment by samreid** [comment]
Here is docs for eslint radix rule, @pixelzoom do you have an opportunity to try this out?
http://eslint.org/docs/rules/radix

**Comment by pixelzoom** [comment]
I added (and tested) the eslint radix rule in the above commit.

Then I noticed that the documentation at http://eslint.org/docs/rules/radix says:

> ECMAScript 5 changed the behavior of parseInt() so that it no longer autodetects octal literals and instead treats them as decimal literals. However, the differences between hexadecimal and decimal interpretation of the first parameter causes many developers to continue using the radix parameter to ensure the string is interpreted in the intended way.
> 
> On the other hand, if the code is targeting only ES5-compliant environments passing the radix 10 may be redundant. In such a case you might want to disallow using such a radix.

This seems to suggest that omitting the radix arg is not an issue for ES5.  Then again, "may be redundant" doesn't sound definitive, so it we may want to err on the side of safety and require the radix.   @samreid your opinion?

**Comment by samreid** [comment]
It seems easy and foolproof to require the radix, let's enforce it for now.

**Comment by pixelzoom** [comment]
Thanks. Closing.
