### ISSUE TITLE
_ is listed in .eslint as overwritable

### ISSUE THREAD

**Issue by andrewadare** [phetsims/chipper#482]
In .eslintrc, we have
```js
    // underscore, lodash
    "_": true,
```
It's the only global in the group with the overwritable attribute set to true. Is that intended? I suspect so, and I'm going to move it up with the others in that category.

**Comment by samreid** [comment]
> It's the only global in the group with the overwritable attribute set to true. Is that intended? I suspect so

I think it is from lines in chipper like:
```js
// 3rd-party packages
var _ = require( '../../../sherpa/lib/lodash-2.4.1.min' ); // eslint-disable-line require-statement-match
```

@andrewadare anything else to do here?

**Comment by andrewadare** [comment]
Nope, let's close it.
