### ISSUE TITLE
branch: progress-indicator

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#484]
To support https://github.com/phetsims/joist/issues/348

**Comment by samreid** [comment]
On hold while @jbphet reviews #348

**Comment by jbphet** [comment]
Just to be clear, @samreid is referring to https://github.com/phetsims/joist/issues/348.

**Comment by samreid** [comment]
Unassigning until November based on discussion in https://github.com/phetsims/special-ops/issues/40

**Comment by samreid** [comment]
Merged, deleted, closing.
