### ISSUE TITLE
add eslint rules for switch statements?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#485]
While working on plinko-probability, I encountered numerous cases (no pun intended) where `switch` statements had no `default` case. In a couple of cases, the code was relying on the `switch` being a no-op if none of the cases matched. In other (most) cases, it was just a blatant lack of error checking.

How do developers feel about enabling the eslint rule that requires a default case in switch statements, or an explicit commenting indicating that there is no default? 

See documentation of the eslint `default-case` rule at http://eslint.org/docs/rules/default-case.

**Comment by pixelzoom** [comment]
Specifically, this would involve adding the following line to the "rules" section of .eslintrc:

```js
"default-case": 2,
```

**Comment by pixelzoom** [comment]
The following repositories have one or more switch statements with no default case:

> energy-forms-and-changes
faradays-law
fraction-matcher
making-tens
neuron
states-of-matter
sun (buttons)
trig-tour

Reviewing these, none of them looks intentional or justified to my eye.  

I also see this `default` case in states-of-matter.MultipleParticlesModel:

```js
        default:
          break;
```

@jbphet Is this really what you intended? This leaves me wondering if the intent is really to use the default value of `triplePointInKelvin` for `MONATOMIC_OXYGEN` (the only molecule type that doesn't have a case), or whether this is a bug.   If it's not a bug, it would be better to have a case for `MONATOMIC_OXYGEN` and a default that does `throw Error( 'invalid molecule type: ' + this.currentMolecule )`.

**Comment by pixelzoom** [comment]
I've created a separate issue for the odd switch statements in states-of-matter.

**Comment by samreid** [comment]
Yes, switch statements should have default statements.  I'm also wondering if we should get rid of switch statements, because ternary or if statements are clearer and no chance of forgetting `break`:

![image](https://cloud.githubusercontent.com/assets/679486/18558416/41279398-7b30-11e6-92cd-be38397dae88.png)

If we must keep switch statements, let's also consider making `break` mandatory through a lint rule.

**Comment by pixelzoom** [comment]
The eslint for requiring a `break` is http://eslint.org/docs/rules/no-fallthrough.  As with the default-case rule, you can add a comment in situations where you intentionally want a fall through.

I'd be happy to add the no-fallthrough rule too.

**Comment by pixelzoom** [comment]
@samreid said:
> I'm also wondering if we should get rid of switch statements, because ternary or if statements are clearer and no chance of forgetting break

I'm not a fan of switch statements, and I generally try to avoid them (with 1 exception in graphing-lines). But there are 92 occurrences of "switch(" in PhET code, it seems that other developers find switch useful.  So I'll abstain from voting on whether to ban `switch`.

**Comment by samreid** [comment]
Here's a case where ternary is arguably better than switch (from Plinko):

SWITCH
```js
// @public (read-only) the ball's orientation within the bin
// Values are: -1 (left), 0 (center), 1 (right) or null (no ball are present)
this.binOrientation = 0;
switch ( this.binCount % 3 ) {

  // a multiple of three, Ball makes decision to be centered
  case 0:
    this.binOrientation = 0; // @public (read-only)
    break;

  // Ball makes probabilistic decision whether to end in left or right horizontal position in the bin
  case 1:
    this.binOrientation = ( phet.joist.random.nextBoolean() ? 1 : -1 );
    break;

  // the ball must take the opposite orientation than the last ball
  case 2:
    this.binOrientation = -lastBallBinOrientation;
    break;

  default:
    throw new Error( 'invalid binOrientation: ' + this.binOrientation );
}
```
CASE
```js
// @public (read-only) the ball's orientation within the bin
// Values are: -1 (left), 0 (center), 1 (right) or null (no ball are present)
this.binOrientation = this.binCount % 3 === 0 ? 0 : // Centered
                      this.binCount % 3 === 1 ? ( phet.joist.random.nextBoolean() ? 1 : -1 ) : // random direction
                      this.binCount % 3 === 2 ? -lastBallBinOrientation : // opposite direction than the last ball
                      assert && assert( false, 'invalid binOrientation: ' + this.binOrientation );
```

CASE WITH LINE BREAKS
```js
this.binOrientation =

    // Centered
  this.binCount % 3 === 0 ? 0 :

    // random direction
  this.binCount % 3 === 1 ? ( phet.joist.random.nextBoolean() ? 1 : -1 ) :

    // opposite direction than the last ball
  this.binCount % 3 === 2 ? -lastBallBinOrientation :
  
    // Illegal value for binCount
  assert && assert( false, 'invalid binOrientation: ' + this.binOrientation );
```

**Comment by pixelzoom** [comment]
I'm not a fan of ternary conditional statements unless they are dirt simple, like:

```var numberOfParticles = DEBUG ? 10 : 100;```

And I really dislike them when they're nested/chained like the example in https://github.com/phetsims/chipper/issues/485#issuecomment-247390037.

**Comment by pixelzoom** [comment]
No sims are currently failing the no-fallthrough rule, so nothing to fix.

**Comment by pixelzoom** [comment]
9/15/16 consensus: Add both rules.

**Comment by pixelzoom** [comment]
Rules have been added to .eslintrc, issues have been created for sims that are now failing lint. 

Closing.
