### ISSUE TITLE
how to prevent buggy 'preload' entries?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#489]
@jbphet had problems publishing an RC version of atomic-interactions.  He was unfortunate and picked up a buggy version of `build.json` where `"../query-string-machine/QueryStringMachine.js",` was added to `preload`, but the corresponding repository (query-string-machine) was not added to `phetLib` (see @b3db3fba23176be5de320a04ea4e18552da146eb).  

Because  `query-string-machine` was missing from `phetLib`, it wasn't added to `dependencies.json` during a build.  So on his next build attempt, he was missing that dependency. (The fact that the source file moved from `query-string-machine/QueryStringMachine.js` to `query-string-machine/js/QueryStringMachine.js` probably didn't help.)

Perhaps the build process should verify that, for every `preload`, its corresponding repository is in `phetLibs`?

**Comment by samreid** [comment]
> Perhaps the build process should verify that, for every `preload`, its corresponding repository is in `phetLibs`?

Yes, this sounds reasonable.  Here are the current preloads:

```js
[
      "../sherpa/lib/jquery-2.1.0.js",
      "../sherpa/lib/lodash-2.4.1.js",
      "../sherpa/lib/FileSaver-b8054a2.js",
      "../assert/js/assert.js",
      "../query-string-machine/js/QueryStringMachine.js",
      "../chipper/js/initialize-globals.js",
      "../phetcommon/js/analytics/google-analytics.js",
      "../sherpa/lib/seedrandom-2.4.2.js",
      "../sherpa/lib/game-up-camera-1.0.0.js"
    ]
```

We can split('/')[1] to take the directory name, but `sherpa` may need to be an exception case.

**Comment by pixelzoom** [comment]
Why might sherpa need to be an exception? It's included in phetLibs, and needs to be in dependencies.json.

**Comment by samreid** [comment]
My apologies, I missed it in phetLibs.

**Comment by pixelzoom** [comment]
TODO: Add validation in getBuildConfig.js.  After calling getPreload, foreach entry in array `buildConfig.preload`, extract the repository name and verify that it's in array `buildConfig.phetLibs`.

**Comment by pixelzoom** [comment]
9/22/16 dev meeting: I fixed it, @samreid volunteered to verify.

**Comment by samreid** [comment]
I instrumented the proposed code with the following console.log statements:

```js
  function validatePreload( preload, phetLibs ) {
    var missingRepositories = [];
    preload.forEach( function( entry ) {

      console.log( 'looking at preload: ' + entry );
      console.log( 'starts with: ' + entry.split( '/' )[ 0 ] );

      // preload entries should start with '..', e.g. "../assert/js/assert.js"
      assert( entry.split( '/' )[ 0 ] === '..', 'malformed preload entry: ' + entry );

      // the preload's repository should be in phetLib
      var repositoryName = entry.split( '/' )[ 1 ];

      console.log( 'repo name = ' + repositoryName );
      console.log( 'index1 = ' + phetLibs.indexOf( repositoryName ) );
      console.log( 'index2 = ' + missingRepositories.indexOf( repositoryName ) );
      if ( phetLibs.indexOf( repositoryName ) === -1 && missingRepositories.indexOf( repositoryName ) === -1 ) {
        missingRepositories.push( repositoryName );
      }
      console.log();
    } );
    assert( missingRepositories.length === 0,
      'phetLib is missing repositories required by preload: ' + missingRepositories.toString() );
  }
```

And observed this output during a FAMB build:

```
looking at preload: ../sherpa/lib/jquery-2.1.0.js
starts with: ..
repo name = sherpa
index1 = 14
index2 = -1

looking at preload: ../sherpa/lib/lodash-2.4.1.js
starts with: ..
repo name = sherpa
index1 = 14
index2 = -1

looking at preload: ../sherpa/lib/FileSaver-b8054a2.js
starts with: ..
repo name = sherpa
index1 = 14
index2 = -1

looking at preload: ../assert/js/assert.js
starts with: ..
repo name = assert
index1 = 0
index2 = -1

looking at preload: ../query-string-machine/js/QueryStringMachine.js
starts with: ..
repo name = query-string-machine
index1 = 11
index2 = -1

looking at preload: ../chipper/js/initialize-globals.js
starts with: ..
repo name = chipper
index1 = 4
index2 = -1

looking at preload: ../phetcommon/js/analytics/google-analytics.js
starts with: ..
repo name = phetcommon
index1 = 10
index2 = -1

looking at preload: ../sherpa/lib/seedrandom-2.4.2.js
starts with: ..
repo name = sherpa
index1 = 14
index2 = -1

looking at preload: ../sherpa/lib/game-up-camera-1.0.0.js
starts with: ..
repo name = sherpa
index1 = 14
index2 = -1

looking at preload: ../sherpa/lib/Tween-r12.js
starts with: ..
repo name = sherpa
index1 = 14
index2 = -1
```

That seems correct.  I'll also try removing something from phetlibs to make sure it errors out.

I removed sherpa and got this error:
```
Loading "Gruntfile.js" tasks...ERROR
>> AssertionError: phetLib is missing repositories required by preload: sherpa
Warning: Task "default" not found. Use --force to continue.

Aborted due to warnings.
```

All seems well, closing.
