### ISSUE TITLE
During a build for a translated version of the sim, output missing (or all) strings

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#49]
During a build for a translated version of the sim, output missing strings in a format that can be delivered to authors.  Or provide all strings so they can all be edited.

**Comment by pixelzoom** [comment]
Do we really need this now that we're close to having a translation UI?

**Comment by samreid** [comment]
As long as the functionality to report on missing strings is being handled somewhere else, this issue can be closed.  I'm not familiar enough with the internationalization project to know whether this is the case.

**Comment by pixelzoom** [comment]
Missing strings will appear as empty fields in the translation UI.  Do you think we need something more, to alter either the translator or PhET to missing strings?  If so, please describe how it fits into PhET's processes.

**Comment by pixelzoom** [comment]
Btw... We never had anything like this for Java/Flash sims, and never (afaik) felt like we needed it.  Good translators are generally motivated to provide thorough translations.  And the new HTML5 translation UI will not allow a translation to be submitted if it doesn't have some major percentage (I don't recall the number) of strings translated.

**Comment by samreid** [comment]
Good points.  That sounds sufficient to me, we can always revisit if it becomes a problem in practice.  Closing.
