### ISSUE TITLE
I removed blank lines in active-sims, active-runnables, active-repos

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#490]
Will this cause any parse errors in code that was relying on a blank line?

**Comment by samreid** [comment]
`for-each.sh` still works properly.

test-sims.js could be simplified:
```js
    simNames = simListText.replace( /\r/g, '' ).split( '\n' ).filter( function( simName ) {
      return simName.length > 0;
    } );
```

**Comment by pixelzoom** [comment]
Blank lines were removed in @5b9d30b09b5fa3616d52aca67928a3e3667aa848

**Comment by pixelzoom** [comment]
I took a quick look through the various scripts and Grunt tasks that process these files. I didn't see anything that looks like it will be affected by removing blank lines.  (I'd be more concerned if we were adding blank lines.)

**Comment by pixelzoom** [comment]
Regarding test-sims.js, this would be cleaner, and doesn't require a function:

```js
simNames = simListText.trim().replace( /^\s*[\r\n]/gm, "" ).split('\n');
```

E.g. in console:

```js
> var simListText = "a\nb\n\nc\nd\n\n";
undefined
> simListText.trim().replace( /^\s*[\r\n]/gm, "" ).split('\n');
["a", "b", "c", "d"]
```

**Comment by samreid** [comment]
Consensus: let's at least have trim() to support blank lines.

**Comment by pixelzoom** [comment]
@samreid will add the blank lines back, since cat'ing a file now looks odd. E.g. if my shell prompt is "%", note that there's no newline between the last entry and my prompt.

```
% cat active-runnables
acid-base-solutions
area-builder
...
vibe
wave-on-a-stringcmalley%
```

**Comment by samreid** [comment]
OK I restored the blank lines, closing.
