### ISSUE TITLE
Centralize grunt?

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#494]
Today when I updated grunt in #445, I had to visit many package.json files and update them.      Then I had to iterate across many sim directories and npm prune and npm install.  While it is rare for us to update package.json or grunt, or change systemwide like grunt-requirejs (though it may happen again), I realized there is an alternate paradigm that may be nice.  Imagine if builds were all done from chipper instead from sim directories. 

// current way:
cd wave-on-a-string
grunt
cd ../forces-and-motion-basics
grunt

// proposed way:
cd chipper
grunt --sim=wave-on-a-string
grunt --sim=forces-and-motion-basics

Build artifacts still appear in the simulation directory, as they do now.

Reasons for proposing this change:
- Get rid of a lot of duplicated package.json data and stub Gruntfiles.  
- Get rid of all the scattered node_modules everywhere
- No need to cd to build different things

Reasons we maybe shouldn't make this change:
- What we have now seems like it is generally working
- Would this kind of change complicate maintenance releases?
- Would we have to repeat ourselves too much when doing deploy commands (or would it remember the sim name that we built)

Note this proposal is an alternate solution to the same problem discussed in https://github.com/phetsims/chipper/issues/383

**Comment by jonathanolson** [comment]
> Get rid of all the scattered node_modules everywhere

This sounds amazing.

> Would this kind of change complicate maintenance releases?

Yup, perennial would need to detect which build style would be needed, and do very different things.

Don't really know yet whether it would be worth it.

**Comment by samreid** [comment]
@jonathanolson pointed out that if we can no longer run `grunt` from sim directories it could complicate the build process.  Then he also said we could have grunt stubs that invoke chipper.

**Comment by samreid** [comment]
@jonathanolson and @samreid are approved to investigate this at medium or medium-low priority.

**Comment by samreid** [comment]
@jonathanolson can we make an appointment to look into this?  I'm interested in investigating it, but lack knowledge and experience in perennial, build-server and chipper as they pertain to node_modules.

**Comment by jonathanolson** [comment]
@samreid sounds good, let me know on Skype. Thurs/Fri open.

**Comment by samreid** [comment]
@jonathanolson I haven't had time for this in the last several days.  Feel free to investigate asychronously if you wish and I'll do the same, or perhaps our times will match up in the coming weeks.

**Comment by samreid** [comment]
I tried a minimal install that just has grunt in devDependencies, but it still weighs in at (16.1 MB on disk) for 3,193 items

Grunt is designed to use "one grunt per project".  If we are going to proceed with this, we would likely need a different build command other than `cd sim; grunt`.

**Comment by samreid** [comment]
It seems like to attain the behavior described in this issue we would need a pattern like:

A:
```
cd chipper
grunt --sim=forces-and-motion-basics
```

or 

B:
```
cd sim
node ../chipper/grunt.js
```

But I'm not convinced we should change the API for builds at the moment.  I'll unassign myself.  @jonathanolson you can look deeper if you wish.

**Comment by samreid** [comment]
In discussion with @jonathanolson, new idea:

```
cd sim
build.sh
```

build.sh would invoke chipper's grunt, and pass through options.

**Comment by samreid** [comment]
Other possibilities:

* Using symlinks to reference one set of node_modules
* putting node_modules in the parent directory (e.g. above the checkouts), so that npm would use that.

**Comment by jonathanolson** [comment]
Example build.sh:
```sh
#!/bin/bash

PWD=`pwd`
SIMNAME=`basename $PWD`
cd ../chipper
npm prune
npm update
grunt --sim=$SIMNAME "$@"
```

would launch chipper's grunt with --sim=(simname), however there are a TON of relative paths in chipper, and this would take a lot of effort.

**Comment by samreid** [comment]
Some details about using node_modules from another directory here: https://github.com/gruntjs/grunt/issues/232

**Comment by samreid** [comment]
According to https://github.com/gruntjs/grunt/issues/232#issuecomment-6376905

When using plugins inside a project's gruntfile, npm module plugins loaded via grunt.loadNpmTasks must be installed locally (in ./node_modules/plugin_name relative to the gruntfile).

If I enforce the constraint that we no longer use grunt plugins, and remove the dependency on grunt-eslint, then builds seem to be able to use ../node_modules.

**Comment by samreid** [comment]
We would also have a problem with this line:

```js
  // TODO: chipper#101 eek, this is scary! we are importing from the repository dir. ideally we should just have uglify-js installed once in chipper?
  var uglify = require( '../../../' + buildConfig.name + '/node_modules/uglify-js' );
```

**Comment by samreid** [comment]
We were discussing this in https://github.com/phetsims/phet-info/issues/44

Generally we think it would be nice to eliminate the node_modules from the sim directories and check in one copy (in sherpa or possibly chipper).

This is working:
```
cd sim
rm -rf node_modules
grunt --base=. --gruntfile ../chipper/Gruntfile.js 
```

**Comment by samreid** [comment]
With a bash alias, the recommendation above sounds pretty nice!

**Comment by samreid** [comment]
@jonathanolson still sees advantages for doing this, but @ariel-phet recommended deferring for now.

**Comment by samreid** [comment]
On my working copy, I added this package.json in the root of my checkouts:

```json
{
  "name": "root",
  "version": "1.0.0-dev.1",
  "license": "MIT",
  "devDependencies": {
    "grunt": "~1.1.0"
  }
}
```

Then I ran `npm install` there. And voila, my sim directories build without needing their own grunt!

**Comment by samreid** [comment]
We have no plans to centralize grunt, and no practical way to do so. Closing.
