### ISSUE TITLE
Update grunt-eslint

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#495]
19.0.0 was updated recently, with the following fixes:
- added maxWarnings option
- don't log newline when no output
- updated eslint to ^3.0.0
- don't error out when there are no files to lint

The new lint started catching issues like "unreachable code" and "Unexpected control character(s) in regular expression"

**Comment by samreid** [comment]
I've updated all package.json locally, and running npm install and grunt lint-all to catch errors.  If all is well, I'll commit everything.  Afterwards, developers will need pull and `npm install` for each simulation, and update their local ESLint to latest (3.0.0 series).

**Comment by samreid** [comment]
OK lint is looking good everywhere, catching only errors that should be caught.  I checked that the new lint is still using our custom rules.  Committing shortly.

**Comment by samreid** [comment]
OK all changes are pushed:

Developers will need pull and `npm install` for each simulation, and update their local ESLint to latest (3.0.0 series).

@jonathanolson can you npm install everywhere on phet-server?

**Comment by jonathanolson** [comment]
> @jonathanolson can you npm install everywhere on phet-server?

I believe @jbphet or @mattpen may have taken care of this in the 'npm update' task?

**Comment by jbphet** [comment]
With the recent modifications, the build server should pull master and run ```npm prune``` and ```npm update``` for chipper, perennial, and the sim that is being built at the beginning of the build process.  So, unless I'm missing something, I don't think any manual steps should be needed.  Back to @samreid to say whether he thinks that the manual update really *is* required for some reason.

**Comment by samreid** [comment]
My mistake, I think I was referring to test-server, and I believe @jonathanolson has already taken care of that.
