### ISSUE TITLE
simTitleStringKey looks incorrect

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#498]
While testing https://github.com/phetsims/phet-io/issues/641 I added this line to deployDev.js

```js
console.log(JSON.stringify(deployConfig,null,2));
```
and I saw this entry for a phet-io build for faradays-law.
```
"simTitleStringKey": "undefined/faradays-law.title"
```

I'm unfamiliar with this part of the build process.  Assigned to developer meeting so we can take a look, decide if it needs fixing, and decide on an assignee.

**Comment by pixelzoom** [comment]
Is this issue specific to faradays-law, or do you see similar results with other sim repos?

**Comment by pixelzoom** [comment]
Based on this in getDeployConfig.js:

```js
68 deployConfig.simTitleStringKey = deployConfig.requirejsNamespace + '/' + deployConfig.name + '.title';
```

I would expect the entry to be:

```js
I would expect the entry to be:

```js
"simTitleStringKey": "FARADAYS_LAW/faradays-law.title"
```

**Comment by pixelzoom** [comment]
deployConfig.requirejsNamespace is obtained from `phet.requirejsNamespace` in package.json.

**Comment by pixelzoom** [comment]
deployConfig.requirejsNamespace is obtained from phet.requirejsNamespace in package.json.  faradays-law/package.json looks OK, so perhaps this is a general issue.

**Comment by pixelzoom** [comment]
Looks like this field should be added to the definition of `deployConfig` on line 54 of getDeployConfig.js

```js
requirejsNamespace: packageJSON.phet.requirejsNamespace
```

And should probably add an assert somewhere in this file, since (I believe) `phet.requirejsNamespace` is a required field in package.json:

```js
 assert( packageJSON.phet.requirejsNamespace, 'phet.requirejsNamespace missing from ' + PACKAGE_FILENAME );
```

**Comment by pixelzoom** [comment]
If the assertion causes problems for non-runnables, then we could do this, as in getBuildConfig.js:

```js
if ( packageJSON.phet ) {

    // verify that required fields are present
    assert( packageJSON.phet.requirejsNamespace, 'phet.requirejsNamespace missing from ' + PACKAGE_FILENAME );
  }
```

**Comment by pixelzoom** [comment]
Also need to update doc at top of getDeployConfig.js (line 110) to indicate that `phet.requirejsNamespace` is a required field.

**Comment by pixelzoom** [comment]
Removing developer-meeting label, since I think there's enough information above to fix this.  @samreid if you can verify that this is not sim-specific, I'll be happy to fix it.

**Comment by samreid** [comment]
It is happening for function builder:

```
~/github/dot$ cd ../function-builder/
~/github/function-builder$ grunt deploy-dev
Running "deploy-dev" task
{
  "name": "function-builder",
  "version": "1.1.0-phetiodev.3",
  "buildServerAuthorizationCode": "d!8-A3fBvG2Jd#HV^SkW",
  "buildServerNotifyEmail": null,
  "devUsername": "reids",
  "devDeployServer": "spot.colorado.edu",
  "devDeployPath": "/htdocs/physics/phet/dev/html/",
  "productionServerURL": "https://phet.colorado.edu",
  "simTitleStringKey": "undefined/function-builder.title"
}
```

Hence it seems general.

**Comment by pixelzoom** [comment]
OK, thanks, I'll take care of this.

**Comment by pixelzoom** [comment]
Fixed in above commit.  

To test, I added this to the end of getDeployConfig.js:

```js
console.log( JSON.stringify( deployConfig ) );
assert( false, 'stop here' );
```

Here's the output with a couple of sims:

```
% cd faradays-law
% grunt deploy-dev
Running "deploy-dev" task
{"name":"faradays-law","version":"1.2.0-phetiodev.1","requirejsNamespace":"FARADAYS_LAW","buildServerAuthorizationCode":"d!8-A3fBvG2Jd#HV^SkW","buildServerNotifyEmail":"cmalley@pixelzoom.com","devUsername":"malleyc","devDeployServer":"spot.colorado.edu","devDeployPath":"/htdocs/physics/phet/dev/html/","productionServerURL":"https://phet.colorado.edu","simTitleStringKey":"FARADAYS_LAW/faradays-law.title"}
Warning: stop here Use --force to continue.

Aborted due to warnings.
% cd ../function-builder
grunt deploy-dev
Running "deploy-dev" task
{"name":"function-builder","version":"1.1.0-phetio.4","requirejsNamespace":"FUNCTION_BUILDER","buildServerAuthorizationCode":"d!8-A3fBvG2Jd#HV^SkW","buildServerNotifyEmail":"cmalley@pixelzoom.com","devUsername":"malleyc","devDeployServer":"spot.colorado.edu","devDeployPath":"/htdocs/physics/phet/dev/html/","productionServerURL":"https://phet.colorado.edu","simTitleStringKey":"FUNCTION_BUILDER/function-builder.title"}
Warning: stop here Use --force to continue.

Aborted due to warnings.
%
```

Back to @samreid for review.

**Comment by samreid** [comment]
Question: how come this issue did not appear in any other symptoms?  Is `simTitleStringKey` really being used?  If so, what for?  Why did have an undefined prefix not cause trouble?  Does it need a prefix?

**Comment by pixelzoom** [comment]
All good questions.

**Comment by samreid** [comment]
I'm trying to understand how simTitleStringKey is created and used, and I'm a bit over my head.  It looks like it was introduced in 7d2cc1f5e8ac7399f143b2b0476dafcc9cfdec60 and usages were expounded upon in 728ef60e7b58a39a7acef1a062b3be41930ad107.  Both commits are from @pixelzoom, when you have time can you help investigate?  If the key or its prefix is not necessary, perhaps it should be removed.

**Comment by pixelzoom** [comment]
`simTitleStringKey` is definitely required in package, and in buildConfig, because createHTMLFiles.js uses it to lookup the sim's title:

```var simTitle = stringMap.en[ buildConfig.simTitleStringKey ];```

Not sure how (or whether) it's used in deployConfig. I'll take a closer a look on Monday.

**Comment by pixelzoom** [comment]
getDeployConfig.js was created in https://github.com/phetsims/chipper/issues/309#issuecomment-133546102, "similar to getBuildConfig.js, but for deploy tasks".  

Doing a search across all PhET files (all file types), I see only `buildConfig.simTitleStringKey` being used, and `deployConfig.simTitleStringKey` appears to be unused.  So I believe that it's safe to remove `simTitleStringKey` from getDeployConfig.js.

**Comment by samreid** [comment]
I removed `simTitleStringKey` from getDeployConfig.js and tested grunt, it seemed OK.  I'll commit changes so I can test deploy-rc with --dryRun

**Comment by samreid** [comment]
grunt deploy-rc --dryRun also seems OK.  @pixelzoom do you want to do anything else for this issue?

**Comment by pixelzoom** [comment]
Nothing else that I can think of. Closing.
