### ISSUE TITLE
Script should run synchronously

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#499]
From https://github.com/phetsims/scenery/issues/567

I tried adding a build-js task to build scenery and include it in a sample HTML file (test.html in scenery's chipper branch).  However, when the test.html starts up, window.scenery is undefined until after one setTimeout.  This is caused by the asychronous e(['']) being used instead of the synchronous e('').  https://github.com/requirejs/almond/issues/42 reports how we can use wrap to guarantee a synchronous load.

I tested the wrap strategy in https://github.com/phetsims/scenery/issues/567 and it appeared to work properly for scenery test.html as well as for a FAMB build.  I'll commit shortly then assign for review.

**Comment by samreid** [comment]
I committed the change above, @jonathanolson or @andrewadare or @pixelzoom do you have time to review?

**Comment by pixelzoom** [comment]
Sorry, I don't have time to look at this one.

**Comment by andrewadare** [comment]
@samreid There's not much to review here; if you tested it and it works, I'm not sure how exactly I can be of assistance. The new source looks fine to me, although I'm not sure whether the generated code should be following the PhET formatting guidelines (space padding in parens).

**Comment by samreid** [comment]
> I'm not sure how exactly I can be of assistance

Perhaps do a build with and without it on a different project (using --uglify=false) and make sure they differ as prescribed, and double check that something builds and runs nicely?

> I'm not sure whether the generated code should be following the PhET formatting guidelines

I do not know whether wrap or uglify goes first.  In either case, the code is intended for build, so would be embedded in HTML.

**Comment by andrewadare** [comment]
Here's a build of CLB diffed between e6236b6 and today's master:
```diff
[capacitor-lab-basics]$ diff clb-chipper-e6236b6.html clb-chipper-master.html
--- clb-chipper-e6236b6.html	2016-09-27 08:50:44.000000000 -0600
+++ clb-chipper-master.html	2016-09-27 08:47:34.000000000 -0600
@@ -38,7 +38,7 @@
   window.phet.chipper = {};
   window.phet.chipper.project = 'capacitor-lab-basics';
   window.phet.chipper.version = '1.0.0-dev.28';
-  window.phet.chipper.buildTimestamp = '2016-09-27 14:50:44 UTC';
+  window.phet.chipper.buildTimestamp = '2016-09-27 14:47:34 UTC';
   window.phet.chipper.brand = 'phet';
   window.phet.chipper.locale = 'en';

@@ -540,7 +540,7 @@
 };
   // ### END THIRD PARTY LICENSE ENTRIES ###
   window.phet.chipper.dependencies = {
-  "comment": "# capacitor-lab-basics 1.0.0-dev.28 Tue Sep 27 2016 08:50:43 GMT-0600 (MDT)",
+  "comment": "# capacitor-lab-basics 1.0.0-dev.28 Tue Sep 27 2016 08:47:33 GMT-0600 (MDT)",
   "assert": {
     "sha": "845be6b591cb746b0b05b7023208aef2e49a8855",
     "branch": "master"
@@ -562,8 +562,8 @@
     "branch": "master"
   },
   "chipper": {
-    "sha": "e6236b6a2ca33377168c40318f73756054b5ae62",
-    "branch": "HEAD"
+    "sha": "589bb2f9e98731e04fd369da279befb6b5bff20c",
+    "branch": "master"
   },
   "dot": {
     "sha": "879674e2590f057a1f099322875561d31503d855",
@@ -18617,7 +18617,7 @@
     };
   })();
 </script>
-<script type="text/javascript">(function () {/**
+<script type="text/javascript">(function() {/**
  * @license almond 0.2.9 Copyright (c) 2011-2014, The Dojo Foundation All Rights Reserved.
  * Available via the MIT or new BSD license.
  * see: http://github.com/jrburke/almond for details
@@ -91529,8 +91529,7 @@
 } );


-
-require(["capacitor-lab-basics-main"]);
+require('capacitor-lab-basics-main');
 }());</script>
 </body>
 </html>
```

So it looks like the square brackets made it in correctly.

Both versions run locally without any problems.

**Comment by samreid** [comment]
Thanks @andrewadare, closing.

**Comment by samreid** [comment]
On Oct 21, @phet-steele identified a problem that using the synchronous main caused failures for the Chrome "Save As..." for saving a simulation, which would make it so the sim wouldn't launch properly.  After reverting this change to make main asychronous again, we are again able to save html sims and launch them.
