### ISSUE TITLE
Change npm install to npm update

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#501]
`npm install` suffered from problems that were cured by `npm update`.  @mattpen @jbphet and I are all mystified about *how* this solved the problem, but we verified that `npm update` has the correct behavior across a variety of cases.

I'm seeing 37 occurrences of `npm install` across our repos, and there may be more across our documentation like bit.ly/phet-development-overview

We need to assign a developer to review these cases and see which should change to `npm update`.

**Comment by jonathanolson** [comment]
Additionally, searching for npm usage (not just 'npm install') sounds important, e.g. maintenance.js:
```js
    npmInstall: function( repo, callback ) {
      this.execute( NPM_CMD, [ 'install' ], '../' + repo, function() {
        callback();
      } );
    },
```

**Comment by samreid** [comment]
@zepumph volunteered to investigate this.  Ping @jonathanolson @jbphet @samreid or @mattpen if you have any questions about this.

**Comment by samreid** [comment]
For background information, read the man pages as well as http://stackoverflow.com/questions/12478679/npm-install-vs-update-whats-the-difference and try out npm install and update and rm -rf node_modules on a few things.

**Comment by samreid** [comment]
There is also a google doc at http://bit.ly/phet-development-overview that you should put on your list to update.

**Comment by zepumph** [comment]
In correlation with a dev discussion we decided to remove  chipper/bin/npm-install-all.sh. This is mainly because no one used it or knew it existed. I attached that to this issue.

**Comment by zepumph** [comment]
Other commits regarding this change:
dot: 6df9bbf492b6110caf47457c9056dca97cd625a8
all-sims: 17a7699fad7fb8e39ff1aee6ea4d7406cf1981f5
kite: b61bda003d6a93f4841c39c8db7904f6163df5f3
perennial: e921f9e7e37991bad3eef4c36141d599e575b1f1
phetmarks: d76927343ed946b01fc821f0e27948c88349745a
scenery: 9c434709b5140e779f6a1af238709458677ffe43
sherpa: cbdbe169a663def55301b07a4497c068b5f25dbf
simula-rasa: 43ec6ca308efdb5ad30d91e59421b86f43e09376

**Comment by zepumph** [comment]
Now the only `npm install` commands left in the project are when someone wants to specifically install a single package. see phet-info\ide\sublime-text\eslint-and-sublime-text.md for an example. Passing this one off to @samreid to review for closing.

**Comment by zepumph** [comment]
I also have updated http://bit.ly/phet-development-overview document to the same specifications as above, keeping npm install if it regards a specific package to be installed

**Comment by samreid** [comment]
I skimmed through all occurrences of npm and the changes look good, thanks @zepumph, closing.
