### ISSUE TITLE
Move test services to aqua

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#502]
In https://github.com/phetsims/chipper/issues/478#issuecomment-250067404 @samreid and @jonathanolson agreed that the test services currently in chipper should move to aqua.  I can start on this but may need @jonathanolson help if updates to phettest.colorado.edu are necessary.

**Comment by samreid** [comment]
It seems this work should coordinate with #478, @jonathanolson can you take care of it or let me know when a good time to work on it is?

**Comment by jonathanolson** [comment]
> It seems this work should coordinate with #478, @jonathanolson can you take care of it or let me know when a good time to work on it is?

I'll be able to handle this and update phettest.colorado.edu.

**Comment by jonathanolson** [comment]
Moved to aqua, bumped handling on phettest.colorado.edu to point to the new version (with new query parameters).
