### ISSUE TITLE
Remove sim version from HTML page title

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/chipper#503]
At 9/29/16 developer meeting we discussed removing the sim version from the HTML page title.

> JG: This is the first thing read by a screen reader, and it is unclear to some what this number means.
SR: It’s OK with me to remove it.
AP: I also support removing this unless it is necessary
CM: OK with me. But recommended to check with KP.
JO: I'm fine for it to be removed
JB: +1 for removal, but let’s not go back and do maintenance releases to implement it on currently published sims, let’s just do it going forward

Adding status meeting label to check with @kathy-phet to see if it is OK to remove the version id from the page title.

**Comment by jessegreenberg** [comment]
In status meeting 10/6/16, @kathy-phet agreed that it was OK to remove the sim version from the page title.

@pixelzoom volunteered to investigate doing this in a developer meeting, so assigning to him.  @pixelzoom if I can help at all, please let me know.

**Comment by pixelzoom** [comment]
This is handled in createHTMLFiles.js.  In addition to the browser title, the version number appears in 2 other places inside the .html file deliverable:

(1) Meta data tags for OpenGraph protocol, e.g.:

```
<!-- metadata for Open Graph protocol -->
  <meta property="og:title" content="&#8234;Function Builder&#8236; 1.1.0-dev.2"/>
  <meta property="og:type" content="phet:simulation"/>
  <meta property="og:url" content="https://phet.colorado.edu/sims/html/function-builder/latest/function-builder_en.html"/>
  <meta property="og:image" content="https://phet.colorado.edu/sims/html/function-builder/latest/function-builder-600.png"/>
```

(2) A comment related to copyright and licensing. E.g.:

```
<!--
<U+202A>Function Builder<U+202C> 1.1.0-dev.2
Copyright 2002-2016, Regents of the University of Colorado
PhET Interactive Simulations, University of Colorado Boulder

This file is licensed under Creative Commons Attribution 4.0
For alternate source code licensing, see https://github.com/phetsims
For licenses for third-party software used by this simulation, see below
For more information, see https://phet.colorado.edu/en/licensing/html

The PhET name and PhET logo are registered trademarks of The Regents of the
University of Colorado. Permission is granted to use the PhET name and PhET logo
only for attribution purposes. Use of the PhET name and/or PhET logo for promotional,
marketing, or advertising purposes requires a separate license agreement from the
University of Colorado. Contact phethelp@colorado.edu regarding licensing.
-->
```

@ariel-phet Do you want either of these occurrences deleted, or just the version number in the browser window title?

**Comment by pixelzoom** [comment]
One more... 

(3) The browser window title for the iframe test, e.g. "Function Builder 1.0.0.dev.2 iframe test".

**Comment by pixelzoom** [comment]
Note to self, relevant lines in createHTMLFiles.js:

```js
49 var simTitleAndVersion = simTitle + ' ' + buildConfig.version;
56 htmlHeader = simTitleAndVersion + '\n' +
66 htmlHeader = simTitleAndVersion + '\n' +
206 var localeTitleAndVersion = stringMap[ locale ][ buildConfig.simTitleStringKey ] + ' ' + buildConfig.version; //TODO: i18n order
213 string = ChipperStringUtils.replaceFirst( string, 'PHET_SIM_TITLE', encoder.htmlEncode( localeTitleAndVersion ) );
216 string = ChipperStringUtils.replaceFirst( string, 'OG_TITLE', encoder.htmlEncode( localeTitleAndVersion ) );
264 iframeTestHtml = ChipperStringUtils.replaceFirst( iframeTestHtml, 'PHET_SIM_TITLE', encoder.htmlEncode( simTitleAndVersion + ' iframe test' ) );
```

**Comment by ariel-phet** [comment]
@pixelzoom this should definitely be removed in (1) and (3) -- we don't want the version showing up in facebook posts.

(2) seems appropriate as the version number WILL appear in the about dialog, so it seems to make sense in the internal licensing, so I would say keep that. I don't see that interfering with any a11y case.

**Comment by pixelzoom** [comment]
There's also some code in Sim.js that needs to be changed. This bit sets the browser window title:

```js
237    //Set the HTML page title to the localized title
238    //TODO: When a sim is embedded on a page, we shouldn't retitle the page
239    $( 'title' ).html( StringUtils.format( titlePatternString, name, self.version ) );
```

**Comment by pixelzoom** [comment]
Work on this is completed. Related issue identified and tracked in #510.

@jessegreenberg Would you mind reviewing?

**Comment by jessegreenberg** [comment]
Reviewed changes in https://github.com/phetsims/joist/commit/d5c572215d5bcbe19182c4d06ff72b7ca872799f and https://github.com/phetsims/chipper/commit/b019ee72dc8dd5c5bbd69f7df43e019e46b16de8, everything looks great.

To sanity check, I ran a handful of sims in requireJS and Built versions.  RequireJS sims all had the repo name as the title, and built sims had the sim name without the version number.  

Looks great, and sounds great with a screen reader.  Thanks @pixelzoom, closing.
