### ISSUE TITLE
grunt and grunt --brand=phet-io cannot succeed for the same codebase

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#507]
Discovered in https://github.com/phetsims/chipper/issues/506 `grunt` and `grunt --brand=phet-io` cannot both succeed for the same codebase because chipper is now checking that version names match our style (phet-io builds must have the string `phetio` in the version name).  This will cause complications for automated testing.

@andrewadare @mattpen @zepumph any ideas about how to deal with this?

**Comment by mattpen** [comment]
@samreid - I'm not able to recreate the problem from #506, if I run `grunt` with phetio in the version it succeeds.  Has this problem already been fixed somewhere?  

Are we doing any automated testing on phet-io builds yet?  The reverse does not work (running `grunt --brand=phet-io` without phetio in the version).  This could be possibly be solved by moving [this assert](https://github.com/phetsims/chipper/blob/5f52de352ec59ab1a6fe91608908e9aaedb8041f/js/grunt/requirejsBuild.js#L20) to deployProduction, although we may need to add a "brand" object to package.json in order for this to work, or require the `--brand=phet-io` flag for phet-io production deploys.

**Comment by samreid** [comment]
> @samreid - I'm not able to recreate the problem from #506, if I run `grunt` with phetio in the version it succeeds.  Has this problem already been fixed somewhere?  

Are you using a stale chipper (from dependencies.json)?  When I added phetio to the version name in forces-and-motion-basics/package.json in master and ran grunt, I saw the following:

~/github/forces-and-motion-basics$ grunt 
Running "eslint:allFiles" (eslint) task

Running "clean" task

Running "requirejs-build" task
Warning: phet versions cannot be named like phet-io versions Use --force to continue.

> Are we doing any automated testing on phet-io builds yet? 

Not yet.

> we may need to add a "brand" object to package.json in order for this to work, or require the `--brand=phet-io` flag for phet-io production deploys. 

Perhaps deployProduction can infer the brand from the build?  Or perhaps there is a better way to handle versioning, such as having the build process automatically append "phetio" if it is a phetio build (so that package.json remains the same).

**Comment by mattpen** [comment]
@samreid - My grunt task wasn't failing because the brand was `'adapted-from-phet'`, I think because I do not have a `"brand"` entry in `build-local.json`.  Would it be acceptable to run the automated testing with this brand?  Then the assertion in [requirejsBuild.js:25](https://github.com/phetsims/chipper/blob/master/js/grunt/requirejsBuild.js#L25) would not fail.

**Comment by samreid** [comment]
It would be best if we could run the automated tests for all 3 supported brands, phet, adapted-from-phet and phet-io.  Until then, it seems like a good idea to keep "phetio" version names out of master and continue testing phet brand on master.  This assertion will help us keep master clean.

**Comment by mattpen** [comment]
Could we possibly add a process to create a transient package.json object during automated testing for each brand?  Or add --version as an command line option to grunt?

**Comment by samreid** [comment]
This would be good to discuss at developer meeting, to brainstorm and evaluate ideas for how to make multi-brand builds possible.

**Comment by samreid** [comment]
@jonathanolson suggests appending the brand to the version number for phet-io builds.

1.2.0-dev.1 => 1.2.0-phetiodev.1
1.2.0 => 1.2.0-phetio

I'll take a look.

**Comment by samreid** [comment]
It looks like buildConfig and deployConfig are the only 2 places in chipper where the version is ready.  Hence these are the 2 sites where the "phetio" string must be inserted.

**Comment by samreid** [comment]
I wrote this file:

```js
// Copyright 2015, University of Colorado Boulder

/**
 * Gets the version name based on the brand.  If the brand is phet-io, then the substring 'phetio' is
 * inserted into the version name at the appropriate place.
 *
 * see https://github.com/phetsims/chipper/issues/507
 *
 * @author Sam Reid (PhET Interactive Simulations)
 */

/**
 * @param {string} brand - the name of the brand
 * @param {string} version - the version string in package.json
 * @return {string} the updated version name
 */
module.exports = function( brand, version ) {
  'use strict';

  if ( brand === 'phet-io' ) {

    // Insert phetio into the version name
    // 1.2.0-dev.31 => 1.2.0-phetiodev.31
    // 1.2.0 => 1.2.0-phetio

    // if there is a hyphen, put phetio before it
    // if there is no hyphen, append phetio
    var hyphenIndex = version.indexOf( '-' );
    if ( hyphenIndex >= 0 ) {
      return version.substring( 0, hyphenIndex + 1 ) + 'phetio' + version.substring( hyphenIndex + 1 );
    }
    else {
      return version + '-phetio';
    }
  }
  return version;
};
```

And use it in getBuildConfig like so:

```js
  var brand = getBrand( grunt, buildLocalJSON );

  var buildConfig = {

    // These fields have no dependencies on other entries in buildConfig.
    name: packageJSON.name,
    version: getVersionForBrand( brand, packageJSON.version ),
    license: packageJSON.license,
    requirejsNamespace: packageJSON.phet.requirejsNamespace,

    // @public (read-write, phetIO)
    brand: brand,

    //TODO: better way to allow requesting different preload lists? chipper#63
    getPreload: getPreload // for generating HTML files for specific configurations, see chipper#63
  };
```

However, there are 3 usage sites of getDeployConfig which also get the version by reading package.json and I cannot figure out how this will work for perennial.  I may need help from someone with perennial experience like @mattpen.

**Comment by samreid** [comment]
I committed getVersionForBrand.js but it is not currently used.

**Comment by samreid** [comment]
@mattpen and I worked to add calls to getVersionForBrand to getDeployConfig and getBuildConfig, and that seems like it will work well (though it needs to be tested).  However, the about dialog is not showing the updated version.  Perhaps package.json is being added into the build without the updated version name?

**Comment by samreid** [comment]
Yes, package.json is being loaded through requirejs:

![image](https://cloud.githubusercontent.com/assets/679486/19609174/ed4fd7f6-9792-11e6-80e9-4d0757130613.png)

**Comment by samreid** [comment]
I skyped the developer chat:

> brace yourselves, Matt & I are testing out some new chipper code for https://github.com/phetsims/chipper/issues/507   Please hold off on deploy until we give the all-clear.

**Comment by samreid** [comment]
@mattpen and I added code to splice in the version name.  It should be tested for dev deploy and production/rc deploy for phet-io and phet brands.

**Comment by samreid** [comment]
We should factor out getVersionForBrand and make it UMD, this will require adding CHIPPER to all config files.

**Comment by samreid** [comment]
@mattpen and I tested a dev phet-io deploy and it seemed good.  I tested a phet rc deploy and it seemed good: http://www.colorado.edu/physics/phet/dev/html/faradays-law/1.2.0-rc.1/

Next I'll try a phet-io rc deploy.

**Comment by samreid** [comment]
phet-io rc deploy also looks good:
http://www.colorado.edu/physics/phet/dev/html/faradays-law/1.2.0-phetiorc.2/

I should create a separate issue to factor out the logic into a UMD file, then this issue can be closed.  Thanks @mattpen!

**Comment by samreid** [comment]
I created a new issue to address the duplicated code, closing.
