### ISSUE TITLE
Add simname_all.html that includes string data for all locales

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#509]
Uses locale query parameter to select on startup. See https://github.com/phetsims/phet-app/issues/234

**Comment by jonathanolson** [comment]
The chipper-built phet.chipper.strings was changed to the format of getStringMap, and it includes all needed locales. Moved up setting phet.chipper.locale to initialize-globals, so that Google Analytics will report properly.

Assigning to @jbphet for review, and to make sure this doesn't cause problems for Rosetta.

**Comment by jbphet** [comment]
Initial comments:
+ I tested doing this build, and it mostly worked, but I found that if I set a locale value that didn't exist in the sim, it bombed.  We should probably just fall back to English in this case.
+ Related to the previous point, using locale=xx as a query parameter to a built sim that is NOT an _all sim causes the same problem, i.e. the sim crashes during launch.
+ Can we consider using --allLocales instead of --allHtml?  I know it's the _all file that gets generated, and that this is consistent with what we did with Java sims, but --allLocales just seems clearer to me
+ There is a comment in chipper-strings-setup.js that looks out of date to me - it says, ```// override strings via the 'strings' query parameter```

I don't see anything that would break Rosetta as far as I can tell from just inspection.

**Comment by jonathanolson** [comment]
So we should basically ignore locales if they aren't in a list?

> Can we consider using --allLocales instead of --allHtml? I know it's the _all file that gets generated, and that this is consistent with what we did with Java sims, but --allLocales just seems clearer to me

Sure, although is it weird to have command-line parameters ```--locales=es --allLocales```?

**Comment by pixelzoom** [comment]
As note in https://github.com/phetsims/chipper/issues/510#issuecomment-255094765:

The grunt help for `--allHTML` says:

> --allHtml : Generate the _all.html file that contains information for all locales

Two issues: 

(1) What is  "information for all locales"?  I have no idea what to expect or to determine why this option would be useful.

(2) I ran `grunt --allHTML` for function-builder, and opened function-builder_all.html.  It does not show me "information for all locales" (whatever that is), it shows me the English sim and nothing more. Is there perhaps some other option that needs to be included?  If so, that should be documented.

**Comment by jonathanolson** [comment]
Notes in https://github.com/phetsims/chipper/issues/510#issuecomment-255152222.

> (1) What is "information for all locales"? I have no idea what to expect or to determine why this option would be useful.

Includes translated strings for all locales, instead of just including strings for a single locale. It allows us to have a single HTML file that (with a query parameter) can run in any locale available.

**Comment by pixelzoom** [comment]
As noted in https://github.com/phetsims/chipper/issues/510#issuecomment-255793825:

> If the documentation for `--allHTML` is accurate ("contains information for all locales"), then why do I need to add `--locales=*`?   Imo, the absence of `--locales` should automatically build all locales, and the grunt help doc should be changed to:

```
--allHtml : Generates the _all.html file that contains strings for all locales. 
            If the --locales option is used, the file will contain strings for only the specified locales. 
            Note that `--locales=*` is equivalent to omitting the `locales` option.
```

**Comment by pixelzoom** [comment]
Also highly recommended to rename this option from allHtml to allHTML.

**Comment by jonathanolson** [comment]
> If the documentation for --allHTML is accurate ("contains information for all locales"), then why do I need to add --locales=*?

I don't see where the documentation specifies that ```--locales``` is needed (it isn't).

**Comment by pixelzoom** [comment]
Apparently I was using `--allHTML` instead of `--allHtml`. Again, highly recommended to rename this option.  And imo the grunt help should still read:

```
--allHtml : Generates the _all.html file that contains strings for all locales. 
            If the --locales option is used, the file will contain strings for only the specified locales. 
            Note that `--locales=*` is equivalent to omitting the `locales` option.
```

**Comment by jonathanolson** [comment]
> Also highly recommended to rename this option from allHtml to allHTML, as evidenced by the number of times that I've typed (and run) this option incorrectly.

Done in above commit.

**Comment by jonathanolson** [comment]
If --allHTML would only include strings for the locales specified by --locales (recommended in https://github.com/phetsims/chipper/issues/509#issuecomment-255798145), that would require build-server would always use locales=*, even if building for one translation update. Otherwise, the _all.html wouldn't include information for all locales (its purpose).

@jbphet, does the build-server use anything other than locales=* (say, from a single rosetta translation build?)

**Comment by pixelzoom** [comment]
> If --allHTML would only include strings for the locales specified by --locales (recommended in https://github.com/phetsims/chipper/issues/509#issuecomment-255798145)

*Not* what I recommended.  Again:

```

```
--allHtml : Generates the _all.html file that contains strings for all locales. 
            If the --locales option is used, the file will contain strings for only the specified locales. 
            Note that `--locales=*` is equivalent to omitting the `locales` option.
```

*If* locales is specified... otherwise equivalent to `--locales=*` .

**Comment by pixelzoom** [comment]
... which is what the implementation does now. This is purely a documentation change.

**Comment by jonathanolson** [comment]
> ... which is what the implementation does now. This is purely a documentation change.

Currently ```grunt --allHtml --locales=en``` includes all available locales (not just English) in the _all.html, so that doesn't seem like just a documentation change.

> Note that `--locales=*` is equivalent to omitting the `locales` option.

Omitting locales is currently (almost, not quite) equivalent to --locales=en, at least for most of the build process.

**Comment by jbphet** [comment]
In response to https://github.com/phetsims/chipper/issues/509#issuecomment-255799583, yes, the build-server often builds just a single non-English locale in support of the translation process.

Since the ```locales``` flag in the build process is what controls which locales are build, how about doing away with the ```--allHTML``` flag and having a value of ```all``` that is a valid locale?  So, for example, we could use ```locales=en,all``` to produce the English and all-locales file.  ```locales=*``` would produce all locales as individual HTML files **and** the all-locales file.

**Comment by pixelzoom** [comment]
I'm obviously very confused about this feature. My currently (revised) understanding:

• allHTML and locales options are independent, not at all related
• allHTML specifies to build an all.html file containing strings for all translated locales 
• locales specifies the locale-specific HTML files to build

I am getting closer?

**Comment by jonathanolson** [comment]
> My current (revised) understanding

Yup, all of those are correct for the current behavior. We'll always want the _all.html (in my opinion) to contain strings from all available locales, regardless of what locale-specific sim HTML files are built.

I don't have strong preferences about the way we tell grunt to build the _all.html, whether it's with an --allHTML flag, or adding 'all' to a list of locales.

**Comment by jonathanolson** [comment]
> My current (revised) understanding

Yup, all of those are correct for the current behavior. We'll always want the _all.html (in my opinion) to contain strings from all available locales, regardless of what locale-specific sim HTML files are built.

I don't have strong preferences about the way we tell grunt to build the _all.html, whether it's with an --allHTML flag, or adding 'all' to a list of locales.

**Comment by jonathanolson** [comment]
Potentially renaming --locales to indicate it's about what locale-specific HTML files should be built might be helpful (and might have helped prevent misunderstandings), but would be tricky for the build-server to handle.

**Comment by pixelzoom** [comment]
@jbphet said:
> how about doing away with the `--allHTML` flag and having a value of `all` that is a valid locale?

Then that would couple the `allHTML` and `locales` options. I don't think that's a good idea, it overloads the functionality of the `locales` option.

@jonathanolson said:
> Potentially renaming --locales to indicate it's about what locale-specific HTML files should be built might be helpful

I don't know if we need to rename `locales`.  But better grunt help might be useful, since the current help doesn't indicate that this option specifies which locale-specific HTML files to build.  Maybe something like:

```
--locales specifies which locale-specific HTML files to build. Examples of valid arguments are:
  * : all translated locales
  fr : French
  ar,fr,es : Arabic, French and Spanish (comma separated locales)
```
 
Btw... `locales=*` is currently documented as `all locales in strings/ directory` which is wrong, since there is no longer a strings dir.

**Comment by pixelzoom** [comment]
I see this in createHTMLFiles.js, line 265:

```js
  // Create an _all.html file
  if ( grunt.option( 'allHTML' ) && buildConfig.brand === 'phet' ) {
    grunt.file.write( 'build/' + buildConfig.name + '_all.html', replaceLocaleConstants( html, 'en', true ) );
  }
```

If `allHTML` is not relevant for non-phet brands, then this should be an error, not silently ignored. And the grunt help should indicate that it's valid only when brand=phet.

**Comment by jonathanolson** [comment]
@samreid, do we need _all.html for phet-io brands?

> If allHTML is not relevant for non-phet brands, then this should be an error, not silently ignored. And the grunt help should indicate that it's valid only when brand=phet.

Agreed.

**Comment by jonathanolson** [comment]
@pixelzoom, the above documentation looks much more helpful.

**Comment by pixelzoom** [comment]
@jbphet said:

> how about doing away with the --allHTML flag and having a value of all that is a valid locale?
Then that would couple the allHTML and locales options. I don't think that's a good idea, it overloads the functionality of the locales option.

And I said:
> Then that would couple the allHTML and locales options. I don't think that's a good idea, it overloads the functionality of the locales option.

@jbphet and I looked at the implement via Skype, and it looks like having `all` as a special value for `locales` would be feasible.  It would involved a change to createHTMLFiles.js that looks something like this:

```js
// Create locale-specific HTML files
for ( var i = 0; i < buildConfig.locales.length; i++ ) {
  var locale = buildConfig.locales[ i ];
  var includeAllLocales = ( locale === 'all' );
  locale = includeAllLocales ? ChipperConstants.FALLBACK_LOCALE : locale;
  // then do the rest of what's currently in the for loop
}

Questions to answer before we could do this:
• Is it appropriate to consider '_all.html' to be a locale-specific HTML file?
• Is generating all.html relevant when `grunt.option( 'chromeWebStore' )`? 
 
I'm not advocating doing this, just documenting what @jbphet and I discussed. Labeled for developer meeting.

**Comment by pixelzoom** [comment]
Another issue with the implementation of this at createHTMLFiles.js line 265:

```js
  // Create an _all.html file
  if ( grunt.option( 'allHTML' ) && buildConfig.brand === 'phet' ) {
    grunt.file.write( 'build/' + buildConfig.name + '_all.html', replaceLocaleConstants( html, 'en', true ) );
  }
```

Locale `'en'` should not be hardcoded, should be using ChipperConstants.FALLBACK_LOCALE.  This is also a problem at line 276 for the iframe.html support:

```js
    //TODO should the next 2 lines be using ChipperConstants.FALLBACK_LOCALE instead of hardcoded to 'en'?
    iframeTestHtml = ChipperStringUtils.replaceFirst( iframeTestHtml, 'PHET_SIM_URL', buildConfig.name + '_en.html' );
    grunt.file.write( 'build/' + buildConfig.name + '_en-iframe' + '.html', iframeTestHtml );
```

**Comment by samreid** [comment]
> @samreid, do we need _all.html for phet-io brands?

phet-io simulations will not run in the iPad app.  But there may be future cases where the _all.html is suitable for phet-io.

**Comment by pixelzoom** [comment]
10/27/16 dev meeting discussion:
• issues related to 'chromeWebStore' moved to #513
• leave `allHTML` as a separate code path in createHTMLFiles.js
• @pixelzoom will replace hardcoded 'en', then close

**Comment by pixelzoom** [comment]
'en' replaced with ChipperConstants.FALLBACK_LOCALE. Tested with `grunt --allHTML` in function-builder, verified that function-builder_all.html and function-builder_en-iframe.html files were created.  Tested both html files, including `??locale=bs` for all.html.

Closing.

**Comment by pixelzoom** [comment]
Reopening. This TODO still needs to be addressed in createHTMLFiles.js:

```js
//TODO if allHTML is truly relevant only when brand=phet, then it should fail instead of being silently ignored
```

**Comment by jbphet** [comment]
Reopening because I think @pixelzoom intended to do so, and the TODO item he references in the above comment is still in the code.

**Comment by pixelzoom** [comment]
The code in question was created by @jonathanolson in @394dd320b2681437d40b064a2566570f2f9e7809, assigning to him.

**Comment by jonathanolson** [comment]
Implemented:
```
Fatal error: alLHTML option only supported with the 'phet' brand
```
and added documentation so `grunt --help` specifies that --allHTML only works with the phet brand.
