### ISSUE TITLE
problems with how browser window title is set

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#510]
There are multiple problems with how the `<title>` tag is set for sim HTML files.  Noted while working on https://github.com/phetsims/chipper/issues/503.

## built html files

chipper/templates/sim.html contains this line:

```js
<title>PHET_SIM_TITLE</title>
```

`SIM_TITLE` is replaced like this in createHTMLFiles.js:

```js
219 string = ChipperStringUtils.replaceFirst( string, 'PHET_SIM_TITLE', encoder.htmlEncode( localizedTitle ) );
```

Sim.js has this bit of code, which does the same thing as the above (and is problematic, as noted by the TODO):

```js
233    //Set the HTML page title to the localized title
234    //TODO: When a sim is embedded on a page, we shouldn't retitle the page
235    $( 'title' ).html( name );
``` 

## development html file

In requirejs mode, there also seems to be a problem. In chipper/templates/sim-developement.html, we have:

```js
11   <!-- Localized title with version will be filled in by JavaScript. -->
12  <title>Loading {REPOSITORY}</title>
```

`REPOSITORY` is replaced by generateDevelopmentHTML.js like this:

```js
47   html = ChipperStringUtils.replaceAll( html, '{REPOSITORY}', repositoryName );
```

So we end up with (e.g.):

```js
<!-- Localized title with version will be filled in by JavaScript. -->
<title>Loading function-builder</title>
```

But then the bit of code in Sim.js replaces this at runtime:

```js
235    $( 'title' ).html( name );
```

## Recommendations

(1) Remove code that sets the title (identified above) from Sim.js

(2) Modify sim-developement.html and generateDevelopmentHTML.js to insert the sim title. Then regenerate development HTML files for all runnables.

**Comment by pixelzoom** [comment]
@samreid @jonathanolson Do you see any problem with the above recommendations?

**Comment by pixelzoom** [comment]
Above I recommended:

> (2) Modify sim-developement.html and generateDevelopmentHTML.js to insert the sim title. 

There will be a significant amount of work required to get the sim title. What do you think of just inserting the repository name, so that (e.g.) "function-builder" is the title for the development HTML file?

**Comment by jonathanolson** [comment]
> There will be a significant amount of work required to get the sim title. What do you think of just inserting the repository name, so that (e.g.) "function-builder" is the title for the development HTML file?

Presumably it would just be
```js
getStringMap( grunt, buildConfig )[ ChipperConstants.FALLBACK_LOCALE ][ buildConfig.simTitleStringKey ];
```
that could be somewhat factored out?

Overall, I agree with (1) and (2) now that we don't add dynamic information to the title (e.g. no version numbers, brand information, etc.)

**Comment by samreid** [comment]
I'm 26 issues behind and it may be a while before I can look into this one.  Though I do agree with steps (1) and (2) above, and I like @jonathanolson suggestion to have the correct text in requirejs mode.

**Comment by pixelzoom** [comment]
Agreed that this should do the job:

> getStringMap( grunt, buildConfig )[ ChipperConstants.FALLBACK_LOCALE ][ buildConfig.simTitleStringKey ];

But when called in generateDevelopmentHTML.js, it currently returns an empty string map.  So there's a problem somewhere, and that's going to take time to investigate.

**Comment by pixelzoom** [comment]
The string map is empty because `global.phet.chipper.strings` is `{}` when called from generateDevelopmentHTML.js. So getStringMap returns an empty map for each locale.

**Comment by pixelzoom** [comment]
In order to get the sim title, `global.phet.chipper.strings` needs to be populated, which requires the `string.js` plugin to run in build mode, which requires the `requirejs-build` task to run.  That's a lot of heavyweight stuff just to get the sim title for the development HTML file. And figuring out how to run the string plugin separately from `requirejs-build` is a serious time investment.  So for the development HTML file, I'm going to use the repository name as the browser window title.

**Comment by pixelzoom** [comment]
All development html files have been regenerated using `grunt-all.sh generate-development-html`. 

I tested a couple of builds to confirm that title is correct in built sims after removing code from Sim.js.

@jonathanolson Would you please review?

**Comment by jonathanolson** [comment]
Looks good.

Only further comment is if we need to worry about sim_all.html titles. Hopefully we don't need to, as they are probably embedded in another page/application.

Thoughts?

**Comment by pixelzoom** [comment]
What is sim_all.html? I don't see any such file in GitHub.

**Comment by jonathanolson** [comment]
See https://github.com/phetsims/chipper/issues/509, added recently. Generated with builds (_all instead of _(locale)), and contains string information for all locales, so the locale can be selected at launch-time with the query parameter.

**Comment by pixelzoom** [comment]
That explains where buildConfig. availableLocales, which I added documentation for in @5907a8c24ced19bdfda877bfc884eb3172b5cfed.

So back to @jonathanolson's question:
> Only further comment is if we need to worry about sim_all.html titles. Hopefully we don't need to, as they are probably embedded in another page/application.

Not clear to me what's involved here, and I'm still not familiar with what this is (since https://github.com/phetsims/chipper/issues/509 contains no useful information to that affect).  So I guess I'll need to generate this thing and figure it out.

**Comment by pixelzoom** [comment]
The grunt help for `--allHTML` says:

> --allHtml : Generate the _all.html file that contains information for all locales

I ran `grunt --allHTML` for function-builder, and opened function-builder_all.html.  It does not show me "information for all locales" (whatever that is), it shows me the English sim and nothing more. Is there perhaps some other option that needs to be included?  And what is "information for all locales"?

Assigned to @jonathanolson.

**Comment by samreid** [comment]
The all HTML was recently proposed as the solution to i18n on the iOS app.

**Comment by jonathanolson** [comment]
> I ran grunt --allHTML for function-builder, and opened function-builder_all.html. It does not show me "information for all locales" (whatever that is), it shows me the English sim and nothing more. Is there perhaps some other option that needs to be included?

Yes, run the built sim file with ?locale=es (or another locale), and it should load in that locale. This is possible since it embeds strings for every locale into the built sim, instead of just embedding strings for one locale.

What are the places where I can improve documentation for this?

**Comment by pixelzoom** [comment]
If the documentation for `--allHTML` is accurate ("contains information for all locales"), then why do I need to add `--locales=*`?   Imo, the absence of `--locales` should automatically build all locales, and the grunt help doc should be changed to:

```
--allHtml : Generates the _all.html file that contains strings for all locales. If the --locales option is used, the file will contain strings for only the specified locales. Note that `--locales=*` is equivalent to omitting the `locales` option.
```

**Comment by pixelzoom** [comment]
Let's continue the discussion about `--allHTML` in https://github.com/phetsims/chipper/issues/509.

Back to the related question that needs to be addressed here... In https://github.com/phetsims/chipper/issues/510#issuecomment-254660600, @jonathanolson said:
> Only further comment is if we need to worry about sim_all.html titles. Hopefully we don't need to, as they are probably embedded in another page/application.

And in https://github.com/phetsims/chipper/issues/510#issuecomment-255094976, @samreid said:
> The all HTML was recently proposed as the solution to i18n on the iOS app.

So what I currently know about the all.html file is:
• It has something to do with the PhET iOS app.
• It contains translated strings for all locales
• The html file looks like English when you run it.

And I have no idea what that means for whether "we need to worry about sim_all.html titles". @jonathanolson or @samreid, can you please clarify?

**Comment by pixelzoom** [comment]
Also highly recommended to rename this option from `allHtml` to `allHTML`.

**Comment by jonathanolson** [comment]
> If the documentation for --allHTML is accurate ("contains information for all locales"), then why do I need to add --locales=*?

I don't see where the documentation specifies that ```--locales``` is needed (it isn't).

**Comment by jonathanolson** [comment]
> The html file looks like English when you run it.

Defaults to English.

As for the purpose of the file, the issue:

> Add simname_all.html that includes string data for all locales
> Uses locale query parameter to select on startup. See phetsims/phet-app#234

And noted in the related issue:

>> Augment our build process so that we have a version that includes all strings, and locale could be set with a query parameter or such.

> Would something like (simname)_all.html be a good solution, deployed in the same directory? In the past, this is fairly easily differentiated from an actual locale.
> 
> There's already the relevant query parameter, and IIRC once the strings are embedded in the sim, it should work as expected.

**Comment by jonathanolson** [comment]
> And I have no idea what that means for whether "we need to worry about sim_all.html titles". @jonathanolson or @samreid, can you please clarify?

The _all.html would usually be run with a locale query parameter which sets the locale on startup, but the auto-generated HTML currently adds the English title. Should we dynamically set the title based on the locale query parameter?

**Comment by pixelzoom** [comment]
Great, that's the information that I needed - for locales other than English, the title isn't localized.

**Comment by pixelzoom** [comment]
Title for all.html addressed in Sim.js.  Note that the title is currently displayed in English until the Sim constructor runs. Is that acceptable?   If not, then perhaps the sim template should not include a title, and the title should be added (for all locales) by Sim.js.

@jonathanolson your thoughts?

**Comment by jonathanolson** [comment]
> Title for all.html addressed in Sim.js. Note that the title is currently displayed in English until the Sim constructor runs. Is that acceptable? If not, then perhaps the sim template should not include a title, and the title should be added (for all locales) by Sim.js.

That seems totally acceptable to me.

**Comment by pixelzoom** [comment]
Here's another idea...

Put this in all sim templates:

```
<title>Will be set by Sim.js</title>
```

Do this unconditionally in Sim.js:

```js
$( 'title' ).html( name );
``

Then the title would be correct for any invocation of a sim, including dev versions (it's currently the repos name).   But would it have issues when a sim is embedded in another page?

**Comment by pixelzoom** [comment]
The templates that would have `<title>Will be set by Sim.js</title>` are:

sim-chrome-web-store.html
sim-development.html
sim-iframe.html
sim.hmtl

**Comment by pixelzoom** [comment]
These 2 lines would be removed from createHTMLFiles.js:

```js
219 string = ChipperStringUtils.replaceFirst( string, 'PHET_SIM_TITLE', encoder.htmlEncode( localizedTitle ) );
275 iframeTestHtml = ChipperStringUtils.replaceFirst( iframeTestHtml, 'PHET_SIM_TITLE', encoder.htmlEncode( simTitle + ' iframe test' ) );
```

This line would be removed from generateDevelopmentHTML.js:

```js
46 html = ChipperStringUtils.replaceAll( html, '{REPOSITORY}', repositoryName );
```

**Comment by jonathanolson** [comment]
It doesn't sound ideal to have Sim.js mentioned in the visible title of production sims, and for locale-specific sims (e.g. _en.html), we want the proper title in the HTML for search engines.

It would be less than ideal for "Will be set by Sim.js" to be shown in Google search results for our sims.

**Comment by pixelzoom** [comment]
OK, then let's stick with the current approach, with these known "warts":

• English title is briefly visible in all.html
• Repository name is the title of developer html.

@jonathanolson Anything else to do here, or can this be closed?

**Comment by jonathanolson** [comment]
Looks good, thanks!
