### ISSUE TITLE
template files use different conventions for placeholders

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#511]
Noted while working on https://github.com/phetsims/chipper/issues/510.

Tokens within the html templates are replaced by grunt tasks.

In sim.html and sim-iframe.html, the tokens are all uppercase, e.g.:

```
window.phet.chipper.strings = PHET_STRINGS;
```

In sim-development.html, the tokens begin and end with curly braces, e.g.:

```
var preloads = ( brand === 'phet-io' ) ? {IO_PRELOADS} : {PRELOADS};
```

Should the same convention be used in all templates? Which convention?

**Comment by pixelzoom** [comment]
+1 for having tokens begin and end with curly braces. It makes it more obvious that they are token, and makes it easier to search for tokens.

**Comment by pixelzoom** [comment]
Please discuss this without me at 10/20 developer meeting. My opinion is in the comment immediately above.  And feel free to assign to me to do the work, since I've recently been in these files.

**Comment by samreid** [comment]
+1 for curly braces.

**Comment by samreid** [comment]
@andrewadare said he was thinking of $$ as well

**Comment by samreid** [comment]
Mustache and other templating engines use {{}}

**Comment by samreid** [comment]
@aadish said we could use https://lodash.com/docs/4.16.4#template

**Comment by jbphet** [comment]
Discussed at 10/20/2016 developer meeting, and had a lot of different ideas about whether to adopt something used by another template platform or what, so we're deferring until next dev meeting when @pixelzoom is back.

**Comment by samreid** [comment]
Also, {VAR} is valid es6 code, so perhaps we should use a different pattern.

**Comment by pixelzoom** [comment]
10/27/16 consensus: Double curly braces, e.g. `{{PHET_SIM_TITLE}}```.

**Comment by pixelzoom** [comment]
Notes for @andrewadare:
• build process templates are in chipper/templates, related code is in createHTMLFiles.js.
• additional templates are in phet-io, talk to @samreid

**Comment by andrewadare** [comment]
Also on the list:
 - search for `$` in phet-io to replace with double curlies

**Comment by samreid** [comment]
And:

* search in copySupplementalPhETIOFiles.js

**Comment by samreid** [comment]
Master checklist of other places we've the pattern that should be changed:

- [ ] Dot Gruntfile
```js
var html = template.replace( '$API_INDEX$', indexHTML ).replace( '$API_CONTENT$', contentHTML );
```

- [ ] copySupplementalPhETIOFiles.js
```js
      contents = ChipperStringUtils.replaceAll( contents, '$SIMULATION_NAME$', buildConfig.name );
      contents = ChipperStringUtils.replaceAll( contents, '$SIMULATION_VERSION$', buildConfig.version );
```

- [ ] createSim.js
```js
        // Replace the title
        contents = ChipperStringUtils.replaceAll( contents, '$TITLE$', title );

        // Replace author
        contents = ChipperStringUtils.replaceAll( contents, '$AUTHOR$', author );
```

- [ ] generateReadme.js
```js
  readme = ChipperStringUtils.replaceAll( readme, '{REPOSITORY}', repositoryName );
  readme = ChipperStringUtils.replaceAll( readme, '{TITLE}', title );
  readme = ChipperStringUtils.replaceAll( readme, '{CLONE_COMMANDS}', cloneCommands );
```

**Comment by andrewadare** [comment]
Tests were carried out before the above commits:

* README generation in chipper
* The doc/reference page for dot's API was generated
* A new sim was created from simula-rasa, it was launched and inspected
* All PhET-iO HTML pages visible from the launcher appear to have the correct sim name and version.

@samreid updated every templated string that we could find throughout all PhET repos to follow a standard {{}} enclosure pattern.

**Comment by samreid** [comment]
Did you test an phet-io build, and also test Instance Proxies => launch?

**Comment by andrewadare** [comment]
It looks like we missed load-state-template.html. Updated now. But the iframe launched from instance-proxies has a 404 error for SimIFrameClient:

![image](https://cloud.githubusercontent.com/assets/154163/19821541/23c9bfac-9d1c-11e6-8b7f-0e6561be3c07.png)


I tried testing a phet-io build, but got stopped by lint errors in classroom-activity.js.

**Comment by samreid** [comment]
We got the templates working and well tested during last week's rollout.  Closing.
