### ISSUE TITLE
delete 'chromeWebStore' option?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#513]
This came up at 10/27/16 dev meeting, while discussing https://github.com/phetsims/chipper/issues/509#issuecomment-255825254.  The `chromeWebStore` options seems like an unfinished feature, and (according to @ariel-phet) it's unlikely to be representative of how PhET would do this now.   So should we remove this feature from the build process?

Labeled for developer meeting, when @mattpen is present.

**Comment by samreid** [comment]
@ariel-phet says: we will likely create an Android app that will supercede the Chrome Web Store version.

@mattpen says if we resume work on this we can resurrect the code.

Assigned to @mattpen to remove the chromeWebStore occurrences for now.

**Comment by pixelzoom** [comment]
More related code in google-analytics.js:

```js
63    else if ( phet.chipper.getQueryParameter( 'chrome-webstore' ) ) {
64      phetPageviewOptions.dimension5 = 'chrome-webstore';
65    }
```

This query parameter is not documented in initialize-globals.js.

**Comment by mattpen** [comment]
Chrome webstore options were removed from google-analytics.js, createHTMLFiles.js, and Gruntfile.js.

**Comment by pixelzoom** [comment]
Reopening. While working on https://github.com/phetsims/chipper/issues/516, I discovered `chipper-string-setup.js`, which is using `getQueryParameter`.  The file was created by @jonathanolson with the commit message "Testing for building Chrome web-store-compatible files, see phetsims/tasks#403".

@jonathanolson Can `chipper-string-setup.js` be deleted? If not, why is it in templates?

**Comment by pixelzoom** [comment]
I also see sim-chrome-web-store.html in chipper.

**Comment by mattpen** [comment]
@pixelzoom - That template was not used anywhere that I could find.  I removed it.

**Comment by pixelzoom** [comment]
Reopening again - `chipper-string-setup.js` (mentioned in https://github.com/phetsims/chipper/issues/513#issuecomment-260245101) not addressed.

**Comment by jonathanolson** [comment]
Removed, no need to keep it. I believe that's everything (did a quick search), closing.

**Comment by pixelzoom** [comment]
👍
