### ISSUE TITLE
move some query parameters to phet-io's schema

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#517]
In https://github.com/phetsims/chipper/issues/516#issuecomment-259238082, @samreid said:
> phet-io should have its own schema for query parameters that apply to most wrappers. 

Please identify which of the query parameters below (currently in chipper.QueryParameters) should be moved to phet-io's schema:

```js
    // when running a simulation using phetio.js, outputs states and deltas within the phetioEvents data stream, see phetio.js
    'phet-io.emitDeltas': { type: 'flag' },

    // when emitting deltas using phetio.js (see phet-io.emitDeltas) emit deltas that are empty, to simplify playback in some systems like Metacog.
    'phet-io.emitEmptyDeltas': { type: 'flag' },

    // emit the Scenery input events
    'phet-io.emitInputEvents': { type: 'flag' },

    // when running a simulation using phetio.js, outputs the state at the end of every frame
    'phet-io.emitStates': { type: 'flag' },

    // will output type documentation to the console, see https://github.com/phetsims/phet-io/issues/218
    'phet-io.docs': { type: 'flag' },

    // evaluate expressions on phet-io wrapper objects, like: ?phet-io.expressions=[["beaker.beakerScreen.soluteSelector","setVisible",[true]]]
    'phet-io.expressions': {
      type: 'string',
      defaultValue: null
    },

    // Specifies where to log phetioEvents
    'phet-io.log': {
      type: 'string',
      defaultValue: null,
      validValues: [
        null, // no logging
        'console', // stream to console in JSON format
        'lines' // stream colorized human-readable events to the console (Chrome and Firefox only)
      ]
    },

    // Causes a phet-io simulation to launch, even without a wrapper "go-ahead" step, see phet-io#181
    'phet-io.standalone': { type: 'flag' },

    // When running as phet-io assertions are normally thrown when uninstrumented objects are encountered.
    // Setting this to false will allow the simulation to proceed.  Useful for partially instrumented simulations.
    'phet-io.validateTandems': {
      type: 'flag',
      defaultValue: true
    },
```

**Comment by pixelzoom** [comment]
Searching for `'phet-io.`, the only uses that I see outside of the phet-io repository are:

Sim.js line 60:
```js
if ( phet.chipper.getQueryParameter( 'phet-io.standalone' ) || phet.chipper.brand !== 'phet-io' ) {
```

Tandem.js line 241:

```js
      if ( phet.chipper.brand === 'phet-io' && phet.chipper.getQueryParameter( 'phet-io.validateTandems' ) !== 'false' ) {
```

**Comment by pixelzoom** [comment]
I'm trying to wrap up https://github.com/phetsims/chipper/issues/516, so raising the priority of this to high.

**Comment by samreid** [comment]
Full context from my quote mentioned the issue description:

https://github.com/phetsims/chipper/issues/516#issuecomment-259238082
> phet-io should have its own schema for query parameters that apply to most wrappers. But many of the query parameters are specific to a single wrapper. For those cases, the wrapper should define the schema. @andrewadare, @zepumph and I can take care of porting the phet-io query parameters to QSM.

However, the simulation query parameters should remain in chipper/initialize-globals.  I'll take a look at them shortly.

**Comment by samreid** [comment]
I reviewed the usage of phet-io query parameters in initialize-globals, made 2 cleanup commits (above) and everything else looks good.

@pixelzoom anything else to do here?

**Comment by pixelzoom** [comment]
I don't see `phet.chipper.queryParameters` being used for any of these query parameters.  I see usages of `QueryStringMachine.get`.  E.g. phetio.js line 317:

```js
if ( QueryStringMachine.get( 'phet-io.emitInputEvents', { type: 'flag' } ) ) {
``` 

... and similarly for all of the query parameters identified in https://github.com/phetsims/chipper/issues/517#issue-188090947 (except 'pheti-io.docs', which was deleted.)  You've duplicated the schemas, and this is an opportunity for those query parameters to get out of sync with initialize-globals.js.

**Comment by samreid** [comment]
Thanks for clarifying the problem @pixelzoom.  I've factored out the simulation query parameters in the above commits.  The wrapper query parameters do not (and should not) use chipper's initialize-globals, so I've left them alone for now.  Would you like to review?

**Comment by pixelzoom** [comment]
👍
