### ISSUE TITLE
make query parameter documentation friendly to non-developers

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#520]
I alerted @phet-steele to the recent conversion to QueryStringMachine. The documentation was pretty much copied from what was previously at the top of initialized-globals.js.  @phet-steele suggested that, as a "back burner task" it would be nice to make the documentation more friendly to non-developers.

Skype discussion:
> [11/21/16, 3:35:29 PM] Steele Dalton:  I was planning on someone going in and adding more layman friendly explanations for each qp.
[11/21/16, 3:36:37 PM] Chris Malley: We will like simplify the 'flag' type (no value allow, 'true' if present, 'false' if absent).   But otherwise done.
[11/21/16, 3:37:05 PM] Chris Malley: Let's coordinate on how to make the documentation more friendly.

**Comment by pixelzoom** [comment]
@phet-steele Let's start by identifying which query parameters have (in your opinion) inadequate or overly technical documentation.

**Comment by pixelzoom** [comment]
Looking through initialize-globals.js, it seems like the majority of query parameters are specific to developers.  

There's a very small subset that may be of interest to testers:  

> dev
fuzzMouse
fuzzRate
profiler
showPointerAreas
stringTest

And an even smaller subset of interest to designers:

> dev
showPointerAreas
stringTest

@phet-steele Are there others that you think would be useful to designers and testers?

**Comment by KatieWoe** [comment]
The QA book now has a list of query parameters that are often used with a brief description of what they do.

**Comment by pixelzoom** [comment]
@KatieWoe your previous comment was very timely.  Some query parameters are not _private_, intended for use by team members only.  The means of enabling private query parameters needs to be kept private, so can't be described in the QA Book.  A draft description is at https://github.com/phetsims/special-ops/issues/129#issuecomment-470688353.  Let's discuss how to make this information accessible to team members, while still keeping it private.

**Comment by pixelzoom** [comment]
@KatieWoe and I discussed private query parameters on Zoom, so she's up to speed.

**Comment by lmulhall-phet** [comment]
Can this issue be closed? I'm fairly certain the QA Book now has documentation for private query parameters. (QA Book links to a markdown document in a private repo.)

**Comment by lmulhall-phet** [comment]
https://github.com/phetsims/QA/blob/master/doc/qa-book.md#private-query-parameters
