### ISSUE TITLE
About dialog does not list publication date properly

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/chipper#521]
@kathy-phet said

> I'm not sure who to best send this question to. I was looking for the publication dates of our latest sims, and in the past I was able to look under the "About" menu and if it was 1.0 it would list the publication date.
> 
> I tried this on our newest simulations, and something is inconsistent ... and I don't know exactly where is would be getting inconsistent.
> 
> For instance, if I look at the about menu for plinko probability it looks like this ... it says 1.0.0 with 11/12/2016 as publication date --- but I know this sim was published in September based on the email thread. The other two sims in the "latest" category (atomic interactions and charges and fields) all have the 11/12/16 date as the publication date.

![plinko](https://cloud.githubusercontent.com/assets/4051174/20571706/d88c555a-b165-11e6-9b61-f28515203d67.PNG)

**Comment by ariel-phet** [comment]
@jonathanolson isn't this related to the fact that the english version is currently being rebuilt when a sim translation is being built? I don't think this is a high priority to fix, but I think we were considering changing a few things in the future also so that the PhET app is not necessarily updated everytime a translation is made.

**Comment by jonathanolson** [comment]
The date/time shown isn't related to when the sim or sim version was published. That is solely the build date for that particular file.

It MAY be re-built when a non-English translation is submitted (@jbphet, is that true?), and if so it might be worth trying to update only the affected locales.

**Comment by jbphet** [comment]
Yes, there seems to be an issue where the English version is rebuilt each time a new translation comes along, see https://github.com/phetsims/rosetta/issues/142.

**Comment by ariel-phet** [comment]
The root of this problem appears to be caused by phetsims/rosetta#142.

Closing this issue, since listing the publication date is not the purpose of of the date being shown, and is not a key requirement of the about dialog.
