### ISSUE TITLE
Add a lint rule that PHET_IO has ifphetio!

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#522]
@jessegreenberg pointed out that Tandem was missing ifphetio! in its import.  We could catch this earlier by adding a lint rule that requires ifphetio! in require statements (except for the phetio repo).  Or it could be easier to change the imports in the phet-io repo to all read "ifphetio!" as well.

@zepumph volunteered to check it out, thanks!

**Comment by zepumph** [comment]
I added the lint rule such that require statements not in the phet-io repo must include ifphetio! . It shows 0 places where this needs to be filled in, which is better than expected, wahoo! I'm going to commit this rule to master. @samreid would you mind giving it a once over before closing.

**Comment by samreid** [comment]
I tested it and skimmed the code, it seems to be working great, nice work!   Closing.
