### ISSUE TITLE
HEAD is not a branch

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#525]
When dependencies.json is created, it sometimes marks some of the branches as "HEAD".  However, this is not a branch.  How can this possibly be correct?

@jonathanolson @pixelzoom @jbphet can you help at your convenience?

**Comment by pixelzoom** [comment]
Example?

**Comment by pixelzoom** [comment]
Example? (link to blob)

**Comment by jonathanolson** [comment]
In a repo:
```
$ git rev-parse --abbrev-ref HEAD
master

$ git checkout git checkout cleanup
$ git rev-parse --abbrev-ref HEAD
cleanup

$ git checkout 5d5559beedcf7152d24c8e38759466fa5b628735
$ git rev-parse --abbrev-ref HEAD
HEAD
```
because yes, the repo is not on a named branch, but on a detached head. Would it be better to name it 'head-abbreviated-reference' than 'branch' (presumably not)?

**Comment by pixelzoom** [comment]
>  Would it be better to name it 'head-abbreviated-reference' than 'branch' (presumably not)?

Definitely not ;)

**Comment by samreid** [comment]
I see, so perhaps saying "HEAD" is like saying "there is no branch".  I think I understand.  Closing.
