### ISSUE TITLE
Prevent and/or Reduce duplicated code

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#526]
In https://github.com/phetsims/phet-info/issues/37 I added scripts that report the amount of duplicated code across our repositories.  You can run it like so:

```js
grunt find-duplicates --everything > ../chipper/data/duplicates.txt
```

Then duplicates.txt shows you all duplicates, and a diff of duplicates.txt (vs previous version) shows you new copy-pasted code.  We can use this tool to detect new duplicates or reduce the amount of existing duplicated code.  It would be nice if we had a process for managing this, perhaps I'll report in this issue the current status of duplicates.txt and we can run it intermittently to make sure things aren't getting worse.

Current status:
info: Found 481 exact clones with 9290 duplicated lines in 443 files
1.81% (9290 lines) duplicated lines out of 514538 total lines of code.

**Comment by zepumph** [comment]
`findDuplicates.js` has a todo that I'm linking here:

`// TODO: Looks like a decent amount of cleanup in this file. Not up to standards yet`

**Comment by samreid** [comment]
In https://github.com/phetsims/chipper/issues/993 we decided to remove this file, closing.
