### ISSUE TITLE
Add a lint rule to check on PhET-iO instrumentation in Sun and scenery-phet

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#531]
To fix phetsims/phet-io#668, we would like to check that files in Sun and Scenery-phet have `Tandem.validateOptions` (indicating that they are instrumented) or `Tandem.indicateUninstrumentedCode` indicating that they are uninstrumented.

**Comment by samreid** [comment]
@zepumph said he can use this rule after I create it to complete https://github.com/phetsims/phet-io/issues/668.  So I'll create the rule, and add an entry to .eslintrc with the rule disabled. @zepumph will enable the rule in his working copy, then when all files are passing, he can enable the rule and commit .eslintrc.

**Comment by samreid** [comment]
I added the new lint rule above.  It is currently set to `"require-tandem-support": 0` which is ignored.  @zepumph we will need to discuss details about this, such as the fact that there are several source files in sun that shouldn't be tandemized (like the namespace)--we will need to come up with an elegant way to annotate those files or blacklist them in the lint rule.  Also, this rule is currently reporting 142 problems, which does not bode well.  We should chat!

**Comment by zepumph** [comment]
@samreid I can't seem to recreate these lint errors, I tried a few different things. 
1. `grunt` and `grunt --brand=phet-io` in an intrumented and uninstrumented sim.
2. grunt lint-everything
3. grunt lint in `sun/`

But beyond that. I think we should talk about this issue a little more before I do too much with it.

**Comment by zepumph** [comment]
By the way I also set `"require-tandem-support": 2`

**Comment by zepumph** [comment]
Starting with sun ( only 50 errors).

Create a blacklist of files that don't need this support:
+ /demo/
+ -main.js
+ -config.js
+ sun.js
+ sun-query-parameters.js


The only files that need to be included in this rule are view components.

**Comment by zepumph** [comment]
Because of https://github.com/phetsims/phet-io/issues/949,

we will need to update this lint rule so that it checks for the line 'createDefaultTandem' and 'addInstance' instead of validateOptions, as that is deprecated.

**Comment by samreid** [comment]
@zepumph thanks for working on this.  I had a few questions about the implementation.

(1) I noticed that you are putting the `Tandem.indicateUninstrumentedCode();` in the require statements, like so:

```js
  var Tandem = require( 'TANDEM/Tandem' );
  Tandem.indicateUninstrumentedCode();
```

I was wondering whether you considered putting these statements in the constructor bodies instead, and what the tradeoffs are?  As I was investigating this, I discovered that putting the `indicateUninstrumentedCode` outside of the constructor makes it less clear (in the call stack) what code is requiring the uninstrumented common code.  On the other hand, the error is caught earlier in the loading process.

(2) I was surprised to see that simulations are relying on many files that have `Tandem.indicateUninstrumentedCode();`.  For instance, I tried to run faraday's law in the recorder wrapper and ran into many errors of this sort.  I recommend to disable the body of `indicateUninstrumentedCode` until all PhET-iO simulations are passing.  Phetmarks has an aqua test with "Test PhET-IO sims" that can help us check for coverage.

**Comment by samreid** [comment]
Heads up to @jbphet @jessegreenberg and @mattpen that PhET-iO simulations may not work in master until the preceding comment is addressed.

**Comment by zepumph** [comment]
Sorry about that, that was dumb not to test it. I turned off the lint rule. @samreid I started adding it below the require lines for the ease of it. It cut my work in half to copy paste one block instead of two. I also didn't foresee any difference, but I didn't think about the anonymous call stack function (this will make it much easier to do (2) from your comment above).  Fortunately it only took about 45 minutes to do all of additions, so it won't be so bad to put it into the constructor of the files.

**Comment by zepumph** [comment]
As I go about fixing all of the current phet-io sims, I have a few questions. @samreid do we want to instrument everything in these repos? For example PhetFont, does that need a tandem passed to it every time it is used?

Also would you mind double checking my 'blacklist' in `require-tandem-support.js` to make sure I'm not leaving anything out/in.

**Comment by samreid** [comment]
I don't think it's practical to instrument every single feature/file/line of code.  Instrumenting PhetFont seems like it would empower clients to customize the fonts during startup (say, making text bigger), which might be valuable.  That being said, it seems it would be a huge effort to pass tandems to every single PhetFont in a sim.  We may need a 3rd strategy: common code which is instrumented but does not require a Tandem.  I used this pattern for ObservableArray and it seemed like a good match.

**Comment by samreid** [comment]
The blacklist looks good so far, but I'm wondering about your opinion about putting the "opt-out" messages in the files themselves.  For instance, in VisibleColor.js there could be a line `// eslint-disable require-tandem-support` to indicate that file does not need to be instrumented.

Pro-distributed: file renames won't disrupt linting
Pro-centralized: it is nice to see the blacklist all at once

**Comment by samreid** [comment]
> I don't think it's practical to instrument every single feature/file/line of code

Maybe we should be more selective about what *must* be instrumented.  For instance, UI components (like CheckBoxes, Radio Buttons, Sliders, Faucets, etc), seem necessary.  Auxiliary, utility and support files probably don't need to be instrumented.

**Comment by zepumph** [comment]
Sounds good. I just got phet-io fuzz testing passing, and it took removing the assert from 50 files. I don't think it is worth passing tandem to all of those. That would be a tremendous effort. 

As for the blacklist, I could go either way, but would rather focus on the other part of this issue now.

**Comment by zepumph** [comment]
Should we create another Tandem method called something like `Tandem.recognizeUnnecessaryToSupportTandem()` haha or something

**Comment by zepumph** [comment]
This will be handled in phetsims/phet-io#985. Closing
