### ISSUE TITLE
Simulations package.jsons should not have entries for requirejs or uglify

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#538]
Requirejs and uglify are provided by chipper, and chipper should use its own copies.  See https://github.com/phetsims/chipper/issues/532#issuecomment-270820361

**Comment by samreid** [comment]
I removed requirejs and uglify from sim package.jsons and spot tested building and launching 2 sims (after rm -rf node-modules and npm install).  All seems well, committing.

**Comment by samreid** [comment]
I removed the extraneous entries from sim package.json files above.  Next I'll look into scenery/kite/dot/axon.

**Comment by samreid** [comment]
I removed:

```
    "grunt-requirejs": "~0.4.0",
    "uglify-js": "~2.4.0",
    "requirejs": "~2.1.8",
```
from dot/package.json and rm -rf node_modules && npm install && grunt build succeeded and 1443/1443 compiled tests are passing.  @jonathanolson anything else I need to test for scenery/kite/dot before removing these lib references?

**Comment by jonathanolson** [comment]
Verifying if Kite's ```generate-svgPath-parser``` grunt task works would be good. If that works, removing scenery/kite/dot references sounds great!

**Comment by samreid** [comment]
Kite's `generate-svgPath-parser` seems to work fine.  Committing...

**Comment by samreid** [comment]
Fixed above in dot and kite.  Scenery and axon were already pruned.
