### ISSUE TITLE
Why is the build directory getting sub-deployed?

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#539]
I noticed http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-black-box-study/1.0.6-phetio/

had a nested "build" directory. Why?

![image](https://cloud.githubusercontent.com/assets/679486/21730902/221ded2a-d40f-11e6-902b-370d6216f84e.png)

**Comment by samreid** [comment]
@mattpen did you see something like this recently, perhaps in perennial?

**Comment by mattpen** [comment]
https://github.com/phetsims/perennial/commit/1867a7f688698f74cfce9e2363ecaefe4c1c1c2d

This commit is probably the reason.  I guess I don't understand which files exactly should be copied to spot.  Can we create a list of files that should and should not be copied?

**Comment by mattpen** [comment]
We investigated this in dev meeting.  The leading hypothesis is that this is caused by a bug in an old sha of chipper, and has not happened since.  We'll check again in a month.

**Comment by mattpen** [comment]
Adding to developer meeting to discuss if anyone has seen strange artifacts like this in the build directory in the past month.

**Comment by mattpen** [comment]
We should also discuss closing https://github.com/phetsims/chipper/issues/539 if builds have been going as expected.

**Comment by samreid** [comment]
I haven't seen any problems recently.

**Comment by mattpen** [comment]
No one reported any nested build directories in the last month at dev meeting.  Closing.
