### ISSUE TITLE
Change cacheBust to boolean with default value true, and passthrough query parameter from phetmarks

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#541]
cacheBuster saved us many times in the past while we were getting used to JS caching, but now it is somewhat of a hindrance because it is impossible to set breakpoints in the dev tools and have them persist across reloads.  We can use a query parameter cacheBuster=false, but I'm wondering if this would be a good time to set cacheBuster=false by default.  I'm wondering what will happen on iPad--perhaps cache buster is essential there.

**Comment by samreid** [comment]
I'm commandeering this issue based on today's dev meeting discussion.

@jessegreenberg said:

> I have been tricked by browser caching a lot lately, especially on iOS Safari and Firefox. Would it be possible to enable ?cacheBust by default in RequireJS? Or possibly by default from phetmarks?

@jonathanolson replied:
> This has been a pain point for me. I would at least prefer making it a default in phetmarks, as it is incredibly rare for me to want the caching.

I replied
> It’s been very productive for me to have persistent breakpoints across reloads.  I have to remember to run with dev tools open so I don’t get stale cache, but it has been worth the trouble for me.  But maybe we need to make it so different developers can have different defaults?  Perhaps a pass-through query parameter for phetmarks?  Like if you bookmark http://localhost/phetmarks/?cacheBust then that query parameter passes through to launched sims?

@pixelzoom said:
> +1 for pass-through query parameters, +1 cacheBust=true default

@jbphet said:
> +1 for pass-through query parameters, +1 cacheBust=true default

@Denz1994 said:
> +1 for cacheBust = true default

Consensus:

SR: I’ll make it boolean, default to true.  There is a usage in phettest to change.  I’ll pass through query parameters in phetmarks.  Hopefully next week!
MK: Update logic in the dev HTMLs
CM: Update the config.js files, probably just doc?

**Comment by samreid** [comment]
The core changes are committed above, those commits will be most pertinent for review.  Following are the commits for `grunt update`.

**Comment by samreid** [comment]
Note to self to consider https://github.com/phetsims/chipper/issues/759 and phettest moving forward.  Commits to many repos follow.

**Comment by jessegreenberg** [comment]
Thanks for working on this @samreid, I can work on the phetmarks part. Is it still beneficial to "pass through" phetmarks or can we add an entry in the phetmarks query param list?

**Comment by samreid** [comment]
I'm sure I would use that "pass through" too much, let's see if it is important for others.

**Comment by pixelzoom** [comment]
@samreid The way that this is presented in phetmarks is confusing, it's a checkbox whose value is !cachBust.  Can we please change to this default:

> - [x] Cache busting (cacheBust=true|false)

**Comment by jessegreenberg** [comment]
Agreed its a little confusing. But when a checkbox above is unchecked it doesn't set a value to false it just allows default value for query param. Since default for `cacheBust` is true in initialize-globals we need the checkbox to disable.

**Comment by jessegreenberg** [comment]
So for meeting 11/14/19 there are two remaining questions.

Does anyone want the ability to pass a query parameter to phetmarks to populate values of the sim "Query Parameters" checkboxes?
Can we live with a "Disable Cache Bust" checkbox or should we work on changing this to a "Cache Bust" checkbox?

**Comment by samreid** [comment]
@zepumph recommends a new issue in phetmarks to properly support boolean query parameters in phetmarks, rather than just being able to append a string or not.
