### ISSUE TITLE
grunt task that generates accessibility test html

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/chipper#547]
It would be nice to have a grunt task that generates a top-level file that runs the sim in an iframe with a copy of the accessibility DOM on the side. It is very useful for accessibility development, and demonstrations, and would be useful for all sims.

**Comment by zepumph** [comment]
@jessegreenberg can we close this, is this the a11y view?

**Comment by jessegreenberg** [comment]
It is, thanks  @zepumph. closing.
