### ISSUE TITLE
Should the require statements be alphabetized?

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#549]
@Denz1994 said @jbphet suggested alphabetizing the require statements.  I haven't been doing this.  What are the benefits?  Drawbacks?  Is it worth the time?

@pixelzoom and @jonathanolson have you been doing this?  What do you recommend?

**Comment by pixelzoom** [comment]
My name is @pixelzoom, and I am a habitual alphabetizer of `require` statements.  Besides satisfying my OCD-ness... 

> What are the benefits? 

I can't point to any significant benefits, other than a slight reduction in the chance of accidentally duplicating `require` statements (which would be reported by eslint).  

> Drawbacks
The only drawback I can point to is the general drawback of having different conventions - which in this case is insignificant. 

>  Is it worth the time?

This is a moot question, unless you measure your time to add `require` statements in milliseconds.  

> What do you recommend?

I recommend that we stick with what we decided when we discussed this "long ago": (a) no convention is necessary, and (b) when modifying code, be consistent with the convention used in the code.  Agreement (b) has not always been kept, but not a big deal, I just reorder the `require` statements when I notice.

**Comment by jonathanolson** [comment]
> @pixelzoom and @jonathanolson have you been doing this? What do you recommend?

I haven't been doing this, but I've thought about it. Sublime has a quick shortcut to alphabetize selected lines, but having something automated would have problems with more odd cases, e.g. like this in Node:
```js
  var Accessibility = require( 'SCENERY/accessibility/Accessibility' );
  require( 'SCENERY/util/CanvasContextWrapper' );
  // commented out so Require.js doesn't balk at the circular dependency
  // require( 'SCENERY/util/Trail' );
  // require( 'SCENERY/util/TrailPointer' );
```

> I recommend that we stick with what we decided when we discussed this "long ago": (a) no convention is necessary, and (b) when modifying code, be consistent with the convention used in the code.

No major preference for my code keeping the specific ordering it has now, don't mind if it gets changed. I'll be fine if we leave things as-is, or standardize on @pixelzoom's preferred ordering.

**Comment by samreid** [comment]
@jbphet does it sound OK to you if we do *not* require ordering of the require statements?

**Comment by jbphet** [comment]
Yes, I'm okay with not requiring it.  I didn't really recommend it to @Denz1994 - I just let him know that I do it and I find it helpful when looking at the require statements in order to quickly see whether a given type is already included.  I'll continue to do it in my own code.

**Comment by samreid** [comment]
Reassigned to @Denz1994 to make sure he is aware of this decision.  @Denz1994 after reviewing this issue, you can close it.
