### ISSUE TITLE
Update devDependencies for all sims

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#55]
I updated sherpa libs in https://github.com/phetsims/sherpa/issues/1 but perhaps we should also update the devDependencies for each sim.  Here are the current versions as coded in ph-scale-basics (a recent sim), with comments for the latest available version.

  "devDependencies": {
    "grunt": "~0.4.1",//0.4.2
    "grunt-requirejs": "~0.4.0",//UP TO DATE
    "grunt-contrib-jshint": "~0.6.4", //0.8.0
    "uglify-js": "~2.4.0",//2.4.8
    "requirejs": "~2.1.8",//2.1.10
    "esprima": "~1.0.4",//UP TO DATE
    "escodegen": "~0.0.27"//1.0.1
  },

The only major version number change is in escodegen--it may have version incompatibilities.  I'm not familiar with how we are using escodegen, perhaps @jonathanolson should comment.

**Comment by pixelzoom** [comment]
I deleted esprima and escodegen from all package.json.  Closing.

**Comment by samreid** [comment]
oops wrong repo in the link above, should be https://github.com/phetsims/sherpa/issues/55
