### ISSUE TITLE
when is SHERPA required in config.js?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#553]
I see `SHERPA` in 27 config.js files:

```js
SHERPA: '../../sherpa',
```

But `SHERPA` is not in simula-rasa-config.js, so it's not added automatically by `grunt create-sim`.  

When is `SHERPA` needed in config.js?

**Comment by pixelzoom** [comment]
I'm asking because:

(a) it doesn't seem to make a difference in `requirejs` or built modes for some of the sims that I've been working on in the past few day (graphing-lines, graphing-slope-intercept, function-builder, function-basics, unit-rates,...), and

(b) I dimly recall some reason for adding it.

**Comment by pixelzoom** [comment]
Looks like I added `SHERPA` and `VIBE` at the same time in graphing-lines-config.js, see https://github.com/phetsims/graphing-lines/commit/8986e1db6d5734d110c6a1dfdf138eaf873a8906.   Is it perhaps a requirement for audio?...

**Comment by samreid** [comment]
I don't see any require statements with SHERPA in them, so I think SHERPA is not necessary in main.  Spot tests seem to agree:
![image](https://cloud.githubusercontent.com/assets/679486/23835216/01021812-0729-11e7-8b8e-6065be8aaad8.png)

I'll commit removals shortly.

**Comment by pixelzoom** [comment]
Did you spot test audio? Looks like all sims that include VIBE also include SHERPA.

**Comment by samreid** [comment]
> Did you spot test audio? Looks like all sims that include VIBE also include SHERPA.

Graphing lines had VIBE and SHERPA.  After removing SHERPA, audio is still working in Requirejs version.

**Comment by pixelzoom** [comment]
> After removing SHERPA, audio is still working in Requirejs version.

And built version?

**Comment by samreid** [comment]
Also is still woking properly in built graphing lines without SHERPA.

**Comment by pixelzoom** [comment]
Looks like you missed a couple: area-builder, function-basics

**Comment by pixelzoom** [comment]
I took care of function-basics, but don't have time to verify area-builder.

**Comment by jbphet** [comment]
Area Builder is loading fine, basic operations are working, and sound is being generated correctly.  Looks good to me.

**Comment by pixelzoom** [comment]
@jbphet SHERPA has not been removed from Area Builder yet.

**Comment by jbphet** [comment]
Okay, I've now removed SHERPA from config.js and done a basic regression test on both the requirejs and built versions, and found no issues.  The sounds are correctly generated within the game.

**Comment by samreid** [comment]
@pixelzoom can this issue be closed?

**Comment by pixelzoom** [comment]
Yep. Closing.
