### ISSUE TITLE
Missing require argument

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#554]
As seen in https://github.com/phetsims/forces-and-motion-basics/issues/222#issuecomment-288441200, several sims are missing the require parameter:

Other sims exhibit the missing `require`:

area-builder
energy-forms-and-changes
energy-skate-park-basics
fluid-pressure-and-flow

**Comment by samreid** [comment]
Fixed in the preceding commits.  Assigning @jbphet so he will be aware of the issue, and to take a look and make sure everything is resolved.

**Comment by jbphet** [comment]
Changes look fine to me.  @samreid - you said
> Assigning @jbphet so he will be aware of the issue, and to take a look and make sure everything is resolved.
I'm now aware of it, but not sure how to make sure everything is resolved other than just reviewing the code.  Let me know if there is more that I can help with, otherwise I think it's okay to close this.

**Comment by samreid** [comment]
Nothing else to do here, a lint rule would be too complicated.
