### ISSUE TITLE
Code Style: @return vs @returns

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#557]
In https://github.com/phetsims/dot/issues/66#issuecomment-292067847 @jonathanolson recommended to use `@returns` instead of `@return`.  I did so then went to see if this problem needed to be fixed elsewhere.  However, I noticed in the JSDoc specs we have been using: https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler it says to use `@return`. I also confirmed that the IDEA auto-jsdoc-generator creates `@return` instead of `@returns`.

Searching across our repos, I see inconsistent usage of the annotations.  For instance, in Function Builder there are 3 occurrences of `@return` and 87 occurrences of `@returns`.

Assigned to @jonathanolson and @pixelzoom for feedback.

**Comment by pixelzoom** [comment]
I have no strong opinion on whether PhET should use `@return` or `@returns`.  Since both convey the information effectively, and since we're not generating doc, I'm not entirely convinced that it matters.  Let me know which one you'd like me to use going forward.

**Comment by pixelzoom** [comment]
According to JSdoc 3 (http://usejsdoc.org), `@returns` is the official tag, and `@return` is a valid synonym.

**Comment by jonathanolson** [comment]
No strong preferences, but I somewhat prefer `@returns`, as it feels more natural to say what the function is returning. If there are hard-to-change IDEA templates, it may be preferable to use `@return`.

**Comment by pixelzoom** [comment]
When I add doc for an existing function in IntelliJ IDEA, it automatically uses `@returns` in the documentation that it generates.  I haven't investigated whether this is configurable in IDEA. So if we must standardize, +1 for `@returns`.

**Comment by samreid** [comment]
It looks like you can switch types with IDEA using the strategy here:
https://youtrack.jetbrains.com/issue/WEB-7516#comment=27-611256

**Comment by samreid** [comment]
I'm going to push changes from `@return` to `@returns`

**Comment by samreid** [comment]
I've switched occurrences of `@return` to `@returns`. @pixelzoom @jbphet @jonathanolson @zepumph @Denz1994 @mattpen please pull all to pick up these changes.

**Comment by Gerst20051** [comment]
@samreid is there a reason this was closed?

**Comment by samreid** [comment]
Good point, I can see numerous places where `@return` are appearing.  Thanks!  Also, maybe we should enforce this with a lint rule.

**Comment by zepumph** [comment]
I see 364 usages of the regex `\* @return[^s]\{` and wonder if we should just batch replace them. I wanted to double check first though.

**Comment by samreid** [comment]
> One problem with changing it everywhere is the parameters no longer align.

Can you clarify what you mean by parameters aligning?

**Comment by Gerst20051** [comment]
Sure @samreid Sublime JSDoc package `DocBlockr` will create the doc block with the sections vertically aligned.

```
/**
 * Helper function to generate an IAM policy.
 * @param  {string} principalId Name of caller.
 * @param  {string} effect      'Allow' or 'Deny'.
 * @param  {string} resource    Requested path.
 * @return {Object}             Generated IAM policy.
 */
```

By updating `@return` to `@returns` the alignment gets messed up. It isn't the worst thing in the world though.

```
/**
 * Helper function to generate an IAM policy.
 * @param  {string} principalId Name of caller.
 * @param  {string} effect      'Allow' or 'Deny'.
 * @param  {string} resource    Requested path.
 * @returns {Object}             Generated IAM policy.
 */
```

**Comment by samreid** [comment]
We are using `@returns` uniformly now, and have a lint rule to help keep us on track.  Closing.

**Comment by pixelzoom** [comment]
A note about configuring WebStorm to complete with `@returns` vs `@return`.   It looks like `@return` is the default, and there is no specific preference for selecting which to use.  But if you type "@ret" and select "@returns" as the completion, then WebStorm will remember that, and use it for completion of "/**" (method comments).

**Comment by pixelzoom** [comment]
I works for me in WebStorm 2024.3.2 GA, which was released on 1/17/2025.  Perhaps try updating?
