### ISSUE TITLE
Add a task/script that clones all git dependencies for a sim

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#56]
As mentioned in #52 it is nontrivial to check out a simulation and all of its dependencies.  Let's create a task/script that clones the dependencies as specified in the package.json file for a simulation.  If created as a grunt task, it will need to have the following 3 dependencies already checked out: the simulation, sherpa and chipper.

**Comment by pixelzoom** [comment]
This was pulled out of Gruntfile.js into cloneDependencies.js, and renamed 'clone-dependencies'.

There was some question about whether this task is now vestigial.  @samreid and @jonathanolson said they don't use it.  How about you @jbphet ?

**Comment by pixelzoom** [comment]
@jbphet Do you use `grunt clone-dependencies` ?

**Comment by pixelzoom** [comment]
@jbphet Do you use `grunt clone-dependencies` ?  If not, I'm going to delete it.

**Comment by pixelzoom** [comment]
Skype thread:
[5/19/15, 1:37:40 PM] Chris Malley: Do you use `grunt clone-dependencies` ?
[5/19/15, 4:37:06 PM] John Blanco: Nope. I use grunt checkout-shas, but not clone-dependencies.
