### ISSUE TITLE
deploy task doesn't handle remote directory properly

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#561]
I attempted to do "grunt deploy-dev" for function-basics 1.0.0-dev.1, without having created the function-basics/ remote directory on spot@dev/html/.   The grunt task appeared to complete without error, but nothing was deployed to spot.  Apparently the build process doesn't test whether the target directory exists, and then silently continues when the deploy fails. 

I think it's fine to require manual creation of the remote directory. But if it doesn't exist, the "grunt deploy-dev" should fail.

Assigning to @ariel-phet to assign and prioritize.

**Comment by pixelzoom** [comment]
There's a similar problem if you forget to change the version id and attempt to deploy the same version twice.  Instead of failing or replacing the remote directory, "grunt deploy-dev" nests a build/ directory inside the existing remote directory.

E.g.:

```
% cd function-basics
% grunt
% grunt deploy-dev
% ssh spot
% ls -1 dev/hmtl/function-basics/1.0.0-dev.1
dependencies.json
function-basics_en.html
function-basics_en-iframe.html
wrappers/
% exit
% grunt deploy-dev
% ssh spot
% ls -1 dev/hmtl/function-basics/1.0.0-dev.1
build/
dependencies.json
function-basics_en.html
function-basics_en-iframe.html
%
```

**Comment by ariel-phet** [comment]
Assigning to @mattpen - seems good to fix

**Comment by mattpen** [comment]
@pixelzoom - I've changed the deploy-dev task so that it creates the directory path if it does not exist.  As the directory now always exists, I had to make the second change as well such that the contents of build are copied to the remote directory, rather than a nested build directory.  

I did not implement a check to report on or block overwrites if they are happening.  Should I add that as well?  It seems like overwriting the contents should be the default, expected behavior to me.

**Comment by pixelzoom** [comment]
In my experience, overwriting an existing deploy is typically a mistake, caused by forgetting to update package.json.  So I think it should fail if the remote directory already exists.  If you want to replace an existing deploy, log in to spot and manually delete the remote directory.

**Comment by mattpen** [comment]
OK.  So now a call to `grunt deploy-dev` should first check if the directory exists.  If it does not, it creates the directory and copies the contents.  If the directory exists, it fails with a message like this:

> $ grunt deploy-dev
Running "deploy-dev" task
Fatal error: Directory spot.colorado.edu:/htdocs/physics/phet/dev/html/chains/1.0.0-dev.4 already exists.  If you intend to replace the content then remove the directory manually from spot.colorado.edu.

@pixelzoom - Does this sound ok to you?  I tested this on my machine using `chains` and it worked as expected, do we need to do any other testing?

**Comment by pixelzoom** [comment]
That behavior and the error message look great.  I didn't test, trust that you did.  So closing.

**Comment by pixelzoom** [comment]
Reopening.  'grunt deploy-dev' now prompts me for a password 4 times, once for each file transferred.  

I tried to enable password-less login by posting my ssh key in my home directory on spot:

> cat ~/.ssh/id_rsa.pub | ssh <user>@spot.colorado.edu 'cat >> .ssh/authorized_keys'

I verified that the files `spot@~/.ssh/authorized_keys` matches `local@~/.ssh/id_rsa.pub`.

And I'm still required to provide a password for ssh to spot, and for "grunt deploy-dev". 

In case ssh version matters...

[4/18/17, 9:58:22 AM] Chris Malley: On my local machine (Mac OS 10.11.6):
[4/18/17, 9:58:26 AM] Chris Malley: % ssh -V
OpenSSH_6.9p1, LibreSSL 2.1.8
[4/18/17, 9:58:33 AM] Chris Malley: On spot:
[4/18/17, 9:58:33 AM] Chris Malley: % ssh -V
Sun_SSH_1.1.8, SSH protocols 1.5/2.0, OpenSSL 0x1000115f
[4/18/17, 9:58:41 AM] Chris Malley: ... if that matters.

So... This is currently broken.   The workaround is to provide my password 4 times.

**Comment by mattpen** [comment]
`grunt deploy-dev` prompts for password four times for each command that needs to run on the dev server (spot).

1. Check if file exists
2. Create directory
3. Modify permissions on the directory
4. Copy the files

I could potentially combine the first three commands into one script, but it would still prompt for password twice.

**Comment by pixelzoom** [comment]
Thinking out loud... Perhaps `deploy-dev` should work like `deploy-rc`?  That is, handled by build-server?

**Comment by samreid** [comment]
> `grunt deploy-dev` prompts for password four times for each command 

The instructions in https://github.com/phetsims/phet-info/blob/master/deployment-info/sim_deployment.md#build-process-configuration worked great for me, we should try to get them working for you too.

I'm not opposed to getting the build server to build dev versions, though I'd recommend spending another 60+ minutes getting the ssh keys working first.

**Comment by pixelzoom** [comment]
The instructions in https://github.com/phetsims/phet-info/blob/master/deployment-info/sim_deployment.md#build-process-configuration (a) indicate that creating an ssh key is option, and (b) don't work for me despite repeated attempts to follow the instructions.

**Comment by pixelzoom** [comment]
On my 4th attempt to follow the instructions, I got ssh key to work.  I'll update the instructions.

**Comment by pixelzoom** [comment]
Instructions in https://github.com/phetsims/phet-info/blob/master/deployment-info/sim_deployment.md#build-process-configuration have been revised, see "Configure an RSA key (optional)" section.

I'm not opposed to making "Configure an RSA key" required.

**Comment by samreid** [comment]
+1 for making the RSA key required so we have a standardized process.

**Comment by samreid** [comment]
We decided to make RSA key required.   @pixelzoom is updating the docs.
