### ISSUE TITLE
wrappers are included for all deploys

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#562]
When I deploy a sim via "grunt deploy-dev" or "grunt deploy-rc", I'm seeing a `wrappers/` directory being deployed.  I have not tested "grunt deploy-production".  My sims are not instrumented for phet-io, and I have not specified brand=phet-io. This seems like a bug.

**Comment by pixelzoom** [comment]
I misspoke... Looks like the wrappers/ are deployed only for `deploy-dev` task, not `deploy-rc`.

**Comment by samreid** [comment]
Do you have a flag where it is remembering your brand?  Like in a .phet directory?

**Comment by pixelzoom** [comment]
`"brand": "phet"` in $HOME/.phet/build-local.json.

**Comment by zepumph** [comment]
I see this line in `deployDev.js`:

```js

  // If there is a protected directory and we are copying to spot, include the .htaccess file
  // This is for PhET-iO simulations, to protected the password protected wrappers, see
  // https://github.com/phetsims/phet-io/issues/641
  if ( grunt.file.isDir( ChipperConstants.BUILD_DIR ) && deployConfig.devDeployServer === 'spot.colorado.edu' ) {
    grunt.file.copy( '../phet-io/templates/spot/.htaccess', ChipperConstants.BUILD_DIR + '/wrappers/.htaccess' );
  }

```

Looks like it isn't checking for brand here, not sure about rc though.

**Comment by pixelzoom** [comment]
That sure looks like the problem.  And as I said above, _not_ a problem for `deploy-rc`.

**Comment by zepumph** [comment]
Oh sorry I missread.

**Comment by pixelzoom** [comment]
I misspoke in my report (first comment), then clarified in second comment.

**Comment by zepumph** [comment]
Ahh I see now. 

It looks like the deployDev task just takes in grunt. I thought that the brand was gathered from the buildConfig though. perhaps we need to pass that in to dev deploys.

**Comment by zepumph** [comment]
CM could you pull and see if it's fixed?

**Comment by pixelzoom** [comment]
👍 Closing.
