### ISSUE TITLE
check in chipper node modules

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#571]
See https://github.com/phetsims/phet-info/issues/44 and https://github.com/phetsims/chipper/issues/494

Checking in node_modules may simplify our process (at least for restoring working copies).

**Comment by samreid** [comment]
Chipper's node_modules is currently about 50MB and includes things such as this picture of a grumpy cat:

![image](https://cloud.githubusercontent.com/assets/679486/25537361/6c93316e-2bfb-11e7-81b8-d65bd372785f.png)

I'm basically wondering about this plan:

1. Delete sim node_modules--they can use chipper's one
2. Prune chipper's node_modules directory to eliminate waste and get lower than 50MB
3. check in chipper's node_modules directory where it is (don't move to sherpa) so that things will continue to work smoothly

Questions
1. does node_modules contain platform-specific binaries?  Comparing or testing across platforms would check this.
2. What would the procedure be for updating dependencies?  Will we still keep package.json checked in?
3. Should we investigate upgrading dependencies before committing?
4. Will this interfere with old versions?  Build tools will have to know not to `npm update` after this change or it would interfere (but we could perhaps delete package.json to solve this).

**Comment by samreid** [comment]
Developers kind of enjoy the ease of typing `grunt` in sim directories, and if that changes we would have to update perennial and maintenance processes.  Nobody really has time to investigate this at the moment.

**Comment by jonathanolson** [comment]
npm caused continuous testing failures by filling up the /tmp directory with files that aren't removed (https://github.com/phetsims/aqua/issues/20). The next time I run into another npm-related issue, I'll probably take a stab at this.

**Comment by pixelzoom** [comment]
10/30/17 dev meeting:
We will continue to rely on a healthy npm ecosystem, and will not check in dependencies.
