### ISSUE TITLE
Investigate https://prepack.io/

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#574]
https://prepack.io/ is a new project that evaluates expressions during the build process to eliminate the need to evaluate them during the runtime.  Will it work in the context of our project?  How much will it speed up startup time or runtime (if any)?

**Comment by samreid** [comment]
Here's a reference version of Forces and Motion: Basics: 
https://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/2.4.0-dev.1/forces-and-motion-basics_en.html

I isolated the main js of FAMB and it is 2.4MB.  I ran prepack on it and it was 3.1MB (though I noticed extra line breaks in this one, so it may be compressible).  The prepacked version is available here:
https://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/2.4.0-dev.2/forces-and-motion-basics_en.html

@phet-steele can you please characterize the startup and runtime performance on iPad2?  Note that the download time may be longer for dev.2--but that may be because it is not minified.

**Comment by phet-steele** [comment]
| **Tycho, iPad2 iOS 9.3.5** | dev.1 | dev.2 (prepacked) |
| --- | --- | --- |
| Startup (s) | 6.49 | I stopped waiting after 5 minutes |
| Homescreen idle (fps) | 60 | (see startup) |
| Net Force cart moving (fps) | 24 - 29 | (see startup) |
| Net Force red won (fps) | 14 - 16 | (see startup) |
| Acceleration with the works (fps) | 9 | (see startup) |
| Acceleration, dragging bucket only (fps) | 11 | (see startup) |

@samreid sorry I couldn't get numbers for dev.2, but if you could make it load faster I'd be happy to test.

**Comment by samreid** [comment]
Thanks @phet-steele, it seems prepack is not feasible for us at the moment, closing.
