### ISSUE TITLE
Speed up pull-all.sh

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#576]
Every day, many PhET developers use the pull-all.sh script one or more times.  

I tried running a 2nd pull with pull-all.sh using the timing command and I saw:

real	1m0.861s
user	0m9.081s
sys	0m6.828s

I also tried the multithreading strategy in this post: https://stackoverflow.com/questions/2425870/multithreading-in-bash

and saw
real	0m5.056s
user	0m13.579s
sys	0m12.041s

The messages are no longer sorted so it is harder to read if there is a problem.  But for the typical use case of needing to pull all repos, this may be more convenient.  I haven't tested on slower systems or systems with less cores--it may crash them with so many pending tasks.  Still, I think I'll commit this (separately and with a different prefix so autocomplete is preserved) and try it out for a while.

**Comment by samreid** [comment]
Implemented above and working nicely as far as I can tell so far.  I'll test it out over the week and bring it up for developer meeting in case others want to test it out.

**Comment by samreid** [comment]
One more caveat before I leave this issue, I haven't tested on Windows (or indeed any other machine than my primary development machine).

**Comment by jessegreenberg** [comment]
I just gave this a shot on my Windows 10 machine with Git Bash.  For a second run of pull-all.sh, I saw:

real    1m24.595s
user    0m0.196s
sys     0m1.150s

Running parallel-pull-all.sh I time:

 real    0m9.291s
user    0m0.271s
sys     0m0.980s

Works great on Windows 10 for me.

**Comment by samreid** [comment]
Thanks for testing this @jessegreenberg, it has been working nicely for me as well.

@Denz1994 also just tried it and it crashed his terminal 💥

**Comment by jonathanolson** [comment]
It should be possible to add something that reports on failures. For instance, in Yotta I kick off three concurrent processes, and handle sending failure emails customized to what failed:
```sh
./bin/1-google-analytics.sh &
PID_GOOGLE_ANALYTICS=$!

./bin/1-offline.sh &
PID_OFFLINE=$!

./bin/1-phet-cache.sh &
PID_PHET_CACHE=$!

wait ${PID_GOOGLE_ANALYTICS}
GOOGLE_ANALYTICS_EXIT=$?
wait ${PID_OFFLINE}
OFFLINE_EXIT=$?
wait ${PID_PHET_CACHE}
PHET_CACHE_EXIT=$?

${LOG_INFO_CMD} "[end] 1-"

if [ ${GOOGLE_ANALYTICS_EXIT} != 0 ]; then
  ${LOG_ERROR_CMD} "Aborted due to 1-google-analytics.sh failure"
  exit 1
fi

if [ ${OFFLINE_EXIT} != 0 ]; then
  ${LOG_ERROR_CMD} "Aborted due to 1-offline.sh failure"
  exit 1
fi

if [ ${PHET_CACHE_EXIT} != 0 ]; then
  ${LOG_ERROR_CMD} "Aborted due to 1-phet-cache.sh failure"
  exit 1
fi
```

**Comment by jonathanolson** [comment]
My timing for a normal pull-all.sh:
```
real    8m40.282s
user    0m0.393s
sys     0m0.997s
```
and the error for parallel-pull-all.sh:
```
$ chipper/bin/parallel-pull-all.sh
chipper/bin/parallel-pull-all.sh: fork: Resource temporarily unavailable
```

**Comment by veillette** [comment]
There exists a package called git-pull-all on npm that allows concurrent pulling of many repos. Berea is using this to pull all repos.

**Comment by samreid** [comment]
@veillette said a pull takes around 30 seconds with that tool.

**Comment by Denz1994** [comment]
Using git-pull-all seems to work on my machine. Slight lag on the terminal, but no crashes. Thanks for the suggestion.

**Comment by veillette** [comment]
to install git-pull-all, you need to run in bash

```
npm install -g git-pull-all
```

Once you have it installed, run it from phetsims
```
cd phetsims
git-pull-all
```

**Comment by jbphet** [comment]
I just installed and tried out `git-pull-all`, and it worked great for me.  Nice find @veillette!

**Comment by samreid** [comment]
Let's leave this open until @pixelzoom has a chance to take a look around.

**Comment by pixelzoom** [comment]
Two things:

(1) I don't want to have to `cd` to the proper directory to run `git-pull-all`.
(2) If `git-pull-all` fails, notify the user to run `npm install -g git-pull-all`

Both of these could be accomplished by modifying pull-all.sh to call `git-pull-all`, and (if not found) print "git-pull-all not found. Install by running: npm install -g git-pull-all".

**Comment by pixelzoom** [comment]
I rewrote pull-all.sh to use git-pull-all, providing the features noted in https://github.com/phetsims/chipper/issues/576#issuecomment-306259433.

@samreid please review.

**Comment by pixelzoom** [comment]
@jonathanolson please have a look too, since you were the author of pull-all.sh.  Does this provide the same functionality as 'git pull --rebase' ?

**Comment by samreid** [comment]
@pixelzoom have you tried using parallel-pull-all.sh?

**Comment by samreid** [comment]
> I rewrote pull-all.sh to use git-pull-all, providing the features noted in #576 (comment).

I'm not too excited about requiring a 3rd party node module to be installed in order to run pull-all.sh.  Will we need to update any of our documentation regarding pull-all.sh?  I'm planning to only use parallel-pull-all.sh for now.

**Comment by pixelzoom** [comment]
Hmmm.... I thought there was consensus on git-pull-all, so went ahead and made the change.  To be honest, I had no problem with the way things were.    So feel free to revert, and handle this any way that you want.  My only 2 requests are documented in https://github.com/phetsims/chipper/issues/576#issuecomment-306259433.

**Comment by jonathanolson** [comment]
git-pull-all looks like it just runs "git pull", so it will probably trigger "merge" mode if there are upstream changes on something.

**Comment by samreid** [comment]
I'm not planning to work on this further and not sure whether it is worth it to have pull-all.sh use this or not.  I'll open that for decision during next developer meeting.

**Comment by pixelzoom** [comment]
I've reverted pull-all.sh.  Apparently there is no consensus on what (if anything) needs to change.

**Comment by ariel-phet** [comment]
Some people using parallel some people not. @pixelzoom recommends adding option instead of mostly duplicated code. @samreid will add option.

**Comment by pixelzoom** [comment]
Note to self:  Add parallel option to pull-all.sh (use `getopts`), delete parallel-pull-all.sh.

**Comment by pixelzoom** [comment]
I tried adding `pull-all.sh -p` for parallel, then discovered that running so many background processes hangs my Mac.  Same behavior for `parallel-pull-all.sh`. 

So I'm punting on this. Here's where I was at with the script.  @samreid please feel free to pursue.

```
#!/bin/bash
#====================================================================================================
#
# Does a 'git pull --rebase' on every active repo.
# Use -p option to handle each repository in parallel.
#
# Author: Jonathan Olson
#
#====================================================================================================

PULL_COMMAND="git pull --rebase"
PARALLEL="false"

# cd to the directory where your git repositories live
CHIPPER_BIN=`dirname "${BASH_SOURCE[0]}"`
WORKING_DIR=${CHIPPER_BIN}/../..
cd ${WORKING_DIR}

# parse command line options
while getopts ":p" opt; do
  case $opt in
    p)
      PARALLEL="true"
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit
      ;;
  esac
done

# pull each repository
for repo in `cat chipper/data/active-repos | xargs | tr -d '\r'`
do
  if [ -d "$repo" ]; then
    cd $repo
    if [ ${PARALLEL} == "true" ]; then
      # run in the background
      ${PULL_COMMAND} &
    else
      ${PULL_COMMAND}
    fi
    cd ..
  fi
done
```

**Comment by jessegreenberg** [comment]
I tested the above, its working great for me so I committed it.  I also tested pull-all.sh without the parallel option. Thanks @pixelzoom.  @samreid also had a ```wait``` command to let it wait for the background processes to finish, I added that back.  @samreid do you want to review or make sure this works for you?  I am going to delete parallel-pull-all.sh.

**Comment by jessegreenberg** [comment]
Actually not going to delete ```parallel-pull-all.sh``` yet until those that want the parallel option are comfortable with https://github.com/phetsims/chipper/commit/80ae1f148ad0339588633f85033d1d6a4bb4000d.

**Comment by samreid** [comment]
From https://github.com/phetsims/chipper/issues/576#issuecomment-307181789

> @pixelzoom recommends adding option instead of mostly duplicated code.

The commits above take pull-all.sh from 23 lines to 51 lines (an addition of 28 lines).  parallel-pull-all.sh weighs in at 28 lines.  Instead of two simple scripts we have one complicated one?  Is simple duplicated code preferable to more complex options parsing code and logic?

Additionally, I prefer to type `para[tab][enter]` to pull everything rather than `pul[tab]-p[enter]`.  If we keep the option in pull-all.sh, how about keeping `parallel-pull-all.sh` as an alias for `pull-all.sh -p`?  I run this many times a day so would prefer to use the more convenient way.

Wouldn't the best way to factor out duplicated logic be for both pull-all.sh and parallel-pull-all.sh to use for-each.sh?

**Comment by pixelzoom** [comment]
> Additionally, I prefer to type `para[tab][enter]` to pull everything rather than `pul[tab]-p[enter]`

Create a bash alias if this really bothers you.

**Comment by samreid** [comment]
Thanks @pixelzoom!  I created a new bash alias for `pull-all.sh -p` and it is working great.  The remaining questions for this issue are:

* Instead of two simple scripts we have one complicated one?

* Is simple duplicated code preferable to more complex options parsing code and logic?

* Wouldn't the best way to factor out duplicated logic be for both pull-all.sh and parallel-pull-all.sh to use for-each.sh?

**Comment by pixelzoom** [comment]
> Instead of two simple scripts we have one complicated one?

51 lines is complicated?  If you'd rather maintain 2 almost-identical scripts, go for it.

> Is simple duplicated code preferable to more complex options parsing code and logic?

Again... complex?  This is bash 101.

> Wouldn't the best way to factor out duplicated logic be for both pull-all.sh and parallel-pull-all.sh to use for-each.sh?

If you'd like to rewrite in terms of forEach.sh, go for it.

**Comment by samreid** [comment]
My alias for `pull-all.sh -p` is working nicely, so I'm fine for parallel-pull-all.sh to be deleted.

> This is bash 101.

I'm still learning bash and not sure what's common knowledge, thanks for helping me learn.

> If you'd like to rewrite in terms of forEach.sh, go for it.

Perhaps some day, but not for this issue.

**Comment by samreid** [comment]
`pull-all.sh -p` is working nicely, and can be set up with an alias.  The separate parallel file was deleted in https://github.com/phetsims/perennial/issues/61, closing.
