### ISSUE TITLE
Add a process for dev deploys

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#577]
Previously, I used to try to batch many changes into a single dev deploys.  That led to the question of when to make the next dev deployment.  For CCK, I'm trying a new strategy of deploying a new dev version for each issues that needs testing from the design or QA team.  This is working well from my perspective, but would be nicer if chipper supported this step a bit better.  I'd like to create a script that creates and publishes a dev version automatically.

**Comment by samreid** [comment]
I committed a rough draft above and will try it out for next deploys.  If we decide to keep it, we can give it a more thorough review process.

**Comment by samreid** [comment]
It's been working nicely and I added another improvement, I'll share this with the team in case it can help others.

**Comment by samreid** [comment]
I informed the team about this task, it seems ready to use.  Should it be reviewed?

**Comment by samreid** [comment]
@ariel-phet suggested that @pixelzoom could take a look when the time is right.

**Comment by pixelzoom** [comment]
The current process was:

```
% grunt
// test what you built
% grunt deploy-dev
```

Questions about your new process:

(1) How is it different?  
(2) Is the build tested before it's deployed?
(3) Why do you feel the need to create a dev version for every issue addressed?

**Comment by samreid** [comment]
> (1) How is it different?  

As documented in https://github.com/phetsims/phet-info/blob/master/deployment-info/sim_deployment.md

If you are working in master, would like to release a dev version by updating the dev number, and your working copy is clean then you can use grunt next-dev. This will run a trial build and if there are any lint or build errors the process will halt. If there are no lint or build errors, package.json will be updated with the next version number and the simulation will be built and deployed.

> (2) Is the build tested before it's deployed?

Lint and build errors are checked before the version number is incremented.  When using `grunt next-dev`, there is no way for the developer to test the built version in the browser before it is deployed.

> (3) Why do you feel the need to create a dev version for every issue addressed?

As I mentioned in the issue description: "Previously, I used to try to batch many changes into a single dev deploys. That led to the question of when to make the next dev deployment. For CCK, I'm trying a new strategy of deploying a new dev version for each issues that needs testing from the design or QA team. This is working well from my perspective [...]"

It works well for me because I am able to get feedback on issues sooner (instead of waiting for batch deploys)--I can keep pushing on issues until they are done rather than getting into a "waiting until next dev version is deployed" state.

**Comment by pixelzoom** [comment]
> As I mentioned in the issue description ...

Sorry.  But I'm getting a bit weary of having to read through every comment in issues to figure out (a) what I'm supposed to review, (b) what information in the comments is relevant, and (c) what information is missing.   But thanks for the clarification.

That said... I have no use for `grunt next-dev`, and I don't think it benefits PhET to have yet-another way to do thing (with code to maintain).  But that's just my opinion.  So if you want to proceed with this, it would be better if someone else reviews it.  

Observations from a quick skim of bumpVersion.js:
• doesn't look very robust (no checking of `lastNumber`)
• `console.log` should be `grunt.log.writeln` in bumpVersion.js
• duplicated code in parsing version (`version.lastIndexOf( '.' ) + 1`)
• incorrect copyright header

**Comment by samreid** [comment]
I fixed a few of the problem above, not sure how to check lastNumber.  This task has proved very useful for my workflow and I suspect it will be valuable to others as well.  @ariel-phet can you please assign a developer for further review?

**Comment by samreid** [comment]
@ariel-phet and I discussed this and thought it would be good to discuss at Developer Meeting.  It would be good to discuss pros and cons of `grunt next-dev`.  Should `next-dev` be the only way to create dev versions?  Will this automated process make it easier for developers to create dev versions?  Should we eliminate the "dev" instructions from sim_deployment.md and flesh out the `grunt next-dev` section?  Why did @pixelzoom say:

>  I have no use for `grunt next-dev`

If you want to test a built version using `grunt next-dev` you could do:
1. `grunt`
2. test the built version
3. `grunt next-dev`

compare this to the prior process
1. `grunt`
2. test the built version
3. manually edit package.json
4. commit package.json with a manually written commit message
5. push changes to package.json
6. `grunt`
7. `grunt deploy-dev`

The grunt `next-dev` command standardizes and automates steps 3,4,5,6,7 into a single command and relieves new developers from having to consult the many steps in sim_deployment.md.  It doubles the build time since it does a pre-change grunt, but this hasn't bothered me as much as I thought it would.

**Comment by jonathanolson** [comment]
So what would the procedure be for deploying a dev version off of a feature branch?

**Comment by samreid** [comment]
> So what would the procedure be for deploying a dev version off of a feature branch?

`grunt next-dev` uses whatever branches are checked out, whether master or feature branches.  So I think it would work with the normal procedure:

Step 1: run `grunt next-dev`
Step 2: there is no step 2

**Comment by samreid** [comment]
My main concern about the widespread use of this task is: if someone ran it right after a production deploy then it would do the wrong thing.  (e.g. taking 1.2.0 to 1.2.1) . Perhaps we should at least add a check that the version contains "-dev.".

**Comment by jonathanolson** [comment]
> grunt next-dev uses whatever branches are checked out, whether master or feature branches.

Does this update the version in package.json on master AND all feature branches? Would I need to cherry-pick commits to other branches?

**Comment by samreid** [comment]
This task only updates the version in the current branch.  It's not clear to me what you mean by feature branches.  When doing dev deploys are we supposed to increment the dev version number across multiple branches?  If so, why?

**Comment by jonathanolson** [comment]
Say I have a sim-repo branch for an alternative version of something that is potentially likely to be ditched. I want to deploy a dev version so people can play/test with it.

How do I do that and then safely deploy dev versions from master later? (Usually I would bump master and the branch's package.json versions so I don't overwrite things).

**Comment by samreid** [comment]
Process for doing a feature branch dev deploy **without** `grunt next-dev` then updating the master version:

1. manually edit package.json
2. commit package.json with a manually written commit message
3. push changes to package.json
4. grunt
5. grunt deploy-dev
6. git checkout master
7. git cherry-pick VERSION_SHA or manually commit & push version change

Process **with** `grunt next-dev`

1. grunt next-dev
2. git checkout master
3. git cherry-pick VERSION_SHA or manually commit & push version change

**Comment by jonathanolson** [comment]
Sounds to me like `grunt next-dev` would be helpful. Presumably `grunt next-rc` would also be helpful?

**Comment by samreid** [comment]
@jbphet recommends to rename it to `grunt deploy-next-dev` so it matches the other `deploy` prefixes.

**Comment by samreid** [comment]
Also a reminder to check that "-dev." is included in the version before proceeding.

**Comment by samreid** [comment]
I made the recommended changes and tested them, closing.
