### ISSUE TITLE
Speed up pull-all.sh?

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#58]
On my development machine, chipper/bin/pull-all.sh takes 2 minutes and IDEA pull all takes 38 seconds.  Could it work any faster if it was parallelized?  Would it be safe to run in parallel?

**Comment by pixelzoom** [comment]
`grunt pull-all` ceased to exist awhile ago. `pull-all.sh` took its place.  So I've re-titled this issue.

If you really wanted to parallelize the `git pull` commands in `pull-all.sh`, you could do so by forking (i.e., backgrounding) them.

**Comment by samreid** [comment]
I haven't had any problems with pull-all.sh lately, can I close this issue?

**Comment by jonathanolson** [comment]
pull-all.sh is fast enough on OS X/Linux for me where NOT being parallel is an advantage (for easy debugging if one pull goes wrong).

Pulling with Intellij/command line on Windows is much more painful, and I don't think it's going to help much.

**Comment by pixelzoom** [comment]
Performance of pull-all.sh has never been a problem for me either.  Closing.
