### ISSUE TITLE
problems with phetLibs

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#580]
This is a general issue, moved here from https://github.com/phetsims/function-builder/issues/112.  In that issue, @samreid observed that a sim will build and run if optional repositories are missing from "phetLibs" in package.json.   

I investigated, and discovered that `buildConfig.phetLibs` is essential to `grunt lint`, `grunt public-README`, generating a correct dependencies.json, and possibly other things.  But there is currently nothing that verifies that `buildConfig.phetLibs` matches {{REPO}}-config.js. And because there is no verification, it's possible to proceed with an incorrect package.json. In the case of README.md and dependencies.json, this causes serious problems.

Possible fixes:

(1) Verify that buildConfig.phetLibs matches {{REPO}}-config.js

(2) Replace "phetLibs" with repositories obtained from {{REPO}}-config.js

I do not intend to pursue this further.  Labeling for developer meeting to decide how to proceed.

**Comment by jonathanolson** [comment]
What about:

(3) `grunt generate-config` creates the config file based on package.json, and we have some grunt command that runs both THAT and `grunt generate-development-html` (which also has to change when other dependencies change).

**Comment by samreid** [comment]
Consensus: we like the recommendation from @jonathanolson and think it could take some 4 or so hours to implement.

**Comment by jonathanolson** [comment]
generate-config would need to look at package.json's requirejsNamespace values for the prefixes.

**Comment by samreid** [comment]
@ariel-phet says it hasn't caused a problem yet, so no need to implement it right away.  Perhaps after @jonathanolson time is freed up more after Pendulum Lab.

**Comment by ariel-phet** [comment]
@jonathanolson time is now a bit more freed up, assigning to him as some preemptive chipper 2.0 work.

**Comment by samreid** [comment]
After adding this new task, @jonathanolson will run this on all sims to make sure they are in-sync.  We should also consider if/how/when to automatically run this as part of the build/deploy process (so developers don't need to remember to do it after changing package.json).

**Comment by jonathanolson** [comment]
Presumably this will also require some small modifications to the "create a new sim from simula-rasa" process.

**Comment by jonathanolson** [comment]
Forgot to tag https://github.com/phetsims/chipper/commit/5db6514c2a651b2e636e9f4580d894d5c260cc29 for the create-sim changes.

**Comment by jonathanolson** [comment]
Updated the code review checklist to instead check the generated file (instead of manually verifying the config file).

I also fixed all cases where things were missing in package.json.

Closing.
