### ISSUE TITLE
'grunt deploy-rc' doesn't check whether version already exists

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#581]
'grunt deploy-rc' doesn't check whether version already exists.  And if the version does already exist (which is will if you forget to manually update package.json), then it will quite happily overwrite the existing version.  Which I just did with function-builder-basics 1.0.2.

**Comment by pixelzoom** [comment]
Btw...  'grunt deploy-dev' checks to see whether the version already exists. Why doesn't 'grunt deploy-rc' do the same?

**Comment by jonathanolson** [comment]
Would this check on the client-side or build-server side?

**Comment by mattpen** [comment]
Client side should check for existing RC and production deploys.  I'll implement this.

**Comment by zepumph** [comment]
This may be done for us because things will be automated, but we should still have this check.

**Comment by jessegreenberg** [comment]
@jessegreenberg and @zepumph will give this a shot!

**Comment by mattpen** [comment]
@jessegreenberg and @zepumph here is the current check in deploy-dev: https://github.com/phetsims/chipper/commit/383755b3d12d643de3ac4f378e4c40f4157119aa

**Comment by jonathanolson** [comment]
This is handled on the perennial-side deployment, tagging for testing.

**Comment by pixelzoom** [comment]
Following the chipper 2.0 merge, I suspect that this can be closed?

**Comment by jonathanolson** [comment]
Correct, closing. Thanks!
