### ISSUE TITLE
Add a check to make sure brands can't cross deploy to production

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#582]
from https://github.com/phetsims/balloons-and-static-electricity/issues/272

@jessegreenberg filled me in on what happened in the above issue, and it seems like this has happened before, and for the most part may not cause much damage. What happens is from a phetio branch, you accidentally leave off the '--brand=phet-io' flag to a deploy, worst case a deploy-production. Although there are edge cases for which this could be quite dangerous. You could probably overwrite a 'latest' version of a sim on the phet website with a sim who's shas are set up for phet-io, and whose accessibility functionality is completely unknown. 

I know that there is a complete build process redesign/refactor on the docket in #567, but that is still a ways off. I think that it would be worth it to add a check the build process that could look at the name of the branch (i.e. 1.3-phetio or 1.3) and check the brand flag in grunt, and make sure that both or none are phetio. 

Marking for dev meeting because it is tomorrow, and may be simple enough to discuss if it is worth taking this temporary step, or if we just need a PSA to be careful about how we deploy production.

**Comment by pixelzoom** [comment]
Is this as simple as verifying that `brand=phet` when running the `deploy-production` task?

**Comment by zepumph** [comment]
This could be similar to the issue #581, also marked for dev meeting today.

You can still deploy-production in phet-io mode. I think you would want to run this command:
`git rev-parse --abbrev-ref HEAD`

That spits out the string of the branch name, and make sure that it ends in '-phetio' if and only if `buildConfig.brand===phet-io` 

This is still a very simple test.

**Comment by zepumph** [comment]
From dev meeting. I will do this, and @mattpen can take a look to make sure all is well.

**Comment by zepumph** [comment]
I implemented this with a bitwise XOR operator in the conditional. @jonathanolson would you mind looking over this commit before closing. Or assign to another to check my work. Thanks!

**Comment by zepumph** [comment]
This will be done automatically in chipper:2.0

**Comment by jonathanolson** [comment]
Is this where you build a 'phet' brand, but deploy as 'phet-io' (or vice versa?). If so, it's handled in the 2.0 branch already, and this can be closed.
