### ISSUE TITLE
batch maintenance process ignores release branch naming conventions

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#588]
As noted in https://github.com/phetsims/chipper/issues/587, if there is a phet and phet-io release branch with the same version number (e.g. 1.1 and 1.1-phetio) then the shas for those branches must be kept in sync.  The batch maintenance process currently ignores this requirement, and causes such related branches to become out of sync.

Assigning to @ariel-phet to prioritize and assign.

**Comment by ariel-phet** [comment]
Marking for dev meeting so I understand how much work is involved, but priority seems reasonably high since we regularly perform maintenance releases

**Comment by jonathanolson** [comment]
If the automated process needs to handle phet-io sims, then phet-io sims should be consistent about branch practices.

**Comment by pixelzoom** [comment]
6/29/17 dev meeting:

• Automated process on patches phet versions.
• Manual patching on phet-io versions is required.
• We'll continue with this process for now.
• @jonathanolson will push back on patches to limit cost.
