### ISSUE TITLE
update data/README.md

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#589]
chipper/data/README.md has become out of sync.  @zepumph and @samreid, please document the files that you've added.

**Comment by samreid** [comment]
@zepumph can you please investigate?

**Comment by pixelzoom** [comment]
Missing descriptions for:

duplicates.txt
test-phetio
wrappers

I can sort of guess what these are for, but I'm not entirely sure.

**Comment by samreid** [comment]
Also, it would be nice to keep duplicates.txt elsewhere so it can easily be excluded.

**Comment by zepumph** [comment]
>Also, it would be nice to keep duplicates.txt elsewhere so it can easily be excluded.

I'm not sure what `duplicates.txt` is, it isn't in the .gitignore. @samreid can you explain what you mean, and the steps I should take to handle `duplicates.txt`.

**Comment by samreid** [comment]
I took care of duplicates.txt in the above commit.  Can you help document test-phetio and wrappers?

**Comment by zepumph** [comment]
Indeed.

**Comment by zepumph** [comment]
The name `test-phetio` doesn't really make sense. For one it should be `phet-io`, but also it is used for more than testing. After discussion with @samreid, I will rename this the `phet-io` because it really is a list of our phet-io sims. I will update the readme here, and I will change the the "how-to-instrument" docs to add a sim to this list early in the process. This this is used by phetmarks to show links to wrappers for a sim, and would be good to have that during instrumentation.

**Comment by zepumph** [comment]
I did the following changes:

1. `test-phetio` renamed to `phet-io`
2. `README` renamed to `README.md`
3. Updated `README.md
4. Update how to instrument docs so that you can use phetmarks to run wrappers much earlier in the process. 

If anyone else has more, please comment and/or reopen. Closing

**Comment by samreid** [comment]
Reopening in case @pixelzoom wants to review the changes here.

**Comment by pixelzoom** [comment]
Fixed a couple of typos, but otherwise looks great. Thanks for doing this @zepumph. Closing.

**Comment by jonathanolson** [comment]
In the future, if breaking changes are made to aqua's continuous testing, I should be notified so I can pull on bayes and restart the server.

**Comment by zepumph** [comment]
That didn't even cross my mind. Sorry about that. I will be more careful in the future.

**Comment by pixelzoom** [comment]
@jonathanolson said:
> ...  if breaking changes are made ...

I have no idea what you're talking about. Please identify the breaking change so that people can avoid in the future.

**Comment by jonathanolson** [comment]
> That didn't even cross my mind. Sorry about that. I will be more careful in the future.

No worries!

> I have no idea what you're talking about. Please identify the breaking change so that people can avoid in the future.

Automated testing currently relies on the chipper/data/* files to determine what needs to be tested. It runs phetio-specific tests, so it needs to determine a list of phetio-enabled sims, and used test-phetio to determine this. https://github.com/phetsims/aqua/commit/5b6b6feda278add452b0b784005a9766d93763a3 was made, and changes don't instantly get applied to the running continuous testing server.

**Comment by pixelzoom** [comment]
Got it, thanks for clarifying.
