### ISSUE TITLE
'grunt checkout-shas --tomaster=true' moves brand to 'master'

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#59]
To publish a sim, you typically do 'grunt checkout-shas', which sets your working copy to the shas indicated in dependencies.json.  After publication, you set your working copy back to master by doing 'grunt checkout-shas --tomaster=true'. 

Since we've added the 'brand' repo, there's a fly in the ointment. We generally want to be using the 'phet' branch of brand. But the above process sets it to master. So you'll need to remember to switch brand to the 'phet' branch. This is something I will surely forget to do at some critical point, so it would be nice if this were addressed in the build process.

**Comment by pixelzoom** [comment]
@samreid Methinks that this is no longer an issue, since we are using a private brand repo, and 3rd parties are using a public brand repo.  Is that correct?

**Comment by samreid** [comment]
Well, brand also has a new 'adapted-from-phet' branch, I think we have that problem again.

**Comment by pixelzoom** [comment]
Why is adapted-from-phet in brand? I thought it was a private repo. Is the plan to make it visible to some people?

**Comment by samreid** [comment]
All brand repos are public.  We are making "adapted from PhET" available to groups that are making minimal modifications to PhET sims.  See https://github.com/phetsims/brand/issues/1

**Comment by pixelzoom** [comment]
I thought the point of having a separate GitHub account and repo (phetbrand/brand) was to keep PhET logos, etc. out of phetsims/brand.  But now I see PhET logos in the 'adapted-from-phet' branch of phetsims/brand.  If you're going to do that, then why not just move phetbrand/brand to a 'phet' branch of phetsims/brand?

**Comment by samreid** [comment]
> But now I see PhET logos in the 'adapted-from-phet' branch of phetsims/brand. If you're going to do that, then why not just move phetbrand/brand to a 'phet' branch of phetsims/brand?

Based on discussion with @kathy-phet & @ariel-phet the goal was to have successively higher hurdles from "unbranded" to "adapted" to "full PhET logos & branding".  I do not know whether this goal has been met.  Let's discuss this strategy at the next developer meeting (I've added it to the agenda).

**Comment by samreid** [comment]
This can be closed after https://github.com/phetsims/brand/issues/11 is completed.

**Comment by samreid** [comment]
I'm unassigning this, and hoping to get to https://github.com/phetsims/brand/issues/11 after Bending Light review.

**Comment by pixelzoom** [comment]
Brands used to be in specific branches. But we change that, in all brands are now in subdirectories of master. So this is no longer an issue.   Closing.
