### ISSUE TITLE
missing version id in third-party-licenses.md

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#593]
Looking at [third-party-licenses.md](https://github.com/phetsims/sherpa/blob/master/third-party-licenses.md), I see that recently published sims don't have a version id next to them.  Is this a new bug in (perhaps) reportThirdParty.js?

E.g.:

```
‪Least-Squares Regression‬ 1.1.6
‪Make a Ten‬
‪Molarity‬
‪Molecule Polarity‬
‪Molecule Shapes‬ 1.1.10
‪Molecule Shapes: Basics‬ 1.1.8
‪Molecules and Light‬ 1.1.15
```

**Comment by pixelzoom** [comment]
Assigning to @ariel-phet to prioritize and assign.

**Comment by ariel-phet** [comment]
@zepumph can you investigate? Putting at medium priority since an investigation should be fairly quick (if you are spending more than an hour or so, lets discuss).

**Comment by pixelzoom** [comment]
To be clear... The list of simulations following the line "This report is for the following simulations" should all have a version id after them, where that version id corresponds to the published version.

**Comment by pixelzoom** [comment]
In reportThirdParty.js, line 364, fileList is the bullet list of sims and their version ids:

```js
'This report is for the following simulations: \n\n* ' + fileList + '\n\nTo see the third party resources used in a particular published ' +
```

**Comment by pixelzoom** [comment]
Looks like `fileList` is assembled by pull titles out of the html files.  Awhile back, there was a decision to remove version ids from the title shown by the browser.  Unconfirmed, but I'll betcha that's when the version id was lost.

**Comment by pixelzoom** [comment]
Confirmed that removing the version id from the document title is the problem.  reportThirdParty.js gets extracts the title from the document:

```js
    var parseTitle = function( html ) {
      var startKey = '<title>';
      var endKey = '</title>';

      var startIndex = html.indexOf( startKey );
      var endIndex = html.indexOf( endKey );

      return html.substring( startIndex + startKey.length, endIndex ).trim();
    };
```

In Molecule Polarity 1.0.0, the document title is:

```<title>&#8234;Molecule Polarity&#8236;</title>```

In a sim that hasn't been published for awhile, the document title is:

```<title>&#8234;Acid-Base Solutions&#8236; 1.2.9</title>```

**Comment by pixelzoom** [comment]
@ariel-phet So, yes, investigation was quick and straightforward.  Unfortunately there is no similar solution.   Labeling for discussion at developer meeting.

**Comment by ariel-phet** [comment]
@mattpen might be good for you to review this issue before dev meeting as I am pretty confident the website database has an easy way to get version ids (since I am pretty sure we use that for app updates and such).

**Comment by pixelzoom** [comment]
Linking to #594. If we decide to handle third-party report on the server, perhaps the version id can be obtained from the website database.

**Comment by mattpen** [comment]
Is the version id necessary for this report?  Can it be omitted? 

If it is necessary we can obtain it by making a call to the Metadata API.  This would not necessitate moving the script to the server (but would still work if it is moved).

**Comment by pixelzoom** [comment]
@mattpen asked:
> Is the version id necessary for this report? Can it be omitted?

You'll have to ask @kathy-phet, she requested this report. As I recall, she wanted the report to pertain to what was currently published on the PhET website.   You I image that she will want the list of sims _and_ their version id.

**Comment by mattpen** [comment]
I'll bring this up with Kathy at the next status meeting.  We need to know whether the version identifier is required and what the priority is.

**Comment by mattpen** [comment]
@kathy-phet said that the version can be optional, it is fine to leave it as is.
