### ISSUE TITLE
handle third-party credits and report on server

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#594]
Each sim webpage has a "Third Party" section in its Credits (stored in the website database).  And sherpa/third-party-report.md (in master) provides a complete report for all published sims.  This is currently handled by 'grunt report-third-party'.  

There are multiple problems with doing this as a client-side grunt task:

1. It's yet-another step in a long check list.
2. Developer must remember to do it (which historically hasn't happened).
3. html files for all published sims must be downloaded to the client.
4. third-party-report.md can't be checked in until sherpa is on master in working copy
5. something invariably goes wrong and the Credits don't look correct on the sim page

Since the goals is to have this information currently for what's on the server, why isn't this task run on the server?  Perhaps build-server should be modified to update the website database, generate third-party-report.md, and check third-party-report.md into master.

**Comment by pixelzoom** [comment]
Assigning to @ariel-phet to prioritize and assign.

**Comment by pixelzoom** [comment]
To add motivation for addressing this....

I just published Molecule Polarity 1.0.0, a port from Java.  I followed the instructions and ran 'grunt report-third-party'.   And it failed to update the website database.   For a Java sim,  'grunt report-third-party' must be run _after_ the HMTL5 version is made visible, or a silent failure occurs on the website side.   So now I'm going to update the "sim deploy" instructions for the Nth time, and make them even more complicated.

**Comment by pixelzoom** [comment]
New and improved checklist item:

> Update the 3rd party credits shown on the sim's web page by running `grunt report-third-party`. Then manually commit and push `sherpa/third-party-licenses.md`. NOTE! For the first publication of an HTML5 sim that was ported from Java, you must do this _after_ the HTML5 version has been made visible on the website. Failure to do so will result in a silent failure on the server, and you won't see any "Third Party" Credits on the HTML5 sim's web page.

**Comment by pixelzoom** [comment]
Linking to https://github.com/phetsims/chipper/issues/593.  If we decide to handle third-party report on the server, perhaps the version id can be obtained from the website database.

**Comment by ariel-phet** [comment]
@mattpen plan on looking into this @pixelzoom returns from vacation (after Aug 15)

**Comment by mattpen** [comment]
I'll take a look at this when @pixelzoom returns from vacation.

**Comment by mattpen** [comment]
We could also investigate migrating this to getThirdPartyLib.js.

**Comment by samreid** [comment]
Marking for potential work in https://github.com/phetsims/chipper/issues/596

**Comment by pixelzoom** [comment]
Perhaps this would work? In build-server.js, modify function afterDeploy to (1) run “grunt report-third-party”, then (2) commit and push sherpa/third-party-report.md.

**Comment by zepumph** [comment]
The plan is to complete this as part of our automating checklist steps.

**Comment by mattpen** [comment]
@jonathanolson has implemented this as a client-side grunt task and automated steps 1,2 and 4 from above.   The only problem remaining is:

> html files for all published sims must be downloaded to the client.

@jonathanolson and I propose that we defer migrating this to perennial because this isn't a critical problem.

**Comment by zepumph** [comment]
>@jonathanolson and I propose that we defer migrating this to perennial because this isn't a critical problem.

@mattpen any objections to moving this to perennial now as part of https://github.com/phetsims/perennial/issues/141?

**Comment by zepumph** [comment]
For now I just left it. It seemed to be a bit easier this way.

**Comment by zepumph** [comment]
@Matthew-phet and @jonathanolson, over in https://github.com/phetsims/perennial/issues/141 I made a daily script that reruns the third party credit generations. I also then removed this step from production deploys. Back over to you two for whatever is left for this.

**Comment by jonathanolson** [comment]
@mattpen I don't see anything else to do here?

**Comment by mattpen** [comment]
Agreed, I think this can be closed.
