### ISSUE TITLE
Update deploy-dev log if in phet-io brand

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#598]
Currently, for a phet-io dev deploy, we get this link at the end:

```
$ grunt deploy-dev --brand=phet-io
Running "deploy-dev" task
deployed: http://www.colorado.edu/physics/phet/dev/html/resistance-in-a-wire/1.3.0-phetiodev.10/resistance-in-a-wire_en.html

Done.
```

but that link is invalid, it should look like  http://www.colorado.edu/physics/phet/dev/html/resistance-in-a-wire/1.3.0-phetiodev.10/wrappers/index

This minor change will help devs new to phet-io find the proper link while testing.

**Comment by zepumph** [comment]
Fixed in the above commits, here is the console output when I built/deployed FL 1.3.7-phetiodev.4. 

```
$ grunt deploy-dev --brand=phet-io
Running "deploy-dev" task
deployed: http://www.colorado.edu/physics/phet/dev/html/faradays-law/1.3.7-phetiodev.4/wrappers/index

Done.
```

And then for 1.3.7-dev.5 
```
Running "deploy-dev" task
deployed: http://www.colorado.edu/physics/phet/dev/html/faradays-law/1.3.7-dev.5/faradays-law_en.html

Done.
```

@mattpen could you just double check that this looks good, since its common code. I think it is ready to close. Thanks.

**Comment by mattpen** [comment]
This looks good to me.
