### ISSUE TITLE
scp problems with deploy-dev.sh

### ISSUE THREAD

**Issue by jbphet** [phetsims/chipper#6]
I found an issue with a deployment (forgot to include sounds as a resource), so I fixed it locally and re-ran the deployment script without updating the version number.  It ended up copying the build dir as a subdir to the deployment dir instead of overwriting the existing deployment.

BTW, CM has looked at this issue and is aware of it.  We tried a quick fix, but that caused other issues.

**Comment by pixelzoom** [comment]
This will eventually be rewritten as a grunt task (see https://github.com/phetsims/chipper/issues/87), so there are no plans to fix this issue.  Closing.
