### ISSUE TITLE
Investigate Node 8.3.0

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#601]
Node 8.3.0 came out and promises performance improvements for CPU bound tasks.  I'd like to take a look and see how it impacts our builds:

Node v8.3.0
https://nodejs.org/en/blog/release/v8.3.0/

Tagging for developer meeting to let other developers know this is in the works.

**Comment by mattpen** [comment]
Can we upgrade to Node 8 without upgrading to NPM 5?  There are still some outstanding questions regarding NPM 5 - https://github.com/phetsims/chipper/issues/578.

**Comment by mattpen** [comment]
Here is what the build-server is currently using:

[mape5853@phet-server ~]$ node -v
v4.6.0
[mape5853@phet-server ~]$ npm -v
2.15.9

**Comment by jbphet** [comment]
@samreid is going to try it out on his local machine and see how it works.

**Comment by samreid** [comment]
1. Close all applications except for chrome and the terminal
2. cd faradays-law; grunt; time grunt

> real	0m15.199s
user	0m15.525s
sys	0m0.494s

3. cd ../function-builder; grunt; time grunt

> real	0m12.908s
user	0m13.163s
sys	0m0.525s

4. cd ../faradays-law; time grunt

> real	0m15.421s
user	0m15.732s
sys	0m0.490s

5. cd ../function-builder;time grunt

> real	0m13.078s
user	0m13.314s
sys	0m0.528s

node --version

> v8.0.0

**Comment by samreid** [comment]
Follow https://stackoverflow.com/questions/8191459/how-do-i-update-node-js to update to 8.3.0 (note not yet in stable)

node --version

> v8.3.0

Faradays law, grunt then time grunt

> real	0m12.846s
user	0m14.040s
sys	0m0.444s

For function builder:

> real	0m11.410s
user	0m12.488s
sys	0m0.486s

Looks like this saves a couple of seconds, to me it doesn't seem like a significant enough reason to recommend upgrading.  (Unless @jonathanolson thinks this would come in handy on bayes).

**Comment by jonathanolson** [comment]
Bayes' continuous testing bottleneck is mainly npm. A slight improvement for node speed would be nice, but not that important (it does 8 concurrent builds at a time, and finishes up all sims faster than npm handling takes).

**Comment by samreid** [comment]
OK thanks, closing.
