### ISSUE TITLE
delete js/grunt/phet-io/createTypeDocumentation.js?

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#603]
In https://github.com/phetsims/phet-io/issues/1169 we implemented a new way to get phet-io docs during the build. This means that `createTypeDocumentation is no longer needed. One purpose to keep it around is that it is how the devguide creates its type documentation. That's why I wanted to discuss. How should we handle these two situations. I don't see an easy way that we could get a master list of all the types (at least common code ones) for the devguide by just loading one sim in the documentation wrapper. 

Maybe we could run a wrapper that runs the documentation wrapper for all phet-io sims, and gather the unique list of all types for the devguide.
Con would be that it would have sim specific types build in. We could code around that, with a `I_AM_A_SIM_TYPE` flag in the ttype, but that seems sloppy.

**Comment by zepumph** [comment]
In the above commit, I reworked the file back to its old usage, where running it from the command line will generate the master list of common code types to the console. Then you can paste those in to the dev guide. This is just so we have it.

**Comment by zepumph** [comment]
And by above I mean below commit.

**Comment by samreid** [comment]
> Maybe we could run a wrapper that runs the documentation wrapper for all phet-io sims, and gather the unique list of all types for the devguide.

We may no longer need to provide "general" type docs if we provide great type docs for each sim, right?  Or if we do need general type docs, we should try to leverage the existing process as much as possible.

Also, how will we handle parameterized types, will `Property.<number>` be different than `Property.<string>`?

**Comment by zepumph** [comment]
>Also, how will we handle parameterized types, will Property.<number> be different than Property.<string>?

It may be nice to handle this in documentation similarly to my current approach for TFunctionWrapper in https://github.com/phetsims/phet-io/issues/1197 (it shows up as "TFunctionWrapper( TString, TBoolean)" instead of "TFunctionWrapper"

**Comment by samreid** [comment]
My concern if we enumerate all of the combinations that appear is that we may end up with hundreds of concrete parameterized types.  Not sure what's best.

**Comment by zepumph** [comment]
I'm sorry if I wasn't more specific before. My thoughts are to do the aforementioned strategy when describing the instance/type tuples like:

```
faradaysLaw.faradaysLawScreen.model.magnetModel.showFieldLinesProperty

TProperty
```

could look like
```
faradaysLaw.faradaysLawScreen.model.magnetModel.showFieldLinesProperty

TProperty.<TBoolean>
```

I do not think each parametric type deserves another listing in the TTypes documentation.

**Comment by samreid** [comment]
Ah, that sounds great!

**Comment by zepumph** [comment]
>We may no longer need to provide "general" type docs if we provide great type docs for each sim, right? Or if we do need general type docs, we should try to leverage the existing process as much as possible.

Very possible! I'm thinking about what to do with the current devguide. Do we just delete the Ttypes section and replace it with:
"Documentation for types and instances for each sim is located in each built sim folder under `VERSION/doc/phet-io-documentation.html`"

Not a horrible plan, but we have to manage backwards compatibility.

**Comment by zepumph** [comment]
Another idea. Somehow make a documentation wrapper in a similar fashion to the playback wrapper where it can work on any sim, and it can get type/instances out of any sim on our site. I think that it would be pretty simple to be backwards compatible for all sims that use SimIFrameClient.launchSim (I think that was implemented back in october or so.) because our wrapper will be able to wire into that. I bet that there aren't many/any sims delivered to our Pearson/Brainpop type clients that were before that. See https://phet-io.colorado.edu/sims/faradays-law/1.3.6-phetio/wrappers/common/js/SimIFrameClient.js (which was published as a batch for Pearson) uses launchSim.

I think this warrants another issue. Let's talk about https://github.com/phetsims/chipper/issues/603#issuecomment-322075302 here though.

**Comment by samreid** [comment]
> Somehow make a documentation wrapper in a similar fashion to the playback wrapper where it can work on any sim, and it can get type/instances out of any sim on our site.

I think that would be great--my main concern is being able to easily generate diffs between APIs.  If we can figure that out, then perhaps these docs can be delivered as a wrapper instead of static docs.

**Comment by samreid** [comment]
https://github.com/phetsims/chipper/issues/603#issuecomment-322075302 sounds great to me.  To handle backward compatibility, we could leave up an archive of the old dev guide until no sims rely on it any longer.  We should chat.

**Comment by zepumph** [comment]
> To handle backward compatibility, we could leave up an archive of the old dev guide until no sims rely on it any longer. We should chat.

Isn't backwards compatibility already handled because we have been copying the devguide into phet-io builds for a year or more.  All of the oldest deliveries found in Partners.md have devguides in their index wrappers. So perhaps the best way to proceed is to say that "old versions" of sims can find their documentation under {{VERSION}}/docs/devguide. 

As for our previous plan of 
>Do we just delete the Ttypes section and replace it with:
"Documentation for types and instances for each sim is located in each built sim folder under VERSION/doc/phet-io-documentation.html"

This is dated, and will be discussed further in https://github.com/phetsims/phet-io/issues/1237. For now I think we should delete this file, because moving forward we will not need to use it anymore even for static docs (nor am I sure it even works). A better plan for the dev guide will be decided when we solidify what will be done with the documentation strategy itself.

**Comment by samreid** [comment]
It looks like the documentation wrapper now supercedes createTypeDocumentation.js, feel free to delete.  @zepumph can this issue be closed?

**Comment by zepumph** [comment]
Agreed! Deleted and closing.
