### ISSUE TITLE
requirejs-build task: WARN: Output exceeds 32000 characters 

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/chipper#605]
I started seeing this warning after the requirejs-build task.
```
Running "requirejs-build" task
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
```

I am seeing it for all sims, though the number of times the warning is printed is different for each sim.  It sounds like other devs are not seeing this.  @jonathanolson recommended I try wiping node_modules in chipper and the sim. I gave it a shot but I am still seeing the warning.

**Comment by jessegreenberg** [comment]
@Denz1994 found what is likely a related option max_line_len https://github.com/mishoo/UglifyJS2

> max_line_len (default false) -- maximum line length (for uglified code)

**Comment by pixelzoom** [comment]
... and it may be in other node_modules subdirectories, which I have excluded from my WebStorm search path.

**Comment by pixelzoom** [comment]
Indeed, I also have `max_line_len: 32000` in chipper/node_modules/requirejs/bin/rs.j.

**Comment by pixelzoom** [comment]
After doing `npm update` in chipper, I am now seeing the same issue as @jessegreenberg.

```
% cd chipper
% npm update
chipper@0.0.0 /Users/cmalley/PhET/GitHub/chipper
└── requirejs@2.3.5

cmalley@semitone[72]: cd ../forces-and-motion-basics/
cmalley@semitone[73]: grunt
Running “lint-all” task

Running “clean” task

Running “requirejs-build” task
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters
WARN: Output exceeds 32000 characters

Running “after-requirejs-build” task

Done.
%
```

**Comment by jessegreenberg** [comment]
If I add ```max_line_len: false``` to ```uglify2``` ```output``` options in ```requireJsBuild.js``` the warning goes away for PhET and PhET-iO builds. According to docs it should already be false by default.

Labelling for dev meeting to see if anyone knows why this started showing up in the first place and if adding this option to ```uglify2``` in ```requireJsBuild.js``` is acceptable.

**Comment by pixelzoom** [comment]
When I did `npm update` in chipper (see https://github.com/phetsims/chipper/issues/605#issuecomment-324420780), the only thing that appeared to update was `requirejs@2.3.5`.  So I suspect the default optimizer setting changed for requirejs. 

+1 for adding `max_line_len: false` to `requirejsBuild.js`.

**Comment by samreid** [comment]
Here's the result of my npm update

```
~/github/chipper$ npm update
+ requirejs@2.3.5
removed 14 packages and updated 1 package in 2.39s
```

**Comment by samreid** [comment]
I'm seeing this output now:

WARN: Output exceeds 32000 characters

**Comment by jessegreenberg** [comment]
Ill build a sim with the option added and make sure output is the same.  If so, Ill commit the option and close.

**Comment by jessegreenberg** [comment]
![capture](https://user-images.githubusercontent.com/6396244/29689888-09ae13b8-88e2-11e7-8a00-7e9f1101bde6.PNG)

Left is build before the option is added, right is build after the option is.  Output seems identical.

**Comment by jessegreenberg** [comment]
Committed, closing.

**Comment by samreid** [comment]
Looks great on my side, thanks!
