### ISSUE TITLE
build broken for sonification wrappers

### ISSUE THREAD

**Issue by jbphet** [phetsims/chipper#607]
The build seems to be broken for the sonification wrappers.  Here is what I see when I attempt a build:

![build-fail](https://user-images.githubusercontent.com/3082831/29987105-b96052a2-8f23-11e7-94a6-f18d9ff1ee14.PNG)

I suspected that this was due to some recent changes related to https://github.com/phetsims/phet-io/issues/1097, so I reverted back to a version of chipper from prior to when that work was started (c6ebc753b034d44354757e97ae7b2ee818c02dfa to be exact) and was able to do a build and deploy.  So, I've got a workaround, but it would be good to get this fixed in master.

**Comment by zepumph** [comment]
I'm so sorry about that!  Sloppy programming, I didn't think to test the sonification wrapper build. It should be fixed now.

**Comment by zepumph** [comment]
Please close or reassign.

**Comment by jbphet** [comment]
It's working now, thanks for the quick fix.  Closing.
