### ISSUE TITLE
Sort all require statements in the project

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#609]
From a discussion on slack, it would be good to have all of the require statements in alphabetical order by Type name. There was a poll taken of developers present.

**Comment by zepumph** [comment]
It looks like the grunt task `sort-require-statements` touches every file and and changes 'CRLF' to 'LF', so even files that don't need sorting show up in intellij's commit dialog. Luckily these 'unchanged' files don't muddy up actual commits. To test this I committed one of these unchanged files with `js/common/view/graph/ConcentrationGraphBarNode.js` in acid-base-solutions in this commit:

https://github.com/phetsims/acid-base-solutions/commit/20d9617a52e6e263ba0dff608b8d4e850bfd5190

It looks like the unchanged file does show up in the commit. I will proceed with looking into the other 4009 files that were touched by the grunt task (many of which will be 'unchanged')

**Comment by zepumph** [comment]
Ahh here is more about CRLF:
https://stackoverflow.com/questions/1552749/difference-between-cr-lf-lf-and-cr-line-break-types

I think I will update the grunt task to join with '\r\n' instead of just a newline.

**Comment by zepumph** [comment]
>I think I will update the grunt task to join with '\r\n' instead of just a newline.

I did so and found just as many places that had just line separator differences. I am going to leave it as is.

**Comment by samreid** [comment]
I spot checked several files and they seem correct.  I re-ran `for-each active-repos sort-require-statements` and did not see any missed files.  Likewise I did not see any lint or systemic aqua errors related to this.  Thanks! Closing.
