### ISSUE TITLE
Eliminate "log:" from phet.log

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#613]
phet.log is implemented like so:

```js
    // Add a log function that displays messages to the console.
    if ( window.phet.chipper.queryParameters.log ) {
      window.phet.log = function( message ) {
        console.log( '%clog: ' + message, 'color: #009900' ); // green
      };
    }
```

This causes the messages to come out like this:
![image](https://user-images.githubusercontent.com/679486/30622787-191049e0-9d71-11e7-9153-d472dfeaa233.png)

The `"log: "` is extraneous.  It is already clearly a message from the phet.log because it is green and because it says it comes from initialize-globals.js.  It gets in the way of the message the programmer is trying to show, and it should be eliminated.

**Comment by pixelzoom** [comment]
Go for it.

**Comment by samreid** [comment]
I went for it!  Closing.
