### ISSUE TITLE
ifphetio start/end should only exist for phetioEvents

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#615]

**Comment by samreid** [comment]
@zepumph can you please review the changes in the ifphetio plugin to make sure it is safe?

**Comment by samreid** [comment]
Also, I was worried this could slow down phet-brand code, but in fact calling no-op functions will be faster than calling emitters with no listeners.

**Comment by zepumph** [comment]
It looks nice. I don't love that you have to type out the function code duplicated as a string, but I'm not sure about a way around that one. `f.toString()` won't show its properties, and `JSON.stringify` doesn't work. Otherwise it looks good. Back to you for a close.
