### ISSUE TITLE
add Gruntfile for all common-code repos

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#62]
It's a bit annoying that you can't go to a common-code repo and do 'grunt lint' to check that it passes jshint. You have to go to a sim repo, type 'grunt lint-common', then wait for all common-code repos to be checked.

So we should add a Gruntfile to common-code repos that facilitates (at a minimum) 'grunt lint'.  

Suggestions for other things that should be in the common-code Gruntfile?

**Comment by pixelzoom** [comment]
All common repos (except scenery, dot, kite) now support 'grunt lint'. 

Assigning to @jonathanolson to add support for scenery, dot and kite.

**Comment by pixelzoom** [comment]
I also didn't do these repos: arch, assert, blast, brand, chronicle, dodecadog, lingo, phet-info, share, shred, together.  Which of these should have a Gruntfile + package.json?

**Comment by jonathanolson** [comment]
I'm confused by the request, 'grunt lint' is already available for scenery/kite/dot. Can you clarify?

**Comment by pixelzoom** [comment]
I said:
> It's a bit annoying that you can't go to a common-code repo and do 'grunt lint' 

@jonathanolson said:
> Scenery/Kite/Dot will want to maintain the functionality in their current gruntfiles, but it would be nice to have that ability from them.

So I took that to mean that 'grunt lint' was not supported by scenery/dot/kite. If the functionality is there, then by all means, close this issue.

**Comment by jonathanolson** [comment]
'grunt lint-common' isn't supported yet in scenery/kite/dot, is that the part that is desired?

**Comment by pixelzoom** [comment]
'grunt lint' is sufficient for common-code repos.

**Comment by jonathanolson** [comment]
Since 'grunt lint' is supported by scenery/kite/dot and the above comment:

> So I took that to mean that 'grunt lint' was not supported by scenery/dot/kite. If the functionality is there, then by all means, close this issue.

I'm closing the issue.

**Comment by samreid** [comment]
Reopening since I don't think we addressed @pixelzoom question:

> I also didn't do these repos: arch, assert, blast, brand, chronicle, dodecadog, lingo, phet-info, share, shred, together. Which of these should have a Gruntfile + package.json?

**Comment by pixelzoom** [comment]
@samreid, I think you created the majority of the repos that don't have a Gruntfile + package.json, so perhaps you can answer the question. Which of these need attention?  arch, assert, blast, brand, chronicle, dodecadog, lingo, phet-info, share, shred, together.

**Comment by samreid** [comment]
arch, chronicle, dodecadog, phet-info, share & together do not follow the same requirejs/module pattern as our normal sims, so should not have Gruntfile+package.json (though we may want a way to jshint them and a few other features).  Blast should get these, though.

**Comment by samreid** [comment]
It looks like Gruntfile and package.json already exist for blast--what is the issue specifically?

**Comment by pixelzoom** [comment]
The issue is that we've been adding Gruntfile to common-code repos so that we can joshing them independently of sims. Some of the grunt tasks (e.g., build) are obviously not appropriate for common-code repos, just don't use those tasks. 

So my evaluation is that any repo that has a js/ directory should be jshint-able, and should therefore have a Gruntfile. That includes arch, chronicle, dodecadog, share & together.  phet-info contains no js, so therefore does not currently need a Gruntfile.

@samreid do you concur?

**Comment by pixelzoom** [comment]
Case in point... I added Gruntfile to arch, and discovered that it fails jshint.

**Comment by pixelzoom** [comment]
I added Gruntfile.js and package.json to arch, chronicle, dodecadog, share & together. All of these repos currently fail `grunt lint` (issue created for each repo.)

For arch, chronicle and together, the license is unspecified in the LICENSE file. So I put this in package.json:

> "license": "contact phethelp@colorado.edu",

@samreid please review.

**Comment by pixelzoom** [comment]
Also added to phetbrand/brand.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/phetcommon/issues/23, we decided to consolidate 'check' scripts into initialize-globals.js and relocate under chipper.  Recommend to put initialize-globals.js under chipper/js, move requirejs-plugins under chipper/js, and add Gruntfile.js and package.json to chipper top-level. Otherwise we can't `grunt lint` any of the JS source in chipper.

**Comment by pixelzoom** [comment]
We also have grunt tasks (.js) under chipper/grunt that should be lintable.

**Comment by pixelzoom** [comment]
chipper linting issue is moved to https://github.com/phetsims/chipper/issues/92.  So if the other repos look OK, feel free to close this issue.

**Comment by samreid** [comment]
No time at the moment to review this, @jonathanolson or @jbphet please feel free to take a look if you wish.

**Comment by pixelzoom** [comment]
I'm just going to close this. It's been a week or so, and no problems have been reported.
