### ISSUE TITLE
bad doc for strings query parameter

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#620]
Noted while working on https://github.com/phetsims/chipper/issues/619.

The documentation for the `strings` query parameter is totally bogus:

```js
    /**
     * override strings, value is JSON that is identical to string.json files
     */
    strings: {
      type: 'string',
      defaultValue: null
    },
```

**Comment by pixelzoom** [comment]
Thanks to @jonathanolson and @jbphet for helping me figure this out.  And the lucky reviewer is:

```
> _.shuffle( ['JB','JO'] )[0]
"JO"
```

**Comment by jonathanolson** [comment]
Docs look great, thanks!
