### ISSUE TITLE
create global: phet.chipper.a11yEnabled

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#623]
From https://github.com/phetsims/joist/issues/454 and https://github.com/phetsims/scenery/issues/710,

We want to create this flag so that we can use it everywhere like for focusProperty in Display.js, UtteranceQueue, and anywhere else it may come up.

**Comment by zepumph** [comment]
@jessegreenberg please review

**Comment by zepumph** [comment]
I thought that it would be confusing to have both of them be named the same. We are running into that right now in phet-io because there is `Sim.activeProperty` and `Screen.activeProperty`, but both are "Active Property". Will it be confusing?

**Comment by jessegreenberg** [comment]
I don't think so, in this case they really are the same thing
```js
  window.phet.chipper.a11yEnabled = phet.chipper.queryParameters.accessibility;
```

I also noticed that `phet.chipper.randomSeed` matches the name of the query parameter.

**Comment by zepumph** [comment]
I am convinced! Closing.
