### ISSUE TITLE
Should PhET have someone whose primary job is the build tools?

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#625]
This was brought up in https://github.com/phetsims/chipper/issues/567#issuecomment-298974310 while discussing integrating the build process for phet-io and phet brands together. I know that Chipper:2.0 is in full swing, and taking many people's time right now, but I think it was worth promoting to its own issue.

**Comment by samreid** [comment]
We may be better poised to answer this after a month or two after chipper 2.0 is complete.

**Comment by samreid** [comment]
@jonathanolson reported:

> I've mostly rewritten or ported (to ES6/promises) most of chipper and perennial, and it's not that much code. Assuming others take on build-server and rosetta, I can probably take on maintenance for this without too much interruption.

@pixelzoom or @ariel-phet ok to close this issue?

**Comment by pixelzoom** [comment]
Responsibility for chipper is not my call, that's up to @ariel-phet.

**Comment by ariel-phet** [comment]
@samreid yes, we can close. I think we have a few people that are familiar with the build tools these days (both @mattpen and @jonathanolson). But I think we will try to make sure if we bring on a new dev we also get them some experience there.
