### ISSUE TITLE
pDOM UI components disappear on first redraw/update

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#626]
When the A11y View first loads, things look good, like this on for MAL in chrome:

![image](https://user-images.githubusercontent.com/6856943/33352577-09ea1196-d456-11e7-9080-69680d02aeb2.png)

Then after interacting with it, many componets disappear in strange ways:
![image](https://user-images.githubusercontent.com/6856943/33352587-202299f6-d456-11e7-9380-dc527b1ec056.png)

This behavior is different depending on the browser, like on firefox we have the same disappearance with the slider, but the radio buttons still work. Assigning to discussion for dev meeting.

**Comment by zepumph** [comment]
We can assign priority to this issue based on the consensus of https://github.com/phetsims/a11y-research/issues/63 after the IDRC meeting Friday.

**Comment by jessegreenberg** [comment]
This was fixed as part of #684, here is a capture of MAL after changes now:
![capture](https://user-images.githubusercontent.com/6396244/42001323-e2521fa4-7a20-11e8-992b-b65393eb4540.PNG)
