### ISSUE TITLE
don't use JB's credentials for build process

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#627]
It's likely that some build process is using @jbphet's credentials, so files end up being owned by him.   As @jbphet suggested below, this should be changed to use "a machine account of some kind". 

Slack thread:

Chris Malley [5:14 PM] 
I see that you published function-builder 1.0.9-rc.1 on 11/17, so it has entered an RC phase. What’s going on?

John Blanco [8:54 AM] 
I think you meant to ping JO on this (kinda freaked me out, since I didn't recall it at all).

Chris Malley [8:55 AM] 
drwxrwsr-x   2 jblanco  physphet    4096 Nov 17 18:51 1.0.9-rc.1/

John Blanco [8:55 AM] 
https://github.com/phetsims/function-builder/commits/1.0

Chris Malley [8:56 AM] 
hmmm… how did the files on spot end up owned by you?

John Blanco [8:57 AM] 
Not sure.  I know rosetta uses my account information for some file transfer operations, maybe this is done in other places in the build tools too.  If so, probably best to modify that to use a machine account of some kind.

As I think about it, but build server is likely using my account info.  I'll put that on my list to investigate today.

**Comment by jbphet** [comment]
Since it's the build server that is doing this, I'm going to move this issue to the perennial repo.

**Comment by jbphet** [comment]
Moved to https://github.com/phetsims/perennial/issues/50, closing.
