### ISSUE TITLE
publication and versioning requirements

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#629]
I collaborated on this issue with @ariel-phet via Zoom.  Other chipper:2.0 decisions should sanity check with the requirements herein.

Breaking this issue out of the checklist in https://github.com/phetsims/phet-io/issues/1137:

> - [ ] What is the relationship between PhET and PhET-iO branded sims? (testing, deployment, version identifiers, update notifications, ...)

@ariel-phet's understanding of the requirements:

• In deciding which brands to publish, ask "which brands are affected by the changes/fixes being made?"
• PhET-iO fixes will typically result in republishing brand=phet-io, but not brand=phet 
• non-PhET-iO fixes (eg sim model bug) will typically result in republishing all supported brands
• build all supported brands, or a subset of supported brands if necessary
• deploy RC versions only of brands that we intend to test
• test all brands that were deployed for RC
• publish all brands that were tested in the RC process
• keep version identifiers "in lock step"
• build a debug version (all.html) for each brand, and each step in the deployment process (so dev and RC have a debug version for QA)
• minimize irrelevant update notifications and app updates by publishing only brands that are actually affected by a change/fix

**Comment by jonathanolson** [comment]
> deploy RC versions only of brands that we intend to test

So, if we test phet-io fixes only, can I just automated-maintenance-release that into phet-brand in the future (since it's only one branch)?

**Comment by pixelzoom** [comment]
> So, if we test phet-io fixes only, can I just automated-maintenance-release that into phet-brand in the future (since it's only one branch)?

If the fix is specific to brand=phet-io, then that should be safe to do.

**Comment by pixelzoom** [comment]
12/4/17 dev meeting notes:

We discussed this requirement:
> •  deploy RC versions only of brands that we intend to test

Decided that this is a good requirement.

Decided to make `brands=...` a required build parameter, comma separated (e.g. `brands=phet,phetio`) with prompted verification and wildcard support (i.e., `brands=*`).

**Comment by ariel-phet** [comment]
@mattpen @jonathanolson this is sort of a "meta issue" to capture our high level goals. Feel free to close at your discretion if everything is clear.

**Comment by jonathanolson** [comment]
These goals are clear to me, and the current chipper 2.0 branch is fully compatible with this. Deployment processes will all take in a required list of brands. Unassigning.

**Comment by mattpen** [comment]
I understand the goals and will keep these in mind for the changes to perennial.
