### ISSUE TITLE
Code review for branch: automated-test-harness

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#631]
See https://github.com/phetsims/chipper/issues/624

I created a chipper branch that can generate a qunit test harness, which should be reviewed before merging into chipper/master.  This will also need to be merged with chipper 2.0 branch.

One of the implementation decisions I made in this branch was to extend and reuse the templates/sim-development.html rather than copy/pasting and modifying a separate template.

@ariel-phet can you please assign a reviewer for this branch?  @jonathanolson would be an ideal candidate because he is most familiar with chipper 2.0 implementation and already somewhat familiar with #624, but I know he is busy.  However, it is not a large change set and it would be nice to get it moved to master and 2.0 soon.

**Comment by samreid** [comment]
Also, the larger development team may wish to discuss these points:

> I elected to put the tests adjacent to the types they are testing, for instance js/Bounds2.js has js/Bounds2Test.js. This is to (1) keep code co-located to what it tests and (2) to give tests equal footing instead of putting them somewhere else (I know this is unconventional).

Likewise, the test main is {{REPO}}/{{REPO}}-test.html, the test config is {{REPO}}/js/{{REPO}}-test-config.js and the test main is {{REPO}}/js/{{REPO}}-test.js

https://github.com/phetsims/chipper/issues/624#issuecomment-346510800

The main philosophy is that tests should not be buried somewhere else, but front and center with the code it is testing.  Our build process ensures that test code doesn't end up in builds.  Each simulation/repo will have one entry point for launching the sim and one entry point for launching the tests, and they are in the same directory.

**Comment by samreid** [comment]
I've merged the chipper branch to master, and we can continue with review and improvement in master.

**Comment by ariel-phet** [comment]
Will plan to discuss on 12/7/2017

**Comment by jonathanolson** [comment]
Since this was merged into master, I'll be reviewing this (as I'll need to essentially port/merge it into the 2.0 branch).

**Comment by jonathanolson** [comment]
@samreid, would we only run the generate step on repositories when we initially add unit tests to them? Or should it be in all repositories?

**Comment by jonathanolson** [comment]
Worth noting (in this issue) that the test HTML has an additional dependency into aqua (which seems like the correct place for the given code to live).

**Comment by jonathanolson** [comment]
Changes look very reasonable, I'll "merge" them into 2.0 (it's ES6+-ified, buildConfig isn't a thing anymore, etc. so it will be easier to do manually).

**Comment by jonathanolson** [comment]
Implemented in the chipper 2.0 branch above, @samreid can you review?

Two further notes:

- I pluralized to stripPreloads (in case we ever want more for some reason).
- It looks like something auto-formatted the tests HTML files that were checked in, as it was different than what was generated. This would be a problem, and we should generate the file with the correct formatting (or prevent intellij or another tool from auto-formatting it). Attempting to create a commit without formatting should be a "this does nothing, won't let you commit" git operation.

**Comment by samreid** [comment]
> @samreid, would we only run the generate step on repositories when we initially add unit tests to them? Or should it be in all repositories?

This is new territory.  Eagerly generating this for all repos would make it trivial for developers to add new unit tests and for them to get tested on Bayes right away.  It would also encourage us to add test, for instance we could have a check on the code review checklist that the simulation should have appropriate QUnit testing coverage.  On the other hand, would it bog down Bayes a lot (runtime and/or UI) if it is running a lot (hundreds?) of tests that run 0/0 qunits?

**Comment by samreid** [comment]
> It looks like something auto-formatted the tests HTML files that were checked in,

I appreciate that my IDE automatically formats files before commit. However, for templates I have to remember to turn this off, then for next commit I have to remember to turn it back on again.  The best solution I can think of is to rename the filename suffixes like ".htmltemplate" or ".jstemplate" since the file isn't really html or js.

**Comment by jonathanolson** [comment]
> I appreciate that my IDE automatically formats files before commit. However, for templates I have to remember to turn this off, then for next commit I have to remember to turn it back on again. The best solution I can think of is to rename the filename suffixes like ".htmltemplate" or ".jstemplate" since the file isn't really html or js.

I'm not talking about the templates, but the actual `${repo}/${repo}-tests.html`. And you propose renaming things, but I don't see any objections to my proposal (and what we've done in the past) which is to just generate the file with the correct formatting in the first place (so that Intellij wouldn't change it in your commit step).

**Comment by jonathanolson** [comment]
>  On the other hand, would it bog down Bayes a lot (runtime and/or UI) if it is running a lot (hundreds?) of tests that run 0/0 qunits?

Actually, that could bog down Apache a decent amount on the server.

**Comment by samreid** [comment]
My apologies for misunderstanding, I'll correct the formatting in https://github.com/phetsims/chipper/issues/634

**Comment by samreid** [comment]
I think this issue is wrapped up, we can continue with the formatting in #634, closing.
