### ISSUE TITLE
Make sure that phet-io builds include the all.html for dev/rc

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#632]
From #630, it seems like the phet-io built html file will be an '_all.html' file. I want to make sure that it is noted that phet-io wrappers will need to support the _all.html query parameters/i18n strings while developing.

@jonathanolson In my mind deploy-dev for brand phet-io will be an _all.html file. Am I wrong there?

**Comment by samreid** [comment]
I'm not sure how I can contribute to this issue, unassigning for now.

**Comment by zepumph** [comment]
To be clear. This issue is to solidify what is the main build artifact (html file) from a phet-io build. I recommend that we never build locale specific phet-io sims, and only build/use _all.html files for phet-io.

@jonathanolson @samreid please agree with or discuss alternatives to moving forward with supporting the following build artifacts for phet-io builds. These will be the **only** _top level_ html files built for phet-io branded sims:

```
  // brand=phetio
  1.0.0-dev.1-phetio/
    faradays-law_all-phetio.html
    faradays-law_all-phetio-debug.html
  1.0.0-rc.1-phetio/
    faradays-law_all-phetio.html
    faradays-law_all-phetio-debug.html
  1.0.0-phetio/
    faradays-law_all-phetio.html
    faradays-law_all-phetio-debug.html


```

**Comment by samreid** [comment]
That seems correct and I agree it seems sensible to only use the _all.html for PhET-iO. Will there also be dependencies.json?

> phet-io wrappers will need to support the _all.html query parameters/i18n strings while developing.

Can you elaborate on what this means?  Are you talking about phet-io clients developing wrappers?

**Comment by zepumph** [comment]
> Are you talking about phet-io clients developing wrappers? 

Yes, I was also thinking that there may be differences in running a wrapper suite wrapper (like instance proxies) in different locales, and it would be good to be able to double check that locally.

This has been sorted out in #560. Closing
