### ISSUE TITLE
document version id conventions

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#636]
From https://github.com/phetsims/chipper/issues/560#issuecomment-350065653:

> • TODO: Document this somewhere when it becomes reality.

Need to document version id, file/dir naming conventions, etc. after #560 has been closed.

**Comment by jonathanolson** [comment]
Somewhat pending on https://github.com/phetsims/perennial/issues/69, but the current version parsing uses `major.minor.maintenance[-test][-oneOff]` where test is `testType.testNumber` (e.g. dev.1). Major/minor/maintenance/testNumber are 1+ digits, and testType/oneOff is anything without `"-"` or `"."`.

toString is basically:
```js
var str = `${this.major}.${this.minor}.${this.maintenance}`;
if ( typeof this.testType === 'string' ) {
  str += `-${this.testType}.${this.testNumber}`;
}
if ( typeof this.oneOff === 'string' ) {
  str += `-${this.oneOff}`;
}
```

I'll be free to fully document conventions when it is fully solidified.

**Comment by ariel-phet** [comment]
labeling for dev meeting for a check in.

**Comment by pixelzoom** [comment]
1/18/18 dev meeting: @jonathanolson will handle doc.

**Comment by jonathanolson** [comment]
Documented in perennial's SimVersion. Is that location fine for the canonical documentation for how versioning works, or should that be moved to some .md file?

**Comment by jonathanolson** [comment]
@pixelzoom, can you comment on whether there should be any improvements to the documentation?

**Comment by pixelzoom** [comment]
Doc in SimVersion and https://github.com/phetsims/chipper/issues/560#issuecomment-359872043 looks great.

Back to @jonathanolson in case there's anything else to do here.  Feel free to close.

**Comment by jonathanolson** [comment]
Closing, thanks!
