### ISSUE TITLE
remove unused aria live attributes from sim html

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#637]
From https://github.com/phetsims/a11y-research/issues/66, we don't need any aria-live elements except the polite one.

**Comment by zepumph** [comment]
We should make sure to remove usages of these other ones first, like in AriaHerald.

**Comment by zepumph** [comment]
What is the status on this? In `AriaHerald` I only see the polite element, I also see commits above that removed it from built sims, but in the sim template for development still has it in it. I will need to remove that.

**Comment by zepumph** [comment]
Alright @jessegreenberg, I have now removed the 3 other aria live elements from (1) `AriaHerald`, (2) the built sim template, and (3) the development sim template (updating all of the sim htmls). Is there anything else to be done here? Could you give me a spot check?

**Comment by jessegreenberg** [comment]
Thanks @zepumph, good to clean this up. I don't think there is anything else to do here.
