### ISSUE TITLE
grunt dev dies silently when "brands" is in build-local.json

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#639]
`cd chains; grunt dev;` dies like:
```
 Michael /e/zepumph/Programming/PHET/git/chains (master)
 $ grunt dev
Running "dev" task
(Forwarding task to perennial)
Running "dev" task

Done.

Done.
```

but `grunt dev --brands=phet-io,phet` works as expected. I have tried my build-local.json in the following patterns:

`brands: ["phet", "phet-io"],` . . .
`brands: "phet,phet-io"`

with the same results.

branches:
chipper: 2.0
perennial: chipper2.0
chains: master
phet-io-wrappers: chipper2.0

Assigning to @jonathanolson. Hopefully this is a helpful report, but let me know if I'm just doing something wrong.

**Comment by jonathanolson** [comment]
I'm curious whether this is still happening. Can you re-test with latest chipper 2.0?

**Comment by pixelzoom** [comment]
I have this in ~/.phet/build-local.json:

`"brands": [ "phet" ],`

... and I've been running `grunt dev` with no problems.

**Comment by zepumph** [comment]
Works well for me now, closing
