### ISSUE TITLE
grunt update-copyright-dates doesn't play nice with config files

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#644]
For instance, gravity-force-lab-basics-config.js has commits from 2016-2017, so `grunt update-copyright-dates changes the statement from:
```js
// Copyright 2017, University of Colorado Boulder
```
to
```js
// Copyright 2016-2017, University of Colorado Boulder
```

The latter is actually correct, I wonder if we should change the `grunt generate-config` task to use this logic when creating the config files?  Or we can add logic to the update copyrights task to skip config files.

@jonathanolson do you have a preference?

**Comment by jonathanolson** [comment]
I'd say it would be great to have this done, but the update-copyright code might take some work to make it apply to single files.

Are you available to potentially modify updateCopyrightDates to take a parameter of a single file to change, and then I can apply the change to the config (or test config) files?

This was a bit awkward for https://github.com/phetsims/chipper/issues/671, just pushed some differing copyright dates along with other good changes.

**Comment by jonathanolson** [comment]
That sounds great (and would allow updating the config/test-config in the same step if both are generated).

**Comment by samreid** [comment]
I added args to updateCopyrightDates in the preceding push.  I do not have time right now to refactor the entire function to act on one file at a time, but I did add the `sourceRoot` and `predicate` arguments, so it should work for the config files.  @jonathanolson at your convenience can you review and apply to the part that updates the config files?

**Comment by jonathanolson** [comment]
Refactored in the above commit, and added the copyright update to config updates. @samreid can you review?

I'll leave myself assigned so I can regenerate configs with proper copyright dates.

**Comment by samreid** [comment]
I skimmed the change set, and tested with `grunt update` and `grunt update-copyright-dates`.  All seems well, thanks!  Closing.
