### ISSUE TITLE
Is there a way to disable the eslint cache?

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#645]
In chipper 1.0 there was a command line option to disable the cache.  Is there one for chipper 2.0?  This is especially helpful when developing new lint rules (though a workaround can be to manually change cache to false in lint.js)

**Comment by jonathanolson** [comment]
The --disable-eslint-cache option was kept in chipper 2.0. Has that been tried, or is it not working?

**Comment by samreid** [comment]
I didn't see it used in lint-everything (maybe it is a different case).  I also noticed that findDuplicates has linting and caching, is that correct?

**Comment by jonathanolson** [comment]
> I didn't see it used in lint-everything (maybe it is a different case).

I added the flag in above, sorry about that.

>  I also noticed that findDuplicates has linting and caching, is that correct?

I really don't know, haven't used findDuplicates.

**Comment by samreid** [comment]
The change set looks reasonable, closing.
