### ISSUE TITLE
chipper 2.0 iframe generation for testing on spot

### ISSUE THREAD

**Issue by phet-steele** [phetsims/chipper#647]
This is a complete list of sim links I'm given when testing on spot under https://www.colorado.edu/physics/phet/dev/html/{{sim}}/{{version}}/phet/

- {{sim}}_all_phet.html  
- {{sim}}_all_phet_debug.html
- {{sim}}_en_phet.html
- {{sim}}_en_iframe.html

There are a few things about this list I want to ask about:

1. Why isn't the last (iframe) link "{{sim}}_en_phet_iframe.html" (with the brand in there)?
2. The last (iframe) link doesn't actually work. It receives a 404 trying to find a sim url that ends in: en.html. This wouldn't exist since now the sim ends in: en_phet.html.
3. Can I also get an iframe for the all_phet? So a {{sim}}_all_phet_iframe.html?

For reference, I'm drawing the above list specifically from https://www.colorado.edu/physics/phet/dev/html/gravity-force-lab-basics/1.0.0-dev.13/phet/.

**Comment by jonathanolson** [comment]
> Why isn't the last (iframe) link "{{sim}}_en_phet_iframe.html" (with the brand in there)?

It could be added

> The last (iframe) link doesn't actually work. It receives a 404 trying to find a sim url that ends in: en.html. This wouldn't exist since now the sim ends in: en_phet.html.

Will fix.

> Can I also get an iframe for the all_phet? So a {{sim}}_all_phet_iframe.html?

How would you want it to work? Would it need to forward query parameters?

**Comment by jonathanolson** [comment]
Please see https://www.colorado.edu/physics/phet/dev/html/chains/1.16.0-dev.1/phet/, does that look good? (try `locale=es` with the _all iframe).

**Comment by phet-steele** [comment]
@jonathanolson, love it! Thanks.
