### ISSUE TITLE
References break with newer require.js versions

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#65]
It seems that if there is a single '/../' after the require.js namespace, it isn't respected, with the latest require.js (2.1.13 from npm). It worked with 2.1.8.

SR initially identified this, and I've applied fixes for kite's parser (was included outside of js/).

**Comment by pixelzoom** [comment]
@jonathanolson is this still an issue?

**Comment by jonathanolson** [comment]
I'd classify it as a "known issue" with require.js where we shouldn't use /../.
