### ISSUE TITLE
`DEPLOY 1.6.1 to PRODUCTION [y/N]? ` should mention the brands

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#650]
As a final check, chipper 2.0 asks `DEPLOY 1.6.1 to PRODUCTION [y/N]? `.  It would be very useful if it also reported brand(s) in the confirmation prompt, because a faulty deploy to PRODUCTION PHET is very different than a faulty deploy to PRODUCTION PHET-IO

Discovered in https://github.com/phetsims/phet-io-wrappers/issues/49

**Comment by jonathanolson** [comment]
Including repos and brands in the confirmation message (with commits above).
