### ISSUE TITLE
Fix a11y-view summary paragraph

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/chipper#652]
@samreid noticed that the description for the a11y view is incorrect

From  slack:
> The accessible version of Friction is embedded in the iframe below.”  But the iframe wasn’t below--would it be better to say “embedded in the iframe”? because the location is unimportant?

**Comment by jessegreenberg** [comment]
Pinging @terracoda so she is aware of this update.

**Comment by jessegreenberg** [comment]
Changed to "embedded in the iframe" in the template. Closing.

**Comment by terracoda** [comment]
@jessegreenberg, the position is not important, so we can remove "below". I would, however, prefer the "general intro" text to be across the top as I described in https://github.com/phetsims/a11y-research/issues/66#issuecomment-358978999

As we continue to improve the A11y View, I'll review the text.
