### ISSUE TITLE
Grunt is doubling options

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#657]
I was looking into https://groups.google.com/forum/#!topic/developing-interactive-simulations-in-html5/Drau-MS0zis and found that changing Gruntfile.createSim to read:

```js
  grunt.registerTask( 'create-sim',
    'Creates a sim based on the simula-rasa template.\n' +
    '--repo="string" : the repository repo\n' +
    '--author="string" : the author name\n' +
    '--title="string" : (optional) the simulation title\n' +
    '--clean=true : (optional) deletes the repository directory if it exists',
    wrapTask( async () => {
      const repo = grunt.option( 'repo' );
      const author = grunt.option( 'author' );
      const title = grunt.option( 'title' );
      const clean = grunt.option( 'clean' );

      assert( grunt.option( 'repo' ), 'Requires specifying a repository name with --repo={{REPO}}' );
      assert( grunt.option( 'author' ), 'Requires specifying a author with --author={{AUTHOR}}' );

      console.log(repo);
      return;
    } ) );
```

Had this result:
```
~/github/simula-rasa$ grunt create-sim --repo=testsim --author="ns"
```

> [ 'testsim', 'testsim' ]

Instead of return "testsim" it is returning an array with two elements.  Hence the createSim call is failing.

**Comment by samreid** [comment]
I'm guessing the chipper => perennial switchover automatically adds a repo.

**Comment by samreid** [comment]
I also cannot figure out why the docs say simula-rasa uses `name` but perennial says it is `repo`.

**Comment by samreid** [comment]
I updated the directions, @jonathanolson can you please review?  Then reassign to me so I can get back to Noel on the google group.

**Comment by jonathanolson** [comment]
Looks good, although it's weird that installing grunt-cli is part of the "creating a new sim" bit, instead of the getting set up part (since it is also required for building sims)

**Comment by samreid** [comment]
We discussed further on Slack, and it seems good now.  I'll write back to Noel.
