### ISSUE TITLE
Render aria-valuetext in the a11y-view

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/chipper#660]
A lot of information is lost in the a11y-view because aria-valuetext is an inline attribute. Can we copy this attribute value and render as a DOM node in the a11y view?

This seems nice for demonstrations. There are pros and cons for development. One pro is that we will be able to see aria-valuetext as we work. But one drawback is that the a11y-view will deviate more from what is actually in the PDOM, meaning that it shouldn't be used for debugging screen reader behavior or verifying expected HTML.

I think it is worth it, but @zepumph @mbarlow12 do you think this drawback is OK?

**Comment by jessegreenberg** [comment]
Added in the above commit, this is what it looks like. Can definitely be removed or modified.

![capture](https://user-images.githubusercontent.com/6396244/37004017-45d057c4-208c-11e8-82a1-54ac6ed86c9e.PNG)

**Comment by zepumph** [comment]
I like it, especially if we think of the rendered PDOM as a visualization of the actual PDOM. Maybe keep it for now and see if there are any complaints from others?

**Comment by zepumph** [comment]
The last bullet in https://github.com/phetsims/a11y-research/issues/66 it was said that @terracoda should design the style of meta content in the pDOM copy, I wonder what she has any thoughts about this styling.

**Comment by mbarlow12** [comment]
I agree with @zepumph; it seems like the a11y-view is beginning to deviate more and more from the actual PDOM in a technical sense. However, information like this is closer to how screen readers will see the content. I think it's useful to think of the a11y-view as a visual, stylized representation of the accessible properties and elements, giving the user a slightly different perspective of the sim.

**Comment by terracoda** [comment]
@terracoda does have some thoughts on styling.
The original idea was to have:
- blue static descriptions
- green dynamic descriptions, and
- orange alerts

I like the way the inline aria-value text looks like code.  Generally speaking I think the values read out on controls (sliders, spinbuttons, comboboxes, etc) would be considered static from a design strategy perspective. The range is determined once and then the user just cycles through them.

Have we settled on a way to wrap the dynamic descriptions, so we can style them? If need be, we can use the code element for this aria-valuetext, and style code elements appropriately - a change to a mono-spaced font might be indicate the code-like nature of the content.

**Comment by terracoda** [comment]
@jessegreenberg, I think this issue is stale in light of changes recently discussed in A11y Design meeting (last week), and work done in https://github.com/phetsims/chipper/issues/684

Closing this issue.
