### ISSUE TITLE
Remove built-in support for .ogg files from audio.js plugin

### ISSUE THREAD

**Issue by jbphet** [phetsims/chipper#663]
The `audio.js` file, which is a RequireJS plugin that is responsible for the loading of audio in PhET sims, is currently written to assume if only the "stem" of an audio file is specified, .mp3 and .ogg files are available for the sound.  It then tests which formats are supported and chooses one.  This was necessary because some browsers didn't support .mp3, but this has changed for all of our targeted platforms.  All usage of .ogg files has been removed, so we should remove the code that makes this assumption about .ogg files from the `audio.js` plugin.

For more information about the remove of .ogg files, see https://github.com/phetsims/vibe/issues/19.

**Comment by jbphet** [comment]
The work for this is done.  It would probably be a good idea to have someone inspect the changes, since the audio plugin is used in all sims that have any sort of audio and, in the future, it will be used in all sims.  Assigning to @ariel-phet to decide who should review.

**Comment by ariel-phet** [comment]
Asking @jonathanolson to take a look (since it seems like this will be quick). If not please reassign back to me.

**Comment by jbphet** [comment]
There was already documentation in the constructor header, but I added some in the body of the constructor, closer to where the URL and base64 properties are used.  I also did this in SoundClip, which is a new file in the tambo repo.  I updated the code style file for my IDE, and that seemed to fix the formatting issues.

@jonathanolson - good to go?  Please close if so.

**Comment by jonathanolson** [comment]
> There was already documentation in the constructor header

Doh, I missed the note about the usage.

I guess I was expecting something that noted the object type, e.g. `Either { url: {string} } or { base64: {string} }`, but the assertions below work for figuring it out. Closing.
