### ISSUE TITLE
iframe test files broken in chipper2.0

### ISSUE THREAD

**Issue by mattpen** [phetsims/chipper#664]
The _all_iframe.html seems to be broken for the latest version of chains.  See: https://ox-dev.colorado.edu/sims/html/chains/1.16.6/chains_all_iframe.html.  It is looking for chains_all_phet.html, but the _phet is stripped out during deploy.  The only other sim that is using the _all_iframe.html is bumper on phet-server, and it seems to be working correctly https://phet.colorado.edu/sims/html/bumper/16.0.1/bumper_all_iframe.html (it has the _phet stripped out).

I asked @jonathanolson about it and he suggested that these aren't necessary for production deploys and could be filtered out of files copied to production.

@ariel-phet - are you aware of any usage of these files that would necessitate their inclusion in production deploys, or would it be ok to omit them?

**Comment by ariel-phet** [comment]
@mattpen these types of files are to the best of my knowledge only ever used for testing, and are not at all necessary for production. I suggest removing all `*.iframe.html` files from production deploys.

**Comment by mattpen** [comment]
This problem is fixed when using phet-dev.colorado.edu links, closing.
