### ISSUE TITLE
Comment type for no-mipmaps.

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#665]
@zepumph and I noticed this code for the mipmaps:

```js
    return '<!-- no mipmaps -->';
```

However, this seems like it should be `return '// no mipmaps'` because buildMipmaps.js is outputting JS code instead of HTML code.

Once my working copy is restored, I'll try building a sim with no mipmaps and see if that is problematic.

**Comment by samreid** [comment]
I short circuited buildMipmaps.js so there were no mipmaps and saw this code get outputted:

```html
<script type="text/javascript"><!-- no mipmaps --></script>
```

This is a syntax error, so I'll go with the JS style comment.

**Comment by samreid** [comment]
After my proposed fix, the code is coming out like this:

```html
<script type="text/javascript">// no mipmaps</script>
```

**Comment by samreid** [comment]
Committed and pushed, @jonathanolson can you please double check?

**Comment by jonathanolson** [comment]
I agree that it shouldn't use the HTML comment, but in general you'd want to concatenate JS strings (and a line comment would modify what it is concatenated with afterward). Could we do comments like `/* no mipmaps */`, or potentially just output a raw string?

**Comment by samreid** [comment]
I agree a block comment is better, can you please spot check the commit?

**Comment by jonathanolson** [comment]
Looks good, thanks.
