### ISSUE TITLE
Remove duplication of *A11yStrings.js xss tests

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/chipper#668]
For xss tests, something like the following is currently in *A11yStrings.js files
```js
  if ( phet.chipper.queryParameters.stringTest === 'xss') {
    for ( var key in JoistA11yStrings ) {
      JoistA11yStrings[ key ].value += /*something that triggers a problem */
    }
  }
```
This shows up many times, it would be good to remove the duplication somehow.

**Comment by zepumph** [comment]
This issue is out of date now. These strings are in main strings files.
