### ISSUE TITLE
change "var" to "const" and "let" in js/grunt

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#669]
From slack:
>Chris Malley [14:08]
Side note… For ES6+ code (files in perennial/data/es6-repos), WebStorm is flagging `'var' used instead of 'let' or 'const'`.  See for example most of the .js files in chipper/js/grunt/.

>Michael Kauzmann [15:38]
I see 156 usages of var in the grunt folder. In other repos that I was working on with es6, I just replaced them all with `let`, and then slowly added in `const` as I got to the file. Should I make an issue?

>Sam Reid [15:39]
What about replacing them all with const--will static tools tell us which ones would need to be lets?

>Jonathan Olson [15:39]
Technically, var and let are slightly different, but it probably won't come up often. When I was "porting", I went through and used const where possible
and I basically const'ed things, used let when things could change (or got flagged), and didn't run into any of the interesting edge cases

>Michael Kauzmann [15:41]
I bet the lint would tell you where const was used incorrectly.

>Michael Kauzmann [15:46]
I batch changed all to const, and there are errors "attempt to assign const" and grunt won't work. Aborting.

>Sam Reid [15:46]
does it tell you which one(s) were the problems?

>Jonathan Olson [15:47]
linting most definitely tells you every const that should change to let

>Sam Reid [15:47]
Perhaps @zepumph is saying he couldn’t run lint if chipper was busted

>Jonathan Olson [15:47]
it seems best to convert things to es8+ all at once, instead of just handling those parts?
fair enoug

>Michael Kauzmann [15:48]
Maybe I aborted too soon. The Gruntfile proper had the problem, so the grunt task couldn't be found for lint (since there was a compile error for the Gruntfile.
I'ma dig a bit deeper for a second.

>Sam Reid [15:49]
ty

**Comment by pixelzoom** [comment]
I spot-checked a few of the commits in WebStorm, and I don't see anything being flagged.  Nice work. Closing.
