### ISSUE TITLE
Fatal Error on git SHA attempt

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/chipper#67]
While testing grunt on my machine with @samreid we ran into the following error:

Fatal error: ERROR on git SHA attempt: code: ENOENT, signal: undefined with stderr:

where nothing is listed after stderr.  This happened on first run of grunt after installation with npm.  Our temporary git work-around was to comment out all content in nextDependency() and simply call done().

**Comment by pixelzoom** [comment]
@jessegreenberg what is the status of this? Is it still a problem?

**Comment by jessegreenberg** [comment]
This was never officially resolved, but it is no longer an issue for me since I received a new machine.  I don't know of anyone else experiencing this problem.  Sorry, perhaps I should have closed this a while ago.  Thanks for checking in.

**Comment by samreid** [comment]
Since we haven't seen this problem elsewhere, I recommend we close the issue.  We can reopen if it occurs again.
