### ISSUE TITLE
Document/implement what generate commands are required

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#671]
E.g. generate-config and generate-development-html are needed on dependency changes, but colors/a11y/unit-test and potentially other generation needs to happen depending on the repository.

It was noted that we should document this in the PhET Development Overview Google doc.

I thought I'd also propose that all of this should be automated, so there would be one generate command that you could run in a repo that would detect what is needed and do it.

Thoughts?

**Comment by pixelzoom** [comment]
+1 for "one generate command", -1 for more steps in PhET Development Overview.

**Comment by samreid** [comment]
Can we call the command `grunt update`?

**Comment by samreid** [comment]
We decided to leave it marked for developer-meeting so @jonathanolson will remember to implement this before the next meeting.

**Comment by jonathanolson** [comment]
Implemented in `grunt update`, leaving to mention at dev meeting.
