### ISSUE TITLE
Open Graph metadata is broken

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#677]
During a refactoring, I noticed these aren't templated properly, so the replacement isn't happening. Looks like `<meta property="og:title" content="OG_TITLE"/>` in some production sims (e.g. area-model).

Looks like the commit https://github.com/phetsims/chipper/commit/3802475832d04bdc99031f21f9e828c8d5dfcdaa#diff-5080177e1b1988f785ccac685d896de0 missed including these as template variables, so things have been broken in master since October 2016.

@ariel-phet this will be fixed in master in my refactoring. This may be a good candidate for a maintenance release (when I'm working on the maintenance release process). Thoughts?

**Comment by jonathanolson** [comment]
Notably, this means thumbnails may not show up when sims are shared in facebook, etc.

**Comment by ariel-phet** [comment]
@jonathanolson yes, seems like a good candidate for maintenance release

**Comment by zepumph** [comment]
Trying out the new label. Is this a good application?

**Comment by jonathanolson** [comment]
> Trying out the new label. Is this a good application?

Perfect, thanks!

**Comment by jonathanolson** [comment]
Maintenance deploys finished.
