### ISSUE TITLE
XHTML builds and ePub compatibility

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#678]
See https://github.com/phetsims/special-ops/issues/105 for more information.

**Comment by jonathanolson** [comment]
Implemented in master for now (since it cleans up some of how we generate normal HTML). Also fixes https://github.com/phetsims/chipper/issues/677 (since I noticed that bug while doing this work).

@ariel-phet, should this be looked over for code review?

**Comment by jonathanolson** [comment]
We'll also want to figure out ways to ideally generate locale-specific HTMLs (since they are now really small, the main payload is in the JS file) and other considerations that I'm not worrying about for the prototype.

**Comment by samreid** [comment]
Can you please add documentation to the --help about how to specify xhtml?  The build --help currently reads:

```
build  Builds the repository. Depending on the     
       repository type                             
       (runnable/wrapper/standalone), the result   
       may vary.                                   
       --uglify=false - Disables uglification, so  
       the built file will include (essentially)   
       concatenated source files.                  
       --mangle=false - During uglification, it    
       will not "mangle" variable names (where they
       get renamed to short constants to reduce    
       file size.                                  
       Runnable build options:                     
       --instrument - Builds a runnable with code  
       coverage tooling inside. See                
       phet-info/docs/code-coverage.md for more    
       information                                 
       --brands={{BRANDS} - Can be * (build all    
       supported brands), or a comma-separated list
       of brand names. Will fall back to using     
                            build-local.json's     
       brands (or adapted-from-phet if that does   
       not exist)                                  
       --allHTML - If provided, will include the   
       _all.html file (if it would not otherwise be
       built, e.g. phet brand)                     
       --debugHTML - Includes a _debug.html version
       that includes assertions enabled (and,      
       depending on the brand, may be un-uglified) 
       --locales={{LOCALES}} - Can be * (build all 
       available locales, "en" and everything in   
       babel), or a comma-separated list of locales
```

**Comment by jonathanolson** [comment]
Added the documentation as requested above.

**Comment by jonathanolson** [comment]
Also @ariel-phet, in addition to deciding about a potential review, should we have locale-specific XHTML files also? Or is the all-locale version currently used sufficient?

**Comment by ariel-phet** [comment]
@jonathanolson these are all good questions. I am going to mark for dev meeting since it seems various expertise might be good to weigh in here.

**Comment by samreid** [comment]
Consensus: Developers can use `?locale` query parameter for the all xhtml.  We do not need to create language-specific xhtml files.  I'll take a review.

**Comment by samreid** [comment]
I did `~/github/faradays-law$ grunt --brands=phet` and uploaded the XHTML to https://validator.w3.org/check and saw:

![image](https://user-images.githubusercontent.com/679486/44664986-0b24fd80-a9d2-11e8-9ed3-0aa6405b7ec8.png)

I tried converting to EPUB following these steps: https://stackoverflow.com/a/4404159 and opening in iBooks, but nothing happened.

I tried `~/github/faradays-law/build/phet$ ~/Downloads/pandoc-2.2.3.2/bin/pandoc xhtml/faradays-law_all_phet.html -o mybook.epub`  and it created an epub that loaded in iBooks, but it looked like this:

![image](https://user-images.githubusercontent.com/679486/44666393-876d1000-a9d5-11e8-90d6-df81432c083f.png)

@jonathanolson any suggestions how we can test the XHTML in an EPUB?

**Comment by samreid** [comment]
I reviewed all of the changes in https://github.com/phetsims/chipper/commit/9f6172d00a9150bad952f6357742c95f4fd211d9 and https://github.com/phetsims/chipper/commit/ba6586b061679b346b169c9d5b811406c1c24b36 and everything looks to be in good shape.  I think we should figure out how to test our XHTML in EPUB context, but I'm not sure how to do so (see prior comment).  Perhaps @jonathanolson has a suggestion about how to do that.

**Comment by jonathanolson** [comment]
> I think we should figure out how to test our XHTML in EPUB context

I really don't know how to embed it either. Our partner did not specify how to embed content, and I think they have their own process. @ariel-phet should I look into creating ePubs of simulations?

**Comment by ariel-phet** [comment]
@jonathanolson @samreid at the moment there is only one client using this functionality, and they appear to be doing custom things with the deliverable in terms of embedding. For the moment, the client seems happy, I think we will punt on further work at the moment since the use case is currently small. I don't think we yet need to look into creating ePubs. Closing.
