### ISSUE TITLE
Can/should we always create the _debug.html?

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#679]
In https://github.com/phetsims/chipper/issues/674 @zepumph and I realized we need to always create the debug HTML for PhET-iO.  We tested and it does not appear to make the build take longer.  Currently we have the logic:

```
debugHTML || brand === 'phet-io' // Gruntfile.js line 177
```

and we were wondering if we can/should simplify this by always creating debug builds. @jonathanolson can you comment?

**Comment by jonathanolson** [comment]
Yup, additional minification is NOT done for the phet brand to produce the _debug.html. It basically just combines outputs into another file.

I'm totally fine with having this always-enabled. Assigning to developer meeting to determine if everyone else is fine with having _debug.html builds generated for every build.

**Comment by zepumph** [comment]
I would be fine with it, when all is said and done it would simplify the build process code (very minorly), and make all build artifacts more consistent, @samreid also noted that we timed the build and found no obvious change when building the debug version vs not, testing about 3 times. 

I can't think of any negatives to it, but I also see that all the positives are not very substantial. All in all that makes for not a ton of conviction as I vote to make it always-enabled for phet brand (does that mean all brands?).

**Comment by samreid** [comment]
@jonathanolson will enable building debug html by default, we will try it out and see if any problems come up.

**Comment by ariel-phet** [comment]
@jonathanolson will flip the switch

**Comment by ariel-phet** [comment]
@samreid will take for quick test-drive when done

**Comment by samreid** [comment]
Unassigning to keep my to-do list clear, please assign to me when ready for testing.

**Comment by samreid** [comment]
I tested by running grunt for faraday's law, then visually inspected faradays-law/build/phet/faradays-law_all_phet_debug.html and it looked good.

This code:

```js
    // enables basic assertions
    var enableBasicAssertions = enableAllAssertions ||
                                ( !phet.chipper.isProduction && phet.chipper.queryParameters.ea ) ||
                                phet.chipper.isDebugBuild;
```

combined with 
```js
window.phet.chipper.isDebugBuild = true;
```

means assertions are always enabled for this, even without a query parameter.

I inspected faradays-law/build/phet-io/faradays-law_all_phet-io_debug.html and found it was minimized, but assertions were not stripped.  And it also has `isDebugBuild=true`.

I checked the documentation in phet-io-wrappers/index/index.html and it showed how to launch the debug version, which uses these constants

```js
  var FILENAME = SIMULATION_NAME + '_all_phet-io.html';
  var FILENAME_DEBUG = SIMULATION_NAME + '_all_phet-io_debug.html';
```

So it seems everything checks out, nice work!  Closing.
