### ISSUE TITLE
Delete getVersionForBrand stub

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#683]
In `getVersionForBrand.js`, @samreid and I see this todo, promoting to an issue:

` TODO: remove this stub once we merge to master (joist/preloads have usage)`

**Comment by ariel-phet** [comment]
Requesting a volunteer....

**Comment by jonathanolson** [comment]
Looks like a duplicate of https://github.com/phetsims/chipper/issues/697 which I fixed earlier this week. Closing.
