### ISSUE TITLE
A few enhancements to the a11y-view

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/chipper#684]
Discussed 6/15/18, a few enhancements to the a11y view would make it easier to present accessibility content to others:
- rewrite intro paragraph (@terracoda)
- Remove brackets and `aria-valuetext` label in front of copy in view
- Figure out why some inputs to to  very small width once value changes (like sliders in john-travoltage-a11y-view)

Assigning to @terracoda and myself.

**Comment by jessegreenberg** [comment]
Second and third points are done and a11y-views have been regenerated. @terracoda over to you for the first bullet. Can you please reassign to me when the new content is ready?

**Comment by terracoda** [comment]
Thanks @jessegreenberg, I just started working on point one using BASE as an example and just noticed that the A11y View document starts with an H3 instead of an H1.

I am not sure when the heading structure disappeared, but we shoudl clean that up, too, while we are at it.

I've archived the old document and am creating a new to work in here:
https://docs.google.com/document/d/1xsucsdRs-Oj1NtYnT4XwiQeuvKxsHEA3PRr6LPLfsj0/edit#

I'll comment again in the issue when I am done.

**Comment by terracoda** [comment]
Ok. I have updated the content and the structure in the design document:
https://docs.google.com/document/d/1xsucsdRs-Oj1NtYnT4XwiQeuvKxsHEA3PRr6LPLfsj0/edit#

**Comment by terracoda** [comment]
@jessegreenberg, do you think my changes are acceptable for implementation, or  would you like me to run them by @emily-phet first?

**Comment by jessegreenberg** [comment]
@terracoda these are quick changes I went ahead and made them. Can you please review? Here is a link to phettest for convenience.
http://phettest.colorado.edu/balloons-and-static-electricity/balloons-and-static-electricity_a11y_view.html

**Comment by terracoda** [comment]
Thanks @jessegreenberg! A bit verbose, but a good first draft to share with the team. I'll make a stab at cutting the content down once everyone gets a chance to read it.

**Comment by terracoda** [comment]
@emily-phet, I can shorten the text, but wanted some feedback before doing that.

**Comment by terracoda** [comment]
Reviewed at A11y meeting. @emily-phet to review content in google doc. @emily-phet, please open a new issue if you want to make any content changes. I am going to close this issue as it has been address.
