### ISSUE TITLE
Tooling or IDEs changing package.json?

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#688]
The following commits look suspicious:

- https://github.com/phetsims/chipper/commit/16cbe7bbaa20a013dd878f60431ed2deaa19f671#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
- https://github.com/phetsims/chipper/commit/910a20f5a91f6252e7bf2aa168e7457884ecb96c#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
- https://github.com/phetsims/chipper/commit/fe3864e45db9f70439770c5821ccf0639cb1e15b#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
- https://github.com/phetsims/chipper/commit/8c3d8a0cce84c4c8e21e39d0fb8da2653368d894#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

@Denz1994 do you know if something is silently changing package.json and committing?

**Comment by Denz1994** [comment]
I can't figure out why this would be happening. It would make sense to review the change logs before committing an unintended change in chipper. Perhaps this has to do with ```npm update```? I will investigate on next set of commits.

**Comment by Denz1994** [comment]
I've haven't had any of these unintentional commits lately. Either way, these changes can be viewed prior to committing (as seen in the past) and should be ignored before committing.
