### ISSUE TITLE
add color option to phet.log

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#690]
All log messages are currently green '#009900'.   Since phet.log doesn't have levels, it would be nice to be able to sometimes emphasize a log message using color.   We discussed this on Slack, and the consensus was to use options to specify the color.

Proposed implementation in initialize-globals.js:

```js
    // Add a log function that displays messages to the console. Examples:
    // phet.log && phet.log( 'You win!' );
    // phet.log && phet.log( 'You lose', { color: 'red' } );
    if ( window.phet.chipper.queryParameters.log ) {
      window.phet.log = function( message, options ) {
        options = _.extend( {
          color: '#009900' // green
        }, options );
        console.log( '%c' + message, 'color: ' + options.color ); // green
      };
    }
```

**Comment by pixelzoom** [comment]
Examples in Chrome console:

![screenshot_690](https://user-images.githubusercontent.com/3046552/42539472-6ef85590-8458-11e8-9fd5-5c5cec6ed748.png)

@zepumph was randomly selected to review.

**Comment by zepumph** [comment]
looks great thanks.
