### ISSUE TITLE
evaluate how ES6 is working out

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#691]
From https://github.com/phetsims/chipper/issues/551#issuecomment-404606004:

> • report back in a future dev meeting about how ES6 is going

**Comment by samreid** [comment]
While working on https://github.com/phetsims/wave-interference/issues/78 I noticed that `inherit` can apparently not be used to extend a `class` even though it is a function.

![image](https://user-images.githubusercontent.com/679486/42720732-361ed3e0-86ea-11e8-9694-b75de8334f10.png)

This error was: `Uncaught TypeError: Class constructor EmitterNode cannot be invoked without 'new'`

I also tried `EmitterNode.constructor.call(` and received `Uncaught SyntaxError: Unexpected identifier`.

Maybe someone on the team will find a way around this, but until then it seems we cannot extend `class` with `inherit.js`

**Comment by samreid** [comment]
When using the `constructor` feature, IDEA no longer autocompletes `/*@constructor*/` when adding JSDoc.  It seems redundant to repeat constructor twice:

```js
    /**
     * @param {Node} content
     * @param {Object} [options]
     * @constructor
     */
    constructor( content, options ) {
```

So I recommend we remove the `/*@constructor` for cases like this, and will do so in https://github.com/phetsims/wave-interference/issues/78

**Comment by samreid** [comment]
Meeting discussion:

* es6-paths already deleted
* Set IDE to ES6
* disable inspections based on developer preference
* honor system to keep ES6 out of common code.

@jonathanolson says sublime already deals with ES6 nicely

**Comment by samreid** [comment]
Should we use function defaults instead of options?  For instance:

```js
    constructor( options ) {

      options = _.extend( {

        // This model supports one or two sources.  If the sources are initially separated, there are two sources
        numberOfSources: 1,

        // Initial amplitude, between 0-10
        initialAmplitude: 8
      }, options );
```

vs

```js
    /**
     * @param {number} [numberOfSources]
     * @param {number} [initialAmplitude]
     */
    constructor(
      // This model supports one or two sources.  If the sources are initially separated, there are two sources
      numberOfSources = 1,
      // Initial amplitude, between 0-10
      initialAmplitude = 8 ) {
```

IDEA wants to collapse the blank lines in the lower version.

**Comment by jonathanolson** [comment]
Above it seems really weird to document the parameters NOT in the JSDoc. Also this isn't scalable, since if you have 20 options...

**Comment by chrisklus** [comment]
7-26-18 dev meeting: 
* Use new features on new code, no plans to go back through old code
* Honor system for keeping ES6 out of common code

**Comment by samreid** [comment]
I found that profiling a babel-transpiled sim is different than profiling a non-babel sim.  It looks like babel is packing functions into key/value objects:

![image](https://user-images.githubusercontent.com/679486/43486218-713e1afa-94d0-11e8-8cd4-cf0f2fcb677e.png)

It looks like functions from a class prototype which are coded like this:
```js
    dampVerticalTemporal( i, di, matrix0, matrix2 ) {
      for ( let j = 0; j < this.height; j++ ) {
        matrix0.set( i, j, matrix2.get( i + di, j ) );
      }
    }
```
Get transpiled like this:

```js
{
  key: "decayVertical",
    value: function(i0, sign, width) {
    for (var j = 0; j < this.height; j++) for (var step = 0; step < width; step++) {
      var distFromDampBoundary = width - step, damp = this.getDamp(distFromDampBoundary), i = i0 + step * sign;
      this.setCurrentValue(i, j, this.getCurrentValue(i, j) * damp), this.setLastValue(i, j, this.getLastValue(i, j) * damp);
    }
  }
},
```

I'm not sure whether this has any broader implications, but I wanted to alert other developers about this.

**Comment by samreid** [comment]
From slack:

Sam Reid [2:51 PM]
Babel transpile has implications for profiling, I took some notes here: https://github.com/phetsims/chipper/issues/691#issuecomment-409362885

Jonathan Olson [2:52 PM]
hmm, interesting. I wonder if there are flags we can provide that would give us better debugging information?

Sam Reid [2:52 PM]
Maybe something to name those anonymous functions?
key: “decayVertical”,
   value: function(i0, sign, width) {

would become

 key: “decayVertical”,
   value: function decayVertical(i0, sign, width) {

Jonathan Olson [2:53 PM]
I know it was decided a while ago that we never wanted to use source maps, but it would help in this case

Sam Reid [2:53 PM]
Is it easy to generate source maps in the babel step?
Or will that obfuscate the profiling anyways?

Jonathan Olson [2:55 PM]
may slightly obfuscate profiling results, but Chrome might be able to show both with/without source maps. I’m not sure, I haven’t used them much
and I believe all of the tooling we use can generate source maps

**Comment by samreid** [comment]
From slack:

Jesse Greenberg [12:52 PM]
Running a sim with es6 on an iPad2 I am seeing "Unexpected keyword 'const'. Const declarations are not supported in strict mode."


Jesse Greenberg [1:00 PM]
Built version is running great. I had thought that IE11 was the only platform that could no longer run RequireJS but I was mistaken.

Michael Kauzmann [1:52 PM]
Is there a master list of platform/environments that no longer support requirejs?
should there be?

Jesse Greenberg [2:31 PM]
Was using iOS 9.3.5, that isn't even listed on caniuse anymore https://caniuse.com/#feat=const
Looks like it was when we were first looking into this in https://github.com/phetsims/chipper/issues/551#issue-211171759. Did QA do any es6 testing with RequireJS? Or just built versions?

**Comment by pixelzoom** [comment]
Before I go creating ES6+ code...   What is the resolution to https://github.com/phetsims/chipper/issues/691#issuecomment-409803686?  Are we going to proceed and live with the inability to test in requirejs mode on iOS 9?

**Comment by samreid** [comment]
It would probably be best to build before testing on iPad 2 to eliminate memory and performance red herrings anyways.

**Comment by pixelzoom** [comment]
I agree for memory and performance testing.  But for general iterative debugging, having to build in order to test will be super inconvenient, and will slow the iterative process considerably.   And as iOS9 ages, it has required such iterative testing (based on recent experience with Equality Explorer.)

**Comment by samreid** [comment]
To clarify on the above point, builds using `time grunt --lint=false` of Equality Explorer on my machine are currently taking around 33 seconds:

0m27.330s
0m33.841s
0m26.006s

I expect on other machines this could be around a minute.  So if you build this 60 times per day, it could cost an hour or so plus overhead from losing train of thought, etc.

**Comment by jonathanolson** [comment]
For memory-limited or slower device (like iPads), I've done builds for testing anyways, so this wouldn't affect me.

**Comment by ariel-phet** [comment]
This ship has sailed, we are using ES6+ so we will close this issue and open up ES6 specific issues
