### ISSUE TITLE
allow dev deploys from release branches

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#692]
After chatting with @jonathanolson, my understanding is that it's currently not possible to do a dev deploy from a release branch.   This is problematic, since I have historically published a dev version to review fixes/changes that are done in a release branch.  Yes, I could publish an RC version to do this, but that's not the purpose of an RC version, and could be confusing when maintainers look at the version history.  

Assigning to @ariel-phet to prioritize and assign.

**Comment by pixelzoom** [comment]
An RC is a "release candidate", a candidate that you're actually considering releasing publicly.  When I have a specific issue to test or potential solution to run past someone, it is not at all being considered for release -- it is a dev version that is being used to demonstrate something that may or may not work out.

**Comment by pixelzoom** [comment]
Labeling with meeting:developer for other devs to weigh in.

**Comment by jessegreenberg** [comment]
I agree we should allow dev deploys from release branches.

**Comment by jonathanolson** [comment]
Would version auto-incrementing just up the test number every time? So if you have `1.4.0-dev.1` and then do an RC it would be `1.4.0-rc.2` (even though there was never an rc.1)?

**Comment by pixelzoom** [comment]
Numbering is indeed the natty issue.  It would be ideal to keep the dev and rc numbering separate.

**Comment by samreid** [comment]
@jonathanolson points out you could use a "one-off" deployment process to handle this.  That would involve creating a new branch from the production branch though.

After discussion, we would like to use `grunt rc` for this.  We can communicate with design team members about the fact that it is a dev version masquerading as an RC version.  We can keep notes about this using `grunt --message="..."` which will appear in the commit message.

**Comment by samreid** [comment]
Reassigned to @jessegreenberg to review.  @jessegreenberg after you review, you can close if it all seems OK.

**Comment by pixelzoom** [comment]
I skimmed this issue, don't see anything left to do, and it's been "assigned for review" for quite awhile.  So I'm going to close it.
