### ISSUE TITLE
Chipper has 40 TODOs

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#695]
While working on https://github.com/phetsims/phet-io-wrappers/issues/116, I noticed that chipper has 40 TODOs (22 in the js/ directory).  Thanks to https://github.com/phetsims/tasks/issues/942 here is a plot of Lines of Code and TODOs x 100 (in js/) vs time:

![image](https://user-images.githubusercontent.com/679486/43488210-297037b6-94d6-11e8-8f19-1106236cab23.png)

Assigned to @ariel-phet so he is aware of this problem and to evaluate/prioritize/assign.  Other common code repos likely have similar problems, aside from joist which is somewhat protected by https://github.com/phetsims/joist/issues/380

**Comment by ariel-phet** [comment]
To me it will depends a fair bit on the nature of the TODO's

Marking for quick discussion at dev meeting (where I will likely assign a lucky volunteer to do a quick review who's name is not @jonathanolson)

**Comment by ariel-phet** [comment]
@mattpen will do a 1 hour review and look at the nature of these. If he feels any are pressing and deserve an issue he will create a github issue and assign me.

**Comment by mattpen** [comment]
I pared this down to 25 usages in code that still need to be addressed.  There are 8 comments regarding improving lint rules, and the rest concern missing documentation or low-priority/no-priority refactoring of code.  The remainder were either handled or have open issues attached.
