### ISSUE TITLE
Remove getVersionForBrand.js

### ISSUE THREAD

**Issue by mattpen** [phetsims/chipper#697]
In getVersionForBrand.js there is the following comment:

```/**
 * Brand is now not included in the version. Used to handle https://github.com/phetsims/chipper/issues/507
 * TODO: remove this stub once we merge to master (joist/preloads have usage)
 */
```

It appears that whatever was needed was merged to master and that this should be removed.  The function is never called (at least that I can determine), but this file is still included in preloads in chipper/build.json and in every instance of {{sim-name}}/{{sim-name}}_en.html.

It seems to me it can be removed, but can @jonathanolson @samreid or @jbphet  please double check?

Opened as part of #695.

**Comment by jbphet** [comment]
I'm seeing a usage in `packageJSON.js` in joist, but I think that can and should be removed since it would appear that the statement has no effect.

**Comment by jonathanolson** [comment]
Implemented, closing.
