### ISSUE TITLE
how to `grunt published-README` for 1.0 release branch? 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#698]
I recently noticed that `grunt published-README` is not occurring for the 1.0 release branch.  See for example https://github.com/phetsims/gene-expression-essentials/issues/122#issuecomment-407152021, https://github.com/phetsims/area-model-common/issues/165, https://github.com/phetsims/circuit-construction-kit-dc/issues/174. 

In https://github.com/phetsims/gene-expression-essentials/issues/122#issuecomment-407152021, @jbphet asked:
> it there a general issue in chipper or perennial to make the grunt task automatically update the README.md for the first RC branch too? I looked around but didn't see such an issue.

Labeling for developer meeting to discuss whether this should be automatic.

**Comment by jonathanolson** [comment]
This is something that I hadn't thought of during the chipper 2.0 work, but @pixelzoom's argument for the correctness of the release branch resonates with me. I thought I had an issue assigned to me to update this (which I can't find), but I'd like to have this generation done during production deploys.

**Comment by jonathanolson** [comment]
I'll do the version bump commit first, THEN readme, then the other commits.

I'll update the master checklist.

**Comment by ariel-phet** [comment]
When @jonathanolson has done this, alert me and I will update the master checklist

**Comment by jonathanolson** [comment]
Slight complication in that the generation task name was renamed in https://github.com/phetsims/chipper/commit/9026d37e0757eb0d43ebf444c6d86296b786f214. It will try `grunt published-README` first, then `generate-published-README`.

**Comment by jonathanolson** [comment]
Also as part of this issue, I'll run it through all of the release branches and update the READMEs.

**Comment by jonathanolson** [comment]
Will be running this temporary script:
```js
const checkoutTarget = require( './js/common/checkoutTarget' );
const execute = require( './js/common/execute' );
const gitAdd = require( './js/common/gitAdd' );
const gitCommit = require( './js/common/gitCommit' );
const gitPush = require( './js/common/gitPush' );
const gruntCommand = require( './js/common/gruntCommand' );
const ReleaseBranch = require( './js/common/ReleaseBranch' );

( async () => {
  const branches = await ReleaseBranch.getMaintenanceBranches();
  for ( let branch of branches ) {
    await checkoutTarget( branch.repo, branch.branch, true );

    try {
      await execute( gruntCommand, [ 'published-README' ], `../${branch.repo}` );
    } catch ( e ) {
      try {
        await execute( gruntCommand, [ 'generate-published-README' ], `../${branch.repo}` );
      }
      catch ( e ) {
        console.log( `CANNOT PUBLISH README: ${branch.repo} ${branch.branch}` );
      }
    }
    await gitAdd( branch.repo, 'README.md' );
    try {
      await gitCommit( branch.repo, `Updating published README on release branch, see https://github.com/phetsims/chipper/issues/698` );
      await gitPush( branch.repo, branch.branch );
    }
    catch ( e ) {
      console.log( 'Production README is already up-to-date' );
    }
  }
} )().then( () => console.log( 'done' ) );
```

**Comment by ariel-phet** [comment]
Changed in checklists. Closing
