### ISSUE TITLE
Should we add sourcemaps?

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#701]
From #691 

From slack:

Sam Reid [2:51 PM]
Babel transpile has implications for profiling, I took some notes here: https://github.com/phetsims/chipper/issues/691#issuecomment-409362885

Jonathan Olson [2:52 PM]
hmm, interesting. I wonder if there are flags we can provide that would give us better debugging information?

Sam Reid [2:52 PM]
Maybe something to name those anonymous functions?
key: “decayVertical”,
   value: function(i0, sign, width) {

would become

 key: “decayVertical”,
   value: function decayVertical(i0, sign, width) {

Jonathan Olson [2:53 PM]
I know it was decided a while ago that we never wanted to use source maps, but it would help in this case

Sam Reid [2:53 PM]
Is it easy to generate source maps in the babel step?
Or will that obfuscate the profiling anyways?

Jonathan Olson [2:55 PM]
may slightly obfuscate profiling results, but Chrome might be able to show both with/without source maps. I’m not sure, I haven’t used them much
and I believe all of the tooling we use can generate source maps

**Comment by jonathanolson** [comment]
Should we add this to https://github.com/phetsims/chipper/issues/602?

**Comment by samreid** [comment]
I added this discussion to #602, closing.
