### ISSUE TITLE
More optimized encoding for assets

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#705]
Currently we use the base64 encoding for assets (images, audio, etc.) since it was simple (and we need that form as output. It should be possible to use more space-efficient encodings, that then can be decoded and converted to the base64 during runtime.

The downsides are that this might slow down the launch of a sim (even if it makes the download faster), and it's unclear how much we might gain for actual download speed (since usually gzip or another form of compression is used for the actual transfer, which may be reducing some of the base64 "bloat").

Is this something that should be investigated?

**Comment by samreid** [comment]
If we can get Apache doing the gzip itself in https://github.com/phetsims/website/issues/482, then it would not help (and would actually hurt) to change from base64 encoding.

**Comment by pixelzoom** [comment]
8/23/18 dev meeting consensus: Do nothing, focus on Apache gzip.
