### ISSUE TITLE
bad URL for phet-io deploy

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#707]
```
grunt rc --repo=molarity --brands=phet,phet-io --branch=1.4
...
Deployed: https://phet-dev.colorado.edu/html/molarity/1.4.2-rc.1/phet/molarity_en_phet.html
Deployed: https://phet-dev.colorado.edu/html/molarity/1.4.2-rc.1/phet-io/wrappers/index
Please wait for the build-server to complete the deployment, and then test!

Done.
```

The phet-io path here does not exist, https://phet-dev.colorado.edu/html/molarity/1.4.2-rc.1/phet-io/wrappers/index.  Perhaps this should be https://phet-dev.colorado.edu/html/molarity/1.4.2-rc.1/phet-io ?

I didn't check whether the same problem exists for `grunt dev` and `grunt production`.

**Comment by jonathanolson** [comment]
Was handled in https://github.com/phetsims/perennial/commit/2d62f5413dfa1a9c03dfab978a5569b0d261b039 for production.

**Comment by jonathanolson** [comment]
It's not auto-tagging, but https://github.com/phetsims/perennial/commit/fcddb00fad47d7a025a9c49f4c013769a0fe90ca handles the other deployment styles.

@pixelzoom can you verify or close?

**Comment by pixelzoom** [comment]
I did a phet-io production deploy of molarity and the paths looked correct. I trust that they are also correct for rc and dev deploys.  Closing.
