### ISSUE TITLE
Sims fail to launch about 1/2 the time in RequireJS mode on iOS 8.0.2

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#71]
Sims fail to launch in RequireJS mode on iOS 8.0.2.  Noticed this for ESPB, it never gets past the splash screen.  Cannot tether until the new OSX is out (or could use a beta).

Current workaround: try launching your sim multiple times.  Or use a compiled version (I haven't seen the issue there yet).

**Comment by pixelzoom** [comment]
@samreid is this still an issue?

**Comment by samreid** [comment]
I haven't seen this problem for a while, will reopen if rediscovered.
