### ISSUE TITLE
add 'fuzz' query parameter

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#714]
10/11/18 dev meeting:

Add 'fuzz' query parameter (as a convenience) to initialize-globals.js.  

Initially, this will be equivalent to `?fuzzMouse&fuzzTouch`.   We'll consider adding `fuzzBoard` later.  

Let QA and other devs know when this is done.

Assigned to @jonathanolson, with @Denz1994 to ride along.

**Comment by Denz1994** [comment]
The above commits include changes to most usages of `fuzzMouse` and `fuzzTouch` to instead use `fuzz`. The new `fuzz` query parameter fires touch and mouse events. These changes were made along with @jonathanolson and Bayes CT was restarted to apply the above changes.

**Comment by Denz1994** [comment]
CT will run automated testing after these changes. If there are any issues related to these commits that come up we will reopen. Closing.
