### ISSUE TITLE
Add a query parameter to double the strings for i18n testing

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#72]
Something I often do during testing in change string.js to double the length of each string, for instance the phrase "Reset All" would become "Reset All:Reset All".  This is a good rule of thumb for handling longer strings for when the sim is translated.  This also tests to see that all strings have been translated-- if you see any strings that appear as a single, they have not been loaded dynamically.  We could empower our QA team to do this kind of testing as well if we add support a query parameter that will automatically double the strings.  The query parameter should work whether in the minified mode or in the requirejs mode.

**Comment by samreid** [comment]
@aaronsamuel137 do you have time to investigate this?

**Comment by aaronsamuel137** [comment]
OK I've given this a shot. It seems to work both in requirejs mode and after being built. And I've eliminated some of the duplicate code. Assigning to @samreid for review.

**Comment by samreid** [comment]
@aaronsamuel137 this looks pretty great, nice work!  In my review, I noticed that mapString is defined as a global function (both in mapString.js and when inlined into the html), is that correct?  If true, could it be either made non-global (preferable) or namespaced under phet.chipper or equivalent?

**Comment by aaronsamuel137** [comment]
Good point. I have made it non-global in require-js mode and namespaced it under window.phet.chipper.mapStrings in build mode. Assigning to @samreid for review.

**Comment by samreid** [comment]
Thanks, this is good.  The other thing I noticed is that it looks like it is using Function.toString in order to get the source code into the html in this line:

```js
phetStringsCode += 'window.phet.chipper.mapString = ' + mapString.toString();
```
Since I am unfamiliar with Function.toString, I'm not sure if the behavior is normalized across platforms, and guaranteed not to change in the future.  Is there a specification that guarantees Function.toString will be safe everywhere for a long time?  Or is there another way to get the source code into the html?

**Comment by samreid** [comment]
MDN report Function.toString is a standard and supplied on all of the platforms they report for.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/toString

Perhaps this is OK?  But I'm curious if you can think of other ways to get the source to the RequireJS mode and to the HTML without duplicating it.  If not, then we can stick with Function.toString.

**Comment by jonathanolson** [comment]
It sounds like it makes sense to preload that file instead of toString()ing it?

**Comment by samreid** [comment]
Perhaps add it to initializeGlobals.js?

**Comment by samreid** [comment]
moving it to initializeGlobals sounds like a good plan to me, thanks @jonathanolson.

**Comment by aaronsamuel137** [comment]
I've moved to mapString to initialize-globals, which eliminates the need to toString(). Assigning to @samreid for review.

**Comment by pixelzoom** [comment]
One of the options for the `stringTest` query parameter is `empty`, which sets all strings to ''.  I understand the described use of this - to identify strings that haven't been localized. But in practice it is causing runtime errors (specifically with layout code), and assertion failures when combined with the `ea` query parameter. To demonstrate the failures, try it with states-of-matter.  So I would dump that particular option, since something like 'stringTest=X' serves the same purpose.  Or if you must have this option,  change it to `space` and use a space (%20) instead of the empty string.

**Comment by samreid** [comment]
I am already getting ?ea exceptions in states of matter basics without a stringTest query parameter:

```js
message: "Attempted to removeChild with a node that was not a child."
```

When I tried FAMB with ?ea&stringTest=empty and didn't see any layout assertions.  Still, I think this feature can be emulated with ?stringTest=%20 so I am OK to drop stringTest=empty.

**Comment by samreid** [comment]
I removed stringTest=empty above, and added documentation.  I'm looking for a better name than `mapString` for this function.  If anyone has ideas, please let me know.

**Comment by jbphet** [comment]
The assertion that you were seeing for SOM is unrelated to strings, see https://github.com/phetsims/states-of-matter/issues/52.  The issue should now be resolved.

**Comment by pixelzoom** [comment]
@samreid wrote:
> When I tried FAMB with ?ea&stringTest=empty and didn't see any layout assertions. 

You wouldn't see them with 'ea', since the sim was failing immediately on startup (due to a sim-specific bug apparently).  Layout asserts were occurring in the 3rd screen - they were complaining that some aspect of scenery.Rectangle was NaN.

**Comment by samreid** [comment]
I finished looking at mapString and its usage sites, and everything seems good. Nice work @aaronsamuel137, closing.
