### ISSUE TITLE
Maintenance release to deal with phetmarks

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#720]
During https://github.com/phetsims/special-ops/issues/122, @jonathanolson and I ran into this case:

```
Maintenance task failed:
Error: Failure with production deploy for beers-law-lab to 1.6-phetio: Error: grunt lint-all clean build --brand=phet-io --locales=en --debugHTML in ../beers-law-lab failed with exit code 3 and stdout:
Running "eslint:allFiles" (eslint) task

/Users/samreid/github/phetmarks/js/phetmarks.js
  50:3  error  Parsing error: The keyword 'const' is reserved

✖ 1 problem (1 error, 0 warnings)

Warning: Task "eslint:allFiles" failed. Use --force to continue.

Aborted due to warnings.

```

This was caused by https://github.com/phetsims/phetmarks/commit/5cedf6bb5134f5ff6c49f6bc7e156e76b3a95fef as part of https://github.com/phetsims/phet-io/issues/1404

Our two possibilities are:

1. Make phetmarks version SHAs with the simulation, so it doesn't accidentally pick up new changes.  We decided we would like to do this in a previous dev meeting.  This would likely require a batch maintenance release to make it work for all sims.
2. Perform a maintenance release that changes chipper to omit phetmarks from the list of linted files.

We could also do both.  Another alternative (maybe short term solution), would be to roll back incompatible changes in phetmarks, and (for now), prevent new breaking commits in phetmarks by policy.

Tagging for https://github.com/phetsims/perennial/issues/110 as a possible upcoming maintenance release.

**Comment by samreid** [comment]
In discussion, we concluded it would be nice to iterate through sims, automatically pluck a compatible phetmarks SHA and add it to the dependencies.json.

**Comment by samreid** [comment]
@zepumph volunteered to help out, thanks!

**Comment by jonathanolson** [comment]
This went out with the just-completed maintenance release, closing.
