### ISSUE TITLE
uglify-es unmaintained

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#721]
The release of uglify-es (the support for ES6) has been unmaintained for a number of months, and development looks like it has switched to https://github.com/terser-js/terser (see https://github.com/mishoo/UglifyJS2/issues/3156#issuecomment-421509930).

Is it worth proactively switching, or waiting until we need some sort of upgrade?

**Comment by samreid** [comment]
I'd recommend spending initial time (1-2 hours)? investigating a proactive switch--if the API is compatible and transition is easy, then great.  If we run into severe issues or compatibility issues we can re-evaluate.

**Comment by jonathanolson** [comment]
> if the API is compatible 

From the documentation:

> terser is a fork of uglify-es that retains API and CLI compatibility with uglify-es and uglify-js@3.

So it seems like it should be fairly straightforward.

**Comment by samreid** [comment]
@zepumph volunteered to investigate this

**Comment by jonathanolson** [comment]
Was easy to do while investigating uglification times. Handled on the modules branch, closing.
