### ISSUE TITLE
Preloads should run through babel

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#723]
In https://github.com/phetsims/joist/issues/539 a `const` sneaked into a preload file.  https://github.com/phetsims/joist/issues/539#issuecomment-443385486 suggested adding a lint rule to make sure that preloads remain ES5, but it may be better to add a babel phase to the preloads so we can use ES6 there, for consistency.  Self assigning and adding @jonathanolson in case he has thoughts or recommendations, or in case he gets to it first.

**Comment by jonathanolson** [comment]
This sounds fine to me, but will definitely need automated testing.

**Comment by samreid** [comment]
Converting `this` to `window` in each of the offending *.js files also fixes the problem, but is not a good long-term solution, at least for `he-1.1.1.js` which we do not control.

**Comment by samreid** [comment]
Here's a patch that works for us since we are babel < 7.0:

```
Index: js/grunt/buildRunnable.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/grunt/transpile.js	(revision 0097c5acd715d88dd12201b2d52690068afa3f0c)
+++ js/grunt/transpile.js	(date 1543898472000)
@@ -27,6 +27,7 @@
 
     // Use chipper's copy of babel-preset-env, so we don't have to have 30MB extra per sim checked out.
     presets: [ [ '../chipper/node_modules/babel-preset-env', {
+      modules: false,
       targets: {
         browsers: [
           // See http://browserl.ist/?q=%3E+0.5%25%2C+safari+9-11%2C+Firefox+ESR%2C+IE+11%2C+ios_saf+11
```

**Comment by samreid** [comment]
In slack, I reported: 

> In https://github.com/phetsims/chipper/issues/723 I’m investigating using babel to transpile preloads.  Initial testing looks good, I’m going to commit my progress and ask @jonathanolson to review.  Please report any issues you observe.

**Comment by samreid** [comment]
It seems the best way to proceed would be to put `babelTranspile = true,` in the minify options, and to try to reuse the minify options from the requirejs code to the preload code--would that work, or will it be problematic to put `stripAssertions = true, stripLogging = true` on the preloads?

**Comment by samreid** [comment]
I reviewed my working copy changes with @jonathanolson and he agreed it is ready for testing.  I'll run the following tests.  If all is well, I'll commit to master.

- [ ] make sure debug version looks full, production version looks minified
- [ ] Sneak in "const" into a preload, make sure it's taken out of production, left in debug.
- [ ] Test some of --minify.uglify=false options

Note that these changes will also affect https://github.com/phetsims/phet-io-wrappers/issues/209

**Comment by samreid** [comment]
My tests seemed OK, I tested with graphing-quadratics, brands=phet,phet-io and the cases identified above.  I used --minify.mangle=false for the final test.

@jonathanolson can you please spot check or run additional tests as you see fit?  Commits incoming.

**Comment by jonathanolson** [comment]
I just tried:

```sh
grunt --minify.mangle=false
```

and built output for some reason looks pretty-printed, e.g.:

```js
            setMuted: {
                returnType: VoidIO,
                parameterTypes: [ BooleanIO ],
                implementation: function(muted) {
                    this.instance.muted(muted);
                },
                documentation: "Set whether the utteranceQueue will be muted or not. If muted, utterances still move through the queue but will not be read by screen readers.",
                invocableForReadOnlyInstances: !1
            },
```

**Comment by samreid** [comment]
Michael Kauzmann [4:56 PM]
Does it surprise anyone else to know that QSM is unminified and has comments in the built sim? I guess all preloads don't get minified.


Sam Reid [4:58 PM]
This may be a new bug?  I was tinkering with preloads in https://github.com/phetsims/chipper/issues/723 and maybe messed something up.

**Comment by samreid** [comment]
@pixelzoom mentioned interest in master SHAs for BCE, so I'll work on this at top priority.

**Comment by samreid** [comment]
> I just tried  `grunt --minify.mangle=false` and built output for some reason looks pretty-printed

Ever since this code was introduced in 2017, `beautify` has been set to `!mangle`.  Is that not as desired?

```js
    // output options documented at https://github.com/mishoo/UglifyJS2#beautifier-options
    output: {
      inline_script: true, // escape </script
      beautify: !mangle
    }
```

**Comment by samreid** [comment]
@zepumph and I discussed the QSM nonminification.  We tested several builds in master and they seemed OK.  @zepumph clarified that on Thursday he saw a non-minified QSM go by, but then on immediate rebuild the problem disappeared.  We tried some intermediate SHAs but could not reproduce the problem.

**Comment by samreid** [comment]
beautify has been set to !mangle. Is that not as desired?

It's definitely a change. How would I build unmangled but unbeautified builds for performance testing?


Sam Reid [1:59 PM]
we can split mangle.beautify into a separate option (not coupled to !mangle) sound OK?

Jonathan Olson [1:59 PM]
(the whitespace takes up additional memory and changes performance characteristics)
that would be fine with me

Sam Reid [2:00 PM]
Anything else to do or review before https://github.com/phetsims/chipper/issues/723 can be closed?  I think I’ll make the “beautify” a separate issue.

Jonathan Olson [2:00 PM]
Sounds good to close
