### ISSUE TITLE
Use prefix and dot notation consistently, particularly regarding minify options

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#724]
Related to https://github.com/phetsims/chipper/issues/723

Chris Malley [12:01 PM]
Instead of “minify.uglify”, is there a better option name that describes what’s being done here?  Something not tied to the specific tools perhaps.
I’ve never seen a grunt option name with a ‘.’ in it, surprised that it even works.

Sam Reid [12:02 PM]
What term or option names do you recommend?

Chris Malley [12:03 PM]
Does ‘minify.uglify’ perform minification, then uglification, in that order?  Where they formerly separate options?

Sam Reid [12:04 PM]
previous options were
--uglify {boolean}
--mangle {boolean}
New options are:

--minify.babelTranspile=false - Disables babel transpilation phase.
--minify.uglify=false - Disables uglification, so the built file will include (essentially) concatenated source files.
--minify.mangle=false - During uglification, it will not “mangle” variable names (where they get renamed to short constants to reduce file size.)
--minify.stripAssertions=false - During uglification, it will strip assertions.
--minify.stripLogging=false - During uglification, it will not strip logging statements.

Chris Malley [12:06 PM]
I didn’t realize there were 5 like this. So the last 3 are presumably ignored if `--minify.uglify=false`.
If so, then should those last 3 be named “uglify.mangle”, “uglify.stripAssertions” and “uglify.stripLogging” ? (edited)
And how about “minify=false” that disables everything related to minification.

Sam Reid [12:10 PM]
> So the last 3 are presumably ignored if `--minify.uglify=false`.

Correct.
> If so, then should those last 3 be named “uglify.mangle”, “uglify.stripAssertions” and “uglify.stripLogging” ?

Should it be minify.uglify.mangle for clarity, or is that too verbose?
> And how about “minify=false” that disables everything related to minification.

The “debug” version already does that in phet-brand builds. (edited)

Chris Malley [12:11 PM]
Too verbose.  If `minify.uglify=false`, then any option with “uglify” prefix is ignored.
The “debug” version presumably does that by specifying `--minify.babelTranspile=false --minify.uglify=false`.  If we have to add something else related to minification, then that build code will need to change.  If it was `minify=false, that would disable all minification and  ignore all options with “minify” prefix.  (Similar to “minify.uglify” and “uglify” prefixed options.)
I’m just pointing out that if you’re going to use a prefix and “.” notation for option names, it would be nice to do so consistently, and in a way that makes it easy to disable all options with a specific prefix.

**Comment by samreid** [comment]
My hope is that no developer will ever need to use any of those options, because our needs are covered by the production build and debug build.  And if a developer does need to use those options, they are all covered in the same place using the same strategy.

minify.js has:

**Comment by samreid** [comment]
If we do decide to structure these options, it seems that keeping the structure would be clearest:

```
--minify={boolean}

// Only applied if minify===true
--minify.babelTranspile={boolean}
--minify.uglify={boolean}

// Only applied if minify===true and minify.uglify===true
--minify.uglify.mangle={boolean}
--minify.uglify.stripAssertions={boolean}
--minify.uglify.stripLogging={boolean}
```

**Comment by jonathanolson** [comment]
I don't feel particularly strongly.

> My hope is that no developer will ever need to use any of those options, because our needs are covered by the production build and debug build.

I constantly need to use (or recommend others to use) builds that are unmangled (since we don't use source maps) for performance profiling. Is this something that should be added as another build artifact/option?

**Comment by zepumph** [comment]
I have never used these sorts of options. I don't have a strong preference about what we go with. Though now that I know these exist, I will probably use whatever we decide on.

@pixelzoom's recommendation makes sense to me, and is a bit clearer than having all options on minify.

**Comment by samreid** [comment]
Trying to understand the central point of the proposal in https://github.com/phetsims/chipper/issues/724#issuecomment-445577973, it seems the point is we don't need to know that `uglify` is technically structured under `minify` in order to set its options.  Why not take it one step further and make the API like so?

```
// Minification, which reduces the size of the html file
--minify={boolean}

// Only relevant if minify is enabled
--babelTranspile={boolean} // babel transpilation phase
--uglify={boolean} // uglification phase

// Only relevant if uglify is enabled
--mangle={boolean} // “mangle” names, where they get renamed to short constants to reduce file size
--stripAssertions={boolean} // strip assertions
--stripLogging={boolean} // strip logging statements
```

Or is the point to specify one parent, so you know the "shutoff valve" for each thing?

**Comment by jonathanolson** [comment]
I personally prefer the non-prefixed flags in https://github.com/phetsims/chipper/issues/724#issuecomment-446247891.

**Comment by pixelzoom** [comment]
@samreid said:
> ... Or is the point to specify one parent, so you know the "shutoff valve" for each thing?

If you're going to use qualified (dot) notation, yes.

@jonathanolson said:
> I personally prefer the non-prefixed flags in https://github.com/phetsims/chipper/issues/724#issuecomment-446247891.

Me too.  As I said in my very first Slack comment:

> I’ve never seen a grunt option name with a ‘.’ in it, surprised that it even works.

**Comment by samreid** [comment]
OK, I'll aim for https://github.com/phetsims/chipper/issues/724#issuecomment-446247891, and will also be adding --beautify, see #725.

**Comment by samreid** [comment]
Developing and testing each changed command line flag should take 2-3 hours.  I haven't made time for it yet and it's not on my radar for the immediate future.  @ariel-phet would you like to assign this to another developer, or keep it assigned to me (at same or elevated priority)?

**Comment by ariel-phet** [comment]
Marking for dev meeting for a brief discussion of if this change would be good to make soon (and if someone else is willing to hop on making it)

**Comment by Denz1994** [comment]
Discussed at dev meeting: 09/19/19

@Denz1994 will continue to work on this. Let's try to get this done within the next month. Ping @samreid for assistance if needed.

**Comment by zepumph** [comment]
All options are now top level and can be accessed with `minify.*`, including `minify.minify=false` to turn off all minification. Closing
