### ISSUE TITLE
Separate mangle and beautify options

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#725]
From https://github.com/phetsims/chipper/issues/723 @jonathanolson requested to separate the mangle and beautify options.  It sounds like beautify=false is preferable for performance testing.

**Comment by samreid** [comment]
Proposed fix committed.  I ran a few tests with faraday's-law:

```
grunt --brands=phet --minify.beautify=true
grunt --brands=phet --minify.mangle=false --minify.beautify=true
grunt --brands=phet --minify.mangle=false
grunt --brands=phet
```

And results were what I expected.  Note the API may change in https://github.com/phetsims/chipper/issues/724.  Reassigned to @jonathanolson to verify.

**Comment by zepumph** [comment]
This looks really great and is working well. Thanks! Closing.
