### ISSUE TITLE
Upgrade eslint to most recent version

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#726]
While working on https://github.com/phetsims/tasks/issues/972, @samreid and I experimented with the new version of eslint (version 5.10.0). It looks like they have added a few new rules that could be nice for us:

```
C:\Users\Michael\PhET\git\axon\js\PropertyTests.js
  59:16  error  Comparing to itself is potentially pointless  no-self-compare

C:\Users\Michael\PhET\git\build-a-molecule\js\control\CollectionBoxNode.js
  140:7  error  The update clause in this loop moves the variable in the wrong direction  for-direction

C:\Users\Michael\PhET\git\phet-io-wrappers\js\tests\SimTests.js
  26:7  error  'isType' is assigned a value but never used  no-unused-vars

C:\Users\Michael\PhET\git\phet-io-wrappers\studio\createInstance.js
  21:7  error  'getMethod' is assigned a value but never used  no-unused-vars

C:\Users\Michael\PhET\git\projectile-motion\js\common\model\DataPoint.js
  67:17  error  Comparing to itself is potentially pointless  no-self-compare

C:\Users\Michael\PhET\git\scenery\js\nodes\Node.js
  4010:22  error  'canvas.width' is assigned to itself  no-self-assign

C:\Users\Michael\PhET\git\scenery\js\util\Features.js
  136:10  error  Expected to return a value in method 'get'  getter-return
```

One other rule that is excluded from this list because there were many errors from it is:     `no-useless-escape`

These all seem like nice rules, and I don't think it would be too hard to accomplish. I'll investigate.

**Comment by zepumph** [comment]
I updated to ~5.14.1 (from ~3.19.0), and got 70 lint errors from the following rules:

* no-useless-escape (63 of the errors)
* no-self-compare
* getter-return
* no-self-assign
* no-unused-vars

So I think I'm going to commit the update, fix the 7 errors that were shown, and then for now turn off the no-useless-escape. That we may need to use `--fix` for, or it can come in another commit.

**Comment by zepumph** [comment]
@samreid can you please review the above commits. Work can be summed up as:

* Upgrade eslint to 5.14
* turn off no-useless-escape lint rule in our base rc file
* fix/disable-line on the other lint rules
* When I did the above checklist, I found that `grunt lint-all` was now broken. This is for the same, `no-lint` reasoning that we had to address in perennial. So I provided a sketchy fix for supporting out `no-lint` blacklist for chipper's grunt lint-all task. This is working, but also points to perennial, so I put a TODO  pointing to this issue in the code.


Next steps: 
* address your review comments
* Fix and then turn on `no-useless-escape` rule, or discuss if we want this rule on (it is now included in eslint:recommended)
* Figure out how to address the issue with excluding the `no-lint` repos in the `grunt lint-all` task in chipper.

**Comment by samreid** [comment]
1. Would it make sense to list the blacklist in chipper, as is done for ignorePattern in https://github.com/phetsims/chipper/blob/4ff287646f7cea993e09b646cdf09cac41e71915/js/grunt/lint.js?
2. I think we should move forward fixing `no-useless-escape` issues and turn that rule on.  That will make it easier for me to read and understand regexes.  I don't see an autofix for this rule though.
3. This commit sneaked in but seems to be from something else: https://github.com/phetsims/phet-io-wrappers/commit/55c179c04eec15df4c15c220c606b2b21542c989

I can help on (2), reassign to me after we discuss (1).

**Comment by zepumph** [comment]
1. Fixed above
2. see https://github.com/phetsims/chipper/issues/750
3. oops. . .  They were unused functions so I'm not too worried about remembering the right issue.

Anything else here?

**Comment by samreid** [comment]
I'm not sure what else to do here, but @zepumph can you please review @jonathanolson's commits on the branches? Will we need to do that elsewhere?  Should we do that eagerly, or wait until problems come up?
