### ISSUE TITLE
Deprecation warning about HTML imports in Chrome

### ISSUE THREAD

**Issue by jbphet** [phetsims/chipper#727]
I'm seeing the following message in the Chrome console when I load sims, either from RequireJS or built:

```
enable-tooltip.ts:143 [Deprecation] HTML Imports is deprecated and will be removed in M73, around March 2019. Please use ES modules instead. See https://www.chromestatus.com/features/5144752345317376 for more details.
```

Here is a screenshot:

![image](https://user-images.githubusercontent.com/3082831/50114961-435f7e80-0203-11e9-8566-7fe795103756.png)

I tested RequireJS versions of several sims and saw it for all of them, then tried a locally-built version of Energy Forms and Changes and the published version of States of Matter and saw it for both of those as well.

I asked via Slack if others were seeing this, and the answer seems to be no.  Here's the dialog:

> jbphet [1:40 PM] I've been seeing the following for a while when loading on Chrome, and I just searched our GitHub issues and wasn't able to find a related one.  Any reason not to log an issue for this?
Untitled 
enable-tooltip.ts:143 [Deprecation] HTML Imports is deprecated and will be removed in M73, around March 2019. Please use ES modules instead. See https://www.chromestatus.com/features/5144752345317376 for more details.

> jessegreenberg [1:40 PM]
Interesting, I don't think I have seen that one yet, Ill keep an eye out

> pixelzoom [1:40 PM]
What are “HTML Imports”?
And where are we currently using them? (edited) 

> jbphet [1:42 PM]
I don't really know, and looked at one of the HTML files where I was getting this and didn't see "import".  I don't know what `enable-tooltip` is either.  I just didn't think I should ignore it.

> jonathanolson [1:43 PM]
Might be something in the require.js system that is feature-checking for imports? Not sure

> pixelzoom [1:43 PM]
Sounds like it’s usage of `<link rel="import" ...>`.  See https://dev.to/nektro/the-downfall-of-html-imports-is-upon-us-to-me
The Practical Dev
The downfall of HTML Imports is upon us (to me)
HTML Imports came out at the same time along with Web Components and they're being phased out. And they should not.

> jbphet [1:45 PM]
I just dug a little, and I think it may be related to the version of jquery we're using.

> jonathanolson [1:45 PM]
Looks like since we're not using CSS imports, it wouldn't affect us?

> pixelzoom [1:46 PM]
@jbphet did you see the above message in the context of running a sim? (edited) 

> jbphet [1:47 PM]
Yes, both RequireJS and built.  I take it none of you are seeing it?

> pixelzoom [1:47 PM]
Which sim?
Which version of Chrome?

> jbphet [1:48 PM]
Every sim, Chrome  71.0.3578.98.
pixelzoom [1:48 PM]
I am not seeing it on macOS.

> jbphet [1:49 PM]
Just tried the published version of SOM, and got it there too.  What's your Chrome version?

> pixelzoom [1:49 PM]
71.0.3578.98
same as yours, latest.

> jbphet [1:50 PM]
Okay.  I'll log an issue, and will put this dialog in there.

> pixelzoom [1:51 PM]
I don’t see it with SOM published, or master.

**Comment by jbphet** [comment]
Assigning to @ariel-phet for delegation and prioritization.

**Comment by jbphet** [comment]
For reference, I'm seeing it on Chrome 71.0.3578.98, Windows 10.

**Comment by jessegreenberg** [comment]
I have the same version of Chrome on Windows 10 and I am not seeing this warning in the dev tools yet when running sims in RequireJS.

**Comment by ariel-phet** [comment]
@jonathanolson no need to fix anything just yet...but it seems that people are nebulous on where we even use these. Can you investigate briefly in the near future (after Jan 31 is fine) to at least see what exactly we are dealing with and what we would need to fix it?

**Comment by jonathanolson** [comment]
I'm not sure why it was being flagged by @jbphet's chrome. It appears we are NOT using HTML imports, and I believe we are using no feature of jQuery that would be using this feature. It is also a chrome-only feature, which seems unlikely for our code to do.

According to https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/h-JwMiPUnuU/sl79aLoLBQAJ, Chrome 73 will have this disabled. I just tested our sims in Chrome 74 (Canary), and things run fine (require.js and built) with no related warnings.

I feel this is resolved and should be safe to close.
