### ISSUE TITLE
Remove jsondiffpatch from sims

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#729]
Currently it is a preload for phet-io builds, but I think we should get rid of it. We can still use it in wrappers, like for `diff`.

**Comment by zepumph** [comment]
This was done in the above commits.

This seems pretty nice. Unminified the library was 150KB, and minified it was estimated at 100KB, not bad in the savings department. 

@samreid please review.

**Comment by zepumph** [comment]
This was done in the above commits.

This seems pretty nice. Unminified the library was 150KB, and minified it was estimated at 100KB, not bad in the savings department. 

@samreid please review. 


(commenting again so it is at the bottom of these commits0

**Comment by samreid** [comment]
Nice work, but I'm seeing one discrepancy.  When I go to faradays-law and run `grunt update`, I see this change:

```
Index: faradays-law-tests.html
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- faradays-law-tests.html	(revision 83e59bf32292f6ea6649aac6f27b7c97f67aab95)
+++ faradays-law-tests.html	(date 1549337888000)
@@ -52,7 +52,6 @@
 
     if ( brand === 'phet-io' ) {
       preloads = preloads.concat( [
-        '../sherpa/lib/jsondiffpatch-v0.3.11.umd.js',
         '../phet-io/js/phet-io-initialize-globals.js'
       ] );
     }
```

I suspect we should remove this from all of the HTML test harnesses (possibly via running `grunt update` in each repo), but wanted to double check with @zepumph first.

**Comment by samreid** [comment]
I'm seeing some references to jsondiffpatch in chipper/js/grunt/phet-io/copySupplementalPhetioFiles.js.  Is that as expected?

**Comment by zepumph** [comment]
Yes that is, because the built diff wrapper still needs to use that library, so it is built with phet-io simulations.

**Comment by samreid** [comment]
Looks great, thanks!  Closing.
