### ISSUE TITLE
Should we be caching the string files for requirejs mode.

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#730]
@zepumph @chrisklus and I noticed that the same string file is being loaded many times when launching a sim in requirejs mode, likely once per string:

![image](https://user-images.githubusercontent.com/679486/50452567-ff056a00-08f7-11e9-86b8-625754271cca.png)

I wonder if we can speed up launch time by caching it and only XHR once?

**Comment by zepumph** [comment]
Windows 10

Chrome No patch:
![image](https://user-images.githubusercontent.com/6856943/52384732-26893f80-2a2b-11e9-9d62-ef2d899d2498.png)

Firefox no patch:
![image](https://user-images.githubusercontent.com/6856943/52384738-3012a780-2a2b-11e9-9186-7f46fa77d02e.png)


Chrome yes patch:
![image](https://user-images.githubusercontent.com/6856943/52384914-f3937b80-2a2b-11e9-87a5-b88bf9506968.png)


firefox yes patch:
![image](https://user-images.githubusercontent.com/6856943/52384920-fb532000-2a2b-11e9-84ae-4c0a7dffe0bd.png)


To me this looks pretty inconclusive. Not really sure how to recommend a direction from here. I trust you. Let me know if I can do anything else.

**Comment by samreid** [comment]
At a minimum, we should remove the buggy code that thinks it is caching but is not actually caching.

**Comment by samreid** [comment]
I outputted cache hits and cache misses, and saw plenty of hits.  Maybe this caching code isn't completely failing.  Maybe we should leave it as it is to avoid additional complexity.

**Comment by samreid** [comment]
I just added a note in a comment, perhaps that is sufficient to close this issue.  @zepumph ok with you?

**Comment by zepumph** [comment]
Yes thanks for taking a look.
