### ISSUE TITLE
Review base config "globals"

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#731]
After @samreid and I looked at them only briefly, it seemed like some of them could be updated.

This issue stems from https://github.com/phetsims/tasks/issues/972, and in it we should:

* Review the globals to see which ones we can delete because they are no longer used.
* Review the globals to see which ones should be added to a more specific configuration file. Either another file in `chipper/eslint` (like sim_es6 or node), or if a global is just used by one sim/directory, then it should be moved to a specific config there.

**Comment by zepumph** [comment]
@samreid I think you will have the best idea about what can be deleted or moved, do you mind taking a first pass and let me know what work you think I can do?

**Comment by zepumph** [comment]
As I started doing this, I see two things immediately:


- [ ] Why is this overwritable? I would think it would be read-only
     ```
    // For use in aqua tests
    // underscore, lodash
    '_': true,
     ```

- [ ] When I commented this out, there were 52 failures, but that seemed weird to me, because I would think that that would be covered by the browser `env` globals.
    >`    'window': false,`

**Comment by samreid** [comment]
I made all of the globals writable: false, because that doesn't apply to `window.variable = ...` notation, which is the only way we assign them.

**Comment by samreid** [comment]
Many improvements in the preceding commits. Local `grunt lint-everything --disable-eslint-cache` is passing.  I scheduled a timer to look at CT in an hour.

**Comment by samreid** [comment]
I see the perennial linting problem and I think I’ll need to restart bayes ct to address it.

**Comment by samreid** [comment]
I removed unused globals and moved sim-specific globals to the appropriate repos.  @zepumph do you want to review?

**Comment by zepumph** [comment]
This is all really nice. Thank you! I like how short that list is. In the future there may be a bit of grossness if we find that we are using himalaya in 100 repos. There should be a threshold as to how much it should be duplicated before it is added to the main file. 

I really like that all globals are read-only. 


> When I commented this out, there were 52 failures, but that seemed weird to me, because I would think that that would be covered by the browser env globals.

Well I think we should just keep this one in then!

Back to you.

**Comment by samreid** [comment]
I think that's everything, please reopen if I'm wrong.
