### ISSUE TITLE
Commented out lint rules

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#734]
While working on cleaning up https://github.com/phetsims/tasks/issues/972, I saw

```

    //    'require-jsdoc': [
    //      2
    //    ],
```

And wondered if we wanted to investigate this at all, or just delete it. @samreid do you have any insight?

**Comment by samreid** [comment]
I flip that rule on temporarily sometimes during code reviews.  But it is now deprecated and ESLint is dropping support for it, see https://eslint.org/docs/rules/valid-jsdoc

**Comment by zepumph** [comment]
I also see:

```
 //    'no-use-before-define': [
    //      2
    //    ],
    // TODO: This may be good to have
    //    'new-cap': [
    //      2
    //    ],


    // disallow trailing whitespace at the end of lines (fixable)
    //    'no-trailing-spaces': 2,

```

Mainly I want to know if we should do one of three things:

1. Delete these
2. Uncomment them
3. Mark them with `// USE THIS DURING CODE REVIEW` which I see another lint rule doing.

**Comment by samreid** [comment]
I've pulled the commented out rules into a dedicated file, and added it to the code review checklist.  @zepumph can you please review?

**Comment by zepumph** [comment]
Looks great!

**Comment by pixelzoom** [comment]
Reopening.   

Slack developer channel:

Chris Malley [4:30 PM]
A new code-review checklist item is “Does linting with “sim_es6_eslintrc_review.js” reveal any problems?”  What is the point of this?  I’m having all kinds of problems with this lint file.  By convention we define private functions after the class definition, and lint is flagging all of these as “used before defined” errors.  I also have dozens of “exceeds the maximum line length of 120" where I’m a char or two over, and intended to exercise my “developer discretion” .   Also a dozen or so “no-trailing-spaces” errors that WebStorm can’t find when I request a reformat. (edited) 

So for my first experience with this… Lots of noise, lots of busy-work, zero benefit so  far.

Michael Kauzmann [4:32 PM]
I am inclined to agree with you. I ran it for GFLB and basically just reformatted line comments for 10 minutes.
I think it has helped @samreid before, and perhaps he would know more.

**Comment by pixelzoom** [comment]
In my single experience with this, it had zero value, and only generated busy work.  Some rules don't even match PhET conventions. 'no-use-before-define' is generating a lot of noise because it's PhET convention to define private functions after the class definition.  `'max-len' 120` is not a hard rule, it's up to developer discretion.   And `'no-trailing-spaces': 2,` kept me busy for 20 minutes reformatting files and hunting for spaces that WebStorm can't find (like spaces after the `define` function).  

I'd like to hear other developers' experiences.

**Comment by samreid** [comment]
I found numerous occurrences of trailing whitespace in comments--those seem tolerable.  I tried changing the rule to:
```
'no-trailing-spaces': ["error", { "ignoreComments": true }],
```
and saw 348 occurrences of trailing whitespace in code (not in comments).  For example:
![image](https://user-images.githubusercontent.com/679486/59243885-79d4ef80-8bcf-11e9-928c-316f813d9d90.png)

When I applied the IDEA formatting rule, these extraneous whitespaces were removed.  So this seems like a one way to detect when the IDEA formatter is not being used.

I'm happy to get rid of the `no-use-before-define` rule.  Not sure about the 120 limit.  Maybe we would say that 120 is a good rule of thumb (developer discretion can go over), but 180 is a hard limit?  Or something like that.  `new-cap` seems to be a useful rule, but not sure what others think. 

I don't feel too strongly about this, but just wanted to throw in 2 cents.

**Comment by zepumph** [comment]
`'no-trailing-spaces'` perhaps should be included in all lint rules, since it is a sign that formatting is not being applied. Perhaps people would be opposed though.

**Comment by samreid** [comment]
In #765 @jessegreenberg said:

One of the steps in the code review checklist is 
> Does linting with "sim_es6_eslintrc_review.js" reveal any problems that should be fixed? (change eslintConfig in package.json and run grunt lint)

When I ran it for gravity-force-lab-basics it identified a number of lint issues mostly related to line length. We determined that these don't need to be fixed. Should the line length check be changed for sim_es6_eslintrc_review?

It also flagged `DerivedPropertyIO( NumberIO )`:
>A function with a name starting with an uppercase letter should only be used as a constructor (new-cap)

I am not sure I understand the purpose of this check - since it is for es6 are we hoping that all es6 sims will pass these rules? Or is this just a way to flag things that *might* be problems.

@samreid  and @zepumph are listed as authors, what do you think?

**Comment by samreid** [comment]
The *_review.js rules were intended to flag things that *might* be problems.  But it sounds this supplemental eslint file is more trouble than it is worth.  I recommend we move any desirable rules to the main eslint file and delete this one.

**Comment by pixelzoom** [comment]
+1 for moving desirable rules to the main eslint file and deleting sim_es6_eslintrc_review.js.

**Comment by jbphet** [comment]
Another +1 for moving desirable rules to the main eslint file.  I am currently working through the code review checklist for "Gas Properties", and the item containing "Does linting with "sim_es6_eslintrc_review.js" reveal any problems that should be fixed?" feels like a waste of time.  There is a rule `no-use-before-define` that is flagging a number of things that seem to be exactly as they should be, so at the very least, that rule should be immediately removed.

**Comment by samreid** [comment]
Tagging for developer meeting to confirm exactly which rules we want to move to the main eslint file.

I recommend to move the following rules:
```
'no-trailing-spaces': 2,

    // specify the maximum length of a line in your program
    'max-len': [
      2,
      // Our convention is to limit to 120 with "use developer discretion", but this is the hard limit (or use
      // eslint-disable)
      160
    ],
```

Note that build-a-molecule/js/model/data/otherMoleculesData.js will need a file-oriented disable.

**Comment by arnabp** [comment]
@samreid We came to an agreement that moving no-trailing-spaces was good, but we wanted to avoid pushing line limit to main eslint and having special cases of long lines (such as github links) breaking lint.

**Comment by pixelzoom** [comment]
Complete list of what needs to be done:
- [ ] move only the 'no-trailing-spaces' to sim_es6_eslintrc.js
- [ ] delete sim_es6_eslintrc_review.js
- [ ] remove item related to sim_es6_eslintrc_review.js from the code-review checklist

**Comment by samreid** [comment]
We also need to decide what to do with the 521 lint errors introduced when this rule is turned on.  Perhaps we will go with `'no-trailing-spaces': [ 2, { skipBlankLines: true, ignoreComments: true } ]` which has 86 errors.

**Comment by samreid** [comment]
My personal preference is to strip whitespace on blank lines, but I don't want to mess up cursor navigation for anyone.  Perhaps we should touch base on this before proceeding?

**Comment by samreid** [comment]
At today's meeting, we agreed to strip all whitespace in comments and blank lines.  I'll address this.

**Comment by samreid** [comment]
@jonathanolson reported here's a way to strip whitespace on empty lines on save in sublime:

> "trim_trailing_white_space_on_save": true (in Sublime user settings)

**Comment by pixelzoom** [comment]
Labeling this for developer meeting.  On 7/18, we decided to delete sim_es6_eslintrc_review.js.  It still exists.

**Comment by samreid** [comment]
This script may be helpful:

for-each.sh perennial/data/active-runnables "find ./js/ -iname '*.js' -type f -exec sed -i '' 's/[[:space:]]\{1,\}$//' {} \+"

Thanks https://stackoverflow.com/questions/10711051/how-to-remove-trailing-whitespaces-for-multiple-files

**Comment by samreid** [comment]
eslint review file removed, trailing whitespace rule added, offending files addressed.  Will monitor CT for a bit and close if all is clear.

**Comment by samreid** [comment]
CT seems clear, closing.
