### ISSUE TITLE
fix lint errors caused by bad-sim-text.js

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#736]
from https://github.com/phetsims/chipper/issues/728, there were 74 errors that were caused by adding `bad-sim-text` lint rule:

Here are the affected repos:

- [x] acid-base-solutions @pixelzoom 
- [x] area-builder @jbphet 
- [x] arithmetic @jbphet 
- [x] balancing-act @jbphet 
- [x] balloons-and-static-electricity @jessegreenberg 
- [x] beers-law-lab @pixelzoom 
- [x] bending-light @samreid 
- [x] build-a-molecule @jonathanolson 
- [x] chipper @zepumph 
- [x] circuit-construction-kit-common @samreid 
- [x] curve-fitting @jonathanolson 
- [x] dot @jonathanolson 
- [x] energy-forms-and-changes @chrisklus (done by @pixelzoom)
- [x] energy-skate-park @jessegreenberg 
- [x] faradays-law @jbphet 
- [x] forces-and-motion-basics @jessegreenberg 
- [x] gene-expression-essentials @jbphet 
- [x] interaction-dashboard @zepumph 
- [x] john-travoltage @samreid 
- [x] joist @jonathanolson 
- [x] kite (@zepumph isn't sure if there need to be converted or ignored, over to you @jonathanolson)
- [x] models-of-the-hydrogen-atom @pixelzoom 
- [x] molarity @pixelzoom 
- [x] molecules-and-light @jessegreenberg 
- [x] neuron @jbphet 
- [x] optics-lab @zepumph 
- [x] ph-scale @pixelzoom 
- [x] phet-core @zepumph 
- [x] phetcommon  @zepumph 
- [x] reactants-products-and-leftovers @pixelzoom 
- [x] scenery @jonathanolson  
- [x] scenery-phet @zepumph 
- [x] states-of-matter @jbphet 
- [x] sun @zepumph 
- [x] tambo @jbphet (fixed by @pixelZoom)

To fix this, one of three actions should occur:
1. Replace that usage with something else as the code review guidelines suggest.
2. ignore this error by following the strategy that done in https://github.com/phetsims/wave-interference/commit/e2a72ce601503e7b42b5f773a13db7ad0fff12ff. Make sure that usages are well documented!!!!
3. Decide that the directory that the error occurs in doesn't belong being linted by sim specific lint rules, and add a `.eslintrc.js` file that specifies the correct lint rules, see `chipper/eslint/README` for more details.

To trigger there errors, got to `chipper/eslint/sim_eslintrc.js` and change the `bad-sim-text` rule to error (value of `2`). Assigning all responsible devs for above sims. I assigned myself to common code repos because they may be less straightforward.

**Comment by zepumph** [comment]
This repos assigned to me are now completed.

**Comment by jessegreenberg** [comment]
@zepumph I am confused by https://github.com/phetsims/wave-interference/commit/e2a72ce, doesn't eslint-disable-line just disable a single line?

**Comment by samreid** [comment]
I agree, lint seems to be passing even without that line.

**Comment by zepumph** [comment]
@jessegreenberg that is the line that the link error flags, yes I agree it is confusing and think instead we should be using the marking to disable for the whole file like https://github.com/phetsims/chipper/commit/cd675bd48eda9ce5a6a354d4e8d4a4e7573703bd

@samreid that may be because of https://github.com/phetsims/chipper/commit/e04f7925cce230cc5de8e0586ecb2bf62e6017d9

**Comment by jessegreenberg** [comment]
Got it, thanks. With https://github.com/phetsims/chipper/issues/737, I was able to use the new lint rule to fix sims assigned to me.

**Comment by jonathanolson** [comment]
Added required changes to the repositories for which I was marked. I had to add some lint disables to files where they either don't have access to joist's random (dot/kite/scenery), or they need access to Math.round (Util.roundSymmetric's implementation).

**Comment by jbphet** [comment]
Works for me.

**Comment by jbphet** [comment]
I've fixed the sims for which I am the responsible developer and have committed the change to the 'bad-sim-text' value to turn on the stricter checking.  I'll watch CT for the next hour or so to make sure it doesn't cause a bunch of failures.

**Comment by jbphet** [comment]
I'm not seeing any unusual failures on CT, so I think this can be closed.  I'm going to assign it back to @zepumph since I *think* everything is done but would like someone who is more familiar with the issue to make sure I'm not missing anything.

**Comment by pixelzoom** [comment]
Should this still be labeled for developer meeting? If so, what feedback do you want?

**Comment by zepumph** [comment]
>bad-text should be rewritten so that it can provide line-specific failures, then we can use eslint-disable-line in the correct places.

lets talk over in https://github.com/phetsims/chipper/issues/738


that and https://github.com/phetsims/chipper/issues/728 are follow up issues. Closing
