### ISSUE TITLE
add lint rule for ES6 string templates?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#741]
A common problem when using ES6 string templates:

```js
// incorrect use of quotes
assert && assert(..., 'invalid value: ${value}' );

// correct use of backquotes
assert && assert(..., `invalid value: ${value}` );
```

Should we add eslint rule [no-template-curly-in-string](https://eslint.org/docs/rules/no-template-curly-in-string)?
To which files should it be added?

**Comment by zepumph** [comment]
This sounds really nice. I added the rule for es6 sims and node code. Looks like there were no usages of this problem in our code that I found (wahoo). I did disable a few false positives though. Anything else to do here?

**Comment by zepumph** [comment]
Notice how it works: 

![image](https://user-images.githubusercontent.com/6856943/53535854-a6497d80-3ab0-11e9-886b-7be0c60a5936.png)

**Comment by ariel-phet** [comment]
Awesome work @zepumph closing!
