### ISSUE TITLE
Fix css in a11y view to see alerts easier

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#742]
We are interested in having the interactive alerts always visible, but now sometimes they can be hidden underneath a large screen. @twant is interested in investigating. Good luck, and let me know if you have any questions.

Feel free to edit the molarity specific a11y view while prototyping, but changes should eventually be made in `chipper/templates/sim-a11y-view.html`. 

When you are happy with a solution you will want to regenerate all a11y views for all a11y sims. You can do this by using the `for-each.sh` command in `perennial/bin`. Something like

`perennial/bin/for-each.sh perennial/data/accessibility grunt generate-a11y-view-html`.

**Comment by zepumph** [comment]
I am running into this more and more, it is a bummer that I wrote such poor css to place the alerts so far below the sim. 

I also want to note that I saw @twant recently using browser zoom-out to be able to see things more clearly. I liked that and it has been an alright workaround for the time being.

**Comment by twant** [comment]
I have redone some of the CSS  to move things around and make the sim iframe sticky. I updated the Balloons and Static Electricity and Molarity a11y views as an example. Would love your feedback on this @terracoda, @zepumph, and @jessegreenberg to see if this feels like it would be a helpful change to the current layout.

**Comment by jessegreenberg** [comment]
Looking good, thanks @twant! This definitely makes it easier to see alerts while playing with the sim, without having to change browser zoom.

**Comment by zepumph** [comment]
I really like that you have changed the left side to be sticky. that feels like a total win. With that is looks really nice to put the intro at the top because you can scroll that away.


For the alerts panel, I really likely having them on the left. While developing, one of the main ways I use the tool is to navigate to an item in the PDOM, and then interact with that in the sim. From this view, I can see the aria-valuetext changing, alerts firing, and see the keyboard interaction. 

The previous implementation was very bad because it didn't support smaller resolution screens. I also know there are a lot of ways to use this, but perhaps there is a way to support many uses. Here are a few ideas:

* If you move it back over to the left under the sim, there are likely some css things we can do to make sure it always appears:
  * set a percentage max height on the iframe, probably via `.aspect-ratio`. This way the alerts always have space.
  * remove some of the horizontal margin, especially in the middle, so that the alerts can be wider, and need less lines. This may involve setting a width for the iframe that is smaller than the "left" in general, so that the sim doesn't get so wide (therefore increasing its height).
* I was also wondering if it isn't worth investing in a few different media queries. @twant our screens are incredible different, and I feel like for a tool that is used so much throughout the project, it way be worth diving into resolution specific optimizations. I think that @emily-phet would agree with this knowing that she also wants to use this in public spaces like in publications/grants/presentations. 

Good luck; let me know how I can help.

**Comment by terracoda** [comment]
@twant, I have always wanted the intro text across the top with 2 columns below. If that is what you are going for, awesome!
What browsers are you using to check? I don't want to jump in too early, but I am not getting 2 columns in Safari.

**Comment by terracoda** [comment]
![Screen Shot 2019-10-28 at 3 25 31 PM](https://user-images.githubusercontent.com/1902116/67704137-864bc000-f997-11e9-8501-ef9c1ffbfc13.png)

**Comment by zepumph** [comment]
@twant, when pairing with @terracoda about the above commits, it looks like on safari the "position: sticky" wasn't working.

**Comment by twant** [comment]
oo interesting. I'll test and see if I can find a Safari solution. I do think `position: sticky` is a newer thing. It may also not be supported by internet explorer and edge. I found a JavaScript way to do it with a scroll handler, but that seemed very likely to contribute to a11y view's existing performance issues.

**Comment by twant** [comment]
And @zepumph will look into adding some media queries that enable us to move the alert box back underneath the sim!

**Comment by zepumph** [comment]
Good luck!

**Comment by twant** [comment]
Looks like the element has to be displayed block in order for the Safari prefix to work. This is causing issues with the two-column format, so currently working on some work-arounds!

**Comment by twant** [comment]
I am having quite a time to get the sticky formatting to work on Safari. I'd like to pull the changes that apply to other browsers onto master (as I do think they are improvements over what we have now). Do you think it's okay to pull those changes over for non-Safari and IE browsers @zepumph @terracoda @emily-phet @jessegreenberg? And, if so, what Safari behavior would you prefer: the behavior we have now, or behavior where nothing is sticky (and the sim and alerts box just flatly scroll like everything else)? The current version on the `a11y-view-improvements branch` is an example of the latter if you test on Safari.

**Comment by terracoda** [comment]
@twant, is there a version I can test?

**Comment by twant** [comment]
@terracoda Try this and let me know!

https://phet-dev.colorado.edu/html/molarity/1.5.0-dev.27/phet/molarity_a11y_view.html

**Comment by terracoda** [comment]
Looks better in Safari, but not in FFox.
I don't have any scrolling in Safari. Is there supposed to be scrolling?
**Safari**
<img width="1269" alt="Screen Shot 2019-12-01 at 9 52 26 PM" src="https://user-images.githubusercontent.com/1902116/69924278-198b8000-1485-11ea-9ac8-ad31d9a174f3.png">

And in FFox, it seems like the iframe is not resizing, so the layout is really broken. Here are 2 screen shots as I scroll down the page.
![Screen Shot 2019-12-01 at 9 55 31 PM](https://user-images.githubusercontent.com/1902116/69924316-58213a80-1485-11ea-8aad-e9fb5884821a.png)
Scroll down a little to see the rest...
![Screen Shot 2019-12-01 at 9 56 21 PM](https://user-images.githubusercontent.com/1902116/69924337-7ab35380-1485-11ea-848d-5de2cf19bb81.png)

**Comment by twant** [comment]
@terracoda apologies for firefox! I've updated the version so that scrolling should work on firefox.
https://phet-dev.colorado.edu/html/molarity/1.5.0-dev.28/phet/molarity_a11y_view.html

For Safari, it does not seem that it is possible to have the same behavior replicated. With that in mind, I'm wondering if you prefer the flat scroll (where the sim frame doesn't stick at all, as it currently is) or the way it was before, where the sim stuck to the frame as it scrolled, but alerts were sometimes offscreen?

**Comment by terracoda** [comment]
For the way I use the A11y View, it is most desirable for to have the ability to have these three blocks:
1. The visual sim
2. The alerts (context responses)
3. The PDOM (State Descriptions and Object Responses)

in view at the same time.
The top content block is the least important in my mind and was only created for people outside our group. We didn't want people to think the A11y View was our accessible solution that learners use. 

The content can likely be shortened (again) shortened.
And maybe we have been going about this problem the wording way. Maybe most or all of that content at the top could be placed in a footer.

I'll try to get a picture drawn up for you this week.

**Comment by terracoda** [comment]
@twant, I haven't looked at this example from Chris Coyier in depth yet, but the demo does scroll in Safari on my computer. The solution is more about "momentum scrolling" for iOS, but maybe something applies to regular scrolling on MacOS, too.

https://css-tricks.com/snippets/css/momentum-scrolling-on-ios-overflow-elements/

**Comment by terracoda** [comment]
Again, as I mentioned in comment https://github.com/phetsims/chipper/issues/742#issuecomment-560387596 it could be very useful to adjust the blocks we putting content in (move the block at the to a footer).

**Comment by terracoda** [comment]
I'll try to sketch this out later this week.

**Comment by terracoda** [comment]
And FFox is working now... so good job there!

**Comment by jessegreenberg** [comment]
For the purposes of development on Chrome this is a major improvement and it is working great!

If we cannot get sticky positioning to work in Safari, my vote would be
> where nothing is sticky (and the sim and alerts box just flatly scroll like everything else)

Alternatively, we could create space for sim+alerts by hiding the introduction paragraph "The A11y View is a design and presentation tool..." under a section called "About the A11y View", like we are doing with "About the PDOM & Descriptions". That paragraph isn't necessary for presentations because all of that content is described during discussion. It is only required when this stands on its own. But it would be good to hear from @terracoda or @emily-phet on that idea.

**Comment by terracoda** [comment]
@jessegreenberg and @twant, yes the content at the top can be hidden inside`details/summary` elements. I was wondering if something could be achieved if we moved the content to a footer. But `details/summary` is another way to create some vertical real estate.

**Comment by twant** [comment]
Okay, that sounds good! So next steps are to keep what is currently there, and just hide the top content in a details tag. I'll push and assign over for review before merging into master and updating all of the a11y views. @jessegreenberg is this something you are able to review?

**Comment by twant** [comment]
Just following up on this so it can be handed off to @zepumph or @jessegreenberg (or another a11y-focused person). I think the next steps for this are to:

- [ ] Review what's currently on the `a11y-view-improvements` branch
- [ ] Merge into master
- [ ] `grunt-update` every sim so that the a11y-view files are up to date

For another potential issue in the future:
- [ ] Figure out how to get the sticky scrolling to work on Safari (right now it's a flat scroll, while other browsers are sticky)

**Comment by zepumph** [comment]
@twant's work looks really good. I just made a few changes to support (hopefully) wider screens. I also converted to use `em` across the board for consistency.

I think we are ready to merge to master.

**Comment by zepumph** [comment]
I merged and pushed updated a11y view above. I put about 40 minutes into investigating safari sticky behavior, and found https://stackoverflow.com/questions/51792783/safari-positionsticky-not-working-in-an-overflowauto-element which talked about how it is likely because we are using `display: inline-block` instead of `block`. That said, I couldn't get sticky to ever work when I switched to using `block` locally. 

Since our a11y team mostly use chrome on mac I feel alright moving forward. That said we only support safari on mac for our sims.  We can bring this up again if there are problems with the new structure. @terracoda how does the new a11y view look to you?

**Comment by jessegreenberg** [comment]
I reviewed comments in this issue and we are almost ready to close this. These improvements have been looking and working great for development in Chrome. I just tried the a11y view in Safari and the scrolling behavior is working well. The a11y view is sometimes shared to people outside of the team to demonstrate features and I think it is totally working well enough for someone who happens to try it out on that platform.

@terracoda is there anything else you would like to see done for this issue?

**Comment by terracoda** [comment]
@jessegreenberg, the scrolling in Safari on Mac has never worked for me. I am not sure if I am missing something. When using the A11y View on Chrome or Firefox the left column stays fixed and the right column scrolls. On Safari both columns scroll up. 

According to Can I Use website, `position:fixed` is supposed to be supported by Safari.

**I just inspected the CSS, and I see:**
`position: sticky;`

**I think it should be:**
`position: fixed;`

I am not sure what `position: sticky;` is used for, maybe little floaty-menus that stick as a page scrolls? It seems less supported than than `position: fixed;`, and in my opinion the A11y View is the ideal case for `position: fixed;`.

Can you try `position: fixed;` for the left column, and I'll see if that works? It seemed to work for me when I tried it directly in the inspector tool.

**Comment by terracoda** [comment]
I just noticed that the PhET Bookmarks page has a working example of `position:fixed;`, but in that case, the right column is fixed, and the left column scrolls.

**Comment by jessegreenberg** [comment]
The behavior you described on Safari is expected with the current implementation. Here is a reference to sticky positioning: https://developer.mozilla.org/en-US/docs/Web/CSS/position#sticky_positioning.  But from comments above (https://github.com/phetsims/chipper/issues/742#issuecomment-560211343, https://github.com/phetsims/chipper/issues/742#issuecomment-587812710) it isn't working well on Safari and the whole a11y view scrolls on that platform.

If that isn't acceptable we can keep working in this issue.

I just tried to replace `sticky` with `fixed` on Safari but then the iframe occluded other things on the page, other layout changes would be necessary.

**Comment by jessegreenberg** [comment]
Based on the most recent comments in this issue I think this can be closed. Thanks for the work here everyone.
