### ISSUE TITLE
XHTML path changes

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#744]
I believe we discussed the changes for xhtml (ePUB-compatible) links in production builds as the following changes:

1. Change the `.html` suffix to `.xhtml`
2. Strip the `_phet` from the HTML on the build-server/website side of things (like how we do this for top-level HTML files).

Can we confirm that this works for developers, AND that vendors have switched to hard-versioned links?

**Comment by pixelzoom** [comment]
This change creates no issues for me.

**Comment by samreid** [comment]
I recall a conversation about this, and there were several constraints on the naming, but I cannot find a paper trail for it in GitHub issues or dev meeting minutes.  Maybe @mattpen remembers?  One constraint was regarding names served from the website (I think).

**Comment by mattpen** [comment]
> 1. Change the .html suffix to .xhtml

I don't recall any discussion of this point.  There is no code in the PhET project that depends on this though. 

> 2. Strip the _phet from the HTML on the build-server/website side of things (like how we do this for top-level HTML files).

The only thing I could find was this issue: https://github.com/phetsims/chipper/issues/706, which is lacking in discussion.  It looks like it was already solved and if it is not happening there is probably a regression.  I remember deciding this though, as our current practice is to strip the brand from any PhET brand production filenames.

**Comment by chrisklus** [comment]
From 3/14/19 dev meeting:

@jonathanolson is going to make this change.

**Comment by kathy-phet** [comment]
@jonathanolson - These 3 simulations will need release that supports both old and new naming. 
Reactants, Products, and Leftovers: https://phet.colorado.edu/sims/html/reactants-products-and-leftovers/latest/xhtml/reactants-products-and-leftovers_all_phet.html
Molarity: https://phet.colorado.edu/sims/html/molarity/latest/xhtml/molarity_all_phet.html
States of Matter: https://phet.colorado.edu/sims/html/states-of-matter/latest/xhtml/states-of-matter_all_phet.html?screens=1

After we deliver new names, we can ask client when we can drop support for the old names from these 3 sims.

**Comment by jonathanolson** [comment]
Finished the maintenance release for this, closing.
