### ISSUE TITLE
lint-all shouldn't use perennial/data/no-lint

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#745]
This has failed my linting process before, because repos like babel are run as a part of `lint-all`.  I'm not sure how to remedy this because chipper shouldn't be able to pull that list into it.

**Comment by zepumph** [comment]
@samreid do you have any ideas?

**Comment by samreid** [comment]
Can you help me reproduce the problem?  That may help me understand the problem better and make better recommendations.  Also, today on slack someone mentioned something like `.eslint-disable` files--maybe we would eliminate no-lint and use those instead?

**Comment by samreid** [comment]
Also, you are probably aware of this, but I do see this in chipper:

```js
    // TODO: don't use this from chipper! see https://github.com/phetsims/chipper/issues/726
    const eslintBlacklist = fs.readFileSync( '../perennial/data/no-lint', 'utf-8' ).trim().split( '\n' ).map( sim => sim.trim() );
```

**Comment by zepumph** [comment]
@samreid I'm sorry I got confused. The problem here is really that the `lint-all` task has to look over to perennial for the no-lint list.

Perhaps we should investigate eslint ignore files as a solution for this.

**Comment by zepumph** [comment]
`data/no-lint` no longer exists. Closing
