### ISSUE TITLE
Investigate git hooks

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#751]
From slack:

Chris Malley [2:04 PM]
PSA: It’s possible to add a pre-commit hook for git that runs commands before committing.  If you create `.git/hooks/pre-commit`, then add `grunt lint` to it, you will be prevented from committing anything that doesn’t pass lint.
Unfortunately you have to do this for every repo.  But consider doing it for the repo you’re working the most on now.

Sam Reid [2:05 PM]
Is the rule: if there is no output, the pre-commit check passed and ok to commit?  If there is some output then the check fails?  Does this integrate with IDE commits or only from command line?

Chris Malley [2:06 PM]
commands return a status code.
Works in WebStorm and command line. (edited) 

Jonathan Olson [2:06 PM]
Interesting. I presume it applies though to any branch, so I may avoid that (as certain automated maintenance things can commit without checking out the corresponding chipper version, so lint would fail out)

Chris Malley [2:07 PM]
Since it’s a file in .git/, yes, I assume it applies to all branches of the repo.
And `.git/hooks/pre-commit` can’t be checked in.
Interesting that WebStorm’s “Commit Changes” dialog has an option to specify something to run _after_ commit, but not before. (edited) 
That dialog is also where the “Run Git hooks” checkbox lives, btw.

Sam Reid [2:11 PM]
What dialog is where “run git hooks” lives?
Pasted image at 2019-04-03, 2:11 PM 

Chris Malley [2:12 PM]
If you don’t have any Git hooks, then there’s probably no checkbox.

Sam Reid [2:12 PM]
oh I see

Chris Malley [2:12 PM]
screenshot_1123.png 

This looks promising https://medium.com/netscape/git-hooks-with-husky-8b98f2556363.
Husky allows you to add pre-push and pre-commit hooks to package.json.

**Comment by samreid** [comment]
Self-assigning for investigation.

**Comment by samreid** [comment]
Things to check before commit:

- [ ] lint is passing
- [ ] images have appropriate licenses, see https://github.com/phetsims/circuit-construction-kit-common/issues/470
- [ ] build is successful (includes linting and media checks)
- [ ] unit tests passing

**Comment by samreid** [comment]
This article emphasizes the importance of keeping commits fast: https://proandroiddev.com/ooga-chaka-git-hooks-to-enforce-code-quality-11ce8d0d23cb

**Comment by samreid** [comment]
I'm no longer planning to investigate this in the near future.  I believe other developers on the team are aware of git hooks, though I'm not sure how widely they are used.  Unassigning for now.

**Comment by samreid** [comment]
To make it possible to edit .git/hooks in WebStorm, I went to Webstorm => Preferences => Editor => File Types => Exclude (GitExclude) and removed `.git`.  This shows "pre-commit" as a committable file though, so may need to be toggled off.

**Comment by samreid** [comment]
Next I added `grunt lint` to the pre-commit file.  With this checkbox checked:

![image](https://user-images.githubusercontent.com/679486/73962640-06a18b80-48cc-11ea-9ef3-6f76b2a30775.png)

Commit took around 3 seconds and reported this error:
![image](https://user-images.githubusercontent.com/679486/73962701-233dc380-48cc-11ea-8c86-8d22482a9d94.png)

With the checkbox unchecked, I am able to commit and the lint is bypassed.

**Comment by zepumph** [comment]
@samreid have you found an easy way to have all repos use a git hook for lint?

**Comment by samreid** [comment]
I haven't worked on that aspect yet.

**Comment by zepumph** [comment]
see https://github.com/phetsims/perennial/issues/171

**Comment by samreid** [comment]
We implemented git hooks and they have been working nicely, closing.
