### ISSUE TITLE
How should we access `grunt`?

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#753]
In many places, `grunt` is loaded as a module like this:
> const grunt = require( 'grunt' );

In a few places, `grunt` is passed through as an option like this:
> findDuplicates( grunt, repo, cache );

I need to access `grunt` in another file for https://github.com/phetsims/chipper/issues/724, wasn't sure which style to use.  I'm leaning toward the former due to its prevalence but thought I'd ask if we need to standardize on this, perhaps convert the latter cases to the former.

@pixelzoom what do you think?

**Comment by pixelzoom** [comment]
Looks like this applies to chipper and perennial. `require( 'grunt' );` is the most prevalent, and makes the most sense to me.  So if I were going to write new code, I'd go with `require( 'grunt' )`.   I'm ambivalent about whether to standardize.

**Comment by samreid** [comment]
It looks like `findDuplicates` is the only place where this problem is occurring.  I addressed that in the commit, closing.
