### ISSUE TITLE
Suggestion for README.md

### ISSUE THREAD

**Issue by joannaho** [phetsims/chipper#757]
I would like to suggest updating the acid-base-solutions/README.md git repo section so that it is easier to clone the multiple repo in one command. 

This is what I used to clone it which is less painful. 

```
git clone https://github.com/phetsims/acid-base-solutions.git && \
git clone https://github.com/phetsims/assert.git && \
git clone https://github.com/phetsims/axon.git && \
git clone https://github.com/phetsims/babel.git && \
git clone https://github.com/phetsims/brand.git && \
git clone https://github.com/phetsims/chipper.git && \
git clone https://github.com/phetsims/dot.git && \
git clone https://github.com/phetsims/joist.git && \
git clone https://github.com/phetsims/kite.git && \
git clone https://github.com/phetsims/phet-core.git && \
git clone https://github.com/phetsims/phetcommon.git && \
git clone https://github.com/phetsims/phetmarks.git && \
git clone https://github.com/phetsims/query-string-machine.git && \
git clone https://github.com/phetsims/scenery.git && \
git clone https://github.com/phetsims/scenery-phet.git && \
git clone https://github.com/phetsims/sherpa.git && \
git clone https://github.com/phetsims/sun.git && \
git clone https://github.com/phetsims/tambo.git && \
git clone https://github.com/phetsims/tandem.git
```

**Comment by mattpen** [comment]
> We should confirm whether git-bash and other commonly-used shells are compatible.

I frequently use `&& \` in git-bash on Win 10, bash on macOS terminal, and bash on RHEL 7.  It seems to have pretty robust support.

**Comment by joannaho** [comment]
> @joannaho Since this issue is relevant to all PhET sims, I'm going to transfer this issue from `acid-base-solutions` to the `chipper` repository, which contains build tools, including generation of `README.md` files.

@pixelzoom Thanks for considering.

**Comment by pixelzoom** [comment]
@joannaho We discussed this in our developer meeting yesterday.  Someone pointed out that you even without the change that you've suggested, you can select all of the `git clone` commands, paste them, into a shell, and all of the commands will be run.   So we're leaning towards not changing anything .  Can you confirm whether copy-pasting all command "as is" from the README.md works for you?  If it doesn't work, what OS and shell are you using?

**Comment by pixelzoom** [comment]
Hi @joannaho, checking in with you again.  See https://github.com/phetsims/chipper/issues/757#issuecomment-493539389 for requested feedback.

**Comment by joannaho** [comment]
@pixelzoom I confirmed that it worked copying straight to the command. This is good to know, i didn't know that would have worked. Thanks for checking!

**Comment by pixelzoom** [comment]
Excellent, then we will not make any changes and I'll close this issue.

Thanks again for creating this issue and contributing to PhET!
