### ISSUE TITLE
Out-of-date check for downloaded HTML5 sims

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/chipper#76]
Currently, if a user runs a .jar file of a sim they downloaded and we have published an update to that sim, the sim will check to see if there is a more recent version available and prompt the user.

We would like this behavior added to HTML5 downloaded sims.

**Comment by pixelzoom** [comment]
This feature request has little to do with chipper, so it has been relocated to https://github.com/phetsims/joist/issues/189. Closing.
