### ISSUE TITLE
Change to a cross-platform enforceable code formatting style

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#761]
I noticed that several simulation repos do not match the formatting specified in the code review checklist.  Should we switch to an open source formatting utility which can be used from command line, as plugins in different IDEs and usable from Sublime Text?  If our new formatter is usable from command line, it could be used to automatically (a) check that the code is formatted or (b) automatically format the code as a git hook or equivalent.

I haven't surveyed the literature yet, but one formatter that looked popular was https://github.com/prettier/prettier.

**Comment by samreid** [comment]
I tried running a file through prettier, and was not impressed with how it handled our code

![image](https://user-images.githubusercontent.com/679486/60398714-b7ff6800-9b18-11e9-939a-da095be7153e.png)

**Comment by pixelzoom** [comment]
I'd like to understand the root cause before deciding whether another tool for formatting is necessary.  Is this occurring because of some inherent different in how IntelliJ/WebStorm and Sublime handle formatting?  Or is this occurring because developers don't have their IDE configured to apply PhET formatting?

**Comment by samreid** [comment]
I'll look at one sim from each responsible dev (assuming each developer may have a different strategy for formatting) and report here:

Acid Base Solutions: 12 files changed on format
Area Builder: 13 files changed on format
Area Model Common: 0 files changed on format
Balloons and Static Electricity: 23 files changed on format
Bending Light: 43 files changed on format
Capacitor Lab: Basics: 9 files changed on format
Coulomb's Law: 8 files changed on format
Energy Forms and Changes: 12 files changed on format

It seems some (not all) of these changes are due to a change in our style.

**Comment by jessegreenberg** [comment]
I don't use any auto formatting currently with Sublime. I explored a couple options a few years ago but in the end couldn't find ways to configure what was available at the time to produce identical formatting to IntelliJ.

**Comment by pixelzoom** [comment]
How about adding a formatting task to the new `daily-grunt-work` task that @zepumph wrote?  There are likely to be many "formatting" commits related to code written by developers who are not using formatting in their IDE Editor.

**Comment by samreid** [comment]
It would be nice to have an automated formatting task.  What is `daily-grunt-work`?  I haven't heard of it before and can't find any references to it.

**Comment by pixelzoom** [comment]
> What is `daily-grunt-work`? ...

`perennial/bin/daily-grunt-work.sh`, mentioned in @zepumph's status report yesterday.

**Comment by samreid** [comment]
Some things to investigate:
https://www.jetbrains.com/help/idea/command-line-formatter.html
https://github.com/beautify-web/js-beautify

**Comment by jessegreenberg** [comment]
From 7/25/19 -

@samreid mentioned that he found jetbrains lets you format from the command line, maybe we can use this: https://www.jetbrains.com/help/idea/command-line-formatter.html. But it means people need to install jebrains products to do formatting.

@jessegreenberg will look into options and will report back in a week or two.

**Comment by jessegreenberg** [comment]
@samreid pointed out https://unibeautify.com/docs/about, which is a single spot to run potentially many beautifiers. For instance, it you could use js-beautify for javascript code and Autopep8 to format python code all through single experience using unibeautify.

**Comment by jessegreenberg** [comment]
I tried out js-beautify, it works pretty well. Testing on a joist/js/ProjectorModeCheckbox with the following config:
<details>

```json
{
  "indent_size": 2,
  "indent_char": " ",
  "indent_with_tabs": false,
  "editorconfig": false,
  "eol": "\n",
  "end_with_newline": false,
  "indent_level": 0,
  "preserve_newlines": true,
  "max_preserve_newlines": 10,
  "space_in_paren": true,
  "space_in_empty_paren": false,
  "jslint_happy": false,
  "space_after_anon_function": false,
  "space_after_named_function": false,
  "brace_style": "end-expand, preserve-inline",
  "unindent_chained_methods": false,
  "break_chained_methods": true,
  "keep_array_indentation": true,
  "unescape_strings": false,
  "wrap_line_length": 0,
  "e4x": false,
  "comma_first": false,
  "operator_position": "before-newline",
  "indent_empty_lines": false,
  "templating": ["auto"]
}
```
</details>

produces no changes to the file. I tried messing up the formatting and running js-beautify and it restored the file to what it is now in master.

There are a few things that will not be supported by js-beautify, namely these settings from phet-idea-codestyle.xml
```
    <option name="ALIGN_MULTILINE_BINARY_OPERATION" value="true" />
    <option name="ALIGN_MULTILINE_TERNARY_OPERATION" value="true" />
...
    <option name="IF_BRACE_FORCE" value="3" />
    <option name="DOWHILE_BRACE_FORCE" value="3" />
    <option name="WHILE_BRACE_FORCE" value="3" />
    <option name="FOR_BRACE_FORCE" value="3" />
```

I also don't see a way to break up objects into multiple lines without enforcing a hard limit on line length. For instance, if to break this up:
```js
      const labelNode = new Text( projectorModeString, { font: options.font, maxWidth: options.maxTextWidth, other: true, other: true, otherL: true } );
```
into this:
```js
const labelNode = new Text( projectorModeString, { 
  font: options.font, 
  maxWidth: options.maxTextWidth, 
  other: true, 
  other: true, 
  otherL: true
} );
```
It also has to wrap other lines that we aren't wrapped by IDEA formatting.

**Comment by samreid** [comment]
I found that `"break_chained_methods": false,` matches with our style (less changes) better than `true`

**Comment by jessegreenberg** [comment]
> is there a way to request formatting for a directory (recursive), or is the API based around single files?

I don't see a way to format recursively from their CLI, here are the options: https://github.com/beautify-web/js-beautify#options.

Over Slack @samreid also explored IDEA/format.sh and said
> The command launches IntelliJ IDEA, which formats the specified files and then quits.
> I tried running /Applications/WebStorm.app/Contents/bin/format.sh  and the first thing it told me is "Only one instance of WebStorm can be run at a time."
> I ran IDEA/format.sh on acid-base solutions and it took a total of 14 seconds

**Comment by samreid** [comment]
> I don't see a way to format recursively from their CLI

It seems later version of js-beautify support glob patterns.

**Comment by jessegreenberg** [comment]
Thanks, I wasn't familiar with what that was, I understand now. https://en.wikipedia.org/wiki/Glob_(programming)

**Comment by samreid** [comment]
There is much more progress on this topic in https://github.com/phetsims/phet-info/issues/150, closing as duplicate.
