### ISSUE TITLE
sim_es6_eslintrc_review usage and changes

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/chipper#765]
One of the steps in the code review checklist is 
> Does linting with "sim_es6_eslintrc_review.js" reveal any problems that should be fixed? (change eslintConfig in package.json and run grunt lint)

When I ran it for gravity-force-lab-basics it identified a number of lint issues mostly related to line length. We determined that these don't need to be fixed. Should the line length check be changed for sim_es6_eslintrc_review?

It also flagged `DerivedPropertyIO( NumberIO )`:
>A function with a name starting with an uppercase letter should only be used as a constructor (new-cap)

I am not sure I understand the purpose of this check - since it is for es6 are we hoping that all es6 sims will pass these rules? Or is this just a way to flag things that *might* be problems.

@samreid  and @zepumph are listed as authors, what do you think?

**Comment by samreid** [comment]
This was covered somewhat in https://github.com/phetsims/chipper/issues/734#issuecomment-500620356.  I recommend that I move @jessegreenberg's comment there and mark it for developer meeting.
