### ISSUE TITLE
grunt checkout-master

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#77]
After doing a deploy from a branch, you need to type this to get all your repos back to master:

> grunt checkout-shas --tomaster=true

It's usually a few months between when I need to do this. And I sometimes (ok, often) get tripped up by the fact that the convention for multi-word arguments is inconsistent ('checkout-shas' vs 'tomaster'). It's also odd to have a 'checkout shas' command where an arg basically says 'ignore the shas'.  So I usually end up typing 'grunt --help', and doing some copy-paste.

It would be much nicer to type:

> grunt checkout-master

**Comment by samreid** [comment]
I agree `grunt checkout-master` would be much nicer!

**Comment by pixelzoom** [comment]
I did a bit of cleanup, and added a `checkout-master` task. Assigning to @samreid to review.

**Comment by samreid** [comment]
I did a bit more cleanup above.  Note that projectName parameter was previously broken (so the sim itself was going to a certain sha--not sure if we want that generally).  Reassigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
@samreid your commit made it impossible to do `grunt checkout-shas --tomaster=true`. I don't think that's what you intended, since `grunt --help` still describes that as an option.   If you want to get rid of the 'tomaster' option, I'm OK with that, but the doc for the 'checkout-shas' task need to be updated.  And everyone (including 3rd-party developers) needs to be informed of that change.

**Comment by pixelzoom** [comment]
Let's get rid of the `tomaster` options, I've updated the help for `checkout-shas` to reflect this. There's really no reason to support that options, it complicates the code, and `checkout-master` is more convenient.  If you agree, please notify the other developers and 3rd parties. 

I also did a little bit of additional cleanup, as noted in the above commits.

**Comment by samreid** [comment]
> @samreid your commit made it impossible to do grunt checkout-shas --tomaster=true. I don't think that's what you intended, since grunt --help still describes tomaster as an option.

Yes, I did intend to remove it, just forgot to remove the --help documentation entry.  I'll review and notify collaborators.

**Comment by samreid** [comment]
I sent this email to our collaborators:

> Hi there.  On occasion it is necessary to check out repository code corresponding to a specific published version (for instance, when a simulation has been branched before release candidate testing and publication).  We have a task `grunt checkout-shas` which is described here:
https://docs.google.com/document/d/1odXkliRagq0zuf1_NdOtQ2BrkC9hwlISnPi2y-dKdrk/edit#bookmark=id.4fiykhwy31vk

> I wanted to write to let you know that the opposite task, which checks out the master version of repositories has been changed.  It used to be:
grunt checkout-shas --tomaster=true

> But now it is simply:
grunt checkout-master

> Please see here for more information:
https://github.com/phetsims/chipper/issues/77#issuecomment-70548725

> Sam

**Comment by samreid** [comment]
Finished review, just made 2 minor doc fixes above.  Everything else looks good, closing.
