### ISSUE TITLE
Document preload order dependencies

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#772]
From https://github.com/phetsims/chipper/issues/764

I said:

> (7) The current implementation requires that chipper-startup.js be loaded last, right? Should that be documented as such? What code could be safely added after this point without disrupting things?

@jonathanolson replied

> Not necessarily, there could conceivably be things in the future that we would want to run after the require.js step (say, if we ever wanted to move analytics code there, although it's currently a preload because there is no concept of "postload"). Should we document all of the order dependencies for the script order? For instance, initializationScript, splashScript, mipmapsJavaScript, ...productionPreloads, productionStringsJS, productionJS, productionStartupJS has some implicit information that I know about (mipmaps could only be swapped with preloads, but otherwise I think order changes would cause problems). build.json also doesn't have documentation about preload order that might be good to have. Do you have suggestions for how to document this? (Should this be it's own issue?). I added some bits of documentation in the commit above.

Should we document order dependencies in preloads?  If so, how?

**Comment by jonathanolson** [comment]
> Should we document order dependencies in preloads? If so, how?

I'm not sure about the importance. Maybe it's a good subject for dev meeting?

**Comment by pixelzoom** [comment]
This sounds like a job for assertions, not comments. If a piece of code requires that other things have been preloaded (dependencies), then there should be assertions that check for the existence of those dependencies.

**Comment by jonathanolson** [comment]
Keeping self-assigned, I'll add assertions to preloads/scripts to ensure things are loaded in the right order (for dependencies), with documentation.

**Comment by jonathanolson** [comment]
Added above, closing.
