### ISSUE TITLE
Should we call setAttribute with string, string?

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#774]
From #764 

I said
> (10) The signature of `setAttribute` is `(string,string)`, perhaps `element.setAttribute( 'font-size', 16 );` should be changed to have string 2nd arg?

@jonathanolson replied:
> The documentation says it converts non-strings to strings. Maybe this is similar to scenery's Text, where it converts them? This is potentially a change for a lot of scenery code (and maybe we should open a separate issue if changes are recommended).

MDN says:

> value
A DOMString containing the value to assign to the attribute. Any non-string value specified is converted automatically into a string.

This sounds somewhat contradictory, but seems legit.  I only noticed it because my IDE highlighted it:

![image](https://user-images.githubusercontent.com/679486/61137387-a441f300-a482-11e9-90c7-67afcdbb6cfb.png)

Also, IDEA's lib.dom.d.ts documents this like:

```js
    /**
     * Sets the value of element's first attribute whose qualified name is qualifiedName to value.
     */
    setAttribute(qualifiedName: string, value: string): void;
```

It doesn't seem like a very big deal, but I'm leaning toward recommending we use string for this.   But it should be decided as a team.

**Comment by samreid** [comment]
I guess one good reason to make our call sites call with (string, string) is to protect ourselves from the (unlikely) case that a browser changes how it coerces something to a string.  (Maybe one day a bug will creep into a browser where they change radix or something).

**Comment by jonathanolson** [comment]
Fixed the above case. Is it worth finding all of the other cases where this is done proactively? Or can this be left as something in our code-review guidelines?

**Comment by samreid** [comment]
Using this regular expression, I spotted around 29 things that could be changed: `\.setAttribute\( \'.*\', [0-9]` . Many sim occurrences are setting the value to 0, so that wouldn't be a concern for units.  Many developers either had no preference or recommended to change.

**Comment by samreid** [comment]
I addressed the number literals in the above commit.  I did not try to address cases like `setAttribute('height',someObject.value)`.  I wasn't sure if some sites should include 'px' or not.  But I tested a few sims and aqua harness and I think this issue can be closed.
