### ISSUE TITLE
Questions about string plugin

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#776]
@jessegreenberg and I glanced at the string plugin in order to instruct how we proceed with https://github.com/phetsims/rosetta/issues/193. We ended up having a few questions about how it was implemented.

1. Why are "fallback" strings not using calling `chipper.mapString` to support `?stringTest`
2. `getWithCache` was calling `onload.error` even though `onload` isn't defined in that function. @jessegreenberg and I moved logic so that that error is called correctly. Does this seem alright?
3. I can't seem to tell if there is a difference between throwing an Error or calling `onload.error`. I can't really seem to differentiate why one would be used over the other, even though I understand from the documentation that "onload.error() can be called . . . if the plugin detects an error condition that means the resource will fail to load correctly." Wouldn't any error that the plugin would want to throw meet that criteria? I would like to use `onload.error()` more.
4. getWithCache has a `headers` option, but it seems like `{ accept: 'application/json' }` could just be baked into the method, simplifying the load function a bit.

I see many commits from @pixelzoom and @samreid in this plugin, though it says @samreid is the author. Assigning over to him.

**Comment by samreid** [comment]
> Why are "fallback" strings not using calling chipper.mapString to support ?stringTest

string.js should be changed to call mapString on the fallback, good catch!

> getWithCache was calling onload.error even though onload isn't defined in that function. @jessegreenberg and I moved logic so that that error is called correctly. Does this seem alright?

Yes, thanks for the fix!

> I can't seem to tell if there is a difference between throwing an Error or calling onload.error. [...]

I don't know why requirejs is implemented this way.  The docs here at https://requirejs.org/docs/plugins.html don't explain much more than we already know.  I didn't look into the requirejs source to try to understand why it is done this way.

> getWithCache has a headers option, but it seems like { accept: 'application/json' } could just be baked into the method, simplifying the load function a bit.

Yes, please simplify it as you prescribed.  I believe the way it was initially written this way was because the first draft was adapted from https://github.com/requirejs/text/blob/master/text.js

**Comment by zepumph** [comment]
That's excellent news @samreid. Thanks for the quick response. I made some updates, and converted to es6. 

I tested in requirejs mode and built mode:
* `?locale=aa&stringTest=long` to note that the fallback strings are mapped now
* `?locale=de&stringTest=long` to see that nothing is problematic with another locale that has translation.
* `?locale=en&stringTest=long`
* and all three above without the stringTest. 

Things seem to be working well. One thing I discovered during this is that the `?strings` query parameter is only supported in requirejs mode. I added doc in init globals for that, but let me know if you think that should be updated in any way. Otherwise please review my changes. Can you think of any problems with the above commits?

**Comment by zepumph** [comment]
>One thing I discovered during this is that the `?strings` query parameter is only supported in requirejs mode.

This is not true. though it is on a branch, see phet.chipper.getStringForBuiltSim (or phet.chipper.strings.get on master). This is supported.

Back to @samreid for final commit spot check.

**Comment by zepumph** [comment]
@samreid, in regards to this spot check, this is now on master.

**Comment by samreid** [comment]
How much of https://github.com/phetsims/chipper/commit/0af3ccecd94b32c07c6c379ad8f28fbd6b60ef54 survived the ES6 module migration?  What, if anything, still warrants review?  Please close if everything was completed in other issues.
