### ISSUE TITLE
rename grunt tasks for jshint

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#78]
In Gruntfile.js, we currently have:

> grunt.registerTask( 'lint-sim', 'lint just the sim\'s js files', [ 'jshint:simFiles' ] );
grunt.registerTask( 'lint-common', 'lint all of the common js files', [ 'jshint:commonFiles' ] );
grunt.registerTask( 'lint', 'lint the sim code and the common code', [ 'lint-sim', 'lint-common' ] );

Questions:

(1) Now that we can run this from common-code repositories, 'lint-sim' seems a little wrong. Suggestions on a better name? lint-self? lint-this? lint-me?

(2) 'lint-common' is also a little wrong, since for some sims that means linting another sim repo. And now the we can lint from any repo, is doesn't seem all that useful. If we don't need this, it would remove a bit of ugliness (line 129) from Gruntfile.js. My vote would be to delete this target.

Comments?

**Comment by pixelzoom** [comment]
I think there's a bug in lint-common. If do 'lint-common' on a repo that has lint problems, it should report nothing. But it seems to be checking all dependent repos, then checking the 'self' repo.  So there's some work being duplicated in both lint-common and lint (which uses lint-common).

**Comment by pixelzoom** [comment]
Indeed, there is a bug with how commonFiles is created. It reads phetLibs, but doesn't filter out the current repo name. Here's the code, chipper.Gruntfile line 124:

```js
// source files for common-code dependencies.
        // phetLibs is a string of repo names, space separated.
        // split converts the string to an array of repo names.
        // map then converts each repo name to the form '../repo/js/**/*.js'.
        // includes an exclusion for kite/js/parser/svgPath.js, which is auto-generated
        commonFiles: [ _.map( pkg.phetLibs.split( ' ' ), function( repo ) { return '../' + repo + '/js/**/*.js'; } ), '!../kite/js/parser/svgPath.js' ],
```

**Comment by samreid** [comment]
> (1) Now that we can run this from common-code repositories, 'lint-sim' seems a little wrong. Suggestions on a better name? lint-self? lint-this? lint-me?

Perhaps `lint-project`?  I'm also okay with `lint-self`.

**Comment by pixelzoom** [comment]
Now that we can lint common code repos independently of sims, `lint common` seems like something we can drop. How about if we collapse to these 2 tasks? :

`grunt lint`: lints only the current repo

`grunt lint-all`: lints the current repo and all of its dependencies

During daily development, we'll typically be doing `grunt lint`.  `grunt build` will do `'lint-all`, and we may want to check that manually on occasion.

**Comment by samreid** [comment]
Sounds great, I agree with `grunt lint` only linting the repo, and `grunt lint-all` linting the repo and its dependencies.

**Comment by jonathanolson** [comment]
The proposal sounds fine.

**Comment by pixelzoom** [comment]
Change completed. PhET and 3rd-party developers notified via email.  Since this was a trivial change, I'm going to close this issue. Feel free to review.
