### ISSUE TITLE
support reportUnusedStrings for nested a11y strings

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#780]
From https://github.com/phetsims/rosetta/issues/193. This is an important piece of the build process, and we should get it working with the new nested strings under the `a11y` key. Promoting todo.

**Comment by zepumph** [comment]
This has been implemented, and should be reviewed as part of https://github.com/phetsims/rosetta/issues/193

**Comment by samreid** [comment]
@zepumph and I reviewed this together and agreed it looks good, thanks!   Closing.
