### ISSUE TITLE
Support comments in string files

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#781]
This was brought up in https://github.com/phetsims/rosetta/issues/193, but lost a bit of steam. From an a11y point of view, I think that this isn't so much of a necessity now that we have support for nesting strings. Still I'm going to create an issue to track it.

**Comment by zepumph** [comment]
@samreid and I discussed this, and we think that comments just work out of the box right now. The important piece of understanding here is that any object key that isn't used in a string key specifically required from the sim is just ignored. It is ignored because the string plugin on building populates the list of used string for the sim as a master list. see string.js `global.phet.chipper.strings`. `getStringMap` uses that global, and then rosetta just uses the output of getStringMap in the built HTML file itself. 

With this in mind the important piece is really to come up with a convention for comments so that they don't get out of hand. perhaps calling them "_comment" or something.

Then we should also make sure to test the whole stack fully to make sure things are properly ignored.

Removing the priority label because perhaps there won't be much work to make sure this is working.

**Comment by samreid** [comment]
We may one day want to leverage comments or something like it in the rosetta UI.

**Comment by zepumph** [comment]
Over in https://github.com/phetsims/rosetta/issues/193#issuecomment-536762104 I committed a bug. While testing if comments would work as expected over here, I found it and fixed it.

I can say now quite confidently that the requirejs/built strings completely ignore anything that isn't the "value" key in objects.

As a reminder, here is the built string map that is compiled when the sim is built:
[stringMap.txt](https://github.com/phetsims/chipper/files/3699949/stringMap.txt)

Anything in the en json files that isn't the "value" key is ignored. Here is some sample stuff I had in there when I built the sim to get the above map:

```js
 "a11y": {
    "chemistryBook": {
      "value": "Chemistry book"
    },
    "__comment": "hello goose",
    "comment2": {"value":  "sup"}, // flagged as an unused string still
    "//": {"value":  "sup"}, // flagged as an unused string still
    "__comment3": 432,
    "__comment4": 43.43212,
    "__comment5": null,
    "//": "hello goose",
    "zoomedInChemistryBook": {
      "value": "zoomed-in Chemistry book",
      "//": "hello goose"
    },
    "grabButtonHelpText": {
      "//": "hello goose 2",
      "value": "Look for grab buttons. Once grabbed, use letter keys W, A, S, or D to move book or zoomed-in book up, left, down, or right."
    }
}
```

I think we should stick with just one name and add comments if desired. For clarity and simplicity, I think that should be `_comment`.

@samreid please review. Can we go with that, close this issue, and open a new one if that doesn't completely handle our needs?

**Comment by samreid** [comment]
`"_comment"` sounds great to me, and I think rosetta will be able to leverage it and show comments in its final tree-structured UI.  I'll close.
