### ISSUE TITLE
Sim specific PhET-iO wrappers not being copied during build

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#785]
Discovered in https://github.com/phetsims/phet-io-wrapper-sonification/issues/84.  It seems the ability to build a sim-specific PhET-iO wrapper was dropped, probably circa https://github.com/phetsims/chipper/commit/34923a2672f09d714b9ac142aa5ecec289a06e49 (part of https://github.com/phetsims/chipper/issues/680) or thereabouts.

**Comment by samreid** [comment]
Proposed fixes pushed, it seemed straightforward. @zepumph can you please review?

**Comment by KatieWoe** [comment]
CT seems to be showing errors.  @zepumph mentioned it may be related to this issue.

**Comment by zepumph** [comment]
The changes look good. Thanks @samreid. Review from here:

* >  `const simSpecificWrappers = packageObject.phet && packageObject.phet[ 'phet-io' ] && packageObject.phet[ 'phet-io' ].wrappers ? packageObject.phet[ 'phet-io' ].wrappers : [];`

  Instead you could use `_.at(packageObject, "phet['phet-io'].wrappers")` which will return `[undefined]` if it doesn't exist. Just a thought, no strong preference.

* there are still dedicated wrappers in `chipper/data/wrappers`. They should be removed and the same process done to them. I made a commit to review.

**Comment by samreid** [comment]
I considered

```js
// A
_.at( packageObject, "phet[ 'phet-io' ].wrappers" );// eslint-disable-line 

// B
_.at( packageObject, 'phet[\'phet-io\'].wrappers' );

// C
_.at( packageObject, 'phet["phet-io"].wrappers' );
```

I prefer the former because searches for `phet[ 'phet-io' ]` won't be missed.  However, I realized that we would need to guard on `undefined` to prevent processing that.  Maybe simpler to improve formatting of the prior strategy?

**Comment by samreid** [comment]
Also, I reviewed the changes that moved classroom activity, lab book and arithmetic wrappers out.  Tested building and running arithmetic's wrapper.  Looks great, closing.

**Comment by zepumph** [comment]
No need to reopen if you still like your way more, I just wanted to post what the difference would be. I think I prefer the latter, but likely only because `_.at` is new and fancy to me.

```
  // Add sim-specific wrappers
  const simSpecificWrappers = packageObject.phet &&
                              packageObject.phet[ 'phet-io' ] &&
                              packageObject.phet[ 'phet-io' ].wrappers ?
                              packageObject.phet[ 'phet-io' ].wrappers : [];

// vs

  const simSpecificWrappers = _.at( packageObject, 'phet[ "phet-io" ].wrappers' )[ 0 ] ?
                              _.at( packageObject, 'phet[ "phet-io" ].wrappers' )[ 0 ] : [];
```

**Comment by samreid** [comment]
It's a good use of `_.at` and much more concise, but my concern is that it impedes text-searchability of the term `phet[ 'phet-io' ]`.
