### ISSUE TITLE
/js/templates should be prefixed with `.template`

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#793]
While poking around this folder with @samreid, we felt like js template in this file shouldn't be named as actual `.js` files. This will avoid WebStorm miss highlighting, and increase clarity.

**Comment by zepumph** [comment]
I renamed one of the files in templates and we lost the webstorm formatting. To me this felt like a deal breaker:

![image](https://user-images.githubusercontent.com/6856943/65721476-9b5ec780-e056-11e9-9550-086db9890b50.png)


I feel fine about turning off inspections in Webstorm, and having lint ignore the templates dir. @samreid please make a recommendation if you feel differently.

**Comment by samreid** [comment]
I see the value in correct formatting.  I wonder if it would be worth the effort to make the template actual correct JavaScript code?

```js
/* eslint-disable */
window.phet = {};
window.phet.chipper = {};
window.phet.chipper.project = '{{PHET_PROJECT}}';
window.phet.chipper.version = '{{PHET_VERSION}}';
window.phet.chipper.buildTimestamp = '{{PHET_BUILD_TIMESTAMP}}';
window.phet.chipper.brand = '{{PHET_BRAND}}';
window.phet.chipper.locale = '{{PHET_LOCALE}}';

// This simulation uses following third-party resources.  The following code block describes each resource
// and provides its licensing information.  The START and END tags make it easy to automatically parse
// and the entries are in JSON.  See getLicenseEntry.js for information about the attributes in each entry.
// {{PHET_START_THIRD_PARTY_LICENSE_ENTRIES}}
window.phet.chipper.thirdPartyLicenseEntries = '{{PHET_THIRD_PARTY_LICENSE_ENTRIES}}';
// {{PHET_END_THIRD_PARTY_LICENSE_ENTRIES}}
window.phet.chipper.dependencies = '{{PHET_DEPENDENCIES}}';
window.phet.chipper.strings = '{{PHET_STRINGS}}';
window.phet.chipper.isDebugBuild = '{{PHET_IS_DEBUG_BUILD}}';
```

Note in the latter cases the string to be replaced would be all of `'{{PHET_IS_DEBUG_BUILD}}'` instead of just `{{PHET_IS_DEBUG_BUILD}}`

**Comment by zepumph** [comment]
That seems confusing to me, I would then expect whatever was being filled in to be inside the string. I don't think that 

>I see the value in correct formatting.

Does this mean that when you change the filename to be `*.js.template` you still have js formatting?

**Comment by samreid** [comment]
> I see the value in correct formatting.

I mean I agree it is valuable to syntax highlight as a JS file, and I was looking for a way to have the template variables be syntactically correct.

**Comment by samreid** [comment]
@zepumph what do you recommend for this issue?

**Comment by zepumph** [comment]
There are multiple files suffixed in `.js` in which you currently go to the file in webstorm and it is underlined as having a syntax error. I would recommend that all of these become `.js.template` files for clarity, since they aren't actually runnable `js` files.

**Comment by samreid** [comment]
In https://github.com/phetsims/chipper/issues/793#issuecomment-535667362 you described that losing all formatting is undesirable and I agree.  I rank both "invalid *.js" and "valid *.js" (like https://github.com/phetsims/chipper/issues/793#issuecomment-537136669 ) higher than "*.template" which has no formatting at all.
