### ISSUE TITLE
Can `phet.chipper.stings.get` and `string!getStringFromFileContents` be simplified?

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#796]
From work with @samreid over in https://github.com/phetsims/chipper/issues/786, I wonder if these two functions can be combined somehow. These two functions do similar things, but one for requirejs and the other for built mode. I'm especially looking at how both call mapString. Perhaps this could be simplified into a function in ChipperStringUtils.js or something.

**Comment by zepumph** [comment]
In the above commit I did the following work on the a11ystring-plugin branch:
* moved `phet.chipper.strings.get` to `initialize-globals`, 
* renamed it to getStringForBuiltSim for clarity
* deleted `chipper-strings.js`
* simplified `mapString` because it doesn't need stringTest parameter

The goal of these changes was to help with clarity, and to simplify the code that is run between built mode and requirejs. Both call mapString, but before it was pretty confusing how the process for loading the built strings worked. I think in-lining the method previously defined in `chipper-strings.js` into init globals makes it simpler and nicer. Furthermore I added an assertion to make sure that this method is only ever called when the sim is built. 

Note this is all on the branch, because there are too many changes about strings on that branch for me to touch master right now.

@jonathanolson you have the most commits on chipper-strings.js, would you mind reviewing? Does the change to `mapString` look alright also?

**Comment by jonathanolson** [comment]
I checked over the commit. It looks good, and I like the changes. Separating out the second parameter to a closure variable seems perfect.

**Comment by zepumph** [comment]
Excellent! I will close this issue, but it won't be on master for now. see #777
