### ISSUE TITLE
A11y View focus issue

### ISSUE THREAD

**Issue by terracoda** [phetsims/chipper#803]
I have been noticing some strange things in the A11y View. The alignment of the mouse hover state is off by quite a bit sometimes.

I've noticed this in Molarity, but can't easily reproduce it.

However, yesterday while using GFL (or maybe GFLB), I noticed it a lot with the position/distance sliders. I click on m1 or m2 to move it and then it doesn't let go when I stop dragging the mass. At the end of the drag, moving my mouse continues to move the mass even when I am not clicking on it.

**Comment by zepumph** [comment]
@twant has been taking on a few a11y view issues. @twant let me know if you want help.

**Comment by jessegreenberg** [comment]
This may be a known behavior with iframes in general. If you click on something, then move your mouse out of an iframe and then release your mouse, objects aren't released. In this state, move your mouse back into the sim and objects will continue to drag.

For example, this happens here: http://phettest.colorado.edu/gravity-force-lab-basics/build/phet/gravity-force-lab-basics_en_iframe_phet.html

Do you think this was the case you encountered @terracoda or was it something else?

**Comment by zepumph** [comment]
>This may be a known behavior with iframes in general. If you click on something, then move your mouse out of an iframe and then release your mouse, objects aren't released. In this state, move your mouse back into the sim and objects will continue to drag.

Right! Good catch. I agree, this is expected if you click in the sim, and the release ourside the sim. The reason is that the iframe (the sim) will never get the mouse up event, because that happens outside of its little home.

**Comment by jessegreenberg** [comment]
🏠

**Comment by terracoda** [comment]
@jessegreenberg, I didn't notice that I was moving outside the frame, but yes, that is exactly what is happening in GFL.

Thanks for the explanation.

**Comment by terracoda** [comment]
And it is the same issue in Molarity. I must have slid outside the frame without realizing it.

**Comment by terracoda** [comment]
I am closing, since this is not a bug.

**Comment by jessegreenberg** [comment]
Thanks @terracoda sounds good - I am not sure if the hovering issues you mentioned were different but if they are and show up again please feel free to open another issue.
