### ISSUE TITLE
branch: a11y-view-improvements

### ISSUE THREAD

**Issue by twant** [phetsims/chipper#809]
This branch is for https://github.com/phetsims/chipper/issues/742 and https://github.com/phetsims/chipper/issues/740. When these are resolved, we'll close the branch.

**Comment by zepumph** [comment]
@twant can you please summarize the work done in this issue so far, and describe if anything here should try to make its way onto master?

**Comment by twant** [comment]
Right now, most of these changes are almost ready to be pulled onto master. The issue right now is with the way that various browsers handle sticky elements. I'm working on modifying the layout for Safari, which doesn't support `position: sticky` without `display: block`. I am going to work on this more this coming week, so I will let you know when it's ready for review and merge into master, @zepumph .

**Comment by twant** [comment]
@zepumph just pushed some changes -- let's discuss on Tuesday if that works for you!

**Comment by zepumph** [comment]
Finished up with https://github.com/phetsims/chipper/issues/742. Closing
