### ISSUE TITLE
Eliminate useless constructors

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#810]
Lint detected that our source code currently has 23 useless constructors, using the "no-useless-constructor" rule described here: https://eslint.org/docs/rules/no-useless-constructor

I manually spotted some of these during Gravity and Orbits code review, and, in my opinion, these should be deleted and we should turn on this rule.

Raising for developer meeting to see if there are any objections.

Here is the list of current issues:

```
~/github/gravity-and-orbits$ grunt lint-everything --disable-eslint-cache
Running "lint-everything" task
(Forwarding task to perennial)
Running "lint-everything" task

/Users/samreid/github/balloons-and-static-electricity/js/balloons-and-static-electricity/view/vibrationController.js
  19:5  error  Useless constructor  no-useless-constructor

/Users/samreid/github/circuit-construction-kit-ac/js/ac-voltage/model/ACVoltageModel.js
  21:5  error  Useless constructor  no-useless-constructor

/Users/samreid/github/circuit-construction-kit-ac/js/lab/model/LabModel.js
  22:5  error  Useless constructor  no-useless-constructor

/Users/samreid/github/circuit-construction-kit-ac/js/rlc/model/RLCModel.js
  22:5  error  Useless constructor  no-useless-constructor

/Users/samreid/github/circuit-construction-kit-dc/js/intro/model/IntroModel.js
  21:5  error  Useless constructor  no-useless-constructor

/Users/samreid/github/circuit-construction-kit-dc/js/lab/model/LabModel.js
  20:5  error  Useless constructor  no-useless-constructor

/Users/samreid/github/coulombs-law/js/common/view/describers/CoulombsLawForceDescriber.js
  18:5  error  Useless constructor  no-useless-constructor

/Users/samreid/github/coulombs-law/js/common/view/describers/CoulombsLawPositionDescriber.js
  17:5  error  Useless constructor  no-useless-constructor

/Users/samreid/github/density-buoyancy-common/js/common/model/FixedTimestepEngine.js
  16:5  error  Useless constructor  no-useless-constructor

/Users/samreid/github/energy-skate-park/js/energy-skate-park/common/model/DebugTracks.js
  23:5  error  Useless constructor  no-useless-constructor

/Users/samreid/github/gas-properties/js/explore/view/ExploreViewProperties.js
  21:5  error  Useless constructor  no-useless-constructor

/Users/samreid/github/gas-properties/js/ideal/view/IdealViewProperties.js
  21:5  error  Useless constructor  no-useless-constructor

/Users/samreid/github/interaction-dashboard/js/elements-used/model/ElementsUsedModel.js
  16:5  error  Useless constructor  no-useless-constructor

/Users/samreid/github/john-travoltage/js/john-travoltage/view/vibrationController.js
  33:5  error  Useless constructor  no-useless-constructor

/Users/samreid/github/models-of-the-hydrogen-atom/js/common/model/AlphaParticle.js
  23:5  error  Useless constructor  no-useless-constructor

/Users/samreid/github/models-of-the-hydrogen-atom/js/spectra/view/SpectraViewProperties.js
  18:5  error  Useless constructor  no-useless-constructor

/Users/samreid/github/natural-selection/js/common/model/LimitedFood.js
  16:5  error  Useless constructor  no-useless-constructor

/Users/samreid/github/natural-selection/js/common/model/ToughFood.js
  16:5  error  Useless constructor  no-useless-constructor

/Users/samreid/github/natural-selection/js/common/model/Wolves.js
  16:5  error  Useless constructor  no-useless-constructor

/Users/samreid/github/natural-selection/js/intro/model/IntroModel.js
  22:5  error  Useless constructor  no-useless-constructor

/Users/samreid/github/natural-selection/js/lab/model/LabModel.js
  23:5  error  Useless constructor  no-useless-constructor

/Users/samreid/github/simula-rasa/js/simula-rasa/model/SimulaRasaModel.js
  20:5  error  Useless constructor  no-useless-constructor

/Users/samreid/github/tappi/js/demo/common/model/BasicsModel.js
  20:5  error  Useless constructor  no-useless-constructor

✖ 23 problems (23 errors, 0 warnings)
Fatal error: 23 Lint Errors
```

**Comment by pixelzoom** [comment]
Until a benefit is identified, I object. 

The ones in natural-selection are stubs that will be filled out.

**Comment by pixelzoom** [comment]
I also disagree that a constructor that delegates to super is "useless".  It saves me the task of having to visit the superclass to identify the subclass' constructor signature and parameter doc.   

For example:

```js
  class ExploreViewProperties extends IdealGasLawViewProperties {

    /**
     * @param {Tandem} tandem
     */
    constructor( tandem ) {
      super( tandem );
    }
  }
```

versus:

```js
 class ExploreViewProperties extends IdealGasLawViewProperties {}
```

**Comment by samreid** [comment]
I see that there are cases where it would be nice to keep those constructors.  But looking over the list above, several cases do not exercise any of those advantages.  For example, the first element in the list:

```js
  class VibrationController {
    constructor() {}
```

Do you recommend we keep that constructor?  Add documentation to it?  Eliminate it?

**Comment by pixelzoom** [comment]
I don't have any strong feelings about empty constructors, and don't see any obvious benefits to deleting them. They're not my style, but if another developer finds them to be useful for some reason, then I would leave them be.

**Comment by samreid** [comment]
Thanks, perhaps it is worth raising for developer meeting discussion, to make sure everyone is aware that constructors automatically "pass through" and to make sure enough developers agree about not checking for this during lint.

**Comment by jessegreenberg** [comment]
I don't have a preference but appreciate knowing that there is a default constructor, I did not know that.

**Comment by samreid** [comment]
We discussed at dev meeting today.  @zepumph said he would prefer to enable this lint rule.  @pixelzoom said it would be frustrating to need to look in the parent type to see the constructor API.  @samreid pointed out that we often need to look in the parent types anyways to look up the options API, and we do not want to duplicate those in the subclasses.  We ran out of time and will schedule for another dev meeting.

**Comment by pixelzoom** [comment]
On 11/6/19, I said:
> Until a benefit is identified, I object.

I still waiting to hear what the benefit of this is.

**Comment by samreid** [comment]
We are talking about code and documentation that:
* is redundant and has no functional effect at runtime
* has to be maintained
* has the potential to become out of sync

The benefit of removing this code is: less to maintain, less things to get out of sync.  I don't feel very strongly one way or the other, but when I came across code like this during code review my instinct was to delete it based on these bullet points.

However, it appears the rule is imperfect.  CoulombsLawForceDescriber.js defines:

```js
    constructor( model, object1Label, object2Label, positionDescriber ) {
      super( model, object1Label, object2Label, positionDescriber );
    }
```

which chains to the super constructor:
```js
constructor( model, object1Label, object2Label, positionDescriber, options ) {
```

[ESLint](https://eslint.org/docs/rules/no-useless-constructor) flags CoulombsLawForceDescriber's constructor as "useless", and describes it in the documentation as 

> This rule flags class constructors that can be safely removed without changing how the class works.

However, it seems like `CoulombsLawForceDescriber` strips out the `options` and would not have the same effect when called with options.

**Comment by pixelzoom** [comment]
> * is redundant and has no functional effect at runtime

Parenthesis around expressions also meet this definition.  For example `( a && b ) || ( c && d)` could be written `a && b || c && d`.  The parens add clarity, and I prefer to use them when I feel that it improves readability.  Would you suggest that we also 

> * has to be maintained
> * has the potential to become out of sync

I'm skeptical (to say the least) that removing these constructor would improve maintainability or reduce the potential to become out of sync. In fact, I can easily construct a scenario where the absence of an explicit constructor actually makes it more likely to become out of sync.  For example, `A extends B`, and `A` has an implicit constructor. I make a change to `B` constructor, but don't have to change anything about `A`, so I forget to change `new A` call sites.

Finally, your `CoulombsLawForceDescriber` points to a more general case that this lint rule is incapable of handling:

```
class A {
   /**
    * @param a
    * @param [b] - optional!
    */
  constructor( a, b );
}

class B extends A {
   /**
    * @param a
    */
   constructor( a ) {
     super( a );
  }
}
```

Superclass `A` has optional parameter `b`.  And I wish to provide a narrower interface for subclass `B`, excluding the optional parameter `b`.   The lint rule apparently has no knowledge of the superclass' constructor signature, and makes it's "useless" determination solely based on number of parameters, whether they match the actual constructor signature or not.

**Comment by pixelzoom** [comment]
Here's another example that the lint rule is flagging:

```js
   * @constructor
   */
  class SimulaRasaModel  {

    /**
     * @param {Tandem} tandem
     */
    constructor( tandem ) {
      //TODO
    }
```

The lint rule is presumably complaining because there's no executable code in the body of the constructor.   But this is our template for new sims, outfitted with the `tandem` parameter that all `*Model` classes should have.   And as a developer,  I understand that the `//TODO` means that I'll be fleshing out the body of the constructor.  This is not a "useless" constructor.

**Comment by samreid** [comment]
Thanks for discussing this, I'm convinced we should not enable the lint rule.  Should we go one step further and say that we require or recommend each type has a constructor?  Or would it be better to suit developer discretion on a case-by-case basis?

**Comment by pixelzoom** [comment]
Developer discretion.

**Comment by samreid** [comment]
Thanks, we can leave this marked for wrapping up discussion at next dev meeting.

**Comment by zepumph** [comment]
We think that this is not useful as a lint rule, especially since it has a bug. Even if it wasn't buggy, developer discretion would still be preferred.

We agree developer discretion is the way to go!!! Closing
