### ISSUE TITLE
Custom lint rules should be linted as node code

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#811]
While working on https://github.com/phetsims/chipper/issues/791, they should use `node_eslint.js`

**Comment by zepumph** [comment]
@jessegreenberg please review this update, though small. What do you think?

**Comment by jessegreenberg** [comment]
Linting custom rules sounds like a great idea. I don't feel like I know enough to review the actual change in https://github.com/phetsims/chipper/commit/5c0e15865c15a3a01973e7bd7481bd81bf8ac606, were there any decisions to be made or is it pretty cut and dry for how to enable this?

**Comment by zepumph** [comment]
>were there any decisions to be made or is it pretty cut and dry for how to enable this?

I realized that adding the node env declaration is the pattern of doing things if you don't already set that by the eslintrc file. `node_eslintrc.js` already sets the proper environment variables allowed. Thus we don't need that, and only need to declare "use strict". I updated things above. Anything else here?

**Comment by jessegreenberg** [comment]
Sounds good to me, thanks! Not that I know of, closing.
