### ISSUE TITLE
Add Array.from polyfill 

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#817]
Over in https://github.com/phetsims/perennial/issues/153 we are going to look into a robust polyfill, but to help unblock publication, we think that adding a specific polyfill for `Array.from` may be best short term.

**Comment by zepumph** [comment]
Noting here that adding Array.from polyfill did fix build IE, and things are working in my local copy build.

**Comment by zepumph** [comment]
The above commit should fix this for phet builds and for scenery builds. Now I just need to commit `grunt update` to add the new preload.

**Comment by zepumph** [comment]
@jonathanolson, currently scenery is actually not supported, because I couldn't figure out how to get around the `checkNamespaces` assertions for trying to include the preload via `requirejs`. Any ideas? 

Phet builds should be working though.

**Comment by zepumph** [comment]
@jonathanolson, currently scenery is actually not supported, because I couldn't figure out how to get around the `checkNamespaces` assertions for trying to include the preload via `requirejs`. Any ideas? 

Phet builds should be working though.

**Comment by zepumph** [comment]
Confirmed fixed in https://phet-dev.colorado.edu/html/gravity-force-lab/2.2.0-dev.17/phet/gravity-force-lab_all_phet.html

**Comment by zepumph** [comment]
@jonathanolson can you please review also while provided ideas about how to support scenery build.

**Comment by zepumph** [comment]
We are interested as a developer team in getting this unblocked for publication quickly. @pixelzoom gave a live review, and mentioned that we may want to worry about the license. I'll take it from here. 

I will move this to sherpa, because Array.from is a licensed file, and other polyfill items will be under a different license.

**Comment by zepumph** [comment]
This was implemented above. @pixelzoom would you please review. Note that the scenery specific stuff that I originally wanted @jonathanolson to review has been moved to https://github.com/phetsims/chipper/issues/819, so @pixelzoom feel free to close if there is nothing you see here.

**Comment by pixelzoom** [comment]
Looks great, closing.
