### ISSUE TITLE
support custom preloads to standalone builds like scenery

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#819]
From https://github.com/phetsims/chipper/issues/817, it would be good to have a way to add the `Array.from` polyfill into scenery/dot/kit builds etc.

**Comment by zepumph** [comment]
Poking around in buildStandlone.js, I see that there is a hardcoded base list so I can just add the polyfill to that, but I think we could also support custom items from each package.json. I'll implement

**Comment by zepumph** [comment]
@jonathanolson please review these changes. Do they sound good for supporting https://github.com/phetsims/chipper/issues/817 in scenery etc, AND does it seem like a good change to support `phet.preload` from package.json for standalone builds?

**Comment by jonathanolson** [comment]
This looks great! Should be incredibly helpful for the future too. Thanks
