### ISSUE TITLE
why does string.js look for '?' in string keys?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#82]
Here's the code in question:

```js
//TODO why are we looking for a '?' in a string key name? when does that occur?
// Pull out the key, which is between the last slash and the first question mark of the 'name' parameter.
var questionMarkIndex = name.lastIndexOf( '?' );
var key = questionMarkIndex < 0 ? name.substring( name.lastIndexOf( '/' ) + 1 ) : name.substring( name.lastIndexOf( '/' ) + 1, questionMarkIndex );
```

Under what circumstances would there be a '?' in a string key?

**Comment by samreid** [comment]
I tested several sims and haven't seen any ? in any of the `name` parameters.  Perhaps it is safe to remove this, since we have a convention that our string keys won't have a question mark in them.

**Comment by pixelzoom** [comment]
Test for '?' in string keys removed. Closing.
