### ISSUE TITLE
Remove grunt wrapper

### ISSUE THREAD

**Issue by jbphet** [phetsims/chipper#822]
The "wrapper" task existed for the sole reason of supporting the sonification wrappers, which are being retired, see https://github.com/phetsims/phet-io-wrapper-sonification/issues/93.  Therefore, the "wrapper" task can now be removed.

**Comment by jbphet** [comment]
Please note that there are references to the phet-io-wrapper-sonification repo in chipper-2.0.md that should probably be removed too, or at least updated.

**Comment by zepumph** [comment]
I also see `isWrapper` being used in phet-io-wrapper-haptics, but https://github.com/phetsims/phet-io-wrapper-haptics/issues/7 makes me think it is safe to remove still.

**Comment by zepumph** [comment]
Removed above. Closing
