### ISSUE TITLE
generate-config has a problem with config.js copyright header

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#830]
When I run `grunt generate-config` (typically as a subtask of `grunt update`) I see this output:

```
% grunt generate-config
Running "generate-config" task
../natural-selection/js/natural-selection-config.js, updated with // Copyright 2019, University of Colorado Boulder
% git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
%
```

natural-selection-config.js is never actually modified, and the copyright header continues to be:

```js
// Copyright 2019, University of Colorado Boulder
```

I believe that this started with the 2020 New Year, so I suspect that there's a hard-coded year somewhere that hasn't been updated. 

Assigning to @ariel-phet to prioritize and assign.

**Comment by pixelzoom** [comment]
The console output is coming from updateCopyrightData.js:

```js
66      console.log( absPath + ', updated with ' + copyrightLine );
```

**Comment by pixelzoom** [comment]
Adding some debug output towards the end of updateCopyrightData.js:

```js
  console.log( `startDate=${startDate}` );
  console.log( `endDate=${endDate}` );
  console.log( `absPath=${absPath}` );
  console.log( `firstLine=${firstLine}` );
  console.log( `copyrightLine=${copyrightLine}` );
```

I see this in the console:

```js
startDate=2019
endDate=2019
absPath=../natural-selection/js/natural-selection-config.js
firstLine=// Copyright 2020, University of Colorado Boulder
copyrightLine=// Copyright 2019, University of Colorado Boulder
../natural-selection/js/natural-selection-config.js, updated with // Copyright 2019, University of Colorado Boulder
```

What looks incorrect here is `firstLine`.   Inspecting natural-selection-config.js, that line is clearly 2019, not 2020.   I don't know where the bad `firstLine` is coming from.

**Comment by samreid** [comment]
`grunt generate-config` updates the copyright of the config file based on the git history of the file.  Created in 2019 and no commits in 2020?  Then the copyright statement is 2019.  I tested this in natural selection and circuit-construction-kit-ac, then added a new commit to circuit-construction-kit-ac and saw that it updated to "2019-2020".  Back to @pixelzoom for discussion.

**Comment by pixelzoom** [comment]
Yes, I understand how it works.  But generate-config is saying that natural-selection-config.j is "Copyright 2020" and should be "Copyright 2019" (see debug output above).   That makes no sense -- it's already "Copyright 2019".

**Comment by samreid** [comment]
It looks as if chipper/js/grunt/generateConfig.js generates a fresh file with the current date (e.g. 2020), then chipper/js/grunt/updateCopyrightDate.js revises the date (e.g. 2019).

**Comment by ariel-phet** [comment]
marking as high, since it would be good to discuss "briefly" at dev meeting, and I feel like this should be fairly quick to fix for the right person.

**Comment by zepumph** [comment]
>It looks as if chipper/js/grunt/generateConfig.js generates a fresh file with the current date (e.g. 2020), then chipper/js/grunt/updateCopyrightDate.js revises the date (e.g. 2019).

Yes this is how I wrote it. see https://github.com/phetsims/chipper/issues/763. I didn't love this solution, but I felt like it was preferable to keep that console log in than to touch the console log, and lose that info in `updateCopyrightDate`. 

Ways to proceed here:
1. Leave it as is, and note that it prints this because of the limitation of how the config template is filled in, like @samreid mentioned.
2. Remove the console.log from `updateCopyrightDate` (My least favorite)
3. Perhaps conditionally suppress the `console.log` via an option and do this for the config generation.

**Comment by pixelzoom** [comment]
My vote is for option 3. 

But I'm a little confused by the relevant code in generateConfig.js:

```js
    // If we get here, then we are overwriting the config file, so let's update the copyright to be appropriate.
    await updateCopyrightDate( repo, relativeFile );
```

It says "If we get here", but it sounds like @zepumph implemented this in a way that we _always_ get here.

**Comment by pixelzoom** [comment]
1/16/2020 dev meeting:

If we need to stick with a workaround, consensus was that option 3 is the lesser of evils.  But @samreid mentioned that the preferred solution would be to generate config.js with the correct copyright date.  @zepumph can you comment on why this was not one of the options, and provide an estimate to do this?

Unlabeling for dev meeting. @zepumph and I will iterate.

**Comment by zepumph** [comment]
Sure thing. I will get back to you. Removing "high" priority because this is a cosmetic error as opposed to a bug with the implementation.

**Comment by zepumph** [comment]
I was able to get rid of the console logging in `grunt update` and `grunt generate-config` in the aboe commit. 

>@zepumph can you comment on why this was not one of the options, and provide an estimate to do this?

Yeah let me explain a bit. To get this to work conditionally we have to see if the file is already checked into github for the "original" date of creation. I remember https://github.com/phetsims/chipper/commit/0792ef142f89471a151d6a1b197b6e4686662bea being quite a bit harder than I originally thought it would be when I started. Because of this I'm very happy to just proceed with the simple addition of "silent" support in `updateCopyrightDate`. I don't think this is a workaround because `generateConfig` is running this code, so by the end of that function running the file will be correct. 

If you disagree feel free to dive in and see if you can find an easier way to generate that first date and put it in the template. Over to @pixelzoom to review, recommend a different direction, and/or close.

**Comment by pixelzoom** [comment]
> ... If you disagree feel free to dive in and see if you can find an easier way to generate that first date and put it in the template. Over to @pixelzoom to review, recommend a different direction, and/or close.

The "preferred solution" referred to in https://github.com/phetsims/chipper/issues/830#issuecomment-575308875 was dev team consensus, so it's not up to me to disagree.  You should probably bring this back to the team, or maybe run it past @samreid who identified the "preferred solution".  I also don't have time to "dive in", but happy to review. That said...

Inspecting the commit, I see that you chose the "suppress console output for config.js" option, which I voted for in https://github.com/phetsims/chipper/issues/830#issuecomment-575269734.  Reviewing https://github.com/phetsims/chipper/commit/0792ef142f89471a151d6a1b197b6e4686662bea, it looks good.  But a couple of things...

(1) Add a comment (referencing this issue) in generateConfig.js about _why_ it's necessary to set `silent = true`. This tells me that nothing will be logged, but it doesn't tell me why:

```js
92 await updateCopyrightDate( repo, relativeFile, true /* don't log to the console */ );
```

(2) As noted in https://github.com/phetsims/chipper/issues/830#issuecomment-575269734, I'm still wondering about this comment in generateConfig.js:

`91 // If we get here, then we are overwriting the config file, so let's update the copyright to be appropriate.`

Why does it say "If we get here"?  I don't see any conditional logic. It looks like we always get "here", and always overwrite the config file.

**Comment by zepumph** [comment]
>Why does it say "If we get here"? I don't see any conditional logic. It looks like we always get "here", and always overwrite the config file.

**Simple answer**: The two execute calls will fail out for a certain case, hence the nesting in a try catch.

**Long answer**:
Sorry I didn't explain this clearer. Everything is connected here with (1) and (2). The code you want better doc for is the reason why it is not (in my opinion) a better solution to try to handle this copyright date from the template as opposed to using `updateCopyrightDate` as a post processing step. I tried to be as clear as possible there, but if there are still questions I would love to talk with you about to get on the same page. The points that I am trying to make are that:
1. There is a different copyright date when recreating (file is already checked in) vs. new file (from simula rasa)
2. The logic to handle the `{{creationDate}}-{{dateLastModified}}` already exists in `updateCopyrightDate`, so why duplicate it over in `generateConfig`.
3. Things are working as desired now.

**Comment by pixelzoom** [comment]
Thanks for updating the doc, and for the clarification. Closing.
