### ISSUE TITLE
Unsupported interlace for some PNG files

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#831]
During https://github.com/phetsims/chipper/issues/820, @jonathanolson and I discovered that some of our images in Natural Selection and Number Play cannot be mipmapped, they fail with an "Unsupported interlace" error.  We have worked around it by omitting mipmaps for those.  But it would be nice to understand why this problem occurred and how we could get around it if we need to mipmap those images in the future.

@amanda-phet or @pixelzoom do you know if these images were generated in an unusual manner that might have caused this problem?  For instance: bunny-brownFur-floppyEars-longTeeth.png suffers from this symptom.  I'm not blaming you at all, this is a flaw with our PNG parsing library, but I want to understand how it can parse our other hundreds of images and just have a problem on these.

**Comment by amanda-phet** [comment]
When I export images I see this dialog. 
![image](https://user-images.githubusercontent.com/7852916/72191893-f7104f00-33c0-11ea-812b-cea9e60f7c1d.png)

Maybe "interlaced" was checked when I exported those? I don't recall checking that intentionally but it could have happened. 

Should I re-export those image and hand them over to you to see if that fixes the problem?

**Comment by amanda-phet** [comment]
![bunny-brownFur-floppyEars-longTeeth](https://user-images.githubusercontent.com/7852916/72192323-7ce0ca00-33c2-11ea-8c23-5183e1fab2cf.png)

I exported this without that checkbox checked, but I didn't verify that the dimensions match what is being used in the sim. Hopefully this is enough to at least help uncover the problem!

**Comment by pixelzoom** [comment]
Nothing for me to do here, and it looks like @amanda-phet has provide what's needed to test. So back to @samreid.

**Comment by samreid** [comment]
I downloaded the PNG linked in https://github.com/phetsims/chipper/issues/831#issuecomment-573239412 and the mipmap plugin was able to load it.  According to https://graphicdesign.stackexchange.com/questions/6677/what-does-the-interlaced-option-in-photoshop-do, image interlacing is to initially show a degraded version of the entire image, and enhance it during download, and "Interlaced will almost always be a bit bigger in filesize".  For PhET, since all of our images are preloaded, it seems like we should not be using interlacing.

@amanda-phet can you please export a file with and without interlacing and report on the file sizes?

**Comment by amanda-phet** [comment]
I just exported the same bunny at medium resolution, but the second with interlaced checked. 

Non-interlaced: 8 kb
Interlaced: 12 kb

**Comment by samreid** [comment]
I used chipper/webpack with `grunt modulify` to test which images could not be loaded via the mipmap plugin, and here is the list:

```
natural-selection/images/bunny-brownFur-floppyEars-longTeeth.png
natural-selection/images/bunny-brownFur-floppyEars-shortTeeth.png
natural-selection/images/bunny-brownFur-straightEars-longTeeth.png
natural-selection/images/bunny-brownFur-straightEars-shortTeeth.png
natural-selection/images/bunny-whiteFur-floppyEars-longTeeth.png
natural-selection/images/bunny-whiteFur-floppyEars-shortTeeth.png
natural-selection/images/bunny-whiteFur-straightEars-longTeeth.png
natural-selection/images/bunny-whiteFur-straightEars-shortTeeth.png
natural-selection/images/wolf.png
number-play/images/dog.png
```

This is likely (but not guaranteed) to be due to interlacing problems.  Assigning to @ariel-phet to coordinate with designers/artists to:

* regenerate these files without interlacing
* disseminate the information to our artists/designers that interlacing is not supported by our current tooling.

**Comment by samreid** [comment]
Reassigned to @amanda-phet to regenerate the images.  After that's done, I'll confirm they work with the mipmap plugin.

**Comment by amanda-phet** [comment]
@samreid I committed the new images.

**Comment by samreid** [comment]
Thanks, I confirmed this fixed the problem for all the rabbits.  Can you please also address the wolf and dog images?  They are the last two in this list: https://github.com/phetsims/chipper/issues/831#issuecomment-574976775

**Comment by amanda-phet** [comment]
>Can you please also address the wolf and dog images? They are the last two in this list: #831 (comment)

Yes, apologies for missing those. I've fixed those images as well.

**Comment by samreid** [comment]
I tested that all of the new images can be loaded by the mipmap module, thanks!  Closing.
