### ISSUE TITLE
Do we want to output the image/sound/text *.js files adjacent to their sources, or in some other directory?

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#834]
Do we want to output the image/sound/text *.js files adjacent to their sources, or in some other directory?

From #820, would have a new precompilation step which generates JS for PNG, JPG, WAV, MP3, Strings, etc.  In the first draft, they are outputted adjacent to their original files, like:

```
license.json
light-bulb-icon.png
light-bulb-icon_png.js
light-bulb-icon_png_mipmap.js
```
etc

Keeping related files adjacent and using suffixed served us well for IO types and Test files, but we were wondering if the team would prefer outputting these files to a separate directory since they are artifacts built during a build step (albeit a precompilation build step).  Note these will still need to be checked in to version control, so that someone can checkout the code and run it with no build steps.

**Comment by samreid** [comment]
Brainstorming for the sake of completeness.  Files such as *.PNG files wouldn't be needed at all at runtime, so maybe we wouldn't need to check those in at all?  So instead of checking in AI + PNG + JS, we would just check in AI + JS?  Perhaps the same would apply to audio.  But right now modulify is set up around converting PNG to JS, and it doesn't know (and shouldn't know) how to parse AI.

**Comment by samreid** [comment]
In today's meeting, we agreed it makes sense to output these files adjacent to their sources.

@pixelzoom asks: Would the license.json file need to be changed?

We could add a rule that ignores *.js files in directiories with license.json.  And makes sure *.js have corresponding non-js files.

@samreid asks how to keep fast searches with all of these new files?

It was recommended to add a filter to the search.

**Comment by pixelzoom** [comment]
> @pixelzoom asks: Would the license.json file need to be changed?

If I have images/floppyEars.png and images/floppyEars.js, with a license.json entry for foo.png, then `grunt` fails: 

```
% grunt
Running "lint-all" task

Running "report-media" task
>> not-annotated: natural-selection/images/floppyEars.js
Fatal error: There is an issue with the licenses for media types.
%
```

**Comment by samreid** [comment]
In https://github.com/phetsims/chipper/issues/834 it made sense to output the strings in another directory.

**Comment by jonathanolson** [comment]
I was assigned, but I'm not sure what I should be doing here. @samreid can you clarify?

**Comment by samreid** [comment]
The remaining work for this issue is identified in https://github.com/phetsims/chipper/issues/834#issuecomment-575335541, for anyone that wants to work on it.

**Comment by jonathanolson** [comment]
It looks like the above work was done (there's a check for JS files in reportMedia). Closing.
