### ISSUE TITLE
no examples of eslintrc for subdirectory

### ISSUE THREAD

**Issue by chrisklus** [phetsims/chipper#835]
When working on https://github.com/phetsims/phet-io-wrappers/issues/292, @samreid and I were removing usages of `phet-io-wrappers/studio`, and noticed this note in eslint/README.md:

```
If there is a sub directory that requires specific configuration, you should create a file called `.eslintrc.js` in that
directory, and specify the necessary configuration there. Don't forget that you also need to "extend" the default 
configuration too. See `phet-io-wrappers/studio/.eslintrc.js` for an example.
```

We remember working with this pattern at some point, but there is no longer a sub directory eslint file in the project (that we can find) that we can give as a replacement example. Should we remove this text block entirely or just the reference to the example? What do you think @zepumph?

**Comment by zepumph** [comment]
Yeah thanks that is a good point. I updated above.

**Comment by chrisklus** [comment]
Thanks @zepumph, looks good. Closing.
