### ISSUE TITLE
For ES6 modules, how should we determine which images to generate mipmaps for?

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#836]
For https://github.com/phetsims/chipper/issues/820 in a rough draft, @jonathanolson and I decided to generate preprocessed mipmaps for every image, so the preprocessing step would be simple.  But I'm wondering whether we actually want to generate mipmaps for every image, since that takes time and space, and clutters up the directory.  

Should we:
a) generate mipmaps for every image because it's a simple process and makes it trivial to use mipmaps when they are needed
b) set up a procedure for identifying which images should be mipmapped vs converted to standard image format
c) something else?

Would be good to decide as a team, I'll mark for developer meeting.

**Comment by pixelzoom** [comment]
I'm not familiar with how you're converting images to .js files.  But could image be a special case of mipmap where levels of resolution is 1 ?

**Comment by samreid** [comment]
> I'm not familiar with how you're converting images to .js files.

We added a script in chipper's webpack branch, that generates an image *.js and a mipmap *.js for every image in the images directory.  Here's the current working prototype for that: https://github.com/phetsims/chipper/blob/1ebce0c4bb0746caee67acb515678ba8fb69b039/js/grunt/modulify.js#L172-L225

Having images be a special case of mipmap where resolution is 1 wouldn't save much complexity on the plugin side, and we would still need a way to direct the preprocessor which images need which resolutions.

This is probably too clever, but another option would be to create a convention for filenames, then traverse all of the source code to identify what images to generate. I'm brainstorming this because it is a closer match to what we used to have in the requirejs build process.

```js
// triggers the preprocessor to convert plain image
import houseImage from '../../images/house_png.js'; 

// triggers the preprocessor to generate a mipmap with level 4 and quality 98
import mountainImage from '../../images/mountain_png_mipmap_level_4_quality_98.js'; 
```

**Comment by zepumph** [comment]
One issue that discusses use of mipmaps a lot if https://github.com/phetsims/joist/issues/258. Perhaps that would be helpful.

**Comment by pixelzoom** [comment]
I believe that I've only used mipmap! in function-builder. Issue https://github.com/phetsims/function-builder/issues/4 may or may not document why. If you want to see the results of image! vs mipmap! in function-builder, run with `?testScreen`.  It adds a 'Test' screen that show the results of every image through every filter.  E.g.:

<img width="1021" alt="screenshot_53" src="https://user-images.githubusercontent.com/3046552/73020221-6be08180-3de2-11ea-961f-c09d34a22255.png">

**Comment by pixelzoom** [comment]
I compared image! to mipmap! in function-builder.  In the "Test" screen, I currently see no difference on latest Safari, Chrome, and Firefox on macOS 10.15.2.

**Comment by samreid** [comment]
We discussed this at the previous developer meeting.   The consensus was that we would add a command line program to generate the mipmap *.js for an image.  Then `grunt modulify` would detect the presence of a mipmap file to decide whether to regenerate it.

**Comment by jonathanolson** [comment]
I saw @pixelzoom as marked on the roadmap doc:

> (CM, ?? hours) [post-publication, need to decide as a team] How to determine which images to mipmap? https://github.com/phetsims/chipper/issues/836 
> SR: Or are we getting rid of mipmaps altogether? https://github.com/phetsims/chipper/issues/840
> CM: I suspect we may need them in the future. Even if you don’t implement the mipmap plugin, I think it would be wise to have a plan that makes it easy to add.
>   SR: Mipmaps are now supported in the es6 module prototype

Assigning, and also co-assigning as since we have a description, I'm capable of this.

**Comment by samreid** [comment]
Would it be simpler to just mark the images that require mipmapping in the package.json?  Something like this:

```diff
Index: package.json
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- package.json	(revision 101e45bcaad9d423687b164fc2e14b9bd6e5c11b)
+++ package.json	(date 1580444575283)
@@ -10,6 +10,10 @@
     "grunt": "~1.0.0"
   },
   "phet": {
+    "mipmaps": [
+      "images/light-bulb-icon.png",
+      "images/solvent.png"
+    ],
     "requirejsNamespace": "ACID_BASE_SOLUTIONS",
     "runnable": true,
     "supportedBrands": [
```

This will leave the modulify step automatic and simplify it somewhat.  It also seems more explicit and direct about which images should be mipmapped rather than relying on a process step.

**Comment by pixelzoom** [comment]
How about simply putting PNG files in separate directories, depending on whether we want an image or a mipmap? I.e. {{REPO}}/images/ and {{REPORT}}/mipmaps/.

**Comment by samreid** [comment]
That's even better, thanks!

**Comment by pixelzoom** [comment]
> I saw @pixelzoom as marked on the roadmap doc: ...  Assigning, and also co-assigning as since we have a description, I'm capable of this.

My role was "input", so self-unassigning.  Let me know if you need any more input.

**Comment by zepumph** [comment]
From today's dev meeting, @samreid will refactor mipmaps into their own `mipmaps/` repo on master. That way when we migrate things will already be setup for success. We also discussed pinging about #840 to see if we even need this.

**Comment by samreid** [comment]
Here is a list of sims which load the same image as mipmap! and image!.

charges-and-fields
circuit-construction-kit-ac
circuit-construction-kit-black-box-study
circuit-construction-kit-dc
circuit-construction-kit-dc-virtual-lab
expression-exchange
fractions-equality
fractions-intro
fractions-mixed-numbers
molecules-and-light
projectile-motion
states-of-matter
states-of-matter-basics

**Comment by samreid** [comment]
I tested locally in aqua and used `grunt --brands=phet` to detect misplaced  license.json entries.  I messaged on slack:

> Commits across many repos inbound for https://github.com/phetsims/chipper/issues/836

**Comment by samreid** [comment]
After the above commit, images are output to images/ and mipmaps are output to mipmaps/.  Tested in Balancing Act.  @jonathanolson can you please review at your convenience?

**Comment by jonathanolson** [comment]
Looks good to me, thanks!
