### ISSUE TITLE
Make it easy to run fast searches

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#838]
In https://github.com/phetsims/chipper/issues/834 we decided to output precompiled image and mipmap and string files adjacent to their sources, but this is slowing down my searches substantially.  I tried introducing a new search "scope" in WebStorm, but it is somewhat clumsy for our project structure.

Should we output all generated files (or things that should not be searchable) into repo/generated or repo/js/generated to make it easier to set ignore filters?  This would include phet-io files as well as precompiled strings/images/mipmaps/audio.  Or the fact that we have to set an ignore pattern once mean its not much more trouble to set additional ignore patterns?  

This magnitude of this problem may be reduced if we reduce the number of mipmap files in https://github.com/phetsims/chipper/issues/836.

Self-assigning for initial review before bringing this to dev team meeting.

**Comment by samreid** [comment]
Also, we may want to ignore the combined strings file, but not the source string file, so it's not clear how to set up a search ignore pattern that would do that.

**Comment by jonathanolson** [comment]
Estimated 1-2 hours in doc.

**Comment by samreid** [comment]
I tried reducing the max memory of WebStorm from 2GB to 512MB, then I invalidated caches and restarted and the search speed is very snappy!  For this to be a real science experiment, I would need to increase the memory again and re-test.

**Comment by samreid** [comment]
I had a terrible time with search performance even before ES6 migration.  My problems went away when I typed this into the “Directories” => Exclude:

```
build;node_modules;images;sounds;*phet-io-elements-baseline.js;*phet-io-elements-overrides.js;*phet-io-types.js
```

**Comment by samreid** [comment]
I also manually excluded these:
![image](https://user-images.githubusercontent.com/679486/77943244-25901e80-727a-11ea-9d64-2af62e5c2f5b.png)
