### ISSUE TITLE
problems with image plug-in and license checks

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#839]
I spent about 30 minutes on this issue, and it seems worth attention. 

I have images/tenderFood.png, with this license.json entry:

```js
  "tenderFoodA.png": {
    "text": [
      "Copyright 2020 University of Colorado Boulder"
    ],
    "projectURL": "http://phet.colorado.edu",
    "license": "contact phethelp@colorado.edu",
    "notes": "created by Amanda McGarry"
  },
```

In a .js file, I used this `require` statement, which is missing the .png suffix.  It worked just fine, that's problem 1.

`const tenderFoodAImage = require( 'image!NATURAL_SELECTION/tenderFoodA' );`

When it was time to build, running `grunt` failed. 

If the license entry was missing, the error would have been:

`>> not-annotated: natural-selection/images/tenderFoodA.png
Fatal error: There is an issue with the licenses for media types.`

But that's not the error that I got, and that's problem 2 -- there is no license entry for 'tenderFoodA', there's an entry for 'tenderFoodA.png', but something is apparently finding the license for 'tenderFoodA.png'.

Instead, the error message was:

`image!NATURAL_SELECTION/tenderFoodA: Error: unacceptable license entry for NATURAL_SELECTION/tenderFoodA`

That's problem 3 - the license entry for 'tenderFoodA' isn't just unacceptable, it doesn't exist. And something is confused about 'tenderFoodA' vs 'tenderFoodA.png'.

Assigning to @ariel-phet to prioritize and assign.

**Comment by ariel-phet** [comment]
Let's try to hit this one quickly at dev meeting and get a volunteer, seems worth fixing if not too difficult to track down the problems.

**Comment by pixelzoom** [comment]
1/23/20 dev meeting:

We decided to defer this.  If/when we move to ES6 modules, images will be .js files, and this presumably will be a non-issue.

**Comment by jonathanolson** [comment]
Estimated as 1-2 hours to get the licensing warnings and stuff working (presumably before we migrate fully).

**Comment by chrisklus** [comment]
@jonathanolson, @samreid does not remember seeing any license warnings recently, do you think anything needs to be done before tomorrow?

**Comment by jonathanolson** [comment]
Yesterday I built all runnables and didn't see any licensing problems.

**Comment by samreid** [comment]
Excellent, thanks!  I don't see any commits on this issue, should we track down how this was resolved?  Generally, anything else before this issue can be closed?

**Comment by samreid** [comment]
Some work completed in ab1281f1966e73d2355430959514fa420ca76331, back to @pixelzoom to double check the 3 problems in the top comment.

**Comment by pixelzoom** [comment]
Not sure how I'd even test this now that .png files are converted to .js.  So I'm going to close.
