### ISSUE TITLE
Can we eliminate mipmaps?

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#840]
One question that arose from https://github.com/phetsims/chipper/issues/836 was whether we still need to support mipmaps, or whether our supported browsers now render nicely enough that we can use plain images. 

Benefits we stand to gain by dropping mipmap support:
* Less code to support and maintain
* Less overhead for image pre-generation, https://github.com/phetsims/chipper/issues/836
* Smaller file size.  For instance, function builder built size reduced by 6.5% when mipmaps were omitted.  This will also lead to faster downloads and faster startup time.

Other issues dealing with the need for mipmap: https://github.com/phetsims/joist/issues/258 (2015) and https://github.com/phetsims/function-builder/issues/4 (2015)

At today's meeting, @ariel-phet asked me to publish dev versions of the following sims with no mipmaps for testing:
* Function Builder
* CCK 
* Balancing Act

After publishing, QA can test and see if the images look acceptable without using mipmaps.  Note, if there is even one platform that requires mipmaps, then we must keep them.  So you might want to begin testing on the riskiest platforms, such as Win/Firefox, IE, Chromebooks, Android.  @pixelzoom reported some preliminary results in https://github.com/phetsims/chipper/issues/836#issuecomment-577859781

Leaving self-assigned until I publish the sims.

**Comment by samreid** [comment]
I published dev.1 of Function builder for reference, it contains mipmaps as usual.
https://phet-dev.colorado.edu/html/function-builder/1.2.0-dev.1/phet/function-builder_en_phet.html

I tried using the strategy @zepumph indicated to point mipmap to use the image plugin, so it would address common code mipmaps easily, but it failed to load for unknown reasons.  Instead, for the upcoming test, I switched to use the branches above, and copy/pasted the image plugin into mipmap.js.  Unfortunately this led to a bad dev.2, my apologies.  Dev.3 failed because image.naturalHeight is undefined for a built sim, again my apologies.  I'll take more time to investigate and test locally before going to dev.4.

Not ready for testing yet.

**Comment by samreid** [comment]
Function builder is ready for testing.  Here's the original version with mipmaps
https://phet-dev.colorado.edu/html/function-builder/1.2.0-dev.1/phet/function-builder_en_phet.html

And the new version without mipmaps.
https://phet-dev.colorado.edu/html/function-builder/1.2.0-dev.4/phet/function-builder_en_phet.html

Our goal is to identify if there are any rendering problems (blurry, aliased, etc) in the version without mipmaps, on any of our supported platforms.

From the top comment:
> Note, if there is even one platform that requires mipmaps, then we must keep them. So you might want to begin testing on the riskiest platforms, such as Win/Firefox, IE, Chromebooks, Android. @pixelzoom reported some preliminary results in #836 (comment)

Assigning to @ariel-phet to prioritize and delegate.
If you find one significant problem, we may determine that sufficient to terminate testing.

**Comment by samreid** [comment]
Balancing act looks 12% smaller without mipmaps.

**Comment by ariel-phet** [comment]
@KatieWoe could you test the sims in https://github.com/phetsims/chipper/issues/840#issuecomment-577936423

Basically we want to know if compared to the published sim the sims tried without mipmaps show any significant degradation of image quality (it will usually look pixelated/jagged edges in some way). The 3 sims should be tested on all supported platforms. The test can cease if even one case is found - if such a case is found please show it here, and reassign the issue to me.

**Comment by KatieWoe** [comment]
- [ ] iPhone
- [ ] iOS 9
- [ ] iOS 10
- [ ] iOS 12
- [ ] iOS 13
- [ ] Mac 10.10 Safari
- [ ] Mac 10.11 Safari
- [ ] Mac 10.11 Chrome
- [ ] Mac 10.12 Safari
- [ ] Mac 10.12 Chrome
- [ ] Mac 10.13 Safari
- [ ] Mac 10.13 Chrome
- [ ] Mac 10.14 Safari
- [ ] Mac 10.14 Chrome
- [ ] Mac 10.15 Safari
- [ ] Mac 10.15 Chrome
- [ ] Win 10 IE
- [ ] Win 10 Edge
- [ ] Win 10 Firefox
- [ ] Win 10 Chrome
- [ ] ChromeOS

**Comment by jessegreenberg** [comment]
As a data point - I last used mipmap for screen icons because they looked fuzzy in Firefox. I just did a side by side comparison changing mipmap with image in Firefox 73 and saw no observable difference.

**Comment by jessegreenberg** [comment]
In https://github.com/phetsims/joist/issues/607#issuecomment-586340474

@pixelzoom said 
>>... wouldn't we just want to strongly encourage said browser to improve its rendering rather than taking matters into our own hands?

>As I recall, that argument didn't fly when we discovered rendering-quality issues that were browser specific. In the past, I've only had to use mipmap because PhET wasn't willing to wait until browsers addressed the issue, not because we needed many levels of image size. So if QA finds no current problems and you want to recommend dropping support for mipmaps, I think that's a decision that designers and @kathy-phet need to sign off on. I recommend a solution that supports mipmaps, even if they aren't used initially. Beyond image-quality issues, we may have good reasons to use mipmaps for this primary purpose (multiple levels of detail).

**Comment by KatieWoe** [comment]
Noting that when screens have lower resolutions (not really dependent on browser) small images can appear a bit different without mipmaps. This is seen in the tm next to the PhET menu, which looks skinnier without mipmaps. In my opinion, it generally looks cleaner this way, so I'm not terribly concerned.
With mipmaps:
![withmipmap](https://user-images.githubusercontent.com/41024075/77362471-95505780-6d16-11ea-96d5-90a067760f6c.png)
Without mipmaps:
![withoutmipmap](https://user-images.githubusercontent.com/41024075/77362486-9d0ffc00-6d16-11ea-8679-6d9a452a3219.png)

**Comment by KatieWoe** [comment]
Another few instances within the sims on Chrome Mac 10.13
CCK With Mipmaps
![cckwith](https://user-images.githubusercontent.com/41024075/78835223-077a9a80-79ad-11ea-8250-b7566de3ff04.png)

CCK Without Mipmaps
![cckwithout](https://user-images.githubusercontent.com/41024075/78835235-0c3f4e80-79ad-11ea-9831-7acc45cfc396.png)

BA With Mipmaps
![balancewith](https://user-images.githubusercontent.com/41024075/78835356-490b4580-79ad-11ea-8fff-49fa27ea3f26.png)

BA Without Mipmaps
![balancewithout](https://user-images.githubusercontent.com/41024075/78835371-4f99bd00-79ad-11ea-8ea2-ffb9cd39a0e0.png)

**Comment by KatieWoe** [comment]
Some more instances from Mac 10.12 safari
With Mipmaps
![withmipmaps](https://user-images.githubusercontent.com/41024075/79028189-527ee400-7b4c-11ea-9a60-d7d42b54f334.png)
Without Mipmaps
![withoutmipmaps](https://user-images.githubusercontent.com/41024075/79028191-53177a80-7b4c-11ea-861f-45473d543764.png)

**Comment by KatieWoe** [comment]
QA is done

**Comment by samreid** [comment]
@ariel-phet can you please review the issue description https://github.com/phetsims/chipper/issues/840#issue-554450589 and the results from the QA study ( https://github.com/phetsims/chipper/issues/840#issuecomment-602852232 and later) and recommend how to proceed?

**Comment by ariel-phet** [comment]
@samreid in the above there at least a few instances where the mipmap is clearly superior. (certainly the balancing act game icons from https://github.com/phetsims/chipper/issues/840#issuecomment-611203502). Therefore we should continue to use them. Closing

**Comment by samreid** [comment]
One last question--should we add a code review checklist item or equivalent to make sure that mipmaps are only used where necessary, to reduce download sizes?  If so, would we do a review of existing mipmaps, or only look at this for new code?

**Comment by pixelzoom** [comment]
@samreid had also identified some cases where sims were using both a mipmap and image version of the same resource.  Were those cleaned up as a result of the ES6 module migration?

**Comment by samreid** [comment]
> @samreid had also identified some cases where sims were using both a mipmap and image version of the same resource. Were those cleaned up as a result of the ES6 module migration?

I believe that was addressed in https://github.com/phetsims/chipper/issues/836#issuecomment-586744317

**Comment by pixelzoom** [comment]
Apparently not?  The first sim in the https://github.com/phetsims/chipper/issues/836#issuecomment-586744317 list (charges-and-fields) has an image and mipmap for the same resource:

```
% cd charges-and-fields
% ls images/ mipmaps/
images/:
electricPotentialPanelOutline.png	license.json
electricPotentialPanelOutline_png.js

mipmaps/:
electricPotentialPanelOutline.png	pencil.png
electricPotentialPanelOutline_png.js	pencil_png.js
license.json
%
```

I didn't check others.

**Comment by samreid** [comment]
That was described in the comment:

> (b) copying the mipmap! to image! if something unusual was happening (I'm looking at you charges-and-fields)

If it's important to guarantee that no image appears in mipmaps/ and images/, please open a new issue and assign to @ariel-phet to delegate.

**Comment by ariel-phet** [comment]
@samreid I don't think we need to necessarily make a CRC item for that - it is a bit hard to predict where they will be "necessary" - but it does seem worth not have duplication as mentioned by @pixelzoom in https://github.com/phetsims/chipper/issues/840#issuecomment-614034282

Seems worth a different issue as suggested.

**Comment by pixelzoom** [comment]
Not sure how I got involved in this, but OK... I'll investigate and open issues for duplicated resources.

**Comment by pixelzoom** [comment]
Here's the list of sims identified in https://github.com/phetsims/chipper/issues/836#issuecomment-586744317 that were loading the same image as mipmap! and image!, prior to ES6 module migration:

- [ ] charges-and-fields
- [ ] circuit-construction-kit-ac
- [ ] circuit-construction-kit-black-box-study
- [ ] circuit-construction-kit-dc
- [ ] circuit-construction-kit-dc-virtual-lab
- [ ] expression-exchange
- [ ] fractions-equality
- [ ] fractions-intro
- [ ] fractions-mixed-numbers
- [ ] molecules-and-light
- [ ] projectile-motion
- [ ] states-of-matter
- [ ] states-of-matter-basics

**Comment by pixelzoom** [comment]
All sims in the above list were checked. The only case was in charges-and-fields, as reported in https://github.com/phetsims/charges-and-fields/issues/180.

I'm not too familiar with this issue, so I don't know if there's anything else that needs to be done.  So back to @ariel-phet.

**Comment by ariel-phet** [comment]
@pixelzoom thanks for doing that check. Since that is the only sim, and there is an existing issue, we can now close.
