### ISSUE TITLE
ES6 modules should import with filename suffix

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#842]
On mac, it seems like filename suffixes are not necessary, but on windows it seems like they are necessary.  And best practice and MDN examples show that we should use suffixes.

**Comment by samreid** [comment]
Fixed, but I don't have a convenient way to test it on my mac.  @zepumph could you please test this on Windows at your convenience?

checkout "webpack" branch in chipper
grunt migrate
grunt modulify

launch acid base solutions

**Comment by zepumph** [comment]
I was able to run it with the following additional steps:

1. Add `.js` to `BackboneDrawable` import in Display.js
2. Add `.js` to every import of `LocalizedStringBundle`

**Comment by samreid** [comment]
Fixed in the above commit, thanks!  Closing.
