### ISSUE TITLE
Race condition in script loading

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#843]
While working on https://github.com/phetsims/chipper/issues/832 in compilation free mode, every so often (say 1/10 times or so), I get an error during start up that says something like "assert not defined" or some other preload global not defined.  I suspect that our code isn't waiting until all other scripts have finished before starting the script type=module part.  We may need to guarantee that ordering.

**Comment by jonathanolson** [comment]
There is some loading order issue triggering "Uncaught ReferenceError: phetio is not defined" on Tandem.js 317 after migrate, happening randomly, usually on the first load

**Comment by jonathanolson** [comment]
There looks like a way to restructure the template so that this works, but I haven't run into a failure recently. Dynamically adding the script with the module tag (with loadURL) in the dev HTML seems like a natural approach.

**Comment by jonathanolson** [comment]
The above should fix it, I'll reopen if I see it.
