### ISSUE TITLE
Separate namespace.register and "inherit" calls from export default.

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#848]
From #846 @pixelzoom pointed out we should separate the `namespace.register` from the `export default`.

**Comment by samreid** [comment]
Ideally we would do the same with inherit statements, but we IDE support for that may be limited anyways because `inherit` is our own invention.

**Comment by samreid** [comment]
I wonder if it may be easier to do this in master and guard against it with a lint rule.  I also noticed several cases where variables were being created inline like so:

```js
  return areaModelCommon.register( 'AreaModelCommonConstants', {

    // {PhetFont} All fonts
    FACTORS_TERM_FONT: new PhetFont( 36 ), // Terms/numbers in the factors box
    FACTORS_PAREN_FONT: new PhetFont( 40 ), // Parentheses in the factors box
    CALCULATION_X_FONT: new PhetFont( 16 ),
```

**Comment by samreid** [comment]
This seems good to do before the migration.

**Comment by samreid** [comment]
@jonathanolson and I discussed this and determined it is not essential to do before the migrate.  However, the `namespace.register` calls may be convenient to add as a migration rule if there is time.  `inherit` will probably be a separate step.

**Comment by samreid** [comment]
As a middle ground, let's convert usages that are single-line statements.

**Comment by samreid** [comment]
I added migration for single-line import/namespace statements and tested a full aqua and lint-everything.  Demoting priority until after the migrate to handle multiline statements.

**Comment by chrisklus** [comment]
It looks like there's many multiline cases that will need to be addressed after the migration. @samreid is going to investigate nested macros to handle these.

**Comment by zepumph** [comment]
Thank you for doing this! I'm afraid there are a few cases here that I am directly responsible for.

**Comment by samreid** [comment]
I finished converting these and added lint rules to prevent their recurrence.  Closing.
