### ISSUE TITLE
migrate can't handle require statements in logic

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#849]
During dev meeting today we found that the migrate doesn't handle require statements that are in logic, here is a list of sims with that:

* test files like QSM, utterance-queue, phet-io-wrappers

search for "&nbsp;&nbsp;require"
- [x] arithmetic (LevelSelectionNode.js) @jbphet
- [x] circuit-construction-kit-dc-virtual-lab (circuit-construction-kit-dc-virtual-lab-main.js) @samreid 
- [x] energy-forms-and-changes (FanNode.js, BikerNode.js) @chrisklus (@pixelzoom did FanNode.js)
- [x] number-line-integers (MonthsComboBox.js) @jbphet
- [x] shred (AtomIdentifier.js) @jbphet 
- [x] tambo (UIComponentsScreenView.js) @jbphet

search for ": require"
- [x] area-builder (AreaBuilderSharedConstants.js) @jbphet (done by @pixelzoom)
- [x] energy-forms-and-changes (BlockNode.js) @chrisklus (done by @pixelzoom)
- [x] graphing-lines @pixelzoom
- [x] least-squares-regression (DataSet.js) @jonathanolson 
- [x] tambo (SoundEncodingComparisonPanel.js) @jbphet

**Comment by zepumph** [comment]
Over in https://github.com/phetsims/area-builder/issues/112 @pixelzoom had a good example of how to change these usages:


AreaBuilderSharedConstants.js:

```js
  INVALID_VALUE: require( 'string!AREA_BUILDER/invalidValue' )
```

This `require` violates PhET conventions and will not be properly handled by ES6 migration tools. You'll need to pull this out into a `const` statement:

```js
const invalidValueString = require( 'string!AREA_BUILDER/invalidValue' );
...
  INVALID_VALUE: invalidValueString
```

**Comment by zepumph** [comment]
Labelled as high because this should be done BEFORE the sprint in a few weeks.

**Comment by pixelzoom** [comment]
@zepumph I don't see ": require" in shred. Can you please identify?

**Comment by zepumph** [comment]
`AtomIdentifier.js`

**Comment by pixelzoom** [comment]
@jbphet @chrisklus I did some of the work in your repos, see above commits, please check.

**Comment by chrisklus** [comment]
Looks good @pixelzoom, thank you

**Comment by samreid** [comment]
I did some work in @jbphet @jonathanolson and @chrisklus repos.  Would be good to be reviewed to make sure the pattern is acceptable, though I don't know that it's necessary to verify each string.  Some files had 50+

**Comment by jonathanolson** [comment]
least-squares-regression looks good, thanks!

**Comment by chrisklus** [comment]
Dang, I missed that I still had a file left. Thanks much @samreid, looks good.

**Comment by jbphet** [comment]
I've reviewed the changes for my repos, they all look reasonable to me.  I think that means that everything is done on this, but it would probably be good for @zepumph to double check before closing.

**Comment by zepumph** [comment]
Great! I looked through a few more usages, and couldn't find any more buggy ones. Closing
