### ISSUE TITLE
cleanup documentation in string.js plugin

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#85]
I'm guessing that string.js conforms to some API, which should be identified in the comment block at the top of the file.

These public functions and their parameters could also benefit from documentation:

```js
load: function( name, parentRequire, onload, config )
write: function( pluginName, moduleName, write )
```

These comments are not at all clear:

> 64 //Browser version first
> 119 //For compiler time

These are also a couple of places where if-then-else statements have blank lines before the else. This is not recommended. Better to move the else comments inside of the else block.

**Comment by samreid** [comment]
Fixed above, reassigning to @pixelzoom for review.

**Comment by samreid** [comment]
Snuck in one other improvement above.

**Comment by pixelzoom** [comment]
Looks awesome. Closing.
