### ISSUE TITLE
Investigate short relative imports (and add to migrate if desired)

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#853]
(SR, 2-4 hours) [DEVELOPER MEETING, sprintable] Decide whether our “relative” imports should go down to the repo, or if we want them to be as short as possible

> Essentially we have two options (e.g. from Vector2):
> import Vector3 from '../../dot/js/Vector3.js';
> import Vector3 from './Vector3.js';
> SR: I recommend as short as possible.
> MK: Short would be cool, but if it is more idiomatic to use relative paths, and our IDEs support move/copy/paste with path updates, then I’m not too worried. I’m more worried about auto complete than I am with length.
> SR: I suspect when WebStorm auto-imports, it will be the short relative paths.
> SR: Is shorter ok?
> JO: Fine with me, I’ll prefer what WebStorm works well with

**Comment by samreid** [comment]
Fixed and working well on my side. @zepumph are you available to test this on windows?  You could do something like the following:

cd chipper
git checkout webpack
git pull
cd ../acid-base-solutions
grunt migrate

and see if the relative paths in acid-base-solutions/js/acid-base-solutions-main.js are correct (and it doesn't crash doing path ops during migrate).

The result on my side is:
```js
// modules
import IntroductionScreen from './introduction/IntroductionScreen.js';
import MySolutionScreen from './mysolution/MySolutionScreen.js';
import Sim from '../../joist/js/Sim.js';
import SimLauncher from '../../joist/js/SimLauncher.js';
import Tandem from '../../tandem/js/Tandem.js';
```

**Comment by zepumph** [comment]
My acid-base paths look like they are using backslash instead of forward slash:

From ABSControlPanel:
```js
// modules
import ABSColors from '..\..\ABSColors.js';
import acidBaseSolutions from '..\..\..\acidBaseSolutions.js';
import HBox from '..\..\..\..\..\scenery\js\nodes\HBox.js';
import inherit from '..\..\..\..\..\phet-core\js\inherit.js';
import merge from '..\..\..\..\..\phet-core\js\merge.js';
import Panel from '..\..\..\..\..\sun\js\Panel.js';
import PhetFont from '..\..\..\..\..\scenery-phet\js\PhetFont.js';
import ResetAllButton from '..\..\..\..\..\scenery-phet\js\buttons\ResetAllButton.js';
import Text from '..\..\..\..\..\scenery\js\nodes\Text.js';
import ToolsControl from '..\ToolsControl.js';
import VBox from '..\..\..\..\..\scenery\js\nodes\VBox.js';
import ViewsControl from '..\ViewsControl.js';

```

Furthermore It looks like there is an extra set of relative dots, as `ViewControls.js` is a sibling to `ABSControlPanel.js`

**Comment by jonathanolson** [comment]
I'm curious about how Mac-specific our current migrate.js is? I see things reconstructed `\n` as newlines, and the path logic might need to be changed for this.

The results of this are working well for me, and I've extracted it out into a shortenImportPath function.

**Comment by samreid** [comment]
> I see things reconstructed \n as newlines, and the path logic might need to be changed for this.

Can you elaborate on this problem?  Would it cause problems if we commit \n newlines everywhere, or should they be preserved?

Also, regarding the paths in particular, is it workable to leave it as unsimplified paths as we continue developing, then require that Mac be used for the migration step?

**Comment by jonathanolson** [comment]
> Also, regarding the paths in particular, is it workable to leave it as unsimplified paths as we continue developing, then require that Mac be used for the migration step?

That's potentially fine, although if it's easy to get it working on Windows, that would be good.

**Comment by zepumph** [comment]
@samreid and i worked on this, but couldn't get it to work too well for windows. Instead we decided to detect when running on windows and warn that this feature is not supported. This way migrate still works as desired, but the better paths is supported for POSIX systems.

This worked well for me, and I'll pass it over to Sam to make sure that it works as expected on mac.

**Comment by samreid** [comment]
Working well here, closing.
