### ISSUE TITLE
Remove vestigial files after es6 module migration

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#855]
From the doc:

(DB, 1 hour) [Sprintable] Delete requirejs *.config files, and check for other cruft
Code that generates these (generate-config) should also be removed
JO: I’d like to review this when complete

Also, see https://github.com/phetsims/chipper/issues/852#issuecomment-582631910 (remove finalizeJS from scenery's package.json)

**Comment by jonathanolson** [comment]
I'm removing config files and other things, and I removed a lot of the old cruft.

Unassigning, we'll still want to do a check after all this is done.

**Comment by chrisklus** [comment]
From a duplicate issue: sim-config.js files should be deleted by migrate.

**Comment by jonathanolson** [comment]
Not sure why high priority was added to this, I made changes yesterday that will delete the sim config files in migrate.

**Comment by samreid** [comment]
Excellent, thanks!  Updating priority and assignees.

**Comment by samreid** [comment]
@jonathanolson anything else to delete here?

**Comment by jonathanolson** [comment]
Removed a few remaining configs above. I don't see anything else to remove at the moment, closing.
