### ISSUE TITLE
Upgrade to latest version of eslint

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#856]
From https://github.com/phetsims/chipper/issues/837#issuecomment-580585200, we are considering using dynamic imports for some PhET-iO features, like so:

```js
/* eslint-disable */
window.isPhetio = true;
window.isPhetio = false;
if ( window.isPhetio ) {

  import(   /* webpackMode: "eager" */ './phetio/phetio.js').then( m => {
    console.log( 'io', m.default );
  } );
}
else {
  import(   /* webpackMode: "eager" */ './phet.js').then( m => {
    console.log( 'phet', m.default );
  } );
}
```

The version of eslint we are on `~5.14.1` shows this error:

```
/Users/samreid/github/chipper/test-webpack-multi-brands/main.js
  6:3  error  Parsing error: 'import' and 'export' may only appear at the top level
```

Note this error is a parsing error and cannot be disabled via `eslint-disable`.

Eslint is currently at version: 6.8.0 and picked up support for dynamic imports in 6.2+, see https://github.com/eslint/eslint/releases/tag/v6.2.0

Here is a migration guide: https://eslint.org/docs/user-guide/migrating-to-6.0.0

**Comment by samreid** [comment]
After updating package.json to `"eslint": "^6.8.0",` and patching the recommended rules which changed in 6.0.0, 

```js
    // Match with 5.0 recommended rules after our upgrade to 6.0, see https://eslint.org/docs/user-guide/migrating-to-6.0.0
    "no-async-promise-executor": "off",
    "no-misleading-character-class": "off",
    "no-prototype-builtins": "off",
    "no-shadow-restricted-names": "off",
    "no-useless-catch": "off",
    "no-with": "off",
    "require-atomic-updates": "off",
```

I'm running into this problem:

```
~/github/chipper$ grunt lint-everything --disable-eslint-cache
Running "lint-everything" task
(Forwarding task to perennial)
Running "lint-everything" task
Fatal error: Perennial task failed:
Error: Failed to load plugin 'react' declared in 'binder/package.json': Cannot find module 'eslint-plugin-react'
Require stack:
```

I noticed @chrisklus worked on https://github.com/phetsims/binder/issues/26, can you please help?

**Comment by samreid** [comment]
There's also this error message, it seems the plugin resolution path `resolvePluginsRelativeTo` is wrong (one too high?)

```
Full Error details:
{
  "code": "MODULE_NOT_FOUND",
  "requireStack": [
    "/Users/samreid/github/__placeholder_.js"
  ],
  "messageTemplate": "plugin-missing",
  "messageData": {
    "pluginName": "eslint-plugin-react",
    "resolvePluginsRelativeTo": "/Users/samreid/github",
    "importerName": "binder/package.json"
  }
}
```

**Comment by samreid** [comment]
I found a new option that must be specified in the CLI:

```js
resolvePluginsRelativeTo: 'chipper/',
```

After that, lint-everything is working nicely, and binder lints correctly.  I'll commit shortly and notify the dev team to update their node_modules.  I don't know if npm update is automatic an CT, but I'll ask.

**Comment by samreid** [comment]
I messaged on Slack:

> Our ESLint has been upgraded from ~5.14.1 to ^6.8.0, please npm update chipper at your convenience.  I think CT will auto-update but I’m not sure, I’ll keep an eye on the next few columns.  Details are in https://github.com/phetsims/chipper/issues/856.  Let me know if you see any problems.

**Comment by chrisklus** [comment]
Sorry I didn't get to this in time, glad you found the solution.
