### ISSUE TITLE
ESLint parsing failure for dynamic import

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#857]
As described in https://github.com/phetsims/chipper/issues/837#issuecomment-580585200, lint fails to parse dynamic imports, even after upgrading to 6.8.0 in #856.  This problem is described here https://stackoverflow.com/questions/36001552/eslint-parsing-error-unexpected-token and https://stackoverflow.com/questions/47815775/dynamic-imports-for-code-splitting-cause-eslint-parsing-error-import and the recommended solution is to use the babel parser rather than the parser that ships with ESLint.  I tested it and it seems to work OK, but lint-everything is taking more than 5 minutes, which feels unacceptable.

```js
  parser: 'babel-eslint',
  parserOptions: {
    sourceType: 'module',
    allowImportExportEverywhere: true
  },
```

```
~/github/chipper$ time grunt lint-everything --disable-eslint-cache
Running "lint-everything" task
(Forwarding task to perennial)
Running "lint-everything" task


Done.

Done.

real	5m35.206s
user	5m58.863s
sys	0m7.964s
```

The only workaround I can think of is to isolate the dynamic module loading to a small trivial file which is excluded from linting.

**Comment by samreid** [comment]
Even when I ran with caching enabled, it still took 6 minutes to `lint-everything`

**Comment by zepumph** [comment]
Tagging https://github.com/phetsims/chipper/issues/857, as that issue is the reason we may have dynamic imports in the future.

**Comment by chrisklus** [comment]
Covered in #884, closing.
