### ISSUE TITLE
Fix filenames

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#86]
In #77 we discussed the naming of files.  @samreid renamed checkout-shas.js to checkoutShas.js since it is a file.  @pixelzoom renamed it back to checkout-shas.js to make it consistent with the other files.  To be consistent with our other projects we should name all of those auxiliary function files as camel-cased.

**Comment by samreid** [comment]
Renamed above so that filenames match var usage (as we do for our simulations), reassigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
I don't see any discussion of file names in #77, and I missed the fact that you renamed checkoutShas (wasn't mentioned in the commit message or any comment).  Camelcase for the .js files is fine. Any reason why we don't use camelcase for the grunt task names too?  This issue claims that "it's typical for task names to use camel case" (but I couldn't verify that claim): https://github.com/stephenharris/grunt-checktextdomain/issues/2

**Comment by samreid** [comment]
I don't feel too strongly about this--perhaps good to hear from other developers.  I'll add it to today's meeting agenda.

**Comment by pixelzoom** [comment]
1/20/15 developer meeting consensus: use camel case for source files, use hyphens for task names. That (coincidentally :) means no changes, so closing this issue.
