### ISSUE TITLE
Make sure unit tests run in ES6 modules

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#860]
I was reminded by https://github.com/phetsims/phet-io/issues/1512 that we discussed the need for qunit tests to run with es6 modules.

**Comment by jonathanolson** [comment]
We still need to get phet-io-wrapper unit tests working.

**Comment by samreid** [comment]
Axon tests are OK but Balloons and Static Electricity tests have trouble.  This should be investigated before migration.

**Comment by samreid** [comment]
I followed the list in continuous-server.js and only 3 failed:

* balloons-and-static-electricity (also fails on master)
* dot
* tandem

**Comment by samreid** [comment]
Hmmm, dot seems OK now (and I didn't change anything).

**Comment by samreid** [comment]
tandem unit tests are fixed after the commit

**Comment by samreid** [comment]
On hold until BASE is addressed.

**Comment by samreid** [comment]
After the above commits, all unit tests listed in continuous-server.js are passing, closing.
