### ISSUE TITLE
Formatting for es6 module imports

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#863]
Came up in discussion in the planning doc:

> ( ) [Dev team discussion] Will we keep // images comments?
SR/JO: That doesn’t seem useful anymore.
MK: why is this different from other comments like strings or text or mipmaps?
JO: We should discuss how we want to organize/sort/comment imports. This can change once we get used to the new system/style

So, do we want to keep the separate sections? I'm fine with that, and our current migrate results in:

```js
// modules
import areaModelCommon from '../areaModelCommon.js';
import AreaModelCommonColorProfile from '../common/view/AreaModelCommonColorProfile.js';
import GameAreaScreenView from '../game/view/GameAreaScreenView.js';
import GenericGameAreaModel from '../game/model/GenericGameAreaModel.js';
import Image from '../../../scenery/js/nodes/Image.js';
import inherit from '../../../phet-core/js/inherit.js';
import Screen from '../../../joist/js/Screen.js';

// images
import genericGameScreenIconImage from '../../images/generic-game-screen-icon_png_mipmap.js';
import genericGameScreenNavbarImage from '../../images/generic-game-screen-navbar_png_mipmap.js';

// strings
import screenGameString from '../../strings/screen.game.js';
```

We'll need to work on code that would sort import statements, and/or how do we have checks or systems for this?

We should check how Intellij handles auto-import, or if it can sort imports.

**Comment by jonathanolson** [comment]
I believe this can be included in the same issue:

> (CK, JO, 2-6 hours) [Sprintable, post-publication] Sort Require statements & tooling: Our "sort require statements" function will need to be revised, we could possibly switch to use https://eslint.org/docs/rules/sort-imports instead, which has an autofix function.
SR: The autofix function doesn’t change line order, maybe we should update our own tooling
JO: Presumably would delete insertRequireStatement code, and figure out Intellij/Sublime ways
JO: I’d like to investigate Sublime tooling, and compare with Intellij
SR: Sublime seems to have a plugin https://github.com/unlight/sublime-import-helper

**Comment by jonathanolson** [comment]
Webstorm supports this style of formatting out-of-the-box, where the paths seem to be lexicographically sorted, e.g.:

```js
import Screen from '../../../joist/js/Screen.js';
import inherit from '../../../phet-core/js/inherit.js';
import Image from '../../../scenery/js/nodes/Image.js';
import variablesScreenIconImage from '../../images/variables-screen-icon_png_mipmap.js';
import areaModelCommonStrings from '../area-model-common-strings.js';
import areaModelCommon from '../areaModelCommon.js';
import AreaModelCommonColorProfile from '../common/view/AreaModelCommonColorProfile.js';
import GenericAreaModel from '../generic/model/GenericAreaModel.js';
import GenericAreaScreenView from '../generic/view/GenericAreaScreenView.js';
```

However this is after removing line comments. If you start with the following:

```js
// modules
import areaModelCommon from '../areaModelCommon.js';
import AreaModelCommonColorProfile from '../common/view/AreaModelCommonColorProfile.js';
import GenericAreaModel from '../generic/model/GenericAreaModel.js';
import GenericAreaScreenView from '../generic/view/GenericAreaScreenView.js';
import Image from '../../../scenery/js/nodes/Image.js';
import inherit from '../../../phet-core/js/inherit.js';
import Screen from '../../../joist/js/Screen.js';

// images
import variablesScreenIconImage from '../../images/variables-screen-icon_png_mipmap.js';

// strings
import areaModelCommonStrings from '../area-model-common-strings.js';
```

and use Intellij's format (control-option-O on mac), you get this:
```js
import Screen from '../../../joist/js/Screen.js';
import inherit from '../../../phet-core/js/inherit.js';
import Image from '../../../scenery/js/nodes/Image.js';
// images
import variablesScreenIconImage from '../../images/variables-screen-icon_png_mipmap.js';
// strings
import areaModelCommonStrings from '../area-model-common-strings.js';
// modules
import areaModelCommon from '../areaModelCommon.js';
import AreaModelCommonColorProfile from '../common/view/AreaModelCommonColorProfile.js';
import GenericAreaModel from '../generic/model/GenericAreaModel.js';
import GenericAreaScreenView from '../generic/view/GenericAreaScreenView.js';
```

which is clearly less than ideal (for sectioning our imports). So either we'll presumably want to go with no-comment-labeled sections and Intellij sorting, or figure out another solution.

**Comment by jonathanolson** [comment]
Another solution could be either updating our sortRequireStatements script, or using a 3rd party code formatter that might be able to handle this (see https://github.com/phetsims/chipper/issues/761).

**Comment by zepumph** [comment]
At dev meeting today we decided to sort just like webstorm does automatically. This means we will get rid of `// images`-like comments and have one big block for all imports.

@jonathanolson: we want the comments to be stripped out in migrate. We will also sort the statements in the migrate.

**Comment by jonathanolson** [comment]
Implemented the handling for imports in migrate. Dropping high priority, will investigate Sublime support.

**Comment by jonathanolson** [comment]
Handled in the sublime plugin, closing.
