### ISSUE TITLE
Replace live namespace checks with lint rules

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#865]
> ( ) [DEV MEETING, post-publication, sprintable] Namespace Checking: We currently have an automatic namespace checker which relies on the r.js pool. Can/should we add something to replace it?
>JO: It’s not clear whether this is technically feasible, or valuable enough to invent something new.
>SR: Do we still need namespaces now that we can use circular references?
>> JO: I still use it for debugging and in the console.
>>> JO: Also, it’s nice to have scenery, kite, etc on a namespace, as well as some phet-io files
>> MK: I also think it is handy
>> JG: I think it’s nice but not critical
>> SR: Lint rule to cover some cases?
>>> JG: yes, sounds nice
>> SR: To clarify, we’re going to delete checkNamespaces.js and replace with a lint rule, which checks namespace.register(a,a) and makes sure a and a match.

**Comment by chrisklus** [comment]
@zepumph noted we could do this for the build - he's going to investigate.

**Comment by zepumph** [comment]
Similar to https://github.com/phetsims/chipper/issues/879, we could use the `stats` output of `compiler.run` in `webpackBuild.js` to get a list of all files loaded, and then perhaps create a plugin that can test that against the namespaces created. I'm not sure about this approach, but it is worth a bit of investigation. If it isn't fruitful, we can bring this to dev meeting to see how valuable this namespace check is.

**Comment by ariel-phet** [comment]
@jessegreenberg can invesitgate

**Comment by jessegreenberg** [comment]
An eslint rule for this was committed above, though it is not yet enabled. I will look through the the errors it found tomorrow and check in with devs before enabling this rule.

**Comment by jessegreenberg** [comment]
The rule was enabled and I fixed all the errors that it caught. I deleted checkNamespaces and removed its usage.

@jonathanolson is there anything else that should be done for this issue?

**Comment by jonathanolson** [comment]
Looks great to me, thanks!
