### ISSUE TITLE
Initial QA checks on es6 module migrated built sims, to make sure we aren't breaking things

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#867]
From the doc:

> (??, ?? hours) QA Testing for new sims.
We should have a QA cycle testing some of the migrated sims so we can make sure everything is working across our platforms.

**Comment by zepumph** [comment]
During dev meeting today, we weren't quite ready for this, but we still want this before we flip the switch.

@jonathanolson is shooting for https://github.com/phetsims/chipper/issues/844 to be a bit further on first.

**Comment by zepumph** [comment]
@samreid recommended a sim that is about to go through RC anyways (like build-a-molecule), as well as something that JUST went through RC, like number-line, to help isolate the effects of es6-module conversion.

**Comment by samreid** [comment]
From today's meeting, the QA test will be important to test a sim on every supported platform.  All tests will be on compiled published dev versions, not compilation-free mode.

Stage 1: Basic test on all platforms, for 2-3 sims.
* Does the sim run and behave normally
* Fuzz the sim for 30 seconds

Stage 2: Just 1-2 sims on a few platforms:
* Do the strings display naturally
* Does English work and Spanish work? and zh_cn?  Use the all file and locale specific files for that.
* Check phet brand, and phet-io brand and adapted-from-phet including credits and licensing
* JB: We will need to test rosetta on a built ES6 sim. @jbphet will create a side issue for that.
* a11y view - do they run and seem ok
* iframe test - do they run
* XHTML
* PhET-iO wrappers
* Check a few sims in the debug version of the iOS app.

**Comment by jonathanolson** [comment]
I have those three sims available in https://phet-dev.colorado.edu/modules-testing/, will be creating the QA issue. It looks like phet-io brand is working well, so I'd like to have that tested.

**Comment by jonathanolson** [comment]
Removing assignment since QA is testing (and it should include our checks)

**Comment by chrisklus** [comment]
QA is finished and all blocking issues have been addressed, closing with @samreid @zepumph
