### ISSUE TITLE
Linting in ES6 modules

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#870]
From the planning doc:

> (DB,1-2 hours to finish linting acid base solutions, uncertain how much lint trouble there is in other repos) [sprintable pre-publication] Lint: Lint-everything should pass, see https://github.com/phetsims/chipper/issues/837
AP: Maybe MK doesn’t need to take the lead on this.
DB: I could help on this part

**Comment by Denz1994** [comment]
Steps used to checkout ES6 module:
```
cd chipper
git checkout webpack
npm update
git pull
cd ..
./perennial/bin/for-each.sh perennial/data/active-common-sim-repos grunt milagro
cd my-simulation
grunt milagro
```
After running through the above commands we can do a few things:
- `grunt lint` from repo
-  try building if it's a sim repo
-  running the sim in the browser to check for failures

We can revert back to master by running ```./perennial/bin/revert-migrate.sh```. If there are any working changes we'll have to run ```git reset --hard``` in the repo. @samreid and I thought it would be good to try out the above steps on a sim like ABS and a common repo then try a larger set of repos.

**Comment by Denz1994** [comment]
Reporting linting error:
```
phet/scenery-phet/js/Drawer.js
  275:26  error  Parsing error: 'import' and 'export' may only appear at the top level
```

**Comment by Denz1994** [comment]
Running ```./perennial/bin/for-each.sh perennial/data/active-common-sim-repos grunt lint``` triggered many errors related to console logs like so:

```
/Users/denz1994/Git/phet/vegas/js/demo/RewardScreenView.js
  35:11  error  Unexpected console statement  no-console
  39:11  error  Unexpected console statement  no-console
```

**Comment by samreid** [comment]
@zepumph said he knew something about the `no-console` rule.  Does something need to be done in the chipper/webpack branch?

**Comment by zepumph** [comment]
@Denz1994 the issue that caused that is over in https://github.com/phetsims/chipper/issues/876

Nothing needed here.

**Comment by samreid** [comment]
Currently there are 3 lint-everything problems that should be addressed before migration.

```
/Users/samreid/github/balloons-and-static-electricity/js/balloons-and-static-electricity-tests.js
  9:43  error  Parsing error: Unterminated regular expression

/Users/samreid/github/faradays-law/js/faradays-law-tests.js
  9:43  error  Parsing error: Unterminated regular expression

/Users/samreid/github/normal-modes/js/two-dimensions/model/TwoDimensionsModel.js
  16:8  error  'Tandem' is defined but never used  no-unused-vars

✖ 3 problems (3 errors, 0 warnings)

```

**Comment by samreid** [comment]
All issues fixed, closing.
