### ISSUE TITLE
Cyclic dependencies in es6 modules

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#871]
> (JO, [SR?] 2-4 hours) [sprintable, JO investigated] Cyclic Dependencies: ES6 modules support cyclic dependencies. So places like scenery and dot, where we had to "trick" the runtime with an assignment-less require statement and then loading things from the namespace will no longer be necessary.
What to do with this pattern and cycles in general? window.require = function(){}; // TODO: https://github.com/phetsims/chipper/issues/820 this supports like require( 'DOT/Utils' ); in Vector2
JO: Cyclic dependencies in our classic style look fine. See https://github.com/phetsims/chipper/issues/820#issuecomment-579395283 for details, use empty imports (import ‘../repo/js/Blah.js’) if we just need to ensure code runs (our migrate will need to change to include this).
JO: Commented-out require statements could be added back in, and use the cyclic form

I'll investigate commented-out require statements, we can potentially just uncomment those and test.

After the fact, I'll also want to do some cleanup in those cases

**Comment by jonathanolson** [comment]
Handled, we're now uncommenting those require statements and it's working nicely.

Keeping open to handle cleanup after full migrate, but dropping priority.

**Comment by samreid** [comment]
Balloons and static electricity exhibits a problem where `scenery.Image` does not exist when `Node.rasterized` is called.  @jonathanolson how do you recommend to proceed?

**Comment by samreid** [comment]
From slack:

Jonathan Olson  5:55 PM
Just have an empty import in Node?

Sam Reid  6:00 PM
I tried but that creates a cycle and fails to load.  Image cannot be defined until Node definition completes

Jonathan Olson  6:01 PM
Then put an empty import where we use rasterize?

Sam Reid  6:02 PM
At each of the top-level call sites?

**Comment by jonathanolson** [comment]
Created https://github.com/phetsims/scenery/issues/1038 for handling that case. I presume we aren't running into any other issues?

**Comment by samreid** [comment]
As far as I can tell, this only triggered in Balloons and Static Electricity, and the workaround I committed seems to be working OK.

**Comment by chrisklus** [comment]
@jonathanolson is there anything to do here? @samreid thinks this might be ready to close.

**Comment by jonathanolson** [comment]
Keeping it open for https://github.com/phetsims/chipper/issues/871#issuecomment-583086655, since things like Vector2/Vector3 will want to not JUST import each other, but USE those imports (which I can't do easily in master before migration).

**Comment by jonathanolson** [comment]
Handled most circular dependency issues. Things like Block/Drawable seem like an issue (where interestingly if we try to import Block from Drawable, it will fail out and I can't identify where that import would cause issues.

@samreid thoughts to continue?

**Comment by jonathanolson** [comment]
The above commit seems to resolve scenery builds, but that's really concerning. @samreid have time to discuss this sometime?

**Comment by samreid** [comment]
Since the commit includes sorting, it is difficult to tell what part is concerning.  Can you please clarify?

**Comment by jonathanolson** [comment]
That removing the import for ParallelDOM in the scenery main.js now allows it to run correctly after building.

And the fact that there were a lot of reasons I couldn't add back in all the imports we wanted (Block/Drawable being most easy to reproduce).

**Comment by jbphet** [comment]
We discussed this in the 6/4/202 dev meeting and the memorable quote was "[T]his is low priority until it becomes a problem."  So, we are going to mark it as deferred and assign it to @ariel-phet.  He'll set a reminder to check it in six months and, if it's not a problem by then, we will close it.

**Comment by ariel-phet** [comment]
Calendar reminder set
