### ISSUE TITLE
Best practices for ES6 modules

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#873]
From the planning doc:

> (CM, ??, 2 hours initial? 10 minutes-16 hours on implementation?) [sprintable, post-publication, but would be good to crystallize soon while the concrete is wet.  JO investigated] Best Practices: We will need to discuss "best practices" for using module import/export. Right now development is set up around export default and import default but there are other features we should consider. This may be a good match for dot/Utils where we just want to require certain methods, for instance. We can also use renaming during import to distinguish between SCENERY/Line and KITE/Line sort of cases.
JO: I believe named exports are useful and ideal in cases of “utils” and “constants” files, recommendations in https://github.com/phetsims/chipper/issues/820#issuecomment-579395283, but the rule will be to use export default and import default.
Investigate new lint rules such as https://github.com/benmosher/eslint-plugin-import

I think this is some time generally looking at module use by other organizations, and general recommendations for things. Also should include the multiple import/export handling.

**Comment by pixelzoom** [comment]
@jonathanolson said:
> JO: I believe named exports are useful and ideal in cases of “utils” and “constants” files, recommendations in #820 (comment), but the rule will be to use `export default` and `import default`.

I agree with this.  For things like "utils" and "constants", I think it might be nice to have both named exports and default export.

See [ECMAScript 6 modules: the final syntax](https://2ality.com/2014/09/es6-modules-final.html) for a nice reference.

**Comment by pixelzoom** [comment]
Features that we should discuss, to decide whether to use them, standardize their usage, etc.

* Having both named exports and a default export in a module

* Multiple `export` keywords in a file vs one `export` statement at the end of the file

* Referring to exports via property notation, e.g.
`import * as lib from 'lib';`

* Renaming exports, e.g. 
`export { MY_CONST as THE_CONST, myFunc as theFunc };`

* Renaming imports, e.g. 
`import { named1 as myNamed1 } from 'src/mylib';`

* Re-exporting - adding another module’s exports to those of the current module. e.g. 
`export { foo as myFoo, bar } from 'src/other_module';`

**Comment by pixelzoom** [comment]
Best practices for `export`: https://ponyfoo.com/articles/es6-modules-in-depth#best-practices-and-export. Summary: "just use export default everywhere and be done with it. ... When paired with the convention of always using export default and always doing it at the end of your modules, you’ll note using the ES6 module system to be painless."

**Comment by pixelzoom** [comment]
Here's a compelling argument for `import` at the top of the module, and `export` at the end of a module.

Any module has this basic structure:

```
imports 

code 

exports
```

By putting all exports at the end of the module, the exported interface is immediately obvious. Instead of having to browse the entire module and to figure out the API, you just scroll to the end.

Similarly, putting all imports at the top of the module makes it determine a module's dependencies.

**Comment by jonathanolson** [comment]
> ES6 modules enable strict mode by default. Do we no longer need 'use strict';?

Not in module files (the majority of our JS)

**Comment by samreid** [comment]
From today's meeting, until we discuss this further, the policy should be to `export default` and `import default` only, and the few occurrences of dynamic `import()`.

**Comment by pixelzoom** [comment]
My recommendation for best practices:

* Put all `imports` at the top of the .js file.

* Use `export default` as the primary convention, placed at the end of the .js file.

* Do not rename imports and exports.

* Do not re-export modules.

* If you encounter an exception to these practices, discuss on Slack.  Modify the best practices if necessary, and/or document (at the use site) why you needed to diverge from the best practices.

Example of diverging from best practices:  SimLauncher has a legitimate need to put imports inside of conditionals.  It should document why ("to support multiple brands")  but currently does not.

When we have consensus on best practices, where should they live? In the CRC?

**Comment by pixelzoom** [comment]
Conversion of my sims is complete, except for these classes:

* equality-explorer: TermDragListener, UniversalOperationControl
* unit-rartes: DoubleNumberLineAccordionBox, ShoppingQuestionsAccordionBox

All of these have complicated "`this` before `super`" issues.

**Comment by pixelzoom** [comment]
3/5/20 dev meeting:

We reviewed and refined https://github.com/phetsims/chipper/issues/873#issuecomment-594079287.  I'll paste that into a new section of the CRC titles 'Exports and Imports'.

**Comment by pixelzoom** [comment]
To reduce clutter in the CRC, I added an item that links to a .md file:

> - [ ] Verify that [Modules Best Practices](https://github.com/phetsims/phet-info/blob/master/doc/modules-best-practices.md) are followed.

@Denz1994 randomly selected to review.

**Comment by Denz1994** [comment]
The item has been added to the CRC Coding Conventions section and the document captures what was discussed in our latest dev meeting. I should reference this doc in the Modules section of the phet-software-design-pattern doc (see https://github.com/phetsims/phet-info/issues/134).

Very minor grammatical point: Shouldn't "Modules Best Practices" be "Modules' Best Practices"? 

I'll leave to @pixelzoom to close this issue. Otherwise, thanks for updating the documentation.

**Comment by pixelzoom** [comment]
Thanks @Denz1994.  I've change the document title to "Best Practices for Modules".
