### ISSUE TITLE
Get aqua passing for es6 modules

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#874]
From the planning doc:

> (SR, JG 6 hours?) [pre-publication, sprintable] Get Aqua passing for compilation-free mode for all sims.
SR: Many are failing due to the race condition mentioned in https://github.com/phetsims/chipper/issues/843.  Others are failing from miscellaneous parts that haven’t been migrated correctly or fully.

**Comment by jessegreenberg** [comment]
It looks like https://github.com/phetsims/chipper/issues/843 has been resolved.

**Comment by samreid** [comment]
Here's a snapshot of the first page of local aqua:

![image](https://user-images.githubusercontent.com/679486/74993417-21195000-5408-11ea-8411-e68a27736df2.png)

**Comment by samreid** [comment]
Everything is passing except for a string problem in density and buoyancy.

**Comment by jonathanolson** [comment]
I believe this was fixed in density-buoyancy-common master. Can this be closed then, or do we re-run right before migrate?

**Comment by samreid** [comment]
Ideally we would re-run after any significant changes, and also again right before migrate in case any untested changes creep in.  Nothing to do for now, so I'll remove the label?

**Comment by samreid** [comment]
I added this as a pre-migrate step, closing.
