### ISSUE TITLE
Allow console.log statements in production build with lint?

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#876]
Promoting TODO to issue from .eslintrc.js:

```
    // Permit console.log statements (we have a lot of them)
    // TODO: Find a way to make sure no console.log statements make it to production.  Can use the no-console rule
    // but we want to be able to use console.log during development.
    'no-console': 0,
```

I think it initially sounds reasonable to try to remove these on production, but perhaps it isn't even worth investigation, since it seems to not be needed.

The TODO was added back when eslint was first added in 2015: https://github.com/phetsims/chipper/issues/235.

Personally I don't think it is a needed distinction. @samreid can you please comment at a low priority about your thoughts on this? 

To me allowing console.log in production builds is fine, since I haven't seen it as a problem for the last few years.

Removing that code now that there is an isssue.

**Comment by samreid** [comment]
I recommend we forbid console.log statements in RCs and production versions.  But since it could be useful to commit these for development, maybe it is better as a QA RC checklist item than a lint item?

**Comment by zepumph** [comment]
What about special lint rules that are used only for rc/production calls in perennial? That sounds pretty obfuscated. 

Maybe we make a new grunt task called `grunt lint-production`, so at least you can check to see if it passes before running the perennial task.

**Comment by zepumph** [comment]
I messed up reverting that commit. I didn't understand that it was relaxing the no-console rule from `eslint:recommended`. I reverted above. Thanks @jbphet for your patience!

**Comment by samreid** [comment]
I turned on this rule temporarily and saw 197 violations across many repos.  It seems unlikely that we would want to eliminate all of these for a production build.  Therefore, I recommend we remove this entry from the .eslintrc.js and close this issue.  We can always change our minds later but this seems reasonable for now.

**Comment by samreid** [comment]
Removed the disabled rule and corresponding TODO, closing.
