### ISSUE TITLE
"isPhetApp" doesn't belong in Brand

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#878]
Discovered in https://github.com/phetsims/chipper/issues/844, one of the brands has this code:

```js
  const Brand = {
    id: 'phet',
    name: 'PhET\u2122 Interactive Simulations', // no i18n
    copyright: 'Copyright © 2002-{{year}} University of Colorado Boulder', // no i18n
    isPhetApp: phet.chipper.queryParameters[ 'phet-app' ] || phet.chipper.queryParameters[ 'phet-android-app' ],
    getLinks: getLinks
  };
```

Whether the sim is running in the app or not is orthogonal to its "brand", so this should be moved elsewhere.

Marking as high since this should be addressed before the ES6 migration.

**Comment by samreid** [comment]
Fixed in the above commits.  I'm not sure how to test this in the app contexts, so I'd like to request a careful review from @mattpen.  Marking as blocks publication until reviewed so we can make sure no bugs creep into the new sim publications.

**Comment by mattpen** [comment]
@samreid Can you publish a dev test with this change so we can test in the apps?

**Comment by samreid** [comment]
I published https://phet-dev.colorado.edu/html/gravity-and-orbits/1.2.0-dev.7/phet/gravity-and-orbits_en_phet.html.

**Comment by mattpen** [comment]
Thanks Sam.

@KatieWoe - Can you do a brief spot test of that sim with the debug build for the ios app?

I'll test this in the Android App with @shreyas-g-ucb.

**Comment by KatieWoe** [comment]
Looked at app on iPadOS 13.3.1. Loaded fine there. Unrelated bug found for Gravity and Orbits. Documenting in that repo.

**Comment by zepumph** [comment]
@mattpen, 

Today @samreid, @chrisklus, and I reviewed @samreid's commits above, and searched for other usages of the `phet-app` query parameter. From this and @KatieWoe's test we feel good to close. Is there anything else from you before closing?

**Comment by mattpen** [comment]
Yes, this looks fine.  @shreyas-g-ucb and I tested this in a debug build of the Android App and it went fine.
