### ISSUE TITLE
sim.html creates an unnecessary global

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#88]
Code in question, from sim.html:

```html
<script type="text/javascript">
  window.phetStringOverrides = JSON.parse( decodeURIComponent( phet.phetcommon.getQueryParameter( 'strings' ) || '{}' ) );
  window.phetStrings.get = function( key ) {

    //Support translation by query parameter to enable translation in the browser
    return window.phetStringOverrides[ key ] || window.phetStrings[ key ];
  };
</script>
```

window.phetStringOverrides is used only in the closure, it doesn't need to be a global. Should be using an IIFE with phetStringOverrides as a local var.

**Comment by pixelzoom** [comment]
Tested with requirejs and built versions of Acid-Base Solutions.  Assigning to @jonathanolson for review.

**Comment by jonathanolson** [comment]
Looks good. I presume window.phetStrings => window.phet.strings will happen in another issue, closing.
