### ISSUE TITLE
Mipmaps are applied inconsistently

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#880]
Discovered during #840 and #836, I noted our project has inconsistent application of mipmaps.  For instance, in Molecules and Light, infrared-source.png is a mipmap, but infrared-source-off.png is an image.  How can we determine which images should be mipmapped and which should be standard images?

Or shall we postpone discussion of this issue until #840 is complete?

**Comment by pixelzoom** [comment]
@samreid,  in Molecules and Light, infrared-source.png was used in 2 places: PhotonEmitterNode and QuadEmissionFrequencyControlPanel.  In the former, there's no need for a mipmap because the image is displayed at about the same size as the PNG file.  In QuadEmissionFrequencyControlPanel, there was a need for mipmap because the image is scaled by 0.27 and that caused artifacts on older Firefox. (See commits https://github.com/phetsims/molecules-and-light/commit/74652f2111d4e02ce26121a288bbf1f5af05a81c and https://github.com/phetsims/molecules-and-light/commit/60684c18cb6c8b4b678ce0f22da247352215df42.)

So I don't see any consistent here at all.  Different .js files have different needs for the same image. And different .js files could choose where to use `image!` or `mipmap!` to meet their needs.   What's changing with the switch to ES6 modules is that if any .js file has a need for mipmap, then all .js files will import the mipmap.

**Comment by samreid** [comment]
But if you have loaded the `mipmap!` of an image, it should be used instead of loading a separate `image!` of the file.  Otherwise you are unnecessarily bloating the download size.

**Comment by samreid** [comment]
PhotonEmitterNode.js has this code:

```js
  const heatLampOffImage = require( 'image!MOLECULES_AND_LIGHT/infrared-source-off.png' );
  const heatLampOnImage = require( 'mipmap!MOLECULES_AND_LIGHT/infrared-source.png' );

// ...

        this.photonEmitterOnImage = new Image( heatLampOnImage );
        this.photonEmitterOffImage = new Image( heatLampOffImage );

// ...

      // scale the on image by the desired width of the emitter and add to top
      this.photonEmitterOnImage.scale( emitterWidth / this.photonEmitterOnImage.width );
      this.photonEmitterOnImage.center = new Vector2( 0, 0 );
      this.addChild( this.photonEmitterOnImage );

      // scale, center, and set opacity of 'off' image - no 'off' image for microwave emitter
      if ( photonWavelength !== WavelengthConstants.MICRO_WAVELENGTH ) {
        this.photonEmitterOffImage.scale( emitterWidth / this.photonEmitterOffImage.width );
        this.photonEmitterOffImage.center = new Vector2( 0, 0 );
        this.photonEmitterOffImage.setOpacity( 1 - emissionFrequency );
        this.addChild( this.photonEmitterOffImage );
      }
```

Two images that have the same scaling and are used in similar ways are loaded with different plugins (`heatLampOffImage` is image and `heatLampOnImage` is mipmap).

> So I don't see any consistent here at all. Different .js files have different needs for the same image. 

If one file is needed as image! and as mipmap!, I recommend to only load it as mipmap! and use that in both places to avoid download bloat, so the image isn't loaded 2x in the download.

**Comment by pixelzoom** [comment]
> Two images that have the same scaling and are used in similar ways are loaded with different plugins

That was not the case until you ran your conversion script.  See https://github.com/phetsims/molecules-and-light/commit/0f194d9ad33c5c9c179f80c16ecd0942abd7a581. 
All of the images loaded in PhotonEmitterNode.js were using the `image!` plugin until your conversion script changed them.    Only the "On" images are used in `QuadEmissionFrequencyControlPanel`, so they are the only images that are loaded using `mipmap!` in the sim. 

> I recommend to only load it as mipmap! and use that in both places to avoid download bloat, so the image isn't loaded 2x in the download.

So every time I load an image, I'm supposed to look to see if it's already loaded elsewhere? And what is going to enforce that? And isn't this moot once we move to the new ES modules paradigm?

**Comment by samreid** [comment]
Thanks for correcting me!  The conversion process created a separate directory for mipmaps/ and images/ and I decided to reuse `const heatLampImage = require( 'mipmap!MOLECULES_AND_LIGHT/infrared-source.png' );` as a mipmap rather than copy/pasting the image to images/.  

There were 2 problems for this issue:

(1) Why would one image be mipmapped and the other not, when they are used in similar circumstances?  You explained that this was not the case, but an artifact of the conversion.  Thanks for correcting me on that!
(2) Should we load a PNG as both a mipmap and an image?

My opinion is that if an image is already loaded as a mipmap, then it shouldn't be duplicated as an image.  Even when the mipmaps/ and images/ directories were combined, this incurred 2x bloat in the  download file.  

> So every time I load an image, I'm supposed to look to see if it's already loaded elsewhere?

If you are thinking a sim needs `image!puppy.png` but notice it already has `mipmap!puppy.png`, why not use `mipmap!puppy.png` to reduce the download size and the repo bloat?  Mipmaps should be substitutable for images anywhere (unless, say, used as a texture for WebGL or something unusual).

**Comment by pixelzoom** [comment]
> My opinion is that if an image is already loaded as a mipmap, then it shouldn't be duplicated as an image.

Sounds like a plan.  Will we need tooling to enforce that?

**Comment by samreid** [comment]
Maybe we should wait to hear about https://github.com/phetsims/chipper/issues/840.  If we no longer need mipmaps it would obviate this problem, or if we only need them in rare circumstances, it could change how we approach the problem.

**Comment by pixelzoom** [comment]
3/5/20 dev meeting:

If it turns out that we still need mipmaps of decide to keep the functionality around for future use... Then if there's already a mipmap.js, use it, don't create an image.js - on your honor for now, add tooling (and create a new issue) if it becomes a problem. Add a line to the CRC. @pixelzoom will do this.

**Comment by pixelzoom** [comment]
In the [Repository Structure](https://github.com/phetsims/phet-info/blob/master/checklists/code_review_checklist.md#repository-structure) section of the CRC, I added:

> - [ ] Verify that the same image file is not present in both images/ and mipmaps/. If you need a mipmap, use it for all occurences of the image.
