### ISSUE TITLE
Should we output deprecation warnings?

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#882]
Should we add a query parameter like `?deprecationWarnings`, then in deprecated code we could do something like this?

```js
/**
 * A drag handler for something that has a position and is constrained to some (optional) bounds.
 *
 * @author Chris Malley (PixelZoom, Inc.)
 * @author Sam Reid (PhET Interactive Simulations)
 * @deprecated - please use DragListener for new code
 */
define( require => {
  'use strict';

  // modules
  // ...

  /**
   * @param {Property.<Vector2>} positionProperty - in model coordinate frame
   * @param {Object} [options]
   * @constructor
   */
  function MovableDragHandler( positionProperty, options ) {
    deprecationWarning();
    const self = this;
```

Then we could add a step to the code review checklist or QA checklist to make sure no deprecated code is used when it shouldn't be.

**Comment by pixelzoom** [comment]
I was thinking that a lint rule would be preferable. I investigated the suggestions at https://github.com/eslint/eslint/issues/6250, but didn't find anything that would meet this need.

**Comment by chrisklus** [comment]
I like the console idea a lot!

>I was thinking that a lint rule would be preferable.

Wouldn't that also hit older sims that we aren't planning on bringing up to date any time soon?

**Comment by pixelzoom** [comment]
> Wouldn't that also hit older sims that we aren't planning on bringing up to date any time soon?

Yes, but if it's a warning, that should still be acceptable right?

**Comment by pixelzoom** [comment]
3/5/20 dev meeting:

```
deprecationWarning( deprecatedThing ) {
  if ( !phet.chipper.queryParameters. deprecationWarnings ) {
    console.warn( 'WARNING: ${deprecatedThing} is deprecated' ); 
  }
}
```

Usage:

```js
/**
 * ...
 * @deprecated
 */
someMethod(...) {
  assert && deprecationWarning( 'someMethod' );
  ...
}
```

For deprecated classes, put it outside the class definition, so that it's logged once when the model is loaded. 

Add to CRC: 

> Run with ?deprecationWarning.  Do not use deprecated methods in new code.

Volunteer: @jessegreenberg

**Comment by samreid** [comment]
I wanted to use this to move forward in Gravity and Orbits review, and @jessegreenberg said to go for it!

**Comment by samreid** [comment]
The commits provide basic functionality for this feature.  There were a few spots where I could not use this warning system:

initialize-globals:

```js
    /**
     * Master volume control for the simulation.  Range is from 0 to 1, which is typical for web audio gain nodes.
     * 1.0 is unity volume, 0.5 is half volume, etc. This is primarily for Vibe sounds.
     * @deprecated see https://github.com/phetsims/vibe/issues/33
     * @type {number}
     */
    audioVolume: {
      type: 'number',
      defaultValue: 1,
      isValidValue: function( value ) { return value >= 0 && value <= 1; }
    },
```

Mouse.js

```js
function Mouse() {
  Pointer.call( this, null, false, 'mouse' );

  // @public {number|null} - Since we need to track the mouse's pointer id occasionally
  this.id = null;

  // @public {boolean} @deprecated, see https://github.com/phetsims/scenery/issues/803
  this.leftDown = false;
```

Pointer.js
```js
// @deprecated @public {BooleanProperty} - Whether this pointer is 'down' (pressed).
```

SunConstants.js

```js
  /**
   * Numbered placeholder in string patterns where a value will be substituted.
   * Typically appears in translated strings (e.g. "{0} nm") and used with StringUtils.format.
   * @deprecated - Named placeholders are the new standard, and numbered placeholders should not be used in new code.
   */
  VALUE_NUMBERED_PLACEHOLDER: '{0}',
```

@jessegreenberg can you please review and recommend how to proceed with the above `@deprecated` things?

**Comment by samreid** [comment]
After implementing this, I'm wondering if the class-level deprecation warnings should move to constructors so we can get stack traces.  We could add a cache in `deprecationWarning.js` so it doesn't output the same message twice.

**Comment by jessegreenberg** [comment]
This is looking great, thanks.

> I'm wondering if the class-level deprecation warnings should move to constructors so we can get stack traces.

After testing ?deprecationWarnings in gravity-force-lab-basics I agree. I got a deprecation warning for SimpleDragHandler and started searching gravity-force-lab-basics, gravity-force-lab, and inverse-square-law-common for a usage of SimpleDragHandler, but eventually discovered that the usage was by Slider in sun. Having a trace to point to this would be helpful.

I did this in the above commits, @samreid can you review?

**Comment by samreid** [comment]
I revised the code review document to use `?deprecationWarnings` instead of `?deprecationWarning`.  Everything else looks great, thanks!
