### ISSUE TITLE
SimLauncher is the only file that should be linted with babel-eslint

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#884]
From https://github.com/phetsims/chipper/issues/844 and related to https://github.com/phetsims/chipper/issues/870.

See **https://github.com/phetsims/chipper/issues/844#issuecomment-586061885** for specifics

We added babel-eslint as the linting parser for joist because the default eslint parser can't recognize dynamic imports. We found there that babel-eslint is much slower (taking over 5 minutes to complete a lint-everything when using babel-eslint for the whole project). We also don't want to allow dynamic imports anywhere but in SimLauncher. 

With these constraints in mind, @samreid and I suggest the following:
* Move `SimLauncher.js` to a sub directory in joist/js called `dynamic-imports-allowed` or something
* add an `eslintrc.js` file that looks like:
```
"extends": "../chipper/eslint/sim_eslintrc.js",
    "parser": "../chipper/node_modules/babel-eslint",
    "parserOptions": {
      "sourceType": "script",
      "allowImportExportEverywhere": true
    }
```

@samreid said that he tried this at one point, but that it didn't work because some part of project didn't know how to find that file.

This can happen after the migration.

**Comment by zepumph** [comment]
We should also investigate why https://github.com/phetsims/tandem/commit/a67d85966f21dab17e126fb4b4ca27241a3ad720 was needed.

**Comment by samreid** [comment]
There is a dynamic module import in the unit tests.

**Comment by zepumph** [comment]
Oh boy.

**Comment by zepumph** [comment]
We have isolated this to a single import for all unit tests (qunitStart.js), and simLauncher.js. @samreid are you ready to close this issue?

**Comment by samreid** [comment]
Looks great, and I confirmed that chipper specfies:

```json
    "parserOptions": {
      "sourceType": "module",
      "allowImportExportEverywhere": true
    }
```

Closing.
