### ISSUE TITLE
Phet-io More things password protected than before

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/chipper#886]
For https://github.com/phetsims/QA/issues/482.
According to the QA book it says:
>The Simulation, Events:colorized, and Events:json are not password protected.

However, in the version being tested all three are behind a password.

**Comment by jonathanolson** [comment]
That's a result of me manually password-protecting everything under phet-io since it wasn't technically a "deployment". This shouldn't be a problem for actual deployments.

Thank you for noticing and reporting!
