### ISSUE TITLE
IE sims don't open es6 dev versions

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/chipper#887]
All three sims don't open/load in IE with the following error.
![Promiseundefined](https://user-images.githubusercontent.com/41024075/75180441-7485e980-56f9-11ea-864a-20819ee5806f.png)

**Comment by KatieWoe** [comment]
For https://github.com/phetsims/QA/issues/482

**Comment by samreid** [comment]
Elevating priority since this would block publication with ES6 modules.

**Comment by jonathanolson** [comment]
(And investigating, I'll let you know details soon)

**Comment by jonathanolson** [comment]
Github wasn't letting me comment earlier. This is resolved in the chipper webpack branch, I'll have new builds soon.
