### ISSUE TITLE
assert not found

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#89]
86f31c341e8d72d58b6e371099fdaeafd86dd01c introduced asserts, but I am now getting this exception running a built version:

<exception>: ReferenceError: assert is not defined
message: "assert is not defined"

This is high priority since it means no built sims can be launched until this is fixed.

**Comment by samreid** [comment]
I've commented out the offending line until we can investigate this further.

**Comment by jonathanolson** [comment]
Two things:
1. I can't reproduce the problem when uncommenting the line, at least with Molecule Shapes
2. The assertion is not at all needed unless you set window.phet.chipper.strings to something that evaluates to false but can have something assigned to it (e.g. an empty string!).

Since setting window.phet.chipper.strings.get will almost assuredly fail with a hard exception whenever the assertion failed, I'd say let's just get rid of it for now.

**Comment by pixelzoom** [comment]
I can't reproduce either. What sim are you running?

And I'm wondering why assert is not defined. It should be loaded before this piece of code, where PRELOAD_INLINE_JAVASCRIPT is in the html file.

But if you don't want to investigate further, I agree with @jonathanolson's comment above, ok to remove the assertion.

**Comment by samreid** [comment]
Steps to reproduce:
0. uncomment the assert lines in sim template
1. cd forces-and-motion-basics
2. grunt
3. open the built version

receive `<exception>: ReferenceError: assert is not defined`

Trying the same instructions for rpal:  no problem.  Perhaps something buggy with forces-and-motion-basics preload order??

**Comment by samreid** [comment]
I noticed rpal/package.json has phetLibs: assert  AND preload: ../assert/js/assert.js

Is one of those incorrect?

**Comment by samreid** [comment]
I found that fpaf was missing an assert.js preload.  After adding it, everything worked properly.  So I decided to resurrect the assert since it helped us find problems like this.  Reassigned to @pixelzoom to discuss the question in the above comment:

> I noticed rpal/package.json has phetLibs: assert AND preload: ../assert/js/assert.js

> Is one of those incorrect?

**Comment by pixelzoom** [comment]
> I noticed rpal/package.json has phetLibs: assert AND preload: ../assert/js/assert.js
> Is one of those incorrect?

dependencies.json is generated from phetLibs in package.json.  And we most certainly want the sha for the `assert` repo in dependencies.json.  So any sim that's *not* including assert in phetLibs is in error.

**Comment by samreid** [comment]
I think the problem here is solved.  And thanks to the assert statement we will identify sims missing the assert preload.  If we want to make sure all package.json have assert entries for SHAs, perhaps that should be addressed during development of the automatic file generation.
