### ISSUE TITLE
Reentry detected on fuzz test

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/chipper#890]
For https://github.com/phetsims/QA/issues/482. Seen once when fuzz testing Build an Atom debug version on ChromeOS. The sim was on the home screen, but it was white instead of black, and the console gave a reentry detected error. Haven't managed to replicate. Will post update if I can replicate.

**Comment by KatieWoe** [comment]
Fuzz testing on ChromeOS seems a bit slower in addition.

**Comment by jonathanolson** [comment]
Running the testing on my end. Was it after running for a while, or fairly immediate?

**Comment by KatieWoe** [comment]
Fairly immediate

**Comment by jonathanolson** [comment]
I'm not able to reproduce so far. @samreid do you know more about this (potentially homescreen and reentry-related issue), or what could cause it? Or if this is something we should ignore?

**Comment by zepumph** [comment]
@samreid, @chrisklus, and I were not able to reproduce this either, both on master and when fuzzing the debug version of BAA. That said I don't have a ChromeOS device to go one step further.

**Comment by samreid** [comment]
@KatieWoe can this be replicated?  How about on other platforms?

**Comment by KatieWoe** [comment]
I haven't been able to replicate it since.

**Comment by samreid** [comment]
I recommend we close this issue for now--can reopen if it appears again.  Thanks for reporting it!
