### ISSUE TITLE
delete or restore no-html-constructors lint rule

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#891]
@samreid and I were experimenting with auto-imports in WebStorm, and had difficultly with conflicts between built-in types and PhET types (e.g. Text, Rectangle,...).  I was surprised that these weren't being flagged by lint, since I recalled a lint rule for this.

In 9baefa17f7f63c648f098a1fad62296ab31d3628, @jonathanolson commented out this lint rule in eslint.rc:

```
    // Custom rule for ensuring that images and text use scenery node
    // 'no-html-constructors': 2,
```

The commit message was "Commenting out no-html-constructors for now, since the AST parsing doesn't work with exports".

If this lint rule is no longer useful after migrating to ES6 modules, it should be deleted, along withno-html-constructors.js .  If it's useful, it should be restored.

**Comment by jonathanolson** [comment]
I took a quick look, but I'm not familiar enough with the process (I haven't worked on linting rules). @jessegreenberg it looks like you wrote the original, how much work do you think this would take to convert the "require" statement search for an import search?

**Comment by jessegreenberg** [comment]
Should be straight forward, we will need to have another function like `addDeclaredType`for new syntax of import statements and replace  `VariableDeclarator` with `ImportDeclarator` for nodes to visit.

**Comment by jessegreenberg** [comment]
After migrate I can do this.

**Comment by jessegreenberg** [comment]
This lint rule has been added back and modified to catch `ImportDeclarator` as one of the ways to declare a type. Tested with `--eslint-disable-cache`. Closing.
