### ISSUE TITLE
IE Won't run debug versions of the sim

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/chipper#893]
For https://github.com/phetsims/QA/issues/482.
The sim will not start to load and may even crash the whole IE session if you use the debug version of the sim.
![Debugfail](https://user-images.githubusercontent.com/41024075/75290335-60b3b380-57dd-11ea-9e2d-1fc6e7fb77fb.png)

**Comment by jonathanolson** [comment]
Thanks for finding!

The debug versions are not transpiled. I would expect that our current production sims' debug versions will not load in IE, can you confirm?

This seems expected to me, if it's not a regression then it should be fine to close.

**Comment by KatieWoe** [comment]
That seems to be the case.

**Comment by lmulhall-phet** [comment]
Same thing happens in Safari. The debug version of BAM doesn't open in macOS 10.10.5 + Safari 10.1.2. You get stuck at the loading page with no progress in the loading bar. This is the error in the console:

![issue](https://user-images.githubusercontent.com/31285590/75299037-44ba0d00-57f1-11ea-8fd2-71c97b9c7f89.png)
