### ISSUE TITLE
upgrade require-statement-match lint rule for modules

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#894]
Ideally we should be checking this with module imports.

@samreid, as the original author, do you know how long it would take to parse the imports and check this? It's also related to https://github.com/phetsims/chipper/issues/891

**Comment by zepumph** [comment]
This lint rule should largely embody the findings of the `import` lines decided on in #873.

**Comment by zepumph** [comment]
Over in https://github.com/phetsims/chipper/issues/923, we decided to delete this lint rule. Closing
