### ISSUE TITLE
Investigate code coverage for es6+ module code

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#895]
Istanbul would need to have ES5-style code (e.g. babel-ified) code run through it. We currently run babel AFTER webpack, so our old style doesn't work well here. Since this seems low priority, I'm bailing after initial investigation.

**Comment by zepumph** [comment]
Note that we still have code in our project related to code coverage that uses `istanbul`, and the latest version of it reports a security vulnerability. @samreid recommended to delete it, I will leave that up to @jonathanolson in this issue. 

Should we just delete generateCoverage.js and remove the dependency in chipper's package.json?

**Comment by jonathanolson** [comment]
Sounds like a plan, implemented.
