### ISSUE TITLE
chipper/build should be cleared after build

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#900]
After running `grunt` on migrated code, chipper/build still has "acid-base-solutions.js".  It seems this should be cleaned up at the end of the build.  @jonathanolson does that sound good to you?

**Comment by jonathanolson** [comment]
Removing the temporary files in the above commit. Is that sufficient?

**Comment by samreid** [comment]
Looks great, thanks!  As a code review step, I would also recommend factoring out the path in the `output`

```js
      // We output our builds to chipper/build/
      output: {
        path: path.resolve( __dirname, '../../build' ),
        filename: `${repo}.js`
      },
```

and the path in the delete:
```js
const jsFile = path.resolve( __dirname, `../../build/${repo}.js` );
```

so they are less likely to deviate.

**Comment by jonathanolson** [comment]
Implemented in the above commit, anything else?

**Comment by samreid** [comment]
Looks great, thanks!  Closing.
