### ISSUE TITLE
Update documentation throughout the code that references RequireJS

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/chipper#905]
Documentation about RequireJS no longer applies since we have switched to ES6 modules. For instance from phet-software-design-patterns.md
> Since requireJS does not do well with circular dependencies, two types can refer to each other through the namespace.

And this comment in GrabDragInteraction
> // wrap in a function because phet.joist.sim doesn't exist at RequireJS time

We should do an inspection to either update comments to reflect "compilation free mode" or remove entirely if they no longer apply.

@jonathanolson @samreid how should we do this, is this a potential chip away issue to be divvied up like https://github.com/phetsims/tasks/issues/1017?

**Comment by jessegreenberg** [comment]
kite, mobius, scenery namespaces have comments like
> The main 'kite' namespace object for the exported (non-Require.js) API. Used internally since it prevents Require.js issues with circular dependencies.

**Comment by samreid** [comment]
I'm also seeing that chipper/package.json still refers to requirejs.

**Comment by jonathanolson** [comment]
Sounds like we'll want to do a project-wide search and try to replace things with improved terminology.

**Comment by samreid** [comment]
That sounds like something a primary developer could take the lead on, and request help if they come across parts where it is unclear how to proceed.  @ariel-phet would you like to recommend someone to take the lead on this?  It could be any developer.

**Comment by ariel-phet** [comment]
@jessegreenberg is willing to take this on, and will call on other devs as needed

**Comment by zepumph** [comment]
I also think that there is a bigger discussion to be had here about the vestigial, but widely used naming of `REQUIREJS_NAMESPACE` formatting. You can search for usages of `requirejsNamespace` including that field in every package.json.

**Comment by jessegreenberg** [comment]
Right, and it is still used throughout chipper @jonathanolson do you have a recommendation for a rename of this field?

**Comment by jonathanolson** [comment]
> do you have a recommendation for a rename of this field?

It accurately describes its legacy purpose, but I'm also not against other people wanting to rename it. Not attached either way.

**Comment by jessegreenberg** [comment]
I realized I am not knowledgeable enough about requireJS and how various things have changed with ES6 modules to do this. I have assembled a list of about 2 dozen questions that are of the form "should the documentation change or does the implementation need to change", and I am still not done going through everything. So I would recommend that a responsible developer for each repository go through first and review references. Here is the main list of places I am seeing them.

- chipper (@jonathanolson, @samreid)
- aqua (@jonathanolson)
- scenery-phet (@jessegreenberg)
- phet-info (@jessegreenberg)
- sherpa (specifically, usage of almond and text-2.0.12 which look specific to requirejs) (???)
- installer-builder (@jbphet)
- joist (documentation, and a usage still of window.requirejs) (???)
- tambo (@jbphet)
- phet-io (@samreid @chrisklus @zepumph)
- dot (todo files) (@jonathanolson)
- yotta (@jonathanolson)
- scenery (@jonathanolson)

Adding to developer meeting to check in, make sure responsible devs are correct, and assign to the few repos that are missing names.

**Comment by Denz1994** [comment]
From dev meeting 04/30/20:

We will have the responsible devs look at each of their repos from the above comment.

**Comment by jbphet** [comment]
I've taken care of tambo and installer-builder.  Unassigning.

**Comment by jonathanolson** [comment]
Should be complete, a lot of work done in https://github.com/phetsims/chipper/commit/0e01ac5d75f83ede34e05e4c1ba244c092bb5e21 removes require.js compatibility in a lot of our build files, and gets rid of a lot of vestigial stuff (e.g. global.phet.chipper). @ariel-phet  A brief review by another dev would probably be good.

**Comment by chrisklus** [comment]
from 06/18/20 dev meeting: @samreid volunteered to review. thanks!

**Comment by samreid** [comment]
In Slack, @jonathanolson said:

> Main review thing is basically that require/define were removed from our browser lint globals + I stripped out ways where files could be used from require.js or node.js (we only needed them in node.js now) + chipperGlobals went away

To review, I took the following steps:

* Examined the change set
* Looked for other occurrences of `typeof define !== 'undefined'` and found none
* Looked for other occurrences of `global.define` and found none
* Tested natural selection in unbuilt mode briefly
* Tested phet and phet-brand builds of natural selection briefly

No problems noted, nice work @jonathanolson, closing.
