### ISSUE TITLE
Grunt update is generating unformatted files

### ISSUE THREAD

**Issue by chrisklus** [phetsims/chipper#907]
@zepumph and I noticed that files generated during `grunt update` recently became formatted incorrectly (`{repo}-phet-io-elements-baseline.js`, `{repo}-phet-io-elements-type.js`, and `{repo}-en.html`). They are still checked in as formatted, we think because @samreid might have "Reformat code" in the commit dialog checked.

This is creating formatting diffs in the commit dialog, and since @zepumph and I don't normally have "Reformat code" turned on, we could unintentionally check them in as unformatted. I am happy to leave that option on for now in order to not change the format of what's checked in, but it's annoying to see false positives for diffs in the commit dialog after generating the files.

I think we should either 1. fix `grunt update` so it generates those files according to our formatting rules, or 2. check in those files as they are currently being generated so we don't see false diffs every time we `grunt update`. If anyone like to keep "Reformat code" turned on, then we should pursue option (1).

Weirder still, i checked out SHAs from before the migration and found that the baseline and types files were checked in as correctly formatted, but the `{repo}_en.html` files had one line with an extra space (there was a very small change if i formatted the file). So maybe it's not normal to have "Reformat code" checked after all.

Assigning to @samreid and @pixelzoom to weigh in.

**Comment by pixelzoom** [comment]
I noticed this today with `cd ph-scale-basics; grunt update`.   I went ahead and committed changes, even though it only looked like formatting.   

Recommended to turn off "Reformat code" when committing.  Since everyone is using different IDEs, it not a good idea.  If you make changes to address an issue, you do not want to have formatting changes tag along, that makes it more difficult to see what's relevant when reviewing a diff.   If you want formatting consistency, do the formatting as a separate step.  Or investigate an automate formatting task like we have for copyright dates.

**Comment by samreid** [comment]
The phet-io files should be generated matching our desired formatting.

**Comment by pixelzoom** [comment]
Agreed. But in general, don't you think that "Reformat Code" before commit should be turned off in WebStorm? 

I just ran into this again https://github.com/phetsims/ph-scale/commit/02dbf3f9b51e0c9b9ef1e101cb457317554a9f7f.

**Comment by chrisklus** [comment]
It looks like 2 space were removed from the opening curly brace of phet-io API files during the es6 modules migration, see phetioEngine.js:149. I added them back in and those files are being generated as formatted again.

I'm not sure how to proceed for the development html files. This patch gets it closer, but is not quite right. For now, I'm just going to run `grunt generate-phet-io-api-files` with an alias when working on phet-io issues so the development html file is not involved.

<details>

```diff

Index: templates/sim-development.html
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- templates/sim-development.html	(revision 328924a37ab3d5450f3e3ee4db047b27fe7d61e0)
+++ templates/sim-development.html	(date 1583088584000)
@@ -7,7 +7,7 @@
   <meta name="viewport" content="initial-scale=1,user-scalable=no,maximum-scale=1"/>
   <meta name="apple-mobile-web-app-capable" content="yes">
   <meta name="phet-sim-level" content="development">
-  {{STYLESHEETS}}
+{{STYLESHEETS}}
   <title>{{BROWSER_WINDOW_TITLE}}</title>
 </head>
 
Index: js/grunt/generateDevelopmentHTML.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/grunt/generateDevelopmentHTML.js	(revision 328924a37ab3d5450f3e3ee4db047b27fe7d61e0)
+++ js/grunt/generateDevelopmentHTML.js	(date 1583087077000)
@@ -77,8 +77,8 @@
   html = ChipperStringUtils.replaceAll( html, '{{MAIN_FILE}}', mainFile );
   html = ChipperStringUtils.replaceAll( html, '{{PHET_IO_PRELOADS}}', stringifyArray( phetioPreloads, '  ' ) );
   html = ChipperStringUtils.replaceAll( html, '{{PRELOADS}}', stringifyArray( preloads, '' ) );
-  html = ChipperStringUtils.replaceAll( html, '{{PACKAGE_OBJECT}}', JSON.stringify( packageObject ) );
-  html = ChipperStringUtils.replaceAll( html, '{{STRING_REPOS}}', JSON.stringify( stringRepos ) );
+  html = ChipperStringUtils.replaceAll( html, '{{PACKAGE_OBJECT}}', JSON.stringify( packageObject, null, 2 ) );
+  html = ChipperStringUtils.replaceAll( html, '{{STRING_REPOS}}', JSON.stringify( stringRepos, null, 2 ) );
 
   // Use the repository name for the browser window title, because getting the sim's title
   // requires running the string plugin in build mode, which is too heavy-weight for this task.

```

</details>

**Comment by samreid** [comment]
> But in general, don't you think that "Reformat Code" before commit should be turned off in WebStorm?

Formatting changes shouldn't "sneak in" with content-changes, especially in unrelated places in the same file.  Turning off "Reformat Code" in the commit dialog is one way to accomplish this.  When working on a repo for which I am the "responsible dev" it can sometimes be more efficient to turn on "Reformat code".

I selected "Reformat Code" during the one-time ES6 migration based on dev team consensus during the migration steps, forgetting that it would also hit the en.html files and unaware there were unformatted changes being produced there.

**Comment by pixelzoom** [comment]
> When working on a repo for which I am the "responsible dev" it can sometimes be more efficient to turn on "Reformat code".

I think it's good practice to treat future yourself like you would any other developer.

**Comment by samreid** [comment]
Much of this was addressed in https://github.com/phetsims/chipper/issues/908, @pixelzoom anything else for this issue?
