### ISSUE TITLE
format of generated files doesn't match PhET code-style format

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#908]
@jbphet pointed out that modulify outputs unformatted code, but in the migrate @samreid had selected "Format Code on Commit".  So now when running modulify it shows as a change.

We could do one of the following:

* re-run modulify on everything and commit that
* change modulify to output code that matches our formatting

To me, the latter seems more futureproof and less disturbing to all repos at the moment.  The former would only take moments of work to do, then commits and pushes across all repos.

@jbphet thought it would be nice to match the formatting.  I already fixed it for images.

**Comment by pixelzoom** [comment]
There is a similar problem with the top-level .html files in each repo.  `grunt update` format doesn't match PhET code style format.  They should be dealt with in the same way.  Changing the issue title to reflect this.

**Comment by samreid** [comment]
The above commits output formatting in a style that won't be disturbed by our code style formatting.  However, the mipmaps style doesn't exactly match what is committed.  Therefore, I recommend to `grunt update` but without changing phet-io files, and without reformatting the results afterwards.

**Comment by samreid** [comment]
In the above commits, I changed the output for mipmaps, images, sounds and html so it is compatible with our formatting.  Then I regenerated the mipmaps and HTML and committed.  @jbphet and/or @pixelzoom can you please verify?  Close if all is well.

**Comment by pixelzoom** [comment]
After pull-all.sh, I ran `grunt update` for a few sims and didn't see any updates. 

Leaving assigned to @jbphet to verify for `grunt modulify`.

**Comment by jbphet** [comment]
I just ran a test where I deleted and re-cloned the molecules-and-light repo, then ran `grunt modulify` for it.  I ended up with 33 modified files, which I think is all the images, sounds, mipmaps, and the strings.  When I diff the file using IntelliJ, it says "Contents are identical".  If I do a `git status` command in the molecules-and-light directory, I get the file list followed by the message `no changes added to commit (use "git add" and/or "git commit -a")`.  If I then pick one of the files and diff it, e.g. `git diff sounds/vibration_mp3.js`, I see this message:
```
warning: LF will be replaced by CRLF in sounds/vibration_mp3.js.
The file will have its original line endings in your working directory.
```

All of this leads me to believe that there is some sort of line ending issue for the files that are created, likely a Windows versus Unix sort of thing.  I think we've dealt with this before, but I don't know exactly how.  Back to you @samreid - seems like this is close, but has some platform-specific issues.

**Comment by jbphet** [comment]
I decided I'd take a quick look at the file in hex, and I can see that indeed, the line endings are being modified by `grunt modulify`.  Here is what the top portion of one of the files looks like before running the command, and I've circled an instance of 0x0d0a, which is ASCII CRLF:

![image](https://user-images.githubusercontent.com/3082831/75915082-1a7cd680-5e13-11ea-8f4a-484272278e30.png)

...and here it is after, and the line ending have been changed to just 0x0a, with is ASCII LF:

![image](https://user-images.githubusercontent.com/3082831/75914841-ae9a6e00-5e12-11ea-9c97-a7b46b5fc9fc.png)

**Comment by samreid** [comment]
To clarify what is desired: if running `grunt modulify` on Windows, it should generate CRLF `\r\n` and running on Mac it should generate LF `\n`.  Then we will rely on git for converting the line endings on pushes and pulls.  Does that sound right?  Checking in with @jbphet and @jonathanolson before further work.

Also, is this already done for the HTML files?  How have we not run into this before?

**Comment by jonathanolson** [comment]
> if running grunt modulify on Windows, it should generate CRLF \r\n and running on Mac it should generate LF \n. Then we will rely on git for converting the line endings on pushes and pulls. Does that sound right?

Sounds good!

> Also, is this already done for the HTML files? How have we not run into this before?

Mostly it's based on template files, instead of specifying things inline in JS multi-line strings. We may have also had newline-only specific code.

I assumed we weren't formatting HTML files (also).

**Comment by jbphet** [comment]
> Does that sound right?

It sounds right to me.  I'm not certain, though, and am happy to test as soon as we have something since I know that you @samreid are on Mac.

> [I]s this already done for the HTML files?

I don't know.  I just ran `grunt modulify` in the molecules-and-light project, and the HTML file was not change, whereas the image, sound, mipmap, and string files were.

> How have we not run into this before?

Good question.  I vaguely recall running into it a long time ago.  Maybe there is some sort of setting for IntelliJ or Git where it ignores these differences.  I'll look around and let you know if I find anything.

**Comment by jbphet** [comment]
I found some information about a Git configuration parameter names `core.autocrlf` which updates the line endings on checkouts and commits, but this value is already set correctly on my system and the functionality it controls seems to be working just fine.  The problem in this case is that the generated files have the Unix-style line endings, so I don't think Git or IntelliJ are the place to look for solutions.

**Comment by jbphet** [comment]
I found a few discussions of this problem online, and here is a link to one that suggests using a particular package and newline indicator: https://stackoverflow.com/questions/10384340/how-to-append-to-new-line-in-node-js.

The example looks like this:
```
var os = require("os");

function processInput ( text ) 
{     
  fs.open('H://log.txt', 'a', 666, function( e, id ) {
   fs.write( id, text + os.EOL, null, 'utf8', function(){
    fs.close(id, function(){
     console.log('file is updated');
    });
   });
  });
 }
```

This strikes me as promising.

**Comment by jbphet** [comment]
...and this approach already seems to be in use in `perennial\generateData.js`.

**Comment by jbphet** [comment]
I just tried doing a checkin where I did a `grunt modulify` and git/IntelliJ was reporting a bunch of changed files that weren't really changed.  I wanted to find out if it would actually check them in - I suspected that it would detect that it was just line endings and not actually commit them.  I was wrong - it checked the files in.  Hopefully this won't be a problem for the sim.  For reference, the commit was https://github.com/phetsims/molecules-and-light/commit/0211257f9487fa92d7818f976f02b36e77f4c2e0.

**Comment by samreid** [comment]
It looks like JS backtick template strings create `\n` line breaks, so we can replace those with os.EOL to achieve the desired behavior.  I implemented this in the commit and it seems to be working properly on Mac.  @jbphet can you please test on Windows?

**Comment by samreid** [comment]
I tested on Mac and it seemed to be working properly, thanks for your thorough test @jbphet and for reporting this problem.  Closing.
