### ISSUE TITLE
implement reportUnusedMedia

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#909]
implement reportUnusedMedia.  It's currently commented out in buildRunnable.js

**Comment by pixelzoom** [comment]
Does this also include used strings, or is that a separate issue?  I've noticed that since the conversion to ES6 modules, unused strings are no longer identified.  I recently almost left an unused string in ABS, after we changed the UI.

**Comment by chrisklus** [comment]
From 4/2/20 dev meeting:

SR: The build only includes sounds and images that were imported in the sim.

We think it would be good to not have unused media left in the repo, so this should still be done at some point.

**Comment by ariel-phet** [comment]
@Denz1994 is willing to tackle this issue - planning to address next week.

**Comment by jbphet** [comment]
@Denz1994 and @jonathanolson are going to work together on this.  @Denz1994 has made some progress but needs a bit of consultation on how to work with `chipperGlobals`.

**Comment by jonathanolson** [comment]
@ariel-phet @samreid Discovered as part of this work that we are NOT reporting third-party media license entries in our current builds in sims. For instance, our deployed molecule-shapes includes e.g. a license entry for "JOIST/keyboard-icon.png", crediting the original Font Awesome version it was derived from, and this is NOT included in our currently built versions off of master (and likely hasn't been included since our ES6 modules switch-over).

This should be done as part of this task (where we scan used media, get license entries, and provide them with a non-global to `getAllThirdPartyEntries`).

@ariel-phet presumably we'll want to maintenance release this into any simulations deployed since the ES6 module switch-over?

**Comment by ariel-phet** [comment]
@jonathanolson yes, it would be good to do that fix as a maintenance release (that set of sims should be quite small).

**Comment by jonathanolson** [comment]
No maintenance release needed! Closing.

**Comment by jessegreenberg** [comment]
When I build a sim I am getting reports of unused media for things that look like they are being used. For example, building molecules-and-light I see this report, but these are being used.
<details>

```
>> Unused sounds module: molecules-and-light/sounds/absorb-photon_mp3.js
>> Unused sounds module: molecules-and-light/sounds/break-apart_mp3.js
>> Unused sounds module: molecules-and-light/sounds/energized_mp3.js
>> Unused sounds module: molecules-and-light/sounds/photon-emit-ir_mp3.js
>> Unused sounds module: molecules-and-light/sounds/photon-emit-microwave_mp3.js
>> Unused sounds module: molecules-and-light/sounds/photon-emit-uv_mp3.js
>> Unused sounds module: molecules-and-light/sounds/photon-emit-visible_mp3.js
>> Unused sounds module: molecules-and-light/sounds/photon-release-ir_mp3.js
>> Unused sounds module: molecules-and-light/sounds/photon-release-microwave_mp3.js
>> Unused sounds module: molecules-and-light/sounds/photon-release-uv_mp3.js
>> Unused sounds module: molecules-and-light/sounds/photon-release-visible_mp3.js
>> Unused sounds module: molecules-and-light/sounds/rotation-clockwise-slow-motion_mp3.js
>> Unused sounds module: molecules-and-light/sounds/rotation-clockwise_mp3.js
>> Unused sounds module: molecules-and-light/sounds/rotation-counterclockwise-slow-motion_mp3.js
>> Unused sounds module: molecules-and-light/sounds/rotation-counterclockwise_mp3.js
>> Unused sounds module: molecules-and-light/sounds/vibration-slow-motion_mp3.js
>> Unused sounds module: molecules-and-light/sounds/vibration_mp3.js
>> Unused images module: molecules-and-light/images/flashlight-off_png.js
>> Unused images module: molecules-and-light/images/infrared-source-off_png.js
>> Unused images module: molecules-and-light/images/microwave-photon_png.js
>> Unused images module: molecules-and-light/images/photon-100_png.js
>> Unused images module: molecules-and-light/images/photon-660_png.js
>> Unused images module: molecules-and-light/images/thin2_png.js
>> Unused images module: molecules-and-light/images/uv-source-off_png.js
>> Unused mipmaps module: molecules-and-light/mipmaps/flashlight_png.js
>> Unused mipmaps module: molecules-and-light/mipmaps/infrared-source_png.js
>> Unused mipmaps module: molecules-and-light/mipmaps/microwave-source_png.js
>> Unused mipmaps module: molecules-and-light/mipmaps/uv-source_png.js
```
</details>

@Denz1994 or @jonathanolson can you take a look?

**Comment by samreid** [comment]
I'll take a look, thanks for the report!

**Comment by samreid** [comment]
Here's what I see when running `grunt` in `molecules-and-light/`

```
~/apache-document-root/main/molecules-and-light$ grunt
Running "lint-all" task

Running "report-media" task

Running "clean" task

Running "build" task
Building runnable repository (molecules-and-light, brands: phet, phet-io)
Building brand: phet
>> Webpack build complete: 2492ms
>> Production minification complete: 16428ms (2693550 bytes)
>> Debug minification complete: 1ms (6580950 bytes)
Building brand: phet-io
>> Webpack build complete: 1922ms
>> Production minification complete: 14436ms (2709620 bytes)
>> Debug minification complete: 15520ms (2950807 bytes)

Done.
```

**Comment by samreid** [comment]
I put 

```js
console.log(usedModules);
```
in chipper/js/grunt/reportUnusedMedia.js and saw elements like:

```
  'dot/js/Vector4.js',
  'dot/js/dot.js',
  'joist/images/keyboard-icon-on-white_png.js',
  'joist/images/keyboard-icon_png.js',
  'joist/js/A11yButtonsHBox.js',
  'joist/js/AboutDialog.js',
  'joist/js/CreditsNode.js',

```

I wonder if there is some platform-specific difference?  I'll reach out to @jessegreenberg on slack.

**Comment by samreid** [comment]
@jessegreenberg and I worked on this and tested on both our platforms, closing.
