### ISSUE TITLE
Convert preloads to modules.

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#912]
We have several files that need to be loaded from multiple locations, such as QueryStringMachine and SimVersion.  Other preloads like `initialize-globals.js` we would like to access information from them such as their query string machine schema for issues like https://github.com/phetsims/joist/issues/602, but it isn't available.

We could move all of these "phet" preloads to "module" preloads.  Then instead of UMD they can just be standard modules.  And we would be able to use `assert` in phet-io wrappers (if we add a build step that traverses modules).

@jonathanolson how does this sound to you?

@chrisklus and I sketched out some ideas here:

<details>

```diff

Index: acid-base-solutions_en.html
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- acid-base-solutions_en.html	(revision 4556e1d47af1b63437486d5522f67c7f37de2f43)
+++ acid-base-solutions_en.html	(date 1583957100567)
@@ -86,18 +86,23 @@
     '../sherpa/lib/FileSaver-b8054a2.js',
     '../sherpa/lib/himalaya-0.2.7.js',
     '../sherpa/lib/he-1.1.1.js',
+    '../sherpa/lib/seedrandom-2.4.2.js',
+    '../sherpa/lib/game-up-camera-1.0.0.js',
+    '../sherpa/lib/base64-js-1.2.0.js',
+    '../sherpa/lib/TextEncoderLite-3c9f6f0.js'
+  ];
+
+  let preloadModules = [
     '../assert/js/assert.js',
     '../query-string-machine/js/QueryStringMachine.js',
     '../chipper/js/initialize-globals.js',
     '../phet-core/js/copyWithSortedKeys.js',
-    '../sherpa/lib/seedrandom-2.4.2.js',
-    '../sherpa/lib/game-up-camera-1.0.0.js',
-    '../sherpa/lib/base64-js-1.2.0.js',
-    '../sherpa/lib/TextEncoderLite-3c9f6f0.js',
     '../tandem/js/PhetioIDUtils.js',
     '../chipper/js/SimVersion.js'
   ];
 
+  preloadModules.forEach( preloadModule => loadURL( preloadModule, 'module' ) );
+
   if ( brand === 'phet-io' ) {
     preloads = preloads.concat( [
       '../phet-io/js/phet-io-initialize-globals.js',

```

</details.

**Comment by jonathanolson** [comment]
I'd like to discuss this more, to understand a lot of the goals and usage. We use a lot of those files in a lot of places, so presumably we'd need to make sure our changes would work in all cases?

@samreid can we schedule to meet sometime about this?

**Comment by samreid** [comment]
@jonathanolson and I discussed this today.  We think it would be nice to continue moving the project toward ES6 modules.  This will allow us to get rid of globals (like window.QueryStringMachine), UMD patterns (like in QueryStringMachine), get rid of instantiation patterns like in SimVersion, and eliminate more files from the preloads section.  

We even discussed converting `assert` and `initialize-globals` and `_` to be loaded via modules.  It's not clear whether we would miss the ability to just access them as globals.

This can be done across phet-io wrappers like in https://github.com/phetsims/studio/issues/120 as well as Node code (see https://github.com/phetsims/chipper/issues/861 ).  

However, to upgrade, we would need to make sure we don't inadvertently add ES6 modules to a platform that cannot easily use it.  @mattpen reported that bayes and phet-server are using Node 10, which requires a command line flag in order to use import/export.  Mostly based on this, we are uncertain about the effort necessary to move more things toward modules and not certain the benefits will be worth the costs (especially in the short run).

**Comment by samreid** [comment]
Some more specific examples:

Converting QueryStringMachine to a module would allow us to delete this code from QueryStringMachine.js

```js
( function( root, factory ) {
  'use strict';

  if ( typeof define === 'function' && define.amd ) {

    // AMD. Register as an anonymous module.
    define( [], factory );
  }
  else if ( typeof module === 'object' && module.exports ) {

    // Node. Does not work with strict CommonJS, but
    // only CommonJS-like environments that support module.exports,
    // like Node.
    module.exports = factory();
  }
  else {

    // Browser globals (root is window)
    root.QueryStringMachine = factory();
  }
}( this, function() {
  'use strict';
```

Usages like this one in Natural Selection would change from:

```js
const NaturalSelectionQueryParameters = QueryStringMachine.getAll( {
```

to 

```js
import '../../query-string-machine/QueryStringMachine.js'`
// ...
const NaturalSelectionQueryParameters = QueryStringMachine.getAll( {
```

We could get rid of the specialized lint exception:

```js
    // Misc
    QueryStringMachine: false,
```

We would get rid of this assertion in initialize-globals (replacing it with an import statement)

```js
assert && assert( window.QueryStringMachine, 'QueryStringMachine is used, and should be loaded before this code runs' );
```

Remove QueryStringMachine.js as a preload from build.json (which will remove it from all the HTML files).
```js
"../query-string-machine/js/QueryStringMachine.js",
```

These seem like significant benefits.  Let's discuss at dev meeting to:
(a) see if there are other concerns or contraindications before moving forward
(b) try to estimate how much work this would be
(c) determine prioirity/timeline/delegation if we decide to go for it.

**Comment by mattpen** [comment]
> @mattpen reported that bayes and phet-server are using Node 10, which requires a command line flag in order to use import/export.

https://nodejs.org/en/about/releases/, it looks like we could switch to 12, but I think that import/export won't be available out of the box in an LTS until 14 is in "Active" state, which looks like it is expected in October.  We could upgrade to 13/`4 now, but I have qualms about using a non-LTS version in production.

**Comment by samreid** [comment]
How significant of a problem is it to have to add the `--experimental-modules` flag when running Node.js 12?

**Comment by jonathanolson** [comment]
> How significant of a problem is it to have to add the --experimental-modules flag when running Node.js 12?

Depends how experimental, if it causes other things to fail? Do we know its robustness?

That sounds like it would be less than ideal to need to add to all node/grunt commands in our automated processes.

**Comment by samreid** [comment]
Want to check back when Node 14 goes active in October?

**Comment by jonathanolson** [comment]
I'm not sure what my preference is. Writing imports in the node.js code I'm writing right now would be nice, but honestly the require statements aren't too different. Having everyone on a new node.js (14) then sounds nice.

**Comment by samreid** [comment]
In today's meeting, we agreed it would be nice to transform initialize-globals.js into an ES6 module, which would allow us to better modularize it. (Say, factoring out the query string machine schema for https://github.com/phetsims/chipper/issues/936 ).

**Comment by zepumph** [comment]
From dev meeting today, it seems like this can be done on a preload by preload basis.

* We will wait on SimVersion and other files used in Node too until Node 14 comes out
* assert and QSM are both used in the phet-io front end library, and may need consideration before turning into modules. That said, devs didn't mind seeing these transformed.
* Initialize globals seems like a good place to start by pulling out individual globals into their own modules. 

@samreid volunteered to investigate. Thanks!

**Comment by samreid** [comment]
Not as high priority as other things on my list, but putting on my list of things to do in the next few months.

**Comment by zepumph** [comment]
We have a calendar reminder for October 15th 2020 to reevaluate the Nodejs stuff.

**Comment by samreid** [comment]
Now that studio moved to ES6, we could also move `copyWithSortedKeys`.  That seems like a nice easy place to start.

**Comment by samreid** [comment]
I've made this change in my working copy, but will need to grunt update all repos, so I won't be committing right away.

**Comment by samreid** [comment]
CT didn't spot any problems with this commit, unmarking for blocks publication.

**Comment by samreid** [comment]
The `game-up-camera-1.0.0.js` is a preload that uses globals defined by `initialize-globals.js`. Hence making initialize-globals.js a module would require making game-up-camera-1.0.0.js a module as well.

**Comment by samreid** [comment]
@KatieWoe do we have a test harness or instructions for how to test the "Game Up Camera"?

**Comment by samreid** [comment]
In discussion, @KatieWoe indicated that QA does not test GameUp/SnapThought.  @kathy-phet are these still used and should we still be supporting them?  I wouldn't want to make changes to `game-up-camera-1.0.0.js` without the ability to test the changes.

If these are still supported features, we should identify how to test them and add it to part of the QA testing cycle.

**Comment by samreid** [comment]
We added steps for testing Game Up regularly.  Self-reassigning to continue with modularization.

**Comment by samreid** [comment]
This issue has >200 hidden items at its current length, let's create side or sub-issues for the remaining work.

**Comment by samreid** [comment]
All remaining work indicated in sub-issues.  Closing.
