### ISSUE TITLE
Code review A11y View

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#916]
While working on https://github.com/phetsims/chipper/issues/740 I found some refactoring and improvements to be done. I will link TODOs here, and try to organize things a bit better in this issue.

**Comment by zepumph** [comment]
I pulled functions out into its own script. There are a few todos added as well.

**Comment by zepumph** [comment]
- [ ] A11y view should use `QueryStringMachine.appendQueryString`

**Comment by zepumph** [comment]
- [ ] It would be nice if the a11y view javascript was linted. The javascript could be pulled out of the sim a11y template into its own js file. Then it could be linted in chipper. Then the grunt process could add it to the a11y view html template.

**Comment by jessegreenberg** [comment]
The remaining TODOs have been addressed.

> A11y view should use QueryStringMachine.appendQueryString

I don't see a precedent for this in other chipper templates so I am going to defer this. I don't see an easy way to bring in QueryStringMachine before sim libraries are loaded.

> It would be nice if the a11y view javascript was linted.

Ditto, but this is also desired for other templates and will done through https://github.com/phetsims/chipper/issues/1405.

For this TODO:
> TODO: Work on refining this, and only modifying the elements that change in the PDOM

This requires a new implementation of the a11y view and doesn't seem worthwhile at this time. It is inneffecient as noted in the documentation, but has not been an issue over the last 8 years.

Thanks for your work here @zepumph! Closing.
