### ISSUE TITLE
chipper should be lint-able

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#92]
This issue was moved out of https://github.com/phetsims/chipper/issues/62.

chipper contains JS code, and we currently have no build support for linting it. The JS code includes:

• chipper/requirejs-plugins/ -  A quick look at these files shows that they will fail lint. (Hence the 'bug' label for this issue.) Some files are missing 'use strict'.  And there may be other issues that we don't know about.

• chipper/grunt/ - implementation of grunt tasks, is not currently linted.

• And in phetsims/phetcommon#23, we decided to consolidate 'check' scripts into initialize-globals.js and relocate under chipper. 

The easiest (and most consistent) solution would be to put all JS code under chipper/js/, so that the existing `grunt lint` works. Another alternative would be to add something to package.json that enumerates the JS-source directories. My preference would be to put all JS source under js/.

Assigning to @samreid for comment, and since he's handling https://github.com/phetsims/chipper/issues/62.

**Comment by pixelzoom** [comment]
@samreid @jonathanolson @jbphet Does anyone mind if I move all chipper JavaScript files under chipper/js, so that it will be lint-able?

**Comment by samreid** [comment]
Are you planning to change the *-config.js files for each simulation?  They currently reference: paths like `../../chipper/requirejs-plugins/image`.  Also, have you checked that we have the capability to make all of our chipper JS files lint-free?  There may be external constraints that could make it difficult.

**Comment by samreid** [comment]
I agree we should try to move things under chipper/js, keeping the directory structure as much as possible.  For instance we will have:

chipper/js/requirejs-plugins/
chipper/js/grunt/
etc. 

Like I mentioned above, this will affect all config files, and it is worth briefly checking (by copy/paste to the js directory) that our other js files will have a chance of passing hint.  @pixelzoom feel free to proceed if you wish or let me know if you'd like me to do so.

**Comment by jonathanolson** [comment]
Curiously due to https://github.com/phetsims/build-a-molecule/issues/71, BAM is now linting chipper files under js/. Does it make sense for all sims to have chipper in their dependencies like that?

**Comment by pixelzoom** [comment]
@samreid asked:
> have you checked that we have the capability to make all of our chipper JS files lint-free?

No, I haven't.  But if it's not possible to make some chipper code conform to PhET's jshint standards, I think it would be preferable to specifically disabled warnings (e.g. `/* jshint -W034 */`) rather than skip linting of foundation code. 

@jonathanolson asked:
>  Does it make sense for all sims to have chipper in their dependencies like that?

chipper should be lint-able independently of sims or other repos.

**Comment by pixelzoom** [comment]
@samreid asked:
> Are you planning to change the *-config.js files for each simulation?

Yes. Move chipper/requirejs-plugins to chipper/js/requirejs-plugins, and change all sim *-config.js to reflect the new location.

Also proposing to move chipper/grunt to chipper/js/grunt. Then fix paths in chipper/js/grunt/Gruntfile.js, and in all sim top-level Gruntfile.js.

**Comment by pixelzoom** [comment]
See #95, #96 and #97 for current lint errors in chipper.

**Comment by pixelzoom** [comment]
Additional JS code discovered in chipper/ast/, and it looks like 3rd-party code that should be in sherpa. On Skype, @jonathanolson said:

[2/11/15, 6:15:33 PM] Jonathan Olson: easier to wipe it out
[2/11/15, 6:15:46 PM] Jonathan Olson: If I need to refer to it in the future, I can check back in revision history (it was an alternative way to stripping out logging/assertions)

**Comment by pixelzoom** [comment]
Reorganization completed.  Assign to @jonathanolson to review.

**Comment by jonathanolson** [comment]
Now looks good, closing. Thanks for taking care of it!

**Comment by jonathanolson** [comment]
Linting build-a-molecule (includes chipper in dependencies) or chipper is still the only way to catch failures (at least for the js/requirejs-plugins/), as linting other sims skips over lint failures for those files.

I'd presume we would want to catch these when running 'lint-all' in sims? Reopening.

**Comment by pixelzoom** [comment]
Many (most?) sims omit `chipper` from `phetLibs` in package.json, assuming that it is automatically added. But this is not the case.`chipper` is automatically added to phetLibs by some grunt tasks. Eg, for the `simAfterRequirejs` task in Grunfile.js:

```js
var dependencies = pkg.phetLibs.split( ' ' );
    if ( dependencies.indexOf( 'chipper' ) === -1 ) {
      dependencies.push( 'chipper' );
    }
```

It's not currently added for the lint-related tasks.  

Options:
(1) Require all sims to add chipper to package.json
(2) Automatically add chipper to pkg.phetLibs for all grunt tasks

I'm on the fence about which option I prefer. Sort of leaning towards (1), since I don't know why we'd treat `chipper` specially when we don't treat other "must have" repos specially (phet-core, phetcommon, scenery, dot, kite,...)

Opinions?

**Comment by jonathanolson** [comment]
I still prefer having chipper included in the dependencies, since we could use that dependency list in the future to automatically check out all repos needed (or other tasks of a similar nature). ("chipper IS a dependency").

**Comment by pixelzoom** [comment]
@jonathanolson wrote:
> I still prefer having chipper included in the dependencies

Unclear (to me anyway) what you're saying. It is included in dependencies, albeit automatically and only in some cases, and is automatically added to dependencies.json. Are you saying you prefer to have it explicitly included in `phetLibs`?

Proposal: Remove special treatment of chipper from Gruntfile, require it to be specified in package.json `phetLibs`.

**Comment by jonathanolson** [comment]
I prefer it explicitly in phetLibs.

**Comment by pixelzoom** [comment]
This is done. chipper was added to phetLibs in all package.json, and special handling of chipper was removed from chipper/js/grunt/Gruntfle.js.
