### ISSUE TITLE
requirejs still a dev dependency in some package.json files

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#920]
I think that universally these shouldn't be needed, but I thought I would check with everyone before deleting. 

```
chipper
installer-builder
phet-io
phet-io-wrappers
studio
```

Found in the above repos' `package.json` file.

**Comment by chrisklus** [comment]
From 4/2/20 dev meeting:

Related to https://github.com/phetsims/chipper/issues/905.
We're happy with this being deleted. Thanks!

**Comment by pixelzoom** [comment]
3 repos (chipper, phet-io-wrappers, studio) have this in package.json. I have no idea whether this is vestigial, is still a dependency, or is a dependency that needs to be removed.

`"requirejs": "~2.3.3"`

All repos have something like this in package.json. If the namespace is still needed, it should probably be renamed to something other than "requirejsNamespace".

`"requirejsNamespace": "ACID_BASE_SOLUTIONS",`

**Comment by ariel-phet** [comment]
@jonathanolson said he can handle this issue (consult with @chrisklus if you have iO related questions).

**Comment by ariel-phet** [comment]
Marking as high priority as we would like to clean up ES-6 issues in a timely manner

**Comment by jonathanolson** [comment]
Verified it was OK to remove, and removed in the above commits.

> All repos have something like this in package.json. If the namespace is still needed, it should probably be renamed to something other than "requirejsNamespace"

That's the best name we have for it, since it's specifically to work with how we USED to handle string keys. Should that be tagged for dev meeting discussion? I recall others feeling that it wasn't the best name also.

**Comment by pixelzoom** [comment]
Verified that `"requirejs": "~2.3.3"` entries were removed.  

It doesn't look like `"requirejsNamespace"` was addressed, see https://github.com/phetsims/chipper/issues/920#issuecomment-626820009. Back to @jonathanolson.

**Comment by jonathanolson** [comment]
> It doesn't look like "requirejsNamespace" was addressed

Correct, I mentioned:

> That's the best name we have for it, since it's specifically to work with how we USED to handle string keys. Should that be tagged for dev meeting discussion? I recall others feeling that it wasn't the best name also.

Proactively tagging this for developer meeting, so we can discuss.

**Comment by pixelzoom** [comment]
Sorry, I somehow missed that.  I'm OK with leaving it as "requirejsNamespace".
