### ISSUE TITLE
Speed up linting pre-commit hook

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#921]
At the moment, `grunt lint` takes around 2.5 seconds, which feels sluggish during commits.  Can this be improved?

**Comment by samreid** [comment]
I added this script in perennial/js/scripts/lint-main.js:

```js
const lint = require( '../../../chipper/js/grunt/lint' );
const path = require( 'path' );
const repo = process.cwd().split( path.sep ).pop()
lint( [ repo ], true, false, true );
```

And it is getting closer to 0.4 seconds.

**Comment by samreid** [comment]
I added the optimized lint script.  @pixelzoom can you please review and see if it is a suitable replacement for the pre-commit hook?

**Comment by zepumph** [comment]
On windows the fast script takes between 1 and 1.1 seconds (depending on if the terminal is fresh or not).

**Comment by samreid** [comment]
Also for the reviewer @pixelzoom: should this script be in chipper or perennial?

**Comment by samreid** [comment]
I think it makes more sense for this to move to chipper, since that is where lint is defined.  Will we have problems on old shas?  I don't think so, because we won't be committing on those old shas.

I'll move it shortly.

**Comment by zepumph** [comment]
I think that we could have problems. Or, at least, I don't know if the following case is problematic.

* Each git repo get's set up to use a git hook that calls a function in chipper
* you checkout a branch of chipper without that script
* you make a commit
* that file can't be found because the git repo is still trying to run the git hook?

If you are as worried about this as I am, perennial is likely the place.

**Comment by samreid** [comment]
But moving just this script to perennial doesn't solve the whole problem, because it still `require`s `lint` from `chipper`.  What if `lint` doesn't appear in the chipper SHA?  Or are you advocating a deep copy of `lint` moving to `perennial`?

**Comment by zepumph** [comment]
`lint.js` has been a file since early 2017. Perhaps that is long enough that the error you described is rare enough that we can ignore it? I wonder how many sims use an older chipper than that?

**Comment by samreid** [comment]
If I'm trying to commit something and my precommit hook is preventing me, perhaps I will just uncheck the Run Git Hooks checkbox:

![image](https://user-images.githubusercontent.com/679486/77705781-2aa55300-6f86-11ea-8153-170750bc1aee.png)

**Comment by samreid** [comment]
By the way, I'm using the `grunt lint` precommit hook and it's slow enough that "Commit and Push" shows a blank "Push" dialog (at least once).  I haven't tested if the faster precommit hook solves this or not.

**Comment by samreid** [comment]
Also, I tried 

```
perennial/bin/for-each.sh perennial/data/active-repos git init --template=/Users/samreid/apache-document-root/main/phet-info/git-template-dir
```
With the proposed precommit hook, and it looks like it did not overwrite the previous version.

**Comment by zepumph** [comment]
I think that is a totally fine option, but I have another idea.

What about the following for a git hook:

```sh
FILE=../chipper/js/scripts/lint-main.js
if [ -f "$FILE" ]; then
    node $FILE
else 
    grunt lint
fi
```

I don't know if this is actual bash, but something close to this. Then we wouldn't have to worry about any of it, and we get the speed boost when possible.

**Comment by samreid** [comment]
I'm inclined to avoid complexity in this precommit hook until I have more experience with it.  And my expectation is that it will be rare to want to commit in a sim repo while having a chipper prior to March 26, 2020 checked out.  But I will happily change my tune the first time it happens!

**Comment by zepumph** [comment]
Sounds good to me!

**Comment by samreid** [comment]
> By the way, I'm using the `grunt lint` precommit hook and it's slow enough that "Commit and Push" shows a blank "Push" dialog (at least once).  I haven't tested if the faster precommit hook solves this or not.

The new script is fast enough that it did not have this problem (in the one and only test).  Hooray!

**Comment by pixelzoom** [comment]
There's been a lot of discussion (and work?) on this since it was assigned to me for review. Is it still ready for review?

**Comment by samreid** [comment]
Yes, please.

**Comment by pixelzoom** [comment]
> should this script be in chipper or perennial?

Since the existing grunt task (lint.js) is in chipper, I'd say chipper.  Looks like you've done that. 

In case anyone else looks at this, instructions for running the script are in lint-main.js.  I tested a few lint errors (missing import, bad-text,...) and it seems to be working as expected. 

I don't see a plan for how this would replace `grunt lint`.  Are you thinking that this is only run in the pre-commit hook?  I don't think we should have 2 different implementations.

**Comment by pixelzoom** [comment]
Ah, I see, lint-main.js uses lint.js.  In lint-main.js:

`const lint = require( '../grunt/lint' );`

So this script is intended for use in git hooks only, but not in other places that currently use lint.js? Could other places benefit this optimization?   (I see no details here about why/how this runs faster, and I don't have time to investigate.)

**Comment by samreid** [comment]
> I see no details here about why/how this runs faster, and I don't have time to investigate.

As described in the documentation, this implementation "avoids the overhead of grunt and Gruntfile.js."  Even running `time grunt --help` takes around 1.5 seconds for me, compared to 0.05 seconds for `time node 2+2`.  Also, commenting out all of the other tasks in Gruntfile.js speeds things up immensely, but lint-main never requires them in the first place, so it avoids that overhead.

> So this script is intended for use in git hooks only, but not in other places that currently use lint.js?

I don't have plans to use this elsewhere at the moment.  It seems unlikely to speed up builds, because they have to run `grunt` and `Gruntfile.js` anyways.  A pattern like this could maybe shave a few seconds off of CT `grunt lint-everything` but that is maybe less important to optimize.  For now, using it in pre-commit seems appropriate.

**Comment by samreid** [comment]
@zepumph reported about 3.5 seconds for `grunt lint` and around 1.0 seconds for `node lint-main` using Windows.

**Comment by pixelzoom** [comment]
Which repo was @zepumph linting?  

For one of my largest sims:

```
% cd equality-explorer
time grunt lint
Running "lint" task

Done.

real	0m3.287s
user	0m1.514s
sys	0m0.567s
% time node ../chipper/js/scripts/lint-main.js

real	0m0.331s
user	0m0.319s
sys	0m0.056s
```

**Comment by samreid** [comment]
@pixelzoom is `lint-main` a suitable replacement for the `git-template-dir/hooks`?  If not, what else remains to be done for this issue?

**Comment by pixelzoom** [comment]
Yes, seem like a nice replacement in hooks.  And thanks for answering my questions.  Feel free to close.

**Comment by zepumph** [comment]
>Which repo was @zepumph linting?

Projectile Motion

**Comment by samreid** [comment]
I replaced the template with lint-main.  Closing, but @pixelzoom or @zepumph feel free to reopen if there's more here.
