### ISSUE TITLE
Review es6 module changes to the string stack

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#922]
From https://github.com/phetsims/chipper/issues/872, files that this touches are specifically:

- [x] getStringMap.js
- [x]  getStringModule.js
- [x] load-runtime-strings.js

**Comment by zepumph** [comment]
Review:

- [ ] I think it would be cleaner if the code that wrote the repo specific strings file in `modulify.js` was pulled out into its own function. Right now it is in the main `module.exports `file and looks really ugly.
- [ ] I don't like that the name of the strings file doesn't nicely match the name of the imported variable. For example `import joistStrings from './joist-strings.js';`. This is annoying to look at, but also ruins my auto import for the IDE, is there a way that we can camel case the generated file instead? (It is after the fact, but that would have been really nice for https://github.com/phetsims/chipper/issues/795)

**`getStringModule`**
- [ ]   RE: the comments immediately in the function: if these comments should be here for general knowledge, then likely they should be in the header, or in the jsdoc eh?
- [ ] `export default` should be the last line of the file, and it should have a named function after it. At least that is what I thought was decided in https://github.com/phetsims/chipper/issues/873#issuecomment-594079287
- [ ] Three nested `forEach` loops is far from the easiest code to read. Perhaps factoring out function or creating more vertical space may help read this. It is a very dense block. I think my main complaint about it is that in order to understand any one piece of it, you have to start at the first loop and mentally work out what is happening at each level. Splitting things up into more modular functions (if possible) may provide better space to block out responsibility and take the logic in more bite sized pieces.
- [ ] I'm of the opinion in complicated code, that the more specific the variable names are the better. With that in mind I recommend the following name changes. All totally optional, just what I'm feeling at this time:
  - [ ] rename `stringKeys` to something like `repoSpecificStringKeys`
  - [ ] rename `stringKey` to something like `stringKeyWithPrefix`
  - [ ] rename `key` to anything else
  - [ ] rename `object` to something that makes it more clear that it is possible (at the end) for this to be a string.

- [ ] Is the capitalized repo name with underscores still called the requirejs namespace?
- [ ] please document this line `          partialKey += `${i > 0 ? '.' : ''}${keyPart}`;`
- [ ] It is not clear to me why the inner assertions need `locale !== FALLBACK_LOCALE` in them.
- [ ] the definition of stringValue and its single usage could be inlined or at least closer.
- [ ] This line does not make sense to me, perhaps explaining where to look in the babel side of life, and why we would still want to include the check here:

  `// We'll need this check anyway for babel string handling`


I finished getStringModule here, with a few other thoughts. I will add to this  issue more later.

**Comment by zepumph** [comment]
Review for `load-runtime-strings.js`:

- [ ] The header doc gives good overview about context and why this file is important. Please add doc about what the file actually does. If I were doing it, I am getting the feeling it would be something like "defines and populates `phet.chipper.strings` for use in sim code.
- [ ] Each function needs jsdoc: requestStringFile, and processStringFile and likely more (including parameter type expressions).
- [ ] This file's header seems like a great place to document the need for ` window.phet.chipper.stringRepos` to be defined, and perhaps what it expects it to look like. 
- [ ] I think some assertions should do well in this file. Though I understand if you don't want to have assert be a dependency in this file. Even so don't you think we should fail out with a helpful error if ` window.phet.chipper.stringRepos` isn't defined or in the right format?
- [ ] This is a superset of the above comment, but I feel like everything is working well right now, but I wonder if we couldn't do better to try to make it a bit less fragile. There are a lot of globals being passed around, and not a lot of documentation about where or how they are being handled.

**Comment by zepumph** [comment]
Review of `getStringMap`:
- [ ] This comment feels outdated and wrong:
  > * Requires global.phet.chipper.strings to be set by the string.js plugin.
- [ ] does `// built-in node APIs` need to be separate from `modules`? If so `grunt should be moved up there.
- [ ] At first glance. I think that all regex should be factored out into constants, and extensive doc be added to each of the about what they match and why they are the way they are. This will do wonders to make things more maintainable. 
- [ ] recommend to rename `reposUsed` to something like `reposThatUsedStrings`
- [ ] RE `requirejsNamespaceMap`, I'm still surprised we are calling it "requirejs namespace" 
- [ ] I think the loop that populates `stringFilesContents` could lend itself nicely as a modular function
- [ ] In general this file is holds big, dense, and complicated loops that take a lot of effort, carefully reading each line to understand what is going on. I think it could benefit from more comments, and perhaps breaking modular pieces out to their own functions. Similar to  comments about `getStringModule`

I would say in general this file is very complicated because the algorithm is very complicated in that it deals with a lot of picky string manipulations. You wrote things well, I think I just am most worried about maintainability. Right now it feels like a black box. I would have a hard time making minor alterations to any of these three files (though especially getStringMap). Sometimes that's just how it goes though. Good work!

**Comment by jonathanolson** [comment]
> is there a way that we can camel case the generated file instead?

This would propose that `js/joist-strings.js` would be changed to `js/joistStrings.js` (or e.g. `js/acidBaseSolutions.js`, camel-cased). That sounds acceptable to me, I'll ask on Slack for any objections.

**Comment by jonathanolson** [comment]
> [getStringModule] RE: the comments immediately in the function: if these comments should be here for general knowledge, then likely they should be in the header, or in the jsdoc eh?

Those seem like implementation notes, not something that describes its interface or would be in the header. Thoughts?

**Comment by jonathanolson** [comment]
> export default should be the last line of the file, and it should have a named function after it. At least that is what I thought was decided in #873 (comment)

Ahh, I interpreted this as it should be the last statement, and that we didn't need to break things out with other names. Does this imply that we need to fix all of our namespace files too:
```js
export default new Namespace( 'joist' );
```
to:
```js
const joist = new Namespace( 'joist' );
export default joist;
```

I'm personally happy with the current way, but I also thought that we generally didn't create `const x; return x;` in favor of `return x`, and figured it would apply here also. Thoughts?

**Comment by jonathanolson** [comment]
> Three nested forEach loops is far from the easiest code to read. Perhaps factoring out function or creating more vertical space may help read this. It is a very dense block. I think my main complaint about it is that in order to understand any one piece of it, you have to start at the first loop and mentally work out what is happening at each level. Splitting things up into more modular functions (if possible) may provide better space to block out responsibility and take the logic in more bite sized pieces.

I'm open to that, especially for naming, but for me having the for-each loops obfuscated by splitting something into functions actually makes things less clear. Maybe more documentation would help? Can you directly propose a recommendation for how it SHOULD be so I could compare?

**Comment by jonathanolson** [comment]
> [getStringModule] rename `object` to something that makes it more clear that it is possible (at the end) for this to be a string.

Would `reference` be good? In almost all normal operation it is an object, however there are edge cases where it MAY point to something else.

**Comment by zepumph** [comment]
>Those seem like implementation notes, not something that describes its interface or would be in the header. Thoughts?

Sounds good! 

>Ahh, I interpreted this as it should be the last statement, and that we didn't need to break things out with other names. Does this imply that we need to fix all of our namespace files too:

I think that if it is already one line, then there isn't a problem. I would still recommend fixing the usage here though.

>I'm open to that, especially for naming, but for me having the for-each loops obfuscated by splitting something into functions actually makes things less clear. Maybe more documentation would help? Can you directly propose a recommendation for how it SHOULD be so I could compare?

How about try more documentation and we can see if that fixes things. I think of splitting tasks that are only run once into a separate function for documentation as something to be done by developer discretion, so feel free to pass on it. 

>Would reference be good? In almost all normal operation it is an object, however there are edge cases where it MAY point to something else.

sounds good!

**Comment by jonathanolson** [comment]
> [getStringModule]
> rename stringKeys to something like repoSpecificStringKeys
> rename stringKey to something like stringKeyWithPrefix

A string key by definition includes the prefix, and is specific to a single repository, so I'm not sure I understand the clarifications here?

Planning on using `stringKeysInRepo` for the array (since it is a list of string keys that are used and in the repo), but I don't see an immediate way to clarify the `stringKey` name.

**Comment by jonathanolson** [comment]
> Is the capitalized repo name with underscores still called the requirejs namespace?

That's the current terminology, yes, and stored in package.json files as `phet.requirejsNamespace`.

**Comment by jonathanolson** [comment]
> [getStringModule] It is not clear to me why the inner assertions need locale !== FALLBACK_LOCALE in them.

We may have other older (unused) keys in babel, and we are only doing the search that matters with the English string keys. Is there an ideal place to document this?

**Comment by jonathanolson** [comment]
>> I'm open to that, especially for naming, but for me having the for-each loops obfuscated by splitting something into functions actually makes things less clear. Maybe more documentation would help? Can you directly propose a recommendation for how it SHOULD be so I could compare?
>
> How about try more documentation and we can see if that fixes things. I think of splitting tasks that are only run once into a separate function for documentation as something to be done by developer discretion, so feel free to pass on it.

Added the documentation in https://github.com/phetsims/chipper/commit/aae473959bb180c68997d87fdcc79b4bcc82a0a9, how does that look?

**Comment by jonathanolson** [comment]
> This line does not make sense to me, perhaps explaining where to look in the babel side of life, and why we would still want to include the check here:
> 
> // We'll need this check anyway for babel string handling

It wasn't a good doc. https://github.com/phetsims/chipper/commit/f254de2ffbfbe00b063c0348ac9e1fd1f57aa03c should fix it, does that look good?

**Comment by jonathanolson** [comment]
> This is a superset of the above comment, but I feel like everything is working well right now, but I wonder if we couldn't do better to try to make it a bit less fragile. There are a lot of globals being passed around, and not a lot of documentation about where or how they are being handled.

That sounds great to me. How would you suggest we do that? It feels like documentation could help.

**Comment by jonathanolson** [comment]
> [load-runtime-strings.js] Also documenting the dependency/support on/for the ?locale query parameter.

I'm a bit confused, what would you recommend documenting? This is documented in initialize-globals.js I believe.

**Comment by jonathanolson** [comment]
> [load-runtime-strings] I also think that we could say that this file is only for unbuilt sims in the header, when describing how it requests files from babel if a custom locale is specified.

I'm not sure how the babel and custom-locale code is related to this? Added a comment to the top, and the rename will help also.

**Comment by jonathanolson** [comment]
> I'm not sure I totally agree with this, but it could be argued that it is cleaner to create a local var, like stringObject, which is built on throughout the file, and then have phet.chipper.strings be only defined at the end. That way the global is only ever complete and accurate, and is never in a half baked state.

That sounds like more moving parts and lines of code. I'm not fully convinced that would be beneficial. Thoughts?

**Comment by jonathanolson** [comment]
> RE requirejsNamespaceMap, I'm still surprised we are calling it "requirejs namespace"

More than happy to talk about changing this. We still use require.js for older simulations, so it still seems relevant for me. "legacy require.js namespace"?

**Comment by jonathanolson** [comment]
> In general this file is holds big, dense, and complicated loops that take a lot of effort, carefully reading each line to understand what is going on. I think it could benefit from more comments, and perhaps breaking modular pieces out to their own functions. Similar to comments about getStringModule

Done in master. A lot of times, if breaking things up into a function with a single use can mess with readability for me, particularly if without the function it's all in logical order in inter-related code. For things that seem somewhat isolated and independent, it's great to break things out. If you find anything specifically to improve let me know, but I didn't see many opportunities here.

**Comment by samreid** [comment]
Several sims are not finishing CT.  For instance, axon unit tests have this error:

> axon-tests.html?ea:110 GET http://localhost/main/chipper/js/load-runtime-strings.js?bust=1585752472995 net::ERR_ABORTED 404 (Not Found)

Leaving assigned to @jonathanolson at increased priority.

**Comment by jonathanolson** [comment]
> At first glance. I think that all regex should be factored out into constants, and extensive doc be added to each of the about what they match and why they are the way they are. This will do wonders to make things more maintainable.

I updated the documentation, but:

1. Some can't be factored out into constants, since they use variables, and
2. Others shouldn't be, since it's better to keep them by their usage site for readability

Thoughts?

**Comment by jonathanolson** [comment]
> Several sims are not finishing CT. For instance, axon unit tests have this error

Should be fixed in master, my apologies!

@zepumph can you review my comments and let me know what else I should do?

**Comment by zepumph** [comment]
I went through all the comments you made, and thumbs upped them when I noted or responded to them. The following is all I think is left with this issue, so long as every unchecked checkbox I created was accompanied with a comment by you (which I think it was). Great work on this stuff. 

>Ahh, I interpreted this as it should be the last statement, and that we didn't need to break things out with other names. Does this imply that we need to fix all of our namespace files too:

I thought it was just important and most clear when it was the last line of the file.  What you have now seem really nice, and I don't recommend changing Namespace usages.


>A string key by definition includes the prefix, and is specific to a single repository.

That is not an obvious statement to me at all. When I think of string key, I think of what I would find and write in the json file, which is why I think it is beneficial to clarify. Up to you if you want to or not. 


>https://github.com/phetsims/chipper/issues/922#issuecomment-606309638

I would recommend factoring out that boolean from the three assertions that I see it in, and then documenting there. What do you think?

>https://github.com/phetsims/chipper/issues/922#issuecomment-606318246

Could some of these, like phet.chipper.stringRepos, turn into es6 modules over in https://github.com/phetsims/chipper/issues/912?  I know that there are performance needs that have us starting string imports as early as possible. Do modules seem potentially clearer to you?

>https://github.com/phetsims/chipper/issues/922#issuecomment-606318473

This line:  `const customLocale = new window.URLSearchParams( window.location.search ).get(  i'locale' );` 
is hidden deep in this file, and doesn't use the normal phet approach for accessing queryParameters. I recommend that at the top of this file, mentioning that it uses `?locale` and to refer to initialize-globals for details.

- [ ] I also just noticed that load-unbuilt-strings, `'en'` could be factored out into a constant like `FALLBACK_LOCALE`


Things are looking very good.

**Comment by jonathanolson** [comment]
>> A string key by definition includes the prefix, and is specific to a single repository.
>
> That is not an obvious statement to me at all. When I think of string key, I think of what I would find and write in the json file, which is why I think it is beneficial to clarify. Up to you if you want to or not.

Where would be good to document this? Currently, a string key is something like `'JOIST/resetAllButton.name'`, and is baked into how we handle things in rosetta, how we support strings overridden in query parameters, etc.

**Comment by jonathanolson** [comment]
> Could some of these, like phet.chipper.stringRepos, turn into es6 modules over in #912? I know that there are performance needs that have us starting string imports as early as possible. Do modules seem potentially clearer to you?

I don't see how that would be technically feasible, unless we (a) turn string files into JS modules and (b) create "empty" modules for where translations don't exist, and (c) use dynamic module imports. Strong preference to avoid all of that.

**Comment by jonathanolson** [comment]
@zepumph I believe I've responded to everything in https://github.com/phetsims/chipper/issues/922#issuecomment-625529653

**Comment by zepumph** [comment]
I added some doc for what a "string key" is where I felt like it was needed. Thoughts? Ready to close?

**Comment by jonathanolson** [comment]
Looks great, thanks!
