### ISSUE TITLE
Delete or replace string-require-statement-match rule for ES6 modules

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/chipper#923]
This rule wasn't replaced after switch to ES6 modules. Many developers are just using the strings module inline now. But for strings used in multiple places or strings with long/nested names it improves readability to use constants, like

```js
const simSoundOnString = sceneryPhetStrings.a11y.soundToggle.alert.simSoundOn;
const simSoundOffString = sceneryPhetStrings.a11y.soundToggle.alert.simSoundOff;
```

For these, do we want to enforce variable names match? If so, what should the rule be, should it match last key in the nesting or should it contain everything to the right of the module name or something else?

I don't think the matching variable name is as important anymore since we don't have a consistent `// strings` block anyway. I think we should delete `string-require-statement-match` but curious about other opinions.

**Comment by samreid** [comment]
We also discussed inlining the strings, since we no longer need those intermediate variables.

**Comment by chrisklus** [comment]
From 4/2/20 dev meeting:

We are all good with deleting it, assigning to @jessegreenberg. Thanks!

**Comment by jessegreenberg** [comment]
I deleted this rule, closing.
