### ISSUE TITLE
Rewrite reportUnusedStrings to work with ES6 modules

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/chipper#924]
reportUnusedMedia and reportUnusedStrings were made for RequireJS and are no longer working. It was helpful to see reports of unused strings and media when building. @jonathanolson would it be possible to have these again with ES6 modules?

**Comment by jonathanolson** [comment]
Yes, reportUnusedMedia should be handled in https://github.com/phetsims/chipper/issues/909.

Renaming this issue for reportUnusedStrings.

**Comment by jonathanolson** [comment]
Should be implemented with the above commit. @jessegreenberg do you mind reviewing/verifying?

**Comment by zepumph** [comment]
This is very exciting! Thanks for doing that.

**Comment by jessegreenberg** [comment]
Tested, this is working really well, thanks!
