### ISSUE TITLE
Eliminate ?cacheBust?

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#925]
After moving we moved to ES6 modules, we no longer have the ability to `?cacheBust` the main JS code, as we did for requireJS.  We opened #866 for alternative ideas about cache busting the ES6 module code, but most developers now just run Chrome with devtools open and disable cache.  We recently added the ability to cache bust preloads as part of #755.  We should decide whether we want to keep this cache busting facility for preloads now that we know that facility won't work for the main ES6 modules.  We may decide to remove cache busting altogether. In that case, search all occurrences of "cachebust" (case insensitive) across JS+HTML files to see where this is in use.  Let's touch base on this at a developer meeting before we proceed.

**Comment by zepumph** [comment]
related to https://github.com/phetsims/chipper/issues/866

**Comment by chrisklus** [comment]
From 4/2/20 dev meeting:

We think unless we try to get cache busting working for ES6 modules in addition to preloads, then we should just get rid of this and rely on dev tools or local servers for no caching. @samreid volunteered to do this.

**Comment by samreid** [comment]
Some questions came up as I was working on this:

* Is phet-core/js/loadScript.js used?  I couldn't find any occurrences.  @jonathanolson is listed as the author, can you recommend how to proceed?  Let me know if I should open a separate issue.
* There is an alternate declaration and usage of `cacheBust` in interaction-dashboard. @zepumph may wish to determine a better way of doing this.  Let me know if I should open a separate issue.

**Comment by samreid** [comment]
Fixed in the preceding commits.  Most changes are in chipper and phetmarks.  Then I updated the html and test-html files for each repo.  Some questions came up as I was working on this:

* Is phet-core/js/loadScript.js used?  I couldn't find any occurrences.  @jonathanolson is listed as the author, can you recommend how to proceed?  Let me know if I should open a separate issue.
* There is an alternate declaration and usage of `cacheBust` in interaction-dashboard. @zepumph may wish to determine a better way of doing this.  Let me know if I should open a separate issue.

Also, does one of you mind reviewing this change?

**Comment by zepumph** [comment]
after investigation, this query parameter should stick around. It has to do with logic when processing giant data stream files, and it is nice to support caching them when iterating on the preprocessor. I can rename it if that would be less confusing. Do you think that is necessary?

**Comment by samreid** [comment]
Interaction Dashboard's ?cacheBust can stick around and does not need to be renamed.

**Comment by zepumph** [comment]
Excellent. Anything else for me here?

**Comment by samreid** [comment]
I think the last step for this issue is for @jonathanolson to review https://github.com/phetsims/chipper/issues/925#issuecomment-609525271

**Comment by jonathanolson** [comment]
> Is phet-core/js/loadScript.js used? I couldn't find any occurrences. @jonathanolson is listed as the author, can you recommend how to proceed? Let me know if I should open a separate issue.

It seems generally useful, but I don't see a use right now. A slight preference for leaving it. If that's ok with you, let's close here?

**Comment by samreid** [comment]
I don't mind leaving it, and my IDE shows a message that loadScript is unused.

![image](https://user-images.githubusercontent.com/679486/79347797-55355c80-7ef1-11ea-81ff-e590ab6710b8.png)

So I think it's clear that it's not used at the moment.  Closing.
