### ISSUE TITLE
Publishing dev versions changes development html

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#926]
Since converting to es6-modules, we have been putting our package.json inline in the development html files. This has been working well, but one downside is that publishing dev versions bumps the package version, but it doesn't update that version in the development html. Thus there is a lingering update needed in that repo that will occur next time `grunt update` is called.

To reproduce:
* cd chains
* grunt dev --brands=phet
* `grunt update` and see that the dev html has a working copy change.

@jonathanolson what about running either updating the dev html and commting as part of dev publications, or manually updating just the version number in the dev html when publishing a dev version?

**Comment by jonathanolson** [comment]
Hmm, what are thoughts on stripping the version from this? I don't want to have `grunt update` logic in perennial, since that will create potential maintenance for that type of thing for years.

**Comment by zepumph** [comment]
Stripping version sounds really good!

**Comment by jonathanolson** [comment]
Changing my opinion here, it appears that the version in that package object is used by `updateCheck`. Since we're doing dev versions off of master, this seems safe enough to bump version, commit the dev/test HTML, THEN handle the deployment. This behavior will be tied to master anyway, and won't be done for RC/production, since we won't care about dev html on branches (or be updating those anyway).

**Comment by jonathanolson** [comment]
Ok, we're including the commits for the dev/test HTML after the version-change commits (and including in the same push) for both release creation and dev deploys.

@zepumph I've tested the configurations here with bumper/twixt (twixt had tests). The commit to review would be https://github.com/phetsims/perennial/commit/dabe202d0d6c6f00e29aa8324f3421f4062d4600 if you'd like.

Does this sound good? (If you'd like to review, go for it?)

**Comment by zepumph** [comment]
Looking really good. Thanks! Closing
