### ISSUE TITLE
Review sortImport.js 

### ISSUE THREAD

**Issue by Denz1994** [phetsims/chipper#930]
Related to https://github.com/phetsims/chipper/issues/872 for reviewing `sortImports.js`

- [x] Similar to the grunt task `sort-require-statements`, should there be grunt task for `sort-imports`. Currently, it is a subtask of `grunt migrate`. I'm bringing this up to be consistent with implementing specific grunt tasks for sorting require-statements and imports.

- [ ] `disallowedComments` aren't caught in a few cases. See ShapeHitDetector.js, ObservationWindow.js, SwitchNode.js, and Concentration.js. Some cases may be due to commented out lines of code within the imports block.

- [x] Consider naming `lastImportIndex + 1` to `lineAfterLastImport` or 'lineFollowingLastImport`

- [x] Consider naming `lines[ i + 1 ]` to `nextLine`

- [x] At top-level documentation, it may be worth noting that the sorting is applied to the string after the `from` and not the module name that is being imported. For example, the top-level doc should clarify why `BatteryShapeCreator.js` organizes `BatteryGraphicNode` at the end of the import statements.

I will assign this issue to @jonathanolson to respond to the above points.

**Comment by jonathanolson** [comment]
> disallowedComments aren't caught in a few cases. See ShapeHitDetector.js, ObservationWindow.js, SwitchNode.js, and Concentration.js. Some cases may be due to commented out lines of code within the imports block.

For cases where there are commented-out bits, they should be moved to a different section. Is there anything else this tool should be doing?

Otherwise should be ready to review my changes. I'm going to look into running this codebase-wide but making sure that it doesn't mess up formatting.

**Comment by Denz1994** [comment]
Thanks for your changes @jonathanolson this is looking a lot better. Regarding the commented out comments, are you saying that sort-imports should handle moving these commented outlines below the import block? An alternative approach may resemble, consoling an error/warning message reading "Failed to sort bad import statement".

**Comment by jonathanolson** [comment]
There were many cases of things being in sections of imports as comments, I'm not sure we'd want to fail out on that. Thoughts on alternatives? It doesn't happen too often, but we could also search the codebase for commented-out imports.

**Comment by Denz1994** [comment]
IMO handling all comments within an import block is out of the scope of the grunt task. If an import is commented my question would be, "Why is this import commented" before performing an operation on it. 

As it stands we are only checking for commented "modules, strings, images, mipmaps", which is fine because including those comments were part of our code style. All other comments in the import block would exist for another reason and that should be handled on a case-by-case basis.

**Comment by jonathanolson** [comment]
Understood! But is there a recommendation to change the code we have here?

**Comment by Denz1994** [comment]
No, I think all is good here. I'll close this issue.
