### ISSUE TITLE
lint rule for visibility annotations

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/chipper#932]
I made a lint rule to catch missing visibility annotations for method declarations. Would people find this useful generally or annoying? We could probably also have a lint rule to catch missing visibility annotations on instance variables.

**Comment by jessegreenberg** [comment]
Checked in but not enabled. When run with lint-everything, it is catching 752 methods that do not have visibility annotations.

**Comment by samreid** [comment]
Looks great, we should enable this and address existing deficiencies.

**Comment by zepumph** [comment]
I think we should turn it on! Thanks for implementing it.

**Comment by zepumph** [comment]
To turn it on, go to `chipper/eslint/rules/.eslintrc.js` and uncomment the `visibility-annotation` rule. 

Devs will take on their own sims, and we may make a chip-away list.

**Comment by samreid** [comment]
Currently at 812 errors for that lint rule (from lint-everything).

**Comment by pixelzoom** [comment]
Self assigning to run this lint rule on the sims that I'm responsible for.

**Comment by pixelzoom** [comment]
My sims are done. Fixes n 43 files took ~20 minutes.  Unassigning.

**Comment by pixelzoom** [comment]
I fixed many of the lint issues in common code.  I skipped classes/methods related to a11y because I'm not familiar with those.

**Comment by jessegreenberg** [comment]
I did sims I am responsible for and a few others (scenery, tappi, scenery-phet, faradays-law, john-travoltage) where functions were related to a11y. We are down to 369! Here is the current list
- [ ] aqua
- [ ] build-an-atom
- [ ] charges-and-fields
- [ ] circuit-construction-kit-black-box-study
- [ ] circuit-construction-kit-common
- [ ] collision-lab
- [ ] color-vision
- [ ] coulombs-law
- [ ] density-buoyancy-common
- [ ] energy-forms-and-changes
- [ ] fluid-pressure-and-flow
- [ ] friction
- [ ] greenhouse-effect
- [ ] interaction-dashboard
- [ ] inverse-square-law-common
- [ ] masses-and-springs
- [ ] number-line-common
- [ ] number-line-integers
- [ ] number-line-operations
- [ ] number-play
- [ ] ohms-law
- [ ] optics-lab
- [ ] perennial
- [ ] phet-io-test-sim
- [ ] phet-io-wrappers\common
- [ ] projectile-motion
- [ ] ratio-and-proportion
- [ ] resistance-in-a-wire
- [ ] shred
- [ ] states-of-matter
- [ ] studio
- [ ] tambo
- [ ] wave-interference

**Comment by pixelzoom** [comment]
5/14/2020 dev meeting:

Please chip away at the repos that you're responsible for.

**Comment by zepumph** [comment]
I did my sims as well as a few others.

**Comment by chrisklus** [comment]
I did my sims and Studio in the commits above.

**Comment by samreid** [comment]
I addressed several repos and updated the assignees accordingly.  I also noted the responsible devs in the list comment: https://github.com/phetsims/chipper/issues/932#issuecomment-628247740

**Comment by pixelzoom** [comment]
It's been 27 days since we decided to move apply this lint rule.  Since the rule hasn't been enabled yet, I've accidentally reintroduced the problem.  And having to enable the rule manually is a drag. 

I propose that we enable the visibility-annotation lint rule, and let the repos fail that need attention.  @jonathanolson @jbphet @Denz1994 when do you think you can get to this?

**Comment by Denz1994** [comment]
I just finished my sims from above. Unassigning.

**Comment by jonathanolson** [comment]
@brandonLi8, are you able to handle this for Collision Lab? There are some things where I'd need to track down what the types are to document.

**Comment by brandonLi8** [comment]
@jonathanolson I am able to handle this. Thanks.

**Comment by pixelzoom** [comment]
6/4/2020 dev meeting:

We agreed to enabled the `visibility-annotation` rule on Thursday, 6/11/2020.

**Comment by jbphet** [comment]
I've addressed this in the sim and common repos for which I believe I'm responsible.  I'm not sure why, but I'm the only one who was assigned to this issue.  I'm going to pass it off to @jessegreenberg because there seem to be a number of a11y-related instances of this problem in inverse-square-law-common and tappi.  Other than that, there are just a handful that we can probably tackle in the meeting when we turn on the lint rule.

@jessegreenberg - you're welcome to assign to whoever owns the most instance of these errors once you're done.

**Comment by pixelzoom** [comment]
@jbphet you the only person assigned because you were the last to have items to check off in the checklist found in https://github.com/phetsims/chipper/issues/932#issuecomment-628247740.  Should all of those now be checked off?

**Comment by jbphet** [comment]
@pixelzoom - Thanks for pointing that out - I've checked off the items that I addressed.  There are still 24 errors occurring for `grunt lint-everything`.

**Comment by pixelzoom** [comment]
I took care of a few of the remaining errors.   Here's what's left:

- [ ] inverse-square-law-common @jessegreenberg 
- [ ] ratio-and-proportion @zepumph 
- [ ] scenery a11y @jessegreenberg 
- [ ] studio @zepumph @chrisklus 
- [ ] tappi @jessegreenberg

**Comment by pixelzoom** [comment]
I addressed the new errors noted in https://github.com/phetsims/chipper/issues/932#issuecomment-640890347, then enabled the visibility-annotations rule, so that we don't introduce more errors.

I posted this PSA to the Slack developer channel:

> 24 new cases of missing visibility annotations have snuck in.  So I addressed all of them, and then enabled the `visibility-annotation` lint rule.  Please pull chipper so that you have this new rule, otherwise you run the risk of introducing a new lint error that will fail in CT.  More details at https://github.com/phetsims/chipper/issues/932.

**Comment by pixelzoom** [comment]
Consensus on Slack was to close this issue.
