### ISSUE TITLE
Update os specific newlines in generated files

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#933]
Over in https://github.com/phetsims/chipper/issues/908 I saw that @samreid used `os.EOL` instead of `\n`. This fixed a windows/mac problem where newly generated files appeared to have changes but it is only from "line separators".

It seems like it worked well there, and it is being used in `generateData`. I think we should apply this to other generated files:
- [x] phet-io api files
- [x] development html
- [x] a11y view?

I'll take a look

**Comment by zepumph** [comment]
After the above commits, when I run `grunt update` I no longer get every generated file showing that it is modified only with line separators. @samreid would you like to use this function `fixEOL` in modulify.js also? I didn't think about that until just now, but have never run that file, and don't know a good repo to test it in.

**Comment by samreid** [comment]
js/grunt/fixEOL.js looks great, and seems like a good candidate to replace the function in modulify.js.  Any repo with mipmaps, images and strings, such as balancing-act would be fine for testing.  Feel free to proceed and I can test on Mac, or leave assigned to me and I can get to it when the time is right.

**Comment by zepumph** [comment]
I don't think this issue applies anymore. If all that is left is updating modulify, then I think we should close this issue. There is no reason to maintain that file in such a minute way at this time.
