### ISSUE TITLE
'grunt generate-phet-io-api-files' does not fail gracefully

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#935]
If `grunt generate-phet-io-api-files` fails for some reason, one or more of your iO API files may be empty, and you're responsible for restoring them.   While it's true that `grunt` clears the build directory before running this task, there's no reason why it shouldn't restore the API files if a problem occurs. 

I've experienced this numerous times, and @jonathanolson asked about it today on Slack.

**Comment by zepumph** [comment]
Agreed! We wrote it that way originally to make sure that a new file was created. We should check if one exists before overwriting its contents with a blank file. Thanks for the feedback.

**Comment by samreid** [comment]
Our process has changed, now `grunt generate-phet-io-api` creates new files and does not overwrite prior files.  I tested by adding `throw new Error();` to Bunny.js constructor and ran `grunt generate-phet-io-api`.  It didn't disturb any existing files, and didn't create any new broken files.  I think this issue can be closed.
