### ISSUE TITLE
Incorrect formatting for strings can break builds

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#938]
From https://github.com/phetsims/chipper/issues/922:

I wanted to add that over in https://github.com/phetsims/ratio-and-proportion/issues/3 I renamed a sim, and that caused me to commit an improperly formatted line that imported the title. As a result the sim wouldn't build. That felt really horrible, and if I hadn't been involved with the implementation of the new string system (i.e. knowing that it runs on regex for detection of used strings), it likely would have taken longer to debug.

Line of code that works properly:
`const ratioAndProportionTitleString = ratioAndProportionStrings[ 'ratio-and-proportion' ].title;`

Line of code that breaks the build:
`const ratioAndProportionTitleString = ratioAndProportionStrings['ratio-and-proportion'].title;`
With error: `AssertionError [ERR_ASSERTION]: missing entry for sim title, key = RATIO_AND_PROPORTION/ratio-and-proportion.title`

I know that we are getting stricter every day about formatting our code, but this feels like a bug. Especially in an open source environment where we don't know who may run this and encounter this bug. 

Over to @jonathanolson. Can we account for spacing in our regular expressions?

**Comment by jonathanolson** [comment]
It seems quite likely that the way we parse for strings could be broken in may other ways (e.g. dynamic indexing, string concatenation inline, double-quoted strings, back-quoted strings, separation into variables, newlines, etc.) Whitespace is also allowed in a ton of different ways, e.g.:
```js
window [    `navigator` ]
  .   userAgent
```

I'm not convinced of the benefit of allowing this one specific case, as it seems like a slippery slope AND something we shouldn't be enabling. If we really want to account for these types of things, presumably we should use an AST parser?

Or an alternative, like a lint rule that would check that formatting?
