### ISSUE TITLE
Add a script that iterates over all active-repos and runs grunt on each

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#94]
@jonathanolson provided an awesome "test all sims" feature in:
http://localhost:PORT/joist/tests/test-sims.html

I am wondering if we already have or can create something similar for running grunt on each of our active repos?  Maybe someone with bash kung-fu can tell me an easy way to do this?  @jonathanolson or @pixelzoom do we already have something like this?  Or is it easy to create one?

Once that is done, another step that would be good to take would be to add a query parameter to the Joist test-sims.html that uses the built versions for testing.

**Comment by samreid** [comment]
@jonathanolson said:

> all-build.sh --force should build everything.

**Comment by samreid** [comment]
@jonathanolson also said he is interested in making the multi-sim tester able to test built sims.

**Comment by jonathanolson** [comment]
all-build.sh current works. The sim tester (mentioned above) can also run with build-server.js to automatically build and test built versions of every sim.

Is anything else needed?

**Comment by samreid** [comment]
Works great, thanks!  Closing.
