### ISSUE TITLE
Puppeteer fails on CT phet-io builds

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#940]
In https://github.com/phetsims/phet-io/issues/1648 we moved the `generate-phet-io-api-files` step from `grunt update` to `grunt`.  However, this means it is now running on build servers, including CT, instead of just developer machines.  This error occurred in CT:

```
gas-properties : build
Build failed with status code 3:
Running "report-media" task
Running "clean" task
Running "build" task
Building runnable repository (gas-properties, brands: phet, phet-io)
Building brand: phet
>> Webpack build complete: 4357ms
>> Production minification complete: 33493ms (1673059 bytes)
>> Debug minification complete: 0ms (5888640 bytes)
Building brand: phet-io
>> Webpack build complete: 3722ms
>> Production minification complete: 29042ms (1689318 bytes)
>> Debug minification complete: 28594ms (1985298 bytes)
Fatal error: Failed to launch the browser process!
[0428/165556.198969:FATAL:zygote_host_impl_linux.cc(116)] No usable sandbox! Update your kernel or see
```

To temporarily mollify CT, I commented out the API file generation in https://github.com/phetsims/chipper/commit/9f49893cf8070d9c0ee04583006ab028ae52bf59

To me, it seems like generating the phet-io API file is an important step of the build and we should be able to run it on the build server, CT or any place where a build occurs.  However, I'm not sure what obstacles are in the way of that goal, or if we will have to resort to workarounds.

Marking as blocks-publication for phet-io since simulations will be built without API files until this is addressed.

@jonathanolson can you please advise?

**Comment by ariel-phet** [comment]
the iO team and @jonathanolson and perhaps @mattpen will try to find a time to discuss

**Comment by jonathanolson** [comment]
Also, we'll want to make sure that this works well concurrently, bayes can be building 8-10 sims at a time.

**Comment by samreid** [comment]
According to https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md#setting-up-chrome-linux-sandbox 

> If you absolutely trust the content you open in Chrome, you can launch Chrome with the --no-sandbox argument:

```js
const browser = await puppeteer.launch({args: ['--no-sandbox', '--disable-setuid-sandbox']});
```

Since we control the code that will run in puppeteer, this would probably work.  They recommend a process called namespace cloning for this.  I'm not familiar with that at all.

**Comment by zepumph** [comment]
Matching priority of parent issue https://github.com/phetsims/phet-io/issues/1664

**Comment by mattpen** [comment]
I had some success on ox-dev setting up user namespace cloning.  I also looked into the setuidbit on ox-dev, it would probably be possible to setup on bayes.

**Comment by samreid** [comment]
@mattpen are there any disadvantages to setting up namespace cloning?

**Comment by mattpen** [comment]
@samreid - As mentioned in the guide you posted, it does expose an attack vector on the server.  However I discussed this with @phetsims/mark-morlino and we decided that this was an acceptable risk and were considering using it in production (it didn't work out for other reasons that aren't relevant here).

I did have some trouble getting it to work in the proper context, but I think it is likely the best solution if it does work.

**Comment by samreid** [comment]
We will also need this to work on the production build server.  Is that risk OK?  Also, we do have control over the code that loads in puppeteer, so the `--no-sandbox` argument may also be acceptable.

**Comment by mattpen** [comment]
@samreid - I think the risk either way is acceptable in this case.

**Comment by samreid** [comment]
I recommend we go with the strategy recommended by the puppeteer team, @mattpen and @jonathanolson can you please investigate that for our build server and CT?  Is there any other place where we have linux running builds?

**Comment by mattpen** [comment]
So the recommended way to enable user namespaces in in Linux does not work on RHEL 7.

```
$ sudo sysctl -w kernel.unprivileged_userns_clone=1
sysctl: cannot stat /proc/sys/kernel/unprivileged_userns_clone: No such file or directory
```

This looks like a command for Debian, and involves components which aren't part of the RedHat kernel.

I was trying to find the conversation I had with @phetsims/mark-morlino about this, but it appears this probably happened on Slack (and is now lost due to message limits).

I found two methods which might work:
1. https://github.com/procszoo/procszoo/wiki/How-to-enable-%22user%22-namespace-in-RHEL7-and-CentOS7%3F (requires reboot)
2. https://superuser.com/a/1294246/493443
Neither one of these really seems like an authoritative answer.  I recall using a method like the first one but I can't remember for sure.

@phetsims/mark-morlino - could you comment on the best way to proceed to allow user namespace cloning on bayes?

**Comment by mattpen** [comment]
@samreid - https://frugalisminds.com/javascript/how-to-setup-puppeteer-in-centos-7/

This looks promising and I was able to run puppeteer in my home directory.  However, it causes a file in node_modules to be owned by root.  I'm assuming this could cause problems later with npm operations, or at the least would require a repeat of this step.

This is the step that causes it to work and also causes me concern.  Note the directory `linux-549031` will be named something unique to the version of linux currently used.

> For running Puppeteer in sandbox mode we need to do few changes as of now .
> 
> If you navigate to node_modules/puppeteer/.local-chromium/linux-549031, you notice that for puppeteer there is a file named chrome_sandbox (with an underscore).
> 
> Renaming this file to chrome-sandbox and perform following steps below
>  
> ```
> sudo mv chrome_sandbox chrome-sandbox
> sudo chown root chrome-sandbox
> sudo chmod 4755 chrome-sandbox
> ```

**Comment by markmorlino** [comment]
@mattpen I think for RH you can put a non-zero value into /proc/sys/usr/max_user_namespaces ie:
`echo 1000 > /proc/sys/user/max_user_namespaces` as root or as non-root something like:
`echo 1000 | sudo tee /proc/sys/user/max_user_namespaces`

but that setting won't persist after a reboot unless you also add a line like `user.max_user_namespaces=1000` to /etc/sysctl.conf or a file in /etc/sysctl.d/

I have no idea what the correct number should be, the examples I found all use pretty high numbers

https://support.tryshift.com/kb/article/207--sandbox-error-starting-shift-on-linux/
https://success.docker.com/article/user-namespace-runtime-error

**Comment by mattpen** [comment]
@samreid - I think puppeteer should be working on bayes now.  I set the max_user_namespaces to 1000, but as @markmorlino says above, this won't persist a reboot.  Please test this out and let me know if it is working for you.

**Comment by samreid** [comment]
On slack, @mattpen and I discussed that puppeteer will also need to run on phet-server for production builds and rcs.  Once we determine that it is working well on CT, @mattpen said he can apply the same strategy to phet-server.

**Comment by samreid** [comment]
I've re-enabled PhET-iO API file generation.  It tested nicely locally.  This commit should trigger CT to run this new build code, we'll see how it does there.

**Comment by samreid** [comment]
Note that over in https://github.com/phetsims/phet-io/issues/1664#issue-615053845 we said:

> when CT does builds, we don't need to do this, to save time/performance.

So we'll just consider this a trial run to make sure this strategy will work for our build server.

**Comment by samreid** [comment]
I enabled this and CT has been running OK for a while. I also checked that /data/share/phet/continuous-testing/ct-snapshots/1590609909531/natural-selection/build/phet-io/natural-selection-phet-io-api.json generated properly.  @mattpen can we apply this pattern to the build-server as well?

**Comment by zepumph** [comment]
The phet-io team finished up https://github.com/phetsims/phet-io/issues/1664, and closed it. We think that this issue is still considered blocking publication because any build from build-server would not yet generate the phet-io api file artifact.

**Comment by chrisklus** [comment]
from 06/18/20 dev meeting:

@mattpen will apply the pattern above to the build server.

**Comment by mattpen** [comment]
I added `user.max_user_namespaces=1000` to `/etc/sysctl.d` on bayes, so that change should persist on a reboot now.

However, when I tried to run `echo 1000 | sudo tee /proc/sys/user/max_user_namespaces` on phet-server, it failed with `tee: /proc/sys/user/max_user_namespaces: No such file or directory`.  In fact `/proc/sys` is missing the user directory, and I can't add it because `/proc/sys` doesn't have write privileges, even for root!

```console
$ ls -la /proc/sys
total 0
dr-xr-xr-x.   1 root root 0 Aug  8  2016 .
dr-xr-xr-x. 928 root root 0 Dec 14  2017 ..
dr-xr-xr-x.   1 root root 0 Jun 22 15:37 abi
dr-xr-xr-x.   1 root root 0 May  8 21:34 crypto
dr-xr-xr-x.   1 root root 0 Jun 22 15:37 debug
dr-xr-xr-x.   1 root root 0 Jun 22 15:37 dev
dr-xr-xr-x.   1 root root 0 Aug  8  2016 fs
dr-xr-xr-x.   1 root root 0 Jun 22 15:37 fscache
dr-xr-xr-x.   1 root root 0 Aug  8  2016 kernel
dr-xr-xr-x.   1 root root 0 Jun 21 20:24 net
dr-xr-xr-x.   1 root root 0 Jun 22 15:37 sunrpc
dr-xr-xr-x.   1 root root 0 Jun 22 07:31 vm
``` 

@markmorlino - any idea why this directory might be missing or how to add it?

**Comment by markmorlino** [comment]
The kernel is supposed to create it, I think it became the default for it to be there on rhel 7.3 or 7.4.

Am I correct in understanding that it existed on bayes but not on phet-server?

I should have some time to look at it this evening.

**Comment by markmorlino** [comment]
Hey @mattpen, sorry for the delay.

Bayes is running a more recent kernel than phet-server but, neither of them are actually running 7.8. I think phet-server needs a reboot to get a new enough kernel.

```
Mon Jun 29 19:05:11 mamo5311@phet-server:~
$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.8 (Maipo)

$ uname -a
Linux phet-server.int.colorado.edu 3.10.0-327.28.2.el7.x86_64 #1 SMP Mon Jun 27 14:48:28 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux

$ sudo grubby --info /boot/vmlinuz-3.10.0-327.28.2.el7.x86_64 
[sudo] password for mamo5311: 
index=2
kernel=/boot/vmlinuz-3.10.0-327.28.2.el7.x86_64
args="ro rd.lvm.lv=os/root rd.lvm.lv=os/swap rhgb quiet rd.shell=0 LANG=en_US.UTF-8"
root=/dev/mapper/os-root
initrd=/boot/initramfs-3.10.0-327.28.2.el7.x86_64.img
title=Red Hat Enterprise Linux Server (3.10.0-327.28.2.el7.x86_64) 7.2 (Maipo)
```

```
Mon Jun 29 19:07:20 mamo5311@bayes:~
$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.8 (Maipo)

$ uname -a
Linux bayes.colorado.edu 3.10.0-693.17.1.el7.x86_64 #1 SMP Sun Jan 14 10:36:03 EST 2018 x86_64 x86_64 x86_64 GNU/Linux

$ sudo grubby --info /boot/vmlinuz-3.10.0-693.17.1.el7.x86_64 
index=2
kernel=/boot/vmlinuz-3.10.0-693.17.1.el7.x86_64
args="ro crashkernel=auto rd.lvm.lv=os/root rd.lvm.lv=os/swap rhgb quiet LANG=en_US.UTF-8"
root=/dev/mapper/os-root
initrd=/boot/initramfs-3.10.0-693.17.1.el7.x86_64.img
title=Red Hat Enterprise Linux Server (3.10.0-693.17.1.el7.x86_64) 7.4 (Maipo)
```

Both bayes and phet-server are setup to boot to the same new kernel version at next reboot. This command outputs the same thing on both.
```$ sudo grubby --info DEFAULT
index=0
kernel=/boot/vmlinuz-3.10.0-1127.13.1.el7.x86_64
args="ro crashkernel=auto rd.lvm.lv=os/root rd.lvm.lv=os/swap rhgb quiet LANG=en_US.UTF-8"
root=/dev/mapper/os-root
initrd=/boot/initramfs-3.10.0-1127.13.1.el7.x86_64.img
title=Red Hat Enterprise Linux Server (3.10.0-1127.13.1.el7.x86_64) 7.8 (Maipo)
```

**Comment by mattpen** [comment]
@markmorlino - Thanks for the details.  

I'm going to plan on rebooting phet-server next Monday, July 6 in the evening.

**Comment by mattpen** [comment]
The reboot was delayed.  I am planning to reboot tonight.

**Comment by mattpen** [comment]
@samreid - The reboot and kernel update was successful.  A cursory test of puppeteer was successful for me.  I think we can proceed with testing the puppeteer dependent process in production.

**Comment by samreid** [comment]
Tagging for developer meeting as a public service announcement to double check existence of API file after next PhET-iO production build.

**Comment by zepumph** [comment]
ph-scale is going to get RC today for phet-io. Assigning to @pixelzoom to double check that the api file was created by the build-server.

**Comment by pixelzoom** [comment]
ph-scale build failed, but it a new issue: https://github.com/phetsims/chipper/issues/961

Let's use phet-io-test-sim to debug that issue and this one.  Reassigning to @zepumph @samreid.

**Comment by zepumph** [comment]
I just created an RC in phet-io-test-sim, and it successfully created an api file:

https://phet-dev.colorado.edu/html/phet-io-test-sim/1.4.0-rc.1/phet-io/phet-io-test-sim-phet-io-api.json

Thanks @mattpen @pixelzoom @markmorlino @samreid for all the help on this issue.
Closing
