### ISSUE TITLE
remove buildWrapper and packageJSON.isWrapper 

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#942]
This is no longer used because the sonification wrapper is no longer in use. Let's go ahead and remove them. If we need wrappers built in the future, there will be better ways to accomplish this.

**Comment by zepumph** [comment]
I think that we could potentially delete phet-io-wrapper-haptics while we are at this. @jessegreenberg, is that wrapper being used for anything now? Does it need to stick around?

**Comment by jessegreenberg** [comment]
Yes, this repo/wrapper can be deleted now, and I started https://github.com/phetsims/phet-io-wrapper-haptics/issues/7 to do so.

**Comment by zepumph** [comment]
isWrapper deleted in https://github.com/phetsims/chipper/issues/822
