### ISSUE TITLE
bad-sim-text should support predicates

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#943]
In https://github.com/phetsims/studio/issues/127 I realized it would be nice to have a predicate tester for bad-text.  Like https://github.com/phetsims/chipper/issues/737, we should add a predicate part for bad-text.

**Comment by samreid** [comment]
I added this support, but didn't have 100% understanding of how usage and regex are supported.  So it would be good for @zepumph to take a look when there is time.

**Comment by zepumph** [comment]
I really like this! It the bad text engine much more powerful. I think this could replace a lot of future simple lint rules that we want to add, and the boilerplate that would need to accompany them. Thanks!

**Comment by samreid** [comment]
Thanks, closing.
