### ISSUE TITLE
Review es6 template files and simLauncher.js

### ISSUE THREAD

**Issue by Denz1994** [phetsims/chipper#944]
Related to #872, for reviewing sim-webpack.ejs, sim-development.html, and SimLauncher.js:

**sim-webpack.js**
- [x] Some top-level documentation indicating the file's use would be useful. I only see this file being used as a template for starting a webpack dev server (`webpackDevServer.js)

**simLauncher.js**
- [ ] The dynamic imports in initializeDynamicImports assumes the path is correct. Perhaps a catch block would be useful for logging an error message for an incorrect path.
- [x] `pendingLocks` type doc is missing. `{Array.<Lock>}`?
- [x] `launchBegan` and `launchComplete` are missing type docs. `{Boolean}`?
- [x] `launch()` and `proceedIfReady()` aren't using ES6 arrow functions
- [x] `proceedIfReady()` missing jsDocs
- [x] `createLock(object)` parameter isn't described in the jsDoc. `@param {Object} object`?

**sim-development.html**
Nothing to note for this file.

Assigning to @jonathanolson to respond to the above points.

**Comment by jonathanolson** [comment]
Looks like some other cleanup was done, but I believe I fixed up all but one thing.

> The dynamic imports in initializeDynamicImports assumes the path is correct. Perhaps a catch block would be useful for logging an error message for an incorrect path.

I wasn't involved with the dynamic import setup for this. The try-catch wouldn't work with the promises, but we could use `.catch()` or `.finally()`. @samreid thoughts?

**Comment by samreid** [comment]
If an incorrect path is provided, the browser will show an error like:

simLauncher.js:21 GET http://localhost/main/brxand/phet/js/Brand.js net::ERR_ABORTED 404 (Not Found)

![image](https://user-images.githubusercontent.com/679486/81963536-71044f00-95d2-11ea-9c11-50ecd3288346.png)

Is that sufficient?

**Comment by Denz1994** [comment]
Thanks for checking @samreid. I wasn't sure how exactly this would fail (hopefully not silently) but the error message shown looks clear. I'll close this issue because the items have been addressed.
