### ISSUE TITLE
Review modulify.js

### ISSUE THREAD

**Issue by Denz1994** [phetsims/chipper#945]
From https://github.com/phetsims/chipper/issues/872:

**modulify.js**

- [x] File export statement is not using ES6 arrow function
- [x] `modulifyFile` and `modulifyMipmap` are handled asynchronously. I would suggest `modulifyImage` to be handled asynchronously as well, for consistency with these other functions. I'll leave to your discretion.
- [x] Consider inlining `const x = loadFileAsDataURI( abspath );` with its usage in `base64:${x}`. Or at least consider renaming to `fileDataURI`.
- [x] `modulifyMipmap` uses an `options` object to pass in args for `createMipmap()'. The args aren't noted as optional. Consider renaming to `config`.
- [x] In `expandDots` consider renaming `x` to `parentDirectory` maybe? 

Docs:
- [x] `expandDots` is missing js doc
- [x] `convertSuffix' is missing `@return` doc
- [x] `getSuffix` is missing `@return` doc
- [x] Typo in export statment docs? Should read `* @param {string} repo - the name of a repo, such as 'joist'`
- [x] `grunt --help` reads `modulify` will generate js files for  `images/strings/audio/etc` while the top level documentation mentions "images or sounds". Should the files mentioned be consistent?

Miscellaneous:
- [x] TODO: Related to support for non-defaults exports. Has this been addressed?
- [x] TODO: Related to mipmap support. This file currently supports modifying mipmaps so can this be removed?

Assigning to @jonathanolson to respond to the above comments.

**Comment by jonathanolson** [comment]
I believe all of the above should be handled with the above commit, can you verify? (Good review items, thanks!)

**Comment by zepumph** [comment]
I think this is probably good to go. Closing, but please reopen @samreid or @jonathanolson if you think there is more here.
