### ISSUE TITLE
Update to QUnit 2.10

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#947]
We are using QUnit 2.4.1, the latest version is 2.10.  The changes are described here: https://github.com/qunitjs/qunit/releases

Should we upgrade?  If so, when/who? Tagging for developer meeting discussion.

**Comment by jessegreenberg** [comment]
Discussed 5/21/20

- We don't expect breaking changes from minor version updates.
- @zepumph (and others) said this seemed like a good thing to do, but not a massive benefit.
- @samreid found this while investigating a bug and thought that updating might resolve that issue. Maybe there are other stability and speed improvements.

@samreid thought if there were no breaking changes it could take 30 minutes to update. Would take longer if fixes are required across many repos.

@samreid volunteered to take a look at medium priority.

**Comment by samreid** [comment]
When I upgraded QUnit to 2.10.0, it worked nicely but the puppeteer harness failed half the time.  It seems like QUnit now runs eagerly and sometimes before the listeners registered.  I'll add a phase to withhold qunit launch until the listeners are registered.

**Comment by samreid** [comment]
While testing this, I also upgraded puppeteer to the latest version.  All of my testing has been done with that version, and it's working well so I'm inclined to keep it.

**Comment by samreid** [comment]
Upgrade complete and I notified #dev-public on slack and will monitor CT for a few cycles.  Closing.

**Comment by samreid** [comment]
@jessegreenberg and @zepumph reported problems with puppeteer when running older versions of Node.  When @jessegreenberg updated to a recent version of node the problem went away.  In @zepumph case, he was running node 10 and `npm install` was itself failing.  We decided for now to downgrade the puppeteer version and discuss as a team how we can update this.

**Comment by samreid** [comment]
From https://github.com/puppeteer/puppeteer

> Note: Prior to v1.18.1, Puppeteer required at least Node v6.4.0. Versions from v1.18.1 to v2.1.0 rely on Node 8.9.0+. Starting from v3.0.0 Puppeteer starts to rely on Node 10.18.1+. All examples below use async/await which is only supported in Node v7.6.0 or greater.

**Comment by samreid** [comment]
Tagging for developer meeting to decide how to proceed, see the last 2 comments for context.

**Comment by Denz1994** [comment]
From Dev Meeting on 07/16/20:

**Resolution:**
We will wait until Node 14 is released and revisit (ETA October). We will only have to upgrade the Node version on our servers once.

**Comment by samreid** [comment]
We agreed to unlabel this from developer meeting and add a calendar entry in the dev agenda.

**Comment by samreid** [comment]
We successfully upgraded to qunit 2.10 in May.  The remaining work for this issue is about puppeteer and will be completed in https://github.com/phetsims/chipper/issues/949, closing.
