### ISSUE TITLE
string.js uses eval and fails lint

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#95]
string.js fails with this jshint error:

```js
Linting requirejs-plugins/string.js ...ERROR
[L31:C122] W061: eval can be harmful.
  var parse = (typeof JSON !== 'undefined' && typeof JSON.parse === 'function') ? JSON.parse : function( text ) { return eval( '(' + text + ')' ); };
```

Is it wise to be using eval?...

Tested by changing line 147 of chipper/grunt/Gruntfile.js to:

> repoFiles: [ 'js/\*\*/\*.js', 'requirejs-plugins/\*\*/\*.js' ],

then running `grunt lint`.

**Comment by pixelzoom** [comment]
@jonathanolson said on Skype:
> if JSON doesn't exist in Node.js, we should import it instead of using eval

**Comment by jonathanolson** [comment]
Looks like a workaround for JSON.parse when it isn't available. We should instead import the equivalent instead of eval.

**Comment by pixelzoom** [comment]
Is there an echo in here? :)

**Comment by jonathanolson** [comment]
Wow, for some reason I didn't see that note. Definitely an echo.

**Comment by pixelzoom** [comment]
What is an equivalent that we can import?

**Comment by pixelzoom** [comment]
Or is it possible the JSON is in fact always defined, and the eval fallback is unnecessary?

**Comment by pixelzoom** [comment]
The very same code path that's using this 'var parse' fallback is also doing an explicit call to JSON.parse. So this appears to be unnecessary.  And it runs fine as JSON.parse in both requirejs and build modes.

**Comment by pixelzoom** [comment]
Removed in https://github.com/phetsims/chipper/commit/6da061128b2ad895a7bc7caa5ecbed80609b97b5. Closing.
