### ISSUE TITLE
no complaint about missing license.json

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#951]
I encountered this during code-review of a 3rd-party sim, see https://github.com/heldentodd/xray-diffraction/issues/1.   

The developer has a mipmaps/ directory with no license.json file.  There was no complaint when building the sim, see below.   So I suspect that there's something wrong with the code that is checking licensing -- possibly just for mipmaps, or possibly for all resource types.

Labeling with "block-publication" since this is a legal/licensing issue.
```
% grunt
Running "lint-all" task

Running "report-media" task

Running "clean" task

Running "build" task
Building runnable repository (xray-diffraction, brands: phet)
Building brand: phet
>> Webpack build complete: 1967ms
>> Unused string: key=LatticeConstant, value=Lattice Constant
>> Production minification complete: 14781ms (1520361 bytes)
>> Debug minification complete: 1ms (5206909 bytes)

Done.
```

**Comment by pixelzoom** [comment]
@ariel-phet FYI.

**Comment by samreid** [comment]
I committed a fix that tests mipmaps for licensing issues.  I deleted license.json from a test directory, and it correctly identified it as a problem.  I ran 

```
for-each.sh active-runnables grunt report-media
```

To see if the problem sneaked in anywhere while this was offline, and no problems were reported.

@pixelzoom can you please review?

**Comment by pixelzoom** [comment]
Looks good, thanks! Closing.

```
% cd xray-diffraction
% grunt
Running "lint-all" task

Running "report-media" task
>> not-annotated: xray-diffraction/mipmaps/protractor.png
Fatal error: There is an issue with the licenses for media types.
% 
```
