### ISSUE TITLE
API for customizing initial string values

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#965]
PhET needs an API for customizing the initial value of strings, overriding what's in the strings file.

There are 2 main needs for changing strings: 
(1) Customizing initial strings
(2) Dynamically changing strings while the sim is running.

These needs are very different, with very different costs to support.  (1) is not currently supported by PhET, and I'm willing to bet that it's the majority of needs.  (2) is supported by PhET, but is more expensive and excludes non-PhET-iO clients. 

So even in cases when the need is (1), PhET is using the more expensive approach (2).  That approach involves adding an O-specific StringProperty for each string that needs to be globally changed. (See for example the solutes in pH Scale, grouped under element `phScale.global.model.solutes`.)  It's often necessary to add more complicated layout code that can handle dynamic strings (for example to keep a string centered under something).  And because the StringProperties can only be modified via PhET-iO, it totally excludes brand=phet clients, like the request in https://github.com/phetsims/ph-scale/issues/182.

See the Slack discussion below for more thoughts and API ideas.

Labeling for discussion at phet-io meeting, to see if this issue gets any traction.

<details>
<summary>Slack conversation</summary>

Chris Malley  6:42 PM
Is there a way to override the value of one or more translated strings via a query parameter?

Sam Reid  6:54 PM
There used to be a way to change i18n strings with the old requirejs string plugin , but I’m not sure whether we kept that feature in the es6 plugin migration. I’m not too familiar with the new string support, but I don’t see support for query parameter replacements in js/getStringModule.js

Chris Malley  6:56 PM
The reason I'm asking is https://github.com/phetsims/ph-scale/issues/182.  Yet another request to be able to customize strings, in brand=phet.  Having to add specific query parameters for specific strings, or set StringProperties via PhET-iO, seem inferior to a general way of overriding translated strings.

Sam Reid  7:00 PM
If we added an API that allowed you to put ph-scale.html?strings=PH_SCALE/drinkMix:My%20Solution, then the string keys would “leak” into the API and we would need to make sure not to change them in newer versions. A sim-specific query parameter could shield us from this API problem

Chris Malley  7:01 PM
Having to add StringProperties that can only be modified by PhET-iO seems way more expensive, and has a similar API problem.

Sam Reid  7:02 PM
I’m not sure we want this client (or class of clients) to have to use the PhET-iO version.

Chris Malley  7:03 PM
StringProperties are superior if you need to change strings dynamically, while the sim is running.  But most of the requests I've heard are to customize strings, and never change them while the sim is running. Using StringProperties in that case also leads to more complicated code to accommodate dynamic layout. The recent work on keeping screen names centered on icons in the navbar is an example. Why do these names need to be dynamically changeable?  They don't - they should be specified on startup, as overrides of the strings file.

And (as you mentioned above) the StringProperty approach to customizing strings totally excludes most of PhET's clients, because strings can only be changed via PhET-iO. (edited) 

Sam Reid  7:08 PM
>Why do these names need to be dynamically changeable?
The main reason we decided that is so that changing strings has the same API & studio interface as everything else.

Chris Malley  7:08 PM
There is a big difference between initializing strings and changing strings. The latter is more expensive.

Sam Reid  7:09 PM
True

Chris Malley  7:09 PM
So I agree that having the same API for changing strings is desirable.  What we lack is an API for initializing strings.  And because of that deficiency, we are forced to use the more expensive "changing strings" method. And we exclude brand=phet clients. And I would guess that initializing strings is the vast majority of string customization.

Sam Reid  7:10 PM
From rosetta & babel, we are already somewhat discouraged from changing string keys, want to just leverage those?

Chris Malley  7:11 PM
Yes, I think that would be the direction. Use the existing string keys, specify key=customValue. Treat the set of keys as an API.

Sam Reid  7:13 PM
Some possible APIs
?strings=PH_SCALE/drinkMix:My%20Solution,JOIST/help:Help!
?string=PH_SCALE/drinkMix=My%20Solution&string=JOIST/help=Help!

Can we use nested =?

Chris Malley  7:14 PM
QSM doesn't allow duplicate query param keys.
Sam Reid  7:15 PM
> Treat the set of keys as an API.
To accomplish this, I recommend a new build artifact “strings.json” which lists all strings for the simulation (from every namespace), so we can easily do string key API tracking from version to version (edited) 

Chris Malley  7:16 PM
That sounds like a good idea, since strings are coming from dependent repos.

</details>

**Comment by zepumph** [comment]
Related to previous phet-io conversations in phetsims/phet-io#1565 and phetsims/phet-io#1551

**Comment by zepumph** [comment]
Today during phet-io meeting, we decided that we are going to defer this. There is no desire currently for offering this to non-phet-io clients (save i18n). For PhET-iO we know that there is a bigger conversation to be had here. There is no bandwidth for it right now. We want to build out our product base, and then discuss with clients about their needs, and then come back to this in the future.

@kathy-phet also mentioned that although the dynamically changing text is expensive (like in the recent Property work in ph-scale), it is nice to be able to see changes immediately in the studio interface. Any solution we did for initial customization will need to build out a user interface like that.

Deferring.

**Comment by pixelzoom** [comment]
@kathy-phet also said that the API for this is most likely _not_ query parameters, because long query parameters are not a good UI for instructional designers. She envisions something more like Rosetta, that is somehow integrated with Studio.

**Comment by samreid** [comment]
We are now able to change the strings through studio and through the phet-io API, and the layout dynamically adjusts.  Closing.
