### ISSUE TITLE
We can use for...of loops in sim code now?

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#966]
A subset of https://github.com/phetsims/tasks/issues/1037, but it looks like our transpilation and target browsers now supports using for...of loops in sim code. I tested in Wilder over in https://github.com/phetsims/chipper/issues/782 and it worked as expected. If we want to do this and can't think of a reason to not pursue it, here are the steps to make it happen:

1. Add a thorough example of it in WilderModel.
2. Build a dev version of that
3. Have QA test it on our supported browsers.
4. Remove the lint rule and node-specific override of `no-restricted-syntax` in `node_eslintrc`.

Marking for dev meeting to see if people want this ability, and if it is worth the work

**Comment by pixelzoom** [comment]
In the benchmarks that I could find, `for of` was by the far the slowest iterator.  So I have no problem with using this if it's available, but know when to use it.

**Comment by mattpen** [comment]
Dev Meeting 7/30, we discussed that transpilation may still be messy and inefficient for for..of loops.  Let's discuss again at dev meeting when we have more time and more developers are available.

**Comment by samreid** [comment]
> In the benchmarks that I could find, `for of` was by the far the slowest iterator.  So I have no problem with using this if it's available, but know when to use it.

The first result I found when searching for "for of" vs "forEach" performance was https://stackoverflow.com/questions/50844095/should-one-use-for-of-or-foreach-when-iterating-through-an-array which says:

> In performance, for...of is faster than forEach. Results can be found here
> forEach is 24% slower than for...of

But one response said:

> In latest firefox, forEach is faster than for of, but in chrome, for of is faster. 

This issue is pertinent to https://github.com/phetsims/axon/issues/317 which has a `forEach` proposal, but may be less overhead to use `for ... of` (since no need to allocate a function/closure each emit).

**Comment by zepumph** [comment]
Here is a jsperf that could be useful for testing https://jsperf.com/foreach-and-for/9

**Comment by samreid** [comment]
Mac Chrome

![image](https://user-images.githubusercontent.com/679486/89571187-81e4eb00-d7e4-11ea-9177-2a52d4b9b26f.png)

**Comment by zepumph** [comment]
Windows chrome:

![image](https://user-images.githubusercontent.com/6856943/89571262-d92e8f80-d7d3-11ea-89e1-ffdf144573f9.png)

**Comment by brandonLi8** [comment]
Mac firefox:

![image](https://user-images.githubusercontent.com/42391580/89571321-b35db680-d7e4-11ea-8452-bb650ca7fe8e.png)

**Comment by zepumph** [comment]
Windows firefox: 
![image](https://user-images.githubusercontent.com/6856943/89571362-03804d00-d7d4-11ea-909d-40b3c1be0dfc.png)

**Comment by chrisklus** [comment]
From 8/6/20 dev meeting:

@samreid: `for .. of` loops are idiomatic JS and in the case that they aren't already well-performing, they likely will be at some point.
@pixelzoom: we should do our homework and not introduce new iterator until we know when and where to use it.
@jonathanolson: these are are great for async/await
@brandonLi8: it's also nice that you can use break/continue, unlike `forEach`

Anyone feel free to add more tests on your platform!

**Comment by samreid** [comment]
iPad 6

![image](https://user-images.githubusercontent.com/679486/89571419-de480a80-d7e4-11ea-8eee-54d1aa0b9260.png)

**Comment by zepumph** [comment]
Windows edge: 

![image](https://user-images.githubusercontent.com/6856943/89571461-2dd20a80-d7d4-11ea-9a88-12df02b84a5d.png)

**Comment by chrisklus** [comment]
Leaving assigned to @zepumph to remove the lint rule that's currently blocking usage of `for ... of`.

**Comment by Denz1994** [comment]
![image](https://user-images.githubusercontent.com/13894380/89571610-f411fb80-d7f5-11ea-9fac-8b5b289dabea.png)

**Comment by zepumph** [comment]
The lint rule was removed above. 

I tested by adding the following code in a sim main js file and linting it, and then running in built and unbuilt modes. It logged as expected.

```js
for ( const x of [ 1, 2, 3, 4 ] ) {
  console.log( x );
}
```

From the above jsperf tests, it looks like chrome highly optimized `forEach` loops, but other than that, much is in the noise. The use of different loops should be optimized on a case by case basis when performance is very important. 

I think we are ready to close this issue. Please reopen if there is anything else.

**Comment by pixelzoom** [comment]
Reopening.  Do we want to capture the iterator performance information somewhere that it can be generally applied?

**Comment by zepumph** [comment]
I do not know where is best, what do you think?

The information I took from the above info is:
* Performance of loops is very browser dependent
* Optimization based choosing loop algorithms should be done in contextualized cases where you can see if changes actually make a difference. 
* I didn't see an obvious, ordered list from the above data, did you?

**Comment by pixelzoom** [comment]
Point taken that iterator performance varies by browser, so specific performance information isn't valuable. 

How about recommendations on how to choose an appropriate `for` iterator?  How do you decide?  I typically start with the classic `for` loop (with exit condition factored out, if it involves a significant computation ) for anything that is even remotely performance  critical.  But I get the feeling that some developers are more concerned with syntax, and consider performance later if it turns out to be a problem.

**Comment by zepumph** [comment]
It definitely seems like developer discretion to me. I don't feel like there was anything solid enough from the dev meeting to summarize a consensus like what you just mentioned as your pattern. If you feel strongly about coming to a consensus, perhaps we should host this question to devs for a final time. Feel free to do that if you'd like.


Also would you like to see a pattern like this documented?

**Comment by pixelzoom** [comment]
Let's just close this. The next time I encounter some code that is performing poorly because of a bad iterator choice, I'll consider creating a new issue.
