### ISSUE TITLE
Browserslist: caniuse-lite is outdated

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#975]
I'm seeing a new warning when running `grunt build` locally, "caniuse-lite is outdated":

```
% grunt
Running "lint-all" task
Running "report-media" task
Running "clean" task
Running "build" task
Building runnable repository (natural-selection, brands: phet)
Building brand: phet
>> Webpack build complete: 2290ms
Browserslist: caniuse-lite is outdated. Please run the following command: `npm update`
>> Production minification complete: 16124ms (2376189 bytes)
>> Debug minification complete: 0ms (6570547 bytes)
```

There is no change after running `npm update`.

I reported this in Slack, and @zepumph responded:
> This is most likely not from the jsdoc skin because it happens before minification. My first guess is that it has to do with how we are doing babel transpile. @chrisklus did you alter the versions of the babel transpile at all for the IE stuff?

... so assigning to @chrisklus.

**Comment by samreid** [comment]
I no longer see this problem in master:

```
~/apache-document-root/main/natural-selection$ grunt
Running "lint-all" task

Running "report-media" task

Running "clean" task

Running "build" task
Building runnable repository (natural-selection, brands: phet, phet-io)
Building brand: phet
>> Webpack build complete: 2732ms
>> Production minification complete: 15267ms (2348704 bytes)
>> Debug minification complete: 12159ms (4138625 bytes)
```

@pixelzoom does this still occur on your development environment?

**Comment by pixelzoom** [comment]
Seems to have self-healed. Closing.
