### ISSUE TITLE
confirm "IO Type" via lint

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#977]
Awhile back, we standardized on "IO Type".  Not "IO type" or some other variations.  In https://github.com/phetsims/tandem/commit/527655c166b03727bab904e7d83bf88a23ccfdf2 I fixed several regressions, including a public-facing one that was introduced by `createIOType`.  

@zepumph suggested that we add a check for this to the bad-text.js lint rule.

Assigning to @ariel-phet to prioritize and assign.

**Comment by zepumph** [comment]
commit coming in hot.

**Comment by zepumph** [comment]
I found 126 lint errors. Fixing them now.

**Comment by zepumph** [comment]
126 is likely made up, but lint is clear after the above commits. @pixelzoom anything else here?

**Comment by zepumph** [comment]
There was one more because I was on a branch in phet-io-test-sim.

**Comment by pixelzoom** [comment]
👍🏻 Closing.
