### ISSUE TITLE
treatment of Node fs (File System) module

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#98]
Node `fs` (File System) module is sometimes defined, sometimes not. Sometimes referred to as `fs`, sometimes referred to as `global.fs`.  Recommended to handle this consistently, in a manner that passes jshint.

Specifically...

In chipper/grunt/Gruntfile:

```js
15 var fs = require( 'fs' );
27 global.fs = fs;
```

In chipper/grunt/pullAll, it's defined again:

```js
4 var fs = require( 'fs' );
```

In chipper/grunt/createSim, it's not defined and causes a lint error (fs undefined):

```js
108 if ( !fs.existsSync( destPath ) || overwrite ) {
```

In chipper/requirejs-plugins/loadFileAsDataURI, it's not defined and causes a lint error:

```js
27 var base64 = 'data:' + mimeType + ';base64,' + Buffer( fs.readFileSync( filename ) ).toString( 'base64' );
```

In chipper/requirejs-plugins/loadFileAsDataURI, it's not defined, causes a lint error, and is referred to as global.fs:

```js
182 else if ( !global.fs.existsSync( path ) ) {
```

**Comment by pixelzoom** [comment]
Any reason we can't define `fs` in all files that use it, like this:

```js
var fs = fs || require( 'fs' );
```

and refer to it everywhere as `fs` ?

**Comment by pixelzoom** [comment]
Proposal:

(1) Remove this from Gruntfile.js:

```js
27 global.fs = fs;
```

(2) Define `fs` in all files that use it, like this:

```js
var fs = fs || require( 'fs' );
```

(3) Refer to it everywhere as `fs`.

**Comment by jonathanolson** [comment]
It's only used for the Node.js (grunt compile) usage for string plugins, so a top-level ```require( 'fs' )``` is likely to cause failures when executed in the browser (especially since 'fs' won't already be defined and would trigger a compilation error before executing the require).

**Comment by pixelzoom** [comment]
New proposal:

(1) Define `fs` in non-plugin code:
```js
var fs = require( 'fs' );
```

(2) Refer to it as `global.fs` in all plugin code.

**Comment by jonathanolson** [comment]
Sounds acceptable to me.

**Comment by pixelzoom** [comment]
Handled in #97. Closing.
