### ISSUE TITLE
Do we want supportsZoom query parameter to be public?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/chipper#980]
As we publish sims with zoom, do we want to give users the ability to turn this off with a query parameter? May determine how we implement enabling of the feature in https://github.com/phetsims/joist/issues/657#issuecomment-686757928. @ariel-phet what do you think about this?

**Comment by ariel-phet** [comment]
@jessegreenberg - yes, we definitely want to maintain the ability to turn this feature off with a query parameter (some clients may need this ability for certain sims in their platform).

**Comment by jessegreenberg** [comment]
OK sounds good - are you OK with `?supportsZoom` as the public name?

**Comment by ariel-phet** [comment]
Hmm, that might be a good question to bring to up at status or such next week. Designers might have some thoughts on what clients might appreciate as a clear name (I just worry that "Zoom" is now used so much to refer to video sharing software we might need something with some disambiguation)

**Comment by jessegreenberg** [comment]
Discussed 9/10/20 during status meeting:

Team thought it was good to include "pan" in the name. "magnification" was discussed but "panAndZoom" was determined to be a bit more user friendly. And all agreed "zoom" alone was a bit loaded now with widely used video sharing software.

The decided name was ?supportsPanAndZoom.

**Comment by jessegreenberg** [comment]
Change was made to the query parameter, it is now a boolean `?supportsPanAndZoom`.
