### ISSUE TITLE
Mipmaps are not outputted in a format compatible with our style formatter

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#982]
From https://github.com/phetsims/natural-selection/issues/228

Our code style formatter adds a new line after the import.  We should auto-generate this new line so that reformat doesn't do anything.

**Comment by samreid** [comment]
Fixed and ready for review.  The commit messages should say `grunt modulify` instead of `grunt update`

**Comment by pixelzoom** [comment]
I spot-checked a few .js files for mipmaps, ran `grunt modulify` etc. and everything looks as expected.

But this change seems to be be only for mipmaps, and phetsims/natural-selection#228 was related to images.  Should the same change (blank line after imports) be made for images?

**Comment by pixelzoom** [comment]
It looks like sounds already have a blank line after imports, so no problem there.

**Comment by samreid** [comment]
Yes, I'll add it for images.

**Comment by samreid** [comment]
OK I added the newline for images as well, ready for review.

**Comment by pixelzoom** [comment]
Tested with NS, looks good, closing.
