### ISSUE TITLE
Automatic identification of dependencies

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/chipper#983]
Recently had some subtle "dependent repo wasn't in package.json phetLibs" cases (https://github.com/phetsims/sun/issues/626), and realized that the potential impact of this if it happens again is "translation update could cause the sim to build with master or old SHAs of an unlisted repo, and break PRODUCTION sims".

Due to this, I believe it would be good to investigate using webpack's list of used modules, and identifying dependencies from there (at least potentially as a side check). This would be a bottleneck if we needed to do it every time we need dependencies (would slow down maintenance releases and many other procedures), so I'd like to propose that this be done on release-branch creation as a sanity check (it will error out if there is an unlisted dependency).

Does that sound like a good approach, or are there alternative suggestions?

**Comment by samreid** [comment]
Our current way of specifying dependencies is to add entries to package.json like so:

```json
        "phetLibs": [
          "vegas",
          "twixt"
        ],
```

This must be a full list of all dependencies (transitive dependencies are not automatically picked up).

It would be nice to move away from this pattern and leverage webpack for this step fully.  However, if we need to cache results or equivalent to make maintenance releases and other procedures faster, then it is unclear when to invalidate the cache.  Perhaps generating dependencies.json on builds is sufficient?

> This would be a bottleneck if we needed to do it every time we need dependencies (would slow down maintenance releases and many other procedures)

Is there a way to run webpack in "trace dependencies" mode which is faster than a full compile?  Or can we at least double check that the webpack build step is too slow?  Also, last time I built Natural Selection, it reported the webpack build time was 2692ms, which is a fraction of the entire build time (but I'm not sure if it's fast enough to be acceptable).

**Comment by zepumph** [comment]
During the dev meeting it wasn't totally clear what more would be need beyond something like this untested patch. It was clear though that @jonathanolson wanted to take time to think through how this may effect our tooling, especially as it pertains to perennial and the batch MR process.

```diff
Index: js/grunt/buildRunnable.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/grunt/buildRunnable.js	(revision 327752cd463dac4d30bf2f1cb46a709f277c089b)
+++ js/grunt/buildRunnable.js	(date 1601580633908)
@@ -117,7 +117,7 @@
   const phetLibs = getPhetLibs( repo, brand );
   const allLocales = [ ChipperConstants.FALLBACK_LOCALE, ...getLocalesFromRepository( repo ) ];
   const locales = localesOption === '*' ? allLocales : localesOption.split( ',' );
-  const dependencies = await getDependencies( repo );
+  const dependencies = await getDependencies( repo, webpackResult.usedModules );
   const version = packageObject.version; // Include the one-off name in the version
   const thirdPartyEntries = getAllThirdPartyEntries( repo, brand, licenseEntries );
   const simTitleStringKey = getTitleStringKey( repo );
Index: js/grunt/getDependencies.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/grunt/getDependencies.js	(revision 327752cd463dac4d30bf2f1cb46a709f277c089b)
+++ js/grunt/getDependencies.js	(date 1601580633911)
@@ -22,7 +22,7 @@
  * @param {string} repo
  * @returns {Promise.<Object>} - In the dependencies.json format. JSON.stringify if you want to output to a file
  */
-module.exports = async function( repo ) {
+module.exports = async function( repo, usedModules ) {
 
   const packageObject = grunt.file.readJSON( `../${repo}/package.json` );
   const version = packageObject.version;
@@ -31,7 +31,7 @@
   const dependencies = getPhetLibs( repo ).filter( dependency => dependency !== 'babel' ); // Remove babel since it should be kept at master
 
   // We need to check dependencies for the main brand, so we can know what is guaranteed to be public
-  const mainDependencies = getPhetLibs( repo, 'phet' ).filter( dependency => dependency !== 'babel' );
+  const mainDependencies = usedModules.filter( dependency => dependency !== 'babel' );
 
   grunt.log.debug( 'Scanning dependencies from:\n' + dependencies.toString() );

**Comment by samreid** [comment]
I think this could have averted a problem in the waves-intro build, discovered in https://github.com/phetsims/QA/issues/580.  Relabeling for dev meeting to see if we need to change priority, assignee or timeline.

**Comment by pixelzoom** [comment]
This bit me in fourier-making-waves.  I started using bamboo instead of griddle, but neglected to change package.json. The build process produced an incomplete dependencies.json for 2 dev versions, and would have happily continued doing so if @samreid hadn't pointed out the problem.

**Comment by zepumph** [comment]
This patch is a half solution in which we just make sure that all used dependencies are in the hard coded lists in package.json, with a loud assertion. Feel free to commit if you are worried of getting bit again The part of ratio and proportion triggers the assertion.

Likely the ideal is the auto detect, this could be improved upon perhaps by passing in the used list of dependencies to getDependencies.

```diff
Index: chipper/js/grunt/buildRunnable.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/chipper/js/grunt/buildRunnable.js b/chipper/js/grunt/buildRunnable.js
--- a/chipper/js/grunt/buildRunnable.js	(revision 64e2c318d57cda799e4eea29027257e00a4f03d0)
+++ b/chipper/js/grunt/buildRunnable.js	(date 1607473531821)
@@ -96,6 +96,8 @@
   const usedModules = webpackResult.usedModules;
   reportUnusedMedia( repo, usedModules );
 
+  const repoDependenciesUsed = _.uniq( usedModules.filter( x => x.match( /^(\w+)[\\/]/ ) ).map( x => x.match( /^(\w+)[\\/]/ )[ 1 ] ) );
+
   const licenseEntries = {};
   ChipperConstants.MEDIA_TYPES.forEach( mediaType => {
     licenseEntries[ mediaType ] = {};
@@ -117,13 +119,18 @@
   const phetLibs = getPhetLibs( repo, brand );
   const allLocales = [ ChipperConstants.FALLBACK_LOCALE, ...getLocalesFromRepository( repo ) ];
   const locales = localesOption === '*' ? allLocales : localesOption.split( ',' );
-  const dependencies = await getDependencies( repo );
+  const hardCodedDependencies = await getDependencies( repo );
+  const dependencies = hardCodedDependencies;
   const version = packageObject.version; // Include the one-off name in the version
   const thirdPartyEntries = getAllThirdPartyEntries( repo, brand, licenseEntries );
   const simTitleStringKey = getTitleStringKey( repo );
 
   const stringMap = getStringMap( allLocales, phetLibs, webpackResult.usedModules );
 
+  repoDependenciesUsed.forEach( repoUsed => {
+    assert( dependencies.hasOwnProperty( repoUsed ), `repo: ${repoUsed} should be in dependencies` );
+  } );
+
   // After our string map is consturcted, report which of the translatable strings are unused.
   reportUnusedStrings( repo, packageObject.phet.requirejsNamespace, stringMap[ ChipperConstants.FALLBACK_LOCALE ] );
 
Index: ratio-and-proportion/js/ratio-and-proportion-main.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/ratio-and-proportion/js/ratio-and-proportion-main.js b/ratio-and-proportion/js/ratio-and-proportion-main.js
--- a/ratio-and-proportion/js/ratio-and-proportion-main.js	(revision 9892edd10b5e19764c755d6953055ac74b326695)
+++ b/ratio-and-proportion/js/ratio-and-proportion-main.js	(date 1607473602633)
@@ -6,6 +6,7 @@
  * @author Michael Kauzmann (PhET Interactive Simulations)
  */
 
+import AxisNode from '../../bamboo/js/AxisNode.js';
 import Sim from '../../joist/js/Sim.js';
 import simLauncher from '../../joist/js/simLauncher.js';
 import Tandem from '../../tandem/js/Tandem.js';
@@ -14,7 +15,7 @@
 import ratioAndProportionStrings from './ratioAndProportionStrings.js';
 
 const ratioAndProportionTitleString = ratioAndProportionStrings[ 'ratio-and-proportion' ].title;
-
+AxisNode;
 const simOptions = {
   credits: {
     leadDesign: '',
```

**Comment by pixelzoom** [comment]
12/20/2020 dev meeting:

@zepumph suggested a patch in https://github.com/phetsims/chipper/issues/983#issuecomment-702351660. 
@jonathanolson wanted to "take time to think through how this may effect our tooling".  
This is still where we're at.

@jonathanolson suggested 3 options:
(1) Specify "phetLibs" in package.json and sanity check it.
(2) Delete "phetLibs" in package.json and automatically generate what is actually used.
(3) Generate a new file that includes all of the dependencies, to be used where phetLibs is currently used. Requires a 'grunt update' to generate the file.

@samreid pointed out that there are 12 usages of phetLibs in chipper code.

@jonathanolson pointed out that phetLibs changes depending on brand.

@samreid suggested that (1) should be if-and-only-if. That is, no missing dependencies, no unused dependencies.  @zepumph and @jonathanolson thought that "no unused dependencies" might be problematic (e.g. assert is not a module).

@samreid likes (3), which involves converting assert to a module.  @zepumph pointed out that every module that uses assert (like initialize-globals) also needs to become a module, a non-trivial amount of work. 

Consensus is that (3) is the best longterm, but we don't have time for it, and it involves a lot of build-tools changes (which @ariel-phet would prefer not to touch right now.)

For now, let's do (1), because it's the least amount of work and addressed the problem immediately.  If we can easily identified unused dependencies in package.json "phetLibs" then we will. Otherwise we'll just identify missing dependencies.  @jonathanon will make it so.

**Comment by jonathanolson** [comment]
Added (1) above, does it look good @zepumph? Presumably we'll keep open to handle (3) eventually, and can re-prioritize if it looks good. I tested all runnables.

**Comment by zepumph** [comment]
Looks really nice, thanks for the assertion. unassigning until we get to automatically calculating dependencies.

**Comment by zepumph** [comment]
Hmm. This is failing an assertion for me in RaP right now when I try to build locally:

```
 Michael ~/PhET/git/ratio-and-proportion (master)
 $ grunt
Running "lint-all" task

Running "report-media" task

Running "clean" task

Running "build" task
Building runnable repository (ratio-and-proportion, brands: phet)
Building brand: phet
>> Webpack build complete: 2574ms
Fatal error: Perennial task failed:
AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: repo axon\js\Action.j missing from package.json's phetLibs for axon\js\Action.js
  at C:\Users\Michael\PhET\git\chipper\js\grunt\buildRunnable.js:124:5
  at Array.forEach (<anonymous>:null:null)
  at module.exports (C:\Users\Michael\PhET\git\chipper\js\grunt\buildRunnable.js:122:29)
  at processTicksAndRejections (internal/process/task_queues.js:93:5)
  at C:\Users\Michael\PhET\git\chipper\js\grunt\Gruntfile.js:253:11
  at wrap (C:\Users\Michael\PhET\git\chipper\js\grunt\Gruntfile.js:72:7)

Full Error details:
{
  "generatedMessage": false,
  "code": "ERR_ASSERTION",
  "actual": false,
  "expected": true,
  "operator": "=="
}

```

I'll take a look

**Comment by zepumph** [comment]
We need a cross-platform way to split the path up. This got things working for me.

**Comment by jonathanolson** [comment]
Sorry about that! Thanks.

**Comment by zepumph** [comment]
Instead of auto, maybe just testing this somehow.

**Comment by zepumph** [comment]
I hit this yesterday with Maintenance tooling that copies only dependencies for a release branch into a dedicated directory (`Maintenance.updateCheckouts()`). This caused a lint error because I accidentally added a type checking dependency on shred in phetcommon. This was incorrect, but it wasn't caught for 6 months until working in a place where we didn't have shred checked out and were linting phetcommon. I believe the best path forward would be CT testing that tells you about import dependencies that aren't in `phetLibs`.

**Comment by zepumph** [comment]
I believe we have good coverage for asserting if phetLibs doesn't include something that is imported. The issue is when we use `import type` instead of an actual code import. I found that webpack doesn't report "usedModules" in these cases.


```js
// Doesn't report Bunny as a used module:
import type Bunny from '../../natural-selection/js/common/model/Bunny.js';
const x = ( x?: Bunny ) => {
  console.log( 'hi', x );
};
x();

// Doesn't report Bunny as a used module:
import Bunny from '../../natural-selection/js/common/model/Bunny.js';
const x = ( x?: Bunny ) => {
  console.log( 'hi', x );
};
x();

// Does report Bunny as a used module:
import Bunny from '../../natural-selection/js/common/model/Bunny.js';
const x = ( x?: Bunny ) => {
  console.log( 'hi', x, Bunny );
};
x();
```

So perhaps we need a custom system for testing `import type` or I need to do more research.

**Comment by zepumph** [comment]
I believe this issue is ready to close. We have automatic identification of dependencies through webpack in chipper. And over in https://github.com/phetsims/aqua/issues/203 we are going to work to get lint/tsc testing on release branches automatically. Thanks all for your hard work.
