### ISSUE TITLE
issues with buildRunnable.js

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#984]
In buildRunnable.js:

```js
module.exports = async function( repo, minifyOptions, instrument, allHTML, brand, localesOption, buildLocal ) {
```

`instrument` is unused.  
`buildLocal` has no `@param` annotation, and is flagged by WebStorm.

**Comment by samreid** [comment]
I removed `--instrument` in https://github.com/phetsims/chipper/issues/985 and `buildLocal` now has an `@param` annotation, added in https://github.com/phetsims/chipper/commit/1967bf38daa15723fb61ad65ebdc2184945f7ce7.  Closing.
