### ISSUE TITLE
--instrument is no longer supported

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#985]
"Instrumentation" of sims for code coverage was apparently stripped out when PhET switched to ES6 modules. And code-coverage.md (the documentation) no longer exists.

grunt help should be removed from chipper/js/grunt/Gruntfile.js:

```js
160  --instrument - Builds a runnable with code coverage tooling inside. See phet-info/doc/code-coverage.md for more information
```

buildRunnable.js does nothing with its `instrument` parameter (see https://github.com/phetsims/chipper/issues/984).  So find and delete all occurrences of `instrument`, like these in Gruntfile.js:

```js
      // grunt options that apply to multiple build tasks
      const instrument = !!grunt.option( 'instrument' );

      // Do not uglify or transpile if it is being instrumented, so it will match development code as closely as possible
      if ( instrument ) {
        minifyOptions.babelTranspile = false;
        minifyOptions.uglify = false;
      }
...
          await buildRunnable( repo, minifyOptions, instrument, allHTML, brand, localesOption, buildLocal );
```

**Comment by samreid** [comment]
I confirmed that code-coverage.md is gone, and agree with @pixelzoom we should remove this option.

**Comment by samreid** [comment]
I removed it, tested a build, tested the documentation. It seemed straightforward, closing.
