### ISSUE TITLE
revise 'grunt production' prompt

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#986]
I ran:

```
% grunt production --branch=1.2 --brands=phet-io
```

One of the prompts is:

```
Does this sim run in PhET-iO brand (requirejs with assertions enabled)? 
This ensures up-to-date api files before continuing. [y/N]?
```

This probably needs to be updated, since requirejs is no longer used.  I'm not sure what the new language should be, and did not investigate where this needs to be changed.

Assigning to @ariel-phet to prioritize and assign.

**Comment by ariel-phet** [comment]
@samreid I imagine this is a fairly quick change, putting at medium priority since it seems good to update and easy

**Comment by samreid** [comment]
This was added by @zepumph as part of https://github.com/phetsims/phet-io/issues/1524.  I think it is safe to remove entirely, since it looks like a failure or timeout during generatePhetioAPI fails the build.  Tagging @zepumph in case I'm wrong, but I'm confident enough to commit.

**Comment by samreid** [comment]
OK I removed the prompt.  @pixelzoom do you have enough context to review?  If not, please assign to @zepumph.
