### ISSUE TITLE
Can we commit debuggers under a query parameter?

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#989]
From slack discussion with @samreid, it would be nice to have a `?debugger` QP that you can use to get at debuggers throughout the code. Mainly in assert.js, and in qunitStart.

**Comment by zepumph** [comment]
I added `?debugger`. When provided, it will debug on thrown assertion errors and qunit failed tests. @samreid please review.

It looks like `debugger` is stripped out even for the debug build, so this would only be useful during development. 

Here is what assert looked like in the debug version of phet brand friction:

![image](https://user-images.githubusercontent.com/6856943/99728447-ebbc9400-2a65-11eb-900c-5533c6fe4bee.png)

**Comment by samreid** [comment]
This looks great to me, I tested throwing an assertion in Gravity and Orbits and it worked as expected.  The code changes look good.  I would recommend as a final step, adding `&debugger` to be on by default for phetmarks.
