### ISSUE TITLE
issues to address when Node 14 is in LTS

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/chipper#990]
When Node 14 is in LTS (scheduled for 10/27/2020), prioritize and assign these issues:

https://github.com/phetsims/chipper/issues/861
https://github.com/phetsims/chipper/issues/949
https://github.com/phetsims/chipper/issues/862
https://github.com/phetsims/chipper/issues/947
https://github.com/phetsims/perennial/issues/179

Added to "Future Reminders" in the PhET Developer Meeting doc, to be revisited on 10/22/2020.

**Comment by pixelzoom** [comment]
Tomorrow is 10/22/2020, labeling for developer meeting to revisit this issue.

**Comment by mattpen** [comment]
Let's defer discussion until next week after it is in Active LTS status.

**Comment by jbphet** [comment]
The release is now in Active LTS.  We decided that the next step is to have all the developers update to Node 14 this week and run like that for a week and make sure that no major issues are encountered, and if all is good we will proceed to the next step, which is to upgrade it on the servers.

**Comment by samreid** [comment]
I updated from v12.16.3 to v14.15.0

**Comment by pixelzoom** [comment]
Yes, I have updated to Node 14:

- [ ] @chrisklus 
- [ ] @Denz1994 
- [ ] @jbphet 
- [ ] @jessegreenberg 
- [ ] @jonathanolson 
- [ ] @mattpen 
- [ ] @pixelzoom 
- [ ] @samreid 
- [ ] @SaurabhTotey

**Comment by mattpen** [comment]
All production servers are now running node 14.15.0, so work on this issue should be able to proceed.

**Comment by chrisklus** [comment]
From 11/12/20 dev meeting:

We are going to close this issues and reprioritize and assign out the issues from https://github.com/phetsims/chipper/issues/990#issue-726907542. Closing.
