### ISSUE TITLE
A11y view: assertive alerts should get a different style from polite

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#991]
From https://github.com/phetsims/ratio-and-proportion/issues/214#issuecomment-713214134, where we added assertive alerting as an option for Utterances and AriaHerald. If we made the assertive paragraphs specially highlighted, that would help communicate that the screen reader will handle them differently. Tagging @jessegreenberg.

**Comment by zepumph** [comment]
Furthermore, as discovered in https://github.com/phetsims/ratio-and-proportion/issues/214#issuecomment-716823546, the mutation observer added for aria live elements could be greatly improved.

**Comment by zepumph** [comment]
I went with a randomish pink background for assertive alerts. @jessegreenberg can you please review the code?

@Matthew-Moore240 and @terracoda please note this change, pink background means the aria-live alert was `assertive`.

![image](https://user-images.githubusercontent.com/6856943/106650113-fbb12380-653e-11eb-9ab1-afb0f067e4fc.png)

**Comment by jessegreenberg** [comment]
Change looks good to me! The change assumes `assertive` is in the id of the AriaHerald elements, and I think that is fine. Tested in ratio-and-proportion myself and it is working well.
