### ISSUE TITLE
npm update on bayes is taking 5+ minutes

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#997]
On slack, @jonathanolson pointed out that bayes npm update is taking 5+ minutes.  It is running node 14.15.0.

reproducible by going to `/data/web/htdocs/dev/phettest/perennial` with our admin account, and running `npm update`.

Assigning to @jonathanolson to ask which processes this will impact, and assigning to @ariel-phet to gather further information, and prioritize.

One solution to this problem may be to investigate yarn 2 as an alternative to npm--yarn 2 can work completely offline and supports a global cache, which may also solve https://github.com/phetsims/chipper/issues/383.  It apparently also has a more deterministic way to pin dependencies, which we discussed in https://github.com/phetsims/chipper/issues/114

**Comment by ariel-phet** [comment]
@jonathanolson said over slack this issue would be good to solve. Assigning to him to hopefully look into this week.

**Comment by jonathanolson** [comment]
This is now resolved, the thing that did the trick was `npm cache clean --force`.
